[로키] 체스 미션 1~3단계 제출합니다.
woowacourse/java-chess pull request #161
Opened 2021-03-18 17:58 UTC by Rok93

휴 안녕하세요 이번 체스미션 리뷰를 받게된 로키입니다. 🙇‍♂️🙇‍♂️🙇‍♂️ 

레벨 1 막바지에 다다를 수록 점점 미션이 어려워지는 것 같습니다. 
이번에 저는 3인 페어로 진행을 하게 되었는데, 미션이 어려웠던만큼 더 다양한 의견들을 들을 수 있고 머리가 하나 늘어서인지 더 빠르게 기능들을 구현할 수 있었던 것 같습니다. 제가 부족했던 부분들은 페어들이 많이 메꿔줬던 것 같습니다 😅. 

이번 미션에서 어려웠던 부분들을 뽑아보라면, 각 말의 움직임을 어떻게 구현할 것인가 였는데, 저희는 ``움직임``(MoveCondition)을 객체로 만들고 Piece들이 폰, 퀸, 킹, 나이트 등등... 자신의 움직임 구현들을 가지고 있게 함으로써, 해결했었습니다. 이 구조는 어떻게 생각하시는지도 궁금합니다. 다른 좋은 방법이 있다면 알고싶습니다. 

페어의 제안으로 사용자로부터 입력받는 command를 객체화 시켰는데, Command를 각 명령어에 맞는 객체들을 구현하여(  ``MoveCommand``, ``StartCommand``, ``EndCommand``, ``StatusCommand``) handler의 개념을 착안하여, handle 하는 방식으로 처리하였습니다. 저희가 짠 구조가 괜찮은지 혹은 개선점이 있다면 어떻게 하면 좋을지 등도 여쭙고싶습니다. (개인적인 생각이지만 한번도 사용해본적 없는 방식이라 괜찮았다.... 라고 생각하고 있습니다만 개선사항이 있을지 )

리뷰 잘 부탁드립니다 🙇‍♂️🙇‍♂️🙇‍♂️🙇‍♂️
감사합니다!

2021-03-21 17:46 UTC, Hue9010 requested changes
로키! 리뷰가 늦었습니다. 죄송합니다. 😭 🙏
요구사항에 맞춰 기능 구현을 굉장히 잘해주셨네요!
기능 상으로 봤을 때는 머지해도 충분하지만 개선했으면 싶은 부분이 있어 피드백 남겼는데 확인해주세요! 😉
궁금한건 언제들 문의주세요!!

2021-03-21 17:46 UTC, Hue9010 commented on src/main/java/chess/domain/command/Command.java
> +public interface Command {
> 페어의 제안으로 사용자로부터 입력받는 command를 객체화 시켰는데, Command를 각 명령어에 맞는 객체들을 구현하여( MoveCommand, StartCommand, EndCommand, StatusCommand) handler의 개념을 착안하여, handle 하는 방식으로 처리하였습니다. 저희가 짠 구조가 괜찮은지 혹은 개선점이 있다면 어떻게 하면 좋을지 등도 여쭙고싶습니다. (개인적인 생각이지만 한번도 사용해본적 없는 방식이라 괜찮았다.... 라고 생각하고 있습니다만 개선사항이 있을지 )

👍
게임쪽에서는 다양한 입력이 존재하여 Command 패턴을 자주 활용한다고 본 것 같아요.(상태, 전략 패턴도 마찬가지이고요)
그런점에서 활용하신 형태를 보니까 잘 사용해주셨네요. 💯

2021-03-21 17:46 UTC, Hue9010 commented on src/main/java/chess/view/dto/BoardDto.java
> +    List<PieceDto> pieceDtos;
👍 
DTO에 익숙치 않으면 놓치기 쉬운 사항인데 Piece도 DTO로 만들어 주셨군요. 💯

2021-03-21 17:46 UTC, Hue9010 commented on src/main/java/chess/view/OutputView.java
> +    private static final String SCORE_FORMAT = "백: %.1f 흑: %.1f %n";
EMPTY_BOARD_UNIT과 달리 특정한 의미를 가지고 있지도 않고, 중복되어 사용되지도 않는데 별도의 상수로 뺄 필요가 있을지 생각해볼 여지가 있을 것 같아요.
약간은 취향의 영역으로 볼 수도 있기때문에 `꼭 고쳐야 한다!` 는건 아닌점 참고바래요. 😉

2021-03-21 17:46 UTC, Hue9010 commented on src/main/java/chess/domain/piece/condition/NormalWhitePawnMoveCondition.java
> +    }
이동에 해당하는 Condition도 세부적으로 보려다가 위 피드백에(+ 조건문에 대한 피드백) 맞춰 수정하면 꽤나 바뀔 수 있는 부분이 있을걸로 보여서 상세한 피드백은 다음번에 하도록 할게요. 이점 참고부탁해요! 😋

2021-03-21 17:46 UTC, Hue9010 commented on README.md
> +****
> 이번 미션은 특히나 객체지향적인 설계를 하기위해서 많은 노력을 했었는데, 설계에 대한 고민을 많이 해본적이 없어서 의견을 많이 못 보탰던 것 같습니다. 객체지향적으로 설계를 잘 짜기위한 서적, 참고자료, 영상 같은 것이 있다면 추천해주실 수 있을까요? 

이미 보셨을 것 같긴하지만 조영호님 자료들이 좋답니다.
[객체지향의 사실과 오해](https://www.aladin.co.kr/shop/wproduct.aspx?ItemId=60550259)
[[우아한테크세미나] 190620 우아한객체지향 by 우아한형제들 개발실장 조영호님
](https://www.youtube.com/watch?v=dJ5C4qRqAgA)
[조영호님 블로그](http://aeternum.egloos.com/) 예전 글들이지만 충분히 좋은 자료들이 많답니다.(객체지향보다는 DDD 등의 내용이 있어 지금 필요한 내용은 적을 수도 있겠네요. 😢 )

이와 같은 자료를 보는 것도 좋지만 어느정도 학습을 학습을 진행했다면 지식을 내것으로 하기 위한 과정으로 이게 맞을까? 혹은 맞다고 생각한대로 구현한다음 어땠는지 다시 생각해보는 과정자체가 더 중요하다고 봐요. 경험의 영역이죠. 고민을 많이 해본적이 없었다면 이김에 고민을 많이해보는 것도 방법이고, 그게 쉽지 않다면 같이 진행을 했던 페어가 어떤 식으로 고민하는지 보는 것도 좋은 방법이에요. 😉

여담이지만 이전 블랙잭을 진행할 때 상태 패턴을 적용하시려는 크루한테 드렸던 조언인데 상태 패턴을 적용하기 전 코드에 맞춰 인터페이스를 만들지 말고 어떤 형태의 인터페이스를 추가해야할지 먼저 고민해서 인터페이스를 추상화한 다음 적용해보라고 피드백을 드렸었네요. 먼저 인터페이스를 고민해도 코드에 맞춰 변경이 이뤄지겠지만 이 차이가 생각보다 크답니다. 설계를 어렵게 생각하실 필요 없이 이러한 과정이 모두 설계의 영역에 들어가고요.

마찬가지로 설계를 너무 어렵게 생각치 말고 먼저 생각하고 구현하는 모든 걸 설계라고 생각하시면 됩니다. 😉

2021-03-22 05:21 UTC, Rok93 commented on src/main/java/chess/domain/game/BlackTurn.java
> +    private static final Color COLOR = Color.BLACK;
이 부분은 [YAGNI](https://ko.wikipedia.org/wiki/YAGNI)를 생각했어야했는데 코드를 짤 때, 당장 필요한 것 이상으로 많이 생각했던 것 같아요 : ) 상수로 추출했던 COLOR들 지역변수로 변경하였습니다.

2021-03-23 12:13 UTC, Rok93 commented on src/main/java/chess/domain/piece/condition/MoveCondition.java
> +public abstract class MoveCondition {
이 부분은 크게 고려했던 부분이 아니였는데, 휴 얘기를 듣고보니 Piece가 condition을 상속할 수도 있겠구나 라는 생각도 들지만, ``폰``의 경우 크게 세가지의 움직임(1. 첫 턴에는 앞으로 1칸 or 2칸 이동, 2. 평소에는 앞으로 1칸, 3. 대각선에 적이 있는 경우 대각선 이동)으로 분류할 수 있었는데, 자바의 특성상 하나의 클래스(추상클래스도 포함해서...)만 상속받을 수 있어 상속보다는 has-a 관계로 조합을 사용하는 것이 낫다고 판단하였습니다. 

다시 생각해봐도 상속의 관점으로는 어떻게 풀어나갈지 감이 안온데, 조금 더 힌트를 주실 수 있을까요?

2021-03-23 12:14 UTC, Rok93 commented on src/main/java/chess/exception/ChessPieceCollisionException.java
> +public class ChessPieceCollisionException extends RuntimeException {
이 부분은 해당 예외 클래스를 삭제하고 커밋 & 푸쉬를 했는데, 반영이 안됐네요 😳

2021-03-23 12:16 UTC, Rok93 commented on src/main/java/chess/view/OutputView.java
> +    private static final String SCORE_FORMAT = "백: %.1f 흑: %.1f %n";
기존 코딩스타일은 모든 하드코딩을 다 상수로 빼는 것이없는데, 뷰나 예외처리 문자열 등 의미가 없는 혹은 자주 쓰이지 않는 값들은 따로 상수로 처리하려고 스타일을 바꾸고있습니다. : )  이부분은 습관적으로 한 것도 있지만, 8의 의미가 코드를 이해하기가 너무 어렵다고 느껴져서 상수처리를 했었습니다. 

포맷은 지금보니 굳이 상수로 추출하지는 않았어도 될 것 같다는 생각이 드네요!

2021-03-23 12:22 UTC, Rok93 commented on src/main/java/chess/domain/piece/condition/NormalWhitePawnMoveCondition.java
> +    }
이 부분은 추상화가 쉽지않아서, 피드백 주신 로직들이 대부분 아래의 두 가지 패턴을 만족한다는 것을 알게되었습니다. 
```java
xxx.stream()
      .filter(*****)
      .noneMatch(******);
```
또는
```java
xxx.stream()
      .anyMatch(******);
```

위의 코드들을 ``Pieces`` 클래스의 ``isNoneMatchByFilteredPieces``와 ``isEnemyExist`` 메서드로 추상화(?) 해봤는데, 음... 추상화가 아직 어렵게 느껴지네요 😅 

혹시 더 좋은 방향이 있다면 힌트를 얻고싶습니다!

2021-03-23 12:39 UTC, Rok93 commented on src/main/java/chess/controller/ChessController.java
> +        }
early return이 필요한 구문이라... 로직을 분리하는 것은 쉽지않다고 느껴집니다. 로직의 변경없이 메서드명을 적절하게(?) 변경해보려고 하는데, 한참을 고민하다가 ``executeByCommand`` 으로 변경했으나 사실 거기서 거기인거 같습니다. 

휴의 의도는 '더 적절한 네이밍을 고려해보라는 것'인지 아니면 '메서드를 비슷한 기능 단위로 분리'(?)하라는 의도인지 알고싶습니다. 또한 혹시나 좋은 방향이 있다면 이 부분도 조언을 얻고싶습니다. 😅

2021-03-24 16:06 UTC, Hue9010 approved these changes
처음부터 잘 구현해주셔서 큰 변경없이 피드백 반영을 잘 해주셨네요. 👍 
이번 단계는 여기서 머지할게요. 간단한 내용 몇개 남겼는데 다음 단계 진행 때 반영해주셔도 충분할 것 같아요.
질문에 대한 답변도 남겼는데 궁금한건 언제든 질문 주세요!(혹시 놓친 질문이 있다면 말씀주세요!)

2021-03-24 16:09 UTC, Hue9010 commented on src/main/java/chess/domain/piece/condition/NormalWhitePawnMoveCondition.java
> +    }
의도한대로 잘 해주셨어요! 😸
피드백 드릴때 고민되는 부분인데 상세히 알려주면 생각할 틈을 주지 않고 방법을 강요하는 느낌이고, 추상적(?)으로 안내를 하면 지금처럼 의미전달이 모호하게 돼서 혼란을 드릴 때가 있네요. 😭

2021-03-24 16:10 UTC, Hue9010 commented on src/main/java/chess/controller/ChessController.java
> +        }
전자입니다. 😉
저도 좋은 네이밍이 떠오르지 않네요. 😭 

![시간](https://media.vlpt.us/images/ggob_2/post/d08477db-9827-4e13-8a9b-a2b5a7d07954/%EA%B0%9C%EB%B0%9C%EC%9E%90%EC%9D%98%20%EA%B3%A0%EC%B6%A9.jpg)

2021-03-24 16:10 UTC, merged

2021-03-25 01:57 UTC, Rok93 commented on src/main/java/chess/domain/piece/condition/MoveCondition.java
> +public abstract class MoveCondition {
물론 상황마다 조금씩 다를 수는 있겠지만 제 개인적인 의견으로는 PR 이전의 코드로 답변을 주시는게 좋다고 생각해요 😁 
혹시나 코드 변경이 있다면 리뷰어도 번거롭고, 리뷰이에게도 혼란이 생길 수 있다고 생각해요.

2021-03-25 16:50 UTC, Hue9010 commented on src/main/java/chess/domain/piece/condition/MoveCondition.java
> +public abstract class MoveCondition {
고민되는 부분이였는데 의견 갑사해요! 😺

2021-04-25 14:33 UTC, Rok93 commented
# 학습로그 - 체스 

## [디자인패턴] 상태패턴 - 3
### 내용
- 체스게임의 현재 상태를 상태패턴으로 구현하여  
### 참고 내용 
- 개발자가 반드시 정복해야 할 객체 지향과 디자인 패턴 (상태 패턴 부분) 

##  [디자인패턴] 커맨드패턴 - 2
### 내용 
- 체스게임을 조작하기 위한 커맨드를 커맨드 패턴으로 변경하여 조작 

### 참고 링크 
* [커맨드 패턴 (Command Pattern) - 기계인간(Jonn Grip)](https://johngrib.github.io/wiki/command-pattern/) 

## [객체지향] DTO - 2 
- Controller와 View의 정보 전달시 model을 직접 전달하거나 받는 형태가 아닌, DTO 객체로 전달