[1,2,3단계 - 체스] 제이온(박진영) 미션 제출합니다.
woowacourse/java-chess pull request #162
Opened 2021-03-20 06:37 UTC by pjy1368

안녕하세요 김고래! 제이온입니다. 😊

이번 미션은 최대한 다형성을 이용하려고 노력하였습니다. 그래서 보드판에 체스말을 초기화하는 과정이나 체스말 자체를 상속을 이용하였습니다. 그 과정에서 '폰' 체스말이 다른 말과 달리 이동 전략이 달라서 다형성을 깨뜨리는 코드가 중간 중간 생겼습니다. 대표적인 코드로 'instanceof' 키워드를 사용하여 특정 객체의 타입을 확인해 주었습니다.

SOLID 원칙을 공부하면서 'instanceof'를 통한 다운 캐스팅이 발생하는 경우 OCP를 위반한다고 배웠습니다. 하지만, 도저히 미션을 진행하면서 '폰', '킹', '빈 공간' 객체에 타입을 확인을 하지 않고, 기능을 구현하기 막막한 메소드가 몇 개 있었습니다. 그리고 한 편으로는 하나의 메소드 내에서 한 개의 타입만 'instanceof' 키워드로 비교하는데, 'instanceof' 키워드가 반드시 나쁜 것인지 의문을 갖게 되었습니다.

그래서 'instanceof' 키워드가 무조건적으로 나쁜 것인지 궁금하고, 만약 그렇다면 해당 코드에서 어떻게 수정하는 것이 좋을지 조언해주시면 감사하겠습니다.

그 외에도 문제가 생기는 코드는 마구마구 피드백해 주시면 좋겠습니다. 리뷰를 위해 귀한 시간 내 주셔서 감사합니다 🙇

2021-03-20 06:57 UTC, pjy1368 commented
# 제이온의 학습 로그
## [설계] 다형성 - 9
### 내용
- 인터페이스를 사용하여 보드에 체스말을 초기화하였다.
- 추상 클래스를 사용하여 각 체스말들의 상위 클래스인 Piece를 정의하였다.
- 폰과 빈 공간 객체 외에는 체스말의 성질이 같으므로 GeneralPiece로 한 단계 더 추상화하였다.

### 링크
- https://github.com/woowacourse/java-chess/pull/162/commits/b440d234a07fe31dbebb271549f330afcdd484ef
- https://github.com/woowacourse/java-chess/pull/162/commits/4f40d2d8521e1bbbf6d10c684765765428d503f8
- https://github.com/woowacourse/java-chess/pull/162/commits/fb60713dc81947c94646b3dd16f0a6a8355d7950

## [로직] 체스말 이동 전략 - 8
### 내용
- 폰, 비숍, 룩, 퀸 외에는 Direction 열거형 클래스를 정의하여 이동이 가능한지 여부를 쉽게 확인할 수 있었다.
- 하지만, 위 4가지 체스 말은 상황에 따라 여러 칸 이동할 수 있으므로 중간에 체스 말이 있는지 확인해야 한다.
- 따라서, 보드에서 시작점과 끝점의 중간 경로에 체스 말이 있는지 체크하는 로직을 추가하였다.
- 그리고 중간 경로에 말이 없다면 끝점 바로 전 위치로 체스 말을 이동하였다고 가정하고, 끝점으로 이동가능한지는 체스 말이 확인하도록 설게하였다.
- 다만, 여기서 폰은 중간에 체스말이 없더라도 곧바로 끝점 바로 전 위치로 체스 말로 이동하면 안 된다. 해당 말이 처음 이동하는지 여부도 판단해야하기 때문이다.

### 링크
- https://github.com/woowacourse/java-chess/pull/162/commits/18642b1606a3c134ed45e554fcde54545b095302
- https://github.com/woowacourse/java-chess/pull/162/commits/a47532c72be00bf76f8fd18e2da6dd2b4e6f9e26

## [설계] TDD - 3
### 내용
- 기존에도 TDD를 하였으나, 커밋 단위를 '기능+테스트'로 한꺼번에 하는 편이었다.
- 이번에는 아론의 의견에 따라, 컴파일은 되지만 실패하는 테스트 한 번, 기능 구현하여 성공하는 테스트 한 번으로 총 2번 커밋을 보내도록 하였다.
- 처음에는 비효율적이라고 생각하였으나, 나중에 테스트 커버리지를 돌려보니 96%라는 성과가 나왔다. 아무래도 좀 더 꼼꼼하게 테스트를 할 수 있어서 그런 듯하다.

### 링크
- https://github.com/woowacourse/java-chess/pull/162/commits/a72588c0952e1654abe467026c5fea74d19114be
- https://github.com/woowacourse/java-chess/pull/162/commits/5ddfc1d29b21b945ab960e31467456232854e998

2021-03-21 07:13 UTC, ep1stas1s requested changes
미션 진행하시느라 고생하셨습니다 👍
코멘트 남겼으니 확인해보시고 궁금한 점 있으면 DM주세요~

2021-03-23 15:36 UTC, ep1stas1s approved these changes
어려운 미션인데도 깔끔하게 잘 하셨네요 💯 
다음 단계도 잘 부탁드립니다~!

2021-03-23 15:36 UTC, ep1stas1s commented on src/main/java/chess/domain/piece/Bishop.java
> +public final class Bishop extends GeneralPiece {
final 👍

2021-03-23 15:36 UTC, ep1stas1s commented on src/main/java/chess/domain/piece/GeneralPiece.java
> +        return isPossibleDirection(source, target) && (isOpponent(piece) || piece instanceof Blank);
```suggestion
        return isPossibleDirection(source, target) && (isOpponent(piece) || piece.isBlank());
```
요기는 누락된거같네요 ^_^

2021-03-23 15:36 UTC, merged