[1,2,3단계 - 체스] 파피(김태완) 미션 제출합니다.
woowacourse/java-chess pull request #173
Opened 2021-03-21 12:26 UTC by TaewanKimmmm

안녕하세요, 김고래!!

이번 미션 정말 어려웠던 것 같아요.

최대한 객체끼리 메시지를 보내려고 노력했는데, 많은 피드백 부탁드립니다🙏🙏

---

# 궁금한 점

1. 모든 기물들이 Piece라는 추상 클래스를 상속받고 있고, Piece의 타입을 확인하기 위해 instanceof 를 쓰는 대신 모든 기물들에 isKing(), isPawn(), isEmptyPiece()을 구현했습니다. 이렇게 하는 게 맞나 의문이 들었는데.. 괜찮을까요?

2. 또, Piece의 추상 메서드 validateMovable은 인자로 direction, targetPiece를 인자로 받도록 되어 있는데
Queen 기물에서 구현한 validateMovable 메서드에서는 모든 방향이 있기 때문에 방향은 확인할 필요가 없어 direction을 인자로 받고도  사용하지 않았던 것도 찝찝하더라고요..이 정도는 눈감고 넘어가도 되는 걸까요? 아니면 설계를 잘못한 걸까요?

3. if 문 안에 들어가는 조건문 맨 앞에 부정 연산자 '''!'''가 있는 경우, isNot을 붙인 또 다른 메서드를 구현하여 쓰는 걸 김고래는 어떻게 생각하시나요? 저는 불필요하다고 생각하면서도 에러가 떴을 때 한참 찾다가  ```!```를 붙이지 않았기 때문이었던 적이 꽤 많아서 확신이 들지 않아서 여쭤봅니다..! 
ex) ```isEmpty()```메서드가 구현되어 있을 때, 비어있지 않은 경우를 조건으로 사용하게 되었다면 ```!isEmpty()``` vs ```isNotEmpty()```를 구현

소중한 시간 내어주셔서 감사합니다!!!!!많은 피드백 부탁드립니다!!!!😀😀😀😀😀

2021-03-22 17:12 UTC, ep1stas1s requested changes
미션 진행하시느라 고생하셨습니다 👍 
답변과 몇 가지 피드백 남겼으니 궁금한 점 있으면 DM주세요~

2021-03-22 17:12 UTC, ep1stas1s commented on src/main/java/chess/domain/Board.java
> +    private void moveStepByStep(Point source, Point target, Piece sourcePiece, Piece targetPiece) {
Point만 받아도 되지 않을까요?

2021-03-22 23:35 UTC, ep1stas1s commented on src/main/java/chess/domain/piece/kind/Piece.java
> +    public abstract boolean isEmptyPiece();
기본값으로 false를 반환해도 좋을 것 같습니다

2021-03-22 23:35 UTC, ep1stas1s commented on src/main/java/chess/domain/piece/kind/Rook.java
> +    public void validateMovable(Direction direction, Piece targetPiece) {
말씀하신대로 한 곳에서만 사용하는 매개변수면... 다른 방법을 고민해봐도 좋을 것 같아요
아니면 pawn과 knight에서 사실상 piece의 위치만 사용하고 있으니, 매개변수로 시작, 도착지점에 해당하는 point를 넘겨주는건 어떨까요?

2021-03-25 15:29 UTC, TaewanKimmmm commented
안녕하세요, 김고래!
모든 피드백 반영하였습니다.
소중한 시간 내어주셔서 감사합니다🙏

2021-03-27 16:14 UTC, ep1stas1s approved these changes
깔끔하게 잘 반영해주셨네요 👍 
간단한 코멘트 남겼으니 다음 미션 진행하면서 참고해주세요 ^_^

2021-03-27 16:15 UTC, merged

2021-03-28 03:46 UTC, TaewanKimmmm commented on src/main/java/chess/domain/piece/Color.java
> +    }
null일 때 더 안전해서 ==를 쓰는 게 나을 수 있겠네요!

2021-03-28 03:52 UTC, TaewanKimmmm commented on src/main/java/chess/domain/Score.java
> +public class Score {
네이밍 Result로 수정했습니다!

2021-03-28 03:52 UTC, TaewanKimmmm commented on src/main/java/chess/domain/Score.java
> +    public String getWinner() {
반영했습니다!

2021-03-28 04:27 UTC, TaewanKimmmm commented on src/main/java/chess/domain/Board.java
> +    public Board() {
반영했습니다!