[1,2,3단계 - 체스] 케빈(박진홍) 미션 제출합니다.
woowacourse/java-chess pull request #174
Opened 2021-03-21 14:28 UTC by xlffm3

2021-03-23 16:58 UTC, dave915 requested changes
케빈 안녕하세요! 리뷰가 늦어서 죄송합니다 🙇‍♂️
요구사항에 맞춰 구현 잘 해주셨네요 👍 
몇가지 피드백 남겼습니다! 확인 부탁드려요! 
혹시 궁금한점이 있다면 언제든 DM주세요!

2021-03-23 16:58 UTC, dave915 commented on src/main/java/chess/domain/command/CommandTokens.java
> +    private final List<String> commandTokens;
```
private String command;
private List<String> options;
```

이런식으로 나누어도 좋을 것 같아요 :)

2021-03-23 16:58 UTC, dave915 commented on src/main/java/chess/controller/ChessController.java
> +    private void executeMoveCommand(CommandTokens commandTokens) {
`Command` 에서 각 명령어별로 CommandTokens 와 ChessBoard를 전달받아 수행하는 BIFunction을 만들고 이 메소드를 Command내부로 이동시키면 어떨까요? 
`이 명렁어는 이 동작을 수행해` 라는 부분이 명시적으로 보이게 할 수 있을 것 같아요 :)

2021-03-23 16:58 UTC, dave915 commented on src/main/java/chess/domain/board/Cell.java
> +    private final List<Piece> pieceOnCell = new ArrayList<>();
ArrayList를 사용한 이유가 있을까요?

2021-03-23 16:58 UTC, dave915 commented on src/main/java/chess/domain/board/ChessBoard.java
> +    public Result calculateScores() {
현재 cells를 받아, 현재 상태를 나타내는 객체를 만들고 점수 계산로직을 해당 객체로 이동시키면 말씀해주신 ChessBoard가 가벼워 질 것 같아요 🤔

2021-03-23 16:58 UTC, dave915 commented on src/main/java/chess/domain/piece/Piece.java
> +    public boolean isKing() {
isKing, isPawn 보단 메세지(classType 또는 Pice의 이름) 등을 전달해 확인해 주는 메소드를 만들어주면 어떨까요?

2021-03-24 00:40 UTC, xlffm3 commented on src/main/java/chess/domain/board/Cell.java
> +    private final List<Piece> pieceOnCell = new ArrayList<>();
Cell은 Piece가 있거나 혹은 없거나의 상태를 가지는데요.
``private Piece piece;`` 처럼 가변을 통해 상태를 보여줄 수도 있는데, 코드 곳곳에 ``piece == null`` 등을 체크하는 것을
``isEmpty()`` 등으로 표현하려고 사용했어요!

다만 list 자체가 여러 원소가 존재할 수 있는 컬렉션이기 때문에 혼란의 여지가 있겠네요..!

2021-03-24 00:41 UTC, xlffm3 commented on src/main/java/chess/domain/piece/Piece.java
> +    public boolean isKing() {
그런 방법은 생각못했네요!! :)

2021-03-24 02:12 UTC, xlffm3 commented on src/main/java/chess/controller/ChessController.java
> +    private void executeMoveCommand(CommandTokens commandTokens) {
Bifunction 필드를 추가하고, move와 status 모두 Command 내부에서 자체적으로 수행하도록 변경했습니다!

2021-03-24 06:01 UTC, xlffm3 commented
안녕하세요 데이브!

* ``isKing``, ``isPawn`` 관련 메서드들을 삭제하고 ``isPieceOf(type)``으로 변경했어요.
* ChessBoard에서 점수를 계산하던 로직을 Score 객체에게 위임했어요.
  * ChessBoard는 현재 보드에서 팀 타입 / 좌표에 따라 기물들을 필터링해서 Score에게 전달하니 말씀하신대로 클래스가 가벼워졌어요.
* 체스보드의 한 칸을 의미하는 Cell의 내부 구조를  ``private final List<Piece> pieceOnCell = new ArrayList<>();``에서 ``private Piece piece;``로 변경했어요.
* Command 명령어에게 CommandRequest(내부적으로 TeamType과 CommandTokens를 가짐) 및 체스 보드를 전달하여 각 명령어에 맞게 로직을 처리하도록 BiFunction을 추가했어요.
  * 별도의 로직이 없는 start나 end는 unspportedOperationException을 발생시키도록 했고, move는 점수를 계산하지 않지만 return type이 존재하여 ``Result.empty()``를 반환하도록 했습니다.
 
* 그 외 ChessBoard에서의 중복되는 부분들을 별도의 메서드, 혹은 다른 클래스의 메서드로 분리 리팩토링했습니다.

2021-03-24 06:45 UTC, xlffm3 commented
# 학습 로그

---

# [OOP] SOLID 원칙 - 4

## 내용

* 단일책임원칙
* 개방폐쇄원칙
* 리스코프치환원칙
* 인터페이스
* 의존성역전원칙
* 예제를 통해 볼 때 위 SOLID 원칙 내용들이 당연하다고 느껴지지만, 막상 개발을 하다보면 이를 위반하는 경우가 상당히 많은 것 같다.
* 객체들의 책임, 역할, 그리고 객체들의 추상화 등을 다각도로 고려하면서 개발해야 겠다고 느꼈다.

2021-03-27 06:07 UTC, dave915 requested changes
케빈 안녕하세요! 
피드백 반영하신 부분 잘 봤습니다 👍 
간단한 피드백 몇개 남겼어요. 확인 부탁드릴게요! 
궁금한점 있다면 언제든 DM주세요!

2021-03-27 06:07 UTC, dave915 commented on src/main/java/chess/domain/piece/Piece.java
> +    }
이 메소드들은 이제 필요 없을 것 같아요 :)

2021-03-27 06:07 UTC, dave915 commented on src/main/java/chess/domain/piece/King.java
> +    public boolean isMovable(ChessBoard chessBoard, Coordinate current, Coordinate destination) {
King하고 Knight 의 isMovable 메소드가 로직이 같은데, 개선 할 수 없을까요?

2021-03-27 06:15 UTC, xlffm3 commented on src/main/java/chess/domain/piece/Piece.java
> +    }
앗 제거를 안했네요,,!!;;;

2021-03-27 06:51 UTC, xlffm3 commented
안녕하세요 데이브.
말씀해주신 불필요한 isKing, isPawn은 삭제 완료했습니다.

또한 isMovable 메서드는
(King, Kinght), (Rook, Bishop, Queen), (Pawn)
총 세 가지 그룹에 해당하는 패턴이 존재하는데요.

Piece 추상클래스 하위에 ConsecutiveMovablePiece(장애물이 없다면 보드의 끝까지 연속된 좌표 이동이 가능한 기물, Rook,Bishop,Queen)와
LimitedMovablePiece(기물 주변의 제한된 몇 칸만 이동할 수 있는 기물, Kinght, King, Pawn)을 두고

각각의 기물들이 해당 클래스들을 상속받도록 변경했습니다!

2021-03-28 05:27 UTC, dave915 approved these changes
케빈 안녕하세요! 
피드백 빠르게 반영해주셨네요! 
다음단계 진행해주세요 :)

2021-03-28 05:27 UTC, dave915 commented on src/main/java/chess/domain/piece/King.java
> +    public boolean isMovable(ChessBoard chessBoard, Coordinate current, Coordinate destination) {
인터페이스 분리 되어서 King의 isMovable 메소드는 삭제해도 될 것 같아요 :)

2021-03-28 05:27 UTC, merged