[1,2,3단계 - 체스] 라이언(권영훈) 미션 제출합니다.
woowacourse/java-chess pull request #175
Opened 2021-03-22 02:52 UTC by YounghoonKwon

안녕하세요 게이츠!

이번 체스 미션은 이전과 다르게 계획했던 설계대로 가지를 못했어요 ㅠ
그래서 reset을 무한반복 했던 기억이 나네요..
특히 Pawn에 대한 움직임을 구현하는 부분이 엄청 힘들었던거 같아요.

전체적으로 코드를 살펴보면,
Piece라는 클래스를 상속받아서 다른 체스 말들을 만들어줬구요.
Grid가 하는 역할을 Line, Lines, Score이 분리해서 하게끔 했어요.
그리고 테스트를 하기 위해서, grid를 초기화 해줄때 전략패턴을 사용했어요.

그리고 이번에 상태패턴을 처음 적용해봤어요.
컨트롤러부분에 상태패턴을 적용해서 Ready, WhiteTurn, BlackTurn, End, Status 의 상태를 가지도록 하였어요.
어떻게 보면 컨트롤러의 역할을 5개의 상태들이 나눠 가지는 형태가 되었네요.
이번에 상태패턴을 처음 짜다보니 되게 어색했는데, 게이츠가 어색하거나 이상한게 있으면 날카로운 지적 해주면 좋겠어요.

이번 미션 잘 부탁드릴께요!!

2021-03-24 22:37 UTC, serverwizard requested changes
안녕하세요. 피카. 체스 미션을 함께할 (빌) 게이츠입니다.

체스 미션 난이도가 꽤 있는데 깔끔하게 구현해 주셨네요 👍 

몇 가지 코멘트 남겼는데 확인 부탁드립니다 🙏
궁금한점이 있다면 언제든지 DM주세요! 

ps. 어제(24일) 새벽에 프로젝트 오픈이 있어서, 리뷰가 많이 늦어진 점 죄송합니다. 😭 🙏

2021-03-24 22:37 UTC, serverwizard commented on src/main/java/chess/controller/ChessController.java
> +            this.gameState = gameState.run(grid);
체스 게임을 관리하는 ChessGame 도메인 객체를 만들어 체스 게임을 관리해보는 건 어떨까요?

2021-03-24 22:37 UTC, serverwizard commented on src/test/java/chess/domain/grid/GridTest.java
> +        assertThat(grid.piece(position)).isEqualTo(piece);
given, when, then을 기준으로 줄바꿈을 넣어준다면 좀 더 가독성이 증가할 것 같아요!

2021-03-24 22:37 UTC, serverwizard commented on src/main/java/chess/controller/state/Playing.java
> +public abstract class Playing implements GameState {
현재 체스 게임과 관련된 GameState가 컨트롤러 패키지에 위치해 있는데요.
MVC 패턴에서 컨트롤러 역할은 어떻게 될까요?

2021-03-24 22:37 UTC, serverwizard commented on src/main/java/chess/domain/grid/Grid.java
> +public final class Grid {
Grid라는 객체를 만들어 처리 하셨네요. 👍

2021-03-24 22:37 UTC, serverwizard commented on src/main/java/chess/domain/grid/Line.java
> +    private static final char EIGHT_COLUMN = 'h';
이를 Enum으로 관리해 볼 수도 있겠네요.

2021-03-24 22:37 UTC, serverwizard commented on src/main/java/chess/controller/state/GameState.java
> +public interface GameState {
상태패턴 👍

2021-03-24 22:37 UTC, serverwizard commented on src/main/java/chess/controller/state/BlackTurn.java
> +            OutputView.printWinner(Color.BLACK);
현재 체스 게임과 관련된 상태들이 Controller 패키지에 있다보니 자연스럽게 View와 의존을 하고 있는데요.
비즈니스 로직을 관리한다는 관점에서 도메인 객체라고 볼 수는 없을까요?

2021-03-25 01:42 UTC, YounghoonKwon commented
> 안녕하세요. 피카. 체스 미션을 함께할 (빌) 게이츠입니다.
> 
> 체스 미션 난이도가 꽤 있는데 깔끔하게 구현해 주셨네요 👍
> 
> 몇 가지 코멘트 남겼는데 확인 부탁드립니다 🙏
> 궁금한점이 있다면 언제든지 DM주세요!
> 
> ps. 어제(24일) 새벽에 프로젝트 오픈이 있어서, 리뷰가 많이 늦어진 점 죄송합니다. 😭 🙏

저 라이언 이에요...

2021-03-25 06:47 UTC, YounghoonKwon commented on src/main/java/chess/controller/state/Playing.java
> +public abstract class Playing implements GameState {
모델이랑 컨트롤러 사이에서 소통하는 역할인것 같아요.
지금 제 코드 구조상 상태가 컨트롤러 역할을 하는 느낌이 나서 컨트롤러 패키지에 넣어놨어요.

상태랑 컨트롤러 역할을 한번 분리 해볼께요!!

2021-03-25 12:16 UTC, YounghoonKwon commented on src/main/java/chess/controller/state/BlackTurn.java
> +            OutputView.printWinner(Color.BLACK);
상태를 view랑 분리 시키고, 컨트롤러에서 view와 소통하게끔 리팩터링 했습니다!
도메인객체라고 볼 수 있을것 같아요!

2021-03-25 12:17 UTC, YounghoonKwon commented on src/main/java/chess/controller/ChessController.java
> +            this.gameState = gameState.run(grid);
ChessGame이라는 도메인 객체를 만들 필요는 궂이 없다고 느껴졌어요..
일단 controller에서 뷰와 관련된 것을 처리하게끔 하였고,
상태를 도메인으로 이동함으로서 비지니스 로직을 관리하게 하였어요.

혹시 chessGame이 필요한 이유가 있을까요?

2021-03-25 14:22 UTC, YounghoonKwon commented
## 학습로그
---
### 가변인수 vs 오버로딩
- 가능하다면 가변인자를 사용한 메서드는 오버로딩을 하지 않는 것이 바람직

### 모던 자바 인 액션 8장, 컬렉션 API 개선
[https://younghoonkwon.github.io/java/%EB%AA%A8%EB%8D%98%20%EC%9E%90%EB%B0%94%20%EC%9D%B8%20%EC%95%A1%EC%85%98/2021/03/24/%EB%AA%A8%EB%8D%98-%EC%9E%90%EB%B0%94-%EC%9D%B8-%EC%95%A1%EC%85%98-8%EC%9E%A5,-%EC%BB%AC%EB%A0%89%EC%85%98-API-%EA%B0%9C%EC%84%A0/#more](url)

### 병행 처리(코딩을 지탱하는 기술)
[https://younghoonkwon.github.io/%EC%BD%94%EB%94%A9%EC%9D%84%20%EC%A7%80%ED%83%B1%ED%95%98%EB%8A%94%20%EA%B8%B0%EC%88%A0/2021/03/22/%EC%BD%94%EB%94%A9%EC%9D%84-%EC%A7%80%ED%83%B1%ED%95%98%EB%8A%94-%EA%B8%B0%EC%88%A0-%EC%99%84%EB%8F%85/#more](url)

### 상태 패턴
[https://younghoonkwon.github.io/java/2021/03/19/%EC%B2%B4%EC%8A%A4-%EB%AF%B8%EC%85%98-%EC%83%81%ED%83%9C%ED%8C%A8%ED%84%B4-%EA%B5%AC%ED%98%84/](url)

2021-03-28 03:07 UTC, serverwizard commented on src/main/java/chess/controller/ChessController.java
> +            this.gameState = gameState.run(grid);
체스게임을 개발/유지보수하는 입장에서 체스게임을 ChessGame도메인 객체를 통해 진행할 수 있다면, 가독성 측면이나 유지보수하는 측면에서 좀 더 좋지 않을까 생각했어요.
즉, 체스게임과 관련된 건 ChessGame을 통해 진행하게 하는거죠.
그러면 API를 사용하는 입장에서도 여러 객체를 알 필요가 없을 것 같구요.

2021-03-28 03:15 UTC, serverwizard approved these changes
라이언 안녕하세요! 
리뷰가 늦었어요😭 죄송합니다 🙇‍♂️

한 가지 코멘트 남겼어요. step2 진행하시면서 참고 부탁드릴게요! 
궁금한점 있으면 언제든지 DM주세요!

2021-03-28 03:15 UTC, serverwizard commented on src/main/java/chess/controller/ChessController.java
> +            return;
가능하다면, 반복되는 조건문을 제거하는 방법 중의 하나로 객체 지향의 다형성을 활용해 해결할 수 없는지 검토해보면 좋을 것 같아요.

2021-03-28 03:15 UTC, merged