[1,2,3단계 - 체스] 크로플(이동환) 미션 제출합니다.
woowacourse/java-chess pull request #178
Opened 2021-03-22 06:00 UTC by perenok

안녕하세요 지노!
체스 첫번째 풀리퀘입니다!! 정말이지 힘든 한 주였어요ㅠㅠ
난이도가 지난번에 비해 많이 올랐다고 느껴지는 미션이었어요ㅋㅋㅋ
이번 미션은 페어 프로그래밍이 저에게 큰 장점으로 다가왔어요! 페어 덕분에 기간 내에 잘 마무리 할 수 있었다고 생각합니다ㅋㅋㅋ
가장 오래 고민했던 것은 Piece가 자신의 현재 좌표를 가지고 있느냐 아니면 Board에서 좌표별로 해당 Piece를 가지고 있냐에 대한 것이었어요. 두번의 reset 끝에 결론은 Piece에게 현재 좌표를 주고 이를 통해 이동 가능한 위치들을 각 Piece 별로 체크하게 만들었어요.
이걸 이용해서 체크메이트까지 구현을 할 수 있을 줄 알았는데... 체크는 충분히 가능한데 체크메이트는 생각보다 더 많은 경우의 수가 필요하더라고요ㅋㅋㅋ 최대한 구현해 보려 하다 실패하고 일단 Todo로 유배 보내놨습니다ㅋㅋㅋ 처음에 생각했던 체크메이트는 king이 움직일 수 있는 위치들이 모두 적들의 공격범위 안에 들면 체크메이트!라고 구현을 했는데 실제로 돌려보니 왕이 움직이지 못하더라도 다른 기물이 경로에 들어오거나, 아니면 체크중인 상대방 기물을 잡을 수 있을 때도 체크메이트로 선언해버리고 게임을 끝내더라고요ㅋㅋㅋ 그래서 좀 더 고민해보고 설계를 손본 뒤에 기능을 추가하겠습니다ㅠㅠ
페어 덕분에 BiFunction을 처음 써봤어요! 입력에 따라 행동을 해줄 ChessAction과 입력인 String값을 받아 GameStatus를 반환하도록 구현해 보았습니다! 또한 포비의 엘레강트 수업에서 controller도 잘못된 네이밍이라는 의견이 있다고 해서 이름을 ChessAction으로 변경했습니다ㅋㅋㅋ
많은 피드백 부탁드려요~~

#### 궁금한 점

Piece에서 instanceof 대신 isKing과 isPawn 메소드를 통해 King과 Pawn인지 구분하고 있습니다. 나머지 Piece에선 false를 반환하는 식으로 이렇게 메소드를 통해 구분하는게 instanceof를 사용하는 것보다 괜찮은 걸까요? instanceof가 안티패턴이라고 지난 블랙잭 미션에서 피드백을 받아서 바꿔 구현했는데 King이나 Pawn이 아닌 클래스까지 코드들이 추가되니 현재 코드가 더 나은지 확신이 안 서네요ㅠㅠ

2021-03-23 09:39 UTC, hyunssooo requested changes
안녕하세요, 크로플! 지노입니다.🙇‍♂️
정말 어려운 체스 미션 진행하신다고 수고 많으셨습니다.👏👏👏
몇 가지 코멘트 남겼어요! 확인 부탁 드립니다!

2021-03-23 09:39 UTC, hyunssooo commented on src/main/java/chess/domain/piece/Pieces.java
> +    }
piece가 움직일 때 마다 전체 piece를 움직임 가능한 경로를 계산해서 가지고 있는데 그러면 연산이 너무 많지 않을까요?
piece가 움직이려고 시도할 때 해당 piece에서만 가능한지 여부를 판단하는 방법은 어떨까요??

2021-03-23 09:39 UTC, hyunssooo commented on src/main/java/chess/domain/piece/Piece.java
> +
상속 받는 클래스에서 재정의 못하게 하려면 final 키워드를 붙여주면 됩니다 :)

2021-03-23 09:39 UTC, hyunssooo commented on src/main/java/chess/domain/piece/Piece.java
> +    public abstract boolean isKing();
```suggestion
    public boolean isPawn() {
        return false;
    }

    public abstract boolean isKing();
```
부모 클래스에서 정의하고 필요한 클래스에서만 재정의 하는 방법도 있습니다 :) 

```java
public class Pawn extends Piece {
  ..
  
  @Override
    public boolean isPawn() {
        return true;
    }
}
```

2021-03-23 09:39 UTC, hyunssooo commented on src/main/java/chess/domain/piece/Piece.java
> +    public abstract boolean isKing();
질문의 메서드가 여기네요. 비즈니스에 필요하니 필요한 메서드라고 생각이 들어요. 또한 각 객체에게 묻는 편이 `instanceof` 보다는 훨씬 나은것 같습니다 👍

2021-03-24 13:56 UTC, perenok commented on src/main/java/chess/domain/Score.java
> +    }
수정했습니다!

2021-03-24 13:57 UTC, perenok commented on src/main/java/chess/domain/piece/Pieces.java
> +    }
optional을 반환하는 메소드를 일반 객체를 반환하도록 변경했습니다ㅎㅎ

2021-03-24 13:57 UTC, perenok commented on src/main/java/chess/domain/piece/moving/BishopMoving.java
> +}
수정했습니다!

2021-03-24 13:58 UTC, perenok commented on src/main/java/chess/util/MessagePositionConverter.java
> +}
정적 클래스로 변경해 매번 객체 생성을 하지 않아도 되게 수정했습니다!

2021-03-24 13:58 UTC, perenok commented on src/main/java/chess/domain/ChessResult.java
> +    }
view에서 해당 if문을 통해 winner를 출력하도록 수정했습니다ㅎㅎ

2021-03-24 13:59 UTC, perenok commented on src/main/java/chess/domain/Position.java
> +    }
String으로 Key를 만드는 것보다 integer로 받는게 더 자연스러울 거 같아 변경해봤어요!

2021-03-24 14:06 UTC, perenok commented on src/main/java/chess/domain/ChessGame.java
> +    }
Pieces에 메세지를 던져 move 로직을 수행하는 방식으로 변경했습니다!
Position이 Piece에 있어야 하나로 페어와 많은 고민을 했습니다. 처음에는 Map<Position, Piece> board를 ChessGame에서 가지는 식으로 만들었어요. 페어와 토론 중에 체크메이트를 계산하기 위해 각 Piece별로 움직일 수 있는 Position들을 알 수 있어야 하지 않겠나라는 얘기가 나와서 최종 결론을 Piece에 Position을 주는 것으로 정했거든요. 기존 방식대로 Map을 이용하면 각 Piece들이 움직일 수 있는 위치들을 저장하는 게 애매하다고 생각했어요. 다른 방법으로는 movablePositions만 Piece가 필드로 가지고 chessGame에서 계산한 뒤 Piece에게 값을 전해주면 되지 않을까 생각이 드네요ㅎㅎ

2021-03-24 14:12 UTC, perenok commented on src/main/java/chess/domain/piece/Pieces.java
> +    }
이 메소드는 왕이 체크가 됐을 때 이동가능한 경로들이 상대방이 공격할 수 있는 범위에 드는지 확인하고 맞다면 움직이지 못하도록 하기 위해 만들었던 메소드에요. 매 턴마다 상대방이 공격 가능한 위치를 검사해야 왕이 못 가게 만들 수 있다고 생각해서 매 턴마다 update를 진행했습니다. 만약 움직이는 말 하나만 update를 하게 되면 그 말로 인해 갈 수 있던 곳이 변경된 다른 말들의 이전 movablePositions를 그대로 사용하여 체크를 계산하게 되니 잘못된 정보가 나오지 않을까 생각했습니다. 다만 현재는 체크메이트도 미구현이고 과도하게 여러곳에서 update를 진행하는 것 같아 check 검사할 때만 하고 piece 하나가 움직였을 때는 그 piece의 movablePostions만 update하도록 변경했습니다!

2021-03-24 14:13 UTC, perenok commented on src/main/java/chess/domain/piece/Piece.java
> +    public abstract boolean isKing();
오 이 방법이 훨씬 좋아보이네요 부모 클래스에서 정의하고 필요한 클래스인 King과 Pawn에서만 override하도록 변경했습니다!

2021-03-25 17:52 UTC, hyunssooo approved these changes
안녕하세요 크로플
step1 진행하신다고 수고 많으셨습니다.
몇 가지 코멘트 남겼어요. step2 진행하시면서 참고 부탁드릴게요! 
step2 진행해주세요!

2021-03-25 17:52 UTC, hyunssooo commented on src/main/java/chess/controller/ChessAction.java
> +
ChessAction이 컨트롤러로 보이네요. 보통 컨트롤러는 인스턴스를 하나만 생성합니다. 
현재 구조는 게임당 컨트롤러를 생성해야될 거 같은 구조네요

2021-03-25 17:52 UTC, hyunssooo commented on src/main/java/chess/domain/Position.java
> +
List를 사용해도 괜찮을 것 같아요 :) index를 사용하면 됩니다!

2021-03-25 17:52 UTC, hyunssooo commented on src/main/java/chess/domain/piece/direction/Direction.java
> +}
```suggestion
}

```
마지막 줄은 개행으로 끝납니다 :)

2021-03-25 17:52 UTC, hyunssooo commented on src/main/java/chess/exception/ImpossibleMoveException.java
> +
custom exception 패키지 위치도 고민해보면 좋을 것 같아요
보통 해당 레이어의 exception은 해당 레이어에 패키지를 별도로 분리합니다.
domain 객체에 대한 exception은 domain 패키지 아래에 생성하면 좋을 것 같아요 :) 
또한, `이펙티브 자바 아이템 72. 표준 예외를 사용하라.` 를 읽어보시고 정말 필요할때만 custom exception을 만들면 좋을 것 같아요 :)

2021-03-25 17:52 UTC, hyunssooo commented on src/main/java/chess/util/MessagePositionConverter.java
> +
불필요한 객체 생성 방지 👍

2021-03-25 17:52 UTC, merged

2021-04-19 15:11 UTC, perenok commented
# 학습 로그
## Optional
- 메서드가 반환할 결과값이 ‘없음’을 명백하게 표현할 필요가 있고, null을 반환하면 에러를 유발할 가능성이 높은 상황의 반환 타입
- orElse, orElseGet을 통해 해당 메소드가 null을 반환할 때 행동을 정해서 null이 반환되는 것을 방지할 수 있다.
- 비싼 연산이므로 단순 값을 얻을 때는 null 비교, 컬렉션을 반환 할 때는 빈 컬렉션을 반환하는 것이 좋다.

## 태그
- OOP, JAVA