[1,2,3단계 - 체스] 완태(김태완) 미션 제출합니다.
woowacourse/java-chess pull request #182
Opened 2021-03-22 07:56 UTC by wannte

안녕하세요 데이브!
구현하는데에도 오랜 시간이 걸렸던 만큼.. 코드 리뷰도 쉽지 않을 것 같은데요! 이번 미션 잘 부탁드려요!

우선, 구조보다도, 기능 구현에 초점을 맞추어 구현을 진행했어요. 점진적으로 리팩토링을 진행해 나가고자 하는데, 구조적으로 개선할 만한 부분이 있으면 피드백 주시면, 최대한 반영하여 리팩토링 진행하겠습니다.

구현함에 있어서 생긴 의문점에 대해서 남깁니다!
1. "start", "end", "move a2 a3" 와 같은 명령어에 대한 책임을 view에서 가지고 있는데, 이 부분을 게임에서 지는게 맞을까요?
2. 체스 보드를 출력하는데에 있어서 Map<Position, Piece> 를 사용하고 있는데요, 현재에는 도메인 로직을 직접 사용하고 있는데요, 어떤 방식으로 DTO?를 구성해 나가는게 좋을까요?

감사합니다!

2021-03-25 11:56 UTC, dave915 requested changes
완태 안녕하세요! 리뷰를 맡게된 데이브입니다 :)
이번주에 업무가 갑자기 많이들어와서 리뷰가 늦었어요😭 죄송합니다 🙇‍♂️

질문 주신 부분에 관한 코멘트와 몇가지 피드백 남겼어요. 
확인부탁드릴게요! 
궁금한점이 있다면 언제든 DM주세요! :)

2021-03-25 11:56 UTC, dave915 commented on src/main/java/chess/view/InputView.java
> +    public static InputPositionDTO requestPositions() {
>"start", "end", "move a2 a3" 와 같은 명령어에 대한 책임을 view에서 가지고 있는데, 이 부분을 게임에서 지는게 맞을까요?

아래와 같은 필드를 가진 객체를 만들고 해당 객체 내부에서 해주면 어떨까요? 

```
private String command;
private List<String> options;
```

2021-03-25 11:56 UTC, dave915 commented on src/main/java/chess/view/OutputView.java
> +    }
>체스 보드를 출력하는데에 있어서 Map<Position, Piece> 를 사용하고 있는데요, 현재에는 도메인 로직을 직접 사용하고 있는데요, 어떤 방식으로 DTO?를 구성해 나가는게 좋을까요?

Domain에서 Map<String, String> ( ex: key는 "a1" value는 "K" )처럼 최소한의 정보만 주면 어떨까요?

2021-03-25 11:56 UTC, dave915 commented on src/main/java/chess/domain/piece/Pieces.java
> +    public Piece getPieceOf(Position position) {
Piece를 얻어올때마다 List<Piece> 를 순회하는데, Map을 이용해보면 어떨까요?

2021-03-25 11:56 UTC, dave915 commented on src/main/java/chess/domain/piece/Pieces.java
> +    public double score(Color color) {
현재 Pieces의 정보를 넘겨주어 결과를 계산 및 저장하고있는 객체를 만들고 계산하는 로직을 해당 객체로 이동시켜도 좋을 것 같아요!

2021-03-25 11:56 UTC, dave915 commented on src/main/java/chess/domain/piece/Rook.java
> +        return 5;
하드코딩을 제거해주세요 :)

2021-03-30 17:51 UTC, wannte commented
안녕하세요 데이브!
아직 상태패턴을 완전하게 적용하지 못했지만! 오늘 PR을 1차로 보내고 내일 마저 작업을 진행하도록 하겠습니다.

감사합니다!

2021-04-01 13:47 UTC, dave915 requested changes
완태 안녕하세요! 
피드백 반영하신 부분에서 약간 더 수정해보면 좋을 것 같아 코멘트 남겼습니다 😁
궁금한점 있으면 편하게 DM주세요!

2021-04-01 13:47 UTC, dave915 commented on src/main/java/chess/domain/moveStrategy/MoveStrategy.java
> +public interface MoveStrategy {
MoveStrategy가 너무 복잡하게 나뉜것 같아요. 
SingleMoveStrategy, MultipleMoveStrategy, PawnMoveStrategy 이렇게만 나누어도 될 것 같아요 :) 

음.. 그리고 `List<List<Position>>` 대신 `List<Position>` 을 리턴하도록 만들 수 있지 않을까요?

2021-04-01 13:47 UTC, dave915 commented on src/main/java/chess/domain/game/Board.java
> +            routes = fromPiece.killablePositions(from);
이 부분은 Pawn때문에 생긴것일까요? Piece의 moveablePosition에게 from, to 모두전달하고, Pawn일때 to가 현재 위치의 대각선에 있다면 killablePositions도 합쳐서 주도록 하는건 어떠신가요?

2021-04-04 12:49 UTC, dave915 approved these changes
완태 안녕하세요 :) 
피드백 반영 하신 부분 확인했습니다 👍 
다음 단계 진행해주세요!

2021-04-04 12:49 UTC, dave915 commented on src/main/java/chess/domain/game/Board.java
> +        if (fromPiece.movablePositions(from, Collections.unmodifiableMap(pieceByPosition)).contains(to)){
`Collections.unmodifiableMap(pieceByPosition)` 대신 `allPieces()` 메소드를 사용해도 될 것 같아요. 
if 조건식 안이 너무 복잡 한 것 같아요 변수 분리후 contains 부분만 조건식 안에 남아있게 수정하면 좋을 것 같아요 😭

2021-04-04 12:49 UTC, dave915 commented on src/main/java/chess/domain/moveStrategy/PawnMove.java
> +                                   .filter(column ->
조건 판별식을 보기가 힘들어요. 변수분리 또는 메소드 분리를 사용해주세요.
코드 전체적으로 판별식 부분은 간단했으면 좋겠어요 :)

2021-04-04 12:49 UTC, merged