[1,2,3단계 - 체스] 와이비(허영범) 미션 제출합니다.
woowacourse/java-chess pull request #188
Opened 2021-03-22 08:44 UTC by hybeom0720

안녕하세요! 김고래! 
체스 미션 리뷰를 받게된 와이비입니다. 잘 부탁드려요!
이번 미션의 경우에는 방대한 양과 각자의 코드 구현 방향이 상이해서 갈피를 찾기 어려웠던 미션이었습니다.
특히 어떤 기능을 어디에 책임을 둬야할지 잘 감이 안 잡혀서 많이 헤멨지만, 그 덕분에 객체의 개념에 대해서는
한 층 더 이해를 할 수 있었던 미션이었습니다.
하지만 많은 기능들을 다루다보니, 코드 구조에 궁금한 점이 상당히 많습니다.

## Q1. 커맨드 패턴의 적용
이번 미션을 진행하면서 전략 패턴과 상태 패턴 이외의 새로운 패턴인 커맨드 패턴에 대해서 알게 되었습니다.
커맨드 패턴의 경우 앞의 두 패턴보다 개념을 빨리 이해할 수가 있었습니다.
하지만 컨트롤러에서 호출한 커맨드에 따른 뷰어를 호출해야한다는 점 때문에 커맨드 패턴을 적용하려고 해도 많은 고민이 필요하게 되었는데요.
각 레이어 별 데이터 통신을 담당하는 DTO를 생성한 다음에 DTO의 state나 Instance of  결과에 따라서 Controller에서 다른 View를 호출하는 방향으로 가야할지 궁금합니다.

##Q2. 컨트롤러에서 Enum
앞서 말한 컨트롤러 패턴을 적용하지 못하였기 때문에, View에서 받아온 값에 따라 다른 로직을 호출하는 기능에 대해서 많은 고민을 하게 되었습니다. 저는 컨트롤러에서 Enum으로 정해진 패턴에서 로직을 호출하는 방향을 선택하게 되었습니다.
하지만  지금의 [Commands](https://github.com/hybeom0720/java-chess/blob/step1/src/main/java/chess/controller/Commands.java) 라는 객체의 책임이 컨트롤러가 아닌 도메인의 책임도 가지고 있는지 궁금합니다. 만약 도메인의 책임을 가지게 된다면, 앞서 말한것 처럼 각 커멘드의 로직의 수행한 뒤에 데이터를 컨트롤러에 넘기고 컨트롤러에서는 이 데이터를 형식에 따라 분류하여 알맞은 뷰어를 호출하는 방식으로 따로 가야하는지 궁금합니다. 

##Q3. 도메인의 책임과 코드의 길이
앞서 언급드렸듯이 이번 미션은 어떤 도메인이 어떤 책임을 가져야하는지에 대한 고민의 연속이었던 것 같습니다.
책임을 가리는 와중에, 인자로 얼마만큼 전달받을 것인가? 어떤 기능을 맡을 것인가?도 중요한 고려 사항이었는데요.
저의 코드에서는 보드가 경로 및 위치에 관한 책임을 가지게 되었습니다.
이 때문에 인자는 줄어들고 위치에 관한 책임은 확실하게 분배가 되었던 것 같지만, 그에 관련된 부분을 충실히 이행하기 위해서
코드가 많이 길어진 듯한 느낌이 듭니다. (140여줄) [보드 코드](https://github.com/hybeom0720/java-chess/blob/step1/src/main/java/chess/domain/board/Board.java)
코드의 길이가 길어지더라도 객체가 맡은 책임에 대해서만 검증과 수행을 해주면 코드의 길이는 상관이 없을지 더 나아가 저의 코드에서 
보드의 책임을 분리할 곳이 없는지 궁금합니다.

이번 리뷰와 피드백을 통해서 잘못 알고 있는 개념을 바로 잡고 더 깊게 코드에 대해서 이해를 하고 싶습니다.
이외에 더 나은 구조나 책임에 대해서 가르쳐주시면 코드에 반영하면서 성장하고 싶습니다.
항상 크루들의 성장에 많은 도움을 주시는 리뷰어에게 감사드립니다!

2021-03-22 09:29 UTC, hybeom0720 commented
# 와이비의 Chess 1차 학습로그 
## [OOP] Command Pattern - 4
### 항목
- 커맨드 패턴을 통해서, 각각의 객체들이 로직을 수행하기 위해서 같은 명령어를 사용할 수 있게 해주는 커멘드 패턴에 대해서 배우게 됨.
- Enum의 사례처럼 최대한의 분기를 줄이면서, 각각의 객체에 대해서만 신경을 써줘도 된다는 점이 큰 강점
- void처럼 반환값이 없으면 괜찮지만, 각각의 객체에서 수행하는 로직들이 반환값이 다르거나 다른 View를 호출할 때 어떻게 이를 다시 분기할 것이지에 대한 고민이 추가적으로 필요함

[커맨드 패턴 참고 링크](https://victorydntmd.tistory.com/295)

## [OOP] 객체 지향 프로그래밍 - 4
### 항목
- 이번주 강의 주제인 엘레강트 오브젝트를 활용하여 객체를 구성하려고 노력
- 각각의 코드 명이 깔끔해지고 조금 더 객체 중심이 되었으나, 유틸리티를 사용하지 않음으로서 생기는 코드 길이의 비대화 및 책임 분리에 대한 추가적인 고려 필요
- 생성자를 다양하게 적극적으로 만들어, 생성의 유연성 및 중복 코드 제거

## [JDK] 함수형 인터페이스 - 5
### 항목
- 다른 언어들처럼 함수 독자적으로 하나의 개체로 보고 다룰 수 있는 함수형 인터페이스를 개념을 넘은 구현으로서 다뤄보게 됨.
- 이를 통하여 Enum에서 하나의 프로퍼티로 다룰 수 있다는 점에서 인터페이스도 하나의 구성 요소로 다룰 수 있다는 점을 알게 됨.
- 기본적인 구성 요소와 활용을 넘어서 이를 이용한 구조 개선에 대해서 공부하고 싶음.

[함수형 인터페이스](https://velog.io/@litien/Modern-Java-Java-8-%ED%95%A8%EC%88%98%ED%98%95-%EC%9D%B8%ED%84%B0%ED%8E%98%EC%9D%B4%EC%8A%A4)

## [JDK] Optional - 3
### 항목
- Null 값 처리를 위한 Optional을 활용하여 코드의 안정성을 높이게 됨.
- try-catch를 통한 예외 처리에 비해 코드의 길이가 비약적으로 줄어들게 됨.
- 스트림과 섞어서 Optional의 장점을 극대화하는 방향으로 공부할 예정.

## [JDK] Char 자료형 - 1
### 항목
 - Char로 구성된 프로퍼티 사용, char가 int로 전환되어 덧샘 및 뺄셈을 사용이 가능함을 확인

2021-03-25 01:31 UTC, ep1stas1s requested changes
객체간 메세지 전달을 통해 잘 구현해주셨네요 👍 
참고할만한 코멘트 몇개 남겼으니 궁금한 점 있으시면 언제든 DM주세요
(리뷰가 늦어져서 죄송합니다 ㅠ_ㅠ)

2021-03-25 01:31 UTC, ep1stas1s commented on src/main/java/chess/domain/board/Board.java
> +    public void putPieceAtPosition(Position position, Piece piece) {
사실 이번 미션에서 중심이 되는 클래스라 기능이 많은건 사실이에요ㅠ_ㅠ
다만 와이비가 기능을 잘게 쪼개다보니 더 길어졌다고 생각하시는 것 같네요ㅎㅎ
코르를 리팩토링하는 과정중에는 잘게 쪼개는 방식도 있지만, 반대로 합치는 과정도 리팩토링 기법 중 하나니까 와이비가 생각하시기에 깔끔한 코드를 만들어주시면 될것 같아요~!

이런 부분은 사람마다 많이 다를 수 있을 것 같아요ㅎㅎ
`putPieceAtPosition(...)`나 `checkPath(...)`와 같은 메서드로 예를 들 수 있겠는데요
개인적으론 이런 메서드는 풀어서 써도 된다고 생각하는 편이에요 ^_^

2021-03-25 01:31 UTC, ep1stas1s commented on src/main/java/chess/domain/board/InitializedBoard.java
> +    private static final Map<Position, Piece> initializedBoard = new HashMap<>();
상태를 가지고 있는 객체를 static으로 사용하면 thread-safe하지 않습니다
현재의 구조에서 웹이나 멀티쓰레드로 변경될 때, 이게 공유해야하는 자원인지에 대해 고민해보면 좋을 것 같아요 😃

2021-03-28 05:07 UTC, ep1stas1s approved these changes
미션 진행하시느라 고생하셨습니다 👍 
간단한 코멘트 남겼으니 다음 단계 진행하면서 참고해주세요ㅎㅎ

2021-03-28 05:08 UTC, merged