[1, 2, 3단계 - 체스] 에어(김준서) 미션 제출합니다.
woowacourse/java-chess pull request #190
Opened 2021-03-22 08:58 UTC by KJunseo

안녕하세요 코니! 이번 체스 미션을 함께하게 된 에어입니다! 잘 부탁드려요 🙏
체스 미션이 이번까지에 비해 많이 어렵고 막막하더라고요 😭 
일단 최대한 페어랑 같이 구현해봤고 코니에게 도움을 받으면서 고쳐나가려고 해요!! 너무 잘하려고 욕심부려서 제출하는 것 보다 리뷰어님이랑 같이 소통하는게 더 좋은 것 같더라고요!(그렇게 하라는 피드백도 받았었어요 ㅎㅎ)
많이 피드백 해주세요!

<hr>

처음에 기능 목록을 대충(?) 작성하고 구현하면서 기능 목록을 수정해나가려고 했는데, 구현에 들어가보니 기능 목록이 자세하지 않으니까. 막히는 부분이 많았어요. 중간에 다시 기능 목록을 세세히 작성한 후 구현을 시작했어요.

이번 미션이 쉽지 않아서 tdd를 많이 적용하지 못했어요. 테스트 코드부터 짜려니까 너무 막막하더라구요. 그래서 프로덕션 코드를 짜고 테스트 코드를 추가한 부분이 많았어요  😭 😭 

<hr>

### 궁금증
Q1. 현재 들어오는 명령어(start, end, move, status)에 따라 수행하는 기능이 다른데 각 명령어에 따른 분기문을 없애려고 하다보니, Command enum에서 처리하려는 시도를 했어요. 그런데 이게 명령어 마다 출력을 해주는 부분도 필요하고 해서 고민을 했어요. Command 자체도 도메인이라고 생각이 들어서 view와 관련된 로직이 들어가면 안될 것 같더라고요. 그리고 결국 move와 status 명령어는 Command 안에서 처리하지 못하고 Controller에서 처리하게 되었습니다. 😭 이 부분을 어떤 방법으로 리팩토링 해볼 수 있을까요?

Q2. 현재 각 piece들이 갈 수 있는 위치 리스트를 구하는 로직에서 많은 중복이 발생했어요. 페어랑 인터페이스를 사용해서 분리해보려고 시도는 해보았지만 잘 되지 않았어요. 저희는 퀸, 룩, 비숍(여러칸을 움직일 수 있음)과 킹, 나이트(한 칸씩 움직일 수 있음)을 폰(특수한 경우) 이렇게 piece들을 인터페이스로 분리해서 생각해보려고 했는데 잘 안되더라구요.. 이 부분도 힌트 부탁드려요!!

Q3. 현재 각 piece가 Team을 인스턴스 변수로 가지고 있어요. 하지만 Board에서 사용할 때 map<Team, Pieces>로 Team에 의해 Piece들이 구분되어져 있는데, Team이 인스턴스 변수로 필요할까? 라는 생각이 들었어요 코니는 어떻게 생각하시나요?

+) 질문이 더 많았는데 바로 생각이 안나네요ㅠㅠ 추가적인 질문은 comment나 dm으로 보내겠습니다!
+) 학습 로그는 오늘 밤안에 추가하겠습니다!

이번 리뷰 정말 잘 부탁드려요  🙏 🙏

2021-03-22 13:24 UTC, KJunseo commented
## 학습로그

# [OOP] 상속 - 4
## 내용
- 체스 말(pawn, rook, knight, bishop, king, queen)을 Piece 추상 클래스로 통해 상속 구현
- 동일한 필드를 가지는 하위 클래스들이 있는 경우 인터페이스를 사용하기보다 상속을 사용하는 것이 낫다고 판단

# [TDD] TDD 적용 - 3
## 내용
- todo list를 작성 후 가장 간단한 도메인부터 테스트 코드 작성 -> 프로덕션 코드 작성 -> 리팩토링 과정을 거쳐 코딩하려고 노력했다.
- 테스트 코드부터 짜기가 힘들어 프로덕션 코드부터 짠 부분이 많았다..

# [JDK] Stream API - 3
## 내용
- 위치에 따라 piece가 존재하는지, 해당 위치의 piece를 삭제, 점수 계산 등에 stream을 적용
- 다수준 스트림은 아직 잘 모르겠지만 간단한 스트림은 조금 사용하기 편해졌다는 것을 느낌
## 링크
- [chess/domain/pieces/Pieces.java](https://github.com/woowacourse/java-chess/blob/6636ff105f393769ea1549d50f3eb40a23a58823/src/main/java/chess/domain/pieces/Pieces.java)

# [Java] Enum - 3
## 내용
- 명령어, Team, 체스판의 Row, Col 에 enum 적용
## 링크
- [chess/view/Command.java](https://github.com/woowacourse/java-chess/blob/6636ff105f393769ea1549d50f3eb40a23a58823/src/main/java/chess/view/Command.java)
- [chess/domain/Team.java](https://github.com/woowacourse/java-chess/blob/6636ff105f393769ea1549d50f3eb40a23a58823/src/main/java/chess/domain/Team.java)
- [chess/domain/position/Row.java](https://github.com/woowacourse/java-chess/blob/6636ff105f393769ea1549d50f3eb40a23a58823/src/main/java/chess/domain/position/Row.java)
- [chess/domain/position/Col.java ](https://github.com/woowacourse/java-chess/blob/6636ff105f393769ea1549d50f3eb40a23a58823/src/main/java/chess/domain/position/Col.java)

# [OOP] 일급콜렉션 사용 - 1
## 내용
- Pieces, Board로 일급콜렉션 적용
## 링크
- [chess/domain/pieces/Pieces.java](https://github.com/woowacourse/java-chess/blob/6636ff105f393769ea1549d50f3eb40a23a58823/src/main/java/chess/domain/pieces/Pieces.java)
- [chess/domain/board/Board.java](https://github.com/woowacourse/java-chess/blob/6636ff105f393769ea1549d50f3eb40a23a58823/src/main/java/chess/domain/board/Board.java)

# [Java] unmodifiableList vs new ArrayList - 2
## 내용
- unmodifiableList와 new ArrayList 차이
## 링크
- [unmodifiableList vs new ArrayList](https://velog.io/@max9106/%EC%83%88%EB%A1%9C-%EB%B0%B0%EC%9A%B4-%EB%82%B4%EC%9A%A9-2021.03.16-2021.04.02#unmodifiablelist-vs-new-arraylist)

2021-03-23 16:33 UTC, choihz requested changes
안녕하세요, 에어! 리뷰어 코니입니다.

체스 미션을 잘 구현해 주셨네요 👍 리뷰 보시고 궁금한 점이나 의견이 있으시다면 언제든 코멘트 또는 DM 주세요~

2021-03-23 16:33 UTC, choihz commented on src/main/java/chess/controller/ChessGameController.java
> +    private void move() {
> 현재 들어오는 명령어(`start`, `end`, `move`, `status`)에 따라 수행하는 기능이 다른데 controller에서 각 명령어에 따른 분기문을 없애려고 하다보니, `enum Command` 에서 처리하려는 시도를 했어요. 그런데 이게 명령어 마다 입력이 필요하거나 출력을 해주는 부분도 필요한 명령어도 있어서 `Command`에서 처리하기가 힘들더라고요. `Command` 자체도 도메인이라고 생각이 들어서 view와 관련된 로직이 들어가면 안될 것 같더라고요. 그래서 결국 `move`와 `status` 명령어는 `Command` 안에서 처리하지 못하고 Controller에서 처리하게 되었습니다. 😭 이 부분을 어떤 방법으로 리팩토링 해볼 수 있을까요?

꼭 반영해야 하는 건 아닌데 [커맨드 패턴](https://johngrib.github.io/wiki/command-pattern/)이란 걸 한번 살펴 보세요. 아무래도 `enum`보다는 좀 더 유연하게 사용할 수 있을 것 같아요. 저는 지금 상태도 나쁘지 않다고 생각합니다 😊

2021-03-23 16:33 UTC, choihz commented on src/main/java/chess/domain/pieces/Pawn.java
> +    private void addMovablePositions(final List<Position> movablePositions, final Board board, final int degree) {
> 현재 각 `piece`들이 갈 수 있는 위치 리스트를 구하는 로직에서 많은 중복이 발생했어요. 페어랑 인터페이스를 사용해서 분리해보려고 시도는 해보았지만 잘 되지 않았어요. 저희는 `퀸`, `룩`, `비숍`(한 번에 여러 칸을 움직일 수 있음)과 `킹`, `나이트`(한 번에 한 칸씩 움직일 수 있음)와 `폰`(특수한 경우) 이렇게 `piece`들을 인터페이스로 분리해서 생각해보려고 했는데 잘 안되더라구요.. 이 부분도 힌트 부탁드려요!!

지금 중복이 많은 건 사실인데요, 아무래도 `Piece`의 계층 구조 때문에 유연하게 대응하는 데 한계가 있는 것 같아요. 이것 역시 필수는 아닌데 이 로직을 구하는 부분 역시 별도 객체로 분리해 보면 더 괜찮은 방법이 나올 수도 있을 것 같아요.

2021-03-23 16:33 UTC, choihz commented on src/main/java/chess/domain/pieces/Piece.java
> +    private final Team team;
> 현재 각 `piece`가 `Team`을 인스턴스 변수로 가지고 있어요. 하지만 `Board`에서 사용할 때 `map<Team, Pieces>`로 `Team`에 의해 `Piece`들이 구분되어져 있는데, `piece`에서 `Team`이 인스턴스 변수로 필요할까? 라는 생각이 들었어요 코니는 어떻게 생각하시나요?

그런데 굉장히 많은 메서드들이 `Team`을 필요로 하고 있는 것으로 보여서요, `Team`을 인스턴스 변수에서 제거하면 이 메서드들은 전부 `Team`을 매개 변수로 받게 되나요? 🤔

2021-03-23 16:33 UTC, choihz commented on src/test/java/chess/domain/board/BoardFactoryTest.java
> +    // list { a ~ h }
??

2021-03-23 16:33 UTC, choihz commented on src/test/java/chess/domain/pieces/BishopTest.java
> +    Position straightBlankPosition = new Position(2, 1);
테스트 코드에서도 접근 제어자 확인 부탁드려요~

2021-03-25 06:35 UTC, KJunseo commented
안녕하세요 코니! 피드백 주신 것 보고 리팩토링 해봤어요!!
리뷰 다시 부탁드립니다!! 🙏🙏

<hr>

추가적으로 질문이 생겼어요!

Q1. 커스텀 예외를 한 번도 써본 적이 없었는데 피드백을 보고 일단 경험해보지 못한 것이니 적용해보자는 생각이 들었어요! 적용해 보고 나니, 커스텀 예외가 무슨 장점이 있는지 잘 와닿지가 않더라구요. 기존에 존재하는 예외에 메세지로 어떤 예외인지 표현하는 것만으로 충분하지 않나? 라는 생각이 들었어요. 커스텀 예외인 경우 예외 클래스 이름을 영어로 써야하는데 이때 가독성이 더 떨어지는 느낌도 조금 들어서요. 혹시 코니는 커스텀 예외가 어떤 장점을 가지고 있다고 생각하시나요?? 

Q2. 말씀해주신 커맨드 패턴을 한 번 적용해보려고 했어요. 그런데 지금 구조에 비해 명령어 별로 클래스가 생기고, 만들어준 커맨드 클래스를 등록하는 등 더 복잡해지는 것에 비해 구조가 크게 나아지는 느낌을 못받아서 커맨드 패턴은 적용하지 않았습니다! 대신 enum 내부를 람다식으로 좀 더 간단하게 만들어봤어요. 

여기에 대해 다른 크루와 이야기해봤는데, Command(enum)에 컨트롤러를 주입해서 사용하더라구요. 저는 Command 자체도 도메인으로 봐서 Controller에 대해 알고 있으면 안된다고 생각했었는데, Command 자체도 컨트롤러 같은 느낌으로 사용했다고 하시더라고요. 코니는 어떻게 생각하시나요? 
```java
// 예시
public enum Command {
    START("START", ChessController::initialize),
    END("END", ChessController::finish),
    MOVE("MOVE", ChessController::move),
    STATUS("STATUS", ChessController::status);
    ...
```

Q3. 이동 가능한 위치를 구하는 로직을 인터페이스로 분리해봤어요. 그런데 매개변수가 4 ~ 5개 까지 가기도 하면서 너무 억지로? 분리한 듯한 느낌이 드네요ㅠㅠ  getter도 사용하게 되어서 이 부분에 대해 한 번 보시고 힌트 주시면 감사하겠습니다! 🙏🙏

2021-03-27 06:13 UTC, choihz approved these changes
안녕하세요, 에어!

피드백을 잘 반영해 주셨네요 💯 이번 단계는 여기서 마무리하도록 할게요. 다음 단계에서 만나요~ 👋

2021-03-27 06:13 UTC, choihz commented on src/main/java/chess/domain/move/Moving.java
> +}
> Q3. 이동 가능한 위치를 구하는 로직을 인터페이스로 분리해봤어요. 그런데 매개변수가 4 ~ 5개 까지 가기도 하면서 너무 억지로? 분리한 듯한 느낌이 드네요ㅠㅠ getter도 사용하게 되어서 이 부분에 대해 한 번 보시고 힌트 주시면 감사하겠습니다! 🙏🙏

`Moving`을 인터페이스로 만드셨고 모든 말이 각각 구현체를 가지는 것이 아니라 공통된 구현체를 공유하고 있는 구조로 결정하셨기 때문에, 이런 제약 하에서는 많은 매개변수가 불가피한 것 같아요. 아예 모든 말에 대해 각각의 `Moving` 구현체를 만들고 `allMovablePositions()` 메서드도 `Moving`으로 옮겨 보면 어떨까요? 하나의 제안일 뿐 필수는 아닙니다 😉

2021-03-27 06:13 UTC, choihz commented on src/main/java/chess/exception/NegativePositionException.java
> +}
사용되지 않고 있네요~

2021-03-27 06:13 UTC, merged

2021-03-27 14:34 UTC, KJunseo commented on src/main/java/chess/view/Command.java
> +public enum Command {
Command도 도메인 처럼 본다고 했는데 정작 위치를 view에 뒀었네요ㅎㅎ.. 도메인 패키지에 두는 것이 적절하다고 생각해요!

2021-03-27 14:37 UTC, KJunseo commented on src/main/java/chess/domain/position/Position.java
> +    }
앗.. 전체적으로 보면서 바꾼다고 바꿨는데 놓친 부분이 있네요ㅠㅠ 1차 리뷰때 말씀하신 부분을 반영하지 못한것같아 부끄럽군요.. 다음부터는 애초부터 변수명 축약을 하지 않아야겠다고 많이 느끼고있네요 😭

2021-03-27 15:59 UTC, KJunseo commented on src/main/java/chess/domain/move/Moving.java
> +}
코니~ 
코니 피드백 보고 각 Piece별로 Moving 인터페이스의 구현체를 만들고, Queen, Bishop, Rook을 다시 MultiMoving 추상클래스로 묶고, King, Knight는 SingleMoving 추상클래스로 묶으니까 매개변수도 줄고, 중복도 없어졌어요!! 전에 비해 꽤 만족스러워졌어요! 감사합니다🙏

2021-03-27 18:01 UTC, KJunseo commented on src/main/java/chess/domain/pieces/Piece.java
> +    private final Moving moving;
저도 Piece가 너무 많은 것을 알고 있다고 생각해서 Team은 아에 필드에서 없애줬고, initial과 score는 하나의 enum으로 묶어서 관리하게 바꿨습니다! 2단계 리뷰보낼 때 봐주시면 감사하겠습니다!! 👍🏻👍🏻