[1,2,3단계 - 체스] 다니(이다은) 미션 제출합니다.
woowacourse/java-chess pull request #193
Opened 2021-03-22 08:59 UTC by da-nyee

안녕하세요, 휴! 다니입니다 🙌

이번 체스 게임 너무 어려웠습니다ㅠ 그래도 페어랑 끝까지 함께 하면서 열심히 구현했습니다!

아직 중복 코드가 많고, 테스트 케이스도 덜 작성한 부분이 있는데요..!
데드라인을 지키는 게 우선인 거 같아서 먼저 PR을 보냅니다!
이후에 리팩토링 하면서 수정하겠습니다 !

이번 미션 코드 리뷰 기다리고 있겠습니다!

귀한 시간 내주셔서 감사드립니다 🙇‍♀️❣

2021-03-22 09:51 UTC, da-nyee commented
# 📚 다니의 학습 로그
## [Design Pattern] Command Pattern - 2.5
### 내용
<p align="center"><img src="https://user-images.githubusercontent.com/50176238/111971007-41519c00-8b3f-11eb-8856-1ce30b280403.PNG"></p>

- 체스 실행 명령들을 Command로 추상화
- 상태 패턴이랑 비슷하다는 느낌을 받음

### 링크
- [[디자인패턴] 커맨드 패턴 ( Command Pattern )](https://victorydntmd.tistory.com/295)
- [java-chess/src/main/java/chess/domain/command/](https://github.com/da-nyee/java-chess/tree/step1/src/main/java/chess/domain/command)

2021-03-23 10:14 UTC, Hue9010 requested changes
다니! 리뷰가 늦었네요. 😭🙏
전체적으로 요구사항에 맞게 잘 만들어주셨네요!
개선하면 좋을 부분과 생각해볼 부분 피드백 남겼는데 확인해주세요!
궁금한건 언제든 질문주시면 됩니다! 피드백 드리지 않은 부분이라도 고민되는 부분 있으면 언제든 말씀주세요. 😉

2021-03-23 10:14 UTC, Hue9010 commented on src/main/java/chess/domain/position/Position.java
> +    public static Position find(final String source) {
Position.find()
Position을 사용하는 사람들은 POSITIONS의 존재를 모르는데 find만 봤을 때는 무엇을 찾는다는건지 아리송할 수 있을 것 같아요.
위치를 찾는다는것보다는 위의 valueOf처럼 객체생성에 관련된 네이밍을 쓰는건 어떨까요?

2021-03-23 10:14 UTC, Hue9010 commented on src/main/java/chess/domain/position/Position.java
> +    }
getRank, getFile의 사용처를 보니까 사용하는 용도가 rank와 file을 가져온 다음 이동시킬 위치만큼 int값을 바꾼 다음 새로 position을 생성하네요
```java
        int rank = position.getRank().getValue();
        int file = position.getFile().getValue();
        Position nextPosition = Position.valueOf(rank + 1, file - 1);
```
결국 기존 Position에서 특정 위치만큼 떨어진 Position을 구하는건데 현재 위치서 이동할 값을 입력 받아 이동된 Position을 제공하는 메서드를 만들면 어떨까요?
position.move(-1, 0);

2021-03-24 00:52 UTC, da-nyee commented on docs/README.md
> +<p align="center"><img src="https://user-images.githubusercontent.com/50176238/111739494-7b643900-88c6-11eb-9f0b-b981f2ce3730.jpg" width="850" height="600"></p>
넵 ㅎㅎㅎ 페어랑 같이 그렸습니다! 😄

2021-03-28 16:23 UTC, da-nyee commented on src/main/java/chess/controller/ChessController.java
> +        while (true) try {
휴가 말씀하신 대로 `do-while`을 사용해서 리팩토링했습니다!

```
private void startChessGame(final Command command) {
    Round round = new Round(StateFactory.initialization(PieceFactory.whitePieces()),
            StateFactory.initialization(PieceFactory.blackPieces()), command);
    do {
        playChessGame(round);
    } while (round.isPlaying());
}

private void playChessGame(final Round round) {
    try {
        play(round);
    } catch (RuntimeException runtimeException) {
        OutputView.showExceptionMessage(runtimeException);
    }
}
```

인덴트 1도 지킬 수 있고 코드도 깔끔해져서 좋은 것 같아요! 피드백 감사합니다 🤗

2021-03-28 16:48 UTC, da-nyee commented on src/main/java/chess/domain/piece/Pieces.java
> +                .findAny();
음...!!! 페어 프로그래밍을 하면서도 Map을 쓰는 게 좋을지, 아니면 List를 쓰는 게 좋을지 잠깐 고민했었는데요!
체스판의 각 위치는 유니크하니까 key로 위치를 갖는 Map을 쓰는 게 맞지 않을까? 하고 바로 Map을 사용하게 됐습니다!

이번에 피드백 남겨주셔서 어떤 자료구조가 더 좋을까를 다시 한번 생각해봤는데요.
만약 List를 사용한다면 각 인덱스가 위치가 되고, 요소로 기물이 들어가야 할 것 같아요.
근데, 체스판은 행과 열을 가지고 있기 때문에 List는 자연스레 2차원 형태로 생성될 거 같아요!

2차원 List도 괜찮은 방법일 것 같지만...! Map보다는 사용하기에 조금 더 복잡한 느낌이 들어요.
그래서 체스판에서는 List보다 Map이 더 단순하게 사용하기 좋을 것 같아요!

혹시 휴의 생각은 어떠신가요?? 의견 공유해주시면 감사하겠습니다! 🙏

2021-03-28 16:57 UTC, da-nyee commented on src/main/java/chess/domain/player/Round.java
> +        if (whitePlayer.isFinish()) {
이 피드백 적용해보려고 했는데, 생각보다 잘 안 되더라구요...!
게임 시작 시에 white, black을 차례로 주입하게 되어 있어 현재 플레이어, 상대 플레이어로 변경하기 어려운 것 같아요 😭
혹시 리팩토링 힌트 조금만 더 주실 수 있나요??

2021-03-28 16:59 UTC, da-nyee commented on src/main/java/chess/domain/position/Position.java
> +                );
스트림 대신 2중 for문으로 변경했는데 가독성이 훨씬 좋아진 것 같아요! 👏

```
static {
    for (Rank rankValue : Rank.values()) {
        initializePosition(rankValue);
    }
}

private static void initializePosition(Rank rankValue) {
    for (File fileValue : File.values()) {
        POSITIONS.put(rankValue.getRank() + fileValue.getFile(), new Position(rankValue, fileValue));
    }
}
```

2021-03-28 17:01 UTC, da-nyee commented on src/main/java/chess/domain/piece/King.java
> +        basePieces.changePiecePosition(this, target);
기물에서 바로 변경이 가능하네요! 수정했습니다~!

```
this.changePosition(target.getPosition());
```

2021-03-28 17:06 UTC, da-nyee commented on src/main/java/chess/domain/piece/King.java
> +    }
전략 패턴을 적용해봤습니다!

![move_strategy](https://user-images.githubusercontent.com/50176238/112760687-ddddd780-9032-11eb-8c44-40e3f26e3ef4.PNG)

구조는 깔끔하게 나온 것 같은데, 아직 내부 코드는 깔끔하지 못한 것 같아요 💦

특히, `MultipleCellMoveStrategy`처럼 여러 칸을 이동해야 돼서 for문을 사용한 경우 중복 코드를 제거하기 어려운데요..
이 중복 코드를 없앨 수 있는 방법이 없을까요?? getRankValue, getFileValue도 없애고 싶은데 좋은 해결책이 떠오르지 않네요 😥

2021-03-28 17:13 UTC, da-nyee commented on src/main/java/chess/domain/piece/Piece.java
> +    }
static으로 되어 있는 isBlack은 인자로 String을 받는데, final로 되어 있는 isBlack은 Piece를 사용해서 대체하기 어려운 것 같아요...! 대체하고 싶은데, 좋은 방법이 없을까요...?!

2021-03-28 17:13 UTC, da-nyee commented on src/main/java/chess/domain/piece/Piece.java
> +    }
확인하지 못한 부분이었네요ㅠㅠ 분리했습니다!

2021-03-28 17:15 UTC, da-nyee commented on src/main/java/chess/domain/player/Round.java
> +            this.command = this.command.end();
아래와 같이 수정했는데, 맞는 방향으로 리팩토링한 건가요?!

```
if (state.isKing(target.getPosition())) {
    isEnd = true;
}
if (isEnd) {
    this.command = command.end();
    return;
}
```

2021-03-28 17:16 UTC, da-nyee commented on src/main/java/chess/controller/ChessController.java
> +            OutputView.showResult(PlayerResultDto.toDto(round.getWhitePlayer()));
아하...!! 이번에 DTO를 처음 사용해봐서 잘 몰랐어요! 네이밍 더 신경쓰도록 하겠습니다!! 🙌

2021-03-28 17:17 UTC, da-nyee commented on src/main/java/chess/view/OutputView.java
> +    public static void showChessBoard(final Map<Position, Piece> chessBoard) {
`ChessBoardDto`를 만들어서 사용하도록 변경했어요~!

2021-03-28 17:21 UTC, da-nyee commented on src/main/java/chess/domain/position/Position.java
> +    }
아래와 같이 이동 방향을 제공해서 이동 가능한 위치를 찾도록 수정했어요!

```
protected List<Position> makeUpRoutes(final Pieces basePieces, final Pieces targetPieces,
                                      final Position position) {
    return findPositions(basePieces, targetPieces, position, UP);
}
```

그런데, 다른 코멘트에도 언급했지만 여러 칸을 확인해야 하는 경우에는 이렇게 적용하기 어려운 것 같아요 😥
더 좋은 방법이 없을지 의견 남겨주시면 감사하겠습니다...!! 🙇‍♀️

2021-03-28 17:24 UTC, da-nyee commented
안녕하세요 휴! 다니입니다 🙌
저번주에 할 일이 많았어서 계획보다 리팩토링이 늦어졌습니다 ㅠㅠ

많은 피드백 남겨주셔서 감사합니다! 열심히 고민해보고 생각할 수 있는 시간이었습니다 🙇‍♀️

아직 부족한 부분들이 꽤 남은 것 같은데, 먼저 리뷰 받고 싶어서 리뷰 요청 보냅니다!

이번에도 귀한 시간 내주셔서 정말 감사합니다~! ✨

2021-03-29 13:31 UTC, Hue9010 approved these changes
다니! 피드백 잘 반영해주셨네요! 👍
이번 단계는 여기서 머지하도록 할게요. 개선하면 좋을 부분과 질문에 대한 답변 남겼는데 확인하시고 궁금한건 언제든 질문 주세요. 😉 
(혹시 제가 놓친 질문이 있다면 말씀주세요!!)

2021-03-29 13:31 UTC, Hue9010 commented on src/main/java/chess/domain/position/Position.java
> +    }
`findNextPositionByDirection`인데 조건에 부합하지 않으면 this를 반환해주네요. 그러면 nextPosition이 아닌 경우도 있는거 아닌가요? 🤔

2021-03-29 13:31 UTC, Hue9010 commented on src/main/java/chess/domain/piece/strategy/MultipleCellMoveStrategy.java
> +        }
> 특히, MultipleCellMoveStrategy처럼 여러 칸을 이동해야 돼서 for문을 사용한 경우 중복 코드를 제거하기 어려운데요..
이 중복 코드를 제거할 방법이 없을까요?? getRankValue, getFileValue도 없애고 싶은데 좋은 해결책이 떠오르지 않네요

지금처럼 조건에 따라 반복하거나 계속하거나 할 때는 재귀를 사용하면 해결 할 수 있을 가능성이 커요.
단순히 바로 재귀를 적용하거나 (그러면 빈 리스트를 보내줘야겠네요) 지금의 작업을 이동할 수 있는 최대(?) 위치를 구하는 것과 현재 위치에서 이동 가능한 위치를 List에 담는 작업 이 두가지를 분리해서 처리 할 수도 있을 것 같아요.

재귀(혹은 반복)을 통해 이동할 수 있는 가장 먼 Position을 찾고, 별개의 다음 반복에서 basePosition에서 targetPosition의 경로에 있는 모든 Position을 추가할 수 있을 것 같아요.

2021-03-29 13:31 UTC, Hue9010 commented on src/main/java/chess/domain/piece/strategy/MultipleCellMoveStrategy.java
> +        }
그리고 여러칸이 어려운거 맞아요. 전 옛날에 더 복잡하게 했던 것 같네요. 🙄
그런 점에서 충분히 잘해주셨습니다. 👏

뭔가 마무리 멘트 같은 이유는 다음 단계인 웹 적용이 쉬울 수도 있지만 막히면 한없이 막힐 수 있어서 피드백을 반영하거나 기존 코드를 바꾸고서 웹 적용을 하다 보면 단순히 웹 적용을 못하고 있는 건지 바꾼 코드에서 문제가 있는건지 판단이 안서고 혼란스러워하다가 많이 헤맬수 있답니다.
그래서 다음 단계를 진행할 때 웹 적용을 우선적으로 생각하고 그에 맞춰 변경을 한다음 나중에 여유가 되실 때 기존 코드를 리팩토링 하는 걸 추천드려요! 그런 면에서 웹 적용시 기존 코드가 망가지는 느낌이 들더라도 우선은 웹 적용만 신경 쓰는게 좋습니다.

전체 완료도를 놓고 봤을 때 웹 적용만해서 전체의 50%인 것과 웹 적용 일부와 기존 코드의 리팩토링까지 해서 전체의 50%면 전자가 마음이 편하실 겁니다. 😄

2021-03-29 13:31 UTC, Hue9010 commented on src/main/java/chess/domain/player/Round.java
> +    private Command command;
아래와 같이 수정했는데, 맞는 방향으로 리팩토링한 건가요?!

```java
if (state.isKing(target.getPosition())) {
    isEnd = true;
}
if (isEnd) {
    this.command = command.end();
    return;
}
```
---

위 코멘트 단 다음 답변주신 코멘트를 나중에 봐서 이것도 요기에 마저 달자면 Round가  Command를 상태로 가지지 않는걸 말씀드린 겁니다. Command가 상태로서 가질만한 객체인가 의문이 들더라고요. 
그래서 execute에서만 command를 사용하고 다른 곳은 이번에 추가한 isEnd를 사용하거나 위에서 언급 드린 것처럼 Command를 ChessController에서 직접 사용하여 확인 할 수 있을 것 같아요.

2021-03-29 13:31 UTC, merged