[1,2,3단계 - 체스] 아마찌(신지혜) 미션 제출합니다.
woowacourse/java-chess pull request #198
Opened 2021-03-22 09:08 UTC by NewWisdom

안녕하세요 휴 ! 아마찌라고 합니다 👀 
험난한 체스 미션을 함께 하게되어 영광입니다 🙇‍♂️

미션은 구현했지만, 구현에 급급하다 보니 설계도 탄탄히 하지 못해
로직이 여기 저기 많이 얽혀 있고 객체 책임도 명확히 분배되지 않은 것 같아서 
아직도 부족함이 많은 코드인 것 같습니다  🥲

미션을 진행하다가 생긴 궁금점은 추후에 코멘트로 달겠습니다 !

이번 미션동안 휴의 피드백을 통해 많이 배우고 스스로 성장하고 싶어요 ! 
어떠한 피드백도 정말 영광으로 생각합니다 👏
이번 미션동안 많이 괴롭혀주세요 ! ㅎㅎ 

잘부탁드리겠습니다 ! 감사합니다 🙏

2021-03-23 20:00 UTC, Hue9010 requested changes
아마찌 반가워요! 이번 리뷰를 맡은 휴입니다.
요구사항에 맞게 깔끔히 잘 구현해주셨네요. 👍
질문에 대한 답변과 몇가지 내용 피드백 남겼는데 확인해주세요!
궁금한건 언제든 질문 주세요. 😉

2021-03-25 15:35 UTC, NewWisdom commented
# 아마찌의 학습 로그 ✨

#### 📐 amazzi's rule 

* 가중치는 1~5로 표현한다.
* 링크는 학습하고 구현하는데 **참고한 링크**, 이것을 **반영한 링크**, 스스로 공부한 내용을 **정리한 링크** 3가지로 나눈다.
* 궁금한 점이나 고민중인 내용은 ❓로 마크해논다.


## [JDK] 람다의 변수 범위 - Effectively final, final

### 내용

리팩토링 전, 기능 구현을 할 때 for 문 내에 stream을 쓰게 되었는데, 반복문의 `i` 를 람다식 내에서 사용하려니 컴파일 에러가 났다.  
"Variable used in lambda expression should be final or effectively final"

*리팩토링 전 live한 코드 🥲*

![image](https://user-images.githubusercontent.com/43840561/111862130-956d4c80-8996-11eb-9abd-c2bef47886d9.png)

람다식 외부에서 선언된 `i` 는 값이 변할 수 있어 신뢰할 수 없으므로 컴파일 에러가 발생한다.  

<img src="https://user-images.githubusercontent.com/43840561/111863899-7de79100-89a1-11eb-8ed3-6c685817269d.png" alt="image" style="zoom:50%;" />

`i` 를 `index` 에 할당하였다.  
람다식은 외부 변수 `index` 를 사용하고 있지만, 람다식이 사용되는 블럭 내에서 값이 변하지 않기 때문에 `effectively final` 이다. 

람다식은 외부 block에 있는 변수에도 접근할 수 있지만 해당 변수가 불변으로 선언되었을 때만 가능하다.  
불변으로 선언해야 하는 이유는 지역 변수는 스택에 저장되기 때문에 람다식에서 값을 바로 참조하는 것에 제약이 있어  
복사된 값을 이용하게 되는데, 이때 멀티 쓰레드 환경에서 복사 될/복사된 값이 변경 가능 할 경우 이로 인한 동시성 이슈를 대응할 수 없기 때문이다.  

java 8부터는 final로 선언되지 않아도 초기화 된 이후 값이 한번도 변경되지 않았다면  
자바 8에서는 `final` 키워드를 붙이지 않아도 붙힌 것과 동일하게 컴파일러에서 처리하며 이를 `effectively final`이라고 할 수 있다.   

### 링크

#### 참고

* [[Java] lambda 와 effectively final](https://vagabond95.me/posts/lambda-with-final/)

## [JDK] Map vs FlatMap

### 내용

하나의 입력을 다시 stream으로 변환을 하고자할때 stream을 두번 쓰지 않고 `flatMap()` 사용

#### map()

단일 스트림 안의 요소를 원하는 특정 형태로 변환할 수 있다.  
파라미터로 받은 mapper에서 `extends R`를 반환한다.

```java
<R> Stream<R> map(Function<? super T, ? extends R> mapper);
```

#### flatMap()

flatMap은 map과는 다르게 mapper의 실행결과를 또다른 스트림으로 리턴한다.  
stream의 값들이 mapper을 돌때마다 새로운 스트림이 생성되는데, 이들을 나중에 합쳐서 하나의 스트림(`Stream<? extends R>`)으로 반환한다.

```java
<R> Stream<R> flatMap(Function<? super T, ? extends Stream<? extends R>> mapper);
```

### 링크

#### 참고

* [자바 map 메서드와 flatMap 메서드의 차이](https://madplay.github.io/post/difference-between-map-and-flatmap-methods-in-java)

#### 반영

* [Position.java ](https://github.com/NewWisdom/java-chess/blob/step1/src/main/java/chess/domain/position/Position.java)

2021-03-28 08:24 UTC, NewWisdom commented on src/main/java/chess/view/OutputView.java
> +        System.out.println("> 게임 이동 : move source위치 target위치 - 예. move b2 b3");
반영했습니다 ! 
1fcc772
감사합니다 :)

2021-03-28 08:53 UTC, NewWisdom commented on src/main/java/chess/domain/ChessGame.java
> +        sourcePiece.move(target, pieces);
휴의 피드백을 받고 보니 `현재 턴이 아닌 말의 움직임`과 `target에 같은 편 말이 있을 경우`는 기물을 제거하기 전에 검증해주니 문제가 되지 않지만,
기물이 제거 된 후에 piece에서 경로에 대한 검증을 해주기 때문에 만약 piece 내에서 경로 검증을 하다가 예외가 발생하면 
이동하지도 않았는데 target 기물이 제거되는 오류가 있었네요 🥲

그래서 이동에 관한 모든 검증을 
```java 
pieces.removePieceByPosition(target);
sourcePiece.move(target, pieces);
```
전에 마치도록 리팩토링을 시도했습니다 !
그런데 제 로직에서는`move()` 안에 기물마다 다른 이동 경로 검증이 얽혀있어서 밖으로 빼기가 쉽지 않더라구요 ! 
또 move()를 하는데, piece에게 pieces를 넘겨주고 움직이려는 기물이 모든 기물을 가지고 경로를 검사하면서 생기는 의존성을 보고
객체가 올바르게 분리되지 않았구나를 느꼈습니다 🥲

때문에 기물이 이동하기 전에 이동에 대한 검증을 외부에서 처리해주고 기물이 움직이도록 대대적인 리팩토링이 시작됐습니다 ㅎㅎ
외부(ChessGame)에서 `현재 턴이 아닌 말의 움직임`과 `target에 같은 편 말이 있을 경우`를 검증하고,  
각 기물들에게 자신의 이동 규칙을 알고 있게 하고, 
기물에게 이를 검증하는 메시지를 보내 이동 규칙에 어긋나지 않는지를 확인한 후 위치를 이동하도록 변경해보았어요 !
이는 아래 코멘트로 달 Direction 객체를 이용해 외부에서 경로 검증을 하도록 했습니다 !!

2021-03-28 08:54 UTC, NewWisdom commented on src/main/java/chess/domain/ChessGame.java
> +            throw new IllegalArgumentException("[ERROR] taget에 같은 편 말이 있습니다.");
오 사소한 것까지.... 너무 감사합니다 👏

2021-03-28 08:56 UTC, NewWisdom commented on src/main/java/chess/domain/position/Position.java
> +    public Position movedPositionByNumber(int xNumber, int yNumber) {
감사합니다 ! 객체 이름이 메소드에 중복 사용되지 않도록 수정했습니다 :)

7bea049

2021-03-28 09:11 UTC, NewWisdom commented on src/main/java/chess/controller/ChessController.java
> +        command.runFirstAction(this);
이 부분에 대한 피드백 너무 감사합니다 🥲👍
스스로 생각해보았을 때도 도메인이 컨트롤러를 실행시킨다는 것이 옳지 않다고 느꼈는데, 
휴의 피드백을 보고 다른 방안을 더 고민해볼 수 있었어요 !!

리팩토링 전 command 패턴에 대해 살펴보았는데, 
command라는 객체를 통해 각각의 command에 따라 chessGame에 메시지를 보내 게임을 진행할 수 있을 것 같아 적용해보았습니다 ! 
또 게임 상태에 따라 command에 대한 예외 처리를 고민하다 보니 블랙잭 미션에서 
상태 객체가 상태에 따라 행동을 결정하던 상태패턴을 적용 시킨 맥락과 비슷하다고(?) 느껴서 자연스럽게 상태패턴을 적용시키게 되었어요 ! 
command 객체는 명령에 따라 chessGame에 실행 메시지를 보내고, 
state로 chessGame의 상태를 관리해 각 명령을 실행할 수 있는지 보도록 구현해보았어요 ! 
각 패턴의 개념을 잘 적용한 것인지는 확신할 수 없지만, 
덕분에 MVC패턴에 어긋나는 도메인에서 컨트롤러를 실행시키고 있는 문제를 고칠 수 있었습니다 !

2021-03-28 09:21 UTC, NewWisdom commented on src/main/java/chess/domain/piece/King.java
> +        }
감사합니다 🙌 
십자로 이동을 진행하고, 실패하면 대각선 이동을 의도했었는데 
이번 미션에서 이런 로직들 대부분을 try catch로 분기문 처럼 사용하고 있었네요 !!
이러한 부분도 대대적인 리팩토링 안에서 없어지고, 이는 방향이 십자인지, 대각선인지를 검증(자신의 이동 규칙인지) 만 하도록 변경했습니다 !!

2021-03-28 09:32 UTC, NewWisdom commented on docs/TODO.md
> +position of랑 생성자랑 검증 유무...
엇 이 부분이 같이 올라갈지 몰랐네요 ㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎ
원래는 지금 존재하는 Empty라는 객체를 `아예 존재하지 않는 값`이라고 여기고 
이에 대한 Position 또한 존재하지 않는 EMPTY라는 값을 주었었어요(`new Position("00")`같이)

그런데 사용자의 위치 입력이 유효한 범위내의 Position인지를 정적 팩터리 메서드인 `of()`에서 검증해주는데,
EMPTY는 유효 범위에 벗어나니 이 정적 팩터리 메서드를 거치지 않고 바로 생성자로 만들어 주었는데,
유효하지 않은 값을 가진 객체의 존재 자체가 괜찮나라는 고민을 하고 있었어요 ! 
그런데 이번 리팩토링 과정에서 Empty라는 객체에게도 
Pawn이동 검증을 할 때 이동하고자 하는 위치의 Piece가 Empty인지를 확인하기 위해 아래와 같이 유효한 Position을 주면서
```java
public Piece findByPosition(Position position) {
        return pieces.stream()
                .filter(piece -> piece.isSamePosition(position))
                .findFirst()
                .orElse(new Empty(position));
    }
```
해당 위치에는 기물이 없음을 나타내도록 변경하면서 해결된 부분이에요 :)

2021-03-28 09:35 UTC, NewWisdom commented on src/main/java/chess/domain/piece/Pawn.java
> +            return;
조건문에 이동이 이뤄지는 메서드가 들어간게 어색했네요 !
해당 부분은 `moveBy~Rule()`이 아닌 각 색마다 이동할 수 있는 방향을 체크하도록 변경되었습니다 
감사합니다 :)

2021-03-28 09:53 UTC, NewWisdom commented on src/main/java/chess/domain/position/Diagonal.java
> +    }
정말 감사합니다 🥲
휴의 피드백을 받고 자신의 상태를 직접 검증하는 방법을 열심히 고민해보았습니다 !
원래는 기물 내부에서 Cross, Diagonal 객체를 통해 Pieces까지 받아서 경로를 검증했는데, 이를 외부에서 검증하고
각 기물은 자신이 이동할 수 있는 방향을 알고 있으면 어떨까를 생각해보았어요 !
그리고 위에서 언급했듯이 `기물이 제거 된 후에 piece에서 경로에 대한 검증을 해주기 때문에 만약 piece 내에서 경로 검증을 하다가 예외가 발생하면이동하지도 않았는데 target 기물이 제거되는 오류`도 이부분과 관련이 있었던 것 같아요!

그래서 이 부분을 체스 게임 내에서 이동할 수 있는 모든 방향을 가진 Direction 객체를 만들고
이 객체를 통해 이동 위치의 방향을 나타내도록 했어요 !
이 객체를 가지고 이에 대한 경로 검증은  pieces를 가진 현재 체스 게임에서 하도록 리팩토링 해보았습니다 ! 
그런데 Direction이 모든 방향을 찾아주도록 하면서 조금 길어진 것 같아 괜찮은 것인지 의문이에요

2021-03-28 10:03 UTC, NewWisdom commented on src/main/java/chess/view/OutputView.java
> +    }
이 부분은 DM으로 얘기 나누고 일단 `pieces.findByPosition(CACHE.get(xy));`로직을 객체 내로 옮겨보았습니다 !

아래 커밋과 같이 리팩토링 했는데 옳은 건지는 확신이 들지 않네요 🥲
(현재 ChessGame에 너무 많이 역할이 들어있는 것 같다고 느꼈는데, 또 분리하자니 리스트로 관리하고 있는 Pieces가 애매하네요 )
dbcf40a

2021-03-28 10:10 UTC, NewWisdom commented
안녕하세요 휴 ! 아마찌입니다 !
과제와 리팩토링 하면서 생각할 것이 많아 시간이 꽤 걸렸던 것 같아요 !!
기다리게해서 너무 죄송합니다 🥲

이번에 command가 컨트롤러를 실행 시키는 문제를 해결하고, 이동 경로 검증에 대한 문제를 고민하면서
대대적인 리팩토링이 일어났습니다 ㅎㅎㅎ
휴의 리뷰 덕분에 많은 부분을 생각해 볼 수 있었어요 !!! 

고민한 부분을 리팩토링 하고 남겨 보았는데 잘 진행된 것인지 걱정이 되네요 🥲
보시고 부족한 부분은 과감없는 피드백 부탁드리겠습니다 🔥

다시한번 리뷰에 귀한 시간 내어주셔서 정말 정말 감사드립니다 🙇‍♂️

2021-03-28 17:17 UTC, Hue9010 approved these changes
잘 반영해주셨네요. 💯 👍
이번 단계는 여기서 머지하도록 할게요.
간단한 피드백 남겼는데 다음 단계때 반영해주시면 됩니다. 😉
피드백에도 남겼지만 피드백 반영보다 웹 적용을 우선적으로 신경쓰는 걸 추천드립니다!
궁금한건 언제든 질문주세요!

2021-03-28 17:17 UTC, Hue9010 commented on src/main/java/chess/domain/command/Commands.java
> +    public static Commands validCommands() {
valid라는 이름만 봤을 때는 유효성 검사와 관련있어 보이는데 실제로는 정적 팩터리 메서드네요.

2021-03-28 17:17 UTC, Hue9010 commented on src/main/java/chess/domain/command/Commands.java
> +    public Command findCommandByText(String anotherCommandText) {
두 가지를 생각보자면
첫번째로 매번 리스트를 순회하면서 찾을 필요가 있을까요? 문제가 되는게 아니라면 최적화를 고려할 필요는 없지만 보통 학습 단계에서 리스트 위주로만 작업을하면서 무의식적으로 다른 가능성에 대해서는 고려치 않는 경향이 있어 이럴 때 Map을 고려해봐도 좋을 것 같아요. Map과 List에 대한 차이점을 간단히 찾아본다음 어떤걸 적용하는지 고민해보면 좋을 것 같아요. 😉 

두번째로 Commands를 생성해서 사용할 필요가 있을까요? 🤔

2021-03-28 17:17 UTC, Hue9010 commented on src/main/java/chess/controller/ChessController.java
> +    private final Commands commands;
Controller에 특정 상태를 두는건 좋지 않습니다. 상태를 둔다는 것 자체가 Controller가 자신의 상태를 관리해야 한다는 얘기이고, 상황에 따라서는 그에 따른 로직이 추가되기도 합니다. 이는 MVC 패턴의 Controller역할에 해당하지 않죠.
그리고 지금은 한사람만 이용하기 때문에 문제가 되지 않지만 상태에 따라서 동시성 문제가 발생할 수 있습니다. 상태라고 표현한 이유 중 하나가 필드를 아예 가지면 안되는건 아니여서 약간의 구분을 해뒀네요.

스프링 기준으로 보면 Contoller layer가 Service layer를 가지지만 Service layer도 별도의 상태를 가지지는 않습니다. Controller와 연관된 도메인과의 연결을 위해 필드를 가지고 있는 거죠. ChessGame을 Service layer로 살짝 보고 허용할 수도 있다고 보긴합니다만 4단계에선 문제가 발생하지 않더라도 5단계 DB 적용에서 혼선이 있을 겁니다. ㅎㅎ

2021-03-28 17:17 UTC, Hue9010 commented on src/main/java/chess/controller/ChessController.java
> +    }
명시적으로 종료 처리를 해야하나 생각이 들었는데 제가 데스크탑 애플리케이션이나 앱을 만든 경우가 없어 약간 고민만 하고 보류했던 사항인데 웹 애플리케이션에서는 제거해주시는게 좋습니다.
웹 애플리케이션은 한사람의 게임이 끝났다고 애플리케이션을 종료하지 않습니다. 지금과 같이 종료 코드가 존재하면 서버 하나당 한번의 게임밖에는 실행시키지 못하겠죠? 😉

2021-03-28 17:19 UTC, Hue9010 commented on src/main/java/chess/domain/position/Diagonal.java
> +    }
> Direction이 모든 방향을 찾아주도록 하면서 조금 길어진 것 같아 괜찮은 것인지

가 어떤 부분을 말씀하시는건지 확실치 않은데 좀더 자세히 알려주시면 좋을 것 같아요. 🙏
몇번 반복했지만 다음 단계는 웹 적용을 최우선적으로 신경쓰는걸 추천드립니다. 😉
특히나 피드백 반영부터 하고 웹 적용하기 보다는 웹 적용부터하고 피드백을 고려하는걸 추천해요. 이유는 뭔가 안되는게 생겼을 때 피드백 반영을하다 문제가 생긴건지 웹 적용에서 문제가 생긴건지 헤맬 가능성도 있어서 이런 가능성은 줄이시는게 좋을 것 같아요.

2021-03-28 17:21 UTC, Hue9010 commented
외부에 변하는 값이 외 람다 안에서 사용불가능한지는 람다가 함수인걸 생각해보면 좋을 것 같아요. 함수형 패러다임적 문제이기도 하죠.
(수학 공식을 생각해보면 입력값 같이 외부에서 제공되는 값 외의 요소로 결과가 바뀌지 않죠. 같은 입력엔 같은 결과가 출력되죠.)

2021-03-28 17:21 UTC, merged

2021-04-08 11:08 UTC, NewWisdom commented on src/main/java/chess/domain/ChessGame.java
> +        sourcePiece.move(target);
휴 말씀대로 일단 ui, db를 연동을 먼저 진행했어요 !

사실  휴가 아래에도 언급했듯, 
탐색에 더 적합한 map<position, piece>를 가진 board라는 객체를 만드는 방향으로 리팩토링을 해볼까 하다가,
제 로직에서는 piece가 position을 가지고 있어야 하는데, 
map의 키로 position을 두면 piece 안에서 position을 또 가지는 것이 언발란스 하더라구요.. !
제가 찾아본 list와 map의 개념을 적용한다면 map이 맞는 것 같은데 이부분은 일단 이러한 이슈(?)로 list로 관리하도록 했습니다 !
이부분에 대해 개선해야할 점이 있다면 피드백 주셔도 좋습니다 🙌

2021-04-08 11:21 UTC, NewWisdom commented on src/main/java/chess/domain/command/Commands.java
> +    public Command findCommandByText(String anotherCommandText) {
### Map과 List의 차이 

#### List

내부 구현이 배열로 되어있기 때문에 저장 공간만 마련되어 있다면 데이터의 저장 속도가 빠르다.  
또한 순차적으로 요소가 저장되므로 데이터의 순서를 보장할 때 사용하기 좋다.   
데이터를 순차적으로 받고, **특정 데이터가 아닌 원하는 데이터 범위를 순차적으로 표현할때 유리한 자료구조**

#### Map

원소를 저장할 때마다 빈 공간을 찾아서 저장하기 때문에 List 보다는 상대적으로 데이터 저장 속도가 느리다.  
ArrayList안에 원하는 데이터를 검색하는 경우에는 0번부터 해당 데이터가 있을때까지 검색을 해야하지만,   
(원하는 데이터의 index를 모르는 경우) hashMap의 경우는 **key값을 통해서 빠르게 데이터를 검색한다.** 

**Map 은빈번한 검색과, 범위데이터가 아닌 특정 데이터를 순간마다 캐치해야할 때 유리한 자료구조이다.** 

아래 커밋에 반영하였습니다 :)
6f0248b

2021-04-08 11:22 UTC, NewWisdom commented on src/main/java/chess/controller/ChessController.java
> +    private final Commands commands;
이 피드백을 기반으로 코멘트에 적은것과 같이 웹 연동에서 controller에서 상태를 가지지 않도록 구현했습니다 !

2021-04-08 15:53 UTC, Hue9010 commented on src/main/java/chess/domain/command/Commands.java
> +    public Command findCommandByText(String anotherCommandText) {
`저장 공간만 마련되어 있다면 데이터의 저장 속도가 빠르다` 리스트의 중간에 삽입하면 어떨까요? 🤔 
`원소를 저장할 때마다 빈 공간을 찾아서 저장하기 때문에 List 보다는 상대적으로 데이터 저장 속도가 느리다.`도 어떤것때문에 그렇게 생각하셨나 살짝 궁금합니다! 사실 맵보다는 set을 생각해봐야 하는 걸 수도 있겠네요. ㅎㅎ

 List 위주로만 작업하다 보면 다른 Collection을 사용할 생각을 못하게 되는 경향이 있는데 그래서 지금은 자료구조를 고민하여 구현해보는 걸로 충분히 훌륭합니다! 👍

대략적인 자료구조의 시간 복잡도정도만 알고 넘어가도 됩니다.(정확한건 면접보기 전에 외우죠. 😋) 그리고 나중에 맵에 대해 확실히 알아야 할 필요가 생긴다면 [Java HashMap은 어떻게 동작하는가?](https://d2.naver.com/helloworld/831311)를 추천 드립니다. 그러나 뒤에 자료는 한참뒤에 여유 되실 때 보시면 됩니다.(일단 어렵고 지금 직접적으로 도움될 내용이 없습니다.) 나중에 필요하다면 "d2에 map 관련 자료가 있었던거 같은데" 하면서 찾아보시면 됩니다. 😄