[1,2,3단계 - 체스] 피케이(박유진) 미션 제출합니다.
woowacourse/java-chess pull request #203
Opened 2021-03-22 09:43 UTC by pkeugine

안녕하세요 닉! 🙌
피케이입니다.

이번 체스 미션은 정말 시간 가는줄 모르고 진행했네요.
마음에 드는 코드를 만들고 싶은 마음과 시간을 지켜야한다는 생각이 계속해서 충돌하는 한 주였어요. 😅

코드가 깔끔하지는 않지만, 체스에 필요한 기능은 잘 돌아가고 있습니다.
현재 리팩토링을 하고 있는데, 리팩토링을 하며 생긴 새로운 클래스 때문에 리뷰하시기 힘들 것 같아요.

그래서 현재 프로그램에서 사용하고 있는 클래스를 정리해봤습니다 (테스트는 다 쓰이고 있어요!):
```
controller
         - ChessController
domain
         - Board
         - BoardFactory
         - Path
         - Paths
         - Game
         - piece 패키지 : MoveUnit, Piece2, EmptyPiece를 제외한 모든 클래스
         - Player
         - Players
         - Column
         - Row
         - Position
         - Result
         - Score
         - Command
util
         - RenderingUtils
view
         - InputView
         - OutputView
그 외 : Application
```

계속해서 리팩토링 진행하며 궁금한 내용이 있으면 DM 보내겠습니다!

2021-03-23 09:19 UTC, wbluke requested changes
안녕하세요 피케이!
코멘트에도 남겼지만, 리팩토링 중인 코드들은 별도 브랜치에서 진행하는 연습을 해보길 바라요 ㅎㅎ (리뷰하기가 꽤 어렵네요)
수정 후 재요청 부탁드려요 🙂

2021-03-23 09:19 UTC, wbluke commented on src/main/java/chess/domain/board/Board.java
> +        paths = paths.findAllPath(piece, coordinates.get(piece));
빈 Paths를 만들고 자기 자신에게서 나온 반환값으로 다시 자신의 참조를 변경하는데요. 이상하지 않으신가요? :)

2021-03-23 09:19 UTC, wbluke commented on src/main/java/chess/domain/board/Paths.java
> +    public Path removeObstacles(Piece piece, Board board) {
장애물을 제거하는 기능인데, Paths로부터 Path가 반환이 되네요.
메서드가 두가지 기능을 하고 있는 듯 보여요!

2021-03-23 09:19 UTC, wbluke commented on src/main/java/chess/domain/board/Path.java
> +    public boolean isAble(Position position) {
메서드명이 조금 모호하네요. 어떤게 가능하다는 의미일지 나타내주시면 좋을 듯 해요 :)

2021-03-23 09:19 UTC, wbluke commented on src/main/java/chess/domain/board/Path.java
> +    }
depth가 꽤 깊은데요, 메서드 분리로 개선해볼 수는 없을까요?
요구사항은 1 depth가 원칙입니다!

2021-03-23 09:19 UTC, wbluke commented on src/main/java/chess/domain/result/Result.java
> +                .map(piece -> piece.score())
```suggestion
                .map(Piece::score)
```

2021-03-23 09:19 UTC, wbluke commented on src/main/java/chess/domain/result/Result.java
> +        return new Score(sum);
- 매직넘버가 많네요!
- 어떤 흐름인지 단번에 파악이 되지 않아요. 메서드로 의미를 부여하고 depth를 줄여볼 수 있을까요?

2021-03-26 00:02 UTC, pkeugine commented
# 피케이 학습로그

## [OOP] 상태 패턴 적용 - 6
### 내용

### 링크

## [OOP] 객체 불변으로 변경 - 8
### 내용

###링크

## [OOP] 전략 패턴 적용 - 8
### 내용

### 링크

2021-03-31 03:43 UTC, wbluke approved these changes
구조가 정말 많이 달라졌네요! 개선하느라 고생 많으셨습니다 👏 
소소한 피드백 남겼으니 참고해주시고, 다음 단계 진행해주세요~!

2021-03-31 03:43 UTC, merged