[1,2,3단계 - 체스] 현구막(최현구) 미션 제출합니다.
woowacourse/java-chess pull request #207
Opened 2021-03-22 10:16 UTC by Hyeon9mak

안녕하세요 닉! 현구막입니다!! 
제출 마감에 쫒겨서 진행하다보니 유닛테스트를 빼먹은 곳도 많고, 일급 컬렉션으로 만들 수 있는 부분도 많이 빠뜨린 것 같아요..
우선 제출부터(😢) 하고 닉이 주시는 피드백과 함께 리팩토링 진행해볼게요!

미션을 진행하면서 궁금한 부분이 몇 가지 있었어요!

<br>

## InitBoardGenerator의 역할을 InitPieces에 통합하는게 어떨까요?
현재 보드 초기상태를 제공하는 제네레이터 클래스가 존재하고 있어요. 얼마전 포비의 엘레강트 오브젝트 수업을 들으면서 `-er` 명명이 붙는 클래스를 지양하라는 말을 들었는데, 이 클래스를 없애려면 InitPieces 라는 클래스에 통합시키는게 나을지, 아니면 현재 상태를 유지하는게 좋을지 고민 중이에요. 닉이 보기엔 어떠신가요?

## Controller 는 지나치게 많은 일을 하는 것 같고, ChessGame은 지나치게 하는 일이 단순한 것 같아요..
블랙잭 미션을 하면서도 비슷한 일을 겪었는데, View와 지속적인 대화를 하기 위해서 Controller가 비대해지고, ChessGame은 원시적인 
명령만 전달받는 형태로 프로그래밍이 되었어요. 마냥 나쁘다고 하기엔 View와 지속적인 대화를 잇기 위해 어쩔수 없는건가 생각도 들고...
잘못된거면 확 잘못됐다는 확신을 얻고 싶어요!!

## Command 안에 ChessGame을, ChessGame 안에 State를, State안에 Board
메세지가 일렬로 전달되도록 구현하는 것을 목표로 했는데, 결국 중간중간에 다른 객체들과 메세지 방향이 뒤섞인 것 같아요 😢 
더 좋은 구상 방법이 있었을까 여전히 고민이 되는데, 힌트를 얻을 수 있을까요?!

감사합니다!

2021-03-23 13:28 UTC, wbluke requested changes
안녕하세요 현구막!
체스에서 상태 패턴 적용하신게 인상적이네요 👍 
질문 주신 내용 포함하여 코멘트 남겼으니 확인 후 재요청 부탁드려요 🙂

2021-03-23 13:28 UTC, wbluke commented on src/main/java/chess/domain/board/Board.java
> +                .orElseThrow(IllegalArgumentException::new);
예외를 던질 때 항상 예외 메시지도 같이 던지면 좋습니다 :)
애플리케이션에서 예외 발생 시 빠르게 어느 지점인지 트래킹할 수 있다는 장점도 있어서요 ㅎㅎ
(전체적으로 한번 체크해보셔요 ㅎㅎ)

2021-03-23 13:28 UTC, wbluke commented on src/main/java/chess/domain/game/state/BlackTurn.java
> +                    Color.BLACK.name() + "턴엔 " + Color.BLACK.name() + "말만 이동 가능합니다."
String.format 사용하면 한눈에 알아보기 쉬울 듯 해요 :)

2021-03-23 13:28 UTC, wbluke commented on src/main/java/chess/domain/board/Board.java
> +    private Boolean isNotMovablePosition(Position source, Position target) {
반환값이 primitive 타입이면 좋을 것 같아요 :)

2021-03-23 13:28 UTC, wbluke commented on src/main/java/chess/domain/board/Board.java
> +        Set<Position> movablePath = moveStrategy.moveStrategy(this, source);
더 나은 메서드명은 없을까요? :)

2021-03-23 13:28 UTC, wbluke commented on src/main/java/chess/domain/movestrategy/PawnMoveStrategy.java
> +        if (!board.pieceOfPosition(positions.get(0)).isEmpty()) {
- 부정연산자(!)는 가독성을 떨어뜨리고 실수를 유발할 여지도 주기 때문에, 반대 의미의 메서드를 만들어서 제공 및 사용하는 것이 좋습니다 :)
- 디미터법칙을 위반하지 않도록 해주세요 ㅎㅎ

애플리케이션 전체적으로 한번 체크해주세요 ㅎㅎ

2021-03-23 13:28 UTC, wbluke commented on src/main/java/chess/utils/ScoreCalculator.java
> +public class ScoreCalculator {
OOP에서 정적클래스는 기본적으로 안티패턴이어서요.
유틸성 클래스가 아니면서, 인스턴스를 만들어서 관리할 수 있다면 그렇게 하는 것이 좋습니다 :)

2021-03-23 13:28 UTC, wbluke commented on src/main/java/chess/utils/ScoreCalculator.java
> +            return countOfPawnsInVertical * 0.5;
매직넘버!

2021-03-25 00:30 UTC, Hyeon9mak commented on src/main/java/chess/domain/board/Board.java
> +    private final List<Map<Position, Piece>> squares;
일급 컬렉션으로 만들 수 있을 것 같아요!!

2021-03-25 08:01 UTC, Hyeon9mak commented on src/main/java/chess/domain/board/Board.java
> +                .orElseThrow(IllegalArgumentException::new);
메서드 참조로 줄여진 것만 사용했지, 함수형 인터페이스 상태로 메세지를 전달할 방법은 생각 못했네요!! 감사합니다!!!!!

2021-03-25 09:12 UTC, Hyeon9mak commented on src/main/java/chess/domain/board/Board.java
> +    private Boolean isNotMovablePosition(Position source, Position target) {
헉.. 너무 급했네요 😭

2021-03-26 08:41 UTC, Hyeon9mak commented on src/main/java/chess/domain/board/Board.java
> +        Set<Position> movablePath = moveStrategy.moveStrategy(this, source);
바로 위에 있는 메서드에서 `valid`라는 표현을 사용해서, 이 메서드도 `isInvalid` 표현을 사용하게 바꿨어요! 👍

2021-03-26 09:27 UTC, Hyeon9mak commented on src/main/java/chess/utils/ScoreCalculator.java
> +public class ScoreCalculator {
점수 한 번 계산하고 할 일이 없는 인스턴스라 생각해서 유틸 클래스로 만들었네요 😢 변경하겠습니다!

2021-03-26 13:58 UTC, Hyeon9mak commented on src/main/java/chess/controller/ChessGameController.java
> +public class ChessGameController {
> BiFunction 에 반환 값으로 Dto 를 넘기게 할까 생각중인데, 2가지 고민점이 따라오는 것 같아요.
> 
> - Enum 클래스가 DtoAssembler의 존재를 알게 된다.
> - Dto의 종류가 다양해서, 인터페이스로 추상화시켜야한다.
> 
> 이전 미션에서 리뷰를 받을 때 도메인이 Dto 관련 로직을 알아선 안된다고 배웠어요. 따라서 DtoAssembler의 존재도 몰라야하는게 아닌지 고민이 되네요…
> 여러 종류의 Dto들을 인터페이스로 추상화시키는 것도 출력만을 위한 오버엔지니어링이 아닌가 고민되고 있어요..

DM으로 질문드렸던대로 결국 커맨드 패턴을 유지하기로 결정했어요 😢

2021-03-26 17:38 UTC, Hyeon9mak commented
안녕하세요 닉!! 피드백 주신 내용 반영이 많이 늦었습니다 😭 

상태패턴에 빠뜨렸던 테스트들을 추가했고, 유틸클래스를 제거하는 등
전반적으로 완성도가 떨어지는 부분들을 다듬는 것에 집중했어요!

Command에 대해 Enum으로 변경을 시도하다가, 각 Command 별 반환이 서로 달라서
(특히 Move의 체스판 반환, Status의 점수 반환 등) 결국 커맨드 패턴을 그대로 유지하게 됐네요.
조금 아쉽지만, 그래도 닉이 주신 힌트 덕분에 BiFunction에 대해서도 공부할 수 있었어요!!

감사합니다!

2021-03-27 12:24 UTC, wbluke approved these changes
안녕하세요 현구막! 피드백 반영 고생하셨습니다 ㅎㅎ
조금 더 피드백 남겼는데요, 다음 단계 진행하시면서 같이 참고해주세요 ! 🙂

2021-03-27 12:24 UTC, wbluke commented on src/main/java/chess/domain/movestrategy/MoveStrategy.java
> +    Set<Position> moveStrategy(Board board, Position source);
> 더 나은 메서드명은 없을까요? :)
> 
> @Hyeon9mak Author
바로 위에 있는 메서드에서 valid라는 표현을 사용해서, 이 메서드도 isInvalid 표현을 사용하게 바꿨어요! 👍

앗, 아뇨 저는 Board에 있는 메서드가 아니라 moveStrategy에 대한 피드백이었는데, 착오가 있었네요.
제가 여기다가 코멘트를 남길걸 그랬나봐요 😢

2021-03-27 12:24 UTC, wbluke commented on src/main/java/chess/domain/game/ScoreCalculator.java
> +    }
음 세 메서드 모두 가공이 상당히 복잡한데요.
일부분은 Rank에서 담당해줄 수 있는 로직도 있지 않을까요? :)

2021-03-27 12:24 UTC, wbluke commented on src/main/java/chess/domain/game/ScoreCalculator.java
> +public class ScoreCalculator {
점수 계산도 중요한 도메인 로직인데, 테스트를 통한 검증이 필수일 것 같아요 :)

2021-03-27 12:24 UTC, wbluke commented on src/main/java/chess/domain/board/Rank.java
> +        return this.squares;
일급컬렉션에서는 담당한 컬렉션을 외부로 반환해야할 때, 외부에서 조작할 수 있으므로 항상 주의해야 합니다.
- 반환하지 않을 수 있다면 가장 Best
- 반환해야만 한다면 불변으로, 혹은 현재 필드와 관계없는 새로운 컬렉션으로 만들어서 반환

2021-03-27 12:25 UTC, merged

2021-03-28 03:14 UTC, Hyeon9mak commented
# [OOP] 커맨드 패턴 - 5
## 내용
- 커맨드패턴에 대한 학습 진행 후 체스게임의 명령어 `start`, `move`, `status`, `end`에 커맨드 패턴을 적용함
## 링크
- https://gmlwjd9405.github.io/2018/07/07/command-pattern.html
- https://github.com/Hyeon9mak/java-chess/commit/afb789dfe72eeb829e3ba5b411a5242dde4bc725

# [JDK] flatMap - 3
## 내용
- 페어 에드로부터 Stream API의 flatMap 메서드에 대해 배운 후 체스미션에 전반적으로 적용함
## 링크
- https://github.com/Hyeon9mak/java-chess/commit/971c7eb1607b18a53ddf9a5827b651d5e6fa045a

2021-03-28 03:19 UTC, Hyeon9mak commented on src/main/java/chess/domain/movestrategy/MoveStrategy.java
> +    Set<Position> moveStrategy(Board board, Position source);
😱 현재 source 좌표에서 이동좌표를 구하는 것이니까, `currentPositionMoveStrategy`로 변경했어요!

2021-03-28 03:20 UTC, Hyeon9mak commented on src/main/java/chess/domain/game/ScoreCalculator.java
> +public class ScoreCalculator {
👍 헉... 당장 추가하겠습니다!

2021-03-28 03:21 UTC, Hyeon9mak commented on src/main/java/chess/domain/board/Rank.java
> +        return this.squares;
일급컬렉션을 일급컬렉션답게 사용하지 못하고 있었네요 😢 
`squares`를 요청하는 곳에서 `Rank`에게 메세지를 보낼 수 있는 방법에 대해 고민해보고 적용해보겠습니다!

2021-03-28 03:22 UTC, Hyeon9mak commented on src/main/java/chess/domain/game/ScoreCalculator.java
> +    }
이것도 역시 일급컬렉션을 일급컬렉션 답게 사용하지 못한거 같네요!!