[1,2,3단계 - 체스] 춘식(안예장) 미션 제출합니다.
woowacourse/java-chess pull request #209
Opened 2021-03-22 10:28 UTC by RinSabbit

안녕하세요 휴!!
1단계 마지막 미션을 함께하게 되었네요. 미션 기간 동안 잘 부탁드립니다!! 🙏 

이번 미션은 유독 어렵게 느껴져서 시간이 오래 걸린 것 같네요ㅠㅠ
그래도 페어랑 많은 얘기를 나누면서 새로 배우게 된 점이 많아 즐거웠습니다. 😄 

미션을 진행하면서 신경을 많이 부분은 움직이기로 한 말이 갈 수 있는 곳을 가지는 Path 객체예요.
시중의 체스 게임들에서 말을 클릭하면 갈 수 있는 경로가 모두 보인다는 점에 착안해
갈 수 있는 위치를 모두 가진 Path를 만들고, target이 갈 수 있는지 확인하는 방식으로 체스말 이동 기능을 구현했습니다.
가야 하는 모든 위치의 유효성을 확인하는 부분이 어려워 여기서 시간을 많이 쏟은 것 같아요.

궁금한 점은 Command에 관한 것인데, 초반엔 도메인 패키지에 속하는 enum 클래스로 어떤 명령인지만 확인하는 정도로만 구현했습니다.
이 상황에서 구현을 하다보니 Game에서 하나하나 체크해 수행을 하는 상황이 생겨 수행을 하는 부분도 Command 클래스로 옮겼습니다.
그 결과 Command에서 View도 쓰이고 다른 도메인 객체들도 사용하는 것 같아 Controller 패키지로 옮겼는데 이렇게 구현해도 되는 지 의문이 조금 듭니다.
더 좋은 방법이 있다면 부담없이 알려주세요!!! 피드백으로 마구 썰어주시면 감사하겠습니다 🤣 

(+) 아직 리팩토링 중인지라 PR이후에도 커밋이 더 올라갈 것 같습니다. 도중에 궁금한 점이 생긴다면 DM 드리겠습니다!!

2021-03-23 21:43 UTC, Hue9010 requested changes
춘식 반가워요! 이번 리뷰를 맡은 휴입니다! 😄 
리뷰가 생각보다 늦어진 점 죄송합니다. 😭 🙏
질문에 대한 답변과 개선하면 좋을 부분 피드백 남겼는데 궁금한건 언제든 질문 주세요!

2021-03-23 21:43 UTC, Hue9010 commented on src/main/java/chess/domain/board/Path.java
> +        return cleanPath;
calculatePawnPath, calculateNonePawnPath에서 cleanPath를 조작하는데 지금과 같은 사용성이라면 calculateXX에서 List를 바로 반환해줄 수 있을 것 같네요.

2021-03-23 21:43 UTC, Hue9010 commented on src/main/java/chess/domain/board/Board.java
> +        return paths.removeObstacles(piece, this);
Paths의 활용도가 굉장히 떨어지는데 여러개의 Path를 가지는 Paths가 필요한가 싶네요. 🤔

2021-03-23 21:43 UTC, Hue9010 commented on src/main/java/chess/domain/board/Board.java
> +        return paths.removeObstacles(piece, this);
> Path와 Paths에서 맡는 역할이 너무 큰 것 같아서 분리를 하면 좋을 것 같은데 어떻게 해야 할 지 막막하네요.

Path를 `보드 상황까지 고려하여 이동 가능한 경로`와 `보드 상황과는 무관하게 이동 가능한 경로` 중 어느 역할로 생각하셨는지에 따라 다를 것 같아요. 전자가 맞다면 책임자체는 크지 않아보입니다. 후자라면 역할을 벗어난 보드 상황에 맞춰 이동가능한지 확인하는 책임을 가지고 있는걸로 보여요.(isAble)

역할이 너무 큰 것 같다. 라고만 하셔서 우선은 이정도가 될 것 같아요. 역할이 크다고 생각하기 전에 우선 어떤 역할을 담당하는지 좀더 명확히 해본다음 그 역할을 벗어나는 책임을 가지고 있는지 보는게 좋아요.
전체적으로 봤을 때 Paths의 존재로 인해서 균형이 깨진 것 같아요. 그런 점에서 Paths가 어떤 역할과 책임을 가지는지 한번 정리해보는게 좋을 것 같아요. 제가 생각치 못한 요소를 고려하셨을 수도 있기 때문에 꼭 Paths가 제거되어야 할 존재인건 아닌 점 참고 부탁드려요! 😉

2021-03-23 21:43 UTC, Hue9010 commented on src/main/java/chess/domain/position/Column.java
> +        return false;
조건문으로 분기를 타지 말고 Direction을 통한 다형성을 제공해줄 수 있지 않을까요? 🤔

2021-03-23 21:43 UTC, Hue9010 commented on src/main/java/chess/domain/board/Paths.java
> +        return new Paths(piece.directions().stream()
directions을 외부에 노출 시키기보다는 piece한테 메시지를 보내서 Path를 찾을 수 있을 것 같네요. 그렇게 된다면 findPathInDirection에 있는 조건문도 해결 할 수 있을 것 같네요. 🤔

2021-03-23 21:43 UTC, Hue9010 commented on README.md
> +## 체스
왠지모르게 `move a2 a3`로 이동하면 존재하지 않는 열이라고 뜨네요. a쪽은 모두 동일합니다. 😢
c2에 있던 폰을 열심히 움직여서 8행으로 이동하려고 할때는 존재하지 않는 행이라고 나옵니다.(빠르게 왕을 잡으려고 단순 무식하게 옮겨서 이건 제가 체스 규칙을 모르고서 실수한 걸 수도 있을 것 같네요 🙄)
이 두가지 확인 부탁드려요!

2021-03-25 02:10 UTC, RinSabbit commented on src/test/java/chess/domain/result/ResultTest.java
> +        board.putPiece(new WhitePawn(), Position.of("a1"));
테스트 수정했습니다! 리팩토링 하면서 주기적으로 테스트를 돌려봐야겠네요. 감사합니다!! 🙏

2021-03-25 02:16 UTC, RinSabbit commented on src/main/java/chess/domain/Game.java
> +            throw new IllegalArgumentException(INVALID_SOURCE_ERROR_MESSAGE);
앗 저도 사실 모든 문자열은 상수화하래서 포장을 하긴 했는데 이런 것까지 상수화를 해야 하나 싶었어요ㅎㅎ
그런데 만약 나중에 게임이나 서비스를 개발할 때 사용하는 유저가 많아지는 경우를 고려한다면 상수화를 해야 하는게 좋지 않을까요? 🤔 
실사용되는 서비스 개발을 해본 적이 없어서 잘 모르겠는데, 휴의 의견이 궁금해요!

2021-03-25 02:23 UTC, RinSabbit commented on src/main/java/chess/domain/piece/Pawn.java
> +        if (from.isBlackPawnStartLine() || from.isWhitePawnStartLine()) {
Pawn이 필드 변수로 boolean isFirstMove를 가지라는 뜻일까요?! 아니면 Position에 isFirstMove 라는 메소드를 만들어 메세지를 보내라는 뜻일까요!! :3

2021-03-25 04:41 UTC, RinSabbit commented on README.md
> +## 체스
제가 Direction에서 leftDirection에 잘못된 Direction을 넣어놨었네요ㅠㅠ 수정했습니다!! 버그 알려주셔서 감사합니다ㅠㅠㅠ

2021-03-25 06:41 UTC, RinSabbit commented on src/main/java/chess/domain/board/Paths.java
> +        return new Paths(piece.directions().stream()
findAllPath를 Piece로 옮기면서 Piece를 상속받는 추상 클래스를 Unlimit/Limit로 나눠 만들었어요!! 확실히 코드가 더 깔끔해진 거 같아요!! 👍 👍

2021-03-25 06:48 UTC, RinSabbit commented on src/main/java/chess/domain/board/Path.java
> +        return cleanPath;
```java
    public List<Position> removeObstacleInPath(Piece piece, Board board) {
        if (piece.isPawn()) {
            Pawn pawn = (Pawn) piece;
            return calculatePawnPath(pawn, board);
        }
        return calculateNonePawnPath(piece, board);
    }
```
이런 식으로 수정했습니다!! 💪

2021-03-25 08:39 UTC, RinSabbit commented on src/main/java/chess/domain/position/Column.java
> +        return false;
고민을 해보다가 다형성 대신 IsInRange 라는 메소드를 만들어 가려는 좌표가 열거 상수들 범위 내에 있는지 확인하는 식으로 리팩토링했습니다!!

2021-03-25 08:44 UTC, RinSabbit commented on src/main/java/chess/domain/Game.java
> +    private void validateKingAlive() {
refreshState로 메소드명 변경했습니다!!

2021-03-25 09:31 UTC, RinSabbit commented on src/main/java/chess/domain/board/Board.java
> +        return paths.removeObstacles(piece, this);
Path는 전자로 생각한 것이 맞습니다. 리팩토링하다보니 Piece에서 Path를 생성할 때 매핑을 두 번 하는 방법으로 Paths를 사용하지 않을 수있게 되어서 Paths를 삭제했습니다!! 💃

2021-03-25 15:59 UTC, RinSabbit commented on src/main/java/chess/controller/Command.java
> +        OutputView.printTurn(game.getTurn());
하지만 game에게 역할 수행을 부여하려면
1) Consumer를 통해 Game에 static 메소드를 수행하도록 하거나
2) Game에서 if문을 이용해서 하나하나 체크하는 방식으로 구현해야 하지 않나요?
저는 Game이 static을 가지는 것보단 enum인 Command가 static 메소드를 가지고 있는게 낫나고 생각했거든요. 🤔 
Command의 역할은 서브 컨트롤러(?) 같은 느낌으로 정의해서 후자에 가깝지 않을까..! 합니다. 😇 
다른 크루들 코드를 보니 커맨드 패턴을 쓰는 분들도 계셔서 어떻게 리팩토링할지 고민이에요.
그런 점에서 휴가 권장하는 리팩토링 방식이 궁금합니다..!

2021-03-25 16:25 UTC, Hue9010 commented on src/main/java/chess/domain/Game.java
> +            throw new IllegalArgumentException(INVALID_SOURCE_ERROR_MESSAGE);
```
맹목적인 어리석음(blind stupidity)을 비롯한 다른 어떤 이유보다도, 효율성이라는 이름으로 저질러지는 죄악이 더 많다(효율성을 반드시 성취하는 것도 아니면서 말이다).
- 윌리엄 울프(William A. Wulf)

작은 효율성(small effiency)에 대해서는, 말하자면 97% 정도에 대해서는, 잊어버려라. 섣부른 최적화는 모든 악의 근원이다.
- 도널드 커누스(Donald E. Knuth)

최적화를 할 때는 아래의 두 규칙을 따르라.
규칙1: 하지마라
규칙2: (전문가들만 따를 것) 아직은 하지마라 - 완벽히 명료한, 최적화되지 않은 해답을 얻을 때까지는.
- M. A. 잭슨(M. A. Jackson)
```
[[이펙티브 자바] 규칙55. 신중하게 최적화하라](https://itstory.tk/entry/이펙티브-자바-규칙55-신중하게-최적화하라)

`유저가 많아지는 경우를 고려한다면 상수화를 해야 하는게 좋지 않을까요?`가 여기서 말하는 최적화가 아닐까요?
덤으로 이김에 String pool에 대해서 가볍게 봐두는 것도 좋을 것 같아요. 😉

2021-03-25 16:26 UTC, Hue9010 commented on src/main/java/chess/domain/piece/Pawn.java
> +        if (from.isBlackPawnStartLine() || from.isWhitePawnStartLine()) {
전자를 생각하고 말한건데 제가 언급드린 방법이 더 낫다는 아닌거라 한번쯤 생각해보는 걸로도 충분합니다. 😄

2021-03-25 16:43 UTC, Hue9010 commented on src/main/java/chess/controller/Command.java
> +        OutputView.printTurn(game.getTurn());
큰 방향만 보고 말씀드려서 실제 구현까지 세세하게 고려하진 못해서 두번째의 조건문이 얼마나 생길지는 확실치 않네요.
사실 지금의 Command를 조금만 바꾼다면 커맨드 패턴이 될 것 같아요. BiConsumer로 가지고 있던 메서드를 각 커맨드를 만들고 가지게 하면 되지 않을까요? 🤔 

지금의 가장 큰 문제는 위에서 말씀드린 것 처럼 Command에 View가 존재하는 것 입니다. 서브 컨트롤러 느낌이라고 하셨는데.. 결국엔 그만큼 MVC에서 멀어지죠..  😢

2번의 Game에 if문이 많아지는 걸 고민하셨는데 한가지 놓치고 있으신게 Game만 신경쓸게 아니라 ChessController에도 코드가 추가되어야 할겁니다.(아마도 조건문도)

제가 생각한 방향은 기본적으로 아래와 같았습니다.
- View는 모두 Controller로 옮기고 아마도 Command에 따른 일부 조건문 추가
- 지금 만든 Command는 커맨드 패턴에 가까운 상태로 보여 커맨드 패턴 적용
- Game은 크게 바뀔게 없을 걸로 예상

우선은 View를 Controller로 어떻게 빼는 것부터 고민해보고 완료 된 다음 그 외에는 굳이(?) 리팩토링을 할 필요가 없을 수도 있습니다.
View를 Command에서 빼는건 MVC에 대한 이유도 있지만 좀더 직접적인 이유는 제가 spark를 크게 다뤄보지 않아 스프링 기준으로 말씀드리면 MVC가 강제 되기 때문에 웹 적용을 할 때 지금처럼 Controller가 아닌 곳에서 View에 접근을 하게 되면 엄청난 난관을 겪게 되실 겁니다. 😢

2021-03-26 04:21 UTC, RinSabbit commented on src/main/java/chess/domain/Game.java
> +            throw new IllegalArgumentException(INVALID_SOURCE_ERROR_MESSAGE);
> 최적화를 할 때는 아래의 두 규칙을 따르라.
> 규칙 1 : 하지 마라.

임팩트 있는 인용이네요 🤣 🤣 참고하겠습니다!! 학습 로그 남길 때 공부해서 가볍게 정리해보겠습니다 🔥

2021-03-26 07:14 UTC, RinSabbit commented on src/main/java/chess/controller/Command.java
> +        OutputView.printTurn(game.getTurn());
조언 감사합니다!! 커맨드 패턴을 이용하여 리팩토링 해봤는데 생각보다 잘 되어서 깜짝 놀랐어요. 처음부터 커맨드 패턴을 적용하려고 했을 땐 감이 잡히지 않았는데 enum으로 기능을 전부 구현하고 보니 공통점이 보여서 좀 더 수월하게 리팩토링을 할 수 있었던 것 같아요. 아쉬운 점은 StatusCommand의 오버라이드 메소드 execute가 아무런 일도 하지 않고 있다는 점입니다. 좀 더 공부해보겠습니다... 🤯

2021-03-26 07:14 UTC, RinSabbit commented on src/main/java/chess/domain/piece/Pawn.java
> +        if (from.isBlackPawnStartLine() || from.isWhitePawnStartLine()) {
생각을 해봤는데... 저는 이대로 가는 게 더 좋다고 느껴져서ㅎㅎ 유지하겠습니다 💦

2021-03-26 07:21 UTC, RinSabbit commented
안녕하세요 휴!!
피드백 반영해서 리팩토링 해봤습니다.
크게 바뀐 점은 다음과 같아요.

- 커맨드 패턴 적용
    - Controller에서만 View가 쓰이도록 함
    - 기존의 Command(현 Commands)는 찾는 Command를 반환하도록 함
- Path의 역할 명시화
    - Piece에서 Path의 경로를 계산하도록 함
    - Paths 삭제
    - 특정 체스말끼리의 공통점을 찾아 Piece를 상속받는 Umlimited / Limited 추상 클래스 생성. 
    체스말들은 해당하는 추상 클래스를 상속받도록 변경

이번 리팩토링은 많이 힘들었지만 🤣 그만큼 많이 배우게 된 것 같아 뿌듯합니다.
늦은 시간에 디엠 드렸는데도 친절하게 답변 주셔서 너무 감사해요 👍 👍 
더 피드백 주실 부분이 있다면 매우 환영입니다!!!

2021-03-27 14:50 UTC, Hue9010 approved these changes
고민하시던 부분 걱정하시던 것과 다르게 잘해주셨네요. 😄 👍👍
이번 단계는 여기서 머지하도록 할게요.
이번엔 크게 피드백 드릴 부분이 없었는데 궁금한건 언제든 질문 주세요. 😉

2021-03-27 14:59 UTC, Hue9010 commented on src/main/java/chess/controller/Command.java
> +        OutputView.printTurn(game.getTurn());
각 Command마다 다른 행동을 할 수 있으니까 아무 일도 하지 않는 것도 다형성으로 볼 수 있을 것 같아요.
처음에는 잘 안됐다가 이번에 생각보다 쉽게 되신 이유는 처음부터 적용하려고 할 때는 기능 구현도 신경쓰면서 패턴을 적용하고자 하니까 

원래 처음부터 적용할 때 쉽게 되면 문제 없지만 잘 안풀리면 기능 구현도 하고 패턴도 적용해야하는데... 하면서 마음의 여유도 없어져서 더 힘들게 느껴지는 법입니다. 그래서 가능하면 기능 구현 먼저 완료 한 다음 패턴을 적용해보는 걸 추천드려요.
그랬을 때의 장점은 패턴 적용이 잘 안풀리면 여차하면 이전 커밋으로 돌아가서 pr을 보낼 수 있죠. 그래서 마음의 여유도 더 있는 상태서 패턴만 고민 할 수 있다는 장점이 있습니다.
이는 패턴만 해당하는게 아니라 과제를 진행하면서 추가로 학습하고자 하는 모든 것에 적용할 수 있어요. 앞서 말씀 드린 것 처럼 처음부터 적용이 잘 풀리면 이렇게 나눠서 했을 때 시간만 더 걸리게 되지만 잘 안풀렸을 때는 나눠서 하는게 시간도 덜 걸릴겁니다. 사실 그것보다는 좀더 편한 마음에서 진행하실 수 있을 겁니다. 😉

그래서 다음 단계 때 웹 적용에 있어서 좋은 구조나 객체지향을 지나치게 신경 쓰기보다는 웹 적용을 우선적으로 생각하고 그 이후 리팩토링 하는걸 추천드려요. 다음 단계는 무엇보다 웹 적용을 경험해보는게 핵심이라고 생각해요.😋

2021-03-27 14:59 UTC, merged