[4, 5단계 - 체스] 알리(허진호) 미션 제출합니다.
woowacourse/java-chess pull request #231
Opened 2021-04-02 09:59 UTC by jh8579

안녕하세요 알리입니다.
매우 간단한 로그인을 위해서 쿠키도 한번 사용해보고,
여러가지 시도를 해보긴 했는데 좋은 코드인지는 확인이 안드네요....
피드백 받고 더 좋은 코드로 만들어보고 싶습니다.
감사합니다.

2021-04-03 13:14 UTC, JunHoPark93 requested changes
안녕하세요 알리! 제이입니다.
미션 구현하느라 고생많으셨어요 🙇‍♂️
몇가지 피드백 남겼는데 확인해보시고 궁금한점 남겨주세요 🙏

2021-04-03 13:14 UTC, JunHoPark93 commented on src/main/java/chess/domain/web/GameHistory.java
> +    private int gameHistoryId;
여기도 사용처에서는 id로 사용이 되고있어요. 네이밍도 id로만 해도 충분할거같아요! 이미 클래스에서 의미가 드러나니까요

2021-04-03 13:14 UTC, JunHoPark93 commented on src/main/java/chess/service/ChessService.java
> +        return gameDao.findRunningGamesByUserId(userId)
없으면 빈 리스트로 나올거같은데 프런트에서 빈 값으로 나오게 되는것도 고려하신거죠?

2021-04-03 13:14 UTC, JunHoPark93 commented on src/main/java/chess/controller/WebController.java
> +        int currentUser = userService.findUserIdByName(user);
개선해볼수있는 포인트는 쿠키에 userId를 담는다면 불필요한 디비 통신을 한번 없앨수있을거같아요.
구조가 안전한 구조는 아니지만 보안을 제외하고는 개선해볼 수 있는 포인트라 남겼습니다!
질문주신 쿠키사용 관련한 자세한 피드백은 상단에 남겨두었어요.

2021-04-03 13:14 UTC, JunHoPark93 commented on src/main/java/chess/service/ChessService.java
> +    private final GameDao gameDao;
서비스도 만들어주셨네요!
요구사항엔 없었던거같은데 구현을 해주셔서 [키워드](https://ko.wikipedia.org/wiki/%EC%9D%98%EC%A1%B4%EA%B4%80%EA%B3%84_%EC%97%AD%EC%A0%84_%EC%9B%90%EC%B9%99)를 하나 남겨드릴게요!
한번 고민해보시고 알리가 만들어주신 서비스가 특정구현체에 의존을 하는것인지 생각해보셔요 🙏

2021-04-03 13:14 UTC, JunHoPark93 commented on src/main/java/chess/util/Database.java
> +        return con;
커넥션을 제대로 획득하지 않은 상태에서 return이 될 수 있을거같아요. catch내부에서 적절히 처리를 해주면 좋지않을까요? (에러를 뱉고 종료 등..)

2021-04-06 17:14 UTC, jh8579 commented on src/main/java/chess/service/UserService.java
> +        return userDao.findByName(name);
Optional을 사용해서 DB 결과와 cookie에 대한 null 처리 로직에 사용해봤습니다.

2021-04-06 17:18 UTC, jh8579 commented on src/main/java/chess/domain/web/GameHistory.java
> +    private int gameHistoryId;
id로 수정했습니다!

2021-04-06 17:20 UTC, jh8579 commented on src/main/java/chess/controller/WebController.java
> +        int currentUser = userService.findUserIdByName(user);
로그인 시에 db에 새로 추가된 사용자의 auto-generated id를 가져오는 로직을 추가해서
쿠키로 사용자 id를 사용하도록 수정했습니다!

2021-04-06 17:29 UTC, jh8579 commented on src/main/java/chess/util/Database.java
> +        return con;
catch문에서 에러를 던지고 종료하도록 수정했습니다

2021-04-06 17:29 UTC, jh8579 commented on src/main/java/chess/service/ChessService.java
> +        return gameDao.findRunningGamesByUserId(userId)
없는 경우에는 프론트에서 표시하지 않도록 처리했습니다.

2021-04-06 17:30 UTC, jh8579 commented on src/main/java/chess/service/ChessService.java
> +        if (historiesByGameId != null) {
사실 빈리스트로 반환을 하고 있었는데 제가 null로 잘못 체크하고 있는 부분이었네요..
이부분도 수정했습니다.

2021-04-06 17:30 UTC, jh8579 commented on src/main/java/chess/service/UserService.java
> +            userDao.addUser(new User(name));
위와 같이 Optional을 적용했습니다

2021-04-06 17:59 UTC, jh8579 commented on src/main/java/chess/controller/WebController.java
> +        res.cookie("user", encodeCookie(userName));
일단 쿠키로 userId를 사용해서 이름과 다르게 unique한 사용자를 식별할 수 있는 요소로 바꾸었지만,
db에 저장된 userId가 유출되는 보안 문제도 있고
사용자가 임의로 클라이언트에서 수정을 하는 경우는 대처할 수 없을 것 같네요....

말씀해주신대로 세션값을 저장하는 방식을 적용한다면 userId도 숨기고,
임의로 수정해서 로그인을 하는 문제를 해결할 수 있을 것 같습니다.

쿠키와 세션을 연결하는 방식은 다음 미션 때 로그인 과정이 있다면 적용해 보겠습니다.
감사합니다!

2021-04-06 18:01 UTC, jh8579 commented
* Optional 사용
  * 로그인이 필요한 함수들을 optional을 사용하여 쿠키를 확인하고 없는경우 리다이렉트 하도록 처리
  * db 조회 시 조회 값이 없는 경우 null 대신 Optional로 반환
*   DB 관련 에러 처리 수정
* 쿠키 username에서 userId로 변경

2021-04-06 18:18 UTC, jh8579 commented on src/main/java/chess/service/ChessService.java
> +    private final GameDao gameDao;
Service 없이 Controller에서 바로 Dao를 사용하려다보니 Controller의 역할이 너무 커지더라구요
그래서 Service를 만들고 User 관련 로직은 UserService에서 Game 관련 로직은 ChessService에서 처리하도록 했습니다.

그런데 리뷰해주신 부분을 다시 생각해보니 Service가 Controller의 세부사항 구현에 너무 의존한 것 같다라는 생각이 드네요
세부사항이 바뀌게되면 관련이 있는 Service 객체도 영향을 받을 것 같아요

2021-04-09 09:32 UTC, JunHoPark93 commented on src/main/java/chess/service/ChessService.java
> +    private final GameDao gameDao;
컨트롤러의 세부사항이 아니라 데이터레이어의 세부사항에 의존하는것 아닐까요?
이부분은 다음 레벨들에서 배우게 되실거같아요!

2021-04-09 09:35 UTC, JunHoPark93 approved these changes
안녕하세요 알리!
피드백 반영하시느라 고생많으셨습니다 🙇‍♂️
방학 잘 보내시고 다음 레벨도 화이팅입니다!

2021-04-09 09:35 UTC, merged