[4, 5단계 - 체스] 영이(최준영) 미션 제출합니다.
woowacourse/java-chess pull request #245
Opened 2021-04-04 08:08 UTC by choijy1705

안녕하세요 미립!

4,5단계 미션 제출합니다. 처음해 보는 것이라 익숙치 않고 정신이 없었습니다. 
리팩토링도 제대로 하고 싶지만 뭔가 리뷰를 받고나서 다시 대 공사가 이뤄질 거 같아서 빨리 리뷰를 받고싶어 먼저 리뷰요청 드렸습니다.

![스크린샷 2021-04-04 오후 4 41 31](https://user-images.githubusercontent.com/63634505/113502057-ab693880-9564-11eb-8b69-27a708c4a4bf.png)
### 첫화면
`START`,`END`,`STATUS` 버튼이 있는데 start를 누르지 않으면 나머지 버튼은 동작하지 않도록 하였습니다. 그리고 START 버튼을 누르는 과정에서 수많은 버그들을 발견하였는데 여기에 매진하고 있다가는 5단계로 나아가질 못할 것 같아 넘어갔습니다 ㅠ

![스크린샷 2021-04-04 오후 4 38 09](https://user-images.githubusercontent.com/63634505/113502010-4ca3bf00-9564-11eb-9d83-611c2fdc1800.png)

### START 이후
- 버튼 상단에 누구의 턴인지 표시됩니다. 
- `END`를 사용하여 게임을 종료시킬 수 있습니다.
- `STATUS` 버튼을 통하여 현재 블랙팀, 화이트팀의 점수를 알 수 있습니다.
- `SAVE` 버튼을 이용하여 현재 말들의 위치 정보를 저장할 수 있습니다. 이전 데이터들은 지워지고 가장 최신의 데이터들만 저장됩니다.
- `LOAD` 버튼을 이용하여 가장 최근에 저장되었던 정보들을 불러옵니다.

## DB
```
create table pieces (
	color VARCHAR(12) NOT NULL,
    shape VARCHAR(12) NOT NULL,
    position VARCHAR(12) NOT NULL
    
);

create table turn(
	turn VARCHAR(12) NOT NULL
)

```
Piece의 정보와 마지막으로 끝났던 팀이 어디인지를 저장하기 위하여 `pieces`와 `turn` 테이블을 생성하였고 여기에 정보들을 저장하였습니다.

## axios
아직까지도 제가 맞게하는지 의문이 많이 드는 곳입니다. axios를 이용하여 Java의 정보를 Javascript로 전송 하였고 정보들을 화면에 나오도록 진행하였습니다. 

```
axios({

}).then((res) => {
    
    }
)
```
**위의 형태로 사용하였는데 then 이전 부분이 Java에서 실행시킬 부분을 적는것이고 then 이후 부터는 javascript를 통하여 진행하는 것이라고 이해 하였는데 이렇게 사용하는 것이 맞는지 궁금합니다.**

### DAO
piece들과 turn 정보를 DB에 저장하고 꺼내오기 위하여 DAO를 사용하였습니다. 처음 사용하는 만큼 인터넷에 다른 사람들이 사용했던 것들을 참고하여 진행하였습니다. DAO에 관하여 지켜야할 부분이 있다거나 수정해야할 부분들을 알려주세요 ㅠ

2021-04-05 08:37 UTC, seok-2-o requested changes
안녕하세요 영이. 
DAO 관련하서 Database 와 컨넥션을 만드는 부분을 다시 한번 학습 및 점검 해보면 좋을 것 같아요.
그외에도 몇가지 코멘트 남겨 놓았으니 확인 부탁드립니다.

남들과 비교하면 조바심이 들 수 있지만, 본인만에 페이스 잃지 말고 끝까지 완주 할 수 있기를 바라요.

진행중 어려운점이나 궁금한점 있으면 편하게 DM 주세요.

2021-04-05 08:37 UTC, seok-2-o commented on src/main/java/chess/WebUIChessApplication.java
> +        get("/", (req, res) -> {
웰컴페이지 👍

2021-04-05 08:37 UTC, seok-2-o commented on src/main/java/chess/WebUIChessApplication.java
> +            System.out.println("-------------------------------");
불필요한 출력은 성능에 좋지 않다고 생각해요 출력이 필요하다면 logger 를 이용하는건 어떤가요 ?

2021-04-05 08:37 UTC, seok-2-o commented on src/main/java/chess/WebUIChessApplication.java
> +                return gson.toJson(new ChessBoardDto("false", new PiecesDto(chessGame.getBoard().getPieces()), "이미 게임이 실행되었습니다.", ""));
정상적인 요청이 아닌경우에 어떤 응답을 주는것이 바람직할까요?
또 현재 피스의 정보를 반환하는것이 좋을까요?

2021-04-05 08:37 UTC, seok-2-o commented on src/main/java/chess/WebUIChessApplication.java
> +            JsonObject jsonObject = (JsonObject) jsonParser.parse(req.body());
body를 Jackson 을 통해 객체로 파싱하는건 어떤가요 지금 코드는 너무 알아보기 힘든 것 같아요.

https://m.blog.naver.com/PostView.nhn?blogId=writer0713&logNo=221122145993&proxyReferer=https:%2F%2Fwww.google.com%2F

2021-04-05 08:37 UTC, seok-2-o commented on src/main/java/chess/WebUIChessApplication.java
> +public class WebUIChessApplication {
전반적으로 상수 사용이 너무 많네요.

2021-04-05 08:37 UTC, seok-2-o commented on src/main/java/chess/WebUIChessApplication.java
> +    private static ChessGame chessGame;
한번에 여러 게임을 실행하려면 어떻게 할 수 있을까요?

2021-04-05 08:37 UTC, seok-2-o commented on src/main/java/chess/WebUIChessApplication.java
> +public class WebUIChessApplication {
모두 ChessBoardDto 를 응답하는게 아니라 상황에 맡는 응답을 하는건 어떻게 생각하시나요?

2021-04-05 08:37 UTC, seok-2-o commented on src/main/java/chess/WebUIChessApplication.java
> +            return gson.toJson(new ChessBoardDto("true", new PiecesDto(chessGame.getBoard().getPieces()), "", chessGame.getStatus()));
ChessBoardDto를 생성하는것도 캡슐화 할 수 있을 것 같아요.

2021-04-05 08:37 UTC, seok-2-o commented on src/main/java/chess/domain/dao/PieceDAO.java
> +        }
이번 과정에서 들여쓰기는 한번으로 제한하고 있어요.

2021-04-05 08:37 UTC, seok-2-o commented on src/main/java/chess/domain/dao/PieceDAO.java
> +            throwable.printStackTrace();
어떤 의미가 있나요?

2021-04-05 08:37 UTC, seok-2-o commented on src/main/java/chess/domain/dao/PieceDAO.java
> +    private static Connection con = getConnection();
https://javacan.tistory.com/entry/78 컨넥션을 비롯한 자원들을 제대로 반환하지 않는다면 어떻게 될까요
해당 자원은 static 으로 사용 할 수 있는 자원이 맞을까요?

2021-04-08 14:13 UTC, choijy1705 commented on src/main/java/chess/WebUIChessApplication.java
> +            JsonObject jsonObject = (JsonObject) jsonParser.parse(req.body());
Jackson을 통하여 객체로 파싱해보았습니다. 
```
ObjectMapper mapper = new ObjectMapper();
MovePositionInfo mpi = mapper.readValue(req.body(), MovePositionInfo.class);
```

객체로 만드는 과정에서 `MismatchedInputException` 이 계속 발생하여 해결방법으로 빈 생성자를 만들면 해결할 수 있다고 하여 빈생성자를 만들어 문제를 해결하였습니다.  혹시 어떠한 원인때문에 예외가 발생하고 빈 생성자가 문제를 해결할 수 있었던 걸까요?

2021-04-08 14:23 UTC, choijy1705 commented on src/main/java/chess/domain/dao/PieceDAO.java
> +            throwable.printStackTrace();
이부분은 최근 체스게임 정보만 저장하려고 이전 정보를 지우기위해 만들었습니다. 방번호 기능을 추가하게 된다면 필요 없을 것 같아요

2021-04-08 15:01 UTC, choijy1705 commented on src/main/java/chess/WebUIChessApplication.java
> +    private static ChessGame chessGame;
이 부분은 조금 더 고민해봐야 할 것 같습니다 ㅠ. 일단 다른 부분들 리팩토링 진행 하였는데 리뷰 부탁드립니다.

2021-04-10 14:22 UTC, choijy1705 commented
방을 여러개 만들 수 있도록 구현해보았습니다.
그리고 게임을 조작하는 화면을 테이블로 구성하여 좀 더 깔끔하게 보이도록 리팩토링 진행하였습니다.
게임을 여러개 만들 수 있도록 구현 하면서 이번에는 따로 `SAVE` 버튼을 구현하지 않고 체스 말을 움직일때마다 게임 정보를 자동으로 DB에 저장되도록 하였습니다.

### 초기 화면
<img width="1242" alt="스크린샷 2021-04-10 오후 11 14 29" src="https://user-images.githubusercontent.com/63634505/114272810-9b64c380-9a52-11eb-94bd-013355b7a782.png">

### START
`START` 는 새로운 게임을 만드는 것으로 사용자로 부터 체스 게임의 방이름을 입력받아 게임을 시작할 수 있도록 하였습니다.

### END
`END` 는 현재 사용중인 방의 이름을 받아서 해당 게임을 종료 시키면서 DB에서 정보를 지우도록 구현하였습니다.

### STATUS
`STATUS` 마찬가지로 현재 사용중인 방의 이름을 받아서 해당 게임에 대한 점수를 보여주도록 구현하였습니다.

### LOAD
`LOAD` DB에 저장된 방의 이름 정보들을 받아 체크를 하면 해당 게임을 이어서 할 수 있도록 하였습니다.

### DB 수정
방을 여러개 만들수 있는 구조로 변경 하면서 DB를 새롭게 구성하였습니다.
```
create table pieces (
    roomID VARCHAR(12) NOT NULL,
    color VARCHAR(12) NOT NULL,
    shape VARCHAR(12) NOT NULL,
    position VARCHAR(12) NOT NULL
);


create table game(
	roomID VARCHAR(12) NOT NULL,
	turn VARCHAR(12) NOT NULL
);

```

2021-04-13 06:30 UTC, seok-2-o approved these changes
영이. 방학은 잘 보내셨나요 :)

몇가지 코멘트를 마지막으로 이번 미션은 마무리하도록 할게요.
다음 미션도 해당 코드를 가지고 진행하는 만큼 지속적으로 리펙토링 진행해보면 좋을 것 같아요.
저와의 미션은 종료되었지만, 앞으로도 궁금한점이나 어려운점 있다면 편하게 DM 주세요.

감사합니다. 🙇

2021-04-13 06:30 UTC, seok-2-o commented on src/main/java/chess/WebUIChessApplication.java
> +            MovePositionInfo mpi = mapper.readValue(req.body(), MovePositionInfo.class);
약어는 최대한 지양하는게 좋을 것 같아요.

2021-04-13 06:30 UTC, seok-2-o commented on src/main/java/chess/domain/dao/PieceDAO.java
> +        }
반드시 모든 익셉션을 처리해주는 것이 좋아요.

2021-04-13 06:30 UTC, seok-2-o commented on src/main/java/chess/domain/dao/PieceDAO.java
> +            ResultSet rs = preparedStatement.executeQuery();
ResultSet 은 반환하지 않아도 괜찮을까요?

2021-04-13 06:30 UTC, seok-2-o commented on src/main/java/chess/domain/piece/Piece.java
> +        return new Piece(color, Shape.Q, new Position(row, col), Collections.singletonList(new QueenMoveCondition()));
이전이 더 가독성이 좋아보이는데 변경하신 이유가 있으실까요?

2021-04-13 06:31 UTC, merged