[4, 5단계 - 체스] 파즈(강승윤) 미션 제출합니다.
woowacourse/java-chess pull request #246
Opened 2021-04-04 08:21 UTC by Be-poz

안녕하세요 닉, 파즈입니다.  

js에 막혀서 pr 날리기까지 꽤 많은 시간이 걸렸네요 ㅜㅜ  

기물을 눌렀을 때에 이동 가능한 좌표를 보이는 기능은 추가하지 않았습니다. 기존 로직 수정이 좀 많이 들어가야 되기도 하고, 온라인 체스말고 실제 대결에서도 그런 기능은 없으니깐요 ..(자기합리화 맞습니다 ㅋㅋㅋ)  

* ``'/'`` 는 html을 렌더링합니다.  
* ``'/loadSavedBoard'`` js 내부에서 해당 url로 api를 날려서 체스판을 db에 저장된 내용으로 초기화 해줍니다.

* ``'/move'`` 시에는 기물이 있던 위치와 이동한 위치의 값만 db에서 수정을 해주게 됩니다.
* ``'/scoreStatus'`` 는 Score 버튼을 누르면 호출하게 되는데, 현재 보드의 점수를 alert 하게 됩니다.
* ``'/resetBoard'`` 는 체스판을 새로 깔아주고, db에도 저장합니다.

처음부터 웹을 한다고 생각하고 1,2,3 단계를 수행했으면 한층 더 편했겠다~ 라고 생각이 드는 4,5 단계 미션이었습니다.  

리뷰하시느라 고생이 많습니다. 피드백 기다리고 있을게요~! 감사합니다. 좋은 주말 마무리 되세요 ㅎㅎ

2021-04-04 11:23 UTC, wbluke requested changes
웹, DB 단계 구현하시느라 고생하셨어요 👏 
피드백 남겼으니 확인 후 수정 부탁드려요~ 🙂

2021-04-04 11:23 UTC, wbluke commented on src/main/java/chess/repository/ChessRepository.java
> +public class ChessRepository extends DBConnector {
Spring을 참고하셔서 그런지 Repository라는 네이밍을 쓰셨는데요.
현재 애플리케이션에서는 Repository보다는 DAO라고 봐야 맞습니다 ㅎㅎ

Repository와 DAO는 DB Access를 담당한다는 역할 관점에서는 동일하지만,
Repository는 JPA와 같은 ORM에서 사용하는 도메인 레이어에 해당하구요, (퍼시스턴트 레이어의 구현체를 받아주는 인터페이스)
DAO는 String 형태의 query에 종속적인 퍼시스턴트 레이어입니다.

2021-04-04 11:23 UTC, wbluke commented on src/main/java/chess/repository/ChessRepository.java
> +        PreparedStatement pstmt = getConnection().prepareStatement(query);
PreparedStatement와 ResultSet도 Connection 처럼 자원회수를 하는 것이 좋습니다.
try-with-resources 구문에 대해서 학습하고 적용해보면 좋겠네요 :)

2021-04-04 11:23 UTC, wbluke commented on src/main/java/chess/service/ChessService.java
> +        ResultSet savedBoardInfo = chessRepository.getSavedBoardInfo();
DB Access 레이어에서 모든 Connection 관련 작업을 마무리하는 것이 좋습니다.
이렇게 되면 Service 레이어가 ResultSet이라는 DB Connection 관련 객체를 알아야만 하기 때문에, 서비스 레이어도 DB Access에 대한 책임을 가지게 되어 레이어 간 결합도가 존재하는 상태인 듯 해요.
즉, 레이어 간에 DTO로만 통신하는 것이 좋겠습니다 :)

2021-04-04 11:23 UTC, wbluke commented on src/main/java/chess/controller/ChessController.java
> +        });
Gson 객체를 재사용할 수 있지 않나요? :)

2021-04-06 08:58 UTC, Be-poz commented on src/main/java/chess/repository/ChessRepository.java
> +public class ChessRepository extends DBConnector {
이 부분에 대해서 제가 기존에 알고 있던 DAO 개념이 잘못됐었나 봅니다!  
저는 dao 를 dto, vo와 같은 개념으로 보고 있었어요! 단순히 db에 접근해서 그 정보들을 담은 vo 라고 생각했었고, repository 에서 service 간의 계층 이동을 위해서 사용하는 것으로 생각하고 있었습니다. 그래서 dto 나 dao나 대체 무슨 차이가 있는 것인가 라고 의문점을 가지고 있었는데 잘못된 개념이었네요. 짚어주셔서 감사합니다.

2021-04-06 09:19 UTC, Be-poz commented on src/main/java/chess/controller/ChessController.java
> +        });
이런걸 못보다니 ㅜㅜ 지적 감사합니다

2021-04-06 13:00 UTC, Be-poz commented on src/main/java/chess/service/ChessService.java
> +        ResultSet savedBoardInfo = chessRepository.getSavedBoardInfo();
그렇겠군요~! 한 가지 의문점이 있습니다. 그냥 String 이나 Map을 리턴하는 경우에도 DTO를 사용해야 할까요 ??  

제가 dto를 사용하는 이유가 정보 유출을 막기위함이라고 알고 있습니다. 만약 Chess 라는 객체를 dao 에서 service 로 보내줄 때에 Chess 라는 객체를 바깥에 알리게 되기 때문에 따로 ChessDTO를 만들어서 필요한 값만 넣어서 반환해주는 것이라고 알고 있습니다.  
예를 들어, 클라이언트가 요구하는 api 를 만족시키기 위해 Toy라는 도메인에 대한 정보가 들어가고 Toy의 모든 필드를 사용하는 것이 아니라 일부만 사용하는 경우이거나, 또는 Toy 와 Candy 이렇게 여러 개의 도메인 객체에 대한 정보가 들어가는 경우에 도메인 전체에 대한 정보를 공개할 수 없기에 api 스펙에 맞춰서 dto를 만드는 방식을 사용하는 것으로 알고 있습니다.  

제가 이번에 리팩토링을 하면서 dao 에서 String 과 Map<String, String> 를 리턴했어야 했습니다. 이런 경우에도 그냥 값을 리턴하는 것이 아니라 dto를 만들어서 리턴하는 것이 과연 맞는 것인지 그냥 String을 리턴해도 되지 않을까? 라는 의구심이 들어 질문 드렸습니다!

2021-04-06 13:31 UTC, Be-poz commented on src/main/java/chess/repository/ChessRepository.java
> +        PreparedStatement pstmt = getConnection().prepareStatement(query);
try-with-resources 를 이용해서 자원해제를 했습니다~!  

자바 9에서는 다음과 같이 바깥에 선언 후 해당 변수명만 try 집어 넣는 것으로도 동일한 기능을 할 수 있다고 하더라구요.  

```java
PreparedStatement pstmt = getConnection().prepareStatement(query);

try(pstmt) {
  ...
}
```

프로젝트 버전 디폴트가 자바 8이어서 하지는 못했지만 새로운 것을 하나 더 알아갈 수 있어서 좋았습니다.

2021-04-06 13:33 UTC, Be-poz commented
안녕하세요 닉, 파즈입니다.  
지난번 피드백 속도에 정말 감명받았습니다.. 감사하게 생각하고 있습니다.  
피드백 반영을 했고, 생긴 의문점은 위의 코멘트에 답 코멘트로 달아두었습니다.  
점점 날이 따뜻해져가는 것 같아서 기분이 좋은 나날들이네요. 이번주도 좋은 한 주 보내시길 바랄게요~

2021-04-07 12:15 UTC, wbluke commented on src/main/java/chess/repository/ChessRepository.java
> +        PreparedStatement pstmt = getConnection().prepareStatement(query);
오 그렇군요? 저도 자바9를 사용하지 않아서 몰랐는데, 좋은 정보 감사합니다 ㅎㅎ 🙇 
자원관리하기가 더 용이하겠네요.

2021-04-07 12:18 UTC, wbluke commented on src/main/java/chess/service/ChessService.java
> +        ResultSet savedBoardInfo = chessRepository.getSavedBoardInfo();
아 네네 물론 그대로의 값을 리턴해도 됩니다ㅎㅎ
하지만 반환 구조가 새롭게 추가되거나 변경되지 않으리라는 보장이 없기 때문에, 미리 DTO 형태로 내부 반환구조를 캡슐화한다면 이후 변경사항이 생기더라도 해당 API를 사용하고 있는 클라이언트에는 큰 변경지점 없이 대응이 가능할거에요 :)

2021-04-07 12:20 UTC, wbluke approved these changes
긴 미션 고생 많으셨어요 파즈 👍 
지난번 코멘트에 주신 질문도 답변 달아놓았으니 참고 부탁드려요 ㅎㅎ
방학 잘 쉬고 마무리 잘 하길 바라요 🙂

2021-04-07 12:20 UTC, wbluke commented on src/main/java/chess/repository/ChessDAO.java
> +            ResultSet savedTurnOwner = pstmt.executeQuery()) {
잘 처리해주셨네요 👍 
개인적으로 이런 구문 볼때마다 답답하긴 한데 ㅋㅋ 말씀해주셨던 자바9의 구문을 사용할 수 있다면 좀 더 편하겠네요 ㅎㅎ

2021-04-07 12:20 UTC, merged