[4, 5단계 - 체스] 피케이(박유진) 미션 제출합니다.
woowacourse/java-chess pull request #252
Opened 2021-04-04 13:27 UTC by pkeugine

안녕하세요 닉!
확실히 레벨1 마지막 미션이라 그런지 쉽지 않았습니다.
브랜치를 따로 만들어서 리팩토링 해본 게 처음이라 커밋도 두 번씩 들어갔네요.
그래도 이번 경험을 통해 똑같은 실수는 하지 않을 것 같습니다.

1단계에서 페어와 함께 체스말이 이동 가능한 경로를 구하려고 머리를 맞대고 고민했었는데,
웹에서 그 경로가 잘 나타나 기분이 좋네요.

제 데이터베이스 DDL은 정말 간단합니다.

```
CREATE DATABASE chess_db DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

use chess_db

CREATE TABLE games (
      game_id VARCHAR(12) PRIMARY KEY NOT NULL,
      game_info VARCHAR(5000),
);
```
game_info 에 게임에 관련된 모든 정보를 담는 식인데, 과연 이 방식이 체스말의 위치, 플레이어 차례, 등등 별도의 table 또는 column을 만드는 방식처럼 일반적으로 쓰이는지 궁금하네요. 아무래도 저도 하면서 좀 단순무식한 느낌이 들긴 했습니다 ㅋㅋㅋ

이 방식을 통해 여러 게임을 저장하고 다른 방을 만들 수 있는 상태이긴 하지만, 제출이 늦어지는 것 같아서 추가 구현은 하지 않았습니다. (기본 구현은 모두 완료된 상태예요).

리뷰 정말 감사합니다!
저는 다시 또 브랜치를 만들어서 리팩토링 + 추가 구현을 진행하고 있겠습니다 😁.

아, 궁금한 점이 있는데
제가 이번 미션에 불변 객체를 만들기 위해 노력을 굉장히 많이 했습니다 (도메인에 한해서).
불변 객체가 현업에서도 중요시되는 요소인가요?
그리고 인자마다, 로컬 변수마다 모두 final 처리를 하는 게 닉이 프로그래밍 할 때 유지하는 습관인가요?

2021-04-06 14:30 UTC, wbluke requested changes
안녕하세요 피케이! 체스 마지막 단계 잘 구현해주셨네요 👏 
주신 질문에 대한 답변과, DB 설계 관련해서 피드백 남겼으니 확인 부탁드려요 🙂

2021-04-06 14:30 UTC, wbluke commented on src/main/java/chess/dao/GameDao.java
> +        ResultSet rs = pstmt.executeQuery();
try-with-resources 를 학습해보고 적용해보면 어떨까요? :)

2021-04-06 14:30 UTC, wbluke commented on src/main/java/chess/dao/GameDao.java
> +        String gameInfo = gson.toJson(gameStateDto);
json 형식으로 한 컬럼에 넣으셨군요ㅎㅎ
물론 이 방법도 사용되지 않는 것은 아닙니다만, 기본적으로 지양해야 할 방법입니다.
다음과 같은 문제가 있을 것 같아요.
- 저장한 데이터에 대한 쿼리(검색)가 아예 불가능하다. (이게 제일 크리티컬합니다)
- 만약 이 애플리케이션이 대용량 데이터 시스템이라면, 위와 같은 데이터 형태는 마이그레이션하기가 어렵습니다. 실무에서는 가끔 기존 데이터를 새로운 구조로 마이그레이션할 일이 생기기도 하는데요. (데이터가 많으면 많을수록 해당 작업이 며칠씩 걸리기도 합니다) 지금처럼 json 형태로 통으로 넣은 데이터는 가공하기가 어려워보여요.

json으로 컬럼을 구성하는 방법은 정말 변경되지 않을 데이터, 쿼리도 필요없고 그저 전체 json -> DTO 조회로만 사용할 데이터인 경우에만 한정적으로 사용합니다 :)

2021-04-06 14:30 UTC, wbluke commented on README.md
> +### 웹 애플리케이션
> 아, 궁금한 점이 있는데
제가 이번 미션에 불변 객체를 만들기 위해 노력을 굉장히 많이 했습니다 (도메인에 한해서).
불변 객체가 현업에서도 중요시되는 요소인가요?

불변객체는 매우 중요합니다. 같은 조건 하에서 불변과 불변이 아닌 설계가 있다면 당연히 불변을 선택해야 하고요.
불변의 장점은 찾아보셨을 것 같은데(Thread-Safe 등), 코스 진행하시면서 한번 계속 고민해보시면 좋겠습니다 :)

> 그리고 인자마다, 로컬 변수마다 모두 final 처리를 하는 게 닉이 프로그래밍 할 때 유지하는 습관인가요?

저는 다음과 같이 합니다.
- 필드 : 꼼꼼하게 final 처리
- 메서드 파라미터, 로컬 변수 : 안합니다.

파라미터와 로컬 변수에 final 처리를 하지 않는 이유는, 클린 코드를 지향하다 보면 하나의 메서드 길이가 몇십줄 이상 되는 경우가 거의 없기 때문에, 선언함으로써 잃는 가독성에 비해 final 키워드의 효과가 미미하기 때문입니다. (물론 이게 정답은 아닙니다. 팀 컨벤션에 따라 다를 수 있겠네요)

2021-04-06 14:30 UTC, wbluke commented on src/main/java/chess/controller/WebController.java
> +        game = game.execute(command);
이렇게 Game 객체 할당을 두번 할 필요가 있나요? :)

2021-04-06 14:30 UTC, wbluke commented on src/main/java/chess/dao/GameSerializer.java
> +        }
관리되어야 할 상수 같네요. 기존 Enum도 있는 것 같고요!

2021-04-06 14:30 UTC, wbluke commented on src/main/java/chess/domain/board/Path.java
> +                    && !otherPiece.isEmpty()) {
if문이 정확히 어떤걸 판단하는지 메서드로 추상화시키면 어떨까요?
다른 곳도 혹시나 비슷한 부분이 없는지 확인해주세요 :)

2021-04-08 08:23 UTC, pkeugine commented
안녕하세요 닉!
피케이입니다 :)

불변 / final 처리에 관한 답변과 json 형태로 저장하는 것에 대한 답변 정말 감사합니다.
try-with-resources도 그렇고 이번 미션이 어려운데 확실히 배워가는 것은 많네요!

보내주신 리뷰를 반영하며 생긴 질문이 있어서 한 번 남겨볼게요!

1. DB를 생각하지 않고 체스 애플리케이션을 만들 때는 게임에 상태패턴을 적용하는게 좋을 것 같다는 생각을 했었어요. "흰색 차례", "검은색 차례", "게임 시작 전", "게임 끝" 과 같은 (제 기준) 명확한 상태가 있었으니까요. 그런데 그 상태 패턴이 오히려 웹을 적용하면서 장애물이 되는 느낌을 강하게 받았습니다. 닉이 제게 주신 리뷰 중 "Game 객체 할당을 두 번 할 필요가 있을까요"도 결국 상태 패턴을 적용하면서 생긴 문제거든요. 게임을 할당을 해주고 start를 넣어줘야 게임이 진짜로 시작되는... 그런 구조라.. 😅
그래서 질문은 이런 체스 게임에서 상태 패턴이 도움이 될까요? 아니면 그냥 DB에 상태를 넣어주고 그것만 매 턴 바꿔주는게 좋을까요?

2. 현재 Game 객체와 GameState를 이용해서 다른 도메인을 관리해주고 있습니다. 그런데 이것 역시 cmd 창에서 구현을 목적으로 만든 클래스라 웹에서 사용할 때 장애물이 되는 느낌이었어요. 알아보니 다양한 컨트롤러에서 도메인과 DB를 사용할 수 있게 service 레이어를 활용한다는 것을 배웠습니다. 아직 service 레이어를 만들어 본 적은 없지만, Game 객체를 이용하여 모든 체스 로직을 관리한다기 보단 service를 만드는 것이 나을까요? 예를 들어 `PieceMoveService` 를 이용해서 체스말을 움직이는 방식으로요.

리뷰 정말 감사합니다!
질문이 조금 애매할 수도 있는데, 혹시라도 이해가 안된다면 알려주세요!!

2021-04-10 01:33 UTC, wbluke approved these changes
피드백 반영 잘 해주셨네요 👍 
질문에 대한 답변은 코멘트 남겼습니다.
긴 체스 미션 고생 많으셨어요! 🙂

2021-04-10 01:33 UTC, wbluke commented on README.md
> +
> DB를 생각하지 않고 체스 애플리케이션을 만들 때는 게임에 상태패턴을 적용하는게 좋을 것 같다는 생각을 했었어요. "흰색 차례", "검은색 차례", "게임 시작 전", "게임 끝" 과 같은 (제 기준) 명확한 상태가 있었으니까요. 그런데 그 상태 패턴이 오히려 웹을 적용하면서 장애물이 되는 느낌을 강하게 받았습니다. 닉이 제게 주신 리뷰 중 "Game 객체 할당을 두 번 할 필요가 있을까요"도 결국 상태 패턴을 적용하면서 생긴 문제거든요. 게임을 할당을 해주고 start를 넣어줘야 게임이 진짜로 시작되는... 그런 구조라.. 😅
그래서 질문은 이런 체스 게임에서 상태 패턴이 도움이 될까요? 아니면 그냥 DB에 상태를 넣어주고 그것만 매 턴 바꿔주는게 좋을까요?

메모리에 상태를 관리하면 배포를 하거나, 서버를 재시작하거나, 혹은 장애로 인해 죽거나 하는 경우 데이터가 날아가게 됩니다.
영속적으로 관리해야하는 정보는 DB로 관리하는 것이 좋겠죠 :)

> 현재 Game 객체와 GameState를 이용해서 다른 도메인을 관리해주고 있습니다. 그런데 이것 역시 cmd 창에서 구현을 목적으로 만든 클래스라 웹에서 사용할 때 장애물이 되는 느낌이었어요. 알아보니 다양한 컨트롤러에서 도메인과 DB를 사용할 수 있게 service 레이어를 활용한다는 것을 배웠습니다. 아직 service 레이어를 만들어 본 적은 없지만, Game 객체를 이용하여 모든 체스 로직을 관리한다기 보단 service를 만드는 것이 나을까요? 예를 들어 PieceMoveService 를 이용해서 체스말을 움직이는 방식으로요.

레이어드 아키텍처를 보고 서비스 레이어를 필수라고 생각할 수도 있지만, 서비스 레이어의 유무보다 도메인 설계가 더 중요합니다.
지금 같은 경우에서는 Game이 콘솔 기반의 서비스 역할을 담당하고 있는거라고 볼 수 있을 것 같고, 또 웹 로직을 위한 서비스가 나올 수도 있겠죠.
핵심은 컨트롤러와 서비스가 어떻게 달라져도 도메인은 변경이 없도록 설계하는 것입니다.
콘솔 기반이라 이 객체가 서비스인지 아닌지, 서비스 레이어를 구상해야하는지에 대한 기준이 조금 애매할 수는 있습니다만, 다음 레벨 때 스프링을 접해보면서 구체적으로 고민해보셔도 좋을 것 같습니다 :)

2021-04-10 01:34 UTC, merged