[4, 5단계 - 체스] 오즈(오주형) 미션 제출합니다.
woowacourse/java-chess pull request #255
Opened 2021-04-04 16:43 UTC by ohjoohyung

안녕하세요 지노!! 
체스 미션 마지막 단계 리뷰를 요청하게된 오즈라고 합니다!!
우선, 오랜만에 자바스크립트와 DB를 접하여 어려움을 겪다보니 지금 제출하게된 점 사과드립니다ㅜㅜ
일단 요구사항 중 필수사항은 구현을 하였고 선택사항의 경우 추후 구현을 위해 DB만 테이블 세팅을 해두었습니다.
그래서 지금은 room_no를 1로 고정시켜두고 하나의 방만 CRUD 하는 방식입니다.

```SQL
CREATE TABLE chess_room (
    room_no int not null,
    black_score double not null,
    white_score double not null,
    turn varchar(10) not null,
    PRIMARY KEY (room_no)
);

CREATE TABLE chess_piece (
    coordinate varchar(10) not null,
    piece_name varchar(10) not null,
    piece_color varchar(10) not null,
    room_no int not null,
    FOREIGN KEY (room_no) references chess_room (room_no)
);
```

게임 방식은 간단하게 시작하기를 누르면 체스판 및 체스말이 생성되고 DB에 방 정보가 저장됩니다.
만약 게임이 이미 진행 중일때 시작하기를 누른다면 게임이 다시 시작됩니다.
체스말을 움직일때마다 DB에 방 정보가 UPDATE 되며
서버를 종료했다가 다시 실행시키고 불러오기를 누르면 DB에 있는 이전 방 정보를 이용하여 게임을 불러옵니다.
마지막으로 나가기를 누르면 DB에 있던 현재 방 정보를 삭제시키고 맨 처음 화면으로 돌아오게 됩니다.

구현을 하다가 몇 가지 궁금한 점이 있어서 질문드립니다!

**첫번째로 현재 DAO 테스트 케이스에 대한 질문인데요.**
테이블에 대한 CRUD를 진행하기 위해 테스트를 작성했습니다. 저는 테스트가 코드 순서대로 (위에서 아래로) 실행이 되는줄
알고 아래의 테스트가 위 테스트에 종속되도록 테스트를 작성했는데 전체 테스트 코드를 실행시키니 순서가 보장되어 있지 않더군요.
그래서 검색하여 TestMethodOrder를 이용해서 메서드 순서를 보장해주었습니다. 근데 각각의 테스트가 독립적이지 않고 서로 종속적인게 과연 괜찮은가라는 의문이 들더군요. 이러한 CRUD 테스트를 독립적이게 작성하는 방법이 있을까요??

**두번째로 DTO와 Service 클래스에 관한 내용입니다.**
제가 이번에 처음으로 DTO, Service를 사용해보았는데요.
DTO의 경우, 방 정보를 클라이언트에 보내줄 때 도메인을 그대로 넘기게 되니 필요없는 정보도 같이 념겨주게 되더라구요. 그래서 이를 넘겨주지 않기 위해 + 데이터를 한꺼번에 담아서 보내주기 위해, 마지막으로 뷰를 위한 도메인의 코드 추가 방지를 위해 사용해야겠다 결심하게 되었습니다. 이러한 이유로 DTO를 사용하는게 맞는건가요? 그리고 DTO가 제대로 작성되었는지 궁금하네요.
Service의 경우도 마찬가지입니다.
제가 알기론 Controller에 Model을 이용하는 비즈니스 로직이 복잡해질 경우 이를 따로 분리하여 Controller는 단순히 매핑하는 역할을 해주기 위해 Service를 추가하는 것으로 알고 있는데 제가 알고 있는 정보가 정확한지 궁금합니다!

**세번째로 예외 처리입니다.**
예외 처리의 경우 서버 쪽에서 try catch를 이용해 에러 문장을 model에 담아 보내준 경우도 있고
DAO에서 생성, 수정, 삭제가 성공했을시 1을 리턴, 그게 아니면 0을 리턴해주어 클라이언트에서 이를 판단하여 0일 경우 에러 표시가 뜨게 한다라는 방식으로도 사용해보았는데요. 이런 방식을 사용해도 괜찮나요?

**마지막으로 게임을 로드했을때 서버에서 생성한 chessBoard와의 싱크를 맞춰주는 방식에 대해서인데요.**
실컷 다 구현해놓고 pr하기 위해 마지막 테스트를 해보니 로드하고 체스말이 움직이지 않더라고요.
보니까 서버에서 사용하는 chessBoard와 로드한 ChessRoomDto와의 싱크 차이 때문이더라고요.
이를 맞춰주기 위해 어쩔수 없이 chessBoard 도메인에 메서드를 추가해 인자로 ChessRoomDto를 넘겨주어 싱크를 맞춰주는 방식으로 해결했습니다.. 이렇게 해결해도 괜찮을가요..?? 

미션이 어렵다보니 질문이 좀 많아졌습니다..!!
이번 리뷰도 잘 부탁드립니다!! 감사합니다!!

2021-04-06 13:28 UTC, ohjoohyung commented
# 오즈의 학습로그

# [TDD] @TestMethodOrder

## 내용

- 하나의 테스트가 다른 테스트에 의존적이다 보니 테스트의 순서를 정해주고 싶었음.
- 테스트 클래스 상단에 @TestMethodOrder를 사용하고 각 테스트에 Order(숫자) 어노테이션을 통해 테스트의 순서를 보장할 수 있었음.
- 다만, 이렇게 하면 테스트가 독립적이지 않아 괜찮은 것인가하는 의문이 들었음.

## 링크

- [https://junit.org/junit5/docs/5.5.0/api/org/junit/jupiter/api/TestMethodOrder.html](https://junit.org/junit5/docs/5.5.0/api/org/junit/jupiter/api/TestMethodOrder.html)
- [https://howtodoinjava.com/best-practices/first-principles-for-good-tests/](https://howtodoinjava.com/best-practices/first-principles-for-good-tests/)
- https://github.com/woowacourse/java-chess/pull/255/commits/a66065d60e85fd6564e66177862ceb951a287f66

<br/>

# [기타] DTO

## 내용

- 도메인을 그대로 클라이언트에 넘겨주려하니 필요없는 데이터를 넘겨주는 경우가 발생함.
- 적절한 형태의 데이터를 넘겨주기 위해 DTO를 사용함.
- 왜 DTO를 사용하는지 알게됨.

## 내용

- [https://youtu.be/EeJnNaiMy3U](https://youtu.be/EeJnNaiMy3U)
- [https://youtu.be/J_Dr6R0Ov8E](https://youtu.be/J_Dr6R0Ov8E)

<br/>

# [JAVA] JDBC 트랜잭션 처리

## 내용

- 관계를 가지고 있는 테이블 2개를 사용하다 보니 INSERT, UPDATE, DELETE를 같이 해주어야 하는 경우가 발생함.
- 이를 위해 작업을 하나의 논리적 단위로 만들어 줄 트랜잭션 처리를 해야했음.
- JDBC에서는 이걸 어떻게 처리하나 찾아보니 auto commit을 false로 만들어 작업을 수행한 뒤 성공하면 수동으로 commit을 해주고 실패하면 rollback을 해주는 방법이 있었음.

## 링크

- [https://hamait.tistory.com/345](https://hamait.tistory.com/345)
- https://github.com/woowacourse/java-chess/pull/255/commits/a66065d60e85fd6564e66177862ceb951a287f66

<br/>

# [Javascript] fetch api

## 내용

- 비동기로 서버와 클라이언트를 통신하고 싶었음.
- Jquery 라이브러리, Axios 라이브러리 등을 사용할 수 있었지만 Javascript에 내장되어 있는 fetch api를 사용하기로 함
- fetch api는 promise 방식 기반이고 리턴 값으로 promise 인스턴스를 반환하게 됨. 이를 이용해 .then()으로 이어가며 간단하게 비동기 통신을 할 수 있음.
- 다만, 아직까지 맛보기 정도만 했을 뿐 promise, async, await에 대해서도 더 공부해야할 필요를 느꼈음.

## 링크

- [https://yeri-kim.github.io/posts/fetch/](https://yeri-kim.github.io/posts/fetch/)
- [https://programmingsummaries.tistory.com/325](https://programmingsummaries.tistory.com/325)

2021-04-06 17:43 UTC, hyunssooo commented
안녕하세요, 오즈! 지노입니다! 

> 현재 DAO 테스트 케이스에 대한 질문

개인적으로는 테스트는 각각 독립적으로 실행되어야 한다고 생각합니다. 테스트의 메서드들은 순서를 보장하지 않구요. 또한, 현재 데이터베이스도 프로덕션 데이터베이스를 사용하지 않나요? 프로덕션에서 사용하는 데이터베이스를 테스트와 함께 사용하면 어떤 문제점이 있을까요? 

```java
    @BeforeEach
    void setUp() { }

    @AfterEach
    void tearDown() { }
```
를 활용해 CRUD 테스트를 진행해볼 수 있을 거 같아요. 

> DTO와 Service 클래스에 관한 질문

레벨 2가 되면 자연스럽게 학습할 내용인데요. DTO같은 경우는 데이터를 보여주기 위한 용도로 많이 사용하는데요. 필요하지 않은 데이터는 dto를 통해서 숨길 수도 있습니다. 현재 오즈의 방식은 충분히 좋다고 생각합니다. 
service 같은 경우는 자연스럽게 아시게 되겠지만 tx를 관리하고 도메인 모델의 흐름을 제어합니다. 비즈니스 로직은 도메인 모델에서 해결하는 것이 맞구요. 비즈니스가 복잡해진다고 service를 사용하지는 않습니다. 

> 예외처리 질문
오즈가 구현한 방식도 방법도 가능하다고는 생각합니다. 하지만 0, 1이라는 값만 봤을때 옆에 있는 동료는 모를수도 있지 않을까요? 
예를 들어 select문으로 도메인 객체를 불러올 경우는 optional을 사용해 처리도 가능할 것 같아요.  레벨2에서 Dao가 아닌 repository를 사용할 때 오즈가 구현한 방식과 비교해보면 좋을 것 같아요. 

> 게임을 로드했을때 서버에서 생성한 chessBoard와의 싱크를 맞춰주는 방식

이 부분은 어느 부분인지 코드를 알려주실수 있을까요? 확인하고 답변 가능할 것 같아요😭

2021-04-06 17:44 UTC, hyunssooo requested changes
안녕하세요, 오즈! 
step2 진행하신다고 수고 많으셨습니다! 👍
connection.setAutoCommit(false); 부분이 인상깊네요 🙂
몇 가지 코멘트 남겼습니다. 참고 부탁드려요!

2021-04-06 17:44 UTC, hyunssooo commented on src/main/java/chess/domain/dao/ChessDao.java
> +        }
con.setAutoCommit(false); 👍👍👍
마지막에 con.setAutoCommit(true); 안해줘도 괜찮나요??

닫아줘야 할 것은 connection만 있는 것은 아닙니다. 
java7에 추가된 try with resources에 대해서 학습해보고 적용시켜 보면 좋을 것 같아요 :)
`이팩티브 자바 item09 try-finally 보다는 try-with-resources를 사용하라.` 를 참고하면 좋을 것 같아요.

```java
try (Connection connection = getConnection();
     PreparedStatement pstmt = connection.prepareStatement(query);
     ResultSet rs = pstmt.executeQuery()
) {
    ..
} catch (SQLException throwables) {
    ..
}
```

2021-04-06 17:44 UTC, hyunssooo commented on src/main/java/chess/domain/dto/ChessRoomDto.java
> +    private Map<PositionDto, PieceDto> chessBoard;
```suggestion
    private int roomNo;
    private Map<PositionDto, PieceDto> chessBoard;
```

2021-04-06 17:44 UTC, hyunssooo commented on src/main/java/chess/domain/dto/ChessRoomDto.java
> +
dto도 불변으로 만들어 보는 것은 어떨까요?

2021-04-06 17:44 UTC, hyunssooo commented on src/main/java/chess/service/ChessService.java
> +    }
개행으로 의미를 부여하는 것은 어떨까요? 

controller에서 서비스로 `Map<String, String>`을 파라미터로 넣어주는데 dto로 받아 보는 것은 어떨까요? 

model을 메서드로 받아서 put하고 controller에서 사용하는데 반환값으로 dto를 반환하고 map에는 controller에서 put하는 방법은 어떨까요?

2021-04-06 17:44 UTC, hyunssooo commented on src/main/java/chess/domain/piece/info/Position.java
> +    }
toString() 은 보통 디버깅용으로 사용합니다. 정해진 규칙에 따라서 작성하는 것이 좋을 것 같아요. 인텔리제이에서 생성해주는 toString()을 사용하는 것은 어떨까요?

2021-04-06 17:44 UTC, hyunssooo commented on src/main/java/chess/domain/dto/ChessRoomDto.java
> +    }
Dto의 생성자가 많아진 이유가 여러곳(controller, service, dao)에서 해당 dto를 사용하기 때문인거 같아요. 
이런 형태라면 한 곳에서 데이터가 추가된다면 다른 곳에서도 의미 없는 필드를 가지고 있을 것 같고 보통은 null이 할당될 거 같아요. 
그렇다면 동료가 실수할 여지가 늘어날 것 같습니다. 하나의 dto를 어느 레이어까지 사용할 것인지도 고민해보면 좋을 것 같아요.

2021-04-06 17:44 UTC, hyunssooo commented on src/main/java/chess/domain/dao/ChessDao.java
> +        }
```suggestion
        } catch (Exception e) {
            con.rollback();
            return 0;
        } finally {
            closeConnection(con);
        }
```

해당 부분은 전체적으로 확인 부탁 드릴게요 :)

2021-04-06 17:44 UTC, hyunssooo commented on src/main/java/chess/service/ChessService.java
> +    private ChessBoard chessBoard;
service에 도메인 객체가 필드로 존재하는 것에 대해서 고민해보면 좋을 것 같습니다. 
현재는 게임이 하나지만 게임이 여러개고 사용자가 여러명이면 어떤 문제점이 있을까요?

2021-04-08 16:03 UTC, ohjoohyung commented
> 게임을 로드했을때 서버에서 생성한 chessBoard와의 싱크를 맞춰주는 방식

chessBoard 클래스에 있는 메서드 코드입니다!
```java
public void sync(Map<PositionDto, PieceDto> chessBoard) {
        this.chessBoard.clear();
        for (PositionDto positionDto : chessBoard.keySet()) {
            Position position = Position.of(positionDto.getPosition().charAt(0), positionDto.getPosition().charAt(1));
            String pieceName = chessBoard.get(positionDto).getName();
            String pieceColor = chessBoard.get(positionDto).getColor();
            Piece piece = piece(pieceName, pieceColor);
            this.chessBoard.put(position, piece);
    }
}

private Piece piece(String pieceName, String pieceColor) {
    if (pieceName.equalsIgnoreCase("K")) {
        return new King(pieceName, Color.from(pieceColor));
    }
    if (pieceName.equalsIgnoreCase("Q")) {
        return new Queen(pieceName, Color.from(pieceColor));
    }
    if (pieceName.equalsIgnoreCase("N")) {
        return new Knight(pieceName, Color.from(pieceColor));
    }
    if (pieceName.equalsIgnoreCase("B")) {
        return new Bishop(pieceName, Color.from(pieceColor));
    }
    if (pieceName.equalsIgnoreCase("R")) {
        return new Rook(pieceName, Color.from(pieceColor));
    }
    return new Pawn(pieceName, Color.from(pieceColor));
}
```

2021-04-09 15:40 UTC, ohjoohyung commented on src/main/java/chess/domain/dao/ChessDao.java
> +        }
connection 외에도 닫아줘야하는지 전혀 몰랐습니다..😂
게다가 setAutoCommit도 false 후에 true로 다시 설정하는걸 권장하더라고요..
https://docs.oracle.com/javase/tutorial/jdbc/basics/transactions.html
알려주셔서 감사합니다!!

기존의 DAO try catch문은 try with resources 블록으로 교체하였습니다! 
다만, try with resources 블록은 catch에서 connection을 사용할 수 없기에 롤백을 위해 try with resources 블록을 한 번 더 사용했습니다. indent가 늘어나긴 했지만..😂

2021-04-09 15:40 UTC, ohjoohyung commented on src/main/java/chess/domain/dto/ChessRoomDto.java
> +    private Map<PositionDto, PieceDto> chessBoard;
앗.. 수정했습니다!

2021-04-09 15:45 UTC, ohjoohyung commented on src/main/java/chess/domain/dto/ChessRoomDto.java
> +
DTO는 불변이 아니어도 괜찮다고 알고 있어서 이렇게 작성했습니다.. 만 
역시 찾아보니까 불변으로 만들어 주면 데이터 전송 중에 변경되지 않음을 보장할 수 있다고 하더라고요..!!
지노도 같은 의미로 이렇게 리뷰 주신거 같아 불변으로 수정했습니다!

2021-04-09 15:49 UTC, ohjoohyung commented on src/main/java/chess/service/ChessService.java
> +    }
우선 map을 인자로 받는 service 메서드는 전부 dto나 값을 받도록 변경했습니다.
그리고 model을 받는 경우는 boolean을 어떻게 넘겨줄까 하다가 그냥 service에서 model을 받아 작업을 수행하자라고 생각해서 저렇게 작성했습니다ㅜㅜ 
근데 다시 보니 movePiece라는 메서드는 dto를 넘겨주고 다른 메서드를 하나 더 만들어서 boolean을 넘겨주면 되더라고요.. 바로 수정했습니다!

2021-04-09 15:50 UTC, ohjoohyung commented on src/main/java/chess/domain/piece/info/Position.java
> +    }
아.. 이거는 사용하지 않는 메서드입니다! 지우는 걸 깜빡했네요😂
알려주셔서 감사합니다!

2021-04-09 15:58 UTC, ohjoohyung commented on src/main/java/chess/domain/dto/ChessRoomDto.java
> +    }
맞아요. 여러 곳에서 사용하다보니 생성자를 많이 만들게 되었습니다.
저도 안쓰는 필드가 있는게 좀 꺼림직하지만 이 dto의 필드를 사용하는 곳이 여러 곳이다보니 다같이 사용하는 방식으로 만들었습니다.
그래서 일단 상황에 따라 다른 dto를 만들어 필드를 모두 할당할 수 있도록 바꿨는데요.
궁금한 점이 있습니다.
이렇게 dto를 여러 개 만들다보니 중복된 데이터를 가지는 dto가 존재하게 되었습니다.
예를 들어 현재 ChessRoomDto에 turn, blackScore, whiteScore를 가지고 있는데 이동에 대한 결과를 웹에 전송할 MoveResultDto도 turn, blackScore, whiteScore를 가지고 있거든요.
필드가 중복이 되더라도 dto는 모든 필드를 할당할 수 있도록 여러 개 만드는게 괜찮은가요?

2021-04-09 16:02 UTC, ohjoohyung commented on src/main/java/chess/service/ChessService.java
> +    private ChessBoard chessBoard;
같은 자원을 공유하는 경우가 발생할 수 있을 것 같습니다😂
그래서 로컬 변수로 바꾸었고 추후에 방이 여러 개 될 수 있는 상황까지 고려해서 ChessBoards라는 클래스에서 Map을 통해 방 번호에 따른 ChessBoard를 가질 수 있도록 수정하였습니다.

2021-04-11 16:01 UTC, hyunssooo approved these changes
안녕하세요 오즈 🙂 지노입니다.
방학까지 체스 미션 진행 하신다고 정말 수고 많으셨어요! 👏👏
레벨2도 잘 진행 하실거라 믿습니다! 🙂
감사합니다!

2021-04-11 16:01 UTC, merged