[4, 5단계 - 체스] 다니(이다은) 미션 제출합니다.
woowacourse/java-chess pull request #258
Opened 2021-04-04 19:56 UTC by da-nyee

안녕하세요, 휴! 다니입니다 🙌

체스 미션.. 정말 어렵네요ㅠㅠ
생각보다 PR이 더 늦어졌습니다 😥

이번 단계에서는 필수 요구사항을 중점적으로 구현했습니다!
선택 요구사항도 구현할까 고민했지만, 선택까지 구현하면 PR이 더 늦어질 것 같아 필수까지 완료하고 PR을 보냅니다!

DB DDL은 [README.md](https://github.com/da-nyee/java-chess/tree/step2/docs#db-ddl)에 정리해두었어요.
테이블을 생성할 때 이 부분을 참고해주세요!

데이터 INSERT에 관한 DML은 README에 따로 적어두지 않았어요.
따라서, 초기 테이블에 데이터를 세팅하기 위해 프로그램 실행 전 [initializePieceStatus()](https://github.com/da-nyee/java-chess/blob/step2/src/test/java/chess/dao/ChessDaoTest.java#L61), [initializeTurn()](https://github.com/da-nyee/java-chess/blob/step2/src/test/java/chess/dao/ChessDaoTest.java#L69)을 먼저 실행해주세요!

미션을 진행하면서 궁금한 점이 몇 가지 생겼는데요.
질문 드려도 괜찮을까요?!

## 궁금한 점 1.
프로그램에 DB를 추가하며 파일 구조에 대해 고민하게 됐어요.
MVC 패턴을 유지하면서 DB 로직을 추가하고 싶은데, 이를 어디에 두어야 할 지 궁금했는데요.
주변 크루들에게 물어보니 Repository Layer에 두면 된다고 해서 이곳에 DB 로직을 작성해뒀어요.
그런데, 다른 크루들의 코드를 참고하니 Service Layer도 있더라구요!
현재 제 코드는 `Controller - Repository - DB` 와 같은 구조를 가지고 있어요.
여기에 Controller - Repository 사이에 Service도 추가하는 게 좋을까요?
만약 Service가 있다면 Controller의 책임이 적어지고 구조가 조금 더 잘 나뉘어진 느낌이 들 것 같긴 해요!
하지만, 지금 단계에서 필요한 내용인지 궁금합니다!

## 궁금한 점 2.
DB Connection은 언제 종료해야 하나요?
서버가 돌아가는 동안에는 계속 DB가 유지되는 게 맞지 않나 싶어서 지금은 따로 종료하고 있지 않아요.
한편으로는, 그래도 DB 연결을 끊는 게 필요할 거 같아요.
DB 연결을 종료하는 적절한 시점이 언제인지 궁금합니다!

## 궁금한 점 3.
테스트는 랜덤으로 실행되지만, ChessDaoTest는 순차적으로 실행시키고 싶어 `@TestMethodOrder`을 추가했어요.
그런데, 테스트는 순서에 의존하면 안 된다는 생각이 들어요. 이런 방식으로 순서를 강제시켜도 괜찮은가요?

제 질문은 여기까지입니다!

이번 코드 리뷰도 잘 부탁드립니다 ✨
매번 귀한 시간 내주셔서 정말 감사합니다 🙇‍♀️❣

2021-04-06 15:53 UTC, Hue9010 requested changes
다니!! 웹 적용이 어려웠을 텐데  잘 적용해 주셨네요! 👍👍👍
질문에 대한 답변과 몇가지 피드백 남겼는데 확인하고 궁금한건 언제든 질문주세요!!
혹시나 제가 빠트린 질문이 있다면 말씀주세요!!

2021-04-06 15:53 UTC, Hue9010 commented on src/main/java/chess/dao/ChessDao.java
> +        String query = "DELETE FROM piece_status WHERE piece_position=?";
보면서 느낀건덴 테이블 네임을 piece_status가 아닌 piece로도 지어도 충분하지 않을까요? 🤔

2021-04-06 15:53 UTC, Hue9010 commented on src/main/java/chess/controller/WebUIChessController.java
> +                return "{\"status\":\"500\", \"message\":\"" + runtimeException.getMessage() + "\"}";
예외 시 500 응답 👍
프레임워크의 기능을 이용하면 좀더 깔끔히 보내는 방법도 있지만(json 형식으로 직접 작성하는 부분도 그렇고) spark는 이번 미션에서만 사용할테니 지금 방법으로 처리해주신 걸로도 충분해 보입니다 👍

2021-04-06 15:53 UTC, Hue9010 commented on src/main/resources/static/chess.js
> +    };
체스판에 DB에 저장된 상태에 맞게 체스말을 배치하는 건 `/`로 요청했을 때 뿐이군요.
`/move` 요청 후 성공해도 아무 데이터도 전송을 안해주다보니 결국엔 화면과 DB에 데이터가 따로 관리되고 있는거네요.
화면상에 작업이 커서 고민이긴 하지만 Client - Server간에 데이터를 주고 받아 처리하는 경험을 하는 측면에서 가능하다면 /move 요청 후 데이터를 받아 화면에 반영해보면 어떨까요?

말씀드린 것 처럼 Client - Server간에 데이터를 주고 받는걸 경험해보는게 목적이기 때문에 모든 걸 다 바꿀 필요는 없습니다. 전체 체스 말만 받거나 여차하면 Source, Target Piece만 받는 식으로 최소화 할 수도 있을 것 같아요. 그것도 아니라면 점수나 이번에 누구 차례인지에 대한 정보라도 좋을 것 같아요. 😉

2021-04-06 15:53 UTC, Hue9010 commented on src/main/java/chess/controller/WebUIChessController.java
> +            String jsonFormatChessBoard = GSON.toJson(stringChessBoard);
> 수직거리
> 서로 밀접한 개념은 세로로 가까이 있어야 한다. 같은 파일에 속해 있는 밀접한 두 개념은 세로 거리로 연관성을 표현한다. 단 두 개념이 서로 다른 파일에 속해 있다면 이런 규칙이 통하지 않는다.
> 변수선언
변수는 사용하는 위치에서 최대한 가까이 선언한다.

[Clean Code -형식 맞추기-](https://medium.com/@ish453525/clean-code-%ED%98%95%EC%8B%9D-%EB%A7%9E%EC%B6%94%EA%B8%B0-b6ee86a45e99) 

Line 104와 너무 멀리 떨어져 있네요. 😉

2021-04-06 15:53 UTC, Hue9010 commented on src/main/java/chess/controller/WebUIChessController.java
> +            CHESS_REPOSITORY.initializePieceStatus(stringChessBoard);
```java
            CHESS_REPOSITORY.removeAllPieces();
```
Line 46과 함께 쓰이는데 매번 지우고 다시 넣을 필요가 있나요? 🤔

2021-04-06 15:53 UTC, Hue9010 commented on src/main/java/chess/controller/WebUIChessController.java
> +            }
제가 잘못 파악한게 아니라면 대략 여기까지가 round를 세팅하는 작업인 걸로 보이네요. 이를 봤을 때는 두가지를 생각 해 볼 수 있을 것 같아요. 아래의 move까지 봤을 때 piece_status, current_turn 테이블에서 가져온 데이터로 round 내부적으로 초기화 하는 기능을 추가 할 수 있지 않을까?

지금 체스의 문제 중 하나가 WebUIChessController가 round를 상태로서 관리하고 있다는 겁니다. 즉, 여러사람이 동시에 플레이하면 하나의 round를 조작하게 되니 문제가 생길겁니다. 그러니 상태로 가지고 있지 말고 매 요청마다 piece_status, current_turn을 통해서 가져온 데이터로 round를 새로 만들면 어떨까요? 이렇게 되면 게임방도 구현 할 수 있을 것 같네요.

위 방법으로 round를 상태로 가지지 않을 수 있을 것 같다고 보긴했지만 제가 100% 이해하지 못한 상태서 답변 드린거라 무조건 바꿀 수 있는건 아닙니다. 그점은 참고 바래요. 🙏

2021-04-06 15:53 UTC, Hue9010 commented on src/test/java/chess/dao/ChessDaoTest.java
> +    }
> 궁금한 점 3.
> 테스트는 랜덤으로 실행되지만, ChessDaoTest는 순차적으로 실행시키고 싶어 @TestMethodOrder을 추가했어요.
그런데, 테스트는 순서에 의존하면 안 된다는 생각이 들어요. 이런 방식으로 순서를 강제시켜도 괜찮은가요?

dao까지 꼼꼼히 테스트 해주셨네요. 👍 
각 테스트가 독립적인게 좋기 때문에 말씀처럼 순서에 의존하지 않는게 좋답니다. 하지만 TestMethodOrder가 왜 존재할까요?? 이상적인건 모든 테스트가 독립적인게 좋긴해도 필요하면 사용하라고 제공을 하는겁니다. 😉
이걸 엄격히 지킬지는 개인 혹은 팀에 따라 다를 것 같아요. 저는 대체적으로 뭐든 `지향`하는 편이라 엄격하게 적용하는 것보다 필요에 따라서는 이와 같은 방법도 적용하는 편입니다.

다만 이 곳에 피드백을 남기는 이유가 있는데 순서를 만든 이유가 removeXXX들 때문이 맞을까요? 그렇다면 이는 스프링 기준으로는 아래와 같은 방법으로 처리 가능합니다.

> 트랜잭션
> @Test 어노테이션과 @Transactional 어노테이션을 함꼐 사용했을 경우 테스트가 끝나면 rollback 되게 처리하면 됩니다.
[[spring] spring boot test](https://joont92.github.io/spring/spring-boot-test/)

하지만 지금은 Spark이니 그에 맞는 방법이 있겠지만 이번만 사용하고 말 프레임워크를 위해 이 이상의 시간을 쓰는건 불필요하다고 봐요. 😉

2021-04-06 15:53 UTC, Hue9010 commented on docs/README.md
> +SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
마지막 라인까지 포함해서 어떤 목적으로 작성한걸까요?(최종적으론 기존 값으로 돌려 놓는 것 같지만ㅎㅎ)
가능하면 db 설정은 직접 만지지 않는게 좋습니다. 왜냐면 어렵거든요. 😳 는 반쯤 농담이지만 남들이 모르는 설정으로 인해 나중에 혹시나 설정으로 인해 문제가 생겼을 때 원인을 알기 힘들답니다.

특정 목적을 위해 이렇게 바꾸고 한다는건 결국 이러한 설정을 모르는 사람은 이 db 혹은 아래 테이블을 제대로 볼 수 없다는 얘기가 됩니다.

2021-04-06 15:53 UTC, Hue9010 commented on docs/README.md
> +  `piece_name` VARCHAR(45) NOT NULL,
모든 분께 드리고 있는 퀴즈인데 MySQL에서 VARCHAR(45)면 한글은 몇글자까지 저장 가능할까요? 😏 
엄청 중요한 퀴즈는 아니기 때문에 생각나는 답변을 주셔도 충분해요!

2021-04-09 10:17 UTC, da-nyee commented on src/test/java/chess/dao/ChessDaoTest.java
> +    }
맞아요! removeXXX 메소드들 때문에 순서를 지정해줬습니다!
아하 스프링에서는 @Test와 @Transactional을 함께 사용해서 처리가 가능하군요 😮
다음 레벨에서 테스트할 때 순서가 중요한 경우에 해당 어노테이션들을 활용해봐야겠습니다!

2021-04-09 13:27 UTC, da-nyee commented on docs/README.md
> +SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
Workbench에서 ERD를 그린 다음 Forward Engineer로 DDL을 추출했는데, 이 과정에서 작성된 내용들입니다!
저도 이게 어떤 설정인지 제대로 모른 채 그저 옮겨 적었는데요...!
무엇인지 확실히 알고 적었어야 했는데 그러질 않았네요.. 😥 바로 삭제했습니다!

2021-04-09 14:20 UTC, da-nyee commented on src/main/java/chess/dao/setting/DBConnection.java
> +    }
질문에 대한 답변 감사합니다! 🙇‍♀️ 커넥션 풀에 대해 알게 되었어요 👍
자원 해제는 `try-with-resources` 문법으로 해결했습니다!
[`43c22b7`](https://github.com/woowacourse/java-chess/pull/258/commits/43c22b77922cd9eb9cacd12ca494e653020e3f6d) 여기서 확인하실 수 있어요!

2021-04-09 14:23 UTC, da-nyee commented on src/main/java/chess/dao/setting/DBConnection.java
> +    }
질문에 대한 답변 감사합니다! 🙇‍♀️ 커넥션 풀에 대해 알게 되었어요 👍
자원 해제는 `try-with-resources` 문법으로 해결했습니다!
[`43c22b7`](https://github.com/woowacourse/java-chess/pull/258/commits/43c22b77922cd9eb9cacd12ca494e653020e3f6d) 여기서 확인하실 수 있어요 !

2021-04-09 16:47 UTC, da-nyee commented on src/main/java/chess/controller/WebUIChessController.java
> +    public static final ChessRepositoryImpl CHESS_REPOSITORY = new ChessRepositoryImpl();
프로그램 파일 구조를 고민할 때 다른 크루들의 코드를 참고했어요!
한 크루가 `Repository` 인터페이스를 만들고, 이를 `RepositoryImpl` 클래스에서 구현했더라구요.
그래서 이렇게 하는 거구나 싶어서, 저도 `ChessRepository`와 `ChessRepositoryImpl`을 만들었습니다...!

그런데, 휴가 남겨주신 두 링크들을 읽어보니 무작정 인터페이스로 추상화 시키는 게 옳은 건 아닌 거 같아요!
휴는 보통 어떻게 하시나요?? 인터페이스를 먼저 만드시나요, 아니면 클래스를 만들고 필요에 따라 추상화 하시나요?

2021-04-09 16:50 UTC, da-nyee commented on src/main/java/chess/controller/WebUIChessController.java
> +    public static final ChessRepositoryImpl CHESS_REPOSITORY = new ChessRepositoryImpl();
프로그램 파일 구조를 고민할 때 다른 크루들의 코드를 참고했어요!
한 크루가 `Repository` 인터페이스를 만들고, 이를 `RepositoryImpl` 클래스에서 구현했더라구요.
그래서 이렇게 하는 거구나 싶어서 저도 `ChessRepository`와 `ChessRepositoryImpl`을 만들었습니다...!

그런데, 휴가 남겨주신 두 링크들을 읽어보니 무작정 인터페이스로 추상화 시키는 게 옳은 건 아닌 거 같아요!
휴는 보통 어떻게 하시나요?? 인터페이스를 먼저 만드시나요, 아니면 클래스를 만들고 필요에 따라 추상화 하시나요?

2021-04-09 17:02 UTC, da-nyee commented on src/main/java/chess/controller/WebUIChessController.java
> +            CHESS_REPOSITORY.initializePieceStatus(stringChessBoard);
현재 프로그램이 동기로 작동해서 매번 지우지 않고 초기화하면 계속 레코드가 추가되더라구요..!
그래서 get 요청이 올 때마다 전체 레코드를 삭제하고 새로 추가하게 구현했습니다!

2021-04-09 18:25 UTC, da-nyee commented on docs/README.md
> +  `piece_name` VARCHAR(45) NOT NULL,
DB 테이블에 직접 값을 INSERT 해서 확인해봤어요!

```
INSERT INTO turn (current_turn) VALUES('가나다');

SELECT current_turn, LENGTH(current_turn) AS len
FROM turn
WHERE id=16;
```

결과는 아래와 같이 나왔습니다!

![korean_varchar](https://user-images.githubusercontent.com/50176238/114223183-774da780-99aa-11eb-9640-dbe2d1a032e5.PNG)

이를 통해 한글은 1글자당 3byte인 것을 알 수 있습니다.
따라서, MySQL에서 VARCHAR(45)면 한글은 총 45 / 3 == 15글자까지 저장이 가능합니다!

2021-04-10 01:57 UTC, Hue9010 commented on docs/README.md
> +  `piece_name` VARCHAR(45) NOT NULL,
퀴즈를 낸 이유가 바이트로 생각하기 쉬워서였습니다!! 😄 

과거버전(4.1 이전)을 사용하는게 아닌 이상 글자수랍니다. 아래 포스팅처럼 간단히 테스트해 보실수도 있을겁니다. 😉
[[MySql] varchar 5라면 한글은 몇 글자까지 들어갈 수 있을까?](https://namocom.tistory.com/792)

[mySql varchar 타입 질문이 있습니다.](http://www.gurubee.net/article/81342)

MySQL 얘기이기 때문에 Oracle, MsSQL등 은 다를 수 있는 점은 유의하셔야 합니다.

사실 크게 중요하지도 대단한 내용이 아닙니다. 맡는 도메인에 따라 한글을 아예 안다룰수도 있고요. 마찬가지로 시니어 분도 한글을 다룰 일 이 없었다면 인지하지 못하고 있을 수도 있습니다. 아무래도 모든 것에 관심을 가질 수는 없거든요.
이러한게 있었다는 정도만 알고 있다가 나중에 필요해지면 `한글 저장이 바이트가 아니였던거 같은데?` 하면서 그때 찾아보면 됩니다. 😉

2021-04-10 02:31 UTC, Hue9010 commented on src/main/java/chess/controller/WebUIChessController.java
> +    public static final ChessRepositoryImpl CHESS_REPOSITORY = new ChessRepositoryImpl();
스프링의 Service를 인터페이스화 하는 건 아직 저도 그게 필요했던 상황이 없어서 크게 고려치 않고 있어요.ㅎㅎ 그게 필요할 것 같은 상황이면 고려를 할 것 같아요. 
다시 생각해보니 스프링에서 Repository는 인터페이스로 만들고 구현은 스프링이 해주는(?) 구조인데 이를 차용한 걸 수도 있겠네요.  Repository 보다는 이후 스프링을 사용할 때 Service layer를 인터페이스화 시킬 필요가 있는지 정도로 봐주면 좋을 것 같아요.

스프링을 배제한 인터페이스로의 추상화 얘기라면 `인터페이스`가 필요한 상황인가를 먼저 생각해볼 것 같아요.

2021-04-10 02:33 UTC, Hue9010 commented on docs/README.md
> +SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
아닙니다. 복붙하는 과정에서 지금처럼 고려치 않은 값들이 같이 복사 될 수가 있는데 보통은 문제가 없겠지만 이 값들로 인해 생각치 못한 사이드 이펙트가 발생할 수도 있습니다. 그래서 (특히나 학습 단계면) 그냥 유의만 해주시면 됩니다! 
의도하신건지 궁금했던 겁니다. 😉

2021-04-10 03:28 UTC, da-nyee commented on src/main/resources/static/chess.js
> +    };
`/move` 요청이 성공하면 현재 턴 정보를 받아와서 다음 턴 정보로 업데이트 하도록 리팩토링 했습니다!
기분 탓인지는 모르겠는데, 이렇게 구현하니까 프로그램 속도가 약간 빨라진 것 같아요!
Client - Server 간의 데이터 전송을 경험할 수 있었습니다 ㅎㅎ 피드백 감사합니다~! 👍

2021-04-10 04:34 UTC, da-nyee commented on src/main/java/chess/controller/WebUIChessController.java
> +            }
`/chess`에서 처음에 DB로부터 pieces 정보를 가져오고, 이를 whitePieces와 blackPieces에 담아 새로운 round를 만들어주고 있어요!
이렇게 하는 방식이 piece 테이블에서 가져온 데이터로 매번 round를 새로 생성하는 게 아닌가요...?!
이 피드백을 반영하고 싶은데, 어떻게 해야할 지 감이 잘 안 와서 한번 여쭤봅니다!

2021-04-10 04:45 UTC, da-nyee commented
안녕하세요, 휴! 다니입니다 🙌

꼼꼼한 피드백과 답변들 정말 감사드립니다 💘
피드백 반영하면서 많이 배우고 공부했어요!
MySQL 관련 퀴즈를 통해서도 새로운 지식을 얻을 수 있었습니다 👍

달아주신 코멘트들에 저도 몇몇 생각과 질문들을 남겼어요!
확인해주시면 감사하겠습니다~!

이번에도 코드 리뷰 잘 부탁합니다!
항상 귀한 시간 내주셔서 감사합니다 🙇‍♀️✨

2021-04-10 17:24 UTC, Hue9010 requested changes
다니! 반영 잘 해주셨네요. 👍👍
마무리 해도 좋을 것 같지만 한가지 좀 더 개선했으면 좋을 것 같은 부분 있어서 의견남겼어요!
확인해주시고 답변 주시면 좋을 것 같아요. 😉

2021-04-10 17:24 UTC, Hue9010 commented on src/main/resources/templates/home.html
> +            <h1 id="chess-game">✨ 체스 게임 ✨</h1>
퍼블리싱 쪽이 변경사항이 바로바로 시각적으로 나타나서 은근 재밌죠. 😄

2021-04-11 09:59 UTC, da-nyee commented on src/main/java/chess/controller/WebUIChessController.java
> +            }
휴!! 이 피드백을 반영해보려고 코드를 이리저리 고쳐봤는데, Round의 결합도가 높아서 쉽지 않네요 😥

말씀하신 대로 Controller가 상태를 가지지 않게 하려고 각 요청 내에서 Round를 매번 새로 생성하게 시도해봤는데요.

특히, `/chess`에서 아래와 같이 round를 계속 새로 생성하니까 move 이후에도 round 내의 turn이 따로 변경되지 않아 무조건 하얀색 기물만 움직일 수 있고, 실제 객체 내의 값과 DB 값이 불일치하는 현상이 발생합니다 ㅠ

```
Round round = new Round(StateFactory.initialization(PiecesFactory.whitePieces()),
                StateFactory.initialization(PiecesFactory.blackPieces()),
                CommandFactory.initialCommand("start"));

round = new Round(StateFactory.initialization(new Pieces(whitePieces)),
                    StateFactory.initialization(new Pieces(blackPieces)),
                    CommandFactory.initialCommand("start"));
```

피드백을 반영해보려고 Round에 대해 고민하면서 객체간 결합도가 크면 리팩토링 하기 어렵다는 것을 알게 되었어요.

지금까지 `객체의 결합도는 낮게, 응집도는 크게 설계하라`는 내용을 머리로는 이해했지만 크게 와닿지는 않았는데요.
이번 미션을 하면서 이 내용이 왜 중요한지 직접 느껴볼 수 있었던 것 같아요.

제 코드의 경우에는 Round의 결합도가 크니까 콘솔을 웹으로 구현하면서 round의 상태를 변경하기 위해 추가해야 되는 코드가 많아지더라구요,,

객체의 결합도가 낮을수록 객체는 자유로워지니까 어떤 상황에서도 대처하기 쉬울 것 같아요.

아무튼,, 이 피드백을 반영하지 못해 너무 아쉽습니다.. 💦

2021-04-11 10:07 UTC, da-nyee commented
안녕하세요 휴!! 다니입니다 🙌

try-with-resources 피드백을 반영하고, round 피드백에 코멘트 남겼습니다!
확인해주시면 감사하겠습니다!

매번 빠른 코드 리뷰 감사합니다 🙇‍♀️💟

2021-04-11 10:39 UTC, Hue9010 approved these changes
다니! 빠르게 반영해주셨네요! 👍
이번 단계는 여기서 머지하도록 할게요. 웹 적용하시면서 고생 많으셨습니다!!
혹시 제가 놓친 질문이 있다면 알려주시고 그 외에도 궁금한건 언제든 질문 주세요. 😉
다음 단계도 화이팅입니다!!

2021-04-11 10:39 UTC, Hue9010 commented on src/main/java/chess/dao/PieceDao.java
> +        try (PreparedStatement psmt = getConnection().prepareStatement(query)) {
PieceDao 😏

2021-04-11 10:39 UTC, Hue9010 commented on src/main/java/chess/controller/WebUIChessController.java
> +            }
이건 제가 웹 적용 전 단계에서 미리 고려해서 같이 개선을 했어야 했는데 놓친것도 크네요. 😭 🙏
다음 단계부터는 웹을 고려한 환경에서 구현을 하기 때문에 이번과 같은 상황이 발생하진 않을거에요. 그런 점에서 개선을 하는 것보다 개선을 해보려다가 실패하고 무엇때문에 실패했고, 어떤게 중요한지 알게 되는게 더 큰 학습이 된다고 생각해요.

마찬가지로 현업에서도 장애를 통해 학습한다는 말도 있거든요. 더 보편적으로는 실패를 통해 성장한다고 하잖아요. 실패를 했던 경험 덕분에 그에 대한 사항은 좀더 확실히 기억하게 되죠. 특히나 (개인적으로 생각하기로)단계를 진행하면서 무언가 학습하는게 중요하지 단순히 단계를 완료하는게 중요하지 않다고 봅니다. 그런 점에서 아쉬운게 아닌 더 큰 경험을 했다고 생각해요. 👍

여담이지만 저는 예전(우테코 과정은 아니지만)에 체스에 db 적용하는 것에서 실패 했었습니다. 😆 그리고 이번 단계서 위 제안이 필수 사항도 아니라서 이미 충분히 잘해 주셨습니다. 👍👍

2021-04-11 10:39 UTC, merged

2021-04-15 08:56 UTC, da-nyee commented
# 📚 다니의 학습 로그
## [Java] try-with-resources - 3
### 내용
- [[Java] try-with-resources](https://da-nyee.github.io/posts/java-try-with-resources/)

### 링크
- [java-chess/src/main/java/chess/dao/TurnDao.java/](https://github.com/da-nyee/java-chess/blob/step2/src/main/java/chess/dao/TurnDao.java)