[4, 5단계 - 체스] 완태(김태완) 미션 제출합니다.
woowacourse/java-chess pull request #264
Opened 2021-04-09 04:53 UTC by wannte

안녕하세요 데이브! 제출에 늦었습니다.

미션을 구현함에 있어, SparkJava의 기능들을 이용해 js 없이 html 렌더링으로만 기능을 구현했습니다.
현재 하나의 게임에 대해서만 디비를 저장하고 불러오기가 가능합니다.

## api
GET /: 처음 시작화면

POST / : 게임을 시작하고, 기존 db의 정보들을 지웁니다.

POST /chess : 체스 게임 에서의 실행 로직, command를 받고 이에 따라 게임을 진행합니다. (move a2 a3)

GET /load : 디비에 저장되어 있는 커맨드들을 불러와 순서대로 게임에 적용시켜 게임을 불러옵니다.

DB의 구조는 명령어들을 순서대로 기록합니다.
![Screenshot from 2021-04-09 13-44-54](https://user-images.githubusercontent.com/49307266/114129622-e343f780-9939-11eb-8ef4-265f6698a3cd.png)

SpartkJava 규약에 맞춰 (포비의 강의에서는 Java Bean 이라고 했던 것 같습니다) getter를 가지고 있는 클래스를 만들어야 Html {{}} 와 함께 사용할 수 있었습니다. 이를 DTO로 명명하여 사용하였는데, DTO라는 명명법이 맞는지 알고 싶습니다

2021-04-12 11:35 UTC, dave915 requested changes
완태 안녕하세요! 방학 잘 보내셨나요 :)
몇가지 코멘트 남겼어요. 확인 부탁드려요! 
궁금한점 있으시면 언제든 질문 주세요!

2021-04-12 11:35 UTC, dave915 commented on src/main/java/chess/controller/CommandDAO.java
> +package chess.controller;
DAO Class 는 `persistence layer` 이기 때문에 보통 Repository 패키지 하단에 두고 있어요 :)

2021-04-12 11:35 UTC, dave915 commented on src/main/java/chess/controller/CommandDAO.java
> +        return con;
메소드 분리 하는것이 좋을 것 같아요!

2021-04-12 11:35 UTC, dave915 commented on src/main/java/chess/controller/CommandDAO.java
> +        pstmt.executeUpdate();
Connection을 사용하고 close해주지 않는다면 memory leak이 발생 할 수 있어요. 
쿼리 수행 후 Connection을 close해주세요! 

이 코멘트 적용하면서 쿼리 수행 중 오류가 나는 경우도 고려해주세요 🤔

2021-04-12 11:35 UTC, dave915 commented on src/main/java/chess/controller/web/dto/BoardDTO.java
> +public class BoardDTO {
PR메세지에 질문 주신 부분처럼 View와 Controller간의 데이터 전달 객체는 DTO로 명명하시면 됩니다 😁

2021-04-12 11:35 UTC, dave915 commented on src/main/java/chess/WebUIChessApplication.java
> +        });
```
(req, res) -> {...}
```
이 부분은 Controller내부 메소드로 분리 해보세요 :)

2021-04-12 11:35 UTC, dave915 commented on src/main/java/chess/controller/web/WebChessController.java
> +        game = new Game(BoardFactory.create());
>현재 하나의 게임에 대해서만 디비를 저장하고 불러오기가 가능합니다.

하나의 게임에 대해서만 저장 및 불러오기 가능하다고 하셨는데, 여러 게임도 가능하도록 시도해보면 좋을 것 같아요! 
이 코멘트는 꼭 반영 안 하셔도 됩니다 😁

2021-04-12 11:35 UTC, dave915 commented on src/main/java/chess/WebUIChessApplication.java
> +            return render(model, "chessboard.html");
음 전체적으로 `(req, res) -> {...}` 내부에 들어가있는 부분이 정리가 안된 것 같아요 😅

2021-04-12 14:58 UTC, wannte commented on src/main/java/chess/controller/CommandDAO.java
> +package chess.controller;
오.. 이건 처음 알았네요! :+1:

2021-04-12 14:59 UTC, wannte commented on src/main/java/chess/controller/CommandDAO.java
> +package chess.controller;
Repository 패키지 하단이라 하면 domain, view, controller 와 같은 계층을 말하는 건가요?

2021-04-12 16:26 UTC, wannte commented on src/main/java/chess/controller/CommandDAO.java
> +        pstmt.executeUpdate();
오.. 이 부분에 대해서는 검색을 하다보니 try-with-resource 를 통해서 해결할 수 있겠더라고요!

추가적인 공부를 해봐야겠어요!

2021-04-12 16:27 UTC, wannte commented on src/main/java/chess/controller/web/WebChessController.java
> +        game = new Game(BoardFactory.create());
이 부분은 내일 진행해보도록 하겠습니다 ㅎㅎ

2021-04-14 15:09 UTC, dave915 commented on src/main/java/chess/controller/CommandDAO.java
> +package chess.controller;
네 맞습니다!

2021-04-15 10:53 UTC, dave915 requested changes
완태 안녕하세요! DM으로 질문 주셨던 부분에 코멘트 남겼어요. 
확인 부탁드릴게요!

2021-04-15 10:53 UTC, dave915 commented on src/main/java/chess/service/ChessService.java
> +        return new ChessBoard(game).html();
Service에서 특정 html을 만들어서 컨트롤러에 전달 한다면, 해당 서비스는 특정 View만 사용 가능 할 것 같아요. 
Controller 와 Service Layer를 나누는 이유 중 하나로 Controller를 이용해 도메인로직이 수행되는 Service Layer와 특정 View의 의존성을 끊기 위함도 있어요. 
그렇기 때문에 이 html로 만들어서 리턴하는로직은 Controller로 옮겨야 한다고 생각해요 🤔

2021-04-15 10:53 UTC, dave915 commented on src/main/java/chess/controller/web/WebChessController2.java
> +        init();
어차피 새로 생성하는데 필드로 들고있을 이유가 없을 것 같아요 :) 
다음 레벨 진행하면서 `Thread safe` 에 관해서 한번 찾아보세요! 
```suggestion
        Game game = new Game(BoardFactory.create());
```

2021-04-15 14:39 UTC, wannte commented on src/main/java/chess/dao/CommandDao.java
> +        try (PreparedStatement pstmt = getConnection().prepareStatement(query)) {
DBConnection 의 getConnection의 try-catch문에서 connection이 닫히는 줄 알았는데, 별도로 구분해야 하나보군요!

2021-04-15 14:53 UTC, wannte commented on src/main/java/chess/service/ChessService.java
> +        return new ChessBoard(game).html();
이 부분 고민이이었는데 감사합니다~

2021-04-15 15:03 UTC, wannte commented on src/main/java/chess/controller/web/WebChessController2.java
> +        init();
move의 경우를 위해서 game을 필드로 가지고 있었던 것 같아요!
move의 경우에도 game을 새로만들어 사용하기 위해서는 load를 해오고 나서 move명령어를 실행시키고 오류가 없을 경우만 디비에 추가하는 방식을 적용시켜야 할 것 같니요 ㅜ

2021-04-17 07:34 UTC, wannte commented
안녕하세요 데이브!

## 우선 DB의 구조를 변경했어요!
```sql
CREATE TABLE room
(
    room_id   SERIAL,
    room_name VARCHAR(30) NOT NULL,
    PRIMARY KEY (room_id)
);

CREATE TABLE command
(
    command_id SERIAL,
    room_id    BIGINT UNSIGNED,
    move_from  VARCHAR(30),
    move_to    VARCHAR(30),
    PRIMARY KEY (command_id),
    FOREIGN KEY (room_id) REFERENCES room (room_id) ON DELETE CASCADE
);
```

방을 생성하고, 삭제하는 기능이 추가했습니다. 이 때, delete cascade를 사용해서, 방을 삭제할 때, 이에 해당하는 명령들 또한 자동 삭제가 됩니다.

 ## 이동 명령 입력 방식을 수정했어요.
 move a2 a3 의 방식으로 입력을 진행 했는데, from, to 를 별도로 입력 받도록 수정했어요.
 view에서 from과 to의 값을 따로 입력받는 것이 더 편할 것이라 생각해요. move a2 a3의 방식이 확장성이 더 떨어지는 구현이라 생각해요
 
## redirect와 exceptoin을 이용하여 controller로직을 간소화했어요
요청의 url이 남는 것이 불편했는데, redirect를 이용하여 해결하였고,
exception의 경우에는 sparkjava내부적으로 구현된 방식으로 편하게 관리할 수 있게 되었어요.

Command 안에 보드의 정보를 저장하는 방식을 아직 구현하지 못했는데, 이 로직의 경우에는 도메인 로직까지 조금 건드려야 될 것 같아서, 우선순위를 조금 미루는 것이 좋을까 생각해요!
자바스크립트를 끝까지 사용하지 않기를 고집해서 그런지 불편한 부분도 많았는데, 추후에는 자바스크립트의 기본적인 공부는 진행해봐야할 것 같아요

2021-04-19 15:36 UTC, dave915 approved these changes
완태 안녕하세요! 
수정하신 부분 확인했습니다.
이번 미션은 여기서 머지해도 될 것 같아요! 
혹시 추가적으로 질문이 있다면 편하게 DM주세요 :)

2021-04-19 15:36 UTC, dave915 commented on src/main/java/chess/controller/web/WebChessController.java
> +        return null;
return type을 void로 두면 안되나요?

2021-04-19 15:36 UTC, dave915 commented on src/main/java/chess/controller/web/WebChessController.java
> +        exception(DataAccessException.class, this::handleException);
👍

2021-04-19 15:36 UTC, dave915 commented on src/main/java/chess/controller/web/WebChessController.java
> +        chessService.move(roomId, request.queryParams("from"), request.queryParams("to"));
👍

2021-04-19 15:36 UTC, merged