[1, 2, 3단계 - 체스] 쿼리치(정석윤) 미션 제출합니다.
woowacourse/java-chess pull request #267
Opened 2022-03-25 07:50 UTC by meatsby

안녕하세요 철시! 쿼리치입니다. 😁
생각보다 페어랑 합이 잘 맞아서 과속해버렸네요!
따끔한 피드백 부탁드립니다! 🙇🏻‍♂️

2022-03-25 08:20 UTC, meatsby commented on src/main/java/chess/domain/board/state/BoardInitializer.java
> +    }
유일하게 10라인 요구사항을 지키지 못한 부분인데요.

```
public static BoardState initBoard() {
    Map<Integer, Rank> ranks = new HashMap<>();
    initRank1(ranks);
    initRank2(ranks);
    for (int i = 3; i < 7; i++) {
        initBlank(ranks, i);
    }
    initRank7(ranks);
    initRank8(ranks);
    return new WhiteTurn(ranks);
}
```

위와 같이 코드를 변경한다면 요구사항을 지킬 수 있었는데요.

중간에 빈칸을 삽입하는 기능을 수행하기 때문에 한 메서드 내에서 처리해야한다고 생각해서 일단은 이대로 두었습니다.

철시의 생각은 어떠신가요? 🤔

2022-03-27 07:19 UTC, pkch93 requested changes
안녕하세요~ 쿼리치~! 👋
어려운 미션이었는데 빠르게 구현해주셨네요~
몇몇 코멘트 남겼는데 확인부탁드릴께요~!

2022-03-27 07:19 UTC, pkch93 commented on src/main/java/chess/domain/piece/Pawn.java
> +                            Position.createNextPosition(position, direction, FIRST_MOVE_DISTANCE))
```java
List.of(
Position.createNextPosition(position, direction),
Position.createNextPosition(position, direction, FIRST_MOVE_DISTANCE)
)
```
위 리스트는 Pawn이 처음 이동할 수 있는 위치를 의미하는 것 같네요. 따로 static으로 정의해서 의미를 부여해도 좋을거 같아요.

2022-03-27 07:19 UTC, pkch93 commented on src/main/java/chess/domain/piece/Position.java
> +    public static boolean isValidPosition(Position position) {
현재 createNextPosition는 따로 유효성 체크가 없네요. 잘못된 Position이 애플리케이션 내에서 사용될 수도 있을텐데요. isValidPosition 체크를 외부에서 사용하도록 만들지말고 생성할때 체크하는건 어떤가요?

2022-03-27 07:19 UTC, pkch93 commented on src/main/java/chess/view/InputView.java
> +    public static String requestCommand() {
InputView가 단순 입력을 반환하기만하는데요.
입력을 Command와 인자를 넘기도록 만들면 어떨까요? ChessGame에서 파싱할 필요 없이 Input에서 파싱해서 넘기도록요~

2022-03-27 07:19 UTC, pkch93 commented on src/test/java/chess/domain/board/state/WhiteWinTest.java
> +        state = state.move(new Position("a4"), new Position("e8"));
전반적으로 BoardState 테스트의 준비과정이 잘 읽히지가 않는데요.. 아마 Board를 만들때 내부적으로 초기 Board를 모두 세팅해줘서 그런거 같은데요. 이부분을 개선해보면 어떨까요?

2022-03-27 07:19 UTC, pkch93 commented on src/main/java/chess/domain/piece/Position.java
> +    public Position(int x, int y) {
이 생성자로 Position을 생성할때는 유효성 검증은 필요없을까요?

2022-03-27 07:19 UTC, pkch93 commented on src/main/java/chess/domain/board/state/Playing.java
> +public abstract class Playing extends GameStarted {
Playing 테스트는 안보이네요. 누락일까요?

2022-03-27 07:23 UTC, pkch93 commented on src/main/java/chess/domain/board/state/BoardInitializer.java
> +    }
위 요구사항이 하나의 메서드에 하나의 일만 하자는 걸로 이해를 해서 하나의 일만 한다면 문제는 없다고 생각은 하는데요. 
위 `initRank3To6`은 2가지로 일을 수행한다고도 볼수 있지 않을까요?

1. Blank 랭크를 생성
2. 4번 Blank 랭크를 생성

위 2가지 일을 각각의 메서드로 분리하면 어떨까요? 그리고 각 메서드들이 `initRank1`, `initRank3To6`과 같이 뒤에 `1`, `3To6`의 의미가 불분명해보이는데 이를 명확히하면 어떨가요?

2022-03-28 22:02 UTC, meatsby commented on src/main/java/chess/domain/board/state/BoardInitializer.java
> +    }
세분화해서 생각해보니 철시의 말이 맞는 것 같아요!

메서드명도 `initWhitePieces` 와 같이 명확하게 수정해봤습니다!

2022-03-28 22:27 UTC, meatsby commented on src/main/java/chess/domain/board/Rank.java
> +public class Rank {
네 맞습니다! 😁

2022-03-28 22:29 UTC, meatsby commented on src/main/java/chess/domain/ChessGame.java
> +            System.out.println(e.getMessage());
재입력 기능을 구현하는 와중에 놓친 부분이 있었군요!

`OutputView` 에게 메시지를 전달하도록 수정했습니다!

2022-03-28 22:42 UTC, meatsby commented on src/main/java/chess/domain/ChessGame.java
> +public class ChessGame {
이번 페어와 대화 중에 현재 상황에서 `Controller` 를 사용하는 것이 적절한가에 대한 토론이 이루어졌는데요.

추후 웹 애플리케이션을 구현 시 해당 클래스를 `Controller` 로 보는 것이 적절한 가에 대한 의문이 있었어요.

웹 경험이 전무한 제 입장에서도 아무래도 많은 부분이 변경될 우려가 있을 것 같아 우선은 도메인으로 활용하는 것이 적절할 것 같다는 생각에 현재 구조를 유지했어요!

철시의 커멘트를 보고 다시 코드를 들여다 본 결과 아무래도 해당 클래스는 `Controller` 의 역할을 하고 있는 것 같네요.

해당 클래스를 `Controller` 로 재정의 해주는 것이 좋은 방향일까요?

2022-03-28 22:46 UTC, meatsby commented on src/main/java/chess/domain/ChessGame.java
> +        if (input.size() == 3) {
앗 좋은 생각인 거 같아요!

추가적으로 `.get()` 에 사용되던 매직넘버 역시 처리해봤어요!

2022-03-28 23:37 UTC, meatsby commented on src/main/java/chess/domain/board/Board.java
> +public class Board {
상태패턴을 적용하기 전에 사용하던 `Board` 를 그대로 사용하고 있었네요. 😅

수정했습니다!

추가적으로 `BoardTest` 도 `PlayingTest` 가 적절한 것 같아 변경해 봤어요!

2022-03-28 23:37 UTC, meatsby commented on src/main/java/chess/domain/board/state/Playing.java
> +public abstract class Playing extends GameStarted {
https://github.com/woowacourse/java-chess/pull/267#discussion_r836935581 로 변경했습니다!

2022-03-29 10:12 UTC, pkch93 commented on src/main/java/chess/domain/ChessGame.java
> +public class ChessGame {
`Controller 로 보는 것이 적절한 가에 대한 의문이 있었어요.` 에 대한 우려는 어떤것일까요?
쿼리치는 Controller를 어떻게 생각하시는지도 궁금합니다.

2022-03-29 11:14 UTC, meatsby commented on src/main/java/chess/domain/ChessGame.java
> +public class ChessGame {
제가 현재까지 이해하는 `Controller` 의 역할은 `Domain` 과 `View` 를 연결해주는 역할을 하고 있다는 건데요!

사실은 해당 클래스를 `Controller` 로 사용하는 것이 좋을 것 같다고 생각했어요.
실제로 하는 역할 역시 `Controller` 이기도 하구요.

그런데 MVC 패턴이 원래는 웹 프로그래밍에 적용되는 개념이라고 하더라구요.
MVC 패턴을 프리코스 때 처음 접해본 제 입장에선 콘솔 프로그램에서 `Controller` 를 사용하는 것은 부적절하다는 크루들의 의견에 일단은 도메인에 남겨두는 방식을 사용하게 되었어요.

아무래도 MVC 패턴에 대한 이해도나 숙련도가 부족한 탓에 이런 구조가 생겨난 것 같은데 잘못 이해하고 있는 부분이 있다면 알려주시면 감사하겠습니다!

2022-03-29 11:23 UTC, meatsby commented on src/main/java/chess/view/InputView.java
> +    public static String requestCommand() {
동의합니다! `InputView` 에서 파싱하도록 수정해봤어요!

2022-03-29 11:37 UTC, meatsby commented on src/main/java/chess/domain/piece/Direction.java
> +    }
`Direction` 내부에 사용되고 있는 방향 리스트 반환 메서드를 각 기물 클래스 내부에 정의하라는 말씀이신가요? 🤔

예를 들면 아래처럼요!
```
// Bishop.java
@Override
protected List<Direction> findPossibleDirections() {
    return List.of(Direction.NORTHEAST, Direction.SOUTHEAST, Direction.SOUTHWEST, Direction.NORTHWEST);
}
```

2022-03-29 12:39 UTC, meatsby commented on src/main/java/chess/domain/piece/Pawn.java
> +                            Position.createNextPosition(position, direction, FIRST_MOVE_DISTANCE))
`static` 으로 의미를 부여 하라는게 어떤 말씀이실까요? 🤔

2022-03-29 12:46 UTC, meatsby commented on src/test/java/chess/domain/board/state/WhiteWinTest.java
> +        state = state.move(new Position("a4"), new Position("e8"));
테스트 하기 좋은 `Board` 환경을 만들어 놓으면 좋을까요?

예를 들면, 블랙 킹과 화이트 킹만 존재하는 `Board` 같은거요!

근데 그렇게 되면 테스트를 코드가 될 것 같아 조금 걱정이에요. 🤔

2022-03-29 13:16 UTC, meatsby commented
안녕하세요 철시! 날카로운 피드백 정말 감사드립니다. 🙇🏻‍♂️

몇가지 이해되지 않는 부분들이 있어서 커멘트 댓글로 남겨봤어요!

확인해 주시면 감사하겠습니다!

2022-03-30 12:18 UTC, meatsby commented on src/main/java/chess/domain/board/state/Playing.java
> +    public BoardState move(Position start, Position target) {
`judgeWinner()` 와 `judgeTurn()` 를 `WhiteTurn` 과 `BlackTurn` 내부로 이동할 수 있을 것 같아서 추가적으로 수정해봤습니다!

2022-03-30 12:44 UTC, meatsby commented on src/main/java/chess/domain/board/state/Playing.java
> +    public BoardState move(Position start, Position target) {
불필요한 분기문을 최대한 제거해봤는데요!
철시가 말씀하신 부분을 잘 이해한건지 잘 모르겠네요. 😅

상태를 반환하던 메서드는 전부 알맞은 상태 내부로 이동하였고 기물을 이동하는 `move()` 에서는 아무리봐도 `Black` 과 `White` 의 차이를 찾을 수 없어서 일단 `Playing` 내부에 그대로 유지 중입니다. 😭

2022-03-30 13:52 UTC, pkch93 commented on src/main/java/chess/domain/ChessGame.java
> +public class ChessGame {
웹 프로그래밍에 많이 적용되기는 하지만 콘솔에서도 충분히 MVC 패턴을 적용할 수 있다고 생각이 들어요. 오히려 MVC를 적용함으로써 같은 베이스의 코드를 다양한 뷰로 표현하는데 유리하다고 생각이 드는데요. `Controller 사용이 부적절하다` 의견은 어떤것이었을까요?

2022-03-30 14:03 UTC, pkch93 commented on src/main/java/chess/domain/board/state/Playing.java
> +    public BoardState move(Position start, Position target) {
음.. 네넵 일단 위 의도는 `BlackTurn`, `WhiteTurn`이라는 상태를 두셨기 때문에 Black과 White를 판단하는 로직이 굳이 Playing에서 가질 필요가 있을까 싶어서 드린 피드백이었어요. `BlackTurn`, `WhiteTurn`에서 처리할수 있을거라 생각이 들어서요.

2022-03-30 14:06 UTC, pkch93 commented on src/main/java/chess/domain/piece/Direction.java
> +    }
네넵 각 기물 클래스 내부에서 정의하면 어떨까 싶어요. 사용처를 보니 각 기물 클래스 내부에서만 사용이 되고 지금 Direction이 꽤 비대해진 느낌인데 그 이유가 각 기물의 Direction을 모두 가지고 있기 때문이라고 생각이 들어요. 이를 분리하면 어떨까 싶었어요.

2022-03-30 14:09 UTC, pkch93 commented on src/main/java/chess/domain/piece/Pawn.java
> +                            Position.createNextPosition(position, direction, FIRST_MOVE_DISTANCE))
음.. 이부분은 제가 잘못본거같아요. static으로 따로 정의할 수가 없겠네요 ;;

2022-03-30 14:15 UTC, pkch93 commented on src/main/java/chess/domain/piece/Position.java
> +    public static boolean isValidPosition(Position position) {
위 메서드를 Position 내부에서 사용하신다는 말씀이실까요? `isValidPosition`을 `createNextPosition`에 추가해주면 어떨까 싶었어요.

2022-03-30 14:19 UTC, pkch93 commented on src/test/java/chess/domain/board/state/WhiteWinTest.java
> +        state = state.move(new Position("a4"), new Position("e8"));
test 폴더 내에 테스트 더미를 구성하면 테스트에서만 사용이 가능할꺼에요. 위 상황에 대해서 이름을 붙여주거나 아니면 굳이 initBoard로 테스트 데이터를 구성할 필요가 있을까 싶네요. 킹을 잡을수 있는 정도로만 Board를 구성해서 테스트 할 수도 있을걸로 보여서요.

2022-03-30 15:16 UTC, meatsby commented on src/main/java/chess/dao/MemberDao.java
> +public class MemberDao {
앗.. 수업 중에 추가된 사항을 같은 브랜치에 커밋하고 있었네요..
죄송합니다 ㅠㅠ 바로 수정하겠습니다!

2022-03-30 15:42 UTC, meatsby commented on src/main/java/chess/domain/piece/Direction.java
> +    }
앗 좋은 생각인 것 같아요!

처음엔 `Direciton` 에 관한 코드여서 `Direction` 내부에 존재하는 게 좋을 것 같다는 생각을 했는데 철시의 의견을 들어보니 각 기물 클래스 내부로 옮기는 게 좋을 것 같네요!

꼼꼼한 피드백 감사드립니다! 🙇🏻‍♂️

2022-03-31 10:51 UTC, meatsby commented on src/main/java/chess/domain/piece/Position.java
> +    public static boolean isValidPosition(Position position) {
현재 이동 로직을 수행하려면 잘못된 `Position` 생성 시 `null` 을 반환하거나 예외를 던져 모든 로직에서 예외를 처리해주도록 구현해야 할 것 같아요.

`null` 을 반환하게 하는 건 지양하고 싶어서 모든 로직에서 예외를 처리하도록 구현해봤는데 적절한 조치였는지 잘 모르겠네요. 😢

2022-03-31 11:08 UTC, meatsby commented on src/test/java/chess/domain/board/state/WhiteWinTest.java
> +        state = state.move(new Position("a4"), new Position("e8"));
`BlackWinTest` 와 `WhiteWinTest` 의 테스트 준비과정이 가장 파악하기 어렵다고 판단되어서 두 클래스에만 더미 보드를 만들어줬어요!

`EndTest` 에도 추가할까 고려해봤는데 아무래도 점수를 계산하려면 여러 기물이 같이 있는 상황이 좋을 것 같아 그대로 유지해봤습니다!

2022-03-31 12:27 UTC, meatsby commented on src/main/java/chess/domain/board/state/BoardState.java
> +public interface BoardState {
현재 적용하고 있는 상태 패턴이 체스판의 상태라기 보다는 체스게임의 상태라고 표현하는 것이 더 적절해보여서 GameState 로 변경해준 뒤 상태 내부에서 Board 를 관리하게 끔 재구성해봤어요!

기존에 Playing 과 End 에서 관리하던 기물 이동 기능과 점수 계산 기능 모두 Board 내부에 재배정하여 상태에서는 게임의 상태에 따라 달라져야 하는 메서드만 남겨두어 추상화하도록 노력해봤어요!

추가적으로 점수계산 시 중복되는 코드를 제거하기 위해 함수형 인터페이스를 적용해봤구요!

2022-03-31 23:08 UTC, pkch93 commented on src/main/java/chess/domain/board/state/BoardState.java
> +public interface BoardState {
Board를 분리해주셨군요 👍 다만, GameState에 추상화한 메서드들 중에 상태마다 지원하지 않는 메서드가 존재해보이네요. 이 부분은 어쩔 수 없는걸까요?

2022-03-31 23:09 UTC, pkch93 approved these changes
쿼리치 고생하셨습니다!
다음 단계 진행을 위해서 이번 단계는 이만 머지할께요.

2022-03-31 23:09 UTC, merged