[1,2,3단계 - 체스] 바니(사현빈) 미션 제출합니다.
woowacourse/java-chess pull request #276
Opened 2022-03-27 05:49 UTC by HyeonbinSa

안녕하세요! 핀! 

이번 체스 미션을 통해 인사를 드리게 되었네요. 만나뵙게 되어 영광입니다~
이번 미션에 대한 첫 번째 리뷰 요청 드립니다 ㅎㅎ 잘 부탁드리겠습니다.

소문대로 체스 미션 정말 너무 어려웠습니다... 
미션을 진행하면서 페어와 함께 다양한 의견을 나눌 수 있던 시간이었고 이전 미션보다 많은 고민을 하고 이야기했었던 미션이었습니다.

많은 피드백 부탁드리겠습니다 ㅎㅎ

오늘 하루도 잘 마무리하시고 남은 주말도 즐거운 주말되시길 바라겠습니다!!

2022-03-28 14:59 UTC, lalize requested changes
바니 안녕하세요!
체스 구현 잘해주셨어요~
몇 가지 코멘트 남겨두었으니 확인 부탁드릴게요~

2022-03-28 14:59 UTC, lalize commented on src/main/java/domain/chessboard/ChessBoard.java
> +    private void validateTargetRouteForPawn(final Position source, final Position target) {
폰의 기본 이동 규칙을 폰 내부로 옮길 수는 없을까요?

2022-03-28 14:59 UTC, lalize commented on src/main/java/domain/chessboard/ChessBoard.java
> +    private Player currentPlayer;
체스 보드는 보드만 관리하도록 하고 플레이어는 체스 게임과 같은 객체가 관리하도록 하면 어떨까요?

2022-03-28 14:59 UTC, lalize commented on src/main/java/domain/piece/WhitePawn.java
> +public class WhitePawn extends Pawn {
BlackPawn, WhitePawn을 나눠야 할 필요가 있어 보이진 않아요.

2022-03-28 14:59 UTC, lalize commented on src/main/java/domain/chessboard/ChessBoard.java
> +    public ChessBoard(final BoardGenerator boardGenerator) {
Map을 받는 게 더 명확하지 않을까요?

2022-03-29 06:43 UTC, HyeonbinSa commented on README.md
> +        - `BLACK 현재 점수 : 36.0(LOSE)`
점수 계산 규칙
- 한 번에 한 쪽의 점수만을 계산해야 한다.

이 항목을 보고 현재 차례인 Player만의 점수와 승무패 결과를 출력한다고 생각했습니다.
다시 한번 살펴보니 요구사항은 `각 진영의 점수를 출력하고 어느 진영이 이겼는지 결과를 볼  수  있어야 한다.`네요....
요구사항에 대한 파악이 미흡했던 것 같습니다. 다시 한번 생각해보고 수정하도록 하겠습니다!

2022-03-29 07:54 UTC, HyeonbinSa commented on src/main/java/domain/piece/Pawn.java
> +            return null;
구현한 `calculateAvailablePosition()` 중 `Pawn`에서 구현한 메서드에서 null을 반환해 불필요한 `null 체크` 로직이 들어갔네요;; 
말씀해주신대로 비어있는 리스트를 반환하는 것으로 수정해서 불필요한 로직을 줄일 수 있었습니다 ㅎㅎ

2022-03-29 15:28 UTC, HyeonbinSa commented on src/main/java/domain/chessboard/BoardGenerator.java
> +public interface BoardGenerator {
`BoardGenerator`라는 인터페이스를 통해 구현했던 목적은 테스트에 사용하기 위함이었습니다.

각 테스트별 커스텀해서 사용할 수 있는 Board를 생성해서 테스트를 하려고 생각했습니다. 
그래서 인터페이스로 생성하였고 아래 코드와 같이 테스트 코드에서 커스텀하여 사용하였습니다.

```java
ChessBoard chessBoard = new ChessBoard(new BoardGenerator() {
            @Override
            public Map<Position, Piece> generate() {
                Map<Position, Piece> board = new HashMap<>();
                board.put(Position.of(File.C, Rank.TWO), new Pawn(Player.WHITE));
                return board;
            }
});
```

이런 커스텀 체스 보드 없이 테스트한다면 `King`이나 `Rook`와 같은 바로 움직일 수 없는 경우 이전에 `Pawn`을 이동한다던지 몇가지 코드를 추가해야할 것 같다고 생각하는데 이럴 때 좋은 방안이 있다면 무엇이 있을지 궁금합니다

2022-03-29 15:29 UTC, HyeonbinSa commented on src/main/java/domain/piece/PieceSymbol.java
> +    Pawn("P");
`PieceSymbol`과 `PieceScore`의 상수를 대문자로 안적었네요;;
주의하도록 하겠습니다!

2022-03-29 15:44 UTC, HyeonbinSa commented on src/main/java/domain/piece/WhitePawn.java
> +public class WhitePawn extends Pawn {
`Pawn`을 `WhitePawn`, `BlackPawn`으로 나눈 이유도 두 기물별로 가지는 특성(시작하는 라인)이 달라 이를 더 명확하게 나누고자 상속 클래스로 분리해서 사용했습니다.
[DirectionGenerator](https://github.com/woowacourse/java-chess/pull/276#discussion_r837607301)에서의 이유와 비슷하다고 생각해서 나누어보았습니다.

이 부분도 다시 클래스를 살펴보면서 불필요한 클래스 분리였는지에 대한 생각에 `Pawn`에서 `Player` 정보에 따라 값을 저장하도록 수정해보았습니다.

관련해서 이렇게 클래스를 분리해서 생기는 단점이나 문제점이 무엇이 있을지 궁금하여 질문드립니다!!

2022-03-30 07:29 UTC, HyeonbinSa commented on src/main/java/domain/chessboard/ChessBoard.java
> +    private void validateTargetRouteForPawn(final Position source, final Position target) {
`Piece`의 "Target 까지의 이동할 수 있는 Position 목록"을 반환하는 메서드인 `getAvailablePositions()` 메서드를 이용해봤습니다.
`getAvailablePosition()`을 `Pawn`에서 재정의해서 이동하는지, 공격하는지에 대한 규칙 로직을 Pawn으로 옮겨보았습니다.

옮기고나니 `ChessBoard`과 `Piece`의 역할이 더 명확해졌다는 느낌을 받았습니다.

2022-03-30 07:37 UTC, HyeonbinSa commented on src/main/java/domain/chessboard/ChessBoardGenerator.java
> +            board.put(Position.of(file, rank), null);
`Piece`의 구현클래스 중 Null 값을 의미하는 `Blank`라는 클래스를 만들어서 적용해봤어요.
List<Piece>를 전체적으로 탐색하는 반목문에서 `null` 값이 포함되어 NullPointException이 발생해서 "null인지 검사하는 코드"를 작성했었습니다.
"널 오브젝트 패턴"을 적용해서 이러한 검증 로직을 줄일 수 있었습니다!! 알려주셔서 감사합니다 ㅎㅎ

하지만 여전히 `isBlank`라는 메서드를 만들어서 비어있는 값인지 확인하는 로직을 사용하도록 수정했는데 핀이 말씀해주신 "널 오브젝트 패턴"이 잘 적용된건지 확신이 서지 않네요....
추가로 고쳐야할 점이나 고려해볼 만한 내용이 있다면 말씀 부탁드리겠습니다!!

2022-03-30 07:39 UTC, HyeonbinSa commented on src/main/java/domain/chessboard/ChessBoard.java
> +    private Player currentPlayer;
말씀해주신대로 Player(Turn)을 관리하는 `ChessGame`이라는 클래스를 만들어서 적용해보았습니다.
변경된 점으로는 `ChessGame`에서 Player를 관리하고 `ChessBoard`를 가지고 있도록 작성해보았습니다.

2022-03-30 07:40 UTC, HyeonbinSa commented on src/main/java/domain/chessboard/ChessBoard.java
> +    public ChessBoard(final BoardGenerator boardGenerator) {
`BoardGenerator`를 받는 것보다 `Map`을 받는 것이 더 명확해보이네요. 수정해보았습니다!

2022-03-30 10:21 UTC, HyeonbinSa commented on src/main/java/domain/chessboard/BoardGenerator.java
> +public interface BoardGenerator {
`ChessBoard` 생성할 때 인자로 `BoardGenerator`를 받는 것이 아닌 `Map`을 전달 받는 것으로 수정하였습니다.
이 과정에서 `ChessBoard`는 이제 `BoardGenerator` 인터페이스에 대해 알지 못하니 불필요한 구현이었다고 다시 생각하였습니다.

그래서 `ChessBoardGenerator`라는 유틸 클래스를 만들어 해당 클래스에서 `Map`을 생성하는 식으로 수정해보았습니다.
`ChessBoard`와 보드 생성기를 다시 분리한 이유는 `ChessBoard` 클래스 내에 코드가 많아 생성하는 부분을 나누어 가독성을 높이고자 하였습니다.
이렇게 구현한 것에 대해 어떻게 생각하실까요??

2022-03-30 10:24 UTC, HyeonbinSa commented
안녕하세요!! 핀!

지난 첫번째 리뷰 꼼꼼하게 작성해주셔서 정말 감사합니다.
"Null Object Pattern"와 같이 새로운 것을 배우는 시간이 되었고 코드에 대해 다시 한번 생각해보는 시간이 됐습니다.

수정하는 부분이 많아지다보니 시간이 많이 걸렸던 것 같습니다. 여전히 부족한 코드지만 두번째 리뷰도 잘 부탁드리겠습니다!!

2022-03-30 16:27 UTC, lalize requested changes
바니, 안녕하세요!
몇 가지 코멘트 남겨두었으니 확인 부탁드릴게요.
궁금한 점 있으시면 DM, 코멘트 남겨주세요~

2022-03-30 16:27 UTC, lalize commented on src/main/java/domain/piece/Piece.java
> +    private final Map<Direction, List<Position>> availableMovePosition;
상태로 갖고 있어야 하나요?

2022-03-30 18:44 UTC, lalize commented on src/main/java/domain/chessboard/ChessBoardGenerator.java
> +            board.put(Position.of(file, rank), null);
NPE를 위해 null 체크를 하는 게 아닌 핵심 비즈니스 로직의 일부로  isBlank를 사용해야 하지 않나요? isBlank 메서드를 통해 확인하는 건 자연스러운 일이라고 생각해요.

2022-03-30 18:46 UTC, lalize commented on src/main/java/domain/directions/DirectionsGenerator.java
> +public interface DirectionsGenerator {
불필요한 의존성은 실제로 필요한 건 `List<Direction>`인데 `DirectionsGenerator`를 생성자로 받아서 `List<Direction>`을 생성하고 끝이라면 꼭 의존하지 않아도 된다고 생각했어요

2022-03-30 18:47 UTC, lalize commented on src/main/java/domain/directions/DirectionsGenerator.java
> +public interface DirectionsGenerator {
불필요한 의존성은 실제로 필요한 건 `List<Direction>`인데 `DirectionsGenerator`를 생성자로 받아서 `List<Direction>`을 생성하고 끝이라면 의존하지 않아도 된다고 생각했어요

2022-03-30 18:53 UTC, lalize commented on src/main/java/domain/chessboard/ChessBoard.java
> +        return board.get(source).symbolByPlayer().equals(PieceSymbol.Pawn.symbol(currentPlayer));
https://github.com/woowacourse/java-chess/pull/276#discussion_r838696280

객체 자신이 가장 잘 아는 건 객체에게 메시지를 보내는 게 좋지 않을까요?

2022-03-30 19:01 UTC, lalize commented on src/main/java/domain/chessboard/ChessBoard.java
> +        return board.get(source).symbolByPlayer().equals(PieceSymbol.Pawn.symbol(currentPlayer));
https://github.com/woowacourse/java-chess/pull/276#discussion_r838696280

Piece에게 너는 폰이니? 킹이니? 물어보는 건 자연스럽고 객체 자신이 가장 잘 아는 거라고 생각하여 메시지를 보내는 게 좋다고 생각해요.

2022-03-31 14:34 UTC, HyeonbinSa commented on gradlew.bat
> +@rem you may not use this rank except in compliance with the License.
처음 구현 했을 때 행, 열을 (Row, Column)으로 작성했다가 이후에 (Rank, File)로 수정하는 과정에서 발생한 것으로 보입니다.
다시 원복해두었고 문자열 바꾸기를 할 때 조심해도록 하겠습니다.

2022-03-31 14:34 UTC, HyeonbinSa commented on src/main/java/domain/Player.java
> +    }
`==` 비교하는 방식으로 수정하였습니다!!

2022-03-31 14:41 UTC, HyeonbinSa commented on src/main/java/utils/PieceScore.java
> +    public static final double DUPLICATE_PAWN = 0.5;
enum 내부에서 사용할 수 있도록 수정하였습니다!

2022-03-31 14:43 UTC, HyeonbinSa commented on src/main/java/utils/PieceScore.java
> +public enum PieceScore {
말씀해주신 내용을 기반으로 수정해보았습니다.
수정해보니 `List<PieceScore>`를 굳이 생성하여 사용했었던 것 같습니다. `Piece`의 symbol 정보를 통해 `PieceScore`를 가지고 오는 불필요한 코드를 줄일 수 있었습니다!

2022-03-31 15:18 UTC, HyeonbinSa commented on src/main/java/domain/piece/Piece.java
> +    }
`generateAvailablePosition ()`, `getAvailablePositions()`, `findDirection()` 이  3개의 함수 대신에 `move()`를 사용하여 줄여보았습니다.
이 외의 메서드들은 "이동 가능한 Position 목록"을 만드는 과정에서 `Piece` 구현 클래스에 사용되기 때문에 그대로 사용하였습니다.
특히 `createPositionByDirection()`과 같은 메서드는 하위 클래스에서 모두 동일하게 사용되기때문에 중복을 줄이기 위해 `Piece`에서 구현해 사용했었습니다. 
그리고`calculateAvailablePosition()`, `getDirections()`와 같이 구현 클래스에서 각각 구현해야하는 로직이 달라 추상 메서드로 작성하였습니다.
그래서 여전히 사용되는 함수가 많다고 느껴지네요...

2022-03-31 15:26 UTC, HyeonbinSa commented on src/main/java/domain/chessgame/ChessBoard.java
> +    private static final String NULL_PIECE_SYMBOL = ".";
또 놓친 코드가 있었네요... 주의하도록 하겠습니다.
요청 전에 한번 더 확인해보도록 하겠습니다.

2022-03-31 15:26 UTC, HyeonbinSa commented on src/main/java/domain/chessgame/ChessBoard.java
> +            .filter(piece -> piece.symbol().equals(PieceSymbol.KING.symbol()))
`Piece`에 `isking()`을 추가해보았습니다.

2022-03-31 15:27 UTC, HyeonbinSa commented on src/main/java/domain/Player.java
> +    public static Player otherPlayer(Player player){
static일 필요가 없었던 것 같습니다. 
그리고 미사용 코드이기도 해서 삭제하였습니다.

2022-03-31 15:29 UTC, HyeonbinSa commented on src/test/java/domain/piece/KnightTest.java
> +    @DisplayName("Knight 은 현재 위치에서 모든 방향으로 한 칸 이동할 수 있다.")
테스트 코드가 많이 미흡했던 것 같습니다.
비슷한 테스트를 하는 과정에서 `DisplayName`이나 함수명의 수정이 부족했었습니다.
주의하도록 하겠습니다.

2022-03-31 15:36 UTC, HyeonbinSa commented on src/main/java/domain/chessboard/BoardGenerator.java
> +public interface BoardGenerator {
`ChessBoard`를 반환하는 것으로 수정해보았습니다!

2022-03-31 15:51 UTC, HyeonbinSa commented
안녕하세요! 핀!

벌써 3번째 리뷰 요청을 드리네요.

이번에 리팩터링을 하면서 `Piece`의 복잡한 이동 로직을 간결하게 수정하는 부분이 정말 어려웠었습니다....
함수의 수를 줄이자니 함수 안의 코드가 많아지고 코드를 분리하니 함수가 많아지더라구요... 
그리고 미사용 메서드나 상수가 많이 남아있었던 것 같은데 주의하도록하겠습니다! 

항상 감사드리며 이번에도 부족한 코드지만 많은 피드백 부탁드리겠습니다.

2022-04-01 09:48 UTC, lalize approved these changes
바니 안녕하세요!
다음 단계 진행을 위해 이만 머지하도록 할게요!
간단히 코멘트 남겨두었으니 다음 단계에 함께 반영해주세요:)

2022-04-01 09:48 UTC, lalize commented on src/main/java/domain/piece/Piece.java
> +    public List<Position> move(Position source, Position target) {
`calculateAvailablePosition`는 Piece마다 서로 다른 구현을 가져야 할 필요가 있을까요?
이동 방향으로 source -> target 의 경로를 구하는 공통 구현을 가지면 되지 않나요? 이를 Navigation 객체에 위임해보면 어떨까요? 그러면 각 Piece들은 source -> target으로 이동하는 방향을 응답하는 추상 메서드만 구현하면 될 것 같아요.

```java
public final List<Position> move(Position source, Position target) {
  Direction direction = direction(source, target);
  return new Navigation(source, target).route(direction);
}

protected abstract Direction direction(Position source, Position target);
```

2022-04-01 09:48 UTC, lalize commented on src/main/java/domain/chessgame/ChessGame.java
> +        double blackScore = chessBoard.calculateScoreByPlayer(Player.BLACK);
ChessBoard의 책임이 너무 많은 것 같아요. Score 객체를 만들어보면 어떨까요?

```java
Score score = new Score(chessBoard);
score.white();
score.black();
```

2022-04-01 09:48 UTC, lalize commented on src/main/java/domain/piece/Piece.java
> +    }
해당 메서드를 제거하고 position에게 메시지를 보내보면 어떨까요?

2022-04-01 09:48 UTC, merged