[1,2,3단계 - 체스] 앤지(손수민) 미션 제출합니다.
woowacourse/java-chess pull request #277
Opened 2022-03-27 06:12 UTC by soominsohn

안녕하세요 또링~ 👏 
앤지입니다. 😄 

만나뵙게 되어서 영광이에요!

제 코드를 잘부탁드려요 😃

2022-03-28 19:33 UTC, jnsorn requested changes
안녕하세요 앤지! 또링입니다. 반가워요. 👋
미션 빠르게 잘 구현해주셨어요. 테스트도 꼼꼼하게 짜주셔서 놀랐습니다. 👍🏼
우선 게임 룰과 객체의 책임 위주로 코멘트 남겼으니 확인 부탁드려요. 궁금한 점은 언제든 편히 DM 주시구요!

2022-03-28 19:33 UTC, jnsorn commented on src/main/java/chess/domain/ScoreCalculator.java
> +        return defaultScore - (calculateSameFilePawnCount(pawnPositions) / PAWN_PENALTY_MINIMUM_COUNT);
현재는 같은 세로줄에 폰이 존재할 경우 각 폰의 점수가 0.5점이라 이 로직이 유효하지만, 점수가 바뀐다면 이 계산 로직을 그대로 사용할 수 있을까요? (특히, `PAWN_PENALTY_MINIMUM_COUNT`로 나누는 로직이 적절하지 않은 것 같아요.)

2022-03-28 19:33 UTC, jnsorn commented on src/main/java/chess/domain/piece/Knight.java
> +    }
Knight의 방향도 Direction에서 관리하면 어떨까요?

2022-03-28 19:33 UTC, jnsorn commented on src/main/java/chess/domain/piece/King.java
> +    private static final String WHITE_DISPLAY = "♚";
View와 관련이 깊어보이네요! domain에 view와 관련된 코드가 있다면 어떤 문제가 있을까요?

2022-03-29 11:23 UTC, jnsorn commented on src/main/java/chess/controller/ChessController.java
> +    private ChessGame progressByCommand(ChessGame chessGame, CommandDto commandDto) {
혹시 앤지가 이 부분 다시 확인해주실수 있나요? 정확한 요구사항을 모르겠네요!

2022-03-31 00:41 UTC, soominsohn commented on src/main/java/chess/domain/piece/Knight.java
> +    }
넵! Knight의 방향도 Direction에서 관리할 수 있게 Knight방향 정보를 Direction에 추가해주었습니다.
Knight의 방향을 추가하면서, Direction을 찾는 로직을 각도로 찾을 수 있게 변경해보았어요.
감사합니다 😄

2022-03-31 00:42 UTC, soominsohn commented on src/test/java/chess/domain/piece/BishopTest.java
> +    }
네! Piece객체를 생성해 비교해 보는 것보단, Position을 비교하니 테스트의 목적이 위치비교라는 것을 더 명확히 알 수 있었어요.
다른 테스트들도 수정했습니다. 감사합니다 :)

2022-03-31 00:42 UTC, soominsohn commented on src/test/java/chess/domain/piece/BishopTest.java
> +        assertThat(actual).isEqualTo(expected);
오오! 굳이 boolean 변수를 선언하지 않고도 비교할 수 있겠네요. 감사합니다!

2022-03-31 00:46 UTC, soominsohn commented on src/main/java/chess/domain/ScoreCalculator.java
> +        return defaultScore - (calculateSameFilePawnCount(pawnPositions) / PAWN_PENALTY_MINIMUM_COUNT);
그대로 사용할 수 없겠죠 😢  pawnPenaltyScore를 따로 계산해주는 메서드를 만든 후, defaultScore에서 빼주는 것으로 변경했습니다. 감사합니다 :)

2022-03-31 00:48 UTC, soominsohn commented on src/main/java/chess/domain/position/PositionUtil.java
> +public class PositionUtil {
PositionUtil은 a1~h8 과 같은 아스키캐릭터를 도메인에서 사용하는 0~7인 rank와 file값으로 바꾸어주는 역할을 가지고 있었어요.
PositionUtil보다는 PositionConverter와 같은 이름이 역할을 나타내기 더 명확할 것 같아서 변경해주었습니다.

2022-03-31 00:49 UTC, soominsohn commented on src/main/java/chess/domain/piece/ChessmenInitializer.java
> +        chessmen.addAll(initWhiteStrongMen());
stream으로 변경하였는데, 올바른 접근 방법 이었을까요? 감사합니다 😄

2022-03-31 00:51 UTC, soominsohn commented on src/main/java/chess/controller/ChessController.java
> +    private ChessGame progressByCommand(ChessGame chessGame, CommandDto commandDto) {
요구사항엔 명확하게 나와있지 않았어요. 그러나 또링의 말씀처럼 게임 진행 중 사용자가 점수를 볼 수 있는 기능이 있어야 된다는 것에 동의해요. 해당부분 수정해서 반영했습니다 😄

2022-03-31 00:58 UTC, soominsohn commented on src/main/java/chess/controller/ChessController.java
> +    private static final String END = "end";
시작, 종료 등 게임 진행에 필요한 커맨드들을 Command라는 클래스로 따로 빼주었어요! 그러나 아직 InputView와 domain 모두에서 "start"와 같은 상수가 중복 사용된다는 문제가 있네요. 

혹시 InputView에서는 사용자의 입력만 받고, 해당 입력이 "start"와 같은 유효한 상수인지는 Command에서 검증을 하는 것이 좋은지,
아니면 InputView에서도 검증하고, Command에서도 검증하는 편이 좋은지,

또링의 의견이 궁금합니다!

2022-03-31 14:58 UTC, jnsorn commented on src/main/java/chess/controller/ChessController.java
> +    private static final String END = "end";
답변을 달다가.. 문득 앤지의 의견이 궁금해졌어요! 앤지는 어떤 방법이 더 좋다고 생각하시나요?

2022-03-31 15:03 UTC, jnsorn commented on src/main/java/chess/domain/piece/ChessmenInitializer.java
> +        chessmen.addAll(initWhiteStrongMen());
엇 ㅎㅎ 제가 너무 애매하게 달았네요. 여기서 호출하는 메서드들의 중복을 의미한거였어요. 😂 (ex. initBlackStrongMen(), initWhiteStrongMen())

2022-03-31 15:32 UTC, jnsorn approved these changes
앤지! 피드백 반영해주신 부분 확인했어요. 👏🏻 
리뷰 남긴 부분에 대해 많이 고민해보신 거 같아요. ㅎㅎ 질문에 대한 답변과 추가 코멘트 남겼는데, 다음 단계 진행하면서 확인 부탁드릴게요. 궁금한 부분은 언제든 코멘트나 DM주시구요! 
다음 단계에서 만나요! 👋

2022-03-31 15:32 UTC, jnsorn commented on src/main/java/chess/domain/ScoreCalculator.java
> +    }
```suggestion
    private double calculateSameFilePawnCount(List<Position> pawnPositions) {
        return IntStream.range(0, PositionConverter.FILES_TOTAL_SIZE)
            .map(fileIdx -> extractSameFilePositionCount(pawnPositions, fileIdx))
            .filter(count -> count >= PAWN_PENALTY_MINIMUM_COUNT)
            .sum();
    }
```

2022-03-31 15:32 UTC, jnsorn commented on src/main/java/chess/domain/ScoreCalculator.java
> +        return pawnScore * penaltyPawnCount * PAWN_PENALTY_RATE;
`pawnScore`가 필요한가요?

2022-03-31 15:32 UTC, jnsorn commented on src/main/java/chess/domain/direction/Direction.java
> +    private final double degree;
각도를 이용해서 방향을 구하도록 수정하셨네요..! 👍🏼
다만, 지금 코드를 보면 굳이 각도가 필요할까라는 의문이 드네요. 오히려 가독성이 떨어지는 것 같아요. 😓 
현재 로직에서는 각도 없이도 충분히 방향을 구할 수 있을 것 같은데, 앤지는 어떻게 생각하시나요?

2022-03-31 15:32 UTC, jnsorn commented on src/main/java/chess/domain/direction/Direction.java
> +    public boolean isLShapeDiagonalDirection() {
👍🏼

2022-03-31 15:32 UTC, jnsorn commented on src/main/java/chess/domain/direction/Direction.java
> +    }
만들어둔 메서드를 활용해도 좋겠네요!

2022-03-31 15:32 UTC, jnsorn commented on src/main/java/chess/domain/piece/Pieces.java
> +    }
`findFirst()`가 맞을까요?
또, 왕이 없는 경우 사용자는 어떤 메세지를 받게 될까요?

2022-03-31 15:35 UTC, jnsorn commented on src/main/java/chess/domain/piece/King.java
> +    private static final String WHITE_DISPLAY = "♚";
넵 name이 view에 의해 변하지 않는 도메인의 속성이라면 지금과 같은 방법도 좋은 것 같아요 :) 

> 만일 view의 정책이 변경된다면, (♔와 같은 표현이 아닌 다른표현으로 체스말을 나타냄) 도메인까지 변경을 해주어야 하는 문제가 생기겠네요 😢 .

이 부분은 다음 단계 진행하면서 더 느끼실수도 있겠네요 +_+

2022-03-31 15:36 UTC, merged