[1,2,3단계 - 체스] 오찌(오지훈) 미션 제출합니다.
woowacourse/java-chess pull request #279
Opened 2022-03-27 09:06 UTC by Ohzzi

안녕하세요 철시! 저는 오찌입니다. 레벨 1 마지막 미션에서 이렇게 만나게 되어 반갑습니다 :)

확실히 선배 크루분들도 다들 체스가 레벨 1의 꽃이라고 다시 하고 싶지 않다고 하는 얘기를 해주셨었는데 그게 맞더라고요 😢 굉장히 고민할 부분도 많고, 하드 코딩 했다가 어떻게든 리팩토링 해보려고 한 부분도 많았던 것 같아요. 이번에는 우선 하드 코딩이 되더라도 기능이 돌아가도록 구현 하는 것에 집중했고, 다 구현이 완료된 뒤에 페어와 함께 시급한 부분부터 리팩토링을 했습니다! 나머지 부분은 구조를 바꾸고 싶은 부분이어서 우선 놔두었고요.

앞으로의 리팩토링 과정에서 제가 하고 싶은 부분을 조금 말씀드리면, 지난 블랙잭 미션 때 상태 패턴을 적용했었는데요, 체스 역시도 상태 패턴을 적용하면 더 깔끔하게 나올 수 있을 것 같더라고요. 아무래도 게임에는 턴이라는 개념이 있는데 인스턴스 변수의 개수를 3개 미만으로 제한하는 규칙 때문에 턴 개념을 구현은 했지만 깔끔하게 넣지는 못했거든요. 그래서 상태 패턴을 한번 적용해볼까 고민중입니다!

그리고 커맨드를 입력받고 알맞은 메서드를 실행하는 부분에서 if 분기가 너무 많은 것 같아 보기가 조금 불편하더라고요. 일단은 여러 방법을 생각해 보다가 당장에 if 분기를 없애는 것은 실패했습니다. 그러다 생각한 방법이 블랙잭에서 상태를 객체로 만들었는데, 게임 명령 역시도 객체로 만들어서 사용할 수 있겠다는(지금은 enum으로 분리했는데 인터페이스 - 구현체 구조로 만들면 if 분기가 확 줄어들 것 같아서요) 생각이 들어 해당 구조를 적용하는 것을 고려하고 있습니다! 다만 한 번도 사용해보지 못한 구조여서 효과적인 구조일까 고민이 들어요. 이런 구조를 사용하는 것이 좋을까요? 😄 

현재까지 작성한 코드에서 질문드리고 싶은 부분은 코드에 댓글 남기도록 할게요!

2022-03-27 09:15 UTC, Ohzzi commented on src/main/java/chess/Chess.java
> +        final Command command = Command.from(args[COMMAND]);
여기 부분은 자바의 main 메서드가 public static void main(String[] args) 에서 영감을 받았는데요, 전에 리뷰에서 배열의 사용은 최대한 지양하고 리스트 사용을 하는 쪽이 낫다라는 얘기를 들었습니다!(이펙티브 자바에도 해당 내용이 있고요) 그런데 생각해보면 지금 딱 원하는 인덱스에 접근하기는 배열이 더 적절할 것 같아서 배열을 사용하긴 했습니다. 철시는 어떻게 생각하시나요?

2022-03-27 09:15 UTC, Ohzzi commented on src/main/java/chess/domain/board/Position.java
> +    }
Position이 일반적으로는 new 생성자를 통해 생성되고 있는데, "move a2 a3"와 같이 받아왔을 때 파싱하는 문제 때문에 정적 팩토리 메서드도 하나 열어준 상태입니다. 이 부분에 대해 얘기를 나눠봤을 때 정적 팩토리 메서드를 열었을 때 생성자를 private으로 막는 것이 좋다는 분들도, 굳이 상관 없다 라고 하는 분들도 있었는데요, 저는 지난 번 미션때도 그렇고 일단은 생성자와 정적 팩토리 둘 다 열어놓긴 했습니다. 철시는 어떻게 생각하시나요? 차라리 생성자를 다 닫고 정적 팩토리로 다 바꿔주거나 "a2" 같은 문자열의 파싱 로직을 다른 클래스로 이동해야 하는 쪽이 좋을까요?

2022-03-27 09:15 UTC, Ohzzi commented on src/main/java/chess/domain/board/strategy/CreateCompleteBoardStrategy.java
> +    }
Entry를 C++의 페어 같이(자바에는 해당 자료구조가 없으니까요) 사용했는데, 이런 식으로 사용하는 경우가 많나요?

2022-03-27 09:15 UTC, Ohzzi commented on src/test/java/chess/domain/CachedPosition.java
> +
테스트에서 특정 포지션이 반복되기 때문에 반복되는 포지션을 캐싱해두고 사용하도록 만들었습니다!
그런데 생각해보면 메인 게임에서 사용되는 포지션도 8x8 = 64개만 나오는데요, 이 부분도 캐싱하는 쪽이 좋다고 생각하시나요?

2022-03-28 13:19 UTC, pkch93 commented on src/main/java/chess/Chess.java
> +    }
위 부분이 if 분기가 많아 불편해보인다는 부분이군요. 말씀하신대로 추상화를 통해서 처리해봐도 좋을거 같아요 :)

2022-03-28 13:23 UTC, pkch93 commented on src/main/java/chess/Chess.java
> +    private GameState gameState;
Chess 클래스가 컨트롤러의 역할을 하는듯 하네요.
컨트롤러에서 한 게임의 상태를 관리하는게 적절할까요?

2022-03-28 13:24 UTC, pkch93 commented on src/main/java/chess/Chess.java
> +        OutputView.printBoard(board.getPieces());
`OutputView.printBoard(board.getPieces());` 빼고는 컨트롤러에서 분리해도 될 로직들이네요.

2022-03-28 13:27 UTC, pkch93 commented on src/main/java/chess/domain/board/Board.java
> +    private Piece get(final Position position) {
메서드 명에 어떤걸 가져오는지 의미를 드러내주면 좋겠어요.

2022-03-28 13:31 UTC, pkch93 commented on src/main/java/chess/domain/board/Board.java
> +    }
현재 체스 말들을 Piece로 추상화해서 정의하셨는데요. 위 분기문은 지금 말의 구현이 어떤것인지 확인해서 로직을 수행하고 있어요. 정의해놓은 추상화를 활용해서 수정해볼수는 없을까요?

2022-03-28 13:37 UTC, pkch93 commented on src/main/java/chess/domain/board/Position.java
> +    }
저는 정적 팩터리 메서드를 정의했다면 굳이 생성자를 열어둘 필요는 없다고 생각해요. 객체의 라이프사이클을 관리할 때 가장 중요한게 객체 생성 시점을 최소화 하는 것이라고 생각하는데요. 최소화할수록 그 객체의 시작점을 찾기 용이하겠죠.
또한 생성자를 두고 정적 팩터리 메서드를 정의했다면 정의한 정적 팩터리 메서드 사용하도록 만드는게 맞다고 생각이 들어요.

2022-03-28 14:29 UTC, Ohzzi commented on src/main/java/chess/Chess.java
> +        final Command command = Command.from(args[COMMAND]);
지금 Command가 enum이라서 view에서 만들어서 전달하는 방법도 고려해 봤었는데요,
만약 아래 코멘트 드린대로 Command별로 객체를 추상화해서 만든다면 그 경우에도 View에서 변환해 주어야 할까요?

2022-03-28 14:39 UTC, Ohzzi commented on src/main/java/chess/domain/board/Position.java
> +    }
체스에서 일반적으로 a1 b1과 같은 형태로 위치를 사용하다 보니, 해당 방법으로 포지션을 생성하는 방식도 하나 있는게 좋다고 생각했습니다! 실제로 프로덕션에서 a1 b1 이런식으로 넣어서 생성하는 편이 더 좋을 때도 있었고요 :) 혹시 a1에 대한 파싱이 필요하다면 다른 클래스로 위임하는 것이 더 좋다는 생각을 말씀해주신 걸까요??

2022-03-28 15:42 UTC, Ohzzi commented on src/main/java/chess/Chess.java
> +    }
그럼 그렇게 한번 적용해볼게요! :)

2022-03-28 15:44 UTC, Ohzzi commented on src/main/java/chess/domain/board/Board.java
> +    private Piece get(final Position position) {
Map의 get 메서드를 한번 감싼거였는데 생각해보니 getPiece 정도가 더 적절하겠네요!

2022-03-28 15:49 UTC, Ohzzi commented on src/main/java/chess/domain/board/Board.java
> +    }
제가 정확히 이해가 안가서 그러는데, isPawn() 이나 isCommonPiece() 같은 형태를 사용하라는 말씀이신가요?

2022-03-29 10:15 UTC, pkch93 commented on src/main/java/chess/domain/board/Position.java
> +    }
이번 미션의 `a1`, `b1`과 같은 부분은 뷰와 연관되어있는 부분이 아닐까라고도 생각이 들어요.
만약 열을 알파벳이 아니라 숫자로 받아야한다는 요구사항이 추가된다면 지금 상황에서 어떻게 구현할 수 있을까요?

2022-03-29 10:24 UTC, pkch93 commented on src/main/java/chess/Chess.java
> +        final Command command = Command.from(args[COMMAND]);
추상화한 Command 객체가 입력 모델로도 볼 수 있는가에 대해서 고민이 필요할 거 같아요. 입력모델로도 사용해도 괜찮다면 변환해도 괜찮을거 같구요. Command를 도메인 영역에서 더 보호하고자 한다면 View에서는 입력받은 String을 전달하거나 입력용 객체를 반환하고 이를 도메인 영역에서 Command로 만들어 줄 수 있겠네요. 😀

2022-03-30 09:29 UTC, Ohzzi commented on src/main/java/chess/command/CommandFactory.java
> +        }
enum처럼 사용하고 싶어서 이런 식으로 만들었는데요, 원래는 stream 돌려서 하려고 했는데 move의 경우에는 생성자 파라미터가 다라서 부득이하게 if문을 사용했습니다!

2022-03-30 09:29 UTC, Ohzzi commented on src/main/java/chess/domain/piece/Direction.java
> +                .orElseThrow(() -> new IllegalArgumentException("유효하지 않은 방향입니다."));
Math 클래스의 atan2 메서드를 사용하면 각도를 구할 수 있어서 Direction을 더 쉽게 구할 수 있더라고요! 다만 Stream 안쪽이 조금 길어지는 감이 있어서요, 이정도 길이는 괜찮을까요?

2022-03-30 09:29 UTC, Ohzzi commented on src/main/java/chess/domain/piece/Pawn.java
> +    }
지금 Pawn만 다른 Piece들과 묶을 수 없는 특수한 로직으로 작동하는데요, 이 부분 때문에 걸리는 것이 있습니다.
지금 CommonPiece와 RangedPiece로 나눠놨는데, 그 두 클래스에서 calculatePathToValidate 메서드가 겹치고 있어요.
(아래에 다시 한번 표시할게요)

그래서 중복을 없애고 싶어서 생각해 봤는데, 이 메서드를 추상 메서드로 만들지 말고 Piece에서 구현한 뒤 Pawn에서 추상 메서드가 아니지만 오버라이딩 하는 방법을 생각했는데, 개인적으로는 추상 메서드가 아닌 메서드를 오버라이딩 하는 것을 그렇게 선호하지 않았거든요.

다른 방법은 추상화 단계를 한 단계 더 추가하는 방법인데, 이 방법을 쓰면 추상화 단계가 너무 많아질 것 같아서 그렇게 하고 싶은 방법은 아니구요.

그래서 오버라이딩을 하고 싶기는 한데, 결론적으로는 추상 메서드가 아닌 메서드를 오버라이딩 하는 것에 대해 어떻게 생각하시나요?

2022-03-30 09:29 UTC, Ohzzi commented on src/main/java/chess/domain/piece/common/CommonPiece.java
> +    }
이 부분이 RangedPiece와 중복되어서 위에 중복 관련 이야기를 드렸습니다!

2022-03-30 09:29 UTC, Ohzzi commented on src/main/java/chess/domain/piece/ranged/RangedPiece.java
> +
King, Knight는 방향이 맞더라도 쭉 뻗어나가지 못하고 지정된 거리만 가야 해서 RangedPiece로 뺐습니다 :)

2022-03-30 22:39 UTC, pkch93 requested changes
안녕하세요 오찌~
피드백에 여러 댓글을 남기셨는데 제가 놓쳤었네요 ㅠ 혹시 답이 없다면 DM으로도 한번 알려주세요.
추가로 피드백 드렸는데 한번 확인부탁드려요~!

2022-03-30 22:39 UTC, pkch93 commented on src/main/java/chess/domain/piece/Direction.java
> +                .orElseThrow(() -> new IllegalArgumentException("유효하지 않은 방향입니다."));
음.. 길이보다도 `Math.atan2(direction.row, direction.column) == Math.atan2(rowDifference, columnDifference)` 이 부분이 한눈에 봤을때 어떤 일을 하는지 눈에 띄지는 않네요. 별도 메서드로 의미를 넣어주면 어떨까요?

2022-03-30 22:39 UTC, pkch93 commented on src/main/java/chess/ChessLauncher.java
> +        final Command command = CommandFactory.find(args.get(COMMAND_INDEX),
Command를 만들때 검증과 인자의 위치를 찾아서 Command를 만들어주는 로직이네요.
CommandFactory 내부에서 Command를 만들때 해줄수 있지 않을까요?

2022-03-30 22:39 UTC, pkch93 commented on src/main/java/chess/command/Move.java
> +        OutputView.printBoard(movedState.getPieces());
Command를 도메인으로 두신걸로 보이네요. OutputView와 소통을 하고 있는 모양인데 적절한지 의문이네요.

2022-03-30 22:39 UTC, pkch93 commented on src/main/java/chess/domain/state/ChessState.java
> +public interface ChessState {
이 부분이 상태 패턴을 적용하신 부분으로 보이네요.
다만 Ready, Running, Finished 각각에 사용되지 않는 메서드들이 있는걸로 보여요. State에 적절한 추상화가 된건지 의심할 여지가 있어보이네요.

2022-03-30 22:39 UTC, pkch93 commented on src/main/java/chess/domain/piece/Pawn.java
> +    }
상위 클래스의 동작이 구현클래스가 다르게 가져가야한다면 오버라이딩을 통해 동작을 다르게 줘도 괜찮다고 생각해요. ㅎㅎ 혹시 비선호하시는 이유가 있을까요?

그리고 RangedPiece가 CommonPiece의 calculatePathToValidate와 isEmpty를 똑같이 구현하고 있네요. RangedPiece가 CommonPiece를 확장하는 선택지도 고려해볼 수 있지 않을까요?

2022-03-30 22:41 UTC, pkch93 commented on src/main/java/chess/Chess.java
> +    private GameState gameState;
ChessLauncher로 나눠주신거 같네요 ㅎㅎ
ChessLauncher의 run 메서드에서 ChessState를 관리하는 로직이 있는데 이것도 도메인 객체로 분리되어야하지 않을까 싶어요.

2022-03-30 22:43 UTC, pkch93 commented on src/main/java/chess/domain/board/Board.java
> +    }
지금은 추상화로 변경이 된걸로 보이네요. `isPawn`, `isCommonPiece`를 사용하기보다는 piece의 구현을 사용하는 쪽에서 모르게 사용하도록 만들면 어떨까라는 피드백이었어요~!

2022-04-01 02:10 UTC, Ohzzi commented on src/main/java/chess/command/Move.java
> +        OutputView.printBoard(movedState.getPieces());
저는 커맨드가 State 안의 상태를 변경시키는 메서드를 호출해서 게임을 진행시키는 역할이어서 컨트롤러의 책임을 일부 분리한 것으로 보았습니다. 커맨드 객체가 없어도 컨트롤러에서 바로 State를 호출하면 게임을 진행시킬 수 있어서 도메인 로직이라고는 보지 않았습니다. 철시는 이 객체를 도메인이라고 보시는 입장인가요?

2022-04-01 02:13 UTC, Ohzzi commented on src/main/java/chess/ChessLauncher.java
> +        final Command command = CommandFactory.find(args.get(COMMAND_INDEX),
그렇네요! 이 부분을 굳이 빼놓을 이유가 없네요 :)

2022-04-01 02:17 UTC, Ohzzi commented on src/main/java/chess/domain/piece/Pawn.java
> +    }
실체가 있는 메서드를 다시 구현하거나 abstract 클래스를 상속한 클래스를 다시 상속하면 하위 클래스에서 맘대로 동작을 바꿔버릴 수 있다고 생각해서, 개인적으로 상속할 수 있는 클래스나 오버라이딩 할 수 있는 메서드는 abstract만으로 한정하자 라는 나름의 규칙을 세워 둔 상태였어요.

그런데 말씀하시는걸 듣고 보니까 RangedPiece가 CommonPiece와 같은 단계에 있지 말고 상속 단계가 한 단계 더 깊은 곳에 있는 선택지도 좋을 것 같네요 :)

2022-04-01 02:17 UTC, Ohzzi commented on src/main/java/chess/domain/piece/Direction.java
> +                .orElseThrow(() -> new IllegalArgumentException("유효하지 않은 방향입니다."));
네! 그렇게 해보도록 하겠습니다. 그런데 이 때 그냥 각도를 구해준다는 의미만 들어가도 괜찮겠죠??

2022-04-01 02:22 UTC, Ohzzi commented on src/main/java/chess/domain/state/ChessState.java
> +public interface ChessState {
이 부분은 어쩔 수 없이 선택하게 된게, 결국 커맨드가 State를 진행시킨다면 State 안에서 if 문을 실행시키지 않기 위해서는 각 동작 별 메서드가 다 들어있어야 할 것 같더라고요. 그리고 사실 원래 Running 상태에서 start 메서드가 쓰이지는 않는다고 하지만 만약 Running 상태인데 콘솔에서 start 명령이 들어오면 예외 처리를 하는 등 실행할 수 없는 메서드에 대한 처리를 해줘야 하기도 하고요.
그래서 부득이하게 일단 모든 메서드를 정의해 두고 실행 불가능한 명령에서 호출하면 IllegalArgumentException(일단 콘솔에서 잘못된 명령이 들어왔다는 뜻이 되니까요)을 던지는 형태로 구상했습니다.

사실 적절한 추상화라는 개념이 되게 어렵게 느껴지긴 하네요 😢

2022-04-01 02:25 UTC, Ohzzi commented on src/main/java/chess/Chess.java
> +    private GameState gameState;
혹시 그렇다면 ChessGame 같은 객체를 한 단계 더 분리해야 한다는 말씀이신가요??

2022-04-01 08:43 UTC, pkch93 commented on src/main/java/chess/command/Move.java
> +        OutputView.printBoard(movedState.getPieces());
네넵 오찌 말도 일리가 있는거 같아요. 핵심 도메인 객체인 ChessState를 반환하걸로 봐서는 도메인 로직에 가깝지 않나라고 생각을 했었어요. 뷰에서 요청을 처리하는 것으로 생각해도 괜찮을거 같네요.

2022-04-01 08:51 UTC, Ohzzi commented on src/main/java/chess/command/Move.java
> +        OutputView.printBoard(movedState.getPieces());
ChessState를 반환한다는 측면에서는 그렇게 볼 수도 있겠네요! 혹시 그렇다면 체스 게임 클래스를 분리한 뒤에 게임 클래스 내에 필드로 상태를 두어서, void로 게임 클래스의 상태 필드를 변화시키도록 하는 방법을 쓴다면 조금 더 도메인에서 분리된다고 볼 수 있을까요? :)

2022-04-01 08:59 UTC, pkch93 commented on src/main/java/chess/domain/state/ChessState.java
> +public interface ChessState {
음.. 객체지향의 SOLID 원칙중에 리스코프 치환 원칙 (LSP)와 인터페이스 분리 원칙(ISP)을 위반하는 게 아닐까 싶어요.
추상화하신 ChessState가 결국은 시작, 플레이(이동), 끝, 결과 도출과 같은 게임 진행에 필요한 모든 것을 추상화한게 아닐까요?

참고: https://doublem.org/SOLID_LSP_ISP_DIP/

어쩌면 ChessState가 너무 많은 역할을 가지고 있어서 그런게 아닐까 싶구요. State가 꼭 필요할까라는 생각도 들긴하네요. 한번 고민해보시면 좋을거 같습니다.

2022-04-01 09:03 UTC, pkch93 commented on src/main/java/chess/domain/piece/Direction.java
> +                .orElseThrow(() -> new IllegalArgumentException("유효하지 않은 방향입니다."));
각이 같은지를 보는거 같은데 위 로직을 처음보는 사람이 이해할 수 있을 정도로 의미를 부여해주면 좋을거 같아요 ㅎㅎ

2022-04-01 09:08 UTC, pkch93 commented on src/main/java/chess/command/Move.java
> +        OutputView.printBoard(movedState.getPieces());
음.. Command를 뷰(입력) 영역으로 쓰고 싶으신거죠? 만약 그렇게 해서 뷰 영역이 도메인 영역을 침범하지 않게 만든다면 괜찮을거 같아요. 웹이나 모바일 등 표현할 수 있는 영역 (또다른 뷰 영역)에 도메인 수정 없이 그대로 사용할 수 있도록 목표로 하면 좋을거 같아요.

2022-04-01 13:29 UTC, Ohzzi commented
안녕하세요 철시 :) 리뷰 받고 설계에 대해서 고민을 좀 더 해봤어요!
다른 커밋들은 소소하게 Entry의 사용을 줄이는 부분에 대한 리팩토링과, 상수가 소문자로 되어 있던 것 등 체크하지 못하고 넘어갔던 부분에 대한 수정이고요, 가장 핵심적으로 생각한 커밋은 상태 패턴을 제거하고 게임 도메인 클래스를 만들어서 거기서 상태를 관리하는 리팩토링 커밋이에요 :)

제가 원래 상태를 GameState enum을 통해 관리중이었다가 상태 패턴을 적용했었는데요. 상태 패턴이 적용할 만 하다고 생각했는데 설계를 다시 정리해보니 Command 객체를 도입하고 나니까 굳이 상태 패턴을 적용하지 않고 이전처럼 GameState enum을 사용해서 상태를 관리하는 방법이 더 좋을 것 같더라고요. 그래서 과감하게 상태 패턴을 다 빼버리고 다시 GameState enum을 사용했습니다.

그리고 그 GameState enum과 Board까지 효과적으로 관리하기 위해 ChessGame 도메인을 만들었습니다. 이렇게 되니까 Command 객체에서는 이전처럼 도메인 객체인 ChessState를 반환할 필요 없이 execute 메서드를 void로 선언해주고 인수로 들어오는 ChessGame 객체의 메서드만(여기서도 void여서 반환값은 없습니다.) 호출해주면 되더라고요. 이렇게 정리하고 보니 추상화를 해치는 부분도 없으면서 Command를 도메인 계층과 잘 분리한 것 같다고 생각합니다! :)

리스코프 치환 원칙 (LSP)와 인터페이스 분리 원칙(ISP)을 사실 아직 잘 몰랐기 때문에 발생했던 해프닝 같아요 😭

혹시나 더 짚어주실 부분이 있다면 짚어주시면 감사하겠습니다 :)

2022-04-02 03:28 UTC, pkch93 approved these changes
고생하셨습니다 오찌! 잘 고민해주신거 같아요 👍 
오찌의 이번 단계는 마무리 할께요!

2022-04-02 03:28 UTC, merged