[1, 2, 3단계 - 체스] 유콩(김유빈) 미션 제출합니다.
woowacourse/java-chess pull request #288
Opened 2022-03-27 17:51 UTC by kyukong

안녕하세요 럿고! 체스 첫번째 PR 보냅니다.

우선, 주말까지 PR 을 보내달라고 하셨는데 기한을 넘긴점 죄송합니다.
이번 체스 미션이 저에겐 많이 어렵기도 했고 미션을 진행하면서 요구사항 우선순위를 파악하지 못해 늦어진것 같네요.....🥲
늦게 보냈는데도 불구하고 코드가 아쉬운 점이 많아 중간중간 코드를 수정할 듯 합니다...

아쉬웠던 점들과 주신 피드백을 반영하여 수정하도록 하겠습니다.
기다리고 있겠습니다. 감사합니다!

2022-03-29 14:45 UTC, ksy90101 requested changes
유콩 안녕하세요 :) 리뷰어 럿고입니다.
체스 미션 너무 잘 해주셨네요 💯 
간단한 피드백을 남겼으니 확인해주세요~

2022-03-29 14:45 UTC, ksy90101 commented on src/main/java/chess/domain/Command.java
> +    STATUS("status", (input, chessGame) -> chessGame.status(Output::printScore)),
Command에서 Output을 알고 있는게 이상해 보이는데요.
혹시 이 부분은 어떻게 방법이 없었을까요?

2022-03-29 14:45 UTC, ksy90101 commented on src/main/java/chess/domain/piece/Piece.java
> +    // TODO: pawn 방식 수정 후 board 삭제
Todo는 구현이 되었다면 삭제하면 어떨까요?

2022-03-29 14:45 UTC, ksy90101 commented on src/main/java/chess/domain/ChessGame.java
> +    public void status(final BiConsumer<String, Double> printScore) {
ObjDoubleConsumer라는 함수형 인터페이스도 있는데요.
한번 알아보시면 좋을거 같습니다 :) 다른곳도 동일합니다~

2022-03-29 14:45 UTC, ksy90101 commented on src/main/java/chess/domain/Command.java
> +        String[] commands = input.split(" ");
" "매직스트링!

2022-03-29 14:45 UTC, ksy90101 commented on src/main/java/chess/domain/board/Initializable.java
> +public interface Initializable {
👍

2022-03-30 02:46 UTC, kyukong commented on src/main/java/chess/dto/PieceDto.java
> +        names.put(new King(Color.BLACK), "♚");
안그래도 너무 하드코딩 하는 듯해 이래도 되나..🤔 싶었는데 좋은 의견 감사합니다!!! enum 으로 관리한다면 출력 형식을 바꾸고 싶을 때 어디로 가서 수정해야하는지 명확하겠군요! 

그리고 아이콘과 관련하여 질문이 있습니다! 매번 객체의 정보가 출력되는 형식에 대한 값 위치가 고민이 됩니다. 이번 미션에서는 화이트 폰은 `p`, 블랙 폰은 `P` 로 표현되는데요, 처음엔 단순히 폰의 이름이라고 생각하여 소문자를 피스 객체에 두고 변환과정을 거쳐서 getName() 으로 건네주었습니다. 근데 이것이 정말 객체가 가지고 있어야 하는 값이 맞는가 고민이 되더라구요. 객체는 그 자체로 완성되었고 그 객체가 p 또는 P 로 표현되는 것은 뷰가 존재하기 때문이라고 판단했습니다. 그래서 DTO 를 이용해서 객체와 뷰 표현값을 분리해보았는데 이런 방식으로 해봐도 될까요? 현재는 아이콘을 가지는 `Form` 객체를 생성하여 `Output -> PieceDto -> Form` 으로 가져오는 형태입니다!

2022-03-30 02:48 UTC, kyukong commented on src/main/java/chess/dto/PieceDto.java
> +    private static final Map<Piece, String> names = new HashMap<>();
헉!!! 피스의 equals 가 잘못 오버라이딩된 듯 합니다! 피스 출력 형태를 가지는 Form 객체를 생성하면서 피스 객체들의 equals 의 오버라이딩을 추가하여 해결하였습니다!

2022-03-30 02:59 UTC, kyukong commented on src/main/java/chess/domain/ChessGame.java
> +    public void status(final BiConsumer<String, Double> printScore) {
오홍!! double 을 어쩔 수 없이 wrapping 한 값을 사용했었는데 따로 함수형 인터페이스를 제공하는군요!😲 사용하고 싶은 함수형 인터페이스를 만들려고해도 이미 다 제공되어 있어서 대부분 만들어진 것을 사용하게 되네요. 정보 감사합니다!

이것과 비슷한 맥락으로 질문이 있습니다! 아직 함수형 인터페이스를 사용해본 적이 1. 테스트에서 람다식으로 값을 지정하기 위해 2. 도메인에 뷰 로직을 건네기 위해 이 두 가지밖에 없습니다. 1번의 경우에는 메인 로직이기 때문에 의미를 부여하기 위해 커스텀 함수형 인터페이스를 사용했습니다. 2번의 경우 입출력 관련 메서드를 넘기기위해 사용하기 때문에 중간 과정일 뿐 메인 로직이 아니라고 판단하여 자바에서 제공하는 기본 함수형 인터페이스를 사용합니다. 럿고는 함수형 인터페이스를 활용해야 하는 상황에서 기본 제공되는 함수형 인터페이스와 커스텀 함수형 인터페이스 중 선택하는 기준이 어떻게 되시나요? 매번 고민이 됩니다.

2022-03-30 04:38 UTC, kyukong commented on src/main/java/chess/domain/piece/Piece.java
> +    // TODO: pawn 방식 수정 후 board 삭제
피스들이 이동하고 싶은 경로가 피스들의 알맞은 이동 경로인지 확인하는 `checkMovingRange` 메서드에서 폰의 경우에만 board 정보가 필요하더라구요. 폰 하나때문에 파라미터가 하나 늘어난 것이 아쉬워 수정하려 TODO 를 남겼으나 폰은 이동할 수 있는 방법이 여러 가지가 있고 보드의 정보를 필요로 하기 때문에 어쩔 수 없이 그대로 두었습니다... 수정하면서 TODO 주석도 삭제하였습니다. 🥲

2022-03-30 06:07 UTC, kyukong commented on src/main/java/chess/domain/Command.java
> +    STATUS("status", (input, chessGame) -> chessGame.status(Output::printScore)),
Command 객체는 Controller 와 ChessGame 을 연결짓기 때문에 `controller` 패키지로 옮겨봤는데 어떤가요? 컨트롤러 패키지로 옮김에 따라 현재 보드 정보를 출력하는 `printBoard` 메서드를 Command 로 옮겼습니다!

2022-03-31 13:37 UTC, ksy90101 approved these changes
안녕하세요 :) 유콩 리뷰어 럿고입니다.
피드백 적용하시느라 고생 많으셨습니다 💯 
간단한 피드백을 좀 더 남겼으니 남은것은들 다음단계에서 진행해주세요 :) 
그럼 다음단계에서 뵙겠습니다~

2022-03-31 13:37 UTC, ksy90101 commented on src/main/java/chess/domain/board/Status.java
> +                .filter(entry -> entry.getKey().getCoordinateX().equals(position.getCoordinateX()))
이 로직을 Position에 넣으면 어떨까요?

2022-03-31 13:37 UTC, ksy90101 commented on src/main/java/chess/domain/piece/Form.java
> +                .map(form -> form.form)
form.form이라는게 어색한데요.
value나 symbol이라는 단어를 쓰는게 어떨까요?

2022-03-31 13:37 UTC, ksy90101 commented on src/main/java/chess/domain/state/Turn.java
> +public abstract class Turn extends State {
Turn이 진행중인 상태인가요?
진행중인 상태는 따로 있고 Turn은 따로 있어야 할거 같은데 어떻게 생각하실까요?

2022-03-31 13:37 UTC, ksy90101 commented on src/test/java/chess/domain/BoardTest.java
> +    void rookMoveException() {
이건 rook과 queen의 테스트 케이스 아닐까요?

2022-03-31 13:38 UTC, merged

2022-04-03 09:14 UTC, kyukong commented on src/main/java/chess/domain/board/Status.java
> +                .filter(entry -> entry.getKey().getCoordinateX().equals(position.getCoordinateX()))
매번 스트림에서 filter 를 사용하면 수많은 게터 때문에 가독성이 (무진장) 나빠졌었는데 따로 메서드를 만들면 되는군요!! 어떻게 보면 당연할 수 있겠지만 저는 떠올리지 못했네요. 🥲 좋은 의견 감사합니다!!

2022-04-03 09:28 UTC, kyukong commented on src/main/java/chess/controller/ChessController.java
> +    private static final Enterable enterable = new Enter();
아직 많이 부족해 피드백의 의도를 이해하지 못했습니다...🥲 외부에서 받아온다는 것은 `Application` 에서 생성한 `Enterable` 객체를 컨트롤러로 넘겨 인스턴스 변수로 가지고 있다는 의미일까요? 이런 방식으로 바꾼다면 현재는 `ChessController` 에서만 사용하는 `Enterable` 을 다른 곳에서도 활용하기 위해서 일까요?

2022-04-03 10:15 UTC, kyukong commented on src/main/java/chess/dto/PieceDto.java
> +public class PieceDto {
PieceDto 를 사용한다면 그저 미리 생성해둔 enum 클래스를 호출하는 형태로 밖에 만들 수 없어 BoardDto 를 생성하였습니다! Dto 객체는 실제 객체의 `사본` 을 만드는 것과 유사하다고 생각하는데 제가 이해한 것이 맞을까요?

2022-04-04 05:25 UTC, kyukong commented on src/main/java/chess/domain/state/BlackTurn.java
> +    }
처음 Turn 을 상태로 두었던 것은 검정 -> 흰색 -> 검정으로 바뀌는 과정을 자연스럽게 잇고 싶어 상태에 포함시켰습니다. Board 에서 Turn 을 가진다면 어떻게 Turn 을 관리하는지 잘 모르겠으나 일단 제가 떠오르는건 **enum 값을 가지고 있고 매번 reverse 같은 메서드를 호출**하여 바꾸는 방식 밖에 없네요...🥲 매번 두 값 중 서로 번갈아서 값이 바뀌는 과정을 자연스럽게 하기 위해 상태에 포함시켰습니다. 특정 상태에서 호출한 로직을 정상적으로 수행 후 다른 적절한 값으로 바꾸어 주기 위해서요. 

이렇게 턴 정보를 상태로 분리하고 나니 다른 이점도 따라 왔습니다. 다른 피드백 답변에도 남긴 내용이지만 기물을 옮기는 하나의 기능에 확인해야 하는 과정이 많더라구요. 1. 올바른 기물을 선택했는지(나의 기물이 맞는지) 2. 기물의 이동경로가 올바른지 3. 이동 경로에 기물이 있는지 의 과정에서 1번 색상 정보를 확인하기 과정을 턴에 두었습니다. 1,2,3번 각각 Turn, Piece, Board 에 검증 단계를 두어 각 객체에 맞는 과정만 확인하여 하나의 객체에서 수행하는 로직을 줄였습니다. 

제가 잘 이해한 것이 맞을까요? 피드백 받는 시간에 다시 여쭈어 보겠습니다. 😂

2022-04-04 05:27 UTC, kyukong commented on src/main/java/chess/domain/state/Turn.java
> +public abstract class Turn extends State {
위에 관련 답변 남겼습니다! Turn 이라는 용어가 헷갈리게 하는 것 같아 `Running` 으로 변경하였습니다!