[1, 2, 3단계 - 체스] 조조그린(조한석) 미션 제출합니다.
woowacourse/java-chess pull request #292
Opened 2022-03-28 03:57 UTC by jojogreen91

안녕하세요 희봉😀
저는 조조그린이라고 합니다 반갑습니다 :)

이번 미션을 하면서 제일 중점적으로 생각했던 부분은 객체지향적인 구조 설계였습니다.
페어와 함께 나름대로 열심히 해봤는데 어떨지 모르겠네요...😂
구조에 대한 간단한 설명 남겨놓겠습니다!

## ♟ Chess 미션 구조 설계
### Piece
<img width="743" alt="스크린샷 2022-03-28 오후 12 20 33" src="https://user-images.githubusercontent.com/82805588/160321419-550775cc-09d9-4d17-b48c-b55cdd3316a2.png">

- Piece 는 체스 보드 위에서 사용하는 기물입니다.
- 체스 기물을 게임에서 실제로 사용하는 기물인 ValidPiece 와 기물이 없는 빈칸을 의미하는 Blank 로 구분했습니다.
- Piece 는 Color 를 가지고 있고 결과를 위한 Point 를 가지고 있습니다.

### Board

- Board 는 체스 게임이 진행되는 체스 보드입니다.
- 체스 보드위 각각의 Position 에 Piece 가 mapping 되어 있는 형태로 체스 보드를 구현했습니다.
- Position 은 체스 보드위의 column 과 row 를 가지는 좌표이다.
- Board 는 게임을 위한 초기화를 할 수 있고 기물의 위치를 변경할 수 있다.

### MoveStrategy
<img width="986" alt="스크린샷 2022-03-28 오후 12 20 20" src="https://user-images.githubusercontent.com/82805588/160322280-80381a7e-2b52-49e0-97b3-f8287107e299.png">

- MoveStrategy 는 체스 각 기물의 이동전략입니다.
- Distance 는 Source Position 에서 Target Position 까지 얼마나 어떻게 했는지를 나타내는 클래스입니다.
- MovePattern 은 체스 기물의 움직임 패턴을 열거한 enum 클래스입니다.
- 각 기물의 MoveStrategy 는 Distance 와 MovePattern 을 이용해서 입력된 Target Position 으로 기물이 이동할 수 있는지 알려줍니다.

### ChessGame

- ChessGame 은 체스게임과 그 규칙을 구현한 클래스입니다.
- 게임이 진행되는 Board 와 게임의 진행 여부를 나타내는 GameSwitch 그리고 현재 차례를 나타내는 Turn 을 멤버변수로가지고 있습니다.
- 규칙에 따라서 기물을 이동시킬 수 있습니다.

### Score

- 체스 게임의 현재 상태를 나타내는 Board 를 이용해서 양 플레이어의 점수를 구하고 승패를 판별하는 클래스입니다.

---

그럼 긴장되는 마음으로 리뷰기다리고 있겠습니다..ㅋㅋ
잘부탁드려요 희봉!
감사합니다😀

2022-03-29 02:44 UTC, heebong requested changes
안녕하세요, 조조그린! 리뷰어 희봉입니다. 😄 
어려운 체스 미션을 잘 수행해주셨네요 👍 역할을 많이 나눠서 하나의 클래스가 과하게 비대해지지 않았네요
몇 가지 코멘트를 남겼습니다. 확인 부탁드려요. 궁금한 내용이 있다면 언제든 DM 주세요!

2022-03-29 02:44 UTC, heebong commented on src/main/java/chess/domain/board/Board.java
> +    public Piece movePiece(final Position source, final Position target) {
`movePiece`를 실행하고 잡힌 `Piece`를 리턴해서 사용하도록 구현하셨네요 👍 

advance 🆙 `movePiece`는 `Piece`를 이동하는 함수로 예상돼요. 하지만 리턴값으로 잡힌 `Piece`가 반환된다는건 예측하기 여려울 것 같아요. (`명령-쿼리 분리 원칙`을 검색해봅시다 😉) 만약 잡히는 `Piece`를 관리하는 객체가 따로 있다면 `movePiece`는 `void` 리턴 함수로 남고 왕이 잡혔는지는 해당 객체한테 물어볼 수 있을 것 같아요. 추가로 어떤 말들이 잡혔는지 확인도 가능하겠네요!

물론 바로 적용해보자는건 아니에요. 이런 방법도 있을 수 있다고 말씀드립니다. 다만 `명령-쿼리 분리 원칙`을 검색해보는건 추천드려요.

2022-03-30 03:13 UTC, jojogreen91 commented on src/test/java/chess/domain/game/ChessGameTest.java
> +    void pieceIsNotMovable() {
앗 에러메시지 수정하다 테스트가 깨진걸 체크 못했네요 ㅠㅠ
수정했습니다🔧

2022-03-30 03:41 UTC, jojogreen91 commented on src/test/java/chess/domain/piece/BlankTest.java
> +public class BlankTest {
piece 패키지의 클래스들에 대한 단위테스트들을 추가했습니다!

2022-03-30 03:43 UTC, jojogreen91 commented on src/main/java/chess/domain/move/PawnMoveStrategy.java
> +    public boolean isMovable(final Board board, final Position source, final Position target) {
앗 `Pawn` 만 빠졌네요ㅠ 수정했습니다🔧

2022-03-30 05:01 UTC, jojogreen91 commented on src/main/java/chess/domain/move/PawnMoveStrategy.java
> +    protected boolean isMovableToTarget(final Piece targetPiece, final Color color) {
그런것 같습니다!
`isMovableToTarget()` 을 이름을 `isCatchable()` 로 변경하고 `isMovableToTarget()` 은 `FirstRowMoveStrategy` 에만 있도록 수정했습니다.
그래서 `MoveStrategy` 도 `abstract class` 에서 `interface` 로 변경했습니다!

2022-03-30 05:07 UTC, jojogreen91 commented on src/main/java/chess/domain/move/PawnMoveStrategy.java
> +    private final static List<MovePattern> BLACK_MOVE_PATTERNS = List.of(
그러네요!
`PawnMoveStrategy` 를 `abstract class` 로 만들고 `PawnBlackMoveStrategy` 과 `PawnWhiteMoveStrategy` 각각 상속 받도록 수정하였습니다.
두개를 나누니까 더 파악하기 쉽고 좋네요!

2022-03-30 05:25 UTC, jojogreen91 commented on src/main/java/chess/domain/move/PawnMoveStrategy.java
> +        final Color color = board.getPiece(source).getColor();
수정했습니다🔧

2022-03-30 07:19 UTC, jojogreen91 commented on src/main/java/chess/domain/board/Board.java
> +    public Piece movePiece(final Position source, final Position target) {
저도 `movePiece` 의 리턴값으로 잡힌 `Piece` 를 반환하는게 예측하기 어렵지 않을까 고민하긴 했는데 마침 또 말씀해 주셔서 한번  수정해 봤습니다!
`CatchPieces` 객체를 만들어서 잡힌 `Piece` 를 관리 하도록 했고 `isKingCatch()` 로 왕이 죽었는지 확인하도록 했습니다!

2022-03-30 07:53 UTC, jojogreen91 commented on src/main/java/chess/domain/move/FirstRowMoveStrategy.java
> +    protected boolean isMovableToTarget(Piece targetPiece, Color color) {
`protected` 로 `FirstRowMoveStrategy` 를 상속하는 기물들 내부에서만 사용되는 메서드라 단위 테스트를 꼭 만들어야 될까 싶은데 그래도 만드는 게 좋을까요?
현재 상태로는 열려있지 않아서 테스트 하기도 여의치 않아서 고민이 되네요!🥲

2022-03-30 08:00 UTC, jojogreen91 commented
안녕하세요 희봉!

말씀해주신 피드백들 반영해봤고 관련된 질문과 반영 내용은 댓글로도 남겨놨습니다😀

지적해주신 부분들이 제가 고민하고 있던 지점이라 희봉 덕분에 뭔가 해결책이 보이고 더 좋은 코드가 되는것 같아서 좋네요 ㅋㅋ

감사합니다 희봉!

2022-03-30 08:09 UTC, jojogreen91 commented
안녕하세요 희봉!

말씀해주신 피드백들 반영해봤고 관련된 질문과 반영 내용은 댓글로도 남겨놨습니다😀

지적해주신 부분들이 제가 고민하고 있던 지점이라 희봉 덕분에 뭔가 해결책이 보이고 더 좋은 코드가 되는것 같아서 좋네요 ㅋㅋ

감사합니다 희봉 :)

2022-03-30 23:38 UTC, heebong approved these changes
안녕하세요, 조조그린! 리뷰어 희봉입니다. 
피드백을 잘 반영해주셨네요! 코드가 더 깔끔해졌네요 👍 
1단계는 여기서 머지하도록 하겠습니다. 몇 가지 코멘트를 남겼는데요, 2단계를 진행하면서 확인 부탁드립니다. 언제든 궁금한 점이 있다면 DM 아시죠? 😄 그럼 2단계에서 만나요~

2022-03-30 23:38 UTC, heebong commented on src/test/java/chess/domain/move/PawnMoveStrategyTest.java
> +        assertThat(pawnBlackMoveStrategy.isMovable(board, source, target)).isTrue();
`PawnMoveStrategy` 테스트지만 현재 테스트는 `PawnBlackMoveStrategy`에 대한 테스트로 보여져요. 
`PawnBlackMoveStrategy`와 `PawnWhiteMoveStrategy`는 각각 테스트로 만들면 더 확인하기 쉽고 관리하기 좋을 것 같아요.
`PawnMoveStrategy`는 어떤 기능을 테스트해야할지 생각해봅시다 😄

2022-03-30 23:38 UTC, heebong commented on src/main/java/chess/domain/board/Board.java
> +        for (int i = 0; i < columns.length; i++) {
향상된 for문(enhanced for)으로 변경할 수 있겠네요 🙂

2022-03-30 23:38 UTC, heebong commented on src/main/java/chess/domain/board/Board.java
> +        catchPieces.addPiece(targetPiece);
인텔리J에서 확인해보면 `targetPiece` 부분에 경고가 뜰겁니다. `targetPiece`가 `null`일 수 있다는 경고에요. 왜 경고가 뜨는지 알아보고 해결해봅시다. 😄

2022-03-30 23:38 UTC, heebong commented on src/main/java/chess/domain/move/BishopMoveStrategy.java
> +        return isMovableToTarget(board.getPiece(target), board.getPiece(source).getColor());
디미터 법칙에 대해 생각해봅시다 🙂

2022-03-30 23:38 UTC, heebong commented on src/main/java/chess/domain/board/Board.java
> +    public void movePiece(final Position source, final Position target, final CatchPieces catchPieces) {
`movePiece`에 대한 테스트가 없네요

2022-03-30 23:38 UTC, heebong commented on src/main/java/chess/domain/board/CatchPieces.java
> +    public void addPiece(final Piece piece) {
테스트가 필요해보입니다 😄

2022-03-30 23:38 UTC, heebong commented on src/main/java/chess/domain/board/CatchPieces.java
> +            blackPieces.add(piece);
코드에 `if (color == BLACK) { ... }` 부분이 많이 보여요. 블랙인지 확인하고 아니라면 화이트 로직을 실행하죠.
하지만 `COLOR`에는 `BLACK`과 `WHITE`만 있는게 아니에요. `BLACK`이 아닌 경우 모두 화이트 로직을 실행할 것으로 보입니다.
이게 의도한 로직이라면 테스트코드가 있으면 좋겠어요.

2022-03-30 23:38 UTC, merged