[1, 2, 3단계 - 체스] 아스피(신동석) 미션 제출합니다.
woowacourse/java-chess pull request #305
Opened 2022-03-28 07:27 UTC by shindong96

안녕하세요 던 :)
체스 미션 리뷰를 부탁드리게 된 아스피입니다!
바쁘신 시간내어 피드백 해주시는만큼 열심히 하겠습니다! 아직 많이 초보라 부족하지만 잘 부탁드리겠습니다.

악명 높은 미션인만큼 많은 고민이 있었던 거 같아요. Piece가 Position을 가지고 있을 것인가와 같은 여러 고민이 있었는데 페어랑 열심히 해결하려고 했습니다. README에 행동에 초점을 맞춰서 구현하기라는 목표를 적어두고 메세지를 던지는 식의 구현을 통해 해보려고 하였습니다. 

피드백 기다리겠습니다!
다시 한 번 잘 부탁드립니다!

2022-03-29 16:30 UTC, gch01410 requested changes
안녕하세요 아스피! 리뷰어 던입니다~
객체 관계가 잘 잡혀있네요! 👍 코멘트 할 부분이 딱히 보이지않았습니다.
piece마다 MovingStrategy를 갖고 있도록 해도 좋을 것 같아요!
간단한 코멘트 남겼으니 확인부탁드려요~

2022-03-29 16:30 UTC, gch01410 commented on src/main/java/chess/domain/ChessGame.java
> +    }
List안에 List가 있어서 코드이해가 쉽지않네요..;;
가독성 좋도록 리팩토링 해볼 수 있을까요~?

2022-03-29 16:30 UTC, gch01410 commented on src/main/java/chess/domain/ChessGame.java
> +    }
킹이 죽으면 턴을 종료처리하도록 구현하셨군요! 괜찮은 방법이네요

2022-03-29 16:30 UTC, gch01410 commented on src/main/java/chess/domain/piece/King.java
> +	private static final List<Direction> MOVABLE_DIRECTIONS = List.of(
이 값은 사용안하고 있네요! 사용안하는 변수는 삭제해주세요!

2022-03-29 16:30 UTC, gch01410 commented on src/test/java/chess/domain/BoardTest.java
> +public class BoardTest {
정상적으로 이동이 되었는지도 테스트해봐야하지 않을까요~?

2022-03-29 16:30 UTC, gch01410 commented on src/test/java/chess/domain/ChessGameTest.java
> +public class ChessGameTest {
ChessGame이 말들을 잘 이동시키는지도 테스트 작성해볼 수 있을 것 같아요!

2022-03-29 16:30 UTC, gch01410 commented on src/main/java/chess/domain/piece/Queen.java
> +	);
piece가 이동전략을 알고 있는것 좋습니다!

2022-03-30 04:47 UTC, shindong96 commented on src/main/java/chess/domain/ChessGame.java
> +    }
헉 제가 push를 덜 한 상태에서 리뷰요청을 했네요ㅜㅜ 수정했습니다!

2022-03-30 04:48 UTC, shindong96 commented on src/main/java/chess/domain/piece/King.java
> +	private static final List<Direction> MOVABLE_DIRECTIONS = List.of(
push를 안한 상태로 요청드렸네요ㅜㅜ죄송합니다!

2022-03-31 00:14 UTC, shindong96 commented on src/main/java/chess/view/InputView.java
> +    private static final String STATUS = "status";
수정했습니다!

2022-03-31 00:21 UTC, shindong96 commented
안녕하세요 던, 아스피입니다 :)
피드백 너무 감사드립니다!!

던의 피드백을 받아 코드를 수정해보았습니다. 또, 페어와 피드백을 공유하여 Controller에 관한 면도 수정해보았는데 괜찮은지 모르겠네요!

처음에는 이동전략을 인터페이스를 이용하려다가 굳이 그렇게 하지 않았습니다. 지금 형태에서 추상화를 한번 더 하는 정도가 적당하다고 판단되어 그렇게 해보았어요!

피드백 기다리겠습니다. 감사합니다!

2022-03-31 15:53 UTC, gch01410 approved these changes
안녕하세요 아스피!
처음부터 객체 관계를 깔끔하게 설계해주셔서 이번에도 코멘트할 부분이 딱히 보이진 않네요 💯 💯 
컨트롤러와 자료구조에 대해 간단한 코멘트 남겼으니 확인 부탁드립니다.
이번 단계는 여기서 머지하도록 하겠습니다.
다음 단계에서 뵙겠습니다!

2022-03-31 15:53 UTC, gch01410 commented on src/main/java/chess/controller/Controller.java
> +    private void executeCommand(Map.Entry<Command, List<Square>> commands) {
프로그램 전반적으로 Map.Entry를 많이 사용하고 있네요~
보통 Map.Entry는 단독으로 잘 사용하지않아요~
Map.Entry를 사용한 이유를 알 수 있을까요?

2022-03-31 15:54 UTC, merged