[1, 2, 3단계 - 체스] 차리(이찬주) 미션 제출합니다.
woowacourse/java-chess pull request #307
Opened 2022-03-28 07:33 UTC by cjlee38

안녕하세요, 던! 먼저, 부족한 코드 리뷰해주셔서 감사하다는 말씀 먼저 드립니다 ☺️

이번 체스미션은 꽤나 까다로웠는데요. 객체에게 책임을 적당히 부여하면서 동시에 복잡한 로직을 수행하려니, 아마 여러 부분에서 많이 놓쳤을 것이라 생각이 듭니다 😢 

페어프로그래밍을 진행하면서, 페어와 함께 리뷰어분께 여쭐 질문을 리스트업 해봤는데, 한번 확인해보시고 말씀주시면 감사하겠습니다!

## 1. View의 static 메소드 사용
이번 체스미션 뿐만 아니라, 예전부터 갖고 있었던 의문점인데요. View를 필드가 없는 instance로 만들어야하는지 or 혹은 모두 static 메소드로 사용해도 괜찮은지? 가 첫 번째 질문입니다. 제 개인적인 생각으로는, 어떠한 메소드는 static이라는 키워드를 붙이는 순간, "이 메소드는 필요한 모든 곳에서 사용될 수 있다" 라는 의미를 가진다고 생각하는데요. 저희가 미션을 진행하면서 만드는 어플리케이션의 경우, 향후 웹으로 전환될 가능성을 배제할 수 없고, 이 때 view는 특정 객체가 가져야 하는 항목이므로 항상 instance로서 사용해왔습니다. 하지만 종종 static 메소드로 만드시는 분들도 계셔서 여쭤봤는데, "view는 상태가 없으니 static으로 만들어도 무방한 것 같다" 라는 답변을 받았습니다. 하지만 저는 여전히 제 생각쪽으로 무게가 실리는데, 던의 생각은 어떠하신지 여쭙고 싶습니다!

## 2. Point(혹은 Position)의 위치.
현재 코드상으로는 Board라는 객체가 Map<Point, Piece>의 형태로 체스말들의 위치를 관리하고 있습니다. 하지만 개념적으로 본다면 말의 입장에서, 본인이 명령받은 위치로 이동하는게 자연스러우므로 Piece가 Point를 갖는게 더욱 타당하다고 느껴집니다.  그럼에도 불구하고, 만약 List<Piece>로 말을 관리하고, 말이 위치값을 갖는다고 가정한다면, 특정 위치값에 존재하는 말들의 정보를 얻어내기 위해서 모든 리스트를 반복해야 한다는 불상사가 생기는데요(특정위치의 말을 얻어내기, 특정위치가 비었는지 확인하기 등..) 이 점이 너무 성능 상 크리티컬하게 작용할 것 같아 결국 Board가 위치값을 관리하도록 수정하였는데, 그러다 보니 Piece는 단순히 "계산기" 역할 밖에 하지 못하는 것 같아 어색하게만 느껴집니다. 던은 Piece가 Point를 관리하는 것에 대해서 어떻게 생각하시나요?

## dto에서의 포매팅
현재 입력받은 명령어는, Command라는 클래스에서 해석하여 함수형 인터페이스로 상태패턴으로 구성된 GameState를 실행하도록 구조가 작성되어 있습니다. 한편,  주어진 요구사항에서는 status라는 명령어를 사용하면 현재 각 팀(컬러)가 갖고 있는 말들의 점수를 계산하여 이를 보여줘야 합니다. start, end, move의 명령어의 경우 실행한 결과에 대해서 어떠한 값을 view로 돌려줄 필요가 없으므로 void로 처리할 수 있지만, status의 경우 특정 값을 돌려줘야하므로 서로 다른 메소드 시그니쳐를 갖게됩니다.

이를 해결할 첫 번째 방법은 if문으로 분기점을 세우는 것인데요. if문을 사용할 경우 1) 'status' command가 내부에서 아무런 로직도 수행하지 않게 되고, 2) controller level에서 command가 'status'인지 확인하는 것이 도메인 로직에 가깝고, 3) 앞으로 또 다른 값을 요구하는 명령어가 추가될 경우 또 다시 if문을 만들어줘야 한다는 점. 이 세 가지로 인해 if문을 사용하지 않고 다른 방법을 차용했습니다.

그 방법이 "모든 명령어가 실행될 때마다" Response라는 dto를 만들어 view로 넘겨줄 수 있도록 처리하는 것인데, 이렇게 될 경우 response 또한 메소드시그니쳐를 맞춰주어야 하므로 String으로 return할 수밖에 없어, dto에서 출력문에 관한 formatting까지 담당하고 있는 상황입니다. 이 부분이 적절하지 않다고 느껴지는데, 별다른 해결 방법을 찾지 못하여, 혹시 던이 보시기에 괜찮은지, 괜찮지 않다면 다른 방법이 있는지 조언해주시면 감사하겠습니다!

## 4. passing(wraping?) method의 테스트
초기에 페어프로그래밍을 진행할 때에는 각각의 말들이 움직이는 방법에 대해서 관리하도록 되어있었습니다. 그런데 각자 헤어지고나서 다시 살펴보니 공통되는 부분이 너무 많다고 느껴져서, 이를 추상화하여 MovingStrategy를 만들었습니다. 그런데 만들고보니 불편한 점이 두 가지가 생겼는데요. 첫 째는, piece 자체가 하는 일이 거의 없다시피 적어졌다는 것이고, 둘 째는, piece의 move를 테스트해야하는가, 아니면 MovingStrategy를 테스트해야하는가 에 대한 의문점이 들었습니다. MovingStrategy는 조합에 따라 셀 수 없이 많은 조건이 생길 수 있는데, 실질적으로 이를 사용하는 쪽인 piece가 기준에 따라 명확하게 분류되어 있다보니, 기존의 piece관련 테스트를 MovingStrategy로 옮겨야할 필요성을 느끼지 못하여 그대로 두었습니다. (테스트 커버리지 자체는 100% class, 100% method, 99% line 입니다). 이러한 상황에서, MovingStrategy에 대한 별도의 테스트를 만들 필요가 있을까요?

----

정신없이 미션을 진행하다보니 자잘한 실수가 많을 것으로 예상됩니다 ㅠㅠ 이 점 미리 양해 부탁드리겠습니다. 감사합니다!

2022-03-29 14:21 UTC, gch01410 requested changes
안녕하세요 차리! 리뷰어 던입니다!
체스미션 구현이 쉽지않았을텐데 정말 잘 구현하셨네요!
특히 테스트 코드를 너무 꼼꼼히, 깔끔하게 작성해주셨네요! 💯 💯 
테스트 코드 보니 마음이 편안해졌습니다.
간단한 코멘트들 남겼으니 확인 부탁드릴게요~

2022-03-29 14:21 UTC, gch01410 commented on src/main/java/chess/domain/board/Point.java
> +    private static Integer keys(int horizontal, int vertical) {
메서드명은 동사로 시작해야하지 않을까요~?

2022-03-29 14:21 UTC, gch01410 commented on src/main/java/chess/domain/board/Board.java
> +        replacePiecePoint(from, to, fromPiece);
tryMove, replacePiecePoint 로직을 각자 다른 메서드로 분리한 이유가 있을까요?

2022-03-29 14:21 UTC, gch01410 commented on src/main/java/chess/domain/piece/King.java
> +        this.strategy = new StraightMovingStrategy(StraightDirection.getAll(), OneStepDistance.init());
각 piece가 이동전략을 갖고 있는것 좋습니다!

2022-03-29 14:21 UTC, gch01410 commented on src/main/java/chess/domain/piece/Color.java
> +package chess.domain.piece;
Color enum을 piece 패키지에 위치시킨 이유가 있을까요?

2022-03-29 14:21 UTC, gch01410 commented on src/main/java/chess/domain/board/Board.java
> +        if (!fromPiece.move(this, from, to)) {
자신의 참조를 보내는게 어색하네요! 서로 참조값을 알고 있어서 양방향으로 호출하게 될 수 있을 것 같아요.
차리는 어떻게 생각하시나요?

2022-03-29 14:21 UTC, gch01410 commented on src/test/java/chess/domain/board/BoardFixtures.java
> +    }
fixture를 사용하셨군요! 👍 
보통 fixture는 미리 값까지 모두 셋팅을 해두고 테스트 코드에서 사용하는 방식으로 사용합니다!

2022-03-31 05:57 UTC, cjlee38 commented on src/main/java/chess/dto/ScoreResponse.java
> +    }
말씀을 듣고 나니 단박에 이해됐습니다 ㅎㅎ..

이 부분을 어떻게 해결해야하나 고민을 많이 해봤는데, 기존 Command라는 클래스가 굳이 영역을 따지자면 도메인이 아닌 컨트롤러쪽에 가깝다는 생각이 들어서, 기존 Command에 있는 BiFunction 제거하고, 도메인에 Game이라는 새로운 클래스에 Map형태로 저장하도록 해두었습니다. 그리고 View쪽 또한 Game과 마찬가지로, Command를 기반으로 어떤 출력문을 보여줄것인지에 대해서 결정할 수 있도록 Map형태로 저장하도록 하였습니다!

2022-03-31 06:04 UTC, cjlee38 commented on src/main/java/chess/dto/Request.java
> +    private final List<String> arguments;
Request라는 네이밍에서 느끼셨을지 모르겠지만, 저는 입력되는 명령어가, 저희가 쉘을 사용하는 것과 비슷하다고 생각을 했었는데요. 쉘 명령어를 크게 두가지로 분류해보자면 특정 실행하고자 하는 명령어와, 그에 수반되는 arguments들이 있다고 생각했습니다. 그리고 이 arguments에 대한 파싱은 명령어에 따른 특정 행위를 수행하는 객체의 책임이라고 생각했었습니다. 따라서, Request의 입장에서는, 그저 어떤 인자를 담고있는 리스트를 가지고 있을뿐이지, 어떤 내용물이 담겨있어야 하는지에 대해서는 몰라도 된다고 생각하고 있습니다!

혹시 던이 생각하시는 다른 의견이 있으실까요?

2022-03-31 06:06 UTC, cjlee38 commented on src/main/java/chess/domain/game/GameState.java
> +public interface GameState {
맞습니다! 만들다보니 Started가 필드만 가지고 있고 특정한 추상/구체 메소드를 갖지 않는다는 것을 이제 확인했습니다. 따라서 GameState라는 인터페이스를 삭제하고 기존 Started가 해당 추상 메소드들을 가지도록 하고, 해당 추상 클래스의 이름을 GameState로 변경했습니다!

2022-03-31 06:08 UTC, cjlee38 commented on src/main/java/chess/domain/board/Board.java
> +            throw new IllegalArgumentException("[ERROR] 자신의 말을 움직여야 합니다.");
같은 명령어 혹은 인자가 들어오더라도 실행이 될수도, 되지 않을수도 있으니 IllegalStateException이 적절해보입니다! 커스텀 예외에 대해서는 저도 긍정적인 입장이긴 한데, "다른 사람들이 보았을때 이해하기 쉬운 코드"가 우선시되어야 한다고 생각하고, 또 표준예외로 충분히 설명이 가능할 것 같다는 생각이 들어 커스텀 예외를 만들지 않았습니다!

2022-03-31 06:09 UTC, cjlee38 commented on src/main/java/chess/domain/board/Board.java
> +    }
기존 board의 로직이 꽤 꼬여있어서 킹이 죽었는지 여부를 미리 판별할 수 있어야 했는데, 구조를 조금 개편하면서 별도로 isKingDead라는 메소드로 확인할 수 있도록 수정하였습니다!

2022-03-31 06:10 UTC, cjlee38 commented on src/main/java/chess/domain/board/Point.java
> +    private static Integer keys(int horizontal, int vertical) {
고친다고 생각하고 깜빡했네요 ㅠ.ㅠ toKey 라는 네이밍으로 변경하였습니다!

2022-03-31 06:15 UTC, cjlee38 commented on src/main/java/chess/domain/board/Point.java
> +    private static Integer keys(int horizontal, int vertical) {
tryMove는 "진짜 움직일수 있는지 여부를 판별하고, 불가능하다면 예외를 던져라" 라는 의도였고, replacePiecePoint는 "진짜 움직여라"(=위치를 교체해라) 라는 의도였습니다. 만약 tryMove가 실제로 말을 한칸씩 움직이는 로직이었다면, 실패했을 때 다시 원상복구를 시키는 로직이 복잡할 것 같아 이와 같이 분리했습니다. 혹시 어떤 의도로 코멘트 남겨주셨는지 말씀해주실 수 있을까요?

2022-03-31 06:17 UTC, cjlee38 commented on src/main/java/chess/domain/piece/Color.java
> +package chess.domain.piece;
말씀을 듣고보니 맞는 것 같습니다! 따라서 "비어있는 좌표들의 목록"을 담은 EmptyPoints라는 클래스를 새로이 생성하여서, 이를 활용할 수 있도록 하였습니다.

다만 한 가지 여쭙고 싶은게, 양방향참조를 고려한다면, 이번 체스뿐만이아니라 모든 코드에서 this를 넘겨주는 순간 양방향 참조를 고려해야할 것 같다는 생각이 들었습니다. 혹시 "this를 사용해도 괜찮은 상황"의 예시 같은것을 알 수 있을까요?

2022-03-31 06:19 UTC, cjlee38 commented on src/main/java/chess/domain/board/Board.java
> +        if (!fromPiece.move(this, from, to)) {
넵기존 board가 mutable 한 객체였기 때문에 위와같이 매번 생성하도록 했었는데, 말씀 듣고 보니 Board를 immutable 로 만들지 않을 이유가 없는 것 같아, 이를 반영하고, 픽스쳐에서 값까지 모두 세팅할 수 있도록 하였습니다!

2022-03-31 06:33 UTC, cjlee38 commented
> 1. 어떠한 메소드는 static이라는 키워드를 붙이는 순간, "이 메소드는 필요한 모든 곳에서 사용될 수 있다" 이건 instance로 사용해도 똑같이 영향받는 것 아닐까요? 인스턴스 생성을 특정 객체에서만 생성할 수 있도록 제한하지않는다면요! 이것에 대해서는 어떻게 생각하시나요?

제 생각을 조금 더 자세히 말씀드리자면, 첫 번째는 유연성에서 차이가 있을 것이라고 생각합니다. View가 static으로만 이루어진 순간, 이를 상속하거나, 혹은 View Interface가 별도로 있을 경우 static으로 인해 다형성을 적절히 활용할 수 없을 것 같습니다. 둘 째로는, 개념적인 차이가 있다고 생각하는데요. static 메소드는 "이 메소드는 필요한 모든 곳에서 사용될 수 있다" 라고 말씀드렸는데, 이를 바꿔말하면 "모든 곳에서 활용되어도 무방하다" 라는 의미로 생각합니다. 즉, 저희가 생성자를 public으로 열었다고 하더라도, Piece 내부에서 Game을 생성하지 않는 이유는, Piece 입장에서, "내가 어떠한 객체로부터의 도움이 필요하다"는 메시지를 수신할 수 있는 책임을 갖는 객체가 Game이 아니기 때문이라고 생각합니다. (아직 배움이 짧아 표현이 좀 어색한데, 제가 말씀드리고 싶은 느낌만 알아주셨으면 감사하겠습니다 ㅠㅠ)


> 2. 특정 위치값에 존재하는 말들의 정보를 얻어내기 위해서 모든 리스트를 반복해야 한다는 불상사가 생기는데요 성능상 크리티컬하다고 생각하셨군요! 과연 성능상 크리티컬할까요? 성능상으로 괜찮다/안괜찮다 기준은 어떻게 잡으시나요? 이것에 대해 차리가 먼저 고민해볼 수 있을까요?

"성능상 크리티컬하다" 라고 표현한 것은 조금 과장된 표현이었던 것 같습니다. 다만, 위치값이 '말 내부'에 있을 경우에는, 단순히 '출발지와 도착지'를 찾을 때만 반복하는 것이 아니라, 매 이동 과정에서 해당 위치가 비어있는지 확인을 해야 하기 때문에, (e.g. 퀸이 a1에서 a8로 이동하는 경우 -> 64개의 값이 담긴 리스트를 8번 반복)불필요한 연산을 너무 과하게 수행하는 것 같다는 생각이었습니다. 물론 이에 대해서 정량적인 지표를 내세울 수는 없겠지만, "굳이" 그렇게 만들 필요가 있을까? 싶어서 Board가 위치값을 갖는게 적절하다고 생각했습니다.


> 4. piece 테스트를 작성해서 MovingStrategy의 로직도 어느정도 검증되었다고 생각이 드네요! 그렇지만 MovingStrategy 의 로직이 변경되었을때 수정해야할 테스트 코드가 너무 많아질 수 있겠어요. 차라리 MovingStrategy 의 테스트 코드를 작성해두는게 나을 것 같긴합니다!

개인적인 생각에 다른 클래스들은 검증이 다 끝난 것 같은데, StraightMovingStrategy에 대해서만 테스트가 구멍이 난 것 같아, 테스트코드를 추가로 작성하였습니다! (MovingStrategy는 어떻게 테스트를 해야할 지 모르겠습니다 ㅠㅠ)

2022-03-31 06:35 UTC, cjlee38 commented on src/main/java/chess/domain/piece/King.java
> +        this.strategy = new StraightMovingStrategy(StraightDirection.getAll(), OneStepDistance.init());
이 부분도 놓친 것 같습니다. 컬러는 도메인 전반에서 사용되는 것 같아 domain 바로 밑에 위치시켰습니다!

2022-03-31 13:14 UTC, cjlee38 commented on src/main/java/chess/domain/board/Board.java
> +        if (!fromPiece.move(this, from, to)) {
말씀을 듣고보니 맞는 것 같습니다! 따라서 "비어있는 좌표들의 목록"을 담은 EmptyPoints라는 클래스를 새로이 생성하여서, 이를 활용할 수 있도록 하였습니다.

다만 한 가지 여쭙고 싶은게, 양방향참조를 고려한다면, 이번 체스뿐만이아니라 모든 코드에서 this를 넘겨주는 순간 양방향 참조를 고려해야할 것 같다는 생각이 들었습니다. 혹시 "this를 사용해도 괜찮은 상황"의 예시 같은것을 알 수 있을까요?

2022-03-31 13:15 UTC, cjlee38 commented on src/main/java/chess/domain/board/Board.java
> +        replacePiecePoint(from, to, fromPiece);
tryMove는 "진짜 움직일수 있는지 여부를 판별하고, 불가능하다면 예외를 던져라" 라는 의도였고, replacePiecePoint는 "진짜 움직여라"(=위치를 교체해라) 라는 의도였습니다. 만약 tryMove가 실제로 말을 한칸씩 움직이는 로직이었다면, 실패했을 때 다시 원상복구를 시키는 로직이 복잡할 것 같아 이와 같이 분리했습니다. 혹시 어떤 의도로 코멘트 남겨주셨는지 말씀해주실 수 있을까요?

2022-04-01 00:02 UTC, gch01410 approved these changes
안녕하세요 차리!
피드백 잘 적용해주셨습니다! 👍 
이번 단계는 여기서 머지하도록 할게요.
다음 단계에서 뵙겠습니다!

2022-04-01 00:25 UTC, gch01410 commented
1. 제가 잘 이해한건지는 모르겠지만,, View에서 다형성을 사용해야한다면 인스턴스화해서 사용하는게 맞을 수 있겠어요. 그치만 확실하게 다형성이 필요한 경우가 아니라면 처음부터 다형성으로 사용될 것을 고려해서 인스턴스화하는건 과하다고 생각해요. 다형성을 사용해야할때 그때 변경해도 충분해보이거든요. 
`모든곳에서 사용될 수 있다`가 `모든 곳에서 활용되어도 무방하다` 라는것은 확대해석된 느낌이 있네요. 그러면 static은 util 클래스에만 사용할 수 있을 것 같아요. 비즈니스 로직이 조금이라도 섞여있다면 모든 곳에서 활용할 수는 없으니깐요!
2. trade off 라고 생각되는데요! piece가 position을 갖도록하는 대신 불필요하다고 생각되는 연산을 수행하게 되겠네요! 이건 사람마다 생각하는것이 다르니 차리가 고민해보고 결정하면 될 것 같아요. 저라면 전자를 선택하겠어요. 이유는 특정 위치의 piece를 알아내는 과정이 불필요한 연산을 과하게 호출하는것이 아니라고 생각해서요! (연산 수도 많지않고, 연산 수가 늘어날 가능성도 없어서요. 그리고 프로그램을 사용하는 입장에서도 불편함을 느낄만한 지연이 발생하지도 않고요!)
4. 인터페이스에 대한 테스트는 없어도 되지않을까요?

2022-04-01 00:25 UTC, merged