[1, 2, 3단계 - 체스] 봄(장보미) 미션 제출합니다.
woowacourse/java-chess pull request #315
Opened 2022-03-28 07:59 UTC by JangBomi

안녕하세요 루피:) 잘 부탁드립니다!

2022-03-28 14:48 UTC, TheDevLuffy requested changes
안녕하세요 봄~
리뷰어 루피입니다 🤠

요구사항이 많기도 하고 복잡하다보니 구현하기 힘드셨을 것 같은데 고생 많으셨어요.
전체적으로 테스트 코드 보충이 필요할 것 같아보여요 ㅎㅎ

추가적으로 코멘트 몇 개 남겨 두었으니 확인 부탁드려요~

2022-03-28 14:48 UTC, TheDevLuffy commented on src/main/java/chess/Board.java
> +        if ((sourcePiece.isMovable(targetPosition) && !hasBlock(sourcePiece, targetPiece)) || sourcePiece.isKill(targetPiece)) {
한줄에 나열하는 것이 오히려 가독성을 해칠수도 있을 것 같아요 😵‍💫

2022-03-28 14:48 UTC, TheDevLuffy commented on src/main/java/chess/Board.java
> +    public void move(List<String> commandPosition, Turn thisTurn) {
`List<String> commandPosition` 를 적절하게 가공해서 넘겨주는 것은 어떨까요 ?

2022-03-28 14:48 UTC, TheDevLuffy commented on src/main/java/chess/piece/RookMovable.java
> +public interface RookMovable {
인터페이스로 만드신 이유가 있으신가요 ?

2022-03-30 06:19 UTC, JangBomi commented on src/main/java/chess/Board.java
> +    public void move(List<String> commandPosition, Turn thisTurn) {
고민이 생겼는데, move에 String source, String target을 넣는 것 vs. Position source, Position target을 넣는 것 둘 중 루피라면 어떤 방식을 사용하실건가요?
제 의견은, String객체가 날것으로 돌아다니는 것 보다, command.getSourcePosition의 return type을 Position으로 둬서, move(Position source, Position target, )으로 하는게 더 낫다..! 인데 루피의 의견도 궁금합니 :)

2022-03-30 06:26 UTC, JangBomi commented on src/main/java/chess/piece/RookMovable.java
> +public interface RookMovable {
룩은 가로/세로로 움직일 수 있고, 비숍은 대각선으로 움직일 수 있고, 퀸은 가로/세로/대각선 으로 움직일 수 있어서 원래는 RookMovable, BishopMovable이 없었는데 퀸에서 로직이 중복되어서 인터페이스로 만들었습니다 ㅠㅠ 
혹시 더 좋은 방법이 있을까요?

2022-03-30 09:39 UTC, JangBomi commented on src/main/java/chess/model/piece/Piece.java
> +
isKing, isPawn같은 경우 Piece에서 false로 선언해주고, 각각 사용하는 클래스인 King, Pawn에서 true로 오버라이딩 해주고 다른 클래스들에서는 오버라이딩 해주지 않았는데, 괜찮게 사용한걸까요? 상속을 잘 사용해보지 않아서 선택적으로 오버라이딩하는게 괜찮은지 모르겠습니다 🥲

2022-03-30 09:41 UTC, JangBomi commented on src/main/java/chess/model/piece/Piece.java
> +
혹시 루피는 추상클래스에서 메서드 선언순서 어떻게 하시나요?
저는 final 메서드 - 그냥 메서드 - abstract 메서드 순으로 했는데 루피는 어떤 순서로 하시는지 궁금해요!

2022-03-30 09:49 UTC, JangBomi commented on src/main/java/chess/model/piece/Pieces.java
> +    }
원래 board에서 pieces.remove(), pieces.add() 두 개를 했는데,  arrange라는 새로운 메서드를 만들어서 board에서는 board.arrange()를 하도록 했어요. 이 메서드는 판에서 타겟 자리에 있던 piece를 없애고, Empty piece를 source자리에 넣는 역할 두개를 합니다. 
마음에 걸리는 부분은, `판을 정리하는` 행위에, `1. 타겟 자리에 있던 피스를 없앤다.`, `2. empty piece를 소스자리에 넣는다. `두 가지 행위가 포함되어 있는 것입니다, 
보드 입장에서 위 두가지 행위는 무조건 함께 일어나야하는 행위라 arrange() 메서드 하나로 묶은건데, 루피는 이렇게 arrange()로 묶은 것에 대해 어떻게 생각하시나요? 🤔

2022-03-30 09:52 UTC, JangBomi commented on src/main/java/chess/model/command/Init.java
> +    }
나름의 상태패턴으로 Command를 구현했는데, if 덩어리가 나오네요.
혹시 이 if를 없앨 수 있는 힌트가 있을까요? 😱

2022-03-30 09:58 UTC, JangBomi commented on src/main/java/chess/model/Board.java
> +    }
isMovable처럼 hasBlock도 sourcePiece입장에서 `내 앞에 가로막는 장애물이 있는가?` 라는 의미로 sourcePiece.hasBlock(targetPiece)로 사용하고 싶었어요. 이렇게 수정하려고 하니, hasBlock 내부 로직에 `Pieces` 클래스를 사용하는 부분이 있어서 망설여지네요. 

위에 말한 것 처럼 수정하려고하니 , `의존이 순환으로 일어나고 있는 느낌`이 들고, 수정 안하려고 하니 `말이 움직일 수 있는지 없는지에 대한 로직이 piece와 board에 흩어져있는 느낌`이 들어요.

루피는 이 상황에서 `1. 수정한다 2. 안한다` 중 어떤 방법을 선택하실껀가요?
다른 크루들을 보니, Board를 position과 piece의 map으로 들고있고, piece는 position을 모르게 구현했던데, piece에게서 position을 삭제하고, `움직일 수 있나 없나`자체를 보드에서 알아야하나,, 라는 생각도 드네요.

정답이 없는 질문인 것 같긴 하지만, 루피의 의견도 궁금해서 여쭤봅니다!

2022-03-30 10:03 UTC, JangBomi reviewed
루피 안녕하세요 :) 🌱 
사실 아직 리팩토링 중이지만, 궁금한게 많아서 우선 리뷰 요청 드립니다!

이번 리뷰요청 보내기 전에,
1. 메서드 선언 순서 리팩토링
2. 매직넘버 등을 상수로 리팩토링
3. 포지션 캐싱
4. 테스트코드 보강
등 코드 전체적으로 완성도를 좀 더 높여보려 했습니다!

루피의 많은 의견 부탁드립니닷 감사합니다 🙇

2022-03-30 15:24 UTC, TheDevLuffy requested changes
보미 안녕하세요~

피드백 반영하시는 도중에 한번 쉬어가는 리뷰 요청 좋습니다 ㅎㅎ
남겨주신 코멘트에 답글 남겨 두었고 추가 코멘트들 남겨 두었으니 확인 후 리뷰 요청 주세요~

2022-03-30 15:24 UTC, TheDevLuffy commented on src/main/java/chess/model/piece/BishopMovable.java
> +public interface BishopMovable {
해당 인터페이스와 `RookMoveable` 과 같이 행위와 구현을 모두 가지는 경우는 클래스로 정의하는 것이 더 좋지 않을까요 ?

2022-03-30 15:24 UTC, TheDevLuffy commented on src/main/java/chess/model/Board.java
> +    }
고민이 많으시군요 ㅎㅎ

저는 현실세계에서 체스게임을 그대로 반영해볼 것 같아요.

혹시 체스게임 해보셨나요 ? 혹은 해리포터에서 체스게임 하는 장면을 본 적 있으신가요 ?

체스 게임에서 말을 움직일 때,
"체스판 A2 칸의 기물을 A3 칸으로 이동한다." 와 같이 표현하지요. > 이런 표현이라면 기물은 위치를 직접 알고 있지 않고, 체스판을 통해 알고 있겠지요 ?
"기물에서 스스로의 위치를 알고, 기물에게 위치를 변환하도록 한다." 라고 표현하는 것이 어색하진 않으신가요 ? ㅎㅎ

요구사항을 미션 진행에 너무 집중하는 것도 좋지만 현실세계에서 어떤 요구사항이 실제로 어떻게 고민하고, 말로 표현할 수 있는지 한번 고민해보시는 것도 좋을 것 같아요 ㅎㅎ

2022-03-30 15:24 UTC, TheDevLuffy commented on src/main/java/chess/model/Position.java
> +
좋은 시도가 되실 것 같아요 !

2022-03-30 15:24 UTC, TheDevLuffy commented on src/main/java/chess/model/piece/Piece.java
> +
1. 네 ! 크게 이상하지 않을 것 같아요. 만약 명시적으로 오버라이딩을 하시고 싶으시다면 `super.method()` 콜을 하시면 될 것 같아요. 인텔리제이에서 오버라이딩 기능을 사용하면 자동으로 생성해주는 코드가 있지요 ?
2. 저는 보미의 생각에 동의합니다 ! ㅎㅎ

2022-03-30 15:24 UTC, TheDevLuffy commented on src/main/java/chess/model/piece/Pieces.java
> +    }
개인적으로 굉장히 응집도 있는 코드라고 생각합니다.

내용이 조금 어려울 수 있을 것 같은데, [추상화 수준에 관한 글](https://onestone-dev.tistory.com/3)을 읽어보시면 좋을 것 같아요.

Pieces 의 입장에서 arrange 는 하나의 행위가 아닐까요 ? ㅎㅎ

2022-03-30 16:10 UTC, JangBomi commented on src/main/java/chess/model/command/Command.java
> +    public static final String STATUS = "status";
앗 명령어들을 Command에서 public으로 정의해두고, Command 하위객체인 Start, End, Move 등에서 Command.START 로 받아오려했어요.

루피의 리뷰를 보고 `public보다 protected를 접근제어자로 사용해서 해당 패키지 내에서 사용할 수 있도록 하는 것` 과 `Start, Move, End 등 모든 클래스에서 상수 선언을 해주는 것` 두 가지를 생각해봤습니다.
전자의 장점은, Start, End 등 자식 클래스에서 중복으로 상수를 선언해주는 것을 막을 수 있다 라고 생각하고, 후자의 장점은 `접근 권한을 최소화했다..?` 인데 저는 전자로 쓰는게 더 좋을 것 같습니다.

루피의 의견도 듣고싶어요~!~!!!

2022-04-01 15:47 UTC, JangBomi commented on src/main/java/chess/model/piece/BishopMovable.java
> +public interface BishopMovable {
이해했습니다!! 제가 작성했던 BishopMovable과 RookMovable은 인터페이스보다는 클래스가 더 나았던 것 같아요! 두 클래스 모두 리팩토링 하는 과정에서 사라졌습니다 :)

2022-04-02 03:38 UTC, JangBomi commented
루피 안녕하세요 🌱
리뷰가 늦어졌네요. 지난 pr 이후로 
1. Piece에서 Position을 삭제하고 Board를 Map<Position, Piece> 형태로 수정
2. Direction, Distance를 도입해 Position의 역할 분배
3. Strategy 인터페이스과 구현체를 통해 Piece 각각이 본인의 이동 방식을 갖고있도록 수정 
4. MoveType 도입
5. GameResult 도입

등 구조적으로 좀 더 수정해봤습니다! 


[https://github.com/woowacourse/java-chess/pull/315#discussion_r838673115](url) 남겨주신 Piece 추상클래스에 대해서는 이해를 아직 못해서 ㅠㅠ 다음 pr 보낼 때까지 고민해보겠습니다! 


감사합니다 :)

2022-04-02 11:22 UTC, TheDevLuffy commented on src/main/java/chess/model/piece/Piece.java
> +
@JangBomi 상속보다 조합을 사용해보면 어떨까요 ㅎㅎ

2022-04-02 11:23 UTC, TheDevLuffy commented on src/main/java/chess/model/command/Command.java
> +    public static final String STATUS = "status";
오,, 제가 다른 클래스에서 사용하고 있는지 놓친 것 같네요

2022-04-02 11:32 UTC, TheDevLuffy approved these changes
봄 안녕하세요~

3번의 리뷰를 거치는 동안 많은 부분들이 개선된 것 같아요 ㅎㅎ
첫 리뷰 요청시 커밋으로 되돌아가서 한번 지금의 코드와 비교해보는 것도 좋을 것 같아요.

코멘트 몇 개 남겨두었으니 확인 부탁드려요.
체스 미션 요구사항이 복잡해서 미션 진행하시는 게 쉽지 않으셨을 것 같은데 고생 많으셨습니다.

이번 단계는 이만 머지하도록 할께요~

2022-04-02 11:32 UTC, TheDevLuffy commented on src/main/java/chess/model/MoveType.java
> +public enum MoveType {
이렇게 생각해볼 수도 있겠네요. 👍
잘 구현해주신 것 같아요 ㅎㅎ

2022-04-02 11:32 UTC, TheDevLuffy commented on src/main/java/chess/model/strategy/PawnMoveStrategy.java
> +         */
불필요한 주석은 제거해주세요~

2022-04-02 11:32 UTC, TheDevLuffy commented on src/main/java/chess/model/board/BoardFactory.java
> +        return new Board(board);
Factory 를 통해 Board 를 생성하도록 해주셨네요 ㅎㅎ

Board 의 생성자를 package private 으로 변경해볼 수 있지 않을까요 ?

2022-04-02 11:32 UTC, TheDevLuffy commented on src/main/java/chess/model/position/Position.java
> +    }
사용하지 않는 메서드들이 있어요~

2022-04-02 11:32 UTC, TheDevLuffy commented on src/main/java/chess/model/piece/Rook.java
> +    private static final List<Direction> directions = Direction.linear();
사용하지 않고 있어요~

2022-04-02 11:32 UTC, merged