[1, 2, 3단계 - 체스] 라쿤(이병훈) 미션 제출합니다.
woowacourse/java-chess pull request #318
Opened 2022-03-28 08:05 UTC by nbalance97

안녕하세요 로운! 리뷰를 요청드릴 라쿤이라고 합니다😄
체스 미션을 하면서 구현 자체가 너무 어렵게 느껴져서 구현에 치중한 나머지 코드가 비교적 깔끔하다고 생각이 되지는 않네요😢

이번 미션을 하면서 제가 가장 신경이 쓰이는 부분은 게임이 실제로 이루어지는게 Board 클래스이다 보니까 해당 클래스에서 너무 많은 일을 하는게 아닌가 걱정이 되어 이 부분에 대한 로운의 생각을 듣고 싶습니다!

바쁜 시간 내어 코드리뷰 해주셔서 감사합니다 🙇🏻‍♂️🙏

2022-03-28 13:00 UTC, lowoon requested changes
반가워요 라쿤! 리뷰어 로운입니다! 😄
질문에 대한 답변은 board에 코멘트 남겼습니다~
피드백 몇 가지 남겨봤으니 확인 부탁드려요.
궁금한 점이 생기면 언제든지 DM 혹은 댓글남주세요 ^-^

2022-03-28 13:00 UTC, lowoon commented on src/main/java/chess/domain/board/Board.java
> +    private void initialBatchPiece() {
배치시키다는 한글인 것 같고, 실제 영어단어 `batch`는 배치시키는 뜻이 아닌거 같아요~

2022-03-28 13:00 UTC, lowoon commented on src/main/java/chess/domain/board/Position.java
> +        List<Position> positions = new ArrayList<>();
`getter`는 가지고 있는 필드를 반환할 때 쓰이는데요.
get이 호출되었을때 position을 생성하는 것이 맞을까요?
게임 중간 중간에 호출될 경우 계속 새로 생성해서 반환해야할 이유가 있을까요?

2022-03-28 13:00 UTC, lowoon commented on src/main/java/chess/domain/board/Position.java
> +        return row < 1 || row > 8 || column < 1 || column > 8;
row와 column의 값도 반복되는 것 같은데 상수로 관리해야 하지 않을까요?

2022-03-28 13:00 UTC, lowoon commented on src/main/java/chess/domain/piece/Knight.java
> +	private static final String WHITE_SYMBOL = "n";
**개인적인 의견입니다~**
모두 black과 white 심볼을 가지고 있는데요.
소문자로 가지고 있어서 블랙일 경우에 toUpperCase를 사용할 수도 있을 거 같고요.
필요하다면 symbol도 객체로 관리할 수 있지 않을까 싶기는 하네요.

2022-03-29 04:42 UTC, nbalance97 commented on src/main/java/chess/domain/board/Board.java
> +    private void initialBatchPiece() {
앗..😂 영어 이슈네요.. 이부분은 메소드명을 ```initialPlacePiece``` 로 변경하였습니다!!

2022-03-29 04:44 UTC, nbalance97 commented on src/main/java/chess/domain/board/Position.java
> +        return row < 1 || row > 8 || column < 1 || column > 8;
매직 넘버 처리가 되지 않았었네요 😅 상수로 변경하였습니다!

2022-03-29 04:46 UTC, nbalance97 commented on src/main/java/chess/view/InputValidator.java
> +    public static void validateCommand(final String answer) {
InputView에 validate 로직까지 모두 가지고있는 것 보다는 검증 자체는 InputValidator이라는 클래스에서 관리해주는게 더 나을 거 같아서 Validator로 따로 빼서 진행하였습니다🙂

2022-03-29 05:22 UTC, nbalance97 commented on src/main/java/chess/view/Command.java
> +
초기 설계에서는 InputView에서 Position으로 바꾸어서 넘겨주도록 하려고 했는데, 구조가 변경되면서 미처 옮기지 못했었네요😅 이부분을 domain으로 넘겨주었습니다!

2022-03-29 05:23 UTC, nbalance97 commented on src/main/java/chess/view/PositionConvertor.java
> +    public static Position to(final String rawPosition) {
아래와 비슷한 이유로 InputView에서 변환을 시켜서 넘겨주려고 했었는데, 구조를 변경하다 보니 미처 옮기지 못했었습니다😢 domain으로 이동시켰습니다!!

2022-03-29 07:24 UTC, nbalance97 commented on src/main/java/chess/controller/ChessController.java
> +        if (!Command.isStart(inputCommand.get(0))) {
0을 상수로 빼서 관리하는 방향으로 정했습니다😀

2022-03-29 07:25 UTC, nbalance97 commented on src/main/java/chess/controller/ChessController.java
> +        functionByCommand.put(Command.START, () -> {
시작을 따로 메소드로 처리했었는데.. 이부분은 유저 입력에 따른 진행을 상태 패턴을 적용하여 해결하였습니다😆

2022-03-29 09:32 UTC, nbalance97 commented on src/main/java/chess/controller/ChessController.java
> +        InputView.printCommandGuide();
이 점에 대해서 고민해본 결과 Controller에서 실행 로직을 가지고 있기 때문에 view와의 의존성이 강하다고 느껴졌습니다. 실행 로직을 Application으로 옮기고, Controller에서는 단순히 실행하여 출력해야 하는 정보만을 리턴하도록 구현하였습니다🙂

2022-03-29 11:27 UTC, nbalance97 commented on src/main/java/chess/domain/board/Board.java
> +        double sum = 0;
개인적으로 Board의 역할은 각 말들의 위치를 저장해 두고, 말들의 이동을 관리하는 역할이라고 생각합니다! 그런 관점에서 보니 board의 계산 로직이 분리되는 것이 더 알맞다고 생각이 되었습니다🙂 
이 점은 board의 계산 로직을 따로 ```ScoreCalculator``` 클래스로 분리하였습니다!

2022-03-29 12:27 UTC, nbalance97 commented on src/main/java/chess/domain/board/Position.java
> +        List<Position> positions = new ArrayList<>();
positions를 매번 생성하는것 보다는 캐싱해서 사용하는 것이 더 효율적이겠네요🙂 
해당 부분은 캐싱 처리 하였습니다😊

2022-03-29 16:23 UTC, nbalance97 commented on src/main/java/chess/domain/piece/Knight.java
> +	private static final String WHITE_SYMBOL = "n";
아하.. 페어랑 이야기를 나누던 부분중 하나입니다! 
black일때 upper, white일때 lower로 한다면 만약 알파벳이 아닌 문자가 온다면 어떻게 해야할까 고민하다가 결론적으로 각각이 BLACK_SYMBOL, WHITE_SYMBOL을 갖는 방식으로 결정하였습니다!

2022-03-30 09:12 UTC, lowoon commented on src/main/java/chess/view/PositionConvertor.java
> +    public static Position to(final String rawPosition) {
**개인적인 의견입니다. 반영하지 않으셔도 돼요.**
이미 Position에 정적팩토리 메서드를 만들었는데요.
positionConverter의 to도 Position 내에 정적팩토리 메서드로 만들면 되지 않을까 생각했어요.
정적팩토리 메서드 자체가 여러 파라미터에 대해서 자기 자신을 반환할 때 쓰이니까요.
convert error의 경우에는 command가 명령에 대해 관리를 하고 있으니 move와 함께 입력되는 값들도 검증하는 역할을 가질 수 있지 않을까?? 생각했습니다~
아니면 Position에서 입력이 잘못되었다고 에러를 던져도 될거 같구요.

2022-03-30 09:14 UTC, lowoon commented on src/main/java/chess/view/InputValidator.java
> +    public static void validateCommand(final String answer) {
**개인적인 의견입니다. 반영하지는 않으셔도 돼요.**
저는 개인적으로 view의 역할과 책임에 기본적인 검증이 포함된다고 생각해서요. (null이 아닌지 string인지 int인지 등등)
현재 view와 validator의 역할이 크지 않은데 분리를 할 필요가 있을까 생각했습니다~

2022-03-30 11:28 UTC, lowoon requested changes
고생하셨어요. 라쿤! 리뷰 반영 잘 해주셨어요! 😄 
몇 가지 코멘트 남겼으니 확인해주세요ㅎㅎ
궁금한 점은 언제든지 DM이나 코멘트 남겨주세요 :)

2022-03-30 14:57 UTC, nbalance97 commented on src/main/java/chess/domain/state/turn/Finished.java
> +    private static final String ALREADY_FINISHED_GAME = "이미 종료된 게임입니다.";
리팩토링 하면서 더이상 사용하지 않는 것 같네요😥 삭제했습니다!

2022-03-30 18:11 UTC, nbalance97 commented on src/main/java/chess/domain/board/ScoreCalculator.java
> +    public ScoreCalculator(Map<Position, Piece> board) {
StatusResult에서 blackScore, whiteScore을 주입받는것이 아닌 board를 받아서 계산하도록 로직을 변경하였습니다ㅎㅎ

2022-03-31 08:35 UTC, nbalance97 commented on src/main/java/chess/domain/piece/King.java
> +        List<Direction> directions = Direction.getKingDirection();
각각의 piece의 내부에 direction을 갖도록 구현을 변경하였습니다. 🙂

2022-03-31 08:38 UTC, nbalance97 commented on src/main/java/chess/domain/board/Board.java
> +        for (Position position : Position.getPositions()) {
아하 이해했습니다! 이부분도 PieceBuilder을 만들어서 build()의 결괏값을 board의 생성자로 주입하는 방식으로 코드를 변경하였습니다😆

2022-03-31 10:08 UTC, lowoon commented on src/main/java/chess/domain/board/ScoreCalculator.java
> +    public ScoreCalculator(Map<Position, Piece> board) {
**개인적인 의견입니다. 반영하지 않으셔도 돼요.**
라쿤이 정한 ScoreCalculator과 StatusResult의 역할과 책임이 궁금했어요.
board 내부에서 calculator를 매번 호출해서 점수를 계산해서 StatusResult에 넘겨주고 있는데요.
결과에서만 필요한 기능이고 결과의 책임에 자기 자신이 필요한 값들을 계산하는 책임도 가지도록 했다면 StatusResult에 board를 넘겨서 자기 자신을 만들도록 할 수도 있지 않을까요??

2022-03-31 10:10 UTC, lowoon approved these changes
고생하셨어요. 라쿤! 이전 리뷰 내용을 잘 반영해주셨습니다 💯
몇가지 코멘트를 달아봤는데요. 코멘트 반영은 4단계에서 부탁드릴게요.
추가적인 궁금증은 이 pr이 머지되어도 댓글 남겨주셔도 좋구 DM도 좋습니다.

2022-03-31 10:11 UTC, lowoon commented on src/main/java/chess/Application.java
> +	private static Map<Command, Runnable> functionByCommand = createFunctionByCommand();
final을 붙여도 될거 같아요~

2022-03-31 10:13 UTC, lowoon commented on src/main/java/chess/domain/board/PieceBuilder.java
> +        Map<Position, Piece> board = new HashMap<>();
개인적인 의견인데요.
pieceBuilder보다는 boardBuilder 혹은 boardGenerator가 더 맞지 않나 라는 생각을 했어요.
pieceBuilder라고 하면 board에 필요한 piece만 만들거라는 생각이 들엇어요~

2022-03-31 10:14 UTC, merged

2022-03-31 10:20 UTC, lowoon commented on src/main/java/chess/domain/board/Position.java
> +    private static final Map<Integer, Map<Integer, Position>> cachedPositions = new HashMap<>();
Map<String, Position>이 아닌 Map<Integer, Map<Integer, Position>>으로 관리한 이유가 있을까요??

2022-04-01 04:03 UTC, nbalance97 commented on src/main/java/chess/domain/board/Position.java
> +    private static final Map<Integer, Map<Integer, Position>> cachedPositions = new HashMap<>();
개인적으로는 Map<Integer, Map<Integer,Position>>으로 코드를 작성했을 때가 행과 열로 접근하는데 있어서 더 명확하게 느껴졌습니다! 😅

2022-04-01 04:08 UTC, nbalance97 commented on src/main/java/chess/domain/board/PieceBuilder.java
> +        Map<Position, Piece> board = new HashMap<>();
아하.. 결국 piece만 생성하는 것 같아서 이름은 PieceBuilder로 두었는데, 로운의 의견이 맞는 거 같습니다😊