[1, 2, 3단계 - 체스] 주디(윤주리) 미션 제출합니다.
woowacourse/java-chess pull request #323
Opened 2022-03-28 08:19 UTC by jurlring

토니 안녕하세요! 저는 주디라고 해요 :)
제 페어인 엘리의 저번 미션 리뷰어시더라구요!
엘리처럼 저도 잘 부탁드려요 ㅎㅎ

이번 미션은 구현보다 설계를 하는 부분에서 많은 시간이 걸렸어요.
구현하면서 구조도 여러 차례 바꾸기도 했고, 한 클래스가 너무 많은 역할을 담당하는 것 같아서 분리하면서 구조가 조금 어수선한 것 같아요!..
당장은 어떻게 수정해야할지 떠오르지 않아서 일단 제출하게 되었습니다.

미션을 진행하면서 궁금했던 점은 코드보면서 질문하겠습니다 :)

바쁘신 와중에 제 코드 리뷰를 해주셔서 감사해요!
나중에 척척학사 개발자가 되어서 24배로 갚겠습니다 :)

2022-03-28 13:32 UTC, jurlring commented on src/main/java/chess/domain/move/MoveChecker.java
> +
MoveChecker에서 이동이 가능한지 전체적으로 확인을 하도록 클래스를 만들었어요!
checkMovement 메서드에서 각 기물마다 행마법이 맞는지 확인하도록 설계를 했는데, 뭔가 move할 수 있는지 확인하는 로직이 분산되어있는 것 같기도 한거 같아요!
토니는 어떻게 생각하시나요?

2022-03-29 13:50 UTC, toneyparky requested changes
안녕하세요 주디! 토니에요~~~

어려운 체스 미션! 고생 많이 하셨습니다.

구현해주신 내용 잘 확인했어요. 상태패턴을 잘 활용하셨군요!

질문 주신 내용과 제가 드리고픈 조언을 남겼으니 확인부탁드려요!
대댓글과 DM은 언제든 환영입니다~!

2022-03-29 13:50 UTC, toneyparky commented on src/main/java/chess/domain/move/MoveChecker.java
> +        if (!board.findPiece(next).equals(new EmptyPiece())) {
board에게 특정 포지션이 비어있는지 물어본다면 보다 이해하기 쉬워질거 같네요!

2022-03-29 13:50 UTC, toneyparky commented on src/main/java/chess/domain/move/Direction.java
> +    public static Direction of(final int fileDistance, final int rankDistance) {
주디는 정적 팩터리 메서드의 이름을 짓는 본인만의 규칙이 있으신가요~?

2022-03-29 13:50 UTC, toneyparky commented on src/main/java/chess/state/State.java
> +
불필요한 공백이 존재하네요!

2022-03-29 16:31 UTC, jurlring commented on src/main/java/chess/domain/piece/EmptyPiece.java
> +public final class EmptyPiece extends Piece {
is-a관계인지 고민을 해봤습니다!
일단 확실하게 has-a 관계는 아니라고 생각이 들었어요. EmptyPiece는 Piece의 일부분이 아니니까요!
일단 is-a관계라면 Piece의 구체화된 클래스가 EmptyPiece일텐데, 비어있는 Piece를 의미하는게 구체화된 클래스라고 할 수 있을까? Piece와 EmptyPiece는 반대의 의미를 가지는게 아닐까? 라는 생각이 들었어요!
그리고 has-a의 반대는 is-a일까? 라는 의문이 들었어요!
블로그등에서 has-a와 is-a는 반대라고들 하는데 저는 이분법적으로 나눌 수 없다고 생각해요.
그렇다면 Piece와 EmptyPiece는 무슨 사이일까요.....ㅜ.ㅜ

2022-03-29 17:27 UTC, jurlring commented on src/test/java/chess/domain/piece/KingPieceTest.java
> +}
엇 저는 왜 빨간 색이 뜨지 않을까요..!!! wooteco code style적용했는데..!
가끔 이걸 생각했었는데, class가장 위에서도 필드와 구분해서 가독성을 높이기 위해 공백을 사용하듯이 마지막 줄에서도 공백이 필요하지 않을까 생각했어요!
근데 딱히 code style에서 warning이 안뜨길래 상관 없는줄 알았네요..!
수정하겠습니다~~!

2022-03-29 17:36 UTC, jurlring commented on src/test/java/chess/domain/piece/KingPieceTest.java
> +}
앗 제가 컨벤션을 못지켰네요!!
수정하겠습니다 :)

2022-03-30 07:45 UTC, jurlring commented on src/test/java/chess/domain/piece/KingPieceTest.java
> +import static org.junit.jupiter.api.Assertions.*;
`org.assertj.core.api.Assertions` 는 외부 라이브러리고, org.junit.jupiter.api.Assertions은 Junit5의 서브 프로젝트 라고 알고 있어요!
둘 중에 하나로 통일하라는 의미?라고 생각해서 `org.assertj.core.api.Assertions`로 통일했습니다 :)

2022-03-31 03:02 UTC, toneyparky commented on src/main/java/chess/domain/Score.java
> +    }
else if가 사용되었네요!

추가로 정수인 Score의 값으로 비교한 후에 0, -1, 1로 반환한다는 개념이 직관적이지 않네요.

enum 클래스인 Result와 같이 수정될 부분을 찾아보면 좋겠어요!

2022-03-31 03:02 UTC, toneyparky commented on src/main/java/chess/domain/position/Position.java
> +    public Position move(final Direction direction) {
주디가 언제 enum을 사용하는지 적어주셨군요! 말씀하신대로 특정한 상수의 집합을 모아서 관리할 때에 사용하면 좋죠! 

예외처리의 핵심을 잘 알고 계시는거 같아요. 개발자에게 예외가 왜 발생했는지 알려주거나 사용자에게 적절한 행동을 유도하는 거죠. 
굳이 null을 반환하지 않더라도 사용하는 사람에게 정보가 충분히 전달되고 체스 게임이 끝나지 않고 현재 상황에서 다시 진행할 수 있어요. 
그렇기에 리팩터링한 방향성이 적절하다고 생각해요.

지금처럼 고민될 때에는 위에 남겨주신 댓글처럼 글로 적어보면 생각을 정리하는 데에 도움이 됩니다. 경력이 많은 개발자가 아니기에 아직 생각만으로 판단을 내리기가 어려울 수 있어요. 이럴 때에는 방금처럼 글로 적고 고민해보아요!

널의 창시자가 널에 대해서 이야기한 내용을 남겨서 널에 대해 고민하실 수 있는 방향성을 제시해드릴게요!
https://lunuy.tistory.com/32

2022-03-31 03:03 UTC, toneyparky commented on src/main/java/chess/domain/piece/EmptyPiece.java
> +public final class EmptyPiece extends Piece {
고민을 많이 하셨군요 주디..!

EmptyPiece를 Piece처럼 눈에 보여야 한다라는 현실의 Piece와 연관짓지 않아도 괜찮아요. 현실의 체스는 EmptyPiece라는 개념이 없이 빈 체스 칸은 비어있지만 우리는 프로그래밍적으로 요구사항을 해결하기 위해서 현실과 다른 개념인 EmptyPiece를 도입한거죠. 객체지향의 사실과 오해라는 책을 읽어보셨을까요? 객체는 꼭 현실의 물건일 필요가 없다는 이야기가 나오기에 읽어보시면 도움이 될거에요. 

이런 관점에서 EmptyPiece는 Piece를 구체화했다고 볼 수 있어요. 다만 위에서도 언급했듯 부모인 Piece의 모든 메서드를 다 지원하지 않기에 리스코프 치환의 원칙을 위배합니다. 

정리하자면 자바에서 null은 만든 사람도 큰 실수라고 할만큼 지양해야해요. null을 사용하지 않으면서 프로그래밍적으로 요구사항을 해결하기 위해 현실에는 없는 EmptyPiece라는 개념을 도입했어요. 그리고 EmptyPiece는 Piece를 어느정도 구체화한 형태라고 생각할 수 있구요. 하지만 완벽히 부모를 따르지는 않기에 주디의 고민이 시작되었어요. 프로그래밍 설계와 객체지향의 규칙 사이에서 어느정도 타협한 결과물이라고 생각해요.

2022-03-31 03:03 UTC, toneyparky commented on src/test/java/chess/domain/piece/KingPieceTest.java
> +import static org.junit.jupiter.api.Assertions.*;
오 좋아요! 

협업을 할 때에 새로 프로젝트를 시작하신다면 팀원과 소통하여 테스팅 라이브러리를 정하여 일관된 규칙으로 진행하시면 좋아요. 이미 진행되는 프로젝트라면 규칙을 따르면 되구용! 만일 더 좋은 툴이 있다면 팀에 제안해보는 방법도 있어요.

2022-03-31 03:03 UTC, toneyparky commented on src/test/java/chess/domain/piece/KingPieceTest.java
> +}
네~! 

컨벤션이기도 하지만 이런 컨벤션이 생기게 된 이유에 대해서도 알아보시면 도움이 될거에요!

2022-03-31 03:04 UTC, toneyparky requested changes
안녕하세요 주디!

리뷰 반영 잘 해주셨어요 😎

조금 더 수정하면 좋겠는 부분에 대해서 코멘트 남겼으니 확인 부탁드려요!

질문이 있으시면 DM 부탁드려용

2022-03-31 07:22 UTC, jurlring commented on src/main/java/chess/domain/Command.java
> +public enum Command {
음 웹 뷰로 바뀐다면 사용을 안할 것 같네요! 도메인이라고 보긴 힘들 것 같아요.

2022-04-01 23:31 UTC, toneyparky commented on src/main/java/chess/domain/Command.java
> +public enum Command {
넵~! 패키지도 옮겨주셨네요! 확인했어요!

2022-04-01 23:32 UTC, toneyparky commented on build.gradle
> +    runtimeOnly 'mysql:mysql-connector-java:8.0.28'
좋습니다~! 추가로 api라는 키워드도 있는데 나중에 그레이들 파일을 다루면서 또 학습해보죠~!

2022-04-01 23:33 UTC, toneyparky approved these changes
좋은 아침이에요 주디! 이번 단계 잘 마무리하셔서 머지하도록 할게요!

제가 드린 질문에도 잘 답변해주셔서 감사해요 😀

다음 단계도 화이팅입니다!

2022-04-01 23:33 UTC, merged