[1, 2, 3단계 - 체스] 라라(박세은) 미션 제출합니다.
woowacourse/java-chess pull request #327
Opened 2022-03-28 08:27 UTC by sure-why-not

앨런 안녕하세요!
이번 체스 미션을 리뷰요청 드리게 된 라라입니다. 😀

소문대로 체스 미션은 굉장히 어렵더라구요. 😭
페어와 이번 PR 까지는 일단 기능 구현을 목표로 구현해보았습니다!
나름 구조를 생각하고 구현하긴 했는데, 아직 부족한 점이 많이 보이네요. 😂

현재 각 객체들이 갖는 역할과 책임이 많다는 생각이 들어서 책임을 분리하기 위한 구조를 고민해보고
앨런의 피드백들과 함께 리팩토링 해나가고 싶습니다!!

잘 부탁드립니다 ~~~ 🥰

2022-03-30 08:26 UTC, hongbin-dev requested changes
안녕하세요 라라👋 리뷰어 앨런입니다
어려운 미션인데 객체지향적으로 구현해주시려는게 보였습니다.
몇 가지 코멘트 남겼으니 확인해주세요~

2022-03-30 08:26 UTC, hongbin-dev commented on src/main/java/chess/domain/piece/Bishop.java
> +public class Bishop extends Piece {
만들어놓은 피스들은 재활용하기 어려울까요?

2022-03-30 08:26 UTC, hongbin-dev commented on src/main/java/chess/domain/piece/Bishop.java
> +    }
이쪽도 상수로 관리하면 좋을 것 같아요~

2022-03-30 08:26 UTC, hongbin-dev commented on src/main/java/chess/domain/piece/Blank.java
> +public class Blank extends Piece {
Blank가 피스의 자식인가요? 이름이 조금 모호한 것 같습니다.

2022-03-30 08:26 UTC, hongbin-dev commented on src/main/java/chess/domain/piece/Blank.java
> +    }
이 부분이 조금 모호한 것 같아요. LSP위반이 아닐까요? 자식이 부모의 역할을 못하고 있어요 🥲

2022-03-30 08:26 UTC, hongbin-dev commented on src/main/java/chess/domain/piece/Knight.java
> +    }
사소한 이슈지만 새 객체를 만들어내지 않고, 
```suggestion
    @Override
    public List<Position> findRoute(Position source, Position target) {
        return List.of();
    }
```
만들어진 객체를 사용하는 것도 방법일 것 같네요~

2022-03-30 08:26 UTC, hongbin-dev commented on src/main/java/chess/domain/piece/Piece.java
> +    }
isDisplaced가 모든 piece의 상태로 갖게된 이유가 있을까요?
폰에서만 사용하고 있는 것 같아서요. 다른방법으로 문제를 풀어낼 순 없을까요?

2022-03-30 08:26 UTC, hongbin-dev commented on src/main/java/chess/domain/position/Position.java
> +public final class Position {
이 부분에 캐시를 적용하는거에 대해서 어떻게 생각하시나요?

2022-03-30 08:26 UTC, hongbin-dev commented on src/main/java/chess/domain/position/Position.java
> +    }
👍

2022-03-30 08:26 UTC, hongbin-dev commented on src/main/java/chess/domain/position/PositionX.java
> +    private final int coordination;
도메인규칙에 따라서 file, rank라는 이름은 어떨까요~?

2022-03-30 08:26 UTC, hongbin-dev commented on src/main/java/chess/domain/position/PositionX.java
> +                .orElseThrow(() -> new IllegalArgumentException("유효하지 않은 좌표입니다."));
어떤 좌표로 에러가 발생했는지 피드백주시면, 디버깅하기 좋을 것 같아요.

2022-03-30 08:26 UTC, hongbin-dev commented on src/main/java/chess/domain/Board.java
> +    }
이쪽에도 실행전에 검증이 필요하지 않을까요? 클라이언트(컨트롤러)는 항상 우리가 원하는순서대로 함수를 호출하지 않을 것 같아요.

2022-03-30 08:26 UTC, hongbin-dev commented on src/main/java/chess/domain/Board.java
> +    }
게임이 끝났는지도 확인이 필요합니다!

2022-03-30 08:26 UTC, hongbin-dev commented on src/main/java/chess/domain/Board.java
> +        return score - 0.5 * countSameRankPawnsOf(color);
0.5의 의미를 알 수 없군요 🥲 상수로 포장해볼까요?

2022-03-30 08:26 UTC, hongbin-dev commented on src/main/java/chess/domain/Board.java
> +                .sum();
이쪽도 포장해주세요!

2022-03-30 08:26 UTC, hongbin-dev commented on src/main/java/chess/domain/Board.java
> +    }
객체에게 메시지 보내는거 좋네요 👍

2022-03-30 08:26 UTC, hongbin-dev commented on src/main/java/chess/domain/ChessGame.java
> +    }
체스게임의 테스트코드가 보이지 않네요~
아무래도 생성자쪽에 `board = new Board(PieceFactory.createChessPieces());` 이 부분 때문인 것 같은데요.
어떻게하면 테스트하기 좋은 구조로 만들 수 있을까요?

2022-03-30 08:26 UTC, hongbin-dev commented on src/main/java/chess/domain/ChessGame.java
> +    }
보드의 책임이 많은 것 같아요! 계산해주는 로직을 분리하는게 어떨까요?

2022-03-30 08:26 UTC, hongbin-dev commented on src/main/java/chess/domain/Color.java
> +    public abstract String correctSignature(String signature);
추상메서드를 구현하는 것도 좋지만, 기능들을 enum의 멤버변수로 갖고있으면 가독성이 좋을 것 같습니다.

2022-03-30 08:26 UTC, hongbin-dev commented on src/test/java/chess/domain/command/CommandTest.java
> +    @DisplayName("값을 통해 Command 를 잘 찾는지")
MethodSource도 좋지만, 조금 읽기어려운 점이 단점인 것 같아요.
CSVsource로 대체가 가능해보이는데, 그쪽으로 변경해볼까요?

2022-03-30 08:26 UTC, hongbin-dev commented on src/test/java/chess/domain/command/MoveCommandTest.java
> +    @DisplayName("입력한 출발점과 도착점의 MoveCommand 를 생성하는지")
입력이 잘못들어올 수 있는 것 같은데, 그런케이스도 작성하면 좋을 것 같네요~

2022-03-30 08:26 UTC, hongbin-dev commented on src/test/java/chess/domain/piece/PawnTest.java
> +public class PawnTest {
폰이 2칸, 1칸, 대각선 이렇게 움직일 수 있는걸로 알고있는데요.
이런 행위단위(Displayname)로 테스트코드가 작성되면 읽기 좋을 것 같아요.

2022-03-31 15:54 UTC, sure-why-not commented on src/main/java/chess/domain/piece/Blank.java
> +public class Blank extends Piece {
기존에 리팩토링 하고싶었던 부분 중 하나인데, 기물을 상속받는 빈칸이라는 기물이 어색하다고 느껴지고 View 출력을 위한 기능들만 존재하는 것 같아서 Blank 를 삭제하였습니다!!

2022-03-31 15:57 UTC, sure-why-not commented on src/main/java/chess/domain/position/PositionX.java
> +    private final int coordination;
네네 좀 더 의미 전달이 잘 되도록 PositionX -> Column, PositionY -> Row 로 변경하고, 좌표 int 값의 네이밍은 file, rank 로 적절하게 변경했습니다!! 😄

2022-03-31 15:59 UTC, sure-why-not commented on src/main/java/chess/domain/piece/Piece.java
> +    }
네 그렇네요!! 😭 그래서 isDisplaced 의 상태를 없애고, 현재 Pawn rank 가 첫 rank 위치인지를 비교하여서 2칸을 움직이도록 변경했습니다!

2022-03-31 15:59 UTC, sure-why-not commented on src/main/java/chess/domain/piece/Knight.java
> +    }
오 이런 방식으로 새로운 객체를 만들지 않아도 되는군요!! 좋은 정보 감사합니다 😀

2022-03-31 16:00 UTC, sure-why-not commented on src/main/java/chess/domain/Board.java
> +        return score - 0.5 * countSameRankPawnsOf(color);
네네 맞습니다 이 부분도 리팩토링 후보 중 하나였어서, 현재는 저런 상수가 필요하지 않도록 로직을 수정했습니다!

2022-03-31 16:08 UTC, sure-why-not commented on src/main/java/chess/domain/position/PositionX.java
> +                .orElseThrow(() -> new IllegalArgumentException("유효하지 않은 좌표입니다."));
오 좋은 방법이네요!! 👍🏻 에러 메세지는 친절할수록 좋은 것 같네요 😃

2022-04-01 07:23 UTC, sure-why-not commented on src/main/java/chess/domain/piece/Bishop.java
> +public class Bishop extends Piece {
현재는 최초에 생성된 기물들 말고는 추가로 생성되지 않도록 변경한 상태입니다!! 🤗

2022-04-01 07:24 UTC, sure-why-not commented on src/main/java/chess/domain/piece/King.java
> +        }
체스 위의 움직임을 변위를 저장하고 판단하는 Movement 를 추가하여 해결했습니다!

2022-04-01 07:26 UTC, sure-why-not commented on src/main/java/chess/domain/position/Position.java
> +public final class Position {
좋은 방법인 것 같아요. Position은 64 종류만 생성될 가능성이 있기때문에 캐싱을 통해 객체를 계속해서 생성하지 않도록 해결했습니다!!

2022-04-01 07:42 UTC, sure-why-not commented on src/main/java/chess/domain/ChessGame.java
> +    }
네 맞습니다. 당시에 TDD 를 잘 적용하지 못했던 점을 반성하는 시간이었습니다. 😭 외부에서 Piece들을 넣어주도록 하여 테스트코드를 추가해두었습니다!!  😌

2022-04-01 07:50 UTC, sure-why-not commented on src/main/java/chess/domain/ChessGame.java
> +    }
네네 이전의 코드에선 Board 가 책임이 굉장히 많았었죠 😱 현재는 계산하는 로직을 Score 에서 수행하도록 변경했고, 경로를 찾는 것도 분리해볼 예정입니다.!!

2022-04-01 07:50 UTC, sure-why-not commented on src/test/java/chess/domain/command/MoveCommandTest.java
> +    @DisplayName("입력한 출발점과 도착점의 MoveCommand 를 생성하는지")
추가했습니다 !! 😄

2022-04-01 07:51 UTC, sure-why-not commented on src/test/java/chess/domain/piece/PawnTest.java
> +public class PawnTest {
모든 기물들이 행마법에 대한 테스트 코드가 부족했던 것 같아 왕창 추가해뒀습니다 ! 🤓

2022-04-01 11:54 UTC, sure-why-not reviewed
앨런 안녕하세요! 😀 라라입니다.

자세한 리뷰 해주셔서 새로운 부분들을 깨닫게 됐습니다. 감사합니다 !! 🤗 

코멘트 남겨주신 부분들 반영하였고, 추가적으로 궁금한 점이나 반영한 이유에 대해 코멘트로 남겨두었어요! ㅎㅎ

일단 이번 PR 에서는 아래와 같은 부분까지만 수정해보았습니다. 

1. 이동 방향/경로나 점수를 계산하는 핵심 로직들을 좀 더 가독성을 높히고 단순하게 풀어보려 해보았습니다.
    1. `Movement` 추가
    2. `Score` 추가
2. Piece 타입별 점수, 시그니처를 `PieceType` 을 추가하여 반영했습니다.
3. View 에 출력하기 위한 정보는 DTO 를 추가하여 반영했습니다.
4. 부족했던 테스트 코드들을 많이 많이 추가했습니다 !!

저번에 말씀드렸다시피 첫 PR 이 코로나 이슈로 굉장히 정리가 안되어있었네요.. 😭 이 부분들을 정리하고 반영하는데에도 꽤나 오래 걸린 것 같아요. 계속 수정하면서 반영하고 싶은 내용들이 있는데 그 부분까지 반영하면 PR 이 너무 늦어질 것 같아서 이 부분까지만 먼저 PR 보내겠습니다 !! 

수정하다보니 적용하면 좋을 것 같다고 느낀 부분이 있는데 괜찮은 아이디어일지 여쭤보고싶습니다!! 코멘트에 남겨두었습니다! ㅎㅎ

크루들과 얘기를 나눠보니 다양한 패턴들을 적용했더라구요. 그래서 조급한 마음이 들었는데.. 제 코드에 정말 필요하다고 느낄 때 반영해보고 싶어서 당장 사용하고 싶진 않더라구요. 🤔 (이런 태도가 오히려 안 좋을까요? 여러 패턴들을 시도해보는게 좋을까요...!!? ㅠㅠ)

아무쪼록 이번 리뷰도 잘 부탁드립니다. 🙇🏼‍♂️🙇🏼‍♂️

2022-04-01 11:54 UTC, sure-why-not commented on src/main/java/chess/Application.java
> +            }
### 추가적으로 반영하고 싶은 내용
이 부분과
```
if (command == Command.START) {
            startGame();
}
```
이 부분이 게임이 무엇을 진행할 수 있는 상태인지에 대해서 외부에서 알아야하고 외부에서 제어하고 있기 때문에 잘못되었다는 생각이 드는데 아직 완벽한 해결책을 찾지 못한 상태입니다.
상태 패턴 얘기를 많이 들었는데 아직 확실히 와 닿진 않아서 더 명확한 이유를 찾고 적용해보려 합니다!!

2022-04-02 18:08 UTC, hongbin-dev commented on src/test/java/chess/domain/command/CommandTest.java
> +    @DisplayName("값을 통해 Command 를 잘 찾는지")
enum객체가 변경됐을 때, 컴파일타임에 체킹이 안돼서 불편할 수도 있겠군요. 
유지하셔도 좋을 것 같습니다

2022-04-02 19:39 UTC, hongbin-dev requested changes
안녕하세요 라라!
피드백 적용하시느라 고생많으셨습니다. 많은 변경이 있었네요.
이만 머지하겠습니다. 피드백은 다음단계에서 적용해주세요~

2022-04-02 19:39 UTC, hongbin-dev commented on src/main/java/chess/dto/StatusDto.java
> +    }
생성자는 최대한 가볍게 작성해주시는게 좋을 것 같습니다.
```
double blackScore = scores.get(Color.BLACK);
        double whiteScore = scores.get(Color.WHITE);
        this.result = WinResult.of(blackScore, whiteScore);
```
또 위와같은 비즈니스는 클라이언트 코드에서 넣어주거나, 정적팩토리메서드를 고려해보는 것도 좋을 것 같아요.

2022-04-02 19:39 UTC, hongbin-dev commented on src/main/java/chess/Application.java
> +        ChessGame game = new ChessGame(PieceFactory.createChessPieces());
👍

2022-04-02 19:39 UTC, hongbin-dev commented on src/test/java/chess/domain/BoardTest.java
> +    }
게임이 종료됐을 때의 상황도 테스트가 있으면 좋겠네요.

2022-04-02 19:39 UTC, hongbin-dev commented on src/main/java/chess/domain/piece/AbstractPiece.java
> +public abstract class AbstractPiece {
AbstractPiece로 이름을 변경하신 이유가 있을까요?

2022-04-02 19:39 UTC, hongbin-dev commented on src/main/java/chess/dto/BoardDto.java
> +    }
이쪽도 생성자가 너무 무거운 것 같습니다.

2022-04-02 19:39 UTC, hongbin-dev commented on src/main/java/chess/dto/BoardDto.java
> +        return ".";
뷰에서 `.`을 넣어주긴 어려울까요~?

2022-04-02 19:39 UTC, hongbin-dev commented on src/main/java/chess/domain/piece/PieceType.java
> +public enum PieceType {
상속을 제거하고 PieceType이라는 객체를 컴포지션으로 가져가시려는 생각이신거죠?

`Piece 단 하나만 두어도 다양한 객체를 생성할 수 있고, 중복되는 isKing(), isPawn()도 PieceType 으로 쉽게 해결할 수 있을 것 같아서요`

이런 장점도 있을 것 같은데, 기존코드와 달라지는 점들은 어떤 게 있을까요?

2022-04-02 19:39 UTC, hongbin-dev commented on src/main/java/chess/domain/piece/Movement.java
> +    NORTH_UNLIMITED((columnDiff, rowDiff) -> columnDiff == 0 && rowDiff <= -1),
상수들을 분리하시느라 고생하셨겠군요 👍 이렇관리하는 것도 괜찮은 것 같아요. 

`NORTH_WEST_1STEP`, `NORTH_WEST_UNLIMITED` 이 두 부분은 한칸과 보드의 끝까지로 이해했는데요.
Movement가 아닌 방향이라는 개념으로 잡으면 UNLIMITED 부분은 분리될 수도 있을 것 같아요. 

위를 적용하게 된다면 findPredicate로 둔 상태를 integer, integer로 관리하면 코드의 가독성을 챙길 수 있을 것 같아요.

(이 부분은 꼭 반영안하셔도 됩니다)

2022-04-02 19:39 UTC, hongbin-dev commented on src/main/java/chess/domain/Score.java
> +    public static Score of(Map<Position, AbstractPiece> pieces) {
1. 정적팩토리 of() 메서드가 체스의 비즈니스 룰에 따라서 생성되는걸로 보입니다. ChessScore라는 이름으로 적용되면 크게 어색하진 않아보이는데요. 라라 생각은 어떠세요?
2. 유틸클래스는 피할 순 없다고 생각해요. 하지만 위 말처럼 of는 체스비즈니스 룰에 맞춰서 값을 계산하고 있어서요. 유틸클래스와는 조금 거리가 있지 않을까요?

'꼭 값 객체로만 봐야할까?' 라는 생각이 듭니다. 아래와 같은 비즈니스는 어떨까요?

```java
score = new Score(pieces);
score.calculate()
```

2022-04-02 19:39 UTC, hongbin-dev approved these changes

2022-04-02 19:39 UTC, merged

2022-04-04 07:02 UTC, hongbin-dev commented
라라! 코멘트에 답변을 못드렸네요

> 크루들과 얘기를 나눠보니 다양한 패턴들을 적용했더라구요. 그래서 조급한 마음이 들었는데.. 제 코드에 정말 필요하다고 느낄 때 반영해보고 싶어서 당장 사용하고 싶진 않더라구요. 🤔 (이런 태도가 오히려 안 좋을까요? 여러 패턴들을 시도해보는게 좋을까요...!!? ㅠㅠ)

저도 라라의견에 공감하는 편이에요. 합당하다싶으시면 적용해도 좋을 것 같아요.
패턴에 집중하기보다는 문제에 집중하는게 좋아보입니다.

2022-04-04 16:34 UTC, sure-why-not commented on src/test/java/chess/domain/BoardTest.java
> +    }
아 그렇네요!! 추가하겠습니다. ☺️