[1, 2, 3단계 - 체스] 클레이(양동주) 미션 제출합니다.
woowacourse/java-chess pull request #328
Opened 2022-03-28 08:28 UTC by yangdongjue5510

안녕하세요 닉!
이번 체스 미션을 함께하게 된 클레이입니다!

이번 미션은 많이 어려워서 아직 완성도가 많이 떨어진 상태로 리뷰 요청드리게 됐네요 😿
궁금하거나 부족했던 부분은 중간에 코멘트로 남겨놓을게요!

되도록 많이 지적해주시면 감사드리겠습니다!

2022-03-28 08:29 UTC, yangdongjue5510 commented on src/main/java/chess/controller/ChessController.java
> +    }
예외가 발생하면 다시 시작할 수 있는 기능을 만들어봤습니다

2022-03-28 09:42 UTC, yangdongjue5510 commented on src/main/java/chess/controller/ChessController.java
> +    }
도중에 예외가 생기면 처음부터 다시 하도록 했습니다.

2022-03-28 09:43 UTC, yangdongjue5510 commented on src/main/java/chess/controller/ChessController.java
> +    }
컨트롤러의 상태에 따라 실행 가능한 명령어만 받아들입니다.
각 명령어에 따라 컨트롤러의 메서드를 호출해서 실행시킵니다.

2022-03-28 09:44 UTC, yangdongjue5510 commented on src/main/java/chess/controller/GameCommandRequest.java
> +    }
사용자의 입력을 마치 웹처럼 커맨드(HTTP 메서드와 비슷한 것 같았습니다.)와 바디로 구분했습니다.
모든 메서드가 이 객체를 통해 요청을 처리하도록 했습니다.

2022-03-28 09:47 UTC, yangdongjue5510 commented on src/main/java/chess/model/Direction.java
> +    }
요구사항에 getter를 사용하지 말라고 했는데,
체스 기물의 위치값인 Square의 위치를 Direction을 통해 움직이다 보니, 어쩔 수 없이 getter를 사용했습니다.
제 생각에는 다른 방법이 떠오르지 않아 일단 이렇게 했는데, 찜찜하긴 합니다.
애초에 설계를 잘못해서 이런 걸까요? 아니면 이 정도는 괜찮을까요? 닉의 의견이 궁금합니다.

2022-03-28 09:51 UTC, yangdongjue5510 commented on src/main/java/chess/model/Square.java
> +    }
이 부분은 최대공약수를 구하는 부분인데,,,
두 좌표를 통해 방향을 알아내려면 필요했습니다.
x값 차이의 절대값 과 y값 차이의 절대값 의 최대 공약수로 각 값의 차이를 나눠주면, Direction의 row와 col 형태로 나와서 방향을 구할 수 있었습니다.

2022-03-28 09:53 UTC, yangdongjue5510 commented on src/main/java/chess/model/Square.java
> +    }
폰이 처음 위치인지 확인하려면 결국 Square에서 확인을 해야 했습니다.
이 메서드가 있는게 조금 어색하네요.... 아무래도 설계를 잘못해서 그런거겠죠?

2022-03-28 09:57 UTC, yangdongjue5510 commented on src/main/java/chess/model/board/Board.java
> +    }
방향이 맞고 거리가 맞다는 전제 하에, 위치를 한번씩 옮겨가면서 목표까지 가는 길에 다른 기물이 없는지 확인하는 방식으로 로직을 짯습니다.
board에 왼쪽 위부터 오른쪽 아래까지 순서대로 저장을 하는 방식이라 인덱스를 구해서 수정해주는 방식으로 말을 이동시켜줘야 했습니다... 이 부분도 순서에 의존하지 않고 말들을 관리 할 수 있으면 좋을 것 같은데 아쉬웠습니다...

2022-03-28 09:58 UTC, yangdongjue5510 commented on src/main/java/chess/model/piece/Pawn.java
> +    }
폰은 진영에 따라 갈 수 있는 방향이 달라져서 추가된 메서드입니다.

2022-03-28 10:00 UTC, yangdongjue5510 commented on src/main/java/chess/model/piece/Piece.java
> +    public Piece(final Color color, final Square square, final MovableStrategy strategy) {
사실 이 클래스를 이렇게 크게 만들 생각은 없었는데 계속 하다보니 이 클래스한테 자꾸 역할이 많이 생기더라구요.
이 클래스를 어떻게 작게 나눌 수 없나? 라고 고민했는데 잘 떠오르지 않았습니다..😿

2022-03-28 10:02 UTC, yangdongjue5510 commented on src/main/java/chess/model/piece/Piece.java
> +    }
이 getter는 폰의 경우 자기가 어디 진영인지, 자기가 현재 시작점에 있는가에 따라서 움직임이 달라져서 추가된 메서드 입니다....
역시 맘에 들지는 않네요 😿

2022-03-28 10:03 UTC, yangdongjue5510 commented on src/main/java/chess/model/piece/strategy/LimitedMovableStrategy.java
> +public class LimitedMovableStrategy implements MovableStrategy {
기물들의 움직임을 따로 분리하려고 만들었습니다.
이동 가능한 칸 수가 제한되어 있는지에 따라 분리 했습니다.

2022-03-28 10:05 UTC, yangdongjue5510 commented on src/main/java/chess/model/piece/strategy/PawnMovableStrategy.java
> +    }
음.... 이 부분이 제일 아쉬웠습니다. 폰으로 명시적 형변환 해줘서 현재 처음 위치인지 확인해줘야 했습니다...
애초에 갈 수 있는지 확인하는 로직을 분리하는게 아닌가? 싶기도 했습니다.
근데 막상 분리 안하면 중복 코드가 엄청 생겼습니다.

2022-03-28 10:08 UTC, yangdongjue5510 commented on src/main/java/chess/model/board/Board.java
> +        return piece.getPoint().getValue();
이 부분도 getter를 사용하게 됐습니다...
게다가 한 줄에 여러 점을 찍고 있어서 많이 아쉬운 부분입니다 ㅠㅠ...

2022-03-28 15:00 UTC, wbluke requested changes
안녕하세요 클레이~! 체스 미션 리뷰를 맡은 닉입니다 🙌 
코멘트에 남겨주신 고민들 잘 봤어요 ㅎㅎㅎ
저도 답변 남겼는데, 한번 리팩토링 해보면서 조금 더 고민해보면 좋을 것 같아요 🙂

2022-03-29 13:30 UTC, yangdongjue5510 commented on src/main/java/chess/controller/ChessController.java
> +        while (!gameState.isEnd(service)) {
오 확실히 `!`가 읽기 어렵게 만드네요!

다음과 같은 경우는 어떻게 생각하는지 궁금해요.
1. 서로 다른 객체인지 확인하는 `!from.equals(other)`
`isDifferent(Square other)`같은 새로운 메서드를 만들었어요. 그런데 이미 equals를 재정의 했는데 굳이 새로운 메서드를 만들어줘야 되나? 싶기도 하네요.
2. 타겟이 같은 팀이 아닌지를 확인하는 `!target.isAlly(source)`
이동 할 때 이동할 곳에 같은 팀 기물이 있으면 안되서 사용한 코드에요. `target.isNotAlly(source)` 이런 내용을 새로운 메서드로 만들어서 사용해야 되나 고민했는데, 저는 굳이 그렇게 해야되나 싶긴 했어요. `isAlly isNotAlly` 이런식으로 메서드를 만드는게 맞나? 싶었어요.

2022-03-29 13:44 UTC, yangdongjue5510 commented on src/main/java/chess/model/board/ChessInitializer.java
> +            pieces.add(piece);
헉... 왠지 있을 것 같았는데 역시 있었군요! IDE를 잘 활용해보도록 하겠습니다..! 감사합니다 😸

2022-03-29 15:10 UTC, yangdongjue5510 commented on src/main/java/chess/model/Square.java
> +        return new Square(file, rank);
`Map<Entry<File, Rank>>`에 Square를 캐싱해봤습니다!!
`putIfAbsent`를 활용해서 캐싱 안된 인스턴스를 캐싱하고 반환하는 방식을 구현해봤습니다!

2022-03-30 01:50 UTC, yangdongjue5510 commented on src/main/java/chess/controller/ChessController.java
> +    }
승자를 판별하는 느낌이라서 컨트롤러에 뒀는데, 지금 보니 View 로직 인 것 같네요!
View 쪽에서 처리하도록 수정하겠습니다!

2022-03-30 01:53 UTC, yangdongjue5510 commented on src/main/java/chess/model/Direction.java
> +    }
Bishop, Rook, Knight는 각 말에서 관리하는게 자연스러울 것 같은데, 문제는 King, Queen이 방향이 동일해서 중복코드가 생기더라구요.
그래서 `getRoyalDirection()`으로 모아서 처리하고 싶은데 어떻게 생각하시나요?

2022-03-31 01:35 UTC, yangdongjue5510 commented on src/main/java/chess/model/board/Board.java
> +    }
Map<Square, Piece> 자료구조로 바꿨습니다!

2022-03-31 01:35 UTC, yangdongjue5510 commented on src/main/java/chess/model/piece/Pawn.java
> +    }
오... BlackPawn과 WhitePawn으로 나눠서 구현해보겠습니다..!

2022-03-31 01:36 UTC, yangdongjue5510 commented on src/main/java/chess/model/piece/Piece.java
> +    public Piece(final Color color, final Square square, final MovableStrategy strategy) {
Piece에서 위치정보를 제거 하도록 할게요!

2022-03-31 01:39 UTC, yangdongjue5510 commented on src/main/java/chess/model/piece/strategy/PawnMovableStrategy.java
> +    }
WhitePawn과 BlackPawn마다 자기진영 시작 위치(Rank)를 전략에 전달해주도록 수정해봤어요!!

2022-03-31 01:47 UTC, yangdongjue5510 commented on src/main/java/chess/controller/ChessController.java
> +    private static void runUntilValid(Runnable runner) {
원래 뷰에서 있었던 로직이라 static을 붙여놨었던 거 같아요!
static 키워드 제거하겠습니다!!

2022-03-31 02:00 UTC, yangdongjue5510 commented on src/main/java/chess/controller/ChessController.java
> +            GameCommand.END, this::end, GameCommand.STATUS, this::status);
음... 고민해봤는데, GameCommand에서 이 역할을 하도록 수정해봤어요!
이렇게 수정하니까 컨트롤러의 메서드가 public으로 열려야 되는 부분이 있긴하네요..!
한번 보시고 어떤지 말씀해주시면 감사하겠습니다..!

2022-03-31 02:24 UTC, yangdongjue5510 commented on src/main/java/chess/util/PieceToLetterConvertor.java
> +            Pawn.class, "p", Empty.class, ".");
오.. 이런 경우에는 Enum을 활용하는게 더 좋을 것 같아요!
반영하겠습니다!!

2022-03-31 02:29 UTC, yangdongjue5510 commented on src/main/java/chess/model/Direction.java
> +    }
아하 이해가 한번에 됐습니다!!
getter가 반드시 필요한 경우인지 고민하고 사용하도록 하겠습니다..!

2022-03-31 02:47 UTC, yangdongjue5510 commented on src/main/java/chess/controller/ChessController.java
> +    }
앗 확실히 웹 환경이라 생각하니 이상하네요..!
`명령어 입력 -> 명령어 수행 -> 출력` 이렇게 한 사이클로 보고,
한 사이클 안에서 에러가 생기면 다시 해당 사이클을 실행시키는 방식으로 수정해봤습니다!
이 부분도 보시고 의견주세요!!

2022-03-31 03:02 UTC, yangdongjue5510 commented
안녕하세요 닉!!!
이번엔 대대적인 리팩토링을 해서 리뷰 요청이 다소 늦었네요 ㅠㅠ...
닉이 주신 의견을 나름대로 해석하고 반영하려고 해봤습니다.

제가 바꿔본 부분이 잘못됐거나 의아하면 피드백 부탁드려요!!
항상 감사드립니다!!

2022-03-31 03:04 UTC, yangdongjue5510 commented on src/main/java/dbstudy/dao/Member.java
> +public class Member {
이 부분은 본 미션과는 관련없는 코드입니다..
DB 수업 시간때 사용했던 코드인데 gitignore에 빠진 부분이라 같이 커밋됐네요..
죄송합니다.

2022-03-31 03:05 UTC, yangdongjue5510 commented on src/main/java/dbstudy/dao/MemberDao.java
> +public class MemberDao {
이 부분도 DB 수업 관련 코드입니다ㅠㅠ

2022-03-31 03:05 UTC, yangdongjue5510 commented on src/main/java/dbstudy/dao/Role.java
> +    private final String role;
이 부분도 DB 수업 관련 코드입니다.. ㅠㅠ

2022-04-01 10:26 UTC, wbluke approved these changes
피드백 반영 잘 해주셨네요 👍 
다음 단계 진행해 주세요 🙂

2022-04-01 10:26 UTC, wbluke commented on src/main/java/chess/controller/ChessController.java
> +        while (gameState.isRunning(service)) {
> 1. 서로 다른 객체인지 확인하는 `!from.equals(other)`
`isDifferent(Square other)`같은 새로운 메서드를 만들었어요. 그런데 이미 equals를 재정의 했는데 굳이 새로운 메서드를 만들어줘야 되나? 싶기도 하네요.
> 2. 타겟이 같은 팀이 아닌지를 확인하는 `!target.isAlly(source)`
`target.isNotAlly(source)` 이런 내용을 새로운 메서드로 만들어서 사용해야 되나 고민했는데, 저는 굳이 그렇게 해야되나 싶긴 했어요.
`isAlly(target)`이 다른 곳에도 필요해서, 결국 `isAlly(target)`와 `isNotAlly(target)` 모두 사용하게 되는데 이런 식으로 메서드들을 만드는게 조금 어색했어요.

오 네네 제가 이해하기로는 1, 2가 같은 내용인 것 같은데 맞나요?
상황에 따라 다를 것 같은데요.
```java
if (!method()) {
    // do A
    return;
}
// do B
```
이런 경우 if문 내의 로직이 예외적인 상황이라 Early return 형태가 아니라면
```java
if (method()) {
    // do B
    return;
}
// do A
```

이렇게 흐름을 가져가는 것도 가능할 것 같고요.

equals 같은 경우는 그나마 인지하기 쉬운 편이라 나을 것 같지만, `isAlly()`나 `isNotAlly()`의 경우는 둘 다 만들어주면 좋다고 생각하긴 해요. 말씀하신대로 둘 다 빈번하게 사용하게 되면 더더욱이요!
나랑 같은 팀인지 아닌지에 대한 판단 정보를 API를 제공하는 쪽에서 친절하게 제공해주면 그것을 사용하는 클라이언트가 자연스럽게 선택해서 사용할 수 있을 것 같거든요.
저번에 말한대로 클라이언트 측 실수의 여지도 줄어들고요.
어색하다고 생각하신 지점이 어떤 부분인지 조금 더 구체적으로 말씀해주셔도 좋을 것 같아요 :)

2022-04-01 10:26 UTC, wbluke commented on src/main/java/chess/controller/GameCommand.java
> +    STATUS("status", ChessController::status);
네네 map으로 관리하던 것보다 훨씬 나은 것 같아요 👍

2022-04-01 10:26 UTC, wbluke commented on src/main/java/chess/model/ChessGame.java
> +        throw new IllegalArgumentException("해당 기물을 움직일 권한이 없습니다. 현재 " + turn.name() + "의 차례입니다.");
String.format()을 사용해보면 어떨까요? :)

2022-04-01 10:26 UTC, wbluke commented on src/main/java/chess/model/board/Square.java
> +        return squareCache.get(squareName);
잘 해주셨네요 👍 
그리고 squareCache는 상수 컨벤션을 지켜주세요 :)

2022-04-01 10:26 UTC, wbluke commented on src/main/java/chess/model/strategy/LimitedMovableStrategy.java
> +            Distance distance = source.getDistance(target);
사용을 안하는 듯 하네요 :)

2022-04-01 10:26 UTC, merged

2022-04-01 12:35 UTC, yangdongjue5510 commented on src/main/java/chess/model/strategy/LimitedMovableStrategy.java
> +            Distance distance = source.getDistance(target);
`UnlimitedMovableStrategy`에서는 거리를 사용하지 않았네요! 수정하겠습니다!!

2022-04-01 12:50 UTC, yangdongjue5510 commented on src/main/java/chess/model/ChessGame.java
> +        throw new IllegalArgumentException("해당 기물을 움직일 권한이 없습니다. 현재 " + turn.name() + "의 차례입니다.");
`String.format()`을 사용하니 훨씬 가독성이 좋아졌네요!!
반영하겠습니다!

2022-04-01 13:03 UTC, yangdongjue5510 commented on src/main/java/chess/controller/ChessController.java
> +        while (gameState.isRunning(service)) {
아하.. 제 개인적인 생각은 `isAlly()`로 이미 상대가 같은 편인지 확인할 수 있는데 굳이 `IsNotAlly`를 제공해줘야 되나? 이 부분이 조금 어색했어요. 특히 `isAlly`와 `isNotAlly` 내부 구현도 엄청 비슷해서 뭔가 중복코드 같이 보이기도 했어요. 
닉의 의견을 읽고 나니 빈번하게 사용되면 `isNotAlly` 를 제공해주는 것도 가독성이나 실수 예방 차원에서 많은 도움이 될 것 같네요!