[1, 2, 3단계 - 체스] 수달(허수진) 미션 제출합니다.
woowacourse/java-chess pull request #334
Opened 2022-03-28 08:35 UTC by her0807

2022-03-29 02:21 UTC, her0807 reviewed
안녕하세요 에던 😄  ✋🏻 

수달입니다. 

이번 미션에서는 요구사항 반영에 초점을 맞춰 페어를 진행했습니다.

요구사항이 어려워 모두 녹여내려고 하다보니 클린 코드와 멀어진 것 같기도 합니다.. 😢 

리뷰 작성하실 때 조금이나마 보탬이 되고자, 아래 코멘트를 달아보았습니다. ㅎㅎ

잘부탁드립니다.

2022-03-29 02:21 UTC, her0807 commented on src/main/java/chess/domain/piece/Team.java
> +    }
체스 판 출력할 때, 흑팀은 대문자, 백팀은 소문자로 출력되게끔 로직을 작성했습니다!

2022-03-29 02:21 UTC, her0807 commented on src/main/java/chess/domain/position/Position.java
> +    }
### 여러칸을 가는 경우 방향 검증
룩, 비숍, 퀸과 같이 여러 칸을 갈 수 있는 경우,
칸의 갯수와 상관 없이 방향이 맞냐를 확인하기 위해 convertCompactValue 를 사용하여 변환했습니다!

2022-03-29 02:21 UTC, her0807 commented on src/main/java/chess/menu/Menu.java
> +}
## 조건 분기문을 제거하기 위한 로직

프로그램을 동작시키고 최초로 start, move, status, end 와 같이 메뉴 명령어를 입력 받고,

그 명령에 따른 행위를 동작시켜야 하는 부분에서 조건 분기 문이 많아졌습니다.

그부분을 해결하기 위해 Menu 라는 인터페이스를 만들고, 명령어마다 다른 행위를 하게끔 로직을 작성했습니다!

(어떤 자료를 참고한게 아니라, 제 느낌으로 작성한거라서 잘못된 방법이라면, 말씀해주세요 🤕)

2022-03-29 02:21 UTC, her0807 commented on src/main/java/chess/view/Command.java
> +    private Position afterPosition;
## 불필요한  인스턴스 변수?

이 클래스는 최초에 명령어를 입력받고

`Move 일 경우 뒤에 따라오는 현재 위치와 이동 위치를 함께 보관`하기 위해 만든 클래스 입니다. 

이말인 즉, move 외 다른 명령어(start, status, end) 일 때는 Position 이 비어있게 된다는 의미이기도 합니다. 😭 

더 좋은 방법이 있을까요?

2022-03-29 15:13 UTC, Laterality requested changes
안녕하세요 수달,

리뷰어 에단입니다 :)

계속 변경될 코드에는 리팩터링도 중요하지만 필요한 기능이 무엇인지 정확하게 파악하는 것이 훨씬 중요합니다. 시간을 충분히 들이시는 게 바람직하다고 생각해요.

몇가지 코멘트 남겨드렸습니다. 확인 부탁드려요. 

질문이 조금 난해할 수도 있으니, 궁금하신 점은 언제든 DM 주세요 :)

2022-03-29 15:13 UTC, Laterality commented on src/main/java/chess/view/OutputView.java
> +    public static void printStatus(Map<Team, Double> status, List<Team> result) {
`result`에는 어떤 리스트가 전달될까요?

2022-03-29 15:13 UTC, Laterality commented on src/test/java/chess/domain/position/PositionTest.java
> +    @DisplayName("좌표 이동")
좌표가 이동하는 것을 검증하는 테스트일까요?

2022-03-30 03:59 UTC, her0807 commented on src/main/java/chess/domain/board/BasicBoardGenerator.java
> +public class BasicBoardGenerator implements BoardGenerator {
오오! 특정 단어를 이름에 사용하여 패턴을 드러낼 수 있군요! ㅎㅎ 
그렇게한다면 다른 분들이 제 코드를 읽는데 큰 도움이 되겠네요. 변경해보겠습니다. 👍🏻 
(새롭게 알게 된 내용은 적용해보며 장/단점을 파악하고자 하고 있어요 ㅎㅎㅎ )

2022-03-30 04:47 UTC, her0807 commented on src/main/java/chess/domain/piece/Team.java
> +    }
대소문자 구분 이라는 의미의 단어 `case-sensitive` 를 사용하여 변경해 보겠습니다. 😄

2022-03-30 08:26 UTC, her0807 commented on src/main/java/chess/domain/position/Position.java
> +    }
고민해보고 변경해보겠습니다!

2022-03-30 09:51 UTC, her0807 commented on src/main/java/chess/view/Command.java
> +    private Position afterPosition;
오오.. 에단의 질문에서 답을 찾은 것 같습니다.  Command -> MenuInfo 로 변경 후, Menu 에 대한 처리만 하도록 변경하면 되겠군요 !!! 감사합니다 👍🏻

2022-03-30 10:48 UTC, her0807 commented on src/main/java/chess/ChessGame.java
> +        boolean nextStep = true;
오오! 변경하겠습니다 이런 부분들이 쌓여서 읽기 좋은 코드가 되는 것 같아요 정말 감사합니다. 👍🏻

2022-03-30 10:54 UTC, her0807 commented on src/main/java/chess/domain/board/Board.java
> +        return board;
의도치 않은 곳에서 변경될 여지가 있군요! Board 의 참조 값을 끊기 위해 CopyOf 사용해 보겠습니다 👍🏻

2022-03-30 11:23 UTC, her0807 commented on src/main/java/chess/domain/board/Board.java
> +    private void validCanMove(Position from, Position to) {
valid 가 형용사였군요 ..! 앞으로 한번씩 찾아보는 습관을 가져야겠습니다... 😢  `valid -> validate `로  변경하겠습니다.

2022-03-30 11:26 UTC, her0807 commented on src/main/java/chess/domain/board/Score.java
> +    King(0.0f),
헙 빠르게 리팩토링하려다보니 잔 실수가 많이 있네요. 죄송합니다 😭

2022-03-30 11:34 UTC, her0807 commented on src/main/java/chess/domain/board/Board.java
> +    private boolean checkAnyMatch(Position to) {
전체적으로 메서드 명에 관해 고민해보겠습니다!

2022-03-30 11:37 UTC, her0807 commented on src/main/java/chess/domain/board/Board.java
> +            return !canMoveKing(kingPaths);
오오,, `부정 연산자는 크기가 작아서 읽다보면 놀치기 쉽다.!` 새로운 인사이트를 얻었습니다 👍🏻

2022-03-30 11:42 UTC, her0807 commented on src/main/java/chess/domain/piece/Direction.java
> +    public static List<Direction> pullKnightDirections() {
행위에 대한 설명으로 변경해보겠습니다!

2022-03-30 11:49 UTC, her0807 commented on src/main/java/chess/domain/position/Position.java
> +    public Direction findDirection(Position position, Piece piece) {
`destination` 로 변경하겠습니다. 😄

2022-03-30 11:50 UTC, her0807 commented on src/main/java/chess/menu/Type.java
> +public enum Type {
아주 좋네요! MenuType 으로 변경하겠습니다.

2022-03-30 11:51 UTC, her0807 commented on src/main/java/chess/menu/Type.java
> +    }
제거한다는 걸,, 깜빡했습니다  죄송합니다 😅

2022-03-30 11:54 UTC, her0807 commented on src/main/java/chess/view/OutputView.java
> +    public static void printStatus(Map<Team, Double> status, List<Team> result) {
승리한 팀을 전달 받게 됩니다. `result ` -> `winnerResult` 로 변경하여 의미 전달이 잘 되게끔 수정하겠습니다 👍🏻

2022-03-30 12:13 UTC, her0807 commented on src/test/java/chess/domain/position/PositionTest.java
> +    @DisplayName("좌표 이동")
현재 위치와 이동 위치로 이동할 방향을 찾는 테스트 입니다. 변경하겠습니다!

2022-03-30 12:21 UTC, her0807 commented on src/main/java/chess/ChessGame.java
> +public class ChessGame {
`controller` 패키지를 추가하여 역할을 나타내겠습니다. 

추가로 웹과 통신할 때처럼 컨트롤러 로직을 작성하지 않은 이유는 1,2,3 단계에서는 콘솔로만 입력을 받아 **아직은  컨트롤러를 경유하는 로직이 불필요하다고 생각했습니다.**

4,5 단계를 진행할 때 추가하겠습니다!

2022-03-30 12:58 UTC, her0807 commented
안녕하세요 에단 👍🏻 

첫 리뷰를 보낼 때 `네이밍` 실수를 많이 한 것 같아 죄송합니다. (코드 이해하느라 힘드셨죠 .. 😢 ) 

이번 리팩토링은 코드를 조금더 이해하기 쉽게 변경해보았습니다.

감사합니다 :) 

Ps.  네이밍에 관한 고민을 하다가 문득 에단을 닉네임으로 지으신 이유가 궁금했습니다. 😄  
저는 수달을 닮아서.. 수달입니다 (^^) 🦦

2022-03-31 00:30 UTC, Laterality requested changes
안녕하세요 수달, 

잘 수정해주셨어요 👍 

몇군데 추가로 코멘트를 남겨드렸어요. 확인 부탁드려요.

제 닉네임은 그 때 생각났던 이름을 쓴 거라 특별히 이유가 있지는 않아요 😅

2022-03-31 00:30 UTC, Laterality commented on src/main/java/chess/domain/piece/Team.java
> +    private final BiPredicate<Double, Double> condition;
무엇을 확인하는 `condition`일까요?

2022-03-31 00:30 UTC, Laterality commented on src/main/java/chess/domain/piece/Team.java
> +    public String changeCaseSensitive(String pieceName) {
이 부분도 한번 고민해볼 수 있겠네요. 

1. 이 메서드는 각 말을 문자열로 나타내기 위해 필요한 메서드입니다.
2. "각 말을 문자열로 나타내는 것"은 도메인에서 필요로 하는 기능일까요?
3. 만약, 말을 더이상 문자열로 나타내지 않게 되더라도(e.g., 웹 페이지 등) 이 기능이 계속 필요할까요?

2022-03-31 09:41 UTC, her0807 commented on src/main/java/chess/domain/piece/Piece.java
> +    public void validateArrive(Piece to, Direction direction) {
에단의 피드백을 받고 다시 살펴보니 그렇네요! 👍🏻 
도착 위치에 같은 팀의 말이 있는지를 검사하고 싶었는데, 조금더 구체화 해보겠습니다!

2022-03-31 14:06 UTC, her0807 commented on src/main/java/chess/domain/piece/Team.java
> +    private final BiPredicate<Double, Double> condition;
승패 여부를 얻기 위한 condition 임을 변수명으로 나타나겠습니다.

2022-03-31 14:09 UTC, her0807 commented on src/main/java/chess/view/MoveInfo.java
> +public class MoveInfo {
이 부분은 불필요할 것 같아 제거했습니다! 알려주신 클린 코드2장은 읽어보겠습니다 😄  👍🏻

2022-03-31 14:34 UTC, her0807 commented on src/main/java/chess/domain/piece/Team.java
> +    public String changeCaseSensitive(String pieceName) {
아하 ! 이부분은 뷰로 옮겨보겠습니다 👍🏻

2022-04-01 12:51 UTC, Laterality approved these changes
안녕하세요 수달,

잘 수정해주셨어요 💯 

이번 미션은 이만 머지하도록 할게요.

고생 많으셨습니다 :)

2022-04-01 12:51 UTC, merged