[1, 2, 3단계 - 체스] 슬로(이한울) 미션 제출합니다.
woowacourse/java-chess pull request #336
Opened 2022-03-28 08:40 UTC by hanull

2022-03-28 11:49 UTC, hanull commented on src/main/java/chess/view/InputView.java
> +    private static void validateStartCommand(final String command) {
입력이 제대로 됐는지 `단순 문자열 검증` 로직은 InputView 에 포함해도 괜찮지 않을까? 라는 생각했는데요,  희봉은 어떻게 생각하시나요??!!

2022-03-29 14:03 UTC, heebong requested changes
안녕하세요, 슬로! 리뷰어 희봉입니다. 😄 
체스 미션을 잘 구현해주셨네요 👍 `Player`를 추가해서 진행한 부분이 인상적이었습니다.
몇가지 생각할 것을 코멘트로 남겼어요. 질문주신 내용도 댓글로 남겼습니다. 확인 부탁드려요. 궁금한게 생기면  언제든 DM 주세요!

2022-03-30 07:35 UTC, hanull commented on src/main/java/chess/domain/piece/Pawn.java
> +        if (distance != PAWN_DEFAULT_MOVE_DISTANCE && distance != PAWN_FIRST_MOVE_DISTANCE) {
오 Set으로 변경해봤는데, 가독성이 더 좋은 것 같아요

```java
final boolean isMovable = FIRST_MOVE_DISTANCE.contains(distance);
if (!isMovable) {
    throw new IllegalArgumentException("폰은 첫번째 턴에는 1칸 또는 2칸만 이동할 수 있습니다.");
}
```

2022-03-30 08:15 UTC, hanull commented on src/main/java/chess/domain/piece/Piece.java
> +    public abstract boolean exist(Position checkingPosition);
앗 확인하지 못했네요 default 메서드로 변경했어요

2022-03-30 08:46 UTC, hanull commented on src/main/java/chess/domain/piece/Pawn.java
> +            throw new IllegalArgumentException("폰은 상대 말이 존재할 경우만 대각선으로 1칸만 이동할 수 있습니다.");
예외 메세지가 적절하지 않고 두 검증이 함께 있어서 어디서 예외가 발생했는지 찾기 어렵겠네요!
검증을 대각선으로 이동하지 않는 경우, 대각선으로 이동하는 거리가 1이 이닌 경우로 분리 할게요

2022-03-31 05:50 UTC, hanull commented on src/main/java/chess/domain/piece/Pawn.java
> +    public boolean isPawn() {
넵 테스트 추가했어요! 

### 궁금한 점
isPawn() 메서드가 Piece 추상 클래스에 디폴트로 선언되어 있는데요, 이럴 경우에 어느 곳에서 테스트 코드를 작성하는 것이 좋을까요?
1. 각각의 체스말 테스트에서 isPawn() 테스트 코드를 작성한다.
2. 폰 테스트 클래스에서 폰인 경우, 아닌 경우를 모두 테스트 코드 작성한다.

- 저는 폰 테스트라서 폰 테스트 코드에서 모두 테스트하는 것이 좋다고 생각했어요

2022-03-31 07:08 UTC, hanull commented on src/main/java/chess/domain/ChessMap.java
> +        };
넵 그런데 제가 저런 방법을 선택한 이유는 
체스라는 룰이 거의 바뀔 일이 없을 것이라고 생각했어요. 그래서 반복분으로 메서드를 분리해서 만드는 것보다, 명시적으로 선언해주는 것이 더 가독성이 높은 방법이라고 생각했어요. 
희봉은 어떻게 생각하시나요??

2022-03-31 07:11 UTC, hanull commented on src/main/java/chess/domain/ChessMap.java
> +        };
### 추가적인 질문
현재 ChessMap 클래스를 맵 출력시에만 유틸 클래스처럼 사용하고 있는데요. 클래스 위치를 view 패키지로 분리시켜주는 것이 더 좋을까요?!

2022-03-31 08:54 UTC, hanull commented on src/main/java/chess/domain/Position.java
> +    private final char file;
rank와 file 검증 로직, 이동 거리 계산하는 로직을 각각 관리할 수 있겠네요! 
그리고 rank, file 모두 일정한 범위의 값만 사용하기 때문에, 매번 새로운 변수를 만들 필요없이 사용할 수 있을 것 같아요.

2022-03-31 13:59 UTC, hanull commented on src/main/java/chess/domain/generator/BlackGenerator.java
> +public class BlackGenerator implements Generator {
중복되는 부분을 추상 클래스로 만들고, 하위 클래스에서는 pawn의 rank와 rank 값을 재선언 하는 방법으로 중복 제거해봤어요!

2022-03-31 15:32 UTC, hanull commented on src/main/java/chess/domain/Position.java
> +    public List<Position> findAllBetweenPosition(final Position destination) {
MoveChecker 클래스를 만들어서 `움직임 확인하는 역할`을 위임했어요. 
이렇게 변경하니까 확실이 테스트가 쉬워진 것 같아요!

2022-04-01 09:14 UTC, heebong approved these changes
안녕하세요, 슬로! 리뷰어 희봉입니다.
피드백 반영을 잘 해주셨네요! 코드가 더 깔끔해졌습니다. 👍 
1단계는 이만 머지하도록 할게요. 추가로 고민해볼 부분을 코멘트로 남겼으니 2단계를 진행하면서 확인 부탁드립니다. 궁금한점이 생기면 언제든 DM 아시죠? 💌  그럼 2단계에서 만나요~

2022-04-01 09:14 UTC, heebong commented on src/main/java/chess/domain/ChessMap.java
> +        };
저 판은 가로는 Rank의 수만큼, 세로는 File의 수만큼 만들어지죠. Rank와 File만큼 만들어진다는게 보이면 더 파악하기 쉬울 것 같아요.

2022-04-01 09:14 UTC, heebong commented on src/main/java/chess/domain/ChessMap.java
> +        };
`추가적인 질문`은 2단계 미션을 하면 답을 찾을 수 있을 것 같아요! 😄 
(노출하기위해 만들어지는 클래스라면 뷰를 위한 클래스가 맞습니다 🙂 )

2022-04-01 09:14 UTC, merged