[1, 2, 3단계 - 체스] 배카라(박성우) 미션 제출합니다.
woowacourse/java-chess pull request #338
Opened 2022-03-28 08:44 UTC by seong-wooo

# 안녕하세요!  미르 

이번 미션 구현이 조금 어려웠어서 많은 지적사항이 있을 것으로 생각됩니다.!

저를 혼내주세요. 🙇🏼‍♂️

2022-03-30 13:39 UTC, ddu0422 requested changes
안녕하세요 배카라! 체스 미션 정말 고생하셨어요.
간단한 코멘트 남겨드렸습니다 😄
궁금한 점은 언제든지 코멘트 달아주시거나 DM 주세요 !
이번 미션도 화이팅이예요 🔥

2022-03-30 13:39 UTC, ddu0422 commented on src/main/java/chess/domain/location/Direction.java
> +    }
Direction에서 특정한 Piece를 알고있군요 ! 🤔 
그렇다면 각 Piece가 해당 책임을 가지지 않을까요?

2022-03-30 13:39 UTC, ddu0422 commented on src/main/java/chess/domain/command/Command.java
> +    public static final int TARGET_LOCATION_INDEX = 2;
접근제한자 범위를 더 줄여볼 수 있지 않을까요?_?

2022-03-30 13:39 UTC, ddu0422 commented on src/main/java/chess/domain/location/Location.java
> +    }
해당 메서드만 인스턴스 변수 위에 위치한 특별한 이유가 있을까요?

2022-03-30 13:39 UTC, ddu0422 commented on src/main/java/chess/domain/location/Rank.java
> +                .filter(rank -> rank.rank == toInteger(value))
인스턴스 변수 네이밍이 rank라서 rank.rank인데 더 좋은 변수명은 없을까요? 🤔

2022-03-30 13:39 UTC, ddu0422 commented on src/main/java/chess/domain/piece/EmptyPiece.java
> +public class EmptyPiece extends Piece{
전체 파일 공백 컨벤션 확인해보면 어떨까요?

2022-03-30 13:39 UTC, ddu0422 commented on src/main/java/chess/domain/location/File.java
> +    ;
이 부분만 컨벤션이 다른 이유가 있을까요?

2022-03-30 13:39 UTC, ddu0422 commented on src/main/java/chess/domain/state/Running.java
> +        }
양 옆이나 나이트가 갈 수 있는 방향이라면 움직일 수 있는걸까요? 🤔 
상대 기물이라면 흰 팀인 경우 검은 팀인지 확인 / 검은 팀이라면 흰 팀인지 확인이 필요하지 않을까요?

2022-03-30 15:05 UTC, seong-wooo commented on README.md
> +- [x] 기물은 Pawn, Rook, kNight, Bishop, Queen, King 이 있다.
일부러 ,, 이렇게 해봤습니다.  king과 knight 둘 다 k 로 시작되어서 대문자 N으로 표기해보았습니다.. !

2022-03-30 15:21 UTC, seong-wooo commented on README.md
> +- [x] 이동할 때 경로에 기물이 있으면 이동하지 못한다.
모든 기물이 상대 기물을 잡을 수 있으므로 체스 게임 룰에 작성하였습니다. !

2022-03-30 15:32 UTC, seong-wooo commented on src/main/java/chess/domain/Board.java
> +        }
람다로 다시 구현해보았습니다 !!

2022-03-30 16:26 UTC, seong-wooo commented on src/main/java/chess/domain/location/Direction.java
> +    }
조건들을 각 Piece에서 확인하도록 구현하였습니다. !

2022-03-30 16:30 UTC, seong-wooo commented on src/main/java/chess/domain/location/Location.java
> +    }
메서드가 사용되는 순서로 작성하다보니 인스턴스 변수 위에 위치했던 것 같습니다. 수정해보았습니다.!

2022-03-30 16:32 UTC, seong-wooo commented on src/main/java/chess/domain/location/Rank.java
> +                .filter(rank -> rank.rank == toInteger(value))
value로 선언해보았습니다. !

2022-03-30 16:35 UTC, seong-wooo commented on src/main/java/chess/domain/piece/EmptyPiece.java
> +public class EmptyPiece extends Piece{
Piece 뒤에 한 칸 띄웠습니다. !

2022-03-30 16:36 UTC, seong-wooo commented on src/main/java/chess/domain/location/File.java
> +    ;
코드를 작성하면서 복사 붙여넣기를 하다가 이렇게 된 것 같습니다. ! 마지막 ,를 지우고 ;를 작성하였습니다. !

2022-03-30 16:53 UTC, seong-wooo commented on src/main/java/chess/domain/state/Running.java
> +        }
각 클래스에서 상대팀인지 확인하는 로직을 구현했습니다.
제가 코드를 수정하다가 실수로 안고친 것 같습니다 ~

2022-03-31 13:37 UTC, ddu0422 approved these changes
안녕하세요 배카라! 1, 2, 3단계 미션 정말 고생하셨어요!
구조적인 부분은 괜찮고 전체적으로 공백 컨벤션만 확인해주세요!
이만 머지해도 될 것 같아서 머지하겠습니다!
다음 미션도 화이팅이예요 🔥

2022-03-31 13:37 UTC, ddu0422 commented on src/main/java/chess/domain/state/Running.java
> +    }
indent가 2네요!

2022-03-31 13:37 UTC, ddu0422 commented on src/main/java/chess/dao/MemberDao.java
> +public class MemberDao {
현재 미션과 관련이 없지만 다음 미션을 준비하는 내용이라면 다음 PR에 올려도 괜찮을 것 같아요 :)

2022-03-31 13:38 UTC, merged