[1, 2, 3단계 - 체스] 필즈(조성우) 미션 제출합니다.
woowacourse/java-chess pull request #343
Opened 2022-03-28 08:55 UTC by progress0407

닉 반가워요~!! 어쩌다 보니 우테코 스타가 리뷰어가 되었네요...ㅎㅎ
(전 필즈에요~!! ㅋㅋ)

- 개발바닥 (신입 개발자 이력서 편), 
- 우테코 youtube (닉&러너덕 점심봇, Spring vs SpringBoot 편)

재미있게 감상했습니다 !! ㅎㅎ
특히 점심봇 만들 때 초반 스토리가 너무 웃겼네요.. 하하

---

흠흠 

블랙잭 기본적인 기능 구현이 늦어서 현재 PR을 날리게 되었는데...

리펙터링을 온전히 하지 못한 부분들이 있지만.. 

시간 여건상 이만 PR을 올리도록 하겠습니다 .. 

(ㅎㅎ.. 잘부탁드립니다~!!)

2022-03-28 15:56 UTC, wbluke requested changes
안녕하세요 필즈~! 체스 리뷰를 맡은 닉입니다 🙌 
여러가지 고민하면서 잘 구현해 주셨네요 ㅎㅎ
몇 가지 리팩토링을 위한 포인트 남겼으니 참고해서 진행해 주세요 🙂

2022-03-28 15:56 UTC, wbluke commented on src/main/java/chess/domain/board/utils/ProductionBoardFactory.java
> +        }
`indent(인덴트, 들여쓰기) depth를 2를 넘지 않도록 구현한다. 1까지만 허용한다.`
프로그래밍 요구사항을 지켜주세요!
전체적으로 체크해 주세요 :)

2022-03-28 15:56 UTC, wbluke commented on src/main/java/chess/domain/board/utils/ProductionBoardFactory.java
> +package chess.domain.board.utils;
보통 유틸이라 함은 도메인 로직과 관련이 없는, 애플리케이션 전체적으로 공통적인 가공 로직이나 변환 등이 필요할 때 사용하는 용어입니다.
(ex. `yyyy-MM-dd` 형태의 문자열을 LocalDate로 변경하는 LocalDateUtils)

2022-03-29 07:08 UTC, progress0407 commented on PAIRCONVENTION.md
> +- 언제든지 코드를 이해하고 싶을 때는 "타임"을 외친다. "타임"을 누군가 외치면 코드 작성을 멈추고 둘다 코드를 이해한 후 다시 시작한다.
☺

2022-03-29 07:09 UTC, progress0407 commented on src/main/java/chess/domain/board/utils/ProductionBoardFactory.java
> +        }
인덴트 확인완료! 알겠습니다 :)

2022-03-29 07:11 UTC, progress0407 commented on src/main/java/chess/domain/board/Position.java
> +    }
맞아요! 현재는 계속 생성하고 있어요!
Position을 자체적으로 싱글턴으로 구조 변경해볼게요

2022-03-29 07:13 UTC, progress0407 commented on src/main/java/chess/controller/ChessController.java
> +        if (beginCommand == END) {
`isEnd` 등으로 말씀이죠?? ㅎ 넵!

2022-03-29 07:17 UTC, progress0407 commented on src/main/java/chess/controller/ChessController.java
> +public class ChessController {
맞습니다~! 이부분이 고민이 많이 되었는데요..
이를 해결하기 위해 입력받는 부분마다 `try-catch` 등을 사용할지 아니면 리플렉션으로 한번 접근을 해볼지 고민 중이에요!

2022-03-29 07:18 UTC, progress0407 commented on src/main/java/chess/domain/board/Board.java
> +            long count = reverseValues().stream()
반대로 정렬될 필요가 없는데 놓친 부분이네요! 확인했습니다 :)

2022-03-29 07:28 UTC, progress0407 commented on src/main/java/chess/domain/piece/Pawn.java
> +    }
헉 그런 방법도 있었군요 !!  참고로 하되, 아직은 폰 입장에서 움직임을 잘 분류를 해보는 방향으로 접근해보겠습니다 !

2022-03-29 07:33 UTC, progress0407 commented on src/main/java/chess/domain/piece/Knight.java
> +            source.rankDistance(target) == 1 && source.fileDistance(target) == 2;
`단위 방향`.. 학생때 배운 단위 벡터 개념이 떠오르네요 ㅎㅎ
흥미로운 도전이 될 것 같아요! 해볼게요

2022-03-29 07:34 UTC, progress0407 commented on src/main/java/chess/constant/MoveType.java
> +    FRIENDLY, ENEMY, EMPTY
작은 설명을 달아준다는 느낌이군요..ㅎㅎ 알겠습니다 !!

2022-03-29 10:07 UTC, progress0407 commented on src/main/java/chess/domain/board/Position.java
> +    }
정정합니다 !!.. `Position`은 현재 총 `64`개의 위치를 나타내어야 하기 때문에 `싱글턴`이 될 수 없네요 ㅠ
  - 정확히는 `file`과 `rank` 가 모두 하나씩 다른 `Position` 객체가 필요!
  - 
따라서 `Position`이 아닌 `Positions`에게 객처 생성의 책임을 위임해주는 방향으로 가야할 것 같아요 !

2022-03-30 02:14 UTC, progress0407 commented on src/main/java/chess/domain/board/Board.java
> +    public boolean move(Position source, Position target) {
맞습니다 ! 현재는 상태를 관리하는 `GameFlow` 로 클래스를 추출했어요!

2022-04-01 08:31 UTC, progress0407 commented on src/main/java/chess/controller/ChessController.java
> +        while (turnDecider.isRunning()) {
처음 봤을 때는 이해가 안 되었는데 현재는 이해가 되었어요.. ~! 적용했습니다 :)

2022-04-01 10:20 UTC, progress0407 commented
닉~! 리뷰 고마워요 ㅠㅠ

제가 다른 크루에 비해 체스 1차 리뷰 요청을 많이 늦게 드렸네요 ㅠㅠ

이번에 바뀌게 된 것들은 아래와 같아요

### 테스트 픽스쳐 생성

`StringBoardFactory` 는 String 정보를 기반으로 체스보드를 만들 수 있어요

예를들어 

```java
List.of(
  "Q.......",
  ".q......",
  "........",
  "........",
  "........",
  "........",
  "........",
  "........"
);
```
위와 같은 문자열은 `검은색 퀸`과 `흰색 퀸` 을 생성해줍니다 :)

만들게 된 이유는 King의 체크 메이트 같은 상황을 만들어내기 위해서는 

수만은 기물들이 움직여야만 했기 때문입니다 ..

### 예외가 한 번이라도 게임 종료 방지

사실 이 부분에 시도하고 싶었던 개념이 있는데 결국 만족할 정도로 해내지는 못했어요 ㅠ

결국 아래와 같은 코드로 종료를 방지했습니다

```java
try {
  실행할_메서드();
} catch ... {
  예외_메세지_출력();
  실행할_메서드();
}
```
### Position을 내부적으로 `캐싱`

Position과 같은 경우 64개의 위치(가로8 * 세로8)만을 알고 있으면 나머지 객체의 생성을 불필요 했습니다

따라서 `Positions` 라는 일급컬렉션을 내부에 만들어 놓고 사용하는 방식으로 `캐싱`하였어요

### 이동에 대한 검증 로직을 `단위 방향` 개념으로 변경

기물들이 이동할 때 각각 나름의 규칙이 있는데,

예를들어 `비숍`의 경우 `대각선` 방향으로만 이동이 가능합니다..

이때 정확한 `단위 벡터`의 개념은 아니지만 

가로 방향 +1, 세로 방향 +1 의 기울기 개념을 단위화 시켜서 적용하였습니다

이 개념은 `MovingDirection` 클래스에 녹여놓았어요!

### 그외 한 것ㄷ르

- 2중 for문 제거

- `enum == 값` 등의 형태 로직 제거
  - 메시지 보내기

- util


## 아쉬운것, 못한 것

---

### 들여쓰기 2단계 제거

들여쓰기가 2단계를 끝내 제거를 하지 못했어요.. 개인적으로 이부분이 아쉬워요 ㅠ

억지로 제거하려다 보니까 가독성이 훼손되는 경우도 있었네요..

### 입력에 대한 예외 방지 - 보일러 플레이트 제거

이때 스프링의 `AOP` 개념을 연상하면서 중복되는 코드를 제거하고자 하는 소망이 있었어요

```java
try {
  실행할_메서드();
} catch ... {
  예외_메세지_출력();
  실행할_메서드();
}
```

`try-catch` 문과 `예외 출력 메세지`, `자신을 재호출` 과 같이 완전히 동일한 로직을 실행하는 이 부분을 최대한 제거해내고 싶었는데 그러지 못했네요...

처음에는 리플렉션과 


### 각기 다른 기물들의 완벽한 행동 추상화

폰의 움직임은 상당히 변칙적입니다.. 나이트 같은 경우는 기물들을 넘나들을 수 있어요

이때 각 기물들의 움직임을 `폰.움직인다()` 등으로 추상화하고 싶었는데 

이때 움직이는 좌표와 해당 좌표에 무엇이 있는 지 등의 정보가 필요한데

이 모든 정보가 체스보드 도메인에 있었습니다.. 

따라서 끝내 각 기물들의 움직임의 완벽한 추상화가 이루어지지 못했던 것 같아요..

2022-04-01 11:22 UTC, wbluke approved these changes
오 남겨주신 글과 고민해주신 내용들 잘 보았습니다 👍 
참고할만한 코멘트 조금 남겼고요, 다음 단계 진행해 주세요 🙂

2022-04-01 11:22 UTC, wbluke commented on src/test/java/chess/domain/board/factory/StringChessBoardFactoryTest.java
> +public class StringChessBoardFactoryTest {
테스트를 위한 클래스를 테스트해야하는군요 ㅠㅠ 고생하셨어요

요런 테스트를 위한 구현체를 만들 때 주의해야 하는 점은,
앞으로의 모든 관련 테스트가 해당 클래스에 굉장히 의존적이게 된다는 것이에요.
다시 말하면 여러 개의 테스트가 이 객체에 의존성이 생기고, 테스트를 유지보수하느라 추가적인 리소스가 들 수 있는 환경이 되었다는 것을 의미해요.
그래서 열심히 만들어주신 것과 별개로... 테스트 케이스를 만들 때 지양하는 것이 좋습니다.
(물론 단순한 구현체라면 사용할 수도 있겠죠 ㅎㅎ)
그렇다고 수정하실 필요는 없어요!

그리고 저는 만들어주신 것처럼 String 까지는 아니어도, 프로덕션 쪽 팩토리에서 어떤 `List<Row>` 형태를 받아서 Board를 생성해주는 기능이 있어도 좋다고 봐요.
다음 단계에서 접하실테지만, 저장된 게임을 불러와서 중간부터 실행해야 하는 경우라면? ㅎㅎ
참고해 주세요 :)

2022-04-01 11:22 UTC, wbluke commented on src/main/java/chess/controller/ChessController.java
> +public class ChessController {
> try-catch 문과 예외 출력 메세지, 자신을 재호출 과 같이 완전히 동일한 로직을 실행하는 이 부분을 최대한 제거해내고 싶었는데 그러지 못했네요...
처음에는 리플렉션 과 프록시 패턴만을 잘 이용하면 해낼 수 있을 줄 알았어요...
하지만 하다가 보니까 코드를 동적으로 생성해주는 방식이 필요하단 것을 알고
그것이 어노테이션 프로세서란 것을 이내 깨달았어요..
잠깐 긴급하게 강의를 사서 들어보았는데 이게 당장에 적용할 수 있는 기술이 아니라 판단하여 우선은 제쳐두기로 했습니다 하핫...

네네 저도 뭔가 하드한 적용을 바란 것은 아니었어요 ㅎㅎ
콘솔 게임이라면 콘솔에 맞는 구현과 사용자 경험을 제공해주어야 하지 않을까? 하는 관점이었고요.
다음 단계의 웹 환경이라면 또 아예 다른 구현이 되어야 할거에요. (도메인은 그대로 유지하면서)
고민하시느라 고생 많으셨어요 :)

2022-04-01 11:22 UTC, wbluke commented on src/main/java/chess/domain/board/position/MoveDirection.java
> +public enum MoveDirection {
도메인 개념을 잘 도출하셨네요 👍

2022-04-01 11:23 UTC, merged

2022-04-04 07:14 UTC, progress0407 commented on src/main/java/chess/domain/board/position/MoveDirection.java
> +public enum MoveDirection {
ㅎㅎ 넵~!

2022-04-04 07:19 UTC, progress0407 commented on src/test/java/chess/domain/board/factory/StringChessBoardFactoryTest.java
> +public class StringChessBoardFactoryTest {
아.. 이 부분은 미쳐 놓치고 있었던 것인데

이러한 테스트를 위한 `Factory` 클래스를 만든 순간 유지보수 대상이 될 수 있다는 것이군요...

요구사항에서 벗어난 부분이지만 

만일 테스트를 한다면 가상으로 테스트 맵을 제공받으면 좋겠단 생각에 만들었었거든요...

알고 있을 게요...~!!... 

프로덕션에서 사용할 구현체라면 괜찮지만.. 이런 것은 또다른 유지보수 대상이 될 수 있다

2022-04-04 07:21 UTC, progress0407 commented on src/main/java/chess/domain/board/position/MoveDirection.java
> +        }
확인했습니다 ~!! :)