[1, 2, 3단계 - 체스] 이브(이유정) 미션 제출합니다.
woowacourse/java-chess pull request #344
Opened 2022-03-28 08:55 UTC by 2yujeong

안녕하세요 카일! 이브입니다.
체스 미션 제출합니다🙂

2022-03-30 06:31 UTC, KIMSIYOUNG requested changes
안녕하세요 이브! 리뷰가 늦어져 죄송합니다.
어려운 미션인데도 잘 구현해주셨네요🙂
몇가지 코멘트 드렸는데 확인 부탁드립니다.

2022-03-31 08:21 UTC, 2yujeong commented on src/main/java/chess/Command.java
> +public enum Command {
수정했습니다!

2022-03-31 08:26 UTC, 2yujeong commented on src/main/java/chess/domain/Score.java
> +        getTeamScore(board, team);
Score의 totalScore 필드가 쓰이고 제대로 쓰이고 있지를 않았네요😅

> 이렇게 설계하는 경우 단순히 ScoreCalculator.calculate(Map<Row,Rank> board, Team team)이렇게 구현하는 것과 어떤 차이가 있나요?

말씀하신 구현 방식과 다른 이점이 없는 거 같아서 각 팀의 점수를 포장하는 값 객체로서의 역할을 추가해주었습니다.

2022-03-31 08:27 UTC, 2yujeong commented on src/main/java/chess/domain/Position.java
> +    private static void validateLength(String position) {
저도 카일과 같은 의견이에요! 입력 로직으로 분리했습니다

2022-03-31 08:28 UTC, 2yujeong commented on src/main/java/chess/domain/piece/Blank.java
> +        return null;
별다른 이유 없이 신경쓰지 못했던 부분이에요😟 수정했습니다!

2022-03-31 08:29 UTC, 2yujeong commented on src/test/java/chess/domain/BoardTest.java
> +        assertThat(board.getTeamScore(Team.WHITE)).isEqualTo(38);
수정했습니다!

2022-03-31 08:35 UTC, 2yujeong commented on src/main/java/chess/domain/Score.java
> +            totalScore -= pawnCount * 0.5;
기능 요구사항에 폰의 기본점수는 1점이라고 정의되어 있어서 Pawn 클래스의 점수 값으로는 1만 정의해줬어요!
폰이 어떠한 상황에선 0.5점으로 계산되는 로직을 Pawn이 아닌 Score에 구현한 이유는, 만약 해당 로직을 폰에서 구현하면
1. 폰의 책임이 너무 무거워지는 거 같다.
2. 폰의 로직과 Score의 로직에 겹치는 부분이 발생한다.
이 두 가지 이유 때문이었어요!
이 로직을 폰이 갖도록 했을 때 더 좋은 이점이 있을까요?? 카일의 의견이 궁금합니다!

2022-03-31 08:42 UTC, 2yujeong commented on src/main/java/chess/domain/Board.java
> +    public boolean isKingDead(Piece piece) {
movePiece에서는 말이 움직이는 로직만 실행되도록 구현하고자 했어요!
또한 이미 매개변수로 받은 dst가 이동 가능한 dst인지 검증하는 로직까지 movePiece에서 가지고 있기 때문에, 왕이 죽은 경우를 판별하는 로직까지 포함시키면 movePiece가 너무 무거워지는 느낌이라 이런 식으로 따로 분리해줬습니다.
목적지의 Piece를 반환 역할을 포함시키는 것보다 왕이 죽었는지 여부를 판별하는 로직을 포함시키는 게 더 나을까요?? 카일의 의견도 궁금합니다!

2022-03-31 08:48 UTC, 2yujeong commented on src/main/java/chess/domain/Board.java
> +    private final Map<Row, Rank> board;
Board를 하나의 가로줄 단위로 나눠서 관리해주고자 Rank를 선언했어요!
Board의 초기화 로직과 점수 계산 로직에 있어서 세부적인 책임을 조금 더 나누고자 중간에 논리적인 단위(Rank)를 하나 더 추가하게 됐는데, Board 초기화 클래스를 분리하고 리뷰를 보면서 생각해보니 꼭 필요한가 싶은 생각도 드네요🤔 더 고민해보고 리팩토링 진행하겠습니다!

2022-04-02 05:18 UTC, KIMSIYOUNG approved these changes
안녕하세요 이브! 
리팩토링 잘 해주셨네요🙂
조금 더 고민해보면 좋을 것들 남겨두었어요.
1단계는 여기서 머지하고 2단계에서 같이 반영해주시면 좋을 것 같습니다.
궁금하신 내용은 언제나 편하게 말씀해주세요!

2022-04-02 05:18 UTC, KIMSIYOUNG commented on src/main/java/chess/domain/Board.java
> +    private final Map<Row, Rank> board;
넵넵! 좋습니당. 도메인에 대해서 이브가 이해한대로 이것들을 풀어가는 과정이 멋있는 것 같아요.

요 부분에서 저 개인적으로는 하나의 가로줄 단위가 폰을 계산하는 경우가 아닌 추가적인 로직들이 계속 생겨난다면 현재의 구조가 더 좋을 것 같고, 그렇지 않다면 저는 Col과 Row를 묶어서 관리했을 것 같네요🙂

2022-04-02 05:18 UTC, KIMSIYOUNG commented on src/main/java/chess/domain/Board.java
> +    public boolean isKingDead(Piece piece) {
이브의 생각도 좋은 생각인 것 같습니다. `이동에 대한 역할`만을 담당하도록 구성해주신 것 같아요. 아래는 제 의견인데 참고해주세요🙂 

저는 왕이 죽었다는 것도 해당 메소드에 넣을 것 같아요. `이동후에 말이 죽으면 게임이 즉시 종료가 되어야한다` 라는 것이 현재는 구현되어있지 않는 것 같아요.  현재와 같이 다음 행위(start, end, move, status)를 입력받고 이를 판단하는건 왕이 죽었는데 게임이 계속되나? 라는 의문을 가지게 만들 수 있는 것 같아요.

그렇다면 도메인 규칙을 지키기 위해선 아래의 두가지 방법이 있는 것 같아요. 그 중 후자를 저는 선호하는 이유는 해당 로직이 이동과 한 번에 이루어져야하는 로직이라고 생각이 되기 때문이에요. 이 부분을 컨트롤러로 위임하는 경우 `이동과 함께 발생할 수 있는 도메인 로직`이 한 곳에 있지 않고 퍼지는 것을 의미하기에 저는 후자를 선호합니다. 추가로 이렇게 되면 게임의 흐름에 대해 현재는 `Controller`에서 모두 제어하지만 `Board`도 흐름을 반환할 필요가 생기는데, 이 부분을 구현할 때는 조금 더 고민해볼 여지들이 있는 것 같아요.

- 입력을 받기전 매번 왕이 죽었는지 물어보고, 죽지 않았다면 입력받기
- 움직인 이후 왕이 죽은 경우 게임을 종료시키기

요렇게 리팩토링 할 생각이 드셨다면, 하면서 궁금하신 부분은 여쭤봐주세요! 이브의 생각대로 이동하는 행위만 담당해야한다면 리팩토링하지 않아도 됩니다!

2022-04-02 05:18 UTC, merged