[1, 2, 3단계 - 체스] 돌범(조재성) 미션 제출합니다.
woowacourse/java-chess pull request #347
Opened 2022-03-28 09:01 UTC by is2js

페어와 naive한 구현 후, 하루 동안 controller로직 및 컨벤션 적용하려고 노력하였습니다.

하이 제이!  아직 많이 모자라지만, 페어들과 함께 4일동안 열심히 구현해본 것 같습니다! 
배웠던 상태패턴을 적용해보았고, 분기가 명확한 command 실행시에 전략패턴을 적용해보았습니다

### 명령어에 따라 `chessgame` 작동 + `outputview`의 출력 분기가 정해져있다면, 커맨드와 함께 outputview객체를 인터페이스 추상메서드 구현하는 곳 파라미터로 같이 넘겨도 되느냐?
- 이 부분에 대해서 제이의 생각이 궁금합니다. **전략패턴 사용하려는데, view로직이 섞여있으면 같이 넘겨서 로직을 실행시켜도 되느냐?**

### 페어들(3인)과 함께 전략패턴을 적용해보았는데 제대로 사용하고 있는지 궁금합니다! 

### king관련 미구현 로직이 존재함(현재 요구사항은 아님)
- **현재 경로를 beforePosition <-> afterPosition 사이의 모든 좌표에 대한 Position을 검사하도록 `PathChceker`를 사용하도록 설계하였는데 이 부분에 대해서 제이는 어떻게 생각하시는지 궁금합니다!**  다른 크루들은 정해진 경로(벡터)를 enum으로 미리 선언해놓고 확인하는 로직을 구현한 분들이 많은 것 같았습니다!

- [ ] 킹
    - [x] 어느 방향이든 한 칸 이동한다.
    - [ ] 스스로 체크 위치로 (잡힐 수 있는 위치) 이동할 수 없다.

2022-03-29 14:15 UTC, is2js commented
가장 마지막에 제출했기 때문에, 아직 코드리뷰가 이루어지지 않을 것 같아서 리팩토링 한 부분 추가 push하였습니다.
시간이 촉박하여 Board 부분에 대해 리팩토링을 거의 하지 못했던 것이 확인되었습니다!
기본적으로 추가된 사항과 의문점을 남겨봅니다!

1. Null객체패턴을 학습한 뒤, NullPiece추가 
- isNullPiece() return false의 중복제거를 위해 추상클래스 `NotNullPiece`를 하나 더 추가했는데 이게 적절한지 제이 생각이 궁금합니다.
- 최종 계획은 `Piece 인터페이스` 아래애 = `NotNullPiece(추상클래스) - Bishop, King...` + `NullPiece`의 구조로 잡고 싶었으나 추상레이어 계층을 맞춰주려면 NullPiece라는 추상클래스를 추가해줘야할 것 같았습니다... 그래서 급한대로 아래 구조로 만들었습니다.
    ![image-20220329230745176](https://raw.githubusercontent.com/is2js/screenshots/main/image-20220329230745176.png)

- 최종적인 구상도
    
![image](https://user-images.githubusercontent.com/35893047/160631810-015dfa3d-a872-4aba-beed-96a2ed25826d.png)


2. Position 객체는 1회만 생성되므로 정적팩토리메서드내에서 캐싱

3. view에서 is해당Piece()냐에 따라 물어보면서, 분기에 따라 view용 알파벳 return
 - 분기를 제거하기 위해 enum 속에 view용 문자열(`b`, `.`, `B`) 등을 매핑하였습니다. **제 생각에는 view출력도 도메인 지식중 하나인 것 같아서 PieceName이라는 enum속에 매핑하였는데, 다음미션(web)할 때도 그렇고, 페어간에 회의를 했을 때도, Bishop객체가 "b"를 들고 있는 것은 view를 위한 변경많은 로직이라 있으면 안된다.고 결론을 냈습니다. enum에 넣어서 찾아써도 되는 것인지 해당 Piece구현체들과 출력 로직을 한번 봐주셨으면 좋겠습니다.**

4. Board의 로직이 복잡하여 
    - Board 생성자 내부 초기화 부분 -> FactoryClass로 추출
    - Board내 status 점수 계산 로직 -> StatusCalculator(Board board)로 추출
    - 계산함수에 Predicate를 사용하여 black/white 계산시 재활용

2022-03-30 06:48 UTC, is2js commented
Turn 관리를 map을 들고 있는 `Board`에게 시켰다가 -> `State`가 관리하도록 변경하였습니다!

2022-03-31 02:22 UTC, kang-hyungu requested changes
돌범 몇 가지 코멘트 남겼어요.
수정해보시고 리뷰 재요청주세요.
리뷰 요청 주신 다음에 슬랙 스레드로 @구구 도 남겨주세요

2022-03-31 02:22 UTC, kang-hyungu commented on src/main/java/chess/controller/ChessGameCommand.java
> +    private final String value;
변수명에 value 금지입니다.
변수명은 의미 있는 이름을 주세요.
명령어 문자열을 저장하고 있는데 변수명이 value면 다른 개발자 입장에서는 무슨 값을 저장하는지 코드를 파악해야됩니다.

2022-03-31 02:22 UTC, kang-hyungu commented on src/main/java/chess/controller/ChessGameCommand.java
> +    private final Function<ChessGame, Command> function;
마찬가지로 변수명에 function 금지입니다.

2022-03-31 02:22 UTC, kang-hyungu commented on src/main/java/chess/controller/ChessGameCommand.java
> +package chess.controller;
왜 컨트롤러 패키지로 묶이나요?

2022-03-31 02:22 UTC, kang-hyungu commented on src/main/java/chess/controller/ChessGameController.java
> +public class ChessGameController {
클래스명에서 컨트롤러를 제거합시다.
역할이 컨트롤러가 아닌데 컨트롤러를 붙이면 다른 개발자가 코드를 잘못 파악할 수 있습니다.

2022-03-31 02:22 UTC, kang-hyungu commented on src/main/java/chess/controller/ChessGameCommand.java
> +    public static Command of(final String inputCommand, ChessGame chessGame) {
메서드명을 점검해보시기 바랍니다.
of라는 이름이 메서드의 리턴값을 제대로 표현하고 있나요?
관례적으로 of를 붙이는 경우는 어떤 경우인가요?

2022-03-31 02:22 UTC, kang-hyungu commented on src/main/java/chess/controller/ChessGameCommand.java
> +        checkNullOrEmpty(inputCommand);
Pattern.matches 메서드에서 어차피 null, empty 문자열이 걸릴거 같은데 따로 검사할 필요가 있을까요

2022-03-31 02:22 UTC, kang-hyungu commented on src/main/java/chess/controller/ChessGameController.java
> +            final String rawInputCommand = inputView.inputCommand();
```suggestion
            final String command = inputView.inputCommand();
```
변수명을 디테일하게 작성할 필요는 없습니다.
클라이언트 입장에서 raw input 이라는 의미를 알아야할 필요가 있을까요?

2022-03-31 02:22 UTC, kang-hyungu commented on src/main/java/chess/controller/command/Command.java
> +    void execute(String rawInputCommand, final OutputView outputView);
```suggestion
    void execute(String command, final OutputView outputView);
```

2022-03-31 02:22 UTC, kang-hyungu commented on src/main/java/chess/controller/command/Command.java
> +public interface Command {
콘솔 명령어를 인터페이스로 둔 이유가 무엇인가요?
커맨드 클래스 한 곳에서 관리해도 충분하지 않나요?
인터페이스로 만들고 클래스를 분리해서 얻을 수 있는 장점은 무엇일까요?

2022-03-31 02:22 UTC, kang-hyungu commented on src/main/java/chess/controller/command/End.java
> +            this.chessGame.off();
```suggestion
            chessGame.off();
```
요즘엔 IDE가 잘 발달되어서 필요한 경우가 아니면 this는 잘 안 붙이는 추세입니다.

2022-03-31 02:22 UTC, kang-hyungu commented on src/main/java/chess/controller/command/Move.java
> +        chessGame.move(movePositions.get(0), movePositions.get(1));
get(0), get(1)이 뭘까요?
Positions라는 일급컬렉션을 만들었으니 적절한 메서드를 추가해서 어떤 값을 추출하는지 메서드명으로 표현해보시기 바랍니다.

2022-03-31 02:22 UTC, kang-hyungu commented on src/main/java/chess/controller/command/Command.java
> +package chess.controller.command;
커맨드는 뷰와 관련된 처리를 하는 것 같은데 왜 컨트롤러인가요?

2022-03-31 07:39 UTC, is2js commented on src/main/java/chess/controller/ChessGameCommand.java
> +    private final String value;
피드백 강의 시간에서 value를 활용한 이후로는 자바어린이로서 애용했었습니다.

해당 부분을 고쳐서 앞으로 버릇을 들여야겠습니다! 
유지보수, 팀원 생각을 해야겠습니다. 감사합니다. 구구!

2022-03-31 07:40 UTC, is2js commented on src/main/java/chess/controller/ChessGameCommand.java
> +    private final Function<ChessGame, Command> function;
함수형 인터페이스는 삭제되었습니다. 
value와 함께 명심하겠습니다.

감사합니다 구구!

2022-03-31 07:41 UTC, is2js commented on src/main/java/chess/controller/ChessGameCommand.java
> +package chess.controller;
내부에 도메인 의존이 있기 때문에 controller에 있으면 안되었습니다.

단순히 controller에 있던 로직을 옮긴 것이라 그대로 두었는데, 애초에 잘못 설계되었던 것 같습니다.

2022-03-31 07:42 UTC, is2js commented on src/main/java/chess/controller/ChessGameController.java
> +public class ChessGameController {
단순히 m과 v의 통로로서 역할만 하는 것이 controller라 생각해도 되겠습니까?

제 기존 코드의 경우, ChessGame의 역할과 ChessGameController가 모두 view와 관련된 로직을 가지는 애매모호한 로직이었던 것 같습니다!

감사합니다 구구~!

2022-03-31 07:43 UTC, is2js commented on src/main/java/chess/controller/ChessGameCommand.java
> +    public static Command of(final String inputCommand, ChessGame chessGame) {
구구의 의도는  Enum return하는 정적팩토리메서드(생성자)가 아니라 다른 인터페이스 구현체를 return하므로 메서드명도 바꿔야한다고 말씀하시는 것 같습니다.

findByInputCommand로 바꿨다가 -> 인터페이스 부분 삭제되고 && 인자도 1개로 줄면서 && 생성자 역할을 하므로 -> `from`으로 변경되었습니다.

2022-03-31 07:44 UTC, is2js commented on src/main/java/chess/controller/ChessGameCommand.java
> +        checkNullOrEmpty(inputCommand);
이 부분은 생각치도 못했습니다. 

일단 input을 받아 생성하는 Enum의 경우, 검증이 Enum내부에서  stream의 orElseThrow에서 일어난다는 것 + 만약 filter에 equals가 아니라 정규식을 활용하면, 한꺼번에 검증될 수도 있다는 점을 새롭게 배웠습니다!

감사합니다 구구!

2022-03-31 07:48 UTC, is2js commented on src/main/java/chess/controller/ChessGameController.java
> +            final String rawInputCommand = inputView.inputCommand();
`메서드내 파라미터`에서 뿐만 아니라 `controller 등의 클라이언트 스코프?`내에서도 구체적으로&지엽적으로 변수명을 잡으면 안되겠네요!

- 혹시 메인로직이 돌아가는 내부에서는 원하는 변수명을 지엽적으로 잡아도 될지도 궁금합니다! 제 생각은 yes.. 캡슐화되어서 클라이언트가 모르니까?? 팀원들도 알아먹을 수 있을 정도는 괜찮다?입니다.

2022-03-31 07:50 UTC, is2js commented on src/main/java/chess/controller/command/Command.java
> +public interface Command {
명령어 실행에 있어서 분기가 확실하고 이 분기를 제거하여 따로 관리해두면 유지보수성에서 이점을 얻을 것이라 생각하였습니다.

추상클래스의 상속구조도 잡을 수 있지만, 일단 인터페이스! 가 아니라 자식들이 의존성이 커지면 유지보수가 오히려 어려워질 수 있으므로 인터페이스! 로, 저번 블랙잭 미션 때 생각을 정리했던 것 같습니다.

하지만, view와의 결합이 이루어지는 인터페이스므로 일단 삭제하였습니다.ㅠ  자세한 것은 밑에 정리해두겠습니다!

2022-03-31 07:52 UTC, is2js commented on src/main/java/chess/controller/command/End.java
> +            this.chessGame.off();
생성자는 생략안되어서 그냥 두었습니다.! 
아직 자바에 익숙하지 않아서 this를 쓰는 것이 덜 헷갈리는데 이 부분은 고민해보겠습니다. 추세를 따라가는 개발자가 되고 싶습니다.ㅎㅎㅎ!
일단 버릇을 들이면 좋을 것 같아 `this.을 모두 삭제`하였습니다!

감사합니다 구구

2022-03-31 07:55 UTC, is2js commented on src/main/java/chess/controller/command/Command.java
> +package chess.controller.command;
혹시 이 클래스(인터페이스)가 존재하고 있었다면  
- inputview + outputView객체 -> 내부 chessGame속 state관련 로직 시행

이 것은 어디다 두어야했을까요?? 고민해보아도 .. 답이 잘 안나옵니다.!
```java
public void execute(final String rawInputCommand, final OutputView outputView) {
        outputView.printFinishMessage();
        if (chessGame.isNotRunning()) {
```

2022-03-31 08:43 UTC, is2js commented on src/main/java/chess/controller/command/Move.java
> +        chessGame.move(movePositions.get(0), movePositions.get(1));
ㅠ_ㅜ 이부분은 몇번 고민해보았는데, 크게 중요하지 않은 로직이 너무 복잡해지는 것 같아서 중간에 롤백 시켰었습니다.

시간이 꽤 소요되었습니다!  일급컬렉션으로 추가하되, get(0) = .before() , get(1) = .after() 필요한 부분에 메세지를 보내는 방식으로 변경했습니다.

2022-03-31 08:53 UTC, is2js commented
구구 피드백에 대한 생각을 남깁니다.

1. Controller 역할을 못하고 있다. -> ChessGame 관련된 로직이 Controller내부에 있다 + **ChessGame도 내부에서 View를 뗄 수 없다**
    - 라고 생각해서, Controller를 제거하고 ChessGame과 통합했습니다.
    - 웹에서는 어떻게 풀어갈지 고민해봐야할 것 같습니다.ㅠ

2. View가 메인 로직(ChessGame)과 분리될 수 없는 상황인 것 같아서 **view객체들을 static으로 선언하고 chessGame내부에서 편하게 사용하도록**

3. Command 인터페이스는 분기를 제거하려고 도입했지만, domain+view가 붙어있었다 -> 다음 미션을 위해 최대한 분리시켜야하기 때문에, 제거하고 분기를 ChessGame내부로 다시 돌렸습니다.


4. Positions의 get(0) get(1)으로 꺼내쓰던 것을 메세지 보내는 방식으로 변경하였습니다.
    - 가장 큰 공사였습니다ㅎㅎ

**결국에는 domain <-> view 분리되지 않는(?) 로직(매 로직마다 서로 다른 출력 요구됨) , controller가 있어도 제 역할을 못할 것이다. 그럴거면 차라리 controller를 삭제해라**를 의도하시는 것이 맞는지 궁금합니다.
    - 다음 웹 미션을 미리 보진 않았지만, 염두에 두었으면 controller를 도입하기 위해서 함수형인터페이스 등을 사용해서 미리 분리해놔야할지 고민입니다!

2022-03-31 14:36 UTC, is2js commented
추가적으로 **Command에 인터페이스 사용(전략패턴)**을 다시 사용하기로 했습니다. 상태패턴을 잘못 사용하는 것인가ㅠ_ㅜ 현재실력으로 view와 도메인을 찢을 수가 없어서 **2개를 못찢는 상황이라면, controller가 필요없다고 결론**내린 뒤, 그냥 view+chessGame 같이 움직이는 분기를 처리하여 유지보수가 편하도록 작성하였습니다.

혼자 오랫동안 쳐다봤는데 아직 답이 안나오는 것 같습니다! 내일은 블랙잭 상태패턴을 2번째 복습해볼 것 같습니다!

2022-04-01 02:35 UTC, merged