[체스(웹/DB)] 정(정진우) 미션 제출합니다.
woowacourse/java-chess pull request #355
Opened 2022-04-04 10:00 UTC by bugoverdose

요구사항대로 현재 도메인을 최대한 건들지 않는 선에서 웹+DB를 추가했습니다.

docker 경로에 있는 docker-compose.yml과 docker/init/init.sql 활용하시면 DB 관련 개발환경 공유가 가능할 것 같습니다.

현재 웹 쪽 예외처리와 DB 문제 상황에 대한 커스텀 예외 클래스를 만들려다가 투머치인 것 같아 일단 멈췄습니다.

2022-04-07 02:40 UTC, kang-hyungu requested changes
정 몇 가지 코멘트 남겼어요.
수정해보시고 리뷰 재요청 주신 다음에 슬랙 스레드에 @구구 남겨주세요.

2022-04-07 02:40 UTC, kang-hyungu commented on docker/db/mysql/init/event_sourcing_init.sql
> +    state ENUM('RUNNING', 'OVER') NOT NULL,
db에서 enum 타입을 쓰게 되면 수정 사항이 생길 때마다 소스코드 뿐만 아니라 db까지 영향을 받겠네요.
타입으로 enum을 써야 할 필요가 있을까요?

2022-04-07 02:40 UTC, kang-hyungu commented on src/main/java/chess/WebApplication.java
> +        router.initHomeRouteHandler();
새로운 route가 추가될 때마다 WebRouter 뿐만 아니라 WebApplication도 수정해야되겠군요.
WebRouter 생성자에서 초기화하도록 바꿔보세요.

2022-04-07 02:40 UTC, kang-hyungu commented on src/main/java/chess/controller/WebController.java
> +public class WebController {
WebRouter와 WebController를 왜 분리했나요?
컨트롤러에서 http 요청에 대한 처리를 맡아야 하지 않을까요?

2022-04-07 02:40 UTC, kang-hyungu commented on src/main/java/chess/dao/CommandBuilder.java
> +public class CommandBuilder {
데이터베이스 관련 처리를 하는 클래스 같은데 왜 커맨드 빌더인가요?
어떤 의미로 지은 이름인가요?

2022-04-07 02:40 UTC, kang-hyungu commented on src/main/java/chess/dao/EventDao.java
> +        new CommandBuilder(sql).setInt(gameId)
saveMove 메서드를 실행할 때마다 CommandBuilder 객체를 새로 생성하게 되는데 미리 객체를 만들어둬도 되지 않을까요?

2022-04-07 02:40 UTC, kang-hyungu commented on src/main/java/chess/dao/CommandBuilder.java
> +public class CommandBuilder {
QueryBuilder도 있는데 하나로 합칠 방법은 없나요?

2022-04-07 02:40 UTC, kang-hyungu commented on src/main/java/chess/controller/WebController.java
> +    private final GameDao gameDao = new GameDao(GAME_TABLE_NAME);
컨트롤러가 왜 테이블 이름을 알아야 하나요?
관심사를 한 곳으로 모으지 못했으니 디비 관련 작업이 생길때마다 컨트롤러도 영향 받겠네요.
dao에게 디비 관련 책임을 맡기세요.

2022-04-07 02:40 UTC, kang-hyungu commented on src/main/java/chess/dao/ResultReader.java
> +}
```suggestion
}

```
깃헙에서 왜 파일 마지막에 newlline을 넣으라고 경고를 띄울까요?

2022-04-07 02:40 UTC, kang-hyungu commented on src/main/java/chess/domain/board/piece/Piece.java
> +        static final int TOTAL_PIECES_COUNT = 12;
전체 피스 갯수는 캐시에서 관리하는게 맞나요?

2022-04-07 02:40 UTC, kang-hyungu commented on src/main/java/chess/domain/board/piece/Piece.java
> +            return cache.computeIfAbsent(key, (__) -> initCacheOf(color, type));
__ 변수명은 적절해보이지 않네요.
사용하지 않는다는 의미의 이름을 붙여보세요

2022-04-07 02:40 UTC, kang-hyungu commented on src/main/java/chess/domain/board/piece/Piece.java
> +            return color + " " + type;
캐시키를 문자열로 관리하는건가요?
키를 변경해야될 상황이 생길 수도 있고 이런 히스토리는 코드를 파악해야 알 수 있어서 좋은 방법이 아닙니다. 구전으로 전파되면 유지보수하기 어려워져요.
더 좋은 방법 없을지 고민해보아요

2022-04-07 02:40 UTC, kang-hyungu commented on src/main/java/chess/domain/board/piece/PieceType.java
> +    private interface RouteChecker {
새로운 functional interface를 추가할 필요가 없어보이네요.
BiFunction 써도 되지 않나요?

2022-04-07 03:09 UTC, bugoverdose commented on docker/db/mysql/init/event_sourcing_init.sql
> +    state ENUM('RUNNING', 'OVER') NOT NULL,
개인적으로 enum은 절대악은 아니고 장점과 단점을 모두 지닌다고 생각했어요. 그래서 일단 enum을 쓰고 별로면 varchar로 바꿀 계획이었는데요. 이 경우 enum을 쓰면 RUNNING이나 OVER 이외의 값을 저장할 수 없다는 점의 효용이 단점보다 더 크다고 느꼈어요.

웹과 게임 플레이 로직에서는 GameState가 WHITE_TURN, BLACK_TURN, OVER라는 3가지로 구분되는데, DB의 경우 state가 RUNNING vs OVER만 신경쓰도록 만들어놓았어요. 어차피 매번 이벤트들 싹 다 읽어서 재실행할건데 굳이 누구 턴인지를 매번 저장하고 수정하는 것은 불필요하다고 느껴서요. 문제는 GameState가 두 종류가 존재해버리니, GameState.WHITE_TURN 같은 값을 DB에 저장할 수 없도록 하는 방어 수단을 어딘가에는 추가하는게 좋지 않나 생각해요. 

다만, 이번에 `ENUM('WHITE_TURN', 'BLACK_TURN', 'OVER')`에서 `ENUM('RUNNING', 'OVER')`로 수정하면서 번거롭다고 느끼기는 했어요. varchar였으면 WHITE_TURN과 BLACK_TURN을 RUNNING으로 일괄 수정했으면 되는데, enum 때문에 그냥 테이블 자체를 DROP 했어서요.

개인적으로 Piece나 Color 같은 값들은 잘못된 값을 실수할 여지가 굉장히 적으니 enum을 쓰는 효용이 적으니, 차라리 varchar를 쓰는게 훨씬 효용이 있을 것 같기는한데, game state는 (1) 애초에 필요한 데이터인지, (2) enum으로 하는게 맞는지 등등 좀 고민했었어요.

2022-04-07 03:15 UTC, bugoverdose commented on src/main/java/chess/controller/WebController.java
> +public class WebController {
사실 저도 그 점이 불편했어요. WebRouter를 WebController로 만들고 WebController를 ChessService로 만들고 싶은데, spark 사용법이 너무 낯설었어요. Spark.get과 Spark.post를 어디서 어떻게 실행해놓아야 할지를 더 고민해봐야 할 것 같아요.

2022-04-07 03:16 UTC, bugoverdose commented on src/main/java/chess/WebApplication.java
> +        router.initHomeRouteHandler();
넵 지저분하기는 하네요

2022-04-07 03:26 UTC, bugoverdose commented on src/main/java/chess/dao/CommandBuilder.java
> +public class CommandBuilder {
sql문의 `?`에 들어올 데이터들을 한땀 한땀 setter로 추가하고 최종적으로 `execute()`을 실행하는 과정이 약간 빌더 패턴에서 최종적으로 build를 실행하는 모습 같지 않나?해서 지은 이름이었어요. 빌더 패턴을 실제로 구현해본적이 없어서 자신은 없네요. 

개인적으로 Query(R)와 Command(CUD)를 구분하는 습관이 있어서 일단 분리하고 본거였어요. 근데 최종적으로 실행하는 부분만 executeQuery, executeCommand처럼 만들면 하나로 합칠 수 있을 것 같아요

2022-04-07 03:29 UTC, bugoverdose commented on src/main/java/chess/dao/EventDao.java
> +        new CommandBuilder(sql).setInt(gameId)
혹시 connection을 close하지 않고 계속 열어두는 방식을 말하는거 맞나요? 

try-with-resources 문법이랑 AutoClosable을 구현해보고 싶어가지고 지금처럼 매번 새로 connection 만들고 한거였는데, 실행될 때 굉장히 느리다는 생각은 들었어요.

2022-04-07 03:32 UTC, bugoverdose commented on src/main/java/chess/controller/WebController.java
> +    private final GameDao gameDao = new GameDao(GAME_TABLE_NAME);
네 여기에 db 정보가 있는건 틀린것 같아요 

game_test와 event_test 테이블에서 dao에 대한 테스트를 진행하려고 테이블 값을 받도록 구분한거였는데 위로 빼다보니까 컨트롤러에까지 오게 되었네요.

2022-04-07 03:34 UTC, bugoverdose commented on src/main/java/chess/domain/board/piece/PieceType.java
> +    private interface RouteChecker {
네 PieceType 내부에서만 사용되니까 효용이 없는 것 같네요.

2022-04-07 06:09 UTC, bugoverdose commented on src/main/java/chess/domain/board/piece/Piece.java
> +        static final int TOTAL_PIECES_COUNT = 12;
저 상수가 PieceCache 내에서만 사용되고, HashMap의 초기 사이즈를 지정하기 위한 값인데, 저게 없더라도 어차피 디폴트 사이즈(16)을 사용하니 그다지 효용이 없어서 (1) 굳이 있어야 하나, (2) 있으면 어떤 이름으로 어디에 있어야 좋을지 고민이었어요.

이름을 `CACHE_CAPACITY`처럼 한다면 PieceCache 내에 있는게 맞고, 용도를 Cache만이 아니라 Piece 관련해서 사용하고자 한다면 Piece에 가는게 맞지 않나 싶어요.

2022-04-07 06:26 UTC, bugoverdose commented on src/main/java/chess/domain/board/piece/Piece.java
> +            return color + " " + type;
이 경우 `Color`가 두 종류밖에 없으니 blackPieceCache와 whitePieceCache를 구분하고 `PieceType`를 key로 쓸 수 있을 것 같아요. 그런데 Color의 종류가 더 많아지게 되거나 키를 구성하는 3번째 값이 등장한다면 이 방식만으로는 한계가 있지 않을까 싶어요.

2022-04-07 06:41 UTC, bugoverdose commented on src/main/java/chess/dao/ResultReader.java
> +}
"마지막 줄이 비어있어야 파일이 끝났다고 인식하는 프로그램들이 존재하기 때문"이 맞나요

2022-04-07 06:45 UTC, bugoverdose commented on docker/db/mysql/init/event_sourcing_init.sql
> +    state ENUM('RUNNING', 'OVER') NOT NULL,
근데 일단 현재 상화에서 event.type은 Enum 대신 varchar가 맞는 것 같아요.

2022-04-07 15:38 UTC, bugoverdose commented
코멘트 외적으로 이벤트소싱, 예외처리 관련된 로직을 추가했습니다.

2022-04-08 03:50 UTC, kang-hyungu requested changes
정 추가 코멘트 남겼어요
코드 다듬어 보시고 리뷰 재요청주세요.

2022-04-08 03:50 UTC, kang-hyungu commented on src/main/java/chess/WebApplication.java
> +    private final static WebConfig config = new WebConfig();
final static
static final

코드 일관성을 맞추세요.
코드 컨벤션을 확인해보세요.

2022-04-08 03:50 UTC, kang-hyungu commented on src/main/java/chess/WebApplication.java
> +        config.init();
WebCofig와 WebRouter를 왜 분리했죠?
config와 router는 연결고리가 없나요?
지금처럼 각자 init으로 초기화하면 두 객체의 연관관계를 파악하기 쉬울까요?

2022-04-08 03:50 UTC, kang-hyungu commented on src/main/java/chess/dao/GameDaoImpl.java
> +public class GameDaoImpl implements GameDao {
1. 네이밍에 약어 사용 금지입니다.
2. 테스트 때문에 인터페이스를 추가하는게 적절한 설계일까요? 테스트를 하기 위한 다른 방법은 없나요?

2022-04-08 03:50 UTC, kang-hyungu commented on src/main/java/chess/service/ChessService.java
> +    private final static ChessService instance = new ChessService(GameDaoImpl.ofProd(), EventDaoImpl.ofProd());
코드 일관성이 반복적으로 지켜지고 있지 않습니다.

2022-04-08 03:50 UTC, kang-hyungu commented on src/main/java/chess/ConsoleApplication.java
> +    private static final ConsoleController controller = new ConsoleController();
왜 콘솔 컨트롤러라고 정의하셨죠? 콘솔 체스 게임이라는 역할을 부여하면 되지 않나요?
컨트롤러인데 왜 콘솔 게임 진행과 관련된 startGame, playGame와 화면 출력을 위한 printGameOver 메서드가 있나요?

2022-04-08 03:50 UTC, kang-hyungu commented on src/main/java/chess/controller/HomeController.java
> +    private static final String JSON_CONTENT_TYPE = "application/json";
컨트롤러마다 JSON_CONTENT_TYPE를 선언하는건 중복 아닌가요?

2022-04-08 03:50 UTC, kang-hyungu commented on src/main/java/chess/domain/board/piece/Piece.java
> +        static Map<PieceType, Piece> whitePieceCache = new HashMap<>(CACHE_CAPACITY);
게임 규칙이 새로 추가되서 다른 색깔이 추가될 때마다 코드가 수정이 발생하겠군요.
Color와 PieceType을 키로 묶을 방법은 없는건가요?

2022-04-08 04:29 UTC, bugoverdose commented on src/main/java/chess/WebApplication.java
> +    private final static WebConfig config = new WebConfig();
넵. `static final`로 통일하겠습니다.

2022-04-08 09:05 UTC, bugoverdose commented on src/main/java/chess/WebApplication.java
> +        config.init();
음 config와 router의 로직 사이에 연결고리가 없다기보다는 이 애플리케이션 입장에서는 서로 별개의 layer?처럼 느껴져서 구분했던걸로 기억해요.

2022-04-08 09:19 UTC, bugoverdose commented on src/main/java/chess/domain/board/piece/Piece.java
> +        static Map<PieceType, Piece> whitePieceCache = new HashMap<>(CACHE_CAPACITY);
혹시 Map 내부에 Map을 넣으면 되려나요.

2022-04-08 09:31 UTC, bugoverdose commented on src/main/java/chess/service/ChessService.java
> +    private final static ChessService instance = new ChessService(GameDaoImpl.ofProd(), EventDaoImpl.ofProd());
IntelliJ에서 자동으로 고쳐주는 설정은 없나 찾아보겠습니다.

2022-04-08 09:51 UTC, bugoverdose commented on src/main/java/chess/dao/GameDaoImpl.java
> +public class GameDaoImpl implements GameDao {
1. `Impl`까지는 허용범위인줄 알았는데 이것도 지양하는게 좋을려나요.

2. 흠 `GameDaoStub`을 `GameDao`의 자식클래스로 만들고 모든 메서드를 Override하면 될려나요.

2022-04-08 11:29 UTC, bugoverdose commented on src/main/java/chess/ConsoleApplication.java
> +    private static final ConsoleController controller = new ConsoleController();
음 웹 애플리케이션에서 사용하는 컨트롤러들과 비교해보니 역할이나 로직의 성질?이 다르다고 느껴지기는 하네요.

2022-04-10 03:01 UTC, kang-hyungu commented on src/main/java/chess/WebApplication.java
> +        config.init();
http라는 동일한 관심사를 가지고 있으니 같은 계층에 포함됩니다.

2022-04-10 03:03 UTC, kang-hyungu commented on src/main/java/chess/domain/board/piece/Piece.java
> +        static Map<PieceType, Piece> whitePieceCache = new HashMap<>(CACHE_CAPACITY);
당연히 Map을 쓰는 건 아니겠죠.

2022-04-10 03:03 UTC, kang-hyungu approved these changes
정 피드백 반영하느라 수고하셨어요.
pr은 머지 처리할게요. 레벨2에서 만나요.

2022-04-10 03:03 UTC, merged

2022-04-10 05:02 UTC, bugoverdose commented on src/main/java/chess/domain/board/piece/Piece.java
> +        static Map<PieceType, Piece> whitePieceCache = new HashMap<>(CACHE_CAPACITY);
가능한 방법이 너무 많아서 오히려 어렵네요.

(1) Map 중첩 : 키의 개수가 증가하면 depth 증가, map의 총 개수는 꾸준히 증가
(2) 캐쉬키만을 위한 객체/클래스를 별도로 정의하여 사용 : 매우 verbose. 클래스에 equals/hashCode까지 구현 필요.
(3) 제네릭 없는 List에 값들 전부 담아서 캐쉬키로 사용 : 간결하게 구현 가능하지만 심리적 거부감/불안감.
(4) Color와 PieceType에서 인스턴스별로 고유한 문자열을 반환해주는 `toKey()` 메서드를 구현하여, `color.toKey() + pieceType.toKey()`를 캐쉬키로 사용 : PositionCache에서 사용한 방법. verbose하다고 느껴져서 PieceCache에서는 처음에 각 enum의 `toString` 사용.