[4, 5단계 - 체스] 오리(최진영) 미션 제출합니다.
woowacourse/java-chess pull request #361
Opened 2022-04-05 13:39 UTC by jinyoungchoi95

안녕하세요 루피 :)

어찌어찌하다보니 많이 늦게 제출하게된 것 같네요 😢
프론트보다는 자바코드에 조금 더 신경쓰고싶었는데 자바스크립트를 할 줄 모르다보니 시간이 많이 뺐겼던 것 같아요…
개발하면서 느꼈던 내용 comment 더해서 풀리퀘 드려요 😄
1. [**JdbcTemplate**](https://github.com/woowacourse/java-chess/pull/361/commits/c2d65028b772a963bf0762b4a51223fecfa24e77)
- 지난주 수업에서부터 이야기가 나왔던 `DAO`에서 반복되는 `try-catch문`을 잡고 싶어서 만들었어요.
- JdbcTemplate은 단순히 `Connection`만 주고 `PreparedStatement`를 생성받아 이를 단순히 실행해주는 역할만 하고, 기존 DAO에서 쿼리를 `PreparedStatement`에 담아 전달하는 방식으로 구현했어요.
- 제공된 FunctionalInterface를 활용해보려고했는데 SQLException 때문에 계속 `try-catch`를 열라는 컴파일 에러가 발생해서 `PreparedStatedmentCreator`와 `ResultSetMapper` 인터페이스를 만들어서 사용했습니다 :) 
- 조금 더 중복되는 부분을 제거할 수 있을 것 같은데 지금 단계에서는 계속 고민중이에요 🤔

2. **Dao test**
- 수업에서는 테스트 더블을 이야기해주셨는데 현재 코드는 수업듣기 전에 구현해두어서 해당 방법을 그대로 두었어요.
- 테스트 더블도 좋은 방법이라는 생각이 들었는데 실제 DB 쿼리가 나가는 행위자체를 테스트하고 싶었기 때문입니다.
- docker에 띄운 프로덕션에서 사용하는 DB가지고 테스트하기에는 운영 DB를 건든다라는 부담이 있고, 그렇다고 DB를 또 띄우기에는 굳이 그래야할까라는 생각이 들었어요.
- 그래서 H2database를 사용해서 테스트용에서만 사용할 수 있도록 connection을 연결해두고 테스트했습니다.
- 다만 테스트 진행 시에 서로 다른 테스트코드의 환경을 독립시키위해서 `@BeforeEach`를 통해 table을 지속적으로 setUp했습니다.

```java
@BeforeEach
void setUp() {
    H2Connection.setUpTable();
    pieceDao = new PieceDaoImpl(H2Connection.getConnection());
	...
}
```
- 아무리 테스트용 DB라지만 테스트할 때마다 테이블을 지우고 삭제하는 행위를 반복하는 것이 좋은 방법이라고는 할 수 없을 것같은데 루피의 생각은 어떠신가요?

감사합니다 🙇‍♂️

2022-04-06 08:33 UTC, TheDevLuffy requested changes
안녕하세요 오리~

지난 1, 2, 3단계에서 남겨드린 코멘트도 같이 반영해주셨더라구요.
4, 5단계도 고생 많으셨습니다. 이번 미션 전반적으로 잘 구현해주셨어요.

테스트에 대한 고민을 많이 하고 계신 것 같아요. 아래 글 참고해보시면 좋을 것 같아요.
* [테스트 더블](https://tecoble.techcourse.co.kr/post/2020-09-19-what-is-test-double/)
* [테스트를 바라보는 관점](https://github.com/msbaek/memo/blob/master/london_vs_chicago.md)

테스트할 때마다 테이블을 지우고 삭제하는 행위를 반복하지 않으려면 어떤 방법이 있을까요 ? ㅎㅎ

추가로 코멘트 몇 개 남겨두었으니 확인 부탁드려요 ! 🙇‍♂️

2022-04-06 08:33 UTC, TheDevLuffy commented on src/main/java/chess/dao/PieceDao.java
> +public interface PieceDao {
구현체가 하나 밖에 없는데 interface - impl 로 구현하신 이유가 무엇인가요 ?

2022-04-06 08:33 UTC, TheDevLuffy commented on src/main/java/chess/service/ChessGameService.java
> +public class ChessGameService {
여기서 사용한 `Service` 는 어떤 의미의 `Service` 인가요 ?

2022-04-06 08:33 UTC, TheDevLuffy commented on src/test/java/chess/util/DBConnectionTest.java
> +    void getConnection() throws SQLException {
전체 테스트를 한번에 실행하는 경우 테스트가 실패해요

2022-04-06 08:33 UTC, TheDevLuffy commented on src/main/java/chess/dao/PieceDao.java
> +    void updatePiece(Position position, Piece changedPiece);
반환형이 void 이면 테스트가 어렵지 않을까요 ?

2022-04-07 02:25 UTC, jinyoungchoi95 commented on src/main/java/chess/dao/PieceDao.java
> +public interface PieceDao {
습관적으로 interface를 만들어두고 사용했는데 지우는 걸 잊고있었네요...
현재는 Dao가 jdbc 구현체만 사용되고있기 때문에 굳이 다른 Dao 구현체를 만들지 않는 시점에서는 interface를 만드는 이유가 없는거같네요 :)

2022-04-07 02:34 UTC, jinyoungchoi95 commented on src/main/java/chess/service/ChessGameService.java
> +public class ChessGameService {
사실 지금까지 미션과 체스1단계까지는 service, controller와 같은 객체를 만들어서 사용하지는 않았었는데요.

현재는 웹과 연결로 인해서 웹과 통신하는 controller, db에 접근하는 dao 객체를 분리해두었어요.
따라서 각각의 객체는 웹과 통신하는 역할, db에 접근해서 데이터를 가져오는 역할만을 가지고 있어요.
이때 service는 요구사항에 해당하는 비즈니스 로직을 수행하기위한 중간다리의 역할로써 사용했어요. 웹 통신에서 받은 요구사항을 가지고 dao를 호출하고 domain의 로직을 실행시켜 결과를 반환하는 용도입니다.

2022-04-07 03:59 UTC, jinyoungchoi95 commented on src/main/java/chess/dao/PieceDao.java
> +    void updatePiece(Position position, Piece changedPiece);
조금 잘못 생각하고 있었던 것 같아요.
save, update, delete의 경우 어짜피 실행되는 결과가 중요하기 때문에 void로 두고 select를 다시해서 해당 값을 검사해야하지 않나라고 생각했는데 `executeUpdate()`에서 쿼리가 실행되어 변경된 값만큼을 int로 반환하는 걸 잊고있었네요 ㅜㅜ

다만 여기에서 궁금한건 테스트를 어디까지 검증하냐인데요.
결과에 따른 반환값을 통해서 테스트를 진행하는데, 실제로 값이 save된건지, update된건지까지 테스트해야하나라는 의문이 있어요.

예를 들어 `updatePiece()`로 위치를 update를 한다라고 하면 쿼리가 실행되어 변경되었다라면 아래와 같이 해도 된다라고 생각하는데요.
```java
int result = pieceDao.updatePiece(position, changePiece);

assertThat(result).isEqualTo(1);
```
근데 이렇게 되었을 때 update메소드가 실행되었다는 사실만 테스트를 하지, update가 어떻게 실행되었는지는 테스트를 못하게됩니다.

그래서 현재는 아래와 같이 select를 또 따로해서 진행을 했는데요.
```java
int result = pieceDao.updatePiece(position, changePiece);
Piece piece = pieceDao.findAllPieces().get(position);

assertAll(
        () -> assertThat(result).isEqualTo(1),
        () -> assertThat(piece.color()).isEqualTo(WHITE),
        () -> assertThat(piece.name()).isEqualTo("queen")
);
```

결국 아래와같이 테스트를 진행하면 이전에 void에서 겪었던 find를 또해야하는 테스트의 복잡성도 발생하고,
dao에 대해서 테스트를 할 때 쿼리가 진행되어 원하는만큼 execute되었냐가 중요하지 또 find하는 행위자체가 해당 메소드 테스트 범위를 벗어난다고 생각해요.

혹시 루피는 어떻게 생각하시는지 궁금합니다 :)

2022-04-07 04:05 UTC, jinyoungchoi95 commented on src/main/java/chess/dao/PieceDao.java
> +    void updatePiece(Position position, Piece changedPiece);
조금 잘못 생각하고 있었던 것 같아요.
save, update, delete의 경우 어짜피 실행되는 결과가 중요하기 때문에 void로 두고 select를 다시해서 해당 값을 검사해야하지 않나라고 생각했는데 executeUpdate()에서 쿼리가 실행되어 변경된 값만큼을 int로 반환하는 걸 잊고있었네요 ㅜㅜ

다만 여기에서 궁금한건 테스트를 어디까지 검증하냐인데요.
결과에 따른 반환값을 통해서 테스트를 진행하는데, 실제로 값이 save된건지, update된건지까지 테스트해야하나라는 의문이 있어요.

예를 들어 update쿼리가 나가는걸 테스트하더라도 실제로 update가 되었는지 select를 추가로 하는 구문이 존재하는데요.
```java
int result = pieceDao.updatePiece(position, changePiece);
Piece piece = pieceDao.findAllPieces().get(position);

assertAll(
        () -> assertThat(result).isEqualTo(1),
        () -> assertThat(piece.color()).isEqualTo(WHITE),
        () -> assertThat(piece.name()).isEqualTo("queen")
);
```

위와 같이 테스트를 진행하면 이전에 void에서 겪었던 find를 또해야하는 테스트의 복잡성도 발생하고,
dao에 대해서 테스트를 할 때 쿼리가 진행되어 원하는만큼 execute되었냐가 중요하지 또 find하는 행위자체가 해당 메소드 테스트 범위를 벗어난다고 생각해요.

그래서 아래와 같이 실제로 쿼리가 잘 동작했고 몇개를 변경했는지를 확인만하면 되지 않을까라는 생각을 해봤어요.
```java
int result = pieceDao.updatePiece(position, changePiece);

assertThat(result).isEqualTo(1);
```

근데 이렇게 되었을 때 update메소드가 실행되었다는 사실만 테스트를 하지, update가 어떻게 실행되었는지는 테스트를 못하게됩니다.

결국 어디까지 Dao의 해당 메소드에 대해서 테스트를 진행할거냐가 고민인데요. 혹시 루피는 어떻게 생각하시는지 궁금합니다 :)

2022-04-07 04:17 UTC, jinyoungchoi95 commented
안녕하세요 루피 :)

피드백 반영하면서 테이블을 계속 지우는 구조도 변경해보았습니다.

테이블을 계속 새로 생성하는것 자체가 문제라고 생각했고, 이를 어떻게하면 개선할 수 있는지 두가지 방법을 떠올렸고 무엇이 좋은지를 비교해서 사용했어요.
1. Dao내에 `allDelete()`를 두어 테스트 실행 후 매번 삭제해준다.
2. `connection.setAutoCommit(false)`로 두고 테스트 실행 후 매번 롤백해준다.

제일 처음 생각한게 첫번째 방법이에요.
정말 단순하게 입력이 들어간 데이터들에 대해서 그냥 삭제하는 쿼리를 날리면 사실 모든게 해결된다라고 생각했어요.
다만 문제는 프로덕션코드에서 사용하지도 않고, 말그대로 테스트코드만을 위한 코드를 만들었기 때문에 엄청나게 불필요한 메소드들이 추가되는 문제가 발생했어요.
그래서 DB에 대한 생각을 하다 두번째 방법을 생각했습니다.

Jdbc connection내에서는 auto commit이 true로 기본 설정되어있어 별다른 옵션을 건들지 않으면 excute할 때 모든 쿼리들이 개별 트랜잭션으로 돌아가요. 그리고 실행될 때 바로 commit을 진행하죠.
이때 `setAutoCommit(false)`를 두면 commit을 직접 날리지 않으면 commit이 직접 호출 될 때 commit이 진행돼요.
이 부분을 테스트에서 활용하면 좋겠다라고 생각해서 적용했는데요.
Auto commit을 끄고, 제가 원하는 데이터를 넣고 테스트하고 select하면 원하는 테스트들은 다 동작해요. 그리고 테스트가 끝날 때 `connection.rollback();`을 호출하여 테스트에서 진행되는 트랜잭션을 끊고 다음 테스트부터는 새로운 트랜잭션을 이용하도록 하는거죠.
즉, 테스트마다 원하는 테스트들에 대해서 db를 활용하며, commit을 실행하지않음으로써 다른 테스트에는 영향이 가지 않도록 진행합니다.

조금더 좋은 방법이 있는지는 좀 더 오래 고민해봐야할 것 같아요 …🤔
루피는 어떻게 생각하시는지, 또다른 방법이 있는지 궁금합니다 :)

감사합니다 🙇‍♂️

2022-04-07 12:58 UTC, TheDevLuffy commented on src/main/java/chess/dao/PieceDao.java
> +            }
해당 로직을 실행하는 도중에 어떠한 이유로 `chessBoard.keySet()` 의 원소 전부에 대하여 실행하지 못하고 중단되는 경우 연산의 원자성을 보장할 수 있을까요 ?

2022-04-07 12:58 UTC, TheDevLuffy commented on src/main/java/chess/service/ChessGameService.java
> +public class ChessGameService {
해당하는 `Service` 의 의미는 마틴 파울러의 엔터프라이즈 아키텍처 패턴(POEAA)의 9장 도메인 논리 패턴의 서비스 계층(p141) 으로 볼 수 있을 것 같아요.

개발을 하면서 `Service` 라고 붙여진 이름이 여러 가지 등장하니 한번 확인하고 넘어가면 좋을 것 같아요 ㅎㅎ

2022-04-07 13:01 UTC, TheDevLuffy commented on src/main/java/chess/dao/PieceDao.java
> +    void updatePiece(Position position, Piece changedPiece);
테스트를 잘 구현해주신 것 같아요.

이런 경우 메서드를 실행 했을 때, 내부에서 어떤 동작을 했는지 확인해볼 수 있을 것 같아요.

메서드가 원자성을 보장한다면 해당 메서드 내의 쿼리가 잘 동작했는지 안했는지만 확인해봐도 충분하지 않을까요 ㅎㅎ

저는 테스트를 작성하고 실행되는 쿼리를 한번 더 확인하기도 합니다.

2022-04-07 13:17 UTC, TheDevLuffy approved these changes
안녕하세요 오리~

피드백 반영하신 내용 잘 확인하였습니다.
전반적으로 잘 구현해주셨고, 미션에서 고민해야 할 부분도 충분히 해주신 것 같아요.

코멘트 몇 개 남겨두었으니 확인 부탁드려요.

이만 머지하도록 하겠습니다.
레벨 1 고생 많으셨습니다 🙇‍♂️

2022-04-07 13:17 UTC, merged