[4, 5단계 - 체스] 연로그(권시연) 미션 제출합니다.
woowacourse/java-chess pull request #366
Opened 2022-04-05 17:32 UTC by yeon-06

안녕하세요 스티치! 좋은 밤입니다!
여러가지 고민하면서 구현을 했는데 이에 대해 함께 이야기 나눠주시면 너무 감사할 것 같아요😄

## 추가 기능 구현

- 웹 UI 연동
  - Spark 이용 (Javascript는 프론트 부분의 복잡도만 높아진다 생각해서 사용하지 않았습니다..😂)
- DB 연동
- 방 번호를 통해 게임방에 입장 가능

## 고민해본 문제들

### 상태 패턴의 제거

- 상태와 뷰 분리하기 위해 불필요한 메서드 계속 늘어남
- 파라미터로 BiConsumer 등을 넘길 수는 있지만 이를 통해 View 메서드를 호출하는 경우 이것 역시 View와 완전히 분리된 것이 아니라고 생각
- 현재 특정 조건이 나타날 때까지 계속 request를 받기 위해 생성하였음
  Web을 적용하게 된다면 한번의 request를 보내면 한번의 response를 무조건 받아야한다고 생각함

위와 같은 사유로 득보다 실이 많다고 판단하여 상태 패턴을 제거하게 되었습니다 T.T
다만 ChessGame은 View만 분리하고 코드를 유지했습니다.
기존의 Status, Move 등의 상태가 갖던 로직을 ChessGame 내부에 status(), move() 같은 메서드로 존재하게 만들었습니다.

### Controller vs Service vs DAO

- Controller: url과 실제 돌아가는 로직을 **매핑**시켜주는 역할
- Service: 로직이 존재하는 위치. (DAO 실행 포함)
- DAO: DB와 연동해 데이터를 받아옴

제 주관적 기준으로는 각자의 역할이 위와 같다는 생각을 하고 로직을 구현했습니다
혹시 잘못 이해하고 있는 부분이 있다면 정정 부탁드려요 🙂

### DAO에 대해

지금은 한 쿼리문을 실행하는 것에 대해서만 처리가 되어있는데요
move의 경우에는 move 실행이 성공한다는 가정 하에 아래 쿼리가 실행됩니다.

1. to에 있는 piece 삭제하기
2. from에 있는 piece를 찾아 위치를 to로 바꾸기
3. 현재 board의 turn 변경하기

위의 세 쿼리문에 대한 것을 한 DAO에 넣어야 할까요?
전 DAO의 원자성, 재사용성을 위해 분리해야한다고 생각했는데 셋 중 하나라도 쿼리문이 실패하면 모두 다 롤백되어야 하는건 아닌가... 
롤백이 되어야한다면 어떤 식으로 할 수 있을지 궁금합니다.

### DB 환경을 테스트 하기
웹 UI를 적용하는건 이미 1~3단계의 테스트코드를 조합하는 정도라 별도의 테스트코드를 작성해가며 진행할 필요가 없다고 생각했습니다.
다만 DB를 연동하는 부분에 대해서는 테스트 코드가 필요하다고 느꼈는데요
(원하는 데이터가 잘 select 되었는지, update 쿼리문을 통해 데이터 변경이 잘 일어났는지 등)
요 부분에 대해 테스트 코드를 짜기가 너무 어려워 막무가내로 짰습니다 😂

현재는 DB에 원하는 데이터가 잘 존재한다는 가정 하에 짜다보니 항상 true가 나올거란 기대를 하기 힘든데요
select를 해서 전후를 비교하자니 테스트 코드를 위해 select 관련 메서드를 만드는게 과연 좋은 방법인지 의문이 드네요ㅠㅠ

2022-04-06 16:32 UTC, lxxjn0 requested changes
연로그, 미션 코드 잘 봤습니다!!

웹 미션이 처음인데도 dto 사용, dao 인터페이스 활용 등 다양하게 좋은 구조를 만들어 주신 것 같아요!! 질문한 부분에 대해서는 중간 중간 코멘트에서 함께 언급해두었습니다!! 상태 패턴의 경우에는 제거된 현재의 코드가 더 직관적이고 이해가 잘 가서 더 좋았습니다!! 👍🏼 

그리고 DB 테스트에 대해서는 코멘트에도 남겨두긴 했지만 외부 라이브러리를 사용하는 것과 동일하기 때문에 DB 동작에 대한 테스트를 굳이 작성하실 필요는 없습니다!! DB에서는 정상적인 결과를 반환한다고 가정하고 그에 따른 다른 테스트들을 보완하는 것이 더 좋아보여요!! :)

2022-04-06 16:32 UTC, lxxjn0 commented on src/main/java/chess/domain/board/Board.java
> +    private final Map<Position, Piece> value;
> 이건 개인적인 의견입니다

해당 변수명을 board에서 value로 바꾼 이유가 있을까요?? 저는 개인적으로 board일 때 하위에 코드들이 더 가독성이 좋다고 느껴져서요 :)

2022-04-06 16:32 UTC, lxxjn0 commented on src/main/java/chess/domain/board/generator/DatabaseLoadBoardGenerator.java
> +    }
해당 로직을 보면 pieceDto가 관리하는 값들을 가져와서 Piece를 생성하고 있어요!! 값을 가진 객체에게 생성을 위임하면 어떨까요?? 객체가 감싸고 있는 정보를 가져오지 않고도 객체지향적으로 문제를 해결할 수 있을 것 같아요!!

2022-04-06 16:32 UTC, lxxjn0 commented on src/main/java/chess/service/ChessService.java
> +public class ChessService {
ChessService의 코드와 ChessGame의 코드를 함께 두고 보면 어떤가요?? 제가 보기엔 Game 클래스의 존재 의미가 없어보여요!! 단순히 Board의 행위를 전달만 하는 역할 그 이상 그 이하도 아니라고 생각합니다. 두 클래스의 코드를 보고 한번 개선해보면 어떨까요?

2022-04-06 16:32 UTC, lxxjn0 commented on src/test/java/chess/dao/BoardDaoImplTest.java
> +class BoardDaoImplTest {
해당 테스트는 DB 의존적인 테스트인 것 같아요!! 그리고 DB는 외부 라이브러리와 마찬가지이기 때문에 굳이 테스트하지 않아도 될 것 같아요!!

2022-04-07 02:12 UTC, yeon-06 commented on src/main/java/chess/controller/ChessController.java
> +        AtomicInteger boardId = new AtomicInteger();
원래 int로 선언했었는데 int로 하니까 IntelliJ가 에러를 띄우면서 AtomicInteger를 추천해주더라고요💦
동시성을 관리하려는 의도는 아니었으나 인텔리제이가 컴파일 에러를 띄워서 추천대로 바꿨습니다!

2022-04-07 02:19 UTC, yeon-06 commented on src/main/java/chess/domain/board/Board.java
> +    private final Map<Position, Piece> value;
Service에서 해당 값을 가져올 일이 있었는데요
chessBoard.getBoard().getBoard()라는게 이상한 것 같더라고요ㅠ.ㅠ
chessBoard.getBoard().getValue()가 더 낫지 않나해서 수정했습니다!

2022-04-08 13:08 UTC, yeon-06 commented on src/main/java/chess/domain/board/generator/DatabaseLoadBoardGenerator.java
> +    }
요기서 하나 궁금한게 있는데요
전 dto가 계층 간의 데이터 교환을 위해 만들어졌다고 생각을 했어요
로직이 들어간 순간 도메인의 영역인건 아닌가? 라는 생각이 들었는데 스티치는 dto의 역할이 어디까지라고 생각하시나요??

2022-04-08 13:16 UTC, yeon-06 commented on src/main/java/chess/dto/PieceDto.java
> +    }
값들을 받는 생성자가 원래 있었고 나중에 Piece랑 Position을 받는 생성자가 생겨났는데요
외부에서 Piece 값을 꺼내서 dto에 넣는 것보다는 dto에서 꺼내 쓰는게 더 깔끔해보일 것 같아서 선택했습니다!

다양한 방식으로 생성할 수 있게 다형성을 제공한다고 생각을 했습니다
이 경우 정적 팩토리 메서드를 사용해본다면 그 장점이 뭔지 여쭤볼 수 있을까요?
여태까지는 뭔가 캐싱(?)을 위해..? 같은 인스턴스를 반환할 때나 사용했는데 dto에서 적용하는 경우 어떤 점이 좋은지 궁금해요!

2022-04-08 14:30 UTC, yeon-06 commented on src/main/java/chess/service/ChessService.java
> +public class ChessService {
현재 콘솔과 웹 두 가지 버전이 존재하기 때문에 존재하는 클래스입니다!
콘솔은 DB와 연동되지 않고 늘 새 게임을 가져오고 있기 때문에 콘솔/웹 공통 로직들이 ChessGame에 존재한다고 이해해주시면 될 것 같아요~!

2022-04-08 14:52 UTC, yeon-06 commented on src/main/java/chess/service/ChessService.java
> +    public Map<String, Object> move(ChessGame chessGame, PieceDao pieceDao, BoardDao boardDao, int boardId,
적용하다가 한가지 고민이 생겨 일단 커밋에서 제외했습니다ㅜ.ㅠ

현재 BoardDao와 PieceDao가 나뉘어져있는데요
한 가지 기능에서 양쪽의 Dao를 다 호출해야 하고, 이 역시 함께 commit / rollback되도록 하고 싶다면 어떤 식으로 조합하는게 좋을까요?

1. DAO에서 SQLException을 throw하고 Service에서 처리해주기
2. BoardDao와 PieceDao를 합치기

위 두 가지로 생각해보았는데 둘 다 썩 마음에 들지는 않네요 ㅠㅠ

2022-04-09 14:33 UTC, lxxjn0 commented on src/main/java/chess/domain/board/generator/DatabaseLoadBoardGenerator.java
> +    }
로직의 범위를 다양하게 볼 수 있을 것 같아요!! 도메인은 (책들에서 말하길) 해결하기 위한 문제의 영역이라고 해요!! 만약 체스라면 체스 게임 로직을 말하는 것이겠죠? 이러한 비즈니스 로직을 관리하는 영역을 도메인 영역이라고 생각합니다!
그런 의미에서 객체의 생성이나 매핑 등 단순한 코드 로직적인 부분에 대해서는 도메인 로직이 아니라고 생각해서 DTO가 충분히 가지고 있을 수 있을 것 같아요!!!

2022-04-09 15:46 UTC, lxxjn0 commented on src/main/java/chess/dto/PieceDto.java
> +    }
정적 팩토리 메서드를 캐싱된 값에 대한 반환으로만 사용되는 것 이외에도 다양한 목적으로 사용하고 있어요!! (https://bit.ly/3NSxQUV)

저 같은 경우는 생성자를 사용할 때는 말 그대로 해당 객체가 가지는 필드들을 통해서 생성할 때만 생성자를 사용하고 그 외로 데이터 가공을 통해 생성하는 경우에는 정적 팩토리 메서드를 사용하곤 합니다!!
이건 순전히 저의 코딩 스타일이기 때문에 참고 정도만 해주셔도 될 것 같아요!!

그런데 해당 코드에서 정적 팩토리 메서드를 추천드린 이유는 this 생성자를 사용하기 위해서 코드가 작성되다 보니 너무 가독성이 떨어져 보여서 그랬습니다!! this 생성자를 사용할 경우 생성자에 넘겨줄 인자를 로컬 변수로 뽑지 못하기 때문에 이러한 코드가 된 것으로 보여요!! 순전히 가독성 개선을 위한 포인트로 정적 팩토리 메서드를 제안드리기도 했고 추가로 저의 개발 스타일에 대한 추천이기도 해서 말씀드려 보았습니다 :)

```suggestion
    public PieceDto(Piece piece, Position position) {
        String team = piece.getTeam().name().toLowerCase();
        String type = piece.getInfo().getType();
        String position = position.getName();

        return new PieceDto(team, type, position);
    }
```

2022-04-09 15:49 UTC, lxxjn0 commented on src/main/java/chess/controller/ChessController.java
> +        AtomicInteger boardId = new AtomicInteger();
AtomicInteger가 어떤 상황에서 주로 사용하는지 한번 살펴보면 좋을 것 같아요!! 현재 상황에서는 굳이 atomicInteger까지 사용할 필요는 없을 것 같아서 int로 처리해도 충분할 것 같습니다! :)

2022-04-09 15:57 UTC, lxxjn0 requested changes
연로그, 코드 리뷰 반영해주신 부분 잘 봤습니다!!

추가로 더 코멘트를 남겨보려고 했는데 제가 요청드린 부분에 대해서 충분히 코드가 잘 반영된 것 같아서 추가로 코멘트를 드릴 부분이 없네요.. ㅠㅠ
그래서 마지막 코멘트로 service 테스트를 요청드렸습니다!! service에서 dao에 대한 의존성이 기존에 비해서 개선된 코드가 어떤 장점을 가지고 있는지 한번 경험해보기 좋을 것 같아요!! :)

2022-04-09 15:57 UTC, lxxjn0 commented on src/main/java/chess/service/ChessService.java
> +    }
dao를 외부에서 받아옴으로써 훨씬 코드를 유연하게 사용할 수 있을 것 같아요!!! 이번에 service에 대한 테스트 코드를 한번 작성해보면 어떨까요?? 그러면 의존성을 외부로부터 주입받은 것에 대한 장점을 좀 더 확실하게 느낄 수 있을 것 같아요!! 👍🏼

2022-04-09 16:05 UTC, lxxjn0 commented on src/main/java/chess/service/ChessService.java
> +    public Map<String, Object> move(ChessGame chessGame, PieceDao pieceDao, BoardDao boardDao, int boardId,
DAO를 나눴을 때 해당 부분에 대해서 따로 고민해보진 못했는데 저도 한번 방법을 고민해볼게요!! 어떤 좋은 방법이 없을까 생각해보겠습니다 😄

2022-04-11 03:01 UTC, yeon-06 commented on src/main/java/chess/controller/ChessController.java
> +        AtomicInteger boardId = new AtomicInteger();
Variable used in lambda expression should be final or effectively final 
라는 컴파일 오류가 떴네요! 람다에서 값을 변경하려고 발생한 문제였어요😂

지금처럼 람다로 구성되어있는게 편리하고 가독성이 좋다고 생각해서 그냥 두었습니다!
(int를 사용하기 위해 이 구조를 깰 필요는 없다고 생각했어요!)

그래도 적용 시도는 해봤는데 궁금증이 하나 더 발생했습니다 ^-T
Spark의 get, post의 두번째 인자는 Route라는 함수형 인터페이스를 받고 있는데요
함수형 인터페이스를 구현하기 위해서는 익명클래스나 람다 등을 이용하면 될 것 같아요
근데 해당 방법을 통해 final이 아닌 값을 int 값을 변경하는 방법이 있을까요!?

2022-04-11 15:28 UTC, lxxjn0 approved these changes
연로그, 리뷰 반영하느라 수고 많으셨습니다!! :)

서비스 테스트에서 사용할 dao 구현체를 따로 두어서 실제 dao에 의존하지 않고 테스트가 가능하게 되었네요!! 추가로 직접 구현한 테스트용 dao 구현체들도 내부적으로 동일하게 동작할 수 있도록 구체적으로 구현해 둔 부분이 인상적이었네요 :)

추가적으로 학습해볼만한 내용 피드백 남겨두었으니 한번 공부해보시면 좋을 것 같아요!! :)
레벨 1 진행하느라 수고 많으셨고 방학 푹 쉬시면서 다음 레벨 2에서 다시 만나뵙길 기대할게요!! 👍🏼 수고하셨어요

2022-04-11 15:28 UTC, lxxjn0 commented on src/main/java/chess/service/BoardDaoTestImpl.java
> +public class BoardDaoTestImpl implements BoardDao {
테스트에서 사용하기 위한 mock 객체 구현 good!!

2022-04-11 15:28 UTC, merged