[4, 5단계 - 체스] 범고래(조충범) 미션 제출합니다.
woowacourse/java-chess pull request #383
Opened 2022-04-06 12:28 UTC by cndqjacndqja

[](https://github.com/woowacourse/java-chess/pull/329#discussion_r839862030)안녕하세요 닉! 범고래입니다~😊

체스 4, 5단계 리뷰 요청 드립니다!

### 체스 게임 웹 설명

**처음 접속 시**
기존에 진행하던 게임이 존재하면, DB를 조회하여 이전 게임을 로드합니다.
만약 진행하던 게임이 없다면, 새로 만들어서 체스판을 보여줍니다.

**점수 조회**
점수 조회 버튼을 클릭 시, 현재까지 White, Black 각각의 점수를 보여줍니다.

**게임 다시 시작하기**
기존의 게임을 초기화 한 후에, 새로운 게임을 보여줍니다.

**게임 종료하기**
버튼 클릭 기준으로, 현재 점수가 더 높은 팀이 우승하여 결과를 출력 후 게임을 종료합니다.

**DB 설명**
자바 구현 코드에서 roomId를 하드코딩하고 있는 코드가 있습니다. 
이것은 처음에 선택 요구사항의 기능을 고려하다가 나온 부분입니다.  추후에 사용자 별로 체스 게임방에 입장할 수 있고, 기록을 관리할 수 있게 하기 위해 RoomDao에서 findById(roomId)를 사용하는 과정에서 나오게 됐습니다.

**이동 시 예외 처리**
API 요청 시 에러가 발생하면 자바에서 throw하고 있는 Exception의 메세지를 출력한 후, 동작하지 않게 구현했습니다.

**질문 사항**
[https://github.com/woowacourse/java-chess/pull/329#discussion_r839862030](https://github.com/woowacourse/java-chess/pull/329#discussion_r839862030)
지난 3단계 콘솔 미션 피드백에서 아래와 같은 질문을 남겼었는데요! 아직 해결되지 않아서 다시 질문드립니다 😊
현재 체스 게임의 경우, static으로 생성한 Position들은 게임을 시작하기 위해서는 모두 생성되어야 하는 상황입니다. 때문에 처음부터 static으로 생성하지 않고, 요청 시에 생성하는 것과 어떤 차이가 있는지 궁금합니다!

추가로 아직 Dao나 4, 5단계에서 추가된 클래스의 테스트가 많이 부족한 상태인데요! 조금 더 학습이 필요한 상태이지만 PR이 늦어질 것 같아서, 이 부분은 학습 후에 추가적으로 리팩토링 해보려합니다!

2022-04-08 02:10 UTC, wbluke requested changes
마지막 단계도 잘 구현해 주셨네요 ㅎㅎ 수정해주신 부분도 잘 봤습니다!
질문에 대한 답변 포함해서 소소한 코멘트 남겼으니 확인해 주세요 🙂

2022-04-08 02:10 UTC, wbluke commented on src/main/java/chess/domain/position/Position.java
>  package chess.domain.position;
아 제가 추가 코멘트를 못봤네요 ㅎㅎ 

> 수정 후 다시 보니, "저장소에 이전에 생성한 인스턴스가 없다면 새로 생성한 후 저장하고 반환" 이 부분이 static으로 미리 캐싱하는 것이 아니라 요청이 왔을 때, 저장하는 것으로 이해했는데 맞을까요??

맞아요!

> 만약 그렇다면 궁금증이 생기는데요!
요청 시 생성하게 되면, Board를 초기화 할 때 생성하게 될 것 같았습니다.
체스 게임을 시작하기 위해서는 이전에 Board가 초기화 되어야 하는데, 이때 생성하는 것과 static으로 생성하는 것의 차이가 있을까요?

좋은 질문입니다.
맞아요. 지금은 어차피 64개를 다 생성해야 하는데 무슨 차이가 있지? 라고 생각하실 수도 있는데요.
저는 `객체 그 자체`와 `객체를 사용하는 방법`에 대한 분리를 강조하고 싶었어요.
예를 들어, Position 객체를 다른 게임이나 특별한 체스 룰에서 10개만 사용한다면?
Position 객체는 지금 어디에서든 이미 그 자체로 64개의 모든 위치를 가지고 있게 됩니다.
어떤 객체의 조합 가능한 경우의 수가 64개가 아니라 10000개였다면?
이런 여러가지 가능성을 고려했을 때 객체를 설계하는 입장에서 미리 클라이언트의 사용법을 예측하는 것이 아니라, 어떤 요청이 와도 받아들일 수 있게 설계하는 것이 중요하다는 이야기였어요. (비록 지금 체스게임에서는 결과적으로 별 차이가 나지 않지만요 ㅎㅎ)

2022-04-08 02:10 UTC, wbluke commented on src/test/java/chess/domain/position/ColumnTest.java
> +        Column expected = Column.E;
검증을 위한 가공이나 선언은 then절에서 해주시면 될 것 같아요 ㅎㅎ
when절은 보통 한줄에서 끝납니다 :)

2022-04-08 02:10 UTC, wbluke commented on src/main/java/chess/service/ChessService.java
> +        Map<String, String> boardDaos = boardDao.findAll(room.get("id"));
변수명이 조금 애매한 것 같네요 :)

2022-04-08 02:10 UTC, wbluke commented on src/main/java/chess/service/ChessService.java
> +        if (room.get("status").equals("White")) {
status가 White, Black 과 같은 형태인 것 같은데, WHITE, BLACK으로 해놓고 조회할 때 Enum으로 바로 받으면 사용하기 훨씬 편할 것 같아요 :)

2022-04-09 18:41 UTC, cndqjacndqja commented on src/main/java/chess/domain/position/Position.java
>  package chess.domain.position;
현재 체스 미션에서  요구사항을 만족하는 Position 객체가 아니라, Position 그 자체의 의미로 표현하는 것이 좋다는 뜻으로 이해했습니다. 64개의 Position을 미리 캐싱했을 때는, 그 값만 사용하게 함으로서 Position의 의미를 한정하는 것이라 생각했습니다. 이런 의미에서 닉이 언급해 주신 대로 Position을 요청에 따라 생성한 후, 반환하는 것이 더 적절한 것 같네요!

2022-04-09 18:44 UTC, cndqjacndqja commented on src/main/java/chess/service/ChessService.java
> +        }
불필요한 메서드를 제거할 때, 제거되었습니다! 🤣

2022-04-09 19:30 UTC, cndqjacndqja commented
안녕하세요 닉! 피드백 반영 후, 리뷰 요청 드립니다!

2022-04-11 01:43 UTC, merged