[4, 5단계 - 체스] 레넌(조형래) 미션 제출합니다.
woowacourse/java-chess pull request #388
Opened 2022-04-06 15:32 UTC by brorae

2022-04-07 15:23 UTC, choihz requested changes
안녕하세요, 레넌!

이번 단계도 잘 구현해 주셨네요 👍 몇 가지 피드백 남겼는데 확인 부탁드리고, 이외에도 더 궁금한 점이나 의견이 있으시다면 언제든 코멘트 또는 DM 주세요~

2022-04-07 15:23 UTC, choihz commented on src/main/java/chess/domain/chessboard/ChessBoard.java
> +    }
> 체스판의 책임이 무거운 것에는 동의합니다. 하지만 외부에서 empty piece까지 생성해서 ChessBoard를 만든다면 테스트에서 어려움이 있을 것이라고 생각합니다. 보드 판을 하나 만들 때마다 Empty 까지 모두 채워줘야하기 때문입니다.

음 꼭 그런가요? `EmptyPiece`를 채우는 로직도 분리하여 재사용하면 되지 않나요? 우선 이번 단계에서는 꼭 고치지 않아도 되지만, 지금 보니 기물들을 채우는 책임을 `PiecesGenerator`와 `ChessBoard`가 나누어 갖고 있는 구조에 약간 의문이 들기도 하네요.

2022-04-07 15:23 UTC, choihz commented on src/main/java/chess/view/OutputView.java
> +    public static void printChessBoard(final Map<Position, Piece> pieces) {
> view에서 getter로 변환하는 것보다 view를 사용하는 쪽에서 getter를 사용하는 것이 더 괜찮은 방법일까요??

이 질문은 잘 이해가 안 되어서 조금 더 설명해 주시면 좋을 것 같아요.

2022-04-07 15:23 UTC, choihz commented on src/main/java/chess/dao/GameDao.java
> +    public GameDto findGameState() {
어차피 문자열만 가져다 사용하는 것 같은데 `GameDto`라는 것이 의미가 있나요?

2022-04-09 06:29 UTC, brorae commented on src/main/java/chess/view/OutputView.java
> +    public static void printChessBoard(final Map<Position, Piece> pieces) {
view의 메소드에서 ChessGame이라는 객체를 파라미터로 받아서 사용하는 것과 이 메소드를 사용하는 쪽에서 getter로  Map<Position, Piece>를 얻어 파라미터로 사용하는 것의 차이점이 질문사항이었습니다. view에서는 도메인 객체를 굳이 알필요가 없으니 후자가 맞는 것 같네요!

2022-04-10 06:54 UTC, brorae commented on src/main/java/chess/dao/BoardDao.java
> +    }
Connector 클래스를 만들어서 해당 메소드를 담당하도록 했습니다!

2022-04-10 06:55 UTC, brorae commented on src/main/java/chess/dao/BoardDao.java
> +    }
try-catch문 안에서 바로 리턴해주고, 예외 발생시 새로운 예외가 발생하도록 수정하였습니다!

2022-04-10 06:56 UTC, brorae commented on src/main/java/chess/dao/GameDao.java
> +                    return 0;
예외가 발생하도록 수정하였습니다!

2022-04-10 06:57 UTC, brorae commented on src/main/java/chess/service/BoardService.java
> +        Map<String, Piece> mapper = new HashMap<>();
수정하였습니다!

2022-04-10 06:58 UTC, brorae commented on src/main/java/chess/controller/WebController.java
> +            boardService.update(chessGame, to);
ChessService를 새로 만들어서 한번에 처리할 수 있도록 해주었습니다. :)

2022-04-10 07:02 UTC, brorae commented on src/main/java/chess/dao/GameDao.java
> +    public GameDto findGameState() {
코니의 말씀에 동의합니다. Dto를 없애고, String으로 처리할 수 있도록 수정했습니다!

2022-04-10 15:16 UTC, brorae commented on src/main/java/chess/domain/chessboard/ChessBoard.java
> +    }
코니의 말씀대로 generator에 Empty Piece를 넣는 로직을 분리하였습니다!

2022-04-11 04:33 UTC, brorae commented on src/main/java/chess/controller/WebController.java
> +            double blackScore = chessGame.calculateScore(Color.BLACK);
ChessService에서 처리할 수 있도록 수정하였습니다!

2022-04-11 04:53 UTC, brorae commented on src/main/java/chess/controller/WebController.java
> +    private ChessGame chessGame;
코니의 말씀대로 도메인 로직이 WebController에서 노출되고 있어서, Service에서 처리할 수 있도록 수정했습니다.
서비스에서는 Dao만 인스턴스 필드로 두고, Dao와의 연결만을 담당하도록 코드를 작성했었습니다.
서비스에서 ChesGame을 인스턴스 필드로 두어도 되는지 고민하다가 Controller에 비즈니스 로직이 들어간 것 같습니다.

2022-04-11 18:49 UTC, choihz approved these changes
안녕하세요, 레넌!

피드백을 잘 반영해 주셔서 이제 이번 미션은 마무리해도 될 것 같습니다. 몇 가지 코멘트와 질문을 남겨 두었는데, 혹시 더 공부하며 의견을 나누고 싶은 부분이 있으시다면 미션 완료 여부와 상관 없이 언제든 코멘트 또는 DM 주세요.

그동안 어려운 체스 미션 하시느라 정말 고생 많으셨어요. 즐거운 방학 보내시고, 다음에 다시 만나요~ 👋

2022-04-11 18:49 UTC, choihz commented on src/main/java/chess/dao/GameDao.java
> +            throw new RuntimeException();
예외에 적절한 메시지를 담아 주는 것이 좋겠죠?

2022-04-11 18:49 UTC, choihz commented on src/main/java/chess/service/ChessService.java
> +    private static final String VICTORY_MESSAGE = " 승리!!";
이런 값들을 `ChessService`에서 알고 있어야 할까요? 여태까지 했던 많은 미션들에서 출력에 관한 것은 출력을 담당하는 곳에서 처리하도록 배우거나 혹은 리뷰를 받으셨을 것 같은데요, 웹 환경에서도 그렇게 하는 편이 좋지 않을까요? 어떤 장점이 있을까요?

2022-04-11 18:49 UTC, choihz commented on src/main/java/chess/service/ChessService.java
> +    private final ChessGame chessGame;
우리가 보편적으로 사용하고 있는 웹 서비스들처럼 이 체스 프로그램을 지금 배포한다면, 오로지 하나의 체스 게임만이 존재하게 될 거예요. 여러 명이 접속해도 하나의 체스 게임을 공유하게 되기 때문에 제대로 게임할 수가 없죠. (물론 지금도 로컬에서 실행하여 여러 창을 띄워보면 바로 확인 가능하지요.) 어떻게 하면 이 구조를 개선할 수 있을지 고민해 보아요.

2022-04-11 18:49 UTC, choihz commented on src/test/java/chess/dao/GameDaoTest.java
> +        final Connection connection = Connector.getConnection();
프로덕션 코드에서 사용하는 `Connector`를 테스트 코드에서도 그대로 사용했을 때 어떤 문제가 발생할 수 있을까요? 이를 해결하려면 어떻게 해야 할까요?

2022-04-11 18:49 UTC, merged