[4, 5단계 - 체스] 판다(김건웅) 미션 제출합니다.
woowacourse/java-chess pull request #395
Opened 2022-04-06 18:40 UTC by woong7

2022-04-06 19:10 UTC, woong7 commented
안녕하세요 핀! 

먼저, 이번 체스 4,5단계 미션은 상당히 어렵게 다가왔습니다. 

DB, Spark, 웹, 쿼리, js, JSON 까지 모두 처음 다뤄보게 되어, 각각의 주제마다 족히 이틀은 공부한 것 같습니다. 
그렇게 해도 여전히 간신히 동작만 하게 만들었다는 느낌을 지울 수가 없네요..

우선 최대한 기존 도메인을 유지하려 하였으나, 콘솔 단계에서는 사용하지 않았던 dto를 작성하고, result나 score 등의 객체를 생성하였습니다. 
특히, 기존 코드 중 Map 형태나 Map.Entry 형태의 필드를 가진 객체들이 있었는데, JSON을 통해 정보를 가져오기가 너무 까다로워져서 가능하면 List 형태로 자료를 저장하도록 하였습니다. 이를 위해 기존의 Map.Entry의 역할을 하는 Grid, Score 등의 객체를 새로 작성하였습니다. 

이번 미션을 진행하면서는 도저히 시간 내에 끝낼 수 없을 것 같다는 압박감을 받았습니다. 그러다 보니, 어떻게든 일단 돌아가는 코드를 만들자라는 일념으로 미션을 수행한 것 같습니다. 추가된 Test 코드도 거의 없고, 30분전에 막 완성한, 그래서 리팩토링이 거의 안되어 있는 코드이지만, 시간 내에 일단 기능을 완성했다는 나름 뿌듯한 기분인 것도 같습니다. 

지속적으로 리팩토링을 진행해 보겠습니다. 이번에도 자세한 피드백 부탁드립니다. 
감사합니다!

2022-04-07 18:26 UTC, lalize requested changes
판다, 안녕하세요~
웹 UI 멋지게 잘 구현하셨네요 👍 
몇 가지 코멘트 남겨두었으니 확인 부탁드릴게요 :)

2022-04-07 18:26 UTC, lalize commented on src/main/java/chess/domain/piece/Piece.java
>      protected int moveCount;
moveCount는 DB에 저장하지 않아도 되나요?

2022-04-07 18:26 UTC, lalize commented on src/main/java/chess/domain/piece/PieceFactory.java
> +    }
Piece는 불변 객체가 아닌데 만들어놓고 사용해도 되나요?

2022-04-07 18:26 UTC, lalize commented on src/main/java/chess/WebApplication.java
> +                    responseDto = webChessController.start();
컨트롤러와 라우터는 1:1로 변경해주세요.

2022-04-07 18:26 UTC, lalize commented on src/main/java/chess/dto/Grid.java
> +public class Grid {
다른 dto 처럼 이름에 일관성을 지켜주세요.

2022-04-07 18:26 UTC, lalize commented on docker/db/mysql/init/init.sql
> +    black_score varchar(20) not null
계산할 수 있는 값인데 DB에 저장한 이유가 있으신가요?
사용하고 있지도 않은 것 같아요.

2022-04-09 22:10 UTC, woong7 commented
안녕하세요 핀. 판다입니다!

주신 피드백 내용을 바탕으로 리팩토링을 진행하고 있는데요, 
서비스 레이어의 개념이나 라우터 등 생소한 개념이 많아 학습하는 것부터 시작하게 되었습니다. 
그러다 보니 시간이 너무 지연되는 것 같아 우선 일부분이라도 미리 리뷰 요청을 드립니다. 

아직 커밋하지 않은 내용으로는 WebChessService를 생성해서 컨트롤러를 다음과 같은 형태로 변경하였고, 
```java
get("/load", (req, res)->gson.toJson(webChessService.loadGame()));
```

결과 도출의 책임을 Result로 넘기는 작업을 진행 중에 있습니다. 

다만 Score 객체는 단순히 구조체로서의 역할을 기대하고 작성했던터라, Score 객체가 꼭 점수 계산 로직을 가져야 하는지 궁금합니다! Winner를 통해 승자를 결정하고, Score를 통해 각각의 점수를 계산한 다음, Winner와 Score를 Result에 넘겨주는 방식이 더 좋은 방식이 될까요? 

또, Piece들은 상속 구조로도 어떻게든 구현은 가능할 것 같지만, Composition으로 전환하는 것을 고민하고 있습니다. 
각각의 기물에 대해 MovingStrategy를 작성해서 Piece에 주입하는 방식으로 구현할 수 있을 것 같은데, 코드의 구조가 대폭 바뀔 것 같아 우선순위를 뒤로 잡았습니다. 

최대한 빨리 다른 부분도 리팩토링을 더 해보도록 하겠습니다. 감사합니다!

2022-04-11 08:50 UTC, lalize requested changes
판다, 안녕하세요!
아직 리팩토링 진행중이신 것 같아서 추가 코멘트 간단히 남겼으니 확인 부탁드릴게요~

2022-04-11 08:50 UTC, lalize commented on docker/db/mysql/init/init.sql
> +);
아래 글을 읽고 전체 파일에 대해서 확인 부탁드릴게요~
* [파일 끝에 개행을 추가해야 하는 이유](https://blog.coderifleman.com/2015/04/04/text-files-end-with-a-newline/)

2022-04-11 08:50 UTC, lalize commented on src/main/java/chess/ChessGame.java
> +public class ChessGame {
ChessGame은 도메인 객체에 가까워 보이는데 패키지 위치가 컨트롤러 레벨에 있고 dto에 의존하고 있어요.

2022-04-11 08:50 UTC, lalize commented on src/main/java/chess/WebChessController.java
> +    final ChessGame chessGame = new ChessGame();
ChessGame을 상태로 갖고 여러 사용자가 동시에 게임을 진행하는 경우 어떤 문제가 있을 수 있을까요?

2022-04-11 08:50 UTC, lalize commented on src/main/java/chess/domain/piece/Piece.java
> +        return (pieceType.name() + color.name()).toLowerCase();
dao를 위한 부분인 것 같은데요. 가능하면 도메인 로직과 관계 없는 부분은 값을 꺼내서 저장하는 게 더 좋아 보여요.
db에 값을 입력하여 저장하는 것과 view에 값을 입력하여 출력하는 것을 동일한 레벨로 생각해보면 어떤 느낌인지 알 수 있을 거예요.

2022-04-11 08:50 UTC, lalize commented on src/main/java/chess/domain/piece/Piece.java
> +        return (pieceType.name() + color.name()).toLowerCase();
DB에 저장할 때 pieceType과 color를 별도 컬럼으로 저장하면 어떨까요?

2022-04-11 08:50 UTC, lalize commented on src/main/java/chess/domain/piece/Piece.java
> +    public Piece setMoveCount(int moveCount) {
생성자로 초기화하면 어떨까요?

2022-04-11 08:50 UTC, lalize commented on src/main/java/chess/domain/piece/PieceType.java
> +    King, Queen, Rook, Knight, Bishop, Pawn, Blank;
enum 상수는 관례적으로 모두 대문자로 작성해요 :)

2022-04-11 08:50 UTC, lalize commented on src/main/java/chess/dto/ChessGameDto.java
> +    public Result getResult(){
dto가 도메인을 반환해도 되나요? dto를 사용하는 목적을 다시 한번 학습해보시면 좋을 것 같아요.

Result는 도메인 객체로서의 역할 보다는 Dto에 가까운 것일 수도 있을 것 같아요. 한번 고민해보시고 Dto라고 생각되시면 Result를 Dto로 리팩토링 해주세요.

2022-04-11 08:50 UTC, lalize commented on src/main/java/chess/domain/game/Score.java
> +public class Score {
> 결과 도출의 책임을 Result로 넘기는 작업을 진행 중에 있습니다.
다만 Score 객체는 단순히 구조체로서의 역할을 기대하고 작성했던터라, Score 객체가 꼭 점수 계산 로직을 가져야 하는지 궁금합니다! Winner를 통해 승자를 결정하고, Score를 통해 각각의 점수를 계산한 다음, Winner와 Score를 Result에 넘겨주는 방식이 더 좋은 방식이 될까요?


판다의 생각을 들어보면 Score는 도메인 객체가 아닌 Dto라고 이해할 수 있을 것 같아요.
구조체의 역할을 기대했다는 것은 객체로 바라보는 것이 아닌 데이터로 바라보고 절차지향적인 코드를 작성하겠다는 의미와 크게 다르지 않은 것 같아요.

2022-04-12 19:34 UTC, woong7 commented
안녕하세요 핀! 
피드백 주신 사항들을 바탕으로 리팩토링을 좀 더 진행해 보았습니다. 

Piece를 상속 구조에서 MovingPattern을 주입받도록 변경한 것을 포함해 변경점이 있습니다. 

방학중임에도 상세한 피드백을 주셔서 감사드립니다!

2022-04-14 09:42 UTC, lalize approved these changes
판다, 안녕하세요~
이전 피드백 반영이 안된 부분이 다수 존재하여 시간 되시면 반영해보시면 좋을 것 같아요.
체스 미션은 이만 머지하도록 할게요! 고생하셨습니다~

2022-04-14 09:42 UTC, lalize commented on src/main/java/chess/WebChessController.java
> +        get("/end", (req, res) -> gson.toJson(webChessService.endGame(chessGame)));
http method에 대해서 학습해보시고, 어떤 method가 적합한지 고민해보시면 좋을 것 같아요.

2022-04-14 09:42 UTC, lalize commented on src/main/java/chess/console/ChessGame.java
웹/DB 연동을 했을 뿐인데 콘솔 체스때 만들어 두었던 ChessGame 도메인을 사용하지 않고 새로 만들게 되었을까요?

2022-04-14 09:43 UTC, merged