[4, 5단계 - 체스] 라라(박세은) 미션 제출합니다.
woowacourse/java-chess pull request #397
Opened 2022-04-06 19:57 UTC by sure-why-not

앨런, 안녕하세요! 라라입니다. 😸 
기존 콘솔 프로그램 리팩토링부터 웹, DB 연동까지 하다보니 벌써 목요일이네요. 😱
웹은 역시나.. (코드가 ...😅 ) 어려웠지만 DB 연동은 재밌었습니다!

### 1. Piece 상속 제거
(이 리팩토링 과정에서 코드가 굉장히 많이 바뀌었습니다. 😅)
**기존 상속 구조에서 추상화시킨 부모 클래스가 `isKing()`, `isPawn()` 과 같은 하위 클래스를 위한 기능들이 계속해서 추가되는 것이 잘못됐다고 생각했습니다.** 그리고 `isMovable()` 의 경우 동일하게 구현되는 기물이 많았기 때문에 중복 문제도 있었습니다.
```
public class Piece {
    private final PieceType type;
    private final PieceColor color;
    private final MovingPattern movingPattern;
```
이렇게 변경하여 `PieceType` 으로 기물의 종류를 결정하였고, 위의 문제점들을 해결할 수 있었습니다.
`MovingPattern` 을 추가함으로써 '기물이 이동과 관련된 책임까지 가져야하나?' 라는 의문을 해결할 수 있었습니다.

### 2. 웹, DB 연동
DAO, Service 와 같은 개념이 낯설어서 잘못된 부분이 많을 것 같습니다. 많은 지적 부탁드려요! 😆
제가 학습한 내용으론 Dao 는 Database에 data를 CRUD하는 계층, Service 는 컨트롤러에 필요한 핵심 비즈니스 로직을 구현하는 계층 이라고 이해하고 구현했습니다.

2022-04-06 20:40 UTC, sure-why-not reviewed
앨런 안녕하세요.
구현 내용과 질문사항 작성했습니다!

잘 부탁드립니다~~🙇🏼‍♂️

2022-04-06 20:40 UTC, sure-why-not commented on docker/db/mysql/init/init.sql
> +
정석대로 하면 game 테이블에 여러 게임을 저장하고, piece 테이블에 게임별 piece과 position_id 를 저장해야할 것 같은데... 일단 구현을 먼저 목표로 하고!!
현재 구현 상태는 게임 1판만 가능하고 한 게임에 대한 piece 만 저장하도록 한 상태입니다! 😂

2022-04-06 20:40 UTC, sure-why-not commented on src/main/java/chess/domain/piece/PieceFactory.java
> +    private final static Piece WHITE_PAWN = new Piece(PAWN, WHITE, new WhitePawnMovingPattern(Movement.getWhitePawnMoving()));
색상/타입별 기물을 캐싱해두고 재사용하도록 했습니다!

2022-04-06 20:40 UTC, sure-why-not commented on src/main/java/chess/domain/piece/PieceFactory.java
> +        }
DB 에 기물의 색상, 타입이 저장되어 있기 때문에 도메인 객체로 변환하는데 마땅한 방법을 찾지 못해 이런 하드코딩이 드러가게 됐습니다. 😂
기존 PieceType 을 많이 수정하면 해결할 수 있을 것 같은데, 기존 도메인 코드가 안 좋은 방향으로 바뀌게 되어 이 방법을 선택했습니다. 안 좋은.. 방법이겠죠....?🙄

2022-04-06 20:40 UTC, sure-why-not commented on src/test/java/chess/dao/GameDaoImplTest.java
> +        );
Dao 를 테스트하는 것에 대해 앨런은 어떻게 생각하시나요??
핵심 로직이라고 생각해서 `BeforeEach` 에서 `removeAll(`) 를 통해 테스트 코드를 작성하긴 했는데,
실제 DB 라면 데이터를 모두 날려버리는 😱  위험한 동작인데 괜찮을까 싶어서요!
그리고 데이터를 모두 삭제했기 때문에.. `save()` 에 의존하는(?) 것 같아서 이 부분도 잘못된 건지 궁금합니다!

2022-04-08 07:09 UTC, hongbin-dev requested changes
안녕하세요 라라! 리뷰어 앨런입니다.
4,5 단계 미션 진행하시느라 고생많으셨어요! 
몇 가지 코멘트 남겼으니 확인해주세요~

2022-04-08 07:09 UTC, hongbin-dev commented on src/main/java/chess/dao/GameDao.java
> +    void updateTurn(String turn);
이쪽은 사용하지 않는 것 같은데요. 삭제하는게 어떨까요?

2022-04-08 07:09 UTC, hongbin-dev commented on src/main/java/chess/dao/GameDaoImpl.java
> +    }
커넥션이 웹서버를 실행할때부터 쭉 물고있는데요. 요청할 때 마다 연결하고, 반환하는 형태로 가는게 어떨까요?

2022-04-08 07:09 UTC, hongbin-dev commented on src/main/java/chess/dao/GameDaoImpl.java
> +        }
쿼리가 실패하면 스택트레이스만 출력하고, 별다른 액션이 없네요.
만약 실패하게되면 어떻게 되나요?

2022-04-08 07:09 UTC, hongbin-dev commented on src/main/java/chess/dao/GameDaoImpl.java
> +        }
PreparedStatement도 자원을 사용하셨으면 반환하셔야합니다!

try with resources 문법을 사용해보면 좋을 것 같아요.
https://tecoble.techcourse.co.kr/post/2021-04-26-try-with-resource/

2022-04-08 07:09 UTC, hongbin-dev commented on src/main/java/chess/dao/GameDaoImpl.java
> +        return null;
null을 반환하는 이유가 있을까요?

2022-04-08 07:09 UTC, hongbin-dev commented on src/main/java/chess/dao/PieceDaoImpl.java
> +        pieceDtos.forEach(this::save);
순차적으로 save를 날리게되면, 데이터베이스와 커넥션이 N번 발생할 것 같습니다!
한번에 데이터베이스로 보낼 수 있는 방법은 없을까요?

2022-04-08 07:09 UTC, hongbin-dev commented on src/main/java/chess/dao/PieceDaoImpl.java
> +        return pieces;
while문 중에 예외가 발생하면, catch에서 잡히고 불안정한 pieces가 반환되지않을까요?
실패 원장성 있도록 코드를 작성하면 좋을 것 같습니다!

2022-04-08 07:09 UTC, hongbin-dev commented on src/main/java/chess/db/DBConnector.java
> +        }
```suggestion
        roadDriver();
        try {
           return DriverManager.getConnection(URL, USER, PASSWORD);
        } catch (SQLException e) {
            throw ...
        }
```
이런식으로하면 불필요한 null할당을 줄일 수 있을 것 같아요.
또 여기 catch부분에서도 `e.printStackTrace();`만 하도록되어있는데, 이 부분도 보완하면 좋겠습니다.

2022-04-08 07:09 UTC, hongbin-dev commented on src/test/java/chess/dao/FakeGameDao.java
> +public class FakeGameDao implements GameDao {
여기는 구현이 덜 된걸까요?

2022-04-08 07:11 UTC, hongbin-dev commented
> 처음에 이게 ChessGame.isRunning() 테스트를 말씀하시는 줄 알았는데 Board 의 테스트더라구요! Board 에서 게임이 종료됐을 때의 상황은 어떤 걸 말씀하시는 것일까요??

왕이 1개인 상황에서 `board.movePiece()` 메서드가 예외발생하는지 테스트 필요하다는 말이었습니다!

2022-04-08 07:20 UTC, hongbin-dev commented on src/main/java/chess/domain/piece/PieceFactory.java
> +        }
캐시 객체를 컬렉션으로 갖게 된다면 하드코딩은 피할 수 있어보이네요

2022-04-08 07:21 UTC, hongbin-dev commented on src/test/java/chess/dao/GameDaoImplTest.java
> +        );
네 보통 AfterEach에서 모두 지우는편인데요.
현재 라라가 걱정하는 부분은, 서버 DB와 테스트 DB가 동일한 곳을 사용해서 문제라고 생각합니다.
커넥터쪽을 추상화해볼 수 있지않을까요?

2022-04-11 18:53 UTC, sure-why-not commented on src/main/java/chess/domain/piece/PieceFactory.java
> +        }
오 좋은 방법이네요!! 감사합니다. 🥺

2022-04-11 18:54 UTC, sure-why-not commented on src/main/java/chess/controller/ChessController.java
> +            response.body(exception.getMessage());
앗 그렇네요!! 🙄  에러 메세지를 ErrorResponceDto 에 담아 전달하도록 변경했습니다!

2022-04-11 18:56 UTC, sure-why-not commented on src/main/java/chess/controller/ChessController.java
> +        return new HandlebarsTemplateEngine().render(new ModelAndView(model, VIEW_NAME));
해당 객체를 미리 생성해두고, 재사용하도록 변경했습니다!! 감사합니다. 😊

2022-04-11 18:56 UTC, sure-why-not commented on src/main/java/chess/dao/GameDao.java
> +    void updateTurn(String turn);
앗 삭제했습니다!!

2022-04-11 18:57 UTC, sure-why-not commented on src/main/java/chess/dao/GameDaoImpl.java
> +    }
미처 생각하지 못했던 부분이네요. 요청할 때만 커넥션을 연결하고, 요청 처리 후에는 반환시키도록 했습니다!!

2022-04-11 19:08 UTC, sure-why-not commented on src/main/java/chess/dao/GameDaoImpl.java
> +        }
이 부분도 생각하지 못했던 부분이네요. ㅠ_ㅠ  
Dao 에서는 SqlQueryException 이라는 custom exception 을 만들어서  클라이언트에게 명확한 예외 메세지와 함께 던져주도록 했습니다.
그리고 Service 에서 해당 예외를 catch 할 경우 또 다시 예외를 던져주도록 했는데, 이 구조가 괜찮을까요?
계층별로 계속해서 try-catch 를 해줘야하는 것 같아서 괜찮은 방법일지 헷갈리네요! 🤔

2022-04-11 19:09 UTC, sure-why-not commented on src/main/java/chess/dao/GameDaoImpl.java
> +        }
반환에 대해서 처리하지 않았었네요. 학습이 부족했던 것을 깨달았습니다. 😂 
 try with resources 를 사용해 Connection, PreparedStatement 자원을 반납하도록 했습니다.
피드백 해주셔서 감사합니다!! 🙇🏼‍♂️

2022-04-11 19:12 UTC, sure-why-not commented on src/main/java/chess/dao/GameDaoImpl.java
> +        return null;
이 부분을 일단 null로 반환하고추가로 리팩토링하려고 남겨두었는데 추후 처리를 하지 못한 부분이네요. 😂
예외가 발생해 데이터를 찾지 못할 경우 예외를 던지도록 변경했습니다!

2022-04-11 19:13 UTC, sure-why-not commented on src/main/java/chess/dao/PieceDaoImpl.java
> +        pieceDtos.forEach(this::save);
앗 그렇네요. 😭
`addBatch()` 를 사용해 다중 쿼리문을 한 번에 보내도록 수정했습니다!!

2022-04-11 19:14 UTC, sure-why-not commented on src/test/java/chess/dao/FakeGameDao.java
> +public class FakeGameDao implements GameDao {
앗 현재 Game 이 1개밖에 없도록 구현된 상태인데, 혹시 어떤 부분이 부족하다고 느끼셨는지 알 수 있을까요?! 🥺

2022-04-11 19:20 UTC, sure-why-not commented on src/test/java/chess/dao/GameDaoImplTest.java
> +        );
커넥터쪽을 추상화한다는 것이 
Dao 처럼 테스터용 DB 를 생성해 해당 DB 에 연결하는 Fake 객체를 만들어서 테스트해보라는 말씀이실까요?!

2022-04-14 06:46 UTC, hongbin-dev commented on src/main/java/chess/dao/GameDaoImpl.java
> +        }
예외는 어디선가 핸들링은 해줘야하긴합니다..! 이 구조도 괜찮을 것 같고, 추후 스프링을 학습하면서 예외핸들링 해주는 객체 이용해봐도 좋을 것 같아요.

2022-04-14 06:49 UTC, hongbin-dev commented on src/test/java/chess/dao/FakeGameDao.java
> +public class FakeGameDao implements GameDao {
테스트 더블에 Fake라고 함은, 실제처럼 동작하는 객체로 애해했는데요. 현재 구현방식이 스터빙형태와 유사해서 코멘트 남겼습니다.

https://tecoble.techcourse.co.kr/post/2020-09-19-what-is-test-double/ 이 부분을 참고해보시면 좋을 것 같아요.

2022-04-14 06:54 UTC, hongbin-dev commented on src/main/java/chess/dao/GameDaoImpl.java
> +        }
다시 확인해보니, 스파크 컨트롤러에 exception 메서드를 사용하고 있군요? 이쪽으로 예외를 위임해봐도 좋을 것 같네요.

2022-04-14 07:07 UTC, hongbin-dev approved these changes
안녕하세요 라라!
피드백 반영 잘 해주셨군요 💯
이만 머지하겠습니다. 체스 고생 많으셨어요 👋

2022-04-14 07:07 UTC, hongbin-dev commented on src/main/java/chess/dao/GameDaoImpl.java
> +    public GameDto find() {
이 메서드는 어떤 row를 찾아도 무관한건가요? 식별자를 받아서 데이터베이스에서 가져와야하지 않을까요?

2022-04-14 07:07 UTC, hongbin-dev commented on src/main/java/chess/dao/GameDaoImpl.java
> +            }
이 부분은 비즈니스 부분인 것 같아요. 값이 없다면 Service레이어에서 대체 값을 전달하는게 좋아보여요.
DAO 데이터를 접근하는데 집중하면 좋을 것 같습니다.

2022-04-14 07:07 UTC, hongbin-dev commented on src/main/java/chess/db/DBConnector.java
> +    }
커넥션을 요청할 때마다 새로 생성하고있는데, 어떻게하면 개선할 수 있을지 고민해보면 좋을 것 같습니다.

2022-04-14 07:07 UTC, merged