[4, 5단계 - 체스] 리버(구동희) 미션 제출합니다.
woowacourse/java-chess pull request #406
Opened 2022-04-07 06:02 UTC by gudonghee2000

안녕하세요 핀!
정말 오랜만에 pr을 드리게됬어요!
웹과 DB에 대해 구현해보았어요!
아직, 웹과 DB에 대한 경험이 거의 없어서 많은 시간을 투자했지만 아쉬움이 남아요..!
그래도 피드백을 한번 부탁드리고싶어 제출하였어요 핀!

이번 리뷰도 잘 부탁드립니다 핀!
감사합니다😊😊

2022-04-09 03:02 UTC, lalize requested changes
리버, 안녕하세요!
구현하신 코드 잘 보았어요~
몇 가지 코멘트 남겼으니 확인 부탁드릴게요 :)

2022-04-11 07:13 UTC, gudonghee2000 commented on src/main/java/chess/dao/GameService.java
> +package chess.dao;
요청에 따라서 값을 꺼내 State를 구성하도록 변경해보았어요!

2022-04-11 07:14 UTC, gudonghee2000 commented on src/main/java/chess/model/board/result/Score.java
> +    public Map<Team, Double> createScore() {
score 함수명을 변경해보았어요!

2022-04-11 07:14 UTC, gudonghee2000 commented on src/main/java/chess/model/board/result/Winner.java
> +    public Team pickFrom(Map<Team, Double> scores) {
Winner 객체 내부의 score필드를 가지고 메서드를 수행하도록 변경하였습니다!

2022-04-11 07:15 UTC, gudonghee2000 commented on src/main/java/chess/model/piece/Bishop.java
> +    private final String symbol = "BISHOP";
필드로 구현하지 않고 getScore와 같이 함수 내부에서 값을 주도록 하였습니다!

2022-04-11 07:16 UTC, gudonghee2000 commented on src/main/java/chess/model/piece/Bishop.java
> +    public String getSymbol() {
`@Override` 어노테이션을 붙였어요!
부모 객체인 `Piece`에서 추상메서드로 `getSymbol()`의 선언부를 작성하였기 때문에 어노테이션을 붙여야한다고 생각해요!
또한, 자식 객체에서 부모객체의 메서드를 오버라이드 했다는 것을 명시해주기 위함이기 때문이라고도 생각해요!

2022-04-11 07:17 UTC, gudonghee2000 commented on src/main/java/chess/dao/SquareDaoImpl.java
> +            final PreparedStatement statement = connection.prepareStatement(sql);
감사합니다 핀!
말씀해주신 Closeable, AutoCloseable, try-with-resources를 공부하고 적용해보았어요!

2022-04-11 07:17 UTC, gudonghee2000 commented on README.md
> +- [ ] 웹 브라우저에서 체스판을 출력한다.
README를 업데이트하였어요!

2022-04-11 07:17 UTC, gudonghee2000 commented on docker/db/mysql/init/init.sql
> +);
헉..! 지금은 turn 테이블을 제거하고 state테이블을 추가하여 DDL을 최신화하였어요!

2022-04-11 07:54 UTC, gudonghee2000 commented on src/main/java/chess/dao/ConnectionManager.java
> +public class ConnectionManager {
DataSource 인터페이스를 구현하여 추상화 해보았어요!

2022-04-11 07:58 UTC, gudonghee2000 commented on src/main/java/chess/controller/WebChessController.java
> +        get("/end", (req, res) -> gson.toJson(gameService.end()));
질문을 드린 후 수정하겠습니다! 감사합니다 핀😊

2022-04-11 08:00 UTC, gudonghee2000 commented
안녕하세요 핀! 
방학이 되고 늦게 pr을 드리게되었어요!😔
말씀해주신 피드백들을 바탕으로 코드를 수정해보았는데요
코드를 리팩터링하면서 몇가지 궁금증이 생겨 질문을 드려요!

### Closeable, AutoCloseable, try-with-resources
말씀 해주신 `Closeable, AutoCloseable, try-with-resources`에 대해 학습을 하고 `try-with-resources`를 적용해보았는데요!
그런데, `try-with-resources`문에서 자원을 닫으려면 `AutoCloseable`을 구현한 객체만 가능하다는 것을 알았어요!
또한,  `try-with-resources`문을 적용한 객체가 `close()`를 잘 수행하는지 테스트 코드를 통해 확인해 볼필요가 있다고 생각하는데요! `try-with-resources`문이 `close()`를 잘 수행하는지 테스트하는 방법이 있을까요?!

### Get이 아닌 Post로 요청을 보내야하는이유
피드백 해주신 `/start`와 `/end`를 post 요청으로 변경하는 것에 대해 궁금증이 있어 질문드려요!
저는 `/start`와 `/end`로 요청을 보낼 때, 암호화된 정보나 따로 데이터를 프론트에서 전달하는 부분이 없어서 `get`을 사용하였는데요! 그래도 `post`를 사용하는것이 적절한 것일까요?? 

항상 꼼꼼한 리뷰 감사해요!
이번 리뷰도 잘 부탁드려요 핀!
감사합니다😊😊

2022-04-12 08:09 UTC, lalize requested changes
리버, 리뷰 반영 잘해주셨어요:)
추가 코멘트 남겼으니 확인 부탁드릴게요~

2022-04-12 08:09 UTC, lalize commented on src/main/java/chess/service/GameService.java
> +    public ResultDto status(String command) {
상태를 업데이트하는 이유가 무엇인가요?
게임 진행중에도 점수를 볼 수 있으면 좋을 것 같아요.

2022-04-13 07:33 UTC, gudonghee2000 commented on src/main/java/chess/service/GameService.java
> +    public ResultDto status(String command) {
status시 상태를 업데이트하지 않고 
점수와 승자만 출력한후 게임을 이어서 진행 할 수 있도록 변경하였어요!

2022-04-13 07:33 UTC, gudonghee2000 commented on src/main/java/chess/controller/WebChessController.java
> +        get("/start", (req, res) -> gson.toJson(gameService.start()));
아! 감사합니다 핀😊
post를 사용하도록 변경하였어요!

2022-04-13 07:34 UTC, gudonghee2000 commented on src/main/java/chess/service/converter/StringToStateConverter.java
> +        if(stateName.equals("READY")) {
NPE가 발생하지 않도록 변경하였어요!

2022-04-13 07:35 UTC, gudonghee2000 commented on src/main/java/chess/service/GameService.java
> +        String nowStateName = stateDao.find();
stateDao.find시에 state 객체를 반환하도록 변경하였습니다! 그런데, stateDao에 Board와 의존성이 형성되었어요..! 수정하도록하겠습니다!😔

2022-04-13 07:35 UTC, gudonghee2000 commented on src/main/java/chess/dao/DataSourceImpl.java
> +    private static final String PASSWORD = "password";
생성자로 주입받도록 변경하였어요!

2022-04-13 07:35 UTC, gudonghee2000 commented on src/main/java/chess/dao/DataSourceImpl.java
> +    }
런타임 예외를 통해 실패하도록 변경해보았어요!

2022-04-13 07:36 UTC, gudonghee2000 commented on src/main/java/chess/dao/StateDao.java
> +    void update(String white_turn, String black_turn);
리팩터링과정에서 발견하지못했던것같아요! 수정하였습니다!

2022-04-13 07:39 UTC, gudonghee2000 commented on src/main/java/chess/dao/SquareDaoImpl.java
> +        throw new IllegalArgumentException("[ERROR] 저장된 데이터를 가져 올 수 없습니다.");
적절하지 못한 인자를 메서드에 넘겨주었을때 발생하는 오류라고 생각해요!
미션을 진행해오면서 `IllegalArgumentException` 만을 사용하다 보니 습관적으로 `IllegalArgumentException`만 사용했던것 같아요..! 지금은 `RuntimeException`으로 수정하였습니다!

2022-04-14 07:04 UTC, gudonghee2000 commented on src/main/java/chess/model/board/result/Winner.java
> +        return NONE;
개별적으로 점수를 요청하도록 변경해보았어요!

2022-04-14 07:06 UTC, gudonghee2000 commented on src/main/java/chess/service/GameService.java
> +        squareDao.update(target, state.getBoard().get(Position.from(target)));
repository를 활용해 서비스에서 DB 구조에 맞게 저장하는 방법을 repository로 이동시켜보았어요!

2022-04-15 03:41 UTC, gudonghee2000 commented on src/main/java/chess/dao/StateDaoImpl.java
> +    public void save(String name) {
공통된 부분을 추출하도록 해보았어요!

2022-04-15 03:43 UTC, gudonghee2000 commented on src/main/java/chess/model/board/result/Winner.java
> +    public Team pickFrom() {
저는 항상동사로 지어야한다고 생각하였어요! 보내주신 링크 감사히 보겠습니다 핀!

2022-04-15 03:45 UTC, gudonghee2000 commented
안녕하세요 핀!
말씀해주신 피드백을 바탕으로 수정을 진행해보았어요! 그런데 리팩터링을 하면서 dao가 점점 복잡해지는 느낌이 들어 dao 리팩터링을 잘 한 것인지 의문이 들었어요!

꼼꼼한 리뷰 항상 감사합니다 핀!!
이번 리뷰도 잘부탁드립니다 감사합니다 핀!😊

2022-04-15 09:49 UTC, lalize approved these changes
리버, 안녕하세요!
리뷰 반영 잘해주셨네요 👍 
체스 미션은 이만 머지 하도록 할게요!
추가로 간단히 코멘트 남겼으니 확인해보시면 좋을 것 같아요~
고생하셨습니다 ~

2022-04-15 09:49 UTC, lalize commented on src/main/java/chess/dao/SquareDaoImpl.java
> +    }
https://github.com/woowacourse/java-chess/pull/406#discussion_r848068888

try-with-resources 기본 프레임은 한 곳에 모으고, 변하는 부분을 인터페이스로 분리하면 반환 타입, 조건 타입이 달라도 중복 없이 모든 dao 코드에서 재사용할 수 있지 않을까요?

아래 예시 코드를 참고해보세요~
```java
interface Query {
  <T> T fetch(...);
}

Query query = new QueryImpl(dataSource);

public Map<String, String> find() {
  String sql = ...;
  StatementSetter statementSetter = ...;
  RowMapper rowMapper = ...;
  return query.fetch(sql1, statementSetter, rowMapper);
}
```

2022-04-15 09:49 UTC, lalize commented on src/main/java/chess/dao/SquareDaoImpl.java
> +        insert(position, piece);
Dao는 단순 CRUD만 하도록 하면 객체의 역할이 더 명확해지고 단순하게 가져갈 수 있지 않을까요?
save를 했을 때 insert를 할건지 update를 할건지는 Repository가 구현하면 어떨까요?

2022-04-15 09:49 UTC, lalize commented on src/main/java/chess/model/board/result/Score.java
> +    private Double team(Team team, Map<Position, Piece> board) {
double 원시 타입을 반환하면 어떨까요?

2022-04-15 09:49 UTC, lalize commented on src/main/java/chess/model/board/result/GameResult.java
> +public class GameResult {
각 메서드는 각각의 필드만 사용하고 있는데요~ GameResult가 정말로 필요한 객체인가요?

2022-04-15 09:49 UTC, merged