[4, 5단계 - 체스] 조시(조현근) 미션 제출합니다.
woowacourse/java-chess pull request #410
Opened 2022-04-07 06:31 UTC by hyunrrr

안녕하세요 구구!!
이번 미션은 최대한 웹과 db가 잘 동작하는데 집중해 구현했습니다!! 처음 해보는 거라 전체적인 코드의 구조는 많이 이상한거같네요..
ui는 맨 처음에 ```localhost:8082```로 접속해 start/end 명령을 입력받고 start인 경우 ```/board``` end인 경우 어플리케이션이 종료되도록 했습니다.
```/board```에서는 move/status명령을 받고 move인 경우 체스말을 이동 시킨 다음 갱신된 체스판을 ```/board```에 출력합니다.
status인 경우 ```/status```로 이동해 현재 상태를 출력하도록 했습니다!!
왕이 잡힌 경우에는 index.html을 보여줘 다시 start/end명령을 입력할 수 있게 했습니다.

db는
```java
create table board
(
    id int not null auto_increment primary key,
    game_id int not null,
    type varchar(1) not null,
    y int not null,
    x int not null,
    foreign key (game_id) references game(id)
);

create table game
(
    id int not null primary key,
    turn varchar(5) not null
);
```
테이블 2개를 만들어 turn에 대한 정보는 game테이블에, 보드 말의 위치에 대한 정보는 board테이블에 저장하도록 했습니다!!
각 db테이블엔 dao객체를 이용해 쿼리를 보내게 했고, dao객체에 대한 요청은 dbService라는 객체를 통해 하도록 했습니다!!!

db요구사항은 필수요구사항만 우선 구현했습니다!!!
감사합니다!!!!

2022-04-07 07:26 UTC, kang-hyungu requested changes
조시 몇 가지 코멘트 남겼어요.
수정하고 나서 리뷰 요청 후에 슬랙 스레드에 @구구 남겨주세요

2022-04-07 07:26 UTC, kang-hyungu commented on src/main/java/chess/domain/ChessBoard.java
> +    public void initFromDb(GameInformationDto gameInformationDto, ChessBoardDto chessBoardDto) {
도메인 객체는 순수하게 체스 게임과 관련된 규칙만 처리해야 합니다.
메서드명에서 db를 제거하고 dto도 사용하지 않도록 바꿔보세요.

2022-04-07 07:26 UTC, kang-hyungu commented on src/main/java/chess/domain/ChessGame.java
> +import chess.dto.ChessBoardDto;
도메인 클래스에서 dto 의존성 만들지 마세요.
dto가 추가될 때마다 도메인 클래스가 수정해야 되고 연결되는 객체가 많아지는 문제가 있습니다.

2022-04-13 06:37 UTC, hyunrrr commented on src/main/java/chess/WebApplication.java
>  public class WebApplication {
컨트롤러에서 http 관련 처리, 그리고 여러 모듈에 대한 흐름처리(ex. move명령인 경우 view로직을 통해 위치 값을 도메인에서 쓸 수 있는 객체로 변환하고, 도메인에서 move를 수행하고, storageService를 통해 데이터를 저장함)를 제외한 나머지 책임은 다른 객체로 모두 옮겼습니다!!

2022-04-13 06:41 UTC, hyunrrr commented on src/main/java/chess/WebApplication.java
> +    private static String doInGameCommand(Response res, ChessGame chessGame, DbService dbService, List<String> inputs) {
이 부분에 대해 고민해봤는데 사실 어떻게 해야 할지 잘 모르겠습니다.. 현재는 controller의 move메서드와 같이 각 커멘드에 대한 메서드로 쪼개고, 메서드 안에서 move명령을 수행하는데 필요한 view로직, 도메인로직, storage저장을 수행하고 있습니다!!
Command객체를 만들고 웹과 콘솔 컨트롤러를 모두 아우를 수 있는 인터페이스를 만들까 생각해보았지만 매개변수(view처리를 위한)가 달라 추상화시키기 힘들었고, 추상화 없이 단순히 command객체에 옮기기에는 굳이라는 생각이 들었습니다.
혹시 제가 놓친 부분이 있을까요..?

2022-04-13 06:46 UTC, hyunrrr commented on src/main/java/chess/WebApplication.java
> +        return null;
그렇군요!! 전체적으로 null을 없애고 emptyCollection을 반환하도록 변경했습니다!!
고민하다가 든 의문이 있는데 현재 제 코드엔 없지만 만약 원시타입을 필드로 가지고 있는 dto를 return해야 할때 아래와 같이 empty인지 나타내기 위한 boolean 필드를 추가로 가지고 있어도 괜찮을까요?
```
class ExampleDto {
    private int data1;
    private String data2;
    private boolean emptyCondition; // 이런 변수를 가지고 있어도 될까요??

    // getter setter

    public boolean isEmpty() {
        return emptyCondition;
    }
}
```

2022-04-13 06:47 UTC, hyunrrr commented on src/main/java/chess/WebApplication.java
> +    private static String doInGameCommand(Response res, ChessGame chessGame, DbService dbService, List<String> inputs) {
게임 규칙에 대해선 도메인에 요청을, db에 대해선 storageService에 요청을 하도록 책임을 분리했습니다!
근데 이런 요청을 보내고 흐름을 제어할 메서드는 컨트롤러에 있어도 괜찮은건가요?

2022-04-13 06:48 UTC, hyunrrr commented on src/main/java/chess/WebApplication.java
>  public class WebApplication {
http처리를 webChessController로 렌더링 클래스는 webOutputView로 책임을 분리했습니다!

2022-04-13 06:54 UTC, hyunrrr commented on src/main/java/chess/controller/ChessController.java
> +    private static final int GAME_ID = 0;
game_id는 사실 현재 제 코드에선 도메인 로직에 필요없는 id입니다. 4, 5단계 필수요구사항까지만 고려하고 코드를 작성했는데 db테이블 설계할때 현재차례와 체스말 위치를 엮어줄 키가 필요했습니다. 이를 위해 game_id라는 값을 사용하게 되었습니다. 아직까진 체스게임을 하는 플레이어가 1명이라 생각했고 view에서 게임 id를 입력받는 것이 과하다 생각했습니다. 우선은 controller에서 id를 상수로 선언해주었고 추후 요구사항이 확장되면 view에서 사용자로 부터 입력받거나 player에 대한 테이블을 추가로 만들고 사용자에 따라 유일한 id를 자동으로 맵핑해주도록 확장하려 했습니다.

2022-04-13 06:54 UTC, hyunrrr commented on src/main/java/chess/dao/DbBoardDao.java
> +public class DbBoardDao {
그렇군요!! db라는 이름을 삭제하거나 storage로 모두 수정했습니다!!!

2022-04-13 06:56 UTC, hyunrrr commented on src/main/java/chess/dao/DbBoardDao.java
> +    public Connection getConnection() {
이 부분은 제가 고민해보지 않고 습관처럼 작성했네요... connection의 접근제어자를 private으로 수정하고 테스트를 삭제했습니다!

2022-04-13 06:58 UTC, hyunrrr commented on src/main/java/chess/dao/DbBoardDao.java
> +        saveAll(gameId, chessBoardDto.getMapInformation());
그렇군요!! 여기까지는 생각하지 못했습니다!! mapInformation을 boardData와 같은 네이밍으로 변경했습니다!

2022-04-13 07:02 UTC, hyunrrr commented on src/main/java/chess/dao/DbBoardDao.java
> +    public ChessBoardDto findAll(int gameId) {
주신 피드백을 보고 dto를 돌아보니 굳이 썼다는 느낌이 드네요.. 여러 데이터타입을 묶어야 하는 dto를 제외하고는 모두 삭제했습니다!!
현재는 보드의 데이터(int column, int row, String chessPieceType)를 묶은 dto와 게임 데이터(int gameId, String turn)를 묶은 dto만 사용하고 있씁니다!!
이 dto를 안쓰기에는 메서드가 너무 나눠져(column을 가져오는 메서드, row를 가져오는 메서드가 분리됨) 위 dto들은 사용하기로 했습니다.

2022-04-13 07:15 UTC, hyunrrr commented on src/main/java/chess/dao/DbGameDao.java
> +    static {
우선은 dao가 아니라 storageService에서 하도록 책임을 옮겼습니다..
근데 이 부분에 대한 의문이 하나 있는데 체스말을 db와 consoleView에서 모두 알파벳(ex.흰색pawn -> p)으로 표현합니다.
db와 consoleView는 서로 다른 모듈이니 코드가 좀 중복되더라도 따로 있는것이 맞다는 생각과
코드중복은 악의 근원이라는 생각이 서로 충돌하는데... 코드가 중복되더라도 각각 다른 패키지에 체스말을 알파벳으로 변환하는 객체를 만드는게 맞을까요?

2022-04-13 07:16 UTC, hyunrrr commented on src/main/java/chess/domain/ChessBoard.java
> +    public void initFromDb(GameInformationDto gameInformationDto, ChessBoardDto chessBoardDto) {
db, dto에 대한 처리는 모두 컨트롤러에서 하도록 변경했습니다!!!!

2022-04-13 07:16 UTC, hyunrrr commented on src/main/java/chess/domain/ChessGame.java
> +import chess.dto.ChessBoardDto;
그렇군요!! 도메인에서 데이터를 받고 필요한 경우 컨트롤러에서 dto를 만들도록 수정했습니다!!

2022-04-13 07:22 UTC, hyunrrr commented
구구 안녕하세요!!! 피드백 반영이 늦어져서 죄송합니다.. 주신 피드백을 보고 제 코드를 봤는데.. 많이 암울하더라고요... 나름 고민해서 최대한 반영해보았습니다!! 아직 제 코드가 마음에 들지 않아 속상하지만 남은 방학동안 열심히 고민하고 고쳐보겠습니다!!! 코딩하는게 그렇게 싫지만은 않네요.. 고민하다보니 한번 바꿔보고 싶은 부분이 있지만 혼자 너무 오래 고민하다 더 중요한 부분을 놓칠까봐 우선 리뷰요청합니다!!! 혹시 제가 놓친 부족한 부분 있으면 말씀해주시면 감사드리겠습니다!!! 피드백 감사합니다!!!!

2022-04-14 02:41 UTC, kang-hyungu commented on src/main/java/chess/WebApplication.java
> +    private static String doInGameCommand(Response res, ChessGame chessGame, DbService dbService, List<String> inputs) {
레벨2에서 시간을 갖고 더 고믾해보면 좋을 것 같네요

2022-04-14 02:44 UTC, kang-hyungu commented on src/main/java/chess/WebApplication.java
> +        return null;
dto는 단순 값을 전달하는 용도로 사용하세요.
그리고 상황에 따라 empty 필드가 필요하면 써야겠죠. 보통은 없을 테구요.
null을 방지하기 위해 optional을 쓰는 것이니 참고하세요.
optional을 변수로 두라는 소리는 아닙니다. optional의 orElse 시리즈를 잘 활용하라는 소리입니다.

2022-04-14 02:44 UTC, kang-hyungu commented on src/main/java/chess/WebApplication.java
> +    private static String doInGameCommand(Response res, ChessGame chessGame, DbService dbService, List<String> inputs) {
이것도 레벨2 학습하면서 더 고민해보시죠.

2022-04-14 02:45 UTC, kang-hyungu commented on src/main/java/chess/dao/DbBoardDao.java
> +        saveAll(gameId, chessBoardDto.getMapInformation());
Data라는 단어를 보면 어떤게 떠오르나요?
구체적인 대상이 떠오르지 않는 건 동일하겠군요.

2022-04-14 02:47 UTC, kang-hyungu commented on src/main/java/chess/dao/DbGameDao.java
> +    static {
비즈니스 로직이라는 관심사와 db, view 같은 기술적 관심사를 섞어서 고민하고 있네요.
이것도 레벨2 학습하면서 좀더 고민해보면 좋을 것 같습니다.

2022-04-14 02:47 UTC, kang-hyungu approved these changes
조시 피드백 반영하느라 고생하셨어요.
pr은 머지 처리하겠습니다. 수고하셨습니다.

2022-04-14 02:47 UTC, merged