[4, 5단계 - 체스] 소주캉(강승주) 미션 제출합니다.
woowacourse/java-chess pull request #414
Opened 2022-04-07 06:55 UTC by sojukang

안녕하세요 `앨런`!!!! 다시 리뷰 신청 드리는 `소주캉`입니다👋👋.
기본적으로 1차 머지 단계의 피드백을 반영하고 웹, DB 기능을 추가하였습니다. 
5단계(DB)는 백, 흑 사용자의 이름을 입력 받아 이를 기준으로 저장, 불러오기, 초기화가 가능하도록 하였습니다. 
테이블 설계는 다음과 같습니다 
```sql
create table game
(
    id int not null,
    id_white_player   varchar(20) not null,
    id_black_player   varchar(20) not null,
    turn varchar(10) not null,
    primary key (id)
);

create table board
(
    id int not null AUTO_INCREMENT,
    game_id   int not null,
    position   varchar(20) not null,
    piece   varchar(20) not null,
    primary key (id),
    foreign key (game_id) references game (id)
);
```

미션 중 특이점은 다음과 같습니다.
1. 5단계를 구현할 때도 TDD를 시도하였는데, PK와 FK로 연관된 엔티티를 테스트할 경우 단위 테스트가 어려워지는 문제점이 있었습니다🤔😭.
2. `controller` 계층에서 Dao에 직접 접근하지 않게 하기 위해 `Service`를 도입해보았는데, 전반적으로 마음에 들지 않지만 더 나은 개선을 위한 경험이 부족하여 막힌 상태입니다😭.

요즘 건강이 위협 받을 수 있는 상황이 많은데, 무탈하시기를 바라며 이번 리뷰도 잘 부탁드립니다👍👍👻

2022-04-08 08:27 UTC, hongbin-dev commented
> 5단계를 구현할 때도 TDD를 시도하였는데, PK와 FK로 연관된 엔티티를 테스트할 경우 단위 테스트가 어려워지는 문제점이 있었습니다 

이 부분은 예를들면 어떤 클래스에서 어떤 테스트하기 어려우셨나요?

2022-04-08 08:28 UTC, hongbin-dev requested changes
안녕하세요 소주캉! 
4, 5단계 미션 진행하시느라 고생많으셨습니다!
몇 가지 개선하면 좋을 점과 질문 코멘트 남겼습니다. 확인부탁드려요~

2022-04-08 08:28 UTC, hongbin-dev commented on docker/db/mysql/init/init.sql
> +drop table game;
이 부분은 왜 들어가는걸까요?

2022-04-08 08:28 UTC, hongbin-dev commented on src/main/java/chess/Game.java
> +    }
게임의 id를 위 코드처럼 정해주고있는데요. 충돌의 위험성, 성능이 잘 안나올 것 같은데요.
다른 방식으로 식별자를 정하는게 좋아보입니다.

2022-04-08 08:28 UTC, hongbin-dev commented on src/main/java/chess/controller/WebChessController.java
> +        end();
스파크에 path라는 메서드가 존재하는데, 여기에 라우트그룹을 등록할 수 있어보여요~

2022-04-08 08:28 UTC, hongbin-dev commented on src/main/java/chess/controller/WebChessController.java
> +            return render(model, "index.html");
모델이 없을 때, 편의 메서드를 만들면 좋을 것 같습니다~

2022-04-08 08:28 UTC, hongbin-dev commented on src/main/java/chess/controller/WebChessController.java
> +                model.put("error", e.getMessage());
예외가 발생했을 때, 메시지를 뷰에 전송하고 있는데요. 그대로 내리는게 좋은방법인지 고민해보면 좋을 것 같습니다.

2022-04-08 08:28 UTC, hongbin-dev commented on src/main/java/chess/controller/WebChessController.java
> +            return render(Map.of(), "index.html");
서비스에서 delete와 init을 나누신 이유가 있을까요?

2022-04-08 08:28 UTC, hongbin-dev commented on src/main/java/chess/controller/WebChessController.java
> +    }
매번 HandlebarsTemplateEngine 객체를 생성하고있는데, 재사용할 수 있는 구조로 갈 수 있을까요?

2022-04-08 08:28 UTC, hongbin-dev commented on src/main/java/chess/dao/BoardDao.java
> +public interface BoardDao {
👍

2022-04-08 08:28 UTC, hongbin-dev commented on src/main/java/chess/dao/BoardDao.java
> +public interface BoardDao {
인터페이스 분리 좋네요!

2022-04-08 08:28 UTC, hongbin-dev commented on src/main/java/chess/dao/BoardDao.java
> +    void save(int gameId, Map<String, String> StringPieceMapByPiecesByPositions);
파라미터 네이밍을 신경써주면 좋을 것 같아요.
또 Map<String, String>형태로 파라미터로 보내는 이유가 있을까요? board를 그대로 넘길 수 있을 것 같은데요

2022-04-08 08:28 UTC, hongbin-dev commented on src/main/java/chess/dao/BoardDaoImpl.java
> +        }
만약 커넥션을 얻지못하면 비즈니스가 어떻게 흐르게되나요?

2022-04-08 08:28 UTC, hongbin-dev commented on src/main/java/chess/dao/GameDaoImpl.java
> +    private final Game game;
DAO에 상태를 갖게한 이유가 있을까요?
만약 서버를 여러 개 띄운다면 문제가 발생할 것 같아요.

2022-04-08 08:28 UTC, hongbin-dev commented on src/main/java/chess/dao/GameDaoImpl.java
> +        return connection;
커넥션코드가 응집되지 않는 것 같아요. 재활용할 수 있는 방법이 없을까요?



---

```suggestion
        try {
           return  DriverManager.getConnection(URL, USER, PASSWORD);
        } catch (SQLException e) {
          throw....
        }
```
또 이런식으로하면 불필요한 null할당은 피할 수 있을 것 같아요

2022-04-08 08:28 UTC, hongbin-dev commented on src/main/java/chess/dao/GameDaoImpl.java
> +    }
Data Access Object인데요. id를 꺼내는요청이 왜 필요할까요?

2022-04-08 08:28 UTC, hongbin-dev commented on src/main/java/chess/dao/GameDaoImpl.java
> +    public List<String> findById(int id) {
식별자로 id를 찾으면 1건만 나올 것 같은데요. List로 반환하는 이유가 있을까요?

2022-04-08 08:28 UTC, hongbin-dev commented on src/main/java/chess/service/ChessGameService.java
> +    private ChessGame chessGame;
ChessGame를 상태로 둔 이유가 있을까요?
DAO와 같은이유로 서버를 확장하면 문제가 생길 것 같습니다.

2022-04-08 08:28 UTC, hongbin-dev commented on src/main/java/chess/service/ChessGameService.java
> +    }
GameDao를 생성자로 받긴 어려울까요?

2022-04-11 08:38 UTC, sojukang commented on docker/db/mysql/init/init.sql
> +drop table game;
초기화 할 때 기존 같은 이름의 테이블을 지우고 만드려는 명령이었는데 맨 위로 옮겨주었습니다!

2022-04-11 08:39 UTC, sojukang commented on src/main/java/chess/Game.java
> +    }
아하!! 이 부분은 새로 생성할 때 기존 마지막 번호에서 1씩 더하는 걸로 바꿔보았습니다. 감사합니다.

2022-04-11 08:39 UTC, sojukang commented on src/main/java/chess/controller/WebChessController.java
> +        end();
path 메서드에 한번에 라우트 그룹들을 등록하니까 훨씬 깔끔하군요!! 감사합니다🌟

2022-04-11 08:40 UTC, sojukang commented on src/main/java/chess/controller/WebChessController.java
> +            return render(model, "index.html");
`renderWithNoModel`을 새로 만들어보았습니다. 감사합니다👍

2022-04-11 08:41 UTC, sojukang commented on src/main/java/chess/controller/WebChessController.java
> +                model.put("error", e.getMessage());
감사합니다!! 예외 메시지를 뷰에 그대로 내리는 것에서 일반적인 예외 메시지로 바꾸어 보내는 것으로 변경해보았습니다.

2022-04-11 08:42 UTC, sojukang commented on src/main/java/chess/controller/WebChessController.java
> +            return render(Map.of(), "index.html");
`init`은 초기에 DB 에서 저장된 데이터를 불러와서 초기화 하는 등 목적이 있어서 delete와 사용 맥락이 항상 같지는 않아서 분리해두었습니다!!

2022-04-11 08:42 UTC, sojukang commented on src/main/java/chess/controller/WebChessController.java
> +    }
`render`를 담당하는 `RenderEngine` 클래스를 따로 분리해보았습니다. 감사합니다👍

2022-04-11 08:46 UTC, sojukang commented on src/main/java/chess/dao/BoardDao.java
> +    void save(int gameId, Map<String, String> StringPieceMapByPiecesByPositions);
😭😭 이건 해결해보려고 노력을 많이 해보았는데  Map<Position, Piece>을 그대로 넘겨서 웹에 표시할 수 있는 방법을 아직 더 공부해봐야할 것 같습니다 😭.

2022-04-11 08:48 UTC, sojukang commented on src/main/java/chess/dao/BoardDaoImpl.java
> +        }
Connection 관련 역할을 `JdbcConnection`으로 분리하여 커넥션을 얻지 못하면 예외를 던지도록 해보았습니다.

2022-04-11 08:48 UTC, sojukang commented on src/main/java/chess/dao/GameDaoImpl.java
> +    private final Game game;
Dao에서 상태를 전부 제거해보았습니다. 감사합니다👍

2022-04-11 08:49 UTC, sojukang commented on src/main/java/chess/dao/GameDaoImpl.java
> +        return connection;
위의 내용처럼 변경하고 객체를 분리해보았습니다. 감사합니다!!!

2022-04-11 08:50 UTC, sojukang commented on src/main/java/chess/dao/GameDaoImpl.java
> +    }
dao가 상태를 가지니 이상한 메서드들이 생겼군요😥 삭제해보았습니다.

2022-04-11 08:50 UTC, sojukang commented on src/main/java/chess/dao/GameDaoImpl.java
> +    public List<String> findById(int id) {
역시 삭제해보았습니다!!

2022-04-11 08:50 UTC, sojukang commented on src/main/java/chess/service/ChessGameService.java
> +    private ChessGame chessGame;
위와 같이 상태를 가지지 않도록 해보았습니다!!!

2022-04-11 08:51 UTC, sojukang commented on src/main/java/chess/service/ChessGameService.java
> +    }
생성자로 받도록 변경해보았습니다. 감사합니다!!!🌟

2022-04-11 09:02 UTC, sojukang commented
안녕하세요 `앨런`!!!👋👋
한 번에 파악하기 힘들고 코드도 많은 체스 미션을 리뷰하시느라 너무 힘드실 것 같아서 죄송스럽습니다😥😥.
그럼에도 정말 도움이 되는 리뷰 남겨주셔서 감사드립니다👍👍👍.
기본적으로 남겨주신 피드백을 바탕으로 수정해보았습니다. 

앞서 드린 질문에서 테스트가 어려웠던 점은 `board` 테이블이 `game` 테이블의 `id`를 `FK`로 가지고 있어 `game`에서 임의로(단독으로) 테이블을 삭제하거나 수정하기 어려워서 발생했던 문제였습니다🧐.

이번 리팩토링에서는 `Service`가 가지는 상태를 밖으로 꺼내서 Controller에서 `ChessGame`을 조작하고 `Service`는 DB 조작에 관련된 부분을 처리하도록 해보았습니다. 그런데 `controller`의 각 메서드에서 이를 이용하려면 인스턴스 변수로 가지는 방법 외에는 마땅한 방법이 안 떠오르더라구요...😥. 아직 경험이 미천하여 힌트를 못 잡고 있는데 어떤 방법이 있을까요..??🧐

아직 코로나가 수그러들지 않아 세상이 혼란한데 부디 건강하시고 리뷰 잘 부탁드립니다🌟🌟!!

2022-04-14 04:09 UTC, hongbin-dev commented
안녕하세요 소주캉~

> 이번 리팩토링에서는 Service가 가지는 상태를 밖으로 꺼내서 Controller에서 ChessGame을 조작하고 Service는 DB 조작에 관련된 부분을 처리하도록 해보았습니다. 그런데 controller의 각 메서드에서 이를 이용하려면 인스턴스 변수로 가지는 방법 외에는 마땅한 방법이 안 떠오르더라구요...😥. 아직 경험이 미천하여 힌트를 못 잡고 있는데 어떤 방법이 있을까요..??🧐

서버는 일반적으로 무상태여야합니다. 도메인객체를 서버상태에 공유하면, 여러명이 접속했을 때 같은 객체를 사용하게 될 것 같아요.
매 요청시 Service에서 영속된 데이터를 꺼내고, 비즈니스를 실행시키는게 자연스러울 것 같네요

추가로, DAO에서 비즈니스가 들어가는 부분이 있는데요. DAO는 Data Access Object인데요. 단순 하나의 데이터를 요청한다고 생각하고 비즈니스를 작성해주셨으면 좋겠어요. 코드처럼 findById인데, id가 없으면 새로 생성하는 2가지역할은 피하셨으면 좋겠네요. (이 부분은 네이밍변경과 서비스에서 데이터의 흐름을 제어하면 좋겠어요)

2022-04-14 04:25 UTC, hongbin-dev requested changes
안녕하세요 소주캉~
피드백 반영해주신거 확인했습니다. 아직 모호한부분이 있으신 것 같아요. 관련된 곳에 코멘트 남겼습니다
또 개선하면 좋을 점 남겨봤는데요. 천천히 고민해보시면 좋을 것 같아요.
체스미션 고생많으셨습니다  머지할게요👍

2022-04-14 04:25 UTC, hongbin-dev commented on docker/db/mysql/init/init.sql
> +drop table game;
이 부분도 매번 삭제해야하는지 고민해보면 좋을 것 같습니다~
만약 실제운영하고있는 코드에 이게 들어간다면, 어떤 일이 일어날까요?

2022-04-14 04:25 UTC, hongbin-dev commented on src/main/java/chess/controller/RenderEngine.java
> +    }
👍

2022-04-14 04:25 UTC, hongbin-dev commented on src/main/java/chess/controller/WebChessController.java
> +            chessGame = service.init(game.getId(), new Turn(game.getTurn()), new DefaultArrangement());
컨트롤러가 무거운 것 같습니다. 비즈니스의 흐름은 Service에 맡기는게 좋을 것 같아요.

2022-04-14 04:25 UTC, hongbin-dev commented on src/main/java/chess/controller/WebChessController.java
> +                game.nextTurn();
코멘트에 남긴 것 처럼, 도메인객체를 공유하게되면 문제가 발생할 수 있어요.
Service를 통해서 영속된 객체를 가져와서 비즈니스를 실행시켜주세요~

2022-04-14 04:25 UTC, hongbin-dev commented on src/main/java/chess/controller/WebChessController.java
> +            model.put("score", chessGame.getScore());
여기도 마찬가지네요~

2022-04-14 04:25 UTC, hongbin-dev commented on src/main/java/chess/controller/WebChessController.java
> +            chessGame = service.init(game.getId(), new Turn(), new DefaultArrangement());
이쪽도 비즈니스의 흐름이 컨트롤러에 있군요! 서비스로 위임해볼 수 있을 것 같아요.

2022-04-14 04:25 UTC, hongbin-dev commented on src/main/java/chess/dao/GameDaoImpl.java
> +        new BoardDaoImpl().deleteById(id);
Dao는 데이터액세스에 집중해주세요. 이 부분은 서비스에서 조합해서 사용하는게 좋을 것 같습니다.
사용자 입장에서 GameDao로 Game을 삭제하는데, Board가 삭제되는지는 파악이 어려울 것 같네요

2022-04-14 04:25 UTC, hongbin-dev commented on src/main/java/chess/dao/GameDaoImpl.java
> +        String sql = "delete from game where id = " + "'" + id + "'";
이렇게 쿼리를 작성하시면 SQL 인젝션공격에 취약합니다. 위처럼 대표적인 방어방법인 PreparedStatement를 사용하시는걸 추천드려요.

https://ko.wikipedia.org/wiki/SQL_%EC%82%BD%EC%9E%85

2022-04-14 04:25 UTC, hongbin-dev commented on src/main/java/chess/dao/GameDaoImpl.java
> +        new BoardDaoImpl().deleteById(id);
```suggestion
        new BoardDaoImpl().deleteByGameId(id);
```
또 이런식으로 짓는게 좋지않을까요? 혹시 둘의 id가 같은가요?

2022-04-14 04:25 UTC, hongbin-dev commented on src/main/java/chess/dao/GameDaoImpl.java
> +    }
예외가 발생하면 null이 리턴되나요? 이런 정상적인 값이 아닌, **대체 값**은 모두 제거해보면 좋을 것 같아요.

2022-04-14 04:25 UTC, hongbin-dev commented on src/main/java/chess/dao/GameDaoImpl.java
> +            return "WHITE";
값이 없을 때, WHITE가 반환되는걸로 확인했는데요. 이건 DAO 비즈니스를 갖고 있는겁니다. 
이 부분은 서비스에서 행해주는게 좋을 것 같아요.

2022-04-14 04:25 UTC, hongbin-dev commented on src/main/java/chess/dao/GameDaoImpl.java
> +        } catch (SQLException e) {
find인데 신규 아이디를 반환하고있어요. 두 가지 일을 하고있고, 네이밍만 보면 이해가 어렵네요
DAO에서 insert하는 로직과 찾는로직을 분기하시고, Service에서 비즈니스를 합치는걸 추천드려요.

2022-04-14 04:25 UTC, hongbin-dev commented on src/main/java/chess/dao/JdbcConnection.java
> +    }
커넥션을 한번 맺고 쭉 유지되는데요. 이렇게 했을 때 어떤 단점이 있을지 생각해보면 좋을 것 같네요.

2022-04-14 04:25 UTC, merged

2022-04-14 04:28 UTC, hongbin-dev commented
3-tier 아키텍처로 컨트롤러/서비스/영속계층을 나눠주신 것 같은데요.
각각의 컴포넌트가 어떤 책임이 있는지 찾아보시면, 코드작성하시는데 도움이 될 것 같아요. 고생많으셨어요 🙂