[4, 5단계 - 체스] 슬로(이한울) 미션 제출합니다.
woowacourse/java-chess pull request #421
Opened 2022-04-07 08:20 UTC by hanull

2022-04-07 14:32 UTC, heebong requested changes
안녕하세요, 슬로! 리뷰어 희봉입니다. 😄 
웹과 db를 추가해주셨네요 👍 아직 move url이 없어 완벽하진 않지만 도메인의 큰 변화 없이 기능을 추가할 수 있을 것 같아요 🙂 
몇가지 내용을 코멘트로 남겼어요. 확인 부탁드립니다. (그리고 해당 피드백이 move url 기능을 추가할 때 도움이 되면 좋겠네요.) 그럼 다음 리뷰요청 기다리겠습니다~!

2022-04-07 14:32 UTC, heebong commented on src/main/java/chess/domain/ChessMap.java
>      private static char[][] initializeChessMap() {
`ChessMap.of()`에 대한 테스트가 있으면 좋겠네요 🙂

2022-04-07 14:32 UTC, heebong commented on src/main/java/chess/service/ChessGameService.java
> +    private ChessGame chessGame;
`ChessGame` 코드에 댓글을 남길 수가 없네요. 여기에 대신 남기겠습니다. 😂 
`ChessGame.move()`의 리턴값이 필요할까요? 현재 리턴값이 사용되지 않네요. 만약 테스트를 위한거라면 `getPlayer()`를 사용해 `Player` 값을 검증하면 될 것 같아요.

advanced 🆙 `명령-쿼리 분리 원칙`에 대해 알아봅시다. 🙂

2022-04-07 14:35 UTC, heebong requested changes
안녕하세요, 슬로! 리뷰어 희봉입니다. 
리퀘스트 체인지를 눌렀는데 알림이 안갔네요ㅎㅎ
위의 코멘트 확인 부탁드립니다!

2022-04-14 12:50 UTC, hanull commented on src/main/java/chess/controller/WebChessGameController.java
> +    public void run() {
넵 그때 체스말이 안움직여서 제외하고 요청드렸어요..ㅎㅎ 이제 드디어 움직인답니다 😁

2022-04-14 12:54 UTC, hanull commented
안녕하세요 희봉!
처음에 구현하지 못했던 체스 저장, 불러오기, 이동 기능 구현했어요.
아직 테스트 코드가 많이 부족해서 이후에 추가해볼게요! 감사합니다 😀

2022-04-15 09:37 UTC, heebong approved these changes
안녕하세요, 슬로! 리뷰어 희봉입니다 😄 
체스 미션 구현하느라 고생하셨어요 👍  도메인 코드를 많이 수정하지 않고 웹 컨트롤러를 잘 적용했네요.
이번 미션은 머지하도록 하겠습니다. 추가로 생각해보면 좋을 내용을 코멘트로 남겼으니 확인 부탁드려요.
얼마 남지 않은 방학 잘 보내시고 다음 레벨에서 만나요~ ✋

2022-04-15 09:37 UTC, heebong commented on src/main/java/chess/service/ChessGameService.java
> +    public ChessGameService(ChessGameDao chessGameDao) {
생성자주입 👍

2022-04-15 09:37 UTC, heebong commented on src/main/java/chess/domain/ChessGame.java
> +    public static ChessGame of(final ChessGameUpdateDto gameUpdateDto) {
`ChessGameUpdateDto`는 `ChessGameDao`에서 사용하는 `dto`로 보입니다. 그런데 `ChessGame`이 해당 `dto`를 의존하고있네요. 맞는 의존방향일지 확인해보면 좋겠습니다. 👀

2022-04-15 09:37 UTC, heebong commented on src/main/java/chess/domain/player/Player.java
> +    private static List<Piece> toPieces(final List<PieceDto> piecesDto) {
`Player`도 `PieceDto`를 의존하는게 맞는 방향일지 고민해보면 좋겠습니다. 🙂

2022-04-15 09:37 UTC, heebong commented on src/main/java/chess/domain/player/Player.java
> +    private static Piece createPieceByState(State state, Position position) {
`State`가 늘어나면 여기 if문도 늘어나야 할 것 같아요. `State`와 `Piece`가 같은 패키지에 위치하고 있어 `new Piece()`를 하는 부분을 `State`에게 위임해도 괜찮을 것 같아요. 여러 방법으로 생각해봅시다 🙂

2022-04-15 09:37 UTC, merged