[4, 5단계 - 체스] 필즈(조성우) 미션 제출합니다.
woowacourse/java-chess pull request #426
Opened 2022-04-07 08:52 UTC by progress0407

`닉`~! 

안녕하세요 `필즈`에요 !

사실은 아직 온전한 완성이 되지는 않았지만 부분 완성된 결과물을 올립니다... 하하 (...)

조금씩 다시 작성하여서 올릴게요 ... ㅎㅎ,,

---

## 현재 된 것들

### Position 내부에서 컬렉션으로 `캐싱`

> https://github.com/woowacourse/java-chess/pull/343#discussion_r836559632

### UI와 Spark 연결

- 서버로부터 기물을 불러와서 초기 체스보드 세팅
- 체스 기물을 움직이는 화면
- 현재 팀이 누군지를 보여주는 기능
- 사용자를 저장하는 화면

### 아직 구현하지 못한 것들

- 체스 상태를 저장하고 불러오는 기능
- 여러가지 저장된 상태 중에서 하나의 게임을 불러오는 기능
- UI 를 UI 스럽게 가다듬기 (...)

2022-04-09 00:29 UTC, wbluke requested changes
구현해주신 부분 잘 봤습니다 ㅎㅎ
몇 가지 개선해보면 좋을 부분들 코멘트 남겼으니 참고 부탁드려요 🙂

2022-04-09 00:29 UTC, wbluke commented on src/main/java/chess/dao/DbUserDao.java
> +            PreparedStatement statement = connection.prepareStatement(sql);
`try-with-resources` 구문을 사용해서 자원을 해제해 봅시다 :)

2022-04-09 00:29 UTC, wbluke commented on build.gradle
> +    runtimeOnly 'mysql:mysql-connector-java:8.0.28'
설계하신 테이블 구조 sql 파일은 없을까요?

2022-04-09 00:29 UTC, wbluke commented on src/main/java/chess/dao/Dao.java
> +public abstract class Dao {
중복 제거를 위한 추상클래스 시도는 좋습니다 ㅎㅎ
하지만 애플리케이션이 발전할수록 2개 이상의 데이터베이스를 사용할 수도 있고, 그에 따라 다른 환경의 커넥션을 가져와야 할 수도 있기 때문에 현 단계에서는 상속보다는 커넥션을 제공하는 정적 클래스로 분리해보는 게 좋을 것 같아요 :)
(나중에 Spring에서는 yml 파일이나 AWS 파라미터 스토어 등으로 접속 정보 등을 별도 관리하고 커넥션을 맺을 수 있어요)

2022-04-09 00:29 UTC, wbluke commented on src/main/java/chess/domain/board/position/Position.java
> +        if (findPosition == null) {
아래에서 null을 리턴하고 다시 null 체크를 하고 있는데, 차라리 Optional 그대로 리턴하고 Optional의 API를 사용하는 게 좋아보이네요 ㅎㅎ
얘기가 나온 김에 Optional의 올바른 사용법은 아래 포스팅 참고해 보세요 :)
https://homoefficio.github.io/2019/10/03/Java-Optional-%EB%B0%94%EB%A5%B4%EA%B2%8C-%EC%93%B0%EA%B8%B0/

2022-04-09 00:29 UTC, wbluke commented on src/main/java/chess/dto/response/StateResponse.java
> +        }
https://tecoble.techcourse.co.kr/post/2021-04-26-instanceof/
참고해 봅시다 :)

2022-04-09 00:29 UTC, wbluke commented on src/test/java/chess/dao/DbUserDaoTest.java
> +    }
- `@BeforeEach` : 테스트 각각 실행 전
- `@AfterAll` : 모든 테스트 이후

굳이 이 두 과정에서 모두 User를 지워줄 필요는 없을 것 같아요.
2개 대신 `@AfterEach`만 있으면 각 테스트가 끝날 때마다 데이터 클렌징을 할 수 있습니다.
각 테스트에서 사용하는 User 데이터도 매번 다르게 만들지 않아도 되고요 ㅎㅎ

2022-04-09 00:29 UTC, wbluke commented on src/test/java/chess/dao/DbUserDaoTest.java
> +    private static final DbUserDao userDao = new DbUserDao();
정적이어야 하는 이유가 있나요? :)

2022-04-09 00:29 UTC, wbluke commented on src/test/java/chess/dao/DbUserDaoTest.java
> +        assertThat(Users.size()).isEqualTo(1);
```suggestion
        assertThat(users).hasSize(1);
```

변수명 대문자도 유의해 주세요 :)

2022-04-18 16:41 UTC, progress0407 commented on src/test/java/chess/dao/DbUserDaoTest.java
> +    }
아.. ㅎㅎ 친절한 설명 감사합니다 ㅎㅎ

사실 저게 클렌징을 테스트 전후로 지워주기 위해서 하고자 저렇게 했었던 부분이었었거든요,

다만 테스트 실행전에는 각각 테스트 메서드에서 한 번씩 모두 지운 후

모든 테스트가 끝났을 때, 테스트 데이터가 남아있을 수도 있으니 그에 대한 부분도 지워주는 것을 염두해 두고

설계했습니다.. :)

> 다만 실제 프로덕션에서 사용하는 `DB`를 연결해놓았으니 ㅠㅠ 실제 데이터도 지워진다는 함정이 있네요...

2022-04-18 16:42 UTC, progress0407 commented on src/main/java/chess/dto/response/StateResponse.java
> +        }
맞습니다..ㅎㅎ 사실 이 얘기가 나올 줄 알았는데.. 저때 시간관계상 못했었던 기억이 있네요 ...

체크했습니다 !

2022-04-18 16:45 UTC, progress0407 commented on src/main/java/chess/WebApplication.java
>      public static void main(String[] args) {
컨트롤러 추출...!!  체크 완료

2022-04-19 02:09 UTC, progress0407 commented on src/main/java/chess/WebApplication.java
> +            inGameUser.put("blackUser", blackPlayer);
아.. 이부분은 기억해두겠습니다 :)
제가 당장은 못할 것 같지만... 비즈니스 로직을 도메인 혹은 서비스에 둔다. 알겠습니다 :)

2022-04-19 02:51 UTC, progress0407 commented on src/main/java/chess/dao/Dao.java
> +public abstract class Dao {
아아.. 정적 클래스로 전환하고 커넥션을 제공하는 유틸 클래스로의 전환을 말씀하신거군요.. ㅎㅎ 한번 바꾸어볼게요

2022-04-19 02:51 UTC, progress0407 commented on build.gradle
> +    runtimeOnly 'mysql:mysql-connector-java:8.0.28'
곧 넣겠습니다 ㅎ

2022-04-19 05:05 UTC, merged

2022-04-23 11:20 UTC, progress0407 commented on src/test/java/chess/dao/DbUserDaoTest.java
> +    private static final DbUserDao userDao = new DbUserDao();
음 사실 저게 한 번만 생성되기만 하면 된다는 생각에 정적으로 생성했었네요 !