[1,2단계 - 체스] 리오(오영택) 미션 제출합니다.
woowacourse/java-chess pull request #431
Opened 2023-03-15 13:12 UTC by Jaeyoung22

안녕하세요 빙봉! 이번에 리뷰를 받게 된 리오라고 합니다! 잘 부탁드려요👍🏻

이번 미션을 진행하며 집중한 부분들과 질문들을 말씀드릴게요!

## 1. 속도와 품질
***
속도와 품질을 모두 챙기며 개발할 수 있는 실력을 갖추고 있다면 좋겠지만 아직 많이 부족합니다.
그러다보니 두 가치를 trade-off하는 상황이 계속 생기네요..
이번 미션에서는 꼭 1등으로 PR을 날려보고 싶어서 속도에 보다 집중했습니다.
그러다보니 품질면에서 "더 좋은 로직이 있을 것 같은데...?"라는 고민을 페어와 계속 했습니다.
마침 최근에 현직에 계시는 이전 크루분과 커피챗을 할 기회가 있었는데,
현업에서는 속도가 보다 중요한 상황들이 많다고 이야기를 들었습니다.
그래서 이번 미션에서, 위에 말한 상황에서는 "일단 돌아가게 해보자!"라는 모토로 빠르게 진행했습니다.
최종 미션 때 포비도 "일단 돌아가는 쓰레기를 만들어라!"라고 하셨던 기억이 있네요...

물론 두 가치를 전부 챙기는 개발자가 되어야겠지만,
빙봉이 생각하기에는 현재 미션에서는 어디에 더 중점을 두어서 학습과 연습을 해야한다고 생각하실까요?

## 2. 더 좋은 로직과 구현 방법을 판단하는 법 & 떠올리는 법
***
오늘까지도 많은 크루들이 서로의 로직을 공유하며 더 좋은 로직을 찾아가고 있고, 저희도 많은 크루들과 이야기를 나누었습니다.
논의된 많은 로직이나 구현 방법 중에, 제가 느끼기에는 성능이나 합리성의 면에서 비슷하다고 느껴지는 것들이 많았는데요,
아무래도 체스라는 상당히 복잡한 도메인 로직을 가진 게임을 구현하기 때문에 굉장히 다양한 방법들이 존재하는 것 같습니다.
이러한 로직과 구현 방법들 중에서, 어떤 것이 더 좋은 것인지 판단하는 기준을 가져야 할 것 같은데
아직은 그러한 기준이 부족한 것 같아요.
어떤 방법들이 이런 기준을 세우는 데에 도움이 될까요?
빙봉은 어떤 방식으로 이런 기준을 잡아나가셨나요?

## 3. View의 역할과 책임
***
요구사항 중에 기물의 이름을 대문자와 소문자로 콘솔에 찍는 것이 있었습니다.
저희는 이것이 view의 역할이라고 생각했고, 그래서 view에서 각 기물이 Piece라는 추상클래스의 어떤 구현체인지
확인할 수 있도록 했고, 그에 따라서 출력을 했습니다.
그러다보니 도메인 내에서 (더 좋은 방법이 있겠지만) 초기에 말들을 각 칸에 올려놓는 메서드가 굉장히 길어지게 되었습니다.
["r", "n", "b", ...] 처럼 초기 기물들이 콘솔에 찍히는 문자로 리스트를 만들어서 여기에 맞게 기물들을 넣어주는 로직을 가진 크루의 코드도 확인했는데요,
저는 view에서 찍히는 내용을 도메인에서 사용하면 안된다고 생각해서 그냥 긴 메서드를 사용하게 되었습니다.
아직도 view의 역할과 책임에 대해서 혼동이 생기는 부분들이 있네요...
빙봉은 어떻게 생각하시나요?

리뷰해주셔서 감사합니다!! 다시 한 번 잘 부탁드릴게요!!

2023-03-18 04:46 UTC, aegis1920 requested changes
안녕하세요 리오! 빙봉입니다 🙂 

1등 PR이라 그런지 속도감이 느껴지는 코드였습니다ㅎㅎ
질문 답변 및 코멘트 남겼습니다. 확인 부탁드려요!

궁금한 점이 있다면 언제든 DM 주세요!

2023-03-18 04:46 UTC, aegis1920 commented on src/main/java/controller/ChessController.java
> +            chessService.execute(inputs);
execute() 메서드에서 isOngoing을 리턴해줘도 되지 않을까요? 그러면 isOngoing으로 체크할 필요없이 로직이 깔끔해질 것 같네요

2023-03-21 02:21 UTC, Jaeyoung22 commented on README.md
> +## ✨ 기능 구현 목록
반성합니다...

2023-03-21 02:27 UTC, Jaeyoung22 commented on README.md
`개인적인 의견을 조금 더 달아보자면 포인트를 둬야할 부분은 속도와 품질이 아닌 마감기한이라는 걸 인지하면 좋겠어요. 그런 의미에서 1등으로 PR을 날리는 것(속도)에 가치를 두기 보단 마감기한까지 속도와 품질을 어떻게 밸런스있게 맞출지에 가치를 두면 더 나은 개발자가 되지 않을까요? 🙂`
최고의 조언이네요... 꼭 명심해서 나은 개발자로 향해 가겠습니다! 감사합니다!!

질문이 너무 광범위했네요... 제가 궁금한 점조차 명확하지 않았어서 이런 질문을 드렸던 것 같습니다.
`본인만의 기준, 철학을 세우는데는 많은 시간이 걸릴 거예요. 저 또한 그렇고요. 지금처럼 크루들과 로직을 공유하고, 고민하고, 이야기를 나누고 그러다보면 자연스럽게 생기지 않을까요?`
그럼에도 불구하고 이런 좋은 답변을 남겨주셔서 감사해요! 빙봉과의 대화도 저만의 기준, 철학을 세우는 데에 큰 자양분이 될 거라는 확신이 듭니다! 감사해요!!

이해하신 부분이 맞습니다!
view에서 각 기물을 확인해야하다보니 각 기물을 나타내는 알파벳의 컬렉션(?) 등으로 간단하게 말을 초기화하는 방법들을 사용할 수 없더라구요.. 제가 말하면서도 잘 설명이 안되는 것 같네요ㅠㅜㅠ
앞으로는 코드에 커멘트를 미리 달아놓겠습니다!! 꿀팁 알려주셔서 감사해요^____^

2023-03-21 02:47 UTC, Jaeyoung22 commented on src/main/java/controller/ChessController.java
> +        if (Command.findRunCommand(command).equals(Command.START)
부끄럽네요...! 감사합니다!!

2023-03-21 05:45 UTC, Jaeyoung22 commented on src/main/java/controller/ChessController.java
> +            if (inputs.length != 1) {
하드코딩이 되었네요.. 부끄럽습니다ㅠㅠ 감사합니다!

2023-03-21 05:46 UTC, Jaeyoung22 commented on src/main/java/controller/ChessController.java
> +                throw new IllegalArgumentException("잘못된 입력입니다.");
그렇겠네요!!! 감사합니다!!

2023-03-21 07:07 UTC, Jaeyoung22 commented on src/main/java/controller/ChessController.java
> +        if (Command.findRunCommand(command).equals(Command.MOVE)) {
윽.. 부끄럽습니다.. 감사합니다!!

2023-03-21 07:07 UTC, Jaeyoung22 commented on src/main/java/controller/ChessController.java
> +            if (inputs[1].length() != 2 || inputs[2].length() != 2) {
그러니까요.. 왜 이렇게 했을까요...

2023-03-21 07:08 UTC, Jaeyoung22 commented on src/main/java/controller/ChessController.java
> +            String[] inputs = commandRequest.split(" ");
맞습니다!! 감사합니다!!

2023-03-21 07:45 UTC, Jaeyoung22 commented on src/main/java/domain/board/ChessBoard.java
> +        Rank BLACK_PAWN_RANK = Rank.SEVEN;
상수로 선언했다가 지역변수로 가져오면서 수정을 못했습니다ㅠㅜㅠ

혹시라도 나중에 룰이 바뀌어서 폰을 깔거나 하는 로직이 변경될 때 변경이 용이하도록 하기 위해서 선언했었는데, 없애는 것이 오히려 가독성이 좋아보일 것 같습니다!

2023-03-21 07:53 UTC, Jaeyoung22 commented on src/main/java/domain/board/ChessBoard.java
> +        List<Square> initialWhitePawnSquares = new ArrayList<>();
최근에 이펙티브 자바 아이템 46을 읽을 기회가 있었습니다.
종단연산인 forEach에서 외부인자인 board의 상태를 변경한다면 스트림을 스트림답게 사용한 것이 아니라고 생각했습니다!
그래서 반복문으로 넣어줬습니다!!

2023-03-21 07:54 UTC, Jaeyoung22 commented on src/main/java/domain/piece/Camp.java
> +public enum Camp {
Color보다는 진영이라는 뜻의 Camp를 사용해봤습니다!
혼동의 여지가 있을까요?

2023-03-21 07:55 UTC, Jaeyoung22 commented on src/main/java/domain/piece/Camp.java
> +    public Camp fetchOppositeCamp() {
앗 그렇군요! 조건 추가하겠습니다!! 감사해요!!

2023-03-21 07:58 UTC, Jaeyoung22 commented on src/main/java/domain/board/File.java
> +    public static File findFile(char value) {
그렇겠네요!!! 감사합니다~!~!

2023-03-21 07:58 UTC, Jaeyoung22 commented on src/main/java/service/ChessService.java
> +    }
맞습니다!! 리팩터링 했습니다!!!

2023-03-21 08:00 UTC, Jaeyoung22 commented on src/main/java/domain/board/ChessBoard.java
> +        return currentCamp.equals(board.get(currentSquare).getCamp());
와 그렇네요!!! 감사합니다!! 많이 배웁니다!!

2023-03-21 08:16 UTC, Jaeyoung22 commented on src/main/java/domain/piece/Piece.java
> +    public Piece(Camp camp) {
protected로 두면 되겠군요..!

2023-03-21 08:17 UTC, Jaeyoung22 commented on src/main/java/domain/board/ChessBoard.java
> +    public Square findSquare(String file, String rank) {
부끄럽습니다!! 넵!!

2023-03-22 05:18 UTC, Jaeyoung22 commented on src/main/java/domain/board/ChessBoard.java
> +        throw new IllegalStateException("움직일 수 없는 경로입니다.");
맞네요!! 각 기물에서 예외를 조금 더 구체화해서 던지도록 변경했습니다!
로직을 변경하면서 미처 확인을 못했던 것 같습니다ㅠㅠ 저도 IllegalArgumentException이라고 생각합니다!

2023-03-22 05:19 UTC, Jaeyoung22 commented on src/main/java/domain/piece/Piece.java
> +        if (camp.equals(Camp.BLACK) && otherCamp.equals(Camp.WHITE)) {
맞습니다!! 변경했습니다!!

2023-03-22 05:19 UTC, Jaeyoung22 commented on src/main/java/domain/piece/Piece.java
> +        return false;
그러게요ㅠㅠ

2023-03-22 05:21 UTC, Jaeyoung22 commented on src/main/java/service/ChessService.java
> +            throw new IllegalStateException("같은 진영의 말만 움직일 수 있습니다.");
오!! 그렇네요!!! 감사합니다!!

2023-03-22 05:21 UTC, Jaeyoung22 commented on src/main/java/service/ChessService.java
> +    }
안 쓰여서 부끄럽네요ㅠㅠ

2023-03-22 05:21 UTC, Jaeyoung22 commented on src/main/java/domain/piece/type/Empty.java
> +    private static class singleEmptyInstanceHolder {
헉!! 진짜 실수가 많네요 ㅠㅠ

2023-03-22 05:22 UTC, Jaeyoung22 commented on src/main/java/domain/piece/type/Empty.java
> +        public static final Empty INSTANCE = new Empty();
맞습니다!!

2023-03-22 05:23 UTC, Jaeyoung22 commented on src/main/java/service/ChessService.java
> +    }
그러게요 왜 저기 있을까요..

2023-03-22 05:23 UTC, Jaeyoung22 commented on src/main/java/domain/piece/type/Bishop.java
> +    private static final List<Direction> movableDirection = List.of(Direction.NORTH_EAST, Direction.NORTH_WEST,
얘는 왜 또 카멜케이스일까요..

2023-03-22 05:26 UTC, Jaeyoung22 commented on src/main/java/view/OutputView.java
저도 그렇게 생각합니다!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! 드디어..... 만났네요....
여태까지 전부 렌더링해서 뷰에 보내줬는데,
지난 미션 내내 도메인을 view에 넘겨도 된다고 생각하시는 리뷰어 분들이 계셔서 이번에는 처음부터 도메인을 넘겨줬거든요..
저도 너무너무 동의합니다. 감사합니다 변경하겠습니다!!!

2023-03-22 05:30 UTC, Jaeyoung22 commented on src/main/java/domain/piece/type/Empty.java
> +        public static final Empty INSTANCE = new Empty();
앗 아닙니다... 컨버터 클래스 만들면서 거기서 쓰여서 퍼블릭으로 두었습니다!

2023-03-22 06:17 UTC, Jaeyoung22 commented on src/main/java/view/OutputView.java
> +    private static String pieceToString(Piece piece) {
맞습니다!! 클래스 분리 했습니다!

2023-03-22 07:58 UTC, Jaeyoung22 commented on src/main/java/controller/ChessController.java
> +    private void validateCommandRequest(String[] inputs) {
View에서 입력 형식 정도의 간단한 검증만 하고, domain에서 자세한 검증을 하는 것이 좋다고 생각합니다!
이번 미션은 빠르게 하느라 컨트롤러 인지도 인식도 못하고 여기서 해버린 것 같네요ㅠㅠ 부끄럽고 죄송합니다ㅠㅠ
사용자의 입력이 중요한 값이라고 생각해서 따로 객체를 만들었는데, 이 부분에 대한 질문을 리뷰요청 드리면서 다시 드리곘습니다!! 감사합니다!!

2023-03-22 08:01 UTC, Jaeyoung22 commented on src/main/java/domain/board/File.java
> +    }
반드시 그러겠습니다..!

2023-03-22 08:01 UTC, Jaeyoung22 commented on src/main/java/domain/board/ChessBoard.java
> +    private Map<Square, Piece> board = new HashMap<>();
그러니까요.. 감사합니다!!

2023-03-22 08:56 UTC, Jaeyoung22 commented on src/main/java/domain/piece/type/Pawn.java
> +    );
넵!!!!

2023-03-22 08:56 UTC, Jaeyoung22 commented on src/main/java/domain/piece/type/Pawn.java
> +    public boolean canMove(Map<Square, Camp> pathInfo, Square targetSquare) {
넵!!! 감사합니다!~!!

2023-03-22 08:57 UTC, Jaeyoung22 commented on src/main/java/domain/piece/type/Pawn.java
> +        return movableSquares;
맞습니다!!! 수정했습니다!! 감사합니다!!!

2023-03-22 08:57 UTC, Jaeyoung22 commented on src/main/java/domain/piece/type/Pawn.java
> +    public List<Square> fetchMovePath(Square currentSquare, Square targetSquare) {
부끄럽습니다..ㅎㅎ

2023-03-22 08:58 UTC, Jaeyoung22 commented on src/main/java/controller/ChessController.java
> +            chessService.execute(inputs);
음.. 메서드 이름을 변경해야할 것 같네요..?
새로운 로직으로 변경해봤는데, 이 로직보다 생각하신 로직이 더 깔끔하다고 느껴지시는지 답변 부탁드려도 될까요?!
빙봉이 알려주신 방법도 시도해보긴 했습니다!

2023-03-22 10:22 UTC, Jaeyoung22 reviewed
안녕하세요 빙봉!!
다시 리뷰요청 드리기까지 시간이 너무 오래걸렸네요ㅠㅠ 죄송합니다
고민할 부분이 좀 많았던 것 같아서 오래 걸렸습니다..ㅠㅠ 이 부분은 커멘트 남겨놨습니다!
또 속도보다는 이번에는 어느정도 볼만하다고 생각이 들 때까지 오래 잡고 있다보니까 늦어졌네요..

빙봉이 조언해주신대로 제한 기간 내에서 속도와 품질을 둘 다 챙기는 더 나은 개발자가 되도록 노력하겠습니다!

다음 리뷰도 잘 부탁드려요!!

2023-03-22 10:22 UTC, Jaeyoung22 commented on src/main/java/service/ChessService.java
> +    private final Map<Command, Consumer<CommandRequest>> commandsAndExecutions = Map.of(
빙봉! 제가 사용자에 입력에 따라서 실행될 메서드들을 `서비스`에서 매핑해놨는데요,
크루들과 의견을 나눠본 결과 `컨트롤러`에 이 맵퍼를 두는 것이 맞다고 하는  의견도 많았습니다.

이 부분은 저는 사용자의 입력을 어떻게 처리하는 가에 달려있다고 생각이 드는데요,
지금의 구조에서 저는 사용자의 입력은 중요하다고 생각해서 (콘솔이기 때문에 더욱)
따로 객체로 관리하고, MOVE 명령의 경우에 대해서 현재 칸과 목표 칸도 반환할 수 있도록 했습니다.
이 경우 만약 컨트롤러에 이 맵퍼가 있다면,
1. 뷰에서 넘어온 입력이 도메인까지 넘어가고,
2. 도메인에서 검증이 끝난 객체가 다시 컨트롤러로 가서,
3. 컨트롤러의 행위를 제어하기 때문에,
저는 도메인에서 일어난 결과가 컨트롤러까지 넘어갔는데 뷰로 넘어가지 않는 것이 어색해서 서비스에 두었습니다!

그런데, 만약 이 입력을 버튼이 눌리는 것 등으로 추상화를 한다면, 컨트롤러에 있어도 된다고 생각해요.

제가 가지고 있는 개념이 설득력이 있는 부분인지 궁금해서 커멘트 남깁니다!

2023-03-23 13:41 UTC, aegis1920 commented on src/main/java/domain/piece/Camp.java
> +public enum Camp {
그런 뜻이 있었군요. 단순히 궁금해서 여쭤본 거였습니다ㅎㅎ 혼동의 여지 없습니다!

2023-03-23 13:59 UTC, aegis1920 commented on src/main/java/controller/ChessController.java
> +            chessService.execute(inputs);
제가 의도했던 방향은 아니나 전보단 나아진 것 같습니다. 👍 
위 피드백을 드렸던 이유는 

- 기존 chessService.isOngoing()을 통해 get하지 않아도 됨
- return 값을 가짐으로써 execute 메서드를 쉽게 테스트 가능

위의 이유가 있었습니다. 참고차 말씀드립니다 🙇

2023-03-23 14:57 UTC, aegis1920 commented on src/main/java/service/ChessService.java
> +    private final Map<Command, Consumer<CommandRequest>> commandsAndExecutions = Map.of(
제가 이해한 걸 바탕으로 상황을 가정하고 이야기해볼게요. 틀린 부분이 있다면 이야기해주세요. 틀렸는데 구구절절 이야기한 걸수도 있습니다ㅎㅎ

아 그리고 이야기해주실 때 어떤 도메인까지 넘어가는지, 컨트롤러의 행위는 어떤 행위를 의미하는지, 도메인에서 일어난 결과가 뭘 의미하는지 구체적으로 이야기해주면 리뷰어에게 도움이 될 것 같습니다 🙂 

Controller에 commandsAndExecutions 맵퍼가 필드로 존재한다면,

1. 콘솔 입력이 View를 통해서 Command 도메인으로 넘어가고
2. Command 도메인에서 입력에 대한 검증이 끝난 후, 
3. Controller에서 Command가 서비스의 행위(start, end, move)를 제어함
4. 여기서 Command 도메인에서 일어난 결과(3)가 View로 넘어가지 않고 Service로 가는 것이 어색함

Command를 도메인으로 생각하신 것 같은데요. Command가 start, end, move로 딱 나눠지니 enum으로 생각하기 좋고 enum이라고 하면 도메인으로 느껴지기 쉬울 것 같습니다. 제 생각에 Command는 RequestDto 단순 그 용도라고 보여지거든요. 그래서 (Piece 같은 도메인에 비해서) 중요한 도메인이라고 보기에 애매하다고 생각이 들어요. CommandDto라고 작성하고 그 안에 start, end, move 문자열을 상수로 작성하고 여기서 입력 검증을 한다고 하면 CommandDto가 도메인이라고 생각들까요? 단순히 요청 DTO라고 생각들진 않을까요?

위의 이유로 제가 생각하는 Command와 리오가 생각하는 Command가 달라서 리오가 가지고 있는 개념이 설득력있다고 판단하긴 어려울 것 같아요.

2023-03-23 15:11 UTC, aegis1920 commented on src/main/java/view/OutputView.java
> +        if (board.values().stream().allMatch(string -> string.equals("."))) {
출력하고 싶은 것의 상태에 따라 출력을 하고 하지 않고를 결정해야한다면 뷰의 역할이라고 볼 수 있을 것 같습니다. (마치 프론트엔드에서 그대로 출력하지 않고 응답받은 상태에 따라 다르게 출력하는 형태)
그런데 올라가지 않은 상태를 출력하지 않으려면 playEachTurn()의 로직 순서를 바꾸면 되지 않을까요..?
```
CommandRequest commandRequest = new CommandRequest(InputView.requestCommand());
chessService.execute(commandRequest);
OutputView.printChessBoard(chessService.getChessBoard());
```

2023-03-23 16:00 UTC, aegis1920 approved these changes
안녕하세요 리오! 빙봉입니다 🙂 

피드백이 많았는데 잘 반영해주셔서 감사합니다 👍 기존에 남겼던 코멘트 답변 및 추가 코멘트 남겼는데 확인 부탁드려요! 도메인에 대한 요구사항은 만족한 것 같아 다음 미션으로 넘어가도 될 것 같습니다. 고생하셨어요!!

궁금한 점은 언제든 DM주세요!

2023-03-23 16:00 UTC, aegis1920 commented on src/main/java/service/ChessService.java
> +    private boolean isOngoing;
함수명이 isOngoing이라 ongoing만 써도 될 것 같은 느낌이 드네요ㅎㅎ

2023-03-23 16:00 UTC, aegis1920 commented on src/main/java/domain/piece/jumper/Jumper.java
이 파일은 뭔가 적용중인 파일인가요?

2023-03-23 16:00 UTC, merged