[1, 2단계 - 체스] 연어(황재현) 미션 제출합니다.
woowacourse/java-chess pull request #465
Opened 2023-03-17 05:12 UTC by nuyh99

안녕하세요 로운!!
폰을 구현하는 것이 너무 어려웠습니다ㅠㅠ
최대한 좋다고 생각하는 방향으로 구현 해봤습니다!
피드백 잘 부탁드려요...! 미리 감사합니다😃

질문이 하나 있는데, 추상 클래스에서 정의한 메서드를 `Pawn` 에서만 재정의 한 상태입니다.
이렇게 사용하는 것이 잘못된 방식일까요...? 
**Override** 를 하는 행위는 `abstract` 메서드에 대해서만 하는 것이 맞는 것일 지 궁금합니다...!

2023-03-18 11:10 UTC, lowoon commented
> 안녕하세요 로운!! 폰을 구현하는 것이 너무 어려웠습니다ㅠㅠ 최대한 좋다고 생각하는 방향으로 구현 해봤습니다! 피드백 잘 부탁드려요...! 미리 감사합니다😃
> 
> 질문이 하나 있는데, 추상 클래스에서 정의한 메서드를 `Pawn` 에서만 재정의 한 상태입니다. 이렇게 사용하는 것이 잘못된 방식일까요...? **Override** 를 하는 행위는 `abstract` 메서드에 대해서만 하는 것이 맞는 것일 지 궁금합니다...!

추상클래스와 interface를 왜 사용하는지에 대해서 한번 고민해 보시고 말씀해주시면 저의 생각을 말씀드릴게요!ㅎㅎ

2023-03-20 07:49 UTC, nuyh99 commented on src/main/java/Application.java
> +        new ChessController().run();
현재 Controller를 사용하는 클라이언트는 `Application.main` 밖에 없으므로 삭제하는 것도 좋은 학습 방법인 것 같습니다!

2023-03-20 09:48 UTC, nuyh99 commented on src/main/java/domain/position/Positions.java
> +        final int COUNT_BETWEEN = getMaxDifference(source, destination)-1;
상수처럼 생각해서 선언했는데 별로 의미가 없는 것 같네요! 수정했습니다.

2023-03-20 12:40 UTC, nuyh99 commented on src/test/java/domain/board/BoardTest.java
> +        assertThat(board.getPieces().containsKey(Positions.from("D4"))).isFalse();
이후의 assertion은 진행되지 않는 군요!
모두가 성공하거나 실패하거나 둘 중 하나라면 모든 검증을 하나로 묶는 `assertAll`이 좋을 것 같고,
순차적으로 검증을 한다면 `assertSoftly`가 좋을 것 같습니다.

지금 상황에서는 동시에 성공해야 하고, 순차적으로 실패할 수 없으므로 `assertAll`이 맞는 것 같습니다!

2023-03-20 13:16 UTC, nuyh99 commented on src/test/java/domain/board/BoardTest.java
> +    void kingMove() {
nested 어노테이션을 사용해서 묶어봤습니다!

이동 방향에 대해서는 Piece 별 테스트에 모두 작성해뒀습니다. 
그래서 BoardTest에서는 상황별로 먹거나, 이동하거나, 둘다 불가능한 상황에 대해서 검증하면 좋겠다고 생각했습니다!

`Piece.isMovable`의 모든 방향에 대한 검증들을 BoardTest에서도 중복 검증하는 것이 나은 가요....??!

2023-03-21 11:53 UTC, lowoon commented on src/main/java/domain/position/Positions.java
> +    }
String으로 관리하는 것이 좋지 않아서요. 입력을 받을때는 괜찮지만 처음에 생성을 할때 모든 위치를 String으로 관리하다 보니 위험해 보여서요.
String으로 관리를 하게 되면 오타의 가능성이 굉장히 높고 같은 값을 여러군데에서 사용을 하게 된다면 관리해야하는 포인트가 늘어날 수 있습니다.
모든 체스에서 위치는 같기 때문에 cache자체는 좋을 수 있는데요. 두가지 방법이 있을 것 같아요.
1. cache를 유지하고 initial board를 만들때, row와 column의 값을 사용한다.
2. cache를 없애고 게임마다 필요한 position들을 만든다.

어떤 방법이 좋을지 고민해보고 적용해보시면 될 것 같아요~

2023-03-21 12:04 UTC, lowoon commented on src/test/java/domain/board/BoardTest.java
> +    void kingMove() {
아뇨 필요하다면 할 수 있지만 같은 부분에 대해서 중복으로 하는 것은 테스트 유지,관리 측면에서 오히려 좋지 않다고 생각합니다!
테스트도 무조건 많다고 좋은 것은 아니니까요.

2023-03-21 12:38 UTC, lowoon requested changes
고생하셨어요. 연어! 리뷰 반영 잘 해주셨어요! 😄 
몇 가지 코멘트 남겼으니 확인해주세요ㅎㅎ
궁금한 점은 언제든지 DM이나 코멘트 남겨주세요 :)

2023-03-21 12:38 UTC, lowoon commented on src/main/java/domain/board/Board.java
> +
처음에는 무조건 black이 움직이는데요.
현재는 white도 움직일 수 있지 않나요?

2023-03-21 12:38 UTC, lowoon commented on src/main/java/domain/piece/Piece.java
> +public abstract class Piece {
position을 캐시했다면 똑같은 의미로 piece들도 캐시할 수 있지 않을까요?? 처음에 쓰이는 piece들은 정해져 있으니까요

2023-03-21 12:38 UTC, lowoon commented on src/main/java/domain/position/Direction.java
> +        final int rank = Integer.compare(rankDifference, 0);
굳이 차이를 얻는 것이 아니라 아래와 같이 하면 되지 않나요?
```java
int rank = Integer.compare(to.getRank, from.getRank)
int file = Integer.compate(to.getFile, from.getFile)
```
그리고 `of(Position from, Position to)`에서 `Direction.values`를 순회하는 로직 하나로 Direction을 구할 수 있지 않나요??
`of(Position from, Position to)`, `of(int rankDifference, intfileDifference)`, `isNotEightDirection`3가지나 필요한걸까요??

2023-03-21 12:38 UTC, lowoon commented on src/main/java/domain/board/Board.java
> +        if (board.containsKey(destination)) {
pawn때문에 이동하는 경우와 잡는 경우를 나눠서 동작하는 것 같은데요.
어쨌는 분리를 필요하기 때문에 잡는 것인지 이동인지에 대한 확인은 필요한거 같아요
1. 현재와 같이 전체 메서드 분리
2. movable에 destination의 기물 여부를 넘겨서 내부에서 여부에 따라 로직이 동작하도록 하는 방법
3. board가 Square라고 하는 객체를 가지고 Square가 Position과 Piece를 가져서 Square끼리 비교하도록 하는 방법

어떤 방법이 좋을지 고민해보고 적용해보시면 좋을것 같습니다~

2023-03-21 12:38 UTC, lowoon commented on src/main/java/view/BoardView.java
> +    private String convertCaseByTeam(final Piece piece) {
역할과 책임에 따라 달라질 수 있는 것 같은데요.
1. peice자체가 팀에 따라 다른 이름을 가져서 서버에서 정의해서 사용하는 것인지
2. peice의 이름은 view만을 위한 것이기 때문에 1가지만 정의하고 view에서 상황에 따라 다르게 보여줄 것인지

차이는 현재는 piece자체를 넘겨서 team이 확인 가능하지만 dto를 넘기게 된다면 이름만 넘길까요 아니면 team도 함께 넘기게 될까요??

2023-03-22 06:06 UTC, nuyh99 commented on src/main/java/domain/position/Positions.java
> +    }
String을 기반으로 한 캐싱을 제거하고 File, Rank를 사용해서 `new Position`으로 한다면 좀더 객체지향적인 코드가 될 것 같네요!

2023-03-22 12:29 UTC, nuyh99 commented on src/main/java/domain/board/InitialChessAlignment.java
> +        final List<Position> white = Positions.of("A1", "H1");
각 Piece들이 초기 위치를 가지도록 하고 추상 메서드에 `getInitialBlackPositions` 등을 오버라이딩 하도록 했습니다.
String으로 관리하던 Position 캐싱을 제거하고 File, Rank를 사용하도록 변경했습니다.

이로 인해서 각 Piece들의 응집력이 좀더 강해진 것 같고, String으로 캐싱하던 불안전성이 사라진 것 같아요!!

2023-03-23 04:21 UTC, nuyh99 commented on src/main/java/domain/board/Board.java
> +
로운! 도메인 지식을 더 습득해왔습니다.
항상 백이 먼저 시작한다고 해서 상태 패턴을 사용해 적용했습니다!

2023-03-23 05:04 UTC, nuyh99 commented on src/main/java/domain/board/Board.java
> +        if (board.containsKey(destination)) {
3번을 한다면 Map으로 관리하기 보다는 List<List<Square>>의 형태로 관리하면 좋을 것 같아요.

1번과 2번에 대해서는 현재 Board에서 전체 Piece를 관리하는 구조라서, `isMovable`, `isCapturable` 두 가지로 Board가 전체적인 로직 흐름을 관리하는 것이 좋다고 생각해요.

---
위와 같이 생각해서 현재 구조가 나쁘지 않은 것 같아요...!

2023-03-23 05:07 UTC, nuyh99 commented on src/main/java/view/BoardView.java
> +    private String convertCaseByTeam(final Piece piece) {
지금처럼 구현한 이유는 2번과 같습니다.

사실 처음에는 Piece의 name 또한 뷰를 위한 것이 아닐까? 하고 생각을 했습니다.
하지만 객체의 고유한 성질이라고 생각해서 놔둬도 된다고 판단했어요.
근데 이때 대문자와 소문자 구별은 뷰에 의존되는 것이여서 지금처럼 뷰에서 가공하도록 했습니다.

만약 DTO를 사용하게 된다면, 이름과 팀을 넘기게 될 것 같아요!!

2023-03-23 05:42 UTC, nuyh99 commented on src/main/java/domain/position/Direction.java
> +        final int rank = Integer.compare(rankDifference, 0);
`isDiagonal`, `isStraight` 메서드의 구현을 수정하고, `Position.compareRank` 등의 메서드를 만들어서 리팩토링했습니다!

2023-03-23 05:46 UTC, nuyh99 commented
최근 로운의 코멘트들을 보면서 정말 다양한 경우를 생각해보고 괜찮은 것들을 적용해봤어요!
그 중 `Position`의 캐싱을 제거하는 것이 side effect가 매우 컸는데, 변경점을 최소화해야 한다는 말이 잘 와닿았습니다🥕🥕🥕

바쁘신 와중 DM 답장도 빨리 주시고 정말 감사드려요ㅠㅠ
이번 피드백도 가감 없이 채찍질 해주세요...!!😁

2023-03-23 12:21 UTC, lowoon commented on src/main/java/view/BoardView.java
> +    private String convertCaseByTeam(final Piece piece) {
저는 반대로 생각을 했던거 같아요!
오히려 piece의 Name을 class 이름과 같은 이름을 가지고 이 이름과 매칭되는 문자를 view에서 관리할 거 같아요!
말씀하신대로 고유한 성질이라면 위와 같은 형태가 맞을 것 같고, 하나는 그대로 사용하고 하나만 대문자로 사용을 한다는 것 자체가 서버의 값에 종속적인거 같아서요. 모두 종속적이라면 서버 자체에서 모든 값을 관리하는 것이 맞고 종속성을 없앤다면 어떤 view에서 사용하던 공통적으로 사용할 수 있는 값을 정해야하지 않을까요??
현재는 console view이지만 Web이나 앱으로 넘어간다고 해도 name을 그대로 사용할 수 있을까요??
서버와 클라의 역할은 어떻게 구분될까요? 자동차 경주를 예로 들면 자동차가 4번 움직였을 때 ----가 아닌 `posiiton = 4`를 넘긴 이유는 무엇일까요?

2023-03-23 12:43 UTC, lowoon approved these changes
고생하셨어요. 연어! 이전 리뷰 내용을 잘 반영해주셨습니다 💯
몇가지 코멘트를 달아봤는데요. 코멘트 반영은 2단계에서 부탁드릴게요.
추가적인 궁금증은 이 pr이 머지되어도 댓글 남겨주셔도 좋구 DM도 좋습니다.

2023-03-23 12:43 UTC, lowoon commented on src/main/java/domain/position/Position.java
> +    public int getFileDifference(final Position other) {
```
public class ClassName {
	// private static final
	// 상수
	// 클래스 변수
	// 인스턴스 변수
	// 생성자
	// 팩토리 메서드
	// 일반 메서드
	// getter, setter
	// equals, hashCode, toString
}
```
의 순서로 작성해주는 것이 좋습니다~

2023-03-23 12:43 UTC, lowoon commented on src/main/java/domain/position/Position.java
> +    public Position move(final Direction direction, final int distance) {
사용하지 않는 메서드는 지워주는 것이 좋습니다~

2023-03-23 12:43 UTC, lowoon commented on src/main/java/domain/position/Position.java
> +        final int rankDifference = otherRank.compareTo(thisRank);
숫자로 가져서 바로 비교하지 않은 이유가 있을까요??
file때문이라면 file의 이름을 char로 가지면 바로 `Integer.compare`를 사용할 수 있는데요.
한번 고민해보시면 좋을것 같아요!

2023-03-23 12:43 UTC, lowoon commented on src/main/java/domain/position/Direction.java
> +                .orElse(NOTHING);
```java
        final int rank = from.compareRank(to);
        final int file = from.compareFile(to);

        return Arrays.stream(Direction.values())
                .filter(direction -> direction.rankDifference == rank && direction.fileDifference == file)
                .findAny()
                .orElse(NOTHING);
```
만 있어도 같은 기능일텐데요. 처음에 분리하는 이유가 더 빨리 구분하기 위해서일까요?

2023-03-23 12:43 UTC, lowoon commented on src/main/java/status/Turn.java
> +abstract class Turn implements Status {
테스트가 없는거 같아요

2023-03-23 12:43 UTC, merged

2023-03-25 06:46 UTC, nuyh99 commented on src/main/java/view/BoardView.java
> +    private String convertCaseByTeam(final Piece piece) {
매우 동의해요!
저도 서버에서 사용하는 값 들은 도메인 로직에서 의미를 가져야 하고, 출력과는 전혀 상관이 없어야 한다고 생각합니다.
뷰에서 바꿔야겠네요!

2023-03-25 10:53 UTC, nuyh99 commented on src/main/java/status/Ready.java
> +public final class Ready implements Status {
안됩니다!
뷰가 수정될 가능성이 도메인에 비해서 높은데, 도메인에서 뷰를 의존하게 되면 side effect가 너무 커질 것 같습니다.

2023-03-25 11:02 UTC, nuyh99 commented on src/main/java/status/Black.java
> +final class Black extends Turn {
Turn에게 현재 플레이어 상태 확인 역할을 위임하면서, 프로그램의 로직 흐름을 State들로 관리할 수 있을 것 같습니다.
Board는 Piece들을 가지고 있는 일급 컬렉션으로 유지할 수 있게 된 것 같아요!!

다만 현재 State 인터페이스에 선언된 메서드들을 모든 구현체에서 다 쓰는 것이 아니라서, `UnsupportedOperation` 예외를 발생시킵니다. 이것이 상태패턴을 쓰면 발생할 확률이 높은 건지, 제가 잘못 적용한 건지 모르겠어요...!

2023-03-25 11:03 UTC, nuyh99 commented on src/main/java/status/Turn.java
> +abstract class Turn implements Status {
UI와 의존을 가져서 작성을 안했었어요ㅠㅠ
잘못된 구조라는 것을 깨닫고, 의존성을 분리한 후 테스트 작성했습니다!

2023-03-26 02:12 UTC, nuyh99 commented on src/main/java/domain/position/Direction.java
> +                .orElse(NOTHING);
같은 기능이 아니라고 생각합니다! 8 방향에 대해서만 구하기 위한 메서드입니다.

대각선의 경우는 File과 Rank의 차이가 같아야 합니다.
File 차이가 -5이고, Rank의 차이가 4라면 대각선이 아닌데 `from.compareRank(to)`와 `from.compareFile(to)`를 거치게 되면
Direction(-1, 1)으로 결과가 나오게 됩니다. SE 방향이 아니지만 결과는 SE로 나오게 되는 것 같아요!