[1,2단계 - 체스] 바론(이소민) 미션 제출합니다.
woowacourse/java-chess pull request #467
Opened 2023-03-17 05:53 UTC by somsom13

안녕하세요, 범블비! 🐝🚕  (트랜스포머의 범블비라고 생각했는데.. 맞나요? ㅎ.ㅎ)
자바 체스 미션의 리뷰를 부탁 드리게 된 바론입니다 ㅎㅎ

체스 미션 어렵네요 😂 
이번 미션에서는 제한 시간 내에 모든 기능을 구현했었지만,,,! 추가 시간이 주어져서 게임의 진행 상황을 제어하기 위해 상태 패턴을 도입해 보았습니다. 

이번에 구현하면서 가장 어려웠던 점은 `ChessBoard` 의 책임을 분리하는 부분 이었습니다.
각 체스 말들이 자신의 이동 규칙에 따라 이동 가능한 모든 경로를 반환하면, 
1. 도착지로 가는 경로에 장애물이 있는지
2. 도착지에 다른 말이 있는 경우, 공격할 수 있는지

등을 판단할 필요가 있었습니다. 

이를 판단하기 위해서는 체스판의 정보와 각 위치에 있는 체스말을 확인해야 했기 때문에, 이러한 정보를 가지는 ChessBoard 객체에서 대부분의 일을 담당하게 되었습니다.

메서드를 분리하다 보니 ChessBoard 의 크기가 굉장히 커진 것 같은데요, 어떻게 하면 책임을 분리할 수 있을지 좋은 방법이 떠오르지 않아서 이 부분을 제대로 리팩터링 하지 못한 것 같습니다 😢 

많이 성장할 수 있는 리뷰 부탁드리겠습니다!
감사합니다 😍

2023-03-17 12:44 UTC, ddaaac requested changes
안녕하세요 바론 👋 

어려운 체스 미션 구현 깔끔하게 잘 해주셨습니다.

그 범블비가 맞긴 한데, 닉네임을 바꾸고 싶은데 포비가 허락을 안해주시더라구요 😅

몇 가지 코멘트를 남겼으니 확인해주세요.

2023-03-17 12:44 UTC, ddaaac commented on src/main/java/chess/domain/path/MovablePaths.java
> +        return paths.get(pathIndex);
stream 과 filter를 사용하면 간단하게 나타낼 수 있을 거 같아요.

2023-03-17 12:44 UTC, ddaaac commented on src/main/java/chess/domain/ChessBoard.java
> +        validateObstacleInDestination(dest, teamColor);
> 이를 판단하기 위해서는 체스판의 정보와 각 위치에 있는 체스말을 확인해야 했기 때문에, 이러한 정보를 가지는 ChessBoard 객체에서 대부분의 일을 담당하게 되었습니다.
메서드를 분리하다 보니 ChessBoard 의 크기가 굉장히 커진 것 같은데요, 어떻게 하면 책임을 분리할 수 있을지 좋은 방법이 떠오르지 않아서 이 부분을 제대로 리팩터링 하지 못한 것 같습니다 😢

- 간단하게 생각해보면 Piece에 path 정보를 어느 정도 넘기면 Piece가 자체적으로 움직임에 대한 여부를 판단할 수 있겠죠. 
- 아마 Path 에 관한 정보를 넘기고 싶지 않아 ChessBoard가 책임을 많이 지게 된 것 같아요.
- 개인적으로는 Pawn의 움직임에 관련된 로직은 모두 Pawn이 갖고 있어야 한다고 생각해요. 캡슐화도 지킬 수 있고 로직을 읽는 사람도 Pawn 클래스에 Pawn에 관한 로직들이 있을 거라고 예상할 테니깐요.
- 그래서 Piece에 적당히 Path 관련된 정보를 넘기는 방식으로 리팩토링 해보시면 좋을 것 같습니다.
- 공통적으로 가져야할 로직들은 Piece에 두고, 각자 가져야할 로직은 추상 메서드에서 구현할 수 있겠죠.

2023-03-17 12:44 UTC, ddaaac commented on src/main/java/chess/controller/state/Start.java
> +
이렇게 대부분의 메서드가 예외를 던지는 상황에서 상태 패턴을 적용하기 적당한 예제인가?라는 생각이 들더라구요.

2023-03-17 12:44 UTC, ddaaac commented on src/main/java/chess/domain/piece/Piece.java
> +    public abstract MovablePaths findMovablePaths(Position position);
여담으로, Piece에 Path관련된 정보를 넘기고 싶지 않다면 Piece에 source, dest만 넘기고 움직임에 관한 전략 + Path를 반환하게 구현할 수 있습니다. 이렇게 반환된 전략과 path를 board에 적용하면 되겠죠. 
이렇게 구성하면 Piece가 자신이 갈 수 있는 Path 계산과 어떤 식으로 움직여야 할 지에 관한 전략을 스스로 구할 수 있습니다.

다만 구현 난이도가 조금 있는 것 같아서 앞서 코멘트 드린 Path 정보를 Piece에 넘기는 방식의 리팩토링을 추천드립니다.

2023-03-17 12:44 UTC, ddaaac commented on src/main/java/chess/domain/path/Path.java
> +    public static Path ofMultiPath(Position current, final Direction direction) {
Direction에만 final이 붙은 이유가 있을까요?

2023-03-19 15:08 UTC, somsom13 commented on src/test/java/chess/domain/ChessBoardTest.java
> +        chessBoard.move(List.of(1, 2), List.of(1, 4), currentTeamColor);
범블비가 남겨주신 것과 똑같은 고민을 했었습니다 ㅎㅎ 
말씀해주신 것 처럼 List를 Position 으로 변환하는 것은  ChessBoard 의 책임이 아니라고 생각합니다!
ChessBoard가 Position 을 바로 받아오도록 하는 것이 "이 시작 position 에서 저 도착 position 으로 이동한다" 라는 의미를 더 명확하게 드러내는 것 같습니다. 
그리고 List 로 그대로 받아오는 것은 ChessBoard 가 View 의 작업을 이어받아 온 것처럼 보이기도 하네요 ㅎㅎ

`move(Position source, Position dest)` 로 변경하였습니다! 감사합니다 😄

2023-03-19 15:10 UTC, somsom13 commented on src/main/java/chess/domain/ChessBoard.java
> +    }
> 1. 검증 -> 2. 로직 실행이 자연스럽습니다.

너무 좋은 것 같습니다!!! 검증을 먼저 하고 로직을 실행하는 것이, "검증에 실패하면 로직을 수행하지 않고 / 검증에 성공하면 실제 작업을 수행한다" 에 더 적합할 것 같습니다.

검증 후에 특정 작업을 수행할 필요가 있는 경우, 검증을 먼저 하도록 변경하였습니다!

2023-03-19 15:11 UTC, somsom13 commented on src/main/java/chess/domain/path/MovablePaths.java
> +        return paths.get(pathIndex);
stream 을 써야겠다는 걸 생각도 못했었어요 ㅎㅎ 민망하네요 😂  stream 으로 바꾸니까 가독성이 훨씬 좋아졌네요! 감사합니다 👍

2023-03-19 15:34 UTC, somsom13 commented on src/main/java/chess/domain/ChessBoard.java
> +        validateObstacleInDestination(dest, teamColor);
조언 감사합니다!
> 아마 Path 에 관한 정보를 넘기고 싶지 않아 ChessBoard가 책임을 많이 지게 된 것 같아요.

말씀하신대로 Piece (체스말) 이 자신보다 훨씬 큰 범위인 ChessBoard와 관련된 정보를 알아야 할 필요가 없다고 생각했기 때문이었습니다!
(ChessBoard 내에 Piece 들이 있는 것이기 때문에 ChessBoard 가 Piece 들을 알고, 움직일 책임은 있지만 Piece 가 ChessBoard의 상황을 알아야 할 이유는 없다고 생각했습니다...!)

> 개인적으로는 Pawn의 움직임에 관련된 로직은 모두 Pawn이 갖고 있어야 한다고 생각해요. 캡슐화도 지킬 수 있고 로직을 읽는 사람도 Pawn 클래스에 Pawn에 관한 로직들이 있을 거라고 예상할 테니깐요.

이런 고민을 하면서도 피드백 남겨주신 것 처럼 ChessBoard 가 **특정 상황인 Pawn 에 대해서 ChessBoard가 별도의 로직을 가져야 한다는 것** 이 잘못되었다는 것을 느끼고 있었습니다 😢 

조언 해주신 내용을 참고해서 
`도착지에 말이 있다면? -> piece 에게 공격이 가능한지 물어본다.`
`도착지에 말이 없다면? -> piece 에게 빈 공간으로의 이동이 가능한지 물어본다.` 
로 리팩터링을 해보았습니다..! 결국 piece 는 여전히 path를 직접적으로 받지 않으면서도, **체스말의 종류에 상관없이 piece 라는 상위 클래스로 각 체스말이 자체적으로 움직임의 여부를 판단하도록 변경했습니다.**

그리고 이 과정에서, piece 에게 이동 가능 여부를 물어보았을 때, 이동이 불가능 하다면
1. piece 의 내부에서 예외를 발생시킨다
2. piece 는 boolean을 반환하고, 예외는 chessBoard 에서 발생시킨다

중 무엇이 더 좋은 방법일지에 대한 고민이 생겼습니다!

piece 는 그저 "요청에 대해 가능한지, 불가능한지 대답만 한다. 답변에 따라 이 상황이 예외인지, 아닌지는 체스 보드가 판단할 일이다." 
라고 생각했기 때문에 예외를 ChessBoard에서 발생시키도록 했는데요, 혹시 범블비는 어떤 방식을 선택하실 것 같은지도 여쭤보고 싶습니다..!!

2023-03-19 15:41 UTC, somsom13 commented on src/main/java/chess/controller/state/Start.java
> +
남겨주신 의견을 보고 제가 생각했던 것들을 순서대로 남겨보겠습니다..!
1. 우선 현재 코드에서 예외를 던지는 메서드가 대부분인 경우는 **한 상태일 때, 수행할 수 있는 작업이 하나로 고정되어 있기 때문** 입니다.
2. 상태 패턴은 "서로 다른 상태일 때, 호출되는 메서드에 따라 다른 작업을 수행하고, 그 결과에 따라 각각 다른 상태를 반환해야할 때" 사용하기 좋은 패턴입니다. 
3. 지금 상황에서는 각 상태마다 수행할 수 있는 메서드가 하나 뿐이기 때문에 **상태에 따라 다른 작업이 수행된다** 라는 상태 패턴의 목적에는 맞지 않는 것 같습니다. (만약 start, progress, end 상태에서 메서드 마다 다른 작업이 수행되고, 다른 상태를 반환해야 했다면 적절했을 것 같습니다.)
4. 무엇보다도, 현재의 상황은 "시작 -> 진행 -> 종료" 라는 상태 변화의 순서가 명확하게 정해져 있기 때문에 더더욱 상태 패턴을 도입할 이유가 없어 보입니다!

정리하자면 
> 상태 패턴은 “호출이 되었을 때, 다른 작업을 수행하고 다른 상태를 반환한다” 가 그 주목적 이기 때문에 아예 호출 자체가 불가능 한 메서드들을 상태 패턴으로 관리할 이유는 없어 보인다.

이라는 결론을 내렸습니다.

4번에 작성했던 것 처럼 "시작 -> 진행 -> 종료" 의 순서가 고정되어 있기 때문에, controller 에서 이 흐름에 맞게 요청을 주고 받도록 변경하고, 재입력 기능을 추가했습니다!

혹시 더 생각해 볼 만한 부분이나, 제가 놓치고 있는 부분이 있다면 조언 주시면 더 공부해 보겠습니다 😄 
좋은 의견 감사합니다!! ❤️

2023-03-19 15:44 UTC, somsom13 commented on src/main/java/chess/domain/piece/Piece.java
> +    public abstract MovablePaths findMovablePaths(Position position);
조언 감사합니다!!
현재로서는 어떻게 해볼 수 있을지 떠오르지 않아서 반영을 못했지만, 더 생각해 보면서 해당 방향으로의 구현도 도전해 보겠습니다 ㅎㅎ 감사합니다!

2023-03-19 15:48 UTC, somsom13 commented on src/main/java/chess/domain/path/Path.java
> +    public static Path ofMultiPath(Position current, final Direction direction) {
이렇게 변경하면 다른 객체들에서 Pawn 만을 위한 로직을 가지지 않도록 변경할 수 있겠네요!!

처음에는 "그러면 체스판의 끝까지 다중 경로를 찾아야 하는 piece 들 (rook, bishop, queen )은 어떡하지..?" 라는 생각을 했었는데요, 해당 piece 들의 내부에 8 이라는 상수를 추가할까 하다가 `Position.max()` 를 통해서 Position 내부의 MAXIMUM 상수를 전달하도록 변경했습니다! 

여기에서도 한 가지 고민이 생겼는데요..!
1. private 상수를 public 으로 재정의한다
2. public getMax() { return MAXIMUM; } 과 같이 내부 상수값을 가져올 수 있는 public 메서드를 추가한다

중 범블비는 혹시 무엇이 더 적합하다고 생각하시나요??

저는 내부의 상수는 외부에서 직접 접근해서는 안된다 라고 생각해서 public 메서드를 선택했는데, 애초에 static final 상수는 한 번 만들어지면 변경이 불가능하기 때문에 외부에서 직접 접근해도 문제가 되지는 않을 것 같다는 생각이 들었습니다..! 

괜찮으시다면 범블비의 의견을 여쭤보고 싶습니다 😄

2023-03-19 15:51 UTC, somsom13 commented on src/main/java/chess/domain/path/Path.java
> +    public static Path ofMultiPath(Position current, final Direction direction) {
`ofMultiPath` 메서드는 현재의 위치 -> 그 다음 위치 -> 그 위치의 다음 위치... 를 반복하여 **체스보드 내에서 한 방향으로 이동 가능한 모든 경로를 반환** 하는 역할을 합니다!

이번에 받아온 next 위치가 다음 `findNextPosition` 의 `current` 가 되기 때문에, 계속해서 current 를 변경해줄 필요가 있습니다. 해당 메서드 내에서 current가 변경되어도 외부의 position 에는 영향을 미치지 않기 때문에 파라미터로 받은 current 를 직접 변경하는 방식을 선택했습니다..!

혹시 current 를 final 로 받아오고, 메서드 내에서 
```
Position foundPosition = current;
foundPosition = foundPosition.findNextPosition();
```
으로 변경하는 것이 더 파라미터로 받아온 current를 보호하기에 더 좋은 방법이었을까요??

2023-03-19 15:55 UTC, somsom13 commented on src/main/java/chess/domain/Position.java
> +    public static Position from(List<Integer> rankFile) {
현재의 입력, 및 체스판 접근 방식은 x축은 알파벳으로, y축은 숫자로 받아와서 (ex. C6) 이에 대응되는 좌표값으로 위치를 찾는 방식입니다!

좌표 평면으로 비유했을 때, c가 x = 3 을 의미한다는 것은 입력에서만 쓰이는 정보라고 생각했었습니다!

view에서 알파벳으로 받은 file을 이에 대응되는 숫자 index로 변환해서 도메인에 넘겨주면, position 이라는 도메인은 그저 입력된 좌표값으로 행위를 하면 된다고 생각했습니다.

그런데 범블비의 리뷰를 받고 다시 한 번 생각해보니, 애초에 File 과 Rank 자체가 "체스판의 크기, 각 칸의 접근 방법" 에 대한 정보를 담고 있는 것 같기도 합니다. 
(file 의 경우 체스판의 가로 칸들은 a ~ h, 즉 1 ~ 8 의 라는 정보를, rank도 마찬가지로 체스판의 세로 칸들은 1 ~ 8 이라는 정보를 담고 있습니다.)

이 부분에서는 또 “체스판의 좌표” 라는 도메인과 직결되어 있는 것 같아서 도메인으로 포함시키는 것이 더 옳은가 싶기도 하네요...! 

File 과 Rank enum 이 view 에 더 가까울지, 아니면 Position 이라는 도메인과 더 가까울 지 생각해보았는데요, 체스판 내의 칸들의 위치 정보를 직접적으로 가지고 있기 때문에 Position 도메인과 더 가깝다고 판단했습니다. 그래서 조언 주신 대로 문자열을 받아오고, position 내부에서 해당 문자열을 좌표로 변환하도록 변경해 보았습니다! 

그래도 범블비가 생각하시기에는 file과 rank 의 책임이 view 와 domain 중 어디에 더 가까운 것 같은지 의견을 여쭤보고 싶습니다 ㅎㅎ 감사합니다! 😄

2023-03-19 15:56 UTC, somsom13 commented on src/test/java/chess/domain/ChessBoardTest.java
> +    }
ChessBoard의 책임을 분리하면서 테스트 코드도 함께 제거했습니다! 감사합니다 😍

2023-03-19 16:00 UTC, somsom13 commented on src/main/java/chess/domain/Position.java
> +        }
첨부해주신 글과 Optional 사용법에 대해 찾아보고, 둘 중 무엇이 현재 상황에 더 적합할지 고민해보았습니다.

우선, Optional 은 null 을 감싸주고 값을 꺼내올 때는 Optional.ifPresent(), 또는 OrElse() 와 같은 방법으로 NPE 가 발생하는 것을 방지할 수 있다는 것이 가장 큰 장점입니다.

실제로 좋은 코드, 나쁜 코드 책을 읽었을 때도 null 을 직접적으로 사용하지 않고 null 안전성을 활용하거나, 자바에서는 Optional 을 적극 활용하라고 적혀있었던 것으로 기억합니다 😂 

현재의 `findNextPosition()` 은 다음 postion 이 없다면 null 을 반환합니다.

- ofSinglePath

```java
List<Position> positions = new ArrayList<>();
current.findNextPosition(direction).ifPresent(positions::add);
return positions;
```

단일 경로의 경우에는, 위의 방법으로 값이 있을 때만 list에 더해주게 함으로써 직접적인 null 체크가 이루어지지 않고 값이 있을 때만 원하는 작업이 수행되게 변경 가능할 것 같습니다.
⇒ 이 경우에는 Optional 의 사용이 적합하다고 생각합니다!

- ofMultiPath
1. current 에 대해서 다음 경로를 찾아온다
2. 찾아온 다음 경로를 다시 current에 넣고, 새로운 다음 경로를 찾아오는 과정을 반복

이렇게 하기 위해서는 매번 current = current.findNextPosition() 을 해줄 필요가 있으며, 반복문 내에서 매번 Optional 의 present 체크를 해주어야 합니다.  
findNextPositoin은 Optional<Position> 이 아닌, Position 자체에 대해 호출되는 메서드 이기 때문에  ifPresent 이면 Optional 에서 Position 을 get 해오고, empty 면 while 문 자체를 끝내야 하는 상황이라고 생각했습니다.

```java
for (int i = 0; i < size; i++) {
            Optional<Position> next = current.findNextPosition2(direction);
            if (next.isEmpty()) {
                break;
            }
            positions.add(next.get());
            current = next.get();
        }
```

제가 생각하기에는 이런 방법 밖에 떠오르지 않는데, 이렇게 되면 next == null 일 때 break 하는 것과 다를 바가 없다는 생각이 들었습니다..!

지금은 물론 findNextPosition 이 사용되는 곳이 제한되어 있어서 null 에 대한 처리가 잘 이루어지지만, 그렇지 않은 곳에서는 문제가 될 수도 있을 것 같다는 생각도 듭니다. 그래도 제 생각에는 지금 코드 자체에서는 null 로 반환하는 것이 더 간결하지 않나 싶습니다!

범블비는 어떤 상황에서 Optional 을 사용하는지, 이번 코드에서는 개인적으로 어떤 견해를 가지고 있는지 여쭤보고 싶습니다 ㅎㅎ 🙇‍♀️

2023-03-19 16:02 UTC, somsom13 commented on src/main/java/chess/domain/ChessBoard.java
> +        final TeamColor teamColor) {
저의 실수입니다 😂 😂  final 을 모두 붙이도록 수정했습니다!
파라미터 줄바꿈은 이번에 ChessBoard의 책임을 분리하면서 파라미터의 수가 줄어들어서 줄바꿈이 발생하는 다른 메서드들에 대해서 적용했습니다!

감사합니다 👍 👍

2023-03-19 16:05 UTC, somsom13 commented
안녕하세요 범블비!! 😸 

좋은 리뷰 정말 감사합니다 😍 

남겨주신 피드백들을 반영하면서 상태 패턴을 제거하고, controller 에 재입력 로직도 추가해보았습니다.

그리고 남겨주신 코멘트들에 대해서 저의 의견, 질문도 남겼는데요..! 최대한 제 생각이 어떤지를 말씀드리려다 보니 말이 너무 길어진 것 같아서 죄송합니다 😢 😢  

이번 리뷰도 잘 부탁드립니다! 감사합니다 👍

2023-03-20 12:50 UTC, ddaaac approved these changes
안녕하세요 바론 👋 

리뷰 반영 잘 해주셨습니다.

다음 단계 진행해주세요~

2023-03-20 12:50 UTC, ddaaac commented on src/main/java/chess/domain/ChessBoard.java
> +        validateObstacleInDestination(dest, teamColor);
개인적으로 validateXXX란 메서드를 만들고 다른 객체에서 호출하는 걸 좋아하지는 않아서 바론이 구현한 것처럼 만들 것 같네요.
검증은 보통 로직에 수반되는 경우가 많습니다. 검증 자체가 메인 동작이 되는 경우는 거의 없다고 생각해요. board.move의 로직을 실행하는 중간에 발생하는 논리 오류를 막기 위해 검증이 들어가야 한다면 piece에게 move 여부에 대해 물어보는 게 조금 더 적당하지 않나 싶어요.
최근 읽었던 예외에 관한 [좋은 글](https://medium.com/@galcyurio/kotlin%EC%97%90%EC%84%9C%EC%9D%98-%EC%98%88%EC%99%B8-%EC%B2%98%EB%A6%AC-%EB%B0%A9%EB%B2%95-48a5cd94a4e6)도 읽어보시면 좋을 것 같네요.

2023-03-20 12:50 UTC, ddaaac commented on src/main/java/chess/domain/path/Path.java
> +    public static Path ofMultiPath(Position current, final Direction direction) {
- `ofSinglePath`는 `ofMultiPath`를 사용해서 구현할 수 있어보여요.
- `ofSinglePath`, `ofMultiPath`, `ofNoLimit` 이런 식의 3개 메서드면 외부에서 Position 관련 상수를 몰라도 되지 않을까요?
- 1, 2번 중에 선택해야한다면 1번을 선택할 것 같아요. 2번처럼 한 번 더 감싸는 건 어떤 이득이 있을까요?

2023-03-20 12:50 UTC, ddaaac commented on src/main/java/chess/domain/path/Path.java
> +    public static Path ofMultiPath(Position current, final Direction direction) {
아 가변 변수였군요. 제가 놓쳤네요 😅

2023-03-20 12:50 UTC, ddaaac commented on src/main/java/chess/domain/Position.java
> +    public static Position from(List<Integer> rankFile) {
> 문자열의 변환까지 객체의 책임일까?

라는 질문인 것 같네요. 이 경우에는 도메인 패키지 내의 File, Rank에 이미 문자, 숫자 관련 정보가 모두 들어가있어서 도메인이라고 봐도 좋을거라고 생각하고 남긴 코멘트였습니다. 리팩토링 해주신 방법도 좋아보여요.
다만, 테스트 코드에서는 변수 등을 활용해서 "C6" 이런 식으로 네이밍해주시면 좀 더 읽기 좋은 코드가 될 것 같네요.

2023-03-20 12:50 UTC, ddaaac commented on src/main/java/chess/domain/Position.java
> +        }
저는 코틀린 유저라 다음 Position이 **없을 경우** null을 리턴하는 게 굉장히 자연스럽게 느껴지긴 해요. 코틀린은 null을 컴파일 단계에서 안전하게 처리할 수 있어서 null 반환에 부담이 없죠.
자바를 사용하게 된다면 개인적으로 Optional은 읽기 불편하다는 생각이 있어서 인텔리제이에서 제공해주는 [`@Nullable`](https://www.jetbrains.com/help/idea/nullable-and-notnull-annotations.html)을 사용할 것 같긴합니다. 이걸 사용하면 인텔리제이가 경고를 잘 해주거든요.
여튼 null을 반환할 때 가장 중요한 점은 클라이언트가 실수하지 않게 알려줘야하는 거라고 생각해요.

2023-03-20 12:50 UTC, ddaaac commented on src/main/java/chess/domain/piece/Queen.java
> +    }
Pawn을 제외한 나머지 Piece들의 동작이 같은 것 같은데 묶는 것도 괜찮아보여요.

2023-03-20 12:50 UTC, ddaaac commented on src/test/java/chess/domain/piece/PawnTest.java
> +@SuppressWarnings("NonAsciiCharacters")
SuppressWarnings 👍

2023-03-20 12:51 UTC, merged