[1, 2단계 - 체스] 조이(김성연) 미션 제출합니다.
woowacourse/java-chess pull request #475
Opened 2023-03-17 06:53 UTC by yeonkkk

2023-03-17 07:46 UTC, yeonkkk commented on src/main/java/chess/controller/GameController.java
> +        }
현재 사용자에게 커맨드를 받고 END인 경우 게임을 종료해야하기 때문에 if문에 return을 사용하고 있습니다. 
그런데 가독성, 메서드 분리를 고려하면 이렇게 작성하는 것이 좋은 방법인지 잘 모르겠습니다. 혹시 해당 코드를 개선할 수 있는 더 좋은 방법이 있을지 궁금합니다!

2023-03-17 07:46 UTC, yeonkkk commented on src/main/java/chess/controller/GameController.java
> +        return command;
위 코드에서 `chessGame.getBoard().getBoardResult()`로 결과를 꺼내고 있습니다.   
그런데 이는 디미터 법칙을 벗어나는 것 같다고 느껴져 chessGame 내에 아래와 같이 메서드를 만드는 것을 고려해보았으나 이게 좋은 방법인지 확신이 들지 않아 우선 그대로 작성해두었습니다.   
 해당 코드를 개선하기 위해 괜찮은 방법인지 궁금합니다!
```
// ChessGame.java
public Map<Integer, String> getBoardResult() {
    return board.getBoardResult();
}
```

2023-03-17 07:46 UTC, yeonkkk commented on src/main/java/chess/domain/Board.java
> +    }
board의 내용을 출력하기 위해 해당 메서드를 만들었습니다. 그런데 이 것이 board의 책임이 맞는지, 그리고 출력을 위한 메서드가 좋은 방법인지 잘 모르겠습니다.. 혹시 dto를 사용하는 것이 좋을까요? 럿고의 의견이 궁금합니다.

2023-03-18 10:28 UTC, ksy90101 commented on src/main/java/chess/domain/ChessGame.java
> +        if (position.size() != 2) {
매직넘버는 잘 관리해주세요 :)

2023-03-18 10:28 UTC, ksy90101 commented on src/main/java/chess/domain/Command.java
> +    private final String command;
별건 아니지만, 굳이 필드를 가지고 있지 않고 name으로 가능하지 않을까요?
toUpperCase와 같은 걸 쓰면 괜찮을거 같은데요!

2023-03-18 10:29 UTC, ksy90101 commented on src/main/java/chess/domain/Pieces.java
> +import static chess.domain.square.Rank.TWO;
이런경우 그냥 *로 불러도 좋을거 같네요 ㅋㅋㅋ

2023-03-18 10:58 UTC, ksy90101 commented on src/main/java/chess/domain/Board.java
> +        for (Square key : pieces.keySet()) {
entrySet을 사용해보면 좋을거 같아요.

2023-03-18 10:58 UTC, ksy90101 commented on src/main/java/chess/domain/Board.java
> +    }
dto를 사용한번 해보시면 좋을거 같아요.
dto를 사용해 보시면서 장단점을 비교해보세요!

2023-03-18 11:01 UTC, ksy90101 commented on src/main/java/chess/domain/ChessGame.java
> +public class ChessGame {
이 클래스도 테스트 코드를 작성해볼수 있지 않을까요?

2023-03-18 11:03 UTC, ksy90101 commented on src/main/java/chess/domain/piece/Pawn.java
> +public class Pawn extends Piece {
Pawn이 대각선 공격을 할수가 없네요.

2023-03-18 11:07 UTC, ksy90101 commented on src/main/java/chess/domain/piece/Pawn.java
> +public class Pawn extends Piece {
확인해보니 전체적으로 공격이 안되어서....ㅠㅠㅠ
기능 테스트가 불가하네요... 한번 확인해주세요.

2023-03-18 11:09 UTC, ksy90101 commented on src/main/java/chess/domain/Pieces.java
> +    private final Map<Square, Piece> pieces = new HashMap<>();
이것또한 캐싱 해둘수 있지 않을까요?

2023-03-18 11:09 UTC, ksy90101 commented on src/main/java/chess/domain/movement/Continuity.java
> +        if (Math.abs(fileInterval) > 1 || Math.abs(rankInterval) > 1) {
매직넘버는 잘 관리해주세요!

2023-03-18 11:09 UTC, ksy90101 commented on src/main/java/chess/domain/movement/Movement.java
> +                .filter(movement -> movement.direction == direction)
&&로 작성해두면 좋지 않을까요?
굳이 두번 순회할 필요가 있나요?

2023-03-18 11:11 UTC, ksy90101 commented on src/main/java/chess/controller/GameController.java
> +        }
음... 전 지금도 나쁘지 않다고 생각합니다.
아니면 아래 do문에 넣을수도 있을거 같아요.

2023-03-18 11:11 UTC, ksy90101 commented on src/main/java/chess/controller/GameController.java
> +        }
참고로 게임을 시작하지 않았는데 End를 맨처음 입력하면 잘못된 입력이라고 생각합니다.

2023-03-18 11:12 UTC, ksy90101 requested changes
안녕하세요 조이 :)
이번 리뷰를 맡은 럿고입니다.
리뷰를 하던 중 보다 보니 공격을 할수가 없는거 같아요 😢 
그래서 간단한 리뷰만 남기긴 했습니다. 한번 기능 점검 부탁드려요.
질문이 있다면 언제든 DM주세요~

2023-03-22 13:16 UTC, yeonkkk commented on src/test/java/chess/domain/BoardTest.java
> +    }
테스트에 사용되는 Square 생성하는 메서드를 작성하였습니다. 
작성 목적은 1. 편리하게 사용하고 2. File, Rank로 인한 import 문 줄이기 3. 게임의 입력으로 받는 String을 input으로 하여 가독성을 높이기 입니다.

해당 메서드는 테스트를 용이하게 하기 위한 메서드 입니다. 
혹시 이렇게 테스트를 위한 메서드를 작성해서 사용하는 것 보다, 이전에 작성해둔 `Square.of()`를 사용하는 것이 더 좋을지 궁금합니다. 만약 이러한 방식을 사용하는 것을 추천하지 않으신다면 이유도 여쭤보고 싶습니다!🙂

2023-03-22 13:16 UTC, yeonkkk commented on src/test/java/chess/domain/piece/InitialPawnTest.java
> +    void canMove_byMovement_fail(int fileInterval, int rankInterval, boolean canAttack) {
테스트 시 display name 을 사용하여 메서드에 대한 설명을 작성하고 있습니다. 
뿐만 아니라 메서드 명을 통해서도 어떤 테스트에 대한 메서드인지 전달하고 있습니다.
이러한 경우 하나의 방법만 사용해도 무관할지 궁금합니다.

제 생각에는 두 가지 설명 방법을 다 사용하면 의미가 분명히 전달되어 좋겠지만, 작성하는 시간이 많이 소요되는 단점도 존재한다고 생각합니다. 그래서 한 가지 방법만 사용해도 괜찮을지, 혹은 시간을 더 투자해서 두 방법을 사용해 명확하게 의미를 전달하는 것이 좋을지 궁금합니다!

2023-03-23 01:18 UTC, ksy90101 commented on src/test/java/chess/domain/BoardTest.java
> +    }
실제 빌드 되는 코드들은 테스트 코드를 제외한 것들일꺼에요.
테스트 코드가 추가되면 즉 빌드할 코드가 많아지게 되는거죠.
또한 실제 프로덕션을 위한 코드만 모여 있어야 할텐데, 차후에 협업자 분이 이 메서드를 보고 의문점을 들수도 있어요.
이러다 보면 계속 코드가 쌓이게 될것이구요.

즉, 테스트를 위한 코드를 작성하지 않는것이 좋습니다!

2023-03-23 04:35 UTC, ksy90101 approved these changes
안냥하세요 조이 :)
체스 미션 고생 많으셨습니다.
전체적으로 잘 구현해주셔서 이만 머지하도록 하겠습니다 :)
언제든 추가적인 질문이 있다면 편히 연락주세요~

2023-03-23 04:35 UTC, merged