[1, 2단계 - 체스] 로이스(원태연) 미션 제출합니다.
woowacourse/java-chess pull request #480
Opened 2023-03-17 07:03 UTC by TaeyeonRoyce

안녕하세요, 리뷰이 로이스입니다!

리뷰 요청 드립니다! 세세한 부분도 편하게 남겨주시면 감사하겠습니다🙇‍♂️
궁금한 점은 코드에 코멘트 달아두겠습니다

2023-03-17 07:16 UTC, TaeyeonRoyce commented on src/main/java/chess/domain/piece/Empty.java
> +}
체스 게임에서 `Piece`를 일괄적으로 처리하기 위해 `Empty`라는 클래스가 생성되었습니다.
64개의 포지션과 32개의 기물만 두면 논리적으로 `빈 칸`을 활용할 지,
`Empty`라는 의미를 가진 객체(Null Objec)로 사용할 지 고민이 많았습니다.

`Empty extends Piece`라는 것 자체가 어색하지만 `Empty`를 활용하는 방향이 안좋은 방향인지 궁금합니다.

2023-03-17 07:16 UTC, TaeyeonRoyce commented on src/main/java/chess/domain/piece/Piece.java
> +    abstract boolean isPieceRule(Position from, Position to);
`Piece`를 상속한 객체들에게 `Rule`을 구현하라고 강제하기 위해  `abstract boolean isPieceRule(Position from, Position to)`를 만들었습니다. 외부에선 호출하지 못하게 디폴트 접근 제어자를 두었는데 괜찮을까요?

현재 구현한 기물들은
```java
public PieceMove getMovement() {
    isPieceRule();
}
```
와 같이 사용하고 있는데, 위 방식의 강제화(?)보다 좋은 방법이 있을지 궁금합니다!

2023-03-17 07:16 UTC, TaeyeonRoyce commented on src/main/java/chess/domain/piece/PieceSymbol.java
> +}
출력하기 위해서만 사용 되고 있는데, (Bishop -> B) 제거할 수 있는 방법이 있는지 궁금합니다...
View에서 체스 기물의 정보를 받았을 때, `instanceOf`를 사용하여 체크할 수 있지만 switch나 무수한 if문이 생길 것 같더라구요

2023-03-18 08:11 UTC, Hyeon9mak requested changes
안녕하세요 로이스~ 체스 미션을 함께할 현구막입니다 🙇‍♂️
체스 미션 완성도 있게 잘 구현해주셨네요~ 프로그램 동작 확인했습니다.
테스트 코드 몇 개가 실패하는 걸 발견했는데요, 수업관련 내용이라 우선 pass 했어요.
전체 테스트시 테스트가 동작하지 않도록 ignore 처리하는 방법을 고민해보는 것도 좋은 학습이 될 것 같습니다 😄 👍

체스 규칙 구현은 취향이 반영될 수 있어서 최대한 넘기고, 설계와 유지보수를 중점적으로 코멘트 남겼어요!
질문 주신 내용들에 대해서도 답변 남겼습니다 😉 

궁금하신 점 DM, 코멘트 남겨주세요 🙇‍♂️

2023-03-18 08:11 UTC, Hyeon9mak commented on src/main/java/chess/domain/piece/PieceSymbol.java
> +}
```java
public enum ViewPieceSymbol {
    PAWN(Pawn.class, "p"),
    BISHOP(Bishop.class, "b"),
    KING(King.class, "k"),
    KNIGHT(King.class, "n"),
    QUEEN(Queen.class, "q"),
    ROOK(Rook.class, "r"),
    EMPTY(Empty.class, "."),
    ;

    private final Class<? extends Piece> piece;
    private final String viewSymbol;

    ViewPieceSymbol2(Class<? extends Piece> piece, String viewSymbol) {
        this.piece = piece;
        this.viewSymbol = viewSymbol;
    }

    public boolean isPieceSymbol(Piece piece) {
        return this.piece.isInstance(piece);
    }
}
```

당장 떠오르는 건 이런 방법이 있겠네요.

2023-03-18 08:11 UTC, Hyeon9mak commented on src/main/java/chess/view/ViewPieceSymbol.java
> +        }
체스 규칙 enum class 와 출력용 enum class 분리 👍 

추후 기물 출력 방식이 이미지(이미지파일 경로)로 변경되면 흑과 백 기물 출력방식이 합쳐진게 문제가 되지 않을까요? 👀

2023-03-19 06:56 UTC, TaeyeonRoyce commented on src/main/java/chess/Application.java
> +    }
예상되지 않는 오류나 예외에 대해서 종료되지 않도록 맨 앞(?)단에서 `try-catch`하도록 작성 하였었습니다.

다시 보니깐 꼭 필요하진 않아보이네요..ㅎ

2023-03-19 06:56 UTC, TaeyeonRoyce commented on src/main/java/chess/controller/ChessCommand.java
> +    ;
저는 `view`에서 열어볼 것 같네요! 좋은 관점 제시해주셔서 감사합니다👍

2023-03-19 06:56 UTC, TaeyeonRoyce commented on src/main/java/chess/controller/ChessController.java
> +    }
코드로 보니 현구막의 의견에 공감되네요. 적용해보도록 하겠습니다

2023-03-19 06:56 UTC, TaeyeonRoyce commented on src/main/java/chess/domain/piece/Piece.java
> +    abstract boolean isPieceRule(Position from, Position to);
좋은 의견 감사드립니다! `package-private`하게 강력한 제약을 두면 말씀하신대로 `piece`의 의미가 일반적인 협력관계의 묶음과는 달라질 수 있겠네요. 다시 보니 상속은 안 했지만 협력하는 `Camp`나 `PieceSymbol`이 `package-private`에 왜 존재하는지에 대한 의문이 들 수 있겠군요.
위 코멘트와 더불어 패키지를 바라보는 새로운 관점을 얻어갑니다ㅎㅎ

2023-03-19 06:56 UTC, TaeyeonRoyce commented on src/main/java/chess/domain/piece/PieceSymbol.java
> +}
헉...👍

2023-03-19 06:56 UTC, TaeyeonRoyce commented on src/main/java/chess/view/ViewPieceSymbol.java
> +        }
외부에서 흑/백을 판단하는게 더 유연할 것 같네요!

2023-03-19 07:06 UTC, TaeyeonRoyce commented on src/main/java/chess/domain/PiecesPosition.java
> +    }
이동 가능한 여부는 `Chess`의 논리라고 생각했습니다..!
기물을 위치시킬 수 있는 판(`PiecePosition`)은 체스라는 게임의 규칙과 별개로 생각했습니다.

위 메서드를 보니 `기물을 옮기고, 집은 위치는 빈 칸으로 바뀜`이라는 체스게임의 특징이 스며든 것 같군요..

```java
public void movePieceTo(Position fromPosition, Position toPosition) {
  piecesPosition.put(toPosition, piecesPosition.get(fromPosition));
}

public void updateEmpty(Position position) {
  piecesPosition.put(fromPosition, new Empty());
}
```

요렇게 판의 책임과 체스게임의 책임을 분명하게 나눠볼 수 있을 거 같습니다!

2023-03-19 13:25 UTC, TaeyeonRoyce commented on src/main/java/chess/domain/piece/PieceSymbol.java
> +}
적용해보려고 하니 `isInstance`를 사용하는 것보단 타입을 두고 있는 게 나을 것 같았습니다.
출력에 대해 좀 더 고민해볼게요!

2023-03-19 13:47 UTC, TaeyeonRoyce commented on src/main/java/chess/domain/piece/Empty.java
> +}
그간 해왔던 고민과 현구막의 의견을 반영하여 `Empty is a Piece`라는 어색한 클래스를 지우려고 했습니다.
결론적으론 안했는데요. 이유는 다음과 같습니다.

64개의 `Position`과 Empty를 포함한 `Piece`를 key, value로 Map으로 가지는 `PiecesPosition`에서 Empty를 관리하지 않기 위해선 `(실제 기물이 존재하는 포지션만 관리, 이동 후 빈 공간은 제거)`과 같은 전략으로 초기에 32개의 `Position`만 저장 할 것 같습니다. 이제 Key인 `Position`으로 조회했을 때, null이면 빈 공간으로 인식하는거죠. 예상되는 64개의 `Position`과 다른 key로 조회하면 발생하는 null 모두 빈 공간으로 인식할 수 있다는 위험이 보이더라구요.
> ex. 
```java
Map<Position, Piece> positions = new HashMap<>();

Position searchPosition = null;
positions.getOrDefault(searchPosition, new Empty());
```
`Bishop`, `Pawn`, ... , `Empty`를 기대했는데 `Bishop`, `Pawn`, ... , else가 되어버린 것 같았습니다.

설령, 예상대로 조회되었다 해도 `Empty`라는 널 객체 없이 null값으로 도메인 레이어에서 출력 레이어까지 전달되면 위험하다는 생각이 들었습니다.

`Piece`를 인터페이스로 변경하여 `Empty`를 구현할 수 있지만, 그 방향이라면 현안이 더 좋다는 생각이 들었습니다!

2023-03-19 13:48 UTC, TaeyeonRoyce commented
코멘트와 리뷰 반영하여 재리뷰 요청 드립니다!

 반영하지 않은 `Null Object 패턴`과 뷰를 위한 `PieceSymbol` 제거 방식에 대한 의견에 대해선 reply 달아두었습니다.

2023-03-20 10:43 UTC, Hyeon9mak commented on src/main/java/chess/domain/piece/Empty.java
> +}
답변 코멘트를 제가 잘 이해하지 못했습니다. 아래 문장들 추가 설명 부탁드릴게요. 🙏 

- Key인 Position으로 조회했을 때, null이면 빈 공간으로 인식하는거죠.
- 그리고 나머지(else)가 되어버린 것 같았습니다.
- Piece를 인터페이스로 변경하여 Empty를 구현할 수 있지만, 그 방향이라면 현안이 더 좋다는 생각이 들었습니다!

우선 추가로 질문을 드리면

1. null 을 사용할 필요 없이 `PiecesPosition` 에게 해당 포지션에 기물이 있는지 물어볼 수 있지 않을까요?

```java
Position A8 = Position.of(File.A, Rank.EIGHT);
piecesPosition.containsKey(A8); // true, false
```

2. is-a 관계가 아니라 상속구조가 틀어져있는데 현안이 더 좋다고 생각하신 이유가 있을까요?

2023-03-20 10:44 UTC, Hyeon9mak commented on src/main/java/chess/domain/piece/PieceSymbol.java
> +}
`isInstance` 사용이 꺼려지는 이유가 있을까요?

2023-03-20 11:23 UTC, Hyeon9mak requested changes
안녕하세요 로이스!
체스와 체스판의 책임을 온전히 분리하고자 하셨군요. 독특한 관점을 많이 생각하시는 것 같아 구경하는 재미가 쏠쏠합니다. 👍

테스트가 실패하지 않도록 disabled 도 잘해주셨습니다! 여유가 되신다면 테스트를 스킵하지 않고 모든 테스트가 통과할 수 있도록 설정을 해보시는 것도 재밌을 것 같아요.

이번에도 체스 규칙은 최대한 넘기고, 설계와 유지보수를 중점적으로 코멘트 남겼습니다.
아래는 추가로 남긴 답변 코멘트들입니다.

- https://github.com/woowacourse/java-chess/pull/480#discussion_r1141929499
- https://github.com/woowacourse/java-chess/pull/480#discussion_r1141930522

저와 함께 view, controller, domain 계층간 책임에 대해 깊은 고민을 해보시죠! 😎 
궁금하신 점 DM, 코멘트 남겨주세요 🙇‍♂️

2023-03-20 11:23 UTC, Hyeon9mak commented on src/main/java/chess/controller/ChessController.java
> +        }
`ChessGame` 클래스가 갖고 있는 문자열 입력 관련 리뷰가 너무 넓은 의미로 전달돼서 패키지 위치를 변경하는 것으로 끝난 것 같아요. 🙏 결론부터 이야기 해보자면 view 도 Command 입력 방식을 관리해야하고, domain 도 자신만의 Command 를 가져야 합니다. 컨트롤러는 이 Command 를 잘 전달할 방법을 고민해야하구요.

controller 의 역할을 조금 컴팩트하게 이야기해보면 "요청사항을 domain 이 잘 알아듣도록 변환(재가공, 매핑)하여 전달한다." 겠죠. 이는 console application 이 아닌 web application 이 되었을 때도 동일합니다.

- "console 에 입력된 요청을 domain 이 잘 알아듣도록 변환(재가공, 매핑)하여 전달한다."
- "http 요청을 domain 이 잘 알아듣도록 변환(재가공, 매핑)하여 전달한다."

즉 view 계층은 어딘가로부터 들어오는 데이터를 잘 전달해주는게 목적이고, controller 계층에서 이를 누구에게 전달할지 결정하고, 포장합니다. 이 때 controller 도 유지보수 편의를 위해 view 로부터 전달되는 데이터를 원시값(String)이 아닌 DTO 형태로 받을 수 있습니다. 이 DTO 는 controller 의 변화에 영향을 받기 때문에 controller 계층에 포함되는게 맞습니다. 

Command 자체는 비즈니스에 해당됩니다. "사용자가 시작 명령을 내린다." 까지도 비즈니스 로직으로 볼 수 있고, 게임 규칙이 변화하면 Command 도 함께 변화합니다. 때문에 domain 클래스에서 게임 흐름과 관련된 Command 나 상태값을 가지는 것이 유리합니다.

View 에서도 사용자의 입력방식을 포장해서 controller 에게 넘겨주는 것이 좋습니다. 그래야 입력방식이 `start`, `end` 에서 `시작`, `종료` 로 변경되어도 controller 는 영향을 받지 않고 포장된 값을 전달 받을 수 있거든요.

<img width="1082" alt="image" src="https://user-images.githubusercontent.com/37354145/226324191-34b1ed82-fb02-4f02-afe5-f9215a472fac.png">

그럼 각각 클래스 파일들의 위치는 알겠는데, 각각 어디서 만들어서 전달해주느냐가 문제가 됩니다.
우선 domain 의 Command 는 간단하죠. domain 계층은 비즈니스 로직 수행에 집중해야하고, controller 의 DTO 에 대해 의존하고 싶지 않습니다. controller 패키지가 통째로 사라지더라도 domain 계층은 이를 알고 싶지 않습니다. 때문에 controller 에서 Command 를 잘 만들어 domain 계층에 전달해주는게 좋겠습니다. 

view 의 입력포장 클래스도 view 에서 알아서 처리하는게 좋겠습니다.

<img width="1073" alt="image" src="https://user-images.githubusercontent.com/37354145/226324260-8c44e281-f778-4ab8-abe4-0130beefd173.png">

controller 의 DTO 는 어디서 만들어줘야할까요? 현재 domain-view-controller 구조에서는 controller 가 맞습니다. view 계층은 controller 계층을 의존하지 않기 때문에 만들어줄 수 없어요. console 에 명령어를 입력할 때도, web 으로 HTTP 요청을 보낼 때도 어떤 controller 에 당도할지, 어떤 DTO 객체에 매핑할지 신경쓰지 않거든요. console 에 명령을 출력할 때도, web 으로 HTTP 응답을 보낼 때도 controller 가 각각 환경에 맞게 다시 변환해서 반환해줘야 합니다.

그렇지만 controller 는 domain 에 적합한 형태로 변환하고 흐름을 관장하는 것 만으로도 이미 할일이 굉장히 많아보여요. 나중엔 인증/인가와 관련된 내용까지 이해해야겠죠. 현재 요청이 어떤 형태의 view 로 들어와 어떤 형태의 view 로 나가는지 까지 알기엔 다소 벅찹니다. 결국 DTO 를 만들어주는 추가 존재의 도움이 필요해보여요.

<img width="1229" alt="image" src="https://user-images.githubusercontent.com/37354145/226324371-37b3e5e0-8fb7-45b8-92d6-d2df6df046dc.png">

다만 현재 구조에서는 추가 존재를 만드는 것이 다소 과해보이죠? 😅 controller 가 view 로부터 들어오는 요청을 혼자 DTO 로 감쌌다가 다시 풀어서 Command 로 바꾸는 행위도 어색하게 느껴집니다. 때문에 당장은 view 의 원시값을 그대로 전달하는 것도 방법이겠네요.

2023-03-20 11:23 UTC, Hyeon9mak commented on src/main/java/chess/view/input/command/ChessCommand.java
> +    }
체스 게임의 규칙(domain)에 해당하는 로직들인 것 같아요.

2023-03-20 11:23 UTC, Hyeon9mak commented on src/main/java/chess/view/output/BlackPieceSymbolView.java
> +    ;
😉 👍 
EMPTY 는 Black, White 가 아니지 않을까요?

2023-03-20 12:08 UTC, TaeyeonRoyce commented on src/main/java/chess/domain/piece/Empty.java
> +}
- `Key인 Position으로 조회했을 때, null이면 빈 공간으로 인식하는거죠.`
- `그리고 나머지(else)가 되어버린 것 같았습니다.`

```java
Map<Position, Piece> positions = new LinkedHashmap<>();
```
만약 위 `positions`에서 `Empty`를 제외한 32개의 `Position-Piece`정보를 담고 있다고 하면 이렇게 조회할 수 있을 거 같아요.
```java
public Piece getPieceOrEmpty(Position at) {
  return positions.getOrDefault(at, new Empty());
//  Empty를 아예 제거했다면,
//return positions.getOrDefault(at, null); 
}
```
이런식으로 저장된 key가 없는 경우를 빈 공간으로 간주하는 거죠.
그리고 제가 생각했던 안전하지 않은 경우는 아래의 경우입니다.
```java
Position empty = null;
PiecesPosition piecesPosition = new PiecesPosition();

assertThat(piecesPosition.pickPieceOrEmpty(empty))
              .isInstanceOf(Empty.class);
```
64개의 포지션에 존재하지 않는 경우를 `Empty`로 인식했는데, 이러한 상황 이외에도 발생할 수 있는 이외의 `null` 케이스를 `Empty`로 간주하게 되는것 같았습니다.

<br>

- `Piece를 인터페이스로 변경하여 Empty를 구현할 수 있지만, 그 방향이라면 현안이 더 좋다는 생각이 들었습니다!`
`+ 1. is-a 관계가 아니라 상속구조가 틀어져있는데 현안이 더 좋다고 생각하신 이유가 있을까요?`

Piece를 인터페이스로 두면 `is-a`관계만 개선 될 뿐, `Empty implements Piece`도 명확한 관계는 아니라고 생각했습니다. 또, 추상 클래스에서 공통으로 구현된 코드들이 구현체 마다 구현해야 하니 중복이 많이 발생할 것 같았습니다. 단순히 Piece를 인터페이스로 변경하는 것보단 현안이 좋다고 생각했습니다.

- `2. null 을 사용할 필요 없이 PiecesPosition 에게 해당 포지션에 기물이 있는지 물어볼 수 있지 않을까요?`
`Empty`를 지우면 `null`을 사용해야 될 것 같다고 생각해서 말씀드린 부분이었습니다! `null`이 돌아다니는 건 아닌것 같고... 설계 구조를 바꿔서 `Empty`클래스를 제거하지 않고 더 적합하게 선언하여 해결해보겠습니다!

2023-03-20 12:21 UTC, TaeyeonRoyce commented on src/main/java/chess/domain/piece/PieceSymbol.java
> +}
`isInstance()`와 `instanceOf`연산자와 큰 차이를 느끼진 못했습니다.
타입 체크는 열심히 해둔 추상화와 객체지향을 풀어버리는 성질이 있다고 생각합니다.

근데 또 도메인은 아니라 상관없을 것 같아 보이기도 하네욥...ㅎㅎ

2023-03-21 07:44 UTC, TaeyeonRoyce commented
피드백 반영하여 다시 리뷰요청 드립니다!

크게 달라진 점은 아래와 같습니다.

## Empty 제거
현구막이 제시한 방법으로 생각해보니 제거해도 괜찮을 것 같더라구요.
`contains`의 반환 값(true/false)인 기물 존재 여부라는 정보는 도메인 동작을 위한 충분한 정보였습니다.
비어있는 기물들도 View에서 표현하기 위해 64개 포지션을 가진 ChessBoard를 활용하였습니다.
View에 종속되도록 하였는데 의견 남겨주시면 감사하겠습니다!

## Controller 역할
리뷰를 보고 Controller에 대한 역할을 생각했습니다. Game을 조작하는 수단으로서 생각했었는데, ChessGame이 가져야 할 논리(실행, 멈춤 등)를 Controller만 가지고 있는건 위험하더라구요. 말씀대로 Dto를 하나 두고, Game이 필요한 GameCommand를 반환하도록 하였는데... 현구막의 말씀대로 독특한 구조인 것 같습니다.

변경사항이 많아 불편하실 수 있지만 리뷰 부탁드립니다!

2023-03-22 06:19 UTC, Hyeon9mak commented on src/main/java/chess/domain/piece/PieceSymbol.java
> +}
객체지향 프로그래밍은 결국 유지보수를 위한 프로그래밍이니 천천히 고민해보신 후 결정해주세요 😄 👍

2023-03-22 11:17 UTC, Hyeon9mak approved these changes
안녕하세요 로이스!
리뷰 반영이 쉽지 않으셨을텐데 너무 깔끔하게 잘 해주셨습니다 👍 💯 

로이스도 다음 단계로 가시죠~!

아래는 질문에 대한 답변입니다.

> Empty 제거

제 마음을 읽으셨군요 😁 👍 덕분에 체스판 표현방식이 바뀌면 ChessBoard(아마 ChessBoardStateFormatter 겠죠?)만 바꾸면 되겠네요!

> Controller 역할

"시작", "이동", "종료" 명령을 받아서 동작을 수행하는 것까지도 로이스가 만든 체스게임의 규칙이라 생각해요. controller 라는 네이밍 때문에 혼란을 줄 수 있지만 명령 또한 어디까지나 비즈니스 도메인이라 domain 에 위치하는게 옳다고 생각했어요. 저는 domain 패키지만 가지고도 함께 게임을 설계한 기획자, 디자이너, PM 등과 함께 대화가 가능해야한다고 생각해요. 😁 

controller 패키지가 통째로 사라져도, domain 패키지만으로도 "이동 좌표1 좌표2 를 주면 기물이 이동 하는구나!" 를 알 수 있게끔. 그러고 나면 controller 는 domain 에 대해 자세히는 모르지만, 정말 흐름만 담당하게 되겠죠. controller 는 domain, view 간 소통을 중계하기도 바쁘니까요.

구조가 독특하게 느껴지는 건 지금 짤 때보다 나중에 고칠 때를 생각해야하는 객체지향 언어의 특성인거 같아요. controller 와 view 에 대한 의존을 극단적으로 끊어내어 controller 를 바꿀 때 view 와 domain 이 영향을 받지 않고, view 를 바꿀 때 domain 이 영향을 받지 않도록 하는게 핵심이라...

controller 와 view 패키지를 접어두고 domain 패키지만 펼쳤을 때 어떤 느낌을 받으시나요? 저는 명령에 대한 객체를 domain 에 잘 옮겨주신 덕분에, 시작과 이동, 종료에 대한 명령이 게임에 존재하고 그걸 통해 게임의 상태가 관리된다는게 추측이 되어서 좋은 것 같아요. 나중에 "일시정지" 라는 명령이 생겼을 때 domain.game.command 패키지에 명령어를 추가하고 나머지 로직들을 수정할 수 있을 것 같아요.

물론 저의 생각일 뿐, 로이스가 생각하시기에 "이렇게 하는게 유지보수에 더 좋을 것 같던데?" 라고 생각되신다면 반영 후 저를 설득해주시면 됩니다 😄 👍 

다음 단계에서 만나요~

2023-03-22 11:18 UTC, merged

2023-03-22 11:55 UTC, TaeyeonRoyce commented on src/main/java/chess/controller/mapper/response/ChessBoardStateFormatter.java
> +    }
view에 두는 것에 동의합니다!