[1, 2단계 - 체스] 오션(김동해) 미션 제출합니다.
woowacourse/java-chess pull request #481
Opened 2023-03-17 07:09 UTC by donghae-kim

안녕하세요 토니 ! 우테코 5기 크루 오션🌊 입니다 !
이번에 체스 미션 PR을 보내게 되었습니다. 잘 부탁드립니다! 부족한 점 많이 지적해주시면 감사하겠습니다!

---
Points To Watch
---
- 시작과 종료에 대한 상태를 추가해 보았습니다. 저번 미션에서 상태 패턴을 보게 되어서 사용해보고 싶어서 적용해보았습니다. 하지만 시작, 종료 에 대한 상태로만 작성하였는데 블랙팀과 화이트팀의 순서를 상태로 적용하는 것에 대해 토니의 의견이 궁금합니다!
- 현재 체스 로직은 선택한 기물 -> 입력 좌표가 기물의 이동방법에 부합하는지(막히는 것 상관없음) -> 보드에서 기물이 이동하는 경로에 우리팀, 상대팀 등 이동이 불가할 경우 검증 -> 움직임 방식으로 진행하였습니다. 

Question
---
 - 저는 보드의 역할이 기물 진행경로 검증 & 움직임 이라고 생각합니다. 그러다보니 메소드가 많아졌는데 책임과 역할 분리를 잘못했다고 볼 수 있는지 궁금합니다.
 - 폰이 조금 복잡한 규칙을 가지고 있었습니다. 페어와 함께 효율적으로 어떻게 작성하면 좋을지 고민해봤으나, 복잡해질 수 밖에 없는 것 같다라는 생각을 하게 되었습니다. 이를 조금 더 효율적으로 작성할 방법이 있을지 궁금합니다.
 - 기물이 위치를 갖고 있는 것에 대해서 어떻게 생각하는지 궁금합니다! 저는 기물이 위치를 가지고 있을 필요가 없다고 생각합니다. 실제 보드판이라고 생각했을때 기물이 알필요가 없다고 생각하기 때문입니다.

2023-03-18 01:29 UTC, toneyparky requested changes
안녕하세요 오션, 체스 미션의 리뷰어 토니에요~!

미션 코드 잘 확인했습니다! 전반적으로 깔끔하게 구성되어 있어서 파악하기가 편했네요. 오션이 각 객체간의 책임을 잘 인지하고 있다고 느꼈어요 👍  

다만 기능적인 버그와 실패하는 테스트 케이스를 발견하여 이 부분은 우선순위 높혀 수정해주시면 좋겠네요. 
추가로 제가 남긴 질문에 대해 답변해주시면 감사하겠습니다.

행복한 하루 보내세요~

2023-03-18 01:29 UTC, toneyparky commented on README.md
> +- [x] 체스게임
복잡한 미션인데 요구사항을 잘 정리해주셨네요~!

2023-03-18 01:29 UTC, toneyparky commented on src/main/java/chessgame/controller/ChessController.java
> +        Game game = new Game(new Board(ChessBoardFactory.create()));
컨트롤러에서 `ChessBoardFactory` 객체를 알도록 `Board`에 직접 넣어준 이유가 있을까요?

2023-03-18 01:29 UTC, toneyparky commented on src/main/java/chessgame/domain/Board.java
> +public class Board {
질문주신 보드의 역할에 대해서 이야기해보죠:

오션이 정의해주신 `검증 & 움직임` 이라는 역할에는 잘 부합하고 있는 것 같아요. 객체의 행위를 보면 그렇게 하고 있으니까요. 다만 아쉬운 점은 테스트를 위해 몇몇 메서드가 public으로 노출되고 있다는 점이에요. 이 부분은 개선되면 좋겠네요. 만일 해당 메서드를 private으로 바꾼 뒤 테스트하기가 어렵다면 추상화 수준을 낮춰서 `Game`에게 `Board`를 더 상세하게 조작할 수 있는 책임을 부여할 수도 있겠어요.

2023-03-18 01:29 UTC, toneyparky commented on src/main/java/chessgame/domain/Board.java
> +        }
`Pawn`에 대한 검사를 먼저 수행하면 로직이 단순해질 수 있을까요?

2023-03-18 01:29 UTC, toneyparky commented on src/main/java/chessgame/domain/Board.java
> +        throw new IllegalArgumentException("움직일 수 없다.");
```suggestion
        throw new IllegalArgumentException("움직일 수 없습니다.");
```

예외 메시지는 읽는이를 고려해야해요. 지금은 해당 메시지가 프로젝트의 고객에게 직접 노출되고 있죠. 그렇기에 일관된 어조로 수정해주시면 고객이 당황하지 않을거에요.

2023-03-18 01:29 UTC, toneyparky commented on src/main/java/chessgame/domain/Board.java
> +            throw new IllegalArgumentException("폰은 직진으로 적을 잡을수 없습니다.");
명확한 에러메시지 좋네요. 커밋을 확인해보니 처음 구현시에는 없다가 예외를 발견하고 추가해주셨더라구요. 

현업에서도 우선은 예외가 발생할 수 있는 상황에 대해 러프하게 에러 메시지를 던지거나, 실제로 장애가 발생한 후(?) 구체적인 에러 메시지로 수정하곤 해요. 우리가 처음부터 모든걸 알면 좋겠지만 코드가 복잡해지면 그러기 더더욱 어렵기 때문이죠.

2023-03-18 01:29 UTC, toneyparky commented on src/main/java/chessgame/domain/Board.java
> +    public boolean checkRoute(Point source, Point target) {
룩이 폰을 통과할 수 있네요~!

```
RNBQKBNR
..PPPPPP
........
pP......
p.......
........
..pppppp
rnbqkbnr
move a8 a2

.NBQKBNR
..PPPPPP
........
pP......
p.......
........
R.pppppp
rnbqkbnr
```

2023-03-18 01:29 UTC, toneyparky commented on src/main/java/chessgame/domain/Board.java
> +    public boolean isContainsKey(Point point) {
단순하게 Map의 메서드를 바이패스하는 러프한 메서드로 보여요. 체스 도메인에 맞는 이름으로 수정해보죠!

2023-03-18 01:29 UTC, toneyparky commented on src/main/java/chessgame/domain/Team.java
> +    public String calculate(String convertedName) {
calculate은 어떤 의미에요?

2023-03-18 01:29 UTC, toneyparky commented on src/main/java/chessgame/domain/piece/Pawn.java
> +public class Pawn implements Piece {
질문주신 폰의 복잡도에 대해서 이야기해보죠 :

알고계시듯 폰은 실제로 로직이 다른 기물에 비해 복잡해요. 그렇기에 코드도 복잡해질 수 밖에 없습니다. 제가 보기에는 충분히 이해가 잘 되고 테스트도 잘 작성되어 있다고 느껴져요. 구현적으로 복잡도를 줄일 수 있는 부분은 아래에 코멘트 남겨볼게요~

2023-03-18 01:29 UTC, toneyparky commented on src/main/java/chessgame/domain/piece/Pawn.java
> +    public boolean isPawnAttack(Point source, Point target, Team team) {
private 메서드여야겠죠? 아래 `isPawnMove` 도 마찬가지네요~

2023-03-18 01:29 UTC, toneyparky commented on src/main/java/chessgame/domain/piece/Pawn.java
> +    private boolean canPawnMove(Point source, Point target, int distance, Rank rank) {
해당 메서드를 꼭 공용으로 만들어야하나요~?

`Pawn`은 어차피 팀을 알고 있으니 `canBlackPawnMove`, `canWhitePawnMove`와 같이 분리하면 메서드의 행위가 조금은 단순해질까해서요.

2023-03-18 01:29 UTC, toneyparky commented on src/main/java/chessgame/domain/piece/Pawn.java
> +        if (source.rankDistance(target) == distance && source.fileDistance(target) == distance) {
if문 안의 내용을 이해하기 위해서는 코드를 하나하나 해석해야하네요. private 메서드로 분리하여 가독성을 높혀보는건 어때요? 혹은 `Point`에게 메시지를 던져봐도 좋구요!

2023-03-18 01:29 UTC, toneyparky commented on src/main/java/chessgame/domain/piece/Piece.java
> +public interface Piece {
기물이 위치를 가져야하는가에 대한 부분에 대해 이야기해보죠 :

저도 지금 오션이 구현한 방법에서는 기물은 온전한 기물이고 보드가 위치에 대한 책임을 가지는 방향이 맞다고 생각해요. 오션은 도메인 구조를 이렇게 바라보시고 구현하셨구요. 

이 부분은 `예정되어 있는 요구사항`인 DB에 저장에 대해 미리 고민해보고 판단해봐도 좋겠네요. 예정되어있으니 위치를 포함하는게 DB에 잘 저장할 수 있을지 지금의 상태가 DB에 잘 저장할 수 있을지 미리 고민해보는거에요.

2023-03-18 01:29 UTC, toneyparky commented on src/main/java/chessgame/domain/state/Button.java
> +public class Button {
Button은 어떤 의미에요? 웹 페이지를 비유한걸까요?

2023-03-18 01:29 UTC, toneyparky commented on src/main/java/chessgame/domain/state/End.java
> +public class End implements State {
상태에 대한 테스트는 없을까요?

2023-03-18 01:29 UTC, toneyparky commented on src/main/java/chessgame/domain/state/State.java
> +public interface State {
상태에 대해 고민해주신 내용을 얘기해보죠!

말씀주셨듯 상태를 더 세분화할 수 있어요. `State` 인터페이스를 필두로 `Running`, `Finished` 와 같은 하위 상태가 있고 `BlackRunning`, WhiteRunning과 같은 상태가 `Running`을 구현하는거죠. 이러면 턴을 관리하는 로직이 상태쪽으로 넘어가지 않을까 싶네요~!

2023-03-18 01:29 UTC, toneyparky commented on src/main/java/chessgame/util/ChessBoardFactory.java
> +package chessgame.util;
Util은 어떤 의미의 객체들이 모이는 패키지에요?

`Point`, `Piece` 객체가 들어있는 체스 보드를 생성하는 역할도 담당할 수 있나요?

2023-03-18 01:29 UTC, toneyparky commented on src/test/java/chessgame/BishopTest.java
> +package chessgame;
테스트 패키지도 프러덕션 코드의 패키지와 동일한 위치에 놓이도록 수정해주세요.

2023-03-18 01:29 UTC, toneyparky commented on src/test/java/chessgame/BoardTest.java
> +        assertDoesNotThrow(() -> new Board(ChessBoardFactory.create()));
이건 `ChessBoardFactory`에 대한 테스트로 보이네요!

2023-03-18 01:29 UTC, toneyparky commented on src/test/java/chessgame/CommandTest.java
> +    @ValueSource(strings = {"move", "move a1", "move z1 z2", "move a1 a2 a3", "move a10 a11"})
테스트 케이스가 실패하네요 ㅠㅜ

2023-03-18 01:29 UTC, toneyparky commented on src/test/java/chessgame/PawnTest.java
> +class PawnTest {
`@Nested`를 이용한 DCI 패턴을 적용하여 테스트를 구체화해볼까요?

[관련 문서](https://johngrib.github.io/wiki/junit5-nested/)

2023-03-18 01:29 UTC, toneyparky commented on src/test/java/chessgame/QueenTest.java
> +    @DisplayName("Queen의 이동정책에 맞지 않으면, Queen은 움직일 수 없다.")
`Queen`의 이동 정책에 맞지 않는건 어떤 경우일까요? 테스트 코드를 보는 사람이 한번에 이해할 수 없고 이동 정책에 대한 내용을 파악하고 있어야하네요~!

2023-03-20 07:19 UTC, donghae-kim commented on src/main/java/chessgame/controller/ChessController.java
> +        Game game = new Game(new Board(ChessBoardFactory.create()));
따로 이유는 없었습니다!
game이 생성되면서 생성하면 될 것 같아서 수정하였습니다!

2023-03-20 07:21 UTC, donghae-kim commented on src/main/java/chessgame/domain/Board.java
> +        throw new IllegalArgumentException("움직일 수 없다.");
생각하지 못했던 부분 이였던 것 같습니다!
일관성 있도록 수정하였습니다!

2023-03-20 07:33 UTC, donghae-kim commented on src/main/java/chessgame/domain/Board.java
> +    public boolean checkRoute(Point source, Point target) {
수정하였습니다 !

2023-03-20 07:43 UTC, donghae-kim commented on src/main/java/chessgame/domain/Board.java
> +    public boolean isContainsKey(Point point) {
지나가는 길에 기물이 길을 막고 있는 것을 검증하는 식이므로 
isBlockedPiece 로 수정하였습니다~

2023-03-20 07:48 UTC, donghae-kim commented on src/main/java/chessgame/domain/Team.java
> +    public String calculate(String convertedName) {
대문자, 소문자 팀을 구별해주는 converter역할을 하는 것 입니다!
convertTeamName이라고 명시적으로 표현했습니다!

2023-03-20 09:14 UTC, donghae-kim commented on src/test/java/chessgame/CommandTest.java
> +    @ValueSource(strings = {"move", "move a1", "move z1 z2", "move a1 a2 a3", "move a10 a11"})
수정하였습니다 !

2023-03-20 09:19 UTC, donghae-kim commented on src/test/java/chessgame/QueenTest.java
> +    @DisplayName("Queen의 이동정책에 맞지 않으면, Queen은 움직일 수 없다.")
테스트 코드에서 기물의 움직임에 대해 이동정책이라고 작성한 부분을 더 명확하게 수정하였습니다!

2023-03-20 09:39 UTC, donghae-kim commented on src/main/java/chessgame/domain/Board.java
> +        }
excutePawnMove, executeMove로 분리하여 구현하였습니다. 하지만 중복 코드가 조금 있는 것 같은데 괜찮은지 궁금합니다!

2023-03-20 09:42 UTC, donghae-kim commented on src/main/java/chessgame/domain/piece/Pawn.java
> +    public boolean isPawnAttack(Point source, Point target, Team team) {
king, knight, pawn 모두 수정했습니다!

2023-03-20 09:57 UTC, donghae-kim commented on src/main/java/chessgame/domain/piece/Pawn.java
> +    private boolean canPawnMove(Point source, Point target, int distance, Rank rank) {
처음에는 `canBlackPawnMove``canWhitePawnMove`로 나누어서 구현했었습니다.
하지만 같은 기능을 하는 것이 흰팀움직임,검은팀움직임, 흰팀 공격, 검은팀  공격 처럼 2개씩 거의 중복되는 코드가 생긴다고 생각하는데 이래도 분리하는 것이 옳을지 궁금합니다!

2023-03-20 10:09 UTC, donghae-kim commented on src/main/java/chessgame/domain/piece/Pawn.java
> +        if (source.rankDistance(target) == distance && source.fileDistance(target) == distance) {
Point 에게 메세지를 던지기 보단 Pawn 내부에서 처리 할 수 있을 것 같아서 메소드 분리하는 방식으로 처리 했습니다!

2023-03-20 10:10 UTC, donghae-kim commented on src/test/java/chessgame/BishopTest.java
> +package chessgame;
수정하였습니다!

2023-03-20 10:19 UTC, donghae-kim commented on src/test/java/chessgame/BoardTest.java
> +        assertDoesNotThrow(() -> new Board(ChessBoardFactory.create()));
옮기면서 ChessBoardFactory테스트도 추가하였습니다!

2023-03-20 10:28 UTC, donghae-kim commented on src/main/java/chessgame/domain/piece/Piece.java
> +public interface Piece {
지금의 상태를 db에 저장하는게 더 잘 될 것 같다는 생각을 하게 되었습니다!
현재 저는 Map으로 보드판과 기물의 위치를 가지고 있는데 Map을 그대로 Table에 저장,불러오기 를 한다면 각각의 기물과 좌표를 저장하는 것보다 낫다고 생각합니다!
아직 Db를 어떻게 적용해야 할 지 잘 모르겠는데 이 두가지 방법을 시행했을때 db에서의 명확한 차이점이 있을까요 ?

2023-03-20 11:07 UTC, donghae-kim commented on src/main/java/chessgame/util/ChessBoardFactory.java
> +package chessgame.util;
저는 util패키지는 프로젝트 전역에서 사용되는 유용한 기능들을 담고 있다고 생각했습니다.
그러다 보니 ChessBoardFactory 는 이름에 맞지 않는다고 생각해서 factory패키지로 정정하였습니다.

혹시 토니의 패키지 명을 명명법이 있다면 알 수 있을까요 ?

2023-03-20 12:31 UTC, donghae-kim commented on src/main/java/chessgame/domain/state/Button.java
> +public class Button {
버튼을 누른다는 방법으로 상태를 바꾸는 형식을 사용했었습니다.
이를 Black,White 상태를 추가함으로써 변경해보았습니다!

2023-03-20 12:35 UTC, donghae-kim commented on src/main/java/chessgame/domain/state/State.java
> +public interface State {
Black과 White의 상태를 추가하고 싶었습니다. 이 상태가 결국 Start상태를 의미하는 것 같아 Start상태는 제거하였습니다.
Ready -> White -> Black -> White -> ... -> End 가 되는 방식으로 구현해 보았습니다!

2023-03-20 13:12 UTC, donghae-kim commented on src/test/java/chessgame/PawnTest.java
> +class PawnTest {
Nested를 이용하여 DCI 패턴을 이용하여 체스 기물이 이동하는 것을 계층화 하여 테스트 해보았습니다!
처음 사용해보니 잘 적용 하였는지 모르겠습니다.. 🥲

2023-03-21 11:32 UTC, toneyparky commented on src/main/java/chessgame/domain/Board.java
> +    private boolean checkRoute(Point source, Point target) {
해당 클래스의 다른 `check-`로 시작하는 메서드는 void인데반해 이 메서드는 불린을 반환하는군요. 이럴 경우 코드를 읽는 사람이 어떤  느낌을 받을까요?

2023-03-21 11:32 UTC, toneyparky commented on src/main/java/chessgame/domain/state/Black.java
> +            board.move(command.makePoints().get(0), command.makePoints().get(1), Team.BLACK);
command에서 source와 target을 가져오도록 처리하면 어때요? 해당 부분의 구현이 노출되어 있는걸로 보여서요.

2023-03-21 11:32 UTC, toneyparky commented on src/main/java/chessgame/domain/piece/Piece.java
> +    boolean isKnight();
질문 주신 부분에 대해 이야기해보죠. 

이 부분은 코드를 깔끔하게 하기 위해 타협했다고 생각해요. 사실 `Piece`가 구현체인 `Pawn, Knight`의 존재를 알고 있음이 메서드 이름을 통해서 표현되죠. 이는 좋은 방식은 아니라 생각해요. 하지만 그렇지 않을 경우 인스턴스 타입을 체크하는 로직이 필요하구요. 

Piece 가 하위 구현체를 알지만 타입 체크를 하는 것 보다는 더 자유적으로 움직일 수 있기에 지금의 구현도 나쁘지 않다고 생각합니다.

2023-03-21 11:32 UTC, toneyparky commented on src/main/java/chessgame/domain/Board.java
> +        }
폰과 관련된 로직이 구분된 이유는 `hasTarget` 때문이라 생각해요. 이 부분에 대한 검증을 폰으로 옮기는건 어때요?

2023-03-21 11:32 UTC, toneyparky commented on src/main/java/chessgame/domain/Board.java
> +        throw new IllegalArgumentException("움직일 수 없다.");
네, 예외 메시지는 의미 있게 작성하는 것도 중요하지만 고객에게 보여지는 메시지일 경우에는 더 신경써야겠죠~?

2023-03-21 11:32 UTC, toneyparky commented on src/main/java/chessgame/domain/Team.java
> +    public String calculate(String convertedName) {
오호 보다 이해가 잘 되네요. 여기서 질문 하나를 더 드릴게요~
기물의 팀을 대문자, 소문자로 구별한다는 로직은 도메인 요구사항인가요? 혹은 뷰의 요구사항인가요?

2023-03-21 11:32 UTC, toneyparky commented on src/main/java/chessgame/domain/piece/Pawn.java
> +    private boolean canPawnMove(Point source, Point target, int distance, Rank rank) {
음 이 부분은 인자가 4개나 되어서 간추릴 수 있으면 좋겠다는 생각에 리뷰를 드렸는데 오히려 중복이 발생하는군요. 분리하지 않는편이 더 낫겠어요.

2023-03-21 11:32 UTC, toneyparky commented on src/main/java/chessgame/domain/piece/Pawn.java
> +        if (source.rankDistance(target) == distance && source.fileDistance(target) == distance) {
`Point `의 `isHorizontal`과 `isVertical` 같은 메서드가 있는데 이런 메서드를 안 만들고 이렇게 따로 비교하는 이유는 뭐에요~? 

분리한 `checkRankLengthOne` 메서드는 인자로 받는 `distance`가 1임을 보장할 수 있나요?

2023-03-21 11:32 UTC, toneyparky commented on src/main/java/chessgame/domain/piece/Piece.java
> +public interface Piece {
DB와 관련해서는 도메인에 대한 고민을 할 때에 미리 예정된 요구사항에 대해 미리 고민해보면 좋겠다는 의도에서 코멘트를 남겼어요. 지금 상황에서는 명확한 차이는 없겠네요. 차이는 DB에 체스 판의 각 칸을 저장하느냐, 기물을 저장하느냐일 것 같아요.
칸을 저장할 경우에는 (a, 1, Rook), (a, 2, pawn), (a, 3, empty) 와 같이 저장하겠죠?
기물로 저장할 경우에는 empty는 굳이 저장할 필요가 없구요. 

오션은 `Board` 중심으로 로직이 진행되기에 전자처럼 모든 보드의 값을 저장하고 Map으로 만드는 방향이 바람직하겠네요~!

2023-03-21 11:32 UTC, toneyparky commented on src/main/java/chessgame/domain/state/Button.java
> +public class Button {
재미있는 비유지만 버튼이라는 UI 적인 요소가 도메인인 상태에 들어갔다고 보여져요. 상태를 바꾸는 데에 버튼을 눌러야만 하는건 아니니까요 😀

2023-03-21 11:32 UTC, toneyparky commented on src/main/java/chessgame/domain/state/End.java
> +public class End implements State {
네, 상태 변경은 중요한 로직이에요. 이 부분에 대해서는 필히 테스트해야합니다 👍 

상태 테스트에 대해서는 더 남기고픈 이야기가 있는데 관련 코드에 남길게요~!

2023-03-21 11:32 UTC, toneyparky commented on src/main/java/chessgame/domain/state/State.java
> +public interface State {
오 좋네요~! 
이런 상태의 변화를 `전이한다`라고 표현해요. 혹시 해당 상태에 대한 전이도를 인터페이스에 주석으로 남겨주실 수 있을까요~? 지금은 그닥 복잡하지 않지만 추후에 상태가 복잡해질 때를 대비해서 연습한다고 생각해보죠~!

아래와 같이 인터페이스를 구현하는 구체 클래스가 전이되는 정책을 아래와 같이 다이어그램으로 표현할 수 있어요. 

```
/**
 *
 *                                   +-----------+
 *                                   | SUBMITTED |
 *                                   +-----+-----+
 *                                         |
 *                                         |
 *                                         v
 *                                   +-----+-----+
 *                                   |  PENDING  |
 *                                   +-----+-----+
 *                                         |
 *                                         v
 *                             ------------+------------
 *                             |                       |
 *                             |                       |
 *                             v                       v
 *                     +-------+----+      +--------+---+
 *                     |  RUNNING   | ---> |  ABORTING  |----------------
 *                     +----+-------+      +------+-----+               |
 *                          |                     |                     |
 *                          v                     v                     |
 *                     --------+-----------------------+                |
 *                     |                               |                |
 *                     |                               |                |
 *                     |                               |                |
 *                     |                               |                |
 *                     |                               |                |
 *                     |                               |                |
 *                     v                               v                v
 *             +-------------+                   +----------+     +-----+------+
 *             |  SUCCEEDED  |                   |  FAILED  |     |  ABORTED   |
 *             +-------------+                   +----------+     +------------+
 *
 */
```

2023-03-21 11:32 UTC, toneyparky commented on src/main/java/chessgame/util/ChessBoardFactory.java
> +package chessgame.util;
네 해당 팩토리는 프로젝트 전역에서 사용하는 역할이 아니죠. 게다가 유틸은 도메인 로직과 관계를 최소화하여 간단한 기능을 가지고 있어야해요. 그러므로 util에 둔 선택은 좋지 않았습니다. 지금도 factory로 옮겨주셨네요. 해당 패키지는 모든 팩토리 객체들이 다 들어가는걸까요? 

`ChessBoardFactory`의 이름이나 형식보다 본질에 집중하면 좋겠어요. 핵심은 File와 Rank을 이용해서 체스 보드를 생성해주고, 어떤  기물이 어디에 위치해야할지와 같은 `도메인 로직`을 담고 있죠.

2023-03-21 11:32 UTC, toneyparky commented on src/test/java/chessgame/BishopTest.java
> +package chessgame;
새로 추가한 `StateTest`와 `ChessBoardFactoryTest` 같은 클래스도 신경써주실 수 있을까요~?

오션은 왜 테스트와 프러덕션 코드가 동일한 위치에 놓여야한다고 생각하시나요?

2023-03-21 11:32 UTC, toneyparky commented on src/test/java/chessgame/BoardTest.java
> +        assertDoesNotThrow(() -> new Board(ChessBoardFactory.create()));
네 좋네요. `@Nested`를 활용해서 팀 별로 테스트를 구분한 부분이 이해도를 높히네요 👍 

해당 테스트를 진행하며 룩, 폰, 나이트만 테스트해주신 이유는 있을까요? 만일 `ChessBoardFactory`가 킹과 퀸의 위치를 바꿔서 생성하더라도 테스트에서는 검증할 수 없겠네요.

2023-03-21 11:33 UTC, toneyparky commented on src/test/java/chessgame/QueenTest.java
> +    @DisplayName("Queen의 이동정책에 맞지 않으면, Queen은 움직일 수 없다.")
네 훨씬 이해하기 좋네요~!

2023-03-21 11:33 UTC, toneyparky requested changes
안녕하세요 오션~! 

어려운 리뷰도 있었는데 잘 확인해주셨네요! 고생하셨어요. 
남겨주신 질문 추가로 확인하고 답변 달았습니다. 그리고 아직 수정하면 좋을 부분이 있어서 추가 코멘트 남겼으니 확인 부탁드려요 😊

2023-03-21 11:52 UTC, toneyparky commented on src/main/java/chessgame/domain/piece/Piece.java
> +    boolean isKnight();
혹은 `PieceType` 과 같은 이넘 객체를 만들고 이를 `Piece`의 필드로 둔 후 이를 이용할 수도 있겠네요.

2023-03-22 04:17 UTC, donghae-kim commented on src/main/java/chessgame/controller/ChessController.java
> +        Game game = new Game(new Board(ChessBoardFactory.create()));
코드를 작성하는데 이유가 부족했던 것 같습니다..😂

토니가 말한 내부적으로 팩토리 사용해서 만든다는 것이
```
public Board() {
        this.board = new Board(ChessBoardFactory.create());
    }
```
이런식이 맞을까요 ?
이를 외부에서 주입해준 것이 아닌 내부에서 구현하는 것에 장점이 있는지 궁금합니다.
저는 팩토리를 사용해서 만든 Board를 Board 내부에서 생성 한 것이 아닌 Game에서 넣어줌으로써 의존성이 줄어들고, 재사용성이 높아질 수 있다고 생각해서 이렇게 구현하였습니다!

2023-03-22 04:46 UTC, donghae-kim commented on src/main/java/chessgame/domain/Board.java
> +        if (((Pawn) piece).isAttack(source, target) && hasTarget) {
공격이라는 행위는 폰외에 다른 기물도 하지만 다른 기물들은 움직임이 움직임과 공격 같은기능을 담당하고 있어서 분리 시 코드 중복이 많아질 것 같아 움직임으로 하나로 진행하고 싶었습니다.
그래서 `isMovable` 에 `hasTarget`을 파라메터로 받아서 `Pawn`에서 공격 과 움직임을 처리하는 방식으로 진행하였습니다.

2023-03-22 04:51 UTC, donghae-kim commented on src/main/java/chessgame/domain/Board.java
> +        }
`hasTarget` 을 `isMovable`안으로 넣음으로써 `pawn`에서 공격과 움직임을 처리할 수 있도록 하였습니다. 자세한 것은 연결된 코멘트에 달아봤습니다!

2023-03-22 04:56 UTC, donghae-kim commented on src/main/java/chessgame/domain/Board.java
> +    public boolean checkRoute(Point source, Point target) {
지금에는 요구사항을 보고 있을 수 있는 모든 경우를 생각하고 테스트코드를 작성하는 것이 옳지 않을까 하는 생각이 듭니다.
지금과 같은 경우에는 **기물별로 진행 방향에 적 팀이 존재할 경우 이동 불가** 와 같은 경우를 생각하고 테스트 코드를 짰더라면 방지할 수 있을 것 같습니다.

2023-03-22 05:13 UTC, donghae-kim commented on src/main/java/chessgame/domain/Team.java
> +    public String calculate(String convertedName) {
기물의 팀을 대,소문자로 구별한다는 것은 뷰의 요구사항인 것 같습니다.
블랙팀 - 대문자, 화이트팀 - 소문자로 구성되어있는데 만약 이게 바뀐다면 ?  수정을 위해 뷰를 먼저 볼 것 이라고 생각 했기 때문에 수정하여 뷰에서 처리하도록 하였습니다!

2023-03-22 05:36 UTC, donghae-kim commented on src/main/java/chessgame/domain/piece/Pawn.java
> +        if (source.rankDistance(target) == distance && source.fileDistance(target) == distance) {
처음에는 `Pawn`하나만을 위한 메소드를 `Point`에 구현해도 될까 ? 라는 생각으로 `Pawn`에 두게 되었습니다. 하지만 이는 다른 `isHorizontal`같은 메소드 들 처럼 `Point`관련 이기에 `Point`에 구현해도 될 것 같아서 수정하였습니다.

인자로 받는 distance는 제가 상수로 넣어준 BLACK_DISTANCE, WHITE_DISTANCE입니다. 이 값들은 제가 수정하지 않는 이상 변하지 않는다고 생각하는데 이럴 경우 1임을 보장할 수 있는 것 아닌가요 !?

2023-03-22 05:40 UTC, donghae-kim commented on src/main/java/chessgame/domain/state/Button.java
> +public class Button {
버튼이라는 요소가 적절하지 않은 것 같아서 저번 요청에서 제거 하여 진행했습니다!

2023-03-22 06:13 UTC, donghae-kim commented on src/test/java/chessgame/BoardTest.java
> +        assertDoesNotThrow(() -> new Board(ChessBoardFactory.create()));
따로 이유는 없었습니다.
이정도만 하면 충분하겠지 라는 생각을 가지고 있었던 것 같습니다 ㅠㅠ.😰
테스트 코드 다양한 케이스를 커버할 수 있도록 작성하겠습니다!

2023-03-22 06:17 UTC, donghae-kim commented on src/test/java/chessgame/PawnTest.java
> +class PawnTest {
이해하였습니다! 감사합니다

2023-03-22 06:37 UTC, donghae-kim commented on src/main/java/chessgame/domain/Board.java
> +    private boolean checkRoute(Point source, Point target) {
코드를 계속 리팩토링 하다 보니 실수한 것 같습니다!
코드를 읽는 사람이 이해하는데 시간도 오래걸리고 헷갈릴 수 있어서 메서드명을 지키는게 중요한 것 같습니다!

2023-03-22 06:47 UTC, donghae-kim commented on src/main/java/chessgame/domain/state/Black.java
> +            board.move(command.makePoints().get(0), command.makePoints().get(1), Team.BLACK);
command에서 source, target을 저장하는 points 를 통해 가져올 수 있도록 변경하였습니다.

2023-03-22 07:05 UTC, donghae-kim commented on src/test/java/chessgame/StateTest.java
> +    @Test
`@Nested`를 이용하여 ready, black, white, end 각 각 상태에 대해 전이와 예외를 테스트 하였습니다.
계층을 나누어 테스트를 하니 확실히 좋은 것을 알았습니다!!

2023-03-22 07:11 UTC, donghae-kim commented on src/main/java/chessgame/domain/piece/Piece.java
> +    boolean isKnight();
토니의 의견도 좋은 것 같지만 현재의 구현 방식을 그대로 유지하기로 결정했습니다.!

2023-03-22 07:53 UTC, donghae-kim commented on src/main/java/chessgame/domain/state/State.java
> +public interface State {
ready -> white, error, end
white -> black, error, end
black -> white, error, end
end -> error 
경우를 작성해봤습니다.

2023-03-22 08:08 UTC, donghae-kim commented on src/test/java/chessgame/BishopTest.java
> +package chessgame;
테스트와 프로덕션 코드가 동일한 위치에 있으면 테스트 사용자가 좀 더 쉽게 테스트를 구분하고 확인 가능하며 같은 패키지의 코드들을 테스트 할 수 있으므로 응집성도 좋아진다고 생각하빈다. 그래서  동일한 위치에 놓여있는 것이 좋다고 생각합니다.

2023-03-22 08:13 UTC, donghae-kim commented on src/main/java/chessgame/util/ChessBoardFactory.java
> +package chessgame.util;
토니 말처럼 도메인 로직을 담고있는 것 같아서 도메인쪽으로 패키지를 이동하게 되었습니다.
하지만 여전히 패키지를 어떻게 분리해야할지에 대한 고민이 있습니다..

2023-03-22 08:19 UTC, donghae-kim commented
안녕하세요 토니! 오션입니다!
먼저 꼼꼼한 리뷰 감사드립니다!
이번에 크게 변경한 것은
- 폰과 board에서 움직임, 공격 메소드를 수정하였습니다.
- 기물의 이름 변경 책임을 view로 옮겼습니다.
- 테스트 코드를 추가하였습니다.
----

DM에도 남겼듯이 아직 명확한 기준이 없어 패키지를 어떻게 정해줘야 하는지에 대한 고민이있습니다. 

감사합니다!

2023-03-22 20:57 UTC, toneyparky commented on src/test/java/chessgame/state/StateTest.java
> +        }
```suggestion
    @DisplayName("ready 상태 일 경우")
    class ReadyState {
        State state = new Ready();

        @Test
        @DisplayName("start 입력시 white 상태로 전이된다")
        void Should_ChangeWhiteState_When_ReadyState() {
            Board board = new Board(ChessBoardFactory.create());

            State start = state.run(Command.of("start"), board);
            assertThat(start).isInstanceOf(White.class);
        }

        @Test
        @DisplayName("move 입력시 예외가 발생한다")
        void Should_ThrowException_When_ReadyState() {
            Board board = new Board(ChessBoardFactory.create());
            assertThatThrownBy(() -> state.run(Command.of("move a2 a4"), board))
                    .isInstanceOf(IllegalArgumentException.class)
                    .hasMessage("move를 입력할 수 없습니다.");
        }
```

DCI를 적용하여 컨텍스트를 잘 나눠주셨어요 👍
조금 더 나가면 각 테스트의 내부 설명만 읽어도 해당 테스트를 이해할 수 있도록 작성해줘도 좋겠어요!

2023-03-22 20:59 UTC, toneyparky commented on src/main/java/chessgame/domain/state/Black.java
> +            throw new IllegalArgumentException("start를 입력할 수 없습니다.");
`IllegalArgumentException`, `IllegalStateException`, `UnsupportedOperationException` 셋의 차이에 대해 학습하시고 내용을 댓글로 남겨주세요~!

이 상황에서는 어떤 예외를 던지는게 베스트일까요?

2023-03-22 20:59 UTC, toneyparky commented on src/main/java/chessgame/controller/ChessController.java
> +        Game game = new Game(new Board(ChessBoardFactory.create()));
네 맞아요. 내부에서 만든다면 외부에 생성자로 `Map<Point, Piece> board`를 노출하지 않고 `Board` 자체만으로도 온전하게 생성할 수 있다는 장점이 있을 것 같아요. 하지만 이는 오션이 본 의존성과 같은 다른 관점에서는 단점으로 비춰질 수 있다고도 생각합니다. 그래서 위의 코멘트에서 장단점이 있다고 말씀드렸구요. 내부에서 생성시의 장점을 적지 않아 궁금하셨나봐요~!

재질문 주신 것도, 지금 정도로 수정해주신 것도 좋습니다!

2023-03-22 20:59 UTC, toneyparky commented on src/main/java/chessgame/domain/Board.java
> +    public boolean checkRoute(Point source, Point target) {
기물, 팀별로 요구사항을 나눠서 들어가는거죠! 좋네요. 특정 기물을 가정하고, 특정 팀을 가정하고....! 마치 DCI 패턴이 적용되기 좋아보여요 😉

2023-03-22 21:00 UTC, toneyparky commented on src/main/java/chessgame/domain/Team.java
> +    public String calculate(String convertedName) {
좋습니다~ 요 부분 맘에 드네요! 뷰의 로직이 도메인에 침투하지 못하도록..!

2023-03-22 21:00 UTC, toneyparky commented on src/main/java/chessgame/domain/piece/Pawn.java
> +        if (source.rankDistance(target) == distance && source.fileDistance(target) == distance) {
이 부분은 `checkRankLengthOne` 함수 입장에서 인자를 제한하지 않기에 1임을 보장하지 않죠. 말씀해주신 것 처럼 사용자가 `BLACK_DISTANCE` 과 같은 1을 넣어주지만 다른 사람이 개발하며 2를 넣어줄 수도 있는거니까요. 그렇기에 정말 1임을 보장하고 싶다면 함수 내부에서 처리해야할 것이며, 그렇지 않다면 함수의 이름을 바꿔서 포괄적으로 사용할 수 있도록 할 거에요.

2023-03-22 21:00 UTC, toneyparky commented on src/test/java/chessgame/BishopTest.java
> +package chessgame;
맞죠! 자바가 제시하는 접근 지시자를 사용할 수도 있고 찾아가기도 편해요. 이 부분은 인텔리제이가 테스트 파일을 생성해주는 기능을 이용하면 자동으로 같은 패키지에 생성해줘요.

클래스 이름에 커서를 올리고 `옵션+엔터`를 누르면 아래와 같은 선택창이 나온답니다~

<img width="891" alt="image" src="https://user-images.githubusercontent.com/37579660/227032881-dbe9d49d-ea30-4bf4-9bcb-3bc93a40034f.png">

2023-03-22 21:00 UTC, toneyparky commented on src/test/java/chessgame/PawnTest.java
> +class PawnTest {
굳굳 이렇게 구성하면 상위 컨텍스트에서 만든 pawn을 재사용할 수 있죠! 매 테스트마다 개념이 완전히 새롭게 생기기보다 범위가 깊어질수록 기존 컨텍스트에 조금씩 추가되기에 사람이 인지하기도 편하구요.

2023-03-22 21:00 UTC, toneyparky commented on src/main/java/chessgame/domain/state/Black.java
> +            board.move(command.makePoints().get(0), command.makePoints().get(1), Team.BLACK);
네 추상화 수준을 한단계 끌어올렸네요. `getSourcePoint`, `getTargetPoint`라는 메서드로 어떤 행위를 하는지 직관적으로 알 수 있어요 😀

2023-03-22 21:00 UTC, toneyparky commented on src/test/java/chessgame/StateTest.java
> +    @DisplayName("end 입력 시 종료 상태가 되는지 테스트")
이 부분도 위에서 DCI 패턴 적용해주시면서 보강해주셨네요!

상태 패턴은 전이되는 상태만큼 전이 안되는 상태에 대해서 검증하는 것도 중요하다고 생각해요. 잘 해주셨습니다!

2023-03-22 21:00 UTC, toneyparky commented on src/main/java/chessgame/domain/piece/Piece.java
> +    boolean isKnight();
네 저도 요정도 타협은 괜찮다고 생각합니다.

2023-03-22 21:01 UTC, toneyparky commented on src/main/java/chessgame/domain/Board.java
> +        if (((Pawn) piece).isAttack(source, target) && hasTarget) {
맞아요 추상 메서드의 인자가 모든 경우에서 사용되지 않는 경우에는 상속을 활용하는 게 맞나라는 고민이 들죠. 하지만 형변환 같은 부분을 외부에 노출하지 않고 기물 내부에서 처리할 수 있도록 한다는 장점이 더 크다고 생각해요. 하나를 얻고 하나를 내줬습니다.

2023-03-22 21:03 UTC, toneyparky approved these changes
안녕하세요 오션~ 좋은 아침이에요!

다음 단계도 있고하니 빠르게 리뷰했습니다. 제가 남긴 코멘트를 수동적으로 수용하기보다 스스로 고민하고 반박하거나 재질문주시는 부분이 인상적이네요 😀

여쭤봐주신 내용에 대해 답변을 달고 저도 추가로 학습하면 좋을 부분을 남겼으니 확인 및 답변 부탁드려요!
이번 단계는 충분히 이야기 나눈 것 같아 머지할테니 필요하신 수정사항은 다음 단계에서 부탁드립니다~~!

조금만 더 화이팅!

2023-03-22 21:03 UTC, merged

2023-03-23 02:20 UTC, donghae-kim commented on src/main/java/chessgame/domain/piece/Pawn.java
> +        if (source.rankDistance(target) == distance && source.fileDistance(target) == distance) {
1임을 보장하기 위해 함수 내부에서 처리했습니다!

2023-03-23 02:25 UTC, donghae-kim commented on src/main/java/chessgame/util/ChessBoardFactory.java
> +package chessgame.util;
현재 도메인 내에 있는 객체에서는 고민되는 것은 없었습니다!
다만 제가 가진 Factory는 어떤식으로 패키징 하면 좋을지에 대한 고민이였습니다.

2023-03-23 02:33 UTC, donghae-kim commented on src/main/java/chessgame/domain/state/Black.java
> +            throw new IllegalArgumentException("start를 입력할 수 없습니다.");
`IllegalArgumentException`는 적절한 인자를 넘기지 않았을 때 발생시키고
`IllegalStateException` 상태가 메소드를 처리하기에 적절한 상태가 아닐경우 발생하며
`UnsupportedOperationException` 지원되지 않는 작업을 처리했기 때문에 발생한다고 알고 있습니다.

처음에는 command라는 인자가 잘못되었다고 생각해서 사용을 하였었는데, 현재와 같은 경우에는 UnsupportedOperationException 이 조금 더 적합하지 않나 생각이 듭니다!