[1, 2단계 - 체스] 블랙캣(송우석) 미션 제출합니다.
woowacourse/java-chess pull request #492
Opened 2023-03-17 07:46 UTC by Songusika

안녕하세요 바다님!! 🌊
이번 페어 [이오](https://github.com/LJW25)와 같이 구현한 체스 미션 Step1-2 제출합니다!
리뷰 잘 부탁드립니다!

**✔️ 구조 설명**

저희는 체스 게임을 아래와 같이 도메인을 분석하고, 설계하였습니다.

체스 게임에 도메인에는 크게 

- `ChessBoard` (체스판)
- `Square` (한 칸)
- 한 칸의 기물 상태를 나타내는 `PieceState`들이 있습니다.

이번 미션에서 저희가 집중해서 설계한 부분은 각 기물과 관련된 도메인으로,

상태 패턴을 적용하여 각 기물 (폰, 룩, 퀸, 킹, 비숍, 나이트)과 빈칸을 하나의 상태로 판단하였습니다.

각 `Square` 가 하나의 상태를 가지도록 구현하였습니다.

또한 각 기물을 자신에 맞는 전략을 `override` 해서 구현하였습니다.

```java
@Override
    public List<Coordinate> findRoute(final Coordinate from, final Coordinate to) {
        validatePossibleDestination(from, to);
			// 폰, 룩, 퀸, 킹, 비숍, 나이트에 맞는 전략 구현
    }

    private void validatePossibleDestination(final Coordinate from, final Coordinate to) {
			// 폰, 룩, 퀸, 킹, 비숍, 나이트에 맞는 전략 구현
    }
```

![image](https://user-images.githubusercontent.com/74398096/225843527-3e00e94a-249b-4681-bdbb-164bbc7dbc2a.png)

**✔️ 기물 이동 로직 설명** 

저희는 기물이 움직이는 로직을 아래와 같이 구현하였습니다.

1. 각 기물은 전달받은 `from`, `to` 까지 이동할 수 있는 좌표인지 검사한다.
2. 이동이 가능하다면, `to`까지의 경로를 반환한다.
3. 체스판으로 부터 해당 경로 모든 `Square`를 가져온다.
4. 가져온 `Square`가 각 기물의 규칙에 맞게 지나갈 수 있는지 검사한다.
5. 검사 통과시 `ChessBoard`는 해당 `Sqaure` 의 상태를 `to` 좌표로 옮기고, `from` 은 빈 칸 상태로 만든다.

저희는 이번 미션을 구현하면서 아래와 같은 궁금증이 생겼어요 바다님과 같이 고민해봤으면 좋겠어요 😅

**Q. 상태 패턴을 구현할 때, 상태를 외부에서 주입받아도 되는 걸까요?**

- Square 를 생성할 때 아래와 같이 상태를 주입하는데 setter를 사용한 것이 아닌가라는 의문이듭니다.
- 상태를 주입 받는 것이 아니라 내부에서 스스로 상태를 생성/관리하는 것이 맞을까요?

```java
final Square square = new Square(new Pawn(Team.BLACK));
```

**Q. getter 를 생성하지 않고 어떻게 하면 메시지를 던져서 테스트를 할 수 있을까요?**

- 이번 미션의 주된 목표 중 하나는 도메인 간 게터와 세터를 사용하지 않는 것인데요
- 때문에 대부분의 테스트 코드는 `extracting` 메서드를 사용해서 테스트하였어요
- 사실상 게터를 피하기 위한 하나의 꼼수라고 생각드는데 다른 방법이 있을까요?

```java
assertThat(new ChessBoard())
        .extracting("squares")
        .asInstanceOf(InstanceOfAssertFactories.list(Square.class))
        .hasSize(64);
```

**Q. 하위 도메인이 상위 도메인을 알 고 있어도 될까요**

- 현재 저희 구조는 Square 각 PieceState를 각 필드로 가지고 있는 구조에요
- 하지만 각 Piece 들이 자신의 전략에 맞게 경로를 지나갈 수 있는지 검사하기 위해서는 경로상의 Square가 필요한 상태입니다.
    - 해당 Square가 비었는지
    - 해당 Square에 아군이 있는지
    - 해당 Square에 적군이 있는지
- 이러한 구조가 저희는 하위 개념 (Piece)이 상위 개념 (Square) 을 알고 있는거라고 생각합니다.
- 또한 하위 개념과 상위 개념이 서로 알고 있는 상태니 상호 참조 성격을 띄고 있구요.
- 이러한 구조가 된이유는 게터 사용을 자제해서 인데요 😭
- 저희가 생각하는 좋은 방법은 Piece가 Piece 를 받아서 각 규칙을 검사하는 것인데요.
- 혹시 이러한 방향으로 리팩터링 하기에 좋은 팁이 있을까요?

 👉  다시 생각해보니까 `Square` 객체가 `SquareBoard` 에서 `List<Square>` 를 받아서 자신의 `Piece`에 넘겨주는 형식이니,
해당 `Square` 객체에서 `List<Square>` 의 `Piece` 를 `List<Piece>` 형식으로 가져와서 넘겨주면
`Piece` 는 상위 개념과 연결을 끊어 줄 수 있겠네요! 이런 방법으로 우선 이런 방법으로 리팩터링해볼게요
혹시 바다님의 다른 아이디어나 방법이 있으면 같이 토론해봤으면 좋겠습니다!

바쁘실텐데 리뷰 해주셔서 감사합니다.
따끔한 코드 리뷰 부탁드립니다!! 🙏

2023-03-19 05:32 UTC, xrabcde requested changes
안녕하세요 블랙캣 ~ 바다입니다 🌊
체스 미션을 함께 하게 되어 반갑습니다 ㅎㅎ
커밋로그를 보니 어려운 미션인데도 TDD로 잘 구현해주셨네요 !
구조와 이동 로직에 대해 PR 내용으로 꼼꼼히 작성해주셔서 리뷰가 수월했습니다 👍🏻

아래 질문에 대한 답변과 몇 가지 코멘트 남겨두었으니
확인해보시고 궁금한 점은 언제든 코멘트나 DM으로 알려주세요~

2023-03-19 05:32 UTC, xrabcde commented on src/main/java/chess/domain/chessboard/Square.java
> +        pieceState.validateRoute(pieceStates);
> 현재 저희 구조는 Square 각 PieceState를 각 필드로 가지고 있는 구조에요. 각 Piece 들이 자신의 전략에 맞게 경로를 지나갈 수 있는지 검사하기 위해서는 경로상의 Square가 필요한 상태입니다.  해당 Square 객체에서 List<Square> 의 Piece 를 List<Piece> 형식으로 가져와서 넘겨주면 Piece 는 상위 개념과 연결을 끊어 줄 수 있겠네요! 

각 기물들은 Square의 하위 개념으로 두신 점이 독특하네요 !
설계에 정답은 없고 모든 구조엔 장단점이 있겠지만, 지금과 같이 기물이 네모칸에 종속적인 구조가 되다보니 
이동 경로를 검증할 때 상호 참조가 일어나지 않도록 조심해야 하는 상황이 생겼어요 

질문의 내용을 읽어보니 Square 에서 List<Square> 를 받아 경로를 검증하도록 잘 리팩터링해주신 것 같아요
여기서 한 번 더 개선을 할만한 부분이라면 
Square 안의 `validateRoute` 에서는 List<Square>를 받아 List<PieceState>로 변환만 해주고
사실 검증은 `pieceState` 에서 하고 있는데 Board 에서 애초에 Piece가 Piece를 받아 검증하도록 해줄 수 있을 것 같아요
만약, getter 사용을 줄이려는 목적이었다면 지금 코드도 충분히 괜찮은 것 같습니다 :)

지금과 같은 구조에서는 모든 체스 칸에 (empty를 포함한) 기물들이 무조건 하나씩 있는 상태가 보장되기 때문에
칸에 아무것도 없는 상황이 발생하지 않아 예외를 다루기에는 훨씬 좋은 구조라고 생각이 되네요 👍🏻

2023-03-19 05:32 UTC, xrabcde commented on src/main/java/chess/view/OutputView.java
> +        System.out.println("abcdefgh");
체스판의 가이드라인까지 챙겨주셨군요 !! 👍🏻

<img width="150" alt="image" src="https://user-images.githubusercontent.com/56033755/226155569-2859096f-a52a-4c6e-a177-4441ecf4c0a9.png">

2023-03-19 05:32 UTC, xrabcde commented on README.md
> +    - [x] 검은색-대문자, 흰색-소문자
아래 룰이 반영이 안 된 것 같아요!

- 백(소문자)이 첫 수를 둔다
- 백과 흑은 번갈아 가며 플레이 한다

<img width="320" alt="image" src="https://user-images.githubusercontent.com/56033755/226155647-efe1e952-a59d-42f0-9d78-a414fcbb9432.png">

<img width="360" alt="image" src="https://user-images.githubusercontent.com/56033755/226155709-3605cade-acbb-41ba-82f8-873dc76d7336.png">

2023-03-19 08:15 UTC, Songusika commented on src/main/java/chess/domain/chessboard/ChessBoard.java
> +            squares.put(Coordinate.of(makeAlphanumeric(file, rank)), createPawnSquareByTeam(team));
체스 도메인 용어에서 체스판의 가로를 `Rank` 세로를 `File` 라고 부르더라구요!
그래서 해당 도메인 용어를 사용해서 반복문 인덱스의 변수명을 작성하였습니다.

2023-03-19 09:50 UTC, Songusika commented on README.md
> +    - [x] 검은색-대문자, 흰색-소문자
앗 해당 부분을 마지막에 구현한다는 것을 깜박했네요 ㅜㅠ!!
WHITE 가 첫 수를 두고 이후 번갈아가며 턴을 두도록 기능 추가하였습니다.

2023-03-20 06:25 UTC, Songusika commented on src/test/java/chess/domain/chessboard/ChessBoardTest.java
> +                .asInstanceOf(InstanceOfAssertFactories.list(Square.class))
글 잘 읽었습니다! 
결국 `getter의 사용을 지양하라!` 이유는 캡슐화의 의미를 잃어버리게 되고
결국 객체가 스스로 행동하는 것이 아닌 외부로부터 영향을 많이 받을 수 있으니
도메인 객체 간에는 `getter`와 `setter` 또한 지양하는 의미이군요.

한가지 더 궁금한 게 생겼어요!
현재 `extracting` 을 사용해서 테스트하는 코드는 도메인 객체의 필드가 변경되어도
컴파일 단에서 오류를 잡아 줄 수 없는 문제가 있습니다.

`getter` 를 작성해서 테스트를 수행하면 그러한 오류를 잡을 순 있겠지만
오직 테스트만을 위한 `getter` 가 생길 수 있다고 생각합니다. (추후 view을 위한 `getter` 가 생길 순 있지만)
저는 이런 점이 조금 찜찜하더라고요. (테스트를 위해서 만들었는데 나중에 프로덕션 코드에서 사용할 수도 있으니)
혹시 바다 님은 이러한 테스트 만을 위해서 메서드(`getter`, `to`, `equals`&amp;`hashCode` 등)
를 작성하는 것에 대해서 어떻게 생각하시나요!!??

2023-03-20 06:27 UTC, Songusika commented on src/test/java/chess/domain/piece/state/PawnTest.java
> +        //given
앗 오타가 있었네요! 수정했습니다!

2023-03-20 06:49 UTC, Songusika commented on src/test/java/chess/domain/piece/state/KingTest.java
> +        Assertions.assertThat(king.findRoute(b2, c2)).containsExactly(Coordinate.of("c2"));
찾아보니 `assertThat` 으로 여러 줄의 테스트 코드를 작성하면 `fail` 이 난 이후의 테스트는 수행하지 않는 군요!
`assertAll` 메서드는 `fail` 이 나도 이후의 인자로 전달된 메서드를 수행하구요!

또 해당 키워드로 검색해보니 AssertJ 의 `SoftAssertions.assertSoftly()` 를 이용하면
`assertAll` 과 동일한 역할을 수행하면서도 `fail` 이 난 코드의 위치까지 같이 알려주네요!

<img width="767" alt="image" src="https://user-images.githubusercontent.com/74398096/226266438-8185855d-8255-468b-bce1-5c9475a5d420.png">


`SoftAssertions.assertSoftly()` 를 사용하여 테스트 코드를 리팩터링 하였습니다!!

2023-03-20 07:51 UTC, Songusika commented on src/test/java/chess/domain/piece/state/BishopTest.java
> +                .isInstanceOf(IllegalArgumentException.class);
각 테스트에 에러 메시지를 상수로 두고 `hasMessage()` 로 검증하도록 리팩터링하였습니다.

2023-03-23 02:26 UTC, Songusika commented on src/main/java/chess/domain/piece/state/Bishop.java
> +            throwCanNotMoveException();
확실히 `!` 표현보다 메서드명으로 표현하는 것이 더 가독성이 좋네요!

2023-03-23 02:32 UTC, Songusika commented on src/main/java/chess/domain/piece/Piece.java
> +        return 1;
`Team` enum에 이미 해당 상수가 정의가 되어있었네요😅

2023-03-23 04:44 UTC, Songusika commented on src/main/java/chess/controller/ChessController.java
> +    }
저는 해당 메서드가 View를 위한 DTO 성격을 띄는 메서드로 보고 있습니다!

그리고 ChessBoard는 도메인이라고 보고 있어서 해당 로직을 Controller에서 수행하였습니다.
ChessBoard 에게 해당 책임을 위임하는 것은 View와 Domain 간 강결합이 생긴다고 생각하는데요!

혹시 해당 로직을 ChessBoard 안에서 수행하길 추천하는 이유를 알 수 있을까요?

2023-03-23 12:21 UTC, Songusika commented on src/main/java/chess/controller/ChessController.java
> +    }
현재는 `DTO` 클래스를 만들어서 `Controller` 에서 `ChessGame`로 부터 `ChessBoard` 를 받아 `DTO`로 변환하여 출력하는 방식으로 리팩터링하였습니다!

2023-03-25 05:36 UTC, xrabcde approved these changes
안녕하세요 블랙캣 ~ 바다입니다 🌊
다음 단계 진행을 위해 이번 단계는 여기서 머지할게요 ㅎㅎ
아래 질문에 대한 답변과 추가 코멘트 몇가지 남겼으니
다음 단계 진행하면서 같이 확인 부탁드립니다 ~
다음 단계에서 만나요 🙌

2023-03-25 05:36 UTC, xrabcde commented on src/main/java/chess/controller/ChessController.java
> +        while (!chessGame.isGameEnd()) {
진행중인지를 확인하도록 바꿔줄 수 있을 것 같아요 ~

2023-03-25 05:36 UTC, xrabcde commented on src/main/java/chess/controller/ChessController.java
> +        OutputView.printChessBoard(new ChessBoardDto(chessGame.getChessBoard()));
> 저는 해당 메서드가 View를 위한 DTO 성격을 띄는 메서드로 보고 있습니다!
그리고 ChessBoard는 도메인이라고 보고 있어서 해당 로직을 Controller에서 수행하였습니다.
ChessBoard 에게 해당 책임을 위임하는 것은 Domain에 View 을 위한 책임이 생긴다고 생각하는데요!
혹시 해당 로직을 ChessBoard 안에서 수행하길 추천하는 이유를 알 수 있을까요?

지금은 DTO로 구조를 잘 개선해주셨지만 이전 질문에 대한 답변을 드리자면,
이전 코드에서는 controller 에서 chessBoard 의 squares 들을 모두 꺼낸 뒤 `subList` , `reverse` 등의 액션을 통해 도메인 로직을 수행하고 있는 것 같아 남긴 코멘트였습니다 ~

2023-03-25 05:36 UTC, xrabcde commented on src/main/java/chess/domain/piece/state/King.java
> +        if (isCanNotMoveDirection(fileDistance, rankDistance)) {
👍🏻👍🏻

2023-03-25 05:36 UTC, xrabcde commented on src/main/java/chess/dto/ChessBoardDto.java
> +    public static final int RANK_SIZE = 8;
접근제어자 확인해주세요 ~

2023-03-25 05:36 UTC, xrabcde commented on src/test/java/chess/domain/chessboard/ChessBoardTest.java
> +    void 체스판은_첫_시작_시_BLACK_이_선으로_두면_예외가_발생한다() {
예외테스트 👍🏻

2023-03-25 05:36 UTC, xrabcde commented on src/test/java/chess/domain/chessboard/CoordinateTest.java
> +                    .isEqualTo('a');
> 현재 extracting 을 사용해서 테스트하는 코드는 도메인 객체의 필드가 변경되어도 컴파일 단에서 오류를 잡아 줄 수 없는 문제가 있습니다.
getter 를 작성해서 테스트를 수행하면 그러한 오류를 잡을 순 있겠지만
오직 테스트만을 위한 getter 가 생길 수 있다고 생각합니다. (추후 view을 위한 getter 가 생길 순 있지만)
저는 이런 점이 조금 찜찜하더라고요. (테스트를 위해서 만들었는데 나중에 프로덕션 코드에서 사용할 수도 있으니)
혹시 바다 님은 이러한 테스트 만을 위해서 메서드(getter, to, equals&hashCode 등)
를 작성하는 것에 대해서 어떻게 생각하시나요!!??

네 extracting 은 원본객체의 변화에 유연하지 않기 때문에 되도록 사용하지 않는 것 같아요 
getter 를 생성해 테스트해줘도 큰 문제는 없어보이지만 
말씀하신 것처럼 테스트만을 위한 메서드인 것 같아 찜찜하다면 
현재 작성되어있는 함수 중 `getSquares` 같은 함수를 이용해 테스트할 수 있을 것 같아요 ~

2023-03-25 05:36 UTC, xrabcde commented on src/test/java/chess/domain/chessboard/CoordinateTest.java
> +        assertSoftly((softly) -> {
💯

2023-03-25 05:36 UTC, merged