[1, 2단계 - 체스] 우르(김현우) 미션 제출합니다.
woowacourse/java-chess pull request #516
Opened 2023-03-17 08:48 UTC by java-saeng

안녕하세요 파즈
이번 리뷰를 받게된 5기 우르입니다 !!

먼저 도메인 의존성 파악하기 위해서 다이어그램 하나 올리겠습니다 !!

![image](https://user-images.githubusercontent.com/62413589/225856127-75a5513c-0f79-4f90-b131-8341e69cf944.png)

DM 보냈듯이 제가 구현에 치여서 TDD를 제대로 하지 못했다고 생각합니다,, 그리고 코드 품질 또한 좋지 못합니다.,,

금요일에 계속해서 리팩터링을 하고 있었지만, 코드를 봐도 스스로 고쳐야할 점이 많아 보여요,,

매직넘버 상수화나 개행 같은 기본적인 것들은 시간이 부족해서 많이 하지 못했어요

많이 부족하겠지만 이번 리뷰도 잘 부탁드립니다 !!

2023-03-18 16:00 UTC, Be-poz requested changes
안녕하세요 우르, 체스미션 수고하셨습니다. 코드 잘 확인했습니다. 
코멘트를 몇 남겼으니 확인해주시면 감사하겠습니다.

2023-03-21 00:45 UTC, java-saeng commented
안녕하세요 파즈 !!

이번 리뷰를 통해서 평상시에 생각하지도 못한 부분들을 배워서 좋았습니다.

### 상수가 책임 분리에도 영향을 주는걸까?

제일 궁금한 점이 파즈의 리뷰 중에 대부분 차지하는게 상수에 관해서인데요.
저는 이전까지 많은 상수들이 필요하지 않아서 대부분 private static final 로 사용했는데요, 이번처럼 상수가 사용할 일이 많아지니 결국 겹치는 부분이 생기더라구요.

그렇다면 `같은 역할을 하는 상수가 여러 클래스에 존재하게 되면, 책임을 잘못 할당한건가 ?` 라는 의심이 들더라구요.
제 의심이 맞는지 여쭙고 싶습니다.

### 도메인


제가 급히 제출하는 바람에 깔끔하지 못한 도메인 로직을 제출해서 마음이 많이 쓰였는데, 파즈도 아시는지 도메인에 관련된 리뷰가 없어서 참 다행이라고 생각했습니다,,, 하하

제가 파즈의 의도를 제대로 이해한건진 모르겠지만, 체스 미션이 나중에 DB도 연결하게 되잖아요?
이 부분도 결국 제일 중요한 도메인을 가운데에다가 모아두고, 그 주위에 DB 를 연결한 것과 같다 생각이 들어서 먼저 바깥쪽 부분(`controller`, `view`) 쪽을 리뷰해주신게 아닌가 싶더라구요.

도메인은 최대한 변하지 않아야하고, 의존성은 최대한 도메인 쪽으로 향해야하며 바깥쪽(외부 adapter) DB와 같은 외부 의존성에 의존되지 않아야하기 때문이죠. 

### 사용하지 않는 메서드의 파라미터는 추상 메서드를 만들면 안된다?

이 부분은 코드로 보는게 편해서 해당 코드에 comment 달겠습니다 !!

### Pawn 을 나눌까? 

위와 연장된 질문이긴합니다만 Pawn은 첫 움직임에 2칸 갈 수 있기 때문에 이미 출발한 적이 있는 폰인가? 처음 출발한 폰인가? 로 나누려고 했습니다.

즉, `InitPawn`, `MovedPawn` 으로 나누려고 했습니다.
왜냐하면 두 폰 공통적으로 상대방이 있으면 대각선 이동 가능, 한칸 이동 가능이 가능하고, 차이점은 2칸 이동의 유무입니다.

하지만 이렇게 나누게 된다면 기존에 하나로 합쳤을 때보다 코드 가독성이 떨어지고, 더 이해하기 어려운 코드가 되었습니다. 또한, 한칸만 이동했을 때도 두칸 이동했는지 안했는지 검사하는게 필요하더라구요,,

그래서 파즈의 생각은 어떠신지 궁금합니다.

2023-03-21 00:59 UTC, java-saeng commented on src/main/java/chess/domain/piece/Piece.java
> +    protected abstract Path moveToLocatedPiece(final Position from, final Position to,
이 부분에 해당하는 질문인데요.

movement 를 구하는 로직이 모든 Piece에 포함되어있고, 필요로합니다.
그래서 searchPathTo라는 Piece의 퍼블릭 인터페이스에 movement를 구하고 Path를 구하는 해당 추상 메서드를 호출합니다.

하지만 Pawn은 목적지 Piece를 나타내는 locatedPiece까지 필요로 하게 됩니다.

즉, 정리하자면 Pawn을 제외한 나머지 Piece들은 locatedPiece가 필요하지 않고, Pawn은 locatedPiece가 필요로 하게 되는데, 이를 추상 메서드로 뺴는 것이 과연 괜찮을까? 라는 생각이 들었습니다.

분명히 같은 메세지를 받을 수 있고, 같은 상태(Color)를 가지고 있기 때문에 Pawn과 다른 Piece들은 같은 메시지를 받아도 된다고 생각합니다. 하지만 이러한 파라미터의 사용 유무 때문에 과연 메시지를 변경해야할까 라는 생각이 들더라구요.

파즈의 생각은 어떠신지 궁금합니다 !

2023-03-21 11:41 UTC, Be-poz commented on src/main/java/chess/controller/ChessController.java
> +    }
``move a22 a33`` 와 같은 동작이 현재 잘 돌아가고있는데 이 또한 예외 처리가 되면 좋겠습니다.

2023-03-21 14:33 UTC, Be-poz commented on src/main/java/chess/domain/board/Board.java
> +        final Piece currentMovePiece = findPieceFrom(from);
아 그러한 이유로 그러셨던거군요. 그런 이유면 납득됩니다! 이미 고려가 된 상황인줄 몰랐네요~!

2023-03-21 15:52 UTC, Be-poz commented
```
org.springframework.kafka.KafkaException: Seek to current after exception; nested exception is com.linecorp.lsp.product.stream.support.exception.LspStreamException: ERROR_BATCH_PROCESSING partitionOffsets : [], ids : []
	at org.springframework.kafka.listener.SeekToCurrentBatchErrorHandler.handle(SeekToCurrentBatchErrorHandler.java:92)
	at com.linecorp.lsp.product.stream.support.kafka.SeekToCurrentMaxAttemptsBatchErrorHandler.handle(SeekToCurrentMaxAttemptsBatchErrorHandler.java:112)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.handleConsumerException(KafkaMessageListenerContainer.java:1251)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.run(KafkaMessageListenerContainer.java:1004)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: com.linecorp.lsp.product.stream.support.exception.LspStreamException: ERROR_BATCH_PROCESSING partitionOffsets : [], ids : []
	at com.linecorp.lsp.product.stream.support.kafka.SeekToCurrentMaxAttemptsBatchErrorHandler.handle(SeekToCurrentMaxAttemptsBatchErrorHandler.java:90)
	... 5 common frames omitted

Caused by: org.apache.kafka.common.errors.SerializationException: Size of data received by LongDeserializer is not 8
```

```java
update
DocumentConverter.convertToPut(54): id : 2465926094
DocumentConverter.convertToPut(55): version : 1679391720000001
DocumentConverter.addColumn(151): addColumn qualifier : colorBit, value : 64
DocumentConverter.addColumn(151): addColumn qualifier : colorMatchType, value : SIGNATURE
DocumentConverter.addColumn(151): addColumn qualifier : updateArea, value : COLOR_NORMALIZER
DocumentConverter.addColumn(151): addColumn qualifier : updateDate, value : 2023-03-21T17:42:00.054+08:00
```



1. 상수가 책임 분리에도 영향을 주는가

   여러 도메인에서 동일한 상수를 쓰는 경우는 당연히 있습니다. 책임을 잘못 할당한 것이라기 보다는 공통된 지식을 갖고 있다라고 생각하면 더 편할 것 같네요. 이런 경우에는 공통 디렉토리에 집어넣어서 같이 사용합니다. 제가 근무하고 있는 환경에서는 msa 환경이다보니 도메인별로 여러 모듈로 나눠져있는 상황이고 공통의 지식을 위해 core 라는 모듈이 따로 존재합니다. 이 미션에서도 공통의 지식을 따로 클래스나 enum으로 빼는 방법으로 대처할 수 있을 것 같네요.

2. 도메인 로직에 관한 것

   이번 체스 미션의 리뷰어 가이드에서 세부 구현사항에 대해서는 터치를 최대한 안하는 것으로 가이드가 내려왔습니다. 그래서 상세 로직에 대해서는 그냥 그런갑다 하고 넘어갔습니다. 그렇지만 다 보긴 봤습니다! 보통 미션리뷰 할 때에 모든 로직을 다 보고 하다보니 2시간 정도 걸리니깐 볼 수 밖에 없습니다! controller와 view 쪽은 아주 의도해서 그런 것은 아니긴 하지만 최대한 이후 리팩토링 편하게끔 리뷰를 하려고 합니다. 이번 5기에서 자바스크립트를 이용한 체스 ui 구현을 하는지는 잘 모르겠지만, 구현을 하고 스프링으로 넘어가는 구간에서 controller와 view가 리팩토링이 잘되어있어야 넘어갈 때에 코드를 크게 바꾸지 않아도 되서 편합니다.  

   도메인은 변할 수 있긴 하지만 view로 인해 변화가 있으면 안됩니다. view는 시시각각 요구사항이 변할 수 있기 때문에 도메인과는 철저히 분리가 되어야 합니다. DB와 같은 외부 의존성에 의존되지 않아야 한다는 것이 도메인과 DB와의 의존관계를 말씀하시는걸까요? 보통 DB에서 읽어올 때에 데이터 내용을 담는 vo를 이용하기도 하고 바로 도메인으로 리턴받기도 합니다. 특히 jpa를 사용하는 환경이라면 도메인이 DB 테이블 그 자체이기 때문에 의존성을 운운하기에 살짝 애매한 감이 있습니다. 그냥 도메인들이 view를 바라보면 안되고 view가 도메인을 바라보는 것은 괜찮다. 라고 생각하시면 편하실 것 같습니다. controller가 view와 맞닿아있는 가장 바깥 표현계층이기 때문에 아무래도 안정성이 떨어지기에 비즈니스 로직들을 모아둔 계층이나 db접근 계층이 controller를 바라보지 않게끔 합니다. 아직 아실 필요 없는 내용이니깐 그냥 view에 의존하지말자 만 지키고 계시면 됩니다. 나중에 이 내용에 대해서 접하실 때에 https://techblog.woowahan.com/2561/ 해당 링크 글을 한 번 읽어보시면 도움이 되실 것 같네요.

3. Pawn이 아닌 다른 기물 클래스에서 메서드 호출할 때에 파라미터에 locatedPiece를 넣지만 사용을 하지않는다는 점이 참 애매하긴하네요. 사용을 하지 않는데 1개를 위해 무조건 넣는 방식은 굉장히 찝찝하긴합니다... 저라면 JumperPiece, SliderPiece를 묶는 상위 계층을 하나 만들고 그에 대응하는 Pawn만을 가지는 상위계층을 하나 만들어서 메서드를 각각 가지고 있게끔 만들 것 같긴합니다. Pawn 하나만을 위해서 너무 계층이 생겨나는 것 같긴하지만, 그렇게 할 것 같긴 하네요.  

   마음 같아서는 오버로딩을 이용하고 싶지만, 상위 클래스인 Piece의 searchPathTo 메서드에서 호출을 하고 있어서 깔끔하지가 않네요. 사실 이런 경우에 다 날리고 처음부터 구조를 다시 짜보면 굉장히 깔끔하게 만들어지고 시간 또한 생각한 것 만큼 걸리지않고 단시간 내에 재구축 가능합니다. 미션이라서 가능한 방법이긴 하지만요..  

   일반적이라면 저는 파라미터 사용을 안하게 되더라도 경우에 따라서 추상 메서드를 만들어도 된다고 생각합니다. 다만 6개의 하위 클래스가 사용하고 1개가 사용안하는 것이 아니라 1개만 사용한다는 점이 문제긴 하지만요...

2023-03-21 15:54 UTC, merged

2023-03-22 02:38 UTC, java-saeng commented on src/main/java/chess/controller/ChessController.java
> +    }
넵 다음 미션 때 바로 수정하겠습니다!