[1, 2단계 - 체스] 무민(박무현) 미션 제출합니다.
woowacourse/java-chess pull request #518
Opened 2023-03-17 08:49 UTC by parkmuhyeun

안녕하세요 춘식! 무민입니다.

상태에 따라 if 분기문이 많이 나오는거 같아 제거하기 위해

2023-03-19 08:05 UTC, bimppap requested changes
안녕하세요 무민! 춘식입니다!
체스 미션 어려웠을텐데 구현 잘 해주셨네요. 👍
코멘트 간단하게 남겨봤으니 확인 부탁드립니다!
궁금하거나 이해가 안 되는 점은 편하게 DM 주세요 😉

2023-03-19 08:05 UTC, bimppap commented on src/main/java/chess/domain/board/Board.java
> +
이 두 개는 테스트가 없는 것 같습니다 👀

2023-03-19 08:05 UTC, bimppap commented on src/main/java/chess/domain/board/Board.java
> +
인텔리제이를 사용한다면 `테스트 커버리지`를 확인할 수 있습니다. 테스트 된 부분과 아닌 부분을 쉽게 확인할 수 있어 추천드립니다!

2023-03-19 08:05 UTC, bimppap commented on README.md
> +## 도메인 다이어그램
깔끔하게 짠 게 한 눈에 보이네요 👍

2023-03-19 08:20 UTC, parkmuhyeun commented on src/main/java/chess/controller/ChessController.java
> +    public void run() {
어 원래 막히는거 확인했었는데.. 마지막에 인덱스 바꾸는 과정에서 뭔가 오류가 있었나 봅니다..ㅠㅠ
확인해 수정하겠습니다!

2023-03-20 14:44 UTC, parkmuhyeun commented on src/main/java/chess/controller/ChessController.java
> +    public void run() {
제가 3D 체스를 만들어버렸군요;;

2023-03-20 15:25 UTC, parkmuhyeun commented on src/main/java/chess/controller/Command.java
> +
아 13번째줄에 개행이 실수로 들어간거 같습니다.. ㅋㅋㅋ

2023-03-20 17:33 UTC, bimppap commented on src/main/java/chess/controller/Command.java
> +
오... 지금 보니 2번으로도 해결은 못하겠군요 넘어가주세요ㅎㅎ;; ~제가 예전에 해결해본 줄 알았는데 저도 해결을 못했네요ㅋㅋ~
(+) 다만 정규표현식을 쓰면 컨트롤러에서 split을 하지 않고 input을 바로 넣어도 되겠네요.
String 타입의 경우 matches라는 정규표현식을 확인하여 boolean을 리턴하는 메서드가 있으니 한번 사용해보면 약소하게나마 코드를 깔끔하게 만들 수 있을 것 같습니다.
(++) 좀 더 깔끔하게 만들고 싶다면 커맨드 패턴을 적용해봐도 좋을 것 같습니다.

2023-03-20 17:39 UTC, bimppap commented on src/main/java/chess/domain/movepattern/MovePattern.java
> +}
넵 맞습니다. 추가적으로 DTO의 경우에는 데이터를 전달하는 목적이 맞기 때문에 굳이 getter를 지양할 필욘 없다고 봅니다. 😊

2023-03-21 15:33 UTC, bimppap approved these changes
안녕하세요 무민, 춘식입니다!
리팩토링 잘 해주셨어요. 원래도 깔끔했는데 더 깔끔해진 것 같네요 🔥
이번 단계는 여기서 마무리해도 될 것 같아 머지하도록 하겠습니다.
답변 및 코멘트들 남겼으니 다음 단계 할 때 참고해주세요!

2023-03-21 15:33 UTC, bimppap commented on src/main/java/chess/domain/movepattern/MovePattern.java
> +public interface MovePattern {
MovePattern을 interface가 아닌 enum으로 바꿔보는 건 어떨까요? 각 기물의 Pattern을 보면 공통적으로 보이는 상수들이 있어서, 아예 한곳에서 관리해주고 팩토리 메서드 형식으로 Piece들에게 movePattern을 전달하면 중복을 줄일 수 있지 않을까 싶습니다.

2023-03-21 15:34 UTC, merged