[3, 4단계 - 체스] 두둠(최영훈) 미션 제출합니다.
woowacourse/java-chess pull request #535
Opened 2023-03-23 12:09 UTC by younghoondoodoom

안녕하세요 완태! 이번에도 좋은 리뷰 부탁 드립니다~!

## Points To Watch
요구 사항 중에 사용자 별로 게임 기록 관리하는 것 빼고 구현을 완료 했습니다. 그 부분은 리펙토링 하면서 진행 해보겠습니다!
이번 단계에서는 트랜잭션을 적용해서 테스트를 롤백하고 각 비즈니스 로직에 트랜잭션 적용을 해봤습니다. 
그리고 최대한 도메인 로직을 건드리지 않고 db를 적용하는 것에 집중 하였습니다.

DB의 세팅과 ddl은 db 폴더에 넣어놨습니다! 참고 부탁 드립니다!

## Questions
1. 상속을 사용하면 캡슐화가 깨진다고들 하는데 정확하게 공감이 되지 않습니다.
상속을 사용해서 오버라이딩을 하게되면 상위 클래스의 구현이 하위 클래스에 노출되는것과 마찬가지라고 하는데, 오버라이딩을 하는 것이 왜 노출이 된다고 표현하는 걸까요? 
super를 사용해서 상위 클래스의 구현을 가져다쓰는 것은 공감이 된다만 오버라이딩이 왜 캡술화를 깬다는 것인지 공감이 잘 안됩니다. 완태의 인사이트가 궁금합니다!

좋은 하루 되세요~!

2023-03-25 18:44 UTC, wannte requested changes
안녕하세요 두둠!

리뷰가 늦었네요 ㅜ.
db 관련하여 위주로 피드백 남겼습니다!  확인부탁드려요!

2023-03-25 18:44 UTC, wannte commented on db/ddl.sql
> +    `row_`                int         not null,
Q. suffix 로 _ 로 준 다른 이유가 있을까요?

2023-03-25 18:44 UTC, wannte commented on src/main/java/common/TransactionContext.java
> +public final class TransactionContext {
Transaction 까지 구현해버리시다.. 💯 

트랜잭션을 활용했을 때, 어떤 장점을 얻을 수 있을까요?

2023-03-25 18:44 UTC, wannte commented on src/main/java/domain/dao/MySqlChessInformationDao.java
> +    }
매번 connection을 넘겨주고 있네요!

비즈니스 로직까지 db connection 을 고려하게 될 것 같은데, Dao 단에서 해당 역할을 가져갈 수 있을 것 같아요!

2023-03-25 18:44 UTC, wannte commented on src/main/java/domain/dao/ChessInformationDao.java
> +    Color findColor(final String id, final Connection connection) throws SQLException;
findLastColor 정도로 그 의미를 명확하게 할 수 있을 것 같아요!

2023-03-25 18:44 UTC, wannte commented on src/main/java/domain/dao/ChessInformationDao.java
> +    Map<Location, Piece> find(final String id, final Connection connection) throws SQLException;
이 메소드도 보다 그 의미가 명확해지면 좋을 것 같습니다!

2023-03-25 18:44 UTC, wannte commented on db/ddl.sql
> +    `boardinformation_id` bigint      not null unique auto_increment,
query 작성을 현업에서 많이하게 되는데, id는 id로 존재하는 게 검색하기 편할 것 같다는 생각 남깁니다!

'Information' 이라는 표현이 모호하다는 느낌이 듭니다.

board vs boardInformation 이 두 테이블 이름만 보더라도 그 차이가 명확해질 수 있으면 좋을 것 같아요!

2023-03-27 05:26 UTC, younghoondoodoom commented on db/ddl.sql
> +    `row_`                int         not null,
쿼리 작성 시에 오류가 떠서 변경 했었는데, `로 감싸니 괜찮네요. 수정 했습니다!

2023-03-28 06:12 UTC, younghoondoodoom commented on src/main/java/domain/dao/MySqlChessInformationDao.java
> +    }
비지니스 로직에서 transaction 단위를 하나로 묶으려고 하다보니 이렇게 구현 했었습니다! 지금은 비즈니스 로직에 connection이 노출 되지 않게 수정 했습니다. 
비즈니스 로직에서 transaction 단위로 묶기 위해 connection을 jdbcContext라는 곳에서 관리하게 하였습니다. 이것 말고는 connection이 비즈니스 로직에서 노출 되는 것을 방지할 수 없는 것 같습니다. 
트랜잭션 전파를 사용해보려고 했는데 이상하게 적용이 안되네요.. 트랜잭션 전파를 사용하려면 따로 설정해야하는 부분이 있는 건가요?? 검색해도 잘 나오지 않는거 같습니다🥲

2023-03-28 06:21 UTC, younghoondoodoom commented on src/main/java/common/TransactionContext.java
> +public final class TransactionContext {
트랜잭션을 활용하면 논리적인 단위에서 트랜잭션을 묶을 수 있는 장점이 있습니다. 해당 트랜잭션 안에서 오류가 날 경우 트랜잭션 전체를 롤백 시켜주니 데이터 무결성을 지킬 수 있습니다!
이번 미션에서 트랜잭션을 적용해야겠다고 생각한 이유는 테스트 시에 사용한 데이터를 롤백 시켜서 각각의 테스트가 독립적으로 돌아가도록 하고 싶었습니다. 이왕 도입한 김에 비즈니스 로직에서 트랜잭션 단위를 만들어 묶어봤습니다.
물론 여러 트랜잭션이 동시에 실행될 일은 없겠지만 학습할 겸 도입 해봤습니다!

2023-03-28 11:04 UTC, wannte approved these changes
안녕하세요 두둠! 피드백 반영 확인했습니다!

전반적으로 코드가 깔끔해졌네요. Repository에서 여러 Dao 를 사용하는 부분이 인상적입니다. 👍 

관련해서 고민해봤으면 하는 포인트 하나 남깁니다! (DM으로 질문 주셔서 좋습니다.)

리뷰 정책상 이만 머지하겠습니다.!

2023-03-28 11:04 UTC, merged