[3, 4단계 - 체스] 아마란스(송세연) 미션 제출합니다.
woowacourse/java-chess pull request #547
Opened 2023-03-25 10:31 UTC by amaran-th

안녕하세요 또링! 
DB를 활용해본 경험이 많이 없어서 4단계를 구현하는 과정에서 객체지향이 많이 깨진 것 같아요.
그래서 몇 가지 질문사항 함께 적어올립니다.
현재 체스의 추가 룰 중 앙파상만 구현한 상태입니다.
*승진과 캐슬링은 추가적인 입력을 요구해서 구현이 복잡해질 것 같아 시간상 생략하였습니다.

### Score 연산
1. 책임
점수를 계산할 때 점수를 계산하는 책임이 적절히 분배된 것인지 잘 모르겠습니다.
각 객체들이 점수에 대한 기능도 일정부분 부담하고 있다보니 코드가 너무 길어지는 것 같아요.
Score를 계산하는 역할만 따로 클래스를 분리해볼까 생각도 해봤지만 마땅한 설계가 떠오르지 않더라구요. 혹시 현재 설계에 근거해서 의견 주실 수 있을까요?

2. 점수 계산 로직
폰의 점수가 블랙잭의 에이스카드처럼 일정한 수치가 아니다보니, 로직이 조금 복잡해졌는데요.
제가 구현한 방식은 한 열에 대해 PieceType별 개수를 가지는 Map을 만들고, 해당 Map을 가지고 각 칸의 점수를 받아온 뒤 합산하는 방식입니다.
성능적으로 좀 더 좋은 로직이 있을지 자문을 구하고 싶습니다.

### DB
1. 패키지 분리 기준
사실 1, 2단계때 질문 드렸어야 할 내용이지만, 패키지 분리 기준에 대해서도 질문 드리고 싶습니다.
현재 크게 domain, controller, view로 나누어져 있는데요.
dto를 따로 패키지로 만들어서 관리하는 분도 계시고, 제 페어분처럼 controller에 넣으시는 분도 계시더라구요.
그리고 이번에 db가 추가되면서 dao 클래스도 생겼는데, 어떻게 패키지를 관리해주는 게 적절한지 궁금합니다.
혹시 이와 관련된 가이드가 있을까요?

2. db의 primary key 관리에 대해
현재 플레이 중인 game의 아이디 값을 어떻게 관리하면 좋을지 고민입니다.
일단은 ChessController의 필드로 선언해주긴 했는데, 로직 상 상수로 정의하기도 어려울 것 같고 , game이 가지고 있는 것도 영 아닌 것 같아요.
혹시 좋은 방법이 있을까요?

### 1, 2단계에서 해결되지 못한 질문들
해당 코드에 코멘트로 달아두었습니다.

감사합니다.

2023-03-28 14:28 UTC, jnsorn requested changes
안녕하세요, 아마란스! 리뷰가 많이 늦었습니다. 😭
이번 단계도 문서화가 잘 되어 있어서 보기 편했습니다 ㅎㅎ 👍 
여러 고민을 하면서 구현해주신 것 같은데, 같이 얘기해보면 좋을 부분에 코멘트 남겨두었으니 확인해보시고 다시 요청주세요!

2023-03-28 14:28 UTC, jnsorn commented on src/main/java/chess/domain/piece/Piece.java
>      public abstract PieceType findType();
> 추후 특수 룰을 구현하기 위해 piece가 Pawn인지, Rook인지, King인지 여부를 반환하는 메서드가 추가될 것을 고려했을 때 중복코드가 많아질 것이라 예상 되어서 판단 책임을 상위 객체에게 넘겨주었습니다...!
예를 들면 Queen에 isKing(), isRook(), isPawn()을 모두 구현해주어야 하는 게 번거롭고, 추후 유지보수 측면에서도 좋지 않을 것 같다고 생각했습니다. 혹시 이런 경우엔 적절한 객체에 책임을 위임하는 것과 가독성&유지보수성 중 어느 것을 더 중요시하는 게 좋을까요? 아니면 더 좋은 대안이 있을까요?

이 글 참고해보셔도 좋을 것 같아요 :) https://tecoble.techcourse.co.kr/post/2021-04-26-instanceof/

2023-03-30 11:01 UTC, amaran-th commented on src/main/java/chess/domain/position/MoveRange.java
이 방법대로라면 (0,0)부터 (8,8)까지 모든 좌표에 대한 enum을 만들어야 하는 것 아닌가요...?
방법이 잘 와닿지 않네요😢

2023-03-30 11:02 UTC, amaran-th commented on docs/README.md
> +# 🔖DB 테이블 설계
앗 최상위 README는 제가 미션이 끝나면 따로 작성해서 추가해주고 있습니다!ㅎㅎ

2023-03-30 11:19 UTC, amaran-th commented on docs/README.md
> +| gameDataId | gameId | source | destination |
반영하였습니다!

2023-03-31 00:26 UTC, jnsorn approved these changes
안녕하세요 아마란스~ 방학임에도 피드백 반영 하시느라 고생 많으셨어요.
체스 미션은 여기서 머지하도록 할게요. 
코멘트 남겨주신 건들은 따로 확인해보고 DM 드릴게요. ☺️

2023-03-31 00:26 UTC, merged

2023-04-02 09:02 UTC, jnsorn commented on src/main/java/chess/controller/ChessController.java
> +        } catch (Exception e) {
네 맞습니다. 현재 개발자가 인지하는 예외상황 뿐만 아니라 모든 exception에 대해 재귀함수를 호출하고 있어요. 만약 복구할 수 없는 예외라면 재귀함수가 종료되지 못하고 시스템은 OOM 등으로 망가지게 될 것 같아요. 
수정해주신 것처럼 복구 가능한 특정한 예외에 대해서 catch하여 재수행 하도록 하는 로직은 괜찮습니다 👍

2023-04-02 09:03 UTC, jnsorn commented on docs/README.md
> +# 🔖DB 테이블 설계
미션 진행 중 해당 프로젝트를 보는 사람(=리뷰어 및 다른 크루들)이 있으니, 미션 진행 중에도 최상위에서 관리해도 좋을 것 같아요! 😃

2023-04-02 09:07 UTC, jnsorn commented on src/main/java/chess/controller/ChessController.java
> +            connection.close();
맞습니다 👍 잘 학습하신 것 같아요!
특히 여러 사용자가 사용하는 서비스의 경우, 한 스레드가 커넥션을 길게 잡고 있으면 커넥션 고갈 문제가 발생할 수 있어 필요할 때 커넥션 풀을 통해 적절히 사용할 수 있도록 하는 게 중요합니다. 이건 다음 미션들 진행하면서 더 고민해보면 좋겠네요!

2023-04-02 09:15 UTC, jnsorn commented on src/main/java/chess/domain/piece/Pawn.java
> +    }
좋은 고민이에요! Board 계산이니 Board/Square에서 계산해야 하지 않을까?라는 생각에 질문 주신 것 같아요. 이건 아마란스가 객체의 역할을 어떻게 정의하냐에 다를 것 같은데요, 저는 지금 구조도 객체지향적이다라고 보여요. Board의 계산을 ChessBoard에서 하는 것도 좋은 구조이지만, 현재 ChessBoard는 그 외에도 많은 역할을 수행하고 있어요(칸에 기물이 있는지 확인도 하고, 해당 칸의 피스를 반환하기도 하는 등..) 따라서, 점수를 계산하는 책임은 다른 객체에 할당하고, board는 그 객체를 이용해 점수를 반환하면 적절하게 책임이 분배되었다고 볼 수도 있을 것 같아요.

2023-04-02 09:19 UTC, jnsorn commented on src/main/java/chess/domain/piece/Piece.java
>  public abstract class Piece {
앙파상 등 게임 구현에 trace가 필요하니, 굳이 빼내지 않아도 합리적인 구조라 보여요! 😃 Trace를 Board/Square 레벨에서 관리하거나, 필요할때마다 DB에서 해당 기물의 history를 꺼내오는 방법도 있겠네요!

2023-04-02 09:23 UTC, jnsorn commented on src/main/java/chess/domain/piece/Piece.java
>      public abstract PieceType findType();
넵 맞습니다.

2023-04-02 09:29 UTC, jnsorn commented on src/main/java/chess/domain/position/MoveRange.java
오 그런 구조를 의도한 것은 아니었어요 ㅎㅎ enum을 통해 기물이 갈 수 있는 방향에 대해 정의하고, 거리 상관 없이 갈 수 있는 기물에 대해서는 위 isCross와 같이 조건만 체크하면 기물이 갈 수 있는 모든 경로에 대해 판단이 가능할 것 같아요.