[3, 4단계 - 체스] 비버(전인표) 미션 제출합니다.
woowacourse/java-chess pull request #550
Opened 2023-03-25 11:38 UTC by ingpyo

2023-03-26 15:51 UTC, iphwade requested changes
안녕하세요 비버! 항상 빠른 피드백 좋습니다-! 👍 
조금 더 집중적인 리뷰를 위해 두 단계로 나누어 리뷰하려 합니다-! 
우선 점수 계산 로직을 제외한 부분에서 리뷰 작성하였습니다-!
피드백 주신 후 다음 리뷰는 점수 계산 로직에 대해 집중적으로 얘기해볼까요-!? 
질문있으시면 언제든! 편하게! 질문주셔요!

2023-03-26 15:51 UTC, iphwade commented on src/main/java/chess/domain/ChessBoard.java
>      private final Map<Position, Piece> board;
static final과 final 사이는 공백이 컨벤션입니다-!

2023-03-26 15:51 UTC, iphwade commented on src/main/java/chess/controller/ChessController.java
> +    private ChessGame game;
일반적으로 View는 뷰 로직을, Service는 도메인 로직을 담당하고 그 사이에서 값을 전달하고 분리하는 등의 로직은 Controller를 통해 이루어집니다. 

그렇다면 ChessGame은 도메인 객체인가요-?

2023-03-26 15:51 UTC, iphwade commented on src/main/java/chess/database/DBChessBoardDao.java
> +        var query = "INSERT INTO move_position(fromMoveFile,fromMoveRank,toMoveFile,toMoveRank) VALUES(?,?,?,?)";
자바 버전 변경을 하셨나보군요!  👍

2023-03-26 15:51 UTC, iphwade commented on src/main/java/chess/database/DBChessBoardDao.java
> +        }
try with resource 로 자원반환을 하셨군요.
DB의 연결에 사용되는 객체들은 비교적 비용이 큰 객체들입니다. 👍

2023-03-26 15:51 UTC, iphwade commented on src/main/java/chess/database/DBChessBoardDao.java
> +public final class DBChessBoardDao implements ChessGameDao {
DB의 커넥션을 열어오고 가져오는 과정은 위 DAO 말고 다른 쪽에서도 충분히 확장되어 사용될 수 있어보입니다.
새로운 데이터를 저장해야하는 로직은 충분히 발생할 수 있어보입니다.
그러니 Connection을 맺는 과정은 따로 분리해보는 것은 어떨까요?

2023-03-26 15:51 UTC, iphwade commented on src/main/java/chess/Service/ChessService.java
> +        }
```
indent(인덴트, 들여쓰기) depth를 2를 넘지 않도록 구현한다. 1까지만 허용한다.
예를 들어 while문 안에 if문이 있으면 들여쓰기는 2이다.
힌트: indent(인덴트, 들여쓰기) depth를 줄이는 좋은 방법은 함수(또는 메서드)를 분리하면 된다.
```

모든 클래스에 적용해주세요!

2023-03-26 15:51 UTC, iphwade commented on src/main/java/chess/database/DBChessBoardDao.java
> +    public List<Position> select() {
select 만으로는 메서드가 하는 모든 역할을 나타내어보이지는 않습니다. 어떤 데이터들을 조회하는 지에 대한 내용을 추가하는 것은 어떨까요?

2023-03-26 15:51 UTC, iphwade commented on src/main/java/chess/database/DBChessBoardDao.java
> +             var preparedStatement = connection.prepareStatement(query)) {
prepareStatement 👍

2023-03-26 15:51 UTC, iphwade commented on src/main/java/chess/database/DBChessBoardDao.java
> +        }
null을 반환하는 것과 empty list를 반환하는 것에 장단에 대해 어떻게 생각하시나요-?!

2023-03-26 15:51 UTC, iphwade commented on src/main/java/chess/database/DBChessBoardDao.java
> +                positions.add(new Position(tomoveFile, tomoveRank));
FromMovePostion과 ToMovePostion을 한번에 담은 객체를 만들어보는 것은 어떨까요?

위와 같이 구현하게 되면 Postion List에 대한 다른 개발자가 예상하지 못할 수 있는 규칙이 생길 수 있어보입니다-!

2023-03-26 15:51 UTC, iphwade commented on src/main/java/chess/Service/ChessService.java
> +        if (gameNotation != null) {
empty list를 반환하는 것은 널 객체 패턴이라고 합니다-!
키워드로 학습하여 보실까요-? 
---
아마 아시겠지만 Piece의 구현체로 Empty가 존재하는 것도 마찬가지로 널 객체 패턴입니다.

널객체패턴은 장점도 있고 어떤 상황에서는 단점도 있습니다-!

2023-03-26 15:51 UTC, iphwade commented on src/main/java/chess/domain/ChessGame.java
> +        return chessBoard.countKing() == KING_COUNT;
두 가지로 해석이 가능하겠네요.
 - KING_COUNT는 ChessGame에 상태로 존재해야하는가?
 - 아니면 ChessBoard에 존재하여 응집도 있게 countKing을 노출시키지 않고 구현할 수 있는가?

비버께서는 어떻게 생각하시나요?!

2023-03-26 15:51 UTC, iphwade commented on src/main/java/chess/controller/ChessController.java
> +        chessService.deleteData(game.isKingsLive());
king이 살아있는 것이 게임의 종료를 의미한다는 것은 한번에 인지하기 쉽지 않습니다.
직관적으로 game의 statue가 존재하고 이를 토대로 게임의 종료를 확인하여 delete하는 것이 더 직관적이지 않을까요?

프로그래밍은 오해를 적게, 예측할 수 있게 작성하는 것이 중요합니다-!

2023-03-27 03:05 UTC, ingpyo commented on src/main/java/chess/domain/ChessGame.java
> +        return chessBoard.countKing() == KING_COUNT;
킹의 갯수를 세서 살아있는지 죽어있는지 판단하는게 게임의 역할인줄 알았는데 생각해보니 이렇게하면 game의 응집도가 떨어진다는 생각을 못해봤던거같아요,,, 수정하겠습니다!

2023-03-27 03:07 UTC, ingpyo commented on src/main/java/chess/Service/ChessService.java
> +        if (gameNotation != null) {
널 오브젝트 패턴을 적용하게 되면 null 포인터 예외를 방지할 수 있는 장점이 있지만 null 대신에 특정한 객체를 반환하므로 제가 생각하는 단점은 객체를 생성해서 메모리를 잡아먹는? 단점밖애 없는거 같은데 코일이 생각하시는 다른 단점도 있을까요??...🥲

2023-03-27 03:09 UTC, ingpyo commented on src/main/java/chess/database/DBChessBoardDao.java
> +                positions.add(new Position(tomoveFile, tomoveRank));
어제 오브젝트 책을 읽으면서 중복코드가 있을때 버그를 발생한다고 읽어 놓고 적용을 안했었네요...🥲

2023-03-27 07:27 UTC, ingpyo commented on src/main/java/chess/domain/ChessBoard.java
>      private final Map<Position, Piece> board;
와,,,처음 알았습니다 코일,,,, 앞으로 컨벤션 지키겠습니다!!

2023-03-28 17:18 UTC, iphwade commented on src/main/java/chess/Service/ChessService.java
> +        if (gameNotation != null) {
Null 포인터 예외가 터지지 않아서 시스템이 잘 돌아가는 것으로 오해할 수 있는 점도 단점으로 있습니다-!

2023-03-28 17:23 UTC, iphwade requested changes
안녕하세요 비버! 
몇가지 잘 적용해주셨네요!
적용은 잘 해주셨지만 제가 단 코멘트에 비버의 의견을 달아주실 수 있으실까요-?
비버가 생각하는 바와 제가 생각하는 바가 같은지 얘기해보며 코멘트를 드리고 싶어서요! :)

2023-03-28 17:23 UTC, iphwade commented on src/main/java/chess/Service/ChessService.java
> +        return chessGame.getWhiteScore();
개인적으로 getter 컨벤션에 로직이 들어가는 것을 지양하는데요!
calculate 라던가 다른 네이밍은 어떨까요-?

2023-03-29 04:09 UTC, ingpyo commented on src/main/java/chess/controller/ChessController.java
> +    private ChessGame game;
저도 서비스를 만들고 게임에서 담당하는 로직들을 서비스로 옮기면 되는거 아닌가라는 생각을 했지만 게임은 체스를 담당하는 정보전문가로 생각해서 도메인객체가 맞다라고 생각했습니다!

2023-03-29 04:11 UTC, ingpyo commented on src/main/java/chess/database/DBChessBoardDao.java
> +public final class DBChessBoardDao implements ChessGameDao {
커낵션과 seve와같은 디비에 접근하는 로직들이 한 세트로 생각했었는데 커낵션을 따로 분리해서 접근을 할 수 있다는 생각을 못해봤습니다... 수정했습니다!

2023-03-29 04:13 UTC, ingpyo commented on src/main/java/chess/database/DBChessBoardDao.java
> +    public List<Position> select() {
dao를 처음 써봐서 save,select와 같이 컨벤션이 있는줄 알았습니다...🥲

2023-03-29 04:17 UTC, ingpyo commented on src/main/java/chess/controller/ChessController.java
> +        chessService.deleteData(game.isKingsLive());
저도 이 부분에서 고민을 하였는데요 결론은 서비스에서 킹이 살아있는 것을 확인하고 삭제해주는 로직을 추가시켰습니다!
이러면 컨트롤러에서 코드를 읽을때 "king이 살아있는 것이 게임의 종료를 의미한다는 것은 한번에 인지하기 쉽지 않습니다." 이러한 오해가 없어질거같다는 생각을 하였습니다!

2023-03-29 04:31 UTC, ingpyo commented on src/main/java/chess/Service/ChessService.java
> +        return chessGame.getWhiteScore();
이러한 함수를 만들면서 조금 찜찜한 부분이있었는데 " getter 컨벤션에 로직이 들어가는 것을 지양하는데요!" 이러한 이유가 있었네요!!
수정했습니다!

2023-03-29 17:12 UTC, iphwade approved these changes
비버 고생이 많으셨습니다.
체스가 쉬운 미션이 아닌데 여러 방면으로 고민하시며 학습하시는 과정이 멋졌습니다. 
또, 전 단계에서 답변주신 부분들 확인했습니다-!
고민할만한 포인트들을 몇가지 달았는데요.
기회가 된다면 학습을 더 해보셔도 괜찮을 것 같습니다.
이번 미션 여기서 머지하도록 하겠습니다.
수고많으셨습니다. 👍

2023-03-29 17:12 UTC, iphwade commented on src/main/java/chess/domain/position/Path.java
> -    public List<Position> getBetweenPositions(Position fromPosition, Position toPosition) {
Path가 List<Postion>을 경로로 들고 있는 일급 컬렉션으로 구현하고
getBetweenPositions() 로직을 사용하여 초기화를 해주는 방법과 지금의 방법의 차이는 무엇일까요?

2023-03-29 17:12 UTC, iphwade commented on src/main/java/chess/controller/ChessController.java
> +        chessService.deleteData(game.isKingsLive());
game의 status라는 상태로 관리하지 않은 이유는 무엇일까요?

2023-03-29 17:12 UTC, iphwade commented on src/main/java/chess/view/OutputView.java
> +    }
VIew에서 ChessGame 도메인이 사용되고 있네요.

2023-03-29 17:12 UTC, iphwade commented on src/main/java/chess/domain/ChessBoard.java
> +    }
get이라는 네이밍은 저는 최대한 피하는 편이긴합니다.
그 이유는 아시겠지만 getter로 보이기 쉬워서인데요.
비버는 어떻게 생각하실까요?

2023-03-29 17:12 UTC, iphwade commented on src/main/java/chess/domain/ChessBoard.java
> +            return 0;
0에 대해서도 어떤 상태일 때 0으로 반환된다라는 것을 표현할 수 있지 않을까요?

2023-03-29 17:13 UTC, merged