[3, 4단계 - 체스] 박스터(한우석) 미션 제출합니다.
woowacourse/java-chess pull request #552
Opened 2023-03-25 14:00 UTC by drunkenhw

안녕하세요 웨지!
3, 4단계를 마무리 했지만 뭔가 찝찝하네요.. 더 깨끗하게 할 수 있을 것 같은데 도저히 생각이 안납니다..

감사합니다!!

2023-03-25 16:51 UTC, sihyung92 requested changes
5기 백엔드 최고 미남 박스터 안녕하세요! 웨지입니다.
리뷰 남겼으니 확인해주시고 반영해주세요 ㅎㅎ 💪
질문 DM 환영입니다!

2023-03-25 16:51 UTC, sihyung92 commented on src/main/java/chess/controller/MoveController.java
> +    // 이렇게 되면 chessRequest는 모든 컨트롤러가 받지만, getSourcePosition()이라는 메소드는 이 부분에서 밖에 쓰이지 않기 때문에 고민입니다..
우선 답변부터 하자면 요건 실패한 추상이라고 할 수 있겠습니다!
1. 저희가 바라던 것은 숫자 0,1이라는 값에 controller가 의존하지 않는 것입니다
2. 지금 Controller라는 인터페이스는 시그니처를 수정하기 않고는 위 요구사항을 반영할 수 없습니다

여기서 ChessRequest를 추가하여 해결할지는 선택의 영역인데요, 이 때 선택의 기준은 "현재 1개만 쓸텐데" 보다는 좀 더 긴 기준으로 봐야합니다. 
interface라는 문법을 사용하는 이유는 미래의 확장에 대비한 것이거든요~~

`void excute(ChessGameService chessGameService, OutputView outputView)` 는 Functional Interface로 치면 Consumer의 구조입니다. 입력은 고려하지 않고 chessGameService / OutputView에 가할 Action에만 집중하고 있습니다.

Controller는 체스게임에서 어떤 역할일까요? InputView의 요청을 전달받아 OutpurView로 전달하는 역할을 수행해야합니다. 앞으로 체스게임이 확장되면 "입력"에 대한 부분 요구사항이 많아질텐데, 이 부분은 ChessRequest라는 객체로 추상화 했다면 3개의 인자를 받는것도 선택의 이유가 될 수 있을거 같아요. 

근데 이 기준으로 보면 OutputView로 역할을 하는 것도 다소 불편합니다. OutputView 구현체에 대한 의존인데, OutputView가 아닌 다른 View 할 때도 Controller를 쓰고 싶다는 요구사항이 들어올 확률이 높거든요. 이래서 SOLID 중 DIP는 구현체에 의존하지 말라는 가르침을 전합니다. 미래에 대비한 것이 추상화인데, 구현체에 의존하면 확장이 어렵거덩여..

말이 길어졌는데 저는 위 관점에서 ChessRequest 받아도 괜찮을거 같아요! 그와 별개로 Controller가 적절한 추상이었냐고 물으면 살짝 아쉽다 드리겠습니다 ㅎㅎ
1. 구현체에 의존 중 임
2. `Controller`라는 상용구를 써서 헷갈림

---
위와 별개로 이 주석은 PR에 코멘트로 만드는게 적절해보여요!! 
추가 작업이 필요하다면 `// todo` 주석을 활용해주시고, 다른 개발자들이 알아야 할 정보라면 적절히 한 줄로 줄여 
`// chessRequest의 의존성을 추가해야할지 결정 필요` 식으로 작성해주세요. 다음 PR 부터는 이런 부분들 모두 코멘트로 바꾸는 연습을 해봅시다~~

2023-03-25 16:51 UTC, sihyung92 commented on src/main/java/chess/controller/ChessController.java
> +        if (service.isGameEnd()) {
move의 return 값이 없는데 그 때 "종료되었음"을 전달할 수 없을까 고민해보셔요 ㅎㅎ `boolean`말고 객체화 해보셔요~~
이유 : move() 리턴값이 boolean이면 게임 종료가 아니라 이동 실패한걸로 오해할 수 있음

2023-03-25 16:51 UTC, sihyung92 commented on src/main/java/chess/controller/ChessController.java
> +        if (service.isGameEnd()) {
코드 흐름을 봤는데 위 코드리뷰를 반영해도 play() 안에서 커버가 안 되겠네요 ㅎㅎ 
controller.execute()가 GameCommand를 반환하는 식으로 구현하면 어떨까요 ㅎ

2023-03-25 16:51 UTC, sihyung92 commented on src/main/java/chess/controller/ChessController.java
> +        commands.put(GameCommand.STATUS, ignored -> new StatusController());
게임 도중에 `status` 명령어에 대한 안내가 없어서 맥도날드 히든 메뉴인 트리플 치즈버거가 생각났습니다~~!
status에 대한 안내문도 추가해주셔요 ㅎㅎ

2023-03-25 16:51 UTC, sihyung92 commented on src/main/java/chess/dao/ChessGameJdbcDao.java
> +    public List<MoveHistory> findAll() {
이벤트 소싱을 의도하고 구현하신건가요? ㅎㅎ
현재 상태가 아닌 'move_history'를 통해 구현하신 이유가 있을까요?

2023-03-25 16:51 UTC, sihyung92 commented on src/main/java/chess/domain/board/Board.java
> +    public Board() {
부생성자 좋네요 ㅎ

2023-03-25 16:51 UTC, sihyung92 commented on src/main/java/chess/domain/piece/RoleType.java
> +public enum RoleType {
Score라는 명명이 낫지 않았을까요? 이미 클래스명에 어떤 기물인지 나와 있는데 `RoleType`은 중복표현된 느낌이어서요. (의도하신게 아니라면 말씀해주세요!)

2023-03-25 16:51 UTC, sihyung92 commented on src/main/java/chess/service/ChessGameService.java
> +    // 이렇게 return과 작동 2가지 일을 하는 메서드도 괜찮을까요?
오 저희는 한 가지의 역할 어쩌고.. 책임이 어쩌고.. 하는 소리를 많이 들었지만 사실 2가지 일을 하는 메서드는 살다보면 숱하게 겪는 일입니다. 두 가지 일 할수도 있죠.

하지만 가장 위험한 건 _**두 가지 일을 하면서 하나의 일만 하는 척 하는 메서드**_ 입니다! (중요해서 bold + italic처리 했습니다) 
해당 코드는  버그가 발생할 가능성이 매우매우~~ 높습니다. 다른 개발자는 해당 메서드를 호출하면서 DB가 밀릴거라는 상상을 할 수 없을 거거든요. 차라리 두 가지 일을 한다고 메서드명을 솔직히 고백하는게 백만 배 낫습니다.
(진짜 버그내는 코드 vs 겉보기에만 조금 안 좋아보이는 코드)
인생이랑 비슷해서 재밌네요 ㅎ

---
위의 교훈과 별개로 clear(); 메서드를 클라이언트 코드가 호출할지 말지 더 나을거 같아요 ㅎ

2023-03-25 16:51 UTC, sihyung92 commented on src/main/java/chess/controller/GameCommand.java
>      public static GameCommand of(String input) {
전 of() 메서드가 뷰의 역할이라고 생각합니다 ㅎ 컨트롤러에서는 "GameCommand라는 enum을 주세요"로 충분하다고 봐요. "start"라고 해야 START가 나온다는 걸 알아야한다는 건 (0,1) 인덱스가 source, target을 알아야하는 것과 비슷한 맥락에서 console view에 의존적인 내용 같습니다.

2023-03-25 16:51 UTC, sihyung92 commented on src/main/java/chess/dao/ChessGameJdbcDao.java
> +    private static final String PASSWORD = "root"; // MySQL 서버 비밀번호
커넥션 정보는 별도 객체로 만들면 어떨까요?

2023-03-25 16:51 UTC, sihyung92 commented on src/main/java/chess/dto/MoveHistory.java
> +public class MoveHistory {
단순 dto로 보기엔 로직에서 중추적인 역할을 수행하고 있는 것 같아요. findAll을 해서 순차적용하는 순간부터 단순히 source, target 데이터가 아니라 "시간 흐름"에 따라 정렬가능한 위치 역할이 추가 된 거 같습니다. 도메인쪽으로 옮겨보면 어떨까요?

2023-03-25 16:51 UTC, sihyung92 commented on src/main/java/chess/domain/game/GameResult.java
> +public class GameResult {
코드가 가독성 좋게 짜여져 읽기 좋았습니다 👍

2023-03-25 16:51 UTC, sihyung92 commented on README.md
> +    - [ ] 킹이 잡히면 게임을 끝낸다.
체크가 빠진 것 같아요 ㅎ

2023-03-27 00:41 UTC, drunkenhw commented on src/main/java/chess/controller/MoveController.java
> +    // 이렇게 되면 chessRequest는 모든 컨트롤러가 받지만, getSourcePosition()이라는 메소드는 이 부분에서 밖에 쓰이지 않기 때문에 고민입니다..
controller라 네이밍을 한 이유는 단지 outputView 와 service를 관리하고 있어서 였습니다.
하지만 하는 일은 무언가를 실행하는 것 뿐입니다.  네이밍을 잘못하고, 웨지 말대로 인터페이스가 구현체에 의존하는 것도 좋아보이지 않아서Functional Interface로 변경 후 메인 controller에서 처리하도록 변경했습니다!
제가 잘 이해해서 반영한건지 모르겠네요 감사합니다

2023-03-27 00:42 UTC, drunkenhw commented on src/main/java/chess/controller/ChessController.java
> +        commands.put(GameCommand.STATUS, ignored -> new StatusController());
죄송합니다...ㅋㅋ
 추가했습니다!

2023-03-27 00:51 UTC, drunkenhw commented on src/main/java/chess/dao/ChessGameJdbcDao.java
> +    public List<MoveHistory> findAll() {
움직인 기보를 저장하면 일단 저 같은 초보자에게 꼭 필요한 무르기라는 기능도 추가할 수 있습니다!
 그리고 체스 게임 규칙인 앙파상, 캐슬링과 같은 기능을 쉽게 구현할 수 있을거라 생각했습니다.
또 상태를 저장하는 것은 여러 정보를 따로 저장하여 관리해야한다는 점이 불편해보였습니다.
 turn이라던지 말의 색깔, 말의 종류 이러한 정보도 같이 저장해야하기 때문에 move history를 저장하는 것이 쉽고 얻을 수 있는 이점이 많아보였습니다.

2023-03-27 00:53 UTC, drunkenhw commented on src/main/java/chess/domain/piece/RoleType.java
> +public enum RoleType {
roleType을 만든 이유는 pawn일 경우 점수 계산을 다르게 한다거나 king이 죽으면 게임이 끝난다거나 하는 로직을 구현하려면 추상 클래스인 piece에 `isPawn()`, `isKing()`과 같은 메서드가 추가되야하고 piece를 상속받은 구현체들은 전부 override 해줘야하는 점이 불편했습니다. 
그래서 `isSameRoleType(PAWN)` 이런 방법으로 찾아오기 위해 추가했습니다..

2023-03-27 00:55 UTC, drunkenhw commented on src/main/java/chess/service/ChessGameService.java
> +    // 이렇게 return과 작동 2가지 일을 하는 메서드도 괜찮을까요?
게임이 끝나면 delete 하지 않고 다른 게임방에 들어가도록 변경하였습니다.!

2023-03-27 01:10 UTC, drunkenhw commented
안녕하세요 천사 웨지 👼  🥔 
리뷰주신 내용을 최대한 반영해보려고 노력했습니다!
하지만 제가 잘못 이해한 부분도 있을 것 같습니다..
좀 더 잘 해보고 싶었지만 예비군 때문에 급하게 제출하게 돼서 아쉽습니다 ㅜㅜ
```sql
CREATE TABLE `game` (
  `id` int PRIMARY KEY AUTO_INCREMENT,
  `finished` boolean
);

CREATE TABLE `move_history` (
  `id` int PRIMARY KEY AUTO_INCREMENT,
  `source` varchar(2),
  `target` varchar(2),
  `game_id` int
);

ALTER TABLE `move_history` ADD FOREIGN KEY (`game_id`) REFERENCES `game` (`id`);
```
이번에는 게임 방을 입장하는 기능은 없지만, 게임을 초기화하거나 왕이 죽으면 게임의 데이터를 삭제하지 않고 새로운 방을 만들어서 하도록 수정해봤습니다!

감사합니다!

2023-03-28 12:35 UTC, sihyung92 commented on src/main/java/chess/dao/ChessGameJdbcDao.java
> +    public List<MoveHistory> findAll() {
ㅎㅎ 네 말씀하신것처럼 어떤 객체의 "현재 상태"를 저장하고 계속 update하는 것이 아니라 (ex. 보드의 현재 모든 좌표값을 DB에 저장하고 로드함)
객체의 상태를 바꾸는 "활동"을 저장하고 꺼내오는 것(ex. 이동 기록을 모두 저장함)을 이벤트 소싱이라고 부릅니다.
장점과 단점이 있는데, 가볍게 찾아보시구 어렵다면 그냥 이런게 있구나~~ 하고 넘어가셔도 좋습니다

2023-03-28 13:41 UTC, sihyung92 requested changes
안녕하세요 우테코 최고미남 박스터! 
빠르게 구현해서 요청 주셨네요 ㅎ 어려운 미션인데 구현하시느라 수고 많으셨습니다!
ChessRequest와 MoveHistory에 남겨드린 리뷰 반영하시면 머지해도  생각합니다 (다음 요청은 리뷰없이 머지지만요 🥲)
궁금하신 점 있으시면 DM 주시고 남은 1단계 잘 마무리하시길 바랍니다!!

2023-03-28 13:41 UTC, sihyung92 commented on src/main/java/chess/dto/ChessRequest.java
> +    }
parsing 책임을 InputView와 나누고 있단 생각이 들었어요. InputView쪽에서 parsing하고 Command 객체로 넘겨줘도 되지 않을까요?

2023-03-28 13:41 UTC, sihyung92 commented on src/main/java/chess/domain/position/Position.java
> +    public boolean isSameRank(RankCoordinate other) {
저는 주로 getter, equals, hashcode, toString 같은 보일러 플레이트 코드는 가장 아래로 내리고 의미가 있는 메서드는 그거보단 위로 올리는 편입니다!

2023-03-28 13:41 UTC, sihyung92 commented on src/main/java/chess/service/MoveHistory.java
> +    private final List<MoveDto> moveDtos;
전 Dto는 계층 이동용 객체라고 생각해서 Dto에 해당하는 개념이 있어야 한다고 생각해요 ㅎ
그래서 MoveDto에 대응되는 개념인 Move가 도메인 패키지나 해당 패키지에 있으면 좋을 것 같아요.
(혹은 Move만 쓰고 MoveDto를 쓰지 않던가요! 기계적으로 Dto를 쓰면 오히려 무의미한 변환코드가 생기기도 합니다.)

2023-03-28 13:41 UTC, sihyung92 commented on src/main/java/chess/service/ChessGameService.java
> +        if (chessGameJdbcDao.findGameIdByNotFinished() == NOT_EXIST) {
exist를 써도 되지 않았을까요? DB에서 전체 개수를 count하는건 부하가 심한 연산이라서 비교적 부하를 덜어줄 수 있는 existNotFinishedGame 등을 활용하는 게 나을듯 하네요 ㅎ

2023-03-30 07:45 UTC, drunkenhw commented on src/main/java/chess/service/MoveHistory.java
> +    private final List<MoveDto> moveDtos;
문자열을 변환 하고, 객체를 문자열로 변환하고 DB에 삽입, 조회를 하기 위한 작업을 어디서 해야할 지 모르겠습니다.. 
웨지는 보통 어디에서 변환 해주나요?

2023-03-30 07:45 UTC, drunkenhw commented on src/main/java/chess/controller/ChessController.java
>  public class ChessController {
하하 감사합니다

2023-03-30 14:11 UTC, sihyung92 commented on src/main/java/chess/service/MoveHistory.java
> +    private final List<MoveDto> moveDtos;
패키지와 패키지간에도 의존관계가 있습니다. 객체와 객체가 양방관계를 맺으면 좋지 않은 신호이듯이, 패키지도 동일한 원칙이 적용됩니다. 
예를들어 도메인 패키지가 데이터베이스 패키지를 참조하고 있다면, 도메인 패키지 쪽에서 맵핑 객체를 만들든 변환 메서드를 넣든간에 데이터베이스에 넣기 위한 변환 작업을 해주는 편입니다.
반대 경우였다면, 데이터베이스 패키지에서 도메인 객체를 받아와 변환해주었겠죠.  

위처럼 패키지 의존관계를 고려해 작업하는 편입니다!

2023-03-31 02:24 UTC, sihyung92 commented
안녕하세요 우테코 역대 최고 미남 박스터!
미션은 즐거우셨나요? 문자열 변환은 코멘트 하나 남겨두었는데요, 확인해보시구 한번 생각해보셔요 ㅎㅎ
즐거운 방학 보내세요~~

2023-03-31 02:34 UTC, sihyung92 approved these changes
안녕하세요 우테코 역대 최고 미남 박스터!
미션은 즐거우셨나요? 문자열 변환은 코멘트 하나 남겨두었는데요, 확인해보시구 한번 생각해보셔요 ㅎㅎ
즐거운 방학 보내세요~~

2023-03-31 02:34 UTC, merged