[3, 4단계 - 체스] 쥬니(전정준) 미션 제출합니다.
woowacourse/java-chess pull request #570
Opened 2023-03-26 16:54 UTC by cpot5620

안녕하세요 라빈 !
우테코 5기 쥬니입니다. 행복한 주말 보내셨나요 ? 😃

체스 미션 3, 4단계 필수 요구사항 + 선택 요구사항 중 `체스 게임방을 만들고 입장할 수 있는 기능`을 구현하여 제출합니다.

해당 미션에 사용한 데이터베이스 테이블은 아래와 같습니다.
```mysql
create table board (
    board_id int auto_increment PRIMARY KEY,
    source char(2),
    piece char(2),
    room_name varchar(255)
);

create table room (
	room_name varchar(255) PRIMARY KEY,
    is_white_turn boolean
);
```

해당 미션을 진행하면서 궁금했던 점은 아래와 같습니다.

**1. 추가 기능 구현 과정에서 getter를 사용함에 따라 기존의 메서드들은 어떻게 해야하는가?**
미션을 진행하면서, `getter`의 사용을 지양하는 대신, 해당 객체에게 질문(?)을 던지라는 이야기를 많이 들었습니다.
실제로, 미션을 진행하면서 객체에게 질문을 던지는 메서드들을 작성하고자 노력하였습니다.
하지만, 데이터베이스 연동 과정에서 `getter`를 사용해야하는 객체가 존재했습니다.
`getter`를 열어둘 경우, 기존에 작성한 `객체에게 질문하는 메서드`가 불필요하지 않을까 ? 라는 생각이 듭니다.
그렇다고 해서, 기존의 메서드들을 제거하는 것은 부적절하다고 생각합니다.

위 상황이 어색하다고 느끼는 것이 아직 초보 개발자라서 그런 것일까요 😢
라빈은 위와 같은 상황을 어떻게 생각하시는지 궁금합니다.

**2. Controller의 코드 라인 수가 너무 많지 않은가 ?**
해당 미션에서 `Controller`의 코드 라인 수는 200줄이 넘어가고 있는 상황입니다.
현재 Controller는 `도메인의 흐름 제어`만을 위한 코드로 구성되어 있다고 생각됩니다. (제가 잘못 생각했다면 죄송합니다 😭)
사용자에게 입력에 따라, 적절한 메서드를 호출과 예외가 발생하더라도 프로그램이 종료하지 않도록 하는 등의 역할이 `Controller`의 역할이라고 생각합니다. 
`Service` 계층을 두지 않았기 때문에, `Controller`에 책임이 가중되는 것은 어쩔 수 없는 것일까요 ?
아니면, 제가 생각하는 `도메인의 흐름 제어`의 범위가 너무 큰 것일까요 ?

2023-03-29 04:49 UTC, giantim requested changes
쥬니 안녕하세요! 리뷰어 라빈입니다 👋
3, 4단계 미션도 잘 구현해 주셨네요. 고생 많으셨습니다.
질문 주신 내용에 대해서 제 의견 남겨드릴께요!

#### 추가 기능 구현 과정에서 getter를 사용함에 따라 기존의 메서드들은 어떻게 해야하는가?
음.. 이 부분은 구체적으로 어느 클래스들에 적용한 내용이신지 다시 알려주실 수 있으실까요? 객체의 역할과 책임에 따라 좀 달라질 수 있을것 같아서요. DTO 객체에 getter를 열어놓은것 때문에 그러실까요? 데이터 전달이 목적인 객체에서는 무방해 보이는데요! 제가 맞게 답변했는지 조금 헷갈리는데 예시를 하나 들어주시면 좋을것 같네요 😉

#### Controller의 코드 라인 수가 너무 많지 않은가 ?
적절한 메소드 호출과 예외에 따라 프로그램 종료를 잘 방어하고 있다고 생각해요. 하지만 현재 그것을 하나의 컨트롤러에서 처리하고 있다 보니 코드 라인 수가 늘어난 것은 어쩔수가 없겠네요. 쥬니가 현재 정의한 각 도메인 객체들의 역할때문에 게임을 진행하기 위한 메소드 호출 순서들 때문에 라인 수가 늘어날 수 있고, 사용자의 입력값을 받는 구현 로직에 따라 늘어날 수 있어요. 좀 더 미션을 진행해 가면서 새로운 계층도 도입해보고 프레임워크도 공부하다보면 개선할 수 있지 않을까요?

추가적으로 드리고 싶은 리뷰가 있는데요. room 테이블을 정의할 때 room_name을 PK로 설정하신 이유가 궁금하네요. 해당 테이블도 auto increment key를 식별자로 가지면 어떨까요? board가 room과의 관계를 컬럼으로 가져갈 때 데이터 크기도 줄 수 있고 room_name을 PK로 두었을 때 어떤 이점이 있을지 잘 모르겠네요 🤔

추가적으로 몇 가지 리뷰 남겨드렸습니다. 확인 부탁드릴께요!

2023-03-29 07:32 UTC, cpot5620 commented on src/main/java/chess/domain/Command.java
> +public enum Command {
해당 Command 클래스를 InputView와 Controller에서 접근하고 있습니다.
MVC 패턴에서, View와 Controller가 domian을 알아도 된다고 생각하여 패키지 분리를 하다보니, domain 영역으로 분리하였습니다. domain 보다는 view에 위치하는 것이 옳은 것 같습니다.

해당 사항 반영하여 수정하였습니다 !

2023-03-29 07:53 UTC, cpot5620 commented on src/main/java/chess/domain/RoomName.java
> +    }
`방 이름은 1글자 이상, 10글자 이하여야 한다.`라는 기능 요구사항을 추가하였습니다.
이에 따라, `RoomName` 객체 생성시 유효성 검사를 수행하도록 수정하였습니다.

데이터베이스의  `VARCHAR(1)과 VARCHAR(255)`의 성능상의 차이가 없다고 알고 있는데, DDL도 수정해야 할까요 ?

2023-03-29 08:00 UTC, cpot5620 commented on src/main/java/chess/dto/FileRenderer.java
> +    }
file이 맞습니다.. 혼란을 일으켜드려서 죄송합니다 😭

2023-03-29 08:48 UTC, cpot5620 commented on src/main/java/chess/dto/SquareRenderer.java
> +public class SquareRenderer {
dto의 `전달`이라는 역할에 마음대로 `변환`도 포함한다고 생각했습니다. 감사합니다 라빈 😭
해당 클래스들은 util 패키지로 분리하는 것이 적절하다고 생각합니다.
view와 controller에서 사용하기 위한 `Command` 클래스와 달리, 해당 클래스들은 데이터베이스에 저장하기 위한 목적으로도 사용됩니다. 이에 따라, view 패키지로 분리한 `Command`와 달리, util 패키지가 적합하다고 생각합니다.

2023-03-30 23:51 UTC, giantim commented on src/main/java/chess/domain/RoomName.java
> +    }
DDL 수정은 하지 않아도 괜찮아 보이네요 :)

2023-03-30 23:53 UTC, giantim commented on src/main/java/chess/controller/ChessController.java
> +        finalize(chessGame);
이미 같은 고민을 하고 계셨군요! ☺️
앞으로 이런 상황이 발생할 때 여러 방면으로 고민해 볼 수 있겠네요 👍

2023-03-31 00:18 UTC, giantim approved these changes
쥬니 안녕하세요! 라빈입니다 👋
피드백 드린 내용 잘 반영해 주셨네요 👍 레벨1 마지막 미션 고생 많으셨습니다!
추가적으로 getter에 대해 의견 드리면요! 이런 경우에는 다른 객체들과 협력하기 위해 필요한 메소드를 만드는것과 getter 두 가지 제공하는 것 괜찮아 보이네요! 두 메소드의 사용처가 다를 수 있고 Square가 갖고 있는 값 자체를 외부에 제공해야할 때와 Square가 담당해야하는 책임에 따라 isSame~ 과 같은 메소드를 제공해야할 수 있어서요! 지금 구조도 충분히 괜찮은것 같습니다.

수고 많으셨습니다 🎉

2023-03-31 00:18 UTC, giantim commented on src/main/java/chess/dao/JdbcDao.java
> +public class JdbcDao {
기존 구조가 더 적절해 보였는데요!
현재 클래스 이름만 봤을 때 데이터에 접근하는 객체의 역할인것은 알겠는데 어떤 도메인과 연관이 있는지는 알 수 없네요. 어떤 API를 제공할지 예상할 수 없어서 더 의미있는 이름을 주면 좋을것 같아요.
두개의 DAO를 하나로 합치신 의도가 궁금하네요 ☺️

2023-03-31 00:18 UTC, merged