[3, 4단계 - 체스] 레오(차영호) 미션 제출합니다.
woowacourse/java-chess pull request #572
Opened 2023-03-26 17:35 UTC by youngh0

안녕하세요 시카~ 리뷰이 레오입니다!!

1,2 단계에서 해주신 리뷰 정말 감사합니다!!

jdbc를 처음하고, 선택 요구사항도 구현하려고 시도하다보니 리뷰 요청이 많이 늦어졌네요.. 사용자 별 체스게임 기록은 구현하지 못했습니다…

3,4 단계를 진행하면서 기존 컨트롤러의 run메서드가 너무 지저분하단 생각이 들어 커맨드 패턴을 적용하려고 해봤습니다. 이 과정에서 각 커맨드 별 로직을 컨트롤러에서 정의했더니 컨트롤러가 깔끔해졌지만, 무거워진 느낌이 드네요…

db를 적용하면서 몇 가지 궁금한 점이 생겨서 질문 남깁니다..!

### dto를 어디서 객체로 변환해야 하는지

현재는 jdbc를 이용해 MySQL에서 제공하는 타입으로 저장해서 크게 상관없는 주제라고 생각합니다. 그러나, 추후 JPA를 사용할 때 결국 객체를 저장하게 될텐데 어느 레이어에서 dto를 객체로 변환하는게 적절하다고 생각하시는지 궁금합니다!!

저는 결국 db쿼리가 나가기 전 레이어인 service레이어에서 변환해주는 것이 적절하다고 생각합니다. 그 이유는, 

1. service레이어는 도메인 객체들의 다양한 비즈니스 로직을 조합해 서비스의 핵심 비즈니스 로직을 수행하고,
2. 실제 쿼리가 나가는 dao레이어의 메서드를 호출하기 때문입니다. 

이러한 이유로 service레이어가 dto를 엔티티로 변환하는 작업을 수행하는게 적절하다고 생각하는데, 시카의 의견이 궁금합니다:)🙂

### dto네이밍

dto에 대해 찾아보니 아무리 같은 데이터를 가진 dto라도 레이어 별로 다른 dto를 생성해 넘겨주는 것이 좋다는 글을 봤습니다.

controller → service → dao로 데이터가 흐를 때, view에서 받은 dto를 컨트롤러에서 바로 service레이어로 넘겨준다고 가정해보겠습니다. 이 경우 controller가 view에게 받는 dto포맷이 변경될 경우 service레이어까지 수정이 일어나는 경우가 있기 때문에 레이어 별로 dto를 가져가는게 좋다는 글을 봤습니다.

그래서 이를 지키려고 하다보니 네이밍 중복이 발생해 많은 고민을 했습니다. 예를 들어 ChessGame을 반환하는 dto의 경우 ChessGameDto라고 명시할 수 있다고 생각합니다. 그러나, 이를 dao, service레이어 각각에서 사용하려고 하다 보니 결국 dto에 레이어를 명시하게됐습니다. ex)`ChessGameDaoResponseDto` 

이 방법에 대해 어떻게 생각하시는지 궁금합니다!!

### db 테스트

데이터베이스 관련 테스트를 처음 시도하려고 하니 너무 막막했습니다. 어떻게 하면 디비에 종속적이지 않은 테스트를 구성할지 많은 고민을 했습니다. 우선, 테스트코드의 결과가 디비에 반영되지 않도록ConnectionGenerator를 생성하고 테스트 용 connection은 autoCommit은 false로 설정했습니다.

이후, 계속 생각해봤지만 실패해서 계속 고민해봐야 할 거 같습니다. 현재는 디비에 저장된 데이터와 상관없는 `새로운 게임 생성, 게임 방 전체 목록 조회 시 예외 발생 안하는지, pk가 0인 게임 방 조회 시 실패 테스트` 이렇게 3가지 테스트만 존재합니다.

중간에 save명령어를 통한 데이터 업데이트, 특정 게임 방 조회 등등의 테스트는 디비 내부 데이터와 연관이 있기 때문에 진행하지 못했습니다.

이와 관련해 추천해주실 만한 키워드나 인사이트가 있으실까요..?

<hr>
controller → service → dao 구조에 익숙치 않다보니 다양한 개념이 머릿속에서 섞여서 질문이 많아졌네요… 

3,4단계 리뷰도 잘 부탁드리겠습니다!!!!!

2023-03-29 16:23 UTC, jaeyeonling requested changes
안녕하세요 레오! 대타 리뷰어 네오입니다 😎 
리뷰를 이어서 하다보니 모든 내용을 확인할 수 없어서 해당 PR 위주로 리뷰하였습니다~
놓친 부분이나 궁금한 점 있으면 편하게 질문 주시고 코멘트 확인 부탁드릴게요!

2023-03-29 16:23 UTC, jaeyeonling commented on src/test/java/dao/ChessDaoTest.java
> +}
https://velog.io/@d-h-k/intellij-%ED%8C%8C%EC%9D%BC%EB%81%9D%EC%97%90-%EA%B0%9C%ED%96%89%EC%9D%84-%EC%9E%90%EB%8F%99%EC%9C%BC%EB%A1%9C-%EC%B6%94%EA%B0%80%ED%95%98%EB%8A%94-%EB%B0%A9%EB%B2%95 

참고 부탁드려요~

2023-03-29 16:23 UTC, jaeyeonling commented on src/test/java/domain/game/BoardTest.java
> +class BoardTest {
테스트가 자세하네요 👍

2023-03-29 16:23 UTC, jaeyeonling commented on src/main/java/dao/ChessGameDao.java
> +            try (Connection connection = connectionGenerator.getConnection()) {
autoCommit 옵션을 건드리셔서 추가 리뷰 드리자면..!
ChessBoard insert 도중에 실패할 경우 일부만 저장이 되는 상황이 생길 것 같은데요. 이러한 문제는 어떻게 해결할 수 있을까요?

2023-03-29 16:23 UTC, jaeyeonling commented on src/main/java/dto/dao/ChessGameDaoResponseDto.java
> +public class ChessGameDaoResponseDto {
> 현재는 jdbc를 이용해 MySQL에서 제공하는 타입으로 저장해서 크게 상관없는 주제라고 생각합니다. 그러나, 추후 JPA를 사용할 때 결국 객체를 저장하게 될텐데 어느 레이어에서 dto를 객체로 변환하는게 적절하다고 생각하시는지 궁금합니다!!
> 
> 저는 결국 db쿼리가 나가기 전 레이어인 service레이어에서 변환해주는 것이 적절하다고 생각합니다. 그 이유는,
> 
> service레이어는 도메인 객체들의 다양한 비즈니스 로직을 조합해 서비스의 핵심 비즈니스 로직을 수행하고,
> 실제 쿼리가 나가는 dao레이어의 메서드를 호출하기 때문입니다.
> 이러한 이유로 service레이어가 dto를 엔티티로 변환하는 작업을 수행하는게 적절하다고 생각하는데, 시카의 의견이 궁금합니다:)🙂

크게

- 도메인에서 바로
- DTO에서 도메인을 받아서 
- Service에서 변환
- 변환의 책임을 가지는 클래스 분리

로 나눠질 것 같은데요. 각 특징마다 장단점이 명확해서 리오의 판단에 맞게 선택하시면 될 것 같네요!
Service에서 담당할 경우 Service의 역할은 무엇이지? 라는 관점으로 접근을 해보면 새로운 고민거리를 얻으실 수 있을 것 같습니다 :) 
학습하는 과정에서 추가적인 궁금증이 생기면 편하게 물어보세요~

2023-03-29 16:23 UTC, jaeyeonling commented on src/main/java/dto/service/ChessGameCreateResponseDto.java
> +public class ChessGameCreateResponseDto {
> dto에 대해 찾아보니 아무리 같은 데이터를 가진 dto라도 레이어 별로 다른 dto를 생성해 넘겨주는 것이 좋다는 글을 봤습니다.
> 
> controller → service → dao로 데이터가 흐를 때, view에서 받은 dto를 컨트롤러에서 바로 service레이어로 넘겨준다고 가정해보겠습니다. 이 경우 controller가 view에게 받는 dto포맷이 변경될 경우 service레이어까지 수정이 일어나는 경우가 있기 때문에 레이어 별로 dto를 가져가는게 좋다는 글을 봤습니다.
> 
> 그래서 이를 지키려고 하다보니 네이밍 중복이 발생해 많은 고민을 했습니다. 예를 들어 ChessGame을 반환하는 dto의 경우 ChessGameDto라고 명시할 수 있다고 생각합니다. 그러나, 이를 dao, service레이어 각각에서 사용하려고 하다 보니 결국 dto에 레이어를 명시하게됐습니다. ex)ChessGameDaoResponseDto
> 
> 이 방법에 대해 어떻게 생각하시는지 궁금합니다!!

DTO는 개념적인 내용이라 꼭 이름에 DTO를 사용하지 않으셔도 됩니다.
예를 들어 `ChessGameCreateResponseDto`에서 `Response`와 `DTO`는 같은 의미를 나타낸다고 생각해서 `ChessGameCreateResponse` 만으로 충분히 의미를 담을 수 있을 것 같아요!

2023-03-29 16:23 UTC, jaeyeonling commented on src/main/java/dao/TestDbConnectionGenerator.java
> +public class TestDbConnectionGenerator implements ConnectionGenerator {
> db 테스트
> 데이터베이스 관련 테스트를 처음 시도하려고 하니 너무 막막했습니다. 어떻게 하면 디비에 종속적이지 않은 테스트를 구성할지 많은 고민을 했습니다. 그 이유는, 디비 내부 데이터에 종속적인 테스트를 작성하면 제 로컬에서만 정상적으로 작동하기 때문입니다.
> 우선, 테스트코드의 결과가 디비에 반영되지 않도록ConnectionGenerator를 생성하고 테스트 용 connection은 autoCommit은 false로 설정했습니다.
> 
> 이후, 계속 생각해봤지만 실패해서 계속 고민해봐야 할 거 같습니다. 현재는 디비에 저장된 데이터와 상관없는 새로운 게임 생성, 게임 방 전체 목록 조회 시 예외 발생 안하는지, pk가 0인 게임 방 조회 시 실패 테스트 이렇게 3가지 테스트만 존재합니다.
> 
> 중간에 save명령어를 통한 데이터 업데이트, 특정 게임 방 조회 등등의 테스트는 디비 내부 데이터와 연관이 있기 때문에 진행하지 못했습니다.

먼저 테스트하려는 대상을 명확하게 하는 것이 좋은데요.
DB와의 통신을 테스트하는 것이 목적이라면 실제 DB에 의존적인 코드가 나올 수밖에 없을 것 같아요.
반면 DB의 통신을 테스트하는 것이 목적이 아니라면 영속화 계층을 분리하여 테스트를 할 수 있을 것 같은데요.
방법은 많이 있지만 먼저 강의에서 다뤘던 테스트 더블을 사용해보면 좋겠습니다 :)

2023-03-30 06:39 UTC, youngh0 commented on db/ddl.sql
> +create table chess.chess_board
후자의 네이밍이 현재 테이블 구조를 더 잘 나타낸다고 생각되네요.
수정했습니다!! 감사합니다:)

2023-03-30 06:42 UTC, youngh0 commented on src/main/java/dao/ChessGameDao.java
> +        final String loadQuery = "select piece_type from chess_board where game_room_id_fk = ?";
예약어의 경우 대문자로 작성하려 했는데 놓쳤습니다.
수정했습니다!! 감사합니다🙂

2023-03-30 06:44 UTC, youngh0 commented on src/main/java/dao/TestDbConnectionGenerator.java
> +            connection.setAutoCommit(false);
데이터베이스 관련 테스트를 실행할 때 마다 해당 데이터는 저장하고 싶지 않아서 인터페이스로 분리했습니다.
테스트에서 사용하는 커넥션은 autoCommit(false)로 설정하고, 프로덕션에서의 커넥션은 autoCommit을 따로 건들지 않았습니다!!

2023-03-30 11:10 UTC, youngh0 commented on src/main/java/dao/ChessGameDao.java
> +            try (Connection connection = connectionGenerator.getConnection()) {
우선 첫 번째 코멘트에 대해서 기물들을 저장하는 것은 하나의 트랜잭션이기 때문에 기물 하나하나 저장할 때 마다 커넥션을 생성하는 것은 매우 비효율적이라는 생각이 드네요... 
궁금한 사항이 있는데 디비 커넥션 하나 당 하나의 트랜잭션에 사용된다고 알고 있는데 커넥션 하나로 여러 개의 트랜잭션을 처리하는 경우도 있나요??

2023-03-30 11:12 UTC, youngh0 commented on src/main/java/dao/ChessGameDao.java
> +            try (Connection connection = connectionGenerator.getConnection()) {
두 번째 코멘트의 경우,실제로 기물 저장 중 특정 포지션에서 예외를 던지니 일부 기물만 저장되고 있었습니다. 그래서 커넥션을 생성하는 try...with resource내부에 별도의 try문을 하나 더 추가해 만약 SQLException이 발생할 경우 해당 과정을 롤백하도록 구현했습니다!

2023-03-30 12:04 UTC, youngh0 commented on src/test/java/domain/game/BoardTest.java
> +class BoardTest {
감사합니다😁🙃

2023-03-30 14:22 UTC, youngh0 commented on src/main/java/dao/ChessGameDao.java
> +            throw new IllegalArgumentException(e);
인텔리제이에서 catch블럭을 자동완성하니 RuntimeException을 던지고 있었습니다. 이를 그대로 가져간 이유는 checkedException보단 unCheckedException을 던지고 싶었습니다. 그리고 보다 구체적인 예외를 던지려고 IllegalArgumentException선택했습니다.
그러나, 리팩터링 과정에서 게임 방은 생성됐는데 기물 저장 중 예외가 발생하면 기존 게임방도 삭제하기 위해 RuntimeException을 던지고 service레이어에서 IllegalArgumentException을 던지도록 수정했습니다!!

2023-03-30 17:05 UTC, youngh0 commented on src/main/java/dto/dao/ChessGameDaoResponseDto.java
> +public class ChessGameDaoResponseDto {
저는 현재 service는 대략적으로 트랜잭션 단위들을 관리하는 역할로 생각하고 있습니다. 그리고 해당 트랜잭션을 수행하기 위한 비즈니스로직도 같이 수행한다고 생각합니다.
그래서 아직은 기존에 적은 코멘트와 동일한 생각입니다. 해당 부분에 대해선 이제 막 학습을 시작한 상태라 더 찾아보고 궁금한 점이 생기면 물어보러 가겠습니다 ㅎㅎ 감사합니다!!!🙂🙂

2023-03-30 17:06 UTC, youngh0 commented on src/main/java/dto/service/ChessGameCreateResponseDto.java
> +public class ChessGameCreateResponseDto {
네이밍에 고민이 많았는데 의미를 정확하게 전달하는 것을 1순위로 고민하면서 프로그래밍 해보겠습니다!! 감사합니다🙂

2023-03-30 17:14 UTC, youngh0 commented
안녕하세요!! 금요일까지 끝내야 해서 리뷰 내용을 반영하기 급급해 코드 품질에 신경을 못쓴 것 같습니다. dao테스트를 작성할 때 정말 dao에 있는 메서드 하나씩만 테스트하고 싶었는데, 작성하다보니 service테스트까지 같이 한 느낌이 드네요ㅠ

이번에 db테스트를 작성하면서 궁금한 점이 생겼습니다. 테스트 코드를 작성할 때 다른 기능에 의존적이지 않아야 한다고 알고 있습니다. 저는 해당 부분을 "하나의 테스트에서 호출할 수 있는 메서드는 테스트하려는 메서드 하나다."로 이해했습니다.

그런데 게임이 생성됐는지 확인하려면 find를 해야하고, find를 테스트 하려면 create을 해야 할 수 밖에 없다고 생각합니다.
어쩔 수 없는 부분일까요??

이번 리뷰도 잘 부탁드립니다!!!

2023-03-31 07:24 UTC, dks301 approved these changes
안녕하세요 레오, 리뷰어 시카입니다. 😄

어려운 미션이었는데 (네오의) 피드백까지 잘 반영해주셨네요! 👍
개인적인 이슈로 시간이 부족해서 아쉽지만 여기서 머지하겠습니다 ㅎㅎ
레벨1 고생 많으셨습니다 🎉🎉

추가로 궁금한 점이 생기면 언제든지 DM 주세요 ㅎㅎ

2023-03-31 07:24 UTC, dks301 commented on src/main/java/dao/ChessGameDao.java
> +            try (Connection connection = connectionGenerator.getConnection()) {
여기서는 트랜잭션의 범위에 대해서 고민해보면 좋을 것 같아요!
체스 보드에서 기물이 하나라도 없다면 그 보드는 일반적으로 의미가 없지 않을까요??

2023-03-31 07:24 UTC, dks301 commented on src/main/java/domain/game/Board.java
>  public class Board {
리뷰 받으신대로 역할과 책임을 잘 나누신것같아요 ㅎㅎㅎ

추가로 `지금 당장은 같은 변수를 갖거나 같은 이름을 가지는 것 같더라도, 과연 기능 확장이나 변경시에도 같을까`에 대해서도 고민해보시면 어떨까요?? ㅎㅎㅎ

2023-03-31 07:24 UTC, dks301 commented on src/main/java/dto/dao/ChessGameDaoResponseDto.java
> +public class ChessGameDaoResponseDto {
저도 네오의 의견에 동의합니다 👍👍
고민할 때 추가로 각 레이어를 넘나들 때 엔티티를 dto로 변환해서 넘기는 근본적인 이유까지 더해서 고민해보시면 어떨까요? ㅎㅎ

2023-03-31 07:30 UTC, merged