[3, 4단계 - 체스] 하마드(이건회) 미션 제출합니다.
woowacourse/java-chess pull request #576
Opened 2023-03-26 20:05 UTC by rawfishthelgh

안녕하세요 터틀! 주말 동안 열심히 미션 진행하고 pr을 올리게 되었습니다ㅎㅎ

이전 피드백에서 구조를 잘 잡아주신 덕에 구현 자체는 어렵지 않게 진행 됐으나, 여전히 놓친 부분이 많았을 것 같네요ㅎㅎ

이번에도 많은 지적 부탁드리겠습니다!!

2023-03-28 11:45 UTC, begaonnuri requested changes
3, 4단계도 잘 구현해주셨네요 하마드 👍🏻
몇가지 리뷰 남겼는데 확인해주세요!

2023-03-28 11:45 UTC, begaonnuri commented on src/main/java/chess/dao/ChessGameDao.java
> +    void delete();
마찬가지로 테이블 전체를 지워버린다는 의미를 내포하면 어떨까요? `deleteAll`, `truncate` 등이 있을 것 같아요.

2023-03-28 11:45 UTC, begaonnuri commented on src/main/java/chess/dao/DBChessGameDao.java
> +public class DBChessGameDao implements ChessGameDao {
구현체를 표현하려는 시도가 좋네요 👍🏻  하지만 DB는 너무 포괄적인 의미인것 같아요. 하마드가 사용하는 DBMS의 이름을 사용하면 어떨까요?

2023-03-28 11:45 UTC, begaonnuri commented on src/main/java/chess/dao/DBChessGameDao.java
> +            final var preparedStatement = connection.prepareStatement(query)) {
쿼리에 바로 데이터를 입력할 수도 있었을텐데 preparedStatement를 사용하면 어떤 장점이 있을까요?

2023-03-28 11:45 UTC, begaonnuri commented on src/main/java/chess/domain/board/ChessBoard.java
> +    }
체스 보드의 책임이 너무 커진것같아요. 점수를 계산하는 부분의 책임을 다른 객체로 위임하면 어떨까요?

그리고 전반적으로 라인수가 많은 클래스가 보이는데 라인이 많다는 것은 객체에 책임이 많다는 신호입니다!

2023-03-28 11:45 UTC, begaonnuri commented on src/main/java/chess/domain/board/RowPieces.java
> +        return extractPieceByTeam.stream()
해당 로직을 합칠 수 있을 것 같아요. collect를 하고 stream을 다시 만드신 이유가 있을까요?

2023-03-28 11:45 UTC, begaonnuri commented on src/main/java/chess/domain/piece/Team.java
> +    }
이 부분도 점수를 계산하는 새로운 객체로 옮길 수 있을것 같아요.

2023-03-28 11:45 UTC, begaonnuri commented on src/main/java/chess/domain/piece/coordinate/Column.java
> +    public static Column fromName(String otherColumn) {
Row의 from과 달리 fromName인 이유가 있을까요?

2023-03-28 11:45 UTC, begaonnuri commented on src/main/java/chess/view/InputView.java
> +            throw new IOException("start, restart만 입력 가능합니다");
`IOException`을 사용하신 이유가 있을까요?

2023-03-28 11:45 UTC, begaonnuri commented on src/main/java/chess/view/OutputView.java
> +        System.out.println(Result.lose(team));
현재 상태를 출력하는데 결과 메시지에 사용하는 메서드가 재사용되고있네요.

이런 경우 상태 출력 형태가 바뀌거나 결과 출력 형태가 변경될때 다른 쪽도 영향을 받을 것 같아요. 서로에게 영향받지 않도록 분리해보면 어떨까요?

2023-03-30 20:50 UTC, rawfishthelgh commented on src/main/java/chess/dao/DBChessGameDao.java
> +            final var preparedStatement = connection.prepareStatement(query)) {
저 같은 경우는 쿼리에 바로 데이터를 입력했다면, 테이블 컬럼명이 길기 때문에 코드 한 줄이 꽤 길어졌을 거라는 생각이 드네요…! preparedStatement를 사용한 덕에 가독성이 더 좋아졌다고 느꼈습니다!

2023-03-30 23:34 UTC, rawfishthelgh commented on src/main/java/chess/controller/ChessController.java
> +    private void applyFormerResults(List<List<String>> formerResults, ChessBoard chessBoard) {
역할과 달라졌다고 설명하시는 부분이 특정 String 값을 가져오는 것이 컨트롤러에 있어서일까요??
아직 DAO에 대한 개념이 부족하긴 하지만, db의 데이터를 접근하도록 하는 매개체라고 정의를 생각했습니다!!

2023-03-30 23:36 UTC, rawfishthelgh commented on src/main/java/chess/controller/ChessController.java
> +        return Command.RESTART.equals(command);
동일성 비교가 가능하다는 것을 알지 못했네요! 동일성 비교를 사용하면 만약 잘못된 타입으로 비교 했을 때 컴파일 타입으로 알아차리는 장점이 더 생길 것 같습니다ㅎㅎ

2023-03-30 23:37 UTC, rawfishthelgh commented on src/main/java/chess/controller/ChessController.java
> +        commandStatusCase(chessBoard, command);
말씀하신 대로 파라미터를 Command를 받으니 같은 로직이 사라졌습니다!ㅎㅎ

2023-03-30 23:37 UTC, rawfishthelgh commented on src/main/java/chess/controller/ChessController.java
> +        return !chessBoard.isKingAlive(team);
왕이 죽었다는 부분을 명확히 드러내려고 메소드를 한번 더 감쌌는데 코드가 과도하게 길어지는 단점이 있었군요ㅜㅜ

2023-03-30 23:39 UTC, rawfishthelgh commented on src/main/java/chess/controller/ChessController.java
> +        }
ChessBoard에 두 왕이 모두 살아있지 않음을 확인하는 메소드를 만들었습니다!!
그런데 이 경우 어떤 팀이 이겼는지 출력되지 않는데 제가 제대로 이해한 것이 맞나요...??

2023-03-30 23:39 UTC, rawfishthelgh commented on src/main/java/chess/dao/ChessGameDao.java
> +    List<List<String>> select();
readFormerGame으로 "이전의 게임을 불러온다"라는 의미를 드러내 봤습니다!!

2023-03-30 23:39 UTC, rawfishthelgh commented on src/main/java/chess/dao/ChessGameDao.java
> +    void delete();
deleteAll 좋네요!! 👍

2023-03-30 23:41 UTC, rawfishthelgh commented on src/main/java/chess/dao/DBChessGameDao.java
> +public class DBChessGameDao implements ChessGameDao {
어떤 db를 사용하는지 이름을 구체적으로 드러내 봤습니다(MysqlChessGameDao)! 다른 db를 사용할 때도 해당 db 이름을 붙여 사용하면 될 것 같네요!

2023-03-30 23:43 UTC, rawfishthelgh commented on src/main/java/chess/dao/DBChessGameDao.java
> +            return DriverManager.getConnection("jdbc:mysql://" + SERVER + "/" + DATABASE + OPTION, USERNAME, PASSWORD);
connectionUrl 이라는 변수를 선언해봤습니다!

2023-03-30 23:44 UTC, rawfishthelgh commented on src/main/java/chess/domain/board/ChessBoard.java
> +    }
PointCalculator 라는 유틸 클래스를 만들어 분리했습니다!

2023-03-30 23:44 UTC, rawfishthelgh commented on src/main/java/chess/domain/board/RowPieces.java
> +        return extractPieceByTeam.stream()
메소드를 두 번 적용할 생각을 못했었네요 감사합니다...!

2023-03-30 23:46 UTC, rawfishthelgh commented on src/main/java/chess/domain/piece/coordinate/Column.java
> +    public static Column fromName(String otherColumn) {
Column의 이름으로부터 반환하려는 의도를 드러내려 했는데 Row와의 통일성이 없었군요...ㅠㅠ

2023-03-30 23:47 UTC, rawfishthelgh commented on src/main/java/chess/view/InputView.java
> +            throw new IOException("start, restart만 입력 가능합니다");
입력에 대한 예외를 드러내려 사용했는데 다시 확인해보니 적합하지 않은 인자를 넘겼다는 점에서 IllegalArgumentException 이 더 적합해 보이네요...!

2023-03-30 23:48 UTC, rawfishthelgh commented on src/main/java/chess/view/OutputView.java
> +        System.out.println(Result.lose(team));
바깥에서 팀 이름을 String으로 넘겨주는 방법으로 변경했습니다!

2023-03-30 23:48 UTC, rawfishthelgh commented
안녕하세요 터틀!! 레벨 인터뷰를 진행하느라 리뷰 요청이 조금 늦었네요ㅠㅠ

2023-03-30 23:50 UTC, rawfishthelgh commented
안녕하세요 터틀!! 레벨 인터뷰를 진행하느라 리뷰 요청이 조금 늦었네요...
이번 리팩토링은 시간의 압박 때문인지 충분한 고민을 못 하고 올려서 조금 속상합니다 😢 
그래도 리뷰 주신 내용 최대한 반영하려고 노력해봤습니다!! 마지막이지만 많은 지적 부탁드립니다!! 👍

2023-03-31 08:44 UTC, begaonnuri commented on src/main/java/chess/controller/ChessController.java
> +    private void applyFormerResults(List<List<String>> formerResults, ChessBoard chessBoard) {
`List<List<String>>` 타입의 경우 타입만 보고 어떤 역할을 하는지 알아보기 유추하기 힘들다고 생각해요.

말씀해주신 DAO 역할이 맞습니다만 추가로 데이터 접근을 통해 데이터에 저장한 객체를 만들어서 반환해보면 어떨까요?`ChessGameDao`인 만큼 데이터베이스 접근을 통해 ChessBoard를 반환해주면 사용하는쪽에서 더 명확하지않을까요?

지금은 `ChessGameDao`에서 데이터를 가져오더라도 applyFormerResults처럼 다시 ChessBoard를 만들어줘야하는 과정이 필요한것같아요. 

역할이 달라졌다는 것은 이렇게 객체를 재구성하는 역할까지 Controller에 추가되어서 드린 말이었습니다!

2023-03-31 08:51 UTC, begaonnuri commented on src/main/java/chess/controller/ChessController.java
> +        }
사용자의 순서로 인해 인지할 수 있는 부분이라고 생각했어요. 이 부분은 죽은 킹의 팀을 반환해서 해결할 수도 있을 것 같네요!

2023-03-31 08:52 UTC, begaonnuri commented on src/main/java/chess/dao/DBChessGameDao.java
> +public class DBChessGameDao implements ChessGameDao {
맞습니다. 일반적으로 데이터저장소가 변경됐을때를 대비하기 위해 인터페이스를 사용하곤 하는데 구현체에도 이를 명시하기 위해 디비 이름을 명시하기도 합니다!

2023-03-31 08:56 UTC, merged