[3, 4단계 - 체스] 리오(오영택) 미션제출합니다.
woowacourse/java-chess pull request #590
Opened 2023-03-27 06:50 UTC by Jaeyoung22

안녕하세요 빙봉! 이번 단계도 잘 부탁드려요!!

우선 제가 db 관련 파일들을 커밋내역에서 아무리 찾아봐도 어디서 했는지 안 보이더라구요ㅠㅠㅠ
그래서 gitignore에 넣지 못하고 전부 커밋이 되어있습니다ㅠㅠㅠ 죄송합니다ㅠㅠㅠㅠㅠㅠ

2023-03-28 16:45 UTC, aegis1920 requested changes
안녕하세요 리오! 빙봉입니다 🙂 

지난 코멘트 기억해주시고 답변 달아주셔서 감사합니다 👍 
코멘트 답변 및 추가 코멘트 남겼으니 확인해주세요!

궁금한 점이 있다면 언제든 DM 주세요!

2023-03-28 16:45 UTC, aegis1920 commented on src/main/java/domain/PieceToScoreConverter.java
> +public class PieceToScoreConverter {
흑과 백 상관없이 기물의 점수는 같은데요. 좀 더 유연하게 구현할 수 있지 않을까요?

2023-03-28 16:45 UTC, aegis1920 commented on src/main/java/service/ChessService.java
> +                    .filter(square -> PieceToScoreConverter.convert(chessBoard.getBoard().get(square)) == 1)
`chessBoard.getBoard().get(square)) == 1` 이 부분은 메시지를 물어보는 형식으로 구현해도 좋을 것 같네요

2023-03-28 16:45 UTC, aegis1920 commented on src/main/java/service/ChessService.java
> +            .filter(piece -> PieceToScoreConverter.convert(piece) == 0 && !piece.isEmpty()).count() != 2) {
`PieceToScoreConverter.convert(piece) == 0` Piece안에 점수가 있다면 메시지를 물어보는 형식으로 구현 가능하겠네요

2023-03-28 16:45 UTC, aegis1920 commented on src/main/java/service/ChessService.java
> +        if (chessBoard.getBoard()
if 조건문이 너무 길지 않나요? 변수로 빼는 건 어떨까요?

2023-03-28 16:45 UTC, aegis1920 commented on src/main/java/service/ChessService.java
> +            chessBoardDao.delete();
chessBoardDao.delete(); 이후에 chessBoardDao.update(chessBoard); 가 진행되는데요. 모두 삭제되고 다시 업데이트하는 시나리오가 맞을까요?

2023-03-28 16:45 UTC, aegis1920 commented on README.md
> 이름이 excute인데 게임이 실행 중인지도 반환하면 한 메서드의 역할이 너무 많은 것이 아닌지 궁금합니다!

반환하는 것과 메서드의 역할이 많은지 여부는 다르게 해석될 수 있는 부분 같습니다. 메서드의 역할이라고 한다면 메서드가 실행되는 블록 위주로 보면 될 것 같아요. 그 블록 안에서 많은 역할을 한다면 메서드의 역할이 많다고 이야기가 될 수 있겠습니다. 

execute()라는 `실행한다`의 의미의 메서드를 실행시켰을 때 실행중인지, 끝났는지 여부를 반환하는 건 적절하다고 생각했습니다 🙂 

> 구체적으로 이야기를 못 드려서 죄송해요!! 다음부터는 잘 하도록 하겠습니다!! 이해하신 내용이 맞습니다!! 그래서 이번에는 dto로 리팩터링 해봤어요!

👍 

> 종료가 되고 나서 보드를 출력하지 않으려다보니까 지금 같은 방법을 택하게 됐습니다!
 
그러면 종료되고 나서 마지막으로 보드를 한 번 더 출력하면 되지 않나요? 단순 궁금증이니 지금 같은 방법으로 진행하셔도 상관없습니다!

> 고민을 많이 해봤는데, 부모의 메서드를 알고 그것의 반환 타입 등도 알고 있는 것이기 때문에 캡슐화가 깨진다고 생각합니다!

그 부분은 추상 클래스를 상속하게 될 때 어쩔 수 없는 부분입니다. 추상 클래스를 상속한 이상, 그런 단점은 감안해야하지 않을까.. 라는 생각이 드네요. 저는 지금 도메인에서 추상 클래스는 적절하다고 판단하여 써도 된다는 주의입니다.

> 서비스로직이 일어난 뒤 바뀐 결과를 지금은 뷰와 DB에 한번에 각각 보내는 양방향 전송이 일어나고 있는데 크루들과 이야기를 해 본 결과, 우선 DB에 전달이 되어서 에러가 나지 않으면 그 뒤에 뷰에 전달하는 단방향 전송이 맞지 않느냐는 결론을 내렸습니다.

너무나 좋은 고민이네요 👍 말씀하신대로입니다.

- 양방향 전송을 진행한다면 어떻게 될까요?
- 서비스 로직을 실행한 뒤, chessBoard 필드가 업데이트되고 View에 전달하고, DB에 전달했습니다.
- 그런데 View에는 전달에 성공하고, DB에는 전달에 실패했습니다. 
- 사용자 입장에서는 View 전달에 성공해서 잘 보이지만, DB에는 전달이 안 됐겠죠?
  - 여기서 DB 오류가 나서 에러가 터져 사용자 입장에서 보여주면 다행입니다. 만약 예외처리가 되어 View에 DB 오류가 전달 안됐다면?
- 사용자 입장에서는 다음 턴을 진행하게 될 걸 기대하고 있을텐데 DB는 그대로이니 다음 턴이 진행되지 않겠죠.

말씀해주신 결론이 맞습니다 💯

2023-03-29 07:10 UTC, Jaeyoung22 commented on src/main/java/controller/ChessController.java
> +    private final Map<Command, Consumer<CommandRequestDto>> commandsAndExecutions = Map.of(
이전에 커밋된 내용을 보면, 각 명령에 따라서 실행될 메서드를 한 메서드 내에서 여러 if문을 사용하면서 분기를 했는데요,
이 부분이 수정이 필요할 것 같아서 고민해봤는데, 맵퍼 패턴이라는 디자인 패턴을 학습할 수 있었습니다!!
이런 방법을 사용해보니까 코드가 엄청 깔끔해졌다고 느꼈습니다.
그런데 오히려 이 방법이 가독성이 떨어진다고 생각하는 크루들도 있더라구요
빙봉은 어떻게 생각하실까요?

2023-03-30 03:16 UTC, Jaeyoung22 commented on README.md
> +"각 팀의 점수를 계산한다."
그렇네요!! 추가하겠습니다!!

2023-03-30 04:06 UTC, Jaeyoung22 commented on docker/docker-compose.yml
처음 해봐서 몰랐습니다ㅠㅠ 넵!! 말씀하신대로 할게요!

2023-03-30 04:26 UTC, Jaeyoung22 commented on src/main/java/domain/PieceNameConverter.java
> +    public static Piece convert(String name) {
넵! 확인했습니다!

2023-03-30 04:34 UTC, Jaeyoung22 commented on src/main/java/domain/PieceToScoreConverter.java
> +        piecesAndScores.put(new Empty(), 0.0);
헉 맞습니다..! 감사합니다!!

2023-03-30 11:33 UTC, Jaeyoung22 commented on src/main/java/dto/BoardResponseDto.java
> +    }
와 왜 이렇게 냈죠.. 마음이 급해서 확인도 못했네요
죄송합니다...

2023-03-30 12:33 UTC, Jaeyoung22 commented on src/main/java/service/ChessService.java
> +            campDao.save(currentCamp);
맞습니다!! 죄송합니다!!

2023-03-30 13:48 UTC, Jaeyoung22 commented on src/main/java/dao/ChessBoardDao.java
> +    public boolean hasData() {
그런 좋은 방법이....!!! 감사합니다!!!!

2023-03-30 15:23 UTC, Jaeyoung22 commented on src/main/java/domain/PieceToScoreConverter.java
> +public class PieceToScoreConverter {
이번 미션에서 나름 집중한 부분인데요, 최대한 캡슐화를 지키고 싶었습니다.
그래서 piece의 각 구현체들이 어떤 구현체인지 묻는 로직을 아예 없애는 것을 목표로 구현을 해봤습니다.
지금 제가 생각할 수 있는 한에서, 이 클래서에서 각 기물의 camp를 모르게 하기 위해서는
기물을 우선 생성하고 camp를 나중에 주입해주는 방법을 사용할 수 있을 것 같은데요,
이 방법은 후에 기물의 camp가 변경될 가능성을 열어두는 것 같아서 저는 좋지 않다고 생각합니다.

이 클래스에서 사용하기 위해서 캡슐화를 깨기보다는, 현재 도메인에서는 아직 기물의 수가 많지 않아서 이와 같은 방법을 선택했는데 많이 유연하지 못한 상황일까요..?

2023-03-30 15:23 UTC, Jaeyoung22 commented on src/main/java/service/ChessService.java
> +                    .filter(square -> PieceToScoreConverter.convert(chessBoard.getBoard().get(square)) == 1)
그럴 수 있겠네요!! 감사합니다!!

2023-03-30 15:29 UTC, Jaeyoung22 commented on src/main/java/service/ChessService.java
> +            .filter(piece -> PieceToScoreConverter.convert(piece) == 0 && !piece.isEmpty()).count() != 2) {
piece가 점수를 들고 있는 건 제 추상화에서는 잘 납득이 안되더라구요..
각 piece의 이름과 점수를 정하는 건 piece 외부에서 결정되는 요인이라고 생각해서,
이 부분을 유틸성 클래스로 구현해봤습니다.
다른 크루들은 각 piece가 이름과 점수를 들고 있는 방식도 많이 사용했더라구요..
조금 더 객체지향에 대해서 공부해봐야할 것 같습니다..!

일단 유틸성 클래스에 질문을 던지는 방법으로 리팩터링해보겠습니다!!

2023-03-30 15:39 UTC, Jaeyoung22 commented on src/main/java/service/ChessService.java
> +            chessBoardDao.delete();
헉 그렇네요!! 감사합니다!! 생각을 못했네요ㅠㅠ

2023-03-31 08:55 UTC, aegis1920 approved these changes
안녕하세요 리오! 리뷰어 빙봉입니다 🙂 

체스 1단계부터 피드백이 많았었는데 매번 잘 반영해주셔서 감사합니다 👍 
레벨 1 고생 많으셨고 방학 의미있게 잘 보내시기 바랍니다. 항상 화이팅하세요!!

2023-03-31 08:55 UTC, merged

2023-04-02 12:53 UTC, aegis1920 commented on src/main/java/controller/ChessController.java
> +    private final Map<Command, Consumer<CommandRequestDto>> commandsAndExecutions = Map.of(
commandsAndExecutions가 Command와 Command에 정해지는 함수를 연결시켜주기 위한 역할을 담당하고 있다고 생각하는데요. switch문을 사용하는 것과 다를 게 없어보여서 질문드렸습니다. 불필요한 필드라고 생각해서 저라면 구현하지 않았을 것 같긴 합니다.

2023-04-02 13:06 UTC, aegis1920 commented on src/main/java/domain/PieceToScoreConverter.java
> +public class PieceToScoreConverter {
현재 코드를 기반으로 말씀해주시고 계셔서 위처럼 답변해주신 것 같은데요. 현재 코드에 변경이 필요한 상황이라 추가 피드백(DM)으로 따로 말씀드리겠습니다.

2023-04-02 13:17 UTC, aegis1920 commented on src/main/java/dto/CommandRequestDto.java
> +        if (COMMANDS_AND_REQUEST_SIZE.containsKey(command)) {
validateCommand라면 Command.find를 사용해도 될 것 같아서요. CommandRequest를 validate하는 구조라면 validateCommandRequest가 더 어울릴 것 같습니다.