[3, 4 단계 - 체스] 디노(신종화) 미션 제출합니다.
woowacourse/java-chess pull request #596
Opened 2023-03-27 07:46 UTC by jjongwa

안녕하세요 소니!
2단계 미션 PR 제출합니다. 🙇‍♂️
PR 요청을 너무 늦게 보내게 돼 죄송합니다ㅜㅜ
만드는 과정에서 선택 요구 사항 충족에 욕심이 생겨 시도하다가 호되게 당하고 어김없이 쓰레기를 만들어 버렸습니다..
우선 필수 요구 사항 부분 완료하여 제출합니다!

제가 구현한 기능은 다음과 같습니다.
- 3단계 
    - 상대편 King이 잡히는 경우 게임 종료하는 기능
    - 3단계 - "status" 명령을 입력하면 각 진영의 점수와 어느 진영이 이겼는지 출력하는 기능
- 4단계
    -  이전에 하던 체스 게임을 다시 시작할 수 있는 기능 (start 커맨드 뒤에 게임 번호를 추가해 요청하는 방식)
    - 각각의 체스 게임방을 만들어 관리하는 기능

이해를 돕기 위해 Application 실행 화면 첨부합니다!

![image](https://user-images.githubusercontent.com/77482065/227869380-4de4722e-f29c-4bc8-9ab1-16e519daabcf.png)

DB에 체스판을 관리하는 방식은 기물의 상태를 저장하는 방식과 기물의 이동 과정을 저장하는 방식(일종의 기보 방식) 중 고민하다 전자의 방식을 채택하였습니다. 

후자의 방식으로 진행할 경우 이전 게임을 불러올 때마다 초기 상태에서 이전의 상태까지 움직여주는 과정을 반복해야 하는 것이 비효율적이고 누군가 악의적으로 특정 이동을 반복한다면 DB에 과도한 양의 데이터가 쌓이는 문제가 생길 수 있다는 생각이었습니다. (하지만 구현을 진행하며 생각해보니 , 한 게임 당 이동의 수가 생각보다 많지 않고, 실제 체스에서는 같은 이동은 3번 반복하면 무승부 처리된다는 룰이 있다는 것을 보고 서비스 단에서 과도한 이동을 제한하면 충분히 효과적인 방법이라는 생각이 들었습니다.)

데이터베이스 테이블은 기물의 상태를 저장하는 ChessBoardDB와 게임의 인덱스와 차례를 저장하는 ChessGameDB의 두 가지 테이블로 구성하였고, create 쿼리는 다음과 같습니다.

```
create table ChessGameDB
(
    gameIdx int(100) AUTO_INCREMENT PRIMARY KEY,
    turn    varchar(10) NOT NULL DEFAULT 'white'
);
```

```
create table ChessBoardDB
(
    gameIdx   int(100),
    bFile     int(10),
    bRank     int(10),
    pieceType varchar(20),
    side      varchar(10)
);
```
해당 쿼리문은 resource.chess의 chessDB.sql 파일에 있습니다.

 추가적으로 상태 패턴을 적용해 게임의 턴을 저장해 다시 불러왔을 때 해당 편부터 시작하는 기능에(현재는 이전 게임을 불러왔을 때 White부터 시작하게 됩니다..) 을 추가하려 했지만 아직 이해가 부족해 구현하지 못했고, 기물이 자신이 이동할 수 있는 위치 리스트를 계산해 반환하는 findMovableRoute의 매개변수에 ChessBoard가 필요하여 순환 의존성 문제를 해결할 방법을 생각해 봤지만 아직 명확한 해결책을 찾지 못한 상황입니다. 
혹시 해당 부분에서 소니가 조언해 주실 부분이 있다면 부탁드립니다..!

감사합니다!

2023-03-27 16:39 UTC, sonypark requested changes
디노 안녕하세요.
4단계까지 잘 구현해주셨네요.
리팩토링 해볼만한 부분이 있어 코멘트 남겼으니 확인부탁드립니다 :)

상태패턴과 게임 턴 판별 관련 질문 주신 부분이 있어 아래와 같이 샘플 코드를 적어보자면.. 이런식으로 게임의 턴을 관리할 수 있을 것 같네요. 

```java
public interface State {
    State start();

    State end();

    State move(Position source, Position target);

    Board board();

    Turn turn();

    Status status();

    boolean isFinished();
}
```

```java
public enum Turn {
    WHITE(Color.WHITE),
    BLACK(Color.BLACK);

    private final Color color;

...
    public Turn next() {
        if (this == WHITE) {
            return BLACK;
        }
        return WHITE;
    }
```

```java
public class Playing implements State {
    private Board board;
    private Turn turn;

    public Playing(Board board, Turn turn) {
        this.board = board;
        this.turn = turn;
    }

...

private void nextTurn() {
        turn = turn.next();
    }
```

2023-03-27 16:39 UTC, sonypark commented on src/main/java/chess/ChessBoard.java
> +    }
- `chessPiece.getShape().equals(Shape.KING))` -> `chessPiece.isKing()` 으로 메시지를 보내 판단하는건 어떨까요?
- `2` 라는 매직넘버를 없애볼까요?

2023-03-27 16:39 UTC, sonypark commented on src/main/java/chess/database/ChessBoardDao.java
> +    }
- JdbcConnector 와 같은 클래스를 만들어서 DB 연결을 담당하는 클래스를 따로 만들어보는건 어떨까요?
- Dao 에서는 JdbcConnector를 주입받아 사용하면 될 것 같습니다

2023-03-27 16:39 UTC, sonypark commented on src/main/java/chess/ChessBoard.java
> +    }
chessBoard에서 너무 많은 역할을 수행하는것 같은데요.
점수 계산 로직을 담당하는 클래스를 만드는건 어떨까요?

2023-03-30 05:29 UTC, jjongwa commented on src/main/java/chess/ChessBoard.java
> +    }
변경했습니다!

2023-03-30 05:38 UTC, jjongwa commented on src/main/java/chess/chessGameApplication.java
2주동안 진행하면서 전혀 눈치도 못챘네요..ㅜㅜ 주의하겠습니다!

2023-03-30 16:30 UTC, jjongwa commented on src/main/java/chess/database/ChessBoardDao.java
> +    }
JdbcConnector 생성했습니다!

2023-03-30 16:47 UTC, jjongwa commented on src/main/java/chess/ChessController.java
> +    }
이 방법이 맞는지 모르겠지만 이전 게임을 불러오는 command인지 확인하는 로직을 App 단으로 옮겼습니다.!

2023-03-30 16:54 UTC, jjongwa commented on src/main/java/chess/ChessBoard.java
> +    }
ChessScore라는 Class 만들어 분리했습니다!

2023-03-30 17:05 UTC, jjongwa commented
안녕하세요 소니!
이번에도 리팩터링이 너무 늦었습니다..죄송해요ㅜㅜ

상태 패턴 부분 예시 코드 정말정말 감사합니다! 소니가 적어 주신 예시 코드들 보면 확실히 이해가 빠른 것 같아요ㅎㅎ
현 브랜치에는 적용하지 않았지만 개인적으로 고쳐보고 싶은 부분이 더 있어 다른 브랜치에서 따로 시도해 보고 있습니다..!
우선 리뷰 주신 부분에 대한 리팩터링 완료해 다시 요청 보냅니다!

감사합니다!

+추가적으로 여쭤볼게 있습니다..! 우테코 활동을 기록하기 위한 리포지터리를 작성하고 있는데 리뷰어 부분에 소니의 깃허브 주소를 태그해도 될까요? https://github.com/jjongwa/woowacourse 이 부분입니다..!

2023-03-31 07:23 UTC, sonypark approved these changes
디노 안녕하세요.
늦은시간까지 고생 많으셨습니다. 열심히 리팩토링해져서 이전보다 구조가 나아진게 보이네요.👏
체스미션은 여기서 머지하겠습니다. 어려운 미션 하느라 수고많으셨어요! 👍 

+ 말씀하신 깃헙링크는 사용하셔도 됩니다 😃

2023-03-31 07:23 UTC, sonypark commented on src/main/java/chess/ChessScore.java
> +        return scoreSum;
ChessBoard 전체가 아닌 Piece만 넘겨줘서 계산하는 방식도 있을 것 같은데, 지금 구조도 큰 문제 없어 보이네요. 분리 잘하셨습니다 👍

2023-03-31 07:23 UTC, sonypark commented on src/main/java/chess/ChessGameApplication.java
> +    }
네 생성자에 로직을 넣는것보다는 이렇게 외부로 로직을 분리해서 넣어주는게 좋을 것 같네요

2023-03-31 07:23 UTC, merged