[3, 4 단계 - 체스] 스플릿(박상현) 미션 제출합니다.
woowacourse/java-chess pull request #599
Opened 2023-03-27 07:57 UTC by splitube

3단계에 들어오면서 이전 단계와 다른 구조로 진행해보고 싶어서 시간을 좀 많이 뺏겼습니다ㅠㅠ

마지막 미션인데 아직까지도 시간에 허덕이고 있네요ㅠㅠ

궁금한점 정리하여 DM드리도록 하겠습니다!

2023-03-30 15:09 UTC, bimppap requested changes
안녕하세요 스플릿! 춘식입니다.
최근 일이 많아져서 리뷰가 늦었네요ㅠㅠ
코멘트 남겼으니 확인 후 리팩토링 해주세요 ☺️
궁금하거나 이해가 안 되는 부분은 편하게 DM 주세요!

2023-03-30 15:48 UTC, splitube commented on src/main/java/domain/board/piece/PieceType.java
> +    )),
Direction을 가진쪽에서 관리한다는 부분에서 좋은 방법 같습니다!!

2023-03-30 16:02 UTC, splitube commented on src/main/java/domain/path/pathValidtor/PathValidatorFactory.java
> +public final class PathValidatorFactory {
PieceType에서 PathValidator를 변수로 가지게 변경하였습니다!!

다만 PieceType에서는 기물에 해당하는 PathValidator의 내부를 알 필요는 없다고 생각하여 PathValidatorFactory에서 필요한 PathValidator를 만드는 책임을 가지는 형식은 유지해보았습니다!!

2023-03-30 16:11 UTC, splitube commented on src/main/java/controller/ChessController.java
> +        executeUntilDoesNotThrowException(this::getGameStartCommand);
기존 메서드 네이밍이 너무 길어 오히려 가독성부분이 떨어져서 주신 리뷰지 않을까? 라고 파악햇습니다~
execute라는 메서드명을 통해서는 오류에 대한 처리가 담긴 메서드인 것을 파악하기 힘들어 자세히 메서드명을 네이밍 했었는데
execute만으로도 충분하다고 생각하신 이유가 궁금합니다😊

2023-03-30 17:42 UTC, splitube commented on src/main/java/controller/ChessController.java
> +        final GameCommand command = GameCommand.find(inputView.getStartCommand().strip());
커맨드 패턴 적용해 보았습니다!!

2023-03-30 17:43 UTC, bimppap commented on src/main/java/controller/ChessController.java
> +        executeUntilDoesNotThrowException(this::getGameStartCommand);
- 예외 처리는 다른 메서드에서도 하고 있으나 메서드명에 오류와 관련된 언급은 없어 통일성이 떨어진다.
- 비즈니스 로직만 봐도 에러가 나면 재시도를 하고 에러가 안 나면 커맨드를 실행시키고 있음을 알 수 있다. 로직이 짧아 흐름 파악이 빠르게 되는 것도 한 몫 한다.
- 해당 메서드의 주목적은 커맨드 실행이고 예외 처리는 부가적이다.

저는 위 세 가지 이유로 좀 더 단순하게 써도 된다고 생각했습니다만, 스플릿이 생각할 때 이 메서드로 에러 처리를 한다고 명시하는게 중요하다고 생각한다면 변경할 필욘 없습니다!

2023-03-30 18:40 UTC, splitube commented on src/main/java/domain/board/piece/Piece.java
> +    }
기물들의 belongs의 경우는 캐싱을 염두해 두고 만들었던 로직이였습니다. 
구현과정에서 캐싱에 대해서 깜빡하여 그저 정적 펙토리 메서드로 사용되었는데 체스게임에서는 Piece 종류에 대한 확장성이 더 존재하지 않을 것이라는 생각이 들어서 캐싱을 사용하는 방식으로 바꾸었습니다.

상속을 사용했던 기존 코드에서 공통된 부분을 최대한 Piece에게 주기 위한 고민을 많이했었고 최종 코드에서는 결국 생성자만 상속받아서 쓰게 되었습니다.
근데 과연 생성자만 상속받아서 사용하는데 굳이 여러가지의 클래스를 만들어서 관리를 해야하는지에 대한 고민이 생겼고 차라리 공통적인 부분들을 Piece의 상태로 가지게 하여 Piece만 관리하면 되도록 바꾸는 방법을 택했습니다!

2023-03-30 18:52 UTC, splitube commented on src/main/java/database/BoardDao.java
> +public class BoardDao {
create table board (
	id int not null auto_increment primary key,
	board_row int not null,
	board_column int not null,
	piece varchar(20) not null,
	camp varchar(20) not null,
	turn varchar(20) not null
)
테이블 생성 쿼리 입니다!!

2023-03-31 05:59 UTC, splitube commented on src/main/java/domain/path/direction/Direction.java
> +
Direction이 스스로를 검증하는 로직을 가져서 스스로를 관리하는 형태가 되는 방법이 좋은 것 같습니다.
이전에는 Direction체크를 PieceMove를 사용하여 진행했는데 row와 column의 차이만으로도 Direction체크가 가능한데 PieceMove를 이용하게 하여 의존성을 만든것 같아서 리뷰를 적용한 부분이 더 좋은 것 같습니다!!

2023-03-31 13:37 UTC, bimppap approved these changes
안녕하세요 스플릿, 춘식입니다!
리팩토링 정말 빠르게⚡️ 반영해주셨네요 👍
고생 많으셨습니다. 체스 미션은 여기서 마무리하도록 할게요.
코멘트 짧게 남겼으니 시간 날 때 확인해주세요. 레벨 1 고생 많으셨고 방학 잘 보내시길 바랍니다!
더 나누고 싶은 얘기가 있다면 편하게 DM 주세요 😉

2023-03-31 13:37 UTC, bimppap commented on src/main/java/domain/board/piece/Piece.java
> +    }
캐싱을 염두에 둔 로직이었군요! 확실히 Piece는 확장의 여지가 없기 때문에 static을 사용하여 미리 만들어두면 메모리와 속도 측면에서 이점을 가질 수 있습니다. 👍

그러나 static은 GC의 관리를 받지 않기 때문에 양이 많아지면 프로그램 퍼포먼스가 나빠질 수 있다는 것도 염두에 두셔야 합니다. (체육 창고가 커지면서 달릴 수 있는 운동장이 좁아지는 느낌이죠.) 또한 static 은 static 영역에 데이터가 할당됨으로서, **모든 클래스에서 해당 데이터를 알게 됩니다.** 객체의 데이터들이 캡슐화되어야 한다는 객체지향 프로그래밍의 원칙을 위반하게 되는 셈이죠. 😭

지금 단계에서는 성능보다 객체지향적인 코드에 중점이 두는게 맞지 않나 싶지만, 실무에서는 속도와 성능 또한 중요하게 다뤄지기에 스플릿의 지향점이 틀린 건 아닙니다! 무엇에 중점을 뒀는지 알고 나니 코드에 목적성이 보여서 좋네요ㅋㅋ 우테코를 진행하면서 퍼포먼스를 향상시키는 방법 또한 배우게 될테니 그때 한번 더 즐겨보면 좋겠습니다 ㅎㅎ

2023-03-31 13:38 UTC, merged