[3, 4단계 - 체스] 도치(김동흠) 미션 제출합니다.
woowacourse/java-chess pull request #609
Opened 2023-03-27 08:24 UTC by hum02

안녕하세요 라빈! 도치입니다 😊
1,2단계의 merge가 미뤄지고 있는데, 오늘이 마지막 리뷰요청날이라 3,4 단계 구현해 pr올립니다.
많은 리뷰를 받지 못해 굉장히 아쉽네요...

이번 step에서 크게 바뀐 점은
## 점수 계산 기능 구현
board에서 cacluateScore()을 통해 계산합니다. 여기서 아쉬운 점은 점수계산의 알고리즘이 번잡해보인다는 것입니다.
1. 전체 점수를 getScore의 점수 전체 합을 구한다.
2. 특정 색의 pawn들의 위치를 구한다.
3.  세로줄을 모두 돌며 같은 색의 pawn이 2개 이상이면 그 수들 만큼 1.의 전체 점수에서 0.5씩 뺀다.

위의 과정으로 pawn이 세로로 겹치면 0.5로 계산하는 로직을 구현합니다.
이게 많은 연산을 하는 것 같아 아쉬움이 있습니다.

## 킹이 죽으면 게임 종료
board가 update될때마다 사라진 기물이 King인지 검사하고  king이 죽었다면 예외를 발생시킵니다.
board의 상위 객체인 GameState에서는 이 예외가 발생하면 게임의 상태를 end로 바꿉니다.
질문은 `king의 죽음 시 상위 객체에 알리는 행위를 Exception을 통해 해도 괜찮을 까요?` 입니다.
"예외는 정말 예외일 때만 던져라" 라는 말을 들어서 잘못된 구현을 한 게 아닌가 우려가 됩니다.
저는 board상에 왕이 2개가 안되는 건 예외적인 상황일 수도 있고, 바로 알려야 하는 상황이라 생각했는데 
이런 생각 괜찮을까요?

## db적용 - 중단된 게임 이어서 진행 가능
선택 요구사항 
1.체스 게임방을 만들고 체스 게임방에 입장할 수 있는 기능을 추가한다.
2. 사용자별로 체스 게임 기록을 관리할 수 있다.
는 우선 필수 요구사항 구현이 먼저라 생각해 구현하지 않았습니다.

db가 적용되니 전반적으로 1.getter나 2.db에 저장된 데이터를 인자로 하는 생성자가 늘어나는 느낌을 받았습니다.
db의 저장데이터가 도메인까지 침범한다는 느낌을 받아서 아쉬운 부분입니다.
 
리뷰 감사합니다.

2023-03-27 08:31 UTC, hum02 commented
이번 미션 db구조입니다.
- piece
![piecedb구조](https://user-images.githubusercontent.com/96762301/227885506-ada3ff02-ff7f-4a45-971e-850c1bc1d1a2.jpg)

- chess_game
![chess_gamedb구조](https://user-images.githubusercontent.com/96762301/227885596-39cf71c4-084a-4aea-a77a-521aa712eeb9.jpg)

게임방 요구사항을 구현하지 않아 게임은 오로지 하나입니다. 때문에 chess_game에는 별도의 id필드를 만들진 않았습니다.
정말 필수적인 기능만을 위한 db이기 때문에 
게임방도 오직 하나이고, 동시성도 전혀 보장되지 않는 등의 아쉬운 점이 있네요.
db에 대한 무슨 리뷰든지 감사하게 듣겠습니다.

2023-03-29 07:11 UTC, giantim requested changes
도치 안녕하세요! 리뷰어 라빈입니다 👋
1, 2단계 마지막 리뷰를 누락해서 죄송합니다 🥲 이번 단계 리뷰에서 같이 검토를 했는데 구조적으로 궁금한점, 변경했으면 하는 점들이 있어서 리뷰 남겼습니다. 같이 의견 나눠보면 좋을것 같아요!

공유주신 내용에 대해 제 의견 전달드리면요!

#### 점수 계산 기능 구현
음... 이정도 연산정도면은 크게 무리가 없다고 생각합니다. 또는 전체 합을 구하기 전에 pawn의 점수부터 계산해볼 수 도 있겠네요.

#### 킹이 죽으면 게임 종료
왕이 잡힌 상황이 왜 예외일까요? 체스 게임에서 왕이 잡힌 상황이 체스 게임의 규칙에 어긋난 행위인가요? 아니면 개발한 시스템이 알 수 없는 상황에 놓여 의도치 않은 동작을 수행한 것일까요? 현재 왕이 잡힌 상황이 바로 알려야 하며 게임을 종료시켜야하는 정상적인 수행 동작입니다. 예외가 아닌 방식으로 구현하세요!

#### db적용 - 중단된 게임 이어서 진행 가능
선택 요구사항에 대해서는 구현하지 않으셔도 무방합니다 😉 그렇기 때문에 최소한의 데이터베이스 테이블 설계가 나온것 같은데요. 현재 로컬에서 실행하는 콘솔 게임이기 때문에 어떤 동시성 문제 등을 고려할 필요가 있을까요? 선택 요구사항을 구현하는 시점에 테이블의 키를 보강한다던지, 갖고 계신 고민점들에 대해서 다시 구현해보면 될것 같습니다.

리뷰 드린 내용 보시고 질문이나 의견 나누고 싶으신 내용 있다면 언제든지 편하게 연락주세요!

2023-03-29 07:11 UTC, giantim commented on src/main/java/chess/domain/Board.java
> +    public static final int KING_COUNT = 1;
사용하지 않는 값은 지워주세요!

2023-03-29 07:11 UTC, giantim commented on src/main/java/chess/domain/PieceDto.java
> +public class PieceDto {
해당 객체는 다른 도메인 객체들과 어떤 협력을 하나요?
단순히 계층간에 값 전달로 사용되는데 도메인 패키지에 정의하는것이 올바를까요?

2023-03-30 09:06 UTC, hum02 commented on src/main/java/chess/controller/command/Command.java
> +    }
제가 매개변수 이름이 너무 한정적이라는 말씀을 잘 이해한 지 확인해보자면,
들어오는 String은 Command의 head인 것은 한정적인 케이스이고
String이 command의 종류를 가지고 있다는 것만 변수명에서 드러나면 되겠다는 의미이실까요?

변수명을 CommandType으로 수정하겠습니다.

2023-03-30 09:20 UTC, hum02 commented on src/main/java/chess/domain/chessGame/ChessGameState.java
> +public interface ChessGameState {
이 부분은 생각지 못했는데, 상태가 start,move, end등을 한다는 것 어색할 수 있겠네요!
ChessGame, PlayingChessGame, ReadyChessGame 으로 이름 수정하겠습니다

2023-03-30 09:22 UTC, hum02 commented on src/main/java/chess/controller/command/CommandExecutorMapper.java
> +    public static final int command_length = 3;
상수를 public으로 할 이유가 여기는 없어 보이네요! 반영하겠습니다.

2023-03-30 09:27 UTC, hum02 commented on src/main/java/chess/domain/piece/move_rule/PawnMoveRule.java
> +    private static final PawnMoveRule whiteInstance = new WhitePawnMoveRule();
움직임 규칙이라는 건 인스턴스에 상관없이 일정하게 동작하기에 싱글톤으로 사용되어야 한다고
생각했습니다. 하지만 지금은 멀티쓰레드 환경도 아니고, PawnMoveRule이 딱히 많이 산재되어 생성되지도 않기 때문에 필요가 없어보이네요 😂
이런 상황이 왜 교착상태로 이어질 수 있는지는 학습해 볼 좋은 주제인 것 같습니다!

싱글톤이 아닌 인스턴스로 사용하도록 수정하겠습니다.

2023-03-30 09:47 UTC, hum02 commented on src/main/java/chess/domain/Board.java
> +            if (count >= 2) {
같은 선상의 중복이 존재한다는 의미로 DUPLICATED_EXIST 로 이름 붙이겠습니다.

2023-03-30 09:51 UTC, hum02 commented on src/main/java/chess/domain/PieceDto.java
> +public class PieceDto {
Dto는 도메인에 포함되지는 않다고 생각합니다!
domain패키지 바깥에 Dto패키지에 넣겠습니다.
전반적으로 패키지에 대한 고민은 부족했던 듯 합니다.

2023-03-30 14:05 UTC, hum02 commented on src/main/java/chess/repository/ChessGameDaoImpl.java
> +        deleteTurn();
사실 이건 이렇게 할 경우 update메서드로 db에 저장된 turn이 없을 경우에 생성까지 가능해서 이렇게 구현했습니다...
update 쿼리로 이 메서드가 작성되면 저장된 turn이 없을 경우 새로운 turn정보를 저장하지 않기에,
가장 쉽게 떠오른 방법이 그냥 삭제 후 생성이었습니다!

2023-03-30 14:14 UTC, hum02 commented on src/main/java/chess/repository/ChessGameDao.java
> +package chess.repository;
사실 많은 생각을 한 네이밍은 아닙니다;;
db관련한 일들을 하는 패키지에 저장소를 의미하는 repository라는 이름을 많이 들어본 것 같아 
이런 네이밍으로 작성했습니다.

혹시 부적절한 패키지명이라 느껴지시나요? 
제 생각에 Dao는 Dao란 패키지명으로 따로 묶는 게 더 정확한 듯 하고,
Connection은 DB란 패키지에 속하는 게 나을 것 같다는 생각이 들어 이렇게 수정하겠습니다.
혹은 라빈이 생각하는 더 적절한 패키지 분리가 있을까요?

2023-03-30 14:24 UTC, hum02 commented
> 도치 안녕하세요! 리뷰어 라빈입니다 👋 1, 2단계 마지막 리뷰를 누락해서 죄송합니다 🥲 이번 단계 리뷰에서 같이 검토를 했는데 구조적으로 궁금한점, 변경했으면 하는 점들이 있어서 리뷰 남겼습니다. 같이 의견 나눠보면 좋을것 같아요!
> 
> 공유주신 내용에 대해 제 의견 전달드리면요!
> 
> #### 점수 계산 기능 구현
> 음... 이정도 연산정도면은 크게 무리가 없다고 생각합니다. 또는 전체 합을 구하기 전에 pawn의 점수부터 계산해볼 수 도 있겠네요.
> 
> #### 킹이 죽으면 게임 종료
> 왕이 잡힌 상황이 왜 예외일까요? 체스 게임에서 왕이 잡힌 상황이 체스 게임의 규칙에 어긋난 행위인가요? 아니면 개발한 시스템이 알 수 없는 상황에 놓여 의도치 않은 동작을 수행한 것일까요? 현재 왕이 잡힌 상황이 바로 알려야 하며 게임을 종료시켜야하는 정상적인 수행 동작입니다. 예외가 아닌 방식으로 구현하세요!
> 
> #### db적용 - 중단된 게임 이어서 진행 가능
> 선택 요구사항에 대해서는 구현하지 않으셔도 무방합니다 😉 그렇기 때문에 최소한의 데이터베이스 테이블 설계가 나온것 같은데요. 현재 로컬에서 실행하는 콘솔 게임이기 때문에 어떤 동시성 문제 등을 고려할 필요가 있을까요? 선택 요구사항을 구현하는 시점에 테이블의 키를 보강한다던지, 갖고 계신 고민점들에 대해서 다시 구현해보면 될것 같습니다.
> 
> 리뷰 드린 내용 보시고 질문이나 의견 나누고 싶으신 내용 있다면 언제든지 편하게 연락주세요!

안녕하세요 라빈! 도치입니다.
최대한 빠르게 수정한 pr을 보내고 싶었지만 레벨 인터뷰 등의 일이 있어 이제 보내게 되네요 😂
리뷰 주신 부분에 대한 수정을 하였고,

왕이 잡힐 시의 예외에 대해서는
보드에 왕이 죽었는지에 대한 검사를 요청 시마다 Map을 전부 순회하는 건 너무 비효율적이라 생각했고,
보드에서 잡힌 기물이 왕일 경우 finish로 상태를 변화시키는 게 합리적이라 생각해 이렇게 구현했습니다.
원래 board는 Map컬렉션만을 가진 나름의 일급 컬렉션이라 상태 변수를 더 두고싶지는 않았지만,
Map을 불필요하게 검사하는 일이 생기느니 상태변수를 두는게 낫다고 판단했습니다.

감사합니다.

2023-03-31 00:35 UTC, giantim commented on src/main/java/chess/domain/piece/move_rule/PawnMoveRule.java
> +    private static final PawnMoveRule whiteInstance = new WhitePawnMoveRule();
음... 싱글턴을 적용하신 근거가 조금은 어색한데요.
인스턴스별로 일정하게 동작하기 위해 반드시 싱글턴 적용이 필요한가요?
클래스가 적절한 책임에 맞게만 API를 제공하면 될것 같은데요! 싱글턴을 적용하는게 적절한 설계인지 여러 방면으로 고민해보는것도 좋을것 같아요 😉

2023-03-31 00:37 UTC, giantim commented on src/main/java/chess/repository/ChessGameDaoImpl.java
> +        deleteTurn();
update라는 기능을 조금 더 엄밀하게 정의하면 좋을것 같아요.
update 하기 위한 대상이 존재함을 보장하기 위해 turn의 키 값을 매개변수로 받아 해당하는 turn을 찾아 업데이트를 시키면 되지 않을까요? 해당 API를 호출하는 상위 객체에서 turn의 존재여부를 판단해도 될것 같구요!

2023-03-31 00:41 UTC, giantim commented on src/main/java/chess/repository/ChessGameDao.java
> +package chess.repository;
현재 구조에서는 스프링 프레임워크와 같이 repository라는 개념 보다는 데이터에 직접 접근하는 DAO 개념이 더 적합하다고 생각되어 남긴 리뷰였습니다!
dao라는 패키지가 도출됐기 때문에 db 패키지는 불필요해 보이는데요. Connection을 가져오는 부분도 데이터 접근을 위해 필수적으로 작성해줘야 하기 때문에 dao 패키지에 묶이는게 더 적합해 보이네요 😉

2023-03-31 00:45 UTC, giantim approved these changes
도치 안녕하세요! 라빈입니다 👋
PR 보내주신 이후에 많은 일이 있으셨군요! 바쁘신 와중에도 빠르게 피드백 잘 반영해 주셨네요 👍
변경해주신 구조에 대해서 더 리뷰 드릴만한 내용은 없는거 같아요. 레벨1 마지막 미션까지 고생 많으셨습니다 🎉

2023-03-31 00:45 UTC, merged