[3, 4단계 - 체스] 엔델(김민준) 미션 제출합니다.
woowacourse/java-chess pull request #625
Opened 2023-03-27 08:49 UTC by SproutMJ

안녕하세요  검프! 엔델입니다.
미션을 진행하는데 생각을 많이 하게 되어서 시간이 조금 늦어진 것 같습니다.
그리고 시간에 맞추려고 하다보니 조금 코드가 복잡해진 경향이 있는 것 같네요.

미션을 하면서 고민된 사항은 다음과 같습니다.
1. 명령어가 한 두개일 때는 상관이 없었지만 명령어가 늘어나다 보니 커맨드 패턴이 필요해질 것 같더라고요. 아직 하는 법을 몰라서 적용을 하지는 못했지만, 개인적으로 궁금한 점은 명령어에 인자(옵션)이 있는 경우 적용이 가능한지 궁금합니다. 예를들어 start나 end는 그냥 가능하지만, move는 시작점, 목적지 인자가 필요해서 그렇습니다.
2. 다형성을 위해 상속을 사용한 기물들을 저장할 때 클래스 이름을 저장하고 리플렉션으로 불러오고 있는데, 괜찮은 방법인지 궁금합니다. 이 방법이  아니라면 상속 구조 때문에 생각나는 방법이 아직 없네요.

이전에 추가로 남겨주신 리뷰는 이번에 요청을 하면서 언급하려 했으나, 어제 달려있는 것을 미처 확인하지 못했네요. 미션 기간동안 추가로 적용해보도록 하겠습니다.
감사합니다.

2023-03-28 13:07 UTC, Livenow14 requested changes
안녕하세요 엔델! 잘구현해주셧어요.

몇가지 간단한 피드백 남겼으니 확인부탁드려요 :) 

질문에 대한 답변 남깁니다.

> 명령어가 한 두개일 때는 상관이 없었지만 명령어가 늘어나다 보니 커맨드 패턴이 필요해질 것 같더라고요. 아직 하는 법을 몰라서 적용을 하지는 못했지만, 개인적으로 궁금한 점은 명령어에 인자(옵션)이 있는 경우 적용이 가능한지 궁금합니다. 예를들어 start나 end는 그냥 가능하지만, move는 시작점, 목적지 인자가 필요해서 그렇습니다.

command라는 객체가 단순 enum이 아닌, input값도 가지게 하는건 어떨까요??! 피드백 중간에도 남겼지만, 표준타입을 정의해주면 되는데요. 
"START" 일때는 파라미터가 없는채로의 책임을 수행
"MOVE" 일때는 파라미터가 존재하는채로 책임을 수행 하게 해주면, 고민이 해결될 것 같아요.. 

> 다형성을 위해 상속을 사용한 기물들을 저장할 때 클래스 이름을 저장하고 리플렉션으로 불러오고 있는데, 괜찮은 방법인지 궁금합니다. 이 방법이 아니라면 상속 구조 때문에 생각나는 방법이 아직 없네요.

저는 리플렉션은 "절대로 사용하지 않는다"의 기조를 가지고 진행하면 좋다고 생각하는데요.
리플렉션이 수행되는 순간 객체의 역할과 책임이 무너지게 되기 때문이에요. 
이번 피드백에선, 추가적인 구현을 하지말고 해당 책임들을 하나씩 풀어나가보는건 어떨까요? 
상속구조여서 사용할 수 밖에 없는것이 아닌, 상속구조를 잘못 작성했을 때 해당 행동(리플렉션, 해킹을 통한 값 가져오기)이 나타나게 되어있어서요...! 

진행하시면서 어려운 부분 있으면 꼭 DM 주세요 :)

수고많으셨습니다.

2023-03-29 05:58 UTC, SproutMJ commented on sql/chess_board.sql
> +-- Dump completed on 2023-03-27 17:30:16
제거 완료 했습니다.

2023-03-29 05:58 UTC, SproutMJ commented on README.md
> +
docker-compose 파일로 변경했습니다.

2023-03-29 05:59 UTC, SproutMJ commented on src/main/java/command/PlayCommandParser.java
> +        }
Play 커맨드로 합쳤습니다.

2023-03-29 05:59 UTC, SproutMJ commented on src/main/java/command/PlayCommandParser.java
> +    private final List<String> parameter;
Map 자료구조로 변경했습니다.

2023-03-29 06:00 UTC, SproutMJ commented on src/main/java/command/StartCommand.java
> +}
사실 하나로 합치고 싶은 생각은 있습니다. 그런데 처음 시작할 때 시작, 로딩, 종료만 들어오게 하고 나머지는 게임을 시작한 이후에 들어오게 구현을 했는데, 하나로 합치면 복잡해질 것 같아 시작할 때만 입력할 수 있는 커맨드들은 따로 나눴습니다.

2023-03-29 06:01 UTC, SproutMJ commented on src/main/java/controller/ChessController.java
> +    public ChessController() {
인터페이스를 주입받도록 해 커넥션을 만들 수 있는 구현체를 받도록 했습니다. 만약 데이터베이스를 변경하고 싶으면, 다른 구현체를 전달하면 됩니다.

2023-03-29 06:02 UTC, SproutMJ commented on src/main/java/database/dao/ChessGameDao.java
> +             final var preparedStatement = connection.prepareStatement(query)) {
statement와 달리 캐싱을 한다고 해서 사용했습니다. 혹시 다른 문제가 있을까요?

2023-03-29 06:05 UTC, SproutMJ commented on src/main/java/database/connection/ConnectionGenerator.java
> +}
Connection 자체를 가져와 전달하는 것에 대해서는 이후에 close 해야 할 때 혹시 문제가 발생하지 않을까요? 예를들어 커넥션을 가져온 이후에 게임을 끝낼 때까지 close를 하면 안된다던가 하는 문제가 발생할 것 같아서 connection을 만들 수 있는 객체를 실행 시 가져오게 해봤습니다.(그래서 사용을 다 하면 close를 하고, 필요할 때마다 getConnection을 하는 방식입니다.)

DB가 연결되어 있지 않은 경우에는 IllegalStatementException을 발생시키도록 해서 처리했습니다.

2023-03-29 06:58 UTC, SproutMJ commented on src/main/java/domain/piece/Piece.java
> +    public abstract boolean isEatable(Position source, Position destination);
이번에 묻지 않고 그냥 move를 해서 값이 없으면 예외를 던지도록 했는데 괜찮은 방법일까요?
아니면 void 반환값에서 그냥 바로 예외를 던지는게 나은지, 다른 방법이 더 나은지 조금 어렵네요.

그리고 https://github.com/woowacourse/java-chess/pull/468#discussion_r1148474024에서, 상수의 경우 무제한으로 갈 수 없는 피스들을 위해 존재하고, 자신이 얼마만큼 가는지 각 구현체에서 알면 좋을 것 같은데 혹시 제가 잘못 생각하고 있는걸까요?

2023-03-29 07:01 UTC, SproutMJ commented on src/main/java/controller/ChessController.java
>      }
각 커맨드별 상태긴 하지만 아직 게임 전체 흐름을 관장하지는 않고 해당 커맨드 시기에만 작동합니다. 따라서 게임이 동작하는 동안을 위해 아직 존재하게 됐습니다,,

2023-03-29 22:08 UTC, SproutMJ commented
DM을 보냈는데 시간 관계상 리뷰요청도 같이 보내게 되었습니다.

아래는 보냈던 DM 내용입니다.
리팩토링을 어느정도 진행 후 남겨진 고민이 있는데요 생각보다 어려워서 DM을 드리게 되었습니다.
데이터베이스를 위한 리플렉션 관련 문제인데요, 피스에 대한 정보를 primitive값으로 저장하고 불러와서 재조립하기, Blob 타입으로 저장하기 외에는 생각이 나지 않아서 고민입니다.
[앞에서 언급하신](https://github.com/woowacourse/java-chess/pull/625#pullrequestreview-1360970181) “상속구조를 잘못 작성했을 때 해당 행동“이 사실 어떤 건지도 잘 모르겠고요,,,
결국, 저 두가지 방법도 근본적인 해결 방법이 아닌 것 같아 질문드리게 되었습니다.
감사합니다.

2023-03-31 08:13 UTC, Livenow14 commented on src/main/java/database/connection/ConnectionGenerator.java
> +}
Connection Pool을 활요하면 괜찮지 않을까요?!

2023-03-31 08:20 UTC, Livenow14 approved these changes
안녕하세요 엔델! 추가 구현 후 코드가 깔끔해졌네요 :) 
docker-compose를 사용하여, 애플리케이션 사용시 필요 벤더 서비스들을 미리 띄워볼 수 있어서 좋았어요..! 

몇가지 간단힌 피드백 남겼는데, 이는 다음 레벨에서 진행해주셔도 될 것 같습니다! 
수고하셨어요.

2023-03-31 08:20 UTC, Livenow14 commented on src/main/java/controller/command/play/PlayAction.java
> +                    final ConnectionGenerator connectionGenerator);
ConnectionGenerator가 정말 필요한 파라미터였을까요?!

2023-03-31 08:20 UTC, Livenow14 commented on src/main/java/controller/command/play/PlayCommandType.java
> +    SAVE("SAVE", new SaveCommand());
💯

2023-03-31 08:20 UTC, Livenow14 commented on src/main/java/controller/ChessController.java
> +    private boolean readPlayCommandAndExecute(final List<String> command, final ChessGame chessGame) {
command가 List가 아닌 Queue 형식이었으면, Index값을 몰라도 됐겠네요 :)

2023-03-31 08:20 UTC, merged