[3, 4단계 - 체스] 저문(유정훈) 미션 제출합니다.
woowacourse/java-chess pull request #627
Opened 2023-03-27 08:51 UTC by jeomxon

안녕하세요 다니 :) 저문입니다!
이번 미션은 구현을 급하게 하고 시간조절을 못해서 그런지 코드가 더 엉망이 된 것 같네요...ㅠㅠ

2023-03-29 14:23 UTC, da-nyee requested changes
안녕하세요 저문! 다니입니다 🙌

이번 단계 어려웠을텐데 잘 구현해주셨어요 💯 
코드리뷰 확인해주세요.
질문에 대한 답변은 별도 코멘트로 곧 남길게요!

혹시 궁금한 점이 있으시다면 언제든지 편하게 코멘트나 슬랙 DM 주세요 🙇‍♀️

2023-03-29 14:23 UTC, da-nyee commented on src/main/java/chess/controller/StartCommand.java
> +    public List<String> getParameters() {
사용하지 않는 메서드네요 👀

2023-03-29 14:23 UTC, da-nyee commented on src/main/java/chess/dao/DBChessGameDao.java
> +                 final var preparedStatement = connection.prepareStatement(query)) {
try-with-resources 👍

2023-03-29 14:23 UTC, da-nyee commented on src/main/java/chess/dao/DBChessGameDao.java
> +                if (team == Team.BLACK) {
> indent(인덴트, 들여쓰기) depth를 2를 넘지 않도록 구현한다. 1까지만 허용한다.

2023-03-29 14:23 UTC, da-nyee commented on src/main/java/chess/piece/Piece.java
> +        if (from.getRank().getIndex() > to.getRank().getIndex()) {
메서드 분리로 추상화 수준을 높여볼까요?

2023-03-29 14:23 UTC, da-nyee commented on src/main/java/chess/piece/Piece.java
> +    protected void validateVertical(final Position from, final Position to, final Map<Position, Piece> board) {
> 함수(또는 메서드)의 길이가 10라인을 넘어가지 않도록 구현한다.

2023-03-29 14:23 UTC, da-nyee commented on src/main/java/chess/piece/WhitePawn.java
> +                !(isGeneral(from, to) && toPiece.isEmpty())) {
메서드 분리로 추상화 수준을 높여볼까요?

2023-03-29 14:23 UTC, da-nyee commented on src/test/java/chess/game/ChessGameTest.java
> +        }
TestFixture로 만드는 건 어떨까요?

2023-03-29 14:23 UTC, da-nyee commented on src/test/java/chess/piece/RookTest.java
> +                    .hasMessage("같은 Rank가 아니면 움직일 수 없습니다.");
테스트 코드 유지보수 👍

2023-03-29 16:12 UTC, jeomxon commented on README.md
> +- [ ] status입력이 들어오면 현재의 각 진영의 점수를 출력하고, 이긴 진영을 출력한다.
시간에 쫓겨 리뷰요청을 보내다보니 기능 목록 최신화를 우선순위에서 내렸네요 ㅠㅠ
깔끔하게 수정해보겠습니다!

2023-03-29 17:36 UTC, da-nyee commented
> DAO는 어디서, 어떻게 사용하는 것이 명확한가?
DAO라는 개념을 사용하면서 이것이 어디까지 영향을 미쳐야하는지가 궁금했습니다.
사용을 할 때의 범위는 어떤 기준으로 어떻게 정해야할지 모르겠어서 피드백 강의 내용을 보면서 따라했습니다.
그러다보니 저만의 기준이 사라진 것 같다고 느꼈습니다.
어떤 부분을 어떻게 공부해야할지도 감이 잘 안왔습니다😭
다니의 조언이 필요합니다!

DAO를 이름 그대로 바라보면 기준을 정하기 조금 더 수월한 것 같아요!

DAO는 Data Access Object, 즉 데이터 접근을 위한 객체죠.
데이터에 접근하기 위해선 어디에 먼저 접근해야 할까요? 바로 DB에 접근해야 해요.
DB는 어떤 계층에 속하는 자원일까요? 바로 인프라 계층이에요.
그러면 DAO가 영향을 미치는 범위는 어디까지일까요? DAO는 DB와 통신해서 데이터를 CRUD하기 때문에 인프라 계층에 영향을 끼치고, DAO를 사용하는 계층에도 영향을 주게 돼요.
그럼 DAO를 어디에서 사용해야 할까요? DAO는 결국 인프라 계층에 속하기 때문에 이보다 상위 계층(e.g. Controller)에서 사용하면 돼요.

지금은 생소한 개념이어서 많이 헷갈릴 수 있어요!
그렇지만 레벨 2에서 웹 애플리케이션을 구현하다보면 자연스레 익히게 될 거예요.
웹 애플리케이션을 설계할 때 [Layered Architecture](https://www.baeldung.com/cs/layered-architecture)를 접하게 될텐데, 이때 계층 구조와 함께 고민하면 기준이 좀 더 명확하게 잡힐 수도 있을 것 같아요.

2023-03-29 18:03 UTC, da-nyee commented
<img width="408" alt="image" src="https://user-images.githubusercontent.com/50176238/228628085-a8c187ef-4b50-431e-959f-4c03e0973bfc.png">

DDL을 보다가 궁금한 점이 생겼는데, team은 nullable한 이유가 있을까요?

2023-03-30 04:06 UTC, jeomxon commented on src/main/java/chess/controller/ChessController.java
> +        if (startCommand.getStartCommandType() == StartCommandType.END) {
Command객체에서 역할을 하도록 수정했습니다!

2023-03-30 04:06 UTC, jeomxon commented on src/main/java/chess/controller/StartCommand.java
> +    public List<String> getParameters() {
삭제하였습니다!

2023-03-30 06:27 UTC, jeomxon commented on src/main/java/chess/board/ChessBoard.java
> +                .noneMatch(piece -> piece.getTeam() == team);
이미 만들어둔 메서드를 사용하지 않고 있어서 수정했습니다!

2023-03-30 06:28 UTC, jeomxon commented on src/main/java/chess/controller/ChessController.java
> +            if (runningCommand.getRunningCommandType() == RunningCommandType.STATUS) {
해당 부분은 depth가 2가 되더라도 위와 같이 작성하는 것이 전체적인 흐름을 판단하는데 더 직관적일 것이라 생각해서 작성했습니다!
더 좋은 방법이 있다면 수정하겠습니다!

2023-03-30 06:33 UTC, jeomxon commented on src/test/java/chess/game/ChessGameTest.java
> +        }
반복해서 사용되는 부분인만큼 TestFixture로 만들어보겠습니다!

2023-03-30 15:03 UTC, jeomxon commented on src/main/java/chess/controller/RunningCommandType.java
> +        if (parameters.size() != parameterSize) {
이 부분도 마찬가지로 어떻게 메서드를 분리해야 추상화 수준을 높게 가져갈 수 있는지 감이 잘 안잡힙니다!
조금 더 자세히 설명해주실 수 있을까요?

2023-03-30 15:10 UTC, jeomxon commented
안녕하세요 다니 :)
코멘트 최대한 반영하여 리팩터링 했습니다!
team은 이전에 EMPTY라는 것을 따로 만들지 않고 하느라 not null을 하지 않았는데,
현재는 수정하여 사용하고 있습니다!
DDL 바로 수정하겠습니다!!

2023-03-31 03:16 UTC, da-nyee commented on src/main/java/chess/controller/ChessController.java
> +        if (startCommand.getStartCommandType() == StartCommandType.END) {
커밋 pull 땡겼는데 요건 반영이 안된 것 같네요 ㅎㅎ

2023-03-31 03:18 UTC, da-nyee commented on src/main/java/chess/controller/RunningCommandType.java
> +                        .equalsIgnoreCase(command))
```java
public static RunningCommandType from(final String command) {
    return Arrays.stream(values())
            .filter(isRunning(command))
            .findAny()
            .orElseThrow(() -> new IllegalArgumentException("게임 진행 중에 입력할 수 없는 명령어입니다."));
}

private static Predicate<RunningCommandType> isRunning(String command) {
    return runningCommandType -> runningCommandType.name().equalsIgnoreCase(command);
}
```

요런 식으로 분리할 수 있을 것 같아요 !

2023-03-31 03:21 UTC, da-nyee commented on src/main/java/chess/controller/RunningCommandType.java
> +        if (parameters.size() != parameterSize) {
```java
public void validateParameterSize(final List<String> parameters) {
    if (isInvalidSize(parameters)) {
        throw new IllegalArgumentException(
                String.format("%s의 파라미터 수는 %d개 이어야 합니다.", this.name(), this.parameterSize)
        );
    }
}

private boolean isInvalidSize(List<String> parameters) {
    return parameters.size() != parameterSize;
}
```

요런 식으로 분리할 수 있을 것 같아요 !

2023-03-31 03:22 UTC, da-nyee commented on src/main/java/chess/controller/RunningCommandType.java
> +        if (parameters.size() != parameterSize) {
+) 클린코드 3장 또는 [요 글](https://onestone-dev.tistory.com/3) 추천드립니다 ㅎㅎ

2023-03-31 03:30 UTC, da-nyee approved these changes
안녕하세요 저문~~! 다니입니다 🙌

피드백 반영 감사합니다 👍 
기존에도 깔끔했지만, 코드가 더 깔끔해졌네요!
처음부터 구현을 잘해주셔서 큰 변경점이 없었던 것 같아요 ㅎㅎ

코드리뷰 규칙에 따라 이번 미션은 여기서 머지하도록 할게요!
길었던 체스 미션 수고 많으셨어요. 레벨 1도 수고하셨습니다 ✨
방학 푹 쉬시고, 남은 우테코 기간도 응원할게요 🧚‍♀️

2023-03-31 03:30 UTC, merged