[1, 2단계 - 체스] 페드로(류형욱) 미션 제출합니다.
woowacourse/java-chess pull request #642
Opened 2024-03-21 06:52 UTC by hw0603

(추가예정)

2024-03-21 13:40 UTC, JunHoPark93 requested changes
안녕하세요 페드로~
전체적으로 코드를 깔끔하게 잘 작성해주셨네요!
큰 변경사항은 없을거같고 폰관련해서 리팩토링 진행해보면 좋을거같아요~

2024-03-21 13:40 UTC, JunHoPark93 commented on src/main/java/domain/game/PieceType.java
> +    BLACK_PAWN(BLACK),
이미 속성이 BLACK인데 BLACK이라는 정보를 중복으로 담고 있을 필요가 있을까요?

2024-03-21 13:40 UTC, JunHoPark93 commented on src/main/java/domain/position/UnitVector.java
> +    UP(-1, 0, (row, col) -> row < 0 && col == 0),
움직임 구성을 잘해보셨네요 👍🏼

2024-03-21 13:40 UTC, JunHoPark93 commented on src/main/java/domain/game/BoardInitializer.java
> +    }
앞으로도 마찬가지겠지만 레벨1에서는 컨벤션관련해서 잘 봐주셔요~

2024-03-21 13:40 UTC, JunHoPark93 commented on src/main/java/domain/game/PieceFactory.java
> +    public static Piece create(PieceType pieceType) {
factory안에 strategy가 숨겨져있고 Piece만 생성하는 구조가 좋아보이네요~

2024-03-21 13:40 UTC, JunHoPark93 commented on src/main/java/domain/strategy/PawnMoveStrategy.java
> +    }
movable동작이 black과 white가 거의 비슷한데요, movable메서드 하나로 통합해볼수도있을거같아요

2024-03-21 13:40 UTC, JunHoPark93 commented on src/main/java/domain/strategy/ContinuousMoveStrategy.java
> +        return isReachable(destination, optimalVector, movePaths);
이 부분도 코드 더 간결하게 써볼수있을거같은데 시도해보면 어떨까요?

2024-03-21 13:40 UTC, JunHoPark93 commented on src/main/java/view/PositionConvertor.java
> +    }
테스트가 없네요~ 1에서8 혹은 a에서h 이외의 값이 들어오면 어떻게 될까요?

2024-03-21 13:40 UTC, JunHoPark93 commented on src/test/java/domain/strategy/ContinuousMoveStrategyTest.java
> +class ContinuousMoveStrategyTest {
룩, 비숍 등에 대한 케이스를 명시적으로 만든 테스트가 있으면 좋을거같아요~

2024-03-22 07:05 UTC, hw0603 commented on src/main/java/domain/game/BoardInitializer.java
> +    }
페어와 레포지토리 분리 이후 급하게 추가하다 보니 확인하지 못했던 부분이 있었네요..! 수정했습니다!

2024-03-22 07:50 UTC, hw0603 commented on src/test/java/domain/strategy/ContinuousMoveStrategyTest.java
> +class ContinuousMoveStrategyTest {
기물별로 존재하는 것이 읽기가 더 쉽겠네요. Nested Test를 통해 추가해 두었습니다!

2024-03-22 08:23 UTC, hw0603 commented on src/main/java/view/PositionConvertor.java
> +    }
현재는 Map에서 해당하는 key를 찾을 수 없어 예외가 발생할 것 같아요. 테스트 코드를 추가하고 Converter에서는 키가 있는지 먼저 검사하여 명시적으로 예외를 던지도록 수정하였습니다.

처음에는 (Position 도메인을 알고 있기는 하지만) view 패키지에 있는 클래스라 별도의 테스트 없이 넘어갔던 것인데요, 제이는 이런 경우 테스트를 다 추가해 주는 편인가요?

2024-03-22 08:30 UTC, hw0603 commented on src/main/java/domain/strategy/ContinuousMoveStrategy.java
> +        return isReachable(destination, optimalVector, movePaths);
`takeWhile` 없이 스트림의 종료조건을 `iterate()`의 인자에 명시하는 것으로 변경하였는데, 적절한 방향이 맞는지 궁금합니다!

2024-03-22 08:54 UTC, hw0603 commented on src/main/java/domain/game/PieceType.java
> +    BLACK_PAWN(BLACK),
저도 설계하면서 마음에 걸렸던 부분인데 당시에는 Enum 값이 `$(COLOR)_$(TYPE)` 형태가 아니라 다른 형태로도 충분히 변경될 수 있다고 생각했어요.
이름에 의존하지 않고 해당 `PieceType`의 색상(팀) 정보를 가져올 수 있는 방법을 고민하다가 `PieceType` 내부에 팀 정보를 명시해 두다 보니 중복이 발생했는데요, "해당 팀에 포함된 말들"에 대한 정보를 담으려면 반대로 `TeamColor` 내부에 각 `PieceType`들을 가지고 있고, 팀 판별 시 '현재 `PieceType`이 `TeamColor`에 속하는가?' 를 물어보는 것이 자연스러울 것 같아 그렇게 수정했습니다!

2024-03-23 09:46 UTC, hw0603 commented on src/main/java/domain/strategy/PawnMoveStrategy.java
> +    }
`PawnMoveStrategy`를 `abstract sealed` 클래스로 변경하고, 그를 구현한 `WhitePawnMoveStrategy` 와 `BlackPawnMoveStrategy`를 새로 만들었습니다.

추상클래스에서 기본 동작을 모두 정의하고, 달라지는 부분(유효한 벡터 타입 등) 만을 구체 클래스에서 제공하도록 리팩토링하였습니다!

2024-03-24 13:27 UTC, JunHoPark93 commented on src/main/java/domain/strategy/PawnMoveStrategy.java
> +    }
중복이 많이 제거 되었네요 👍🏼

2024-03-24 13:31 UTC, JunHoPark93 commented on src/main/java/domain/strategy/ContinuousMoveStrategy.java
> +        return isReachable(destination, optimalVector, movePaths);
오 최적화를 해보셨네요 잘시도해주신거같아요

2024-03-24 13:34 UTC, JunHoPark93 commented on src/main/java/view/PositionConvertor.java
> +    }
넵 잘해주셨어요.
넵 이런부분들도 테스트를 해주는편입니다. 이런식으로 하다보면 예외처리가 중복으로 생길수는 있는데요, 그럼에도 해주는편이 더 견고한 프로그램을 만들수있는거같아요!

2024-03-24 13:39 UTC, JunHoPark93 commented
커밋메세지를 정말 꼼꼼하게 작성해주셨네요 고생많으셨습니다. 힘들진않으셨나요?
이런 습관을 잘 들여놓으면 실제로 업무할때도 많은 도움이 되실거에요.

2024-03-24 13:40 UTC, JunHoPark93 approved these changes
안녕하세요 페드로~
리뷰 반영하느라 고생많으셨습니다.
커밋메세지도 정말 꼼꼼하게 잘 작성해주셨네요~
다음 단계에서 뵙겠습니다.

2024-03-24 13:40 UTC, JunHoPark93 commented on src/main/java/domain/position/Position.java
> +    private static final Map<String, Position> CACHE = new HashMap<>();
👍🏼

2024-03-24 13:40 UTC, merged

2024-03-24 15:17 UTC, hw0603 commented on src/main/java/view/PositionConvertor.java
> +    }
중복된 예외처리가 생길 때 마다 고민이 되었었는데 앞으로는 부담 없이 해 주어야겠어요. 감사합니다👍