[1, 2단계 - 체스] 알파카(최휘용) 미션 제출합니다.
woowacourse/java-chess pull request #649
Opened 2024-03-21 07:21 UTC by slimsha2dy

안녕하세요 레벨 1의 마지막 과제인 체스 미션의 리뷰를 부탁드리게 된 알파카입니다!!

이번 과제를 구현하면서 체스 기물들의 반복 로직을 최대한 줄이기 위해 상속 관계가 깊어졌습니다.
쉽게 보실 수 있도록 다이어그램도 같이 첨부하겠습니다
### 다이어그램
![Piece](https://github.com/woowacourse/java-chess/assets/99064014/322967c4-3c35-40e9-ae79-85ed9d4c7abf)
이동 가능성을 파악하는 부분 중 중복되는 로직을 추상 메서드와 상속을 통해 처리해봤습니다.
그런데 이렇게 처리하다 보니 추가되는 이동 검증 로직들에 대한 메서드가 구현체에서 확인하는 검증 로직과 합쳐지게 되었고, 한 메서드가 하는 일을 간단하게 메서드명으로 서술하기가 애매해져서 메서드명이 많이 길어지게 되었습니다. 일단 현재 상태에서는 중복되는 코드를 줄이는 것의 이득이 더 크다고 생각해 이대로 구현을 완료했는데 구조가 잘못된 건지, 아니면 감수해야 할 부분일지 궁금합니다!
***
### 테스트 코드의 중복
체스 기물들에서 확인해봐야 할 테스트들 중 인자값만 달라지는 부분이 많았는데, 총 기물의 갯수가 6개이다 보니 중복되는 코드가 많이 나오게 되었습니다. 예를 들어 퀸과 룩, 비숍이 이동 가능성을 확인할 때 출발지와 목적지 사이에 기물이 있는지, 목적지에 아군 팀 기물이 있는지 등에 대해 전부 체크해야 하는데 짧지 않은 코드가 반복된다고 느껴져서 합치는게 괜찮을지 고민했었습니다. 테스트 코드도 코드라서 중복되는 코드를 줄여야 할지, 테스트 코드는 하나의 문서이므로 각 기물들에 대한 기능 문서의 일환으로 그래도 두어야할지 생각하다가 후자를 택하게 되었습니다. 중복되는 코드가 더 많아지게 된다면 이를 합쳐서 줄이는 편이 나을까요?

2024-03-21 14:16 UTC, summerlunaa requested changes
알파카 안녕하세요~ 체스 미션의 리뷰어 파랑입니다 🐳

레벨 1의 마지막 미션까지 오셨네요! 특히나 이번 미션은 쉽지 않았을 것 같은데 시간 맞춰서 잘 구현해주셨습니다ㅎㅎ

첫 리뷰인데다 양도 많은 만큼 리뷰를 많이 드리지는 않았습니다. 짧게 자주 티키타카 해보면 좋을 것 같아요. 필요하시면 언제든 편하게 DM 주시구요~ 감사합니다 ☺️

2024-03-21 14:16 UTC, summerlunaa commented on src/main/java/domain/AbstractCatchOnMovePiece.java
> +package domain;
클래스를 쉽게 찾기 위해 연관된 클래스끼리 패키지를 나눠볼까요?

2024-03-21 14:16 UTC, summerlunaa commented on src/main/java/domain/Piece.java
> +	public abstract int getRow();
>이동 가능성을 파악하는 부분 중 중복되는 로직을 추상 메서드와 상속을 통해 처리해봤습니다.

알파카는 중복 로직을 피하기 위해 어떤 방법들을 고민해보셨나요? 최종적으로 추상 메서드와 상속이 선택된 이유가 궁금합니다!

2024-03-21 14:16 UTC, summerlunaa commented on src/main/java/domain/PieceMoveResult.java
> +	}
조금 더 적절한 네이밍으로 변경해볼까요?

2024-03-21 14:16 UTC, summerlunaa commented on src/main/java/domain/PieceWrapper.java
> +	boolean isOn(Position position) {
모든 클래스와 메서드에 접근제어자를 명시하지 않는 이유가 있나요?

2024-03-21 14:16 UTC, summerlunaa commented on src/main/java/domain/PieceWrapper.java
> +	boolean isOn(Position position) {
PieceWrapper는 어떤 역할을 하는 클래스인가요? 필요성을 모르겠네요 🤔

2024-03-21 14:16 UTC, summerlunaa commented on src/main/java/domain/Command.java
> +}
시작/종료/이동 세 가지 클래스를 Command 추상 클래스를 상속하게 해서 묶었네요. 여러 문제점이 보이는데요!

- getOptions는 사실상 이동 시에만 사용하는데요, 모든 명령어가 이 메서드를 구현할 필요가 있나요?
- 반환 타입 역시 언제나 Position인데 제네릭을 사용하셨네요. 제네릭도 잘 사용하면 너무나도 편리하지만 이해하기 쉬운 방식은 아닙니다. 불필요한 제네릭은 삭제해주세요~
- `배열 대신 컬렉션을 사용한다.`라는 프로그래밍 요구사항이 왜 나왔는지 찾아봅시다.

상속을 대신할 수 있는 방법에는 어떤 것들이 있을까요? 상속과 더불어 각각의 방법들은 어떤 상황에서 사용해야 할까요? 알파카는 어떻게 생각하는지 궁금합니다.

2024-03-21 14:16 UTC, summerlunaa commented on src/main/java/Application.java
> +        Position to = options.get(1);
이동 명령에 option은 항상 from, to 두 개가 끝인데 이 값들을 0, 1 인덱스로 접근하는 방식은 가독성도 떨어지고 Index 에러를 발생시키는 원인이 됩니다. 다른 방식을 찾아볼까요?

2024-03-21 14:16 UTC, summerlunaa commented on src/main/java/domain/AbstractMoveStraightMovePiece.java
> +abstract class AbstractMoveStraightMovePiece extends AbstractCatchOnMovePiece {
클래스명에 Move가 중복으로 들어갔네요~

2024-03-21 14:16 UTC, summerlunaa commented on src/main/java/domain/AbstractMoveStraightMovePiece.java
> +    protected Optional<PieceMoveResult> tryMoveAssumeAloneAndCheckRoute(Position targetPosition,
> 한 메서드가 하는 일을 간단하게 메서드명으로 서술하기가 애매해져서 메서드명이 많이 길어지게 되었습니다. 일단 현재 상태에서는 중복되는 코드를 줄이는 것의 이득이 더 크다고 생각해 이대로 구현을 완료했는데 구조가 잘못된 건지, 아니면 감수해야 할 부분일지 궁금합니다!

메서드명 짓기가 쉽지 않았을 것 같네요 🥹 현재 구조에서는 어쩔 수 없는 부분이라 생각합니다. 메서드명을 인터페이스명에 따라 `tryMoveStraightAssumeAlone`, `tryCatchOnMoveAssumeAlone` 등으로 수정해볼 수는 있을 것 같습니다 :-)

2024-03-21 14:16 UTC, summerlunaa commented on src/main/java/domain/AbstractPiece.java
> +abstract class AbstractPiece extends Piece {
이미 추상클래스인 Piece가 있는데 AbstractPiece를 만든 이유가 있을까요?

2024-03-21 14:16 UTC, summerlunaa commented on src/test/java/domain/QueenTest.java
> +class QueenTest {
> 테스트 코드도 코드라서 중복되는 코드를 줄여야 할지, 테스트 코드는 하나의 문서이므로 각 기물들에 대한 기능 문서의 일환으로 그래도 두어야할지 생각하다가 후자를 택하게 되었습니다. 중복되는 코드가 더 많아지게 된다면 이를 합쳐서 줄이는 편이 나을까요?

저는 지금도 좋다고 생각해요. 테스트를 각 기물들에 대한 기능 문서의 일환으로 본다면 말씀하신 것처럼 각 기물들의 동작을 각 기물별 테스트에서 확인하는 것이 더 보기 좋은 것 같습니다.
개인적으로 테스트에서는 중복 코드를 줄이기보다 가독성이 좋은 쪽을 더 선호합니다.

2024-03-21 14:16 UTC, summerlunaa commented on src/main/java/domain/InitialPieces.java
> +		new Bishop(C8, BLACK), new Bishop(F8, BLACK), new Queen(D8, BLACK), new King(E8, BLACK)
<img width="80" alt="image" src="https://github.com/woowacourse/java-chess/assets/77425729/a3dd2e98-f17a-44c3-9686-125bd93aaa41">
G1, G8은 Rook이 아니라 Knight 입니다.

2024-03-22 05:53 UTC, slimsha2dy commented on src/main/java/domain/InitialPieces.java
> +		new Bishop(C8, BLACK), new Bishop(F8, BLACK), new Queen(D8, BLACK), new King(E8, BLACK)
기본적인 요구사항을 놓쳤네요 죄송합니다 수정했습니다..

2024-03-22 06:24 UTC, slimsha2dy commented on src/main/java/domain/AbstractMoveStraightMovePiece.java
> +abstract class AbstractMoveStraightMovePiece extends AbstractCatchOnMovePiece {
pr 제출 전에 확인해서 수정했었는데 혹시 반영이 안 되어있는 걸까요..?
다시 확인해봐도 수정돼있는 걸로 나와서요..
<img width="845" alt="스크린샷 2024-03-22 오후 3 23 55" src="https://github.com/woowacourse/java-chess/assets/99064014/e02efec1-e2ee-47c0-9c6e-28b0fe3b9267">
제출 전 마지막 커밋에서 반영했었습니다

2024-03-22 06:28 UTC, slimsha2dy commented on src/main/java/domain/PieceMoveResult.java
> +	}
움직인 건지 파악하는 메서드이므로 isMoved로 변경했습니다!

2024-03-22 06:57 UTC, slimsha2dy commented on src/main/java/domain/AbstractPiece.java
> +abstract class AbstractPiece extends Piece {
처음에 Piece를 인터페이스로 작성했다가 이후 추상 클래스로 변경하다보니까 합칠 수 있게 된 것을 신경쓰지 못했네요.. 하나로 합치는 것이 더 나을 것 같아 Piece 하나로 수정했습니다!

2024-03-22 08:02 UTC, slimsha2dy commented on src/main/java/domain/AbstractCatchOnMovePiece.java
> +package domain;
도메인의 정보를 view로 넘길 때 dto 대신 Piece를 직접 넘기도록 처리했는데, view에서 Piece를 직접 조작하지 못하도록 move 메서드를 default 접근제어자로 숨겼습니다. 그러다 보니 ```Piece```와 ```Piece.move()```를 실행하는 ```Board```가 같은 패키지에 있어야 하는데, 패키지를 나눌 때 이 둘을 같은 패키지로 묶으면 나누는 의미가 없다고 생각해 차라리 아예 분리하지 않게 되었습니다. 물론 모든 클래스가 모여 있어 찾기 조금 불편한 것은 맞지만 그래도 dto를 사용하지 않으면서 외부에서의 변조를 막을 수 있는 점이 더 크다고 생각했습니다.

2024-03-25 05:08 UTC, slimsha2dy commented on src/main/java/domain/PieceWrapper.java
> +	boolean isOn(Position position) {
위에서 언급했던 것처럼 view 같은 도메인 외부에서 사용하지 않아야 하는 메서드를 숨기기 위해 default로 접근을 제어했습니다. 패키지를 분리하면서 해당 메서드들 대부분이 public으로 변경되었습니다!

2024-03-25 05:13 UTC, slimsha2dy commented on src/main/java/domain/PieceWrapper.java
> +	boolean isOn(Position position) {
```PieceWrapper```도 마찬가지로 메서드를 숨기기 위해 사용했습니다. ```Piece```가 움직일 수 있는 위치를 판단하기 위해 보드 위의 ```Piece``` 정보를 ```PiecesOnChessBoard``` 클래스로 가져오는데, 이 때 move 메서드를 사용하지 못하도록, 즉  어떤 ```Piece```에서는 다른 ```Piece```의 정보를 조회만 할 수 있도록 포장한 클래스인 ```PieceWrapper```를 사용하게 되었습니다.

또한 패키지를 분리하면서 default를 사용하기 힘들어져 view에서도 ```Piece```를 조작할 수 없도록 ```PieceWrapper```를 넘기게 수정했습니다!

2024-03-25 05:36 UTC, slimsha2dy commented on src/main/java/domain/Piece.java
> +	public abstract int getRow();
여러 체스 말들의 규칙에 중복되는 로직이 있고, 이러한 로직들은 위의 ```Piece``` 클래스의 다이어그램에서 확인할 수 있는 것처럼 hierarchical한 형태를 띄고 있어 상속이 가장 적합하다고 생각했습니다. 또한 중복되는 로직은 존재하지만 직접적으로 한 기물만 확장하는 형태의 기물은 존재하지 않으므로 어떤 기물을 직접 상속하는 것보다는 추상 클래스를 통해 로직을 처리하는 것이 더 깔끔하다고 생각해서 해당 방식을 선택했습니다.

2024-03-25 06:42 UTC, slimsha2dy commented on src/main/java/domain/Command.java
> +}
```getOptions```는 이후 다른 커맨드들이 입력되는 경우를 고려해서 위와 같은 형태가 되었습니다. 처음에 ```Command```를 추상화할 때 뒤에 들어올 수 있는 값이 어쩔 땐 존재하고 어쩔 땐 없으므로 option이라는 단어로 추상화했고 단어 자체가 없을 수도 있다는 뜻을 내포하고 있다고 생각해 모든 명령어에서 구현하게 되었습니다.
반환 타입을 제네릭으로 한 이유도 지금 당장 과제 구현 요구사항은 아니지만 체스의 여러 특수 룰을 적용하기 위한 커맨드를 추가하려 할 때 option이 항상 ```Position```은 아닐 것이라 생각했기 때문입니다. 예를 들어 프로모션을 하게 될 경우 option으로 Piece의 Type을 받아야 하는데, 이럴 경우 ```getOptions```의 반환값 또한 ```PieceType```이 되는 것이 더 적절한 방법이 될 것 같았습니다. 

그런데 주신 리뷰를 보면서 다시 생각해보니 어차피 명령어를 받는 곳에서 항상 명령어에 따라 처리를 따로 하게 되므로 굳이 ```getOptions()```를 모두 갖고 있을 필요는 없다고 생각이 드네요. 따라서 중복 로직이 필요 없어진 Command를 인터페이스로 변경하고, option이 필요한 명령어에서는 따로 가질 수 있도록 수정했습니다. 또한 이에 따라 제네릭을 사용하지 않게 변경되었습니다.

- String 배열 사용은 놓친 부분이었네요.. 컬렉션을 사용하도록 수정했습니다!

2024-03-25 06:42 UTC, slimsha2dy commented on src/main/java/Application.java
> +        Position to = options.get(1);
위에서 Commad를 수정하면서 ```getFrom```, ```getTo``` 명령어로 변경하였습니다

2024-03-25 06:56 UTC, slimsha2dy commented on src/main/java/domain/Command.java
> +}
이 부분을 설계하면서 고려한 방법은 상속, enum, 인터페이스가 있었습니다. 처음에는 명령어와 옵션을 추상화하다보니 확장성을 고려하면 중복되는 부분이 발생할 수 있을 것이라 생각해 상속과 추상 클래스를 사용했습니다. enum의 경우 차이가 나는 부분인 Position을 갖고 있어야 한다는 점 때문에 사용하지 않았고, 인터페이스 또한 마찬가지로 중복되는 로직을 구체화하지 않는다는 점에서 사용하지 않았습니다.
그런데 지금은 위에서 언급한 내용처럼 중복된 로직이 거의 없기도 하고 필요성이 크게 느껴지지 않아 인터페이스로 수정하게 되었습니다. 제가 생각했을 때 이 부분에서 직관적인 인터페이스의 장점은
1. 업캐스팅: view에서 어떻게 값을 받게 되어도 Command라는 인터페이스로 도메인에 넘길 수 있게 된다
2. 가독성: Command라는 인터페이스로 여러 명령어들을 묶을 수 있다 -> 분류할 수 있다
3. 추상 클래스에 비해 결합도가 느슨하다 -> 명령어들을 유연하게 구성할 수 있어 확장에 용이하다

정도가 되는 것 같습니다!

2024-03-25 08:38 UTC, summerlunaa commented on src/main/java/domain/AbstractCatchOnMovePiece.java
> +package domain;
네 접근자를 최소화하는 건 좋지만 그로 인해 패키지 분리를 할 수 없다면 다른 방법을 찾는 것이 맞습니다. 지금이 도메인을 파악하기 훨씬 좋네요 👍

2024-03-25 08:44 UTC, summerlunaa commented on src/main/java/domain/PieceWrapper.java
> +	boolean isOn(Position position) {
아하 외부에서 객체를 변경하지 못하도록 막아주는 역할을 하는 클래스였군요!

2024-03-25 10:50 UTC, summerlunaa commented on src/main/java/domain/Command.java
> +}
아하 되게 많은 고민을 거쳐서 나온 코드였네요ㅎㅎ
기존 코드에서 `getOptions`를 왜 넣게 되었는지는 알파카의 설명을 읽고 이해했습니다. 알파카가 설명해준 것처럼 명령어가 다양하게 존재하고, 명령어에 따라 여러 인자를 받아야 했다면 저도 알파카가 처음 구현한 방식과 동일하게 구현했을 것 같아요.

하지만 지금은 명령어의 개수가 한정적이고 추가 인자를 필요로 하는 명령어도 Move 하나인 만큼 추상화까지 필요한지 고민해봐도 좋을 것 같아요~ 추상화가 항상 장점만 갖고 있는 건 아니거든요. 그만큼 코드가 복잡해져서 관리하고 이해하기 힘들어집니다. 이번 케이스에서 명령을 Command 인터페이스로 추상화하는 것과 하지 않는 것의 장단점을 비교했을 때 알파카는 어떤 방식이 더 적절하다 생각하시나요?

2024-03-25 11:13 UTC, summerlunaa requested changes
알파카 안녕하세요~

이전 리뷰에 대한 코멘트와 추가 리뷰 남겨두었습니다.

한번 더 확인 부탁드릴게요!

2024-03-25 11:13 UTC, summerlunaa commented on src/main/java/domain/command/EndCommand.java
> +import java.util.List;
사용하지 않는 import는 정리해주세요~ (다른 곳들도 확인해주세요)

2024-03-25 11:13 UTC, summerlunaa commented on src/main/java/domain/command/MoveCommand.java
> +    public MoveCommand(String... options) {
받을 수 있는 인자의 개수가 2개로 정해져있는데 가변인자로 받을 필요가 있을까요?

2024-03-25 11:13 UTC, summerlunaa commented on src/main/java/domain/piece/Piece.java
> +	public abstract PieceType getPieceType();
알파카는 어떤 기준으로 메서드를 정렬하나요? 보통 추상 메서드는 생성자 다음 순서에 두는 것 같아요. 이 클래스를 상속하려면 반드시 구현해야 한다는 게 한 눈에 보이면 좋으니까요!

2024-03-25 11:13 UTC, summerlunaa commented on src/main/java/domain/Position.java
> +                .orElseThrow();
예외를 구체적으로 작성해볼까요?

2024-03-25 11:13 UTC, summerlunaa commented on src/main/java/domain/Position.java
> +        throw new RuntimeException();
왜 RuntimeException을 사용하셨나요? 예외 메시지는 항상 구체적으로 작성해주세요. 사용자도 문제를 파악하기 어렵지만 개발자 본인도 문제를 찾기 어렵습니다.

2024-03-25 11:13 UTC, summerlunaa commented on src/main/java/domain/ChessBoard.java
> +    ChessBoard(Piece... pieces) {
Collection을 사용하지 않는 이유가 있나요?

2024-03-25 11:13 UTC, summerlunaa commented on src/main/java/domain/PiecesOnChessBoard.java
> +public class PiecesOnChessBoard {
PiecesOnChessBoard와 PieceWrapper 모두 불필요한 메서드 호출을 막기 위한 장치네요!
중요한 도메인 객체를 보호하기 위함이라는 것은 이해하지만 기물이 이동할 때마다 객체를 생성해주어야 하고, 클래스를 관리하는 비용도 커질 것 같아요. 요 부분에 대해서는 어떻게 생각하시나요?

2024-03-25 11:13 UTC, summerlunaa commented on src/main/java/domain/piece/AbstractCatchOnMovePiece.java
> +        return targetTeam.isPresent() && targetTeam.get().equals(getTeam().otherTeam());
여기저기서 Optional을 많이 활용해주고 계신데요 enum에 관련 값(NONE 등)을 추가하지 않고 Optional을 사용하는 이유가 있나요? Optional을 사용하는 것도 비용입니다. 항상 존재하는지 확인하고 사용해야하기 때문에 가독성과 편리함도 떨어지구요. 가능하면 꼭 필요한 곳에서만 사용했으면 좋겠습니다~

2024-03-25 11:40 UTC, slimsha2dy commented on src/main/java/domain/command/EndCommand.java
> +import java.util.List;
자동 설정이 꺼져있었네요ㅜㅜ 다 정리하고 다시 적용했습니다!

2024-03-25 11:49 UTC, slimsha2dy commented on src/main/java/domain/command/MoveCommand.java
> +    public MoveCommand(String... options) {
죄송합니다 이전에 사용하던 부분이라서 그냥 지나쳤던 것 같네요. from과 to 두 개의 문자열을 받도록 수정했습니다.

2024-03-26 04:57 UTC, slimsha2dy commented on src/main/java/domain/piece/Piece.java
> +	public abstract PieceType getPieceType();
기존에는 다른 건 고려하지 않았고 사용하는 순서로만 메서드를 정렬했었습니다. 그래서 추상 메서드는 딱히 신경쓰지 못했었는데 말씀하신 것처럼 정렬하는 것이 나을 것 같아 수정했습니다!

2024-03-26 05:11 UTC, slimsha2dy commented on src/main/java/domain/Position.java
> +        throw new RuntimeException();
이미 앞에서 처리를 한 예외인데 다시 발생하는 경우가 명확하지 않아 일단 RuntimeException으로 했던 것 같습니다. 잘못된 인자가 들어온 것으로 명확하게 알 수 있도록 IllegalArgumentException로 수정하고 예외 메시지를 추가했습니다!

2024-03-26 05:19 UTC, slimsha2dy commented on src/main/java/domain/ChessBoard.java
> +    ChessBoard(Piece... pieces) {
아니요 이부분도 마찬가지로 놓친 부분이네요 죄송합니다.. 수정했습니다..

2024-03-26 06:42 UTC, slimsha2dy commented on src/main/java/domain/piece/AbstractCatchOnMovePiece.java
> +        return targetTeam.isPresent() && targetTeam.get().equals(getTeam().otherTeam());
이 부분에 대해서 안그래도 페어와 얘기한 적이 있었는데, ```Team```이라는 enum에 NONE이 있는 것이 의미 상 부자연스럽기도 하고, NONE과 Optional로 각각 처리할 때를 비교했을 때 굳이 NONE을 추가해서 얻을 수 있는 이점이 생각보다 크지 않다고 결론을 짓게 되어 위와 같은 구현이 나오게 되었습니다.
그래서 말씀하신 부분을 보고 Optional에 대해 더 알아보았는데 결국 Optional을 사용하는 것 자체도 객체 비용이 발생하고 특히 매번 Optional에 대해 처리를 해주는 부분이 관련 값을 추가해서 쓰는 것에 비해 가독성에서 차이가 생각보다 더 크게 발생한다는 것에 공감하게 되었습니다.. 따라서 ```Optional<Team>```을 사용하는 부분을 수정했습니다!

2024-03-26 06:54 UTC, slimsha2dy commented on src/main/java/domain/PiecesOnChessBoard.java
> +public class PiecesOnChessBoard {
사실 이런 상황에서 무엇을 우선해야 할지에 대한 명확한 기준이 아직까지는 없는 것 같습니다. 다만, 현재 제가 배우는 과정을 고려해봤을 때, 비용이나 성능에서 큰 차이가 나는 상황이 아니라면 객체지향과 책임의 분리에 좀 더 집중해야 할 것 같다는 생각이 컸기 때문에 위와 같은 방식을 사용하게 된 것 같습니다.
다만 클래스를 관리하는 비용은 크게 신경쓰지 못했던 것 같습니다. 단순히 순환 참조로 인해 생길 수 있는 실수를 막기 위해서 위의 클래스들을 구현하긴 했지만 오히려 이 때문에 구조가 복잡해져서 쉽게 이해하기 힘들어지고 유지보수의 측면에서의 적지 않은 비용도 감수해야 할 것 같습니다.
일단 제가 당장 생각나는 다른 방법은 순환참조를 감수하는 것인데, Piece에서 Piece를 직접 참조했을 때, 필드인 Position을 움직일 수 없는 곳으로 변경한다거나 하는 위험이 크다고 생각합니다. 혹시 제가 놓친 부분이나 생각하지 못한 다른 방법이 있다면 궁금합니다!

2024-03-26 07:00 UTC, slimsha2dy commented on src/main/java/domain/Command.java
> +}
```Command``` 인터페이스로 추상화하게 되면 view와의 분리에서 장점이 큰 것 같습니다. 지금은 콘솔을 통해 String이 들어오지만,버튼을 통해 들어온다거나 하는 방식으로 변경되면 들어오는 값도 변하게 될 것 같습니다. ```Command```를 추상화하면 view에서는 어떤 값이 들어와도 컨트롤러에 ```Command```를 넘길 수 있으므로 변경을 최소화할 수 있을 것 같습니다!

2024-03-26 10:08 UTC, summerlunaa commented on src/main/java/domain/PiecesOnChessBoard.java
> +public class PiecesOnChessBoard {
넵 모든 방법에는 장단점이 있고 완벽한 방법은 없으니까요! 정답은 없지만 여러 방식을 고민하는 과정 자체가 의미있다고 생각합니다.
순환참조와 값 변경의 위험성을 감수할 것인지, 클래스를 관리하는 비용과 복잡한 구조를 감수할 것인지 알파카가 더 낫다고 생각하는 방향으로 진행하시면 될 것 같습니다 👍

2024-03-26 10:14 UTC, summerlunaa approved these changes
알파카 안녕하세요~

리뷰 반영 잘 해주셨습니다 👍 다만 몇 군데 빠진 곳이 있어서 코멘트 다시 달아두었어요.
이번 단계 요구사항은 다 만족해주셔서 나머지는 다음 단계에서 반영해주세요!

1,2단계는 여기서 머지하겠습니다! 수고하셨습니다 👏

2024-03-26 10:14 UTC, summerlunaa commented on src/main/java/domain/Position.java
> +        throw new RuntimeException();
요 부분 아직 수정이 안 된 것 같아요~ 확인 부탁드립니다.

2024-03-26 10:14 UTC, summerlunaa commented on src/main/java/domain/piece/AbstractCatchOnMovePiece.java
> +        return targetTeam.isPresent() && targetTeam.get().equals(getTeam().otherTeam());
아직 Optional이 남아있는 부분들은 Optional을 사용하는 게 더 낫다고 판단하셔서 남긴 건가요? 아니면 깜빡하셨을까요? 👀

2024-03-26 10:14 UTC, merged

2024-03-26 11:15 UTC, slimsha2dy commented on src/main/java/domain/piece/AbstractCatchOnMovePiece.java
> +        return targetTeam.isPresent() && targetTeam.get().equals(getTeam().otherTeam());
해당 41번 줄 부분은 아래 커밋에서 반영했는데 github 상에서는 수정이 안되어있네요..ㅜㅜ
https://github.com/woowacourse/java-chess/pull/649/commits/66fa2dc6e1f621d3e26305a210df1f9ed5d1b3ee

나머지 부분인 ```Optional<PieceMoveResult>```에서는 메서드의 반환값이 없는 경우(이동이 성공인지 실패인지 확실하지 않은 경우) 바깥의 메서드로 반환 결과 판단을 유보하기 위해 사용했는데, ```PieceMoveResult```가 이런 의미를 갖고 있는 것은 많이 어색하다고 생각해서 Optional을 사용했습니다. 오히려 결과가 존재할 경우 return하고 존재하지 않는 경우 다른 경우를 확인해본다는 점에서 Optional과 의미가 잘 맞는다고 생각하는데 이런 상황에서도 단순 의미 때문이라면 사용을 지양하는 편이 맞을까요?

2024-03-26 11:55 UTC, summerlunaa commented on src/main/java/domain/piece/AbstractCatchOnMovePiece.java
> +        return targetTeam.isPresent() && targetTeam.get().equals(getTeam().otherTeam());
오 여기 수정된 건 확인했어요. 다른 곳은 수정이 안 되었길래 의도한건지 까먹은건지 궁금해서 여쭤봤어요 ㅎㅎ 의도하신 거라면 이대로 가셔도 괜찮습니다~!

2024-03-26 12:01 UTC, summerlunaa commented on src/main/java/domain/ChessBoard.java
> +        return optionalPiece.isEmpty();
```java
return piecesOnBoard.stream()
            .noneMatch(piece -> piece.isOn(from));
```
추가로 여기는 이렇게 변경할 수 있겠네요.

그리고 메서드의 파라미터명을 보니 from, to로 되어있는데 position 등의 적절한 이름으로 변경해주세요! 메서드가 호출되는 맥락을 메서드는 알 필요가 없습니다.

2024-03-26 12:44 UTC, slimsha2dy commented on src/main/java/domain/ChessBoard.java
> +        return optionalPiece.isEmpty();
Optional을 굳이 쓸 필요 없는 부분에서 사용하고 있었고 쓰지 않는 방식이 훨씬 깔끔한 것 같네요.. 이 부분도 수정했습니다.

지금 다시 보니까 메서드 밖의 맥락이 매개변수 명에 들어가서 부자연스럽기도 하고 활용성이 한정되는 느낌도 드네요.. 직접적인 의미가 있는 move 메서드를 제외하고 from, to라는 이름을 position으로 변경했습니다.