[1, 2단계 - 체스] 호기(조호연) 미션 제출합니다.
woowacourse/java-chess pull request #652
Opened 2024-03-21 07:34 UTC by hoyeonyy

2024-03-21 09:40 UTC, jinyoungchoi95 requested changes
안녕하세요 호기 😄

미션의 리뷰어를 맡은 오리입니다.

어느덧 레벨1의 마지막 미션이네요🙂 몇가지 코멘트 남겨두었으니 확인부탁드려요.

궁금하거나 고민이 되는 부분이 있으시다면 언제든 pr 코멘트 또는 dm으로 요청 부탁드립니다.
감사합니다 🙇‍♂️

2024-03-21 09:40 UTC, jinyoungchoi95 commented on src/main/java/chess/piece/Piece.java
> +public abstract class Piece {
> 저희는 Piece 를 상속하여 각각 기물들을 구현하였습니다. 하지만 폰은 공격과 이동의 움직임이 달랐고 또한 색깔에 따라서도 달랐습니다. 때문에 다른 Piece 들과 형식을 똑같이 맞출 수 없어 Pawn이라는 부모객체를 하나 더 만들어 사용했습니다.
> 저희는 최선이라 생각했지만 혹시 가독성을 헤치지는 않는지 궁금합니다.

1. abstract를 사용했을 때 하위에서 상속받은 개체가 override하게되면 캡슐화가 깨지는 것 아닌가요? abstract를 사용하신다면 그 단점과 그걸 보완하는 방법에 대해서 학습해보시면 좋을 것 같아요.
2. protected로 최대한 막으신 것으로 보이는데요. java에서는 protected와 default를 제공하긴하지만 결국 반쪽만 막을 수 있기 때문에 캡슐화를 최대한 보장할 수는 있지만 보장을 한다라고 볼수는 없습니다. 미션을 진행하면서 public과 private만으로는 설계할 수 없을지 한번 고민해보세요. (현재 코드에서 private으로 막아두어도될 것 같은데 protected로 되어있는 메소드들이 있네요.)
3. 호기는 abstract 메소드와 일반 메소드의 위치를 어떻게 배치하는 편인가요? 현재 구조는 혼재되어있어보이네요.

2024-03-21 09:40 UTC, jinyoungchoi95 commented on src/main/java/chess/position/Direction.java
> +public enum Direction {
> 기물들이 갈 수 있는 8방향을 표현하기 위해 Direction 클래스를 만들었습니다. 그리고 Direction과 매칭 될 수 있는 함수형 인터페이스와 단위 움직임을 작성해 놓았습니다. 전부 필요해서 작성했다 생각하지만 만들고 보니 가독성이 별로인가..? 라는 생각이 들었습니다. 이 부분도 더 나아질 수 있는지 궁금합니다!

1. `private final BiPredicate<Position, Position> predicate;`이 무얼 뜻하는지 알기 힘들어요. 자바에서 제공하는 functional interface는 적극적으로 사용해도된다라는 생각이지만 변수명은 명확하게 지어주세요.
2. `KNIGHT`가 방향에 포함되는 것이 맞을까요? `Direction`은 말그대로 방향에 대한 1칸을 의미하는 것으로 보이는데 `KNIGHT`는 `Knight`가 가져야하는 특수한 이동방식아닐까요?

2024-03-21 09:40 UTC, jinyoungchoi95 commented on src/main/java/chess/position/Direction.java
> +                .orElseThrow(() -> new IllegalArgumentException("잘못된 방향입니다."));
호기는 `IllegalArgumentException`과 `IllegalStateException`의 차이가 무엇이고 각각 언제 사용되어야한다고 생각하시나요?

2024-03-21 09:40 UTC, jinyoungchoi95 commented on src/main/java/chess/position/Direction.java
> +                .findFirst()
`findFirst`와 `findAny`의 차이는 무엇인가요?

2024-03-21 09:40 UTC, jinyoungchoi95 commented on src/test/java/chess/position/DirectionTest.java
> +                .isEqualTo(Direction.POSITIVE_FILE_POSITIVE_RANK);
BDD(given-when-then)에서는 when은 테스트하고자 하는 행위, then은 행위에 대한 검증을 표현해요. 따라서
```java
// when
var actual = Direction.calculateBetween(source, destination)

// then
assertThat(actual).isEqualTo(Direction.POSITIVE_FILE_POSITIVE_RANK);
```
이 BDD에 맞는 표현이에요. `when&then`으로 함께쓰이는 케이스는 보통 예외와 같이 메소드실행부가 검증부에 의해 감싸져야할때 보통 사용해요.

2024-03-21 09:40 UTC, jinyoungchoi95 commented on src/test/java/chess/position/DirectionTest.java
> +    Position source = Position.of(File.D, Rank.FOUR);
```suggestion
    private Position source = Position.of(File.D, Rank.FOUR);
```
외부 사용을 막아주어야할 것 같네요 :)

2024-03-21 09:40 UTC, jinyoungchoi95 commented on src/test/java/chess/position/DirectionTest.java
> +class DirectionTest {
```java
public Position nextPosition(Position position) {
    return nextPositionGenerator.apply(position);
}
```
에 대한 테스트도 필요해보이네요.

2024-03-21 09:40 UTC, jinyoungchoi95 commented on src/test/java/chess/position/FileTest.java
> +class FileTest {
`subtract`와 `createFileByDifferenceOf`도 테스트해야겠네요. 해당 클래스만이 아닌 전반적으로 모든 클래스에서 테스트가 누락되지 않았는지 확인부탁드려요.

클래스를 사용하는 상위클래스에서 테스트한다고 테스트하는 것이 아닌 가장 작은 단위부터 테스트하는것을 항상 고려해보세요. TDD때 했던 경험을 떠올려보시면 좋을 것 같아요 😄

2024-03-21 09:40 UTC, jinyoungchoi95 commented on src/main/java/chess/position/Position.java
> +    static {
static block 👍 

호기가 생각했을 때 static block의 단점은 없었나요?

2024-03-21 09:40 UTC, jinyoungchoi95 commented on src/test/java/chess/position/PositionTest.java
> +    @DisplayName("두 위치가 양의 기울기 대각선인 경우를 올바르게 판단한다.")
테스트 케이스들이 명확해서 좋네요.

2024-03-21 09:40 UTC, jinyoungchoi95 commented on src/main/java/chess/position/Position.java
> +        return Math.abs(rank.subtract(other.rank) * file.subtract(other.file)) == 2;
2는 의미가 있는 상수로 표현되어야하지 않을까요?

2024-03-21 09:40 UTC, jinyoungchoi95 commented on src/main/java/chess/position/Position.java
> +    public boolean isNotEquals(Position other) {
(반영하지 않으셔도 됩니다.) `!`가 사용될수록 가독성이 떨어지기 때문에 부정표현메소드를 추가하신 것은 이해가 되어요. 다만 단순히 `!`를 표현하는 메소드를 추가하는 것이 과하지는 않은가 고민해보시면 좋을 것 같아요.

안그래도 방향에 대한 책임이 큰 `Position`에게 메소드 한개 추가는 과하지 않을까요? 단순히 부정인데 테스트까지 추가되어야하는 점도 단점이겠네요. (테스트가 없네요.)

2024-03-21 09:40 UTC, jinyoungchoi95 commented on src/test/java/chess/position/PositionTest.java
> +    @DisplayName("동등성을 올바르게 판단한다.")
1. 캐싱되어 사용되고 있는데 equals를 재정의할 필요가 있을까요?
2. 동일성을 판단하지 않아도 될까요?

2024-03-21 09:40 UTC, jinyoungchoi95 commented on src/main/java/chess/piece/PieceAttributes.java
> +    private final PieceType pieceType;
`PieceType`은 각각의 타입을 정의하고 있고, 이걸 가진 `Piece` 구현체들은 그 타입에 따라 클래스명을 짓고 있는데요. `PieceType`은 instanceOf를 대체하는 용도로 사용되는 것으로 보이는데 상속을 사용할 것이라면 상속을, 조합을 사용할 것이라면 조합을 사용하도록 하는 방법을 고려해보세요. 현재 코드를 풀어서 보면
```java
public class King {
    private final PieceType pieceType = KING;
```
가 되는데 표현이 어색하지 않나요?

`King`클래스가 `PieceType.KING`을 가지고 있는 것이라면 조합을 통해서 표현하는게 낫지 않을까요?

2024-03-21 09:40 UTC, jinyoungchoi95 commented on src/main/java/chess/piece/Queen.java
> +                )
상수여도 되지않을까요?

2024-03-21 09:40 UTC, jinyoungchoi95 commented on src/main/java/chess/piece/Piece.java
abstract 클래스의 테스트는 누가하여야 적절할까요?

2024-03-21 09:40 UTC, jinyoungchoi95 commented on src/main/java/chess/view/Command.java
> +    private final String value;
enum은 `values()`를 통해서 enum의 list값을 제공해요. 그래서 가능하면  enum의 필드에는 `value`라는 네이밍을 지양하는편입니다.

2024-03-21 09:40 UTC, jinyoungchoi95 commented on src/main/java/chess/view/InputView.java
> +        if (!POSITION_PATTERN.matcher(input).matches()) {
호기가 생각하기에 한줄에 점을 한줄만 찍어야한다는 규칙은 무슨 장점이 있어서 나왔다고 생각하시나요?

2024-03-21 09:40 UTC, jinyoungchoi95 commented on src/main/java/chess/board/BoardInitializer.java
> +    private static final Map<Position, Piece> pieces = new HashMap<>();
```suggestion
    private static final Map<Position, Piece> PIECES = new HashMap<>();
```

2024-03-21 09:40 UTC, jinyoungchoi95 commented on README.md
> +- [ ] (특수 룰: 캐슬링)
todo일까요?

2024-03-24 06:24 UTC, hoyeonyy commented on src/main/java/chess/piece/Piece.java
> +public abstract class Piece {
최저도 protected를 사용할 때 찝찝하기는 했습니다..😂 오리 말대로 최대한 public 과 private를 사용해서 코드를 작성해보도록 하겠습니다. 

abstract 에 대해 공부하다 궁금한 점이 생겨 여쭈어보려고 합니다!

abstract 메서드를 만들어 override 해서 사용한다면 자식 클래스가 부모의 메서드나 변수에 접근 할 수 있기 때문에 부모 클래스의 캡슐화가 깨지는 것에는 동의합니다! 하지만 한편으로는 부모와 자식이 하나의 캡슐로 묶여 사용되는 것이 아닐까..?🤔 라는 생각이 들었습니다.

혹시 이것에 대해 오리의 생각이 어떤지 궁금합니다!

2024-03-24 06:41 UTC, hoyeonyy commented on src/main/java/chess/position/Direction.java
> +public enum Direction {
방향에 대해 Knight 방식이 올바르지 않다고 생각해서 삭제하고 코드를 수정했습니다!

2024-03-24 11:41 UTC, hoyeonyy commented on src/main/java/chess/position/Direction.java
> +                .orElseThrow(() -> new IllegalArgumentException("잘못된 방향입니다."));
제가 미처 생각하지 못했던 부분인 것 같아요..!
찾아본 결과 `IllegalArgumentException` 은 잘못된 인자가 넘어왔을 때, 예를 들어 양수만 받을 수 있는데 음수가 넘어왔을 경우 던지는 예외이고,

`IllegalStateException` 은 메서드가 호출 되면 안될때 메서드가 호출된 경우에 사용한다고 학습했습니다!

이경우에서 `Direction`에 `calculateBetween` 함수는 `IllegalStateException` 이 올바른 것 같습니다!

2024-03-24 11:49 UTC, hoyeonyy commented on src/main/java/chess/position/Direction.java
> +                .findFirst()
`findFirst`는 stream내에서 조건에 맞는 첫번째 요소를, `findAny`는 조건에 맞는 요소를 가져오지만 첫번째를 보장해주지는 않는다고 알고있습니다!

2024-03-24 11:51 UTC, hoyeonyy commented on src/test/java/chess/position/DirectionTest.java
> +                .isEqualTo(Direction.POSITIVE_FILE_POSITIVE_RANK);
제가 BDD를 오해하고 있었던 것 같습니다!

위 처럼 수정해보겠습니다!

2024-03-24 11:52 UTC, hoyeonyy commented on src/test/java/chess/position/DirectionTest.java
> +    Position source = Position.of(File.D, Rank.FOUR);
테스트코드에서도 변수를 접근제어자로 막아주어야 하나요?!

2024-03-24 11:56 UTC, hoyeonyy commented on src/test/java/chess/position/FileTest.java
> +class FileTest {
테스트 커버리지만 돌려보고 넘어가는 것이 문제였던 것 같습니다..😂

앞으로는 작은 단위부터 테스트하도록 노력해보겠습니다!

2024-03-24 12:05 UTC, hoyeonyy commented on src/main/java/chess/position/Position.java
> +    static {
static block의 단점은 메모리 문제와 thread safe하지 않다는 점이라고 생각합니다!

프로그램과 생명주기를 함께 하다보니 GC의 컬렉션 대상이 되지 않습니다. 때문에 많은 static 맴버는 메모리 문제를 일으킬 수 있을 것 같습니다.

또한 모든 스레드들이 static을 공유하다보니 동시성 문제가 일어날 수 있을 것 같습니다!

2024-03-24 12:19 UTC, hoyeonyy commented on src/main/java/chess/position/Position.java
> +    public boolean isNotEquals(Position other) {
이 부분에 대해 궁금한 점이 생겼습니다!

오리가 말씀하신 "작은 단위 테스트부터 시작 해야 된다" 라는 말에 안일해졌던 저의 모습을 반성하게 된거 같아요..😭
이번 `isNotEquals` 메서드 안에는 `equals` 메서드만 들어있는데요! 이런 자바에서 제공해주는 메서드에 대한 테스트또한 테스트 대상에 포함이 되어야 할지 궁금합니다.

저의 짧은 견해로 판단했을 때에는 자바의 메서드를 테스트하는 느낌이 들어 안했던 것 같아요. 이에 대한 오리의 생각이 궁금합니다!

2024-03-24 12:26 UTC, hoyeonyy commented on src/test/java/chess/position/PositionTest.java
> +    @DisplayName("동등성을 올바르게 판단한다.")
> 캐싱되어 사용되고 있는데 equals를 재정의할 필요가 있을까요?

캐싱을 마지막에 하게되서 equals를 지우는 것을 놓쳤습니다..ㅠㅠ

>동일성을 판단하지 않아도 될까요?

동일성을 판단하는 게 맞을 것 같아요!
캐싱을 했을 때는 동일성을 판단하고 캐싱을 하지 않을 때에는 동등성을 판단하는게 맞는 걸까요?

2024-03-24 12:39 UTC, hoyeonyy commented on src/main/java/chess/piece/PieceAttributes.java
> +    private final PieceType pieceType;
제가 이해한게 맞는 지 궁금해서 한번 더 여쭈어보고싶습니다!

현재 Piece의 구현체 들로 king, queen, ..  과 같이 타입에 따라 클래스의 이름을 지었고 그에 대해 PieceType 이라는 객체로 표현을 하고 있는데요!

Piece의 상속을 받고 PieceType은 조합을 사용하고 있어 어색하는 것일까요??🤔

2024-03-24 12:47 UTC, hoyeonyy commented on src/main/java/chess/piece/Piece.java
처음에는 구현 클래스에서 하는 게 맞다고 생각했지만 너무 의존적인 테스트가 될 것 같습니다.
그렇다고 비어있는 구현 클래스를 하나 만들어서 테스트 하기엔 테스트를 위한 코드를 작성하는 것 같아 고민입니다..!

구현 클래스에서 하는게 가장 나은 선택일까요?

2024-03-24 12:53 UTC, hoyeonyy commented on src/main/java/chess/view/InputView.java
> +        if (!POSITION_PATTERN.matcher(input).matches()) {
객체에서 멀리 떨어진 객체를 불러와서 메세지를 보내지 말라 라는 의미에서 사용한다고 생각합니다.

객체를 타고타고 물어 보는 것이 아니라 메서드를 분리해서 하나의 객체에게만 물어보게 하여 의존도를 낮추는 것이 목적이라 생각합니다.

2024-03-24 12:55 UTC, hoyeonyy commented on README.md
> +- [ ] (특수 룰: 캐슬링)
페어와 시간이 되면 구현하자 했는데 시간에 쫒겨 하지 못했습니다..🥹

2024-03-24 13:27 UTC, hoyeonyy commented on src/test/java/chess/position/FileTest.java
> +class FileTest {
테스트를 추가하다가 궁금증이 생겼습니다!

작은 단위테스트를 하였고 그 메서드만을 사용하는 상위클래스의 메서드가 있다면 그 메서드는 테스트를 해야할까요??

```java
public boolean hasLowerFileThan(Position other) {
        return file.subtract(other.file) < 0;
    }
```

위와 같은 메서드가 있을 때 `subtract` 에 대한 테스트를 끝냈다면 `hasLowerFileThan` 에 대한 테스트가 있어야 할까요??

2024-03-24 17:00 UTC, jinyoungchoi95 commented on src/main/java/chess/piece/Piece.java
> +public abstract class Piece {
간단하게 이야기하면 부모와 자식은 분리된 클래스이기 때문에 하나의 캡슐이라고 표현할 수 없어요. 클래스가 분리되면 서로의 영향 범위가 분리되는 것과 마찬가지이기 때문에 별개의 클래스로 판단합니다.

2024-03-24 17:02 UTC, jinyoungchoi95 commented on src/test/java/chess/position/DirectionTest.java
> +    Position source = Position.of(File.D, Rank.FOUR);
호기는 막았을 때와 안막았을 때 각각 어떤 차이가 있다고 생각하시나요?

2024-03-24 17:05 UTC, jinyoungchoi95 commented on src/test/java/chess/position/FileTest.java
> +class FileTest {
`substract`에 대한 테스트는 끝났지만 `< 0`에 대한 테스트는 아무도 하지 않았기 때문에 필요하지 않을까요?

2024-03-24 17:10 UTC, jinyoungchoi95 commented on src/main/java/chess/position/Position.java
> +    public boolean isNotEquals(Position other) {
제 의견보다는
```
모든 기능을 TDD로 구현해 단위 테스트가 존재해야 한다. 단, UI(System.out, [System.in](http://system.in/)) 로직은 제외
```
미션에서 요구사항으로 나온것처럼 모든 기능을 단위테스트해보세요. 정답이 없는 내용이기 때문에 우테코 기간동안은 미션의 요구사항에 대해서 극단적으로 지켜보면서 다 경험해본 후 호기만의 판단 기준을 만들어나가보는게 좋을 것 같아요.

2024-03-24 17:13 UTC, jinyoungchoi95 commented on src/test/java/chess/position/PositionTest.java
> +    @DisplayName("동등성을 올바르게 판단한다.")
> 캐싱을 했을 때는 동일성을 판단하고 캐싱을 하지 않을 때에는 동등성을 판단하는게 맞는 걸까요?

캐싱을 하지 않았을 때 객체간의 동등성을 비교해야한다면 그렇게 해야하지 않을까요?

2024-03-24 17:13 UTC, jinyoungchoi95 commented on src/main/java/chess/piece/PieceAttributes.java
> +    private final PieceType pieceType;
네 상속을 하는 이유는 구현체에 대한 추상화인데 `PieceType`을 통해서 구현체에 대한 타입정보를 또 들고 있는다면 과연 추상화 올바르게 잘 했는지 고민해보시면 좋을 것 같아요.

2024-03-24 17:16 UTC, jinyoungchoi95 commented on src/main/java/chess/piece/Piece.java
둘다 해보시고 호기가 느끼는 장단점을 알려주세요 :)

2024-03-24 18:05 UTC, jinyoungchoi95 requested changes
안녕하세요 호기 😄

피드백 잘 반영해주셨네요. 몇가지 코멘트 추가로 남겨두었으니 확인부탁드려요.

궁금하거나 고민이 되는 부분이 있으시다면 언제든 pr 코멘트 또는 dm으로 요청 부탁드립니다.
감사합니다 🙇‍♂️

2024-03-24 18:05 UTC, jinyoungchoi95 commented on src/main/java/chess/controller/ChessGameController.java
> +public class ChessGameController {
Controller로 변경해주신 걸로 보이는데 Controller라는 이름이 적절할까요?

MVC, Spring에서 사용하는 controller를 생각하고 네이밍하셨다면 1레벨은 "자바만을 사용하여 만드는 어플리케이션"이기 때문에 특정 패턴에 종속적인 네이밍을 사용하지 않아도 됩니다. 패턴은 이론적으로 학습하고 적용할 것을 찾아 억지로 네이밍하는 것보다는 자연스럽게 미션을 통해서 적절한 상황의 디자인 패턴을 발견하는 재미를 느끼셨으면 좋겠습니다 :)

그럼 종속적인 네이밍을 뒤로하고 "컨트롤러"라는 이름은 이 클래스의 기능을 담아내기에 충분한 네이밍을 가지고 있나요? 컨트롤러는 조이스틱과 같은 게임의 컨트롤러를 뜻한다고 보이는데요. 조이스틱이 게임을 실행시키고 화면을 출력하지 않듯 Controller보다는 이 객체를 표현해줄 더 좋은 네이밍을 고려하셨으면 좋겠습니다.

2024-03-24 18:05 UTC, jinyoungchoi95 commented on src/main/java/chess/domain/position/Position.java
> +        return !this.equals(other);
```suggestion
        return !.equals(other);
```
클래스 내에서 `this`를 사용하는 호기의 기준이 있을까요?

2024-03-24 18:05 UTC, jinyoungchoi95 commented on src/test/java/chess/domain/position/PositionTest.java
> +class PositionTest {
테스트 👍

2024-03-24 18:05 UTC, jinyoungchoi95 commented on src/main/java/chess/domain/piece/PieceAttributes.java
> +    private final PieceType pieceType;
https://github.com/woowacourse/java-chess/pull/652#discussion_r1533503004

에서의 이야기처럼 상속을 했다면 하위구현체에 대한 구현정보(무슨 타입인지)가 필요없어야 잘 된 추상화입니다. 상속을 사용할건지 조합을 사용할건지는 다시 한번 고민해보세요 :)

2024-03-24 18:05 UTC, jinyoungchoi95 commented on src/main/java/chess/domain/piece/Rook.java
> +        );
```suggestion
        super(PieceType.ROOK, color, ROOK_DIRECTION);
```
과도한 줄바꿈은 가독성에 오히려 해가 되어요. refactoring에서 길이로 제약사항이 걸리지 않는 이상 줄바꿈은 지양하는 것이 좋습니다.

2024-03-24 18:05 UTC, jinyoungchoi95 commented on src/test/java/chess/domain/piece/RookTest.java
> +                () -> assertThat(rook.isMovable(source, Position.of(File.H, Rank.FOUR))).isTrue()
현재 테스트하고자하는 대상은 `isMovable`이에요. 지금 4가지의 케이스는 주어진 각각 다른 상황인거죠.

그래서 `isMovable`안에 있는 데이터는 `CsvSource`로 분리하거나 상, 하, 좌, 우 각각의 테스트 메소드로 분리하는 것이 무엇을 테스트하고자 하는지 명확해집니다.

2024-03-24 18:05 UTC, jinyoungchoi95 commented on src/main/java/chess/domain/position/Direction.java
> +    public Position nextPosition(Position position) {
각각의 위치를 생성하고 있어 모든 경우에 대한 테스트가 필요해보여요.

2024-03-24 18:05 UTC, jinyoungchoi95 commented on src/main/java/chess/domain/piece/Piece.java
> +public abstract class Piece {
abstract를 상속한 클래스에서 잘못된 override를 막기위한 방안은 없을까요?

2024-03-24 18:05 UTC, jinyoungchoi95 commented on src/main/java/chess/domain/piece/Pawn.java
> +        return BLACK_PAWN_DIRECTION;
좀더 책임을 분리한다면 WhitePawn과 BlackPawn을 만들수도 있겠네요.

2024-03-24 18:05 UTC, jinyoungchoi95 commented on src/main/java/chess/domain/board/BoardInitializer.java
> +        return new Board(PIECES);
원하는 체스판의 형태를 갖추는지도 테스트가 필요할까요?

2024-03-24 18:05 UTC, jinyoungchoi95 commented on src/main/java/chess/domain/board/Board.java
> +    }
https://github.com/woowacourse/java-chess/pull/652#discussion_r1533420656 에서 말씀드렸던 default는 반쪽짜리 접근제어자에요.

생성자를 막아야하는 이유가 있을까요? 메소드는 불필요한 기능의 확장이기 때문에 막는다지만 생성자는 안정적인 객체를 생성함을 보장하면 열어두어도 되지 않나요?

2024-03-24 18:05 UTC, jinyoungchoi95 commented on src/main/java/chess/domain/board/Board.java
> +        validateAllyPieceNotOnDestination(source, destination);
validation 로직을 래핑하려면 `validateNoPiecesBetween`까지 같이 래핑을 하는건 어떨까요? 혹은 래핑메소드를 제거해도 의미는 충분히 전달될 것 같아보여요.

2024-03-24 18:05 UTC, jinyoungchoi95 commented on src/main/java/chess/domain/board/Board.java
> +        if (pieces.get(source) == null) {
```suggestion
        if (pieces.containsKey(source)) {
```
로 표현될 수 있겠네요 :)

2024-03-24 18:05 UTC, jinyoungchoi95 commented on src/main/java/chess/domain/board/Board.java
> +        if (destinationPiece != null && destinationPiece.hasSameColorWith(sourcePiece)) {
null을 활용한 로직들은 모두 제거해주세요. null은 어떤 값으로 인해 문제가 발생했는지 의미를 파악하기 힘들 뿐더러 다양한 문제를 발생시킵니다.
https://www.mimul.com/blog/why-null-is-bad/

2024-03-24 18:05 UTC, jinyoungchoi95 commented on src/main/java/chess/domain/board/Board.java
> +    public void replacePiece(Position source, Position destination, Piece piece) {
```suggestion
    private void replacePiece(Position source, Position destination, Piece piece) {
```
👀

2024-03-24 18:05 UTC, jinyoungchoi95 commented on src/main/java/chess/view/display/BoardDisplayConverter.java
> +        return new RankDisplay(pieceDisplays);
stream foreach를 종단 연산에서 사용하는 것은 안티패턴이에요. 바로 toList를 해도되지 않을까요?

Terminal operations, such as Stream.forEach or IntStream.sum, may traverse the stream to produce a result or a side-effect. After the terminal operation is performed, the stream pipeline is considered consumed, and can no longer be used; if you need to traverse the same data source again, you must return to the data source to get a new stream. In almost all cases, terminal operations are eager, completing their traversal of the data source and processing of the pipeline before returning. Only the terminal operations iterator() and spliterator() are not; these are provided as an "escape hatch" to enable arbitrary client-controlled pipeline traversals in the event that the existing operations are not sufficient to the task.

https://docs.oracle.com/javase/8/docs/api/java/util/stream/package-summary.html

2024-03-24 18:05 UTC, jinyoungchoi95 commented on src/test/java/chess/domain/board/BoardTest.java
> +        // when, then
(반영하지 않으셔도 됩니다.) when&then을 expect로 표현하기도 합니다.

2024-03-24 18:05 UTC, jinyoungchoi95 commented on src/test/java/chess/domain/board/BoardTest.java
> +        assertThat(actual.hasColorOf(Color.WHITE)).isTrue();
assertAll로 감싸주어야 143이 실패해도 144와 145라인의 테스트 여부를 알 수 있겠네요.

2024-03-25 05:27 UTC, hoyeonyy commented on src/test/java/chess/position/DirectionTest.java
> +    Position source = Position.of(File.D, Rank.FOUR);
같은 패키지의 다른 테스트에서 변수에 접근을 할 수가 있겠네요.

테스트가 순서대로 실행이 되는 것이 아니기 때문에 다른 테스트에서 변수를 만졌을 경우 테스트가 깨질 수 있을 것 같아요..!

고민해보지 못한 부분을 알려주셔서 감사합니다!

2024-03-25 05:29 UTC, hoyeonyy commented on src/main/java/chess/position/Position.java
> +    public boolean isNotEquals(Position other) {
이번 미션은 모든 메서드에 대해 테스트 해보면서 저의 주관을 만들어 와보겠습니다!

2024-03-25 07:03 UTC, hoyeonyy commented on src/main/java/chess/piece/PieceAttributes.java
> +    private final PieceType pieceType;
instanceOf를 지양 하는 이유는 캡슐화 문제가 아닐까 싶습니다.

instanceOf 는 객체의 클래스를 꺼내 오는 것이므로 getter 와 같다고 생각합니다! 때문에 PieceType을 만들어 뷰와 매핑을 하였습니다.

하지만 한편으로는 PieceType 은 뷰에 매핑하는 역할만 가진 클래스라고 생각합니다. 이 때문에 도메인에 불필요한 코드가 포함되었다고 생각합니다. 뷰에 데이터를 전달할 때 getter를 사용하듯이 뷰에 instanceOf 를 사용해보면 어떨까?!라는 생각이 들었습니다.

2024-03-25 07:04 UTC, hoyeonyy commented on src/main/java/chess/piece/Piece.java
넵 둘다 한번 해보고 리뷰 요청 남기겠습니다!

2024-03-25 07:33 UTC, hoyeonyy commented on src/main/java/chess/controller/ChessGameController.java
> +public class ChessGameController {
저도 이 부분에 대해서 크루 들과 대화도 해보았고 구글링도 많이 해봤었습니다. 하지만 이 만큼 와닿은 비유는 없었던 것 같습니다..🥰 조이스틱과 비교를 하니 이해가 되네요.

저는 이것 외에도 컨벤션(???) 같은 느낌으로 사용하기도 하는데요! 예를 들어 제가 누군가의 코드를 본다면 컨트롤러 부터 보고 있습니다! 컨트롤러를 봐야 전체적으로 어떤 흐름으로 흘러가는지 알기 쉽다고 생각해서요! 이 이유만으로는 컨트롤러 라는 네이밍에는 무리가 있을까요?

2024-03-25 07:40 UTC, hoyeonyy commented on src/main/java/chess/domain/position/Position.java
> +        return !this.equals(other);
자바 문법에 서툴렀던 것 같습니다..!
인스턴스 자신과 `other`를 비교하기 때문에 `this.equals(other)` 이라고 기술 했는데 this를 안써도 되는지 몰랐습니다..!
수정하겠습니다!

2024-03-26 02:51 UTC, hoyeonyy commented on src/main/java/chess/domain/piece/Piece.java
> +public abstract class Piece {
final 키워드를 붙여 override하지 못하게 막았습니다!

2024-03-26 02:58 UTC, hoyeonyy commented on src/main/java/chess/domain/piece/Pawn.java
> +        return BLACK_PAWN_DIRECTION;
페어와 의견을 나누어 봤던 내용이었는데요. WhitePawn,  BlackPawn 을 나눌까 고민했었습니다..!

저희가 내렸던 결론은 WhitePawn 과 BlackPawn은 다른 것이 방향밖에 없어 나누는 것이 과한 분리가 아닐까..?! 생각했습니다. 만약 색깔로도 클래스를 분리 한다면 WhiteInitPawn, WhiteMovedPawn, BlackInitPawn, BlackMovedPawn 이렇게 4가지로 분리해야 할 것 같은데 이런 분리가 과한 분리는 아닌지 궁금합니다!

2024-03-26 05:47 UTC, hoyeonyy commented on src/main/java/chess/domain/board/BoardInitializer.java
> +        return new Board(PIECES);
Board의 생성자를 만드는 과정에서 코드가 너무 많아 BoardInitializer 라는 클래스로 분리 했습니다.
그래서 createBoard 를 테스트 하는 것은 생성자를 테스트 하는 것 같은 느낌이 들어 생략했습니다.
이런 create를 담당하는 객체나 생성자에 대한 테스트가 필요할까요?

2024-03-26 05:51 UTC, hoyeonyy commented on src/main/java/chess/domain/board/Board.java
> +    }
무작정 이 생성자는 사용하지 않을 것이기 때문에 최대한 막아보자 라는 생각으로 default로 막았던 것 같습니다.

하지만 오리 말씀대로 생성자의 매개변수 올바른 형식만 들어오면 안정적인 객체를 만들 수 있을 것 같습니다!

2024-03-26 06:12 UTC, hoyeonyy commented on src/main/java/chess/domain/board/Board.java
> +        if (destinationPiece != null && destinationPiece.hasSameColorWith(sourcePiece)) {
null 이라는 단어가 의도가 명확해 보이지 않나..? 라는 생각으로 null을 사용했습니다.

하지만 오리가 보내준 자료를 보니 지양해야될 로직이네요. null 을 사용하는 작업들을 전부 제거하겠습니다.

2024-03-26 06:50 UTC, hoyeonyy commented on src/main/java/chess/view/display/BoardDisplayConverter.java
> +        return new RankDisplay(pieceDisplays);
null 도 같이 삭제해서 반영했습니다! 감사합니다!!

2024-03-26 15:12 UTC, jinyoungchoi95 commented on src/main/java/chess/piece/PieceAttributes.java
> +    private final PieceType pieceType;
instanceOf는 결국 그 객체의 타입을 알기위함이에요. 근데 추상화를 한 목적은 무엇일까요? 구현체에 대해서 의존하기 위한 것이 아닌 추상적으로 객체를 표현하기 위함 아닐까요?

instanceOf를 뷰에 사용하건 어디에 사용하건 과연 그 구현체의 타입 정보를 알아야한다면 지금 이 Piece는 잘 추상화한 상속을 사용한 것인지를 고민하셨으면해서 남긴 코멘트였어요.

2024-03-26 15:17 UTC, jinyoungchoi95 commented on src/main/java/chess/controller/ChessGameController.java
> +public class ChessGameController {
네 mvc나 스프링을 잘 알지 못하는 사람이 볼 때 컨트롤러는 말씀드린대로 이 객체를 설명해주기 힘든 네이밍이고, mvc라고 하더라도 mvc에서의 controller는 view를 들고 모든 행위를 한꺼번에 실행시키지는 않아요.

controller에 대한 내용은 2레벨에서 배우는만큼 그때 잘 배우고 사용하셨으면해서 controller말고 다른 도메인객체를 네이밍 지은 것처럼 지어달라는 이야기였어요.

자동차때 미션 피드백에서도
> MVC 패턴 기반으로 리팩터링해 view 패키지의 객체가 domain 패키지 객체에 의존할 수 있지만, domain 패키지의 객체는 view 패키지 객체에 의존하지 않도록 구현한다.
"기반"으로 domain이 view에 의존하지 않는 형태로 구현하라고 이야기하지 controller를 구성해야한다는 이야기는 없어요. 이미지에서도 controller는 view에게 전달하는 용도이지 view를 들고 모든 게임의 실행내용을 본인이 플로우를 들고 처리하지 않습니다.

2024-03-26 15:18 UTC, jinyoungchoi95 commented on src/main/java/chess/domain/piece/Pawn.java
> +        return BLACK_PAWN_DIRECTION;
각각의 실행동작과 책임이 다른데 분리하지 않을 이유는 없는 것 같아요. 이동 전략자체가 다르지 않을까요?

2024-03-26 15:19 UTC, jinyoungchoi95 commented on src/main/java/chess/domain/board/BoardInitializer.java
> +        return new Board(PIECES);
TDD를 했다면 체스판 위의 말들의 위치가 어디있는지 기능명세를 먼저하고, 테스트를 작성 후 코드를 짰기 때문에 모든 위치에 대한 테스트검증이 존재하지 않았을까요?

2024-03-26 15:32 UTC, jinyoungchoi95 requested changes
안녕하세요 호기 😄

다음 단계로 넘어가기 전 몇가지 코멘트 남겨두었는데 확인이 필요하여 request change드려요. 확인 및 반영 후 요청주시면 머지하겠습니다.

궁금하거나 고민이 되는 부분이 있으시다면 언제든 pr 코멘트 또는 dm으로 요청 부탁드립니다.
감사합니다 🙇‍♂️

2024-03-26 15:32 UTC, jinyoungchoi95 commented on src/main/java/chess/domain/piece/Piece.java
> +    private final boolean isReachable(Position source, Position destination, Direction direction) {
private은 외부 접근이 불가능하기 때문에 final을 안달아주어도 될 것 같아요.

2024-03-26 15:32 UTC, jinyoungchoi95 commented on src/main/java/chess/domain/piece/Piece.java
> +    }
enum은 동일성과 동등성 중 무엇을 비교하는 것이 좋을까요?

2024-03-26 15:32 UTC, jinyoungchoi95 commented on src/main/java/chess/view/display/BoardDisplayConverter.java
> +        return rankDisplays;
https://github.com/woowacourse/java-chess/pull/652#discussion_r1536872722 코멘트 다시 확인해주세요 :)

2024-03-26 15:32 UTC, jinyoungchoi95 commented on src/main/java/chess/view/display/PieceDisplay.java
> +    EMPTY(null, null, ".");
null보다는 `Empty.class`를 추가하는게 낫지않을까요?

2024-03-26 15:32 UTC, jinyoungchoi95 commented on src/main/java/chess/ChessApplication.java
> +    //TODO : abstract 큻래스 테스트하기 1. 구현체로, 2. 빈 ㄱ개체 하나만들어서
todo는 모두 제거해주세요 😄

2024-03-27 06:23 UTC, hoyeonyy commented on src/main/java/chess/controller/ChessGameController.java
> +public class ChessGameController {
좋은 말 감사합니다ㅠㅠ 컨트롤러라는 네이밍을 사용할 때 조금 더 생각해보겠습니다!

2024-03-27 06:29 UTC, hoyeonyy commented on src/main/java/chess/piece/PieceAttributes.java
> +    private final PieceType pieceType;
오리 말씀대로
1. 추상화를 위해 추상클래스를 상속한 구체 클래스를 만들었음에도 불구하고 PieceType 이라는 구체 클래스의 정보를 다시 명시 하는 것도 이상한 것 같습니다.

2. instanceOf 를 사용한다 하더라도 추상화를 했다면 구체 클래스에 의존하는 코드가 있으면 안되는데 결국 instanceOf를 사용하며 구체 클라스를 의존하는 것도 DIP 를 위배한다고 생각합니다,.

3. 조합을 고려해봤을 때 King이라는 클래스가 Piece를 가지며 피스들의 동작방식을 가지고 있다는 개념도 저에게는 조금 낯선것 같습니다..

어떻게 해야 더 좋은 설계를 할 수 있을지 잘 모르겠어요..😂😂😂 다시 한번 고민해 봐야겠습니다..

2024-03-27 06:32 UTC, hoyeonyy commented on src/main/java/chess/domain/board/BoardInitializer.java
> +        return new Board(PIECES);
오리 말을 듣고 제가 보여주기식으로 TDD를 하고 있었던 것 같네요..

제대로 된 TDD의 흐름을 따라갔더라면 테스트를 하냐 마냐에 대한 고민자체가 없었겠군요..

앞으로 조금더 TDD를 연습해 보겠습니다!

2024-03-27 06:59 UTC, hoyeonyy commented on src/main/java/chess/domain/piece/Piece.java
> +    }
enum은 동일성을 확인하는게 맞는 것 같습니다!

수정하겠습니다!

2024-03-27 11:51 UTC, jinyoungchoi95 commented on src/main/java/chess/piece/PieceAttributes.java
> +    private final PieceType pieceType;
3은 `Piece`가 color, 움직임에 대한 전략을 나타내는 형태로 고민을 해보셔도 좋을 것 같아요. 조합이 무언가 큰 설계가 필요한게 아니라 클래스를 그냥 필드로 가지고 있는 것 뿐이에요.

현재로도 미션에서 필요한 구현과 학습은 충분하니 시간이 여유되실 때 한번 다시 고민해보세요 :)

2024-03-27 11:53 UTC, jinyoungchoi95 approved these changes
안녕하세요 호기 😄

다음 미션 진행을 위해 머지하겠습니다.

궁금하거나 고민이 되는 부분이 있으시다면 언제든 pr 코멘트 또는 dm으로 요청 부탁드립니다.
감사합니다 🙇‍♂️

2024-03-27 11:53 UTC, jinyoungchoi95 commented on src/test/java/chess/domain/board/BoardInitializerTest.java
> +        }
makeBoard를 만들어 for문을 돌리기보다는 assertAll로 각각의 필드를 한라인에서 다 검증하는게 나을 것 같아요. 검증부는 최대한 하드코딩하여 그 값을 명확화하고 최대한 단순하게 로직을 없애어(for문조차도) 무엇을 검증하는지에 대해서 명확화하는 것이 중요해요.

2024-03-27 11:54 UTC, merged