[1,2단계 - 체스] 백호(전호건) 미션 제출합니다.
woowacourse/java-chess pull request #664
Opened 2024-03-21 08:09 UTC by Arachneee

안녕하세요~ 러너덕 🦆 
백호입니다.

객체들의 역할 구분에 신경써서 작성했습니다.

### 고민 사항
- 1. ChessTable의 초기 세팅을 하는 객체가 따로 있는 것이 좋을까요?
초기 세팅이 하드코딩되어 있는 부분이 많아서 ChessTable 의 가독성이 안좋아 진것 같습니다.
하지만 생성자에서 초기 생성을 하는 것이 생성자의 역할인 거 같기도 합니다.
러너덕은 어떻게 생각하시나요?

-2. Controller에서 Command를 어떻게 받아서 처리하는 것이 좋을까요?
Command enum을 만드는 것을 고려해봤는데 Move의 경우 추가 데이터가 있어 어려움이 있었습니다.

2024-03-21 08:57 UTC, Arachneee commented on src/main/java/controller/ChessController.java
> +        }
인덴트가 3이지만 재입력과 반복을 구현하기 위한 최선의 구조입니다.
더 좋은 구조가 있을까요?

2024-03-21 08:57 UTC, Arachneee commented on src/main/java/view/PieceTypeFormat.java
> +    }
질문이 있습니다. 해당 메소드를 다음과 같이 바꿀 수 있는데 어떤 방식이 더 읽기 쉬워 보이시나요?
```java
public static String findFormat(final Piece piece) {
        return Arrays.stream(values())
                .filter(type -> type.piece.equals(piece))
                .findFirst()
                .orElseThrow(() -> new IllegalArgumentException("피스 타입이 없습니다."))
                .format;
    }
```

2024-03-21 13:08 UTC, Arachneee commented on src/main/java/domain/piece/Piece.java
> +}
메소드 순서 컨밴션을 찾아봤는데 추상 메소드에 대한 내용을 찾지 못해서 질문드립니다.
추상 메소드끼리 묶어두는 것이 좋을까요? 아니면 접근제어자의 순서를 따르는 것이 좋을까요?

2024-03-22 17:18 UTC, Deocksoo requested changes
안녕하세요 백호, 리뷰어 러너덕입니다.
객체들이 역할에 맞게 잘 구분되어있고, 기물들이 Piece로 잘 추상화되었네요 👍 
깔끔하게 구현해주신것 같아요.

간단한 코멘트 몇 군데 남겨두었으니, 확인 한 번 부탁드려요~

> ChessTable의 초기 세팅을 하는 객체가 따로 있는 것이 좋을까요?
초기 세팅이 하드코딩되어 있는 부분이 많아서 ChessTable 의 가독성이 안좋아 진것 같습니다.
하지만 생성자에서 초기 생성을 하는 것이 생성자의 역할인 거 같기도 합니다.
러너덕은 어떻게 생각하시나요?

지금은 factory 메서드를 활용하여 ChessBoard에서 생성하고 계시네요 :)
아직은 역할을 분리해야할 만큼 크게 복잡하지 않은 것 같고, 지금 위치도 나쁘지 않아보여요.

> Controller에서 Command를 어떻게 받아서 처리하는 것이 좋을까요?
Command enum을 만드는 것을 고려해봤는데 Move의 경우 추가 데이터가 있어 어려움이 있었습니다.

Enum 말고 객체로 만드는 것은 어떤가요? 적당한 역할을 주어줄 수도 있을것 같은데요~

2024-03-22 17:18 UTC, Deocksoo commented on src/main/java/controller/ChessController.java
> +    private void validateMoveCommend(final List<String> input) {
이 부분은 command를 별도로 분리해내고, 그 안에서 검증하면 어떤가요?
source와 target을 가져오도록 할 수도 있을것같은데요!

2024-03-22 17:18 UTC, Deocksoo commented on src/main/java/domain/ChessBoard.java
> +        validateSameSquare(source, target);
piece를 얻기 전에 해주어도 좋겠네요.

2024-03-22 17:18 UTC, Deocksoo commented on src/main/java/domain/ChessBoard.java
> +        validateTeam(sourcePiece);
pieceSquares.get(source) 과 묶어서 메서드로 추출하면 어떤가요?

2024-03-22 17:18 UTC, Deocksoo commented on src/main/java/domain/ChessBoard.java
> +    private Team team;
현재 움직일 차례의 팀이라는 의미를 조금 더 드러내주면 어떤가요?

2024-03-22 17:18 UTC, Deocksoo commented on src/main/java/domain/ChessBoard.java
> +    private boolean isBlocked(final Square source, final Square target) {
이 부분이 조금 어렵게 느껴지네요.
아마도 나이트는 이 로직에서 blocked에 걸리지 않게 될 것 같은데, 어떻게 그렇게 되나요?
테스트를 통해서 확인할 수도 없으니 기물을 뛰어넘을 수 있다는 사실이 어디에 구현되어있는지 알기가 어려워요.

2024-03-22 17:18 UTC, Deocksoo commented on src/test/java/domain/ChessBoardTest.java
> +    void blockingPiece() {
이 부분은 조금 더 자세히 테스트되면 어떤가요?
source가 어떤 기물인지까지 적어주면 각 기물이 어떤 경우에 막혀서 못 가는지 더 꼼꼼하게 검증해줄 수 있을것같아요.

2024-03-22 17:18 UTC, Deocksoo commented on src/main/java/domain/piece/Knight.java
> +    private static final List<ChessVector> CHESS_VECTORS = List.of(
나이트가 움직일 수 있는 벡터를 표현한 것 같은데, 조금 더 명확한 이름을 지어주는 것은 어떤가요?

2024-03-22 17:18 UTC, Deocksoo commented on src/main/java/domain/Square.java
> +    public ChessVector calculateVector(final Square other) {
중요한 도메인 로직이니, 테스트가 있으면 좋겠네요

2024-03-22 17:18 UTC, Deocksoo commented on src/main/java/domain/Square.java
> +    public Square next(final ChessVector chessVector) {
Ditto

2024-03-22 17:18 UTC, Deocksoo commented on src/main/java/domain/piece/Piece.java
> +    public final boolean canNotAttack(final Square source, final Square target) {
abstract로 만들면 어떤가요?
Pawn에서 다르게 구현하고 있는 부분이 굉장히 중요할 것 같은데,
Pawn을 확인하기 전까지는 move와 attack이 다를 것이 없어보여요.
해당 부분을 읽어보기 전까지는 그 사실을 놓칠수도 있겠네요.

2024-03-22 17:18 UTC, Deocksoo commented on src/main/java/controller/ChessController.java
> +        }
이 부분은 비교적 중요한 부분이 아니고, 
커맨드 패턴까지 이용하여 구조화할 필요는 없을것 같네요 :) 
이정도로 구현해도 크게 문제되지 않을 것 같아요.

2024-03-23 07:20 UTC, Arachneee commented on src/main/java/controller/ChessController.java
> +    private void validateMoveCommend(final List<String> input) {
Command를 객체화 해보겠습니다.

2024-03-23 07:21 UTC, Arachneee commented on src/main/java/domain/ChessBoard.java
> +        validateTeam(sourcePiece);
검증 로직을 간소화 해보겠습니다.

2024-03-23 07:21 UTC, Arachneee commented on src/main/java/domain/ChessBoard.java
> +    private Team team;
생각하지 못했는데 currentTeam으로 바꾸어도 괜찮겠네요.

2024-03-23 07:27 UTC, Arachneee commented on src/main/java/domain/ChessBoard.java
> +    private boolean isBlocked(final Square source, final Square target) {
target 좌표에서 source 좌표를 뺀 벡터를 scaleDown하면 단위방향이 나옵니다. 
ex) (0,6) -> (0,1), (5,5) -> (1,1), (1,2) -> (1,2)
나이트의 경우 (1,2) 는 그데로 (1,2) 이므로 중간 기물을 뛰어넘어 확인하게됩니다.

테스트 코드를 추가하여 표현해보겠습니다.

2024-03-23 07:30 UTC, Arachneee commented on src/test/java/domain/ChessBoardTest.java
> +    void blockingPiece() {
테스트 코드를 더 추가해보겠습니다.

2024-03-23 07:45 UTC, Arachneee commented on src/main/java/domain/piece/Knight.java
> +    private static final List<ChessVector> CHESS_VECTORS = List.of(
MOVABLE_VECTORS 가 명확한 것 같습니다!

2024-03-23 07:47 UTC, Arachneee commented on src/main/java/domain/piece/Piece.java
> +    public final boolean canNotAttack(final Square source, final Square target) {
추상클래스보다 구현체를 먼저 보게 되므로 구현체 중심으로 설계를 하는 것이 좋겠네요.

2024-03-23 09:32 UTC, Deocksoo commented on src/main/java/domain/piece/Piece.java
> +}
이 부분은 따로 컨벤션이 있는 것은 아닐것같고, 크루만의 기준이 있으면 될것같아요.
어떻게 정리하는 것이 보기 편할것같나요?

2024-03-23 09:33 UTC, Deocksoo commented on src/main/java/view/PieceTypeFormat.java
> +    }
map 을 사용하는 것이 조금 더 일관성있어보이네요.

2024-03-23 16:05 UTC, Arachneee commented
안녕하세요 러너덕!

부족한 테스트 코드를 더 추가했습니다!!

그리고 Command를 객체화 시켰습니다.
Command를 객체로 구현했는데 어떤 Command인지 확인하기 위해 instanceOf를 사용하거나 isStart() 등의 메소드를 인터페이스에 추가해야했습니다. 
이렇게 각 class를 확인하는 기능이 필요하다면 인터페이스를 사용하는 의미가 없고 객체화의 의미가 없다고 판단했습니다.
그래서 Command의 class를 확인하지 않고 구현하기 위해 Command에 ChessBoard를 전달하여 필요한 기능을 할 수 있게했습니다.

현재는 MoveCommand에서만 ChessBoard를 사용하고 있지만 나중에 DB를 연결하면 StartCommand에는 DB 로딩 명령, EndCommand에는 DB 저장 명령을 수행할 수 있을 것 같습니다.

제가 고민되는 사항은 Command의 run 메소드 실행후 EndCommand만 false를 반환하고 나머지는 true를 반환하게 하여 동작을 제어하고 있습니다.

run 메소드가 2가지의 일을 하고 있다고 볼 수 도 있을 것 같은데 러너덕은 어떻게 생각하시나요?

2024-03-24 01:55 UTC, Arachneee commented on src/main/java/domain/piece/Piece.java
> +}
제가 추상클래스를 본다고 생각해봤을 때 어떤 추상메소드가 있어 Override 해야하는지 한눈에 파악하는 것이 좋을 것 같습니다.
그래서 추상메소드를 생성자 다음에 몰아서 위치시킬려고 합니다.

2024-03-24 04:46 UTC, Arachneee commented
안녕하세요 러너덕!

부족한 테스트 코드를 더 추가했습니다!!

그리고 Command를 객체화 시켰습니다.
Command를 객체로 구현했는데 어떤 Command인지 확인하기 위해 instanceOf를 사용하거나 isStart() 등의 메소드를 인터페이스에 추가해야했습니다. 
이렇게 각 class를 확인하는 기능이 필요하다면 인터페이스를 사용하는 의미가 없고 객체화의 의미가 없다고 판단했습니다.
그래서 Command의 class를 확인하지 않고 구현하기 위해 Command에 ChessGame을 전달하여 필요한 기능을 할 수 있게했습니다.

Game 객체를 통해 Game의 상태를 관리할 수 있는 기능도 추가했습니다.

2024-03-24 06:28 UTC, Deocksoo commented on src/main/java/domain/ChessBoard.java
> +    private void validateMove(final Square source, final Square target) {
👍

2024-03-24 06:28 UTC, Deocksoo commented on src/main/java/domain/ChessBoard.java
> +    private boolean isBlocked(final Square source, final Square target) {
아하 이해했어요. 나이트도 다른 기물들과 마찬가지로 진행하려는 벡터의 시작과 끝점 사이에 있는 기물은 뛰어넘지 못하는군요. 
다만 (1, 2) 의 시작점과 끝점 사이에 기물이 놓일 수가 없어서 원하는 위치는 어느 곳이든 이동할 수 있게 되겠네요. 👍

2024-03-24 06:33 UTC, Deocksoo commented on src/test/java/domain/ChessBoardTest.java
> +class ChessBoardTest {
👍  테스트가 훨씬 자세해졌네요

2024-03-24 06:33 UTC, Deocksoo commented on src/main/java/domain/piece/Piece.java
> +    public final boolean canNotAttack(final Square source, final Square target) {
의도대로 잘 수정해주셨네요.
다만 코멘트 드린 의도를 약간 오해하셨을수도 있을것같아 첨언하면,
구조를 파악할 때는 구현체보다 추상클래스를 먼저 봐요.
추상클래스만 보고도 '아, 이 부분이 확장될 가능성이 있는 메서드구나' 하는 부분을 알 수 있도록 하자는 의미로 드린 코멘트였어요.

2024-03-24 13:11 UTC, Deocksoo approved these changes
안녕하세요 백호,
테스트도 꼼꼼하게 추가해주셨고, 리뷰 깔끔하게 잘 반영해주셨네요 👍 
다음 단계 계속 진행해주시면 될것같아요.
간단한 코멘트 하나 추가로 남겨두었으니, 나중에 확인 한 번 부탁드려요.

2024-03-24 13:11 UTC, Deocksoo commented on src/main/java/domain/game/command/ChessCommand.java
> +public interface ChessCommand {
command를 domain으로 분리하셨군요.
이 부분은 도메인이라고 보기에는 핵심적인 체스 게임 도메인 규칙과 관련이 적은것 같기도 하고, 그렇다고 view로 보기에는 어느정도 게임과 관련된 동작이 들어가게 되어서 이렇게 두신 것 같아요.

그러면 controller와 domain 사이에서 동작을 연결해주는 layer를 만들어 구분해보면 어떤가요?

2024-03-24 13:13 UTC, Deocksoo commented on src/main/java/domain/piece/Piece.java
> +    public abstract boolean equals(final Object o);
이 equals와 hashCode는 꼭 필요한 메서드인가요?

2024-03-24 13:14 UTC, merged

2024-03-24 13:43 UTC, Arachneee commented on src/main/java/domain/game/command/ChessCommand.java
> +public interface ChessCommand {
controller와 domain을 연결하는 layer는 service layer가 될 것이라 생각합니다. 패키지를 구분해보겠습니다.

2024-03-24 13:49 UTC, Arachneee commented on src/main/java/domain/piece/Piece.java
> +    public abstract boolean equals(final Object o);
View에서 Piece의 equals를 통해 기물의 출력형식을 매핑하고 있습니다. View때문에 생긴 메소드라 생각이 됩니다. 
하지만 다르게 보면 Piece를 구현하는 객체를 VO로 만들기 위해 꼭 필요하다고 생각합니다.
같은 Black Pawn인데 동등성이 보장되어야 하지 않을까요?

해당 방법을 사용하지 않고 View의 출력형식을 매핑하기 위해서는 PieceType같은 enum 클래스를 새로 만들어 PieceType과 Team 데이터를 전달해야합니다. 
이 방식을 사용하게 되면 Piece를 구현하는 구현체가 추가될 때마다 PieceType도 추가되어야합니다. 
그래서 유지보수에 안좋다고 생각합니다.