[1, 2단계 - 체스] 클로버(이은정) 미션 제출합니다.
woowacourse/java-chess pull request #673
Opened 2024-03-21 08:19 UTC by eunjungL

안녕하세요, 안돌! 클로버입니다.
이번 체스 미션동안 리뷰 잘 부탁드립니다. 🙇 

## 고민이 되는 부분
이번에 각 기물이 종류별로 다른 움직임 규칙을 가지고 있어 전략 패턴을 적용했습니다. `MoveStrategy`를 만들고 `check()`이라는 메서드를 각 기물이 본인의 규칙에 맞게 오버라이드 할 수 있도록 구조를 설계했습니다. 

이 부분을 진행하면서 `check()`의 매개변수 중에 `colorType`이라는 매개변수가 `PawnMoveStrategy`에서만 사용되고 다른 움직임 전략들에서는 사용하지 않는 형태로 코드가 작성됐습니다. 하나의 구현체에서 사용하기 위해 `colorType`을 다른 구현체에서도 갖게 강제하는 것이 비효율적이라 느껴져 개선하고 싶었는데 어떻게 개선할지 방법을 찾지 못했습니다.

찾았던 방법 중 하나는 추상 클래스로 변경하여 다형성을 이용해 하나만 구현할 수 있도록 만드는 방법이었는데 추상 클래스와 인터페이스 중 선택할 때 어떤 기준을 따라야하는지 아직 배우고 있는 중이 확신이 없어 한 번 사용해봤던 인터페이스 구현을 사용했습니다.
1. 인터페이스의 메서드 중 하나의 구현체에서만 사용하기 위한 매개변수는 비효율적이므로 개선돼야 하는 부분이라고 생각하는데 제 생각이 맞는지 궁금합니다.
2. 개선 방법으로 추상 클래스를 고려해볼 수 있다고 생각 중인데, 상속은 부모 클래스의 변경이 자식 클래스에 큰 영향을 주고 캡슐화가 깨질 수 있기 때문에 제일 마지막 방법으로 고려해야 한다고 공부한 적이 있습니다. 하지만 현재 상황에서는 추상 클래스 내부에 추상 메서드만 들어갈 것이기 때문에 위의 단점이 적용되지 않는다고 생각 중입니다. 위의 생각들이 맞는지, 아니라면 어떻게 개선해볼 수 있는지 조언을 듣고싶습니다.

체스 게임의 구현이 많이 복잡하고 시간이 부족하다고 느껴져서 코드가 정돈되지 않은 부분이 있을 것 같습니다.
리뷰를 진행하면서 많이 개선할 수 있도록 노력하겠습니다. 😢 
감사합니다. 🙇

2024-03-21 14:36 UTC, andole98 commented
> 인터페이스의 메서드 중 하나의 구현체에서만 사용하기 위한 매개변수는 비효율적이므로 개선돼야 하는 부분이라고 생각

저도 그렇게 생각합니다. 하나만 뭔가가 다르다면 해당 인터페이스와 관련이 없다고 봐야겠죠. (뭔가 다른 하나는 인터페이스와는 다른 종류이다)

> 개선 방법으로 추상 클래스를 고려해볼 수 있다고 생각 중~~~

추상클래스를 이용한다고 해서 개선되지 않을것 같다고 생각해요. 혹시 코드로 알려줄 수 있나요? show me the code

++) 정답은 없다고 생각해요. 이런이런점에서 더 나은 방법은 있겠지만, "이게 답이다"라고 할만한 명제는 "정답은 없다"입니다.

결국 `제 생각이 맞는지`은 `현재 상황에서 다른 무엇과 어떤 점에서 더 나은지`를 판단해야 합니다.

2024-03-21 17:16 UTC, andole98 requested changes
안녕하세요 리뷰어 안돌입니다.

Square와 그 캐시, 전략패턴 등이 인상적이네요. 잘 구현하셨어요.

몇가지 코멘트 남겼습니다. 각 Piece의 역할에 대해 조금더 생각해보시면 좋겠네요.

2024-03-21 17:16 UTC, andole98 commented on README.md
> +# 기능 구현 목록
도메인 / 개념별로 기능을 정리하셨군요. 좋습니다.

2024-03-21 17:16 UTC, andole98 commented on src/main/java/chess/ChessGame.java
> +        if (!inputView.isStartCommand(progressCommand)) {
inputView가 command 종류를 판별하는게 조금 어색하네요. 게임이 커맨드에 대해 반응하는게 덜 어색한것 같아요.

2024-03-21 17:16 UTC, andole98 commented on src/main/java/chess/ChessGame.java
> +    private Board initBoard() {
이 메서드는 inline하지 않는게 더 나을것 같아요.

`initBoard`만 하고 있나요? 출력과 묶인 이유를 잘 모르겠어요.

2024-03-21 17:16 UTC, andole98 commented on src/main/java/chess/domain/board/Board.java
> +
이부분은 특정 말 (Pawn) 맥락이 새어들었네요. 다른 부분은 Piece로 처리되는데, Pawn에 관한 제어가 Pawn이 아닌 board에 있는것이 어색합니다.

2024-03-21 17:16 UTC, andole98 commented on src/main/java/chess/domain/board/Board.java
> +    private boolean needFindPathCondition(Square source, Piece sourcePiece) {
Pawn의 코멘트와 같음

2024-03-21 17:16 UTC, andole98 commented on src/main/java/chess/domain/board/Board.java
> +    private final Map<Square, Piece> board;
가로세로 좌표를 담당하느 Square가 있으니 구조가 간단하군요

2024-03-21 17:16 UTC, andole98 commented on src/main/java/chess/domain/board/BoardFactory.java
> +    private Piece makePiece(Rank rank, File file, Piece piece) {
최초 생성은 다이나믹한 (if / for 등 제어문으로 처리)것도 좋지만 고정값이니 value(하드코딩)으로 해도 나쁘지 않을것 같아요. 가독성 면에서 더 나을것 같고요.

2024-03-21 17:16 UTC, andole98 commented on src/main/java/chess/domain/board/Turn.java
> +public class Turn {
홀짝으로 블랙/화이트를 나눴군요 맘에 드는 객체입니다

2024-03-21 17:16 UTC, andole98 commented on src/main/java/chess/domain/board/Turn.java
> +    public void update() {
update보다는 next나 take 정도 어떤가요?

2024-03-21 17:16 UTC, andole98 commented on src/main/java/chess/domain/piece/ColorType.java
> +    EMPTY,
이건 Color가 아닌것 같은데요? 체스판 한 지점이 가질수 있는 상태인것 같아요.

블랙 말이 있거나 화이트 말이 있거나 비어있거나.

2024-03-21 17:16 UTC, andole98 commented on src/main/java/chess/domain/piece/PieceType.java
> +public enum PieceType {
아주 좋은 전략 패턴이네요~

2024-03-21 17:16 UTC, andole98 commented on src/main/java/chess/domain/position/File.java
> +public enum File {
이름에 약간 의문이 드네요. File이 `수직` 뉘앙스가 있긴 하지만 더 관용적인 file 파일이 먼저 떠오르네요.

2024-03-21 17:16 UTC, andole98 commented on src/main/java/chess/domain/position/Square.java
> +    private static final Map<String, Square> pool = Arrays.stream(Rank.values())
로직이 적잖이 있는 편인데, BoardFactory처럼 역할을 담당해줄 객체가 있으면 좋겠네요.

2024-03-21 17:16 UTC, andole98 commented on src/main/java/chess/domain/position/Square.java
> +    private static String toKey(File file, Rank rank) {
적절한 cacheKey를 만드셨네요~

2024-03-21 17:16 UTC, andole98 commented on src/main/java/chess/domain/position/Square.java
> +    public static Square from(String command) {
command가 만약 객체라면, `charAt` 과 같은 접근은 필요 없어질것 같네요.

2024-03-21 17:16 UTC, andole98 commented on src/main/java/chess/domain/position/Square.java
> +    public boolean isPawnStartSquare() {
Pawn의 맥락이 번지는것 같아요. Pawn과 관련한것은 Pawn 객체에서만 다루게 할 수 없을까요?

2024-03-21 17:16 UTC, andole98 commented on src/main/java/chess/domain/strategy/MoveStrategy.java
> +    // TODO: 폰만을 위한 인자인 colorType을 제거할 수 있는 방안 생각해보기
인터페이스 계층이 두개일수도..?

Pawn -> PawnStrategy -> MoveStrategy

2024-03-21 17:16 UTC, andole98 commented on src/main/java/chess/domain/strategy/MoveStrategy.java
> +    boolean check(Square source, Square destination, ColorType colorType);
MoveStrategy.check가 어색한것 같아요. 이동전략.check보다는 이동전략.apply / 이동전략.move 등등이 어울리는것 같아요.

지금처럼 메서드 자체가 중요한 경우는 이름을 바꿔보면 어떤가요? `MoveCommandCheckStrategy.check()` 이런 느낌??

2024-03-21 17:16 UTC, andole98 commented on src/main/java/chess/domain/piece/PieceType.java
> +    EMPTY(new PawnMoveStrategy()),
Empty도 PawnMoveStrategy인가요?

2024-03-21 17:16 UTC, andole98 commented on src/main/java/chess/domain/strategy/PawnMoveStrategy.java
> +public class PawnMoveStrategy implements MoveStrategy {
인터페이스를 구현한다고 하더라도, 인스턴스 필드나 생성자를 다르게 갖출수도 있습니다.

2024-03-21 17:16 UTC, andole98 commented on src/main/java/chess/dto/BoardOutput.java
> +package chess.dto;
이 친구는 domain에서 만드는 객체인것 같아요. dto이긴 하지만 domain에 속하는것 같은데 클로버의 생각은 어떤가요?

dto끼리 모여있으면 어떤게 좋길래 패키지로 구성했을까요?

2024-03-21 17:16 UTC, andole98 commented on src/main/java/chess/domain/piece/Piece.java
> +    public boolean isSameType(PieceType pieceType) {
이 메서드는 사실상 instanceof 역할을 하는것 같아요. 다형성 / 전략패턴이 완전하지 못하다는 느낌입니다. isSameType처럼 특정 타입을 구분하려는 니즈는, 개별 타입들이 본인의 역할을 미처 다 하지 못하기 때문에 다른 객체에서 처리하고 있기 때문인것 같아요.

2024-03-21 17:16 UTC, andole98 commented on src/main/java/chess/domain/position/Rank.java
> +
엄하게 공백이 있네요

2024-03-22 15:33 UTC, andole98 commented on src/main/java/chess/domain/position/File.java
> +public enum File {
요거 찾아보니 File이 체스 관용어더군요.... 제가 무식한걸루

2024-03-23 13:29 UTC, eunjungL reviewed
안녕하세요, 안돌! 클로버입니다.
1단계에서 세세한 리뷰를 남겨주셔서 감사했습니다. 🙇 

제가 질문에 남겼던 부분에서 오류가 있었는데요,
> 추상클래스를 이용해서 개선할 수 있다고 생각

이 부분이 미션을 진행하면서 찾아봤을 때 다형성을 활용하면 하나의 메서드만 오버라이드 해도 된다는 글을 봐서였는데 실제로 코드를 작성해보니 잘못된 정보였음을 알게됐습니다. 😢 하지만 남겨주신 답변과 다른 리뷰를 토대로 고민했을 때 위의 질문이 해결됐고 많이 배울 수 있었습니다.

추가로 리뷰를 반영하면서 생겼던 궁금증에 대해서 질문을 남겨두었습니다. 🙇 

남은 기간 동안도 잘 부탁드립니다!

2024-03-23 13:29 UTC, eunjungL commented on src/main/java/chess/ChessGame.java
> +        if (!inputView.isStartCommand(progressCommand)) {
1. command의 종류를 `InputView`에서 상수로 관리하고 있어 밖으로 상수를 빼지 않으려는 이유
2. `command`는 입력에 대한 검증이니까 `InputView`의 책임이라는 생각

위의 두 가지 이유로 메서드를 분리했었는데 리뷰를 본 후 다시 생각해보니 커맨드에 대한 검증은 게임이 직접 하는게 더 자연스러운 것 같습니다. 반영 완료했습니다. 감사합니다! 👍

2024-03-23 13:29 UTC, eunjungL commented on src/main/java/chess/ChessGame.java
> +    private Board initBoard() {
코드를 작성할 당시에는 `Board`를 초기화하고 첫 모습을 출력해준다는 의미에서 하나의 메서드로 묶었습니다. 하지만 생성과 출력은 각자 다른 책임이기 때문에 하나로 묶이지 않는게 맞는 것 같습니다.
분리 완료했습니다. 좋은 의견 감사합니다! 🙇

2024-03-23 13:29 UTC, eunjungL commented on src/main/java/chess/domain/board/Board.java
> +
폰 로직이 복잡해 코드를 작성하면서 로직이 새어나간 것을 모르고 있었는데 짚어주셔서 감사합니다. 🙇
`PawnMoveStrategy`가 직접 확인할 수 있도록 수정 완료했습니다!

2024-03-23 13:29 UTC, eunjungL commented on src/main/java/chess/domain/board/Board.java
> +    private boolean needFindPathCondition(Square source, Piece sourcePiece) {
해당 부분 역시 `Pawn`, `Bishop`, `Rook`, `Queen`에서 처리할 수 있도록 이동했습니다. 
이동하는 과정에서 중복 코드가 발생했고 이를 해결하기 위해 `BlockedPathFindStrategy`라는 새로운 이동 검증 전략을 만들었습니다. 이 검증 전략은 필요한 기물의 전략에만 선택적으로 포함될 수 있도록 설계했습니다.
좋은 의견 감사합니다! 🙇

2024-03-23 13:29 UTC, eunjungL commented on src/main/java/chess/domain/board/Turn.java
> +    public void update() {
다음 턴으로 넘어가는 것을 명시해줘야 하니 `next`가 `update`보다 훨씬 나은 것 같습니다!
좋은 네이밍 추천 감사합니다 👍 👍

2024-03-23 13:29 UTC, eunjungL commented on src/main/java/chess/domain/piece/Piece.java
> +    public boolean isSameType(PieceType pieceType) {
`개별 타입이 본인의 역할을 미쳐 다 하지 못했다.`는 부분을 놓치고 있었던 것 같습니다. 위에 남겨주신 리뷰를 토대로 스스로 처리할 수 있게 변경하였더니 해당 메서드도 더 이상 사용할 필요가 없어져 제거하였습니다.
놓치고 있던 부분을 짚어주셔서 감사합니다! 🙇

2024-03-23 13:29 UTC, eunjungL commented on src/main/java/chess/domain/piece/PieceType.java
> +    EMPTY(new PawnMoveStrategy()),
`Empty`는 늘 false를 리턴하도록 하는 전략을 따로 만들어줬어야 하는데 비어있는 칸을 검증하는 로직이 `Board`에서도 행해지고 있어 놓치고 있었습니다. 적절한 전략을 갖도록 수정 완료했습니다!

2024-03-23 13:29 UTC, eunjungL commented on src/main/java/chess/domain/position/Rank.java
> +
수정 완료했습니다!

2024-03-23 13:29 UTC, eunjungL commented on src/main/java/chess/domain/position/Square.java
> +    public boolean isPawnStartSquare() {
폰이 복잡한 조건을 갖고 있어 구현하다 역할이 흩어지고 있는지도 몰랐는데 짚어주셔서 감사합니다. `Square`에게는 주어진 랭크와 동일 선상에 있는지 묻는 메시지를 보내게 하고 `PawnMoveStrategy`에서 직접 확인 후 처리할 수 있도록 변경 완료했습니다! 👍

2024-03-23 13:29 UTC, eunjungL commented on src/main/java/chess/domain/board/BoardFactory.java
> +    private Piece makePiece(Rank rank, File file, Piece piece) {
말씀해주신 것처럼 고정 값이라 정해진 순서가 있으니 순서를 미리 만들어두는게 더 나을 것 같단 생각이 들었습니다. 정해진 순서를 상수로 만들어 if문의 수를 줄이고 생성될 수 있도록 코드 수정 완료했습니다. 👍

2024-03-23 13:29 UTC, eunjungL commented on src/main/java/chess/domain/position/File.java
> +public enum File {
저도 File이 체스 용어인지 이번에 진행하면서 처음 알았습니다. 😄 말씀해주신 것처럼 `File`의 다른 뜻이 생각나기도해서 `ChessFile`로 이름 변경을 고려했으나 이미 Chess 패키지 내부에 있기도하고 다른 도메인(`Rank`, `Board` 등)도 앞에 prefix가 붙어있지 않아 기존의 이름을 그대로 가져가기로 했습니다!

2024-03-23 13:29 UTC, eunjungL commented on src/main/java/chess/domain/position/Square.java
> +    private static final Map<String, Square> pool = Arrays.stream(Rank.values())
다른 클래스로 분리를 시도했는데 걸리는 부분이 생겨 클래스 내부에 생성을 담당해주는 메서드로 분리했습니다.

하나의 객체만 만들어두고 계속해서 꺼내 쓰겠다는 목적으로 캐싱을 진행했기 때문에 새로운 객체를 만드는 기본 생성자는 `private`으로 막혀있어야 한다는 생각이 있습니다. 하지만 클래스를 분리하면 기본 생성자를 `public`으로 열어야 하고 `toKey`와 같은 내부 메서드도 함께 `public`으로 열리게 되는데 캡슐화가 깨진다는 느낌이 들었고 지금과 같은 구조로 리팩토링을 진행했습니다.
하지만 메서드로 분리하고나니 생성을 위한 기능이 많아져 말씀해주신 것처럼 담당 객체가 필요하다는 느낌도 들었습니다.

이런 상황에서는 트레이드 오프가 되는 것 같은데, 안돌이라면 어떤 방식을 선택할지 의견이 궁금합니다!

2024-03-23 13:29 UTC, eunjungL commented on src/main/java/chess/domain/position/Square.java
> +    public static Square from(String command) {
말씀해주신 것처럼 `charAt`과 같은 인덱스로 접근되는 부분이 불안하게 느껴졌는데 좋은 의견 감사합니다!
`SquareCreateCommand`라는 dto를 만들어서 반영 완료했습니다. 🙇

2024-03-23 13:29 UTC, eunjungL commented on src/main/java/chess/domain/strategy/MoveStrategy.java
> +    // TODO: 폰만을 위한 인자인 colorType을 제거할 수 있는 방안 생각해보기
리뷰를 보고 계층 분리에 대해서 한 번 더 고민해봤는데 다른 리뷰를 반영하는 과정에서 인자의 `colorType`이 자연스레 제거되고 모두가 공유하는 `Board`가 생겨 해결이 완료됐습니다!
주신 힌트를 토대로 앞으로 프로그래밍을 할 때 하나만을 위한 인자가 생겼을 때 계층을 분리하는 방법에 대해서 고려해볼 수 있을 것 같습니다. 힌트 감사합니다 🙇

2024-03-23 13:29 UTC, eunjungL commented on src/main/java/chess/domain/strategy/MoveStrategy.java
> +    boolean check(Square source, Square destination, ColorType colorType);
`움직임 전략이 움직일 수 있는지 여부를 검증해준다.`라는 의미에서 `check`를 사용했는데요, 어색하게 보일 수도 있다는 것을 리뷰를 통해 깨달았습니다. 
가능 여부를 `check` 해주는 로직이므로 메서드 명은 유지하고 전략의 이름을 변경했습니다. 체스에서 기물이 움직일 수 있는 경로를 `legal move`라는 용어로 사용한다고 하여서 `LegalMoveCheckStrategy`로 변경했습니다. 
짚어주셔서 감사합니다! 👍 👍

2024-03-23 13:29 UTC, eunjungL commented on src/main/java/chess/domain/strategy/PawnMoveStrategy.java
> +public class PawnMoveStrategy implements MoveStrategy {
말씀해주신 것 참고해서 필요한 전략들만 `BlockedPathFindStrategy`를 컴포지션으로 사용할 수 있게 활용해봤습니다.
좋은 인사이트 감사합니다! 🙇

2024-03-23 13:29 UTC, eunjungL commented on src/main/java/chess/dto/BoardOutput.java
> +package chess.dto;
domain 패키지에는 도메인 객체만 들어가야 한다는 편견이 있었던 것 같습니다. 
찾아보니 여러 패키지에서 공유된다면 `dto` 패키지를 만들어 거기에서 관리하고, 사용되는 곳이 특정돼 있으면 해당 도메인 패키지에 함께 들어가는 기준으로 분리할 수 있을 것 같습니다.
말씀해주신 것 처럼 해당 도메인에 들어간다면 어디서 사용하는 dto인지 바로 판단이 가능해 가독성이 더 좋아질 것 같습니다!
좋은 인사이트 감사합니다 👍

2024-03-23 13:29 UTC, eunjungL commented on src/main/java/chess/domain/piece/ColorType.java
> +    EMPTY,
체스판이 비어있을 때 사용되는 `PieceType.EMPTY`에 대응하기 위해 추가된 상수인데요, 말씀해주신 것처럼 color라는 말과는 잘 어울리지 않는 것 같습니다.
따라서 Piece의 상태를 나타낼 때 `BLACK 진영`, `WHITE 진영`, `빈 진영`을 표현하기 위해 `CampType`으로 클래스 명을 변경하는 쪽으로 개선해봤습니다.

2024-03-24 07:34 UTC, andole98 approved these changes
각 piece에 대한 문제를 잘 해결하신것 같네요 :+1:

인터페이스를 잘 다루셨고 그 결과로 중복이 줄어들고 역할이 잘 정리된것 같네요.

몇가지 소소한 코멘트를 남겼습니다. 다음 미션 진행전에 살펴보시고, 반영할것은 반영해주세요.

다음 스텝에서 보아요~

2024-03-24 07:34 UTC, andole98 commented on src/main/java/chess/domain/piece/Piece.java
> +    public boolean isSameType(String pieceViewName) {
파라미터 String pieceViewName은 사실상 뷰 로직을 의식하고 있다고 말하고 있네요.

뷰에서 도메인 객체인 pieceType으로 구별하도록 하면 어떤가요?

```java
// view
if (somePiece.getPieceType() == PiceType.KING) {
        ...        
}
// 또는
String pieceName = pieceNameFinder.find(somePiece.getPieceType());
```

2024-03-24 07:34 UTC, andole98 commented on src/main/java/chess/domain/strategy/LegalMoveCheckStrategy.java
> +package chess.domain.strategy;
지금 레벨에선 아주 중요하진 않지만.. 적극적으로 패키징을 하신것을 보고 코멘트 남깁니다

이 패키지의 의미에 대해서 생각해보시면 좋겠네요.

체스말에 대한 strategy가 chess.domain.strategy에 들어왔어요.

strategy 패키지는 무엇을 의미하나요? 예전 dto끼리 패키지 묶으면 무엇이 좋으냐고 질문한 것과 유사하네요. 종류별로 묶으면 무엇이 좋은가요? 

혹시 체스 추가룰(캐스팅 등)에 대한 전략도 추가된다고 하면 여기에 넣으실건가요? 체스온라인게임이 생기고 플레이어를 매칭하는 전략도 추가된다면 여기에 넣나요?

2024-03-24 07:34 UTC, andole98 commented on src/main/java/chess/domain/strategy/BlockedPathCheckStrategy.java
> +public class BlockedPathCheckStrategy implements LegalMoveCheckStrategy {
이 객체가 많은 중복을 줄여주는군요 :+1:

2024-03-24 07:34 UTC, andole98 commented on src/main/java/chess/domain/Direction.java
> +
Direction은 아주 순수한 도메인인줄 알았는데 아니네요.

순수한 -> 다른 의존성이 없음. 나머지 객체들이 Direction을 이용해서 역할을 수행함.

2024-03-24 07:34 UTC, andole98 commented on src/main/java/chess/view/PieceView.java
> +public enum PieceView {
Piece에서 남긴 코멘트와 유사하네요. pieceType과의 매핑이 있으면 좋을것 같아요.

2024-03-24 07:34 UTC, andole98 commented on src/main/java/chess/view/PieceView.java
> +    public static String toView(Piece piece) {
필드명 blackView / whiteView 포함해서`toView`는 어색한 이름같아요.

view는 타입또는 종류 인가요? `장기말뷰.뷰로` 보다는 `장기말이름.찾아줘` 정도가 어떤지? `PieceName.find`

enum element를 찾아내고 그에 해당하는 값을 찾으면 어떤가요?

2024-03-24 07:34 UTC, andole98 commented on src/test/java/chess/domain/board/BoardFactoryTest.java
> +    private Map<Square, Piece> createExpectedBoard() {
사실상 production코드와 다를게 없을것 같아요. 테스트에서는 더 표현력 있게 해보면 좋을것 같기도 합니다.

테스트하고 싶은 내용은 "초기체스판 규칙대로 잘 만들었냐" 이므로, 이렇게 보는게 더 의미있고 가독성 있을것 같네요.

```java
@Test
void 손코딩어렵다() {
    Map<Squre, Piece> expected = new HashMap<Squre, Piece>();
    expected.add(new Squre(..), new Piece(..));
    expected.add(new Squre(..), new Piece(..));
    expected.add(new Squre(..), new Piece(..));
    expected.add(new Squre(..), new Piece(..));
    expected.add(new Squre(..), new Piece(..));
    
    ..
    
    assertThat(actual).usingRecursiveComparison().isEqualTo(expected);
}


```

2024-03-24 07:34 UTC, andole98 commented on src/test/java/chess/domain/piece/PieceTypeTest.java
> +    @Nested
Nested도 좋지만 테스트 본문의 양이 매우 많네요. 테스트클래스를 나누는건 어떨까 합니다.

pieceType은 사실상 Pawn -> PawnStrategy 매핑을 담당하지, 실제 로직은 PawnStrategy에 있으니까요.

`PawnStrategyTest` 로 따로 나온다면 관심대상에 대한것만 나올것 같아요. 테스트 본문이 줄어들고 가독성 & 유지보수가 더 나을것 같아요.

2024-03-24 07:34 UTC, merged

2024-03-24 07:39 UTC, andole98 commented on src/main/java/chess/domain/position/Square.java
> +    private static final Map<String, Square> pool = Arrays.stream(Rank.values())
생성자는 막아두고 미리 풀을 만들어야 하는 상황이라면, innerClass 등을 활용해볼것을 고려할것 같네요.

```java
public class Square {
  private Squre() {
  }
...
  public static class SqurePoolCreator {
      ....
  }
}
```

이렇게 하면 생성자 private 가능 / 로직 분리 가능 / 테스트 가능 모두 챙길수 있겠네요.

2024-03-25 06:15 UTC, eunjungL reviewed
안녕하세요, 안돌! 클로버입니다.
1단계에서 자세하고 상세한 리뷰 감사했습니다.

말씀해주신 부분들은 2단계 시작 전에 반영 완료했습니다.
또한 답변해주신 이너 클래스에 대한 부분도 추가적으로 공부 진행하도록 하겠습니다.

2단계도 잘 부탁드립니다.
감사합니다! 🙇

2024-03-25 06:15 UTC, eunjungL commented on src/main/java/chess/domain/Direction.java
> +
원래는 `Direction`이 `nextSquare`를 만들지 않고 `Square`에게 해당 책임이 있었는데요, `Direction`에게 해당하는 방향으로 나아가는 다음 위치를 알려주라는 역할을 부여해 `Square`에 대한 의존이 생겼습니다. 
도메인의 순수성에 대해서 고려해본 적이 없는데 좀 더 공부해보도록 하겠습니다. 🙇

2024-03-25 06:15 UTC, eunjungL commented on src/main/java/chess/domain/piece/Piece.java
> +    public boolean isSameType(String pieceViewName) {
말씀해주신 것처럼 도메인이 뷰를 위한 로직을 가지고 있는게 맘에 들지 않았는데요, 프로그래밍 요구사항이었던 `getter`를 사용하지 않는다를 지키기 위해 무리해서 구조를 짰던 것 같습니다. 하지만 도메인이 억지로 뷰 로직을 갖게 되는 것이 필요에 따른 `getter` 사용보다 더 안좋은 구조라고 느껴졌습니다.
반영해서 수정하도록 하겠습니다. 좋은 의견 감사합니다 👍

2024-03-25 06:15 UTC, eunjungL commented on src/main/java/chess/domain/strategy/LegalMoveCheckStrategy.java
> +package chess.domain.strategy;
도메인과 관련된 상태로 묶는 것이 더 좋은 패키징인걸 배웠음에도 strategy 쪽을 또 한번 놓쳤네요. 짚어주셔서 감사합니다. 🙇 
각 도메인과 관련된 클래스는 도메인 패키지에 넣는 것이 해당 클래스의 목적을 파악하기에도 용이하고 수정 사항이 생겼을 때 찾아가기도 훨씬 수월할 것 같습니다.
종류별로 묶기보다 도메인 별로 묶는 습관을 들여보도록 하겠습니다. 좋은 인사이트 감사합니다! 👍

2024-03-25 06:15 UTC, eunjungL commented on src/main/java/chess/view/PieceView.java
> +public enum PieceView {
`Piece`에 `pieceType`을 가져오는 getter를 만들어 사용할 수 있게끔 코드를 변경했습니다! 👍

2024-03-25 06:15 UTC, eunjungL commented on src/main/java/chess/view/PieceView.java
> +    public static String toView(Piece piece) {
view에서 사용되니까 `PieceView`라는 이름으로 지었는데 말씀해주신 것처럼 이름을 나타내고 있으니 `PieceName`으로 변경되는 것이 자연스러운 것 같습니다. 또한 메서드에 대한 네이밍도 Piece를 사용해 이름을 찾는다는 의미에서 `findName`으로 변경했습니다.
좋은 의견 감사합니다 🙇

2024-03-25 06:15 UTC, eunjungL commented on src/test/java/chess/domain/board/BoardFactoryTest.java
> +    private Map<Square, Piece> createExpectedBoard() {
기존에는 말씀해주신 것처럼 하드코딩으로 코드를 작성했는데요, 반복 코드가 많아져 오히려 가독성을 해치고 있지 않은가? 라는 생각에 지금과 같은 구조로 변경했습니다. 하지만 말씀해주신 것처럼 테스트 코드의 목적은 규칙대로 잘 만들어졌는지를 검증하는 것이므로 직접 규칙대로 넣어준 후 검증하는게 더 정확하고 의미가 있을 것 같습니다.
다시 변경하도록 하겠습니다! 의견 감사합니다 👍

2024-03-25 06:15 UTC, eunjungL commented on src/test/java/chess/domain/piece/PieceTypeTest.java
> +    @Nested
각 `Startegty`에 대한 테스트도 진행하고 `PieceType` 역시 도메인인만큼 테스트가 진행되는게 좋다는 생각에 분리를 진행했습니다. 하지만 말씀해주신 것처럼 `PieceTypeTest`는 맵핑만 할 뿐 각 전략의 테스트와 동일한 역할을 수행하고 있어서 오히려 전략이 바뀔 때마다 두 개의 클래스를 모두 수정해야되는 번거로움만 있었던 것 같습니다. 
`PieceTypeTest`는 제거하고 각 전략에서 세세한 테스트를 진행하도록 하겠습니다. 좋은 의견 감사합니다! 🙇