[1,2단계 - 체스] 레디(최동근) 미션 제출합니다.
woowacourse/java-chess pull request #678
Opened 2024-03-21 08:26 UTC by reddevilmidzy

2024-03-21 12:12 UTC, jamie9504 requested changes
안녕하세요, 레디 😄 리뷰어 제이미입니다.

만나서 반가워요 🎉 

`일단 돌아가는 게 중요해!라며 흐린 눈 하며 코드를 작성하였습니다.`
아주 중요한 포인트라고 생각해요. 기능 요구사항과 마감기한을 지키는 것만큼 중요한 것은 없다고 생각합니다.

하지만 이번 첫 Request Changes를 통해서는 프로그래밍 요구사항도 챙겨보시고, 흐린 눈을 다시 맑게 떠보시면 좋을 것 같아요.
1레벨 마지막 미션인만큼, 1~3단계에서 배워왔고 신경썼던 부분도 함께 녹여봐보세요!

> 레디가 이번 미션은 시간이 부족해서 적용하지 못한 부분들이 많을 것이라고 생각해요.
> 제가 코드에 대한 코멘트를 많이 남기는 방식을 더 좋아하실 수도 있지만,
> 어디까지를 알고 있지만 시간이 없어서 적용하지 못한 것인지
> 어디부터는 시간이 있어도 알지 못하기에 적용하지 못한 것인지 구분하기 위하여
> 첫 번째 리뷰 코멘트는 최소한으로 작성드리도록 하겠습니다.
> (은근슬쩍 새양/안나/포케에게 전달해주시면 감사하겠습니다. 😉)

다음 리뷰 요청 때 만나요 💪

2024-03-21 12:12 UTC, jamie9504 commented on docs/README.md
> +# 체스 미션
리뷰 요청은 코드 커밋 푸시 및 코멘트를 전부 다 달고 나서 해주세요!

<img width="828" alt="image" src="https://github.com/woowacourse/java-chess/assets/59511689/65994734-44f1-408e-a023-d13ea51cc98e">

2024-03-21 12:12 UTC, jamie9504 commented on src/main/java/application/Application.java
> +        chessController.run();
InputView와 OutputView를 Application에서 생성해서 넣어주는 이유는 무엇인가요?

InputController는 Controller의 기능이 맞을까요?
레디는 Controller가 어떠한 기능을 하는 클래스라고 생각하시나요?

chessController를 run한다는 것은 어떠한 의미인가요?

2024-03-21 12:12 UTC, jamie9504 commented on src/main/java/controller/ChessController.java
> +    public void run() {
불필요한 두 줄 개행 등 코드 스타일 전반적으로 체크해주세요.

---

<img width="776" alt="image" src="https://github.com/woowacourse/java-chess/assets/59511689/43ee961a-bc3b-4d6e-b7ce-59e5acf20c4c">

예외 발생시 사용자에게 StackTrace를 보여주는 것은 좋은 방식일까요?

2024-03-21 12:12 UTC, jamie9504 commented on src/main/java/controller/ChessController.java
> +        gameBoard.setting();
이 생성자와 메서드는 함께 붙어다녀야 할 것 같이 생겼는데, 나뉘어서 작업을 해주는 이유는 무엇인가요?
빈 생성자로 생성시 도메인이 해당 역할을 잘 수행할 수 있나요?
그리고 setting이라는 메서드는 뭔가 추상적인 느낌도 줄 수 있겠네요!

2024-03-21 12:12 UTC, jamie9504 commented on src/main/java/controller/ChessController.java
> +                Moving moving = getMoving(input.get(1), input.get(2));
시작에 대한 validation도 이곳 저곳 흩어져있네요!

레디의 매직넘버의 기준은 무엇인가요?

> else 예약어를 쓰지 않는다.
> else 예약어를 쓰지 말라고 하니 switch/case로 구현하는 경우가 있는데 switch/case도 허용하지 않는다.
> 힌트: if문에서 값을 반환하는 방식으로 구현하면 else 예약어를 사용하지 않아도 된다.

요구사항을 지켜서 리팩터링해볼까요?

2024-03-21 12:12 UTC, jamie9504 commented on src/main/java/controller/ChessController.java
> +        outputView.printCurrentCame(camp);
`printCurrentCame(camp);` 오타인가요?

currentCamp라는 용어를 사용할지 camp라는 용어를 사용할지도 고민해보세요.

2024-03-21 12:12 UTC, jamie9504 commented on src/main/java/dto/GameBoardDto.java
> +            tmp.get(entry.getKey().getRowIndex()).set(entry.getKey().getColumnIndex(), PieceType.from(entry.getValue()).getValue());
잠시 사용하더라도 가독성있고 직관적인 이름을 지어주면 좋을 것 같네요.

> 한 줄에 점을 하나만 찍는다.

2024-03-21 12:12 UTC, jamie9504 commented on src/main/java/model/piece/Bishop.java
> +    }
ToString은 어떨 때 쓰는 메서드일까요?
현재 해당 구현이 메서드의 존재 이유와 부합하고 있나요?

2024-03-21 12:12 UTC, jamie9504 commented on src/main/java/model/piece/King.java
> +            throw new IllegalArgumentException("이동 불가");
예외메시지 스타일도 하나로 일관성있게 가면 좋겠죠?

2024-03-21 12:12 UTC, jamie9504 commented on src/test/java/model/GameBoardTest.java
> +    void initPieces() {
테스트 메서드도 자주쓰는 명명규칙들이 있긴 한데요!
거기서 맘에 드는 게 있다면, 이번 미션에서 적용해보면 좋습니다. (없으면 패스하셔도 무관합니다.)
체스가 테스트도 여러가지 케이스가 나오기 좋아서, 테스트 메서드명에 익숙해지기 좋더라구요 😉 

현재 코드에서 클래스의 메서드별 테스트가 완전하지 않은 부분이 있는데 (코드 커버리지를 참고하세요)
테스트를 채워줘볼까요?
> 모든 기능을 TDD로 구현해 단위 테스트가 존재해야 한다.

2024-03-21 12:12 UTC, jamie9504 commented on src/test/java/model/GameBoardTest.java
> +                + "[r, n, b, q, k, b, n, r]%n");
출력에 의존한 코드는 앞으로 기물을 나타내는 글자가 수정된다던가 등의 수정 포인트에서 어디까지 대응을 해줘야 할까요?
수정 가능성에 대해 고민해보세요.

2024-03-23 11:18 UTC, reddevilmidzy commented
두눈 똑바로 뜬 채로 리팩터링 해보았습니다!👁👁

**변경된 점**

* 완벽에 가까워진 예외시 재입력 기능
* 게임 진행 상태를 객체로 두어 한결 깔끔해진 컨트롤러
* 전체적인 테스트 명
* 부족했던 테스트 추가 작성
  * 폰 이동
  * 기물 삭제
  * 이동 예외 케이스
* 커스텀 예외 구현

리뷰 미리 감사드립니다!

2024-03-23 11:19 UTC, reddevilmidzy commented on docs/README.md
> +# 체스 미션
죄송합니다! 다음부터는 주의하겠습니다!!

2024-03-23 11:19 UTC, reddevilmidzy commented on src/main/java/controller/ChessController.java
> +    public void run() {
최종적인 목표는 예외가 발생하면 StackTrace를 보여주는 것이 아니라 예외 메시지를 출력하고 재입력 받는 기능입니다!
시간안에 다 구현하기 힘들었네요..ㅎㅎ😵

2024-03-23 11:19 UTC, reddevilmidzy commented on src/main/java/model/piece/Bishop.java
> +    }
빠르게 구현하기 위해 기존에는 

```java
@Override
public String toString() {
    if (camp == Camp.BLACK) {
        return "B";
    return "b";
}
```

이런식으로 일단 콘솔에 출력할 때 사용하는 메서드로 사용하였었습니다.

이후에 리팩터링 과정에서 PieceType 객체를 만들어 이 toString 메서드를 사용하지 않고 콘솔에 출력하는 방향으로 변경하였습니다. 그럼 이제 이 toString 메서드는 프로덕션 코드에서 사용하지 않는데 지우지 않았던 이유는 디버깅을 할 때 사용하려고 두었습니다!

2024-03-23 11:19 UTC, reddevilmidzy commented on src/main/java/controller/ChessController.java
> +    public void run() {
StackTrace 대신 예외 메시지를 출력하고 재입력 받는 기능을 구현하였습니다!

2024-03-23 11:19 UTC, reddevilmidzy commented on src/test/java/model/GameBoardTest.java
> +                + "[r, n, b, q, k, b, n, r]%n");
우선 이 테스트의 목적은 보드의 출력물을 확인하는 것이 아니라 초기 위치를 확인하는 게 목적이었기에 Map을 비교하는 형태로 변경하였습니다!

출력에 의존한 코드는 무언가 변경이 될때마다 일일히 계속 수정해야 한다는 번거로움이 있겠네요
사실 이전 블랙잭 미션에서도 뭔가 변경이 있을 때마다 테스트를 수정해야하는 상황이 발생했었는데, 그때 내린 결론으로는 귀찮지만 열심히 수정하자! 였습니다 😅

2024-03-23 11:19 UTC, reddevilmidzy commented on src/test/java/model/GameBoardTest.java
> +    void initPieces() {
테스트 메서드 명명 규칙들을 구글링하다가 낯익은 닉네임의 [블로그](https://jamie95.tistory.com/125)가 보이길래 홀린듯이 들어갔네요😄

스윽 보고 적용해본다고 하긴 했는데 테스트 메서드 명 짓기도 쉽지 않네요 😵

2024-03-23 11:19 UTC, reddevilmidzy commented on src/main/java/application/Application.java
> +        chessController.run();
저는 Model 과 view를 이어주는 녀석이 Controller라고 생각하고 있습니다!

이전에는 InputContoller 안에서 입력을 받고 Model로 변경해주는 과정에서 예외가 발생하면 여기 InputController에서 잡고 올바른 값이 올때까지 이 InputController 가 처리 한다음 Model 로 변환하여 메인 Contoller 로 값을 넘겨주는 방식을 사용하였었습니다.

다시 정리하자면 예외시 재입력 및 입력 값을 Model로 변환하는 작업을 InputController 에서 처리해주었었는데, 현재 미션에선 이 InputController 가 재구실을 하지 못한 것 같습니다

2024-03-23 11:19 UTC, reddevilmidzy commented on src/main/java/controller/ChessController.java
> +        gameBoard.setting();
아무런 기물이 없는 체스 게임 보드를 만들고 싶어서 작업을 나눴습니다! 아무런 기물이 없는 체스 게임 보드 만들고 그 위에 원하는 기물들 몇개만 올리는 형태가 된다면 테스트가 쉬워질 거 같았습니다.

하지만 여러 테스트 작성하면서 제가 원하는 형태로 테스트 할 일이 없어져 생성자를 private 로 막고 정적 팩토리 메서드를 활용하는 방향으로 변경하였습니다!

2024-03-23 11:19 UTC, reddevilmidzy commented on src/main/java/controller/ChessController.java
> +                Moving moving = getMoving(input.get(1), input.get(2));
게임 상태를 객체화 하여 예외를 한곳에 모아봤습니다!

저는 여러군데에서 사용되거나, 그 값이 어떤 것을 의미하는지 전달이 안된다면 매직넘버라고 생각하여 상수로 분리하는 편입니다!

출력할 때 사용하는 메시지는 상수로 분리하는 것 보다는 그 자체로도 의미전달이 충분히 된다고 하여 상수로 분리하지는 않고, 출력 형식 같이 여러 번 사용되는 것은 상수로 분리하며 코딩하고 있습니다 :)

2024-03-23 11:19 UTC, reddevilmidzy commented on src/main/java/application/Application.java
> +        chessController.run();
의존성 주입을 위하여 InputView와 OutputView를 Application에서 생성한 후 넣었습니다!

chessController 를 run 하는건 프로그램한테 체스게임 시작할 준비해! 라는 의미였는데 다시 보니 그러면 이름이 chessController가 과연 적절한 이름일까 의문이 생기는군요ㅎㅎ

조금 더 고민해보겠습니다ㅏ!

2024-03-24 06:10 UTC, jamie9504 requested changes
안녕하세요, 레디 😄 리뷰어 제이미입니다.

코멘트 조금 더 남겨두었어요!
이번 Request Changes 반영을 하고 나면, 1\~2단계 요구사항은 충분히 충족하는 것 같아서 3~4단계로 넘어가봐도 좋겠네요.

즐거운 주말 보내세요! 💪

2024-03-24 06:10 UTC, jamie9504 commented on docs/README.md
> +# 체스 미션
> 두눈 똑바로 뜬 채로 리팩터링 해보았습니다!👁👁
> 
> **변경된 점**
> 
> * 완벽에 가까워진 예외시 재입력 기능
> * 게임 진행 상태를 객체로 두어 한결 깔끔해진 컨트롤러
> * 전체적인 테스트 명
> * 부족했던 테스트 추가 작성
>   * 폰 이동
>   * 기물 삭제
>   * 이동 예외 케이스
> * 커스텀 예외 구현

👍 

이번 체스 미션을 할 때, 시간이 촉박했었고 그로 인해 포기한 기능/구현 방식들이 있었겠죠?
그 지점을 이번에 추가적으로 리팩터링해주신거구요! 이 부분을 적어주신 점은 무척 좋았네요.

이를 통해 레디는 여러 가지를 알 수 있게 되는데요. (공통 피드백)
1. 미션 시간이 과연 부족했던 것이 맞을까? 어떠한 부분에서 지나치게 시간을 잡아먹은 부분은 없을까? 이 부분은 어떻게 개선할 수 있을까
2. 시간이 부족했을 때 내가 어떤 부분을 포기할 수 있는가(우선순위)
3. 내가 포기한 부분이 예상했던 것보다 더 적거나 많은 시간이 드는가? 즉, 시간 산정을 제대로 했던 것일까?
4. 시간이 넉넉할 때와 부족할 때 모두 협업이 용이했는가?

뭐 기타 등등에 대한 고민을 충분히 해볼 수 있겠죠!

체스 게임 구현에 대한 고민을 해보는 것도 충분히 좋지만, 이번 미션을 통해 마감기간이 정해진 무언가를 할 때 나의 선택 방향과, 그 방향이 의도한 방향인가, 아니라면 의도한 방향으로 전환하려면 어떤 자세를 취해야 하는가 등등 전반적인 부분에 대해서도 고찰해보면 좋을 것 같아요 😃

2024-03-24 06:10 UTC, jamie9504 commented on docs/README.md
> +# 체스 미션
👍 덧붙이자면, PR을 올린다는 것은 다른 개발자들이 해당 내용들을 확인할 수 있다는 의미겠죠? 😃 

물론 마감 시간이 촉박했으리라 짐작하지만, PR을 올린 후 코멘트를 변경하거나, 추가적으로 커밋 푸시가 생기거나 했을 때는
해당 PR을 확인하는 다른 개발자의 리뷰를 방해할 수 있다는 점으로 접근해보면 좋을 것 같아요 😉

2024-03-24 06:10 UTC, jamie9504 commented on src/main/java/application/Application.java
> +        chessController.run();
> 예외시 재입력 및 입력 값을 Model로 변환하는 작업을 InputController 에서 처리해주었었는데, 현재 미션에선 이 InputController 가 재구실을 하지 못한 것 같습니다

😄 

> 의존성 주입을 위하여 InputView와 OutputView를 Application에서 생성한 후 넣었습니다!

의존성 주입을 해주는 이유는 무엇인가요?

> 적절한 이름일까 의문이 생기는군요ㅎㅎ 조금 더 고민해보겠습니다ㅏ!

👍

2024-03-24 06:10 UTC, jamie9504 commented on src/main/java/controller/ChessController.java
> +    public void run() {
> 최종적인 목표는 예외가 발생하면 StackTrace를 보여주는 것이 아니라 예외 메시지를 출력하고 재입력 받는 기능입니다!

위 내용은 이해했습니다.
하지만 시간이 모자라서 구현하지 못했다면, 그 때는 재입력을 받지 않더라도 예외 메시지만 출력하는 부분까지는 구현을 했어도 좋았을 것 같아요!
이 프로그램에서는 괜찮지만 stacktrace가 노출되면 보안적으로 취약한 부분이 되기도 하기 때문에 잘 챙겨주시면 좋습니다 💪

2024-03-24 06:10 UTC, jamie9504 commented on src/main/java/controller/ChessController.java
> +        gameBoard.setting();
> 아무런 기물이 없는 체스 게임 보드를 만들고 싶어서 작업을 나눴습니다! 아무런 기물이 없는 체스 게임 보드 만들고 그 위에 원하는 기물들 몇개만 올리는 형태가 된다면 테스트가 쉬워질 거 같았습니다.

의도는 좋습니다! 아래 부분을 고민해보면 좋겠네요!

1. 기물이 없는 체스보드의 경우, 체스보드의 역할을 제대로 해줄 수 있는지
2. 원하는 기물들을 받아 체스보드를 만들어주는 생성자(또는 정적팩터리메서드)로도 동일한 효과를 얻을 수 있는 게 아닐지

---

`setupStartingPosition()` 이름의 정적팩터리메서드를 생성해주었네요 😃 
정적 팩터리 메서드의 경우도 주로 사용되는 명명규칙이 있는데 이를 한 번 알아보는 것도 좋을 것 같네요!

2024-03-24 06:10 UTC, jamie9504 commented on src/main/java/controller/ChessController.java
> +                Moving moving = getMoving(input.get(1), input.get(2));
👍 

`Moving moving = getMoving(input.get(1), input.get(2));`
요 부분에서 1과 2는 매직넘버일까가 궁금해서 코멘트 드렸었습니다 😃 
개인적으로 매직넘버에 대한 생각은 어느정도 일관성이 있다면 괜찮다고 생각합니다. 😉

2024-03-24 06:10 UTC, jamie9504 commented on src/main/java/model/piece/Bishop.java
> +    }
디버깅 용도로 사용하는 부분 좋습니다! 👍 

여쭤봤던 이유가 레디가 설명해줬던 이유와 동일한데요.
커밋 로그를 쭉 보니 중간에는 출력을 위한 용도로 사용한 경우가 있었더라구요!
물론 시간이 부족했던 부분은 감안하고 있지만, toString은 디버깅 용도로 주로 사용되므로 급하더라도 다른 출력용 메서드를 만드는 것이 좋지 않았을까? 해서 남겨뒀던 코멘트였습니다 😉

2024-03-24 06:10 UTC, jamie9504 commented on src/test/java/model/GameBoardTest.java
> +    void initPieces() {
테스트 메서드명도 일반 메서드명과 동일하게 내부에서 실행하고 있는 내용을 직관적으로 설명하고 있는가?를 중점으로 생각해보셔도 좋을 것 같아요.

개발자마다 이 부분도 의견이 분분한데요.
`@DisplayName`에서 충분히 설명을 했다고 생각하는 경우 메서드명은 조금 간략하게 적기도 하고,
두 개 다 잘 적어줘야 한다고 생각하기도 하고, 메서드명이 우선이다라고 생각하기도 하고, 뭐 여러 생각이 있을 수 있죠!

이에 대한 레디의 기준을 잡아보는 것도 좋고,
일단 둘 다 잘 작성할 수 있게 된 후 선택적으로 레디의 기준대로 따라가보는 것도 좋을 것 같아요.
할 수 있지만 하지 않는 것과, 할 수 없으며 하지 않는 것은 다르니까요 😃

2024-03-24 06:10 UTC, jamie9504 commented on src/test/java/model/GameBoardTest.java
> +                + "[r, n, b, q, k, b, n, r]%n");
> 우선 이 테스트의 목적은 보드의 출력물을 확인하는 것이 아니라 초기 위치를 확인하는 게 목적이었기에 Map을 비교하는 형태로 변경하였습니다!

👍 

> 출력에 의존한 코드는 무언가 변경이 될때마다 일일히 계속 수정해야 한다는 번거로움이 있겠네요
사실 이전 블랙잭 미션에서도 뭔가 변경이 있을 때마다 테스트를 수정해야하는 상황이 발생했었는데, 그때 내린 결론으로는 귀찮지만 열심히 수정하자! 였습니다 😅

이 부분에 대해서 고민해볼만한 건 몇 가지가 있겠네요.

1. Domain(로직)과 View(출력)중 어떤 것이 더 수정이 빈번할까? 입니다.
예를 들어 수정 전 테스트코드의 경우 Domain이 정상 동작하는지 테스트를 해줘야 하는데, View가 바뀔때마다 해당 테스트를 계속 수정해야겠지요?

2. 다른 개발자가 이를 짐작할 수 있을까? 입니다.
View를 수정하라고 해서 수정했는데, Domain의 테스트 코드가 깨질 것이라고 짐작할 수 있을까요?
Domain이 수정되었을 때 -> View가 영향 받는 것과, View과 수정되었을 때 -> Domain이 영향 받는 것에 대해 고민해보세요.

2024-03-24 06:10 UTC, jamie9504 commented on docs/README.md
> +  * [ ] 체크 상황이면 체크를 피하는 방향으로만 이동 가능
`* 특수 행마법` 구현은 재미있던 것 같아요. 체스 미션 다음 3, 4단계까지 다 끝난 후 추가로 구현해봐도 좋겠네요.
`* 체크 상황` 1번은 3단계에서 구현을 하게 될 것 같고, 2번의 경우 예전에 게임에서 그만 지고 싶을 수도 있지 않나...라는 고민도 해봤었네요 😄

체스는 룰이 많아서 이것 저것 시도해보기 좋죠 👍

2024-03-24 06:10 UTC, jamie9504 commented on src/main/java/constant/ErrorCode.java
> +public enum ErrorCode {
CustomException + ErrorCode 조합으로 사용하고 있는데,
CustomException과 ErrorCode가 1:1로 매칭이 되고 있는 것 같기도 하네요 😃 

그렇다면 같은 내용을 두 개로 나눠서 사용하고 있는 게 아닐까요 ?

2024-03-24 06:10 UTC, jamie9504 commented on src/main/java/controller/ChessController.java
> +        outputView.printCamp(chessBoard.getCamp());
이 둘이 항상 함께 움직인다면, ChessBoardDto에서 camp 정보를 가지고 있어도 되지 않을까요? 😃

2024-03-24 06:10 UTC, jamie9504 commented on src/main/java/controller/ChessController.java
> +    private List<String> getCommand() {
해당 List<String>은 뭔가 가공해줄 수 있지 않을까요?

> 모든 원시 값과 문자열을 포장한다
> 일급 컬렉션을 쓴다.

2024-03-24 06:10 UTC, jamie9504 commented on src/main/java/dto/ChessBoardDto.java
> +    private static final String RANK_GUIDE_LINE = "  %s";
FILE_GUIDE_LINE와 RANK_GUIDE_LINE는 같은 늬앙스로 사용되고 있지만 담고 있는 의미가 다르죠?

2024-03-24 06:10 UTC, jamie9504 commented on src/main/java/dto/ChessBoardDto.java
> +        this.value = value;
value보다 적절한 이름은 없었을까요?

2024-03-24 06:10 UTC, jamie9504 commented on src/main/java/dto/ChessBoardDto.java
> +                        .collect(Collectors.joining()))
저는 Stream 내에서 Stream을 이용하는 것도 일종의 Indent 2라고 생각합니다.
메서드를 적절히 분리해본 후 가독성의 차이가 있는지 확인해볼까요?

> indent(인덴트, 들여쓰기) depth를 2를 넘지 않도록 구현한다. 1까지만 허용한다.
> 예를 들어 while문 안에 if문이 있으면 들여쓰기는 2이다.
> 힌트: indent(인덴트, 들여쓰기) depth를 줄이는 좋은 방법은 함수(또는 메서드)를 분리하면 된다.

2024-03-24 06:10 UTC, jamie9504 commented on src/main/java/exception/CustomException.java
> +public class CustomException extends RuntimeException {
CustomExcecption을 사용했을 때 어떠한 장/단점이 있었을까요?

2024-03-24 06:10 UTC, jamie9504 commented on src/main/java/model/ChessBoard.java
> +    }
static final을 사용할 때 항상 고민해야 하는 점은 수정 가능한 상수인가? 인데요.

현재 startingPosition은 final로 재할당은 금지되었지만, Map의 메서드를 이용해 요소를 추가/수정/삭제가 가능해보이네요.
이는 레디가 의도한 바일까요?

2024-03-24 06:10 UTC, jamie9504 commented on src/main/java/model/ChessBoard.java
> +    private final Map<Position, Piece> board;
> 일급 컬렉션을 쓴다.

😃 적용해볼까요?

2024-03-24 06:10 UTC, jamie9504 commented on src/main/java/model/ChessBoard.java
> +        Map<Position, Piece> res = new HashMap<>();
> 줄여 쓰지 않는다(축약 금지).

모든 변수는 직관적이며 적절한 이름을 지어주도록 해요!

2024-03-24 06:10 UTC, jamie9504 commented on src/main/java/model/ChessBoard.java
> +            board.put(new Position(file, rank), startingPosition.get(file).apply(camp));
> 한 줄에 점을 하나만 찍는다.

가 생겨난 배경을 알아보고, 그 배경과 의미에 따라서 리팩터링해보도록 해요!

2024-03-24 06:10 UTC, jamie9504 commented on src/main/java/model/ChessBoard.java
> +        final Position currentPosition = moving.getCurrentPosition();
> 함수(또는 메서드)의 길이가 10라인을 넘어가지 않도록 구현한다.
> 함수(또는 메소드)가 한 가지 일만 하도록 최대한 작게 만들어라.

2024-03-24 06:10 UTC, jamie9504 commented on src/main/java/model/ChessBoard.java
> +        return board;
불변이 아닌 board를 그대로 내려준다면 어떠한 문제가 있을 수 있을지 고민해보아요!

2024-03-24 06:10 UTC, jamie9504 commented on src/main/java/model/Command.java
> +
의미없는/불필요한 개행은 모두 제거해주세요!
위와 같은 개행들은 오히려 가독성을 해치게 됩니다.

2024-03-24 06:10 UTC, jamie9504 commented on src/main/java/model/Command.java
> +    }
실상 같은 size인지 비교하는 메서드네요! `isAvailableSize`라는 의미가 적절한가요?

그리고 해당 부분은 테스트되지 않았네요! 테스트 없이 구현된 메서드의 기능들을 체크해볼까요?

> 모든 기능을 TDD로 구현해 단위 테스트가 존재해야 한다. 단, UI(System.out, System.in) 로직은 제외

2024-03-24 06:10 UTC, jamie9504 commented on src/main/java/model/status/Initialization.java
> +public class Initialization {
이 친구는 어떻게 보면 GameStatus가 아니라 GameStatus를 위한 Factory같은 느낌이군요!
조금 더 적절한 클래스명과 메서드명을 지어줘도 좋을 것 같아요!

2024-03-24 06:10 UTC, jamie9504 commented on src/main/java/view/message/ErrorCodeMessage.java
> +public enum ErrorCodeMessage {
View를 위한 ErrorCodeMessage를 만들었군요!
Domain에 View에 대한 내용을 포함하지 않기 위해 이러한 작업을 했다고 예상되는데요.

이렇게 분리했을 때의 실질적인 장/단점은 무엇이 있었을까요?

2024-03-24 06:10 UTC, jamie9504 commented on src/test/java/model/ChessBoardTest.java
> +    @Test
고민할만한 포인트네요!

`new Moving(E4, E5);` 를 move 했을 때 `PieceDoesNotExistException` 예외가 발생하는 부분을 검증하는 것이
기물이 없는 경우 예외가 발생함을 모두 보장해줄 수 있을까요 ?

2024-03-26 05:31 UTC, reddevilmidzy reviewed
꼼꼼한 리뷰 감사드립니다 제이미!

주신 코멘트 이외에 pawn을 추상클래스로 변경하고 blackPawn과 whitePawn 만들이 pawn을 상속받는 형태로 구현하였습니다

덕분에 중복되는 코드를 제거할 수 있었습니다!

2024-03-26 05:31 UTC, reddevilmidzy commented on src/main/java/model/piece/Bishop.java
> +    }
아하 의견에 동의합니다!

다음부터는 급해도 출력용 메서드를 만들어보겠습니다💪💪

2024-03-26 05:31 UTC, reddevilmidzy commented on docs/README.md
> +  * [ ] 체크 상황이면 체크를 피하는 방향으로만 이동 가능
아 3단계 요구 사항으로 게임 종료가 있었군요! 그럼 그때로 미뤄두도록 하죠 ㅎㅎㅎ
2번 같은 경우는 `게임에서 승리`가 플레이어의 목적이라고 생각하여 구현하려 했었는데, 생각해보니 과연 플레이어의 목적이 `게임에서 승리`가 맞을까? 라는 고민이 생겼네요. 질 수도 있지!

2024-03-26 05:31 UTC, reddevilmidzy commented on src/main/java/dto/ChessBoardDto.java
> +    private static final String RANK_GUIDE_LINE = "  %s";
으엇 예리하십니다!!! 👍👍
놓친 부분이네요

2024-03-26 05:31 UTC, reddevilmidzy commented on src/main/java/exception/CustomException.java
> +public class CustomException extends RuntimeException {
우선 제가 커스텀 예외를 사용한 이유는,,,

이전에는 IllegalArgumentException 안에 각 예외 상황에 따라 다른 `예외 메시지`를 넣어 구분을 지어주었습니다.
그러다 공통된 예외가 생기다 보니 중복되는 예외 메시지들이 보였고, 이들을 한 곳에서 관리해줄 녀석이 필요했습니다.
그렇게 한 곳에서 어떻게 관리할 지 고민하다가 내가 표현하고 싶었던 것은 `예외 상황`이고 이를 메세지로서 표현했었는데, 메세지 보다는 커스텀 예외가 더 명확하게 전달할 수 있다고 생각하여 사용하였습니다!

**장점**

* 예외 상황을 명확하게 전달할 수 있다.

**단점**

* 관리해야하는 코드가 들어난다.

2024-03-26 05:31 UTC, reddevilmidzy commented on src/main/java/controller/ChessController.java
> +        outputView.printCamp(chessBoard.getCamp());
해당 방식으로 변경하였습니다! 👍👍

2024-03-26 05:31 UTC, reddevilmidzy commented on src/main/java/controller/ChessController.java
> +    private List<String> getCommand() {
요것도 CommandLine 이라는 객체를 만들고 여기 필드에는 head, body로 나누어 명령을 가지고 있게 하였습니다!

한번 더 감싸주니까 애매하게 돌아다니고 있던 List<String> 이 제 역할을 찾은 듯한 느낌이네요👍👍

2024-03-26 05:31 UTC, reddevilmidzy commented on src/main/java/model/ChessBoard.java
> +    }
오 간과했던 부분입니다!

Map.of() 형태로 변경하여 제일 처음에 생성할 때 값을 세팅해주는 형태로 변경하였지만 여전히 수정은 가능하네요🤔

2024-03-26 05:31 UTC, reddevilmidzy commented on src/main/java/model/status/Initialization.java
> +public class Initialization {
Initalization 클래스명을 StatusFactory로 변경하고 메서드 명을 create로 변경해보았습니다!
사실 상태 패턴이 익숙치가 않아 어떻게 지어야 할지 감이 안잡힙니다...ㅎ

2024-03-26 05:31 UTC, reddevilmidzy commented on src/main/java/constant/ErrorCode.java
> +public enum ErrorCode {
맞네요!! 그럼 ErrorCode를 좀 더 세분화 해보겠습ㄴ디ㅏ💪

2024-03-26 05:31 UTC, reddevilmidzy commented on src/test/java/model/ChessBoardTest.java
> +    @Test
테스트 케이스가 빈약하다는 의견이였을까요?!

케이스를 좀 더 추가하였습니다!

2024-03-26 05:31 UTC, reddevilmidzy commented on src/main/java/view/message/ErrorCodeMessage.java
> +public enum ErrorCodeMessage {
domain에서 view를 걷어냄으로써 자주 변경될 수 있는 view에 수정이 생겼을 때 view 패키지에서만 수정을 하고 domain은 건들이지 않아도 된다는 장점이 있습니다!

단점으로는 커스텀예외의 단점과 비슷하게 관리해야하는 코드가 증가라고 생각합니다

2024-03-26 05:31 UTC, reddevilmidzy commented on docs/README.md
> +# 체스 미션
우왓 감사합니다 미션을 바라보는 새로운 눈이 생긴 거 같네요🙇‍♂️

주신 질문에 나름의 답을 해보자면,,

1. 코드를 작성하기 전에 설계를 한번 하고 들어갔다면, 초반에 다른 길로 새지 않았을 거 같습니다. (board를 이차원 리스트로 구현했던 점, 현재는 맵)
2. 시간이 없을 때 요구사항이 아닌 것들을 포기할 수 있을 거 같습니다. 제일 처음 제출을 하고 이런 고민이 들었습니다. 이번 미션의 요구사항중 클린코드도 있었는데 일단은 돌아가는 코드를 만들겠다고 너무 클린코드 재껴버렸던 것은 아닌지,, 조금은 아쉬운 감이 있었습니다 :)

2024-03-26 05:31 UTC, reddevilmidzy commented on src/main/java/application/Application.java
> +        chessController.run();
의존성 주입을 하게 된다면 서로 느슨한 결합을 유지할 수 있어 변경과 확장이 쉬워집니다!

2024-03-26 12:16 UTC, reddevilmidzy commented
폰을 블랙폰과 화이트폰으로 나누어서 중복 코드는 줄어들었지만 한번에 이해하기가 어려워진 느낌도 있군요
이 메서드 어디서 쓰는 거야! 하고 다른 클래스를 뒤져봐야 하네요

역시 뭐든 트레이드 오프🤔

2024-03-26 14:06 UTC, reddevilmidzy commented on src/main/java/model/ChessBoard.java
> +        return board;
헉 이부분 반영했다고 생각했었는데 놓쳤네요..ㅠ

그냥 날것의 board를 넘기면 이제 외부에서 마음껏 수정이 가능해버린다는 문제점이 발생합니다🥲

2024-03-26 14:39 UTC, jamie9504 approved these changes
안녕하세요, 레디 😄 리뷰어 제이미입니다.

간단한 코멘트들은 남겨두었으니, 다음 단계 작업하시면서 같이 고민/반영해주세요!
관련된 코멘트들은 모두 현재 PR이 아니라, 새로 작업하는 3, 4단계 PR에 올려주세요 😃 

지난번 Request changes 때 말씀드렸듯이, 1/2단계는 모두 충족하여 Approve & Merge합니다.
다음 단계도 화이팅입니다. 💪

2024-03-26 14:39 UTC, jamie9504 commented on src/main/java/application/Application.java
> +        chessController.run();
인터페이스를 사용하지 않는데도 느슨한 결합이 되었다고 할 수 있을까요?

레디의 의도에 따라 구현된 코드인지 한 번 더 체크해볼까요?

2024-03-26 14:39 UTC, jamie9504 commented on docs/README.md
> +# 체스 미션
매 미션마다, 미션에서의 아쉬웠던 점과 좋았던 점을 고민해본다면
레디의 강점과 약점을 분석하고, 어떠한 방향으로 나아가는 것이 좋을지 지표가 될 수도 있습니다 😃

2024-03-26 14:39 UTC, jamie9504 commented on src/main/java/exception/CustomException.java
> +public class CustomException extends RuntimeException {
> 내가 표현하고 싶었던 것은 예외 상황이고 이를 메세지로서 표현했었는데, 메세지 보다는 커스텀 예외가 더 명확하게 전달할 수 있다고 생각하여 사용하였습니다!

현재는 예외 메시지와 커스텀 예외를 모두 쓰고 있죠?

커스텀 예외를 사용했을 때의 장/단점에 대해 조금 더 심도 깊게 생각해보세요!

장점) 예외 상황을 명확하게 전달해서 현재 얻고 있는 이점은 무엇인가요?

단점) 관리해야하는 코드가 늘어나있는 현재 코드에선 어떤 부가적인 단점들이 있을 수 있을까요?

2024-03-26 14:39 UTC, jamie9504 commented on src/main/java/model/ChessBoard.java
> +    }
그러면 어떻게 개선해볼 수 있을까요?

2024-03-26 14:39 UTC, jamie9504 commented on src/main/java/model/status/Initialization.java
> +public class Initialization {
요 친구는 상태패턴과는 관계가 없는 Factory 인 것 같아요! (상태패턴을 만들어주고는 있지만요!)
디자인패턴을 전부 다 알 필요는 없지만, 사용하는 or 사용한 디자인패턴에 대해서는 조금 더 알아보고 가는 것도 좋겠네요 😉 
버퍼 기간을 활용해봐도 좋구요!

2024-03-26 14:39 UTC, jamie9504 commented on src/test/java/model/ChessBoardTest.java
> +    @Test
테스트가 빈약하다/빈약하지 않다보다
구현된 테스트가 레디의 의도대로 구현되었는가?가 궁금했어요 😃

2024-03-26 14:39 UTC, jamie9504 commented on docs/README.md
> +* [x] 예외 시 재입력 구현하기
리팩터링 부분이 README에 들어가는 것이 맞을지 고민해보세요!

README.md는 github에 올라가는 파일인만큼 많은 사람이 볼 수 있고, 지속적인 유지보수가 필요하답니다 😉

2024-03-26 14:39 UTC, jamie9504 commented on src/main/java/application/Application.java
> +package application;
패키지를 나누는 기준은 무엇인가요.
현재는 일관성이 없이 나뉘어져 있는 것 같기도 하네요 😃 

보편적으로 main 메서드가 있는 Application은 어디에 위치하는지도 알아보시면 좋을 것 같아요!

2024-03-26 14:39 UTC, jamie9504 commented on src/main/java/controller/ChessController.java
> +            List<String> command = inputView.readCommandList();
final을 붙이는 경우와 붙이지 않는 경우를 레디는 어떤 기준으로 구분하고 계신가요?

2024-03-26 14:39 UTC, jamie9504 commented on src/main/java/dto/ChessBoardDto.java
> +    private static final String RANK_GUIDE_LINE_FORM = "  %s";
> 줄여 쓰지 않는다(축약 금지).

2024-03-26 14:39 UTC, jamie9504 commented on src/main/java/dto/ChessBoardDto.java
> +    private static final int BOARD_SIZE = 8;
BoardSize를 DTO에서 가지고 있어야 하는 정보인가요?

2024-03-26 14:39 UTC, jamie9504 commented on src/main/java/dto/ChessBoardDto.java
> +    private static String paddedRankGuidLine(final File file, final Rank rank) {
메서드명으로 적절한 이름인가요?

2024-03-26 14:39 UTC, jamie9504 commented on src/main/java/model/ChessGame.java
> +    }
setup은 뭔가 현재 객체에서 상태를 세팅해줄 것 같은 이름이긴 하네요 😃 
더 적절한 이름이 있는지 고민해볼까요?

2024-03-26 14:39 UTC, jamie9504 commented on src/main/java/model/command/Command.java
> +    private final Pattern pattern;
조금 더 이름을 잘 지어줘봐도 좋을 것 같아요.
또한 `Pattern.compile`는 중복이 아닐까요?

2024-03-26 14:39 UTC, jamie9504 commented on src/main/java/model/command/Command.java
> +            throw new InvalidCommandException(ErrorCode.INVALID_COMMAND);
> 모든 기능을 TDD로 구현해 단위 테스트가 존재해야 한다. 단, UI(System.out, System.in) 로직은 제외
> 핵심 로직을 구현하는 코드와 UI를 담당하는 로직을 구분한다.
> UI 로직을 InputView, ResultView와 같은 클래스를 추가해 분리한다.

한번 쭉 점검해줄까요?

---

해당 메서드에서는 values, 아래 메서드에서는 input을 쓰고 있는데, 이름에 대해서도 일관성을 가져가면 좋을 것 같아요.

2024-03-26 14:39 UTC, jamie9504 commented on src/main/java/model/command/CommandLine.java
> +    public static final int NEXT_POSITION_INDEX = 1;
public ! ! 상수로 추출할 때 실수한 부분이라면 상수 추출시 C를 한 번 더 눌러서 기본 접근제어자를 바꿔주는 것도 방법이겠죠?

---

piece들에 있는 숫자는 매직넘버로 빼지 않고, 해당 부분은 매직넘버로 뺀 이유도 궁금하네요 😃

2024-03-26 14:39 UTC, jamie9504 commented on src/main/java/model/command/CommandLine.java
> +        return body;
body를 수정할 수 있겠군요 💪 

getter로 보내줄 때 가변인 상태로 보내주는 것이 의도된 동작인지 검토해볼까요?

2024-03-26 14:39 UTC, jamie9504 commented on src/main/java/model/piece/Pawn.java
> +    }
Pawn은 BlackPawn과 WhitePawn의 부모인데, 구현체를 알아도 되는걸까요?

2024-03-26 14:39 UTC, merged

2024-03-26 15:38 UTC, reddevilmidzy reviewed
리뷰 감사드립니다! 그럼 3,4단계 때 보아요😁

2024-03-26 15:38 UTC, reddevilmidzy commented on src/main/java/controller/ChessController.java
> +            List<String> command = inputView.readCommandList();
필사적으로 전부 다 붙이려고하는데 요 친구는 놓쳤네요😌

그럼 final 왜 붙이는데?? 라고 누군가 물어봤을 때 답해보자면, 이 코드는 추후에 내가 아닌 다른 사람이 볼텐데, final을 붙임으로써 "이거 이제 멋대로 건들이지마!!"라는 메시지를 전달할 수 있다고 생각하여 필요한 곳에 전부 붙여주고 있습니다

final이 붙어서 좀 가독성이 떨어지는 느낌도 있지만 이제 익숙해져 없으면 허전한거 같기도...ㅎㅎ (근데 요곤 왜 놓쳤지 보니까 저어기 인터페이스에서도 안붙어 있군요)

2024-03-26 15:38 UTC, reddevilmidzy commented on src/main/java/dto/ChessBoardDto.java
> +    private static final int BOARD_SIZE = 8;
웁스 아닙니다!!

2024-03-26 15:38 UTC, reddevilmidzy commented on src/main/java/dto/ChessBoardDto.java
> +    private static String paddedRankGuidLine(final File file, final Rank rank) {
이름짓기가 진짜 어려운거 같아요...ㅎㅎ
todo 붙여두고 지금은 시간없으니 나중에 이쁜 이름 지어줘야지 했다가 다시 지으러 왔을 땐 이게 대충 괜찮네 하고 넘어가기 일쑤..

메서드가 하는 일에 맞춰 의도를 전달하는 이름 짓는 연습이 더 필요해보이네요😗

2024-03-26 15:38 UTC, reddevilmidzy commented on src/main/java/model/piece/Pawn.java
> +    }
헉뜨 현실세계에선 부모가 자식 아는게 당연한거 같은데 객체지향 세계에선 또 다르네요👍
구현체를 알게되면 의존성 역전 원칙이 깨지게 되는 문제가 발생합니다!

2024-03-26 15:38 UTC, reddevilmidzy commented on src/main/java/model/ChessBoard.java
> +    }
지금 딱 생각나는건 두가지가 있는데 둘다 마음엔 안드네요😅
1. Map을 없앤다.
2. static final 을 없앤다. (써놓고 보니 너무 이상하네요)

2024-03-26 15:38 UTC, reddevilmidzy commented on src/main/java/model/ChessBoard.java
> +    }
3,4 단계에서 계속 고민해보겠습니다!ㅎㅎ

2024-03-26 15:38 UTC, reddevilmidzy commented on src/main/java/application/Application.java
> +        chessController.run();
오오오 좋습니다! 질문을 너무 맛있게 해주셔서 코딩할 맛이 나는데요 😁

2024-03-26 15:38 UTC, reddevilmidzy commented on src/main/java/model/status/Initialization.java
> +public class Initialization {
아하 버퍼 기간 야무지게 활용해보겠습니다!!!