[1, 2단계 - 체스] 무빈(김현중) 미션 제출합니다.
woowacourse/java-chess pull request #684
Opened 2024-03-21 08:30 UTC by hjk0761

안녕하세요, 레벨1 마지막 미션 수행중인 무빈이라고 합니다!

미션 요구사항에 맞게 구현하려고 노력했지만, 능력의 부족을 많이 느낀 미션이었습니다.

잘 부탁 드립니다!

2024-03-22 01:09 UTC, summerlunaa requested changes
무빈 안녕하세요~ 체스 미션의 리뷰어 파랑입니다 🐳

레벨 1의 마지막 미션까지 오셨네요! 특히나 이번 미션은 쉽지 않았을 것 같은데 시간 맞춰서 잘 구현해주셨습니다ㅎㅎ

첫 리뷰인데다 코드 양도 많은 만큼 리뷰를 많이 드리지는 않았습니다. 짧게 자주 티키타카 해보면 좋을 것 같아요. 필요하시면 언제든 편하게 DM 주시구요~ 감사합니다 ☺️

2024-03-22 01:09 UTC, summerlunaa commented on src/main/java/chess/controller/ChessGameController.java
> +    private void playOneTurnForStart(ChessGame chessGame) {
메서드명이 자세하다고 항상 읽기 좋은 것은 아닙니다. `start`, `startGame` 등으로 간결하게 수정해볼까요?

2024-03-22 01:09 UTC, summerlunaa commented on src/main/java/chess/domain/Board.java
> +        initialize(board);
지금 보드를 초기화하는 방식이 이해하기 쉬운 방식은 아니네요! 조금 더 단순하게 만들어 봐도 좋을 것 같아요. `createPieceLocationsByIndex` 특히 요런 메서드는 파악하기 굉장히 어렵습니다. 어려운 코드는 에러의 원인이 되기 쉽습니다.

2024-03-22 01:09 UTC, summerlunaa commented on src/main/java/chess/domain/Board.java
> +        initialize(board);
무빈은 어떤 기준으로 메서드를 정렬하나요?

2024-03-22 01:09 UTC, summerlunaa commented on src/main/java/chess/domain/piece/ChessPiece.java
> +public abstract class ChessPiece implements Piece {
인터페이스와 추상클래스를 잘 활용하셨네요 👍

2024-03-22 01:09 UTC, summerlunaa commented on src/main/java/chess/domain/piece/ChessPiece.java
> +    public abstract ChessPiece move(Position newPosition, boolean isDisturbed, boolean isOtherPieceExist,
파라미터가 이렇게 많아지게 된 건 board 자체를 넘기기 싫어서인가요? 
[프로그래밍 체크리스트](https://github.com/woowacourse/woowacourse-docs/blob/master/cleancode/pr_checklist.md)에서 인자 수를 왜 제한하고 있을까요? 고민해보면 좋겠습니다~

2024-03-22 01:09 UTC, summerlunaa commented on src/main/java/chess/domain/strategy/MoveStrategy.java
> +}
각 기물들의 행마법도 잘 분리해주셨네요~ 기물들의 개별 행마법을 각각의 클래스에서 확인하기 쉬웠어요. 요런 방식을 어떻게 선택하게 되었는지 궁금합니다!

2024-03-22 06:32 UTC, hjk0761 commented on src/main/java/chess/domain/piece/ChessPiece.java
> +    public abstract ChessPiece move(Position newPosition, boolean isDisturbed, boolean isOtherPieceExist,
맞습니다! Board 자체를 넘겨주는 행위가 순환참조가 된다고 생각해서 최대한 피하려고 했었습니다.
Board에서 Piece의 move를 사용하기 때문에 인자 수에 대한 제한이 있었음에도 많은 인자를 넘기는 방향을 선택했습니다.

```
//기존 코드
Piece movedPiece = movePiece(source, target, piece);

//수정 코드
Piece movedPiece = movePiece(piece, target, this);
```

또한 위와 같이 Board가 this를 통해 본인을 넘겨줘야 하는 상황이 생겨 이 방법이 안전한 방법인지 확신이 생기지 않아 지금과 같은 방법으로 진행했습니다.

혹시 파랑께서는 Board가 스스로를 넘겨주는 행위가 괜찮다고 생각하시나요? 그렇다면 그 이유도 궁금합니다!

2024-03-22 06:34 UTC, hjk0761 commented on src/main/java/chess/domain/strategy/MoveStrategy.java
> +}
기물들이 체스 말로 추상화 할 때 '움직인다'라는 행동 또한 추상화의 대상이라고 생각했습니다!
어떻게 움직이는 지는 각 기물마다 다르지만, 기물 모두 '움직임이 가능하면, 움직인다' 라는 공통 행위를 가지는 객체라고 생각해서 각각의 움직임 전략을 따로 가지는 방향으로 구현하게 되었습니다!

2024-03-22 06:38 UTC, hjk0761 commented on src/main/java/chess/controller/ChessGameController.java
> +    private void playOneTurnForStart(ChessGame chessGame) {
해당 클래스가 커맨드에 따른 ChessGame의 각 메서드를 호출하는 역할을 수행하므로 이에 맞게 직관적일 수 있도록 바꾸어 보았습니다!

2024-03-22 08:55 UTC, hjk0761 commented on src/main/java/chess/domain/Board.java
> +        initialize(board);
이전 블랙잭 미션에서 52장의 카드를 일일이 만들어 주었던 과정에 비해서, 6종류와 32개의 말을 초기화 하기 위해 메서드를 만들고 분리한 행동이 필요 이상으로 노력을 들였다는 생각이 들었습니다.
그래서 기물들을 초기화 하는 클래스를 따로 만들어서, 불필요한 자동화, 일반화를 하지 않도록 단순하게 만들었습니다.
파랑이 이 부분을 짚어주신 의도를 단순함이 필요한 부분에 불필요한 복잡한 로직을 끼워넣는 것을 지양하라는 말로 이해해서 최소한의 부분만 반복문을 사용하도록 구현해 보았습니다!

2024-03-22 09:02 UTC, hjk0761 commented on src/main/java/chess/domain/Board.java
> +        initialize(board);
저는 정렬 기준을 생성자 - (생성자에서 쓰이는 메서드 - ) public - private - override - getter 순으로 사용하려고 노력합니다.

다만, 현재 Board 에서 구현 과정에서 메서드의 범위와 역할이 많이 바뀌었는데, 이를 순서 상으로 반영하지 못한 것 같습니다.
또한 외부에서 사용해서 public 으로 열려있었지만, 수정 이후에 내부에서만 사용하도록 바뀐 메서드도 있었습니다.

이런 경우에 이미 테스트가 존재하는데, 이를 위해 접근제어자를 default로 바꾸는 행동은 올바르지 않다는 생각이 듭니다.
이럴 때에 파랑께서는 테스트를 바꾸시는지 궁금합니다!

2024-03-22 10:27 UTC, summerlunaa commented on src/main/java/chess/domain/piece/ChessPiece.java
> +    public abstract ChessPiece move(Position newPosition, boolean isDisturbed, boolean isOtherPieceExist,
어려운 부분이네요 ^-^ 생각나는 방법들을 정리해봤습니다.

- 인자의 수가 많아지더라도 현재 방법을 유지
- 순환참조를 감수하고 인자의 수를 줄이기
- 필요한 인자들을 가진 객체 생성
- piece는 이동 가능한 경로만 파악하고 최종 이동 여부는 board에서 결정

저는 이전에 두 번째 방법을 사용하긴 했습니다만 말씀하신대로 순환참조가 발생하기 때문에 추천할만한 방법이라 말씀드리긴 어려울 것 같아요. 여러 방법들을 고민해보고 무빈이 내린 결정이라면 저는 지금도 좋다고 생각해요 👍 모든 조건을 만족시키는 구현은 없으니까요.

2024-03-23 12:25 UTC, summerlunaa requested changes
무빈 안녕하세요~

리뷰 빠르게 반영해주셨네요! 리팩토링 잘 해주셔서 코드가 훨씬 읽기 좋아졌습니다 👍 

몇가지 리뷰 더 남겨두었어요. 확인 부탁드립니다~

2024-03-23 12:25 UTC, summerlunaa commented on src/main/java/chess/domain/BoardInitializer.java
> +public class BoardInitializer {
오 보드 초기화 클래스를 따로 만드셨네요. 로직도 훨씬 깔끔해져서 이해하기 너무 좋습니다 💯

2024-03-23 12:25 UTC, summerlunaa commented on src/main/java/chess/domain/Command.java
> +    private final String command;
Command 클래스 분리 좋습니다 👍  List에서 index로 가져오는 것보다 안전하고 깔끔하네요.
다만 command에 CommandType을 사용하지 않고 String을 사용한 이유가 있을까요?

2024-03-23 12:25 UTC, summerlunaa commented on src/main/java/chess/domain/ChessGame.java
> +        if (turn != Team.WHITE && turn != Team.BLACK) {
```suggestion
        if (turn.notStarted()) {
```
와 같이 메서드를 추가해 볼 수 있겠네요!

2024-03-23 12:25 UTC, summerlunaa commented on src/main/java/chess/domain/ChessGame.java
> +            throw new IllegalArgumentException("source좌표와 target좌표가 같을 수 없습니다.");
상황에 따른 자세한 에러 메시지 좋습니다 👍

2024-03-23 12:25 UTC, summerlunaa commented on src/main/java/chess/domain/Team.java
> +    public static Team takeTurn(Team team) {
사용하지 않는 메서드네요. 정리해볼까요?

2024-03-23 12:25 UTC, summerlunaa commented on src/main/java/chess/domain/Position.java
> +    private final int y;
좌표를 int로 저정하다보니 변환시에 아스키코드를 사용하는 부분이 많더라구요. 사실 `'a'+1`, `(char) ('a' + x)`와 같은 코드가 이해하기 쉬운 변환 방식은 아닌 것 같아요. FILE, RANK 등의 enum을 사용해봐도 좋을 것 같습니다.

2024-03-23 12:25 UTC, summerlunaa commented on src/main/java/chess/domain/Command.java
> +    private final String command;
추가된 클래스에 대한 테스트가 없네요 👀

2024-03-23 12:25 UTC, summerlunaa commented on src/main/java/chess/domain/Board.java
> +        initialize(board);
public 메서드를 통해 private 메서드의 로직 테스트가 가능하면 그렇게 진행하구요. private 메서드의 로직이 너무 중요하고 public 메서드를 통해 테스트하기도 힘들다, 이런 경우에는 접근자를 default로 하거나 리플렉션을 사용해서라도 테스트를 추가할 것 같아요!

2024-03-23 12:46 UTC, hjk0761 commented on src/main/java/chess/domain/Team.java
> +    public static Team takeTurn(Team team) {
차례를 바꾸는 책임이 ChessGame에 넘어가면서 미처 제거하지 못했습니다. 제거하도록 수정했습니다!

2024-03-23 12:50 UTC, hjk0761 commented on src/main/java/chess/domain/ChessGame.java
> +        if (turn != Team.WHITE && turn != Team.BLACK) {
'ChessGame의 차례가 시작하지 않았다' 보다 'ChessGame이 시작하지 않았다' 라는 의미가 더 적절하다는 생각이 들어 turn.notStarted() 대신 notStarted() 로 추상화 하였습니다!

2024-03-23 13:02 UTC, hjk0761 commented on src/main/java/chess/domain/Command.java
> +    private final String command;
입력받는 타입이 String 이여서 단순히 이를 저장하여야 한다고만 생각했었는데, 미리 만들어둔 CommandType 을 사용하는 것이 더욱 의미 전달에 좋을 것 같습니다!

리팩터링을 진행하는 중에 떠오르는 것을 급하게 구현하다 보니 TDD 사이클을 따르지 못한 것 같습니다... 잘 짚어주셔서 감사드립니다!

2024-03-23 13:22 UTC, hjk0761 commented on src/main/java/chess/domain/Board.java
> +        initialize(board);
해당 메서스들이 움직임을 결정하는 중요한 로직임이기에 테스트가 꼭 필요하다고 생각합니다.
하지만 Board 내부의 메서드에서만 호출되는 로직이기 때문에 말씀 주신 방법 중에서는 default 생성자를 사용하는 것이 지금 상황에서 가장 좋은 방법이라고 생각해서 수정하였습니다!

핵심 로직에 포함되는 메서드를 어떻게 관리해야 로직이 잘 작동하는 지 테스트로도 확인할 수 있으면서 외부로 불필요한 노출을 숨길 수 있는지 개인적으로 좀 더 고민해보겠습니다!
좋은 인사이트 주셔서 감사합니다 ㅎㅎ

2024-03-23 14:01 UTC, hjk0761 commented on src/main/java/chess/domain/Position.java
> +    private final int y;
위치를 int로 관리하는 데에 매몰되어 문자와 상호변환하는 부분이 너무 직관적이지 못했던 것 같습니다!

File, Rank Enum 을 적용하여 조금 더 직관적인 좌표 변환 로직을 설계하도록 수정해 보았습니다 ㅎㅎ
수정하는 과정에서 처음에 Enum 의 ordinal() 을 사용하려고 했지만 조금 더 찾아보니 공식문서에서 사용을 지양하라고 하여 index를 추가해 관리했습니다.

2024-03-24 06:27 UTC, summerlunaa commented on src/main/java/chess/domain/Position.java
> +    private final int y;
리팩토링 해주신 부분 확인했습니다. ordinal을 사용하지 않은 점도 너무 좋네요ㅎㅎ 잘 찾아보셨습니다 👍

2024-03-24 06:31 UTC, summerlunaa approved these changes
무빈 안녕하세요~

이번에도 굉장히 빠르게 리뷰 반영해주셨군요 👏  어려운 미션이었을텐데 구현부터 리팩토링까지 너무 잘 해주셨습니다. 1,2단계는 여기서 머지해도 괜찮을 것 같아요.

다음 단계도 파이팅입니다 💪

2024-03-24 06:43 UTC, merged