[1,2단계 - 체스] 도도(김도선) 미션 제출합니다.
woowacourse/java-chess pull request #688
Opened 2024-03-21 08:34 UTC by ehtjsv2

안녕하세요! 안돌!

이번 체스미션 시간이 부족하여 뷰와 컨트롤러보다는 도메인에 집중했습니다!

체스미션 리뷰 잘부탁드립니다!

2024-03-22 14:10 UTC, andole98 requested changes
안녕하세요 리뷰어 안돌입니다.

Space 등 위치정보에 관해 고민을 많이 하신것 같네요. 위치와 피스의 관계를 더 잘 정리해보시면 좋을것 같아요. 

코멘트 내용이 이해되지 않거나 다른 의견 있다면 댓글 & 슬랙 주세요.

2024-03-22 14:10 UTC, andole98 commented on README.md
> +### 기능 요구 사항
기능 요구사항을 개념/도메인별로 잘 작성하셨네요.

2024-03-22 14:10 UTC, andole98 commented on src/main/java/chess/ChessMachine.java
> +            String command = fromTo.get(0);
command도 객체라면 좋을것 같네요.

```java
class MoveCommand {
  String from;
  String to;
}
```

2024-03-22 14:10 UTC, andole98 commented on src/main/java/chess/domain/chessBoard/ChessSpaceGenerator.java
> +        return spaces;
여기는 indent depth가 2 이네요.

space를 만들때 Position 정보가 필요해서 2차원배열 처리가 필요하네요. 

어느정도 도메인이나 구현상에서 피하기 어려운 부분이라 도도가 불편하지 않다면 그대로 둬도 될것 같기도 하네요.

제 생각에는 `List<Position>` 이 먼저 생기고, Position에 맞는 piece를 맞춰가면서 Space를 만들어보는것도 괜찮을것 같네요.

2024-03-22 14:10 UTC, andole98 commented on src/main/java/chess/domain/chessBoard/PieceGenerator.java
> +    public static List<Piece> makeSpecialPieces(Color color) {
static 메서드만 있네요. `PieceGenerator`는 객체인가요?

2024-03-22 14:10 UTC, andole98 commented on src/main/java/chess/domain/chessBoard/PieceGenerator.java
> +    public static List<Piece> makePawnPieces(Color color, int amount) {
amount는 항상 8일것 같아요

2024-03-22 14:10 UTC, andole98 commented on src/main/java/chess/domain/chessBoard/Space.java
> +import chess.view.PieceSign;
domain에 view가 들어왔네요. pieceSign이 도메인으로 편입되든, space가 pieceSign을 배제하든 정리가 필요하네요.

2024-03-22 14:10 UTC, andole98 commented on src/main/java/chess/domain/chessBoard/Space.java
> +        if (piece.getClass() == Knight.class) {
Piece로 캡슐화를 시도했는데 이 코드가 캡슐화를 깨뜨리네요.

route에 관한 정보는 Knight가 관리하려면 어떻게 해야 할까요?

2024-03-22 14:10 UTC, andole98 commented on src/main/java/chess/domain/chessBoard/Space.java
> +    public void movePiece(Space targetSpace, List<Space> spaces) {
이 메서드는 조금 의문이 드네요. space가 다른 space와 함께 `List<Space>`를 받는데, space 전체에요. 사실상 `List<Space>` 하나만 있어도 target destination allspace 모두 알수 있는거 아닌가요?

2024-03-22 14:10 UTC, andole98 commented on src/main/java/chess/domain/chessBoard/Space.java
> +                validateRouteHasPiece(route, space);
이것때문에 spaces를 받는것 같네요. space는 개별 space(targetSpace)와 비교만 하고 `List<Space>` 를  잘 다루는 객체가 로직을 갖는게 좋을것 같아요.

2024-03-22 14:10 UTC, andole98 commented on src/main/java/chess/domain/chessBoard/Space.java
> +        return piece.isSameColor(new EmptyPiece());
EmptyPiece가 비교의 대상인데 매번 생성하는건 조금 불편하네요.

조금 어려울지 모르겠으나 [empty object pattern / null object pattern](https://johngrib.github.io/wiki/pattern/null-object/)에 대해 알아보면 좋을것 같아요.

2024-03-22 14:10 UTC, andole98 commented on src/main/java/chess/domain/piece/EmptyPiece.java
> +public class EmptyPiece extends Piece{
```suggestion
public class EmptyPiece extends Piece {
```

2024-03-22 14:10 UTC, andole98 commented on src/main/java/chess/domain/piece/King.java
> +    private static Rule decideRule() {
functional interface가 조금 로직이 복잡해지니 불편해지네요.

이 룰은 개별적으로 테스트하기 쉽나요? static method가 아니라 KingRule 같은 객체로 나오면 테스트가 더 쉽고 가독서도 좋아질것 같네요.

2024-03-22 14:10 UTC, andole98 commented on src/main/java/chess/domain/piece/Piece.java
> +    private final Rule moveRule;
abstract class로 구성하셨으니 필드로 Rule을 강제하는 대신 `isMovable`을 abstract로 구성해서 사실상 Rule을 자유롭게 구성하도록 열어주면 어떨까요?

2024-03-22 14:10 UTC, andole98 commented on src/main/java/chess/domain/position/PositionDifference.java
> +    public boolean isObeyRule(Rule rule) {
이건 사실상 순환참조인것 같네요. Rule이라는 친구는 사실 피스의 영역에 있는 친구고, 피스는 position 개념에 의존하고 있어요. 하지만 position에서 다시 Rule에 의존하고 있네요.

Rule에게 positionDifference를 넘기도록 하면 조금 편해질지도?

2024-03-22 14:10 UTC, andole98 commented on src/main/java/chess/domain/position/Difference.java
> +public abstract class Difference {
이 친구는 왜 abstract인지 잘 모르겠어요. 그냥 Difference가 class이고 FileDifference / RankDifference가 사라져도 되는거 아닌지?

만약 file / rank를 엄격히 구분하려면 생성자나 필드부터 file / rank를 얘기해야 할것 같고요.

2024-03-22 14:10 UTC, andole98 commented on src/main/java/chess/domain/position/Position.java
> +        return new Position(File.of(fileName),Rank.of(rankName));
```suggestion
        String fileName = positionName.substring(0, 1);
        String rankName = positionName.substring(1, 2);
        return new Position(File.of(fileName), Rank.of(rankName));
```

2024-03-22 14:10 UTC, andole98 commented on src/main/java/chess/domain/position/Position.java
> +        return new Position(File.of(fileName),Rank.of(rankName));
positionName은 사실상 view에 가까운것 같네요. 위에 남긴 command 개념의 객체를 잘 이용하면 입력으로부터 Position을 잘 찾아낼지도 모르겠네요.

2024-03-22 14:10 UTC, andole98 commented on src/main/java/chess/domain/position/Rank.java
> +
상당히 어려운 로직이네요. enum class가 가질만한 로직이 아닌것 같아요. 

반복문도 상당히 어렵네요. 도도는 잘 이해되나요?

2024-03-22 14:10 UTC, andole98 commented on src/main/java/chess/view/PieceSign.java
> +            if (piece.getClass() == value.pieceClass) {
Piece로 다형성을 구하고자 했으나 getClass 때문에 무너지는 상황이네요.

지금구조에서는 `getClass`를 없애기 어렵다는건 공감하지만, "prnbqk" 등을 도메인 요소로 인정하거나, classType이 아닌 다른 정보로 피스정보를 알수 있도록 하면 어떨까요?

2024-03-22 14:10 UTC, andole98 commented on src/test/java/chess/piece/BishopTest.java
> +class BishopTest {
Bishop에 관한 테스트인데 Space가 없으면 테스트가 안되네요?

2024-03-22 14:10 UTC, andole98 commented on src/main/java/chess/domain/chessBoard/SpaceGenerator.java
> +public interface SpaceGenerator {
구현체가 하나밖에 없는데 왜 인터페이스가 필요했을까요?

2024-03-24 17:57 UTC, ehtjsv2 commented on README.md
> +### 기능 요구 사항
감사합니다!

2024-03-24 17:57 UTC, ehtjsv2 commented on src/main/java/chess/ChessMachine.java
> +            String command = fromTo.get(0);
Command클래스 생성하고 scanner.next()를 활용해서 게임 진행에 대한 코드를 매끄럽게 바꿔보았습니다!

2024-03-24 17:58 UTC, ehtjsv2 commented on src/main/java/chess/domain/chessBoard/ChessSpaceGenerator.java
> +        return spaces;
아무래도 Position이 file의 for문 rank의 for문 각각 두개 해야되다보니 2중for문이 불가피할 것 같은데 방법을 좀 더 찾아보고 수정해보겠습니다.

2024-03-24 18:09 UTC, ehtjsv2 commented on src/main/java/chess/domain/chessBoard/PieceGenerator.java
> +    public static List<Piece> makeSpecialPieces(Color color) {
인스턴스화 하지 않고 사용하다 보니 객체라고 보기에는 어려울 것 같습니다.

코드 작성 당시에는 크게 생각안하고 작성했던 코드였습니다.

지금 생각해보니, PieceGenerator는 처음 체스판을 생성하는 당시에만 사용됩니다.

그렇기 때문에 프로그램 실행 중 메모리에 계속 들고있게되는 static은 좋은 코드는 아닌 것 같습니다.

2024-03-24 18:13 UTC, ehtjsv2 commented on src/main/java/chess/domain/chessBoard/PieceGenerator.java
> +    public static List<Piece> makePawnPieces(Color color, int amount) {
처음에는 체스확장판인 그레이트체스(?)를 생각하고 만든 amount였습니다.

하지만 기존 규칙에서 amount를 이렇게 수정가능하게 두는 방법은 에러의 위험이 있다는 생각이 드네요.

만약 확장가능하게 했을 것이라면 PieceGenerator를 인터페이스로 두고 OriginalRule에 대한 구현체로 makePawnPieces(Color color)가 더 좋을 것 같습니다.

amount삭제하겠습니다!

2024-03-24 18:15 UTC, ehtjsv2 commented on src/main/java/chess/domain/chessBoard/Space.java
> +import chess.view.PieceSign;
getter를 안쓰려고 하다보니 도메인이 뷰로직(PieceSign)에 의존하고 있던 것 같습니다.

콘솔출력을 위한 getter은 불가피하다고 생각하여 도메인로직에서만 getter를 안쓰도록 조심하고 출력에는 get을 쓰도록 수정하겠습니다.

2024-03-24 18:19 UTC, ehtjsv2 commented on src/main/java/chess/domain/chessBoard/Space.java
> +        if (piece.getClass() == Knight.class) {
맞습니다. Piece로 캡슐화를 했지만 현재 코드로 캡슐화가 되어있다고 보기 어렵게 됐네요.

validateClearRoute 메서드는 현재위치에서 tartgetSpace까지의 루트에서 방해될만한 피스가 루트상에 없는 지 체크하는 함수입니다.

하지만 Knight는 route생성 시 route가 추가 되지않도록 되어있습니다. 따라서 if()를 하지않고 밑의 코드가 실행되어도 예외를 발생시킬일이 없습니다.

if문을 삭제하도록 하겠습니다!

2024-03-24 18:21 UTC, ehtjsv2 commented on src/main/java/chess/domain/chessBoard/Space.java
> +    public void movePiece(Space targetSpace, List<Space> spaces) {
- 본인의 룰을 가지고 있는 것은 piece이다.
- 그 rule로 갈 수 있는 곳을 정한다. → 갈 수 있는 곳을 알려면 모든 체스판의 상황을 알고 있어야한다.
- piece로 체스판의 상황을 가지고 있는 piece를 보내는 것으로 생기는 순환참조는 어쩔 수 없는 부분인 것 같다.

라고 생각하며 어쩔 수 없다고 생각하며 구현했습니다.

하지만 타겟까지의 루트를 구하는 것은 아래에 맡기고 ChessBoard에서 해당 루트에 피스가 있는 지 확인하는 것으로 바꿀 수 있을 것 같습니다.

List<Space>가 있는 ChessBoard에서 할 수 있도록 코드 수정했습니다!

2024-03-24 18:22 UTC, ehtjsv2 commented on src/main/java/chess/domain/chessBoard/Space.java
> +                validateRouteHasPiece(route, space);
위 코멘트에서 답했습니다!

2024-03-24 18:23 UTC, ehtjsv2 commented on src/main/java/chess/domain/chessBoard/Space.java
> +        return piece.isSameColor(new EmptyPiece());
읽어보았지만, 한번에 이해가 되지않네요..

리뷰요청을 오늘안에 해야할 것 같아 다시 제대로 읽어보고 다음 리뷰요청전에는 꼭 적용시켜보겠습니다!

2024-03-24 18:25 UTC, ehtjsv2 commented on src/main/java/chess/domain/piece/Piece.java
> +    private final Rule moveRule;
rule을 자유롭게 구성하도록 열어주고 메소드명에 의미를 부여함으로써 가독성이 더 좋게 만들 수 있을 것 같습니다.

수정했습니다!

2024-03-24 18:26 UTC, ehtjsv2 commented on src/main/java/chess/domain/position/PositionDifference.java
> +    public boolean isObeyRule(Rule rule) {
이미 만들어진 PositionDifference를 활용해야겠다는 생각에 순환참조를 생각하지 못하고 구현한 것 같습니다.

순환참조가 꼭 필요하다면 사용하겠지만, 이 부분은 순환참조 없이 구현 가능합니다! 수정하겠습니다.

2024-03-24 18:26 UTC, ehtjsv2 commented on src/main/java/chess/domain/position/Difference.java
> +public abstract class Difference {
file과 rank를 엄격하게 구분하기 위해 만들었습니다!

현재코드는 FileDifference나 RankDifference 둘 다 int형 difference만 넣으면 생성된다는 점에서 염격하게 구분하고 있다고 보기는 어려운 것 같습니다.

FileDifference와 RankDifference생성자에서 (FIle from, File to)를 받아서 생성하는 것으로 변경했습니다.

2024-03-24 18:33 UTC, ehtjsv2 commented on src/main/java/chess/domain/position/Position.java
> +        return new Position(File.of(fileName),Rank.of(rankName));
Command를 생성하고 scanner.next()를 활용하여 inputView에서 바로 fromPosition과 toPosition을 생성하도록 변경했습니다!

2024-03-24 18:36 UTC, ehtjsv2 commented on src/main/java/chess/domain/position/Rank.java
> +
시간에 가장 쫓기며 구현했던 부분인데, 아무래도 이해하기 힘든 로직이라고 생각합니다.

이 로직을 완전 바꾸기에는 설계를 처음부터 바꾸어야 할 것 같아서 적절한 메소드 분리와 메서드명으로 최대한 이해가능하도록 바꾸어 보았습니다.

2024-03-24 18:39 UTC, ehtjsv2 commented on src/main/java/chess/view/PieceSign.java
> +            if (piece.getClass() == value.pieceClass) {
- [ ]  

PieceSign은 삭제하고 도메인에 PieceType을 생성했습니다.

Piece는 PieceType을 멤버로 가지고 있도록 변경했습니다.

view에서는 pieceType을 확인 후, 알맞은 출력을 하게 했습니다.

이후 도메인에서도 PieceType로 피스정보를 원활하게 확인할 수 있게 됐습니다.

2024-03-24 18:39 UTC, ehtjsv2 commented on src/test/java/chess/piece/BishopTest.java
> +class BishopTest {
맞습니다. 지금의 코드는 Space에 의존적인 테스트였네요..

각 피스 본인이 가지고 있는 isMovable로 테스트 하도록 변경했습니다!

2024-03-24 18:49 UTC, ehtjsv2 commented on src/main/java/chess/domain/chessBoard/SpaceGenerator.java
> +public interface SpaceGenerator {
첫번째로, 클래스를 제어가능한 상태로 만드는 것은 중요하다고 생각합니다.

이 생각이 처음 든 것은 이전 미션에서 테스트 코드를 작성할 때 입니다.

제어할 수 없는 클래스의 메서드를 테스트하기 위해서는 기능 세부구현에 의존적이게 테스트를 구성해야 했고, 리팩토링 할 때마다 자주 깨지는 테스트가 만들어졌습니다.

제어가 가능하게 만들어지면 이전보다 테스트가 세부구현에 의존적이지 않을 수 있다고 생각합니다.

현재 체스판도 비슷한 경우라고 생각했습니다.

현재 SpaceGenerator로 체스판을 생성함으로써, 테스트 시 체스판의 여러 상황에 대하여 테스트할 수 있을 것입니다. (익명 클래스를 활용하여. 하지만 실제로 이용하고 있지는 않습니다.)


그리고 두번째로, 실제로 체스는 여러 확장규칙이 있고 그에 따라 체스말의 초기위치가 바뀌기도합니다.

인터페이스를 작성하는 것이 크게 자원이 드는 것도 아니라고 생각하여 큰 고민없이 바로 인터페이스를 생성했고 구현체로 하나가 생성됐습니다.

요약하면, 테스트용이성을 위하여, 확장가능성을 위하여 입니다!

2024-03-24 19:09 UTC, ehtjsv2 commented
피드백 주셔서 감사합니다!

역시나 많은 곳에서 빈틈이 있었네요..!

Command를 활용하여 게임 진행을 매끄럽게 해보았고

Piece의 캡슐화가 깨지지 않도록 코드를 리팩토링 해보았습니다.

그리고 순환참조가 일어나는 부분들 또한 모두 수정했습니다!

## 궁금한 것

### 예외처리 어느정도 해야할까?
페어프로그래밍을 하다가 의문이 든 부분이 있습니다. 리팩토링 전에는 if검증안에 많은 로직을 실행했었습니다.

하지만 리팩토링을 하면서 “많은 로직 부분”이 private 메소드로 분리가 되었습니다.

아래는 코드 예시입니다.

```java
 public List<Position> findRoute(Position position) {
       ....

        if (files.size() == ranks.size()) {
            ...많은 로직이 들어감; // -> findDigonalRoute로 나중에 분리됨
        }
        ...
    }
```

```java
private List<Position> findDiagonalRoute(List<File> files, List<Rank> ranks);
```

이렇게 됐을 경우 private메서드안에서도 두 size가 같은지 한번 더 예외처리를 해주어야하나요?

대립된의견

의견1: 메소드는 언제든 재사용의 가능성이 있으니 잘못된 재사용은 막아야 하므로 한번 더 검증해야한다.

의견2: 이 private 메소드는 오직 저것만을 위해 생성된 것이므로 검증할 필요 없다.

안돌의 의견이 궁금합니다! 현업에서도 어느정도로 예외처리 하는 지도 궁금합니다!(아무래도 모든 예외를 다 생각하면 끝도 없이 많을 것 같습니다..)

 감사합니다!

2024-03-25 06:04 UTC, andole98 commented on src/main/java/chess/domain/chessBoard/SpaceGenerator.java
> +public interface SpaceGenerator {
> 하지만 실제로 이용하고 있지는 않습니다 
> 실제로 체스는 여러 확장규칙이 있고 그에 따라 체스말의 초기위치가 바뀌기도
> 터페이스를 작성하는 것이 크게 자원이 드는 것도 아니라고 생각하여 큰 고민없이 바로 인터페이스를 생성

현재 그렇지 않은데 미리 만들어두어서 좋은것은 무엇일까요? TDD를 연습하고 계신게 맞는지 궁금하네요.

2024-03-25 06:18 UTC, andole98 commented
> 예외처리 어느정도 해야할까? private메서드안에서도 두 size가 같은지 한번 더 예외처리를 해주어야하나?

예외처리보다는 private 메서드 정체에 대한 얘기 같아요. 상당히 핵심적인 주제입니다.

oop 개념을 제시한 앨런케이는, 핵심은 메시지다([The big idea is "messaging"](https://wiki.c2.com/?AlanKayOnMessaging)) 라고 말한적 있어요. [설명](https://www.enjoyalgorithms.com/blog/message-passing-oops) private 메서드도 자기자신에 대한 메시지라고 볼 수 있느냐 따라 의견1/2가 갈릴것 같네요.

제가 경험한 현업에서는 private 메서드를 subroutine으로 취급하는 경우가 99%였어요.

나머지는 디자인 잘 하시는 분들이나 좀 친다는 분들의 케이스로 private 메서드 자체가 거의 없는 경우였던것 같아요. 고작해야 동작에 이름을 붙이기 위한 메서드 정도?

제 기준에서는 질문한 내용과 같은 생각이 든다는 것 자체가 역할분리 시그널이라고 느껴집니다. A 객체 내에서 이런저런 기능을 수행하기 위해 다른 맥락의 무언가를 extract해야 한다? 그것이 method extract가 맞나? object extract가 되어야 하는거 아닌가?

2024-03-25 08:24 UTC, ehtjsv2 commented on src/main/java/chess/domain/chessBoard/Space.java
> +        return piece.isSameColor(new EmptyPiece());
```Java
 public boolean hasPiece() {
        return !piece.isSameColor(Color.EMPTY);
    }
```
일단 이런 방식으로도 변경가능해서 이렇게 변경했습니다!

2024-03-25 08:51 UTC, ehtjsv2 commented on src/main/java/chess/ChessMachine.java
> +            String command = fromTo.get(0);
예시코드를 제가 못봤었네요! MoveCommand라는 클래스를 생성하는 방법을 추천해주셧었군요..

현재는 다른방법으로 했습니다!

2024-03-25 14:34 UTC, andole98 requested changes
piece를 잘 정리해주신것 같아요. Rule 이 사라지니까 Piece의 다형성을 구현하기 더 쉬워진 것 같아요.

Space와 Position이 반복문을 두번 만들게끔 하는 형태는 다음 스텝에서 정리가 필요할 것 같아요.

프로젝트에 컴파일 오류가 있어요. 컴파일 오류 해결하시고 리뷰요청하시면 머지하도록 하겠습니다.

2024-03-25 14:34 UTC, andole98 commented on src/main/java/chess/domain/chessBoard/ChessBoard.java
> +        for (Position route : routes) {
반복문이 중첩되는 케이스가 여러번 발견되네요. `Space`가 이차원 정보를 flat하게 해주는듯 하지만 그렇지 못한점이 아쉽네요.

다음 스텝을 진행하면서 정리하면 좋을것 같아요.

2024-03-25 14:34 UTC, andole98 commented on src/main/java/chess/domain/chessBoard/ChessBoard.java
> +    }
고수준에서는 어색함 없이 잘 정리된 것 같네요.

2024-03-25 14:34 UTC, andole98 commented on src/main/java/chess/domain/chessBoard/PieceGenerator.java
> +        for (int i = 0; i < 8; i++) {
magic number

2024-03-25 14:34 UTC, andole98 commented on src/main/java/chess/domain/chessBoard/Space.java
> +            targetSpace.piece = piece;
이 조건문은 굉장히 어렵네요. 메서드로 분리해보면 좋을것 같아요.

2024-03-25 14:34 UTC, andole98 commented on src/main/java/chess/domain/piece/Piece.java
> +
`canMove`, `canCatch` 는 어떤가요? is + able도 자주 쓰이지만 조동사 표현이 더 명확한 뉘앙스인것 같아요.

2024-03-25 14:34 UTC, andole98 commented on src/main/java/chess/view/OutputView.java
> +        for (int j = 0; j < CHESS_BOARD_WIDTH; j++) {
interator에 i / j는 관용적으로 많이 쓰이지만, 지금 같은 경우에는 도메인 용어를 써도 좋을것 같아요.

```java
for (int width = 0; width < CHESS_BOARD_WIDTH; widget++) {
        
}

or

for (int rank = 0; rank < CHESS_BOARD_WIDTH; rank++) {

}
```

2024-03-25 14:34 UTC, andole98 commented on src/test/java/chess/chessBoard/SpaceTest.java
> +        assertThat(space1.doesNotHavePiece()).isTrue();
여기서 컴파일이 깨지네요

2024-03-25 14:34 UTC, andole98 commented on src/test/java/chess/chessBoard/SpaceTest.java
> +        assertThat(space.doesNotHavePiece()).isTrue();
여기도 컴파일 오류네요. 안정된 버전이 아니면 머지하기 어렵습니다ㅠ

인텔리제이에서 커맨드 F9나 build project를 하면 미리 컴파일 에러를 볼 수 있습니다.

습관적으로 테스트를 돌리는게 여러모로 도움됩니다.

2024-03-26 06:25 UTC, ehtjsv2 commented on src/main/java/chess/domain/chessBoard/SpaceGenerator.java
> +public interface SpaceGenerator {
항상 기능요구사항 먼저보고 테스트 작성하고 기능을 구현하고있습니다. 

하지만 한 가지 요구사항에 대하여 하위 기능이 예상치 못하게 생길 때가 있습니다. 

그럴 때,그  하위 public 메소드에 대한 테스트 생성을 놓치는 경우는 종종 있습니다..

안돌께서 이 질문에서 어떤 의미로 TDD를 연습하고 있는것이 맞는 지 궁금하다고 한지는 의도를 잘 모르겠습니다...

</br>

저는 이 인터페이스를  확장되는 규칙에 관해서만 적용한 것은 아닙니다.

> 테스트 시 체스판의 여러 상황에 대하여 테스트할 수 있을 것입니다.
> 
실제로 기본룰만을 가지고 서비스를 시작하게됐고, 사용자가 체스 사용중 어떤 상황에서 버그가 발생했다고 가정하겠습니다.

인터페이스로 구현하지 않았다면, 그 상황을 만들기 위해 저는 move함수를 여러번 사용하며 상황을 구성해서 테스트를 진행해야 합니다.

하지만 인터페이스가 적용되어있다면, 체스판 생성이 제어하기 편하여 상황을 구성하기 쉽게 됩니다.

크게 시간이 드는 작업도 아니고, 나중에 규칙이 확장되어 그제서야 적용했을 때, 그에 따른 리팩토링이 여러 곳에서 발생하는 것보다 지금 적용해도 되겠다고 생각했습니다.

혹시 안돌이 생각하시는 적용하면 안좋은 이유같은 것이 있을까요?

2024-03-26 06:43 UTC, ehtjsv2 commented on src/main/java/chess/domain/chessBoard/ChessBoard.java
> +        for (Position route : routes) {
모든 곳에서 indent 1지키는 것을 적용하도록 수정했습니다!

2024-03-26 06:44 UTC, ehtjsv2 commented on src/main/java/chess/domain/chessBoard/PieceGenerator.java
> +        for (int i = 0; i < 8; i++) {
이 부분 포함해서 매직넘버 있는 지 확인하고 수정했습니다!

2024-03-26 06:44 UTC, ehtjsv2 commented on src/main/java/chess/domain/chessBoard/Space.java
> +            targetSpace.piece = piece;
메서드 분리로 각각 의미가 더 정확하도록 수정했습니다!

2024-03-26 07:34 UTC, ehtjsv2 commented
좋은 글 추천 감사합니다!(이런 글은 어떻게 찾아오시는건지..신기..)

private메서드가 거의 없도록 클래스 분리가 가능하다니 신기하네요!

이번에 Position 클래스가 루트를 찾는 기능까지 하기에는 역할이 많나 싶어서 RouteFinder라는 클래스를 만들어 보았습니다!

하지만 결국 File과 Rank를 Position이 가지고 있기 때문에 getter없이는 완성시키지 못한다고 생각하여 다시 돌려놓았습니다..

---
컴파일 오류가 있었다니,, 죄송합니다,,

2024-03-26 09:07 UTC, andole98 commented on src/main/java/chess/domain/chessBoard/SpaceGenerator.java
> +public interface SpaceGenerator {
인터페이스 자체에 대한 이야기보다는 구현에 관한 이야기로 봐주시면 좋을것 같아요. 제가 코멘트를 남긴 의도는 도도가 이야기한 장점을 코드로 보여달라는 것에 가깝습니다. 지금 그 장점이 필요하다 느낀다면 추가하고 아니라면 없는것이 낫겠다는 이야기에요.

도도가 얘기한건 맞는 말이에요. 나쁠건 없죠. 제가 말하고 싶은건 관심사의 분리 에 가까워요.

도도가 이야기한건 현재 코드에 없어요. 인터페이스 대신 ChessSpaceGenerator 클래스만 있어도 현재는 아~무 이슈가 없을것 같아요. 

우리가 연습하려는 TDD 사이클은 이런것 아닌가요?

- 내가 해야 하는 것은 Space들을 만드는 것이다. -> 테스트 작성

- 테스트를 통과를 위한 최대한의 집중, 나머지 배제

- 테스트 통과 이후 새로운 목적 설정 (테스트가 좀더 쉬워지면 좋겠어, 초기세팅이 아닌 경우도 테스트할수 있으면 좋겠어 등 도도가 말한 이야기들)

continue

이런 싸이클보다는 Space에 대해 머릿속으로 "미리 구현"해놓고 코딩하고 있지 않는지 생각해보세요.

이런이런 장점이 있으니까 이렇게 구현하면 좋겠지?

무슨 차인데? 라고 묻는다면, 

- 복잡함을 다루는 방법
의도적으로 관심사를 분리/집중하는 훈련은 문제를 제대로 이해하고 필요한 것을 찾아내고 우선순위를 매길 수 있게 합니다. 일을 잘하기 위한 필요조건입니다.

- 기능적으로
더더더더 복잡한 도메인을 "미리 구현" 해놓고 버그없이 잘 돌아가길 "기도"하는게 괜찮다면 별 문제 없는것 같아요.

테스트가 있다고 하더라도 "미리 구현"된 내용을 테스트하게 됩니다. 당연히 통과되는 테스트만 만들어져요. (훨씬 복잡한 도메인입니다. 내 자신의 인지를 넘어선 테스트가 거의 불가능함)

- 디자인/설계적으로
머릿속에 "미리 구현"되어 있기 때문에 역할/타입분리 / 사용패턴 / 레이어 등 갖가지 관심사들이 섞이게 됩니다. 재사용성이 떨어지고 품질낮은 컴포넌트가 구현될 가능성이 높아요. 또 개인에 따라 일관성 없는 구현이 나올 확률이 높아요.

- ... 기타등등

우리가 체스게임을 만들어보고 그 코드에 대해 이야기해보는것은 "훈련" 또는 "연습"에 가까운것 같아요. 도도가 구현한 체스게임을 실제로 사용하거나... 가치를 매기는게 아니니까요.

쉽지 않다는것에는 정말 공감해요. 그렇기에 저런 코멘트도 남기면서 리마인드한다고 보면 좋을것 같아요.

2024-03-26 11:36 UTC, andole98 commented on src/main/java/chess/domain/chessBoard/ChessBoard.java
> +        for (Position route : routes) {
indent를 잘 줄여주셨네요. 다만 매번 모든 element를 순회해서 filter하는 방법보다 더 효율적인 방법이 있을지 고민해봐 주시면 좋을것 같아요.

2024-03-26 11:45 UTC, andole98 approved these changes
처음 구현에 비해서 piece의 구현이 정말 좋아졌네요.

고생 많았습니다. 다음 스텝도 화이팅하세요~

2024-03-26 11:45 UTC, andole98 commented on src/main/java/chess/domain/position/File.java
> +                .orElseThrow(IllegalArgumentException::new);
에러를 던질때 메시지도 고려하시면 좋을것 같아요.

2024-03-26 11:45 UTC, andole98 commented on src/main/java/chess/domain/position/Position.java
> +        }
```suggestion
            positions.add(new Position(files.get(i), ranks.get(i)));
```

2024-03-26 11:45 UTC, andole98 commented on src/main/java/chess/domain/position/Position.java
> +        }
intellij에서 본인의 환경에 맞는 code format하는 방법을 찾아보고 적용해보세요.

2024-03-26 11:45 UTC, merged