[1, 2단계 - 체스] 타칸(최원준) 미션 제출합니다.
woowacourse/java-chess pull request #689
Opened 2024-03-21 08:35 UTC by jhon3242

안녕하세요 찰리! 🙋‍♂️
타칸이라고 합니다! 잘부탁드립니다!!🙇‍♂️

## 기능 명세

### MoveStrategy
입력으로 들어온 시작 위치 `Position`를 이용하여 `Board`에서 기물을 조회합니다.
각 기물은 `PieceType`을 가지고 있고, `MoveStrategy` 는 `이동 방향`과 `가중치`를 가지고 있습니다.

`MoveStrategy` 구현체는 각각 정의된 이동 방향과 가중치를 이용하여 현재 위치에서 이동할 수 있는 모든 후보 좌표들을 반환합니다.
`ChessGame` 클래스는 `Board`를 가지고 있으며 반환받은 후보 좌표를 이용하여 해당 좌표가 실제로 이동할 수 있는 위치인지 판단하고, 이동할 수 없는 위치들을 걸러냅니다. (장애물, 목표가 우리 팀 기물인지)

이후 입력으로 받은 목표 위치가 실제로 이동할 수 있는 위치에 포함된다면 `board`의 `move` 메서드를 호출하여 기물을 이동시킵니다.
이런 방식으로 구현한 이유는 저와 페어 모두 실제 온라인 체스 게임을 상상하며, 특정 기물을 클릭했을 때, 실제로 이동할 수 있는 포지션이 초록색 칸으로 표시되는 방식을 원했습니다. 콘솔 게임에서 실제 웹 프로젝트로 변경될 경우를 많이 고려했던 것 같습니다.

### 기물 이동 처리 방식
이번 2단계까지의 요구사항에서 핵심 기능은 기물을 이동시키는 것이라고 생각합니다.
그래서 기물의 이동을 어떻게 처리할지 고민이 많았습니다.

맨 처음에는 각 기물한테 본인이 갈 수 있는 경로를 물어보고 가져오는 방식을 생각했었습니다.
그러나 본인이 갈 수 있는 경로를 가져오기 위해서는 체스판의 상황에 따라 달라졌습니다.
즉, 본인이 갈 수 있는 경로를 가져오기 위해서는 기물(`Piece`)이 체스판(`Board`)을 알아야 하는 상황이었습니다.
기물이 체스판을 알아야 하는 것이 어색하다고 느껴져서 이 방식을 채택하지 않았습니다.

그래서 저희가 선택한 방식은 우선 기물마다 현재 위치를 받으면 그 위치를 기반으로 기물의 이동 가능할 수 있는 경로를 전부 가져오도록 하였습니다.
(예를 들어서 룩한테 `generateMovablePositions(B4)` 와 같이 호출하면 체스판의 상황과 상관없이 체스판을 넘지 않는 모든 경로를 이동 순서대로 가져오도록 했습니다. 
이 경우에는 
* B3~B1, 
* C4~H4, 
* B5~B8, 
* A4 
를 가져올 것입니다.)

그리고 해당 값을 `Map` 자료구조로 가져와서 `ChessGame` 에서 체스판(`Board`)를 확인해 보면서 실제로 이동할 수 있는 경로를 필터링하도록 구현하였습니다.

## 마무리
이번 체스 미션은 개인적으로 가장 시간이 부족한 미션이었습니다.
이번 미션 주제가 OOP 인 만큼 객체마다 적절한 책임을 가지고 있는가에 대해서 고민을 조금 해봤는데 아직은 어색한 것 같습니다ㅠ
리팩터링 할 부분도 많이 보이는 데 시간 관계상 하지 못한 부분이 많습니다..😭
계속 찾아보면서 수정해 보겠습니다. 긴 글과 코드를 읽어주셔서 감사합니다!😊

2024-03-21 13:57 UTC, Gomding requested changes
안녕하세요 타칸!
체스미션 함께하게된 찰리입니다 🙇 
구현하느라 고생하셨어요~

몇 가지 코멘트 남겼으니 확인해주세요 🙏 

궁금한 점 있으면 언제든 DM이나 코멘트 남겨주세요!

2024-03-21 13:57 UTC, Gomding commented on src/main/java/chess/controller/ChessGameController.java
> +    private final ChessGame chessGame = new ChessGame(new Board());
ChessGameController 가 ChessGame 이라는 상태를 가져도 괜찮을까요? 🤔 

지금은 사용자 한명만 진행하는 서비스라서 문제가 없어요!

만약 동시에 여러명이 사용하는 서비스라면 
여러 사용자가 하나의 ChessGame을 공유하거나 
사용자마다 ChessGameController 객체를 새로 생성해줘야해요!

ChessGameController 는 View와 Domain 간에 소통을 담당하는 만큼 상태없이 하나만 만들어두고 사용하는것이 좋다고 생각해요~

2024-03-21 13:57 UTC, Gomding commented on src/main/java/chess/domain/Board.java
> +        initializeWhiteTeam();
Board를 생성하기 위한 로직구현이 쉽지않았죠.. 😓

그만큼 코드량도 많은데요
Board의 행위에 집중할 수 있게 Board를 생성하는 객체를 분리해보면 어떠신가요!
물론 취향차이라서 Board에 생성 로직이 있어도 괜찮습니다~

```java
public class BoardInitilizer {
    private BoardInitilizer() {}

    public static Board initialize() {
        initializeBlackTeam();
        initializeWhiteTeam();
    }
}
```

이렇게 하면 장점은 Board 클래스에 생성을 위한 로직은 사라지고 행위에 대한 로직만 남아요.
이로 인해 가독성이 좋아진다고 생각해요!

2024-03-21 13:57 UTC, Gomding commented on src/main/java/chess/domain/CandidatePositions.java
> +public class CandidatePositions {
현재는 사용하지 않는 클래스군요 🤔 

리팩토링 시도의 흔적일까요 😃

2024-03-21 13:57 UTC, Gomding commented on src/main/java/chess/domain/Direction.java
> +    NNW(-2, -1);
방향을 표현한 요소들 👍 💯

2024-03-21 13:57 UTC, Gomding commented on src/main/java/chess/domain/Piece.java
> +    private final PieceType pieceType;
각각의 Piece들을 객체가 아닌 PieceType으로 표현해주셨군요!

Piece를 추상화하여 구현체들을 만드는 방식도 있었을텐데
타칸의 구현에는 어떤 장단점이 있으셨나요?

2024-03-21 13:57 UTC, Gomding commented on src/main/java/chess/controller/ChessGameController.java
> +        chessGame.movePiece(movablePositions, from, to);
Line 72 ~ 73 은 도메인 로직이라고 느껴져요!
(사실 69, 70 도 약간 도메인이 섞여있는 느낌이 들어요)

ChessGame 내부에서 처리해보면 좋겠어요~

2024-03-21 13:57 UTC, Gomding commented on src/main/java/chess/domain/strategy/MoveStrategy.java
> +public interface MoveStrategy {
움직임을 전략 객체로 만들어주신점 👍

2024-03-21 13:57 UTC, Gomding commented on src/main/java/chess/domain/ChessGame.java
> +        if (piece.isPawn()) {
폰인지 물어봐야하는 점이 조금 아쉬워요 😢 
ChessGame을 보면 말을 움직이기 위한 로직들이 들어있는데요
이로인해 ChessGame의 책임이 많아진것으로 보이네요!

moveStrategy를 더 다양하게 활용해보거나
추상화를 이용해서 ChessGame에서는 piece가 어떤것인지 모르고 움직이라는 명령만 내리면 좋겠어요!

2024-03-21 13:57 UTC, Gomding commented on src/main/java/chess/view/PieceMapper.java
> +    BLACK_PAWN(PieceType.BLACK_PAWN, "P"),
view 와 도메인 분리를 위한 Mapper 👍

2024-03-21 13:57 UTC, Gomding commented on src/main/java/chess/controller/ChessGameController.java
> +    private void handleMoveCommend(Board board, List<String> commendValues) {
chess 에는 턴제라는 개념이 있으니 턴을 번갈아가며 사용할 수 있게끔 강제해주면 좋겠어요!

현재는 한쪽(White 또는 Black)이 두 번 연속 기물을 이동하는것이 가능하네요 😎

2024-03-21 13:57 UTC, Gomding commented on src/main/java/chess/controller/ChessGameController.java
> +    private void handleMoveCommend(Board board, List<String> commendValues) {
view -> controller 로 명령어 정보를 보낼 때
형태를 알맞게 변경해주면 좋겠어요!
```java
public class MoveRequest {
    private final String fromRow;
    private final String fromColumn;
    private final String toRow;
    private final String toColumn;
}
```

물론 이건 타칸이 정하기 나름이라 넘어가셔도 됩니다~!

2024-03-23 08:51 UTC, jhon3242 reviewed
안녕하세요 찰리~ 타칸입니다!!😁
이번에 찰리가 주신 리뷰를 반영하면서 리팩터링을 진행했었습니다.
그러다가 한 가지 고민거리가 발생했습니다.

## 패키지의 분리
현재 클래스들이 많이 발생하다 보니 패키지를 분리해 줄 필요성이 보였어요. 그래서 비슷한 성격을 가진 클래스들끼리 묶어서 패키지로 만들어주어 봤습니다. 그런데 그렇게 되면 서로의 패키지를 순환 참조하는 경우가 자주 발생하게 되더라고요. 패키지끼리 순환 참조는 지양하는 게 맞다는 생각에 결국 원래 패키지 구조대로 되돌아오게 되었습니다.

순환 참조를 지양하는 이유는 패키지 단위로 릴리즈를 할 때 순환 참조를 하게 되는 경우 서로의 패키지가 강력하게 결합되어 결국 패키지를 분리하는 의미가 사라진다고 알고있습니다.

그런데 순환 참조를 하지 않으려면 하나의 패키지 안에 너무나 많은 클래스들이 들어가게 되어야 하고 이러면 클래스들을 분리해줄 수는 없는건가? 라는 의문이 들었습니다.

패키지를 비슷한 성격의 클래스들을 모아두기 위한 하나의 "폴더" 와 같이 활용하면 안되는것인지 궁금합니다!

2024-03-23 08:51 UTC, jhon3242 commented on src/main/java/chess/controller/ChessGameController.java
> +    private final ChessGame chessGame = new ChessGame(new Board());
동의합니다! 사용자마다 상태가 달라야한느 객체가 아닌 경우라면 매번 객체를 초기화 해줄 필요가 없어보여요!
메서드 안에서 객체를 생성하는 방식으로 리팩터링 해보겠습니다!

추가로 지금 뷰는 컨트롤러안에서 객체를 생성하고 있는데, 상태를 가지는 것이 아니면 static으로 사용해보는 것도 좋을 것 같아요!

2024-03-23 08:51 UTC, jhon3242 commented on src/main/java/chess/controller/ChessGameController.java
> +        chessGame.movePiece(movablePositions, from, to);
동의합니다! ChessGame 에서 처리할 수 있는 부분인데 ChessGameContrller 에 있는 느낌이 강하게 듭니다.
이러면 `ChessGame` 와 `ChessGameContrller` 를 구분하는 기준이 모호해질 것 같아요! 리팩터링 해주겠습니다!

2024-03-23 08:51 UTC, jhon3242 commented on src/main/java/chess/domain/Board.java
> +        initializeWhiteTeam();
안그래도 초기화 로직이 많다고 느꼈었는데 보드 생성 로직을 분리하면 좋을 것 같아요! 감사합니다!!😊

2024-03-23 08:51 UTC, jhon3242 commented on src/main/java/chess/domain/ChessGame.java
> +        if (piece.isPawn()) {
> 추상화를 이용해서 ChessGame에서는 piece가 어떤것인지 모르고 움직이라는 명령만 내리면 좋겠어요!

동의합니다! piece 가 폰인지 판단하는 로직까지 ChessGame 에 남게 되면서 코드가 더 많아진 것 같아요.. 리팩터링 해주겠습니다!

2024-03-23 08:51 UTC, jhon3242 commented on src/main/java/chess/domain/Piece.java
> +    private final PieceType pieceType;
우선 장점은 다음과 같을 것 같아요.
1. 전략을 쉽게 갈아끼울 수 있기 때문에 유지보수에서 이점을 챙길 수 있다.
2. 각 기물별로 객체를 생성하지 않아도 되어서 코드의 복잡성이 줄어들 수 있다.

현재 단계에서는 각 기물들의 차이점은 "움직임 전략" 뿐이라고 느꼈어요.
그래서 각 기물들을 객체로 만들어줄 필요가 없어보였고, 그 결과 PieceType Enum 을 활용한 방식을 선택하였습니다.

하지만 단점으로는 다음과 같을 것 같아요.
1.  기물마다 다른 타입의 상태를 가지는 경우 활용할 수 없다.
2. 특정 기물에만 필요한 메서드가 발생하는 경우 문제가 발생한다.

지금 제가 생각하기에는 이러한 장단점이 있는 것 같아요. 
요구사항이 자주 변경되는 상황에서는 확실히 PieceType 의 장점을 활용하는 것보다는 단점으로 얻는 불이익이 더 클 것 같다고 생각이 드네요🧐
혹시 놓친 장단점이 있다면 첨언 부탁드립니다!

2024-03-23 12:53 UTC, Gomding commented on src/main/java/chess/controller/ChessGameController.java
> +    private final ChessGame chessGame = new ChessGame(new Board());
> 지금 뷰는 컨트롤러안에서 객체를 생성하고 있는데, 상태를 가지는 것이 아니면 static으로 사용해보는 것도 좋을 것 같아요!

요것도 조금 의견을 드리자면..! (해당 부분 반영은 필수 아닙니다!)
객체 필드에서 바로 초기화하는것과 생성자에서 받는것에는 어떤 차이가 있을지 고민해보면 좋겠어요!
(또는 static 객체를 사용하면 의존이 얼마나 강해지는지도 함께 고민해보구요 😃 )

static 객체를 사용한다는 것은 추상화하는것도 쉽지않고, 강한 의존이 생겨서 유연하지 않은 코드가 된다고 생각합니다 :)

조금 억지스러운 예시를 들어보자면 ㅎ..
체스게임을 콘솔 입출력, 웹 입출력 둘 다 서비스하고 싶은데
현재 ChessGameController 로는 웹 입출력으로 넘어가기 위해서는 고쳐야할 부분들이 많을것같아요!
InputView와 OutputView가 static 으로 강하게 결합되어있고 다른 방식의 InputView와 OutputView로 바꿔서 사용하기가 어려우니까요!
반면에 ChessGameController의 생성자에서 InputView와 OutputView 객체를 주입받아본다면 InputView와 OutputView를 추상화만 해두면 언제든 다른 구현체로 갈아끼워볼 수 있겠죠?

```java
public class ChessGameController {
    public ChessGameController(InputView inputView, OutputView outputView) {
        this.inputView = inputView;
        this.outputView = outputView;
    }
}
```

다시 한 번 말씀드리지만 그냥 의견일 뿐 현재 단계에서는 굳이 받영하지 않으셔도 됩니다 ㅎ,..!
타칸이 충분히 공감하고 필요성을 느낀다면 반영하셔도 됩니다 😃

2024-03-23 14:25 UTC, Gomding requested changes
안녕하세요 타칸!
ChessGame내부에서 Piece가 Pawn인지 확인하던 부분을 깔끔하게 제거해주셨네요 👏 👏 
몇 가지 코멘트 남겼으니 확인해주세요!

궁금한 점 있으면 언제든 편하게 코멘트나 DM 남겨주세요~

2024-03-23 14:25 UTC, Gomding commented on README.md
> ### 패키지의 분리
> 현재 클래스들이 많이 발생하다 보니 패키지를 분리해 줄 필요성이 보였어요. 그래서 비슷한 성격을 가진 클래스들끼리 묶어서 패키지로 만들어주어 봤습니다. 그런데 그렇게 되면 서로의 패키지를 순환 참조하는 경우가 자주 발생하게 되더라고요. 패키지끼리 순환 참조는 지양하는 게 맞다는 생각에 결국 원래 패키지 구조대로 되돌아오게 되었습니다.
> 
> 순환 참조를 지양하는 이유는 패키지 단위로 릴리즈를 할 때 순환 참조를 하게 되는 경우 서로의 패키지가 강력하게 결합되어 결국 패키지를 분리하는 의미가 사라진다고 알고있습니다.
> 
> 그런데 순환 참조를 하지 않으려면 하나의 패키지 안에 너무나 많은 클래스들이 들어가게 되어야 하고 이러면 클래스들을 분리해줄 수는 없는건가? 라는 의문이 들었습니다.
> 
> 패키지를 비슷한 성격의 클래스들을 모아두기 위한 하나의 "폴더" 와 같이 활용하면 안되는것인지 궁금합니다!

좋은 고민을 하고 계시네요 😃 

>  그런데 그렇게 되면 서로의 패키지를 순환 참조하는 경우가 자주 발생하게 되더라고요. 패키지끼리 순환 참조는 지양하는 게 맞다는 생각에 결국 원래 패키지 구조대로 되돌아오게 되었습니다.

물론 순환 참조를 해결하는 방법이 몇 개 있지만..!
저는 지금 단계에서는 조금 복잡하기도하고 필요한 구현은 아니라고 생각해요 😇

우선은 타칸이 의도한대로 비슷한 성격의 클래스들 끼리 묶어놓는 것만으로
전체 구조를 이해하는데 많은 도움이 될거라고 생각해요 :)

우선 패키지 분리를 반영해주시고
함께 구조 보면서 더 논의해보시죠..! 🏃 
순환 참조 발생하는 부분도 말씀해주시면 더 좋구요 ㅎㅎ

+) 질문. 순환 참조로 인해 발생하는 문제는 어떤것일까요?

2024-03-23 14:25 UTC, Gomding commented on src/main/java/chess/controller/ChessGameController.java
> +        ChessGame chessGame = new ChessGame(new Board());
메서드에서 생성하도록 변경해주셨군요 👍

2024-03-23 14:25 UTC, Gomding commented on src/main/java/chess/view/CommendDto.java
> +public record CommendDto(Commend commend, String from, String to) {
Comm`a`nd 오타가 난듯합니다..! 🦅

2024-03-23 14:25 UTC, Gomding commented on src/main/java/chess/controller/ChessGameController.java
> +        chessGame.handleMove(commendDto, currentTurn);
CommandDto를 만들어주신점 👍 

한가지 아쉬운점은 CommandDto가 도메인까지 들어갔다는 점이에요~!
도메인에서 CommandDto를 의존하게 됐는데 Dto까지 의존해야했을까요? 🤔 

chessGame 의 handleMove 메서드는 결국 위치에 대한 문자열(String) 값이니 해당 값만 넘겨줘도 좋다고 생각해요!
타칸은 어떻게 생각하시나요?

```java
    private void handleMoveCommend(ChessGame chessGame, CommendDto commendDto, Color currentTurn) {
        chessGame.handleMove(commendDto.from(), commendDto.to(), currentTurn);
```

아래 추가한 코멘트와 관련있어 보이네요!
아래 코멘트도 함께 고민하여 반영해주세요!

2024-03-23 14:25 UTC, Gomding commented on src/main/java/chess/domain/Position.java
> +        Column column = ColumnMapper.findByInputValue(positionValue.split("")[INPUT_COLUMN_INDEX]);
여기도 한 가지 아쉬운 것은 RowMapper와 ColumnMapper가 view 객체임에도 도메인이 의존하고 있다는 것인데요..!
이렇게하면 결국 도메인이 view를 알게되는 구조가 형성됐어요 😢 

이걸 리팩터링하는것이 쉽지않아보이는데 도전해보셨으면 좋겠어요!

저는 타칸의 Row, Column 두 enum을 봤을 때 
각각 0~7의 숫자로 판단하고 있는것으로 봤어요

그렇다면 도메인에서 사용하는 0~7 값으로 Controller 에서 도메인으로 넘겨주는게 좋을것같아요 :)
진짜 단순하게 생각한 코드인데 타칸이 더 멋있게 만들어주실거라 믿어요 😎 

```java
public static Position from(int rowIndex, int columnIndex) {
    Row row = Row.findByIndex(rowIndex);
    Column column = Column.findByIndex(columnIndex);
    // ...
}
```

결국 `String positionValue 를 어디서 index값으로 파싱할 것인가?` 가 포인트군요 😃

2024-03-23 14:25 UTC, Gomding commented on src/main/java/chess/domain/Position.java
> +        return Objects.hash(column, row);
equals, hashCode 재정의 👍

2024-03-23 14:25 UTC, Gomding commented on src/main/java/chess/view/CommendDto.java
> +public record CommendDto(Commend commend, String from, String to) {
여기서 약간(X 10_000_000) 아쉬운것은 CommandDto는 start, end, move 모두 사용할 수 있는데도
start 와 end에서는 사용하지 않는 from 과 to 필드가 존재한다는 것이에요 🤔 

null로 초기화 해야한다는 것이 신경쓰이지만..!
타칸이 느끼기에 `Dto에 그 정도로 분리가 필요한가?` 하는 생각이 드신다면 넘어가셔도 좋습니다 ㅎㅎ!
도메인에 더 집중하는것이 중요하니까요!

2024-03-23 14:25 UTC, Gomding commented on src/main/java/chess/controller/ChessGameController.java
> +            turnColor = turnColor.opposite();
턴 규칙 도입해주셨군요! 👍 

![image](https://github.com/woowacourse/java-chess/assets/57378410/74ef50d5-6462-472a-8a80-82722dfd0c27)

turnColor 도 chessGame이 관리해보는건 어떻게 생각하시나요?
현재 턴이라는 개념은 체스 내부의 중요한 도메인으로 생각했어요 😃

2024-03-23 14:25 UTC, Gomding commented on src/test/java/chess/domain/PositionTest.java
> +class PositionTest {
꼼꼼하게 변경해주셨군요 👍

2024-03-23 14:25 UTC, Gomding commented on src/main/java/chess/domain/ChessGame.java
> +        Piece fromPiece = board.findPieceByPosition(fromPosition);
명확한 변수명으로 변경 👍 
가독성이 굉장히 증가했네요 😄

2024-03-23 14:25 UTC, Gomding commented on src/main/java/chess/domain/ChessGame.java
> +            throw new IllegalArgumentException("다른 팀의 기물을 움직일 수 없습니다.");
사용자에게 더 명확한 피드백이 될 수 있게 
예외 메세지에서 현재 턴이 누구인지 알려주면 좋겠어요 😃

2024-03-23 14:25 UTC, Gomding commented on src/main/java/chess/domain/ChessGame.java
> +        }
이쪽 로직이 너무 깔끔하다고 생각되네요 😃 
`filterInvalidPositions` -> 불가능한 위치들은 필터링해주겠다
`while (isEmptySpace(direction, piece, currentPosition)) {` -> 비어있는 공간까지는 계속 가능한 위치로 판단
`if (isEnemySpace(direction, piece, currentPosition)) {` -> 비어있지 않지만 적이 있다면 이동 가능한 위치로 판단

메서드 추출로 각 부분에 이름을 부여해보면 더 좋겠지만 
생각해보니 오히려 로직이 좀 복잡해질것같네요 ㅎ..!

2024-03-23 14:25 UTC, Gomding commented on src/main/java/chess/domain/Piece.java
> +    private final PieceType pieceType;
훌륭하시네요... 💯 💯 💯 💯 

저는 전략패턴으로 만들어주신것도 너무 좋다고 생각합니다 😄 

> 현재 단계에서는 각 기물들의 차이점은 "움직임 전략" 뿐이라고 느꼈어요.
그래서 각 기물들을 객체로 만들어줄 필요가 없어보였고, 그 결과 PieceType Enum 을 활용한 방식을 선택하였습니다.

이걸 생각해보면 깔끔하다는 코드가 간결하여 읽어야할 코드량이 줄어든다는 장점이 느껴졌어요 👍 
실제로 타칸의 코드는 읽어야할 코드량이 많지않다고 느꼈어요 :)

말씀대로 enum으로 구현했을 때 앞으로 변경이 힘들다는것도 인지하고 계시니 훌륭합니다 💯

2024-03-23 14:25 UTC, Gomding commented on src/test/java/chess/domain/chessGame/KnightTest.java
> +class KnightTest {
약간 의문스러운것은..!

기물에 대한 테스트들 (KingTest, KnightTest, QueenTest ... 등등등)은 테스트 내용을 보면 chessGame에 대한 테스트에 가깝다고 생각했어요..!

하지만 각각을 분리하신 것은 가독성을 위해서였겠죠? 👍 👍 👍 👍

2024-03-23 14:25 UTC, Gomding commented on src/main/java/chess/domain/Piece.java
> +        return true;
이런 부분도 Piece 내부에서 PAWN이 노출되어 조금 아쉽긴하네요 😢 
이런것을 위해서 PieceType enum을 각각의 객체로 구분해보는 것도 고민해볼 수 있겠네요..!
타칸은 어떻게 생각하세요?
(절대절대 강요아닙니다! 진짜 의견이 궁금해요!)

2024-03-24 02:47 UTC, jhon3242 commented on README.md
디버깅이 어려울 것 같아요!

패키지가 하나의 캡슐화된 기능을 제공한다 라고 이해하고 있다.

2024-03-24 11:47 UTC, jhon3242 reviewed
안녕하세요 찰리!
꼼꼼한 리뷰 감사합니다~!!
최대한 리뷰 반영해봤는데 좋게 봐주시면 감사하겠습니다!🙇‍♂️

2024-03-24 11:47 UTC, jhon3242 commented on src/main/java/chess/controller/ChessGameController.java
> +            turnColor = turnColor.opposite();
동의합니다! 컨트롤러에서 Color 라는 도메인에 대해서 알 필요가 없을 것 같아요! chessGame 내부에서 관리하는 편이 더 좋을 것 같스빈다!

2024-03-24 11:47 UTC, jhon3242 commented on src/main/java/chess/controller/ChessGameController.java
> +    private final ChessGame chessGame = new ChessGame(new Board());
static 을 사용하면 강력하게 결합된다는 것을 깨달지 못하고 지금까지 많이 사용해왔던 것 같아요.. 생각이 확장된 것 같아요 ㅎㅎ 감사합니다! 😊

그런데 이렇게 확장 가능하게 설계를 할 때마다 YOGNI 법칙에 위배되는 것은 아닌지 스스로 고민하게 되는 것 같아요. 물론 저만의 기준을 찾아가면서 판단을 잘 해야하는 것은 맞지만 명확한 기준을 만들어가는게 어려운 것 같아요. 그래서 매번 방식이 바뀌는 것 같고 통일성을 못지키는 것 같아요.. 😭 

찰리는 어떠한 기준으로 "아 이때는 확장 가능하게 추상화를 해둬야겠다." or "이 확장은 불필요하니까 굳이 추상화를 하지 말아야겠다" 를 판단하는지 궁금합니다!!

2024-03-24 11:47 UTC, jhon3242 commented on src/main/java/chess/domain/ChessGame.java
> +        }
메서드 추출도 고려해봤는데 currentPosition 를 새롭게 할당해주는 부분이 가독성이 떨어진다고 판단했어요!

```java
private List<Position> filterInvalidPositions(Deque<Position> expectedPositions, Direction direction, Piece piece{
        List<Position> result = new ArrayList<>();
        Position currentPosition = expectedPositions.poll();
        currentPosition = filterEmptySpace(expectedPositions, direction, piece, result, currentPosition);
        ...
}
```

매우 간단하게 메서드만 추출하면 위와 같을 것 같아요!
위 코드만 읽었을 왜 `filterEmptySpace` 가 `currentPosition` 를 리턴하는지 이해가 안될 것 같아서 메서드를 추출하지 않았답니다 ㅎㅎ

2024-03-24 11:47 UTC, jhon3242 commented on src/main/java/chess/domain/Piece.java
> +        return true;
동의합니다! 이런 부분 같이 각 기물마다 다른 역할이 늘어나면 늘어날수록 Enum 을 사용하는 장점이 줄어들고 결국 각 기물을 객체로 만드는 방식으로 리팩터링 될 것 같아요! (Step3 나 Step4 에서 아마 바뀔 수 도 있지 않을까.. 싶네요😭)

그런데 위 문제는 지금 단계에서는 간단히 pieceType 에 블랙 폰인지, 화이트 폰인지 물어보는 메서드를 구현하면 간단히 해결해줄 수 있을 것 같아요! 물론 이런 작업들이 많아지면 각 객체로 분리하는게 더 나은 선택이 될 것 같습니다!!👍

2024-03-24 11:47 UTC, jhon3242 commented on src/main/java/chess/view/CommendDto.java
> +public record CommendDto(Commend commend, String from, String to) {
저도 그 부분에 대해서 생각을 해보긴 했는데 좋은 방법이 딱히 떠오르지 않더라고요😅
DTO 를 Record 로 활용해주고 싶은데 Record 는 불변 객체여서 상속도 안되고요..

어떻게 하면 깔끔하게 분리해줄 수 있을까요?? 힌트 부탁드립니다!🙇‍♂️

2024-03-24 11:47 UTC, jhon3242 commented on src/test/java/chess/domain/chessGame/KnightTest.java
> +class KnightTest {
네! ㅎㅎ 처음에는 ChessGame 에 대한 테스트이기 때문에 ChessGameTest 에 넣어주었는데 ChessGameTest 에 너무나 많은 테스트가 발생하더라고요! 그래서 `@Nested` 를 활용해서 구분해줄 방법도 떠오르긴 했었는데 그럴바에는 가독성을 위해 그냥 별도의 클래스로 분리해주는게 낫다는 판단을 했습니다!!

그런데 처음 본 사람들은 찰리가 생각하신 것 처럼 생각할 것 같아요.. 
그렇다면 별도의 클래스로 분리한 것이 가독성을 좋게 하기 위한 조치일지에 대해 의문이 드네요. 
오히려 헷갈려서 가독성을 떨어트리는 것은 아닐까요??🤔 
(물론 구조를 파악하게 된다면 가독성이 좋아지긴하지만요.ㅎㅎ)

2024-03-24 11:47 UTC, jhon3242 commented on src/main/java/chess/domain/Position.java
> +        Column column = ColumnMapper.findByInputValue(positionValue.split("")[INPUT_COLUMN_INDEX]);
찰리가 주신 의견에 공감합니다!
Mapper 가 도메인 객체에서 알고 있다는 것은 잘못된 것 같아요! 
그래서 우선은 해당 로직을 컨트롤러로 다시 옮겨 주었습니다.

```java
private Position createPositionByString(String positionValue) {
      Row row = RowMapper.findByInputValue(positionValue.split("")[INPUT_ROW_INDEX]);
      Column column = ColumnMapper.findByInputValue(positionValue.split("")[INPUT_COLUMN_INDEX]);
      return new Position(row, column);
  }
```

위 메서드를 컨트롤러로 옮겨주었는데요. 
옮기고 보니까 "Position 을 반환하는 메서드가 컨트롤러에 있다는 것이 과연 맞을까?" 라는 의문이 들었습니다. 

그래서 문자열을 받아서 `Position` 을 반환해주는 Parser 객체를 도입해 보았습니다.
그런데 이 방법이 옳은 방법인지에 대해선 확신이 없습니다.😭
이 파싱 객체가 도메인 객체인지 뷰 객체인지도 잘 모르겠구요..(그래서 dto 패키지를 만들어서 넣어주었습니다..)
더 좋은 방법이 있을까요??😭

2024-03-25 11:04 UTC, Gomding commented on src/main/java/chess/controller/ChessGameController.java
> +    private final ChessGame chessGame = new ChessGame(new Board());
> 그런데 이렇게 확장 가능하게 설계를 할 때마다 YOGNI 법칙에 위배되는 것은 아닌지 스스로 고민하게 되는 것 같아요. 물론 저만의 기준을 찾아가면서 판단을 잘 해야하는 것은 맞지만 명확한 기준을 만들어가는게 어려운 것 같아요. 그래서 매번 방식이 바뀌는 것 같고 통일성을 못지키는 것 같아요.. 😭

말씀대로 YAGNI 법칙에 위배된다는 것도 동의합니다 :)
모든곳에 확장 가능한 것을 고려하여 `인터페이스 > 구현체 코드 작성` 은 너무 고통스럽기도 하고..
코드 읽는 사람도 고통스럽게 만들죠

> 찰리는 어떠한 기준으로 "아 이때는 확장 가능하게 추상화를 해둬야겠다." or "이 확장은 불필요하니까 굳이 추상화를 하지 말아야겠다" 를 판단하는지 궁금합니다!!

확장이 높은 확률로 보이거나 곧 확장이 예정됐다면 확장 가능하게 만들구요 😃 

보통은 확장을 고려하지 않은 코드를 먼저 작성합니다!
해당 코드가 변경될지 안될지 모르는 상황에서 오버 엔지니어링을 하는것은 낭비가 되니까요~!
나중에 변경이 생긴다면 그때 리팩터링 하는것이 좋다고 생각합니다!
이를 위해서 처음에 테스트 코드를 잘 작성해놓는건 미래의 리팩터링에 도움이 되겠죠 :)

단 최소한의 확장을 위한 장치들은 마련해두는데
가능하면 static 객체에 대한 의존을 피하려고 하고
생성자 주입을 해놓습니다!
나중에 생성자만 잘 손보면 리팩터링이 끝날 수도 있거든요 😃

2024-03-25 11:15 UTC, Gomding commented on src/main/java/chess/domain/Position.java
> +        Column column = ColumnMapper.findByInputValue(positionValue.split("")[INPUT_COLUMN_INDEX]);
타칸의 코멘트 예시로 들어준 로직을 Parser 안으로 넣어셨군요
parsing 하는 과정만을 담당하여 해당 과정을 알 수 있다는 장점이 있어 보이는데
꼭 필요한지는 의문이 들었어요..! 🤔 
+) dto 패키지에 있을 이유가 있을까요 😃 

---

좀 강하게 도메인을 분리하고 싶다~ 라면
Controller 에서 `a8` 과 같은 위치 문자열을 int rowIndex, int columnIndex로 넘겨볼것 같아요..!
근데 원시값을 넘기는 것이 실수도 발생할 수 있어서 좀 불편하죠.. 😓

타칸이 만들어주신 Positio의 경우 VO로 불변하다는 것이 장점이니
Controller 에서 생성하여 전달해도 크게 문제될 것은 없을것같아요!

Controller에서 도메인을 최대한 없애는것을 목표로 드렸던 코멘트라
이 정도만 고민하고 넘어가셔도 좋습니다 ㅎㅎ

2024-03-25 11:19 UTC, Gomding commented on src/main/java/chess/view/CommendDto.java
> +public record CommendDto(Commend commend, String from, String to) {
> DTO 를 Record 로 활용해주고 싶은데 Record 는 불변 객체여서 상속도 안되고요..

상속을 하고싶다면 record를 포기하는것도 하나의 방법이구요..!
상속이 필요한데 record를 사용하고싶다는것은 모순이니까요 🤔 

Command 패턴 같은 디자인 패턴을 활용해볼 수도 있는데
저는 DTO에 그 정도 리소스를..?
하는 생각이 들어서 막 추천드리고 싶지는 않습니다 ㅎㅎ...

타칸이 관심이 있다면 도전해보셔도 좋아요~

2024-03-25 11:21 UTC, Gomding commented on src/main/java/chess/domain/ChessGame.java
> +        }
저도 ` currentPosition 를 새롭게 할당해주는 부분` 이 부분이 마음에 걸렸어요..! ㅎㅎ
그래서 오히려 로직이 복잡해질것 같구요..

2024-03-25 11:23 UTC, Gomding commented on src/test/java/chess/domain/chessGame/KnightTest.java
> +class KnightTest {
테스트 코드도 다른 사람이 읽어야하는 것이니 가독성을 고려하여 분리하는 것도 고려해볼만 하다 생각합니다!
특히 체스 같은 경우 체스판 위에서 말의 움직임을 검증하는 테스트도 있다보니
타칸의 분리의도가 충분히 이해됩니다!

> 각각을 분리하신 것은 가독성을 위해서였겠죠? 👍 👍 👍 👍

이걸 눈치채는데도 오래걸리지 않았어요 😄

2024-03-25 11:46 UTC, Gomding approved these changes
안녕하세요 타칸!
1,2 단계 충분히 리팩터링 해주신것 같아요!
이번 단계는 이만 merge 하겠습니다 🙏 

질문에 대한 답변과 함께 몇 가지 코멘트 남겼으니 다음 단계 진행하면서 함께 고민해주세요 !

다음 단계 화이팅입니다~

2024-03-25 11:46 UTC, Gomding commented on src/main/java/chess/domain/ChessGame.java
> +        throw new IllegalArgumentException("기물을 해당 위치로 이동시킬 수 없습니다.");
어떤 이유로 이동 시킬 수 없는지 예외 메세지에 표현해주면
사용자가 다음 액션을 하는데 더 도움이 될것같아요!
또는 무엇을 잘못했는지 인지할 수 있게요 :)

턴 규칙에 의해 발생하는 예외메세지 처럼요! 👍   
`다른 팀의 기물을 움직일 수 없습니다. 현재 턴 : WHITE`

2024-03-25 11:46 UTC, Gomding commented on src/main/java/chess/domain/ChessGame.java
> +        return currentPosition != null
currentPosition 이 null인 경우가 존재하는지 궁금해요!
null인 경우를 비정상적인 상황으로 보고 예외를 발생시켜야하는 것은 아닐까요?

2024-03-25 11:46 UTC, Gomding commented on src/main/java/chess/domain/ChessGame.java
> +        this.currentTurn = START_COLOR;
시작 턴을 상수로 표현 👍

2024-03-25 11:46 UTC, Gomding commented on src/main/java/chess/domain/strategy/speical/RookMoveStrategy.java
> +    private static final List<Direction> DIRECTIONS = List.of(Direction.N, Direction.W, Direction.S, Direction.E);
```suggestion
    private static final List<Direction> DIRECTIONS = Direction.straightDirections();
```

이런식으로 표현해볼 수도 있다고 생각해요!
타칸은 어떻게 생각하시나요?

2024-03-25 11:46 UTC, Gomding commented on src/main/java/chess/domain/Board.java
> +    }
해당 생성자는 더이상 사용하지 않는것으로 보이네요 :)

2024-03-25 11:46 UTC, merged

2024-03-25 12:05 UTC, jhon3242 commented on src/main/java/chess/domain/ChessGame.java
> +        throw new IllegalArgumentException("기물을 해당 위치로 이동시킬 수 없습니다.");
앞에 기물이 있어서 못가는 것인지, 해당 기물이 움직일 수 있는 경로가 아닌지를 구분해주면 훨씬 좋을 것 같아요!
다만, 지금 코드 구조에서는 해당 메시지를 구분해주기 위해선 너무나 많은 로직이 수정 될 것 같아요😭

예외 메시지를 구분해줄 수 없다는 것이 어떻게 보면 구조의 수정이 필요한 신호라고도 볼 수 있을 것 같네요!

그런데 한편으로는 예외 메시지를 구분해주기 위해 코드를 수정해야한다면 배보다 배꼽이 큰 것이 아닌가? 라는 생각도 드는 것 같아요.

찰리는 어떻게 생각하시는지 궁금합니다!

2024-03-31 06:38 UTC, jhon3242 commented on src/main/java/chess/domain/ChessGame.java
> +        return currentPosition != null
룩이 a1 에 있다고 가정해보면
북 : a2, a3, a4, a5, a6, a7, a8
동 : b1, c1, d1, e1, f1, g1, h1

위와 같이 Key 는 방향, Value 는 이동 가능성이 있는 방향들(이동 순서대로) Deque 로 있을 것이에요.
```java
while (isEmptySpace(direction, piece, currentPosition)) {
    result.add(currentPosition);
    currentPosition = expectedPositions.poll();
}
```
그리고 위 부분이 호출되고 반복문을 빠져나가게 된다면 경우의 수는 2가지일 것 같아요
1. 보드판 끝까지 도달해서 더 이상 갈 수 있는 방향이 없는 경우
2. 덱에는 더 갈 수 있는 방향이 있는데 현재 위치에 어떤 기물이 있는 경우

그리고 `isEmptySpace` 에서는 1번 경우를 위해서 `null` 체크 부분이 필요하다고 생각했습니다!
isEmptySpace 에서 currentPosition 가 null 인 경우는 덱에서 모든 위치를 꺼내서 확인한 결과 모두 갈 수 있는 상황이니까요 ㅎㅎ
이는 정상 케이스이지, 예외를 발생시켜야하는 문제는 아니라고 판단했어요!
그래서 예외를 발생시켜주지 않았습니다!

isEnemySpace 에서 null 인 경우도 마찬가지로 "모든 위치를 갈 수 있는 경우"에 덱에 더 이상 체크할 방향이 남아있지 않는 상황이니까 마찬가지로 예외를 발생시켜주지 않았습니다!