[1, 2단계 - 체스] 메이슨(김경원) 미션 제출합니다.
woowacourse/java-chess pull request #690
Opened 2024-03-21 08:36 UTC by masonkimseoul

안녕하세요 러너덕! 메이슨입니다.

페어 프로그래밍과 TDD를 통해 다음과 같이 '1, 2단계 - 체스'를 완료했습니다.
이번 미션은 시간이 촉박해 요구사항을 모두 충족하는 것이 꽤 어려웠던 것 같습니다.

- 체스의 룰 중 프로모션, 앙파상, 캐슬링을 제외하고 구현하였습니다.
- 기능 요구 사항은 docs/README.md에 정리해두었습니다.

---
## 다이어그램

![image](https://github.com/woowacourse/java-chess/assets/87306418/d6372394-361d-42e5-9984-db77c11c478e)

기물이 존재하지 않는 곳은 None 클래스의 기물을 넣어, 기물의 비교 로직을 간단하게 작성할 수 있도록 하였습니다.
---
## 질문
1. 본래는 Direction enum을 사용하여 모든 기물들의 이동 방향을 계산하려고 하였습니다. 그러나 이런 식으로 코드를 작성하니 킹, 나이트, 폰의 이동 로직이 굉장히 복잡해졌고, 이 세 기물의 경우 기물 내부에서 이동 방향에 대한 계산을 진행하도록 하였습니다. 모든 기물들의 이동 방향 계산 로직이 통일되지 않아 클린한 코드에서 거리가 멀어진 것 같습니다. 만약 이런 상황이 발생한다면 러너덕은 코드의 복잡도와 통일성 중 어떤 걸 선택하시나요?

2. 이번 미션에서 몇 메서드의 경우 10줄 이내로 작성하는 컨벤션을 지키지 못했습니다. 분리할 경우 가독성이 떨어지기도 하고 return할 값이 한 개가 아니라서 분리가 어렵기도 했습니다. 저는 가독성이 조금 더 중요한 것 같아 분리하지 않았지만, 이런 경우 러너덕은 Map이나 dto를 사용해서라도 분리하시는 편인지 여쭤보고 싶습니다.

긴 글과 미숙한 코드를 읽어주셔서 감사합니다!

2024-03-22 18:41 UTC, Deocksoo requested changes
안녕하세요 메이슨, 러너덕입니다!
None을 사용하여 불필요한 구분 로직들을 없애도록 한 것이 좋네요 👍 
다만 None을 잘 활용했음에도 Piece에 제대로 추상화되지 못한 부분이 남아있는 것 같아요.
관련해서 코멘트 몇 군데 남겨두었으니, 확인 한 번 부탁드려요~

> 본래는 Direction enum을 사용하여 모든 기물들의 이동 방향을 계산하려고 하였습니다. 그러나 이런 식으로 코드를 작성하니 킹, 나이트, 폰의 이동 로직이 굉장히 복잡해졌고, 이 세 기물의 경우 기물 내부에서 이동 방향에 대한 계산을 진행하도록 하였습니다. 모든 기물들의 이동 방향 계산 로직이 통일되지 않아 클린한 코드에서 거리가 멀어진 것 같습니다. 만약 이런 상황이 발생한다면 러너덕은 코드의 복잡도와 통일성 중 어떤 걸 선택하시나요?

질문을 잘 이해하지 못했어요.
지금 트레이드오프로 비교하고 있는 대상인 통일성이 무슨 통일성인가요?
조금 더 구체적인 예시가 있으면 좋겠네요.

> 이번 미션에서 몇 메서드의 경우 10줄 이내로 작성하는 컨벤션을 지키지 못했습니다. 분리할 경우 가독성이 떨어지기도 하고 return할 값이 한 개가 아니라서 분리가 어렵기도 했습니다. 저는 가독성이 조금 더 중요한 것 같아 분리하지 않았지만, 이런 경우 러너덕은 Map이나 dto를 사용해서라도 분리하시는 편인지 여쭤보고 싶습니다.

어떤 부분을 이야기하시는 걸까요~? 조금 더 구체적인 예시가 있으면 좋겠네요!

2024-03-22 18:41 UTC, Deocksoo commented on src/main/java/chess/controller/ChessGame.java
> +        Board board = null;
사소한 것이지만, null은 되도록 코드 안에서 돌아다니지 않도록 하는 것이 좋아요.
어떨 때는 타입을 추론하기도 어렵고, 예외가 발생했을 때 트러블슈팅도 어려워지죠.
지금은 큰 문제가 없으니 인지만 하고 계셔도 될것같네요.

2024-03-22 18:41 UTC, Deocksoo commented on src/main/java/chess/model/piece/PieceType.java
> +    public boolean isSameColor(int turnCount) {
이런 부분은 구현에는 큰 문제가 없지만 디버깅을 어렵게 만들 수도 있겠네요.
가끔 숫자 그대로 DB에 들어갔다가, 의미를 알 수 없는 레거시가 되어 후대 개발자들 대대로 고통받는 숫자가 되기도 하죠.
색 구분을 위해 ENUM을 사용해보는 것은 어떤가요?

2024-03-22 18:41 UTC, Deocksoo commented on src/main/java/chess/model/piece/Pawn.java
> +    public boolean canAttack(Position source, Position target) {
이 부분때문에 추상화가 깨지네요.
Piece에 abstract로 넣는 것은 어떤가요?
그러면 굳이 sourcePiece.isPawn() 와 같은 방식으로 타입체크를 하거나, 타입 캐스팅을 하지 않아도 될것같아요.

2024-03-22 18:41 UTC, Deocksoo commented on src/main/java/chess/model/piece/Piece.java
> +public abstract class Piece implements MoveStrategy {
이 MoveStrategy가 필요한 이유는 무엇인가요?
오히려 Piece에 명시되어있어야 할 move가 보이지 않아서, 
중요한 명세 하나를 가려버리는 것 같은데요.

2024-03-22 18:41 UTC, Deocksoo commented on src/main/java/chess/model/Board.java
> +        board.put(source, Piece.from(PieceType.NONE));
PieceType을 None으로 만드니, 비어있는 곳에 계속 의미없는 새로운 객체가 들어가네요.
Piece.EMPTY 같은 객체를 만들어서 한 개로 사용하는 것은 어떤가요?

2024-03-22 18:41 UTC, Deocksoo commented on src/main/java/chess/model/piece/None.java
> +public class None extends Piece {
👍 덕분에 구현이 조금 더 깔끔해졌네요.
이런 기본값이 생각보다 도움이 될 때가 많죠.

2024-03-22 18:41 UTC, Deocksoo commented on src/main/java/chess/model/piece/Piece.java
> +    public boolean isKnight() {
이런 메서드는 사실상 instanceof 와 크게 다를 바가 없죠. 
결국 밖에서 타입을 묻는 것이나 다름없어요. 올바른 추상화로 보기 어렵죠.
이렇게 타입을 확인하여 다르게 동작하게 하기보다는, 각각의 객체에게 기물을 건너뛸 수 있는지 물어볼 수 있도록 추상 메서드를 제공하면 어떤가요?

2024-03-22 18:41 UTC, Deocksoo commented on src/main/java/chess/model/Board.java
> +            Position position = new Position(source.getRow() + rowDifference, source.getColumn() + columnDifference);
이 부분은 읽기가 조금 어렵네요.
position에게 맡기기는 어려울까요?

2024-03-22 18:41 UTC, Deocksoo commented on src/main/java/chess/model/Board.java
> +            Piece targetPiece = board.get(position);
아래에 만들어둔 메서드를 사용하면 되겠네요 :)

2024-03-24 08:16 UTC, masonkimseoul commented on src/main/java/chess/model/Board.java
> +            Position position = new Position(source.getRow() + rowDifference, source.getColumn() + columnDifference);
Position 클래스에서 row와 column의 차이값을 받아 새 Position 객체를 만들어주는 `makeRemotePosition` 메서드를 작성하였습니다. 감사합니다!

2024-03-24 08:21 UTC, masonkimseoul commented on src/main/java/chess/model/Board.java
> +        board.put(source, Piece.from(PieceType.NONE));
한 객체만 만들어두고 돌려쓴다면 불필요한 새 객체를 만들 필요가 없었네요.

Board에서 하나의 None 객체를 생성한 뒤 재사용하도록 수정하였습니다. 감사합니다.

2024-03-24 11:07 UTC, masonkimseoul commented on src/main/java/chess/model/piece/Piece.java
> +    public boolean isKnight() {
getter를 지양하려고 하다보니 좋지 않은 구조가 된 것 같습니다. 추상 메서드로 바꾸니 훨씬 깔끔해진 것 같네요. 감사합니다!

2024-03-25 05:51 UTC, masonkimseoul commented on src/main/java/chess/model/piece/Pawn.java
> +    public boolean canAttack(Position source, Position target) {
다른 기물들은 이동과 공격이 같아 Pawn의 공격 로직만 따로 구현하기 어려웠는데 추상 메서드로 바꾼다면 해결되겠네요! Pawn을 제외한 다른 기물들의 canAttack에선 canMove를 호출하는 것으로 수정하였습니다. 감사합니다!

2024-03-25 05:54 UTC, masonkimseoul commented on src/main/java/chess/model/piece/Piece.java
> +public abstract class Piece implements MoveStrategy {
Pawn의 canAttack에 대한 고려를 충분히 하지 않은 상태에서 인터페이스를 사용해 canMove를 구현하려던 결과였던 것 같습니다. 이 부분도 MoveStrategy를 제거하고 canMove를 추상 메서드로 변경한다면 해결할 수 있겠네요. 감사합니다.

2024-03-25 08:37 UTC, masonkimseoul commented on src/main/java/chess/model/piece/PieceType.java
> +    public boolean isSameColor(int turnCount) {
Color enum 클래스를 생성하여 PieceType에서 색 관련 로직을 분리했습니다. 또한 turn도 정수가 아닌 Color를 사용하도록 수정하였습니다.

수정해야 할 부분이 꽤 많았습니다만 역할 분리가 잘 돼서 코드가 많이 깔끔해진 것 같습니다! 감사합니다.

2024-03-25 12:30 UTC, masonkimseoul commented
안녕하세요 러너덕! 메이슨입니다.

작성해주신 피드백 덕분에 코드가 더 클린해진 것 같습니다.
다름이 아니라 지난번 질문드린 내용에 부족한 점이 있는 것 같아 추가로 설명드릴려고 합니다.

> 본래는 Direction enum을 사용하여 모든 기물들의 이동 방향을 계산하려고 하였습니다. 그러나 이런 식으로 코드를 작성하니 킹, 나이트, 폰의 이동 로직이 굉장히 복잡해졌고, 이 세 기물의 경우 기물 내부에서 이동 방향에 대한 계산을 진행하도록 하였습니다. 모든 기물들의 이동 방향 계산 로직이 통일되지 않아 클린한 코드에서 거리가 멀어진 것 같습니다. 만약 이런 상황이 발생한다면 러너덕은 코드의 복잡도와 통일성 중 어떤 걸 선택하시나요?

여기서 말씀드린 통일성은 다음과 같습니다.

```java
//Queen 클래스
@Override
public boolean canMove(Position source, Position target) {
    Direction direction = Direction.findDirection(source, target);
    if (direction == UP_LEFT || direction == DOWN_LEFT || direction == UP_RIGHT || direction == DOWN_RIGHT) {
        return true;
    }
    return direction == UP || direction == DOWN || direction == LEFT || direction == RIGHT;
}
```
```java
//Knight 클래스
@Override
public boolean canMove(Position source, Position target) {
    int rowDifference = Math.abs(calculateRowDifference(source, target));
    int columnDifference = Math.abs(calculateColumnDifference(source, target));

    if (rowDifference == FIRST_MOVEMENT && columnDifference == SECOND_MOVEMENT) {
        return true;
    }
    return columnDifference == FIRST_MOVEMENT && rowDifference == SECOND_MOVEMENT;
}
```
`Queen` 클래스의 `canMove`는 `Direction` enum을 사용해 유효한 위치인지 판단합니다. `Knight` 클래스의 `canMove`는 인덱스의 차이값으로 유효한 위치인지 판단합니다.
`Knight` 클래스의 `canMove`도 `Queen`의 `canMove`처럼 `Direction`을 사용할수도 있겠지만, 그만큼 코드의 복잡도가 올라갈 것이라 판단해 `Direction`을 사용하지 않았습니다.
그래서 `Queen, Bishop, Rook`은 `Direction`으로 `canMove`를 구현하였고, `Knight, King, Pawn`은 인덱스의 차이값으로 `canMove`를 구현했습니다. 그 결과로 `Piece`의 `canMove` 로직이 하나로 통일되지 않아 설계상으로 조금 아쉬움이 남았습니다. 여기서 러너덕은 통일성과 복잡도 둘 중 어느걸 더 중요하게 생각하고 구현하시는지 여쭤보고 싶습니다.

---

> 이번 미션에서 몇 메서드의 경우 10줄 이내로 작성하는 컨벤션을 지키지 못했습니다. 분리할 경우 가독성이 떨어지기도 하고 return할 값이 한 개가 아니라서 분리가 어렵기도 했습니다. 저는 가독성이 조금 더 중요한 것 같아 분리하지 않았지만, 이런 경우 러너덕은 Map이나 dto를 사용해서라도 분리하시는 편인지 여쭤보고 싶습니다.

이 부분은 처음 질문했을 당시 구현을 마치기 이전 코드와 혼동했었던 것 같습니다 😅
당시 수정했던 내용은 다음과 같습니다.
```java
private Board executeCommand(Board board) {
    List<String> commands = InputView.askGameCommands();
    Command command = Command.findCommand(commands.get(COMMAND_INDEX));
    if (command.isEnd()) {
        return null;
    }
    if (command.isStart()) {
        return executeStart();
    }
    if (command.isMove() && board != null) {
        executeMove(commands, board);
    }
    return board;
}
```

게임 명령어를 `List<String>`으로 받아오는데, move는 start, end와 다르게 좌표를 추가적으로 받습니다.
이때 명령어와 좌표값을 입력하는 로직을 분리하여, 명령어의 validation 처리를 분리하고 싶었습니다. 그러나 명령어와 좌표값을 분리하여 하나씩 검증하는 구조가 잘 생각나지 않아 `List<String>`을 사용해서 위와 같이 구현하는 것으로 수정하여 해결하였습니다.

2024-03-26 15:14 UTC, Deocksoo approved these changes
안녕하세요 메이슨, 러너덕입니다.
리뷰 깔끔하게 잘 반영해주셨네요 👍 필요한 것들이 보다 잘 추상화되었어요.
다음 미션 계속 진행해주셔도 될 것 같아요.
간단한 리뷰 몇 개 남겨두었으니, 다음 미션 진행하실때 확인 부탁드려요.

> Queen 클래스의 ... 여기서 러너덕은 통일성과 복잡도 둘 중 어느걸 더 중요하게 생각하고 구현하시는지 여쭤보고 싶습니다.

일관적으로 일관성 있는 코드를 작성하는 것은 중요하지만, 이 부분에서는 이미 코드 Piece를 활용해 어느정도 구조를 잘 잡아놓으셨어요. 말씀하신 정도의 구현상의 차이는 크게 일관성을 해치지 않을것같네요. 일관성을 그정도로까지 맞추기 위해 과하게 복잡하게 코드를 작성하면 오히려 관리하기 어려운 코드가 될 것 같아요.

그 뒤에 여쭤봐주셨던 부분은 스스로 잘 해소하신 것 같네요 :)

2024-03-26 15:14 UTC, Deocksoo commented on src/main/java/chess/model/Command.java
> +public enum Command {
View에 있어야할것같은 객체인데, 위치를 옮기는 것은 어떤가요?

2024-03-26 15:14 UTC, Deocksoo commented on src/main/java/chess/model/Direction.java
> +package chess.model;
지금은 Position과 Dirction이 모두 model 패키지 최상단에 위치하고, 그 안에 piece 패키지가 존재하죠.
그런데 안쪽에 있는 패키지에서 상위 패키지에 있는 객체에 의존하고있네요.
패키지를 구분하는 기준이 어떻게 되나요?

2024-03-26 15:14 UTC, merged

2024-03-27 06:59 UTC, masonkimseoul commented on src/main/java/chess/model/Direction.java
> +package chess.model;
저는 가급적 필드로 들어가는 클래스(Piece의 경우 PieceType과 Color)를 한 패키지에 묶으려고 합니다.

그래서 Position과 Direction을 piece 패키지에 넣는 것이 어색하다고 생각했었습니다.

그런데 의존 관계까지는 고려하지 못한 것 같네요. 일단 Position과 Direction을 position 패키지로, piece 패키지와 동등한 레벨로 묶어보았습니다.