[1,2단계 - 체스] 위브(김기범) 미션 제출합니다.
woowacourse/java-chess pull request #693
Opened 2024-03-21 08:40 UTC by jimi567

안녕하세요. 현구막..
위브라고 합니다.. 이번 페어는 아톰이랑 함께 진행했습니다.!!
리뷰 잘부탁드립니다.

2024-03-22 11:44 UTC, Hyeon9mak requested changes
안녕하세요 위브, 체스 미션을 함께할 현구막입니다. 🙇‍♂️ 
체스 미션 자체가 규모가 크다보니 시간이 부족하셨을 것 같아요.

그렇지만 주어진 기간 내에 요구사항을 모두 만족시키는 것이 무엇보다 중요합니다.
클라이언트의 요구사항을 만족하지 못한다면 뛰어난 설계, 읽기 좋은 코드, 유지보수 하기 좋은 코드는 모두 말짱 도루묵일거에요.

> 당시 윈도우95에는 약 3500개의 버그가 남아 있었고, 나를 비롯한 다른 개발자 모두가 그 사실을 알고 있었다.
하지만 우리는 윈도우95를 예정대로 공개했다. (중략) 프로그래머에게 요구되는 것은 100점이 아닌 80~90점짜리 프로그램을 기한 내에 완성하는 일이다.
(중략) 윈도우95는 전 세계적으로 팔려나갔다. 전문가의 눈에는 완성도가 떨어지는 결과물로 보였을 것이다.
하지만 일반 대중은 윈도우95를 ‘획기적인 신제품’으로 받아들였다.
기억하라. 수정은 일을 끝낸 후에도 충분히 가능하다. (55쪽_2장 ‘윈도우95는 3500개의 버그가 있어도 세계를 제패했다’ 中)

설계와 코드가 어떠한가는 결국 개발자끼리의 이야기일뿐, 클라이언트에게는 중요하지 않습니다.
우선 동작하는 프로그램을 구현하고, 점진적으로 개선해나가는 경험을 해보시면 좋겠어요.

우선 체스게임이 정상적으로 진행되지 않는 걸로 보여요.

<img width="839" alt="image" src="https://github.com/woowacourse/java-chess/assets/37354145/1d604c8c-94ae-4387-b151-fe4db6c20762">

이번 리뷰요청 전에 체스 기능이 정상적으로 동작할 수 있게 되면 좋겠습니다!

몇 가지 코멘트 남겼으니 확인해주세요!
궁금하신 점 코멘트 남겨주세요~

2024-03-22 11:44 UTC, Hyeon9mak commented on docs/README.md
> +    - [x] 폰은 초기 위치에 있을 경우, 적진 방향으로 2칸 움직일 수 있다.
요구사항 정리 💯

2024-03-22 11:44 UTC, Hyeon9mak commented on src/main/java/chess/Controller.java
> +    }
기획자가 낙낙의 동료 개발자에게 "아무래도 영어보단 한글이 낫겠어요. 게임 명령어를 `시작`, `종료` 로 바꿔주세요." 라는 요구사항을 전달하면, 동료 개발자는 view 와 controller 중 어떤 클래스를 먼저 열어보게 될까요?

2024-03-22 11:44 UTC, Hyeon9mak commented on src/main/java/chess/Controller.java
> +            playChess(board);
각각의 인덱스가 어떤 값인지 상수로 이름을 부여해주는 건 어떨까요?

2024-03-22 11:44 UTC, Hyeon9mak commented on src/main/java/chess/Controller.java
> +            playChess(board);
List<Coordinate> 를 한번더 객체로 감싼다면, `get(0)`, `get(1)` 대신 메서드로 이름을 부여해줄 수 있지 않을까요?

2024-03-22 11:44 UTC, Hyeon9mak commented on src/main/java/chess/domain/board/Board.java
> +    }
상대 기물을 공격하는 경우 기물이 존재할 수 있지 않나요? 🤔

2024-03-22 11:44 UTC, Hyeon9mak commented on src/main/java/chess/domain/board/BoardFactory.java
> +    }
체스 게임은 오랜 세월동안 규칙이 변하지 않았으므로, 새로운 기물이 추가될 일이 없을 것 같아요.
그렇다면 각 기물 인스턴스를 캐싱하여 활용해볼 수도 있을 것 같네요!

2024-03-22 11:44 UTC, Hyeon9mak commented on src/main/java/chess/domain/piece/Bishop.java
> +    }
움직일 수 있는 경로를 찾지 못한 경우 예외 상황이 아닐까요? 😱

2024-03-22 11:44 UTC, Hyeon9mak commented on src/main/java/chess/domain/piece/King.java
> +    );
king 과 bishop 의 이동경로 확인 방식이 다른 이유가 있었을까요?

2024-03-22 11:44 UTC, Hyeon9mak commented on src/main/java/chess/view/PieceShape.java
> +
👍 각 기물들이 어떻게 표현되는가는 view 의 책임이죠!
그리고 view 에서도 얼마든지 enum 활용이 가능하죠! 💯

2024-03-25 08:54 UTC, jimi567 commented on src/main/java/chess/Controller.java
> +    }
Command라는 view 로직을 관리하는 클래스를 추가하여, 컨트롤러에 뷰 로직에 대한 의존성을 최대한 줄여봤습니다.

2024-03-25 08:56 UTC, jimi567 commented on src/main/java/chess/domain/piece/Bishop.java
> +    }
예외처리를 borad에서 몰아서 해주기 보다는 적절한 장소에서 해주도록 변경했습니다.!

2024-03-25 09:15 UTC, jimi567 commented on src/main/java/chess/domain/piece/King.java
> +    );
비숍은 대각 방향 아무곳이나 갈 수 있고,
킹은 현재 위치에서 고정된 8개 위치로만 이동할 수 있어서 이동경로 방식이 달랐던 것 같습니다.

2024-03-25 09:28 UTC, jimi567 commented
안녕하세요. 현구막!
말씀해주신 것처럼 "적 기물을 잡는다" 라는 개념이 구현되어 있지 않아서, 피드백 반영이 많이 늦어진 것 같습니다.
새로운 개념을 구현하느라, 코드 구조가 꽤 많이 달라졌어요..!ㅠㅠ

이번에도 피드백도 잘 부탁드립니다. ㅠ

이번 체스 미션을 구현하면서 궁금했던 점은 다음입니다.

1. 보드와 기물간의 양방향 의존성을 어떻게 해야 끊어낼 수 있을까?

일단 임시방편으로, 
Piece에게 현재 위치에서 갈 수 있는 다음  위치를 알아내고,
그 위치에 대한 borad 정보를 piece에게 넘겨준 다음 piece가 정말 갈 수 있는 지를 체크하는 방식으로 구현했습니다.
직접적으로 borad 라는 객체를 piece에게 넘겨준 것은 아니지만, borad의 일부 정보를 넘겨준다는 점에서 의존관계가 완전히 끊어진걸까? 라는 의문점이 남았습니다.

제 설계가 잘못된 것일지,,, 체스라는 도메인 특징상 보드와 기물간에는 의존관계를 끊을 수 없는게 당연한건지에 대한 의문점이 남습니다.

2. piece가 보드상에서 현재 위치를 갖고 있는게 맞을까?

네오의 체스 피드백 강의를 보면서, 들었던 의문점입니다.
네오는 piece 객체를 구현할때, 각 piece가 현재 상태를 갖고 관리하도록 구현을 했습니다.
하지만 저의 생각에는 piece객체 자체는 borad상의 현재 자기 위치를 안다는 것이 합리적이지 않다는 생각이 들었습니다.
결국은 제 생각대로 piece는 현재 위치를 갖지 않고, borad에게 주입받도록 구현했습니다.
물론 구현하는 사람마다 생각이 다르고 스타일이 다르다고 생각하지만, 이 부분에서의 현구막의 의견이 궁금합니다.
(크루원들과도 의견을 나누고 있지만, 최대한 많은 사람들의 의견을 듣고 싶어서 여쭤봅니다.!!)

첫 pr에 비해 코드가 대거 바뀌게 되었습니다. ㅠㅠ 이점 정말 죄송하게 생각합니다.
코드가 바뀜에 따라 피드백 해주신 내용 중 적용하기 힘든 부분도 있어서, 그 부분을 제외한 다른 부분을 최대한 적용시키는 방식으로 피드백을 반영해봤습니다.
다시 한번 잘부탁드립니다. 현구막!!

2024-03-25 09:29 UTC, jimi567 commented on src/main/java/chess/domain/board/BoardFactory.java
> +    }
설계가 바뀌어서 , piece의 각 타입을 캐싱하기가 힘들다고 생각해서 이 부분은 제외하고 구현했습니다.!

2024-03-25 09:30 UTC, jimi567 commented on src/main/java/chess/domain/board/Board.java
> +    }
말씀해주신 것처럼 기물을 잡는다는 개념을 구현하지 않아서, 폰도 양쪽 대각으로 못갑니다 ㅎㅎ...
이 부분 적용시켜서 구현했습니다.!

2024-03-25 09:33 UTC, jimi567 commented on src/main/java/chess/Controller.java
> +            playChess(board);
컨트롤러의 뷰 로직을 최대한 제외하는 과정에서, 이 부분의 코드가 사라져서 반영 못했습니다.ㅠ
이 부분 외에도 List<Coordinate>를 사용하는 부분이 존재하지만, 일급객체로 감싸게 될 경우 로직이 더 복잡해지고 List<Coordinate>의 일급컬렉션이 제공할만한 별다른 기능이 없다고 생각해서 따로 만들지는 않았습니다.

2024-03-25 09:36 UTC, jimi567 commented on src/main/java/chess/view/PieceShape.java
> +
이전 미션에서 피드백 받았던 내용인데,
역시 view와 도메인의 철저한 분리가 정말 중요하다는 것을 다시 상기하게 되네요..! 감사합니다

2024-03-25 09:51 UTC, jimi567 commented
안녕하세요. 현구막!
말씀해주신 것처럼 "적 기물을 잡는다" 라는 개념이 구현되어 있지 않아서, 피드백 반영이 많이 늦어진 것 같습니다.
새로운 개념을 구현하느라, 코드 구조가 꽤 많이 달라졌어요..!ㅠㅠ

이번에도 피드백도 잘 부탁드립니다. ㅠ

이번 체스 미션을 구현하면서 궁금했던 점은 다음입니다.

보드와 기물간의 양방향 의존성을 어떻게 해야 끊어낼 수 있을까?
일단 임시방편으로,
Piece에게 현재 위치에서 갈 수 있는 다음 위치를 알아내고,
그 위치에 대한 borad 정보를 piece에게 넘겨준 다음 piece가 정말 갈 수 있는 지를 체크하는 방식으로 구현했습니다.
직접적으로 borad 라는 객체를 piece에게 넘겨준 것은 아니지만, borad의 일부 정보를 넘겨준다는 점에서 의존관계가 완전히 끊어진걸까? 라는 의문점이 남았습니다.

제 설계가 잘못된 것일지,,, 체스라는 도메인 특징상 보드와 기물간에는 의존관계를 끊을 수 없는게 당연한건지에 대한 의문점이 남습니다.

piece가 보드상에서 현재 위치를 갖고 있는게 맞을까?
네오의 체스 피드백 강의를 보면서, 들었던 의문점입니다.
네오는 piece 객체를 구현할때, 각 piece가 현재 상태를 갖고 관리하도록 구현을 했습니다.
하지만 저의 생각에는 piece객체 자체는 borad상의 현재 자기 위치를 안다는 것이 합리적이지 않다는 생각이 들었습니다.
결국은 제 생각대로 piece는 현재 위치를 갖지 않고, borad에게 주입받도록 구현했습니다.
물론 구현하는 사람마다 생각이 다르고 스타일이 다르다고 생각하지만, 이 부분에서의 현구막의 의견이 궁금합니다.
(크루원들과도 의견을 나누고 있지만, 최대한 많은 사람들의 의견을 듣고 싶어서 여쭤봅니다.!!)

첫 pr에 비해 코드가 대거 바뀌게 되었습니다. ㅠㅠ 이점 정말 죄송하게 생각합니다.
코드가 바뀜에 따라 피드백 해주신 내용 중 적용하기 힘든 부분도 있어서, 그 부분을 제외한 다른 부분을 최대한 적용시키는 방식으로 피드백을 반영해봤습니다.
다시 한번 잘부탁드립니다. 현구막!!

2024-03-27 08:08 UTC, Hyeon9mak requested changes
안녕하세요 위브.. 리뷰가 너무 늦었네요 🙏 
대신 더 꼼꼼히 리뷰 진행할게요..!!!!

### 보드와 기물간의 양방향 의존성을 어떻게 해야 끊어낼 수 있을까?

의존을 끊는 행위 그 자체보다, 끊으려는 이유가 가장 중요하겠는데요.
끊으려는 이유는 결국 "양방향 의존이 생기면 리팩터링이 너무 어려워진다." 였을걸로 추측해요.
간접적으로 보드와 기물간 양방향 의존성이 살아있는 것 같지만, 유지보수성이 개선되진 않았나요?
그렇다면 잘 끊어낸 것이겠고, 아니라면 다시 끊어내야겠네요.

끊어내는 방법은 여러가지가 있겠지만(전체 설계를 바꾼다던지)
중간에 매핑/전달을 하는 객체를 만들어 연결을 최대한 끊어내는 방법도 있을거 같아요.

### piece가 보드상에서 현재 위치를 갖고 있는게 맞을까?

글쎄요? 😉 
제가 감히 이 설계가 좋겠다, 저 설계가 좋겠다는 이야기를 하면서 위브의 상상력을 방해하고 싶지 않아요.
구현 방식은 최대한 자유롭게 하셨으면 해요.
그러나 어떤게 좋은 설계일지 구분 지을 수 있는 기준점을 하나 제시해드리자면,
결국 "유지보수 하는 시점에 유지보수가 용이할까?" 를 따져보시면 될거 같아요.

가령 우테코 미션에서 공통적으로 view 패키지를 분리하는 이유는,
'자동차, 로또, 블랙잭, 체스 미션 모두 언제든지 웹 프로그래밍으로 변경될 수 있다.' 라는 기조가 있기 때문일텐데요,
"체스 게임은 이런 부분에 변화가 자주 생길거야." 를 위브가 상상해보시면서
'이 코드를 꼭 다른 코드들과 섞어서 봐야할까? 별도 클래스 파일로 분리하는건 어떨까?'
'이건 오히려 한 곳에 몰아두는게 로직의 의미를 파악하기 쉽겠는데? 합쳐야겠다.'
'여기 의존이 생기면 리팩터링이 어려울거 같은데... 중간객체를 만들어서 의존을 최대한 희석시켜볼까?'
생각을 확장해보시면 좋겠어요.

그런 관점에서... piece 가 보드상에서 현재 위치를 갖고 있는게 맞을까요? 😄 

간단한 코멘트 몇 가지 남겼습니다.
궁금하신 점 언제든지 연락주세요!

2024-03-27 08:08 UTC, Hyeon9mak commented on src/main/java/chess/Controller.java
> +
👍 

> view 관련한 개념이 컨트롤러에 남아 있어서, 적절하게 분리 됐는지는 아직 의문점이 남습니다.

직접적으로 "start" 라는 문자열을 다루는지가 사라졌기 때문에 유지보수 타이밍에 view 패키지만 살펴보면 될 것 같아요.
결국 객체지향은 "설계상 어떠한가?" 보다는, "유지보수 시점에 어떠한가?" 가 더 중요한 가치라고 생각해요.

> 낙낙..

비슷한 코멘트를 남기면서 다른 크루의 이름을 사용해버렸네요.. 😱 🙇‍♂️

2024-03-27 08:08 UTC, Hyeon9mak commented on src/main/java/chess/Controller.java
> +        }
코드의 복잡성이 올라간다는게 어떤 의미일까요?
현재 코드는 복잡성이 어떠한가요? 🤔

2024-03-27 08:08 UTC, Hyeon9mak commented on src/main/java/chess/domain/piece/directionmove/Bishop.java
> +
인스턴스를 캐싱할 코드의 위치는 해당 객체 클래스 파일 쪽에 두는게 찾아내기 쉽죠 👍

2024-03-27 08:08 UTC, Hyeon9mak commented on src/main/java/chess/domain/piece/directionmove/Bishop.java
> +
> 내가 개발하는 도메인에 대한 이해도를 갖추는 것도 중요한 것 같네요.

💯

2024-03-27 08:08 UTC, Hyeon9mak commented on src/main/java/chess/domain/piece/directionmove/Queen.java
> +    }
> 의미상 분류하는게 코드를 이해하는 측면에서 더 도움이 될 것 같다는 생각으로 다르게 구현한 것 같습니다.

구현 방식이 왜 다른지 매번 질문이 생길 것 같고, 매번 답변을 해야할 것 같다면 리팩터링을,
얼추 무슨 느낌인지 이해할 것 같다면 그냥 가도 좋을 것 같아요 ㅎㅎ 👍

2024-03-27 08:08 UTC, Hyeon9mak commented on src/main/java/chess/domain/piece/fixedmove/FixedMovePiece.java
> +    }
사소하지만, `canMove` 메서드의 steam api 도 개행을 진행해주면 가독성이 향상되겠네요!

2024-03-27 08:08 UTC, Hyeon9mak commented on src/main/java/chess/domain/piece/fixedmove/Knight.java
> +        );
(Map.entry) 자체를 변수나 상수로 분리하여 어떤 방향인지 이름을 부여해주는 것도 좋겠네요!!

2024-03-27 08:08 UTC, Hyeon9mak commented on src/main/java/chess/view/Command.java
> +}
메서드를 분리하여 질의하기 👍

2024-03-27 08:08 UTC, Hyeon9mak commented on src/main/java/chess/view/Command.java
> +        return Coordinate.of(File.from(input.charAt(0)), Rank.from(input.charAt(1) - '0'));
`isNotMove()` 로 질의하면 if 키워드 사이 잘 눈에 띄지 않는 `!` 를 제거해볼 수 있겠네요!

2024-03-27 08:08 UTC, Hyeon9mak commented on src/main/java/chess/view/Command.java
> +        return Coordinate.of(File.from(input.charAt(0)), Rank.from(input.charAt(1) - '0'));
view 패키지에 위치한 덕분에 부담없이 입력 문자열을 다룰 수 있네요 👍

2024-03-27 10:50 UTC, jimi567 commented on src/main/java/chess/Controller.java
> +        }
이거 사실 pr 보내 놓고 좀 생각이 바뀐 부분입니다.(주관 없이 이랬다 저랬다 하네요ㅠㅠ)
지금은 move 커맨드가 move, 시작 위치, 도착 위치 순서로 입력이 됩니다. 만약 이 부분의 요구사항이 변경돼서,
도착위치, 시작위치 순으로 입력받아라 한다면, 저 코드를 구현했던 저를 제외하고는 어느 부분을 바꿔야 할지 감 잡기가 힘들 것 같다는 생각이 들었어요. 차라리 한번 더 감싸서, 저 commandInput.get(1) <-이 부분에 네이밍을 주면 더 좋을 것 같다. 로 현재는 결론이 나서 적용할 것 같습니다.

> 코드의 복잡성이 올라간다는게 어떤 의미일까요?

저는 이해하기 어렵고, 코드가 불필요하게 길면 복잡성이 올라간다 라고 이해하고 있어요! 한마디로 명확하게 이해가 안되는 코드를 복잡도가 높은 코드라고 생각합니다.

기본적으로 클래스 수가 늘어난다면, 그걸 파악하는데 리소스가 많이 들어간다고 생각해요.
하지만 위에서 언급했던 것 처럼 현재 코드는 유지보수 하기에 힘들다고 판단이 됩니다.
클래스가 늘어난다. <<< 유지보수하기 힘들다. 이런 상황인 것 같아서, 현구막이 추천해주신 방향이 더 합리적이라는 생각이 들어요

2024-03-27 10:55 UTC, jimi567 commented on src/main/java/chess/domain/piece/directionmove/Queen.java
> +    }
저는 킹이라는 기물은 방향으로 움직이는 퀸 비숍 룩 보다는 현재 위치에서 정해진 다음 좌표로 움직이는 나이트와 결이 더 가깝다고 생각을 해서, 이 부분은 유지할 것 같아요. 물론 체스라는 도메인 자체를 이번 미션을 통해서 구체적으로 알게된 입장이라 기존에 체스에 친숙한 사람이 보기에는 다르게 느낄 순 있다고 생각합니다.
만약 팀으로 개발하게 될 경우, 많은 팀 개발자들이 "킹의 이동방식은 룩 비숍 퀸이랑 더 결이 가깝지않아?"
라고 말한다면 바꿀 것 같긴 합니다.

> 구현 방식이 왜 다른지 매번 질문이 생길 것 같고, 매번 답변을 해야할 것 같다면 리팩터링을,  

이건 너무 좋은 기준점인 것 같습니다. 새로운 관점을 알게 되는 것 같아요 감사합니다

2024-03-27 10:57 UTC, jimi567 commented on src/main/java/chess/domain/piece/fixedmove/FixedMovePiece.java
> +    }
이전에도, 피드백 받았던 부분인데 또 놓쳤네요....(그때도 짧은 스트림 코드라 그냥 이어서 작성했습니다.)
이번을 마지막으로 진짜 체화 하도록 노력해야될 것 같습니다.

2024-03-27 10:58 UTC, jimi567 commented on src/main/java/chess/domain/piece/fixedmove/Knight.java
> +        );
weights 이라는 메소드안에 존재하는 숫자라 이정도면 이해하는데 문제없지않을까? 라는 생각을 했던 것 같아요.
확실히 저런 값들에 네이밍까지 더 해준다면 더 이해하기 편한 것 같네요.

2024-03-27 11:00 UTC, jimi567 commented on src/main/java/chess/view/Command.java
> +        return Coordinate.of(File.from(input.charAt(0)), Rank.from(input.charAt(1) - '0'));
> isNotMove() 로 질의하면 if 키워드 사이 잘 눈에 띄지 않는 ! 를 제거해볼 수 있겠네요!

어디서 본 글인지는 기억이 안나지만, ! < 이 연산자가 생각보다 눈에 안들어와서 클래스 내부에 메서드를 하나 추가해주는 한이 있더라도 부정연산자를 되도록 사용안하는게 좋다는 글을 본 기억이 나네요. 감사합니다~~

2024-03-27 11:20 UTC, jimi567 commented on src/main/java/chess/Controller.java
> +
> 결국 객체지향은 "설계상 어떠한가?" 보다는, "유지보수 시점에 어떠한가?" 가 더 중요한 가치라고 생각해요.

너무 공감되는 구문인 것 같아요.
클린코드나 객체지향에대한 식견이 좁아서, 만약 요구사항의 변경이 발생 할 때, 내가 어떻게 짜야 편하게 변경 사항이나 확장사항을 적용할까? 라는 생각을 가지고 프리코스를 진행했던 기억이 나네요.

그렇다고 클린코드나 객체지향에 관련한 학습을 안해도 되겠다! 는 아니지만,
정말 고민이 되거나 답이 잘 안보일 때는 초심으로 돌아가 저런 관점으로 다시 생각하면 좋을 것 같네요

2024-03-27 12:58 UTC, jimi567 reviewed
.

2024-03-27 13:16 UTC, jimi567 commented on src/main/java/chess/domain/piece/AbstractPiece.java
> +    }
제가 널 체크를 자꾸하는게 귀찮아서 더미피스(널 객체)를 사용했습니다.
그에 따라 저 두 메소드를 추가해서 보드의 특정 위치에 있는 piece가 널 객체인지 아닌지를 판단해주었습니다.

piece 인터페이스가 이런 메서드를 가지고 있는게,
사용하는 입장에서는 "아 piece의 구현체중에 널객체가 있구나?" 를 알게 돼서 캡슐화가 깨지는걸까? 라는 의문점이 듭니다.

현구막은 어떻게 생각하시나요 ?

2024-03-29 04:20 UTC, Hyeon9mak approved these changes
안녕하세요 위브! 피드백 반영 고생하셨습니다 👍 
전반적으로 비슷한 기조의 코멘트를 많이 남겨드렸는데,
위브만의 스타일로 잘 이해해주신 것 같아요.
결국 모든건 유지보수를 위해서다... ㅎㅎㅎ

몇 가지 간단한 코멘트만 남겼는데요, 다음 단계를 진행하시면서 함께 확인해주시면 될 것 같아요.
가능하면 3단계와 4단계를 분리하여 진행해보시길 추천드립니다.

다음 단계에서 뵐게요!

2024-03-29 04:20 UTC, Hyeon9mak commented on src/main/java/chess/Controller.java
> +        }
> 만약 이 부분의 요구사항이 변경돼서,
도착위치, 시작위치 순으로 입력받아라 한다면, 저 코드를 구현했던 저를 제외하고는 어느 부분을 바꿔야 할지 감 잡기가 힘들 것 같다는 생각이 들었어요.

협업하기 좋은 개발자에 한발자국 더 다가가셨군요 💯

2024-03-29 04:20 UTC, Hyeon9mak commented on src/main/java/chess/domain/piece/fixedmove/FixedMovePiece.java
> +
사소한 행동들이 결국 습관과 버릇이 되고, 반복되면서 큰 결과물을 만들어내니까요 👍 체화하시면 좋겠습니다 👍

2024-03-29 04:20 UTC, Hyeon9mak commented on src/main/java/chess/domain/piece/fixedmove/Knight.java
> +        );
👍 한 눈에 상상이 되네요!

2024-03-29 04:20 UTC, Hyeon9mak commented on src/main/java/chess/domain/piece/AbstractPiece.java
> +    }
> 사용하는 입장에서는 "아 piece의 구현체중에 널객체가 있구나?" 를 알게 돼서 캡슐화가 깨지는걸까? 라는 의문점이 듭니다.

위브 말씀대로 캡슐화 깨진다고 볼 수 있겠어요. 
(답변을 어느정도 예측하시겠지만) "Null 객체가 있다는 사실이 드러났을 때 유지보수가 어려운가?" 를 고민해보면 되겠네요.

제가 보았을 땐 그정도는 드러나더라도 충분히 좋은 선택이라고 보여요.
특히 위브가 직접 편의를 위해서("제가 널 체크를 자꾸하는게 귀찮아서") 진행하신 일이니까요 👍 👍

2024-03-29 04:20 UTC, merged