[1, 2단계 - 체스] 폭포(이성주) 미션 제출합니다.
woowacourse/java-chess pull request #695
Opened 2024-03-21 08:41 UTC by BurningFalls

안녕하세요! 폭포입니다.

체스 미션 1, 2단계 구현 마쳐 PR 보냅니다.

리뷰 부탁드립니다. 감사합니다. 😄

2024-03-22 12:34 UTC, JunHoPark93 requested changes
안녕하세요 폭포~
1단계 구현하느라 고생많으셨습니다.
구조자체는 잘 만들어주신거같아요. 몇가지 피드백 남겼는데 확인 후 의견 및 반영부탁드려요!

2024-03-22 12:34 UTC, JunHoPark93 commented on src/main/java/chess/domain/Board.java
> +        }
움직일때마다 새로운 객체를 생성하는건 의도하신거죠?
pieceInfo라고 만들어주신 객체에 질의하는 형태로 구현하면 더 좋을거같네요!

2024-03-22 12:34 UTC, JunHoPark93 commented on src/main/java/chess/controller/ChessGame.java
> +        return board.getBoard().get(source).isSameTeam(team);
연속된 getter를 개선할 수 있는 방법이 있을까요?

2024-03-22 12:34 UTC, JunHoPark93 commented on src/main/java/chess/domain/piece/Pawn.java
> +    public Pawn move(Position newPosition, boolean isDisturbed, boolean isOtherPieceExist, boolean isSameTeam) {
상위 type으로 리턴해도 되지 않을까요? 🤔

2024-03-22 12:34 UTC, JunHoPark93 commented on src/main/java/chess/domain/piece/ChessPiece.java
> +        return Objects.equals(pieceInfo, that.pieceInfo) && Objects.equals(moveStrategy,
말의 동등성을 비교할때 moveStrategy를 활용하는게 맞을까요?

2024-03-22 12:34 UTC, JunHoPark93 commented on src/main/java/chess/domain/piece/Pawn.java
> +        return new Pawn(newPieceInfo, changeMovedStrategy());
움직일때마다 새로운 movestrategy객체가 생성되는거같은데 개선이 가능할까요?

2024-03-22 12:34 UTC, JunHoPark93 commented on src/main/java/chess/controller/ChessGame.java
> +        if (START.sameCommand(startCommand)) {
일단 Command로 만든후에 isStart등을 구현하는게 더 가독에 좋지 않을까요?

2024-03-22 12:34 UTC, JunHoPark93 commented on src/main/java/chess/domain/strategy/BlackPawnFirstMoveStrategy.java
> +}
canMoveStraight, canMoveDiagonal 계산이 4개의 클래스 (blackPawnFirst, blackPawnNotFirst, whitePawn...)에서 비슷한 패턴을 가지고있는데 개선해볼 수 있을까요?

2024-03-22 12:34 UTC, JunHoPark93 commented on src/main/java/chess/domain/PositionDifference.java
> +    }
(참고만해주세요!) 
매번 움직일때마다 abs계산을 하는데 미리 계산해두고 재사용할 수도있을거같네요

2024-03-22 12:34 UTC, JunHoPark93 commented on src/main/java/chess/domain/Board.java
> +        this.board = board;
생성자내에서 로컬변수를 따로 만들지말고 initialize()반환값으로 한번에 초기화하는건 어떨까요?

2024-03-22 12:34 UTC, JunHoPark93 commented on src/main/java/chess/domain/Board.java
> +                checkObstacleInRange(source, target),
move인자에서 disturb 를 사용하셨는데 단어를 통일시켜보면 어떨까요?

2024-03-22 12:34 UTC, JunHoPark93 commented on src/main/java/chess/domain/piece/Bishop.java
> +    }
isMoveInvalid 라는건 canMove 의 역으로 생각이되는데 실제로 여러 조건들의 결합이 필요하네요. 가독성을 높일 수 있는 방법이 있을까요?
다른부분들도 마찬가지입니다!

2024-03-22 12:34 UTC, JunHoPark93 commented on src/main/java/chess/domain/piece/ChessPiece.java
> +    final PieceInfo pieceInfo;
제한자가 없는건 의도하신걸까요?

2024-03-23 01:25 UTC, BurningFalls commented on src/main/java/chess/domain/Board.java
> +        }
> 움직일때마다 새로운 객체를 생성하는건 의도하신거죠?

해당 객체를 넘겨받은 쪽에서 객체의 필드를 변경할 수 있는 위험성이 있다고 판단하여, 원래 객체는 원래 객체의 값을 그대로 유지하기 위해 새로운 객체로 생성했습니다.

현재 체스 프로그램 로직 상에서 위험이 있는지 판단한 것이 아니라 무조건 이렇게 방어하는 편입니다. 메모리를 새로 할당한다는 단점이 있지만, 값을 보호하는 것이 더 중요하다고 생각했기 때문입니다.

---

추가로 제 코드에서 실제로 위험성이 존재하는지 검증해보았습니다.

`Piece piece = board.get(source);`은 `piece` 객체를 방어적 복사 없이 그대로 가져옵니다. 따라서 `piece.pieceInfo`를 `new PieceInfo(changedPosition, changedTeam)`으로 재할당하게 되면, `Board`에 있는 값도 함께 변경되어 버립니다.

물론 체스 로직 상으로는 체스 말이 이동하면 값이 새로운 값으로 변경되어야 하는 것이 맞지만, 다른 방식으로 변경가능한 위험성 또한 열어두기 때문에 안전하지 않습니다.

---

다음과 같이 분석해보았습니다. 혹시나 제가 놓쳤거나 틀린 부분이 있다면 확인해주시면 감사합니다.

2024-03-23 01:33 UTC, BurningFalls commented on src/main/java/chess/domain/Board.java
> +        }
> pieceInfo라고 만들어주신 객체에 질의하는 형태로 구현하면 더 좋을거같네요!

디미터의 법칙을 제대로 지키지 않았네요. 하드코딩하고 리팩토링을 했어야 했는데 미처 확인하지 못한 부분입니다.

`PieceInfo` 클래스에 아래 메서드를 만들어서 해결했습니다.

```java
public boolean isSamePosition(Position otherPosition) {
    return position.equals(otherPosition);
}
```

2024-03-23 02:00 UTC, BurningFalls commented on src/main/java/chess/controller/ChessGame.java
> +        return board.getBoard().get(source).isSameTeam(team);
마찬가지로 하드코딩이후 리팩토링을 했어야 하는데 제대로 체크하지 못한 부분이네요. 아래와 같이 수정했습니다.

```java
    private boolean isOppositeTurn(Position source, Team team) {
        return board.isPieceFromOtherTeam(source, team);
    }
```

```java
public boolean isPieceFromOtherTeam(Position source, Team team) {
    Piece piece = board.get(source);
    return !piece.isSameTeam(team);
}
```

2024-03-23 02:12 UTC, BurningFalls commented on src/main/java/chess/domain/piece/Pawn.java
> +    public Pawn move(Position newPosition, boolean isDisturbed, boolean isOtherPieceExist, boolean isSameTeam) {
하위 타입으로 리턴하는 것과 상위 타입으로 리턴하는 것에 큰 차이를 느끼지 못하고 주변 크루들에게 물어봤습니다. 

`ChessPiece`에서 `ChessPiece`를 리턴하도록 메서드를 만들었기 때문에, 형식을 오버라이드된 곳에서도 통일하려면 `ChessPiece`가 맞지 않냐라는 의견을 들었습니다. 이 의견을 듣고 100% 동의해서 바꿨습니다.

혹시 제이가 생각하는 상위 타입으로 리턴해야하는 다른 이유가 있나요? 있다면 새로운 인사이트를 얻고 싶습니다.

2024-03-23 02:30 UTC, BurningFalls commented on src/main/java/chess/domain/piece/ChessPiece.java
> +        return Objects.equals(pieceInfo, that.pieceInfo) && Objects.equals(moveStrategy,
제이의 리뷰를 읽고 다시 생각해보니, 위치와 색깔을 담고 있는 `PieceInfo`가 다르면 서로 다른 말임이 자명하기 때문에 `moveStrategy`를 굳이 활용할 필요는 없다는 것을 느꼈습니다.

해당 코드를 삭제했습니다.

2024-03-23 02:56 UTC, BurningFalls commented on src/main/java/chess/controller/ChessGame.java
> +        if (START.sameCommand(startCommand)) {
말씀해주신대로 메서드를 만들어 가독성을 높였습니다.

```java
private boolean isStart(String command) {
    return START.sameCommand(command);
}

private boolean isMove(String command) {
    return MOVE.sameCommand(command);
}

private boolean isEnd(String command) {
    return END.sameCommand(command);
}
```

2024-03-23 05:06 UTC, BurningFalls commented on src/main/java/chess/domain/strategy/BlackPawnFirstMoveStrategy.java
> +}
`ChessPiece`를 만들었던 것처럼, 네 폰이 공통 로직을 갖고 있으므로 하나의 추상 클래스로 묶을 수 있네요!

`PawnMoveStrategy` 추상 클래스를 두어 공통 로직으로 묶고, 네 폰 클래스가 이 클래스를 상속받도록 바꾸었습니다. 각 폰 클래스에서 갖는 `MOVE_RANGE` 값들은 고정이므로, 전략 생성 즉시 갖고 있는 상수값으로 초기화되도록 했습니다.

2024-03-23 05:18 UTC, BurningFalls commented on src/main/java/chess/domain/PositionDifference.java
> +    }
```java
for (int i = 0; i < 100 * 100 * 100; i++) {
    // logic
}
```

위와 같이 구현하면 `100*100*100` 연산을 반복문이 백만번 돌 때마다 쓸데없이 계산해버리는 것과 비슷한 문제네요!

```java
int threshold = 100 * 100 * 100;
for (int i = 0; i < threshold; i++) {
    // logic
}
```

이런 식으로 미리 계산해두고 사용하는게 좋다는 것에 저 또한 완전히 동의합니다.

2024-03-23 05:23 UTC, BurningFalls commented on src/main/java/chess/domain/piece/Pawn.java
> +        return new Pawn(newPieceInfo, changeMovedStrategy());
전략은 내부 필드가 변화하는 것이 아니기 때문에 새로운 객체를 생성할 필요가 없네요. 내부에서 상수로 정의해서 받는 식으로 변경했습니다.

2024-03-23 05:32 UTC, BurningFalls commented on src/main/java/chess/domain/Board.java
> +        this.board = board;
`initialize`가 `Map`을 반환하면 생성자에서 굳이 로컬변수를 만들 필요가 없어지네요! 수정했습니다.

2024-03-23 05:37 UTC, BurningFalls commented on src/main/java/chess/domain/Board.java
> +                checkObstacleInRange(source, target),
`checkObstacleInRange`를 `checkDisturbed`로 바꾸기에는 파라미터로 `source`와 `target`을 받고 있기 때문에 어색하게 느껴졌습니다. 따라서 `isDisturbed`를 `isObstacleInRange`로 바꾸었습니다.

나머지 메서드명도 변수명들과 통일시켜 변경했습니다.

2024-03-23 05:53 UTC, BurningFalls commented on src/main/java/chess/domain/piece/ChessPiece.java
> +    final PieceInfo pieceInfo;
제한자가 없으면 자동으로 `default`가 되는데, 다시 생각해보니 상속받는 클래스가 부모 클래스의 필드를 사용 가능하게 한다는 의미에서는 `protected`로 확실하게 선언해주는 것이 더 좋을 것 같다는 생각이 들었습니다.

접근제한자를 `protected`로 수정했습니다.

2024-03-23 06:08 UTC, BurningFalls commented on src/main/java/chess/domain/piece/Bishop.java
> +    }
너무 함수 길이를 줄이는 데에 매몰되어 있었던 것 같네요. 아래와 같이 다른 모든 클래스들을 수정했습니다.

```java
    @Override
    public boolean isMoveInvalid(Position newPosition, boolean isDisturbed, boolean isOtherPieceExist,
                                 boolean isSameTeamExist) {
        Position currentPosition = pieceInfo.getPosition();
        if (!moveStrategy.canMove(currentPosition, newPosition)) {
            return true;
        }
        if (isDisturbed || isSameTeamExist) {
            return true;
        }
        return false;
    }
```

2024-03-23 06:10 UTC, BurningFalls commented
상세한 리뷰 감사합니다 제이!

RC 확인부탁드립니다. 감사합니다.

2024-03-23 16:04 UTC, BurningFalls commented
상세한 리뷰 감사합니다, 제이!

수정한 내용 확인부탁드립니다. 감사합니다.

2024-03-24 02:13 UTC, JunHoPark93 commented on src/main/java/chess/domain/Board.java
> +        }
넵 잘 생각해주셨어요~

2024-03-24 02:19 UTC, JunHoPark93 commented on src/main/java/chess/domain/piece/Pawn.java
> +    public Pawn move(Position newPosition, boolean isDisturbed, boolean isOtherPieceExist, boolean isSameTeam) {
통일성측면에서의 이유가 전부였을까요?

다형성 기본원리, 구체적인 사항보다는 인터페이스나 추상클래스제공하는 기능에 집중할 수 있게끔 추상화수준향상, 시스템의 한 부분을 변경할 때 영향을 줄일 수 있게끔 코드간 결합도 감소등 여러이유가 있는데 이 내용들을 정리해보셨으면 좋겠어요. 
제가 설명드리는것보다 자료가 매우 많이 나와있으니 스스로 학습해보시길 바랍니다.

2024-03-24 02:22 UTC, JunHoPark93 commented on src/main/java/chess/domain/strategy/PawnMoveStrategy.java
> +public abstract class PawnMoveStrategy implements MoveStrategy {
잘 분리해보셨네요 👍🏼

2024-03-24 02:22 UTC, JunHoPark93 commented on src/main/java/chess/domain/piece/Bishop.java
> +    }
극단적인 요구사항을 지켜보면서 발생할 수 있는 사이드이펙트를 잘 경험해보셨네요!

2024-03-24 02:24 UTC, JunHoPark93 approved these changes
안녕하세요 폭포~
리뷰 잘 반영해주셨네요.
구조를 더 간단히 만드는게 쉽지 않았을텐데 잘해주셨습니다!
타입관련해서 코멘트 남겨드린부분은 정리하셔서 다음번 미션 진행하실때 첨부해주시면 더 좋을거같아요~

2024-03-24 02:24 UTC, merged

2024-03-25 23:19 UTC, BurningFalls commented
자바에 대해서 깊이있는 공부를 하지 않은 상태에서 시작했다보니, 객체지향의 다형성에 대해서 모르고 있었습니다. 지금까지 자연스럽게 사용해온 인터페이스와 추상 클래스를 비롯한 것들과 제가 하게 된 고민들, 짚어주신 부분에 대한 해답이 전부 다형성에 담겨 있었네요. 이번 기회에 공부하면서 확실하게 정리할 수 있었습니다. 정말 감사합니다! 🙇

---

"자바의 정석" 책을 읽고 다형성에 대해서 학습한 내용을 제 블로그에 정리해봤습니다.

[[Java] 객체지향에서 다형성(Polymorphism)이란?](https://burningfalls.github.io/java/what-is-polymorphism/)

---

아래는 제 미션에서 실제로 다형성의 이점을 이용한 코드입니다. 상위 타입을 리턴함에 따라, 추상클래스에서 공통 함수로 묶을 수 있게 되었습니다. (추상화 수준 향상)

> 원래는 코드가 변화한 모습을 하나의 커밋(ex. `refactor: 다형성 적용`)으로 보여드려야 하지만, git을 잘못 건드리는 바람에 conflict를 수동으로 해결하면서 변경했던 모든 복잡한 사항을 한 커밋에 담아버릴 수밖에 없었습니다. 그래서 부득이하게 직접 코드로 보여드리는 점 양해부탁드립니다.

```java
// 다형성 적용 전
public class Bishop extends ChessPiece {
    // ...
    @Override
    public Bishop move(Position newPosition, boolean isObstacleInRange, boolean isOtherPieceExist, boolean isSameTeamExist) {
        if (isMoveInvalid(newPosition, isObstacleInRange, isOtherPieceExist, isSameTeamExist)) {
            return this;
        }

        PieceInfo newPieceInfo = pieceInfo.renewPosition(newPosition);
        return new Bishop(newPieceInfo, moveStrategy);
    }
}
public class King extends ChessPiece {
    // ...
    @Override
    public King move(Position newPosition, boolean isObstacleInRange, boolean isOtherPieceExist, boolean isSameTeamExist) {
        if (isMoveInvalid(newPosition, isObstacleInRange, isOtherPieceExist, isSameTeamExist)) {
            return this;
        }

        PieceInfo newPieceInfo = pieceInfo.renewPosition(newPosition);
        return new King(newPieceInfo, moveStrategy);
    }
}
```

```java
// 다형성 적용 후
public abstract class ChessPiece implements Piece {
    // ...
    @Override
    public ChessPiece move(Position newPosition, boolean isObstacleInRange, boolean isOtherPieceExist, boolean isSameTeamExist) {
        if (isMoveInvalid(newPosition, isObstacleInRange, isOtherPieceExist, isSameTeamExist)) {
            return this;
        }

        PieceInfo newPieceInfo = pieceInfo.renewPosition(newPosition);
        return createNewPiece(newPieceInfo);
    }

    @Override
    public abstract ChessPiece createNewPiece(PieceInfo newPieceInfo);
}

public class Bishop extends ChessPiece {
    // ...
    @Override
    public ChessPiece createNewPiece(PieceInfo newPieceInfo) {
        return new Bishop(newPieceInfo, moveStrategy);
    }
}
public class King extends ChessPiece {
    // ...
    @Override
    public ChessPiece createNewPiece(PieceInfo newPieceInfo) {
        return new King(newPieceInfo, moveStrategy);
    }
}
```