[1, 2단계 - 체스] 카키(서현준) 미션 제출합니다.
woowacourse/java-chess pull request #696
Opened 2024-03-21 08:42 UTC by hyeon0208

안녕하세요 !
이번 미션에서는 특히 코드를 보는 상대방 입장을 생각해 코드의 가독성이 좋을 수 있게 노력해보았습니다.
또한 객체가 한 가지 일만을 담당할 수 있도록 최대한 분리해 보았는데 

---
❓이것이 궁금해요

## 폰의 공격 기능을 위한 파라미터 추가
다른 기물들은 이동할 수 있는 위치에 상대 기물이 있다면 공격할 수 있지만 폰은 이동 조건과 공격 조건이 달라 추상 메서드에 도착 지점에 있는 기물 매개변수(Piece)를 추가했어요.
폰을 제외한 다른 기물들은 piece 매개변수를 사용하진 않는데 폰만을 위해 매개변수가 추가 되었다는 것이 조금 찜찜하더라구요..
그래서 다른 방법인 isAttack()같은 추상 메서드를 추가하는 것에 대해 고려 해봤는데 폰 하나 때문에 모든 기물들이 필요하지 않는 기능이 추가되는 것이 꺼려졌어요
그래서 여러 고민을 하다 모든 기물들에 불필요한 기능이 추가되기보다는 매개변수를 추가하는 방법을 생각했는데
폰만을 위해 매개변수가 추가되었다는 점이 문제가 될 수 있을까요?

이외에도 부족한 부분들에 대해 서슴없이 마구마구 말씀해주시면 감사하겠습니다 😆

2024-03-22 13:49 UTC, Hyunta requested changes
안녕하세요 카키,
복잡한 구조를 잘 풀어내주셔서 읽기 편했습니다.
가독성에 신경써주신 점이 많이 느껴졌습니다👍🏻
관련해서 몇가지 커멘트 남겼는데 확인 부탁드립니다.
궁금한 내용이 있으면 언제든 DM 주세요!

2024-03-22 13:49 UTC, Hyunta commented on src/main/java/chess/domain/board/BoardFactory.java
> +    }
보드 초기화를 깔끔하게 잘 해주셨네요👍🏻

2024-03-22 13:49 UTC, Hyunta commented on src/main/java/chess/view/InputView.java
> +        System.out.println(MOVE_INFO_MESSAGE);
한눈에 보기 쉽게 textblock을 써보는건 어떨까요?
https://www.baeldung.com/java-text-blocks

2024-03-22 13:49 UTC, Hyunta commented on src/main/java/chess/Game.java
> +    }
DTO 변환로직은 PieceResponse에서 처리하는게 어떨까요?

2024-03-22 13:49 UTC, Hyunta commented on src/main/java/chess/view/OutputView.java
> +        return board;
[질문]
Array를 사용한 이유가 있을까요?

2024-03-22 13:49 UTC, Hyunta commented on src/main/java/chess/view/OutputView.java
> +    }
사소한 내용이긴한데 Status는 빼도 될 것 같습니다.
개인적으로 Status는 진행중, 진행완료, 준비 이런 보드의 상태가 떠올라요.

```suggestion
    private void printBoard(final char[][] board) {
        IntStream.range(0, board.length)
                .mapToObj(lineCount -> board[board.length - 1 - lineCount])
                .map(String::new)
                .forEach(System.out::println);
    }
```

2024-03-22 13:49 UTC, Hyunta commented on src/main/java/chess/view/InputView.java
> +    }
`move a1 a2` 를 받아와서 파싱하는 로직을 view에서 처리하면 어떤 이점이 있나요?

2024-03-22 13:49 UTC, Hyunta commented on src/main/java/chess/domain/square/File.java
> +    }
findFirst() vs findAny()
각각 언제 쓰는게 좋을까요?

2024-03-22 13:49 UTC, Hyunta commented on src/main/java/chess/domain/Movement.java
> +    }
수학을 이용해서 검증해주셨네요👍🏻
저도 수학을 좋아하기 때문에 방법에는 문제가 없다고 생각하는데,
가독성이 좋은 코드인지는 또 다른 질문인 것 같아요.

**반영하라는 이야기는 절대 아닙니다.**

한번 고민해보시라는 이유에서 전달드립니다.
Direction이라는 방향 개념을 사용해서 상하좌우에 해당하면 Cross 라고 작성되어있으면 조금더 직관적이지 않을까요?
그럼 Movement라는 다소 애매할 수 있는 객체의 개념이 확실히 잡힐 수도 있을 것 같아요

```java
    public boolean isCross(Direction direction) {
       return List.of(Direction.UP,Direction.DOWN,Direction.LEFT,Direction.RIGHT).contains(direction);
    }
```

2024-03-22 13:49 UTC, Hyunta commented on src/main/java/chess/domain/board/Board.java
> +    }
기물의 이동 조건을 추상 클래스로 잘 풀어내주셨네요👍🏻

2024-03-22 13:49 UTC, Hyunta commented on src/main/java/chess/domain/board/Board.java
> +    }
validate라는 메서드 이름을 조금 더 구체적으로 지어볼까요?

2024-03-22 13:49 UTC, Hyunta commented on src/main/java/chess/Game.java
> +        }
게임 중에 end를 입력해도 종료가 안됩니다.

2024-03-22 13:49 UTC, Hyunta commented on src/test/java/chess/domain/board/BoardTest.java
> +    Board board;
private 누락하신 것 같네요
```suggestion
class BoardTest {
    private Board board;
```

2024-03-22 14:08 UTC, Hyunta commented
> 그래서 여러 고민을 하다 모든 기물들에 불필요한 기능이 추가되기보다는 매개변수를 추가하는 방법을 생각했는데
폰만을 위해 매개변수가 추가되었다는 점이 문제가 될 수 있을까요?

체스를 구현하면서 Pawn 움직이는 조건이 독특해서 어떻게 풀어야할지 고민을 많이했던 것 기억이 나네요.
파라미터가 특정 경우를 위해 추가되었다는 것이 찜찜하게 느껴질 수 있고,객체 지향 설계 원칙 중 하나인 인터페이스 분리 원칙(ISP)을 위반하는 것처럼 보일 수 있을 것 같습니다
지금 상황에서는 piece를 넘겨주지 않고서 Pawn이 공격 움직임인지 확인하는게 어려울 것 같네요.

그런데 validateDestinationColor작업을 canMove에서 같이 진행해주면 공격대상인지 확인하는 로직을 piece 쪽으로 넘겨볼 수 있지 않을까요?
여전히 destination의 piece를 넘겨줘야하는데 해당 값을 이용해서 지금 공격이 가능한 대상인지 확인하는 로직은 모든 기물에서 공통으로 사용할 수 있을 것 같습니다.
의문점이 생기면 언제든 DM 주세요!

2024-03-23 13:47 UTC, hyeon0208 commented on src/main/java/chess/view/InputView.java
> +        System.out.println(MOVE_INFO_MESSAGE);
이런 방법도 있었네요 !
확실히 텍스트 블록으로 출력 메시지를 묶으니까 한 눈에 보기 편하다는 생각이 들었어요 😀

이 부분에 대해 수정하다 궁금한점이 생겨서 질문 드립니다 !
텍스트 블록으로 감쌀 시에 상수를 사용하게 되면 오히려 가독성이 떨어질 수 있을 것 같아서 상수를 제거 하고 메시지를 그대로 드러나게 했어요
이 부분에 대해서 메시지를 "상수화한다 vs 안한다"에 대해 아서의 의견이 궁금해졌습니다.
저의 경우에는 재사용 될 일이 없다고 판단되는 출력용 메시지는 상수화를 하지 않고 문자열을 그대로 작성하는 편이였습니다.
출력 메시지는 이미 문자에서 의도가 드러나는데 상수화를 하는 것 상수 네이밍까지 생각해야하는 비용이 든다고 생각했기 때문이였어요.
하지만 페어와 이 점에 대해 논의 하다 이번에는 메시지도 상수화를 해 메시지에 대한 요구사항이 변경될 경우 상수를 모아 둔 클래스 상단에서 한 번에 관리하기 편하지 않을까?로 결론을 내고 상수로 정의해보았는데
아서의 경우에는 출력용 메시지를 "상수화 한다 vs 안한다" 중 어디 쪽이 신가요 ??

2024-03-23 14:10 UTC, hyeon0208 commented on src/main/java/chess/view/OutputView.java
> +    }
말씀대로 Status가 붙으면서 더 어색해지는 느낌이 드는 것 같아 제거했습니다
사소한 부분까지 꼼꼼한 리뷰 감사드립니다 😄

2024-03-23 15:05 UTC, hyeon0208 commented on src/main/java/chess/view/OutputView.java
> +        return board;
미션의 요구사항 중에 "배열 대신 컬렉션을 사용하라"라는 요구사항이 있어 ArrayList를 고려했었는데요
이 부분에 대해서 Array를 사용한 이유는 다음과 같았었습니다.

첫 번째로 체스판의 크기는 항상 8 * 8의 고정된 크기를 갖는다고 판단해 고정된 크기의 데이터를 다루기 위한 배열을 사용하고 싶었어요.
두 번쨰로는 접근하고자 하는 요소에 빠르게 접근할 수 있어서 기물의 위치들을 2차원 배열에 리스트 보다 빠르게 저장할 수 있을거라 생각했어요.

이러한 이유를 생각해 리스트 대신 배열을 사용했는데
아무래도 요구사항을 지키지 않은 부분이라 찜찜한 것 같네요 ..
아서의 생각은 어떠신가요 ? 요구사항을 어기면서까지 리스트 대신 배열을 사용한게 좋은 방법이였을까요 ?

2024-03-23 15:38 UTC, hyeon0208 commented on src/main/java/chess/view/InputView.java
> +    }
입력값을 파싱해서 반환해주는 역할을 InputView가 가질 수 있다고 생각해
view에서 파싱을 처리함으로써 컨트롤러에서 추가적인 로직을 수행하지 않아도 된다는 점이 장점으로 생각했습니다

지금 상황에서는 특별한 문제상황이 그려지지 않아서
이러한 방식이 혹시 문제를 일으킬 수 있을까요 !?

2024-03-23 15:52 UTC, hyeon0208 commented on src/main/java/chess/domain/square/File.java
> +    }
이 부분에 대해 이해가 부족했어서 질문에 대해 정리해보았습니다!

> findFirst()는 Stream의 순서를 고려해 조건에 일치하는 제일 첫 번째 요소를 반환하는 반면,
findAny()는 병렬 작업에서 최대 성능을 허용하기 위해 Stream의 순서를 고려하지 않고 조건에 일치하는 요소를 자유롭게 반환한다.

즉, 순서가 중요해 순서대로 처리된 결과를 기대할 경우 findFirst()
순서가 중요하지 않고 성능 최적화가 필요할 경우 FindAny()를 사용하는 것이 좋다고 결론을 지었습니다!

위 경우에는 인자의 값과 일치하는 지 여부를 판단해 순서는 중요하지 않다고 생각해
더 성능이 좋은 findAny()를 사용하도록 수정해 보았습니다!

2024-03-23 16:01 UTC, hyeon0208 commented on src/main/java/chess/domain/board/Board.java
> +    }
목적지로 이동하는 상황에서 발생할 수 있는 예외를 체크한다는 의미로
validateDestinationMove()로 네이밍해 보았습니다!

2024-03-23 16:10 UTC, hyeon0208 commented on src/test/java/chess/domain/board/BoardTest.java
> +    Board board;
테스트 코드 학습을 할 때 접근 제어자를 안붙히는 코드를 많이 접해서 그런지
default 제어자로 선언하는게 습관이 된 것 같아요 😅
다른 테스트와 필드가 공유될게 아니라면 private를 명시해 공유되는 필드가 아니라는 의도를 전달하면 좋을꺼 같네요 !

2024-03-23 17:03 UTC, hyeon0208 commented on src/main/java/chess/Game.java
> +        }
진행 중에 end를 입력하면 종료되도록 수정하였습니다!

2024-03-24 06:31 UTC, hyeon0208 commented on src/main/java/chess/Game.java
> +    }
서비스 레이어가 있었다면 이 변환 로직 또한 비즈니스로직으로 보고
서비스 레이어가 DTO 변환을 담당하게 했을 것 같은데
서비스 레이어가 없는 지금 상황에서 DTO 변환 로직을 어디서 처리하면 좋을까에 대해 고민했었어요

도메인 내부에 변환 로직이 있다면 순환 참조 문제 때문에 이는 배제했고,
DTO는 view에서 처리될 데이터기 때문에 컨트롤러에서 model을 받아 변환 후 view에 넘기는게 자연스럽지 않을까?라고 생각해 위와 같이 처리하게 했었어요

말씀대로 DTO 내부에서 변환 로직을 처리한다면 관련 로직이 해당 DTO에 모여있어 유지보수가 용이하고 컨트롤러 코드가 더 깔끔해질 것 같은데

```
public record PieceResponse(Square square, Piece piece) {

    public static List<PieceResponse> createResponses(final Map<Square, Piece> pieces) {
        return pieces.entrySet().stream()
                .map(entry -> new PieceResponse(entry.getKey(), entry.getValue()))
                .toList();
    }
```
DTO가 데이터 전달만이 아닌 키 값 별로 PieceResponse를 만들어 List<PieceResponse>를 반환하는 로직을 처리한다는게 조금 어색하게 느껴졌어요🤔

이에 대해서 아서의 의견이 궁금합니다!

2024-03-24 11:58 UTC, hyeon0208 commented on src/main/java/chess/domain/Movement.java
> +    }
개인적으로도 위 공식은 다른 사람이 볼 때 한 눈에 파악하기 어렵다고 느껴졌어서 한 눈에 파악할 수 있도록 해보고 싶었어요
아서가 말씀하신 방법대로 이동 방향을 관리하는 Enum 클래스 `direction`를 추가하고 이동 방향이 한눈에 파악 될 수 있도록 수정해보았습니다!

추가적으로 최대 이동가능한 거리에 대한 값도 상수를 통해 의미가 전달 될 수 있도록 해보았습니다 😄

2024-03-24 14:17 UTC, hyeon0208 commented
꼼꼼한 리뷰 감사드립니다 아서!
주말 잘 보내셨나요 ?? 리뷰 요청이 조금 늦은 것 같네요 😅

코멘트에 대해서는 답글을 남겼는데
리뷰를 반영하다 추가적으로 변경한 부분들이 있어 변경사항을 정리해보았습니다!
이번에도 잘부탁드립니다 🙇🏼‍♂️🙇🏼‍♂️

---
### ✅ 변경사항
> String 변환 로직 제거

이전에는 board의 라인을 출력하기 전에 String으로 변환하고 있었는데
String을 변환해야지만 얻을 수 있는 출력 결과도 아니고 해당 메서드가 매번 실행될 때마다
반복문을 돌면서 불필요한 변환 작업이 이뤄진다고 판단해 제거했습니다.

```java
    private void printBoard(final char[][] board) {
        IntStream.range(0, board.length)
                .mapToObj(lineCount -> board[board.length - 1 - lineCount])
                .forEach(System.out::println);
    }
```

<br>

> **char[][] board 캐시화**

이전에는 플레이어가 기물을 이동할 때마다 `printBoard()` 를 출력하고 이 내부에서는 
`setUpBoard()` 메서드가 매번 char[][] board를 생성하고 반환해주고 있었습니다.
하지만 지금같이 콘솔로 게임을 진행하는 환경에서는 멀티 스레드 상황을 고려하지 않아도 된다고 생각해
char[][] board를 static으로 선언해두고 메모리 사용량을 줄일 수 있도록 수정해 보았습니다.

```java
private static final char[][] board = new char[BOARD_SIZE][BOARD_SIZE];
```

여기서 궁금한점이 생겼는데, 해당 필드도 OutputView의 상태로 봐야할까요 ?
`char[][] board`의 상태는 매번 변경되고 있어 OutputView가 상태를 관리하는 것 처럼 보이는데,
저 같은 경우에는 이를 상태를 관리하기 보다는 출력을 위한 정보를 관리하는 것으로 생각하고 위 처럼 필드를 두게 되었습니다.
아서는 어떻게 생각하시나요 !?

<br>

> 명령어를 관리하는 객체 추가

인덱스를 이용해  현재 위치와 이동 위치를 가져오는 로직이 가독성이 떨어진다고 생각했습니다.
명령어를 관리하는 객체를 추가해 메시지를 통해 원하는 위치를 반환해주고
명령어에 end가 들어오면 종료하는 기능을 추가하면서,
명령어가 end인지 판단하여 반환해줄 수 있도록 하였습니다.

<br>

> 다음 위치 (Sqaure)를 구하는 로직을 Movement 클래스로 이동

기존에 Sqaure 내에서 다음 Square를 구하고 있었는데
Sqaure 객체가 자신만이 아닌 다른 Sqaure를 알고 있다는게 어색했어요 ..
이동 경로를 구할 때만 다음 Sqaure가 필요 해 해당 로직을
Movement 클래스 내부에서 사용하도록 옮겨 보았습니다.

<br>

> 어색한 네이밍 수정

이동 방향을 상수를 통해 직관적으로 전달할 수 있게 하면서 
전체적으로 코드를 리팩토링 진행하게 되었는데 조금 어색한 네이밍들이 있어
의도가 더 잘 전달 될 수 있도록 네이밍 수정해보았습니다.

2024-03-25 11:19 UTC, Hyunta commented on src/main/java/chess/view/InputView.java
> +        System.out.println(MOVE_INFO_MESSAGE);
답변을 하기에 앞서서 무작정 상수화를 하기보다는 왜 해야할까 고민하고 크루와 토론해본 점이 너무 좋네요💯

`왜 String, Integer 값에 대해서 상수화를 해야하는지?` 질문에 대한 답을 하고 결정해보면 좋을 것 같아요.
제가 생각할 때는 3가지 정도의 장점이 있을 것 같습니다.
1. 가독성
2. 유지보수 용이성
3. 성능 최적화
그런데 매직넘버를 상수화 하는데 있어서 가장 큰 가치를 가지는 것은 1번 가독성이라고 생각됩니다.
예를 들어서 카키가 InputView에 작성해준 `MOVE_COMMAND_DELIMITER`를 상수화하지 않았으면 왜 스페이스를 기준으로 나누고 있지? 라는 질문을 해소하기 위해서 요구사항을 읽어봐야 합니다.
```java
private static final String MOVE_COMMAND_DELIMITER = " ";
```

그렇다면 텍스트블록으로 작성해준 게임 안내 문구는 상수화하면서 어떤 가치를 가질 수 있을까요?
직관적으로 보기 위해서 상수화를 진행해보겠습니다.
```java
    public String readStartCommand() {
        System.out.print("""
                > 체스 게임을 시작합니다.
                > 게임 시작 : start
                > 게임 종료 : end
                > 게임 이동 : move source위치 target위치 - 예. move b2 b3
                """);
        String input = scanner.nextLine();
        validateGameCommand(input);
        return input;
    }
```
```java
    public String readStartCommand() {
        System.out.print(GAME_INTRODUCTION_ANNOUNCEMENT);
        String input = scanner.nextLine();
        validateGameCommand(input);
        return input;
    }
```
만약 멘트가 너무 길어서 메서드 파악하는데 문제가 생겼다면 장점을 가져갈 수 있었을 것 같아요.
그런데 개인적으로 상수화를 하게 되면 한번에 봐야하는 위치가 2곳으로 늘어나기 때문에 오히려 가독성이 줄어든게 아닌가 생각이 듭니다.
그렇다고 지금 재사용을 할 대상도 아니기 때문에 2,3번의 장점을 가져갈 수도 없습니다.
그래서 저도 카키가 해주신 것처럼 상수화를 진행하지 않을 것 같아요!

2024-03-25 11:36 UTC, Hyunta commented on src/main/java/chess/Game.java
> +    }
> 서비스 레이어가 있었다면 이 변환 로직 또한 비즈니스로직으로 보고

DTO 변환 로직을 비즈니스 로직으로 생각하신 이유가 궁금합니다.

> DTO는 view에서 처리될 데이터기 때문에 컨트롤러에서 model을 받아 변환 후 view에 넘기는게 자연스럽지 않을까?

현재는 model의 데이터로 DTO를 생성하고, 처리하는 위치가 view 입니다.
반대로 view에서 생성하고 model에서 처리해야하는 DTO가 필요할 수도 있지 않나요?
controllers를 model과 view를 이어주는 모듈로 생각하셨다면 dto의 위치또한 controller와 같은 패키지에 위치했어야했고, 그렇다면 controller에서 dto 생성 로직을 dto로 뽑아내는데 더 자연스러워졌을 것 같네요ㅎㅎ

> DTO가 데이터 전달만이 아닌 키 값 별로 PieceResponse를 만들어 List를 반환하는 로직을 처리한다는게 조금 어색하게 느껴졌어요🤔

말씀해주신 것처럼 지금 구성해주신 model, view, controller 구조에서 DTO의 역할은 각 모듈간에 데이터를 전달해주는 역할이죠.
그런데 데이터를 전달하려면 처음에 데이터를 누군가가 주입을 해줘야할 거에요. 그때 각 모듈에서 dto를 만들어서 전달을 해줘야한다면 현재 카키가 구상하고 있는 아키텍처에서는 controller 모듈이 제일 적합해 보입니다. 

의존성의 방향으로 한번 생각해볼까요?
controller의 code는 view, model이 모두 몰라야 합니다.
반대로 controller는 view, model 모듈을 모두 알아도 상관이 없죠 애초에 그런 역할이니까요.
이렇게 구조를 설계하셨다면 view에 필요한 dto는 view가 가지고 있어야할 것 같고, model에 필요한 dto는 model이 갖고 있어야할 것 같아요. 그런데 지금은 view한테 전달하기 위한 dto를 model이 가지고 있네요. 그럼 model에서 view로의 의존성이 생긴 것 아닐까요?

정리해보자면,
controller에 dto 생성 로직이 있나, dto에 생성 로직이 있나 어차피 원래 같은 모듈에 속해야했던 것 아니었을까? 입니다.

dto에 대한 고민은 어차피 레벨2부터 많이 고민해보실 단계라서 
제가 작성한 내용에 대해서 고민해보는 것으로 이번 미션에서는 충분하거나 조금 과도할 수도 있을 것 같네요.
이해가 안가는 내용이 있으면 DM을 주셔도 되고 스킵하셔도 됩니다.

2024-03-25 11:41 UTC, Hyunta commented on src/main/java/chess/view/OutputView.java
> +        return board;
제가 배열을 사용해서 구현을 잘 안하기 때문에 뚜렷한 단점을 잘 모를 수도 있습니다.
만약에 유지보수를 해야하는데 배열로 된 타입을 다뤄야한다면 컬렉션 보다는 데이터를 다루기위해 필요한 기능을 많이 제공하지 않아서 공수가 많이들 것 같습니다.
그래서 저는 List를 사용했을 것 같은데, 카키의 의견이 확고하시다면 배열로 유지하셔도 문제는 없을 것 같습니다.

2024-03-25 12:16 UTC, Hyunta approved these changes
안녕하세요 카키,
남겨드린 피드백 뿐만 아니라 개선하기 위해서 코드 수정을 많이 해주셨네요.
흐름이 더 쉽게 파악할 수 있게 개선된 것 같습니다.
남긴 커멘트에 답변 달아놨습니다.
다음 단계도 화이팅 입니다!

2024-03-25 12:16 UTC, Hyunta commented on src/main/java/chess/domain/Movement.java
> +    }
Direction을 구할 때 최대공약수를 이용하면 Knight도 같은 메서드를 사용할 수 있을 것 같습니다.
현재는 move b1 d5를 했을 때 방향이 잘못됐다고 나오는데, 엄밀히는 거리가 잘못된 요청인 것 같아서요

2024-03-25 12:16 UTC, Hyunta commented on src/main/java/chess/domain/piece/Bishop.java
> +    }
다른 기물들에서는 로직이 아주 깔끔하게 잘 만들어졌네요👍🏻

2024-03-25 12:16 UTC, Hyunta commented on src/main/java/chess/view/InputView.java
> +    }
개인적으로 파싱하는 것까지는 괜찮은데,
move에 대한 검증을 inputView에서 하는게 부적절할 수도 있다는 생각입니다.
입력을 `move a1 a2`로 했는데 controller에서는 `a1 a2` 가 들어온 List를 처리하게 되니 처음에 읽을때 파악이 필요했습니다.

2024-03-25 12:16 UTC, Hyunta commented on src/main/java/chess/domain/board/Board.java
> +    }
적절하게 반영해주신 것 같습니다!
여전히 Piece 내부에서는 불필요한 인자까지 넘겨주고 있긴 하지만
Pawn과 같이 추상화하려면 어쩔 수 없는 부분인 것 같습니다.

+validate 메서드를 구체적으로 작성해주세요

2024-03-25 12:20 UTC, Hyunta commented
> 여기서 궁금한점이 생겼는데, 해당 필드도 OutputView의 상태로 봐야할까요 ?
char[][] board의 상태는 매번 변경되고 있어 OutputView가 상태를 관리하는 것 처럼 보이는데,

좋아보이지는 않습니다.
요청이 올때마다 새롭게 만들어서 출력해주는 편이 안전해보여요
게다가 static으로 관리하게 되면 체스게임을 여러명이서 할때 재사용할 수도 없어집니다.
멀티 스레드와는 별도의 문제입니다. 애플리케이션을 단 한명을 위한 서비스로 설계하는 것은 좋아보이지 않습니다.

2024-03-25 12:21 UTC, merged

2024-03-25 14:27 UTC, hyeon0208 commented on src/main/java/chess/view/InputView.java
> +    }
해당 로직은 InputView에서는 입력값에 대한 구분자만을 검증하고 구분자로 문자열을 나눠 List로 만들어서 반환하고
Command 객체에서 이 List<String>을 받아 명령어를 검증하고 이동 전 위치와 이동 할 위치를 반환해주도록 수정했습니다

이 답글을 변경이 일어나기 전에 달았었는데 변경 후에 미쳐 생각하지 못했었네요 😅🙏🏻

2024-03-26 02:01 UTC, hyeon0208 commented on src/main/java/chess/domain/board/Board.java
> +    }
도착가능한지에 대한 여부를 검증하기에 validateArrival로 수정하였습니다!

2024-03-26 09:00 UTC, hyeon0208 commented on src/main/java/chess/domain/Movement.java
> +    }
눈치 못채고 있었는데 유효하지 않은 거리만큼 이동해도 방향이 잘못되었다고 나오고 있었네요 ..
거리 차이를 이용해 Direction을 찾다보니 b1 -> c4로 움직엿을 때 (1, 3)인 방향을 찾는데 이 방향이 없어서
방향에 대한 예외가 터지고 있었어요
말씀대로 최대공약수를 이용해 이동 단위를 구하고 이 이동 단위를 나누니까 x축과 y축에  대한 방향이 나오네요
최대 공약수를 활용하는 방법은 생각도 못했는데 인사이트 얻어 갑니다..👍🏻