[1, 2단계 - 체스] 에버(손채영) 미션 제출합니다.
woowacourse/java-chess pull request #700
Opened 2024-03-21 08:45 UTC by helenason

(작성 중)

2024-03-22 00:01 UTC, Gomding requested changes
안녕하세요 에버!
체스미션 함께하게 된 찰리입니다 🙇 

몇 가지 코멘트 남겼으니 확인해주세요~

궁금한 점 있으면 언제든 DM이나 코멘트 남겨주세요

2024-03-22 00:01 UTC, Gomding commented on src/main/java/controller/GameManager.java
> +public class GameManager {
> 패키지 이름에 대한 고민
> 
> 저희는 도메인과 뷰 사이를 연결하는 클래스를 GameManager로 두었습니다. MVC 패턴의 일부를 차용하여 Domain과 View를 분리하긴 하였지만 현재 저희의 GameManager는 게임 로직의 일부를 포함하고 있기 때문에 완전한 Controller는 아니라고 판단하였습니다. 그리하여 클래스명 또한 GameController가 아닌 GameManager라고 이름 지었습니다. 여기서 페어와 의견을 나누었던 부분은 패키지의 이름이었습니다. 아래는 저와 페어의 의견입니다.
> 
> 컨트롤러는 아니지만 controller라는 패키지를 통해 뷰와 도메인을 연결하는 역할임을 드러낼 수 있다. 컨트롤러라는 용어는 개발자 사이에서 도메인과 뷰를 연결하는 역할을 함축하므로 패키지를 통해 간접적으로 그러한 역할을 드러내는 것은 합당하다.
컨트롤러가 아니기 때문에 컨트롤러라는 용어를 사용하는 것보다는 우리만의 다른 용어를 정의하는 것이 낫다. 컨트롤러라는 용어를 사용하면 컨트롤러가 아닌 클래스에 컨트롤러라는 오해를 불러일으킨다.
위에 대해 찰리는 어떻게 생각하시나요?

`GameManager는 게임 로직의 일부를 포함하고 있기 때문에` 말씀하시는 게임의 로직의 일부가 도메인 로직의 일부를 의미할까요?
어떤 부분에서 도메인 로직의 일부가 포함됐다고 느끼셨을까요? 🤔 

GameManager에 만약 게임의 로직 일부(도메인 로직의 일부)가 포함됐다면 
저는 Controller 에 도메인 로직이 침범했다고 생각하고 도메인 로직을 제거하고
GameController 라는 이름을 부여할것같아요..! 😃 
결국 GameManager의 핵심 역할은 Controller 라고 생각해요!

에버는 어떻게 생각하시나요?

2024-03-22 00:01 UTC, Gomding commented on src/main/java/controller/GameManager.java
> +    private void playChess(Chess chess, List<String> moveTokens) {
playChess보다 `기물을 움직인다`는 메서드 이름이 부여되는게 메서드 행위에 어울리는것같아요 🤔 
에버는 어떻게 생각하시나요?

2024-03-22 00:01 UTC, Gomding commented on src/main/java/controller/GameManager.java
> +        PositionGenerator positionGenerator = new PositionGenerator();
PositionGenerator 는 playChess를 호출할때마다 매번 새로운 객체를 생성하고 있어요!
꼭 매번 새로생성해야하는 객체일까요?

한 번 생성해놓고 재사용하는걸 고려해볼까요..!

2024-03-22 00:01 UTC, Gomding commented on src/main/java/domain/position/PositionGenerator.java
> +        File file = FileInput.asFile(tokens.get(0));
PositionGenerator <-- 이녀석은 domain 객체인데
FileInput <-- 이녀석은 view의 mapper 객체군요 🤔 

domain 에서 view의 객체를 의존하는것으로 보여요 😢 
에버는 어떻게 생각하시나요?

2024-03-22 00:01 UTC, Gomding commented on src/main/java/controller/GameManager.java
> +    private final OutputView outputView = new OutputView();
객체 생성 시 내부 초기화하는것과 생성자에서 초기화하는 방법이 있는데
둘을 어떤 차이가 있을까요?

2024-03-22 00:01 UTC, Gomding commented on src/main/java/domain/board/SquaresGenerator.java
> +        Map<Position, Piece> squares = new LinkedHashMap<>();
LinkedHashMap 구현체를 사용한 이유가 궁금해요 🙋

2024-03-22 00:01 UTC, Gomding commented on src/main/java/domain/board/SquaresGenerator.java
> +public class SquaresGenerator {
복잡한 체스판(Board) 생성로직을 분리해주셨군요 👍 
Board 객체에서는 행위에 대한 메서드만 남아서 가독성이 좋겠어요 :)

2024-03-22 00:01 UTC, Gomding commented on src/main/java/domain/Chess.java
> +    public void play(Position sourcePosition, Position targetPosition) {
여기도 기물을 움직인다는 행위에 맞는 이름이 부여되면 좋겠어요! 😃

2024-03-22 00:01 UTC, Gomding commented on src/main/java/domain/Chess.java
> +        if (sourcePiece.isDifferentColor(targetPiece) && sourcePiece.canMove(sourcePosition, targetPosition)
턴제의 규칙도 구현되면 좋겠어요!

지금은 백 또는 흑이 두 번 이상 기물을 움직이는것이 가능하네요 😢

2024-03-23 21:20 UTC, helenason commented on src/main/java/domain/Chess.java
> +        if (sourcePiece.isDifferentColor(targetPiece) && sourcePiece.canMove(sourcePosition, targetPosition)
시간 부족으로 첫 리뷰 요청에서는 구현하지 못하였습니다 🥲
구현 후 리뷰 재요청드리겠습니다!

2024-03-23 21:22 UTC, helenason commented on src/main/java/domain/board/SquaresGenerator.java
> +        Map<Position, Piece> squares = new LinkedHashMap<>();
체스판을 출력할 때 칸의 순서대로 출력하기 위함입니다!
Key로 접근하는 로직 없이 value를 순서에 맞게 뽑아 outputView의 printBoard()에서 출력하고 있습니다 😊

2024-03-23 21:29 UTC, helenason commented on src/main/java/controller/GameManager.java
> +    private final OutputView outputView = new OutputView();
페어와 상의하여 클래스 내부에서 초기화하는 경우 필드에서 초기화하는 방향으로 통일했습니다!

외부에서 파라미터를 받아야 하는 경우 생성자 초기화가 필수이지만,
인스턴스 변수가 객체 내부에서 초기화되는 경우 필드에서 바로 초기화해도 큰 문제 없다고 판단하였습니다.

2024-03-23 21:34 UTC, helenason commented on src/main/java/domain/position/PositionGenerator.java
> +        File file = FileInput.asFile(tokens.get(0));
찰리 의견에 동의합니다.
명령어가 어떤 형태로 받아지는지에 대해서는 도메인이 모르도록 코드 수정하겠습니다!

2024-03-23 21:35 UTC, helenason commented on src/main/java/controller/GameManager.java
> +        PositionGenerator positionGenerator = new PositionGenerator();
정적 메서드로 수정하는 방향을 고려하다가, 하나의 메서드만을 분리하기 위한 클래스로 보여서
객체 생성 역할을 Position 클래스로 위임하였습니다!

2024-03-23 21:38 UTC, helenason commented on src/main/java/controller/GameManager.java
> +    private void playChess(Chess chess, List<String> moveTokens) {
맞습니다! 찰리의 리뷰를 반영하기 전 전체적인 리팩토링으로 코드가 많이 달라져, playGame 메서드가 tryMove를 호출하도록 네이밍하였습니다!

2024-03-23 21:49 UTC, helenason commented on src/main/java/controller/GameManager.java
> +public class GameManager {
네 맞습니다! 컨트롤러의 역할만을 가지고 있는 클래스라면 저도 GameController라고 이름 짓는 것이 합당하다고 생각합니다. 하지만 저희의 GameManager 클래스가 온전히 뷰 로직과 도메인 로직을 연결하는 역할만을 갖기는 힘들다고 판단하였습니다. 그래서 페어와 패키지 이름에 대해 많이 고민하였고 이에 대한 찰리의 의견이 궁금했습니다 🙂 즉, 완전한 컨트롤러는 아니지만 컨트롤러의 역할을 포함하고있는 클래스의 패키지 이름을 찰리는 어떻게 지으실 것 같나요?

2024-03-24 05:28 UTC, helenason commented on src/main/java/controller/GameManager.java
> +public class GameManager {
페어와 이 주제에 대해 다시 이야기하던 중 저희가 클래스명이나 패키지명보다는 `GameManager가 컨트롤러가 맞는가?`에서 의견이 갈린다는 것을 알게 되었습니다. 다시 정리하여 찰리의 의견을 묻고 싶습니다!

의견1: 뷰와 도메인을 연결하는 것이 컨트롤러니까 확실히 컨트롤러가 맞다. 클래스명에 Controller를 사용하지 않으려던 이유는 다른 수식어 없이 Controller만 있는 게 역할을 제대로 반영하지 못한다고 생각했기 때문이다. 그래서 패키지명은 controller로 확실히 해두고 클래스명을 사용자(View)와 각 도메인을 연결하는 역할을 하는, 현실세계를 반영할 수 있는 이름을 붙이고 싶었다.

의견2: 명확한 컨트롤러는 아니다. 뷰와 도메인을 연결하는 역할이 핵심은 맞지만, 추가적으로 체스판 초기화 메서드와 Command 확인 메서드를 호출하는 역할 또한 갖고 있기 때문에 게임이 진행되는 순서 일부를 컨트롤러가 알고 있다고 생각한다. 체스판을 초기화한다는 사실과 명령어를 통해 게임의 흐름이 진행된다는 사실이 컨트롤러에서 드러나기 때문이다. 따라서 컨트롤러가 아닌 클래스의 패키지명을 controller라고 지어도 괜찮은가?에 대해 고민했다.

찰리는 현재 저희의 GameManager를 컨트롤러라고 판단하시는지 궁금합니다! 😃

2024-03-24 07:04 UTC, helenason commented
찰리 안녕하세요!

전체적으로 크게 리팩토링 과정을 거치면서 예상보다 조금 늦게 PR 재요청 드립니다 😁

리팩토링하면서 중점을 두었던 부분을 설명드리고 싶어요!

## ✅ 리팩토링 포인트
### 1. Piece를 추상화하기

기존 코드에서는 Piece가 Type이라는 enum 클래스를 가지고 있었습니다. 기물의 전술을 Type에서 함수형 인터페이스로 관리하였습니다. 하지만 이 방식으로는 Pawn의 색깔 별 움직임을 구분하기 위해 외부에서 color 인자를 받아야했습니다. Type이 color를 아는 것이 어색하다고 생각했지만 첫 리뷰 요청 시에는 시간 부족으로 일단 구현해두었습니다. 리팩토링 과정을 거치면서 대공사를 진행하였습니다. Enum 클래스로 관리하던 기물의 타입을 Piece 클래스의 하위 클래스로 추상화하였습니다.

그러나 이 구조에서는 뷰 로직(display 메서드)을 도메인에서 분리하기가 어렵습니다. 이전의 코드에서는 enum 클래스의 mapper를 사용하였으나, 현재의 구조에서는 클래스의 타입을 하나씩 체크해야 하기 때문에 다형성이 깨져 추상화의 목적을 잃는다고 생각했습니다. 찰리라면 이러한 경우 어떻게 뷰 로직을 분리하실 건가요?

기존 코드
```java
public enum Type {

    BISHOP(Position::isDiagonal),
    KING(Position::isNeighbor),
    KNIGHT(Position::isStraightDiagonal),
    PAWN((source, target) -> source.isForwardStraight(target, false) || source.canAttackDiagonal(target, false)),
    QUEEN((source, target) -> source.isDiagonal(target) || source.isStraight(target)),
    ROOK(Position::isStraight),
    NONE((source, target) -> false),
    ;

    private final BiPredicate<Position, Position> tactic;

    Type(BiPredicate<Position, Position> tactic) {
        this.tactic = tactic;
    }

    public boolean canMove(Position source, Position target) {
        return tactic.test(source, target);
    }
}
```
현재 코드 - 다형성이 깨지는 코드
```java
if (piece.getClass() == Rook.class) {
    System.out.println("R");
}
if (piece.getClass() == Bishop.class) {
    System.out.println("B");
}
if (piece.getClass() == Queen.class) {
    System.out.println("Q");
}
...
```

### 2. Position에서 방향과 거리를 나누어 검증하기

기존 Position 클래스의 메서드는 target의 position을 파라미터로 받아 방향과 거리를 체크하여 옳은지, 옳지 않은지를 반환하도록 하였습니다. 하지만 각 기물의 전술에 맞는 방향과 거리를 Position 메서드가 알고 관리하는 것이 각 Piece에 의존한다고 판단하여 두 역할을 다른 메서드로 분리하여 Piece가 직접 골라 사용할 수 있도록 하였습니다.

예시) `직선방향으로 한 칸 앞인가` -> `직선방향인가` + `한 칸 앞인가`

추가로, 기존 클래스에서는 source와 target의 거리가 0, 1, 2인 경우에 대해  해당 클래스 내에서 체크하도록 구현하였는데, 이 숫자들이 기물의 전술에 해당한다고 판단하여 각 기물에서 허용하는 거리(0, 1, 2)를 외부에서 파라미터로 넣어주도록 하였습니다.

최대한 클래스의 역할에 맞는 행위만 부여하고 싶어 이런저런 생각을 하고 있는데, 아직 과정이 많이 어색해서 저의 이러한 생각의 흐름이 옳은 방향인지 찰리에게 묻고 싶습니다!

### 3. 깨끗한 코드 vs 성능

// 리팩토링 전 커밋 첨부
Chess 클래스의 tryMove 메서드를 리팩토링하는 과정에서, 파라미터의 수를 줄이기 위해 position으로 piece를 구하는 함수를 중복해서 많이 사용했습니다. 해당 함수는 Map 자료구조에서 키로 값을 가져오는 함수입니다. 시간복잡도가 1이기에  중복으로 크게 성능에 차이가 나지 않을 것이라 판단한 후 파라미터를 줄여 코드의 가독성을 높였습니다. 저는 이렇게 판단하였지만, 찰리의 생각 또한 궁금합니다! 찰리는 파라미터를 줄여 코드의 가독성을 높일 것인가요, 가독성이 좋지 않더라도 성능을 위한 코드를 작성할 것인가요?

### 4. Position 클래스의 캐시 사용

코드를 작성하다보니 Position 객체를 생성하는 로직이 많이 필요했습니다. Position은 file과 rank 속성값을 통해 객체를 판별할 수 있고 각 속성값이 불변인 VO에 해당하는데, 같은 객체를 여러번 생성하는 이 과정이 메모리를 불필요하게 많이 사용한다고 판단하였습니다. 따라서 클래스를 정의하는 과정에서 64개의 Position 객체를 캐싱해둔 후 필요한 경우 꺼내 사용할 수 있도록 리팩토링하였습니다! 캐싱을 처음 활용해보아서 아직 어색한데, 저의 생각의 흐름과 구현한 코드가 어색하지 않은지 찰리에게 묻고 싶습니다!

찰리의 리뷰를 반영하면서 크게 리팩토링을 진행한 부분은 위와 같습니다.

이번 리뷰도 잘 부탁드립니다!
감사합니다 ☺️

2024-03-24 07:40 UTC, helenason commented on src/main/java/domain/board/SquaresGenerator.java
> +        Map<Position, Piece> squares = new LinkedHashMap<>();
하지만.. Piece를 순서대로 저장해두는 것이 오직 출력을 위한 자료구조라면
이는 도메인이 뷰에 의존하는 형태인가? 하는 의문이 들었습니다.

따라서 체스판을 순서에 맞게 출력하는 책임을 OutputView에 위임하였습니다! (resolvePiecesByOrder 메서드)

2024-03-24 16:31 UTC, Gomding commented on src/main/java/controller/GameManager.java
> +public class GameManager {
> 즉, 완전한 컨트롤러는 아니지만 컨트롤러의 역할을 포함하고있는 클래스의 패키지 이름을 찰리는 어떻게 지으실 것 같나요?

완전한 컨트롤러가 아니라는것이 약간 모순으로 느껴지는데요..!
그럼 컨트롤러의 역할에 맞게 만들어주면 되는것은 아닐까하는 생각합니다 🤔 
View와 Domain은 나눴는데 둘 사이의 소통만을 담당하는 역할의 객체는 만들지 못했다..? 라고 이해했어요
이름을 보다는 GameManager의 내부 구조를 어떻게 리팩토링해야할까를 더 고민해야하는 상황같아요!

만약에 컨트롤러의 역할 + 다른 역할이 있다해도 Controller (패키지도 controller) 로 지어줄것같아요~!
나중에 다른 개발자가 보더라도 해당 클래스의 핵심 기능이 무엇인지 알 수 있으니까요!
GameManager라고 지어놓는다면 다른사람은 이걸 어떻게 받아들여야하는지 혼란스러울 수 있다고 생각되네요 :)

---

> 뷰와 도메인을 연결하는 역할이 핵심은 맞지만, 추가적으로 체스판 초기화 메서드와 Command 확인 메서드를 호출하는 역할 또한 갖고 있기 때문에 게임이 진행되는 순서 일부를 컨트롤러가 알고 있다고 생각한다.

Command를 어떻게 바라볼 것인지가 궁금해요!
체스 게임 도메인에서 Command 는 중요한 도메인 로직일까요? 🤔 
또는 View만을 위한 로직일까요?

만약 `콘솔 서비스 -> 웹 서비스` 로 변경된다면 Command는 어떻게 될까요? 😃 
웹 서비스일 때도 Command가 계속 사용될지 고민해볼 수 있어요!

2024-03-24 16:42 UTC, Gomding commented on src/main/java/controller/GameManager.java
> +    private final OutputView outputView = new OutputView();
제가 코멘트를 다소 애매하게 써놨네요😓
객체 생성 시 내부 초기화하는것과 생성자 주입 방식을 질문 드리고 싶었어요 😢 

필드에서 직접 초기화 한다면 해당 객체내에서 강하게 의존하게 된다는 부분이 있습니다!

물론 지금은 InputView와 OutputView가 추상화되어 있는것도 아니고
굳이 추상화할 필요도 없을것 같구요 😄 
생성자 초기화의 장점으로는 구현체를 바깥에서 지정해줄 수 있다는 것이에요.

예를들면 자동차 경주 때 움직임을 위한 숫자 생성 시 ~~Generator 라는 interface를 많이 보셨을 거에요.
요걸 필드에서 바로 초기화하는 것과 생성자에서 주입받는것은 다음과 같아요.

```java
// 필드 초기화
class CarRaceGame {
    private final MoveValueGenerator moveValueGenerator = new MoveValueRandomGenerator();
}

// 생성자에서 주입
class CarRaceGame {
    private final MoveValueGenerator moveValueGenerator;

    public CarRaceGame(final MoveValueGenerator moveValueGenerator) {
        this.moveValueGenerator = moveValueGenerator;
    }
}
```

생성자에서 주입받으면 구현체를 바깥에서 지정해줄 수 있어요.
결국 바깥에서 MoveValueGenerator의 구현체를 변경하더라도 CarRaceGame의 코드는 변경이 없겠죠!

2024-03-24 16:46 UTC, Gomding commented on src/main/java/domain/board/SquaresGenerator.java
> +        Map<Position, Piece> squares = new LinkedHashMap<>();
> 하지만.. Piece를 순서대로 저장해두는 것이 오직 출력을 위한 자료구조라면
이는 도메인이 뷰에 의존하는 형태인가? 하는 의문이 들었습니다.

저도 약간 모호했던 부분인데
편의를 위한 구현체(LinkedHashMap)를 지정할 수도 있다고 생각해요 😃 

에버의 입장에서는 아마 LinkedHashMap 을 사용하는것이 코드 작성하는데는 훨씬 편했을거라 생각해요!
view 쪽에서 사용하기도 편리하니까요 😃 

에버의 의견대로 도메인 입장에서는 꼭 필요한 구현체는 아니니까 잘 리팩터링 해주신거라 생각합니다~

2024-03-24 17:55 UTC, Gomding requested changes
안녕하세요 에버!
리팩터링 꼼꼼하게 해주셨네요 👍 👍 

질문에 대한 답변과 함께 코멘트 남겼어요!

궁금한 점 있으면 언제든 코멘트나 DM 남겨주세요~

2024-03-24 17:55 UTC, Gomding commented on src/main/java/domain/piece/King.java
> +        return "k";
> 리팩토링 과정을 거치면서 Enum 클래스로 관리하던 기물의 타입을 Piece 추상 클래스의 하위 클래스로 관리함으로써 외부에서 color를 받지 않아도 객체가 자체적으로 처리할 수 있도록 하였습니다. 그러나 이 구조에서는 뷰 로직(Piece의 display 메서드)을 도메인에서 분리하기가 어렵습니다. 이전의 코드에서는 enum 클래스의 mapper를 사용하였으나, 현재의 구조에서는 클래스의 타입을 하나씩 체크해야 하기 때문에 다형성이 깨져 추상화의 목적을 잃는다고 생각했습니다. 따라서 현재는 Piece 클래스에 display 메서드로 출력 형태를 관리하고 있습니다. 찰리라면 이러한 경우 어떻게 뷰 로직을 분리하실 건가요?

자세한 예시와 함께 질문주셔서 감사해요! 😃 
각 기물에서 view와 관련된 부분을 분리하기가 쉽지 않았죠..!

만약 다형성을 깨지 않고싶다면 Piece에 isKing, isKnight, isQueen ... 등등 메서드를 생성할 것 같은데
그러면 Piece의 인터페이스가 너무 지저분해지고 불필요한 코드가 너무 많이 생긴다고 생각해요 🤔 
그리고 단순히 view와 분리를 위해서 메서드가 생기는 것이니 마음이 불편하구요 ㅎㅎ..

저는 에버가 말한 Mapper 에서 각 클래스인지 확인하는것

```java
if (piece.getClass() == Rook.class) {
    System.out.println("R");
}
if (piece.getClass() == Bishop.class) {
    System.out.println("B");
}
if (piece.getClass() == Queen.class) {
    System.out.println("Q");
}
```

이 부분도 나쁘진 않다고 생각해요!
좋은 코드는 아니지만 단순히 DTO 변환을 위한 코드이고 중요한 도메인 로직도 아니니까요..! 🤔

2024-03-24 17:55 UTC, Gomding commented on src/main/java/domain/position/Position.java
> +    }
> 최대한 클래스의 역할에 맞는 행위만 부여하고 싶어 이런저런 생각을 하고 있는데, 아직 과정이 많이 어색해서 저의 이러한 생각의 흐름이 옳은 방향인지 찰리에게 묻고 싶습니다!

저는 좋은 방향으로 고민하고 변경하고 있다고 생각해요! 👍 
`클래스의 역할에 맞는 행위를 부여하는 것` 이것이 객체지향의 핵심 아닐까요? 😄

2024-03-24 17:55 UTC, Gomding commented on src/main/java/domain/Chess.java
> +        return sourcePiece.canAttack(sourcePosition, targetPosition) && targetPiece.isOppositeSide(sourcePiece);
> 해당 함수는 Map 자료구조에서 키로 값을 가져오는 함수입니다. 시간복잡도가 1이기에 크게 성능 차이가 나지 않을 것이라 판단한 후 파라미터를 줄여 코드의 가독성을 높였습니다. 저는 이렇게 판단하였지만, 찰리의 생각도 궁금합니다! 찰리는 파라미터를 줄여 코드의 가독성을 높일 것인가요, 가독성이 좋지 않더라도 성능을 위한 코드를 작성할 것인가요?

어떤 기능을 만들면서 성능에 문제가 생기리라 예측하는 것은 정말 힘들어요
(그게 성능이 정말 안좋아서 문제 생길게 뻔한것이 아니면요 ㅎㅎ..)

그렇다면 최선의 방법은 우선 가독성 높은 코드를 작성하고
성능 문제가 발생했을 때 리팩터링을 해보는것이 좋다고 생각합니다!
(테스트 코드가 있다면 리팩터링이 어렵지 않겠죠?)

2024-03-24 17:55 UTC, Gomding commented on src/main/java/domain/position/Position.java
> +    }
> 코드를 작성하다보니 Position 객체를 생성하는 로직이 많이 필요했습니다. Position은 file과 rank 속성값을 통해 객체를 판별할 수 있고 각 속성값이 불변인 VO에 해당하는데, 같은 객체를 여러번 생성함으로써 메모리를 불필요하게 많이 사용한다고 판단하였습니다. 따라서 클래스를 정의하는 과정에서 64개의 Position 객체를 미리 캐싱해둔 후 필요한 경우 꺼내 사용할 수 있도록 리팩토링하였습니다! 캐싱을 처음 활용해보아서 아직 어색한데, 저의 생각의 흐름과 코드가 어색하지 않은지 찰리에게 묻고 싶습니다!

저는 좋다고 생각해요~!

아마 체스 게임에서 자주 사용하게 될 객체라서
캐싱해두면 성능에 많은 도움이 될 수 있겠죠!

한가지 아쉬운것은 캐싱의 구현체가 List 라는 점인데
조회시 성능이 아쉬울것같네요 😢 
캐시 조회를 위한 key를 만들어보는것도 좋습니다!

2024-03-24 17:55 UTC, Gomding commented on src/main/java/view/OutputView.java
> +            System.out.println("화이트(소문자) 진영의 차례입니다.");
출력 메세지가 사용자에게 친절하군요 💯 💯 💯 💯 

![image](https://github.com/woowacourse/java-chess/assets/57378410/dbeedaeb-c23d-4364-8839-f36c1df673ac)

2024-03-24 17:55 UTC, Gomding commented on src/main/java/controller/GameManager.java
> +            return false;
체스 게임 진행 중 start를 입력하면 재시작 되는것은 의도하신 부분일까요?

![image](https://github.com/woowacourse/java-chess/assets/57378410/3b07524c-9efb-4f27-a0e6-8508b863bcfc)

2024-03-24 17:55 UTC, Gomding commented on src/main/java/domain/Chess.java
> +        validate(board.isBlocked(sourcePosition, targetPosition), "[ERROR] 다른 기물이 길을 막습니다.");
validateMovement의 validate 하는 부분과 순서가 명확하게 보여서 좋네요 👍  

+) validateMovement의 로직에 있는 에러 메세지들이 사용자에게 더 많은 피드백을 주면 좋겠어요!

2024-03-24 17:55 UTC, Gomding commented on src/main/java/domain/Chess.java
> +        // move()와 같은 역할의 함수지만 확장성을 위해 분리하였습니다.
주석을 달아서 설명해주셨군요 :)
필요하시다면 github 에서 해당 부분에 직접 코멘트 작성하셔도 좋습니다 😃 

+) 확장성을 위해서 분리했다는 의미가 어떤것인지 궁금해요!

2024-03-24 17:55 UTC, Gomding commented on src/test/java/domain/board/SquaresGeneratorTest.java
> +        assertThat(squares).hasSize(64);
`64개 인것만 검증하면 충분할까?` 라는 생각이 들었는데
에버는 어떻게 생각하시나요?

2024-03-24 17:55 UTC, Gomding commented on src/test/java/domain/piece/KingTest.java
> +     */
테스트 이해를 돕기위한 주석 💯 💯 💯 💯

2024-03-24 17:55 UTC, Gomding commented on src/main/java/domain/position/Position.java
> +                .orElse(new Position(file, rank));
Optional 에서 orElse 와 orElseGet은 어떤 차이가 있을까요?

[Java Optional 바르게 쓰기](https://homoefficio.github.io/2019/10/03/Java-Optional-%EB%B0%94%EB%A5%B4%EA%B2%8C-%EC%93%B0%EA%B8%B0/)

2024-03-24 17:55 UTC, Gomding commented on src/main/java/domain/position/Position.java
> +    private boolean isHorizontal(Position target) {
방향에 대한 enum 객체를 만들어서 처리해볼 수 있지 않을까 라는 생각을 해봤어요..!
에버는 어떻게 생각하시나요?

```java
public enum Direction {
    UP((source, target) -> source.getFile().isSame(target.getFile()) && source.getRank().isUp(target.getRank()));
    
    private final BiFunction<Position, Position, Boolean> isSomthing;
    
    Direction(BiFunction<Position, Position, Boolean> isSomthing) {
        this.isSomthing = isSomthing;
    }

    public boolean isSameDirection(Position source, Position target) {
        return isSomthing.apply(source, target);
    }
}

public class Rook extends Piece {
    List<Direction> directions = List.of(Direction.UP, Direction.DOWN, Direction.RIGHT, Direction.LEFT);

    @Override
    public boolean canMove(Position source, Position target) {
        return directions.stream()
                .anyMatch(direction -> direction.isSameDirection(source, target));
    }
}

```

최소한으로 작성한 코드라서 감안하고 봐주세요 ㅎㅎ..

2024-03-25 05:35 UTC, helenason commented on src/main/java/controller/GameManager.java
> +    private final OutputView outputView = new OutputView();
엇 아니요! 저는 찰리 코멘트 제대로 이해했었습니다. 제가 조금 모호하게 답변을 드린 것 같네요 😅

맞습니다. 저희도 지금은 외부에서 구현체를 주입받을 상황이 없기 때문에 필드에서 직접 초기화하는 방향으로 진행하였어요! 하지만 찰리의 의견을 듣고 보니, 나중을 위해 생성자에서 주입받는 방향으로 구현하는 것이 더 낫다고 생각했습니다. 객체 간 의존도를 최대한 낮추는 방향이 확장성을 위해서도 좋겠네요!

2024-03-25 07:51 UTC, helenason commented on src/main/java/domain/piece/King.java
> +        return "k";
오 도메인과 뷰의 중요도 관점에서도 생각해볼 수 있네요!
그렇다면 다형성을 지키느냐, 뷰가 도메인에 일부 의존하느냐의 차이겠군요!

나중을 생각했을 때, 뷰에 수정사항이 생겼을 때 도메인을 수정해야하는 상황이 발생하면 너무 번거로울 것 같아요.
그래서 찰리의 의견 반영하여 잠시 다형성을 깨는 방향을 적용하기로 하였습니다 ㅎㅎ!

2024-03-25 08:14 UTC, helenason commented on src/main/java/domain/piece/King.java
> +        return "k";
하지만.. if문을 나열하는 방식은 깔끔하지 않았고, 메서드 10줄 이하 요구사항도 충족하지 못했습니다.
따라서 PieceOutput 클래스를 생성하여 해당 클래스가 Piece의 타입과 출력 형태를 매핑하도록 하였습니다!

2024-03-25 08:16 UTC, helenason commented on src/main/java/domain/Chess.java
> +        return sourcePiece.canAttack(sourcePosition, targetPosition) && targetPiece.isOppositeSide(sourcePiece);
오! 좋은 말씀 감사합니다. 제가 성능을 예측하는 건 쉽지 않겠네요.
그렇다면 먼저 가독성을 우선으로 코드를 작성하도록 하겠습니다!

2024-03-25 08:53 UTC, helenason commented on src/main/java/domain/position/Position.java
> +    }
네! 찰리의 의견에 동의합니다.
기껏 성능 높이려고 캐싱을 도입했는데 조회 속도 때문에 성능이 낮아졌었네요.
이중 Map을 사용하여 file과 rank를 키로 Position을 조회하도록 하였습니다!

2024-03-25 08:54 UTC, helenason commented on src/main/java/controller/GameManager.java
> +            return false;
네 start 명령어를 입력받으면 게임을 초기화하도록 하였습니다!

2024-03-25 09:16 UTC, helenason commented on src/main/java/domain/Chess.java
> +        // move()와 같은 역할의 함수지만 확장성을 위해 분리하였습니다.
사실 attack()과 move()는 같은 역할을 하는 메서드인데,
이후 3, 4단계에서 공격할 경우와 이동할 경우의 로직을 다르게 처리하기 위해 메서드를 분리하였습니다!

2024-03-25 11:02 UTC, helenason commented on src/test/java/domain/board/SquaresGeneratorTest.java
> +        assertThat(squares).hasSize(64);
저도 `하나하나 다 확인하는 게 맞을까?`와 `이정도는 안 해도 괜찮지 않을까?` 사이에서 페어와 의논한 결과, 개수만 확인하고 넘어가기로 했었습니다. 하지만 저도 찰리와 같이 테스트는 빈틈이 없을수록 좋다고 생각하는 편이기 때문에 테스트 생성하도록 하겠습니다!

2024-03-25 11:16 UTC, helenason commented on src/main/java/domain/position/Position.java
> +                .orElse(new Position(file, rank));
orElse에 담긴 코드는 Optional이 null이 아니어도 무조건 수행된다는 특징이 있었네요.
새로운 객체를 생성하는 로직을 수행하고 싶을 땐 불필요한 객체 생성을 줄이기 위해 orElseGet를 사용해야겠어요!
좋은 코멘트 감사합니다 : )

2024-03-26 11:57 UTC, helenason commented on src/main/java/view/OutputView.java
> +            System.out.println("화이트(소문자) 진영의 차례입니다.");
감사합니다! 제가 사용자로서 게임에 참여했을 때 불편함을 느껴서 요구사항에 없는 로직이지만 추가해주었습니다 ㅎㅎ

2024-03-26 12:12 UTC, helenason commented on src/main/java/domain/Chess.java
> +        validate(board.isBlocked(sourcePosition, targetPosition), "[ERROR] 다른 기물이 길을 막습니다.");
감사합니다! 사용자에게 출력되는 에러 메시지 구체화하겠습니다.

2024-03-26 12:20 UTC, helenason commented on src/main/java/domain/position/Position.java
> +    private boolean isHorizontal(Position target) {
네 저도 Position 객체가 방향에 대한 모든 정보를 메서드로 관리하고 있는 부분이 너무 구체적이지 않다고 생각하였습니다.
Direction이 source와 target Position을 받아 방향을 판단하도록 하였고, Piece가 방향을 갖고 있도록 하니, 코드의 가독성이 더욱 향상되었습니다!

2024-03-26 12:22 UTC, helenason commented on src/main/java/controller/GameManager.java
> +        PositionGenerator positionGenerator = new PositionGenerator();
하지만.. 계속 새로운 로직을 추가하다보니 Position이 많이 무거워져, 생성 로직을 PositionGenerator로 다시 분리하였습니다 ㅎㅎ

2024-03-26 12:32 UTC, helenason commented on src/main/java/controller/GameManager.java
> +public class GameManager {
> Command를 어떻게 바라볼 것인지가 궁금해요!
> 체스 게임 도메인에서 Command 는 중요한 도메인 로직일까요? 🤔
> 또는 View만을 위한 로직일까요?

입력된 명령어를 Command 객체로 변환하는 역할은 뷰의 CommandInput에게 부여한 상태이고, Command 객체를 통해 게임의 전체적인 흐름이 진행된다고 판단하여 Command 객체를 controller 패키지로 이동하였습니다! Command를 컨트롤러로 바라보니 GameManager 또한 더욱 컨트롤러의 역할을 한다고 생각되네요!

> 만약 콘솔 서비스 -> 웹 서비스 로 변경된다면 Command는 어떻게 될까요? 😃
> 웹 서비스일 때도 Command가 계속 사용될지 고민해볼 수 있어요!

뷰 로직을 관리하는 CommandInput에는 변경 사항이 존재하겠지만, 콘솔 서비스가 웹 서비스로 변경되더라도 Command 객체는 그대로 사용될 것 같습니다!

2024-03-26 13:54 UTC, helenason commented
찰리! 이번에도 열심히 리팩토링하여 리뷰 요청 드립니다.

## 리팩토링 포인트
- 테스트 커버리지를 높이기 위해 여러 테스트 케이스를 추가하였습니다.
- Position 클래스에서 캐시 등의 역할이 많아지면서 클래스가 무거워졌습니다. 따라서 PositionGenerator를 다시 생성하였습니다.
    - 이 경우 PositionGenerator에서 Position을 생성하기 위해서는 Position 생성자를 최소 protected로 열어놓아야 합니다. 그래도 괜찮을까요?
- PositionGenerator 클래스의 generate 메서드는 file과 rank를 키로 두 번 값에 접근합니다. 제가 직접 정의한 File과 Rank가 아닌 경우 해당 코드는 NullPointerException 발생 가능성이 있습니다.

감사합니다 찰리! 이번 PR도 잘 부탁드려요 😁

2024-03-27 11:50 UTC, Gomding commented on src/main/java/domain/piece/King.java
> +        return "k";
제가 무슨 정신으로 코멘트를 썼는지 모르곘지만
각 기물을 확인하는 `isXXX` 를 쓰는것도 다형성을 꺠는거라 생각해요 😅
`instanceof` 와 별 차이가 없는 구현이라서요 ㅎㅎ..
결국 각 기물이 뭔지 확인하겠다는 소리이니..

2024-03-27 11:52 UTC, Gomding commented on src/main/java/domain/Chess.java
> +        return sourcePiece.canAttack(sourcePosition, targetPosition) && targetPiece.isOppositeSide(sourcePiece);
물론 성능을 완전 나몰라라 하는건 아니고
성능을 어느정도 챙기면서 가독성 우선의 코드를 작성하는게 필요합니다! 😃

2024-03-27 11:56 UTC, Gomding commented on src/main/java/domain/Chess.java
> +        // move()와 같은 역할의 함수지만 확장성을 위해 분리하였습니다.
미리 요구사항을 파악해두신것 같군요 😃

2024-03-27 12:00 UTC, Gomding commented on src/test/java/domain/board/SquaresGeneratorTest.java
> +        assertThat(squares).hasSize(64);
`체스판의 처음 기물들의 위치`는 체스에서 중요한 부분이라 생각해요 :)
누군가 SquaresGenerator를 수정하다가 기물 위치에 버그가 발생할 수 있죠 😃

2024-03-27 12:47 UTC, Gomding approved these changes
안녕하세요 에버!
이번 단계는 충분히 리팩터링 해주셨네요 :)
이만 merge 하겠습니다 🙏 

체스미션 다음 단계도 화이팅입니다~

2024-03-27 12:47 UTC, Gomding commented on src/main/java/domain/position/PositionGenerator.java
> +public class PositionGenerator {
> Position 클래스에서 캐시 등의 역할이 많아지면서 클래스가 무거워졌습니다. 따라서 PositionGenerator를 다시 생성하였습니다. 이 경우 PositionGenerator에서 Position을 생성하기 위해서는 Position 생성자를 최소 protected로 열어놓아야 하는데 그래도 괜찮을까요? '책임이 무거워져도 변수의 접근 제한자를 닫기 위해 하나의 클래스에서 관리하느냐'와 '제한을 일부 풀고 책임을 분리하느냐' 사이에서 고민이 되었습니다. 관련해서 언급해주시면 감사하겠습니다!

Position을 보니 분리하신것은 좋은 판단이라 생각했어요 😃 

접근 제한자는 필요에의해 지정한다고 생각해요!
최대한 닫아놓는것을 지향할 뿐, 필요하다면 적당히 열어주는것도 필요합니다~
물론 접근제한자를 닫을 수 있는 구조가 있고, 그것이 어색하지 않다면 그렇게 구현해야한다고 생각해요 😃 

+) PositionGenerator를 Position의 내부 클래스로 두는 방법도 있어요!

```java
public class Position {
    public static Position create(File file, Rank rank) {
        return PositionGenerator.generator(file, rank);
    }
}

class PositionGenerator {
   // ... 생략
}

```

2024-03-27 12:47 UTC, Gomding commented on src/main/java/domain/position/PositionGenerator.java
> +        return CACHE.getOrDefault(file, new HashMap<>()).getOrDefault(rank, new Position(file, rank));
사실 PositionGenerator는 캐시를 가지고 반환해주는 객체이고
generate 라는 행위와 많이 다르다고 생각합니다.

+) 현재는 캐시에 없다면 객체 생성하여 바로 반환해주는데요
캐시에 없었다면 캐시에 생성한 객체를 추가한 뒤 반환해주는건 어떻게 생각하시나요? 😃

2024-03-27 12:47 UTC, Gomding commented on src/main/java/domain/position/PositionGenerator.java
> +        Rank rank = RankInput.asRank(rawRank);
RankInput, FileInput는 view 객체인데 여기 도메인객체에 존재하고 있군요 🤔

2024-03-27 12:47 UTC, Gomding commented on src/main/java/domain/position/PositionGenerator.java
> +    public static Position generate(File file, Rank rank) {
위 코멘트에서 적었지만

PositionGenerator 자체도 바깥에서 몰라도 된다고 생각해요 :)
사실 바깥에서 중요한건 Position 이고 `Position이 어떻게 생성되는지(PositionGenerator)`는 몰라도 된다고 생각해요
괜한 의존만 늘어난다고 생각합니다 :)

Position 객체 생성 호출 시 PositionGenerator 에서 반환해주는 것으로 처리해봐도 좋다고 생각해요 😃 

에버는 어떻게 생각하시나요?

2024-03-27 12:47 UTC, Gomding commented on src/main/java/domain/position/Rank.java
> +    public static List<Rank> reversedValues() {
해당 메서드 테스트가 누락됐군요!

2024-03-27 12:47 UTC, Gomding commented on src/main/java/domain/position/Position.java
> +        }
Direction에게 요청해보는것은 어떠신가요? :)

```java
final Direction direction = Direction.asDirection(this, target);
if (Direction.isStraight(direction)) {
    return betweenStraightPositions(target);
}
```

2024-03-27 12:47 UTC, Gomding commented on src/main/java/domain/piece/Pawn.java
> +public class Pawn extends Piece {
Pawn에 if 분기가 너무 많다고 느껴지신다면
Pawn을 두 객체로 나눠볼 수도 있어요!

```java
public class BlackPawn extends Pawn {

}

public class WhitePawn extends Pawn {

}
```

2024-03-27 12:47 UTC, merged