[1, 2단계 - 체스] 폰드(권규택) 미션 제출합니다.
woowacourse/java-chess pull request #704
Opened 2024-03-21 08:47 UTC by tackyu

안녕하세요 알렉스! 6기 BE 폰드입니다.

이번 체스 미션에서는 많은 조건들을 처리하는데 애를 먹었습니다.
각 체스말마다 도착 위치 까지 이동할 수 있는지에 대한 조건과, 조건을 통과한다면 출발지부터 도착지까지 이동할 수 있는 거리 리스트를 반환해서
체스보드에서 방해 기물들이 있는지 검증하도록 구현하였습니다.
결국 폰이 대각선으로 이동하는 것을 막지는 못했지만, 수정하도록 하겠습니다!

감사합니다!

2024-03-22 11:58 UTC, yxxnghwan requested changes
안녕하세요 폰드! 체스 미션 리뷰하게 된 알렉스입니다!
어려운 미션이었는데 시간내에 잘 구현해주셨네요!
코멘트 남겼으니 확인 부탁드립니다!

2024-03-22 11:58 UTC, yxxnghwan commented on src/main/java/chess/domain/Command.java
> +public enum Command {
view의 명령어를 관리하는 클래스 아닐까요?
패키지 위치가 어색한 것 같아요

2024-03-22 11:58 UTC, yxxnghwan commented on src/main/java/chess/domain/Command.java
> +    END("end");
```suggestion
    MOVE("move"),
    END("end"),
    ;
```

다음에 추가될 enum을 생각해서 위처럼 쓰기도 합니다 :)

2024-03-22 11:58 UTC, yxxnghwan commented on src/main/java/chess/domain/chessBoard/ChessBoard.java
> +    }
라인이 옆으로 많이 길어지네요! 적당히 개행하면 좋을 것 같아요!

2024-03-22 11:58 UTC, yxxnghwan commented on src/main/java/chess/domain/position/Column.java
> +public class Column {
체스판의 사이즈는 고정적인데, enum으로 만들면 어떨까요? Row도 마찬가지로요!

2024-03-22 11:58 UTC, yxxnghwan commented on src/main/java/chess/domain/chessPiece/Piece.java
> +package chess.domain.chessPiece;
자바 공식 컨벤션상 패키지명은 모두 소문자로 쓰고 있어요!

2024-03-22 11:58 UTC, yxxnghwan commented on src/main/java/chess/domain/chessPiece/Knight.java
> +        return Collections.unmodifiableList(route);
route라는 변수는 사용되지 않고 그냥 바로 응답으로 나가는 것 같네요

2024-03-22 11:58 UTC, yxxnghwan commented on src/main/java/chess/domain/chessPiece/Piece.java
> +    }
부모 클래스가 자식 클래스를 알아도 괜찮을까요?

2024-03-22 11:58 UTC, yxxnghwan commented on src/test/java/chess/domain/PositionTest.java
> +    }
에러 메시지도 검증하는건 어떨까요?

2024-03-22 11:58 UTC, yxxnghwan commented on src/test/java/chess/domain/chessPiece/BishopTest.java
> +      Piece piece=new Bishop(WHITE);
```suggestion
      Piece piece = new Bishop(WHITE);
```

2024-03-22 11:58 UTC, yxxnghwan commented on src/main/java/chess/domain/chessPiece/Pawn.java
> +                || attack(source, target);
각각 확인만 하는 메소드들인데 메소드명이 마치 저 행동들을 하는 것같은 메소드명이네요!

2024-03-22 11:58 UTC, yxxnghwan commented on src/main/java/chess/domain/position/Column.java
> +        int columnDirection = direction;
필요하지 않은 지역변수인 것 같아요!

2024-03-22 11:58 UTC, yxxnghwan commented on src/main/java/chess/domain/position/Column.java
> +    }
```suggestion
    public int compare(Column column) {
        return Integer.compare(column.value, value);
    }
```

2024-03-24 04:18 UTC, tackyu commented on src/main/java/chess/domain/Command.java
> +    END("end");
감사합니다!

2024-03-24 06:14 UTC, tackyu commented on src/main/java/chess/domain/chessPiece/Pawn.java
> +                || attack(source, target);
can을 앞에 붙여서 수정하였습니다!

2024-03-24 07:38 UTC, tackyu commented on src/main/java/chess/domain/position/Column.java
> +public class Column {
row와 column을 enum으로 수정 하였습니다!
캐싱을 활용하는 방법은 비추천하시나요??

2024-03-24 07:45 UTC, tackyu commented on src/main/java/chess/domain/Command.java
> +public enum Command {
깊게 고려하지 못했습니다😅
감사합니다!

2024-03-24 08:21 UTC, tackyu commented on src/main/java/chess/domain/chessPiece/Piece.java
> +    }
부모 클래스는 자식 클래스를 알 필요가 없을 것 같은데, 그 이유가 자식 클래스에 접근하면 에러가 발생할 수 있기 때문인가요??

chessBoard에서 피스의 역할을 구분 하도록 수정 하였는데, 체스 보드의 역할로 적절한지 잘 모르겠습니다.
알렉스는 어떻게 생각하시나요?
각 체스말이 역할을 판별할 수 있어야 할 것 같은데, 그렇다면 Piece의 자식 클래스마다 체스 보드에서 쓰일 isPawn또는 isEmpty를 구현하는게 나을까요??

2024-03-25 05:49 UTC, yxxnghwan commented on src/main/java/chess/domain/chessPiece/Piece.java
> +    }
보드가 폰만 따로 구분해서 알아야할 필요가 있을까요?
힌트를 드리자면 추상화를 잘 해보면 굳이 보드가 체스를 알지 않아도 될 것 같은데..!

2024-03-25 06:06 UTC, yxxnghwan approved these changes
안녕하세요 폰드! 코멘트 잘 반영해주셨네요!
이번 단계에서는 충분한 코드인 것 같아서 이만 머지하도록 할게요!
생각해볼만한 코멘트 몇개 남겼는데, 다음 단계에서 고민해서 반영해주시면 좋을 것 같습니다!
그럼 다음단계에서 봬요~!👋

2024-03-25 06:06 UTC, yxxnghwan commented on src/main/java/chess/domain/chesspiece/Empty.java
> +public class Empty extends Piece{
```suggestion
public class Empty extends Piece {
```

2024-03-25 06:06 UTC, yxxnghwan commented on src/main/java/chess/domain/chesspiece/Pawn.java
> +    }
동작 파악이 더 수월해진 것 같네요!

2024-03-25 06:06 UTC, yxxnghwan commented on src/main/java/chess/domain/position/Row.java
> +    }
사이즈 검증인데 에러 메시지가 어색한 것 같네요!

2024-03-25 06:06 UTC, yxxnghwan commented on src/main/java/chess/domain/position/Position.java
> +    }
팀이 화이트가 아닌 케이스의 테스트도 필요할 것 같아요!

2024-03-25 06:06 UTC, yxxnghwan commented on src/main/java/chess/domain/position/Column.java
> +    }
여기도 팀이 화이트가 아닌 것에 대한 테스트가 없네요!

2024-03-25 06:06 UTC, yxxnghwan commented on src/main/java/chess/domain/position/Column.java
> +    }
추가적으로 Position, Column이 팀이나 폰을 알 필요가 있을까요?
폰에게 책임을 주는건 어떤가요?

2024-03-25 06:06 UTC, yxxnghwan commented on src/main/java/chess/domain/chessboard/ChessBoard.java
> +    }
에러나는 케이스의 테스트가 필요할 것 같네요!

2024-03-25 06:07 UTC, merged

2024-03-25 06:26 UTC, tackyu commented on src/main/java/chess/domain/chesspiece/Pawn.java
> +    }
감사합니다!

2024-03-26 10:14 UTC, tackyu commented on src/main/java/chess/domain/chessPiece/Piece.java
> +    }
폰의 getRoute를 따로 오버라이딩 해주었고, Piece에서 willAttack 메서드를 만들었습니다.
그런데, pawn 하나 때문에 해당 메서드가 DIrection을 받게 되었는데 괜찮다고 생각하시나요??

2024-03-26 14:13 UTC, tackyu commented on src/main/java/chess/domain/position/Column.java
> +    }
폰의 책임인 게 적절한 것 같습니다!