[1, 2단계 - 체스] 엘라(오숙현) 미션 제출합니다.
woowacourse/java-chess pull request #713
Opened 2024-03-21 08:52 UTC by oshyun00

2024-03-22 03:17 UTC, choijy1705 requested changes
안녕하세요 엘라!
전체적으로 아주 읽기 좋은 코드를 작성해주신것 같아요👍
질문에 대한 답변과 함께 더 읽기 좋은 코드를 위해 줄일 수 있는 부분들 리뷰 남겼습니다
동작성에 대한 리뷰는 다음 리뷰로 챙겨볼께요
확인해보시고 먼자 반영부탁드려요!

2024-03-22 03:17 UTC, choijy1705 commented on src/main/java/chess/domain/position/Positions.java
> +    }
다른 크루들도 대부분다 캐싱을 적용해주셨는데 어떤 이점이 있는지 잘모르겠습니다.
`64개 position을 순회하는 비용 + static 으로 만들어 둔 메모리 비용 < 객체 생성 비용`
일 정도인가요? 
또한 가독성 측면에서도 그렇게 좋아보이지 않은것 같아요

2024-03-22 03:17 UTC, choijy1705 commented on src/test/java/chess/domain/piece/BishopTest.java
> +        bishop = new Bishop(Color.WHITE);
질문을 잘 이해 못했어요 ㅠ
beforeEach말고 한번만 초기화 해준다는게 어떤 의미일까요??

모든 테스트는 독립적으로 동작되어야합니다! 어떤 의미인지는 정확하게 모르겠으나. 테스트가 실행될때마다 매번 초기화 해주는 방향이 적절할 것 같습니다!

2024-03-22 03:17 UTC, choijy1705 commented on src/test/java/chess/domain/piece/BishopTest.java
> +        bishop = new Bishop(Color.WHITE);
리플랙션에 대한 답변도 드릴께요!
테스트를 위해서 리플렉션을 쓰는건 대부분 적절하지 않을것 같네요!
현업에서는 getter를 쓰지 않는 경우는 없기 때문에 대부분다 getter를 사용합니다. 리플렉션을 사용하기보다는 getter를 구현하는게 저는 더 좋을것 같네요🤔

리플렉션을 어디서 사용했는지 코드에 다가 코멘트 남겨주시면 좀 더 자세히 보겠습니다!

2024-03-22 03:17 UTC, choijy1705 commented on src/main/java/chess/controller/ChessGame.java
> +public class ChessGame {
Controller라면 클래스명에 Controller라고 남겨주시는게 좋을것 같습니다!

2024-03-22 03:17 UTC, choijy1705 commented on src/main/java/chess/controller/ChessGame.java
> +        chessBoard.initialBoard();
생성자에서 초기화 시켜주면 좋을것 같네요!
그럼 굳이 메서드로 뺄 필요도 없을것 같고요

2024-03-22 03:17 UTC, choijy1705 commented on src/main/java/chess/domain/state/Progress.java
> +        if (command.equals(START_COMMAND)) {
```suggestion
        if (START_COMMAND.equals(command)) {
```
equals비교시 상수가 앞으로 오게하여 혹시 모를 NPE를 예방해주세요!

2024-03-22 03:17 UTC, choijy1705 commented on src/main/java/chess/controller/ChessGame.java
> +        return gameState;
```suggestion
        return gameState.play(command);
```

2024-03-22 03:17 UTC, choijy1705 commented on src/main/java/chess/controller/ChessGame.java
> +            chessBoardDto = chessBoard.convertToDto();
```suggestion
        if (!gameState.isEnd()) {
            ChessBoardDto chessBoardDto = chessBoard.convertToDto();
```

2024-03-22 03:17 UTC, choijy1705 commented on src/main/java/chess/domain/board/ChessBoard.java
> +    }
호출하는 곳에서 그냥 생성자를 사용하면 될 것 같네요!

2024-03-22 03:17 UTC, choijy1705 commented on src/main/java/chess/domain/piece/Piece.java
> +public interface Piece {
인터페이스 사용 좋습니다!
질문에 답변 드리자면 구현체를 상속하는 경우는 거의 없는것 같아요!
인터페이스의 경우 default 메서드도 지원하고 필요한경우 인터페이스를 상속하는 추상클래스를 만들어서 중복되는 코드를 제거하는 경우가 많은것 같습니다.

지금도 color 비교하는 로직들은 모든 곳에서 piece들에서 공통적으로 체크하는데 매번 구현이 되어있네요
추상클래스 혹은 default메서드를 사용하여 중복을 제거하면 좋을것 같아요!

2024-03-22 03:17 UTC, choijy1705 commented on src/main/java/chess/view/FileSymbol.java
> +public enum FileSymbol {
요 enum은 조금 오버엔지니어링 같네요!
a~h가 아니라면 에러를 내는것은 File 혹은 Position에서 충분히 처리할 수 있을것 같습니다!

2024-03-22 03:17 UTC, choijy1705 commented on src/main/java/chess/view/PieceSymbol.java
> +public enum PieceSymbol {
Piece모양의 정보도 Piece에서 관리하는게 어떨까 싶네요!

2024-03-22 03:17 UTC, choijy1705 commented on src/main/java/chess/domain/state/Ready.java
> +        throw new IllegalArgumentException("올바르지 않은 command입니다.");
에러를 하나로 합쳐도 무방할것 같아요!

2024-03-22 03:17 UTC, choijy1705 commented on src/main/java/chess/domain/state/End.java
> +        throw new IllegalArgumentException("올바르지 않은 command입니다.");
여기도 에러를 하나로 합쳐도 무방할것 같네요!

2024-03-22 03:17 UTC, choijy1705 commented on src/main/java/chess/domain/position/Rank.java
> +        return Arrays.stream(Rank.values()).filter(start -> start.rank == Integer.parseInt(i))
Integer.parseInt부분을 여기서 처리하면 숫자로 변경할수없는 값이 들어왔을때 의도치 않은 에러가 발생할 수 있을것 같네요
int를 파라미터로 받는다면 move에서도 비슷한 로직을 한 메서드로 처리할 수 있을것 같네요!

2024-03-23 07:19 UTC, choijy1705 approved these changes
엘라 전체적으로 너무 잘짜주셔서
오히려 제가 감탄했던것 같네요!👍
이번 단계는 여기서 머지해도 될 것 같습니다
몇가지 마이너한 개선점 리뷰 남겼으니 확인해보시고 다음단계에 반영 고려해주세요!

2024-03-23 07:19 UTC, choijy1705 commented on src/main/java/chess/domain/position/Position.java
> +    }
```suggestion
        private static final Map<String, Position> CACHE = Arrays.stream(Rank.values())
        .flatMap(rank -> Arrays.stream(File.values()).map(file -> new Position(file, rank)))
        .collect(Collectors.toMap(position -> toKey(position.file, position.rank), Function.identity()));
```
하나로 합칠 수 있을것 같아요!

2024-03-23 07:19 UTC, choijy1705 commented on src/main/java/chess/controller/ChessGameController.java
> +        GameState gameState = new Ready(chessBoard);
흐름상 playGame 메서드 안에서 생성해주는게 자연스러울것 같아요!

2024-03-23 07:19 UTC, choijy1705 commented on src/main/java/chess/domain/piece/Bishop.java
> +        int rankUnit = rankDiff / Math.abs(rankDiff);
unit을 계산하는 로직은 util클래스를 만들어서 별도로 관리되면 더 좋을것 같아요!

2024-03-23 07:19 UTC, choijy1705 commented on src/main/java/chess/domain/board/ChessBoard.java
> +        Piece sourcePiece = chessBoard.get(source);
canMove에서도 get하여 sourcePiece를 찾고 여기서도 찾고 있어요 
canMove이전에 sourcePiece, targetPiece를 먼저 찾고 시작하면 불필요한 반복 조회를 줄일 수 있을것 같네요!

2024-03-23 07:19 UTC, choijy1705 commented on src/test/java/chess/domain/board/ChessBoardTest.java
> +                .satisfies(map -> assertThat((Map<?, ?>) map).hasSize(32));
getChessBoard 메서드가 있는데 extracting을 사용하신 이유가 궁금합니다!

2024-03-23 07:19 UTC, choijy1705 commented on src/main/java/chess/domain/board/ChessBoard.java
> +        }
```suggestion
        Piece targetPiece = chessBoard.get(target);
        Color targetPieceColor = Optional.ofNullable(targetPiece)
            .map(Piece::getColor).orElse(Color.NONE);
```
할당된 변수를 변경하기보다는 생성할때 결정하도록 짜면 더 좋을것 같습니다!

2024-03-23 07:19 UTC, merged

2024-03-24 02:59 UTC, oshyun00 reviewed
피드백 반영하였습니다. 감사합니다!

2024-03-24 02:59 UTC, oshyun00 commented on src/test/java/chess/domain/board/ChessBoardTest.java
> +    }
chessBoard에서 Piece가 이동할 수 있는지 판단하는 테스트케이스에서 리플렉션을 사용하게 되었습니다. 처음 알게된 개념이라 적용하면서도 이게 맞나? 하는 의문이 들었어요. (요구사항을 최대한 지켜보기 위해 리플렉션을 적용했습니다.)
우선, 리플렉션을 사용하면 기껏 포장해두었던 객체를 다시 뜯어본다는 느낌을 강하게 받았습니다. Private으로 숨겨둔 필드를 강제로 열어서 확인하는것보다는 필요하다면 getter를 사용하는게 더 나을 것 같습니다.

2024-03-24 02:59 UTC, oshyun00 commented on src/main/java/chess/controller/ChessGame.java
> +        chessBoard.initialBoard();
생성되면 무조건 수행되는 로직이라면 생성자에서 수행하는게 실수할 우려도 없고 좋겠네요!! 수정하였습니다.

2024-03-24 02:59 UTC, oshyun00 commented on src/main/java/chess/controller/ChessGame.java
> +        return gameState;
위에서 상태를 변경해주고 있어서 변경된 상태만 리턴해주면 되는군요! 수정하였습니다.

2024-03-24 02:59 UTC, oshyun00 commented on src/main/java/chess/domain/board/ChessBoard.java
> +    }
dto 생성자 사용으로 변경했습니다!!

2024-03-24 02:59 UTC, oshyun00 commented on src/main/java/chess/domain/state/Ready.java
> +        throw new IllegalArgumentException("올바르지 않은 command입니다.");
하나로 수정하였습니다!

2024-03-24 02:59 UTC, oshyun00 commented on src/main/java/chess/domain/position/Rank.java
> +        return Arrays.stream(Rank.values()).filter(start -> start.rank == Integer.parseInt(i))
inputView에서 move 명령어의 형태를 검증하고 있어서 숫자로 변경할 수 있는 값만 컨트롤러, 도메인들로 전달된다고 생각했습니다. 한번 검증을 한 상태여도 형 변환을 할때에는 예외 검증을 해주는게 나을까요?
int를 파라미터로 받으니 move에서 int값을 rank로 변경하는 로직에도 해당 메서드를 적용할 수 있네요! 해당 방식으로 수정하였습니다.

2024-03-24 02:59 UTC, oshyun00 commented on src/main/java/chess/view/FileSymbol.java
> +public enum FileSymbol {
domain이 FileSymbol을 참조하는 형태로 되어있네요.😅 domain에서 view를 참조하는 형태는 바람직하지 않은것같습니다! symbol로직 File 클래스로 이동하였습니다.

2024-03-24 02:59 UTC, oshyun00 commented on src/main/java/chess/view/PieceSymbol.java
> +public enum PieceSymbol {
Piece에 따라 출력되는 형태(K,Q,P 등)는 view와 관련된 부분이라고 생각해서 view로 분리하게 되었습니다.
만약 piece를 출력하는 형태가 “K,Q,P”에서 “킹, 퀸, 폰”으로 바뀐다면? -> view 와 관련된 부분이니 view를 먼저 열어서 수정하려고 하지 않을까? 하는 생각에 View에 별도 enum으로 관리하게 되었습니다.
사실 체스 게임의 경우 규칙이 확실하고 변경될 가능성이 거의 없어서 출력 형태를 domain에서 같이 관리하는것도 효율적일 것 같지만, 미션을 하면서는 view와 domain을 구분해보고 싶었습니다.
혹시 이런 관점에 대해서는 어떻게 생각하시는지 영이의 의견이 궁금합니다.🥹

2024-03-24 02:59 UTC, oshyun00 commented on src/main/java/chess/domain/piece/Piece.java
> +public interface Piece {
말씀 감사합니다!! 이번 경우는 color 비교를 위해서는 필드가 필요해서 추상 클래스로 변경해서 적용하였습니다.

2024-03-24 02:59 UTC, oshyun00 commented on src/test/java/chess/domain/piece/BishopTest.java
> +        bishop = new Bishop(Color.WHITE);
제가 설명이 조금 부족했던것같습니다🥲 
이번에 테스트 코드를 작성하면서 페어가 아래와 같이 공통으로 사용되는 필드는 테스트 클래스 제일 상단에서 한번만 초기화 하면 되지 않을까 하는 의견을 얘기했었습니다.
현재 구현한 방식으로는 테스트가 수행되면서 각 Piece의 상태가 변경될 일이 없어 테스트 케이스간에 영향을 주지 않지만, 저는 혹시 모를 상황에 대비해 각 케이스별로 초기화를 해주는것이 낫다고 생각했습니다.
```@BeforeEach```를 사용하면 테스트 케이스마다 객체가 생성된다는점은 있지만 테스트는 매번 초기화가 보장되어있어야한다고 생각했어요. 그래서 아래 방식 대신 ```@BeforeEach```로 매번 초기화 하도록 구현하였는데요, 말씀해주신 ```테스트가 실행될때마다 매번 초기화 해주는 방향이 적절할 것 같습니다!```와 동일한 내용인것같아요!

```java
class BishopTest {
    Bishop bishop = new Bishop(Color.WHITE);
    Position source = Position.of(File.C, Rank.ONE);

    @DisplayName("비숍은 대각선으로 움직일 수 있다.")
    @Test
    void canMove() {
        // given
        Position target = Position.of(File.E, Rank.THREE);
        Color color = Color.NONE;

        // when
        boolean canMove = bishop.canMove(source, target, color);

        //then
        assertThat(canMove).isTrue();
    }
    ...
}

```

2024-03-24 02:59 UTC, oshyun00 commented on src/test/java/chess/domain/piece/BishopTest.java
> +        bishop = new Bishop(Color.WHITE);
리플렉션에 대한 부분은 코드에 코멘트 남겨두었습니다.

2024-03-24 02:59 UTC, oshyun00 commented on src/main/java/chess/domain/position/Positions.java
> +    }
처음 캐싱을 도입했던 이유는 크게 두가지였습니다.

1. Position의 종류가 고유한 64개로 제한되어있다.
2. 이동시마다 어떤 Position으로 이동했는지 리턴해주어야해서 재사용이 많다. 출력할때도 각 Position을 확인하므로 Position의 호출이 잦다.

체스 게임이 진행되면 동일한 위치에 대한 Position 인스턴스가 여러개 생성될 수도 있습니다. 그래서 매번 메모리 할당을 하는것보다 캐싱해놓고 사용하는것이 나을거라고 생각했습니다. 

말씀해주신 내용을 보고 생각해보니 막상 게임이 진행되면 64개의 모든 Position이 다 사용되지 않을수도 있고, List를 순회하는 비용도  낭비라는 생각이 들었어요. 그래서 캐시를 사용하지 않는 방식을 적용시켜보기도 했습니다.

그런데 작성하다보니 동일한 Position의 사용이 굉장히 많다고 느껴졌어요.  “이렇게 재사용이 많다면 사실상 동일한 값을 가진 객체를 매번 새로 생성하기보다 캐싱을 하고, 대신 Map<key, Position> 형태로 적용하면 적절한 위치를 검색하는데 비용이 줄어들지 않을까?” 하는 생각이 들었습니다. 그래서 캐싱 방식을 Map형태로 수정했습니다. 

대신 캐시를 Positions 클래스로 분리하는것이 아니라, Position 클래스에 static 필드로 갖고 정적 팩터리 메서드를 통해 Position을 찾아오도록 했습니다. Positions.of() 보다 Position.of() 가 문맥상 더 맞다고 생각했어요. 
이렇게 코드를 수정해보면서 추가 궁금증이 생겼습니다.

“캐싱을 64개를 미리 다 해놓는것이 아니라 캐시에 저장되어있지 않으면 새로운 Position을 생성하고, 캐시에 있으면 그 값을 가져와서 사용하면 어떨까?” -> 이 경우 사용되지 않은 Position은 캐시에 저장되지 않으니 메모리 낭비를 줄일 수 있지 않을까 하는 생각이 들었습니다. 아래 코드와 같은 형태가 될것같습니다.

```java
private static Position of(File file, Rank rank) {
    String key = toKey(file, rank);
    if (CACHE.containsKey(key)) {
        return CACHE.get(key);
    }
    Position position = new Position(file, rank);
    CACHE.put(key, position);
    return position;
}
```

생각해보다보니 내용이 조금 길어졌네요😅 혹시 영이는 제가 생각했던 캐시 적용 이유와 적용 방식(① 캐시 형태로 Map 적용, ② CACHE에 해당되는 값이 있으면 해당값 리턴하고 없으면 새로 생성)에 대해 어떻게 생각하시는지 궁금합니다!!

2024-03-24 02:59 UTC, oshyun00 commented on src/main/java/chess/domain/board/ChessBoard.java
> +        Piece sourcePiece = chessBoard.get(source);
canMove() 호출 이전에 get 할 수 있도록 수정하였습니다!

2024-03-24 02:59 UTC, oshyun00 commented on src/test/java/chess/domain/board/ChessBoardTest.java
> +                .satisfies(map -> assertThat((Map<?, ?>) map).hasSize(32));
처음에는 getter를 최대한 쓰지 않기 위해 extracting을 적용했었습니다. 그런데 DTO를 생성하면서 getter가 추가되었습니다. 해당 부분 getter 적용하는것으로 수정하였습니다!

2024-03-24 02:59 UTC, oshyun00 commented on src/main/java/chess/domain/board/ChessBoard.java
> +        }
Optional을 사용해서 한번에 처리할수도 있네요! 반영하였습니다. 감사합니다.

2024-03-25 14:24 UTC, choijy1705 commented on src/main/java/chess/domain/position/Positions.java
> +    }
1. List 보다는 Map이 성능적으로 훨씬 의미가 있다고 봅니다. 다만 캐싱이라는 것이 정말 필요한지는 의문입니다. 캐싱의 목적이 서로 다른 레이어의 접근은 시간이 많이 소모되기 때문에 가까운 레이어에 캐싱을 하여 시간을 단축하는 거라고 생각하는데요! 객체를 생성하는 비용이 캐싱을 해서 메모리를 소모하고 있을만큼의 가치가 있는지는 의문입니다😭 코드의 복잡성만 증가시키는게 아닐까 라는 생각입니다.
2. cache에 해당값이 없다면 당연히 새로 생성하는게 맞을것 같네요!

2024-03-25 14:26 UTC, choijy1705 commented on src/main/java/chess/view/PieceSymbol.java
> +public enum PieceSymbol {
이 부분은 취향 차이일것 같네요
저라면 코드의 가독성을 위해서 Piece가 name을 가지도록 처리할 것 같네요!