[1, 2단계 - 체스] 프람(김민종) 미션 제출합니다.
woowacourse/java-chess pull request #720
Opened 2024-03-21 08:56 UTC by koust6u

안녕하세요! 썬 체스 과제를 통해 찾아뵙게 된 프람입니다 .😊

이번 미션를 진행하면서 빠듯한 일정 때문에 못하게 모든 요구사항을 충족하지 못했어요.😭

부족한 부분은 따로 README파일에 정리를 두었습니다. 피드백 주신 후에 바로 해당 부분도 같이 리팩토링하도록 하겠습니다 ㅠㅠ.

잘 부탁드립니다!!

2024-03-23 05:23 UTC, syoun602 requested changes
안녕하세요 프람~ 리뷰어 썬입니다 ☀️
체스 미션이 쉽지 않았을텐데 고생 많으셨습니다!
우선 동작이 제대로 되고 있지 않는 것 같은데, 먼저 요구사항을 모두 충족하는 코드를 만들어보아요~

2024-03-23 05:23 UTC, syoun602 commented on src/main/java/controller/ChessController.java
> +    public void start() {
우선 동작이 제대로 되지 않아서 세세히 볼 수가 없네요 😢
동작이 되도록 구현해봅시다~

2024-03-23 05:23 UTC, syoun602 commented on src/main/java/domain/ChessBoard.java
> +        return piece.orElseThrow(() -> new IllegalArgumentException("해당 포인트에는 기물이 없습니다"));
var을 쓸때와 안쓸때의 차이가 있나요? 하나로 통일하는게 좋아보입니다~
```suggestion
        return pieces.findPieceWithPoint(point)
            .orElseThrow(() -> new IllegalArgumentException("해당 포인트에는 기물이 없습니다"));
```

2024-03-23 05:23 UTC, syoun602 commented on src/main/java/domain/ChessBoard.java
> +        if (pieces.check(piece, endPoint)) {
어떤걸 check하는건가요~?

2024-03-23 05:23 UTC, syoun602 commented on src/main/java/domain/piece/Pieces.java
> +    public Map<Point, Piece> toMap() {
애초부터 맵으로 가지고 있는건 어떤가요??

2024-03-23 05:23 UTC, syoun602 commented on src/main/java/domain/piece/Pieces.java
> +        return switch (piece.getStatus()) {
`else 예약어를 쓰지 않는다.
else 예약어를 쓰지 말라고 하니 switch/case로 구현하는 경우가 있는데 switch/case도 허용하지 않는다.`

2024-03-23 05:23 UTC, syoun602 commented on src/main/java/domain/piece/attribute/point/Direction.java
> +    // TODO : PAWN 에서 사용하기 위함 + 함수명이 Straight 일시 왼쪽 오른쪽 선도 생각 가능
주석은 제거해주세요~

2024-03-23 05:23 UTC, syoun602 commented on src/main/java/domain/piece/attribute/point/File.java
> +    public static File from(final char value) {
간단한 stream으로 변경해봅시다

2024-03-23 05:23 UTC, syoun602 commented on src/main/java/domain/piece/kind/Knight.java
> +    private static final List<List<Direction>> directionList = List.of(List.of(UP, UP_RIGHT),
나이트의 방향을 추가하면 List<List<>>가 필요없겠네요 👀

2024-03-23 05:23 UTC, syoun602 commented on src/main/java/domain/piece/kind/Pawn.java
> +    private boolean flag = false;
변수가 유의미하게 사용되고 있지 않는 것 같아요

2024-03-23 05:23 UTC, syoun602 commented on src/main/java/domain/piece/kind/Pawn.java
> +    private static List<Direction> whiteList = List.of(UP, UP_LEFT, UP_RIGHT);
```suggestion
    private static final List<Direction> blackList = List.of(DOWN, DOWN_LEFT, DOWN_RIGHT);
    private static final List<Direction> whiteList = List.of(UP, UP_LEFT, UP_RIGHT);
```
final이 누락되었어요~ 또한 제가 남긴 코멘트들은 프로젝트 전체적으로 훑어봐주세요😊

2024-03-23 05:23 UTC, syoun602 commented on src/main/java/domain/piece/kind/Queen.java
> +    public boolean canMove(final Point point) {
다음 리뷰까지는 todo는 제거하거나 모두 적용해주세요~

2024-03-23 05:23 UTC, syoun602 commented on src/main/java/util/BoardMapper.java
> +public class BoardMapper {
사실 dto나 mapper를 만드는건 상관이 없다고 생각되지만, 모든 동작이 제대로 안되는 상황에서 이런 클래스들을 만드는게 의미가 있는지는 잘 모르겠습니다 😢 의존성을 분리하는 것보다는 구현이 먼저 되어야 하지 않을까요?

2024-03-23 05:23 UTC, syoun602 commented on src/main/java/util/DirectionUtil.java
> +    public static Direction determineDirection(final Point standard, final Point comparison) {
`함수(또는 메서드)의 길이가 10라인을 넘어가지 않도록 구현한다`

2024-03-24 05:23 UTC, koust6u commented on src/main/java/domain/ChessBoard.java
> +        return piece.orElseThrow(() -> new IllegalArgumentException("해당 포인트에는 기물이 없습니다"));
var를 쓸때와 안쓸때의 차이는 없습니다. 시간이 타이트하고 페어 프로그램을 진행하다 보니 각자 스타일대로 혼용하여 사용한 곳 많은 것 같습니다.  수정하겠습니다 😊

2024-03-24 05:31 UTC, koust6u commented on src/main/java/controller/ChessController.java
> +    public void start() {
앗.. 죄송합니다. PR전 최종 확인을 했어야했는데 꼼꼼하게 확인 못했습니다! 코드가 돌아가도록 수정하겠습니다.

2024-03-26 14:34 UTC, koust6u commented on src/main/java/domain/ChessBoard.java
> +        if (pieces.check(piece, endPoint)) {
chek라는 것은 이동 첫 번째 파라미터인 pIece가 두번째 파라미터인 point로 이동이 가능한지 확인하는 기능이었습니다.

해당 기능을하는 Pieces의 check 메서드는canReplace로 이름을 변경해주어 해당 기물이 해당 위치로 대체 될 수 있는지 더 직관적인 이름으로 변경하였습니다.

2024-03-27 06:56 UTC, koust6u commented on src/main/java/domain/piece/Pieces.java
> +    public Map<Point, Piece> toMap() {
애초에 맵을 가지고 있었다면 불필요한 코드로 보입니다. 

피드백 후 제출한 코드에는 Map의 형태가 아닌 PieceDto를 리스트 형태로 가지고있도록 dto의 구조를 수정해주었습니다 😊

2024-03-27 07:00 UTC, koust6u commented on src/main/java/domain/piece/Pieces.java
> +        return switch (piece.getStatus()) {
네 최초 리뷰요청에서 시간이 많이 부족하여 요구사항보다 일단은 돌아가게 만들자 생각하여 요구사항을 어기는 코드가 상당히 많았습니다. 이번 요청에서는 하나씩 모두 수정하였습니다!

2024-03-27 07:02 UTC, koust6u commented on src/main/java/domain/piece/kind/Knight.java
> +    private static final List<List<Direction>> directionList = List.of(List.of(UP, UP_RIGHT),
네 좋은 아이디어 감사합니다😊  Direction(Movement로 이름 변경됨)에 나이트의 이동 방향을 추가하여 해당 List<List<>>를 대체해주었습니다

2024-03-27 07:03 UTC, koust6u commented on src/main/java/domain/piece/kind/Pawn.java
> +    private boolean flag = false;
네 사용되지 않고 있거나 무의미한 상수 역시 코드 전반적으로 모두 삭제해주었습니다!

2024-03-27 07:04 UTC, koust6u commented on src/main/java/util/BoardMapper.java
> +public class BoardMapper {
네 썬의 의견에 전적으로 동의합니다. 일단 돌아가는 코드를 완성하고 점진적으로 리팩토링을 하도록 하겠습니다.!!!

2024-03-27 07:29 UTC, koust6u commented
안녕하세요 썬! 

최초 리뷰요청이 이후 버그 수정뿐만 아니라  미션 요구사항(EX, 인덴트 뎁스제한 , 세로줄 제한) 을 코드의 구조를 전반적으로 바꾸느라 재리뷰요청이 조금 늦어졌습니다.   😭

---
코드 구조 변경 사항

1. Mapper를 통해 dto넘겨주는 로직 삭제후 도메인에서 dto 생성해서 넘겨주도록 바꿨습니다.
> 하지만 이러한 변경은 뷰에서 사용되는 dto를 도메인에서 생성한다는 것이 올바른 접근인지 의문이 듭니다.

2024-03-27 13:09 UTC, syoun602 approved these changes
안녕하세요 프람~

체스 게임 잘 구현해주셨네요~ 전부 동작하는 것 확인했습니다 👍 
코멘트를 통해 점진적으로 살펴보려 했는데, 리뷰 반영과 별개로 스스로 리팩토링을 진행하시느라 시간이 꽤 걸렸군요..! 많은 변경이 생겨 1,2단계에서 조금 더 얘기해보고 싶은 부분들이 있는데, 지금 변경 요청을 드리면 3,4단계에 대한 부담이 생길 것 같아서 다음 단계에서 더 얘기나눠보도록 하겠습니다 🥲 

남긴 코멘트는 다음 단계에서 반영해주세요! 그럼 다음 단계도 화이팅입나다 ~ 💪

2024-03-27 13:09 UTC, syoun602 commented on src/main/java/chessgame/controller/ChessController.java
> +public class ChessController {
컨트롤러보다 더 좋은 네이밍은 없을까요?
일반적으로 컨트롤러가 게임 진행과 출력 순서까지 모두 알고 있지 않을 것 같아서요!

2024-03-27 13:09 UTC, syoun602 commented on src/main/java/chessgame/controller/ChessController.java
> +    private final Map<ChessCommand, Consumer<ChessBoard>> commandPerformances
커맨드에 대한 함수를 커맨드 내부에 들고 있는 것은 어떨까요?

2024-03-27 13:09 UTC, syoun602 commented on src/main/java/chessgame/controller/ChessController.java
> +        var chessBoard = new ChessBoard();
요기는 final이 필요없네요~

2024-03-27 13:09 UTC, syoun602 commented on src/main/java/chessgame/controller/ChessController.java
> +    public void start() {
start+move로 게임을 진행하다가 다시 start가 입력되면 새로 시작되는데 의도된 사항일까요?

2024-03-27 13:09 UTC, syoun602 commented on src/main/java/chessgame/domain/ChessBoard.java
> +        this.pieces = new Pieces(Set.of());
```
public Pieces() {
    this(Collections.emptySet());
}
```
이런 부생성자를 만들어볼 수 있을 것 같아요

2024-03-27 13:09 UTC, syoun602 commented on src/main/java/chessgame/controller/ChessController.java
> +        if (chessCommand == END) {
```suggestion
        if (chessCommand.isEnd()) {
```
와 같이 객체에게 물어봅시다

2024-03-27 13:09 UTC, syoun602 commented on src/main/java/chessgame/domain/ChessBoard.java
> +    }
도메인 내부에서 dto 변환 로직이 있는 것은 좋은 방법 같지는 않습니다.
자동차 경주에서의 요구사항을 다시 살펴볼까요?
`MVC 패턴 기반으로 리팩터링해 view 패키지의 객체가 domain 패키지 객체에 의존할 수 있지만, domain 패키지의 객체는 view 패키지 객체에 의존하지 않도록 구현한다`
근데 현재 체스보드의 import를 살펴보면 다음과 같네요.
```
import chessgame.dto.ChessBoardDto;
import chessgame.dto.RouteDto;
```
위와 같은 요구사항이 있는 이유는 간단해요.
도메인이 자주 변화하는 view로부터 분리되어 잘 변화하지 않는 비즈니스 규칙을 지키기 위해서입니다.
대부분의 변경은 view의 영역이고 따라서 dto만 수정하면 되는데, 현재 방식에서는 도메인까지 침범해야 합니다.
dto에서 도메인을 의존하는 방향으로 변경하는게 좋아보이네요 😁

2024-03-27 13:09 UTC, syoun602 commented on src/main/java/chessgame/domain/ChessBoard.java
> +    public void move(final RouteDto dto) {
dto는 말 그대로 data transfer object로써 뷰 <-> 컨트롤러 <-> 도메인 사이 사이에서 의존성을 끊기 위해 사용해야하는데, 현재는 도메인끼리도 dto로 소통하고 있네요. 차라리 dto를 전부 제거하고 도메인만 사용하는 것은 어떨까요? 
dto와 관련된 내용은 레벨 2에서 심층적으로 다루게될텐데, 레벨1의 핵심은 도메인과 객체지향에 대한 지식과 경험을 쌓는거라고 생각해서요 🙂

2024-03-27 13:09 UTC, syoun602 commented on src/main/java/chessgame/domain/piece/Piece.java
> +        return this.color == Color.WHITE;
이런 부분들도 메시지를 보내볼 수 있겠네요
```suggestion
        return color.isWhite();
```

2024-03-27 13:09 UTC, syoun602 commented on src/main/java/chessgame/domain/piece/Pieces.java
> +import java.util.*;
wildcard import 단점에 대해 한번 알아봅시다~

2024-03-27 13:09 UTC, syoun602 commented on src/main/java/chessgame/domain/piece/kind/pawn/BlackPawn.java
> +    }
whitePawn과 정확히 일치하는 메서드네요. 중복을 제거해볼까요?

2024-03-27 13:09 UTC, syoun602 commented on src/main/java/chessgame/domain/piece/Pieces.java
> +        values.remove(piece);
HashSet은 내부적으로 무엇을 들고 있을까요? 
remove 메서드도 한번 살펴봅시다~ ifPresent가 꼭 필요하지 않을 것 같아서요

2024-03-27 13:09 UTC, syoun602 commented on src/main/java/chessgame/domain/piece/Pieces.java
> +    public boolean isFriend(final Piece piece, final Point point) {
friend보다 더 좋은 단어를 고민해보아요.
ally, team, color 는 어떤가요?

2024-03-27 13:09 UTC, syoun602 commented on src/main/java/chessgame/domain/piece/Pieces.java
> +public class Pieces {
대체로 필터를 통해서 찾고 ifPresent와 같은 메서드를 사용하고 있는데, position, piece를 map으로 들고 있었다면 좀 더 구현이 한눈에 들어오지 않을까? 라는 의문이 있습니다 🤔

2024-03-27 13:09 UTC, syoun602 commented on src/main/java/chessgame/domain/piece/attribute/point/File.java
> +    }
이펙티브 자바에 `아이템 35 : ordinal 메서드 대신 인스턴스 필드를 사용하라` 라는 내용이 있습니다~!
[해당 글](https://kukim.tistory.com/69)을 한번 살펴볼까요?

2024-03-27 13:09 UTC, syoun602 commented on src/main/java/chessgame/domain/piece/attribute/point/Movement.java
> +    RIGHT_RIGHT_DOWN(RIGHT.x * 2, DOWN.y);
모두 숫자로 통일하는 것은 어떤가요? (1, 1) (1, 2) (-1, 0) 등
현재 방식이 가독성이 좋은지 한번 의심해볼 필요가 있는 것 같아요

2024-03-27 13:09 UTC, syoun602 commented on src/main/java/chessgame/domain/piece/attribute/point/Movement.java
> +    }
Lombok 어노테이션을 쓰든, IDE에서 getter를 자동생성하든 get을 항상 붙여주기 때문에
저는 개인적으로 자바 언어를 사용할때는 단순 값 반환시 get을 붙이는 편입니다.

2024-03-27 13:09 UTC, syoun602 commented on src/main/java/chessgame/domain/piece/kind/jumping/King.java
> +    }
List로도 충분해보이는데 Set을 사용하신 이유가 있을까요?

2024-03-27 13:10 UTC, merged

2024-03-29 05:29 UTC, koust6u commented on src/main/java/chessgame/controller/ChessController.java
> +public class ChessController {
썬 의견에 동의합니다! 의식적으로 생각을 하지 않다보니 단지 View와 Domain을 연결시켜주어 controller로 명명했었습니다. 다른 이름으로 수정하겠습니다👍

2024-03-29 05:34 UTC, koust6u commented on src/main/java/chessgame/controller/ChessController.java
> +    private final Map<ChessCommand, Consumer<ChessBoard>> commandPerformances
사실 저도 커멘드에 가지고 있는것이 논리적을 올바른거라고 생각을 했었습니다.

다만 커멘드는 view에서 입력받아 생성되기 때문에 view의 일부라 생각했습니다. 

그런데 커멘드에서 해당 맵을 가지고 있으면 결과적으로 view가 도메인(chessBoard)에 의존적이지 않을까? 라는 생각이었습니다. 

썬의 의견은 어떤가요?

2024-03-29 05:36 UTC, koust6u commented on src/main/java/chessgame/controller/ChessController.java
> +    public void start() {
예 맞습니다. 사실 end라는 명령어는 게임 자체를 종료한다고 가정을 했고 start는 말 그대로 게임을 시작한다는 방향으로 접근하여 게임 진행중 start를 입력 받으면 게임을 재시작한다고 가정을 했습니다.

2024-03-29 05:47 UTC, koust6u commented on src/main/java/chessgame/controller/ChessController.java
> +        if (chessCommand == END) {
좋은 코멘트 감사합니다 ☺️

2024-03-29 06:11 UTC, koust6u commented on src/main/java/chessgame/domain/ChessBoard.java
> +    }
썬의 친철한 답변 정말 감사합니다. 들었던 의문에 대해서 명쾌한 이해가 되었습니다. 
3,4 단계에서는 해주신 답변을 토대로 view와 domain을 분리해보겠습니다. 
해보면서 또 어려운점이 있다면 해당 pr에서 자세하게 질문해보겠습니다 !!

2024-03-29 06:22 UTC, koust6u commented on src/main/java/chessgame/domain/piece/attribute/point/Movement.java
> +    RIGHT_RIGHT_DOWN(RIGHT.x * 2, DOWN.y);
좋은 의견 감사합니다. 말씀 주신거처럼 숫자로 직접 넣어주는 것이 훨씬 가독성 측면에서 좋다 생각이 됩니다!

2024-03-29 06:27 UTC, koust6u commented on src/main/java/chessgame/domain/piece/attribute/point/Movement.java
> +    }
네 말씀 주신 코멘트를 보고 찾아보니 자바 빈즈 규약 중`클래스의 속성들은 get, set 혹은 표준 명명법을 따르는 메서드들을 사용해 접근할 수 있어야 한다.` 있다는 것을 찾을 수 있었습니다. 

규약에 따라 관련 메소드에 일관적으로 get를 붙여주는 것이 좀 더 바람직하다고 느꼈습니다. 
감사합니다😊

2024-03-29 06:40 UTC, koust6u commented on src/main/java/chessgame/domain/piece/Pieces.java
> +import java.util.*;
[와일드 카드의 문제점에 대해 알아보았습니다.](https://jiga.dev/avoiding-wildcard-imports-in-java-kotlin-with-intellij/)

사실 구글 자바 스타일 가이드 컨벤션에서 와일드카드를 사용하지 말라는 내용을 인지는 하고 있었는데 급하게 코드를 작성하다보니 의도치 않게 와일드 카드 임포트가 발생했던 것 같습니다. 
이번 리뷰어님의 코멘트 덕분에 왜 컨벤션에서 사용을 지양하는지 알 수 있었습니다. 감사합니다!

2024-03-29 06:53 UTC, koust6u commented on src/main/java/chessgame/domain/piece/Pieces.java
> +    public boolean isFriend(final Piece piece, final Point point) {
맞습니다. 이번 미션을 하면서 네이밍에 신경을 많이 못썼습니다. 좋은 의견감사합니다

2024-03-29 07:21 UTC, koust6u commented on src/main/java/chessgame/domain/piece/Pieces.java
> +public class Pieces {
예 저도 같은 생각입니다! buttom up 방식으로 작은 단위부터 개발 진행하다. 논리적으로 페어와 '기물이 위치를 가지고 있는게 자연스럽지 않을까?'라는 생각에서 코드를 map없이 진행하게 되었습니다. ㅜㅜ 꽤 많이 진행하고 나서 썬이 말씀하신 것과 같은 문제점을 찾게 되었습니다. 이미 구조를 수정하기 너무 늦어 그대로 코드를 완성하고 제출하게되었습니다. 3,4 단계에서 여유가 남는다면 해당 구조로 변경해보도록 하겠습니다!

2024-03-29 07:39 UTC, koust6u commented on src/main/java/chessgame/domain/piece/Pieces.java
> +        values.remove(piece);
HashSet은 HashMap을 맴버로 가지고 있었습니다. 그런데 질문 주신 의도가 무엇인지 잘 가늠이 가지않습니다. 혹시 더 구체적으로 설명부탁드려도 괜찮을까요??

2024-03-29 07:40 UTC, koust6u commented on src/main/java/chessgame/domain/piece/attribute/point/File.java
> +    }
이렇게 세세하게 쪽집게식으로 짚어주셔서 정말로 감사드립니다. 바로 반영토록하겠습니다.!!!

2024-03-29 08:02 UTC, koust6u commented on src/main/java/chessgame/domain/piece/attribute/point/File.java
> +    }
생각하지도 못했던 내용이었습니다. 좋은 의견 감사합니다!!

2024-03-29 08:04 UTC, koust6u commented
전반적으로 3,4단계 구현 시간이 빠듯할거 같아 말씀 주신 코멘트들을 적용해보았습니다. 3.4단계를 진행하면서 적용못한 코멘트들과 코멘트들에 대한 저의 의견을 첨언하여 pr하도록하겠습니다. 꼼꼼한 코드 리뷰 정말 감사합니다!!!

2024-03-29 08:07 UTC, koust6u commented on src/main/java/chessgame/domain/piece/kind/jumping/King.java
> +    }
제가 알기로는 set list의 차이는 
Set은 중복을 허용하지 않고 List는 중복을 허용하지만 순서를 보장한다는 특징이 있는 것으로 압니다. 

굳이 순서에 대해 보장해줄 필요가 없고 중복 역시 필요가 없다는 것을 자료형을 통해 묵시적으로 표현하고 싶어 사용하였습니다.

혹시 위와 같이 굳이 어떤 자료구조를 사용하더라도 상관이 없을 경우 Set보다 List가 권장되는 이유가 있을까요?? 
썬의 의견이 궁금합니다!!