[3, 4단계 - 체스] 우주(김성현) 미션 제출합니다.
woowacourse/java-chess pull request #733
Opened 2024-03-27 06:56 UTC by tsulocalize

안녕하세요, 미르! 
3,4단계 미션 진행하며 궁금한 점을 정리해봤습니다.

1. DB 연결을 통해 체스판 상태를 저장하고 다시 불러오는 기능을 만들었는데요.
getter 없이 체스 상태를 저장할 수 없어 getter를 만들어 줬고, setter도 없어 객체로 변환하는 과정이 복잡해졌습니다.
혹시 이 문제에 대해 명쾌한 해답이 있을까요?

2. 도메인 변경을 최소화하라는 규칙을 잘 지키지 못한 것 같습니다.
잘 설계했으면 도메인에 큰 변화 없이 DB 기능을 만들 수 있었을까요? 아니면 처음부터 DB 연결을 가정하고 설계하지 않았기 때문에 불가피한 변경인 걸까요?

사실 완벽한 상태는 아니라고 생각하지만 더 많이 의견을 나누고 싶어 빨리 제출하게 됐습니다!

2024-03-28 03:50 UTC, ddu0422 commented on src/main/java/chess/domain/chessBoard/ChessBoard.java
> +                .filter(space -> space.hasColor(color))
과정을 줄여보는건 어떨까요?

2024-03-28 03:50 UTC, ddu0422 commented on src/main/java/chess/machine/Status.java
> +    private static class Result {
inner class를 사용한 이유는 무엇인가요?

2024-03-28 03:50 UTC, ddu0422 commented on src/main/java/chess/Application.java
> +                new ChessBoardService(new ChessBoardRepositoryImpl()));
👍🏻 👍🏻

2024-03-28 03:50 UTC, ddu0422 commented on src/main/java/chess/repository/ChessBoardRepositoryImpl.java
> +    private static final String PASSWORD = "root"; // MySQL 서버 비밀번호
상수로 의미를 적절히 표현하고 있지 않을까요?

2024-03-28 03:50 UTC, ddu0422 commented on src/main/java/chess/repository/ChessBoardRepositoryImpl.java
> +            return null;
null을 반환하게 되면, 어떤 문제가 발생할까요?

2024-03-28 03:50 UTC, ddu0422 commented on src/main/java/chess/repository/ChessBoardRepositoryImpl.java
> +        return result;
빈 값을 반환하면 어떤 의미가 있을까요?

2024-03-28 03:50 UTC, ddu0422 commented on src/main/java/chess/repository/TurnConverter.java
> +public class TurnConverter {
TurnConverter는 `String <-> Turn`을 변경해주고 있는 역할만 해야하지 않을까요?
`startGame(), oppositeTurn()` 등은 어떨 때 필요한걸까요?

2024-03-28 03:50 UTC, ddu0422 commented on src/main/java/chess/repository/exchanger/TurnConverter.java
> +public class TurnConverter implements ObjectConverter<Turn, String> {
TurnConverter는 `Turn <-> String` 변경 역할만 해야하지 않을까요?
```java
Turn turn = whiteTurn();
turn.oppositeTurn();
```

와 같은 코드를 개선해볼 수 있지 않을까요?

2024-03-28 03:59 UTC, ddu0422 requested changes
안녕하세요 우주! 미르입니다 :)
3, 4 단계 미션 잘 구현해주셨네요!
몇 가지 코멘트 남겼으니 확인 부탁드립니다~

추가로 Schema를 알 수 있을까요?
Schema를 알 수 없어 Application 진행하기 어렵네요 😢 

## 답변

> DB 연결을 통해 체스판 상태를 저장하고 다시 불러오는 기능을 만들었는데요.
getter 없이 체스 상태를 저장할 수 없어 getter를 만들어 줬고, setter도 없어 객체로 변환하는 과정이 복잡해졌습니다.
혹시 이 문제에 대해 명쾌한 해답이 있을까요?

저는 이미 충분히 잘해주셨다고 생각해요~
- getter로 데이터를 반환
- setter대신 Mapping 클래스로 변경

> 도메인 변경을 최소화하라는 규칙을 잘 지키지 못한 것 같습니다.
잘 설계했으면 도메인에 큰 변화 없이 DB 기능을 만들 수 있었을까요? 아니면 처음부터 DB 연결을 가정하고 설계하지 않았기 때문에 불가피한 변경인 걸까요?

현재는 불가피한 변경이 일어날 수 밖에 없다고 생각해요.

`도메인 변경을 최소화`규칙 때문에 불가피하게 변경하지 말아야 할 이유가 있을까요?
그렇다면 `도메인 변경을 최소화` 규칙은 어떤 의미에서 생겨난 규칙일까요?

2024-03-28 04:17 UTC, tsulocalize commented on src/main/java/chess/machine/Status.java
> +    private static class Result {
Result가 Status 외 클래스에서 사용될 일이 없다고 판단해서 inner class로 두게 되었습니다.
재사용성을 생각해 외부에 두는 게 좋았을까요?

2024-03-28 04:18 UTC, tsulocalize commented on src/main/java/chess/repository/ChessBoardRepositoryImpl.java
> +    private static final String PASSWORD = "root"; // MySQL 서버 비밀번호
실습 코드를 가져와 쓰다보니 이렇게 됐네요;;; 수정했습니다!

2024-03-28 04:29 UTC, tsulocalize commented on src/main/java/chess/repository/ChessBoardRepositoryImpl.java
> +            return null;
connection을 사용하는 곳에서 NPE가 발생하겠네요...!
unchecked exception을 보내도록 바꿨습니다!

2024-03-28 07:25 UTC, tsulocalize commented on src/main/java/chess/repository/ChessBoardRepositoryImpl.java
> +        return result;
빈 값을 반환하면 데이터를 가져왔다고 착각할 가능성이 있을 것 같습니다!
Exception을 던지도록 수정했습니다

2024-03-28 07:25 UTC, tsulocalize commented on src/main/java/chess/domain/chessBoard/ChessBoard.java
> +                .filter(space -> space.hasColor(color))
해당 코드를 한 줄로 바꿔주었습니다!

2024-03-28 07:47 UTC, tsulocalize commented on src/main/java/chess/repository/TurnConverter.java
> +public class TurnConverter {
domain 변경 없이 Turn을 만들어주려다보니, 이리저리 몸을 비틀어(?) 만들어 진 코드인 것 같습니다.
Turn 생성자를 public으로 변경해 객체 변환이 용이하도록 수정했습니다!

2024-03-28 07:48 UTC, tsulocalize commented on src/main/java/chess/repository/exchanger/TurnConverter.java
> +public class TurnConverter implements ObjectConverter<Turn, String> {
위 코멘트 답변대로 변경해봤습니다!

2024-03-28 13:17 UTC, ddu0422 commented on src/main/java/chess/repository/exchanger/TurnConverter.java
> +public class TurnConverter implements ObjectConverter<Turn, String> {
깃허브 버그로 인해 중간에 리뷰가 없어졌었는데 2개가 생겼네요. 😭

2024-03-28 14:39 UTC, ddu0422 commented on src/main/java/chess/machine/Status.java
> +    private static class Result {
effective java inner class를 검색항 장단점을 확인해보면 어떨까요?

2024-03-28 14:47 UTC, ddu0422 requested changes
안녕하세요 우주! 미르입니다 :D
미션 구현 잘 해주셨네요!
몇 가지 간단한 코멘트 남겼으니 확인해주시면 감사하겠습니다~ 🙏🏻

2024-03-28 14:47 UTC, ddu0422 commented on src/main/java/chess/domain/chessGame/TurnState.java
> +                .orElseThrow(() -> new IllegalArgumentException("잘못된 상태입니다"));
에러 메시지가 비슷하네요.
에러 메시지를 작성하는 목적이 무엇일까요? 에러 메시지가 비슷하면 어떤 문제가 발생할까요?

2024-03-28 14:47 UTC, ddu0422 commented on src/main/java/chess/machine/ChessMachine.java
> +    private ChessGame findOrCreateGame() {
최초 실행 시 에러 로그가 기록되어야할까요? 🤔

2024-03-28 14:47 UTC, ddu0422 commented on src/main/java/chess/repository/ChessBoardRepositoryImpl.java
> +public class ChessBoardRepositoryImpl implements ChessBoardRepository {
현재는 `JDBC 연결 + 쿼리 요청`이네요.  ChessBoardRepository는 어떤 역할을 해야할까요?

2024-03-28 14:47 UTC, ddu0422 commented on src/main/java/chess/repository/ChessBoardRepositoryImpl.java
> +        final var query = "SELECT * FROM board WHERE board_id = 1";
board가 늘어나면 어떻게 될까요?

2024-03-29 05:16 UTC, tsulocalize commented on src/main/java/chess/machine/Status.java
> +    private static class Result {
effective java에서도, 인터넷에서도 하나의 클래스와 소통하는 package-private 클래스를 내부 클래스로 정의하라 되어 있어, 미르의 의도가 잘 와닫지 않는 것 같습니다...

2024-03-29 05:23 UTC, tsulocalize commented on src/main/java/chess/domain/chessGame/TurnState.java
> +                .orElseThrow(() -> new IllegalArgumentException("잘못된 상태입니다"));
에러가 발생했을 때, 어디가 원인인지 알기 힘들어지겠죠.
에러 해결을 위한 적절한 정보를 담고 있지 않게 되어 있는 것 같기도 하네요.
수정했습니다!

2024-03-29 06:00 UTC, tsulocalize commented on src/main/java/chess/machine/ChessMachine.java
> +    private ChessGame findOrCreateGame() {
최초 실행 시 데이터가 없는 상황은 에러가 아니고, 로그가 있더라도 사용자에게 출력되지 않아야 할 것 같습니다.

2024-03-29 06:39 UTC, tsulocalize commented on src/main/java/chess/repository/ChessBoardRepositoryImpl.java
> +public class ChessBoardRepositoryImpl implements ChessBoardRepository {
Repository는 객체를 저장하고 검색하거나 불러오는 작업을 하는 개념이라고 알고 있습니다.
혹시 지금 코드가 위 기능을 제대로 수행하지 못하고 있을까요?

2024-03-29 06:44 UTC, tsulocalize commented on src/main/java/chess/repository/ChessBoardRepositoryImpl.java
> +        final var query = "SELECT * FROM board WHERE board_id = 1";
말씀하신 board가 늘어난다는 뜻이 8*8 사이즈가 아닌, 저장되는 board 수 맞을까요?
그렇다면 board_id를 인수에 추가로 받게 바꿀 수 있을 것 같습니다.
또한, 저장 시에 DB row 수를 통해 생성한 new_id로 값을 저장할 수 있을 것 같네요.

2024-03-29 11:04 UTC, ddu0422 commented on src/main/java/chess/machine/Status.java
> +    private static class Result {
`사용하지 않으면 어떨까요?`의 의도가 아닌 장단점을 생각하여 inner class를 작성하면 어떨까해서 남겨드린 내용입니다.
하나의 클래스와 소통하니 내부 클래스로 정의하는 방법은 괜찮다고 생각합니다.

inner class를 사용하는 방법은 non-static / static 방법이 있습니다.
둘의 차이도 알고 적절한 방법에서 사용하였는지 고민해보면 어떨까합니다.

> 재사용성을 생각해 외부에 두는 게 좋았을까요?

위 부분의 고려사항이라고 생각합니다 :D

2024-03-29 11:07 UTC, ddu0422 commented on src/main/java/chess/repository/ChessBoardRepositoryImpl.java
> +public class ChessBoardRepositoryImpl implements ChessBoardRepository {
아니요 2가지의 기능을 하고 있지 않느냐는 의미입니다.
만약 다른 Repository가 늘어나면 동일한 JDBC 연결이 필요하지 않을까요?

2024-03-29 11:16 UTC, ddu0422 requested changes
안녕하세요 우주! 미르입니다 😄 
체스 미션 잘 구현해주셨네요!
몇 가지 의논하고 싶어 RC 요청드립니다 :D

2024-03-30 11:00 UTC, tsulocalize commented on src/main/java/chess/repository/ChessBoardRepositoryImpl.java
> +public class ChessBoardRepositoryImpl implements ChessBoardRepository {
그렇긴 하네요.
별도 connection class를 만들어두었습니다!

여담) 확장성을 어디까지 고려하면 좋을지 결정하는 게 쉽지 않네요.
이전에 SpaceGenerator interface의 경우에는 `확장성이 필요할 때 추가하라`고 하셨고,
이번 JDBC 연결은 `Repository가 늘어날 경우를 고려해라`라고 하셨죠.

저도 은총알이 없다는 건 알고 있지만, 그럼에도 개발자 사이에서 어느정도 동의하는 부분이 있지 않을까 싶어서요.

2024-03-30 11:15 UTC, tsulocalize commented on src/main/java/chess/machine/Status.java
> +    private static class Result {
non-static inner class는 바깥 class에 대해 참조를 갖게되어 메모리 누수가 발생할 수 있기 때문에, 바깥 class에 접근할 일이 없다면 static으로 선언하는 것이 좋습니다. IDE에서도 이를 경고해주고 있네요.

Result 클래스를 필요 시 별도 클래스로 분리하는 것이 어렵지 않을 것 같다는 생각이 들어,
저는 이대로 두도록 하겠습니다!

2024-03-30 13:22 UTC, ddu0422 commented on src/main/java/chess/machine/Status.java
> +    private static class Result {
좋습니다~!

2024-03-30 13:26 UTC, ddu0422 commented on src/main/java/chess/repository/ChessBoardRepositoryImpl.java
> +public class ChessBoardRepositoryImpl implements ChessBoardRepository {
두 가지 이야기를 하고 싶었습니다.

1. 책임
2. 확장성

## 책임
현재 Repository는 `저장하고 검색하거나 불러오는 작업을 하는 개념`라고 이야기 해주셨어요.
하지만 현재는 `DB 연결 + 저장 및 검색`을 진행하고 있습니다.

즉, DB 연결이 변경될 때 Repository가 변경되어야하고 저장 및 검색이 변경될 때도 Repository가 변경되어야합니다.
그렇다면 SOLID 원칙 중 SRP 위반이 아닐까요?

## 확장성
> 확장성을 어디까지 고려하면 좋을지 결정하는 게 쉽지 않네요.

2024-03-30 13:38 UTC, ddu0422 approved these changes
안녕하세요 우주! 미르입니다 :)
체스 미션 잘 구현해주셨어요!
이만 머지해도 괜찮을 것 같습니다 :D
미션 하시느라 고생 많으셨습니다~~

고민되는 부분이 있으시면 언제든지 DM 주셔도 괜찮습니다 😄 
추가 미션도 진행해보시면 많은 도움이 될 거예요!

2024-03-30 13:38 UTC, merged