[3, 4 단계 - 체스] 감자(김주하) 미션 제출합니다.
woowacourse/java-chess pull request #737
Opened 2024-03-28 07:28 UTC by khabh

안녕하세요 범블비, 감자입니다 :)
3, 4단계 리뷰도 잘 부탁드립니다. 🙇‍♀️🙇‍♀️

#### [1, 2 단계 변경 사항]
Board에 getRank 메서드를 추가해서 기존에 있던 RankDTO를 조금 수정했습니다.

#### [3, 4 단계 기능 구현]
**점수 계산**
Score enum에 각 기물 타입별 점수를 저장하고, ScoreGenerator에서 점수 계산 로직을 수행하도록 코드를 작성했습니다.

**데이터베이스 테이블**
데이터베이스 연결을 위해 다음과 같은 pieces, turns 테이블을 생성해서 보드의 진행 상황을 저장했습니다.
![image](https://github.com/woowacourse/java-chess/assets/84626225/a7206eb3-1474-4989-913c-8811c8744b35)

**DAO와 도메인 데이터 변환**
데이터베이스 저장을 위해 다음과 같이 PieceDTO와 TurnDTO를 추가로 정의했고, BoardService에 데이터 변환 로직을 작성했습니다.
```java
// PieceDTO.java
public record PieceDTO(int file, int rank, String type) {
}

// TurnDTO.java
public record TurnDTO(String currentColor) {
}
```

**체스 보드 초기화**
데이터베이스에 체스판이 존재하면 기존 체스판을 불러오고, 아니면 새로운 체스판을 생성하도록 구현했습니다.
```java
    // ChessGameController.java
    private Board getOrCreateBoard() {
        if (boardService.isBoardExist()) {
            return boardService.getBoard();
        }
        return new InitialBoardGenerator().create();
    }
```

**데이터베이스 테스트**
테스트와 프로덕션 데이터를 분리하기 위해 서로 다른 스키마를 사용하도록 ConnectionManager를 정의했습니다.
```java
private static final ConnectionManager PRODUCTION_MANAGER = new ConnectionManager("chess");
private static final ConnectionManager TEST_MANAGER = new ConnectionManager("chess_test");
```

2024-03-29 02:58 UTC, ddaaac requested changes
안녕하세요 감자 👋 

3,4단계 구현 잘 해주셨네요.

몇 가지 코멘트 남겼으니 확인해주세요.

2024-03-29 02:58 UTC, ddaaac commented on src/main/java/chess/model/score/ScoreGenerator.java
> +                .map(file -> board.countPieceOfFile(pawn, file))
ScoreGenerator가 Board와 협력해서 점수를 구하도록 굉장히 잘 구현해주셨네요. 각 객체에 알맞은 책임이 지워진 것 같습니다 👍 

조금 고민해볼만한 지점은 board.countPieceOfFile(pawn, file)입니다. 여러 Piece에 대하여 범용적으로 사용할 수 있게 구현해주신 것 아닐까 싶어요. 아마도 Board의 책임을 고려한 설계인 것 같네요.
하지만 같은 세로열에 있는 Pawn의 갯수에 대한 요구사항만 있으니, 좀 더 디테일한 메서드를 만들 수 있지 않을까요? 그 편이 도메인 요구사항이 더 잘 드러나는 것 같기도 하구요.

2024-03-29 02:58 UTC, ddaaac commented on src/main/java/chess/model/score/Score.java
> +    KING(0.0, Type.WHITE_KING, Type.BLACK_KING);
각 Piece의 구현체가 점수를 갖는 것과 Score enum을 따로 만드는 건 어떤 차이가 있을까요?

2024-03-29 02:58 UTC, ddaaac commented on src/main/java/chess/model/board/Board.java
> +    public Board(Map<Position, Piece> squares, Color currentColor) {
DB 로직을 넣으면서 변경된 생성자이군요.
생성자가 열려있는 것이 어떤 유연함을 가져오는지 느끼셨으면 좋을 것 같습니다.

2024-03-29 02:58 UTC, ddaaac commented on docker/docker-compose.yml
> +version: "3.9"
https://github.com/woowacourse/java-chess/pull/729#discussion_r1540401597

2024-03-29 02:58 UTC, ddaaac commented on src/main/java/chess/db/ConnectionManager.java
> +    }
https://github.com/woowacourse/java-chess/pull/729#discussion_r1540421280

2024-03-29 02:58 UTC, ddaaac commented on src/main/java/chess/dao/TurnDAO.java
> +        try (Connection connection = getConnection()) {
https://github.com/woowacourse/java-chess/pull/729#discussion_r1540418138

여기서는 매 요청마다 새로운 커넥션이 생기겠네요.

2024-03-29 02:58 UTC, ddaaac commented on src/main/java/chess/db/ConnectionManager.java
> +    private static final ConnectionManager TEST_MANAGER = new ConnectionManager("chess_test");
프로덕션 코드에 Test 관련 코드가 들어간 것 같네요.
이 매니저는 테스트 패키지에서 만드는 건 어떨까요?

2024-03-29 02:58 UTC, ddaaac commented on src/main/java/chess/dao/TurnDAO.java
> +            return convertToTurn(selectedTurn);
Optional을 반환해주세요.

2024-03-29 02:58 UTC, ddaaac commented on src/main/java/chess/service/BoardService.java
> +        return convertToBoard(turnDTO, pieceDTOs);
BoardService에서 Dao 에서 떙겨온 데이터들로 Board 객체를 잘 조립해주고 있네요.

2024-03-29 05:31 UTC, khabh commented on src/main/java/chess/model/board/Board.java
> +    public Board(Map<Position, Piece> squares, Color currentColor) {
이전 코드에서는 DB에 저장된 상태를 불러오기도 어렵고, 승패 판정 로직이 currentColor에 의존적이라 테스트하기 힘들었습니다. 버릇처럼 필드를 클래스 내부에서 초기화해버렸는데, 생성자를 통한 주입이 가져오는 이점을 확실히 느끼게 되었습니다!

2024-03-29 05:53 UTC, khabh commented on src/main/java/chess/model/score/ScoreGenerator.java
> +                .map(file -> board.countPieceOfFile(pawn, file))
일단은 요구사항에 맞는 디테일한 메서드를 정의하고, 확장이 필요한 시점이 왔을 때 범용적으로 사용할 수 있도록 수정하는 것이 더 명확해 보이네요 😊
Pawn에 대해서만 해당 로직을 수행하도록 수정했습니다

2024-03-29 06:13 UTC, khabh commented on docker/docker-compose.yml
> +version: "3.9"
리드미에 도커 실행 관련 내용 추가했습니다 :)

2024-03-29 08:24 UTC, khabh commented on src/main/java/chess/db/ConnectionManager.java
> +    private static final ConnectionManager TEST_MANAGER = new ConnectionManager("chess_test");
알려주셔서 감사합니다 🙇‍♀️
테스트에 필요한 Connector를 테스트 패키지로 분리했습니다!

2024-03-29 08:29 UTC, khabh commented on src/main/java/chess/db/ConnectionManager.java
> +    }
현재는 테스트와 프로덕션에서 스키마를 제외한 다른 옵션들이 모두 동일해서, 해당 매개변수만 public 생성자로 입력받도록 코드를 수정했습니다!

2024-03-30 05:22 UTC, khabh commented on src/main/java/chess/dao/TurnDAO.java
> +        try (Connection connection = getConnection()) {
반영할 필요 없다고 하셨는데, 커넥션 풀이라는 개념이 생소해서 한 번 시도해 봤습니다.

```java
    private final DataSource dataSource;

    public ConnectionManager(String database) {
        this.dataSource = dataSource(database);
    }

    private DataSource dataSource(String database) {
        HikariConfig config = new HikariConfig();
        config.setJdbcUrl("jdbc:mysql://" + SERVER + "/" + database + OPTION);
        config.setUsername(USERNAME);
        config.setPassword(PASSWORD);
        config.setMaximumPoolSize(5);

        return new HikariDataSource(config);
    }
```

로깅 메시지가 많이 떠서 커밋은 하지 않았습니다 😅 좋은 정보 알려 주셔서 감사합니다!

2024-03-30 06:38 UTC, khabh commented on src/main/java/chess/model/score/Score.java
> +    KING(0.0, Type.WHITE_KING, Type.BLACK_KING);
점수 계산 기능을 구현하면서 두 방식 사이에서 고민을 많이 했습니다.

**Piece의 구현체가 점수를 가지는 경우**
- 기물의 속성을 직접적으로 표현함으로써 캡슐화를 강화합니다.
- 새로운 기물이 추가될 때마다 해당 기물의 구현체에 점수를 명시함으로써, 점수 누락의 가능성을 최소화합니다.

**Score enum을 따로 만드는 경우**
- 모든 기물의 점수를 한 곳에서 관리함으로써 유지보수가 용이해집니다.
- Piece에서 점수에 대한 역할을 완전히 분리하여 Piece는 행마법에, ScoreGenerator와 Score는 점수 계산에 집중할 수 있습니다.

Piece의 구현체가 점수를 가진다면, 점수를 반환하는 getter 그 이상의 역할을 수행하게 해야 한다는 부담을 느꼈습니다. 그러나 Pawn만 점수 계산 방식이 달라서 적절한 설계 방법이 떠오르지 않았습니다. 그리고 체스 게임의 특성상 기물 유형이 추가될 일이 없기 때문에 구현체가 점수를 가지는 경우의 장점이 크지 않다고 생각했습니다.

결국 Pawn의 특별한 점수 규칙으로 인해 Score enum을 사용하는 것이 더 적절하다고 판단했습니다. 이 방식은 중앙 집중화된 점수 관리를 통해, 예외적인 규칙을 보다 쉽게 구현하고 관리할 수 있게 해줍니다.

한편으로는 Score가 필드로 가지는 Type이 Color 정보를 같이 담고 있는 탓에 블랙과 화이트 두 개의 Type을 저장해야 하는 것이 단점이라고 느껴지기도 했습니다. Piece가 그저 getter의 역할을 수행하게 되더라도, Score enum을 두는 것보다 구현체가 점수를 갖는 것이 더 자연스러운 것일까요? 🤔 범블비는 이에 대해 어떤 의견인지 궁금합니다!

2024-03-31 06:02 UTC, ddaaac requested changes
안녕하세요 감자 👋 

리뷰 반영 잘 해주셨습니다.

몇 가지 코멘트 남겼으니 확인해주세요.

2024-03-31 06:02 UTC, ddaaac commented on src/main/java/chess/dao/DatabaseException.java
> +public class DatabaseException extends IllegalStateException {
일반적인 표준 예외를 상속하는 경우는 드문 것 같네요.
커스텀 예외를 적용할거라면 RuntimeException 정도를 상속하면 좋을 것 같아요.

2024-03-31 06:02 UTC, ddaaac commented on src/main/java/chess/dao/TurnDAO.java
> +        try (Connection connection = getConnection()) {
좋은 시도네요 👍 

[로그 레벨](https://stackoverflow.com/a/60778768)도 수정이 가능합니다. 패키지가 정확히 같진 않을 수 있지만 여튼 import 경로를 따라가서 해당 로그 레벨을 조절하면 원하는 레벨의 로그만 볼 수 있습니다.

2024-03-31 06:02 UTC, ddaaac commented on src/test/java/chess/dao/PieceDAOTest.java
> +    private static final ConnectionManager CONNECTION_MANAGER = new ConnectionManager("chess_test");
테스트 여러 군데서 사용되고 있는데 테스트 전체에 하나의 인스턴스만 갖게 할 수 있을 것 같네요.

2024-03-31 06:02 UTC, ddaaac commented on src/test/java/chess/dao/PieceDAOTest.java
> +            PreparedStatement truncateStatement = connection.prepareStatement("TRUNCATE TABLE pieces");
지금은 크게 상관없지만 테스트 DB 전체를 날리는 쿼리는 위험할 수 있습니다.
개발용 테스트, QA 등등 테스트용 데이터가 중요한 경우가 있습니다. 이 때 이런 테스트 코드가 해당 테스트 환경에서 돌아가면 필요한 데이터들이 날라갈 수 있거든요.
항상 이번 테스트에 사용한 데이터들만 날리는 습관을 들이면 좋을 것 같네요.

2024-03-31 06:02 UTC, ddaaac commented on src/main/java/chess/model/score/Score.java
> +    KING(0.0, Type.WHITE_KING, Type.BLACK_KING);
> 모든 기물의 점수를 한 곳에서 관리함으로써 유지보수가 용이해집니다.

어떤 유지보수가 용이해질까요? 점수를 한 눈에 볼 수 있어서 얻은 이점을 조금 더 설명해주시면 좋을 것 같아요.
객체지향은 객체끼리 질문을 통한 협력이라고 표현할 수 있습니다. 어떤 객체가 점수가 궁금하다고 하면, 그 객체는 누구한테 질문을 해야할까요? Piece에게 "너 몇 점이야?"가 먼저 떠오를지, 아니면 Score라는 enum이 따로 존재하는 것을 알고 Score에 질문을 할까요?

> Pawn만 점수 계산 방식이 달라서 적절한 설계 방법이 떠오르지 않았습니다. 

지금 Score enum에도 폰의 특수한 점수 계산 로직이 들어가 있지는 않은 것 같아요.

2024-03-31 06:02 UTC, ddaaac commented on src/test/java/chess/service/BoardServiceTest.java
> +    private static final ConnectionManager CONNECTION_MANAGER = new ConnectionManager("chess_test");
https://github.com/woowacourse/java-chess/pull/729#discussion_r1544005842

이 부분 반영은 감자가 선택해주세요.

2024-03-31 06:37 UTC, khabh commented on src/main/java/chess/dao/TurnDAO.java
> +        try (Connection connection = getConnection()) {
로그 레벨이라는 개념이 있었군요!
불필요한 메시지가 너무 많이 떠서 놀랐는데, 다음에 필요한 상황이 오면 적용해 보도록 하겠습니다. 감사합니다 🙇

2024-03-31 07:04 UTC, khabh commented on src/main/java/chess/model/score/Score.java
> +    KING(0.0, Type.WHITE_KING, Type.BLACK_KING);
예를 들어 모든 기물의 점수를 2점씩 추가해야 되는 상황이 온다면, 점수에 대한 정보가 각 구현체에 정의되어 있는 경우보다 Score enum이 있는 경우가 더 수정이 쉽기에 유지보수가 용이하다고 표현했습니다.

처음 질문을 받고 몇몇 크루들과 두 방식에 대한 이야기를 나눴지만 확실하게 어느 쪽이 좋다는 결론을 내리기가 어려웠습니다. 범블비가 객체끼리의 질문을 통한 협력을 말씀하시니까 Piece의 구현체들이 점수를 가지는 방식이 훨씬 객체지향적 설계에 부합한다는 것을 깨달았습니다. Piece가 오로지 getter의 역할만 할 것이라면, 점수를 Piece에게 주는 것은 불필요하게 책임을 늘리는 것이라고 생각했는데, 오히려 과도한 분리가 된 것 같네요. 범블비의 생각을 공유해 주셔서 감사합니다!

2024-03-31 08:11 UTC, khabh commented on src/test/java/chess/dao/PieceDAOTest.java
> +            PreparedStatement truncateStatement = connection.prepareStatement("TRUNCATE TABLE pieces");
찾아보니 Connection의 autoCommit을 false로 설정하고, 테스트 후에 rollback을 호출하는 방법이 있네요! 현재 제 코드에서는 DAO가 Connection이 아닌 ConnectionManager를 받아오고 있어서 아쉽게도 적용하지 못했습니다.

PieceDAO에서는 테스트에서 추가되는 모든 데이터들을 @AfterEach에서 삭제해 주도록 수정했습니다. 추가적으로 TurnDAO에서는 여러 데이터를 다루지 않고, 더미 데이터도 추가하고 있지 않아서 기존 코드를 유지했습니다 :)

테스트용 데이터의 중요성에 대해서는 한 번도 고민하지 않았는데, 편리성을 위해서 모든 데이터를 한번에 삭제하면 다른 테스트들이 아예 안 돌아가는 상황이 올 수도 있겠네요 😓 알려주셔서 감사합니다 😊

2024-03-31 09:27 UTC, khabh commented on src/test/java/chess/service/BoardServiceTest.java
> +    private static final ConnectionManager CONNECTION_MANAGER = new ConnectionManager("chess_test");
테스트 더블을 적용하려고 하니 또 BoardService의 생성자에서 직접적으로 TurnDAO와 PieceDAO를 받지 않고 있던 것이 문제가 되었습니다. 생성자 주입이 프로그래밍 시에 얼마나 큰 장점을 가져다 주는지 다시 깨닫게 되었네요.

DB 없이 BoardService를 테스트하니 확실히 테스트 실행 시간도 많이 줄어들고, 데이터베이스 설정에 의존하지 않는 환경에서 코드를 테스트 해 볼 수 있다는 점이 좋았습니다. 통합 테스트가 DAO의 작동까지 확인해 주어서 더 넓은 범위의 테스트가 가능하지만, 독립적으로 Service에 대한 테스트만 수행하고 싶을 때는 테스트 더블이 더 높은 자유도를 보장합니다.

두 경우를 직접 코드로 구현해 보니 테스트 더블과 통합 테스트의 장단점을 느낄 수 있어서 유익했던 것 같습니다😊

2024-03-31 10:52 UTC, ddaaac approved these changes
안녕하세요 감자 👋 

어려운 미션 너무 잘 구현해주셨습니다.

고생 정말 많으셨고 방학 즐겁게 보내세요!

2024-03-31 10:52 UTC, merged