[체스 - 3단계] 레모네(이지현) 미션 제출합니다.
woowacourse/java-chess pull request #741
Opened 2024-03-29 05:20 UTC by JiHyeonL

안녕하세요, 스티치! 레모네입니다 🎉

DB 사용에 익숙하지 않아서 4단계가 오래 걸릴 것 같아 3단계를 먼저 요청드리게 되었습니다.

## 추가된 것
status 명령어를 처리하기 위해 GameStatus에 status 상수를 추가해 주었습니다.

또한 king이 잡힌다면 더이상 move가 불가능하기 때문에 king이 죽었는지, 살아있는지에 따라 입력을 받는 메서드를 다르게 적용해 주었습니다.

점수 계산은 board에서 해 주었습니다. 같은 세로줄에 같은 색의 폰이 있을 경우 0.5점을 부여하는 조건 때문에 Square가 필요했습니다. 그래서 Square에 위치한 Piece를 알 수 있는 board 안에서 점수 계산을 해 주었는데, board의 역할이 너무 많아진 것이 아닐지 고민입니다.

감사합니다!

2024-03-30 14:39 UTC, lxxjn0 requested changes
레모네, 미션 구현하시느라 수고 많으셨습니다.

3단계는 실제 코드 구조에는 큰 변화를 주진 않아서 크게 피드백을 드릴만한 부분은 보이지 않네요. 코드 적인 부분에 대해서 간단하게 피드백 남겨봤는데 한번 확인 부탁드릴게요 :)

2024-03-30 14:39 UTC, lxxjn0 commented on src/main/java/chess/ChessGame.java
> +        Board board = new Board(new BoardFactory().create());
BoardFactory에서 Board 객체를 생성해주는 것은 어떨까요? 이름에 맞는 책임을 가지게 하는 것이 좋을 것 같습니다.

2024-03-30 14:39 UTC, lxxjn0 commented on src/main/java/chess/ChessGame.java
>      }
메서드를 적절한 크기로 분리해보면 어떨까요?

2024-03-30 14:39 UTC, lxxjn0 commented on src/main/java/chess/view/GameStatus.java
> +    }
해당 메서드가 잘 이해가 되지 않습니다. 어떤 의미로 지은 이름일까요?

2024-03-30 14:39 UTC, lxxjn0 commented on src/main/java/chess/domain/score/Score.java
> +    }
NPE가 발생할 수도 있는 로직으로 보이는데 안전하게 대응해보면 어떨까요?

2024-03-30 14:39 UTC, lxxjn0 commented on src/main/java/chess/domain/board/Board.java
> +    }
해당 메서드들이 로직이 거의 유사한 것으로 보여집니다. 적절한 수정을 통해서 코드의 중복을 해결해보는 것은 어떨까요? 추가로 행위를 하는 메서드의 이름은 동사형을 사용해주세요.

2024-03-30 14:39 UTC, lxxjn0 commented on src/main/java/chess/domain/board/Board.java
> +    private double scoreByFile(Predicate<Piece> isMyColor, File file, int pawnCount, double totalScore) {
pawnCount가 항상 0으로 보입니다. 그렇다면 해당 메서드 내에서 로컬 변수로 생성해서 사용할 수 있지 않을까요?

2024-03-30 14:39 UTC, lxxjn0 commented on src/main/java/chess/domain/board/Board.java
> +        }
이렇게 하면 동일한 연산을 두번 반복하게 될 것 같습니다. 메서드를 한 번만 호출할 수 있도록 수정하면 좋을 것 같습니다.

2024-04-01 06:00 UTC, JiHyeonL commented on src/main/java/chess/ChessGame.java
> +        Board board = new Board(new BoardFactory().create());
Board 객체를 반환하도록 수정해 주었습니다! 
Map이 아닌 Board를 반환하게 되면서 Map이 제대로 생성되었는지 확인하는 테스트가 불가능해졌는데, 이런 경우 기존 테스트를 삭제해도 괜찮을까요?

2024-04-01 07:09 UTC, JiHyeonL commented on src/main/java/chess/view/GameStatus.java
> +    }
왕이 죽은 뒤 가능한 명령어가 end와 status라 생각해서 만들어 준 메서드입니다.
그러나 왕이 죽으면 바로 종료하라는 요구사항 때문에 현재 삭제한 메서드입니다!

2024-04-01 08:49 UTC, JiHyeonL commented
안녕하세요, 스티치! 레모네입니다.🫨

3단계 피드백을 반영하였고, 4단계 구현을 완료하였습니다. 
현재 필수 요구사항인 `애플리케이션을 재시작하더라도 이전에 하던 체스 게임을 다시 시작할 수 있어야 한다.` 만 완성한 상태입니다.

## 게임 결과 update 
처음에는 체스 말을 `move` 할 때마다 DB에 있는 source와 destination 위치에 있는 `piece`를 바꿔 주었습니다. 
그러나 필요한 것은 `종료 전 게임 결과`이고, 그렇다면  `end 명령어`가 들어왔을 때 `현재 게임 결과를 한번에 update` 하면 되지 않을까? 라고 생각했습니다.

이 방법이 효율적이라 생각했으나 다시 생각해보니 `강제 종료`(명령어 end가 아닌 어플리케이션 중지)할 경우 게임 결과를 모두 잃어버리는 단점이 있었습니다.
그래서 이 부분은 `move 할 때마다 update` 하는 방식으로 수정할 계획입니다.

## 프로젝트 구조
기능 완성을 목표로 구현하다 보니 효율적인 설계를 고려하지 못했습니다. 
repository, service 또한 어떻게 활용해야 할지 감이 잡히지 않아 controller에서 BoardDao를 사용하고 있습니다.
DB를 사용한 스프링 프로젝트 경험이 없어서 그런지 제 설계와 접근 방식이 올바른지 판단하기가 어려웠습니다. 

---
리팩토링을 진행하면서 선택 요구사항을 추가로 구현해 볼 계획입니다.
편하게 피드백 주시면 감사드리겠습니다!

2024-04-02 07:30 UTC, lxxjn0 requested changes
레모네, 미션 진행하시느라 수고 많으셨습니다.

먼저 기보를 저장하는 방식으로 변경하면서 Dao나 DB 커넥션 분리 등을 한번 적용해보면 좋을 것 같습니다. 그리고 repository나 service에 대해서 말씀하셨는데 이 두 레이어가 꼭 있어야하는 것은 아니라는 걸 알아주셨으면 합니다. 이미 레모네가 구현한 코드에서는 ChessGame이 서비스 레이어의 역할을 담당하고 있는 것 같습니다. 그래서 지금의 구조 그대로 개발을 이어나가셔도 충분할 것 같아요 :)
추가로 불필요한 파일들이 깃으로 관리되고 있는 것 같습니다. 해당 파일들도 제거 부탁드릴게요 👍🏼

2024-04-02 07:30 UTC, lxxjn0 commented on src/main/java/chess/ChessGame.java
> +        Board board = new Board(new BoardFactory().create());
넵넵!! 사용하지 않거나 필요없는 테스트는 과감하게 삭제하셔도 됩니다. 만약 나중에 필요하다고 하더라고 커밋을 통해 파악이 가능하니깐요 :)

2024-04-02 07:30 UTC, lxxjn0 commented on .DS_Store
불필요한 파일들이 커밋에 많이 남아있는 것 같습니다. 체크 부탁드릴게요!

2024-04-02 07:30 UTC, lxxjn0 commented on src/main/java/chess/ChessGame.java
> +        return command.gameStatus().equals(GameStatus.END);
메시지를 보내서 물어보는 것이 어떨까요?

2024-04-02 07:30 UTC, lxxjn0 commented on src/main/java/chess/domain/dao/BoardDao.java
> +    public Connection getConnection() {
데이터베이스를 연결하는 부분을 따로 클래스로 관리해보는 것은 어떨까요? DAO에서는 쿼리의 실행과 관련된 부분을 책임지도록 만드는 것이 좋을 것 같습니다 :)

2024-04-02 07:30 UTC, lxxjn0 commented on src/main/java/chess/domain/dao/BoardDao.java
> +                Piece piece = board.findPieceBySquare(Square.of(file, rank));
보드가 이미 Map으로 관리하고 있는 데이터를 가져오는 것으로 보여지네요. 그럼 관리하는 값을 그대로 가져와서 저장하면 되지 않을까요?

2024-04-02 07:30 UTC, lxxjn0 commented on src/main/java/chess/domain/score/Score.java
> +                .findFirst();
메서드 내부에서 사용된다면 Optional을 사용할 필요가 없을 것 같습니다. Optional에 대해 한번 학습해보시고 어떠한 장단점을 가지는지, 어떤 상황에서 사용하는 것이 적절할 지 한번 고민해보시면 좋을 것 같습니다!

2024-04-03 02:18 UTC, JiHyeonL commented on src/main/java/chess/domain/dao/BoardDao.java
> +                Piece piece = board.findPieceBySquare(Square.of(file, rank));
관리하는 값을 그대로 가져오기 위해서는 getter를 추가해 주어야 했기 때문에 기존의 findPieceBySquare 메서드를 활용하는 방식을 사용했습니다.
스티치는 이 경우 getter 메서드를 추가하는 것을 선호하시는지 궁금합니다!

2024-04-03 04:23 UTC, JiHyeonL commented on src/main/java/chess/domain/score/Score.java
> +                .findFirst();
optional 대신 findAny에 orElseThrow()를 사용하여 값이 존재하지 않으면 예외를 throw 하도록 수정하였습니다!

2024-04-04 07:55 UTC, lxxjn0 commented on src/main/java/chess/domain/dao/BoardDao.java
> +                Piece piece = board.findPieceBySquare(Square.of(file, rank));
비즈니스 로직을 전개하기 위함이 아닌 데이터 저장 또는 뷰 노출 등의 부분에서는 결국 데이터를 읽어야 하므로 getter의 사용은 어느정도 가능해야 한다고 생각합니다. 위 로직도 사실 비즈니스 로직의 접근을 제한하기 위해서 getter를 안쓴것이 아니고 getter를 안쓰려고 하다보니 생긴 코드라는 생각입니다. getter를 올바르게 사용하는 것이 중요하지 최대한 사용하지 말아야 할 필요는 없다고 생각합니다.

2024-04-04 07:59 UTC, lxxjn0 approved these changes
레모네, 미션 진행하시느라 수고 많으셨습니다. 추가적으로 수정할 만한 내용은 크게 없어서 미션은 여기서 마무리하면 될 것 같아요! 아주 간단한 코멘트 하나만 남겨놨으니 한번 읽어만주세요 :) 수고하셨습니다.

2024-04-04 07:59 UTC, lxxjn0 commented on src/main/java/chess/view/GameStatus.java
> +    }
이 부분은 UserCommand가 GameStatus를 가지고 있으니 UserCommand에 질의하는 코드가 있는 것이 더 낫지 않을까 싶습니다. 결국 여기서 getter를 사용하는 것은 마찬가지로 보여서요.

그럼 아마 `commmand.isEndStatus()`로 사용되지 않았을까 싶습니다.

2024-04-04 07:59 UTC, merged