Step2
woowacourse/java-chess pull request #745
Opened 2024-03-29 07:29 UTC by nayonsoso

스티치 안녕하세요, 산초입니다!
DM으로 여쭤본 내용에 대해 편의를 봐주신 것에 다시 한 번 감사드리며,. 🥹
구현한 내용을 정리해보겠습니다.

<br>

### 📌 바뀐 구조에 대한 설명
---

이전에는 각각의 기물이 '이동할 수 있는 방향'만을 알고 있었습니다. 그래서 해당 기물이 정말로 위치까지 움직일 수 있는지를 검증하기 위해 chessBoard 에서 상세히 검사를 해줘야 했습니다.

변경된 구조에서는 각 기물이 MoveStreategy를 사용합니다. `MoveStreategy` 인터페이스를 구현하는 클래스는 `OneStepMoveStreategy`, `MultiStepMoveStreategy`, `PawnMoveStreategy`입니다.

```java
public interface MoveStrategy {

    boolean canMove(final Set<Direction> movementDirections,
                    final Position sourcePosition,
                    final Position targetPosition);

    boolean canAttack(final Set<Direction> attackDirections,
                      final Position sourcePosition,
                      final Position targetPosition);
}
```

그리고 코멘트에서 말씀하신대로, Pawn을 제외한 기물들은 이동 가능한 위치와 공격 가능한 위치가 같다는 점을 적용했습니다. 따라서 `OneStepMoveStreategy`와 `MultiStepMoveStreategy`에서는 canAttack() 메서드 안에서 바로 canMove() 메서드를 호출합니다.

<br>

### 📌 출력 형식
---
점수에 대한 출력 형식은 정확히 정해지지 않았던 것 같습니다. 그래서 점수 출력, 그리고 게임이 종료되었을 때 승자의 출력 형식을 아래와 같이 정해봤습니다.

![image](https://github.com/woowacourse/java-chess/assets/76177848/ff030ab3-ef07-4ec6-b356-4dd2b53a8a54)

![image](https://github.com/woowacourse/java-chess/assets/76177848/182694b4-efb4-497a-9269-a309b6b7c48d)

![image](https://github.com/woowacourse/java-chess/assets/76177848/3b24b75c-5c2b-4d8a-ae28-a62fb31174de)

<br>

### 📌 개선하고 싶은 부분과 질문
---
1. 바꾼 Piece 상속 구조에 대한 피드백을 듣고 싶습니다.
2. 기물의 이동과 점수의 계산을 ChessBoard가 모두 하고 있습니다. 저는 두가지 역할 다 체스보드가 하는게 자연스럽다고 생각해서 객체 분리를 하지 않았습니다. 그런데 막상 코드가 150줄이 넘어가니 가독성이 좋지 않다는 생각이 듭니다😓 스티치는 언제 객체를 분리해야 한다고 생각하시는지, 그리고 그 기준에 의하면 ChessBoard의 책임을 분리를 해야 한다고 생각하시는지 궁금합니다.

2024-03-30 16:35 UTC, lxxjn0 requested changes
산초, 3단계 미션 진행하시느라 수고하셨습니다.

앞서 고민하시고 개선하신 piece와 관련된 부분은 충분히 잘 작성된 것 같아요. 코드를 봤을 때는 크게 이상하거나 수정될만한 부분은 없어보입니다. 또한 보드에서 piece들을 관리하고 있기에 스코어 관리 등의 책임을 가지는 것도 적절할 것 같습니다. 단지 메서드 분리가 조금 과한 부분이 있는 것 같아요. 그래서 오히려 코드를 읽기에 어려움이 느껴졌습니다. 메서드를 작게만 나눈다고 생각하기 보다는 스스로 생각하기에 적절한 맥락의 크기에 따라서 구분을 해보는 것도 한번 시도해보시면 좋을 것 같습니다 👍🏼

2024-03-30 16:35 UTC, lxxjn0 commented on src/main/java/chess/controller/ChessController.java
> +    }
해당 메서드까지는 굳이 분리하진 않아도 될 것 같습니다. 메서드 분리가 너무 많으면 오히려 코드의 로직을 파악하기에 어려움이 생길 수도 있습니다. 코드를 작성함에 있어 유의미한 범위에 맞춰 메서드 분리를 해보는 것도 좋지 않을까 싶습니다. 

이렇게 말씀드린 이유는 `readGameLifeCycleCommandWithErrorHandling` 메서드를 읽기 위해선 너무 많은 뎁스를 따라 들어가게 되면서 오히려 코드의 로직 파악이 어려웠던 것 같습니다. 메서드의 행위에 맞는 범위로 코드를 관리하는 것이 좋을 수 있을 것 같습니다.

2024-03-30 16:35 UTC, lxxjn0 commented on src/main/java/chess/controller/ChessController.java
> +    private Command readGameLifeCycleCommandWithErrorHandling() {
제 개인적인 생각인데 메서드 이름에 불필요한 내용이 많다는 느낌이 들었습니다. 해당 메서드 뿐만 아니라 executeGameFlow에서의 GameFlow라던지, GameLifeCycle와 같은 용어들입니다. 그러다보니 오히려 메서드를 읽으면서 계속 어떠한 역할을 하는 지가 오히려 더 잘 파악되지 않는 것 같아요. 

또한 반복문에 대한 해결을 재귀를 많이 사용하였는데 재귀 안에서 또 재귀가 반복되는 구조도 있는 것 같습니다. 재귀는 코드의 복잡도를 낮춰주는 장점은 있을 수 있지만 많은 반복에서는 힙 스택을 많이 차지하면서 성능 상의 이슈를 만들어 낼 수도 있습니다. 알고리즘과 같은 코드에서는 재귀의 설명이 명확하다고 생각하는데 실제 비즈니스 로직을 작성할 때는 재귀가 로직을 명확히 드러내는 데에 있어 장점이 있는지 제 개인적으로는 잘 느껴지지 않더라고요. 이 부분은 제 개인적인 의견일 수 있으니 참고만 해주시고 재귀가 가질 수 있는 문제점이 존재하기에 이런 부분에 대해서도 고려해보고 코드를 적용해보시면 좋을 것 같습니다!

2024-03-30 16:35 UTC, lxxjn0 commented on src/main/java/chess/domain/Command.java
> +    }
해당 메서드를 두는 것도 괜찮고 또는 `matchesType(CommandType commandType)` 으로 일치 여부를 확인할 type을 받아서 판단하는 메서드를 만들어 사용할 수도 있을 것 같습니다. 이건 개인의 선택이니 참고만 해주세요 ㅎㅎㅎ

2024-03-30 16:35 UTC, lxxjn0 commented on src/main/java/chess/view/CommandDto.java
> +    private static final String STATUS_EXPRESSION = "status";
이렇게 관리하면 명령어가 추가될 때마다 작업 범위가 CommandType과 View로 분리될 것 같아요. CommandType을 관리하는 곳에서 함께 관리하는 것이 어떨까요?

2024-03-30 16:35 UTC, lxxjn0 commented on src/main/java/chess/view/CommandDto.java
> +        String command = parsedInput.get(0);
매직넘버는 상수로 추출해주세요

2024-03-30 16:35 UTC, lxxjn0 commented on src/main/java/chess/view/CommandDto.java
> +        Rank rank = Rank.findByValue(rankIdx);
rank와 file에서 숫자와 알파벳을 관리하고 있으니 이를 통해서 생성하는 것이 어떨까요? 또는 Position에서 'a1'과 같은 값을 받아서 Position을 생성하거나 찾을 수 있는 정적 팩토리 메서드를 두는 것도 방법이 될 수 있을 것 같습니다.

2024-03-30 16:35 UTC, lxxjn0 commented on src/main/java/chess/domain/Rank.java
>      }
enum의 객체 순서가 변경되면 큰 이슈가 발생할 수 있지 않을까요?

2024-03-30 16:35 UTC, lxxjn0 commented on src/main/java/chess/domain/Command.java
> +    }
여기서의 인덱스도 매직넘버일 것 같아요. 또는 아예 source와 target을 나눠서 필드로 관리하는 것도 방법이 될 수 있을 것 같습니다.

2024-03-30 16:35 UTC, lxxjn0 commented on src/main/java/chess/domain/ChessGame.java
> +        chessBoard.findPieceByPosition(sourcePosition);
두 번째 라인은 필요없는 코드로 보이는데 삭제가 되지 않은걸까요?

2024-03-30 16:35 UTC, lxxjn0 commented on src/main/java/chess/domain/piece/Piece.java
> +    public final boolean isOppositeColor(final Piece piece) {
해당 메서드와 아래의 컬러를 확인하는 추가적인 메서드는 color에서 이미 oppositeColor를 반환해주는 메서드가 있으니 그 메서드를 활용하면 더 로직을 간단하게 처리할 수 있지 않을까요? 또는 color에 oppositeColor인지 확인할 수 있는 메서드를 제공해준다면 마찬가지로 더 간단하게 해결할 수 있을 것 같아요.

2024-03-30 16:35 UTC, lxxjn0 commented on src/main/java/chess/domain/piece/Piece.java
> +    public abstract Set<Direction> getAttackDirections();
pawn을 제외한 모든 piece들이 move와 attack의 direction이 같으니 getAttackDirection을 여기서 미리 getMoveDirection을 호출하도록 해두는 것은 어떨까요?

2024-03-31 12:55 UTC, nayonsoso commented on src/main/java/chess/view/CommandDto.java
> +    private static final String STATUS_EXPRESSION = "status";
관리 포인트가 늘어난다는 부분은 동의합니다. 하지만, 

1. CommandType을 관리하는 곳은 도메인인데, 도메인에서 입력 형식(view에 대한 내용)을 알고 있으면 안될 것 같습니다.

2. View에 있는 CommandDto에서는 '입력 형식 검증'을, domain에 속하는 CommandType에서는 '인자의 갯수 검증'을 해주고 있기 때문에 어쩔 수 없는 문제라고 생각합니다. 예를 들어, 블랙잭 게임에서는 사용자의 이름을 입력받았을 때 not blanck 검증과 이름길이 검증은 inputView에서 하고, '딜러'와 같은 이름을 사용할 수 없는건 Name이라는 도메인에서 해줬던 것과 비슷한 상황이라 생각해요.

3. 명령어의 갯수가 추가되는 상황을 말씀해주셨어요. 그런데 이런 경우 도메인도, 그리고 inputView도 바뀌는게 자연스럽다고 생각합니다. 관리 포인트가 2개인게 이상하게 느껴지지 않습니다!

저는 위와 같은 이유로 지금 코드도 괜찮다고 생각을 합니다. 스티치는 이에 대해 어떻게 생각하시나요? 제가 미처 고려하지 못한 부분이 있다면 말씀해주시면 감사하겠습니다🤗

2024-03-31 12:57 UTC, nayonsoso commented on src/main/java/chess/view/CommandDto.java
> +        String command = parsedInput.get(0);
아래와 같이 변경했습니다. 짚어주셔서 감사합니다😊

```java
private static CommandType computeCommandType(final List<String> parsedInput) {
    String command = parsedInput.get(COMMAND_INDEX); // ❗변경 부분
    validateCommandExpression(command);

    return parseToCommandType(command);
}
```

2024-03-31 13:01 UTC, nayonsoso commented on src/main/java/chess/domain/Rank.java
>      }
그렇겠네요😵 전에 코멘트해주셔서 만들어둔 value를 사용하도록 아래와 같이 변경했습니다.

```java
public int calculateDifference(final Rank rank) {
    return this.value - rank.value;
}
```

2024-03-31 13:12 UTC, nayonsoso commented on src/main/java/chess/domain/Command.java
> +    }
동의합니다😊 source와 target를 필드로 만들어 이를 반환하도록 변경해봤습니다.

2024-03-31 13:13 UTC, nayonsoso commented on src/main/java/chess/domain/ChessGame.java
> +        chessBoard.findPieceByPosition(sourcePosition);
앗 그런 것 같습니다😓 삭제했습니다!

2024-03-31 15:06 UTC, nayonsoso commented on src/main/java/chess/controller/ChessController.java
> +    }
`메서드가 하나의 일만 하게 하라`는 요구사항을 고려해서 위와 같이 작성했습니다. 입력을 받아 도메인 객체로 변환을 하는 것과, 도메인을 받아 검증하는 것은 다른 일이라고 생각했기 때문에 함수를 분리했습니다. 그런데 지금처럼 함수가 너무 많아지는 상황에서는 조금의 융통성이 필요하다는 생각이 드네요. 코드를 리뷰해주시는 스티치가 그렇게 느꼈으니,... 제 코드를 볼 다른 개발자들도 똑같이 느끼겠죠😓 앞으로는 무조건적으로 원칙을 고수하기보다, 상황에 맞게 적용해보도록 하겠습니다. 말씀해주셔서 감사합니다. 코드는 아래와 같이 변경했습니다.

```java
private Command readStartCommand() {
    try {
        CommandDto commandDto = inputView.readCommand();
        Command command = Command.from(commandDto);
        validateStartCommand(command);
        return command;
    } catch (IllegalArgumentException e) {
        outputView.printErrorMessage(e.getMessage());
        return readStartCommand();
    }
}
```

2024-03-31 15:20 UTC, nayonsoso commented on src/main/java/chess/controller/ChessController.java
> +    private Command readGameLifeCycleCommandWithErrorHandling() {
제가 제 코드에서 이상하게 느꼈지만, 정확히 무었 때문인지 모르던 부분을 정확히 말씀해주셨네요🥹👍 아래와 같이 바꿔봤습니다.

#### 함수 이름 변경
1. readGameLifeCycleCommandWithErrorHandling -> `readStartCommand()`
2. readGameLifeCycleCommand -> `readRunCommand()`
3. readCommandWithNoticingCurrentColor -> `readCommand(Color color)`

#### 재귀함수 사용 줄이기
사실 재귀함수를 완전히 없애기는 힘들 것 같다고 생각됩니다😓 제 컨트롤러에는 세개의 recursion이 있습니다. 
① 게임 시작시 최초 입력이 start가 아니면 예외가 발생하고 다시 입력받기 
② 게임 도중 명령어를 입력받고, 형식이 맞이 않으면 예외가 발생하고 다시 입력받기
③ end를 입력하기 전까지 move 와 status를 계속 입력받기

심지어 ③번은 ②번에서 검증이 통과해야 실행될 수 있습니다. 이 재귀의 형태를 완전히 없애진 못했고, 구조를 개선해봤습니다.

#### AS-IS
이전 코드에서는 ②번의 재귀 안에서 ③ 번의 재귀가 실행되었습니다. 

#### TO-BE
 ③번을 재귀가 아니라 while문으로 구현하고, ②번을 ③번의 while문 안에 넣어주었습니다.


```java
while (!command.matchesType(END)) { // ❗③번의 while문
    Color roundColor = chessGame.getCurrentRoundColor();
    command = runRound(chessGame, roundColor);  // ❗②번의 재귀함수
}

private Command runRound(ChessGame chessGame, Color color) {
    try {
        CommandDto commandDto = inputView.readCommand(color);
        Command command = Command.from(commandDto);
        validateStartDuplicate(command);
        return executeCommand(chessGame, command);
    } catch (IllegalArgumentException e) {
        outputView.printErrorMessage(e.getMessage());
        return runRound(chessGame, color);
    }
}
```

2024-03-31 15:22 UTC, nayonsoso commented on src/main/java/chess/domain/Command.java
> +    }
적용했습니다🤗 이전의 구현대로라면, 새로운 명령어가 추가될 때, 상수 뿐 아니라 함수도 추가될 것입니다. 말씀해주신대로 하나의 함수에서 비교를 하게 하면 그런 변경사항이 없어질 것이라 생각해서 적용했습니다. 말씀해주셔서 감사합니다!

2024-03-31 15:30 UTC, nayonsoso commented on src/main/java/chess/view/CommandDto.java
> +        Rank rank = Rank.findByValue(rankIdx);
'a1'을 받아서 `new Position(File.A, Rank.ONE)` 객체를 바로 생성해주는 정적 팩토리 메서드는 좋지 않다고 생각합니다😓 입력 형식이 1a로 바뀌면, 도메인의 코드를 바꿔줘야 할 것 같아요. 그리고 a를 받아서 File.A로 반환해주는 File.of(String string) 정적 팩토리 메서드를 만들더라도, 입력 형식이 A1로 바뀌면 그또한 바꿔줘야 할 것 같습니다. 요구사항이 바뀌었을 때 도메인 코드 변경은 최소화해야 한다고 생각합니다.

그래서 조금 나이브해보이긴 하지만, 위와 같이 view에 있는 Dto에서 입력을 도메인으로 바꿔주는게 좋을 것 같습니다. Dto의 코드는 얼마든지 바꿀 수 있으니깐요. 여기에 대해 스티치는 어떻게 생각하시나요?

2024-03-31 15:34 UTC, nayonsoso commented on src/main/java/chess/domain/piece/Piece.java
> +    public final boolean isOppositeColor(final Piece piece) {
말씀해주신대로 하니 훨씬 간단해졌습니다. 감사합니다🌞

2024-03-31 15:38 UTC, nayonsoso commented on src/main/java/chess/domain/piece/Piece.java
> +    public abstract Set<Direction> getAttackDirections();
적용했습니다. 이것도 적용해보니 코드 라인이 훨씬 줄어드네요🥹🥰

2024-03-31 15:40 UTC, nayonsoso commented
스티치, 주말은 잘 보내셨나요?
오랜만에 코멘트 남기네요 ㅎㅎ
저는 일요일에 내내 일정이 있었어서 이제야 3단계 리뷰 요청을 드립니다😭
월요일 오후 6시까지 4단계 리뷰 요청 드릴 수 있도록 최선을 다해보겠습니다!
항상 리뷰 감사드립니다💐

2024-04-01 09:26 UTC, nayonsoso commented
스티치 안녕하세요, 산초입니다. 
즐거운 하루 보내고 계신가요? 이번주부터 날씨가 많이 풀린다고 하네요. 
좋은 날씨에, 좋은 기분으로 하루를 보내시길 바랍니다🌞 

4단계 구현 내용을 간단히 정리해봤습니다.

<br>

### 📌 DDL
---
```sql
create table chess_game (
    id int primary key auto_increment,
    status varchar(50) not null  # END, CONTINUE
);

create table movement (
    id int primary key auto_increment,
    source_file varchar(50),
    source_rank varchar(50),
    target_file varchar(50),
    target_rank varchar(50),
    chess_game_id int,
    foreign key (chess_game_id) references chess_game(id)
);
```

저는 `구현은 최소한으로 하되, 확장성을 생각하기` 라는 원칙을 지키며 테이블을 설계하려 했어요. 
그래서 아래와 같이 선택을 해봤습니다.

**🔸 체스보드의 각 칸에 어떤 기물이 있는지 저장 VS 움직임을 저장하고 복구하기**
=>나중에 물리기와 같은 기능이 추가될 것을 염두에 두어, 후자를 선택했습니다.
또한 예기치 못하게 게임이 종료되었을 때도 후자가 더 안전하다고 생각했습니다.
물론 매번 DB에 접근하면 너무 DB 접근 비용이 크지 않나? 라는 생각도 들었지만,
sql을 몇번 덜 날리는 것보다, 안전하고 확장성 있게 DB를 설계하고 싶었습니다.

**🔸 체스게임과 움직임에 각각 id를 만들어주기**
=> 체스 게임을 여러개 할 경우를 염두에 두어 id 컬럼을 만들어주었습니다.
또한, 이렇게 하면 한 게임을 여러번 할 경우에도 이전 내역을 볼 수 있다는 장점이 있습니다. 

<br>

### 📌 Service의 역할
---
DB에 접근해야 하는 비지니스로직은 서비스에서 처리하게 했습니다.
ChessGameService는 아래 함수들을 가집니다.
- `ChessGame getRecentChessGame()`
- `addMovement(Position sourcePosition, Position targetPosition)`
- `endCurrentGame()`

<br>

### 📌 스스로 부족하다고 생각한 점 & 궁금한 점
---
- Dao에 대한 테스트 코드에서 autoIncrement를 설정해둔 부분이 테스트코드를 돌릴 때마다 증가한다는 것을 알게되었습니다🥲 검색해보니 `테스트용 DB를 사용하는 방법`과 `autoIncrement를 초기화하는 방법`이 있었습니다. 그런데 autoIncrement 초기화는 DB 자체를 수정하는 것이기 때문에 내키지 않았습니다. 그리고 테스트용 DB를 사용하는 방법은 아직 몰라 autoIncrement와 관련된 부분은 따로 테스트하지 않았습니다😭 추가 리팩터링을 할 때 적용해보겠습니다.
- DB에 어떤 방식으로 저장할지도 일종의 '형식 지정'이라고 생각해서 Mapper와 Dto를 많이 만들어주었습니다. 이런 방법이 괜찮은것인지 궁금합니다!
- dao 패키지를 잘 나누었는지 궁금합니다. 현재 dao 안에는 dao 뿐 아니라 [dao에서 사용하는 dto 패키지 / DB와 연결을 담당하는 ChessDBConnectionManager / dao에서만 사용하는 StatusType / dao에서만 사용하는 EnumMapper] 가 담겨있는데요, 이런 것들이 dao 패키지 안에 있어도 괜찮을까요?

2024-04-02 07:11 UTC, lxxjn0 requested changes
산초, 4단계 미션 진행하시느라 수고하셨습니다 👍🏼 

서비스 객체의 사용에 대해서 약간의 아쉬운 점이 있었습니다. 도메인 로직의 진행을 컨트롤러에서 담당하도록 개발하였던데 이 부분을 서비스 레이어에서 진행할 수 있도록 수정해보면 좋을 것 같습니다! 추가로 주셨던 질문에 대해서는 피드백에 적절히 남겨둔 것 같습니다. dao에 대한 패키지는 현재는 충분해 보입니다. dao에서 주로 사용되고 의존을 가지는 클래스를 적절히 배치해두신 것 같아서 괜찮을 것 같습니다.

2024-04-02 07:11 UTC, lxxjn0 commented on src/main/java/chess/controller/ChessController.java
> +    private Command readGameLifeCycleCommandWithErrorHandling() {
```java
while (!command.matchesType(END)) { // ❗3번의 while문
    Color roundColor = chessGame.getCurrentRoundColor();
    command = runRound(chessGame, roundColor);  // ❗2번의 재귀함수
}

private Command runRound(ChessGame chessGame, Color color) {
    try {
        CommandDto commandDto = inputView.readCommand(color);
        Command command = Command.from(commandDto);
        validateStartDuplicate(command);
        return executeCommand(chessGame, command);
    } catch (IllegalArgumentException e) {
        outputView.printErrorMessage(e.getMessage());
    }
}
```

산초가 작성한 로직에서 마지막 catch 문의 호출을 삭제해도 while 문을 그대로 다시 타고 재실행 할 수 있지 않나요? 재귀를 무조건 없애달라는 의미로 남긴 코멘트는 아니고 코드를 봤을때 해결이 가능할 것처럼 보여서 코멘트 남겨봤습니다 :)

아, 추가로 제가 남긴 리뷰에 대해서 고민한 부분과 해결한 부분을 너무 상세히 잘 남겨주셔서 맥락을 이해하기 너무 좋았습니다 👍🏼

2024-04-02 07:11 UTC, lxxjn0 commented on src/main/java/chess/controller/ChessController.java
> +    }
하나의 일만 하게 하라는 의미에서 '하나의 일'을 너무 잘게 나눠서 생각하실 필요는 없을 것 같아요. 메서드를 분리할 때는 그로 인해 얻을 수 있는 장점을 생각해보면 좋을 것 같습니다. 개발자가 정의하는 일련의 행위를 단순히 코드로 표현할 수는 없기에 적절한 행위의 범위를 묶어서 메서드의 이름으로 표현한다고 생각해볼 수도 있을 것 같아요. 그렇다면 코드만으로도 충분히 행위가 드러나는 것에서 굳이 메서드 분리가 필요한가? 라는 생각을 해볼 수 있습니다. 

예를 들어서 산초가 작성한 코드 중 아래의 코드를 봐볼게요.

```java
private Command readCommand() {
    CommandDto commandDto = inputView.readCommand();
    return Command.from(commandDto);
}
```

이 코드에서 inputView에서 가져와서 Command로 생성하는 로직은 코드를 읽기만 해도 '코멘트를 읽어오는구나'라는 하나의 맥락을 이해할 수 있습니다. 그런 경우는 메서드 분리를 굳이 할 필요는 없다고 생각해요. 그러나 코멘트를 읽어와서 하나의 프로세스를 실행하는 내용은 단순히 나열만으로는 설명이 어려울 수 있기에 메서드 분리가 유의미할 수 있다고 생각합니다. 메서드 분리는 결국 어느 정도의 복잡도를 만들어내므로 이 두 장단점 사이의 적절한 균형이 필요할 것 같습니다 👍🏼

2024-04-02 07:11 UTC, lxxjn0 commented on src/main/java/chess/view/CommandDto.java
> +        Rank rank = Rank.findByValue(rankIdx);
이 부분은 도메인에 대한 조금 더 이해가 있으면 좋을 것 같습니다. 말씀해주신 입력 형식이 바뀐다는 가정을 체스에서 하는 것은 적절하지 않다고 생각합니다.

https://en.wikipedia.org/wiki/Chess

위키피디아의 내용을 보더라도 기물의 위치를 file과 rank 순서대로 표현하는 것은 체스라는 게임에서 공식적으로 사용되는 표현법이라고 볼 수 있을 것 같습니다. 우리가 수학에서 함수를 f(x)라고 표현하는 것처럼요. 이처럼 도메인에서 변경이 발생할 수 있는 가능성이 없는 영역을 변경 가능 영역으로 가정하고 개발을 한다면 그 가정의 범위는 걷잡을 수 없지 않을까 싶습니다(어떤 도메인에서 이미 설정된 내용을 모두 변경 가능한 개념이라고 치부하는 것을 말씀드린 것입니다). 그래서 저는 해당 도메인에서 이러한 표현법은 변경 가능한 범위에 속하지 않는다고 판단했고 그렇기에 제안드려봤습니다 :)

비즈니스에서 제공한 개념에 대해서 모두 다 변경이 가능할 수 있다라고 열려있는 생각을 하는 것은 좋은 접근이라고 생각합니다. 그러나 도메인에 대한 이해와 어떤 범위에서는 비즈니스가 변경되더라도 코드상의 변경을 만들지 않고 사용할 수도 있을 것입니다. 만약 a1이 ㅁ1이라는 표기법으로 바뀐다면 도메인의 유지를 위해서 view에서 ㅁ1을 a1으로 매핑하는 로직을 두는 것도 방법이 될 것이고요. 이는 추가적인 다른 접근 방법 중 하나이니 참고차 남겨봤습니다!

2024-04-02 07:11 UTC, lxxjn0 commented on src/main/java/chess/view/CommandDto.java
> +    private static final String STATUS_EXPRESSION = "status";
해당 코멘트에 대한 리뷰를 읽기 전에 먼저 아래 리뷰에 대한 추가 코멘트를 확인한 후 읽어주시면 감사하겠습니다 🙇🏼‍♂️ 

https://github.com/woowacourse/java-chess/pull/745/files/f0e79caead8bb39ce6e1fa1160644a555f3469c6#r1545453472

위 코멘트에 이어서 제 생각을 한번 말씀드려보겠습니다.

먼저 사용자가 입력하는 커맨드(명령)을 단순히 inputView의 형식으로만 봐야하는가에 대해서 전 동의하지 않습니다. 명령은 사용자가 체스 게임을 실행하기 위한 행위이므로 도메인으로 보는게 적절하다고 생각합니다. 그렇다면 이때 명령을 어떻게 내리는 지, 이를 뷰에서 어떻게 표현하는지는 뷰의 영역인지 도메인의 영역인지에 대한 구분이 필요할 것 같습니다. 

만약 게임에 사용되는 커맨드를 도메인에서는 뷰와 전혀 다른 개념이나 용어로 관리한다면 분리할 필요가 있다고 생각합니다. 만약 뷰에서는 한글로 받고 이를 서버에서는 영어로 변환해야 한다면 말이죠. 그러나 START라는 키워드를 'start'라는 용어로 관리하는 것에서 뷰의 영향 범위로 봐야만 하는지는 조금 고민이 될 것 같습니다. 저라면 위에 링크에서 마지막에 남긴 말처럼 커맨드의 행위를 동일한 문자로 관리하고 이후 뷰에서 변경되는 내용에 대해서는 뷰의 매핑로직을 두고 관리할 것 같습니다. 결국은 인터페이스와 같은 개념이 아닐까 생각합니다.

예를 들어서 체스를 웹뷰로 바꾼다고 생각하고 사용자에게는 커맨드를 입력받는 방법을 버튼으로 변경한다고 생각해보겠습니다. 그렇다면 view에서는 서버에서 제공하는 커멘드에 맞게 매핑을 해서 'start'라는 명령으로 api를 호출하면 되지 않을까요?

또는 만약 DTO에서 명령에 대한 매핑을 관리하고 싶다면 적어도 코드상의 매핑으로 변경에 대한 범위를 확인할 수 있는 방식으로 관리가 되어야 하지 않을까 싶습니다. 이 말이 어려울 수 있는데 enum에서 CommandType을 필드로 가지고 그에 맞는 view의 입력 text를 필드로 가진 후 찾아서 사용할 수 있는 방식으로요.

```java
public enum CommandMapper {
    START(CommandType.START, "start"),
    // ...
}
```

결론은 제가 느끼기에 '도메인에서 사용되는 동일한 용어로 view에서 이미 사용하고 있는데 이를 view의 내용을 도메인이 알게 된다고 봐야하나?' 에 대해서는 '도메인의 용어를 view에서 사용하는 것이 아닌가?'라고 보는게 더 적절하지 않을까 라는 생각이었습니다.

만약 DTO에서 관리하는 것이 조금 더 선호에 맞다면 적어도 도메인과 이러한 실행과 관련된 명령에 의존성을 부여해서 코드의 변경에 따른 변경 범위를 추적할 수 있도록 코드를 작성하는 것이 좋지 않을까 생각합니다 :)

2024-04-02 07:11 UTC, lxxjn0 commented on src/main/java/chess/dao/EnumMapper.java
> +public class EnumMapper {
해당 클래스가 필요한가요? 그냥 `name()` 메서드를 호출하면 될 것 같아서요.

2024-04-02 07:11 UTC, lxxjn0 commented on src/main/java/chess/dao/ChessGameDao.java
> +            final var resultSet = preparedStatement.executeQuery();
try-with-resource 구문 사용 👍🏼

2024-04-02 07:11 UTC, lxxjn0 commented on src/main/java/chess/dao/StatusType.java
> +public enum StatusType {
해당 클래스는 결국 게임 상태를 관리하게 되는데 dao의 객체로 보는게 맞을까요? 결국 비즈니스 로직을 전개하는데 사용되는 클래스로 보여져서요.

2024-04-02 07:11 UTC, lxxjn0 commented on src/main/java/chess/dao/MovementDao.java
> +                String targetRank = resultSet.getString("target_rank");
해당 데이터도 앞선 리뷰를 참고해서 'a1'과 같은 포지션으로 관리하는 것은 어떨까 싶습니다. 나중에 데이터를 확인할 때도 가독성인 부분에서 더 장점을 가질 수 있을 것 같아서요.

2024-04-02 07:11 UTC, lxxjn0 commented on src/main/java/chess/service/ChessGameService.java
> +        if (responseChessGameDto == null || responseChessGameDto.statusType().isEnd()) {
디미터의 법칙을 한번 참고해보고 개선해보면 좋을 것 같습니다!

2024-04-02 07:11 UTC, lxxjn0 commented on src/main/java/chess/controller/ChessController.java
> +        chessGameService.addMovement(source, target);
컨트롤러에서 도메인 로직의 진행을 담당하고 있습니다. 서비스 레이어가 추가된 만큼 도메인에 대한 행위는 서비스에서 담당하는 것이 적절할 것 같습니다. 서비스 레이어가 하는 역할에 대해서 한번 학습해보시는 것도 좋을 것 같습니다!

2024-04-02 11:00 UTC, nayonsoso commented on src/main/java/chess/controller/ChessController.java
> +    }
> 하나의 일을 너무 잘게 나누어 생각할 필요는 없다. 

> 함수는 행위를 묶어 코드로 표현하는 것인데, 
코드 자체로 행위가 드러난다면 굳이 메서드 분리가 필요한가?

어느 순간부터 함수를 `최대한 작게` 나눠야 한다고 생각했던 것 같습니다😓
스티치의 리뷰를 통해 함수의 의미에 대해 더 생각해볼 수 있었습니다. 감사합니다!

2024-04-03 05:23 UTC, nayonsoso commented on src/main/java/chess/view/CommandDto.java
> +        Rank rank = Rank.findByValue(rankIdx);
> 도메인에서 변경이 발생할 수 있는 가능성이 없는 영역을 변경 가능 영역으로 가정하고 개발을 한다면 그 가정의 범위는 걷잡을 수 없지 않을까 싶습니다.

정말 맞는 말씀이라 생각해요😭✨👍 변경 가능의 범위를 너무 넓게 생각하니 걷잡을 수 없게 된 것을 이번에 경험하기도 했고요. 그리고 만약 바뀌더라도 해결 방법을 말씀해주셔서 `혹시라도 바뀌면 이런 방법을 쓰면 되겠다`는 식으로 생각도 정리할 수 있게 되었습니다! 큰 도움이 된 답변이었습니다. 감사합니다.

리뷰를 반영하여 "a1"을 받아 Position을 반환하는 정적 팩토리 메서드를 만들어주었습니다🌞

2024-04-03 05:32 UTC, nayonsoso commented on src/main/java/chess/view/CommandDto.java
> +    private static final String STATUS_EXPRESSION = "status";
> 먼저 사용자가 입력하는 커맨드(명령)을 단순히 inputView의 형식으로만 봐야하는가에 대해서 전 동의하지 않습니다. 명령은 사용자가 체스 게임을 실행하기 위한 행위이므로 도메인으로 보는게 적절하다고 생각합니다. 

확실히 이전 미션에서 inputView로 입력받은 이름과 비교했을 때 `명령`은 그 성질이 다른 것 같습니다. 이름은 그 내용 자체가 도메인에서 중요한건 아니지만, 명령은 그 내용이 특정 행위와 일대일 대응된다는 큰 차이가 있겠네요. 자세하게 예시를 들어 설명해주셔서 스티치가 어떤 말씀을 하시는지 이해할 수 있었습니다😊

---

> 도메인의 용어를 view에서 사용하는 것이 아닌가?

위 내용을 보고 머리가 띵 했습니다. `나는 왜 이런 생각을 못해봤을까` 하며 말이죠🥲 한번도 그런 방식으로 생각해본적은 없는데,.. 정말 맞는 말씀이라 느꼈습니다. 덕분에 새로운 측면에서 생각할 수 있게 된 것 같습니다.

---

> 적어도 도메인과 이러한 실행과 관련된 명령에 의존성을 부여해서 코드의 변경에 따른 변경 범위를 추적할 수 있도록 코드를 작성하는 것이 좋지 않을까

또한 변경 범위를 추척할 수 있게 코드를 작성하는 방법을 알려주신 것도 감사합니다. 저는 `어쩔 수 없는 부분이다` 하고 넘어갔었는데, 스티치가 알려주신 방법을 사용하면 분리를 하면서도 연관 관계를 명시적으로 나타낼 수 있을 것 같습니다!

<br>

결론적으로 코드를 이렇게 바꿔봤습니다.


```java
public enum CommandType { // commandType에서 명령어 표현들을 관리
    START("start", 0),
    MOVE("move", 2),
    END("end", 0),
    STATUS("status", 0),
    ;
}
```

2024-04-03 05:35 UTC, nayonsoso commented on src/main/java/chess/dao/EnumMapper.java
> +public class EnumMapper {
이 클래스는 enum을 String으로 바꾸기도 하지만, String을 Enum으로 바꾸기 위해 만들어주었어요.
DB에서 enum을 받아올 때는 String 형식이지만, 도메인 객체로 바꾸기 위해서
이 String을 Enum으로 바꿔주는 과정이 필요했습니다.
그리고 각 Enum마다 Mapper를 만들어주기에는 중복 코드가 많아서 
위 코드를 만들어 중복 코드를 줄인 것입니다!

2024-04-03 05:36 UTC, nayonsoso commented on src/main/java/chess/dao/StatusType.java
> +public enum StatusType {
맞습니다.. 😓
그리고 StatusType이 도메인에서 사용하는 GameStatus 와 동일한 역할을 하고있더라고요.
그래서 도메인의 GameStatus enum을 사용하도록 바꿔주었습니다!

2024-04-03 05:44 UTC, nayonsoso commented on src/main/java/chess/dao/MovementDao.java
> +                String targetRank = resultSet.getString("target_rank");
이 부분은 확장성을 고려해 file과 rank를 분리해둔 것입니다!

예를 들어, 이벤트를 위한 체스 게임을 만들어서 `특정 File에 말이 있으면 점수를 두배로 얻는 이벤트`를 연다고 가정해볼게요. (조금 이상한 규칙 같지만, 제가 좋아하는 모두의 마블에서는 흔하게 일어나는 일입니다😂) 그렇다면 File을 기준으로 기물을 조회해야 할거에요. 물론 position으로 file과 rank를 한번에 관리해도 데이터를 가져올수는 있겠지만 과정이 많이 복잡해질 것이라 생각합니다. 

그리고 DB의 경우 데이터가 있는 상태라면 그 구조를 나중에 변경하기가 더 힘들다고 생각합니다. 또한, 지금도 충분히 가독성이 괜찮다는 생각이 들어 설계를 유지하고 싶어요. 스티치는 이에 대해 어떻게 생각하시나요?

2024-04-03 05:45 UTC, nayonsoso commented on src/main/java/chess/service/ChessGameService.java
> +        if (responseChessGameDto == null || responseChessGameDto.statusType().isEnd()) {
위 코드에서 디미터의 법칙을 지키기 위해서는 
responseChessGameDto에 `isEnd()` 메서드가 있어야 할 것 같아요. 
그런데 이는 값을 전달하는 역할을 하는 dto에 어울리지 않는다는 생각이 듭니다😭
스티치는 dto에 다른 함수가 들어가더라도 디미터 법칙을 지켜야 한다고 생각하시나요?
의견을 듣고 싶습니다!

2024-04-03 05:54 UTC, nayonsoso commented on src/main/java/chess/controller/ChessController.java
> +        chessGameService.addMovement(source, target);
말씀해주신 덕분에 서비스 레이어에 대해 공부해보았습니다🫡
가장 와닿는 정리는 아래와 같았어요.

1. 도메인 객체간의 상호작용을 조정하고
2. Persistence Layer와 데이터를 주고 받으며
3. 한 기능 단위의 결과물을 Controller로 전달한다.

저는 2번의 기능만 생각했던 것 같습니다😓
리뷰를 반영하며, 체스보드에서 말을 옮기는 기능 자체를 서비스가 수행하도록 변경해보았습니다.
그리고 이 과정에서 서비스가 필드를 갖지 않은 상태에서 ChessGame을 변경할 수 있도록,
ChessGame을 불변하게 만들어주었습니다.

```java
public class ChessGame {
    public ChessGame executeRound(final Position sourcePosition, final Position targetPosition) {
        validateRoundColor(sourcePosition);
        GameStatus gameStatusAfterMove = chessBoard.move(sourcePosition, targetPosition);
        Color nextRoundColor = currentRoundColor.getOppositeColor();
    
        return new ChessGame(this.chessBoard, nextRoundColor, gameStatusAfterMove);
    }
}
```

```java
public class ChessGameService {
    public ChessGame executeMove(final ChessGame chessGame, final Position sourcePosition, final Position targetPosition) {
        // 움직임을 저장한 후
        int chessGameId = chessGameDao.findRecentChessGameId();
        RequestMovementDto requestMovementDto = RequestMovementDto.of(sourcePosition, targetPosition, chessGameId);
        movementDao.addMovement(requestMovementDto);

        // 움직이고 나서의 체스게임을 반환
        return chessGame.executeRound(sourcePosition, targetPosition);
    }
}
```

2024-04-03 06:07 UTC, nayonsoso commented
스티치 안녕하세요, 다시 찾아온 산초입니다🌞
지난 코멘트를 보며 감동을 받았습니다😭✨
장문으로, 예시를 들어 설명해주셔서 새로운 관점을 갖을 수 있게 되었습니다.
스티치와 리뷰를 진행하며 많이 성장하고 있음을 느낍니다🔥
이번 리뷰도 잘 부탁드립니다!

<br>

### 📌 리팩토링 내용 목록
- [x] "a1"를 입력받으면, Position(File.A, Rank.ONE)을 생성하는 정적 팩토리 메서드 생성
- [x] dao에 있는 StatusType대신 도메인에 enum 을 사용하도록 수정
- [x] 명령어 입력 형식을 CommandType에서 관리해주도록 수정
- [x] 서비스 계층에서 도메인 로직을 실행하도록 수정
- [x] 테스트 DB를 사용해서 id 증가하는 것 테스트 -> 이 부분은 첫번째 PR에서 '리팩토링을 하며 적용해보겠다'라고 말씀드린 부분입니다!

<br>

### 📌 지난 코멘트에 대해 궁금한 점
- 확장성을 고려해 DB에서 "a1"을 한번에 저장하지 않고, "a" 와 "1"을 따로 저장하게 했는데 이 이유가 타당하다고 생각하시는지? [링크](https://github.com/woowacourse/java-chess/pull/745#discussion_r1548944128)
- 디미터의 법칙을 지키기 위해 dto에 함수를 만들어 줘야할지? [링크](https://github.com/woowacourse/java-chess/pull/745#discussion_r1548945867)

<br>

### 📌 구현을 하며 생긴 궁금한 점 : 테스트용 DB의 사용
- 4단계 첫번째 PR에서 말씀드린대로, 프로덕트 DB와 테스트 DB를 같은 것을 사용하다보니 `auto_increment를 사용하는 id가 테스트 코드에 의해 계속 증가하는 문제`를 겪었습니다. 그리고 이를 해결하기 위해서 `테스트용 DB`를 만들어 테스트해보았습니다. 그 방법은, jdbc에서 제공하는 인메모리 h2를 사용해서, 테스트 시작할 때 테이블을 만들고, 테스트 종료시 테이블을 지우는 방법입니다. 이 방법을 사용했더니 id에 대한 테스트도 문제없이 할 수 있었습니다. 하지만 테스트용 DB를 만드는 것이 처음이다보니 .. 😓 이 방법이 맞는지 확신은 없네요.. 스티치는 어떻게 생각하시는지 궁금합니다!

2024-04-03 06:29 UTC, nayonsoso commented
스티치 안녕하세요, 다시 찾아온 산초입니다🌞
지난 코멘트를 보며 감동을 받았습니다😭✨
장문으로, 예시를 들어 설명해주셔서 새로운 관점을 갖을 수 있게 되었습니다.
스티치와 리뷰를 진행하며 많이 성장하고 있음을 느낍니다🔥
이번 리뷰도 잘 부탁드립니다!

<br>

### 📌 리팩토링 내용 목록
- [x] "a1"를 입력받으면, Position(File.A, Rank.ONE)을 생성하는 정적 팩토리 메서드 생성
- [x] dao에 있는 StatusType대신 도메인에 enum 을 사용하도록 수정
- [x] 명령어 입력 형식을 CommandType에서 관리해주도록 수정
- [x] 서비스 계층에서 도메인 로직을 실행하도록 수정
- [x] 테스트 DB를 사용해서 id 증가하는 것 테스트 -> 이 부분은 첫번째 PR에서 '리팩토링을 하며 적용해보겠다'라고 말씀드린 부분입니다!

<br>

### 📌 지난 코멘트에 대해 궁금한 점
- 확장성을 고려해 DB에서 "a1"을 한번에 저장하지 않고, "a" 와 "1"을 따로 저장하게 했는데 이 이유가 타당하다고 생각하시는지? [링크](https://github.com/woowacourse/java-chess/pull/745#discussion_r1548944128)
- 디미터의 법칙을 지키기 위해 dto에 함수를 만들어 줘야할지? [링크](https://github.com/woowacourse/java-chess/pull/745#discussion_r1548945867)

<br>

### 📌 구현을 하며 생긴 궁금한 점 : 테스트용 DB의 사용
- 4단계 첫번째 PR에서 말씀드린대로, 프로덕트 DB와 테스트 DB를 같은 것을 사용하다보니 `auto_increment를 사용하는 id가 테스트 코드에 의해 계속 증가하는 문제`를 겪었습니다. 그리고 이를 해결하기 위해서 `테스트용 DB`를 만들어 테스트해보았습니다. 그 방법은, jdbc에서 제공하는 인메모리 h2를 사용해서, 테스트 시작할 때 테이블을 만들고, 테스트 종료시 테이블을 지우는 방법입니다. 이 방법을 사용했더니 id에 대한 테스트도 문제없이 할 수 있었습니다. 하지만 테스트용 DB를 만드는 것이 처음이다보니 .. 😓 이 방법이 맞는지 확신은 없네요.. 스티치는 어떻게 생각하시는지 궁금합니다!

2024-04-04 07:45 UTC, lxxjn0 commented on src/main/java/chess/dao/EnumMapper.java
> +public class EnumMapper {
String을 Enum으로 바꿀 때도 지금의 로직이라면 기본적으로 Enum에서 제공되는 valueOf 메서드를 사용해도 될 것 같아보입니다. 사실 사용하겠다면 상관은 없지만 제가 보기엔 이러한 유틸리티 클래스를 두고 사용하는 것이 좋다라는 생각이 크루들 사이에 많이 퍼져있는 듯한 느낌이 들어서요(다른 크루들의 코드를 리뷰할 때도 이러한 성격의 클래스를 자주 마주치는 것 같습니다). 간단하게 해결이 가능하다면 그 해결책을 쓰는 것이 더 좋지 않을까 생각해서 리뷰 남겨봤습니다.

2024-04-04 07:47 UTC, lxxjn0 commented on src/main/java/chess/dao/MovementDao.java
> +                String targetRank = resultSet.getString("target_rank");
위와 같이 피드백을 드린 이유는 결국 Position 객체로 만들어서 사용하시는 것 같더라고요. 그리고 그게 저도 맞다고 생각하고요. 그렇다면 나중에 점수가 2배인 경우가 생긴다면 그건 Position 객체에서 가져야 할 책임이지 않을까요?

2024-04-04 07:48 UTC, lxxjn0 commented on src/main/java/chess/service/ChessGameService.java
> +        if (responseChessGameDto == null || responseChessGameDto.statusType().isEnd()) {
산초의 의견도 어느정도 일리가 있다고 생각합니다. response 객체라면 사실 값의 캡슐화에 대해서 굳이 고려를 하지 않아도 될 수 있으니 지금의 방법도 괜찮을 것 같다는 생각이 드네요 :)

2024-04-04 07:53 UTC, lxxjn0 approved these changes
산초, 미션 진행하시느라 수고 많으셨습니다. 전체적으로 코드가 잘 마무리된 것 같아서 이만 종료하려고 합니다. 

남겨주신 질문은 보통 테스트 코드에서는 인메모리 DB를 사용해서 테스트를 하곤 합니다. 그런데 사실 DB와 관련된 부분은 mocking 처리를 해서 주로 테스트를 진행하는 것 같아요. 결국 테스트 시점에 DB를 구동시키는 것이 비용이 될 수 있기 때문입니다. 이 부분은 레벨2에서 미션 진행하면서 한번 경험해볼 수 있을 것 같습니다 :)

체스 미션 진행하시느라 정말 수고 많으셨습니다 👍🏼

2024-04-04 07:53 UTC, merged