[체스 - 3,4단계] 로키(정해성) 미션 제출합니다.
woowacourse/java-chess pull request #757
Opened 2024-03-29 13:31 UTC by HaiSeong

피케이 안녕하세요.
이전 구조를 변경하지 않고 3, 4단계를 진행하는 것을 목표로 했습니다.
기물의 음직임을 db에 저장했습니다.
게임을 실행 후 start를 누르면 처음부터 깨끗하게 시작, continue를 누르면 기존에 플레이 하던 게임을 시작하게 했습니다.

### db 생성 쿼리
```sql
CREATE TABLE move (
    source_x INT CHECK (source_x >= 1 AND source_x <= 8),
    source_y INT CHECK (source_y >= 1 AND source_y <= 8),
    destination_x INT CHECK (destination_x >= 1 AND destination_x <= 8),
    destination_y INT CHECK (destination_y >= 1 AND destination_y <= 8)
);

```

몇가지 질문이 있습니다!

1. DB를 사용하게 되면서 repository 계층이 생겼습니다. 스프링을 잠깐 사용해본적이 있는데 그때는 repository 라는 이름의 패키지로 사용했던 기억이 있어 이렇게 작성했습니다. dao 또는 database 라는 패키지 명이 더 어울리는지 궁금합니다.
2. service 레이어가 필요한지 궁금합니다. 제가 지금까지 조사하고 생각해본 service가 필요한 이유와 생각은 다음과 같습니다.
> 1. controller 가 너무 커진다. service로 분리해서 깔끔하게 해보자. 
>->  controller가 커져서 service를 만든다면 1,2 단계에서는 왜 안만들었나?
> 2. controller에 테스트가 필요한 로직들을 service로 만들어서 테스트 하자.
> -> 이전에는 왜 controller 테스트 안했나? 테스트 때문에 service가 필요한것 같다는 이유로는 도입하지 못하겠다.
> 3. service의 메서드 하나가 한 트렌젝션이다. 여러 유저 같이 접속하면 어떡할거냐
> -> 지금 게임에서 여러 유저가 같이 접속하는 시나리오는 아직 없는것 같다.

3, 4 단계 리뷰도 잘 부탁드립니다.

2024-03-31 02:48 UTC, pkeugine requested changes
안녕하세요 로키!
정말 깔끔하게 추가 요구사항 구현해주셨네요.
리뷰 남겨봤으니 한 번 확인해주세요.
혹시라도 이해가 안되거나 궁금한 점이 생기면 언제든지 DM 주세요!

2024-03-31 02:48 UTC, pkeugine commented on build.gradle
> +    runtimeOnly("com.mysql:mysql-connector-j:8.3.0")
드디어 DB 를 사용하게 되었어요 👏 👏 👏 
gradle 에서 의존성을 불러올 때 사용하는 `runtimeOnly`, `implementation`, 그리고 `testImplementation` 에 대해 학습하고 적용해보는건 어떨까요?

2024-03-31 02:48 UTC, pkeugine commented on src/main/java/chess/Application.java
> +        MoveRepository moveRepository = new MoveDao();
> DB를 사용하게 되면서 repository 계층이 생겼습니다. 스프링을 잠깐 사용해본적이 있는데 그때는 repository 라는 이름의 패키지로 사용했던 기억이 있어 이렇게 작성했습니다. dao 또는 database 라는 패키지 명이 더 어울리는지 궁금합니다.

마침 제가 다음과 같은 리뷰를 남기려고 했어요 : 
```
`MoveRepository` 와 그 구현체인 `MoveDao` 가 있네요.
Dao 와 Repository 라고 각각 이름 지은 이유가 궁금해요!
```

dao 와 repository 가 각각 어떤 것을 의미하는지, repository 라는 표현은 어쩌다 나온건지를 한 번 알아보셔도 좋을 것 같아요. 그리고 그렇게 알아보고 난 뒤에 MoveRepository 는 어떤 패키지에 들어가는게 적절한지도 생각해보면 재밌겠네요.

제 생각엔 repository 라는 이름을 사용하신게 딱히 어색하진 않아요. 그리고 dao / database 라고 이름을 지어도 어색하지 않고요. Spring 에서 지은 이름을 따라가기 보단 로키가 어떤 방식으로 DB 에 있는 자료를 다룰건지를 고민해보고, 그에 맞는 이름을 지어주면 됩니다! 예를 들어 Repository 라고 이름을 짓는다면 이를 마치 일급 컬렉션처럼 다루면 될 것 같네요.

2024-03-31 02:48 UTC, pkeugine commented on src/main/java/chess/controller/ChessGameController.java
> +        waitStartCommand(chessGame);
사용자가 선택할 수 있는 옵션이 늘어났으니 메서드의 이름에도 이를 반영해보는건 어떨까요?

2024-03-31 02:48 UTC, pkeugine commented on src/main/java/chess/dto/Move.java
> +}
메서드와 변수명 컨벤션을 지켜주세요 :)
https://google.github.io/styleguide/javaguide.html#s5.2.3-method-names

2024-03-31 02:48 UTC, pkeugine commented on src/main/java/chess/controller/ChessGameController.java
> +        }
승리 상태를 출력하는 부분은 OutputView 에게 역할을 주면 좋을 것 같네요.

2024-03-31 02:48 UTC, pkeugine commented on src/main/java/chess/domain/ChessGame.java
> +    }
```suggestion
    public StatusDto calculateScore() {
        return new StatusDto(
            moveState.calculateScore(Color.WHITE),
            moveState.calculateScore(Color.BLACK)
        );
    }
```
줄바꿈을 활용해서 가독성을 높여보는건 어떨까요?

2024-03-31 02:48 UTC, pkeugine commented on src/main/java/chess/view/OutputView.java
>          System.out.println("> 게임 이동 : move source위치 target위치 - 예. move b2 b3");
애플리케이션 기능이 많아지면서 출력할 내용도 많아지죠?
이렇게 한줄씩 출력하는 방법이 아니라 문자열을 미리 만들어서 한 번에 출력하는 방식으로 변경해보는건 어떨까요?
multiline String 방식을 사용해도 좋고, `System.out.lineSeparator` 를 사용해봐도 좋을 것 같아요.
왜 그러면 좋을지도 한 번 알아보아요 :)

2024-03-31 02:48 UTC, pkeugine commented on src/main/java/chess/domain/dto/StatusDto.java
> +}
OutputView 에 전달되는 값 중 점수만 DTO 를 만들어주신 이유가 궁금해요.

2024-03-31 02:48 UTC, pkeugine commented on src/main/java/chess/repository/MoveDao.java
> +    }
이 메서드는 로키의 다른 코드와 이질감이 느껴지는 부분인데요,

* 이 곳에서만 catch 부분에 final 처리를 한 이유
* return null 을 하는 이유

위와 같은 부분이 궁금합니다.

2024-03-31 02:48 UTC, pkeugine commented on src/main/java/chess/repository/MoveDao.java
> +            e.printStackTrace();
DB 관련 예외가 발생했을 때도 예외 메시지를 유저에게 잘 전달해보는건 어떨까요?

2024-03-31 02:48 UTC, pkeugine commented on src/main/java/chess/repository/MoveDao.java
> +                int destination_y = resultSet.getInt(4);
위의 리뷰에서도 남겼듯이, 변수명 컨벤션을 지켜주세요 :)

2024-03-31 02:48 UTC, pkeugine commented on src/main/java/chess/repository/MoveDao.java
> +        try (PreparedStatement statement = connection.prepareStatement(sql)) {
PreparedStatement 사용시 try-with-resources 👍 
Connection 이나 ResultSet 을 형성할 때도 try-with-resources 를 사용할 수 있는데요, 한 번 알아볼까요?
필수로 적용하지는 않으셔도 괜찮아요.

2024-03-31 02:48 UTC, pkeugine commented on src/main/java/chess/domain/state/MoveState.java
> +
MoveState 의 접근제한자를 변경해주세요! 저번 step 에서 변경되지 않고 넘어왔네요 😂

2024-03-31 02:48 UTC, pkeugine commented on src/main/java/chess/domain/state/MoveState.java
> +                .sum();
PieceScore 로부터 점수를 가져오는걸 piece 가 직접 하도록 변경해보면 어떨까요?
Piece 를 이용해서 로직을 만들 때 훨씬 편리할 것 같아요

```suggestion
        double totalScore = board.values().stream()
                .filter(piece -> piece.isSameColor(color))
                .mapToDouble(piece -> piece.score())
                .sum();
```

2024-03-31 02:48 UTC, pkeugine commented on src/main/java/chess/domain/state/MoveState.java
> +    }
pawn 점수 계산 깔끔하게 잘 만들어주셨네요 👍

2024-03-31 02:48 UTC, pkeugine commented on src/test/java/chess/domain/state/MoveStateTest.java
> +}
file 의 끝부분에 공백 넣는 것 잊지마세요! :)
intelliJ 설정을 바꿔서 저장될 때마다 자동으로 공백을 넣어주도록 할 수도 있어요.

2024-03-31 02:48 UTC, pkeugine commented on src/main/java/chess/controller/ChessGameController.java
> +    public ChessGameController(final InputView inputView, final OutputView outputView, MoveRepository moveRepository) {
> service 레이어가 필요한지 궁금합니다.

로키의 생각 잘 읽었습니다 ㅋㅋㅋ
페어가 없어도 스스로 치열하게 고민하시네요 👍 

우선 제 생각은 다음과 같습니다 : 
`지금 시점에서 슬슬 service 를 도입해봐도 괜찮겠다.`

로키가 적어주신 로키의 생각을 따라가면서 그 이유를 적어볼게요:

**controller 가 너무 커진다. service로 분리해서 깔끔하게 해보자.**
저는 지금의 controller 가 그리 크다고 생각하지 않습니다. 기능이 추가되면서 로직이 많아지고 있긴 하지만, 아직까지는 그리 복잡하다는 생각은 들지 않아요. 오히려 service 로 분리하면 더 복잡해질 수 있다는 생각이 듭니다. 로직이 복잡해진다기보단 dto 와 같은 파생되는 클래스도 생길거니까요. 만약 이 애플리케이션이 콘솔에만 머물고 더 이상 요구사항이 없을 거라면 저는 service 는 굳이 만들 필요 없다고 생각합니다.

`controller가 커져서 service를 만든다면 1,2 단계에서는 왜 안만들었나?` 라는 생각은 그렇게 생각하지 않으셔도 괜찮아요. 저번에 안 했다고 오늘의 내 판단이 거기 영향을 받으면 안된다고 생각합니다!

**controller에 테스트가 필요한 로직들을 service로 만들어서 테스트 하자.**
이건 service 로 분리하는 것과는 다른 내용인 것 같아요. 분리 여부를 떠나서 통합테스트를 만들 수 있으니까요. 오히려 service 만 테스트를 만들고 그걸 유지보수하는 것보다 전체적인 흐름을 통합 테스트로 확인하는게 쉽고 유용할 때가 많아요.
그렇기 때문에 `이전에는 왜 controller 테스트 안했나? 테스트 때문에 service가 필요한것 같다는 이유로는 도입하지 못하겠다.` 라는 생각엔 저도 동의합니다. 굳이 구조를 바꾸지 않더라도 테스트 할 수 있으니까요.

**service의 메서드 하나가 한 트렌젝션이다. 여러 유저 같이 접속하면 어떡할거냐**
정확히 말하자면 SpringBoot 로 개발할 때 꼭 `하나의 트랜잭션 = 하나의 메서드` 이진 않아요. 그런데 이 생각을 로키가 왜 하셨는지 제가 이해를 잘 못한거 같습니다. 조금 더 구체적으로 설명해주시면 감사하겠습니다.

`지금 게임에서 여러 유저가 같이 접속하는 시나리오는 아직 없는것 같다.`
좋은 생각이에요. 그런데 그럼에도 불구하고 제가 `지금 시점에서 슬슬 service 를 도입해봐도 괜찮겠다.` 라고 생각한 이유는, 다른 미션에서 체스를 콘솔이 아닌 다른 형태로 유저에게 보여주는 요구사항이 나올 수도 있기 때문이에요. 그래서 도메인과 dao (repository) 를 사용하는 로직을 따로 묶어놓는 작업을 지금 한 번쯤 해보고, 나중에 그게 어떻게 도움이 되었는지, 도움이 안되었다면 왜 그랬는지 확인해보기 좋다고 생각했습니다. 😄

2024-03-31 03:50 UTC, HaiSeong commented on src/main/java/chess/controller/ChessGameController.java
> +        waitStartCommand(chessGame);
조금더 포괄적인 의미를 담은 메서드 이름으로 변경해보겠습니다. `waitGameInitializationCommand` 라는 이름으로 바꿔보겠습니다!

2024-03-31 04:53 UTC, HaiSeong commented on src/main/java/chess/dto/Move.java
> +}
변수명은 `int source_x, int source_y, int destination_x, int destination_y`를 말씀하신것 같아요. x -> column, y -> rank 로 수정하겠습니다.

또한 애초에 클래스명 또한 Move 라는 이름보다 Movement 라는 명사형 이름이 어울리겠다 생각합니다.

다만 메서드명에 대해서는 정적팩토리명에 대해서 말씀하신 것인지 Position의 getX, getY를 말씀하신것인지 궁금합니다.

1. 만약 정적팩토리라면
테코블의 [정적 팩토리 메서드(Static Factory Method)는 왜 사용할까?](https://tecoble.techcourse.co.kr/post/2020-05-26-static-factory-method/) 라는 글의 마지막에 `정적 팩토리 메서드 네이밍 컨벤션`의 `of : 여러개의 매개 변수를 받아서 객체를 생성` 라는 내용을 참고해서 of 라는 이름이 나쁘지 않겠다는 생각에 만들었습니다.

그러나 of 라는 이름이 단순히 만든다는 의미를 준다는 점 외에는 없어서 조금더 의미있는 이름이 필요하다는것은 동의합니다.
이전 미션 리뷰에서 List<String> names을 이용해서 `Cars`라는 일급 컬랙션 클래스를 생성하는 만드는 정적 팩토리 메서드 이름으로 `from`을 사용한적이 있었습니다. 그때 받은 리뷰에서 조금더 의미를 담아서 'fromNames' 라고 바꾸는게 어떻겠는가 라는 내용이 있었습니다.

이와 같은 맥락의 수정을 원하신것인지 궁금합니다! 

또한 `from`, `of` 라는 정적 팩토리 메서드의 네이밍 컨벤션이 있는데 이것을 'fromNames', 'ofPositions' 라는 식으로 변경해도 네이밍 컨벤션을 위반하는게 아닌지, 다른 개발자들이 이 메서드를 봐도 "이건 정적 팩토리 메서드 겠구나!" 라고 인식할지 궁금합니다.

2. 만약 getX에 대해서 말씀하신거라면
Positon 에서는 column, rank 보다는 x, y 라는 이름이 어울리는것 같습니다. 그래서 이 값을 가져오는 메서드 이름에서도 getX, getY로 지어줬습니다. 저는 이 메서드 명은 괜찮다고 생각이 되는데 getColumn, getRank 라는 이름으로 사용하기를 원하시는것인지 궁금합니다!

2024-03-31 04:54 UTC, HaiSeong commented on src/main/java/chess/controller/ChessGameController.java
> +        }
System.out.println 부분을 따로 OutputView 메서드로 만들겠습니다!

2024-03-31 05:15 UTC, HaiSeong commented on src/main/java/chess/controller/ChessGameController.java
> +        }
기존에 있던 로직을 활용해서 만들  수 있을것 같네요!

2024-03-31 05:18 UTC, HaiSeong commented on src/main/java/chess/domain/ChessGame.java
> +    }
좋은것 같습니다. 가독성이 훨신 좋네요!

2024-03-31 05:20 UTC, HaiSeong commented on src/main/java/chess/domain/state/MoveState.java
> +    }
감사합니다!!

2024-03-31 06:41 UTC, HaiSeong commented on src/main/java/chess/domain/state/MoveState.java
> +                .sum();
각 기물이 score를 리턴하면 되겠군요! 좋은 방법인것 같아요. 👍

2024-03-31 06:49 UTC, HaiSeong commented on src/main/java/chess/domain/dto/StatusDto.java
> +}
지금 출력이 흰색의 점수가 출력될 때 검은색의 점수가 같이 출력되니 따로따로 만들지 않고 같이 전송해줬어요.

다른 코드와의 일관성의 측면에서 따로따로 double값을 반환하는 방법을 쓰는것도 좋겠네요.
그리고 이렇게 묶어놓으니 도메인이 view의 로직을 알고있다는 생각도 드는것 같아요.
Color를 인자로 해서 점수를 계산해오는 방식으로 바꾸겠습니다!

2024-03-31 07:14 UTC, HaiSeong commented on src/main/java/chess/view/OutputView.java
>          System.out.println("> 게임 이동 : move source위치 target위치 - 예. move b2 b3");
multiline String 을 지원한다는 사실을 피케이 덕분에 처음 알게되었습니다..!!!
지금까지 왜 아무도 알려주지 않은거죠..? ㅠㅠㅠ
multiline String 사용해서 변경하겠습니다!

2024-03-31 10:23 UTC, HaiSeong commented on src/main/java/chess/repository/MoveDao.java
> +            e.printStackTrace();
적절한 예외메시지 전달하도록 하겠습니다

2024-03-31 10:27 UTC, HaiSeong commented on src/main/java/chess/repository/MoveDao.java
> +    }
#### 이 곳에서만 catch 부분에 final 처리를 한 이유
사실 이전까지 JDBC API를 이용해서 Dao를 만들어본적이 없어서 수업때 다루었던 코드를 이용해서 만들었던 흔적이 남았네요 😅 죄송해요.

#### return null 을 하는 이유
이것도 예제 코드의 내용이긴한데 처음 제출할 당시는 다른 부분에서 예외를 잡아줄것이니 null을 반환해도 뭔가 이상할게 없다고 생각되었던것 같아요. 지금 보니 예외를 잡아줄수 있는 곳도 없고 이상한 코드였네요. 예외를 발생하도록 하겠습니다!

2024-03-31 10:29 UTC, HaiSeong commented on src/main/java/chess/repository/MoveDao.java
> +        try (PreparedStatement statement = connection.prepareStatement(sql)) {
넵 찾아보니 resultSet역시 닫지 않으면 문제가 생기는군요. ry-with-resources를 적용해보겠습니다!

2024-03-31 10:32 UTC, HaiSeong commented on src/main/java/chess/Application.java
> +        MoveRepository moveRepository = new MoveDao();
좋은 답변이 되었었습니다!

2024-03-31 10:45 UTC, HaiSeong commented on build.gradle
> +    runtimeOnly("com.mysql:mysql-connector-j:8.3.0")
세가지 키워드의 차이점을 공부해봤습니다. 지금 상황에서는 dao에 대한 테스트가 없다보니 `mysql-connector-j` 는 런타임에만 사용하면 될것 같다는 생각이 듭니다. 그래서  `runtimeOnly`를 유지하는것으로 했습니다!

2024-03-31 15:49 UTC, HaiSeong commented on src/main/java/chess/controller/ChessGameController.java
> +    public ChessGameController(final InputView inputView, final OutputView outputView, MoveRepository moveRepository) {
감사합니다. 좋은 답변이 된것 같아요.
service를 도입하여 계층은 분리해봤습니다!

2024-03-31 15:51 UTC, HaiSeong commented
테이블명이 변경되어 위에도 추가했지만 다시 올립니다!
```sql
CREATE TABLE movement
(
    source_column      INT CHECK (source_column >= 1 AND source_column <= 8),
    source_rank        INT CHECK (source_rank >= 1 AND source_rank <= 8),
    destination_column INT CHECK (destination_column >= 1 AND destination_column <= 8),
    destination_rank   INT CHECK (destination_rank >= 1 AND destination_rank <= 8)
);
```

2024-04-01 21:39 UTC, pkeugine commented on src/main/java/chess/dto/Move.java
> +}
아 그냥 간단하게 변수명에 underscore 를 사용하지 말자는 리뷰였습니다 😅 
Move 가 record 이다보니 변수명에 따라 메서드명도 만들어져서 메서드도 언급한 것이었구요.

`int source_x, int source_y, int destination_x, int destination_y` 
->
`int sourceX, int sourceY, int destinationX, int destinationY`

리뷰를 남긴 부분에 다른 메서드들이 있어서 의도가 잘못 전달된 것 같네요.

Move 는 명사로 사용되기도 하기 때문에 딱히 이름과 관련된 생각은 없었습니다.

정적 팩토리 메서드 네이밍은 많은 분들이 로키가 남겨주신 `정적 팩토리 메서드 네이밍 컨벤션` 을 따르긴합니다.
하지만 그러면서도 개인마다 이름을 짓는 스타일에 따라서 조금씩 다르기도 해요.
그래서 정말 의미를 알기 힘들다면 리뷰를 남기는 편인데, 이 상황에서 `of` 는 딱히 불편함을 느끼진 않았습니다.

팀 내에서 정적 팩토리 메서드 네이밍 방식에 대해 컨벤션을 만들어 놓는 것을 추천드려요.
'우리는 보편적인 정적 팩토리 메서드 네이밍 방식을 따르자' 라던지, 'of 만 사용하고 그 뒤에 필요한 요소의 이름을 붙여주자. ofNames 처럼.' 이런 식으로 간단하게 정하고 넘어가면 모두가 알아보기 쉬운 이름으로 만들어질거에요. 결국 컨벤션을 명시하는 것이 제일 중요한 것 같네요.

getter 에 대해서도 리뷰를 남길 의도는 없었습니다!

2024-04-01 21:47 UTC, pkeugine commented on src/main/java/chess/repository/MoveDao.java
> +        try (PreparedStatement statement = connection.prepareStatement(sql)) {
필수로 적용하지 않아도 된다고 했는데, [ResultSet 의 javadoc](https://docs.oracle.com/javase/8/docs/api/java/sql/ResultSet.html) 을 확인해보면 다음과 같은 내용이 있습니다 : 

> A ResultSet object is automatically closed when the Statement object that generated it is closed, re-executed, or used to retrieve the next result from a sequence of multiple results.

그래서 Statement 가 닫히면 ResultSet 도 닫히는 구조이긴해요!
물론 개발자가 명시적으로, 원하는 시점에 닫을수도 있지만요.

새로운 클래스를 사용할 땐 그 클래스의 javadoc 을 보면 유용한 정보를 얻을 수 있더라구요 :)

2024-04-01 22:07 UTC, pkeugine requested changes
안녕하세요 로키!
리뷰 잘 반영해주셨네요.
간단한 리뷰 몇 개 더 남겨봤어요.
아직 merge 하기엔 로키가 원하시는 변경사항이 남아있을 듯 하여 request change 로 둘게요.
리뷰와 별개로 질문이 있다면 언제든지 DM 주세요!

2024-04-01 22:07 UTC, pkeugine commented on src/main/java/chess/service/ChessService.java
> +    }
사용되지 않는 메서드가 있어요!

2024-04-01 22:07 UTC, pkeugine commented on src/main/java/chess/service/ChessService.java
> +    }
리팩토링을 하시면서 메서드 순서가 뒤바뀐 것 같아요

2024-04-01 22:07 UTC, pkeugine commented on src/main/java/chess/service/ChessService.java
> +    public ChessService(final MoveRepository moveRepository) {
service 정말 잘 만들어주셨네요 👍

2024-04-01 22:07 UTC, pkeugine commented on src/main/java/chess/repository/MoveRepository.java
> +public interface MoveRepository {
Repository 쪽과 state 쪽에 아직 변경된 이름이 적용되지 않는 곳들이 있어요.

2024-04-01 22:07 UTC, pkeugine commented on src/main/java/chess/dto/Movement.java
> +public record Movement(int source_column, int source_rank, int destination_column, int destination_rank) {
Movement 는 현재 repository 에서 외부에게 (service 에게) data 를 전달할 때 사용되는데요,
dto 패키지를 외부에 두는 것이 아니라 repository 패키지에 두고 사용하는건 어떨까요?

2024-04-02 06:16 UTC, HaiSeong commented on src/main/java/chess/service/ChessService.java
> +    }
앗 수정하겠습니다!

2024-04-02 06:17 UTC, HaiSeong commented on src/main/java/chess/service/ChessService.java
> +    }
논리적 순서대로 바꿔보겠습니다! 전체적으로 확인해볼게요!

2024-04-02 06:18 UTC, HaiSeong commented on src/main/java/chess/service/ChessService.java
> +    public ChessService(final MoveRepository moveRepository) {
🙇‍♂️🙇‍♂️🙇‍♂️

2024-04-02 06:19 UTC, HaiSeong commented on src/main/java/chess/repository/MoveRepository.java
> +public interface MoveRepository {
확인해보겠습니다!

2024-04-02 06:22 UTC, HaiSeong commented on src/main/java/chess/dto/Movement.java
> +public record Movement(int source_column, int source_rank, int destination_column, int destination_rank) {
이 커멘트로 dto 패키지를 어디에 만들지에 대한 기준을 잡을 수 있었습니다!
dto가 계층간 데이터 전달을 목적으로 하니 둘중에 어떤 패키지에 있어야할지 기준이 안잡혔는데
`A에서 B로만 전달한다.` 라는 식이라면 A패키지에 있는게 유리하겠네요.

그렇다면 혹시 dto가 `A에서 B로 전달하고 B에서 C로 전달한다.` 라면 전역적으로 두고 사용해도 되는건가요??

2024-04-02 06:28 UTC, HaiSeong commented on src/main/java/chess/repository/MoveRepository.java
> +public interface MoveRepository {
MoveRepository는 MovementRepository로변경 완료했습니다. 
MoveState는 제가 의도한 이름이라 그대로 두었습니다!

2024-04-02 17:39 UTC, pkeugine commented on src/main/java/chess/dto/Movement.java
> +public record Movement(int source_column, int source_rank, int destination_column, int destination_rank) {
ㅋㅋㅋ 응용 버전인가요!
dto 가 세 개의 레이어에서 사용되는 경우는 그 구조가 괜찮은가 생각해볼 필요도 있을 것 같아요.
참고로 제가 Movement 를 repository 에 두자고 한 이유는 MovementRepository 와 함께 있어야하는 dto 라고 생각했기 때문이에요. (구현체가 아닌 인터페이스 MorementRepository.)

질문에 대한 제 생각을 정말 쉽게 말하면 dto 는 '어떤 레이어에게 주도권을 주고 싶은가' 에 따라서 넣는 위치를 정하면 좋을 것 같아요.
해당 DTO 를 제공하는 레이어 (또는 패키지) 가 정하는 방식대로 다른 레이어 (또는 패키지) 가 따르고, 그 형식에 맞게 데이터를 제공해주거나 데이터를 전달받는거죠. 보통 도메인과 가까운 계층이 아닐까 싶네요. 그런데 쉽게 결정할 수 없으면 전역으로 두고 사용해도 좋다고 생각합니다.

2024-04-02 17:46 UTC, pkeugine approved these changes
안녕하세요 로키, 체스 미션 고생 많으셨어요!
service 도입하는 고민과 그 과정도 그렇고, 전체적으로 리뷰하면서 꽤나 재밌었어요 :)
이번에 시도해본 경험을 통해 방학 후 미션에서 많은 것을 더 얻어가셨으면 좋겠습니다.
추가로 반영하고자 하는 내용을 다 올려주신 것 같아서 체스는 이만 머지하도록 할게요.
방학 재밌게 보내시고, 다음 레벨에서도 파이팅입니다!

2024-04-02 17:46 UTC, merged