[체스 - 3, 4 단계] 폭포(이성주) 미션 제출합니다.
woowacourse/java-chess pull request #760
Opened 2024-03-29 16:50 UTC by BurningFalls

안녕하세요 제이! 폭포입니다.

체스 미션 3, 4단계 구현 마쳐 PR 보냅니다.

리뷰 부탁드립니다. 감사합니다.

---

## A. 1, 2단계 추가 리팩토링

1, 2단계에서 `Command` 클래스를 생성한 것에서 더 나아가, 커맨드 관련 모든 로직을 관리하는 클래스인 `CommandLogger` 클래스를 생성했습니다. 얻은 장점은 다음과 같습니다.

* `CommandLogger`가 커맨드 관련 로직을 처리 -> `Controller`의 역할 감소 + 클래스간의 적절한 책임 분배
* `Controller`의 역할 감소 -> `Controller` 코드의 가독성 향상
* `CommandLogger`가 커맨드 순서를 알고 있음 -> 게임 종료 판단 가능 + 커맨드 순서 오류 판단 가능
* 커맨드가 추가되더라도 `CommandLogger` 클래스에서 간단히 처리 가능 -> 확장성과 유연성 향상

이 리팩토링을 전부 진행하고 3, 4단계를 돌입했다보니, `status`, `load`, `save` 명령어들을 매우 쉽게 문제없이 추가할 수 있어서 엄청 뿌듯했습니다. 

## B. 3단계 진행

> "status" 명령을 입력하면 각 진영의 점수를 출력하고 어느 진영이 이겼는지 결과를 볼 수 있어야 한다.

`status` 명령어를 입력하면, 아래 예시와 같이 각 진영의 점수를 출력하고 어느 진영이 이겼는지 결과를 보여주고, 게임은 계속 진행됩니다.

```
BLACK 팀 점수: 36.0
WHITE 팀 점수: 38.0
이긴 진영: WHITE 팀
```

> King이 잡혔을 때 게임을 종료해야 한다.

King이 잡히면 게임을 종료하도록 구현했습니다. 아래는 킹이 잡히는 기보입니다.

```
move f2 f4
move e7 e5
move a2 a3
move d8 h4
move a3 a4
move h4 e1
```

## C. 4단계 진행 - 필수 요구사항

`docker 실행`, `piece 테이블 생성`, `chess_room 테이블 생성` 코드는 `README.md`에 기록해놓았습니다.

> 애플리케이션을 재시작하더라도 이전에 하던 체스 게임을 다시 시작할 수 있어야 한다.

다음과 같이 `load`와 `save`를 구현했습니다.

* `load` -> 입력 시 현재 게임 진행 상황(보드와 턴)을 저장한다.
* `save` -> 마지막으로 저장한 게임 진행 상황(보드와 턴)을 불러온다.
* `save`는 게임 진행 중 언제든지 가능하지만, `load`는 처음 시작할 때만 가능하다.
* 시작할 때, `start`(새로운 게임 시작)와 `load`(저장한 게임 불러오기) 둘 중 하나를 선택한다.

## D. 4단계 진행 - 기초 부족

DB 설계 및 도메인 로직과의 연결 코드 작성 실력이 굉장히 부족하여 엄청 헤맸고, 결과적으로 TDD를 제대로 하지 못했고 테스트도 부실하며 Commit도 세부 구현으로 명확히 나누지 못했습니다. 기초를 배우는 단계라고 생각해서 가장 단순한 설계를 만들었고, 이 코드에 대해서 리뷰를 받고 싶습니다. 제 부족한 실력을 인정하고 한정된 시간을 계산하여 아직 심화 단계를 나아갈 수준이 아니라고 판단했습니다. 

## E. 4단계 진행 - 테이블 설계

* 필수 요구사항만 봤을 때 체스 방이 하나만 존재하기 때문에, 현재 모든 코드에서는 `CHESS_ROOM_ID`를 `1`로 고정시킨채로 구현되어 있습니다.
* 필수 요구사항만 구현하면 `piece` 테이블에 `chess_room_id`가 필요없기는 하지만, 나중에 방학 때라도 선택 요구사항을 구현할 때 체스 방이 더 생길 것을 고려해서 해당 애트리뷰트를 만들어두었습니다.
* `chess_room_id`와 `piece_id`를 갖는 중간 테이블을 만들어 `piece` 테이블에서의 `chess_room_id` 애트리뷰트의 중복을 없애는 방법이 있다는 것을 인지했습니다. 하지만 제가 아직 기초적인 부분이 많이 부족하고 피드백 받을 부분이 많다고 생각해서, 심화학습까지 한 번에 진행하지 않았습니다. 이 부분도 방학 때 추가로 해볼 생각입니다.
* 위와 같은 방법은 데이터 중복은 줄일 수 있으나 데이터 조회의 복잡성 증가라는 명확한 트레이드오프가 존재합니다. 실제 DB를 설계할 때는 이를 고려해야 하지만, 지금 구현하는 체스 게임에서는 큰 차이가 없기 때문에 '학습'의 의미로 시도할 가치는 충분하다고 생각합니다.

## F. 1, 2단계 리뷰 공부

> 타입관련해서 코멘트 남겨드린부분은 정리하셔서 다음번 미션 진행하실때 첨부해주시면 더 좋을거같아요~

자바에 대해서 깊이있는 공부를 하지 않은 상태에서 시작했다보니, 객체지향의 다형성에 대해서 모르고 있었습니다. 지금까지 자연스럽게 사용해온 인터페이스와 추상 클래스를 비롯한 것들과 제가 하게 된 고민들, 짚어주신 부분에 대한 해답이 전부 다형성에 담겨 있었네요. 이번 기회에 공부하면서 확실하게 정리할 수 있었습니다. 정말 감사합니다! 🙇

"자바의 정석" 책을 읽고 다형성에 대해서 학습한 내용을 제 블로그에 정리해봤습니다.

[[Java] 객체지향에서 다형성(Polymorphism)이란?](https://burningfalls.github.io/java/what-is-polymorphism/)

아래는 제 미션에서 실제로 다형성의 이점을 이용한 코드입니다. 상위 타입을 리턴함에 따라, 추상클래스에서 공통 함수로 묶을 수 있게 되었습니다. (추상화 수준 향상)

> 원래는 코드가 변화한 모습을 하나의 커밋(ex. `refactor: 다형성 적용`)으로 보여드려야 하지만, git을 잘못 건드리는 바람에 conflict를 수동으로 해결하면서 변경했던 모든 복잡한 사항을 한 커밋에 담아버릴 수밖에 없었습니다. 그래서 부득이하게 직접 코드로 보여드리는 점 양해부탁드립니다.

```java
// 다형성 적용 전
public class Bishop extends ChessPiece {
    // ...
    @Override
    public Bishop move(Position newPosition, boolean isObstacleInRange, boolean isOtherPieceExist, boolean isSameTeamExist) {
        if (isMoveInvalid(newPosition, isObstacleInRange, isOtherPieceExist, isSameTeamExist)) {
            return this;
        }

        PieceInfo newPieceInfo = pieceInfo.renewPosition(newPosition);
        return new Bishop(newPieceInfo, moveStrategy);
    }
}
public class King extends ChessPiece {
    // ...
    @Override
    public King move(Position newPosition, boolean isObstacleInRange, boolean isOtherPieceExist, boolean isSameTeamExist) {
        if (isMoveInvalid(newPosition, isObstacleInRange, isOtherPieceExist, isSameTeamExist)) {
            return this;
        }

        PieceInfo newPieceInfo = pieceInfo.renewPosition(newPosition);
        return new King(newPieceInfo, moveStrategy);
    }
}
```

```java
// 다형성 적용 후
public abstract class ChessPiece implements Piece {
    // ...
    @Override
    public ChessPiece move(Position newPosition, boolean isObstacleInRange, boolean isOtherPieceExist, boolean isSameTeamExist) {
        if (isMoveInvalid(newPosition, isObstacleInRange, isOtherPieceExist, isSameTeamExist)) {
            return this;
        }

        PieceInfo newPieceInfo = pieceInfo.renewPosition(newPosition);
        return createNewPiece(newPieceInfo);
    }

    @Override
    public abstract ChessPiece createNewPiece(PieceInfo newPieceInfo);
}

public class Bishop extends ChessPiece {
    // ...
    @Override
    public ChessPiece createNewPiece(PieceInfo newPieceInfo) {
        return new Bishop(newPieceInfo, moveStrategy);
    }
}
public class King extends ChessPiece {
    // ...
    @Override
    public ChessPiece createNewPiece(PieceInfo newPieceInfo) {
        return new King(newPieceInfo, moveStrategy);
    }
}
```

2024-03-31 10:12 UTC, JunHoPark93 requested changes
안녕하세요 폭포~
마지막 단계 구현하느라 고생많으셨습니다.
코멘트 몇가지 남겨드렸는데 구조관련한부분, 테스트코드, db접근부분 위주로 봐주시면 좋을거같아요.

2024-03-31 10:12 UTC, JunHoPark93 commented on docker/db/mysql/data/binlog.index
> +./binlog.000001
db local파일들도 같이 업로드가 되었는데 필요한 것들 아니면 버전관리에서 제외시켜주세요. 
key파일들도 들어가있는거같아요.

2024-03-31 10:12 UTC, JunHoPark93 commented on src/main/java/chess/controller/ChessGameController.java
> +public class ChessGameController {
> 현재는 ChessGameController라는 하나의 컨트롤러에서 게임의 전반적인 흐름과 체스 게임의 세부적인 규칙을 전부 관리하고 있습니다. 그런데 이 역할을 분리해서 ChessController와 GameController 두 개의 컨트롤러로 만들면 어떨까? 하는 생각이 들었습니다.
> 제가 생각해본 장단점은 다음과 같습니다.
> 장점: 컨트롤러의 책임과 역할을 분산시켜 SRP를 만족시킬 수 있다. 이는 확장성과 유지보수성에 도움을 준다.
> 단점: GameController에서 ChessService를 가지고 있어 이를 사용해서 게임 정보를 load하면, load 해온 board 객체를 ChessController에 넘기는 과정이 필요해진다. 이를 main에서 처리하거나 Facade pattern으로 하나로 묶게 되면, 결국 하나의 컨트롤러에서 처리하는 것과 다를 바가 없어지는 것 같다.
> 이에 대해서 제이는 어떻게 생각하는지 제이의 의견과 조언을 듣고 싶습니다.

굳이 안나눠도 될거같아요. 혹시 makeBoard 같은 로직을 세부적인 규칙을 담당하는 부분이라고 봐주신걸까요?
이런부분들은 컨트롤러의 역할이라기보다 유틸리성 메서드로 따로 관리가 되는게 더 맞을거같기도해요. 분리가 필요하다면 이런 세부로직들을 나눠보는 시도를 해보시는게 더 좋을거같습니다.

2024-03-31 10:12 UTC, JunHoPark93 commented on src/main/java/chess/controller/ChessGameController.java
> +    private Team turn;
인스턴스변수 개수 규칙을 지켜볼까요?

2024-03-31 10:12 UTC, JunHoPark93 commented on src/main/java/chess/controller/ChessGameController.java
> +    private Team turn;
위에 질문주신 부분과도 연관이 있을거같아요. 
ChessService를 보면 dao클래스 2개를 가지고있어서 데이터를 가져오는 역할을 주로 담당하고있어요. 컨트롤러와 정의해주신 ChessService 사이에 한 레이어를 더 둬야 적절히 나눠볼 수 있을거같은데 어떻게 생각하실까요?

2024-03-31 10:12 UTC, JunHoPark93 commented on src/main/java/chess/domain/command/CommandLogger.java
> +    }
logger를 만들어주셨는데 내부에 리스트로 계속 관리되도록 유지하신게 의도하신걸까요?

2024-03-31 10:12 UTC, JunHoPark93 commented on src/main/java/chess/domain/board/Board.java
> +    private void renewBoard(Piece movedPiece, Position source, Position target) {
보드를 초기화하는것이 아닌 특정 position의 기물들을 다루는것이니 적절한 이름으로 바꿔볼까요?

2024-03-31 10:12 UTC, JunHoPark93 commented on src/main/java/chess/domain/board/Board.java
> +    private final DeadPieces deadPieces;
👍🏼
구현하기나름이라 답은없지만 개인적으로 보드가 죽은 기물을 관리하는것이 게임진행여부를 결정하는데 필요한 역할이라고 생각합니다. 복잡한 로직을 통해서 계산한분들이 많던데.. 잘해주셨네요.

2024-03-31 10:12 UTC, JunHoPark93 commented on src/main/java/chess/domain/board/Board.java
> +    }
👍🏼

2024-03-31 10:12 UTC, JunHoPark93 commented on src/main/java/chess/domain/board/Board.java
> +                .map(Map.Entry::getValue)
getFileIndex보다 Position에 질의를 해보면 어떨까요?

2024-03-31 10:12 UTC, JunHoPark93 commented on src/test/java/chess/domain/board/LivePiecesInFileTest.java
> +    @Test
테스트들도 잘 작성해주셨어요.
다만 폰 외에 다른 경우도들도 몇 개 더 있으면 좋을거같아요~

2024-03-31 10:12 UTC, JunHoPark93 commented on src/main/java/chess/domain/command/CommandType.java
> +                .orElseThrow(() -> new IllegalArgumentException("존재하지 않는 커맨드 타입입니다."));
인자인 command도 같이 찍어주면 예외추적에 유리합니다

2024-03-31 10:12 UTC, JunHoPark93 commented on src/main/java/chess/domain/dao/ChessRoomDao.java
> +    }
자동증가컬럼을 다시 초기화할 필요가 있을까요?
적절한 컬럼이 맞는지 다시 생각해보면 좋을거같아요.

2024-03-31 10:12 UTC, JunHoPark93 commented on src/main/java/chess/controller/ChessGameController.java
> +            turn = chessService.loadTurn();
load할때 id값이 없네요. 
무조건 1개만 존재할거라는 가정이 있어서 그렇게 만들어주신거같은데요, 내부의 하드코딩된 id를 사용하는게 아니라 로드시점에 id를 같이 넘겨주세요~

2024-03-31 10:12 UTC, JunHoPark93 commented on src/main/java/chess/controller/ChessGameController.java
> +            turn = chessService.loadTurn();
다수의 방에 대한기능은 추가요구사항이지만 추가요구사항을 반영한다고 가정했을때 지금 어떻게 만들어놓는게 좋을지 고민해보시면 좋을거같아요.

2024-03-31 10:12 UTC, JunHoPark93 commented on src/main/java/chess/domain/dao/ChessRoomDao.java
> +            throw new RuntimeException(e);
예외가 발생했을때 어떻게 될까요?
제일 상위의 호출부중에서 아래 작업중 하나만 성공하고 하나는 실패할경우에 어떻게 처리하면 좋을지 생각해보시면 좋을거같아요.
```
chessService.saveData(board);
chessService.saveTurn(turn);
```
여력이 되면 살펴봐주시고 꼭 개선해보지 않아도 좋습니다.

2024-03-31 10:12 UTC, JunHoPark93 commented on src/main/java/chess/domain/dao/ChessRoomDao.java
> +            return null;
null반환은 최대한 지양해주세요

2024-03-31 10:12 UTC, JunHoPark93 commented on src/main/java/chess/service/ChessService.java
> +public class ChessService {
테스트가 아예없네요. 전체적으로 확인주시고 테스트도 추가부탁드릴게요~

2024-03-31 10:12 UTC, JunHoPark93 commented on src/main/java/chess/service/ChessService.java
> +        pieces.values().stream()
save메서드안에 deleteAll이 숨겨져있네요.

테이블 모든 데이터를 전부 delete하는 기능인데 이러한 기능이 save메서드에 숨겨져있으면 매우 위험합니다. 의도가 잘 드러나게 개선하려면 어떻게 해야할까요?

2024-03-31 10:50 UTC, BurningFalls commented on docker/db/mysql/data/binlog.index
> +./binlog.000001
지금까지 `gitignore`에 무언가를 추가할만한 상황이 없었다보니 깜빡 잊고 있었네요. 크리티컬한 파일들이 올라가지 않도록 더 신경써야할 것 같습니다.

`git rm --cached -r docker/db`를 실행해서 github에서 해당 파일들을 삭제하고,
`.gitignore`에 `docker/db`를 추가해서 git 변경사항에 추가되지 않도록 막았습니다.

2024-03-31 11:03 UTC, BurningFalls commented on src/main/java/chess/controller/ChessGameController.java
> +public class ChessGameController {
다른 컨트롤러를 만들기 보다는 유틸리티 클래스로의 분리가 필요하다는 말씀이군요, 조언 감사합니다!

2024-03-31 12:45 UTC, BurningFalls commented on src/main/java/chess/controller/ChessGameController.java
> +    private Team turn;
와 안그래도 저 부분 때문에 고민 중이었어요. 그래서 컨트롤러를 두 개 만들어야 하나 생각 중이었는데, 파사드 패턴을 여기에 적용하면 깔끔하게 해결이 되네요!

`ChessGameController`와 `ChessService` 사이에 `ChessGame` 인터페이스를 두어 게임 관련 로직 처리를 하게 만들었습니다. 각 클래스가 적절하게 책임과 역할이 분리된 것 같아서 매우 기분이 좋네요. 감사합니다.

2024-03-31 12:50 UTC, BurningFalls commented on src/main/java/chess/domain/command/CommandLogger.java
> +    }
명령어를 입력한 적이 있는지 확인하는 기능과 가장 마지막 명령어가 무엇인지 확인하는 기능만 있다면, 리스트로 만들 필요 없이 하나의 `Command`만 저장해서 계속 덮어씌워도 해당 기능들이 구현 가능하긴 합니다.

하지만 명령어가 추가되고 기능 명세서를 어떻게 해석하느냐에 따라서, 명령어 간의 순서 파악이 필요해지거나(이전 명령어가 무엇인지 알아야 하는 경우) 다른 복잡한 조건들이 얼마든지 추가될 수 있음을 인지하고 `List<Comand>`로 관리되도록 의도했습니다.

2024-03-31 13:11 UTC, BurningFalls commented on src/main/java/chess/domain/board/Board.java
> +    private void renewBoard(Piece movedPiece, Position source, Position target) {
메서드명이 메서드의 동작을 명확하게 표현하고 있지 않네요. 아래와 같이 명확한 네이밍의 두 메서드로 분리해서 작성했습니다.

```java
removePieceAtSource(source);
placePieceAtTarget(movedPiece, target);
```

2024-03-31 13:18 UTC, BurningFalls commented on src/main/java/chess/domain/board/Board.java
> +    private final DeadPieces deadPieces;
처음 시도했던 건 `movePiece` 메서드가 죽은 기물(`Piece`)를 반환하는 방법이었습니다. 그러나 막상 코드를 작성해보니, 메서드를 타고 세 번이나 밖으로 나가는 과정에서 반환 값을 전달하기 위해 계속 return을 해주어야 했고, 반환값을 받아서 처리하는 로직까지 추가되어 코드가 너무 보기 싫어졌습니다. 그래서 전부 롤백했습니다.

두 번째 시도한 방법은 `livePieces`를 관리하는 방법이었습니다. 이 방법도 실제로 구현해보고 나서야 문제점을 발견했는데, `livePieces`에서 킹이 살아있는 것을 확인하는 건 쉽지만, 죽은 말을 제거하는 과정의 시간복잡도가 너무 높고 로직이 복잡했습니다. 그래서 또 전부 롤백했습니다.

그러고 나서야 `deadPieces`를 관리하는 방법을 떠올렸습니다. `deadPieces`는 단순히 말을 더해주기만 하면 됐기 때문에 `livePieces`를 관리하는 것보다 훨씬 수월하고 시간복잡도도 낮았습니다. 반환값을 이용하는 방법처럼 외부 코드를 변화시킬 필요성도 전혀 없었습니다. 그래서 결론적으로 이 방법을 선택하게 되었습니다.

2024-03-31 13:27 UTC, BurningFalls commented on src/main/java/chess/domain/board/Board.java
> +                .map(Map.Entry::getValue)
`position`의 `fileIndex` 값을 꺼내서 원하는 값인지 확인하는 방식으로, `getter` 지양에 위배되는 코드를 작성해버렸네요. `Position` 클래스 내부에 아래 메서드를 만들어서 수정했습니다.

```java
public boolean isCorrectFile(int fileIndex) {
    return file.getIndex() == fileIndex;
}
```

2024-03-31 13:44 UTC, BurningFalls commented on src/main/java/chess/domain/command/CommandType.java
> +                .orElseThrow(() -> new IllegalArgumentException("존재하지 않는 커맨드 타입입니다."));
* 체스 2단계 에러 메시지: `커맨드 타입은 start, end, move 중 하나여야 합니다.`
* 체스 3단계 에러 메시지: `커맨드 타입은 start, end, move, status 중 하나여야 합니다.`
* 체스 4단계 에러 메시지: `커맨드 타입은 start, end, move, status, load, save 중 하나여야 합니다.`

체스 단계를 진행할 때마다 에러 메시지가 다음과 같이 변화했습니다. 그래서 에러 메시지의 유연성이 없다고 생각해서 `존재하지 않는 커맨드 타입입니다.`로 통일시켜 버린 기억이 납니다.

그래서 사용자 편의성을 위해 모든 에러 메시지를 출력해주면서도 동시에 유연성도 챙기기 위해서, 아래와 같이 모든 enum string을 이어붙여서 리턴하는 메서드를 만들어 이용하는 방식으로 수정했습니다.

```java
new IllegalArgumentException("커맨드 타입은 " + getCommandTypes() + " 중 하나여야 합니다.")

private static String getCommandTypes() {
    return Arrays.stream(CommandType.values())
            .map(CommandType::get)
            .collect(Collectors.joining(", "));
}
```

2024-04-01 00:04 UTC, BurningFalls commented on src/main/java/chess/controller/ChessGameController.java
> +            turn = chessService.loadTurn();
`chess_room_id`를 `Application`에서 사용자 입력을 받는다고 가정하고, 전체적인 코드를 수정했습니다. 변경된 사항은 다음과 같습니다.

* `ChessService`가 필드로 `chess_room_id`를 저장
* `PieceDao`와 `ChessRoomDao`의 CRUD 메서드에 `chess_room_id` 파라미터를 전달하여 SQL 쿼리문 수행
* `chess_room` 테이블의 `id` 애트리뷰트 `AUTO INCREMENT` 삭제
* `ChessRoomDao`의 `setAutoIncrementToOne` 메서드 삭제
* `ChessRoomDto`에 `id` 필드 추가
* `PieceDto`의 `chess_room_id` 필드 삭제

2024-04-01 00:06 UTC, BurningFalls commented on src/main/java/chess/domain/dao/ChessRoomDao.java
> +    }
아래에서 `chess_room_id`를 파라미터로 넘겨받게 바꿈에 따라, 한 번에 수정했습니다.

2024-04-01 00:17 UTC, BurningFalls commented on src/main/java/chess/domain/dao/ChessRoomDao.java
> +            throw new RuntimeException(e);
세상에 `saveTurn`에서 에러가 나면, data 저장만 성공해버리는 꽤나 크리티컬한 에러가 발생하네요. 전혀 인지하지 못했습니다.

조사해본 결과 이를 해결하기 위해서는 트랜잭션 처리가 필요하다고 하는데, 제대로 공부한 뒤 나중에 개선해보아야 할 것 같습니다. 추가로 공부해야할 부분을 알려주셔서 감사합니다!

2024-04-01 00:38 UTC, BurningFalls commented on src/main/java/chess/domain/dao/ChessRoomDao.java
> +            return null;
`null` 대신 예외를 던지게 수정했습니다. `ChessRoomDao`의 READ 함수를 바꿈에 따라, 마찬가지로 `PieceDao`의 READ 함수도 바꾸었습니다.

```java
// ChessRoomDao.java
if (resultSet.next()) {
    return resultSet.getString("turn");
}
throw new NoSuchElementException("ID에 해당하는 턴을 찾을 수 없습니다: " + id);
```

```java
// PieceDao.java
if (pieceDtos.isEmpty()) {
    throw new NoSuchElementException("ID에 해당하는 피스가 없습니다: " + chess_room_id);
}
```

```java
// ChessRoomController.java
private void playGame() {
    try {
        play();
    } catch (IllegalArgumentException | NoSuchElementException e) {
        OutputView.printErrorMessage(e.getMessage());
    }
}
```

2024-04-01 01:06 UTC, BurningFalls commented on src/main/java/chess/service/ChessService.java
> +        pieces.values().stream()
협업 관점에서 볼때, 다른 사람이 데이터를 저장하고 싶어서 `saveData` 함수의 내부 구현을 보지 않고 (당연히 데이터를 저장하는 함수겠지 생각하고) 그냥 가져다 써버리면, 의도치 않았는데 피스의 데이터들이 삭제돼버리는 위험한 상황이 발생할 수 있다는 의미군요! 생각해보지 못했습니다.

데이터를 삭제하는 함수와 데이터를 저장하는 함수를 분리시켜서, 외부에 명확하게 의미를 노출시키도록 수정했습니다.

```java
public void saveData() {
    chessService.savePieces(board);
    chessService.saveTurn(turn);
}

public void deleteData() {
    chessService.deletePieces();
}
```

2024-04-01 01:36 UTC, BurningFalls commented
안녕하세요, 제이!

상세한 리뷰 감사합니다. 

덕분에 제가 놓치고 있었던 부분은 무엇인지, 다시 생각해볼 부분은 무엇인지, 앞으로 공부해야할 부분은 무엇인지에 대해 알 수 있었습니다. 😄 

몇 가지 추가로 말씀드리고 싶은 부분들은 아래에 기입했습니다.

---

## 테스트 코드의 부실함

이번에 처음으로 DB 설계 및 관련 프로덕션 코드를 작성해봐서 이를 수행하는 것만 해도 상당히 헤맬 수 밖에 없었습니다. 그래서 어쩔 수 없이 아직 실력이 부족함을 인정하고, DB 로직과 관련된 코드는 TDD를 포기한채로 프로덕션 코드를 작성했습니다. 그러다보니 테스트가 매우 부실해졌습니다. 거기에 PR을 받을 수 있는 마감기한을 고려해 보았을 때, 테스트 코드까지 작성하는 건 무리가 있어보여 `Service`에 대한 테스트 코드 부분을 포기한 바 있습니다.

프로덕션 코드에서 제가 개선해나가야 할 부분들을 중점적으로 알고 싶어서, 그리고 PR을 받을 수 있는 정해진 시간을 최대한 효율적으로 활용하고 싶어서 테스트 코드 작성은 비교적 뒤로 미루게 되었습니다. 오늘이 마감일이기 때문에 이번에도 테스트 코드 작성까지는 가지 못할 것 같습니다. 그래도 리뷰 요청을 보내고 나서도 오늘의 남는 시간동안은 최대한 노력해서 계속 부족한 테스트 코드를 작성할 예정입니다. 테스트 코드 추가에 대한 reply를 반영하지 못한 점 죄송합니다.

## Review Reply 소프트 스킬에 대해 궁금한 점

리뷰를 받고 답을 보낼 때, 지금까지 저는 코드가 어떤 식으로 변화했는지 대략적으로 코드 블럭으로 적어서 제출하곤 했습니다. 그러다가 문득 어차피 커밋 기록으로 볼 수 있기 때문에 이게 과연 의미가 있는 행동일까에 대한 의문이 생겼습니다. 리뷰어분의 입장에서 리뷰이가 어떤 식으로 답글을 다는 것이 편하신지, Reply 메시지를 개선한다면 어떤 방향으로 개선할 수 있을지에 대한 조언을 듣고 싶습니다.

## ChessService가 필드로 chess_room_id를 갖고 있는 것에 대한 의문점

```java
public class ChessService {
    private final Long chess_room_id;
    private final PieceDao pieceDao;
    private final ChessRoomDao chessRoomDao;
    // ...
}
```

`chess_room_id`를 사용자에게 입력받는다고 가정한채로 코드를 수정하게 되면서, `ChessService`가 필드로 `chess_room_id`를 갖게 되었습니다. `dao`의 여러 메서드들을 사용함에 있어 해당 변수가 여러 번 필요하기 때문에 필드로 갖고 있으면 편해서 다음과 같이 코드를 작성했습니다. 하지만 객체지향적으로 생각해보았을 때(클래스가 적절한 책임과 역할을 갖고 있는가), 과연 이것이 어색하지 않은가에 대해서는 확답을 내리지 못하겠는 상황입니다. 만약 어색하다면 어떤 식으로 바꾸어야 맞는지도 더 생각나는 방향이 없습니다.

또한 그럴 설계가 생길지는 모르겠지만, 사용자 입력이 `chess_room_id` 뿐만 아니라 더 많다면 예를 들어 세 개라면, `ChessService`에 그 입력을 전부 필드로 저장하게 되면 필드의 개수가 또 너무 많아질 것 같습니다. 이를 해결할 수 있는 방법 또는 방향성에 대해 알고 싶습니다.

2024-04-01 01:38 UTC, BurningFalls commented on src/main/java/chess/service/ChessService.java
> +public class ChessService {
테스트 코드에 대한 부분은 아래 코멘트에 작성했습니다.

2024-04-01 01:38 UTC, BurningFalls commented on src/test/java/chess/domain/board/LivePiecesInFileTest.java
> +    @Test
테스트 코드에 대한 부분은 아래 코멘트에 작성했습니다.

2024-04-01 07:04 UTC, BurningFalls commented
안녕하세요, 제이!

상세한 리뷰 감사합니다. 

덕분에 제가 놓치고 있었던 부분은 무엇인지, 다시 생각해볼 부분은 무엇인지, 앞으로 공부해야할 부분은 무엇인지에 대해 알 수 있었습니다. 😄 

몇 가지 추가로 말씀드리고 싶은 부분들은 아래에 기입했습니다.

---

## DB 테이블 변경 사항

```
USE chess;

CREATE TABLE chess_room (
    id BIGINT NOT NULL,
    turn VARCHAR(10) NOT NULL,

    PRIMARY KEY (id)
);
```

`chess_room` 테이블의 `id`의 `AUTO_INCREMENT` 속성을 삭제했습니다. 제 코드를 다시 실행시키는 경우, 테이블 상태 변경이 필요합니다.

## Review Reply 소프트 스킬에 대해 궁금한 점

리뷰를 받고 답을 보낼 때, 지금까지 저는 코드가 어떤 식으로 변화했는지 대략적으로 코드 블럭으로 적어서 제출하곤 했습니다. 그러다가 문득 어차피 커밋 기록으로 볼 수 있기 때문에 이게 과연 의미가 있는 행동일까에 대한 의문이 생겼습니다. 리뷰어분의 입장에서 리뷰이가 어떤 식으로 답글을 다는 것이 편하신지, Reply 메시지를 개선한다면 어떤 방향으로 개선할 수 있을지에 대한 조언을 듣고 싶습니다.

## ChessService가 필드로 chess_room_id를 갖고 있는 것에 대한 의문점

```java
public class ChessService {
    private final Long chess_room_id;
    private final PieceDao pieceDao;
    private final ChessRoomDao chessRoomDao;
    // ...
}
```

`chess_room_id`를 사용자에게 입력받는다고 가정한채로 코드를 수정하게 되면서, `ChessService`가 필드로 `chess_room_id`를 갖게 되었습니다. `dao`의 여러 메서드들을 사용함에 있어 해당 변수가 여러 번 필요하기 때문에 필드로 갖고 있으면 편해서 다음과 같이 코드를 작성했습니다. 하지만 객체지향적으로 생각해보았을 때(클래스가 적절한 책임과 역할을 갖고 있는가), 과연 이것이 어색하지 않은가에 대해서는 확답을 내리지 못하겠는 상황입니다. 만약 어색하다면 어떤 식으로 바꾸어야 맞는지도 더 생각나는 방향이 없습니다.

또한 그럴 설계가 생길지는 모르겠지만, 사용자 입력이 `chess_room_id` 뿐만 아니라 더 많다면, `ChessService`에 그 입력을 전부 필드로 저장하게 되면 필드의 개수가 또 너무 많아질 것 같습니다. 이를 해결할 수 있는 방법 또는 방향성에 대해 알고 싶습니다.

2024-04-02 01:14 UTC, JunHoPark93 commented on docker/db/mysql/data/binlog.index
> +./binlog.000001
넵 관련 내용들은 한번 올라갔으면 전부 삭제해서 재 생성해주시면 됩니다

2024-04-02 01:17 UTC, JunHoPark93 commented on src/main/java/chess/domain/command/CommandLogger.java
> +    }
단순 로그의 의미를 두신게 아니었군요, (참고만해주세요!) 메모리에서 관리됐을때 어떤 문제가 있을지 차차 고민해보시면 좋을거같아요.

2024-04-02 01:17 UTC, JunHoPark93 commented on src/main/java/chess/domain/board/Board.java
> +    private final DeadPieces deadPieces;
잘하셨습니다!

2024-04-02 01:18 UTC, JunHoPark93 commented on src/main/java/chess/domain/command/CommandType.java
> +                .orElseThrow(() -> new IllegalArgumentException("존재하지 않는 커맨드 타입입니다."));
잘하셨습니다. 습관을 들이시면 나중에 프로젝트가 점점 커질때 예외메세지를 보고 원인 추적하는데 수월하실거에요!

2024-04-02 01:18 UTC, JunHoPark93 commented on src/main/java/chess/domain/dao/ChessRoomDao.java
> +            throw new RuntimeException(e);
넵 이부분은 다음 레벨때 공부해두시면 도움많이되실거에요!

2024-04-02 01:21 UTC, JunHoPark93 commented on src/main/java/chess/service/ChessService.java
> +        pieces.values().stream()
의도치 않은 삭제와 생각했던 개수이상의 쿼리가 날아가는 등의 여파가 있기때문에 잘 수정해주셨습니다

2024-04-02 01:31 UTC, JunHoPark93 commented
> Review Reply 소프트 스킬에 대해 궁금한 점
> 리뷰를 받고 답을 보낼 때, 지금까지 저는 코드가 어떤 식으로 변화했는지 대략적으로 코드 블럭으로 적어서 제출하곤 했습니다. 그러다가 문득 어차피 커밋 기록으로 볼 수 있기 때문에 이게 과연 의미가 있는 행동일까에 대한 의문이 생겼습니다. 리뷰어분의 입장에서 리뷰이가 어떤 식으로 답글을 다는 것이 편하신지, Reply 메시지를 개선한다면 어떤 방향으로 개선할 수 있을지에 대한 조언을 듣고 싶습니다.
> 

리뷰어입장에서는 
1. 해당 라인에 코멘트를 달거나
2. 코드블럭을 적거나

이 두가지중 하나면 충분합니다. 저는 1번을 더 선호하긴합니다. 1번은 해당 부분에 스레드를 계속 이어갈 수 있다는장점이 있고(pr 플러그인쓰시는분들은 ide에서 바로볼수도있구요) 2번으로 했을때는 해당부분을 찾아서 코멘트를 남기는 작업이 추가로 들기때문입니다. 그리고 1번으로했을때 나중에 리뷰이분들이 보시기에도 최초질문부터 스레드가 존재하기때문에 더 편하실거에요.

2024-04-02 01:34 UTC, JunHoPark93 commented
> ChessService가 필드로 chess_room_id를 갖고 있는 것에 대한 의문점
> public class ChessService {
>     private final Long chess_room_id;
>     private final PieceDao pieceDao;
>     private final ChessRoomDao chessRoomDao;
>     // ...
> }
> chess_room_id를 사용자에게 입력받는다고 가정한채로 코드를 수정하게 되면서, ChessService가 필드로 chess_room_id를 갖게 되었습니다. dao의 여러 메서드들을 사용함에 있어 해당 변수가 여러 번 필요하기 때문에 필드로 갖고 있으면 편해서 다음과 같이 코드를 작성했습니다. 하지만 객체지향적으로 생각해보았을 때(클래스가 적절한 책임과 역할을 갖고 있는가), 과연 이것이 어색하지 않은가에 대해서는 확답을 내리지 못하겠는 상황입니다. 만약 어색하다면 어떤 식으로 바꾸어야 맞는지도 더 생각나는 방향이 없습니다.
> 
> 또한 그럴 설계가 생길지는 모르겠지만, 사용자 입력이 chess_room_id 뿐만 아니라 더 많다면, ChessService에 그 입력을 전부 필드로 저장하게 되면 필드의 개수가 또 너무 많아질 것 같습니다. 이를 해결할 수 있는 방법 또는 방향성에 대해 알고 싶습니다.

반대로 여쭤볼게요.
종류가 아니라 사용자가 많아지면 어떻게 될까요? ChessService를 여러 사용자가 사용할 수 있을까요?

제가 바로 답을 알려드리는것보다 이부분고민해보고 스스로 답을 내서 (결론을 짓지 못하고 중간 답만 내도 좋습니다) 저한테 dm주세요. 이 부분은 앞으로도 중요한 부분이라 직접 고민해보시는것이 훨씬 도움이 될거에요!

2024-04-02 01:37 UTC, JunHoPark93 approved these changes
안녕하세요 폭포~
리뷰 반영하시느라 고생많으셨습니다.
답을 다 알려드리지 않은 부분들도 잘 수정해주셨네요!
추가로 질문주신 부분들은 제가 역질문을 남겨두었는데 확인해보시고 dm부탁드려요.
다음 레벨도 화이팅입니다!

2024-04-02 01:38 UTC, merged