[체스 - 3단계] 낙낙(이낙헌) 미션 제출합니다.
woowacourse/java-chess pull request #763
Opened 2024-03-30 04:48 UTC by nak-honest

안녕하세요 현구막!
3단계 구현 후 제출합니다!!

고민되는 부분이 있어 2개의 TODO가 해결되지 않았는데, 코멘트로 남겨 놓았습니다!

이전 미션들은 제 기준하에 완성도가 아쉬워 늘 제출 마감 직전에 PR을 보냈는데,
욕심은 조금 내려 놓고 현구막과 더 많은 이야기 나누어보는게 더 좋을 것 같다고 생각했습니다 :)

스스로 오랫동안 고민해서 결론 짓는 것도 물론 좋지만, 어느정도 고민을 해도 결론이 나지 않으면 빠르게 물어보는게 더 좋을 것 같더라구요!

이번 리뷰도 잘 부탁드립니다 🙇
감사합니다 현구막!!!

2024-03-30 06:10 UTC, nak-honest commented on src/main/java/chess/domain/piece/Piece.java
>      }
현재 구조에서는 `Piece`가 `Movements`를 필드로 가지고 있습니다.

하지만 각 체스말의 구현체들은 움직임이 변하지 않기 때문에 각각 `Movements`가 고정되어 있습니다.
따라서 각 Movements를 static 변수로 가지고 있습니다.

그런데 문득 각 체스말들이 객체로서 동작한다는 느낌 보다는, 굉장히 정적으로 동작한다는 느낌이 들었습니다.
대부분의 로직들이 static 변수로 인해 수행되기 때문입니다.
<br>

따라서 각 구현체 클래스들을 전부 없애고 `Piece`를 일반 클래스로 바꾼뒤,
`PieceFactory`와 같은 걸 만들어서 `Piece`에 알맞는 상태를 주입해주면 어떨까라는 생각이 들었습니다.
가령 다음과 같이 메소드를 통해 각각의 체스말들을 만들어 줄 수 있겠다고 생각했습니다.

```java
public class PieceFactory {
	public static Piece createRook(Color color) {
		return new Piece(color, MovementsFactory.createStraight());
	}
	// ...
}
```

이렇게 하면 Piece는 좀 더 자신의 상태에 따라 행동하는 동적인 객체가 되는 것 같습니다.
새로운 Piece를 만들 때에도 클래스를 확장할 필요 없이 `Piece` 객체를 직접 만들 수 있을 것 같구요.

하지만 체스라는 도메인을 생각했을 때에는 새로운 체스말이 추가될 가능성은 낮고, 각 체스말의 움직임도 바뀔 가능성이 낮습니다.

이러한 측면에서는 각 체스말을 상속을 통해 클래스로 고정하는 것이 좋겠다는 생각도 듭니다.
그리고 각 움직임이 고정된다는 것을 고려했을 때 `Piece`에서 굳이 `Movements`를 필드로 가지지 않고 각 구현체에서 static `Movements`를 활용할 수 있을 것 같습니다.


말로 잘 정리가 안되는데,
1. "새로운 체스말이 추가될 가능성이 적고 체스말의 움직임도 변할 가능성이 적으니, 클래스와 static 변수로 고정하자"
2. "좀더 Piece를 객체답게 사용하기 위해 자신의 상태에 따라 움직이도록 Piece를 일반 클래스로 정의하자"

이 2가지 중에 고민이 되는 것 같습니다.
`도메인 상황 고려 vs 객체지향` 이 둘 사이에서 뭔가 저울질이 되는 것 같은데 현구막은 이에 대해 어떻게 생각하실까요?
좀더 고민해볼만한 포인트나 의견 주시면 감사하겠습니다!!

2024-03-30 06:10 UTC, nak-honest commented on src/main/java/chess/domain/board/ChessBoard.java
현재 `ChessBoard`가 크다고 생각 됩니다.
하지만 일급 컬렉션 관점에서는 자신이 가지고 있는 `pieces`에 대한 행동으로 보이기 때문에,
분리도 조금 애매한 것 같습니다.

가령 `Path`와 같은 객체를 만들어서 start와 end에 대한 검증을 맡길까 생각하였지만,
이후 Map에서 두 `Piece`를 바꾸는 것이 애매해 질 것 같았습니다.

현구막이 보시기에는 현재 `ChessBoard`의 역할과 책임이 많다고 느끼시는지 궁금합니다!!

2024-03-31 10:56 UTC, Hyeon9mak requested changes
안녕하세요 낙낙! 3단계 잘 진행해주셨습니다.

정말 유지보수에 좋은 코드가 무엇인지 깊은 고민을 하고 계신 것 같아요.
무작정 좋은 방법, 방식을 공부하는 건 의미가 없죠.
이따금씩 "이게 정말 필요한 것인가?" 에 대한 본질적인 고민을 항상 해야
더 나은, 더 좋은 방법도 고안해낼 수 있다고 생각합니다 👍 

저도 보탬이 되기 위해 몇 가지 이야기와 질문 남겼습니다.
확인 후 답변해주세요!

2024-03-31 10:56 UTC, Hyeon9mak commented on src/main/java/chess/domain/board/ChessBoard.java
낙낙도 아시듯 역할이라는 것은 `ChessBoard` 가 public method 로 행하는 모든 행위가 "체스 게임의 체스 보드처럼 보여?" 겠고,
책임이라는 것은 "우리 사업 특성상 `ChessBoard` 클래스 파일을 수정할 경우의 수가 ~정도 돼." 일거에요.

그런 관점에서는 `ChessBoard` 가 꼭 분리될 필요가 없을 정도로 적당한 역할과 책임을 갖고 있다고 생각되는데요,
"`ChessBoard` 가 크다." 고 생각하신 건 아무래도 '코드량이 많아서 부담스럽게 느껴진다.' 인 것 같아요.
사실 코드량이 너무 많으면 아무리 역할과 책임을 잘 나누더라도 읽는 사람이 힘이 부칠 수 밖에 없죠.
(집중도가 많이 떨어짐)

역할과 책임을 나누는 것도 결국 인간의 인지능력을 보완하기 위한 작업인만큼, 절대적인 코드량도 관리를 해야겠는데요,
이런 애매한 상황에서 한가지 해결책이 될 수 있는 방법이 있어요.

사실 우리가 통상적으로 "체스 게임의 체스보드" 라는 객체에게 기대하는 건 "체스 기물을 좌표상에서 이동시키는 것" 일텐데요,
현재 `ChessBoard` 는 이동로직 외에도 여러가지 검증을 해주느라 몹시 바쁜 상태에요.
`ChessBoard` 가 다루고 있는 검증 로직들을 별도 클래스 파일로 분리해보는 건 어떨까요?

2024-03-31 10:56 UTC, Hyeon9mak commented on src/main/java/chess/domain/board/ChessBoard.java
순수한 비즈니스 로직만 수행하는 객체와 검증 전문 객체를 분리하는 것이 항상 정답은 아니에요.

두 가지 상황을 예를 들어서 비즈니스 객체에서 직접 검증하는 것과, 
검증 전문 객체를 분리하는 것 중 어떤 것이 더 잘어울릴지, 왜 잘어울린다고 생각했는지 이야기해주세요.

A. 기물별 이동로직이 불특정한 주기로 변경되는 케이스 (1월엔 퀸, 7월엔 폰, 9월엔 킹)
B. 전체 체스 게임의 규칙이 매해 1월마다 한꺼번에 변경되는 케이스

2024-03-31 10:56 UTC, Hyeon9mak commented on src/main/java/chess/domain/game/ChessGame.java
>      }
`Turn` 개념을 포장해둔 것이 `State` 로 자연스럽게 변경되는 경험을 하셨군요 👍 
만약 `Turn` 에게 메세지를 보내지 않고 `Turn` 에서 값을 꺼내어 다루거나 했다면,
`ChessGame` 내에서 코드 변화도 굉장히 많았겠죠. (캡슐화의 이점X)

2024-03-31 10:56 UTC, Hyeon9mak commented on src/main/java/chess/domain/game/state/EndState.java
> +    }
상태패턴 활용 👍

2024-03-31 10:56 UTC, Hyeon9mak commented on src/test/java/chess/domain/game/ChessGameTest.java
> +            rnbqkbnr
주석 덕분에 게임 진행 상황을 알기 매우 쉽네요!! 💯 👍 
이런 사소한 배려가 팀 전체 작업속도를 엄청나게 높혀주죠!!

2024-03-31 10:56 UTC, Hyeon9mak commented on src/main/java/chess/domain/piece/Piece.java
>      }
좋은 고민이라고 생각합니다 💯 
당연히 앞으로 코드를 유지보수하기 유리한 방향은 2번 방향일텐데요,
아시다시피 그보다 앞서 고민해볼 것은 1번 방향처럼 "정말 유지보수가 필요한가?" 라는 본질적인 부분이에요.

유지보수가 필요하지 않은 부분에 공을 들여 만들어봤자, 유지보수를 하지 않는다면... 🤔 
"일을 잘하는 것"과도 연결지어 생각해볼 수 있겠네요.

이 지점이 예술 연구와, 공학의 차이라고 생각해요. 
예술이나 연구는 끊임없이 탐구를 하지만, 공학은 문제를 해결하는 것에 초점이 맞춰져있으니까요.
남들이 눈여겨 보지 않은 문제에 초점을 맞추고 몰입하여 더 나은 해결책을 찾아내는 건 분명 좋은 일이지만
현실적으로 그럴 여유가 없거든요. 눈 앞에 놓인 문제들이 얼마나 많은데... 😅 

................................ 만 사실 우테코 교육기간 중 그렇게 생각하면 막상 공부할 것들이 없기 때문에 ㅋㅋㅋ
낙낙이 적당히 밸런스를 찾아가보시면 좋을거 같아요 😄 👍

2024-03-31 13:16 UTC, nak-honest commented on src/main/java/chess/domain/game/ChessGame.java
>      }
사실 현구막이 말씀해 주시기 전까지는 전혀 느끼지 못했었는데,,,

Files Changed 를 보니 수정이 적다는게 눈으로 보이는 것 같네요!!
객체에게 적절한 책임을 부여하고 로직(내부 행동)을 잘 캡슐화하는 것이
어떻게 유지보수성을 증가시켜주는지 느껴지는 것 같습니다 :)

감사합니다 👍

2024-03-31 13:39 UTC, nak-honest commented on src/main/java/chess/domain/piece/Piece.java
>      }
ㅎㅎ 좋은 말씀 감사합니다!
확실히 학습 측면에서는 많은걸 얻어갈때도 있는 것 같아요!!

그리고 우테코는 샌드박스이기 때문에 요것저것 시도해보면서 직접 경험해 보면 깨달음이 더 큰 것 같구요 ㅎㅎ
제가 너무 과한 설계를 하게되었을때 이를 바로 잡아줄 리뷰어와 주변 크루들도 있구요!
<br>

하지만 이러한 상황적인 배경 상황은 제하고 딱 소프트웨어만 보았을 때 과연 어떤지도 고민해야 하는 것 같아요.
모든 상황에 맞는 해결 방법이란 존재하지 않으니, "이게 정말 필요한 것인가?" 를 늘 고민하며 접근해야겠습니다!
그리고 무엇이든 맹목적으로 따르지 않으려 경계하겠습니다.

좋은 의견 감사합니다 현구막!!
덕분에 많이 고민하고, 또 배워가게 되는 것 같습니다 :)

2024-03-31 15:24 UTC, nak-honest commented on src/main/java/chess/domain/board/ChessBoard.java
고민을 해 보았는데 많이 어려운 것 같습니다 ㅎㅎ
하지만 그만큼 많은 것을 얻어갈 수 있는 질문인 것 같습니다 :)
<br>
<br>

객체가 하나의 책임만을 가져야한다는 SRP 원칙은,
바꿔 말해서 객체가 변하는 이유가 하나이어야 함을 의미합니다.

그리고 이는 객체 내부 각 책임들이 같은 주기로 변경되어야 한다는 것을 의미하구요.
<br>

#### A. 기물별 이동로직이 불특정한 주기로 변경되는 케이스 (1월엔 퀸, 7월엔 폰, 9월엔 킹)
검증 객체를 분리하는 것이 더 잘 어울린다고 생각합니다.

위의 케이스에서는 기물별 이동로직이 변할 때 start와 end에 대한 검증 로직이 변할 가능성이 낮습니다.

하지만 체스 보드의 행동은 변경될 가능성이 더 높습니다.
가령 체스말 중 하나가 다른 체스말을 뛰어넘는 방식으로 변경된다고 하면(장기에서 "포"와 같은 움직임)
체스 보드에서 변경사항이 발생하게 됩니다.
현재 체스 보드는 체스말의 이동 경로에 장애물이 없는지만 체크하기 때문입니다.
<br>

즉 검증 로직과 체스 보드의 행동이 다른 주기로 변하게 됩니다. 
따라서 위의 케이스에서는 검증 로직을 분리하는 것이 좋다고 생각합니다.

그렇게 되면 기물의 이동 로직이 변할 때 분리된 검증 전문 객체는 변하지 않게 되므로 
각 객체가 하나의 이유로 변경된다는 SRP 원칙이 잘 적용되었다고 볼 수 있을 것 같습니다.
<br>

#### B. 전체 체스 게임의 규칙이 매해 1월마다 한꺼번에 변경되는 케이스
이 케이스에서는 검증 로직과 체스보드의 행동이 매해 1월에 같이 변경될 가능성이 높습니다.

가령 같은 편 기물을 잡아 먹었을때 특정 기능이 추가된다던지, 
윷놀이처럼 같은 편 기물에 업기 기능이 추가된다던지,
특정 상황에서는 적의 기물을 먹을 수 없는 등의 변경사항이 발생하게 되면 
검증 로직이 변해야하고, 체스 보드의 행동도 변해야 합니다.

즉 검증로직과 체스 보드의 행동이 같은 주기로 변경될 것이라 기대되기 때문에 `ChessBoard`가 직접 검증해주는 것이 더 잘 어울린다고 생각합니다.

2024-03-31 16:09 UTC, nak-honest commented
안녕하세요 현구막!!

간단하게 피드백 반영하고,
코멘트를 통해 답변 드렸습니다 :)

감사합니다 😀

2024-04-01 23:36 UTC, Hyeon9mak approved these changes
안녕하세요 낙낙! 피드백 반영 고생하셨습니다.
객체의 책임을 어떻게 나누는게 좋을지에 대한 낙낙만의 기준이 잡히셨을까요? 😄 👍 
드디어 마지막 단계만 앞두고 있네요!! 바로 가보시죠!!

2024-04-01 23:36 UTC, Hyeon9mak commented on src/main/java/chess/domain/piece/Piece.java
`Piece` 가 엄청 가벼워졌군요 😮

2024-04-01 23:36 UTC, Hyeon9mak commented on src/main/java/chess/domain/board/ChessBoard.java
> +            passPiece(startEndPosition);
> A. 기물별 이동로직이 불특정한 주기로 변경되는 케이스 (1월엔 퀸, 7월엔 폰, 9월엔 킹)
검증 객체를 분리하는 것이 더 잘 어울린다고 생각합니다.

> B. 전체 체스 게임의 규칙이 매해 1월마다 한꺼번에 변경되는 케이스
이 케이스에서는 검증 로직과 체스보드의 행동이 매해 1월에 같이 변경될 가능성이 높습니다.

주어진 예시 상황 속에서 어떤 클래스 파일에 대량의 코드 변화가 발생할지 상상하며 답을 잘 정해주신 것 같아요. 👍 
객체의 책임을 어떻게 나누는게 좋을지에 대한 낙낙만의 기준이 생기셨을까요? 😄

2024-04-01 23:36 UTC, merged