[3, 4단계 - 체스] 트레 미션 제출합니다.
woowacourse/java-chess pull request #764
Opened 2024-03-30 05:41 UTC by takoyakimchi

안녕하세요 호돌!
지난번에 주신 피드백에 이어서, 3~4단계 적용해 보았습니다.
구현 방향성 말씀드리겠습니다.

### 체스판 저장 방식
<img width="520" alt="image" src="https://github.com/woowacourse/java-chess/assets/37261785/73e1ab99-f885-4251-a2e2-b8dd2b3c033b">

`chess`라는 이름의 스키마를 생성하여 진행하였습니다.
체스판은 사진과 같이 하나하나 문자로 변환하고, 길이가 64개인 문자열로 저장합니다.
다음 차례가 누구인지 또한 문자열로 저장합니다.
`game_id`는 auto increment하는 PK이며, 추후 선택 요구사항을 구현할 때 사용할 예정입니다.

추가로, `OutputView`와 동일한 문자 변환 로직을 사용하다 보니 방대한 양의 if문과 코드 중복이 일어나게 되었고,
이것을 해결하고자 각 Piece의 도메인에 해당 로직을 집어넣게 되었습니다.
뷰 로직이 도메인을 침범한다는 점에서 위화감이 느껴지지만 중복 제거 및 구현 편의성에서 오는 이점이 더 크다고 판단했습니다.

### 상태 패턴 적용
* WHITE와 BLACK이 번갈아가면서 말 이동
* 게임이 시작되었는데 `start`를 입력했을 때의 처리
* `start`를 하지 않고 `move`를 입력했을 때의 처리

등등 다양한 예외 처리가 가능하다는 이점이 있다고 판단하였고, 상태 패턴을 적용시켰습니다.

### Piece를 싱글톤으로 관리
* `instanceof`를 제거하고 `equals`로 각각의 기물을 판단하도록 수정하다 보니 인스턴스 생성이 많아졌습니다.
* 메모리 낭비를 방지하고자 싱글톤으로 관리하도록 수정하였습니다.
* `Piece`가 위치 정보를 가지고 있지 않기 때문에, 싱글톤으로 관리하여도 적합하다고 판단하였습니다.

### 1~2단계 피드백 반영
https://github.com/woowacourse/java-chess/pull/658#discussion_r1539736394
https://github.com/woowacourse/java-chess/pull/658#discussion_r1540353626
참고 부탁드립니다!

피드백 미리 감사드립니다. 좋은 주말 보내세요! 👍

2024-03-30 09:03 UTC, kimhodol requested changes
안녕하세요 트레 👋 

3, 4 단계 구현 잘 해주셨네요 👍 

코멘트 확인 부탁드릴게요 🙇

2024-03-30 09:03 UTC, woonjangahn commented on src/main/java/chess/application/ChessApplication.java
> +            outputView.printMessage("[ERROR] " + exception.getMessage());
View에 예외 메세지를 보여주는 함수가 별도로 있어도 좋을 것 같네요.

2024-03-30 09:03 UTC, woonjangahn commented on src/main/java/chess/db/ChessDao.java
> +            throw new UnsupportedOperationException("서버 연결이 끊겼습니다.");
UnsupportedOperationException이 이 상황에서 올바른 예외일까요?

2024-03-30 09:03 UTC, woonjangahn commented on src/main/java/chess/db/GameRepository.java
> +            + "PRIMARY KEY (game_id))";
Java 15부터 Multiline String을 사용할 수 있어요.

```java
String query = """
            CREATE TABLE IF NOT EXISTS board(
            game_id INT NOT NULL AUTO_INCREMENT,
            board_text VARCHAR(255) NOT NULL,
            turn_text VARCHAR(255) NOT NULL,
            PRIMARY KEY (game_id));
        """;
```

2024-03-30 09:03 UTC, woonjangahn commented on src/main/java/chess/db/GameRepository.java
> +            throw new UnsupportedOperationException("서버와의 연결이 끊겼습니다");
SQLException은 다양하게 나올 수 있는데, 서버와의 연결이 끊겼다는 메세지는 항상 맞지는 않을 것 같아요.

2024-03-30 09:03 UTC, woonjangahn commented on src/main/java/chess/db/GameRepository.java
> +        }
인덴트를 1 이하로 유지해주세요 :)

2024-03-30 09:03 UTC, woonjangahn commented on src/main/java/chess/db/GameRepository.java
> +            }
인덴트를 1 이하로 유지해주세요 :)

2024-03-30 09:03 UTC, woonjangahn commented on src/main/java/chess/db/GameRepository.java
> +    }
enum의 name()을 사용해도 될것 같네요.

2024-03-30 09:03 UTC, woonjangahn commented on src/main/java/chess/db/GameRepository.java
> +    public String serializeBoard(Board board) {
serializeXXX들은 public일 필요가 없어보입니다.

2024-03-30 09:03 UTC, woonjangahn commented on src/main/java/chess/domain/board/Board.java
> +            .filter(piece -> piece.equals(King.withColor(WHITE)) || piece.equals(King.withColor(BLACK)))
equals보다 piece.isKing()은 어떨까요?

2024-03-30 09:03 UTC, woonjangahn commented on src/main/java/chess/domain/board/Board.java
> +            .filter(number -> number >= 2)
매직넘버를 상수화해주세요.

2024-03-30 09:03 UTC, woonjangahn commented on src/main/java/chess/domain/board/Board.java
> +        return IntStream.rangeClosed(1, 8)
마찬가지로 매직넘버를 상수화해주세요.

2024-03-30 09:03 UTC, woonjangahn commented on src/main/java/chess/domain/board/Board.java
> +    public boolean equals(Object o) {
Board.equals는 어디서 사용하고 있나요?

2024-03-30 09:03 UTC, woonjangahn commented on src/main/java/chess/domain/game/Game.java
> +        return board.kingCount() < 2;
매직넘버를 상수화해주세요.

2024-03-30 09:03 UTC, woonjangahn commented on src/main/java/chess/domain/game/Game.java
> +    public Game start() {
Game을 반환할 것이라면 start, move, end보다는 started, moved, ended는 어떨까요?

2024-03-30 09:03 UTC, woonjangahn commented on src/main/java/chess/domain/piece/King.java
>      }
text()는 도메인의 관심사가 아닐 것 같아요.

2024-03-30 09:03 UTC, kimhodol commented on src/main/java/chess/view/CommandType.java
> +        String prefix = commands.get(0);
IndexOutOfBound가 날 수 있을 것 같아요.

2024-03-30 09:03 UTC, kimhodol commented on src/test/java/chess/db/GameRepositoryTest.java
> +class GameRepositoryTest {
실행환경에 따라 실패할 수 있는 테스트는 자기완결성이 있다고 보기 어렵지 않을까요?

2024-03-30 09:03 UTC, kimhodol commented on src/test/java/chess/db/GameRepositoryTest.java
> +    void saveGame_loadGame() {
테스트 메소드명도 자바의 컨벤션을 맞춰주세요.

2024-03-31 05:48 UTC, takoyakimchi commented on src/main/java/chess/application/ChessApplication.java
> +            outputView.printMessage("[ERROR] " + exception.getMessage());
좋네요 !! 반영했습니다!! 👍👍

2024-03-31 05:48 UTC, takoyakimchi commented on src/main/java/chess/db/ChessDao.java
> +            throw new UnsupportedOperationException("서버 연결이 끊겼습니다.");
`IllegalStateException` 으로 수정해 보겠습니다

2024-03-31 05:49 UTC, takoyakimchi commented on src/main/java/chess/db/GameRepository.java
> +            + "PRIMARY KEY (game_id))";
이런 것도 가능하군요!
꿀팁 감사드립니다!

2024-03-31 05:53 UTC, takoyakimchi commented on src/main/java/chess/db/GameRepository.java
> +            throw new UnsupportedOperationException("서버와의 연결이 끊겼습니다");
예외 메시지 구체화 진행하겠습니다!

2024-03-31 06:24 UTC, takoyakimchi commented on src/main/java/chess/db/GameRepository.java
> +    }
감사합니다!

2024-03-31 06:24 UTC, takoyakimchi commented on src/main/java/chess/db/GameRepository.java
> +    public String serializeBoard(Board board) {
`private`으로 변경하겠습니다.

2024-03-31 06:27 UTC, takoyakimchi commented on src/main/java/chess/domain/board/Board.java
> +            .filter(piece -> piece.equals(King.withColor(WHITE)) || piece.equals(King.withColor(BLACK)))
말씀하신 대로, 의미를 담아 메시지를 전달하면 더 좋겠군요!
반영하겠습니다.

2024-03-31 06:43 UTC, takoyakimchi commented on src/main/java/chess/domain/board/Board.java
> +    public boolean equals(Object o) {
테스트에서만 사용되고 있는 것을 확인했습니다. equals and hashcode 제거해도 되겠네요!

2024-03-31 06:47 UTC, takoyakimchi commented on src/main/java/chess/domain/board/Board.java
> +    public boolean equals(Object o) {
equals 사용해서 테스트하던 코드는 테스트 케이스를 줄이고 경계값으로만 진행해 보겠습니다.

2024-03-31 06:48 UTC, takoyakimchi commented on src/main/java/chess/domain/game/Game.java
> +    public Game start() {
이 부분에 대한 고민이 있었는데, 기존 코드처럼 동사로 이름을 지으면 void 메소드 같은 느낌이 들겠네요.

반영하겠습니다!

2024-03-31 07:02 UTC, takoyakimchi commented on src/main/java/chess/view/CommandType.java
> +        String prefix = commands.get(0);
더 안정성 있는 코드 작성하도록 신경 쓰겠습니다!

2024-03-31 07:13 UTC, takoyakimchi commented on src/test/java/chess/db/GameRepositoryTest.java
> +    void saveGame_loadGame() {
반영하였습니다!

저는 테스트 메소드명에 한해서는 언더바를 사용해서 의미를 구분짓는 편인데요.
(물론 이 코드에서는 `saveGame_LoadGame`이 되어야겠군요!)

호돌은 어떤 방식을 주로 사용하시나요?

2024-03-31 08:16 UTC, takoyakimchi commented on src/main/java/chess/domain/piece/King.java
>      }
`text()` 제거하고 `db` 패키지와 `view` 패키지로 이동시켰습니다.

2024-03-31 08:21 UTC, takoyakimchi commented on src/main/java/chess/db/GameRepository.java
> +            }
반영하였습니다!

2024-03-31 08:21 UTC, takoyakimchi commented on src/main/java/chess/db/GameRepository.java
> +        }
반영하였습니다!

2024-04-01 06:56 UTC, takoyakimchi commented on src/test/java/chess/db/GameRepositoryTest.java
> +class GameRepositoryTest {
DB에 의존적인 테스트 제거하겠습니다!

2024-04-01 10:54 UTC, kimhodol commented on src/test/java/chess/db/GameRepositoryTest.java
> +    void saveGame_loadGame() {
JUnit의 DisplayName이 없을 때는 테스트 메소드 명에 언더스코어 등을 넣어서 사용하는 컨벤션이 있었던 것 같은데요, DisplayName이 생긴이후에는 테스트 메소드명을 크게 신경쓰지는 않는 것 같습니다!

2024-04-01 11:05 UTC, kimhodol requested changes
안녕하세요 트레 👋 

코드가 많이 깔끔해졌네요 👍 

코멘트 참고 부탁드릴게요 🙇

2024-04-01 11:05 UTC, woonjangahn commented on src/main/java/chess/application/ChessApplication.java
> +        } catch (UnsupportedOperationException | IllegalArgumentException | IllegalStateException exception) {
RuntimeException으로 묶어서 catch할 수 있겠네요!

2024-04-01 11:05 UTC, woonjangahn commented on src/main/java/chess/application/ChessApplication.java
> +        game.started();
여기서 game = game.started()를 해주지 않아도 되나요?

2024-04-01 11:05 UTC, woonjangahn commented on src/main/java/chess/db/GameRepository.java
> +public class GameRepository {
DAO와 Repository의 차이점은 무엇일까요?

2024-04-01 11:05 UTC, kimhodol commented on src/main/java/chess/domain/board/DeserializingBoardGenerator.java
> +    private static void putWhitePieces(Map<Character, Piece> toPieceMap) {
인자명이 toPieceMap인데, 좀 어색하게 느껴져요. 차라리 다른 곳에서처럼 그냥 map으로 가도 되겠네요. 개인적으로는 자료형을 변수명에 잘 쓰지 않는 편이긴한데, 그냥 pieces나 pieceByCharacter 이런식으로 쓰기도 합니다!

2024-04-02 06:59 UTC, takoyakimchi commented on src/main/java/chess/application/ChessApplication.java
> +        } catch (UnsupportedOperationException | IllegalArgumentException | IllegalStateException exception) {
원치 않는 (명시한 3개 외의) RuntimeException을 잡아서 처리하는 경우가 생기지 않을까요?

2024-04-02 08:27 UTC, takoyakimchi commented on src/main/java/chess/application/ChessApplication.java
> +        game.started();
밑에서 `game = gameRepository.loadGame();`를 통해 `game`을 초기화해주고 있기 때문에,
`game = game.started()` 했을 때의 결과값이 ignore 되는 warning이 발생하였습니다.

`started()` 메소드에서 `Game`을 반환하는데, 결과적으로는 `void` 메소드 처럼 사용되고 있는 것 자체가 문제라고 판단하였고,
해당 메소드를 `void`로 바꾸었습니다.

2024-04-02 08:30 UTC, takoyakimchi commented on src/main/java/chess/domain/board/DeserializingBoardGenerator.java
> +    private static void putWhitePieces(Map<Character, Piece> toPieceMap) {
반영하겠습니다!
**자료형을 변수에 쓰지 않는다**는 규칙을 저도 선호하는데, map은 이름 짓기가 항상 어렵네요.

2024-04-02 11:34 UTC, takoyakimchi commented on src/main/java/chess/db/GameRepository.java
> +public class GameRepository {
DAO
- DB에 더 가깝다 (테이블 중심)
- 저수준의 CRUD를 처리한다
- DB 접근 관련 로직이 들어있다

Repository
- 도메인에 더 가깝다 (객체 중심)

도메인이 작아서 큰 차이가 없다는 생각도 드네요. 하나로 통일시켜 보겠습니다

2024-04-03 06:40 UTC, kimhodol commented on src/main/java/chess/application/ChessApplication.java
> +        } catch (UnsupportedOperationException | IllegalArgumentException | IllegalStateException exception) {
그렇긴하네요! 저 3개의 Exception 말고 Custom Exception을 만들어서 도메인 로직에 문제가 생겼을 때 해당 exception을 반환하는 것도 고려해볼 수 있을 것 같아요. 매번 새로운 예외를 만들때마다 추가하기 번거로울 수 있으니깐요 :)

2024-04-03 06:48 UTC, kimhodol requested changes
안녕하세요 트레 👋 

거의 다 왔네요 💯 

코멘트 확인 부탁드릴게요 🙇

2024-04-03 06:48 UTC, kimhodol commented on src/main/java/chess/application/ChessApplication.java
>      public static void main(String[] args) {
Controller같은 객체에 각각의 View나 Repository를 주입해주고, controller.run 등만 main에 남기는것도 괜찮을 것 같아요. Application은 아무래도 main entry point만 짧게 있는게 더 나을 것 같아서요.

2024-04-03 06:48 UTC, kimhodol commented on src/main/java/chess/db/GameRepository.java
> +    }
PieceSerializer처럼 serializer 객체를 따로 두는것은 어떨까요?

2024-04-03 08:38 UTC, takoyakimchi commented on src/main/java/chess/db/GameRepository.java
> +    }
serialize 관련 로직을 모두 하나의 클래스로 관리해 보겠습니다.

2024-04-03 08:43 UTC, takoyakimchi commented
안녕하세요 호돌! 피드백 감사합니다.
피드백 반영 및 선택 요구사항(`체스 게임방을 만들고 체스 게임방에 입장할 수 있는 기능을 추가한다.`)까지 구현해 보았습니다.
어색한 부분이 있으면 추가적인 피드백 부탁드립니다. 감사합니다!

## 선택 요구사항을 구현하면서 변경된 사항
- `start` 명령어를 제거했습니다.
- 대신 `enter {id}`로 게임에 입장하면 게임이 자동으로 시작됩니다.
- `GameState`에서 사용했던 `start` 메소드도 필요가 없어졌기에 제어했습니다.

2024-04-04 04:54 UTC, kimhodol requested changes
안녕하세요 트레 👋 

추가 요구사항도 잘 구현해주셨네요 💯 

간단한 코멘트 확인 부탁드릴게요 🙇

2024-04-04 04:54 UTC, kimhodol commented on src/main/java/chess/controller/ChessController.java
> +            return gameRepository.makeGameThenFindId(Board.generatedBy(new InitialBoardGenerator()), Color.WHITE);
Board.initializeNewGame() 같은 식으로 다른 팩토리 생성자를 사용해도 되겠네요.

2024-04-04 04:54 UTC, kimhodol commented on src/main/java/chess/application/ChessApplication.java
> +        chessController.run();
👍

2024-04-04 04:54 UTC, kimhodol commented on src/main/java/chess/controller/ChessController.java
> +        } catch (NullPointerException exception) {
NPE가 나는 경우는 어떤 경우일까요?

2024-04-04 04:54 UTC, kimhodol commented on src/main/java/chess/db/GameRepository.java
> +            resultSet.next();
1개만 가져오는게 의도라면 sql 에서 limit 1을 하면 어떨까요?

2024-04-04 04:54 UTC, kimhodol commented on src/main/java/chess/db/ObjectSerializer.java
> +    }
static일 필요가 없어보이네요.

2024-04-04 05:57 UTC, takoyakimchi commented on src/main/java/chess/controller/ChessController.java
> +        } catch (NullPointerException exception) {
일차적으로 존재하지 않는 명령어인 경우 `CommandType`에서 `올바르지 않은 명령어 입력입니다.`라는 예외 메시지를 출력합니다.
존재하는 명령어이지만 게임 실행 도중에 입력할 수 없는 경우 `CommandType.MOVE`, `CommandType.STATUS`, `CommandType.END` 이외의 값을 `get()`하게 되어 NPE가 발생하고 `게임 진행중에 입력할 수 없는 명령어입니다.`라는 예외 메시지를 출력합니다.

<img width="395" alt="image" src="https://github.com/woowacourse/java-chess/assets/37261785/82285058-3b38-43e3-bcc4-a0b2d3cde1cc">

2024-04-04 05:57 UTC, takoyakimchi commented on src/main/java/chess/application/ChessApplication.java
> +        chessController.run();
😄

2024-04-04 05:59 UTC, takoyakimchi commented on src/main/java/chess/db/GameRepository.java
> +            resultSet.next();
감사합니다!

2024-04-04 06:00 UTC, takoyakimchi commented on src/main/java/chess/db/ObjectSerializer.java
> +    }
옮기는 과정에서 실수가 있었네요. 감사합니다!

2024-04-04 06:09 UTC, takoyakimchi commented on src/main/java/chess/controller/ChessController.java
> +            return gameRepository.makeGameThenFindId(Board.generatedBy(new InitialBoardGenerator()), Color.WHITE);
작성하면서도 있으면 좋겠다는 생각이 들었어요! 반영하겠습니다!

2024-04-06 00:21 UTC, kimhodol commented on src/main/java/chess/controller/ChessController.java
> +        } catch (NullPointerException exception) {
이런 식으로 풀면 어떨까요?

```java
private Game executeGameCommand(Game game, int gameId, Command command) {
    Map<CommandType, GameCommandExecutor> commandExecutionMap = Map.of(
            CommandType.MOVE, () -> move(game, gameId, command),
            CommandType.STATUS, () -> showStatus(game),
            CommandType.END, () -> end(game)
    );
    return commandExecutionMap.getOrDefault(command.type(), () -> {
        throw new IllegalArgumentException("게임 진행중에 입력할 수 없는 명령어입니다.");
    }).execute();
}
```

2024-04-06 00:22 UTC, kimhodol approved these changes
안녕하세요 트레 👋 

이번 미션은 여기서 마무리해도 될 것 같아요 💯 

레벨 1 정말 고생 많으셨고, 방학 잘 보내세요 🍹

2024-04-06 00:23 UTC, merged