[체스 3, 4단계] 새양(양경호) 미션 제출합니다.
woowacourse/java-chess pull request #768
Opened 2024-03-30 12:06 UTC by geoje

## 🧐 리뷰어님!
제이미~ 안녕하세요 새양입니다!

`JDBC` 를 사용하는 것에 어려움을 살짝 느꼈었고 막상 하다 보니 아래 사항들이 욕심이 나더라구요!
- 프로그램 실행 시 `DB` 와 `Table` 이 이 없을 경우 자동 생성되도록 한다.
- 선택 요구사항: 체스 게임방에 입장할 수 있고, 사용자별 게임 기록 관리 할 수 있다.

단순 콘솔 프로그램이지만 `DB` 까지 연결하여 하니 시간이 좀 걸려서 최대한 모든 것을 해보려고 했습니다!

또한 아래의 새로운 패턴들도 한번 시도해 보았어요!
- **상태 패턴:**  Ready, Progress, End
- **커맨드 패턴:**  start, resume, room, user, move, status

## 💊 캡슐화
객체의 속성(필드)과 행위(메서드)를 하나로 묶고, 실제 구현 내용 일부를 외부에 감추어 은닉한다.

이점으로는 코드의 중복을 피하고, 데이터 처리 동작 방식을 외부에서 알 필요가 없다는 것입니다!

객체 스스로 처리하도록 하면 추후에 변경에 대해서도 내부 로직만 변경하면 되어 큰 어려움이 없다라는 장점을 가져갑니다!

## 🤔 궁금한 점
### DAO 테스트
이번에 새롭게 `DB` 를 적용하며 테스트를 어떻게 할지 고민을 했습니다!
생성에 대한 테스트는 끝나고 지워줘야 했고,
업데이트와 삭제는 미리 데이터를 삽입해야 했습니다.

이 모든 것을 하나의 테스트로 두어 `assertThat` 을 3번 수행을 했는데 실제 `production` 에 영향이 안가도록 더 좋은 테스트 방법은 없을까요?

- MySQL의 `transaction` 을 시작하여 생성한 뒤 `rollback` 한다.
- 테스트용 DB를 스키마가 똑같도록 하나 더 만든다.

어떤방법이 최선의 선택일지 이 방법 외에도 뭐가 있을지 궁금합니다!!

``` java
final Room savedRoom = roomDao.save(room);
assertThat(savedRoom.id().value()).isGreaterThan(0);

final int updatedCount = roomDao.updateWinnerById(savedRoom.id().value(), "blackTester");
assertThat(updatedCount).isGreaterThan(0);

final int deletedCount = roomDao.deleteAllById(savedRoom.id().value());
assertThat(deletedCount).isGreaterThan(0);
```

그리고 너무 늦게 제출해서 죄송합니다 😭
1,2 단계 처음에 부실한 코드로 리뷰를 받은 것 같아 완벽하게 다 만들고(제 기준에서 최대한...) 리뷰를 받고 싶어 이제서야 PR을 작성하네요 😢
그럼 잘 부탁 드립니다!! 😂

2024-03-31 12:30 UTC, jamie9504 requested changes
안녕하세요, 새양 😄 리뷰어 제이미입니다.

코멘트 조금 남겨두었어요.

오늘도 좋은 주말 보내세요 😉

2024-03-31 12:30 UTC, jamie9504 commented on README.md
DAO 테스트는 프로젝트 상황에 따라 다르게 선택하는 부분이니 이 방법 저 방법 모두 익혀보는 것도 좋을 것 같습니다.

- MySQL의 transaction 을 시작하여 생성한 뒤 rollback 한다.
- 테스트용 DB를 스키마가 똑같도록 하나 더 만든다.

이 외의 방법은 다음 우테코 2레벨 미션들을 하면서 넓혀보면 좋을 것 같네요 😉

2024-03-31 12:30 UTC, jamie9504 commented on README.md
> +```
<img width="479" alt="image" src="https://github.com/woowacourse/java-chess/assets/59511689/a6576cf7-0028-4c45-9ffd-b9bab8df3942">

출력이 다음과 같이 되는 이유는 의도한 공백일까요?

2024-03-31 12:30 UTC, jamie9504 commented on src/main/java/chess/controller/ChessGame.java
> +        );
Map을 수정 가능한 상태로 정의해도 될까요?

2024-03-31 12:30 UTC, jamie9504 commented on src/main/java/chess/controller/ChessGame.java
>      public void run() {
<img width="307" alt="image" src="https://github.com/woowacourse/java-chess/assets/59511689/40df4035-b100-4d9b-af74-672c8ca421c6">

기본 상태에서 해당 점수가 맞는지 체크해주세요.

<img width="374" alt="image" src="https://github.com/woowacourse/java-chess/assets/59511689/b991f154-35ee-4c51-a229-a8ee86e82d7e">

King을 잡아서 끝난 방을 이어서 할 수 있네요!

<img width="277" alt="image" src="https://github.com/woowacourse/java-chess/assets/59511689/0bf71253-6eb6-482e-82b0-2acbb34185e1">

한 번 움직이면 바로 게임이 종료되긴 하지만요,

<img width="312" alt="image" src="https://github.com/woowacourse/java-chess/assets/59511689/69cefc94-1232-4f0a-b116-35fc7ca1bf42">

집념으로 상대쪽 왕도 잡을 수 있었어요 😃 

<img width="368" alt="image" src="https://github.com/woowacourse/java-chess/assets/59511689/d33f52ee-1ad8-40ae-9732-db02404fa1fa">

집념으로 두 왕을 다 잡았지만 점수 계산도 할 수 있었어요 😃

2024-03-31 12:30 UTC, jamie9504 commented on src/main/java/chess/controller/ChessGame.java
> +        Room roomWithoutId = Room.from(command.getArgument(1), command.getArgument(2));
정적팩터리메서드 명명규칙을 알아볼까요?
from에 어울리는 메서드인가요?

2024-03-31 12:30 UTC, jamie9504 commented on src/main/java/chess/controller/ChessGame.java
> +        int roomId = room.id().value();
> 한 줄에 점을 하나만 찍는다.

디미터의 법칙에 대해서 알아볼까요?

2024-03-31 12:30 UTC, jamie9504 commented on src/main/java/chess/db/DatabaseConfiguration.java
> +
불필요한 개행은 제거해볼까요?

전반적으로 개행 포함 코드스타일을 맞춰봐주세요!

2024-03-31 12:30 UTC, jamie9504 commented on src/main/java/chess/db/JdbcConnection.java
> +    private static final JdbcConnection INSTANCE = new JdbcConnection();
`INSTANCE`라는 이름이라면, 싱글턴 패턴에 대해 알아보는 것도 좋겠네요 😄

2024-03-31 12:30 UTC, jamie9504 commented on src/main/java/chess/domain/board/Board.java
>          if (sourcePiece.getColor() != turn) {
getColor를 해와서 비교해주어야 할까요?

2024-03-31 12:30 UTC, jamie9504 commented on src/main/java/chess/domain/board/Board.java
> +                .filter(piece -> piece instanceof Pawn)
instanceof란 무엇인가요?
instanceof를 사용한다면, 상속의 다형성을 잘 이용했다고 볼 수 있을까요?

2024-03-31 12:30 UTC, jamie9504 commented on src/main/java/chess/domain/board/BoardFactory.java
> +        return PIECES_ARRANGEMENT.get(file.getIndex()).apply(pieceColor, square);
> 한 줄에 점을 하나만 찍는다.

코드 전반적으로 프로그래밍 요구사항을 지켜주세요.

2024-03-31 12:30 UTC, jamie9504 commented on src/main/java/chess/domain/game/room/RoomId.java
> +        if (!value.matches("-?\\d+")) {
어떤 내용인지 한 번에 짐작하기 어려운 정규식의 경우엔 상수로 빼거나 변수로 빼주면 좋겠죠?

2024-03-31 12:30 UTC, jamie9504 commented on src/main/java/chess/domain/piece/Piece.java
움직일 때 piece는 board 정보를 받고, board는 piece를 가지고 있는 상황이네요!
이런 구조는 좋은 구조일까요?

2024-03-31 12:30 UTC, jamie9504 commented on src/main/java/chess/domain/square/File.java
> +    public char toInput() {
메서드명으로 적합한 이름인가요?

2024-03-31 12:30 UTC, jamie9504 commented on src/main/java/chess/domain/square/Move.java
> +public record Move(int roomId, Square source, Square target) {
RoomId객체를 사용하지 않고, int를 사용하는 이유는 무엇인가요?

2024-03-31 12:30 UTC, jamie9504 commented on src/main/java/chess/dto/GameStatus.java
> +public record GameStatus(double whiteScore, double blackScore) {
> 모든 원시 값과 문자열을 포장한다

2024-03-31 12:30 UTC, jamie9504 commented on src/main/java/chess/dto/PieceDrawing.java
>      public static PieceDrawing from(final Piece piece) {
이 친구를 꼭 Board가 호출해주어야 하는걸까요?
(지난번 코멘트의 연장선)

2024-03-31 12:30 UTC, jamie9504 commented on src/main/java/chess/repository/MoveDao.java
> +public class MoveDao implements MoveRepository {
Dao와 Repository는 어떤 의미의 차이가 있나요?

2024-03-31 12:30 UTC, jamie9504 commented on src/main/java/chess/repository/MoveDao.java
> +        }
> 함수(또는 메서드)의 길이가 10라인을 넘어가지 않도록 구현한다.

2024-03-31 12:30 UTC, jamie9504 commented on src/main/java/chess/view/PieceColorMapper.java
> +public enum PieceColorMapper {
쓰는 Enum인가요?

2024-03-31 12:30 UTC, jamie9504 commented on src/main/resources/ddl.sql
> +);
move 정보를 저장하는 방법과 piece 정보를 저장하는 방법이 있을텐데,
move 정보를 저장하는 방식을 선택했을 때는 어떠한 장/단점이 있을까요?

<img width="28" alt="image" src="https://github.com/woowacourse/java-chess/assets/59511689/57708810-35b8-468f-af58-5f2fe1250f99">
는 개행을 해주어야겠죠? 전반적으로 한 번 확인해주세요!

2024-03-31 12:30 UTC, jamie9504 commented on src/test/java/chess/db/DatabaseInitializerTest.java
> +class DatabaseInitializerTest {
테스트코드를 돌리면 방 번호 기준이 AUTO_INCREMENT되면서 올라가는군요!
의도된 구현인가요?

2024-04-01 07:48 UTC, geoje commented on README.md
> +```
운영체제간의 출력을 고려하지 못했습니다!
콘솔 출력의 `\t` 을 조절하기 힘든 것 같습니다...
다음과 같이 우측 부분을 제거했습니다 ㅠㅠ

``` java
+-------------------------------------------------------
| 우아한 체스 게임
+-------------------------------------------------------
| 게임 시작: start [white유저이름] [black유저이름]
| 게임 재개: resume [방번호]
| 방 리스트: room
| 유저 정보: user [유저이름]
| 이동: move [source위치] [target위치]
| 승패 및 점수: status
| 게임 종료: end
+-------------------------------------------------------
```

2024-04-01 07:51 UTC, geoje commented on src/main/java/chess/controller/ChessGame.java
> +        );
`Map.of` 를 사용하면 `Unmodifiable` 로 정의되는 것으로 알고 있습니다!
따라서, 필드인 `invockers` 는 수정되지 않습니다...!

![image](https://github.com/woowacourse/java-chess/assets/22692687/0f95cb8a-d68b-4bfa-b2bd-21b8d7703455)

2024-04-01 07:55 UTC, geoje commented on src/main/java/chess/controller/ChessGame.java
>      public void run() {
제이미의 집념에 감탄은 금치 못하였습니다... 😶😵🤪

2024-04-01 07:58 UTC, geoje commented on src/main/java/chess/controller/ChessGame.java
>      public void run() {
초기 점수에 대해 제가 룩을 `5`점이 아닌 `7` 점으로 부여했었네요!
기능 요구 사항을 잘못 적용한 불상사를 초래했습니다...
실제 프로젝트였다면 기획자 에게 욕을 먹지 않았을까 싶습니다 😅
![image](https://github.com/woowacourse/java-chess/assets/22692687/7aa3102d-9c60-400c-9f12-303f6e892853)

2024-04-01 08:06 UTC, geoje commented on src/main/java/chess/controller/ChessGame.java
>      public void run() {
끝난 방을 다시 들어가면 진행을 못하게 해야한다는 것을 인지하였지만 그것에 대한 테스트(코드로든 직접으로든)를 하지 않았다는 것이 저 자신에게 너무 아쉽네요 ㅠㅠ
지금은 아래와 같이 끝난 방에 입장 할 경우해당 상태를 보여준 뒤 커맨드를 다시 받도록 수정하였습니다!
![image](https://github.com/woowacourse/java-chess/assets/22692687/b2e3d956-32b2-49ae-99b3-9eb1d2b29e86)

2024-04-01 08:10 UTC, geoje commented on src/main/java/chess/controller/ChessGame.java
> +        Room roomWithoutId = Room.from(command.getArgument(1), command.getArgument(2));
`from` 과 `of` 에 대해 매개변수 개수에 따른 명명 규칙을 알아왔습니다!!!
이제` Room.of` 로 변경하였습니다!

### 메서드 명명 방식

1. from
매개 변수를 하나 받아서 해당 타입의 인스턴스를 반환하는 메서드에 주로 사용합니다.
``` java
Date date = Date.from(instnace);
```

2. of
여러 매개변수를 받아 적합한 타입의 인스턴스를 반환하는 집계 메서드에서 주로 사용합니다.
``` java
List list = List.of(1, 2, 3);
```

2024-04-01 08:53 UTC, geoje commented on src/main/java/chess/controller/ChessGame.java
> +        int roomId = room.id().value();
줄여서 `LoD` 라고 불리는 디미터의 법칙은 평소 생각하면서도 정말 적용하기 어려운 부분인 것 같습니다 ㅠㅠ
**객체의 속사정을 몰라야 한다**

Editing now...

2024-04-02 04:42 UTC, geoje commented on src/main/java/chess/db/DatabaseConfiguration.java
> +
알려주신 부분 뿐만 아니라 많은 부분에 개행 컨벤션이 지켜지지 않고 있었네요 ㅠㅠ
프로덕션과 테스트 모든 코드에서의 개행 관련 컨벤션을 수정하였습니다!

2024-04-02 05:26 UTC, geoje commented on src/main/java/chess/db/JdbcConnection.java
> +    private static final JdbcConnection INSTANCE = new JdbcConnection();
네, 싱글턴 패턴을 간략하게만 알고 있었는데 이번에 정확하게 학습하게 되었습니다!

**클래스에 인스턴스가 하나만 있도록 한다** 는 기본 적인 의미이고,
사용하는 일반적인 이유는 **일부 공유 리소스(DB, File) 에 대한 접근을 제어하기 위함 이라고 합니다!

생성자 호출은 반드시 새 객체를 반환해야 하기 때문에 싱글턴을 일반 생성자로 구현할 수는 없고, 전역 접근 지점을 제공해야 합니다.

필드의 접근 제어를 `public` 으로 하는 방법도 있겠지만 저는
저는 이를 `getConnection()` 이라는 메서드를 통해 가져갈 수 있도록 정적 `Getter` 를 사용하였습니다.

또한 여기서 중요 포인트로 추후 **멀티 스레딩**을 환경을 지원할 때 인스턴스 생성 시점에 `Lock` 을 걸어 여러 인스턴스가 생성되지 않도록 해야한다는 것도 중요합니다!

하지만 단점으로는 이 패턴을 통해 한 번에 두 가지의 문제를 동시에 해결하기 때문에 **단일 책임 원칙**을  위반한다고 합니다!

또한 단위 테스트에도 어려움이 있기 때문에 싱글턴의 한계를 극복할 수 있는 더 나은 방법을 강구하는 것도 좋다고 생각됩니다.

다른 크루들의 얘기를 들어보니 `Spring JDBC` 를 하게되면 1차 감탄을 하게 된다던데 `Spring` 에서는 `JDBC` 문제를 어떻게 극복했을 지 궁금해집니다!

2024-04-02 05:47 UTC, geoje commented on src/main/java/chess/domain/board/Board.java
>          if (sourcePiece.getColor() != turn) {
`isColor` 라는 메서드를 만들어 가져오는 것이 아니라 비교하는 행위를 시키도록 변경하였습니다!

``` java
public boolean isColor(PieceColor color) {
    return color == this.color;
}
```

또한 `Color` 쪽도 디미터의 법칙을 지키지 못하는 것으로 확인되어 `getColorName` 과 `getColorType` 함수를 `Piece` 에 추가하여 `.` 을 2회 사용하는 것을 줄였습니다!

2024-04-02 07:01 UTC, geoje commented on src/main/java/chess/domain/board/Board.java
> +                .filter(piece -> piece instanceof Pawn)
결론은 `Piece` 에 정의되어 있던 `getType` 메서드를 사용하였습니다!

추상 메서드로 `isPawn` 이나 `isKing` 과 같이 하여 점수 계산, 게임 종료 체크를 하는 것은 추후에 캐슬링과 같은 새로운 요구사항이 생겼을 때 `isRook` 과 같은 메서드를 생성하도록 하여 만약 기물이 몇십개가 되면 각 기물들마다 특수한 요구사항에 사용하기 위해 메서드를 만들어야 한다는 단점이 있는 것으로 보입니다.

따라서, 기물 타입을 `Enum` 으로 사용하였기에 이를 `getType` 메서드를 통해 반환하고 `Board` 는 이를 비교하여 특별한 상황을 수행할 수 있게 해주었습니다!

2024-04-02 07:08 UTC, geoje commented on src/main/java/chess/domain/board/BoardFactory.java
> +        return PIECES_ARRANGEMENT.get(file.getIndex()).apply(pieceColor, square);
변수와 라인 분리를 통해 해당 부분을 지키게 되었고 나머지 부분도 모두 확인하여 `.` 이 한 라인에 2개 이상 오지 않도록 하였습니다!!

``` java
Square square = Square.of(file, rank);
int fileIndex = file.getIndex();
return PIECES_ARRANGEMENT.get(fileIndex)
        .apply(pieceColor, square);
```

2024-04-02 07:17 UTC, geoje commented on src/main/java/chess/domain/board/BoardFactory.java
> +        return PIECES_ARRANGEMENT.get(file.getIndex()).apply(pieceColor, square);
디미터의 법칙일 지키기 위해 아래 같은 변경사항에 대해서는 어떻게 생각하시는지 궁금합니다...!
불필요한 변수와 라인 분리가 오히려 많이 일어난 것 같아서 입니다!

이러한 것을 `IntputView` 의 역할이 크다고 봐야하는 걸까요?
`InputView` 의 책임을 하기 위해 이정도 했다고 생각하는데 불필요한 분리인지 제이미의 의견이 궁금합니다!

**[변경 전]**
``` java
return List.of(scanner.nextLine().trim().split(COMMAND_DELIMITER));
```

**[변경 후]**
``` java
String line = scanner.nextLine();
String trimmedLine = line.trim();
String[] splitLineByDelimiter = trimmedLine.split(COMMAND_DELIMITER);
return List.of(splitLineByDelimiter);
```

2024-04-02 07:18 UTC, geoje commented on src/main/java/chess/domain/game/room/RoomId.java
> +        if (!value.matches("-?\\d+")) {
앗! 그러네요 `NUMERIC_PATTERN` 라는 정적 상수 필드로 분리하였습니다!

2024-04-02 07:33 UTC, geoje commented on src/main/java/chess/domain/piece/Piece.java
`step` 부터 상당히 고민을 많이 하고 크루들과 소통을 했던 부분이었습니다.

기물들은 스스로 움직이고 자신의 점수 상태를 계산할 수 있어야 한다
따라서 보드는 기물에게 `움직여!` 또는 `점수 몇점이야!` 라고 메세지를 보내 받기만 하도록 할 수 있으며 이를 하기 위해서는 기물들 또한 주변 기물들의 상태를 알아야 했습니다.

이 때, 보드가 들고있는 `Set<Piece>` 전체를 주게 될 경우 다른 피스들에게 접근이 가능하여 피스가 다른 피스의 상태를 직접적으로 변경 시킬 수 있는 상태가 되므로 (Board를 넘겨줘서 이 상황을 해결하지는 못함) 다른 피스들의 상태를 체크해줄 수 있는 메서드가 정의된 `Board` 를 넘겨주게 되었습니다.

만약 피스들은 인자로 움직임 위치를 받아 움직이게만 한다면 점수 체크와 피스의 움직임에 대한 체크 등은 모두 보드에서 이루어 질 것이며 이는 단일 책임 원칙을 위배하는 것이고 보드의 책임이 너무 방대해 진다고 생각하였습니다.

좋은 구조라고 생각은 되지 않지만 필요한 상황이라 그렇게 하였고 더 좋은 케이스는 어떤 것이 있을지도 궁금합니다.

2024-04-02 07:38 UTC, geoje commented on src/main/java/chess/domain/square/File.java
> +    public char toInput() {
`convertToKey`로 변경하였습니다!

동사 접두어의 명명 규칙을 또 지키지 못하였네요... 모든 메서드를 확인하여 명명 규칙이 지켜지지 않은 부분을 수정하였습니다.

2024-04-02 07:48 UTC, geoje commented on src/main/java/chess/domain/square/Move.java
> +public record Move(int roomId, Square source, Square target) {
앗... 이 부분은 실수 입니다!
`Move` 객체 생성 이후에 `RoomId` 의 필요성을 느껴 만들게 되었는데 해당 부분을 변환하지 못하였던 것 같습니다.

**모든 원시값을 포장한다** 라는 규칙이 있어도 이 원시 값이 현재에는 여기 있는 객체 속에서 다른 필드들과 포장되어도 충분하다 생각하였지만 이후에 판단이 변경되었을 때 모든 것을 변경하지 못하였습니다...

원시 값을 포장과 같이 특정한 의미를 하는 것을 감싸는 행동을 하였을 때 관련된 부분을 한번 다시 살펴보는 습관을 가져야겠습니다...!

2024-04-02 07:59 UTC, geoje commented on src/main/java/chess/dto/GameStatus.java
> +public record GameStatus(double whiteScore, double blackScore) {
`Score` 라는 객체를 만들어 원시값을 포장하였으며 다른 곳에서도 원시 값이나 문자열을 검증 없이 단독 사용되는 경우를 체크하였습니다!

2024-04-02 08:09 UTC, geoje commented on src/main/java/chess/dto/PieceDrawing.java
>      public static PieceDrawing from(final Piece piece) {
`Board` 에서 호출하지 않을 경우 결국 `Controller` 가 도메인과 뷰의 연결 점이라 생각되어 여기에서 수행하게 될텐데 결국 보드가 들고 있는 기물들의 (위치, 색상, 타입) 정보가 필요하게 됩니다!

그렇다고 `Board` 자기 자신이 관리하고 있는 `Set<Piece>` 를 `Getter` 로 만들어 `Controller` 가 사용하는 것도 `Controller` 에서 피스의 상태를 변경할 수 있으므로 위험하다 생각되었습니다.

결국 `Board` 내에 있는 `Piece` 컬렉션을 잘 감쌀 수 있고 뷰에게 전달하여 출력할 수 있도록 하는 최소한의 정보를 담는 `PieceDrawing` 이라는 `DTO` 객체가 생성하였다고 판단하였습니다.

2024-04-02 08:36 UTC, geoje commented on src/main/java/chess/repository/MoveDao.java
> +public class MoveDao implements MoveRepository {
`DAO` 는 `DB` 와 조금 더 가까운 `CRUD` 만을 하는 역할을 하고
`Repository` 는 `DB` 에서 가져와진 값을 조금 더 객체 기반으로 다루어주는 역할을 한다고 판단하였습니다!

따라서 제 상황의 경우 `MoveDao` 의 네이밍 보다 `MoveRepositoryImpl` 정도로 지을 수 있다고 생각이 됩니다...!

`DAO` 라는 것에 의미를 조금 더 정확하게 알고 사용해야 할 것 같습니다.

참조 문헌: [https://www.baeldung.com/java-dao-vs-repository](https://www.baeldung.com/java-dao-vs-repository)

2024-04-02 08:40 UTC, geoje commented on src/main/java/chess/view/PieceColorMapper.java
> +public enum PieceColorMapper {
앗... 사용이 필요 없어 졌는데 제거를 하지 않았네요.
테스트 코드 까지 제거 완료 하였습니다!

리팩토링 할 때 단순 `0 Usage` 를 볼 것이 아닌  `Usage` 가 `Test` 에서만 사용되는지도 확인해야 할 것 같습니다!

2024-04-02 08:56 UTC, geoje commented on src/main/java/chess/repository/MoveDao.java
> +        }
`Optional` 과 메서드 분리를 사용하여 `null` 처리 및 메서드 라인 컨벤션도 지킬 수 있었습니다!!

2024-04-02 14:23 UTC, geoje commented on src/main/resources/ddl.sql
> +);
전체적으로 마지막 EOL 을 작성해주었습니다!
또한 기존 자바 파일에는 `format on save` 기능을 켜두어 괜찮았는데 `.sql` 파일에 적용이 안된 것 같습니다..!
기능을 도와줄 뿐 직접 눈으로도 확인해야겠습니다! 😀

2024-04-02 14:25 UTC, geoje commented on src/test/java/chess/db/DatabaseInitializerTest.java
> +class DatabaseInitializerTest {
네, 방 번호는 유니크하게 증가하도록 설계하였습니다.
조금 더 고도화 하여 설계를 할 수만 있다면 굳이 유저에게 유니크한 방 번호를 입력하게 및 보여주지 않고 `resume [username]` 을 입력하면 계속 진행 할 방은 선택하도록 하는 방법도 있을 것이라 생각되었습니다.

현재로써는 `AUTO_INCREASEMENT` 면 충분하다고 판단하였습니다!!!

2024-04-03 06:52 UTC, jamie9504 approved these changes
안녕하세요. 새양 😄 리뷰어 제이미입니다.

1레벨 마지막 미션인 체스 고생 많으셨습니다 👏 
코멘트를 조금 남겨두었으니, 시간 되실 때 확인해주시면 좋을 것 같습니다.

남은 버퍼 기간 및 방학 기간도 즐겁게 보내시길 바랍니다.
이만 Approve & Merge합니다.

2024-04-03 06:52 UTC, jamie9504 commented on README.md
> +```
콘솔에서 작업할 때는, 운영체제간 출력이 다를 수 있다는 것을 항상 고려해주면 좋습니다 👍 

README도 같이 수정이 되어야 겠지요?

2024-04-03 06:52 UTC, jamie9504 commented on src/main/java/chess/controller/ChessGame.java
> +        );
사실 Map.of를 무지성으로 사용하는 경우가 있어서, 찔러보는 겸 남겨뒀던 코멘트였습니다 😉

2024-04-03 06:52 UTC, jamie9504 commented on src/main/java/chess/controller/ChessGame.java
>      public void run() {
요구사항의 정의가 이렇게 중요하답니다!

어떤 부분까지 테스트를 해야하는지도 항상 고려하면 좋을 것 같아요 😉 
인지한 부분은 놓치지 않고 진행해주는 것도 잊지 마세요!

2024-04-03 06:52 UTC, jamie9504 commented on src/main/java/chess/controller/ChessGame.java
> +        int roomId = room.id().value();
디미터의 법칙이 나오게 된 배경이나, 지켰을 때 어떤 장점이 있을지도 알아보면 좋습니다.
그 부분을 새양이 인지하여 아 이래서 필요하구나가 되어야 의식을 덜 하더라도 지키기 쉬울 것이에요!

2024-04-03 06:52 UTC, jamie9504 commented on src/main/java/chess/domain/board/Board.java
> +                .filter(piece -> piece instanceof Pawn)
결국 instanceof를 피하기 위해 각각의 Piece 구현체가 새로운 Enum인 PieceType을 반환하는 형태가 되어버렸네요!
PieceType을 사실상 인스턴스 변수로 가지고 있어야 했던 상황으로도 보이고, PieceType과 구현체들의 의미가 중복되는 느낌도 드네요 😃

2024-04-03 06:52 UTC, jamie9504 commented on src/main/java/chess/domain/board/BoardFactory.java
> +        return PIECES_ARRANGEMENT.get(file.getIndex()).apply(pieceColor, square);
디미터의 법칙이 나오게 된 배경을 한 번 확인해주세요.
객체에 대해서는 디미터의 법칙을 기반하여 리팩터링을 해주시고,

메서드 체이닝을 한 부분은 개행을 통해 가독성을 향상시켜줄 수 있겠죠 !

2024-04-03 06:52 UTC, jamie9504 commented on src/main/java/chess/domain/piece/Piece.java
결국 두 클래스는 서로가 서로를 조작할 수 있는 상황인데요.

board는 인스턴스변수로 piece 정보를 가지고 있으므로 클래스 어디서든 piece를 조작할 수 있고,
piece는 board를 파라미터로 받으니 특정 메서드 (현재 2개) 내부에서는 board를 조작할 수 있습니다.

현재의 구조는 그렇지 않지만, 추후 기능을 늘려가거나 리팩터링을 하는 과정에서
호출하는 것이 서로 물고 물리는 관계가 되면 어떻게 될까요? 😃 

순환참조에 대해 조금 더 알아보고, 고민해보면 좋을 것 같습니다.

더 좋은 케이스라기보단 다른 케이스들은 버퍼기간에 크루들과 각자 구현한 구조에 대해 토론해보는 것도 좋겠네요!

2024-04-03 06:52 UTC, jamie9504 commented on src/main/java/chess/dto/PieceDrawing.java
>      public static PieceDrawing from(final Piece piece) {
그럼 결국 View를 위한 객체인 Dto를 만드는 작업을 도메인이 하게 되는거네요 !
View에서의 요건이 변경되었을 때, Dto도 변경될 수 있는데 그 여파를 도메인까지 받는 것이 좋은 구조일지 고민해보세요.

2024-04-03 06:52 UTC, jamie9504 commented on src/main/java/chess/repository/MoveDao.java
> +public class MoveDao implements MoveRepository {
이름을 Impl로 짓는다면, 네이밍에 문제가 있거나 잘못된 추상화라고 생각합니다.
인터페이스의 구현이라는 의미밖에 담기지 않으니까요. 클래스 네이밍에 조금 더 힘을 써주세요!

2024-04-03 06:52 UTC, jamie9504 commented on src/test/java/chess/db/DatabaseInitializerTest.java
> +class DatabaseInitializerTest {
실제 DB가 테스트로 인해 영향을 받는 부분에 대한 코멘트였습니다 😃 
Autoincrement 부분이라 문제는 없겠지만, 불필요하게 번호가 올라가긴 하겠죠?

2024-04-03 06:52 UTC, jamie9504 commented on build.gradle
> +    runtimeOnly("com.mysql:mysql-connector-j:8.3.0")
runtimeOnly란 무엇인가요?
runtimeOnly가 dependencies 블록의 해당 위치에 추가된 이유가 있나요?

2024-04-03 06:52 UTC, jamie9504 commented on src/main/java/chess/controller/ChessGame.java
> +    private final Map<CommandType, Consumer<Command>> invokers;
> 3개 이상의 인스턴스 변수를 가진 클래스를 쓰지 않는다.

프로그래밍 요구사항을 지켜서 리팩터링해봐도 좋을 것 같네요 😃

2024-04-03 06:52 UTC, jamie9504 commented on src/main/java/chess/controller/ChessGame.java
>      }
WinnerName / WinnerUserName 은 어떤 느낌의 차이가 있을까요?

PieceColor가 White, Black만 있어서, 해당되지 않는 경우 ""를 내려주는 것과 예외를 내려주는 것은 어떤 차이가 있을까요?

2024-04-03 06:52 UTC, jamie9504 commented on src/main/java/chess/db/DatabaseConfiguration.java
> +    }
메서드로 제공해주는 것과 상수로 제공해주는 것은 어떤 차이가 있을까요?

2024-04-03 06:52 UTC, jamie9504 commented on src/main/java/chess/domain/board/Board.java
> +    private static final int SINGLE_KING_COUNT = 1;
SINGLE은 사실 ONE이랑 비슷하게 결국 1을 의미할 것 같은 용어죠!
이름을 지어줬을 때 역할을 명확히 명시하지 않는다면, 매직넘버로 두는 것과 차이가 없을 수 있습니다.

예를 들자면 `private static final int ONE = 1;` 처럼요!

2024-04-03 06:52 UTC, jamie9504 commented on src/main/java/chess/domain/board/Board.java
> +    }
GameStatus는 DTO군요.

Domain이 DTO를 아는 것과, DTO가 Domain을 아는 것 중 어떤 것이 새양의 기준에서 더 자연스러운 일일지 고민해보면 좋을 것 같아요 😃

2024-04-03 06:52 UTC, jamie9504 commented on src/main/java/chess/domain/board/Board.java
> +    public PieceColor getWinnerColor() {
get-과 find- 각각의 접두사로 시작하는 메서드는 어떤 의미를 가지게 되는지 알아봐도 좋을 것 같아요.

2024-04-03 06:52 UTC, jamie9504 commented on src/main/java/chess/domain/board/Board.java
> +                .filter(piece -> piece instanceof King)
instanceof를 쓰는 것이 자연스러운지 고민해보세요.
부모 객체로 사용하지만, 자식 객체인지 타입을 검증해야 하니까요!

2024-04-03 06:52 UTC, jamie9504 commented on src/main/java/chess/domain/game/User.java
> +        validateLength(name);
이런 경우에도 메서드 분리를 해주어야 할까요?

2024-04-03 06:52 UTC, jamie9504 commented on src/main/java/chess/domain/game/room/RoomId.java
> +        if (!value.matches(NUMERIC_PATTERN)) {
String의 matches 내부 구현을 확인해볼까요?
Pattern 객체는 비용이 큰 객체일거에요 😃 그럼 어떻게 해야 좋을까요?

2024-04-03 06:52 UTC, jamie9504 commented on src/main/java/chess/dto/Score.java
> +    private void validatePositive(double value) {
0은 positive인가요?

2024-04-03 06:52 UTC, jamie9504 commented on src/main/java/chess/domain/piece/Bishop.java
> +    public double getScore(Board board) {
사실상 board가 필요하지 않은 구현이죠, board를 넘겨준건 순수 폰 때문인 것 같은데 이런 구조가 상속을 바르게 쓴 구조일까요?

2024-04-03 06:52 UTC, jamie9504 commented on src/main/java/chess/dto/UserStatus.java
> +        final List<Room> inProgressRooms = rooms.stream().filter(room -> room.getWinnerName().isEmpty()).toList();
스트림의 경우 체이닝을 하면서 사용하게 되는데,
개행없이 쭉 사용할 경우와 개행을 사용할 경우 각각 가독성에 어떤 차이가 있을지 고민해보세요.

2024-04-03 06:52 UTC, merged