[4단계 - DB 적용] 아루(이동훈) 미션 제출합니다.
woowacourse/java-chess pull request #772
Opened 2024-03-30 15:30 UTC by donghoony

안녕하세요 비밥 🤠🤠 4단계로 돌아왔습니다.

지난 3단계 구현에서 미처 `push`하지 못한 게 있어서 초반에는 해당 내용이 들어가 있습니다... 3단계 head 커밋 기준으로 컴파일이 되지 않더라고요 😥 꼼꼼히 확인해봐야겠습니다

Jdbc 관련한 지식이 없어 맨바닥에 헤딩하는 느낌이었습니다 😶 계층을 하나 더 나눠야할 것 같아, 기존 `ChessGame`이 `Controller`가 되었습니다. `Service` 계층이 `Dao`를 통해 데이터베이스와 직접 통신하게 됩니다.

지금까지 하던 대로, 작성하면서 느낀 점들은 코드에 적어두겠습니다. 매번 고맙습니다 😎

2024-03-30 15:42 UTC, donghoony commented on src/main/java/chess/game/state/Paused.java
> +public abstract class Paused implements GameState {
진행 중 `END` 커맨드 입력 시, 기존 내용을 모두 저장하고 종료할 필요가 있습니다. 이때, `Controller`에서의 `isPlaying`을 탈출할 방법이 없어 상태를 추가했습니다.

2024-03-30 15:42 UTC, donghoony commented on src/main/java/chess/game/state/GameState.java
>  public interface GameState {
각 `State`는 상태를 가지지 않고 서로 전이하므로 싱글톤을 적용해 보았습니다

2024-03-30 15:42 UTC, donghoony commented on src/main/java/chess/dao/PieceMapper.java
> +public enum PieceMapper {
`DB`에 적용하기 위한 것은 `View`에서 값을 조회하기 위한 `getter`와 비슷한 맥락으로 사용 가능하다고 생각했습니다.

2024-03-30 15:42 UTC, donghoony commented on src/main/java/chess/service/GameService.java
> +public class GameService {
지금까지의 프리코스/미션에서는 `Controller - Service` 관련 네이밍을 사용하는 것을 지양했습니다. `Spring`에서 온 네이밍이기도 하고, 해당 클래스가 그 네이밍을 대표할 수 없다고 생각했기 때문이예요. 계층이 확실히 나뉜 이번 DB 미션에서는 `Controller`가 `Service`를 사용하고, `Service`에서 `DB`에 접근한다는 맥락으로 충분히 사용할 수 있다고 보았습니다.

2024-03-30 15:42 UTC, donghoony commented on src/main/java/chess/game/ChessGame.java
>  public class ChessGame {
`ChessGame`은 이제 작은 도메인이 되었습니다. `Service`에서 직접 다뤄지고, `ChessGame`이 다른 도메인과 상호작용하는 방식이 되었습니다. 계층과 책임이 잘 나뉘어졌을지 궁금합니다. 어떻게 보면 `Service`에서 `ChessGame`의 메서드를 그대로 넘겨주는 느낌이 들기도 해요.

2024-03-31 06:19 UTC, pci2676 requested changes
도메인 로직에 대해서는 이전 리뷰에서 많이 이야기를 충분히 나눈것 같습니다.

이번에는 새로운 객체간 역할과 책임의 범위에 대해 이야기해보면 좋을것 같습니다.

리뷰 확인 부탁드립니다.

2024-03-31 06:19 UTC, pci2676 commented on docker/db/mysql/init/init.sql
> +);
많은 사람의 게임을 동시에 지원할 수 있는 구조가 되면 좋을것 같습니다.

2024-03-31 06:19 UTC, pci2676 commented on docker/db/mysql/init/init.sql
> +);
DB에 어떻게 무엇을 저장할지는 구현세부사항입니다.  
특정 타입을 DB 수준에서 제어한다면 도메인 수정이 용이하지 않게 될 수 있습니다.  
도메인을 유연하게 변경할 수 있으면 더 좋을것 같습니다.

2024-03-31 06:19 UTC, pci2676 commented on src/main/java/chess/dao/ChessGameJdbcDao.java
> +    }
`private final PieceDao pieceDao;`

ChessGameJdbcDao에 구현하지 않고 별도의 인터페이스, 구현체를 둔 이유는 무엇인가요?

2024-03-31 06:19 UTC, pci2676 commented on src/main/java/chess/game/ChessGame.java
>  public class ChessGame {
> 어떻게 보면 Service에서 ChessGame의 메서드를 그대로 넘겨주는 느낌이 들기도 해요.

저는 Service는 Dao와 소통하는 창구가 되어주는 역할을 하고 있어 보여서 괜찮아 보입니다.  
다만 조금 더 책임을 부여하면 좋을것 같아보이기는 하네요.

2024-03-31 06:19 UTC, pci2676 commented on src/main/java/chess/controller/ChessController.java
> +    }
저는 Dto 에서는 바로 domain 객체를 생성해도 괜찮을것 같습니다.

controller에 별도의 로직이 많이 구현되는 것을 지양하는 것은 지양하는 것이 좋아 보입니다.

2024-03-31 06:19 UTC, pci2676 commented on src/main/java/chess/controller/ChessController.java
> +        PathDto pathDto = inputView.readPosition();
아니면 바로 View에서 바로 position을 전달해주는것도 이상해보이지 않습니다.

의존성을 따져보았을때 view가 domain에 그것도 불변한 값 객체에 의존하는것은 이상하지 않을것 같습니다.

2024-03-31 06:19 UTC, pci2676 commented on src/main/java/chess/controller/ChessController.java
> +public class ChessController {
controller의 역할과 책임이 어디까지라고 생각하고 계신가요?

생각하고 계신 역할과 책임의 범위에 대해 이야기해보면 좋을것 같습니다.

2024-03-31 12:12 UTC, donghoony commented on src/main/java/chess/dao/ChessGameJdbcDao.java
> +    }
각 책임을 따로 보았기 때문이예요. `Game`은 전반적인 게임 자체를 진행하는 것을 목표로, `Piece`는 각 기물을 저장하는 것을 목표로 했습니다. 데이터베이스 테이블이 서로 다르기도 하고요.

2024-03-31 12:13 UTC, donghoony commented on src/main/java/chess/controller/ChessController.java
> +    }
컨트롤러에 별도 로직을 지양하라는 말씀이시겠죠 😎

2024-03-31 12:14 UTC, donghoony commented on src/main/java/chess/controller/ChessController.java
> +        PathDto pathDto = inputView.readPosition();
저도 이 부분은 고민을 많이 했습니다. 도메인 객체를 어느 계층까지 끌어올려도 괜찮은가? 에 대한 결론이 게임 흐름을 관장하는 부분까지였는데요 (페어와 합의를 본 부분) - 불변 객체에 한해서는 (Enum이나 Position 등) View까지 올라와도 괜찮다고 생각해요. 물론 도메인의 변경이 잦으면 `Dto`를 만드는 것을 고려하겠으나, 체스라는 굳건한 도메인상에서는 괜찮겠네요!

2024-03-31 12:19 UTC, donghoony commented on src/main/java/chess/controller/ChessController.java
> +    }
적어도 이번 네 개의 미션에서는 Dto라는 것을 사용하는 것을 지양하는 것을 목표로 했었지만, 레이어 간 통신을 위해, 관례적으로 Dto라는 표현을 사용하게 되었네요. 비록 View-Controller 사이 연결이었지만 Dto에서 도메인을 생성하는 것은 괜찮다는 게 결론입니다. 도메인과 Dto 중 더 수정 가능성이 높은 건 Dto 쪽이라서예요. 😊

2024-03-31 12:21 UTC, donghoony commented on src/main/java/chess/controller/ChessController.java
> +        PathDto pathDto = inputView.readPosition();
한 번에 두 개의 값(source, destination)을 받아오기 때문에, `PathDto`에서 `Position`을 생성합니다.

2024-03-31 12:30 UTC, donghoony commented on src/main/java/chess/dao/ChessGameJdbcDao.java
> +    }
만약 말씀하신 내용이 `ChessGameDao`를 인터페이스로 둔 것에 대한 질문이라면, 구현을 최대한 미루기 위해서 인터페이스를 우선 사용했습니다. `Dao`를 구현하는 것보다 `Service`를 구현하는 것이 먼저라고 생각했어서, 인터페이스를 기준으로 `Service`의 뼈대를 잡았습니다. (거의 동시에 구현돼서 커밋은 Dao쪽이 먼저 되었어요.)

2024-03-31 12:32 UTC, donghoony commented on src/main/java/chess/controller/ChessController.java
> +public class ChessController {
> controller에 별도의 로직이 많이 구현되는 것은 지양하는 것이 좋아 보입니다.

위쪽 코멘트와 일맥상통하는 것 같습니다. 현재 `Game`을 다루는 모습이 `Service`에 가면 좋지 않을까 싶네요. `Controller`에서는 `View`와 `Service` 사이의 의존을 떼어내고자 흐름을 담당하는 것이라, 저번에 말씀해주신 리모컨에 다시 비유해보면 되려나요 🤔

2024-03-31 12:33 UTC, donghoony commented on docker/db/mysql/init/init.sql
> +);
오? `DB` 자체에서의 `check`은 필요하지 않을 수도 있겠다 싶네요. 결국 어플리케이션 내부 객체 매핑 과정에서 예외가 터진다면 그걸로 DB의 무결성(?)을 확인할 수 있네요! 결국 도메인-DB 간 결합이 강하게 되었네요 😂

2024-03-31 12:34 UTC, donghoony commented on docker/db/mysql/init/init.sql
> +);
'어? 외부에서 직접 DB를 통해 올바르지 않은 값이 들어가게 된다면 어플리케이션이 정상적으로 작동하지 않을 텐데?' 라는 생각에 `check`를 작성하게 되었습니다.

2024-03-31 14:57 UTC, donghoony commented on src/main/java/chess/controller/ChessController.java
> +public class ChessController {
와, 비밥이 말씀해주셨던 *추상화 수준*이라는 것이 점점 와닿고 있습니다. 컨트롤러에서는 결국 메서드를 활용하는 수준으로 전체적인 흐름을 잡아주고, 세부 구현은 해당 클래스에서 진행하는... 🤯🤯🤯

2024-03-31 14:58 UTC, donghoony commented
비밥 안녕하세요, *컨트롤러가 무슨 역할을 해야 하는가?* 에 대해 좀 더 많이 생각해본 결과 이와 같은 코드가 되었습니다. 주셨던 질문들에 대한 대답은 `resolve`하지 않았으니 한 번 확인해주시면 감사하겠습니다. 처음에는 막막했는데 몇몇 실마리를 던져주신 덕분에 많이 나아간 듯하네요. 확인해주시고 더 보완할 점을 남겨주세요 😊

2024-03-31 15:04 UTC, donghoony commented on docker/db/mysql/init/init.sql
> +    room_name varchar(50) primary key not null,
`id` 개념이 필요해 이를 `room_name`으로 두었습니다. 이제 방 이름으로 체스게임에 입장합니다.

2024-03-31 15:04 UTC, donghoony commented on src/main/java/chess/controller/ChessController.java
> +    public ChessController(InputView inputView, OutputView outputView, GameService gameService) {
더 이상 `Controller`에서 `ChessGame`을 다루지 않습니다. 이는 다양한 곳에서의 접근을 허용하기 위함입니다. `DB`에 가해지는 부하가 조금 커지겠지만, 전자를 허용하는 구현을 위해서는 이 방법이 좋다고 생각했어요. 나아가 `Controller`에서 직접적인 도메인 의존성을 떼어낼 수 있습니다. 모든 명령어는 `Service`에게 올바른 형태로 전달됩니다.

2024-03-31 15:04 UTC, donghoony commented on src/main/java/chess/controller/ChessController.java
> +    public void loopGame(String roomName) {
이 부분은 그래도 로직을 담고 있다고 생각하는데, 결국 콘솔 게임이라 루프를 도는 것에 대한 책임은 컨트롤러인 것 같아 이대로 두었습니다.

2024-03-31 15:04 UTC, donghoony commented on src/main/java/chess/dao/ChessGameDto.java
> +public record ChessGameDto(String name, Map<Position, Piece> pieces, GameState gameState) {
요청 시에 사용하는 `Dto`와 결괏값 반환을 위해 사용하는 `Dto`는 따로 구현해야 하나요? 안에 완전히 같은 값이 들어있어서 우선은 합쳐 두고, 추후에 달라질 일이 생기면 그때 나눠야겠다 싶었습니다.

2024-03-31 16:48 UTC, donghoony commented on src/main/java/chess/controller/ChessController.java
> +public class ChessController {
돌아보니 던져주신 질문에 대한 대답은 하지 않았네요.. 😅
`Controller`는 `Service`가 생긴 이상, `View`에 결과를 전달하고, 어떤 명령을 실행할지 골라주는 역할을 한다고 볼 수 있겠습니다. 딱 리모컨과 같다고 보여지네요.
현재 레이어 상으로는: 
```
         View
          |
      Controller
          |
       Service  ---- Dao ---- Database
          |
     Domain (Game)
          |
  세부 Domain (Square, ...)
```
와 같은 느낌이 되겠네요.

2024-03-31 17:02 UTC, pci2676 commented on src/main/java/chess/dao/ChessGameJdbcDao.java
> +public class ChessGameJdbcDao implements ChessGameDao {
데이터베이스 connection을 이용하는 행위는 다음과 같이 추상화 해볼수 있습니다.

1. 쿼리작성
2. 쿼리파라미터주입
3. 쿼리실행
4. 결과추출

이를 추상화 하여 하나의 템플릿으로 제공해보는 것을 도전해보시면 좋을것 같습니다.

2024-03-31 17:02 UTC, pci2676 commented on src/main/java/chess/dao/ChessGameJdbcDao.java
> +    }
>각 책임을 따로 보았기 때문이예요. Game은 전반적인 게임 자체를 진행하는 것을 목표로, Piece는 각 기물을 저장하는 것을 목표로 했습니다. 데이터베이스 테이블이 서로 다르기도 하고요.

두 데이터는 ACID를 위배해서는 안되는것으로 보이는데 현재 상태에서 이를 보장할 수 있을까요?

2024-03-31 17:02 UTC, pci2676 commented on docker/db/mysql/init/init.sql
> +);
>'어? 외부에서 직접 DB를 통해 올바르지 않은 값이 들어가게 된다면 어플리케이션이 정상적으로 작동하지 않을 텐데?

이를 조금 다른 시각에서 바라본다면

애플리케이션에서 보장해야하는 정책을(책임을) DB가 책임지고 있게 되는것은 아닐까요?

>결국 도메인-DB 간 결합이 강하게 되었네요 😂

제가 생각하는 바를 정확히 잡아주신 것 같습니다 😄

2024-03-31 17:21 UTC, pci2676 requested changes
이전에 드린 리뷰는 모두 깔끔하게 반영해주신것 같습니다.

질문해주신 부분에 대한 답변을 남겨두었고

한번 시도해보면 좋을것 같은 부분이 보여 리뷰를 남겨두었습니다. 

거의 다 온 것 같네요! 😄

2024-03-31 17:21 UTC, pci2676 commented on src/main/java/chess/service/GameService.java
> +public class GameService {
👍

2024-03-31 17:26 UTC, donghoony commented on src/main/java/chess/dao/ChessGameJdbcDao.java
> +    }
같은 `Connection`을 들고있지 않기 때문에 `Atomicity` 보장이 안 되네요..! 고민해보겠습니다.

2024-04-01 08:19 UTC, donghoony commented
비밥 안녕하세요, 남겨주신 리뷰 보고 너무 재밌게 공부했습니다.
남겨주신 두 가지 요구사항은 Template 만들기, ACID 지키기였는데요, 전자를 먼저 구현하고 Atomicity를 지키기 위한 방법을 찾다 고민이 생겼습니다. 제 생각의 흐름은 아래와 같아요.

Dao 메서드에서도 하나의 일만 하는 게 맞다 (수정이면 수정, 조회면 조회...). Service 입장에서 각 메서드가 불릴 때마다 이전에 Connection 만들고, 끝나고 commit해야 한다 → 하나의 메서드가 하나의 Transaction 단위가 된다. 그래야 Atomicity를 지킬 수 있다.
1. Dao에서 메서드를 나누는 순간, JdbcTemplate을 사용하므로 커넥션을 매번 생성하게 된다.
2. Dao 메서드에서 connection을 인자로 받아오는 수밖에 없다 (개인적인 의견)
3. Service의 메서드 하나가 결국 하나의 Transaction 단위이다
4. 그럼 바깥에서 Connection을 주입하고 서비스 단위에서 커밋한다면?
5. 코드가 중복될 테니, 이걸 좀 더 추상화한다면?

Dao에서 Connection을 인자로 받으면 FakeDao를 만들기가 어려워진다. 테스트는 어떻게 할까?
Dao에서 Connection을 신경쓰지 않기 위해서 Template을 만들었다… 그런데 Connection이 오고가는 것이 Dao 차원에서 보이게 되면 Template의 의미가 퇴색되지 않을까? 메서드 전후로 콜백함수를 실행하는 방법이 있을까?

...이런 생각의 흐름이 이끌어낸 결과가 결국 리플렉션을 활용한 프록시 객체의 생성이었습니다. 조금은 과할 것 같지만 이렇게 하면 메서드가 하나의 일만 하면서 Atomicity를 지킬 수 있다는점이 매력적으로 다가왔습니다. 다른 해결 방법이 있음에도 제가 깊게 생각해보지 않았던 것인지 궁금하네요..! 구현해보는 방향성이 이 쪽이 알맞다고 생각하신다면 RC 주시면 감사하겠습니다. 한 번 더 진행해볼게요 🙂 (아직 Atomicity가 구현되지 않았습니다)

2024-04-01 14:10 UTC, donghoony commented
조금 도전을 해 보았습니다... 좋은 방향의 도전인지는 모르겠으나, `Service`에서 DB에 변형을 일으키는 `Dao` 콜이 한 개뿐이라는 것에서 착안된 아이디어에서 나오게 되었어요. 조금 더 복잡한 서비스라면 여러 DB에 읽고 쓰는 연산을 진행할 테니, 위쪽에서 이야기한 프록시 쪽이 더 알맞을 수도 있겠다는 생각입니다.

각각의 쿼리를 체이닝할 수 있도록 하고, 쿼리에 리턴값이 존재한다면 해당 값을 가지도록 합니다. 이를 통해 하나의 커넥션을 들고, 최종 커밋 이전에는 DB에 반영이 되지 않습니다. `ResultSet`도 `AutoClosable`이라, 각 행을 하나의 데이터로 가지는 `Map`을 들도록 했습니다.

대신 이 경우에도 매번 `QueryChain`을 생성할 때마다 `commitAndClose`를 해줘야하는 단점이 있었습니다 😂 그래도 DB 변형상의 atomicity는 지킬 수 있게 된 것 같아 우선 올려둡니다. 기존 `JdbcTemplate`을 사용하지 않게 되었습니다.

2024-04-01 22:06 UTC, pci2676 approved these changes
체스를 포함해 레벨 1 수행하느라 고생 많으셨습니다.

머지하겠습니다. 🚀 

즐거운 방학 보내세요.

2024-04-01 22:06 UTC, pci2676 commented on src/main/java/chess/dao/ChessGameJdbcDao.java
> +    }
오.. 사실 저는 template 정도만 구현하고 acid에 대해서는 한번 고민만 해보시면 좋겠다는 생각에 드린 리뷰였는데 이걸 다 구현해 주실줄은 몰랐습니다.

acid를 지키기 위해 하나의 connection을 계속해서 사용한다는 그림은 좋은것 같습니다. 고생하셨습니다. 👍

2024-04-01 22:06 UTC, pci2676 commented on src/main/java/chess/dao/ChessGameJdbcDao.java
> +        saveAllPieces(chain, chessGameDto.name(), chessGameDto.pieces());
게임 상태를 변경하고  
기존 데이터를 전부 지우고  
새로운 데이터를 다시 insert하는 구조로 보이는것 같습니다.

가능한 db를 통한 행위는 줄이는 것이 좋습니다.

사용자가 입력한 행위에 대한 정보만 순서에 맞춰 저장해 둔다면  
이를 토대로 replay하면 현재의 상태를 다시 복원할 수 있고, DB에 접근하는 횟수도 줄어들 수 있을것 같습니다.

데이터를 설계하는 방법도 여러가지가 있으니 다방면에서 고민해보시는 것을 추천드립니다.

2024-04-01 22:06 UTC, merged

2024-04-02 01:50 UTC, donghoony commented on src/main/java/chess/dao/ChessGameJdbcDao.java
> +        saveAllPieces(chain, chessGameDto.name(), chessGameDto.pieces());
DB는 결국 매우 느린 IO에 해당되니 줄여보는 게 좋겠네요. 처음에는 Move할 때 두 Piece의 위치만 옮기는 것을 고려했습니다. 비밥이 말씀해주신 대로 움직인다면 많은 움직임을 저장하는 하드웨어적 비용도 들 수 있다고 생각했기 때문이예요 😊 설계에 따라 코드가 바뀌는 경험도 했습니다. 너무 즐거웠어요 고맙습니다 🤗