[체스 3, 4단계] 폰드(권규택) 미션 제출합니다.
woowacourse/java-chess pull request #775
Opened 2024-03-30 19:47 UTC by tackyu

안녕하세요 알렉스! 6기 BE 폰드입니다.

이번 미션에서는 ScoreManager라는 클래스를 두어 점수 계산 로직을 구현하였습니다.
각 열에 위치한 체스 말들을 팀으로 구분한 다음, 점수를 계산하계끔 하였습니다.

db에는 익숙지 않아, 수업시간에 활용 했던 코드들을 조금씩 수정해서 구현하는데 그쳤습니다
start를 했을 때, 진행중인 게임이 없다면 chess_game 테이블에 새로운 게임을 추가하고, chessboard 테이블에 초기화된 체스판이 생성되게 했습니다.
end를 입력받아 게임이 종료된다면, 다시 실행 했을 때 그 게임을 이어받아서 하게끔 구현했고,
king이 잡혀서 게임이 종료된다면,  테이블을 초기화 시켜주고 최종 우승자를 출력하게 만들었습니다.

그리고 이번 미션에서 Role, State enum 클래스를 체스 말과 체스 게임의 상태를 알려주는데 많이 활용했는데,
이런 사용법에 대한 알렉스의 의견이 궁금합니다.

감사합니다!

2024-03-31 15:50 UTC, yxxnghwan requested changes
안녕하세요 폰드 이번 단계도 잘 구현해주셨네요!
생각해볼만한 코멘트 몇개 남겼습니다. 확인 부탁드려요! :)

2024-03-31 15:50 UTC, yxxnghwan commented on src/main/java/chess/domain/dao/ChessBoardDao.java
> +    }
public 메소드일 필요가 있나요?

2024-03-31 15:50 UTC, yxxnghwan commented on src/main/java/chess/domain/dao/ChessBoardDao.java
> +public class ChessBoardDao {
이 클래스에 있는 메소드들의 동작에 공통된 부분이 꽤 많은 것 같아요!

1. 커넥션 맺기
2. PrepareStatement 세팅
3. 쿼리 실행

이러한 패턴은 바뀌지도 않을 것 같은데, 중복으로 코드가 존재하네요! 중복을 제거할 순 없을까요?🤔

2024-03-31 15:50 UTC, yxxnghwan commented on src/main/java/chess/view/Command.java
> +    STATUS("status");
다음 enum이 추가될 때를 생각해서 세미콜론을 아래로 내리고 각 이넘마다 ,를 붙여 줬었는데 원래대로 돌아갔네요😂

2024-03-31 15:50 UTC, yxxnghwan commented on src/main/java/chess/domain/chesspiece/Role.java
> +    }
테스트하지 않아도 되는 메소드일까요?

2024-03-31 15:50 UTC, yxxnghwan commented on src/main/java/chess/domain/chesspiece/Role.java
> +    EMPTY(new Empty());
piece의 타입과 team이 합쳐서 관리되고 있는 것 같은데 어떻게 생각하시나요?

2024-03-31 15:50 UTC, yxxnghwan commented on src/main/java/chess/domain/chesspiece/Rook.java
>      }
상수로 관리되면 좋을 것 같지 않나요?!

2024-03-31 15:50 UTC, yxxnghwan commented on src/main/java/chess/domain/ScoreManager.java
> +        return 0.5 * count;
각 매직넘버들에 의미를 알기 어려운 것 같아요!

2024-03-31 15:50 UTC, yxxnghwan commented on src/main/createTable.sql
> +);
기물 데이터가 저장되는 테이블 같은데 piece라는 테이블명이 좀 더 맞지 않을까요?

2024-03-31 15:50 UTC, yxxnghwan commented on src/main/java/chess/controller/Controller.java
> +    }
board에 움직이는 동작을 수행한 후 그 상태를 db에 update하는 로직이네요.
만약 개발자의 실수로 db update하는 구문을 하나 누락하게 되었다면 사전에 어떤 방법을 사용해서 검증할 수 있을까요?
이러한 동작은 테스트코드가 필요하지 않은 걸까요?

2024-03-31 15:50 UTC, yxxnghwan commented on src/main/createTable.sql
> +
불필요한 공백인 것 같아요 :)

2024-03-31 15:50 UTC, yxxnghwan commented on README.md
> +
DB를 연결해서 실행하는 방법도 리드미에 작성하면 어떨까요?

2024-03-31 15:50 UTC, yxxnghwan commented on .gitignore
> +docker/db
이거 통째로 안올리는거 맞을까요? docker/db/data 만 안올려도 될 것 같아서요!

2024-03-31 15:50 UTC, yxxnghwan commented on src/main/java/chess/domain/ScoreManager.java
> +        Position startPosition = Position.of("a1");
position이 a1 과 같은 형태로 입력된다는건 view의 요구사항 아닐까요? 이 클래스가 알아도 될까요?

2024-03-31 16:26 UTC, tackyu commented on src/main/java/chess/domain/dao/ChessBoardDao.java
> +    }
private이 적절한 것 같습니다!

2024-03-31 17:56 UTC, tackyu commented on src/main/java/chess/view/Command.java
> +    STATUS("status");
수정하였습니다!😅

2024-03-31 18:59 UTC, tackyu commented on .gitignore
> +docker/db
올리는 기준에 대해서 알려주실 수 있나요?

2024-04-01 04:56 UTC, tackyu commented on src/main/java/chess/domain/dao/ChessBoardDao.java
> +public class ChessBoardDao {
private PreparedStatement setPreparedStatement(String query) throws SQLException {
        return getConnection().prepareStatement(query);
    }
이런 방법으로 1번과 2번을 묶었습니다.
쿼리 실행 코드의 중복을 처리하는 방법에 대해서 힌트를 얻을 수 있을까요?🥲

2024-04-01 06:19 UTC, tackyu commented on src/main/java/chess/domain/chesspiece/Role.java
> +    EMPTY(new Empty());
Function<Team, Piece> 필드를 만들고, Team.findTeam 메서드를 통해서 팀을 찾아내도록 수정했습니다.
piece의 타입과 team이 합쳐서 관리되면, 코드에서 실수할 여지가 줄어들것 같은데, 좋지 않은 방법인지 궁금합니다.
팀을 일일이 적어주어야하는 불편함 때문인가요??

2024-04-01 06:27 UTC, tackyu commented on src/main/java/chess/domain/ScoreManager.java
> +        return 0.5 * count;
ScoreManager에서 pawn의 점수를 상수로 갖고 있게 수정했습니다

2024-04-01 06:31 UTC, tackyu commented on src/main/createTable.sql
> +);
코드에서 piece가 각 위치를 갖고 있지 않고, 체스 보드가 기물을 갖고 있게끔 구현해서, 테이블도 chessboard로 명명하였습니다!

2024-04-01 07:26 UTC, tackyu commented on README.md
> +
docker-compose -p chess up -d와 같은 명령어를 명시하라는 말씀이신가요??

2024-04-01 07:28 UTC, tackyu commented on src/main/java/chess/domain/ScoreManager.java
> +        Position startPosition = Position.of("a1");
Position이 뷰에 의존하게 된 걸 고려하지 못했습니다🥲
인덱스를 받는 Position 생성자를 추가하였습니다

2024-04-01 08:42 UTC, tackyu commented on src/main/java/chess/controller/Controller.java
> +    }
move가 정상적으로 동작하는 지 확인하기 위한 테스트 코드가 필요할 것 같습니다!
진행되는 게임이 없는 상태를 나타내기 위한, chess_game_id가 -1인 경우를 사용해서 테스트 코드를 작성했습니다.
그런데 해당 메서드를 테스트하기 위해 접근 제어자를 default로 변경하였는데, 더 나은 방법이 있을까요??

2024-04-01 08:52 UTC, tackyu commented on src/main/java/chess/domain/ScoreManager.java
> +        Position startPosition = Position.of("a1");
a1과 같은 형태로 입력받는 것은 도메인인 Position이 아예 갖지 않는게 나을까요??

2024-04-02 05:36 UTC, yxxnghwan commented on src/main/java/chess/domain/dao/ChessBoardDao.java
> +public class ChessBoardDao {
jdbc를 사용해 쿼리를 실행하는 유형들을 잘 추상화해보면 좋을 것 같아요..!

1. 쿼리로 데이터를 읽어들여서 원하는 형태로 만드는 메소드
2. 쿼리를 실행시켜 DB를 변경시키는 메소드

이렇게 두개만 있으면 될 것 같아요!
추가적인 힌트를 드리자면 함수형 인터페이스를 활용해보시면 좋은 구조가 될 것 같습니다!

2024-04-02 05:38 UTC, yxxnghwan commented on src/main/java/chess/domain/chesspiece/Role.java
> +    EMPTY(new Empty());
현재는 정해진 갯수의 팀과 기물타입들이 존재하지만, 추가될 여지가 있는 경우에는 유지보수성이 많이 떨어지는 구조일 것 같아요..!
뭔가 하나 추가될 때마다 다른 enum의 갯수만큼 추가해줘야 하니까요!

2024-04-02 05:45 UTC, yxxnghwan commented on .gitignore
> +docker/db
올려주신 docker-compose.yml 파일상 `docker/db/init/init.sql` 파일이 존재해야 컨테이너가 뜨면서 DB 스키마도 같이 생성될 것 같아요! 
추후 회사에 지원하여 과제를 하게 되었을 때를 대비해서 과제 검토자의 간편한 실행을 위한 세팅을 고민해보시면 좋을 것 같아요!

2024-04-02 05:46 UTC, yxxnghwan commented on src/main/java/chess/controller/Controller.java
> +    }
저장소의 상태를 변경하는 로직을 묶어서 담당하는 역할을 가진 클래스가 있으면 어떨까요? 그 클래스의 public 메소드를 테스트하면 좋을 것 같아서요!

2024-04-02 05:46 UTC, yxxnghwan commented on README.md
> +
추후 회사에 지원하여 과제를 하게 되었을 때를 대비해서 과제 검토자의 간편한 실행을 위한 세팅을 고민해보시면 좋을 것 같아요!

2024-04-02 06:00 UTC, yxxnghwan requested changes
안녕하세요 폰드! 거의 다 왔네요! 생각해볼만한 코멘트 좀 더 남겼습니다!
마지막까지 화이팅이에요! 💪

2024-04-02 06:00 UTC, yxxnghwan commented on src/main/java/chess/domain/ScoreManager.java
> +        for (int i = 0; i < 8; i++) {
8은 어떤 숫자일까요?

2024-04-02 06:00 UTC, yxxnghwan commented on src/main/java/chess/domain/chessboard/ChessBoard.java
> +        checkTeam(target, piece);//이동~ 같은 팀이면 예외
주석의 의미를 메소드 이름에 녹이는건 어떠신가요?

2024-04-02 06:00 UTC, yxxnghwan commented on src/main/java/chess/domain/chesspiece/Piece.java
> +    protected double score;
score는 같은 기물이면 모두 같은 값을 가질 것 같은데 각 기물 클래스에 상수로 관리하는건 어떠실까요?

2024-04-03 04:59 UTC, tackyu commented on src/main/java/chess/domain/ScoreManager.java
> +        for (int i = 0; i < 8; i++) {
체스판 Column의 사이즈입니다😅
Column의 사이즈를 반환하는 메서드로 대체하였습니다!

2024-04-03 05:09 UTC, tackyu commented on src/main/java/chess/domain/chessboard/ChessBoard.java
> +        checkTeam(target, piece);//이동~ 같은 팀이면 예외
검증의 의미를 담을 수 있도록 checkObstacle과 checkTeam의 메서드를 변경하였습니다!

2024-04-03 05:19 UTC, tackyu commented on src/main/java/chess/domain/chesspiece/Piece.java
> +    protected double score;
굳이 필드로 갖을 필요가 없을 것 같네요😅
감사합니다!

2024-04-03 06:26 UTC, tackyu commented on src/main/java/chess/domain/dao/ChessBoardDao.java
> +public class ChessBoardDao {
dao에는 위 두개의 메서드만 갖고, 사용하는 클래스에서 직접 쿼리를 넣어주는 형식을 의미하신게 맞나요??

2024-04-04 06:00 UTC, tackyu commented on README.md
> +
감사합니다!

2024-04-04 06:01 UTC, tackyu commented on .gitignore
> +docker/db
도커가 docker/init 폴더의 init.sql을 실행시켜서 테이블을 생성되도록 했습니다.
감사합니다!

2024-04-04 06:54 UTC, tackyu commented on src/main/java/chess/domain/dao/ChessBoardDao.java
> +public class ChessBoardDao {
PrepareStatement 세팅은 StatementSetter 인터페이스를 통해서 하도록 하고,
1번과 2번은 DaoExecutor 클래스에 changeDB와 processData로 추상화 하도록 변경해보았습니다!

2024-04-04 08:13 UTC, tackyu commented on src/main/java/chess/controller/Controller.java
> +    }
저장소가 변경되는 로직을 담당하는 DBManager란 클래스를 생성해주었습니다!

2024-04-04 08:16 UTC, tackyu commented on src/main/java/chess/domain/chesspiece/Role.java
> +    EMPTY(new Empty());
아 만약 Green이 추가된다면 모든 기물에 Green을 추가한 enum이 필요하다는 말씀이시군요!
한정된 기물만 생각하고 설계를 진행해서 유지보수성을 미처 고려하지 못한 것 같습니다🥲

2024-04-04 15:31 UTC, yxxnghwan approved these changes
안녕하세요 폰드! 레벨1 수고 많으셨습니다! 코멘트 잘 반영해주셨네요! 이번 단계에서 할만한 고민은 충분히 해주신 것 같아 이만 머지하도록 할게요! 다음 레벨도 화이팅입니다! 💪

2024-04-04 15:31 UTC, merged