[3, 4단계 - 체스] 제리(김민정) 미션 제출합니다.
woowacourse/java-chess pull request #786
Opened 2024-03-31 13:03 UTC by mzeong

2024-04-01 14:41 UTC, syoun602 requested changes
안녕하세요 제리!

3,4 단계 시간내에 잘 구현해주셨네요 💯
원래 폴더 구조를 변경하면 어쩔 수 없는 부분이라 생각합니다 😁
리뷰하면서 궁금했던 부분들 위주로 남겨봤습니다!
고민을 많이 하셨다고 하셨는데, 어떤 고민들이 있었는지도 남겨주면 좋겠네요 👍

2024-04-01 14:41 UTC, syoun602 commented on README.md
>  ### 입력
꾸준히 업데이트하는 모습 좋습니다 👍👍

2024-04-01 14:41 UTC, syoun602 commented on build.gradle
> +    runtimeOnly("com.mysql:mysql-connector-j:8.3.0")
runtimeOnly로 사용하신 이유가 있나요? 다른 api, implementation, comileOnly 등과는 어떤 차이가 있을까요?

2024-04-01 14:41 UTC, syoun602 commented on src/main/java/chess/service/GameDaoImpl.java
> +    private static final String PASSWORD = "root";
현재는 dao가 하나라서 분리할 필요가 없지만 커넥션을 만드는 객체를 분리해보는건 어떨까요?

2024-04-01 14:41 UTC, syoun602 commented on src/main/java/chess/service/BoardConverter.java
> +public enum BoardConverter {
이렇게 모두 converter를 이용해서 domain<->view를 분리했는데 하시면서 느낀 장단점을 공유해주실 수 있나요 😊

2024-04-01 14:41 UTC, syoun602 commented on src/main/java/chess/service/GameDaoImpl.java
> +            return null;
커넥션을 획득하려 했는데, null을 리턴해도 될까요?

2024-04-01 14:41 UTC, syoun602 commented on src/main/java/chess/service/GameDaoImpl.java
> +    }
오호 하나의 테이블로 생성하셨네요 👍
해당 방식을 선택하게 된 계기가 궁금합니다!!

2024-04-01 14:41 UTC, syoun602 commented on src/test/java/chess/service/GameServiceTest.java
> +        gameService = new GameService(new GameDao() {
Dao를 왜 따로 두었는지 살펴봤는데, 익명 객체를 사용하셨네요!
`FakeGameDao`와 같은 클래스를 만들지 않고 이렇게 사용하신 이유가 궁금합니다~

2024-04-01 14:41 UTC, syoun602 commented on src/main/java/chess/domain/piece/WhitePawn.java
> +    }
package-private 접근제어자를 사용하는 이유가 있을까요?

2024-04-01 14:41 UTC, syoun602 commented on src/main/java/chess/service/GameDaoImpl.java
> +             final var preparedStatement = connection.prepareStatement(query)) {
여기만 `final var`가 적용되어 있네요 👀

2024-04-02 06:03 UTC, mzeong commented on src/main/java/chess/domain/piece/WhitePawn.java
> +    }
기물 관련 클래스들이 piece 패키지에 모여 있어서 package-private를 사용하였는데 
해당 클래스를 상속받은 클래스라면 접근 가능하도록 해야 문제가 생기지 않을 것 같아 protected로 변경하였습니다!

2024-04-02 06:37 UTC, mzeong commented on src/main/java/chess/service/GameDaoImpl.java
> +             final var preparedStatement = connection.prepareStatement(query)) {
네오가 `final var`를 사용하는 것을 보았는데 Connection, PreparedStatement, ResultSet으로 적는 것보다 코드가 깔끔한 것 같아 적용해 보았습니다 😅

일관성을 위해 `final var`를 모든 코드에 사용하거나 모두 사용하지 않는 편이 좋을까요?

2024-04-02 07:39 UTC, mzeong commented on src/main/java/chess/service/GameDaoImpl.java
> +    }
이전에 하던 체스 게임을 다시 시작할 수 있는 최소한의 형태로 테이블을 설계했습니다 

요구사항을 만족하기 위해 새로운 체스 게임을 만드는 InitialGameCreator 대신 이전 체스 게임을 만드는 GameCreator가 필요했어요
GameCreator는 Board와 BoardStatus를 제공하기 때문에 이 둘을 테이블의 열로 두고 DB에 저장 및 조회를 수행했어요

2024-04-02 08:07 UTC, mzeong commented on src/test/java/chess/service/GameServiceTest.java
> +        gameService = new GameService(new GameDao() {
GameService를 테스트하기 위해 FakeGameDao가 필요하지만 
FakeGameDao가 GameServiceTest라는 파일 하나에서만 사용되어 해당 파일 내에 익명 객체로 만들어 사용했어요 

저는 익명으로 만들어도 동일하게 FakeGameDao로써 기능한다고 생각하는데 썬은 FakeGameDao라는 클래스를 만들 때와 차이가 있다고 보시나요?

2024-04-02 13:19 UTC, mzeong commented on build.gradle
> +    runtimeOnly("com.mysql:mysql-connector-j:8.3.0")
아래와 같은 차이가 있음을 확인했습니다! 애플리케이션을 실행할 때만 필요하므로 runtimeOnly가 적절한 것 같아요

compileOnly - 컴파일 시점에만 필요
runtimeOnly - 런타임에만 필요
Implementation, api - 컴파일 및 런타임에 모두 필요 (단 api는 전이 의존성을 허용하므로 사용 지양)

2024-04-02 13:41 UTC, mzeong commented on src/main/java/chess/service/BoardConverter.java
> +public enum BoardConverter {
일단 단점은 기존에 존재하던 mapper와 거의 유사한 코드가 중복으로 생겼어요. 그러나 비교적 변경될 여지가 많은 뷰의 mapper를 사용해서 DB에 저장할 데이터로 변환하는 것은 적절하지 않다고 판단해서 별도로 converter를 만들었어요

저는 converter -> service -> dao 순으로 코드를 작성했는데, converter에 대한 테스트를 따로 먼저 진행하니 
이후에 service에 대한 테스트와 코드를 작성하는 것이 용이했습니다

사실 Map<Position, Piece>를 어떻게 데이터베이스에 넣어야 할지 모르겠어서 이렇게 변환해서 저장하는 것이 맞을지 고민이 많이 되었고 아직도 최선의 방법이라는 확신이 들지는 않는데, 더 나은 방법을 생각해내지 못했어요

2024-04-02 17:30 UTC, syoun602 requested changes
안녕하세요 제리!

빠르게 리뷰 반영해주셨네요 👍 추가적인 코멘트 남겨두었습니다!
체스 미션 잘 구현해주셔서 이만 머지해도 될 것 같은데, 혹시 더 중점적으로 봐줬으면 하는 부분이 있을까봐 RC로 둘게요. 추가 질문이 있다면 언제든 코멘트에 남겨주세요!

2024-04-02 17:30 UTC, syoun602 commented on src/main/java/chess/domain/piece/WhitePawn.java
> +    }
넵 package-private을 사용하게되면 패키지 변경에 의해 문제가 생길 수도 있기 때문에 최대한 지양하는게 좋아보입니다! 
사실  pakage-private을 실제로 사용하는 경우를 잘 보지 못하기도 했고, 만약 썼다하더라도 프로젝트가 커지는 과정에서 (패키지 변경이라던지) 문제가 생길 수 있을 것 같아요. 상속을 통해 구현된다는걸 명시하기 위해서라도 protected로 변경되는게 좋아보입니다.

변경하라는 뜻은 아니고 추후에 개발하시면서 생각해보면 좋을 것 같아 남길게요! 현재는 하위 객체에서 구현이 무조건 되야하기 때문에 protected로 열어둬야 하지만, 조금 더 나아가서 default와 protected를 최대한 사용하지 않는 방법을 구사하는 것도 추천드립니다. protected를 사용할 경우 결국 같은 패키지 내에서는 접근이 가능하기도 하고, 부모의 관점에서 캡슐화가 깨지기 때문인데요. 이렇게 되면 객체지향에서 흔히 얘기하는 LSP나 OCP 원칙에 위반할 확률이 높아집니다. 

관계는 부모-자식이지만, 각 클래스는 독립적인 객체이기 때문에 최대한 private 또는 public으로 작성하거나 상속 대신 합성을 사용하는 것도 방법일 것 같아요 😄

2024-04-02 17:30 UTC, syoun602 commented on src/main/java/chess/controller/GameManager.java
> +        GameService gameService = new GameService(new GameDaoImpl(new DatabaseConnector()));
의존성 주입 👍👍

2024-04-02 17:30 UTC, syoun602 commented on src/main/java/chess/service/BoardConverter.java
> +    private static Piece toObject(String string) {
toObject보다는 toPieces는 어떨까요?

2024-04-02 17:30 UTC, syoun602 commented on src/main/java/chess/service/DatabaseConnector.java
> +public class DatabaseConnector {
👍

2024-04-02 17:30 UTC, syoun602 commented on src/main/java/chess/service/GameDaoImpl.java
> +            }
else는 제거하는 방향으로 고쳐주세요 !

2024-04-02 17:30 UTC, syoun602 commented on src/main/java/chess/service/GameDaoImpl.java
> +             final var preparedStatement = connection.prepareStatement(query)) {
다른 코드에서는 final도 var도 사용하지 않는데, 여기서만 작성되어 있으면 의아하긴할 것 같아요.
지금 상황은 아니지만 누군가가 코드를 보고 여기서만 사용하는 이유가 있는지 찾게 되는 계기가 될 수도 있구요.
컨벤션을 단순히 코드를 예쁘게 만드는 것보다는 언어에 대한 문법을 작성한다고 봐주시면 좋을 것 같아요. 한글의 띄어쓰기나 받침처럼요! 나 하나 정도는, 여기서만이라는 생각으로 프로젝트에 참여한 모든 개발자가 자신만의 스타일로 작성하게 된다면 같은 자바 언어라도 완전히 다른 코드처럼 보여질 것 같아요. 🥲

2024-04-02 17:30 UTC, syoun602 commented on src/test/java/chess/service/GameServiceTest.java
> +        gameService = new GameService(new GameDao() {
메서드 하나만 가지고 있는 함수형 인터페이스와 같은 경우가 아니라면, 저는 주로 명확하게 구현체가 있음을 나타내도록 클래스를 작성하는 편입니다. 익명 객체를 사용할 경우 코드가 지저분해지는 점이 제일 크고, 프로젝트를 진행하면서 주로 한 곳에서만 사용되는 경우가 거의 없었거든요! 만약 추후에 방도 만들게 되고 roomService도 추가되면 다른 곳에서도 해당 dao를 필요로 할 수도 있겠네요.

하지만 굳이 [변경을 예측하기](https://blog.voidmainvoid.net/511)보다는 필요에 의해 분리하는게 더 좋은 자세인 것 같아요! 잘 사용하셨습니다 👍

2024-04-02 17:30 UTC, syoun602 commented on src/main/java/chess/service/BoardConverter.java
> +public enum BoardConverter {
넵 도메인이 db에 대한 의존성을 가지고 있지 않도록 잘 분리해주셨습니다 👍 dto 형식으로 사용하는 방법도 있었을텐데 mapper 방식으로 처리한 특별한 이유가 있나요??

2024-04-03 06:17 UTC, mzeong commented on src/main/java/chess/service/GameDaoImpl.java
> +             final var preparedStatement = connection.prepareStatement(query)) {
썬의 의견에 공감해요 읽거나 관리하기 쉽도록 코드를 작성해야 하는데 제가 중요한 것을 잠시 잊었네요!! 코드를 수정하였습니다 🙇‍♀️

2024-04-03 06:35 UTC, mzeong commented on src/main/java/chess/domain/piece/WhitePawn.java
> +    }
이전에는 package-private를 접근 제어자 중 한 가지로만 생각해서 종종 사용했는데, 썬의 리뷰를 통해 지양해야 할 필요성을 명확하게 이해했어요! `관계는 부모-자식이지만, 각 클래스는 독립적인 객체이다` 라는 말이 저의 기존 인식을 바꿔주네요 👍

썬의 리뷰 정말 재밌어요!! 다음에는 default와 protected를 최대한 사용하지 않는 방법으로 개발을 진행해 볼게요 (지난 번 남겨주신 DCI 패턴도 꼭 적용해보고 싶답니다) 좋은 리뷰 남겨주셔서 감사해요 🙇‍♀️

2024-04-03 08:15 UTC, mzeong commented on src/main/java/chess/service/BoardConverter.java
> +public enum BoardConverter {
특별한 이유가 있는 것은 아니고 제가 아직 dto를 사용할 정도로 잘 알지 못해서 dto 형식으로 사용하는 방법을 떠올리지 못했습니다!

2024-04-05 12:45 UTC, syoun602 approved these changes
안녕하세요 제리!
처음부터 잘해주셔서 크게 변경할 점이 없었는데, 리뷰 반영도 잘해주셨네요!! 
체스 미션동안 배워간게 많았으면 좋겠네요 😊 수고많으셨고 방학동안 편히 쉬세요! 고생많으셨습니다 😄

2024-04-05 12:45 UTC, merged