[체스 - 4단계] 초롱(정회성) 미션 제출합니다.
woowacourse/java-chess pull request #790
Opened 2024-03-31 17:22 UTC by HoeSeong123

안녕하세요 오리!!
드디어 마지막 리뷰요청이네요.
기쁘기도 하지만 한 편으로는 아쉬운 마음이 듭니다..😭

4단계 구현을 하면서 정말 어려운 점이 많았습니다.
아무래도 제가 데이터베이스를 처음 사용해봐서 더 어려웠던 것 같습니다..
그래도 다른 미션을 할 때는 프리코스 때부터 공부해온 것이 있어서 그런지 어느 정도 틀은 잡혀 있다고 생각하는데
이번 미션은 하면서도 계속 이렇게 하는 게 맞나.. 하는 생각이 자꾸만 들었습니다..😅

우선은 필수 요구사항만 만족시켰습니다!
선택 요구사항도 하고 싶었지만 어느덧 마지막 리뷰요청날이 다가왔기 때문에 어쩔 수 없이..😥

또한 리팩토링 하고 싶은 부분이 너무나도 많아서 다 고치고 제출할까 싶었지만 오리와 리뷰를 주고받으면서 고쳐나가고 싶어서 제출하게 되었습니다!
물론 마감기한이 다가왔기 때문도 있지만요..😅

## 궁금한 점
정말 많은 궁금한 점이 있지만 우선 가장 궁금했던 점에 대해서 질문드리겠습니다!

오리와 1,2 단계 리뷰를 주고 받으면서 각 피스들이 타입을 가지지 않고 equals를 통해서 비교를 하게 변경하였습니다.
하지만 데이터 베이스에 피스를 저장할 때는 반드시 type이라는 특성(?) 이 있어야 하는데 이를 어떻게 저장해야 할 지 감이 잘 오지 않았습니다.
결국 별도의 mapper를 사용하여 데이터베이스에 저장하고, 꺼내올 때만 사용하도록 하였는데 이게 맞는 방식인지 궁금합니다.

만약 별로 권장되지 않는 방법이라면 설계에서부터 잘못된 걸까요..😨

기물 뿐만 아니라 다양한 곳에서 설계를 잘못한 것 같다는 느낌을 많이 받았었습니다.
하지만 데이터베이스를 고려하지 않은 상태에서 설계를 진행했기 때문에 어쩔 수 없지 않았나 하는 생각도 듭니다.

이번 미션을 진행하면서 오리가 왜 3단계와 4단계를 나눠서 진행하는 것을 권장했는지 이해가 됐습니다.
`잘못 설계된` 도메인에 db를 적용하면 어떤 문제가 발생하는지, 전부는 아니지만 많이 느낄 수 있었던 미션이었습니다...😅

많이 늦었지만 마지막 리뷰 요청도 잘 부탁드립니다!!

2024-04-01 00:42 UTC, jinyoungchoi95 requested changes
안녕하세요 초롱 😄

4단계 잘 구현해주셨네요. 몇가지 코멘트 남겨두었으니 확인부탁드려요.

궁금하거나 고민이 되는 부분이 있으시다면 언제든 pr 코멘트 또는 dm으로 요청 부탁드립니다.
감사합니다 🙇‍♂️

2024-04-01 00:42 UTC, jinyoungchoi95 commented on src/main/java/chess/domain/dao/PieceMapper.java
> 오리와 1,2 단계 리뷰를 주고 받으면서 각 피스들이 타입을 가지지 않고 equals를 통해서 비교를 하게 변경하였습니다.
> 하지만 데이터 베이스에 피스를 저장할 때는 반드시 type이라는 특성(?) 이 있어야 하는데 이를 어떻게 저장해야 할 지 감이 잘 오지 않았습니다.
> 결국 별도의 mapper를 사용하여 데이터베이스에 저장하고, 꺼내올 때만 사용하도록 하였는데 이게 맞는 방식인지 궁금합니다.

데이터베이스와 객체지향간의 싱크가 맞지 않아 어쩔수없이 발생하는 문제라고 봐주시면 될 것 같아요. 말씀하신대로 데이터베이스는 type이라는 컬럼이 존재해야하는 상태로 설계를 할 수 밖에 없고, 객체지향에서 초롱이 설계해주신 상속는 type이라는 정보를 알 필요가 없도록 추상화하는 개념이기 때문에 type이 필요가 없는 거죠.

domain객체와 데이터베이스는 설계를 하는 관점에서 객체지향이 그 둘의 차이를 갈라놓기 때문에 현재와 같이 도메인으로 넘어가기 전, db의 데이터를 단순히 가져오는 `Mapper`와 같은 클래스를 두기도 해요.

2024-04-01 00:42 UTC, jinyoungchoi95 commented on src/main/resources/chessboard.sql
> 기물 뿐만 아니라 다양한 곳에서 설계를 잘못한 것 같다는 느낌을 많이 받았었습니다.
> 하지만 데이터베이스를 고려하지 않은 상태에서 설계를 진행했기 때문에 어쩔 수 없지 않았나 하는 생각도 듭니다.

이어서 이야기하면 데이터베이스를 고려를 꼭 했어야했을까요? 도메인의 설계와 db의 설계는 별개로 생각해도 되지 않을까요?

데이터베이스의 관점과 객체지향의 관점은 앞서이야기한대로 차이가 있기 때문에 더 객체지향적으로 설계할수록 db와는 멀어질수도 있다라고 생각해요. 현재 미션은 db를 직접 적용해보는 것이 목표이기 때문에 객체와 db의 괴리감에 대해서 너무 걱정하지 않으셔도 좋을 것 같아요.

2024-04-01 00:42 UTC, jinyoungchoi95 commented on src/main/resources/chessboard.sql
> +delete from board where position = 'a5';
실제로 운영되어야하는 `db.sql` 파일에는 테스트에 사용된 데이터는 제거해주세요.

2024-04-01 00:42 UTC, jinyoungchoi95 commented on src/main/resources/chessboard.sql
> +    team CHAR(5)    NOT NULL,
`piece`를 어떻게 설계하느냐에 따라서 다르겠지만 (`type`, `team`)은 unique해야하지않을까요?

2024-04-01 00:42 UTC, jinyoungchoi95 commented on src/main/java/chess/domain/dao/PieceMapper.java
> +public enum PieceMapper {
domain과 db의 괴리감으로 인헤 `Mapper`를 만들어주셨다면 `dao` 패키지는 어떻게보면 domain 패키지의 하위가 아닌 domain과 같은 레벨의 패키지가 아닐까요?

2024-04-01 00:42 UTC, jinyoungchoi95 commented on src/main/java/chess/domain/dao/PieceMapper.java
> +    private Piece piece;
```suggestion
    private final String type;
    private final String team;
    private final Piece piece;
```

2024-04-01 00:42 UTC, jinyoungchoi95 commented on src/main/java/chess/domain/dao/PieceMapper.java
> +    }
테스트가 필요해보여요 :)

2024-04-01 00:42 UTC, jinyoungchoi95 commented on src/main/java/chess/domain/dao/PieceDao.java
> +        } catch (final SQLException e) {
checked exception을 잘 처리해주셨네요 👍

2024-04-01 00:42 UTC, jinyoungchoi95 commented on src/main/java/chess/domain/dao/PieceDao.java
> +            String team = resultSet.getString("team");
`type`, `team`을 상수로 선언하고, query에서도 이를 재사용하는 방법이 더 안전하지 않을까요?

2024-04-01 00:42 UTC, jinyoungchoi95 commented on src/test/java/chess/domain/dao/PieceDaoTest.java
> +    }
```suggestion
    static void connection() throws SQLException {
        connection = ConnectionGenerator.getConnection();
        connection.setAutoCommit(false);
    }
```
1. 테스트메소드에서는 try-catch로 굳이 감싸주지 않으셔도 될 것 같아요.
2. connection을 다 쓴 이후에는 setAutoCommit을 true로 바꾸어줘야하지 않나요?

2024-04-01 00:42 UTC, jinyoungchoi95 commented on src/main/java/chess/domain/dao/PieceDao.java
> +    public Piece findPieceById(byte id) {
long, int가 아닌 byte로 설계된 이유가 있을까요?

2024-04-01 00:42 UTC, jinyoungchoi95 commented on src/test/java/chess/domain/dao/ChessGameDaoTest.java
> +            connection.rollback();
👍 

1. 각 테스트가 끝나고 데이터를 지우는 방식도 있었을텐데 해당방식을 사용한 이유가 있을까요?
2. rollback이 `ChessGameDao`에만 설정되어있네요.

2024-04-01 00:42 UTC, jinyoungchoi95 commented on src/test/java/chess/domain/dao/ChessGameDaoTest.java
> +                .doesNotThrowAnyException();
실제로 업데이트가 되었는지 데이터를 확인하지 않아도 되나요?

2024-04-01 00:42 UTC, jinyoungchoi95 commented on src/test/java/chess/domain/dao/ChessBoardDaoTest.java
> +        assertThat(result.get(new Position("b", "3"))).isEqualTo(new King(WHITE));
`assertAll`로 감싸주면 좋겠네요. 통합테스트가 진행됨에 따라 여러번 테스트 돌리기에는 속도가 더 느려질 가능성이 있어 하나의 테스트에서 최대한 많은 결과를 보는 것이 중요합니다.

2024-04-01 00:42 UTC, jinyoungchoi95 commented on src/main/java/chess/domain/dao/ConnectionGenerator.java
> +            return null;
연결이 오류가 났다면 그냥 exception을 터트려도 되지 않을까요?

2024-04-01 05:08 UTC, HoeSeong123 commented on src/main/resources/chessboard.sql
객체와 db에서 괴리감이 발생하는 것은 당연한 일이었군요!
당연히 도메인을 설계할 때 db를 고려해야 한다고 생각했는데 별개라고는 생각해보지 못했네요😅

2024-04-01 05:26 UTC, HoeSeong123 commented on src/main/resources/chessboard.sql
> +    team CHAR(5)    NOT NULL,
조합으로도 unique를 걸 수 있다는 것은 처음 알았네요😆

2024-04-01 07:29 UTC, HoeSeong123 commented on src/main/java/chess/domain/dao/PieceDao.java
> +    public Piece findPieceById(byte id) {
기물의 경우 그 종류가 많지 않아 메모리 절약 차원에서 TINYINT 데이터 타입을 사용했었습니다.

종류가 많지 않다고 하더라도 INT형이 일반적으로 사용되나요?

2024-04-01 07:31 UTC, HoeSeong123 commented on src/test/java/chess/domain/dao/ChessGameDaoTest.java
> +            connection.rollback();
1. 각 테스트마다 얼마만큼의 데이터가 추가되는 지 알 수 없기도 하고, 아직 데이터베이스를 다루는 것이 익숙치 않아 혹시나 지우면 안되는 데이터가 지워질 수도 있을 것 같아 `rollback`을 사용하게 되었습니다.

2024-04-01 07:55 UTC, HoeSeong123 commented on src/test/java/chess/domain/dao/ChessGameDaoTest.java
> +                .doesNotThrowAnyException();
처음에는 update가 아니라 addGameStatus 메소드여서 테스트 코드를 저렇게 작성했었는데 업데이트로 바꾸고 테스트 코드를 수정하는 것을 깜빡했네요😅

2024-04-01 08:16 UTC, HoeSeong123 commented
안녕하세요 거위! 주말 잘 보내셨나요?
슬랙에 들어갔더니 오리가 아닌 거위로 바뀌어있으셔서 깜짝 놀랐습니다🤣🤣

벌써 마감 기한이 다가와서 서둘러 피드백을 반영한 후 리뷰 요청 드립니다!!

2024-04-01 10:00 UTC, jinyoungchoi95 commented on src/main/java/chess/domain/dao/PieceDao.java
> +    public Piece findPieceById(byte id) {
메모리절약차원에서 사용하실수도 있는데 저는 굳이라는것이 더 커요. 그정도까지 메모리리스크를 감소하면서까지 다른 id 타입들과 일관성을 깨면서 성능을 올려야하냐라는 관점에서, 물론 그게 중요한것은 맞지만 요즘 하드웨어 퍼포먼스를 생각하면 그 이후 이걸 알아봐야하는 히스토리비용이 더 크다고 느끼는 편이거든요.

물론 `TINYINT`타입의 사용이 잘못되었다라는건 아니기때문에 이런 관점에서도 생각할 수 있다 정도로 넘어가주셔도 좋을 것 같아요.

2024-04-01 10:14 UTC, jinyoungchoi95 requested changes
안녕하세요 초롱 😄

피드백 잘 반영해주셨네요. 4단계에 필요한 학습과 구현을 충분히 진행하신 것으로 보여 머지하려고하는데요. 남겨둔 코멘트에 궁금하신 것이 있을까하여 request change드려요.

궁금하거나 고민이 되는 부분이 있으시다면 언제든 pr 코멘트 또는 dm으로 요청 부탁드립니다.
감사합니다 🙇‍♂️

2024-04-01 10:14 UTC, jinyoungchoi95 commented on build.gradle
> +    runtimeOnly("com.mysql:mysql-connector-j:8.3.0")
`runtimeOnly`는 어떤 기능으로 동작할까요? implementation, compileOnly, api와 무슨 차이가 있을까요?

2024-04-01 10:14 UTC, jinyoungchoi95 commented on src/main/java/chess/dao/ChessBoardDao.java
> +            }
dao의 책임은 어디까지일까요? 데이터베이스와 연결을 통해서 가져온 entity와 도메인 클래스를 연결시켜주는 것까지이고 해당 메소드구문은 비즈니스로직에 더 가깝지 않을까요?

dao 메소드는 최대한 단순하게 하나의 sql 구문을 처리할 수 있도록 변경해보세요. 이런 로직들은 dao를 사용하는 비즈니스 처리담당 클래스에서 처리하는것이 더 적절해보여요.

2024-04-01 10:14 UTC, jinyoungchoi95 commented on src/main/java/chess/dao/ConnectionGenerator.java
> +public class ConnectionGenerator {
private으로 생성자를 막아주면 좋겠네요.

2024-04-01 10:14 UTC, jinyoungchoi95 commented on src/main/resources/chessboard.sql
> +    CONSTRAINT type_with_team UNIQUE (type, team)
👍

2024-04-02 07:26 UTC, HoeSeong123 commented on build.gradle
> +    runtimeOnly("com.mysql:mysql-connector-j:8.3.0")
전혀 생각해보지 못한 부분인데 오리 덕분에 주변에 있던 크루들과 함께 공부해보았습니다😁
공부한 내용을 제 방식대로 정리해보았습니다.

우선 `runtimeOnly`와 `compileOnly`의 차이는 이름에서 드러나듯이 런타임시에만 사용, 컴파일시에만 사용으로 나누어집니다.
`compileOnly`의 대표적인 예로는 `lombok`이 있습니다. 컴파일 시에 getter, setter 등 필요한 것을 생성하고, 런타임 시에는 사용되지 않기 때문입니다.
`runtimeOnly`는 주로 DB 관련에서 사용됩니다.

implementation과 api의 차이는 public과 private의 차이와 비슷한 것 같습니다.
implementation을 사용한 의존성은 해당 모듈에서만 사용할 수 있고
api를 사용한 의존성은 해당 모듈에 의존하고 있는 모든 모듈도 사용할 수 있게 됩니다.

이 내용에 대해 공부하면서 모듈, 컴파일, 런타임 등등 개념이 애매했던 것들이 있었는데 해당 내용들도 다시 한 번 공부할 수 있었습니다😆😆

2024-04-02 07:54 UTC, HoeSeong123 commented on src/main/java/chess/dao/ChessBoardDao.java
> +            }
저 기능을 누구한테 맡겨야 하는지 애매했는데 `dao 메소드는 하나의 sql 구문을 처리한다` 라고 생각하니까 명확해지네요😁

2024-04-02 11:04 UTC, HoeSeong123 commented
마지막 리뷰 요청 드립니다 오리!
아직도 모르는 부분이 한가득이지만 뭘 모르는지조차 모르겠어서 질문을 드릴 수가 없네요😭
질문을 잘 할 줄 아는 것도 정말 중요한 것 같습니다..

마지막 미션을 오리와 함께 해서 정말 영광이었습니다😀
정말 감사드립니다 오리!!

2024-04-02 11:11 UTC, jinyoungchoi95 commented on build.gradle
> +    runtimeOnly("com.mysql:mysql-connector-j:8.3.0")
`api`는 말씀해주신대로 의존이 전파되기때문에 모듈 의존성을 복잡하게 만들어 지양한다는 점만 더 알고계시면 좋을것같아요.

2024-04-02 11:12 UTC, jinyoungchoi95 approved these changes
안녕하세요 초롱 😄

1레벨동안 고생많으셨습니다. 다음 레벨도 화이팅하세요 :)

감사합니다 🙇‍♂️

2024-04-02 11:13 UTC, merged