[3, 4단계 - 체스] 프린(남기범) 미션 제출합니다.
woowacourse/java-chess pull request #797
Opened 2024-04-01 04:34 UTC by GIVEN53

2024-04-01 16:52 UTC, syoun602 requested changes
안녕하세요 프린~ 👋

전체적으로 잘 구현해주셨네요 👍 선택 요구사항까지 다 하실줄이야 👀
대체로 질문같은 코멘트 몇개 남겨두었으니 확인 부탁드려요!

2024-04-01 16:52 UTC, syoun602 commented on README.md
> +### 체스 보드
문서 업데이트 👍

2024-04-01 16:52 UTC, syoun602 commented on build.gradle
> +    runtimeOnly("com.mysql:mysql-connector-j:8.3.0")
runtimeOnly로 설정하신 이유가 궁금합니다 😁

2024-04-01 16:52 UTC, syoun602 commented on src/main/java/Application.java
>  public class Application {
어디서 많이 본 구조네요 😮 
커넥션 풀까지 만들어둔게 인상깊네요! 💯
근데 아직 콘솔 어플리케이션인데 이렇게 스프링과 유사하게 + 레이어드 아키텍처로 구성하신 이유가 있으신가요?
하시면서 들었던 생각도 공유해주시면 좋을 것 같습니다 :)

2024-04-01 16:52 UTC, syoun602 commented on src/main/java/controller/board/BoardController.java
> +        });
```suggestion
        commands.put(BoardCommand.END, (ignore, roomId) -> {}); 
```
요게 더 한 눈에 들어오는 것 같아요!

2024-04-01 16:52 UTC, syoun602 commented on src/main/java/database/DefaultConnectionPool.java
> +    }
사실 지금 단계에서 얘기할 부분인지는 잘 모르겠지만, 구현해주셔서 남깁니다.
Connections가 모두 사용 중인 상태에서 getConnection 요청이 들어오면 어떻게 될까요? 🤔

2024-04-01 16:52 UTC, syoun602 commented on src/main/java/database/JdbcTemplate.java
> +    public void update(String query, Object... args) {
indent가 2 이상인 것 같아요 👀

2024-04-01 16:52 UTC, syoun602 commented on src/main/java/domain/board/ChessBoard.java
> +
stream의 filter 내부가 복잡하게 동작하고 있는데, 프린은 자바8에서 stream이 등장한 근본적인 이유가 무엇이라고 생각하시나요?

2024-04-01 16:52 UTC, syoun602 commented on src/main/java/domain/piece/Piece.java
> +    default double score() {
사실 저는 default 메서드를 잘 사용하지는 않으나 현재 구조에서 잘 적용해주신 것 같아요!
default 메서드가 나온 배경에 대해서 한번 알아봐도 좋을 것 같습니다 😊

2024-04-01 16:52 UTC, syoun602 commented on src/main/java/domain/position/Position.java
> +                        .map(rank -> Map.entry(toKey(file, rank), new Position(file, rank))))
toKey()보다는 inline 처리하는게 더 알아보기 쉬워보이는데, 어떻게 생각하시나요?

2024-04-01 16:52 UTC, syoun602 commented on src/main/java/controller/GateController.java
> +        while ((command = getCommand()) != GateCommand.END) {
변수로 추출할 필요가 없어보입니다~!

2024-04-01 16:52 UTC, syoun602 commented on src/main/java/controller/board/BoardController.java
> +    private final Map<BoardCommand, BiConsumer<List<String>, Integer>> commands;
커맨드 패턴이 어느 패키지에 종속되어야 하는지에 대해서는 크게 신경쓰지는 않을 것 같아요. (별도의 패키지로 두든 커맨드로 따로 추출하든) 관점에 따라 command가 도메인일 수도, 단순 view에 종속적인 하나의 응집된 행위일 수도 있을 것 같거든요. 아키텍처나 패턴을 사용하는 이유는 결국 더 유지보수하기 좋은 코드를 만들기 위함이지 무조건적으로 정답이 있는 부분이 아니기 때문에 프린이 생각하시기에 더 한 눈에 들어오는 방향으로 두시면 될 것 같습니다 😊

2024-04-03 06:01 UTC, GIVEN53 commented on build.gradle
> +    runtimeOnly("com.mysql:mysql-connector-j:8.3.0")
JDBC 드라이버는 데이터베이스와 통신하기 위해 사용하는 드라이버입니다 그래서 런타임에는 필수입니다
하지만 컴파일 타임에는 데이터베이스와의 통신이 필요하지 않기 때문에 runtimeOnly로 설정했습니다

추가로 컴파일 타임에만 필요할 경우 `compileOnly`를 사용할 수 있고, 런타임과 컴파일 타임 모두 필요하면 `implementation`을 사용합니다

2024-04-03 06:35 UTC, GIVEN53 commented on src/main/java/Application.java
>  public class Application {
dao를 구성하고 책임, 관심사를 분리하면서 자연스럽게 계층 구조의 아키텍처가 만들어진 것 같아요
애플리케이션이 작아서 장점을 크게 체감하지 못했지만 각 계층이 각자만의 역할을 수행하고 관심사가 명확하기 때문에
유지 보수가 용이하고, 하나의 계층에서 발생한 변경은 다른 계층에 영향을 주지 않을 것이라 생각했습니다!

2024-04-03 07:07 UTC, GIVEN53 commented on src/main/java/controller/board/BoardController.java
> +        });
우테코 컨벤션을 쓰고 있는데 코드 자동 정렬하면 개행이 돼요 🥲

2024-04-03 07:24 UTC, GIVEN53 commented on src/main/java/database/DefaultConnectionPool.java
> +    }
서로 다른 쓰레드가 같은 커넥션을 사용하는 경우가 발생합니다 트랜잭션이 공유되기 떄문에 데이터 일관성이 깨질 수 있습니다

Queue 자료구조를 사용해서 커넥션을 하나씩 꺼내고, 사용한 커넥션은 다시 반납하는 방식으로 수정했습니다!
그리고 커넥션풀은 여러 쓰레드에서 접근하기 때문에 thread safe를 보장할 수 있는 Queue 구현체에 대해 학습했어요
![image](https://github.com/woowacourse/java-chess/assets/101033262/d41484a8-d2e8-4f38-b570-7eb404c6cd5d)

여러 구현체 중 `ArrayBlockingQueue`가 현재 상황에 가장 적합하다고 판단해서 해당 구현체를 사용해서 수정했습니다

2024-04-03 07:36 UTC, GIVEN53 commented on src/main/java/domain/board/ChessBoard.java
> +
함수형 프로그래밍을 지원해서 코드의 간결성과 유지보수성을 높이기 위함이라고 생각해요
filter 내부 로직을 `isSameColorPawn()` 메서드로 추출해서 수정했습니다!

2024-04-03 08:05 UTC, GIVEN53 commented on src/main/java/domain/position/Position.java
> +                        .map(rank -> Map.entry(toKey(file, rank), new Position(file, rank))))
인라인으로 처리하는게 깔끔한 것 같아요 인라인으로 수정했습니다

2024-04-03 08:05 UTC, GIVEN53 commented on src/main/java/database/JdbcTemplate.java
> +    public void update(String query, Object... args) {
메서드를 분리해서 수정했습니다!

2024-04-03 08:06 UTC, GIVEN53 commented on src/main/java/controller/GateController.java
> +        while ((command = getCommand()) != GateCommand.END) {
변수 제거했습니다!

2024-04-03 11:41 UTC, syoun602 approved these changes
안녕하세요 프린!

기존에도 워낙 잘 구현해주셔서 더 드릴 코멘트가 별로 없네요 💯
체스 미션 수고 많으셨습니다! 남은 레벨1 잘 마무리하시고 레벨2도 화이팅입니다~~💪
혹시 궁금한 부분이 있다면 언제든 DM 주셔도 됩니다!

2024-04-03 11:41 UTC, syoun602 commented on src/main/java/database/JdbcTemplate.java
> +        }
커넥션 반환까지 잘 고려하셨네요 👍

2024-04-03 11:41 UTC, syoun602 commented on src/main/java/database/JdbcTemplate.java
> +    }
옵셔널 활용까지 👍

2024-04-03 11:41 UTC, syoun602 commented on src/main/java/domain/board/ChessBoard.java
> +
넵 잘 분리해주셨어요! 스트림은 가독성 때문만은 아니고 함수형 프로그래밍을 위해 등장하게 되었어요!
따라서 행위를 잘 나타내주는 것이 중요하다고 생각합니다 😁

2024-04-03 11:41 UTC, syoun602 commented on src/main/java/controller/board/BoardController.java
> +        });
헉 이부분은 저도 몰랐네요..!! 😢

2024-04-03 11:41 UTC, syoun602 commented on src/main/java/Application.java
>      public static void main(String[] args) {
의존성 주입 👍👍

2024-04-03 11:41 UTC, merged