[3,4단계] 체스 미션 제출합니다. (애쉬)
woowacourse/java-chess pull request #799
Opened 2024-04-01 05:56 UTC by ashsty

안녕하세요, 웨지!

3, 4단계 미션으로 다시 뵐 수 있어서 기쁩니다. 이번 미션에서의 제 status는 다음과 같아요.

--- 

**- DB 적용이 처음이다.**

_이번 미션이 jdbc를 이용한 첫 DB 사용 경험입니다. 코드의 뼈대는 네오의 강의에서 실습했던 코드를 많이 참고했어요. 아직 sql을 활용하는 jdbc 관련 로직에 대한 이해도가 높지 않아서 미숙한 부분이 많을 것 같아요._

**- 객체 분리를 위해 노력했다.**

_점수 계산이나 DB 연결 서비스의 경우 클래스를 분리해 적용해보았습니다. 그 과정에서 기존 도메인 코드는 최대한 변경하지 않으려고 노력했어요._

**- 이전 단계의 리팩토링이 아직 끝나지 않았다.** 

_3, 4단계 미션에 집중하느라 Piece의 움직임을 조정하는 `slidingPiece` 메소드의 경우 아직 리팩토링을 하지 않았습니다. 이 부분은 이번 피드백 적용하면서 조금 더 생각해보려고 해요!_

</br>

지난 단계에 정성스러운 피드백과 함께 고려할 점들을 많이 지적해주셔서 이번 단계를 구현하는 중에도 최대한 반영해보려고 노력했습니다. 물론 아직 많이 부족하다고 느끼지만요...🥲 이번 리뷰도 잘 부탁드립니다.

---

## STEP 1 피드백 적용
- Team (구 : Color) 생성자 삭제

## STEP 2 DB 형태 (+init.sql)
```sql
GRANT ALL PRIVILEGES ON *.* TO 'root'@'%';
FLUSH PRIVILEGES;

CREATE DATABASE IF NOT EXISTS chess DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
CREATE DATABASE IF NOT EXISTS chess_test DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

# Production DB 테이블 초기화
USE chess;
CREATE TABLE IF NOT EXISTS pieces
(
    board_file VARCHAR(10) NOT NULL,
    board_rank VARCHAR(10) NOT NULL,
    piece_team VARCHAR(10) NOT NULL,
    piece_type VARCHAR(20) NOT NULL,
    PRIMARY KEY (board_file, board_rank),
    
    UNIQUE (board_file, board_rank, piece_team, piece_type)
);

# Test DB 테이블 초기화
USE chess_test;
CREATE TABLE IF NOT EXISTS pieces
(
    board_file VARCHAR(10) NOT NULL,
    board_rank VARCHAR(10) NOT NULL,
    piece_team VARCHAR(10) NOT NULL,
    piece_type VARCHAR(20) NOT NULL,
    PRIMARY KEY (board_file, board_rank),
    
    UNIQUE (board_file, board_rank, piece_team, piece_type)
);
```

프로덕션 코드를 위한 `chess` 테이블과 `chess_test` 테이블 두 개를 초기화하는 코드입니다.

각각의 테이블은 `board_file`, `board_rank`, `piece_team`, `piece_type`을 col로 가지고 있으면 그중에서도 `board_file, board_rank`를 key로 가집니다. 

저는 workbench를 활용하여 개발하였기 때문에 해당 init.sql은 workbench에서 별도 실행이 필요합니다. 상세 사항은 readme에 기술해두었는데, 혹시 문제가 있다면 말씀 주세요! (저도 아직 배움이 부족한 부분이라 원활한 연결이 되지 않을 수도 있습니다... 🙇🏻‍♀️)

## 기타 문제
step2를 구현하면서 branch 분리를 따로 해두지 않아서 step1 branch의 커밋 기록이 섞여 있습니다... 
`3ae6761` 부터가 3단계 커밋 시작이에요... 

</br>

이번 리뷰도 잘 부탁드립니다! 🙇🏻‍♀️🙇🏻‍♀️🙇🏻‍♀️

2024-04-01 14:29 UTC, sihyung92 requested changes
안녕하세요 애쉬! 리뷰어 웨지입니다.
어려운 미션인데 잘 구현해주셨네요 ㅎ 
README.md에 어플리케이션 구동을 위한 정보를 적어주신게 특히 인상 깊습니다.
리뷰 남겼으니 확인해주셔요~!

2024-04-01 14:29 UTC, sihyung92 commented on src/main/java/chess/dao/PiecesDao.java
> +    DBConnector dbConnector;
접근 제어자를 누락하신 것 같네요 ㅎ

2024-04-01 14:29 UTC, sihyung92 commented on README.md
>  # java-chess
미리 접속 정보를 주셔서 서버를 켜볼 수 있었습니다 ㅎ 친절한 안내 감사합니다
서버를 구동하는데 필요한 초기 정보는 README.md에 있으면 더욱 좋다고 생각하는데, 잘 적용해주셨네요.
다른 개발자를 위한 친절함이 묻어나는 거 같아 매우 좋습니다.

2024-04-01 14:29 UTC, sihyung92 commented on src/main/java/chess/controller/ChessGame.java
> +        if (command.get(0).equals(STATUS_COMMAND) && gameState.getClass().equals(Progress.class)) {
실제로 진행해보면 한쪽 팀만 계속 진행할 수 있었습니다 ㅎ 
(move b2 b3, move b3 b4, move b4 b5) 
게임도 완성단계여야 하니까 턴을 잘 구현해주세요.
로드 후에 턴이 제대로 기능하는 부분도요

2024-04-01 14:29 UTC, sihyung92 commented on src/main/java/chess/controller/ChessGame.java
> +        if (command.get(0).equals(STATUS_COMMAND) && gameState.getClass().equals(Progress.class)) {
그리고 NPE를 방지하기 위해선 항상 null이 아님이 분명한 쪽이 메서드를 사용하도록 구현해주는 게 좋습니다.
```suggestion
        if (STATUS_COMMAND).equals(command.get(0) && Progress.class.equals(gameState.getClass())) {
```

또 class 타입 비교는 언어에서 지원해주는 연산자인 instanceOf 를 사용하는 게 낫고요,

개인적으로는 이렇게 타입 체크를 해주면서 로직을 진행해야 하면 상태패턴을 사용하지 않는 편이 더 낫다고 생각합니다. 😏

2024-04-01 14:29 UTC, sihyung92 commented on src/main/java/chess/dao/PiecesDao.java
> +        }
복잡한 접속정보를 Dao 마다 기억할 필요 없도록 추상화해 주신 부분은 좋습니다 :+1: 

try catch 문도 반복되는데, 오류 메시지만 달라질 뿐 반복코드인 것 같아서 이런 부분도 공통화 되면 좋을거 같습니다.

2024-04-01 14:29 UTC, sihyung92 commented on src/main/java/chess/dao/PiecesDao.java
> +                    "UPDATE pieces SET piece_team = ?, piece_type =? WHERE board_file = ? AND board_rank =?");
쿼리마다 띄어쓰기가 다른 부분들이 있네요 ㅎ

2024-04-01 14:29 UTC, sihyung92 commented on src/main/java/chess/dao/PiecesDao.java
> +            var type = Type.convertToType(resultSet.getString("piece_type"));
좀 어려운 얘기를 해볼게요. 
정규화에 관한 부분과 인덱스에 관한 부분입니다. 

이번 미션은 DB 적용 정도가 전부이니 적용하실 필요는 없지만, 앞으로 RDB와는 친구가 되실테니 미리 적어봅니다.

RDB의 강력함은 '정규화'를 통해 데이터 중복이 없도록 하는 부분에서 나옵니다. 빡빡한 사전 설정, 스키마를 바꾸기 어렵다는 것이 단점이지만 다양한 NoSQL (RDB의 관계형 모델에 대한 대안으로 나온 DB들)이 등장했지만 RDB의 수요는 끊이질 않죠 ㅎ 

1. 정규화 관련

해당 테이블은 정규화가 잘 안 지켜지고 있다고 생각해요. 상황마다 다르지만 보통 3정규화 정도까지는 지키도록 구성하는 편이 많습니다.

정규화에 관한건 ChatGPT에게 데이터베이스의 정규화에 대해 물어보고, 1정규화 / 2정규화 / 3정규화에 대해 예제와 함께 쉽게 설명해달라고 요청해보세요. 저보다 훨씬 잘 설명해줄거라 믿습니다
(저는 ChatGPT를 답지를 뽑아주는 용도보단 제 이해를 심화시키는데 활용하는데, AI 언어 처리모델들이 이런 부분에서 탁월하다고 생각합니다. 학습 도우미로 활용하셔요)

2. 인덱스 관련

나중에 대용량 테이블이 되어 인덱싱에 유리하려면 file / rank를 하나로 합친 칼럼이 낫다고 생각해요.
'a1' ~ 'h8'이 오름차순으로 잘 정리되는 문자열이기 때문임니다.
저라면 나중에 userID, file_rank 칼럼 두 가지를 복합인덱스로 걸거 같아요. 
인덱스에 대해 잘 모르시겠다면 아주 가볍게만 알아두시고, (레벨 2에 학습이 있으니까요) 그렇구나 하고 넘어가셔도 됩니다

2024-04-01 14:29 UTC, sihyung92 commented on src/main/java/chess/db/DBConnector.java
> +    private static final DBConnector TEST_DATABASE = new DBConnector("chess_test"); // MySQL TEST DATABASE 이름
주석은 다 동어반복인거 같네요 ㅎㅎ 없어도 될거같아요

[좋은코드 나쁜코드](https://www.yes24.com/Product/Goods/109366833?pid=123487&cosemkid=go16528515239662655&gad_source=1&gclid=CjwKCAjwtqmwBhBVEiwAL-WAYQnTTSl15wEx2jzZJNEQUE25jAxuS6buex4IZx7utaFxNRKKg03XGhoC91gQAvD_BwE) 루터회관에 있을텐데 p127 부분(5.2 주석문의 적절한 사용)만 따로 한번 읽어보셔요.

2024-04-01 14:29 UTC, sihyung92 commented on src/main/java/chess/domain/board/ScoreBoard.java
> +public class ScoreBoard {
지금 객체는 무상태성 함수들만 가지고 있어요.
이러면 굳이 Instance화 할 필요 없다고 생각합니다.
Chessboard를 상태(필드)로 받아 계산하던지, 아니면 아예 static 메서드만 가진 객체(util 객체)로 만들어보세요. util 객체로 만들 경우 네이밍은 변화가 필요할거에요.

2024-04-01 14:29 UTC, sihyung92 commented on src/main/java/chess/controller/ChessGame.java
> +        return chessService.loadChessBoard();
이거야말로 Ready 상태에 어울리는 작업 아닌가요? ㅎㅎ controller와 state가 service를 각각 활용하고 있어서 코드가 헷갈려요. 
service란 무엇인가요? 어떤 작업을 하는 계층으로 정의하셨으며, 어떤 객체들이 의존하면 좋을까요? 
인터넷에 치면 나오는거 말고 애쉬의 생각이 듣고싶어요.

2024-04-02 08:30 UTC, ashsty commented on src/main/java/chess/controller/ChessGame.java
> +        if (command.get(0).equals(STATUS_COMMAND) && gameState.getClass().equals(Progress.class)) {
> 실제로 진행해보면 한쪽 팀만 계속 진행할 수 있었습니다 ㅎ (move b2 b3, move b3 b4, move b4 b5) 게임도 완성단계여야 하니까 턴을 잘 구현해주세요. 로드 후에 턴이 제대로 기능하는 부분도요

turnsDAO 생성해주었고, 상단 PR comment의 init.sql도 함께 수정해두었습니다.

2024-04-03 01:56 UTC, ashsty commented on src/main/java/chess/controller/ChessGame.java
> +        if (command.get(0).equals(STATUS_COMMAND) && gameState.getClass().equals(Progress.class)) {
> 그리고 NPE를 방지하기 위해선 항상 null이 아님이 분명한 쪽이 메서드를 사용하도록 구현해주는 게 좋습니다.
> 
> 또 class 타입 비교는 언어에서 지원해주는 연산자인 instanceOf 를 사용하는 게 낫고요,
> 
> 개인적으로는 이렇게 타입 체크를 해주면서 로직을 진행해야 하면 상태패턴을 사용하지 않는 편이 더 낫다고 생각합니다. 😏

equals 적용 순서 변경, Instance of 적용 마쳤습니다! (start 입력 전 status 입력 시 예외 처리를 위함)

아래에서 초기화 로직을 Ready State 안으로 옮기면서도 생각한 거지만, 이게 웨지가 말씀하셨던 '이럴 거면 괜히 구현했다...' 싶은 경우 같기도 합니다. 굳이 적용할 필요 없었던 디자인 패턴을 사용하면서 괜히 프로그램이 더 복잡해지고 체크해줘야 하는 분기가 늘어난 기분이어서요. 🧐 아마 컨트롤러에서 해당 작업을 전부 진행해주었다면 클래스 타입 체크를 할 일도 없었겠죠?

제가 밀고 나가기로 결심한 패턴이다 보니 끝까지 책임지고 싶다는 오기 때문에 열심히 리팩토링하고 있긴 하지만(매몰 비용의 위험성 😱) 이럴 때 웨지는 어떤 결정을 내리시는지도 궁금해지네요! 최초 설계가 그리 효율적이지 않았다는 사실을 프로젝트 중후반쯤에 깨달았다면 웨지는 과감하게 지금까지의 구현을 엎고 리팩토링하시는 편인가요? 물론 지금 제 프로젝트는 아주 아담하고 바꾸려고 든다면 얼마 걸리지 않기야 하겠지만요... ㅎㅎ 🫣

2024-04-03 02:24 UTC, ashsty commented on src/main/java/chess/db/DBConnector.java
> +    private static final DBConnector TEST_DATABASE = new DBConnector("chess_test"); // MySQL TEST DATABASE 이름
중복되는 주석의 사용은 장려되지 않는군요 🤔
DB 사용이 처음이다 보니 `내가 모르는 내용 > 주석으로 설명을 달아놓자!` 라는 생각으로 비슷한 주석이라도 남용했던 것 같아요. 

앞으로는 주석 사용에 있어서도 조금 더 신중해져야겠다는 생각을 했습니다. 🫢

2024-04-03 03:00 UTC, ashsty commented on src/main/java/chess/domain/board/ScoreBoard.java
> +public class ScoreBoard {
매번 상태가 바뀌는 `Chessboard`를 매번 업데이트 해주기 보다는 util 객체로 사용하는 것이 낫다고 판단해 해당 클래스를 util 객체로 변경하였습니다. 

다만 현재 Score를 계산하는 곳이 ChessGame 클래스 한 곳 밖에 없는데 Score 계산 클래스를 util 객체로 만드는 게 괜찮은지에 대해서는 아직 분명한 주관이 서지 않은 것 같다고 생각했어요. 저는 많은 클래스에서 사용되는 기능이 아니라면 util 객체로 만들지 않는 편이 낫다고 생각하는 편이었는데, util을 사용하는 웨지의 기준이 있는지가 궁금합니다! 

(이번 리뷰 요청에는 어쩐지 물음표 달린 코멘트가 조금 있는 것 같은데요... 저만의 확실한 기준이 생기기 전 최대한 많은 사람들의 다양한 견해를 들어두고 싶은 마음에 이런저런 질문이 많아지는 것 같아요. 얜 뭘 이런 걸 물어봐? 싶으시겠지만... 아무쪼록 잘 부탁 드립니다! 🙇🏻‍♀️🙇🏻‍♀️)

제가 위처럼 생각한 이유는 'static 사용을 지양하라' 같은 명제 때문인데요.

static을 사용하면 우선 
1. 캡슐화가 깨짐 (static은 객체 지향이라기보다는 절차 지향적)
2. static 메소드를 활용한 기능에서 오류가 생겼을 때 오류 추적이 어려움
3. 메모리 문제

위와 같은 문제가 있다고 학습했어요. 하지만 아직 어떤 경우에는 static을 쓰는 경우가 낫고, 또 어떤 경우에는 지양하는 게 맞는지 결정하기가 어려운 것 같습니다. 🤔

2024-04-03 03:17 UTC, ashsty commented on src/main/java/chess/controller/ChessGame.java
> +        return chessService.loadChessBoard();
> 이거야말로 Ready 상태에 어울리는 작업 아닌가요? ㅎㅎ controller와 state가 service를 각각 활용하고 있어서 코드가 헷갈려요. 

우선 보드와 턴을 초기화하는 작업은 Ready State 클래스로 이동하였습니다.

> service란 무엇인가요? 어떤 작업을 하는 계층으로 정의하셨으며, 어떤 객체들이 의존하면 좋을까요? 인터넷에 치면 나오는거 말고 애쉬의 생각이 듣고싶어요.

사실 이 코멘트를 보고 인터넷에 한 번 service의 역할에 대해 검색해봤는데요 (👀)
처음 구현할 때도 저 역시 그 결과와 거의 비슷한 정의로 구현했던 것 같아요.

제가 정의한 서비스 계층은 'DB와 게임 진행 상황을 연결'해주는 역할입니다.

DAO(Data Access Object)가 단순히 DB에 저장된 데이터를 조작하는 방식을 정의한다면, 
Service 단에서는 그런 DAO를 활용하여 로컬 콘솔에서 발생하는 데이터 작업을 데이터베이스에 접목하는 책임을 부여하고 싶었습니다. 

예시 ) 
게임을 진행하며 말 이동 커맨드 입력 
-> 게임 내부 로직에 따라 말 이동, 실 데이터 조작 
-> service의 update 메소드를 호출 
-> DAO를 이용해 DB 업데이트 

위와 같은 단계를 거치길 바랐고요.

그런 관점에서 생각해보면 게임을 진행하며 실제 변화가 일어나는 (command 입력을 받는) state 객체들만이 Service를 활용할 권한을 가지는 게 맞는 것 같습니다. controller는 결국 입출력 로직과 상태 객체들을 연결해주고 있는 역할이라고 생각했기 때문입니다. 🤔

2024-04-03 04:03 UTC, ashsty commented on src/main/java/chess/dao/PiecesDao.java
> +            var type = Type.convertToType(resultSet.getString("piece_type"));
SQL 공부하면서 말로만 들었던 정규화 이야기네요! 😮 오래전에 공부만 해놓고 정작 실전에서 사용할 때는 전~혀 고려하지 않고 있었다니 어쩐지 부끄럽습니다... 웨지 덕분에 오랜만에 먼지 쌓인 책을 꺼내 (그리고 우리의 친구 짹쥐피티와 함께) 말씀해주신 부분에 대해 조금 찾아봤어요.

1 / 2 / 3 정규화 케이스를 살펴보면 지금의 테이블에서 문제가 되는건 

1. 중복 : 같은 File, Rank 값에 동일한 Team/Type의 말이 위치할 수 있다. 
- 저는 이걸 UNIQUE로 잡을 수 있겠다고 생각했는데, 동일한 기물(2개 이상 존재: 검은 폰, 검은 비숍, 흰 나이트...)이 같은 위치에 있는 케이스는 구분하지 못하겠더라고요. 😱 물론 지금의 설계로는 게임 로직 내부에서 그러한 움직임을 허용하지 않겠지만, 데이터베이스 상에서는 예외 처리가 안되고 있어요.

2. 부분 종속 : File, Rank이 결정되면 Team/Type이 결정됨
- 2 정규화가 제대로 되지 않고 있는 모습입니다. . .

그래서 piece와 position 테이블을 분리해보는 해결책을 생각해봤습니다. 
```sql
Piece Table

piece_id (PRIMARY KEY)
piece_team
piece_type
PiecePosition:

Position Table

piece_id (FOREIGN KEY REFERENCES Piece(piece_id))
board_file
board_rank

```
추가적으로 인덱스에 대해서도 말씀해주신 점에 공감해요. 

지금은 File, Rank column을 각각 확인해야 하는데 애초에 두 가지 값을 한 번에 확인할 수 있게 되면 인덱싱 속도에도 영향을 줄 것 같고요. 🤔 현재 테이블 구조(Pieces)를 유지한다고 생각하면 key 값을 바꾸는 게 더 효율적일 것 같다는 생각이 드네요!

2024-04-04 05:41 UTC, sihyung92 commented on src/main/java/chess/controller/ChessGame.java
> +        if (command.get(0).equals(STATUS_COMMAND) && gameState.getClass().equals(Progress.class)) {
만약에 최초 구현이면 다시 엎을수도 있는데요, 
이미 출시된 기능이면 고려해야할게 많아집니다 (변경은 곧 장애 가능성 이거든요 ㅠ)
보통 안 고치고 마음속에 부채1로 남게 되죠..
그렇게 살아가는 거 같습니다

2024-04-04 09:30 UTC, sihyung92 commented on src/main/java/chess/db/DBConnector.java
> +    private static final DBConnector TEST_DATABASE = new DBConnector("chess_test"); // MySQL TEST DATABASE 이름
전 주석 자체에는 반대하지 않습니다만, 주석 반대파 입장에 대해서는 공감합니다.

1. 주석도 유지보수 대상임 (실제 동작과 다른 주석이 있으면 큰 혼란을 야기함)
2. 주석을 믿고 코드가 더러워지는 경향이 있음

좋은코드 나쁜코드에서 말하는 "좋은 주석"에 대해서는 매우 찬성하는 편입니다

--

음~ 책 추천은.. 
저는 당장의 나에게 도움이 되는 책이 학습효과가 높다고 생각합니다.
그래서 레벨 1,2 내용과 연관된 책들을 읽는 게 좋다고 생각해요.

오브젝트, 코딩을 지탱하는 기술, 프로그래머의 뇌, 좋은코드 나쁜코드 정도 생각나네요

2024-04-04 09:40 UTC, sihyung92 commented on src/main/java/chess/domain/board/ScoreBoard.java
> +public class ScoreBoard {
전 Util 객체를 안 좋아하는 편이에요 ㅎ 
왜냐하면 객체 그래프가 잘 안 보이기 때문입니다 (A 클래스 들어가보면 필드가 뭐뭐 있는지로 대강 역할을 파악하는데, 유틸 객체들은 메서드 안에서 갑툭튀함)

그런데 쓰다보면 거의 모든 곳에 쓰이는 것도 있는데.. 그럴 때마다 의존해주는 것도 피곤해서 그럴땐 유틸객체로 만들기도 합니다

2024-04-04 09:46 UTC, sihyung92 approved these changes
안녕하세요 애쉬! 리뷰어 웨지입니다 
전체적으로 제가 원하는 방향으로 리팩토링이 이루어진 것 같습니다 ㅎ 
리뷰 반영 잘 해주셔서 여기서 머지할게요. 감사합니다.

2024-04-04 09:46 UTC, sihyung92 commented on src/main/java/chess/dao/PiecesDao.java
> +
공통화 잘 해주셨네요 ㅎ

2024-04-04 09:46 UTC, sihyung92 commented on src/main/java/chess/service/ChessService.java
> +public class ChessService {
서비스 의존이 제가 생각하는 것과 비슷한 방향으로 잘 된 것 같습니다.

service는 개인적으론 비즈니스 플로우를 절차적으로 정의해주는 계층이라고 생각합니다. 
꼭 DB와의 가교 역할을 수행하는 건 아니지만, 웹 개발은 대부분 DB로 향하는 경우가 많아서 DB 접근 계층처럼 여겨지는 경향이 있는 것 같습니다.

2024-04-04 09:46 UTC, merged