[3, 4단계 - 체스] 커찬(이충안) 미션 제출합니다.
woowacourse/java-chess pull request #806
Opened 2024-04-01 07:22 UTC by leegwichan

안녕하세요 조앤! 커찬입니다.
1,2단계는 생각보다 일찍 끝났는데, 3,4단계는 너무 오래 걸렸네요 ㅠ_ㅠ

일단은 전에 남겨주셨던 리뷰에 대한 글 남겨봅니다.

### 리뷰에 대한 생각

> ChessGame.executeMove에 board에서 move 동작을 실행한다라는 의미가 담겨있다고 생각하시는지 궁금해요ㅎㅎ

제가 사용한 `execute`라는 단어는 하나의 명령어를 상황에 맞게 실행한다고 생각했습니다. 그래서 단순히 `move`보다는 `executeMove`를 사용했습니다.

> 단순히 board.get(start); 만 봤을 때, 저는 Piece가 반환될 것이라고는 생각되지 않는 것 같아요ㅎㅎ
다만 board 위에는 piece들이 있을 것이니, 위치를 넘겼을 때 piece가 반환될 수 있다고 이해는 되어요.
이 부분에 대해서 커찬은 어떻게 생각하시는지 궁금해요~!

`board`가 `Map`임을 알고 있다면 쉽게 유추할 수 있다고 생각합니다. `Map`을 감싸는 일급 컬렉션을 사용한다면 더 명확한 이름을 줄 수 있겠네요. 
3,4단계 구현 내용들을 지키느라 해당 내용을 생각만하고 구현하지 못했습니다. 그래서 리뷰 주신 내용을 반영할 때 같이 해보도록 하겠습니다.

> start와 end도 하나의 객체 내부에서 관리해보는 것은 어떨까요?

저도 고려해 보았습니다만, 실제로는 하지 않았습니다.
1. `new Moving(Position start, Position end)`와 같은 객체로 사용한다면, 특정 위치에 있는 기물들을 조회할 때, getter를 사용해야 될 것 같았습니다. 
2. `Moving`을 사용한다면 `rankDifference`, `fileDifference`와 같은 숫자들을 `Moving`안에서 관리해줄 수 있는 장점이 있다고 생각합니다. 그리고 가독성을 통해 쉽게 상황을 유추할 수 있다고 생각합니다. 하지만 `Moving`이 너무 많은 메서드들을 들고 있게 되고, 구현된 메서드(`isRightSide()`, `isLeftSide()`, ...)들도 다른 곳에서 한 번 정도만 사용될 것 같았습니다.

그래서 고려만 하고 도입하지는 않았습니다.

> 지금은 각 Piece별로 이동할 수 있는지/없는지만 테스트하고 있는데, 해당 MovementRule들이 적절한 Piece에 적용되었는지 확인하는 테스트코드가 있으면 좋을 것 같아요. 그렇다면 휴먼 에러를 최대한 줄일 수 있을 것 같아요.

해당 테스트가 있다면, 휴먼 에러를 줄일 수 있다는 점에는 동감합니다. 하지만 너무 세부 구현에 의존하는 테스트가 아닌지 걱정됩니다. "각 말이 원하는 위치로 움직일 수 있는가?"는 이미 각 말들의 `findPath()` 메서드를 테스트하며 진행합니다. 해당 메서드를 테스트 할 때, 각 움직임 규칙들에 해당하는 예제들을 넣어놓습니다. 중요 케이스들을 놓치지 않는다면, 굳이 위와 같은 테스트가 없어도 휴먼 에러를 줄일 수 있다고 생각합니다.

### 프로그램 실행 방법

1. database 폴더로 이동한다.
2. docker-compose.yml를 통하여 docker를 실행한다.
3. init.sql의 명령어를 docker 내부에서 차례로 실행한다.
4. IDE를 통해 ChessApplication를 실행한다.

-> Docker(Mysql)가 실행되지 않거나 초기 테이블 설정이 되어있지 않다면, 프로그램이 정상적으로 작동하지 않습니다.

### 구현 시 고려한 점

#### 요구 사항 만족

"돌아가는 쓰레기를 만들자"와 "주어진 프로그래밍 요구 사항을 지킬 수 있는 만큼 지키자"를 목표로 프로그램을 만들었습니다. 메서드 네이밍이 직관적이지 않거나 구조 측면이 과하게 복잡할 수 있습니다. 보이시는 만큼 리뷰 부탁드립니다. ( _ _ )

#### 자동 저장 기능

말이 한 번 움직일 때마다 저장합니다. 입력 받는 중에 예기치 못하게 중단되거나 오류가 발생한다 하더라도 이전의 상황을 그대로 사용할 수 있습니다.

### 고려하지 못한 점

#### 트랜젝션

따로 트랜젝션을 사용하지 않아서, 동작 중에 오류가 발생하면 DB가 정상적으로 저장되지 않을 수 있습니다.

2024-04-01 13:51 UTC, seovalue requested changes
안녕하세요, 커찬. 코멘트 확인 후 다시 리뷰 요청주세요~
그리고 PR에 함께 남겨주신 멘트에 대해 여쭤보고 싶은 부분이 있어요. 

> "돌아가는 쓰레기를 만들자"와 "주어진 프로그래밍 요구 사항을 지킬 수 있는 만큼 지키자"를 목표로 프로그램을 만들었습니다. 메서드 네이밍이 직관적이지 않거나 구조 측면이 과하게 복잡할 수 있습니다. 보이시는 만큼 리뷰 부탁드립니다. ( _ _ )

라고 남겨주셨는데, 저는 말씀해주신 부분이 공감이 안되어서요.
미션을 진행하는 것은, 기한 내에 주어진 프로그래밍 요구사항을 모두 지킨 상태로 제출하는 것을 의미한다고 생각해요. 실제 업무에서도 동일할 거고요. 지금이 실제 업무라고 가정했을 때, 기한 안에 지킬 수 있는 만큼만 지킨 채로 돌아가는 쓰레기를 배포하실 건가요?

리뷰를 하는 목적은 본인이 고심해서 구현한 내용에 대해 어떻게 생각하는지를 함께 이야기나눠보고 좋은 방향으로 개선하나가는 것이라고 생각해요. 과하게 복잡한 내용은 저도 이해하기 어렵고, 이해하기 어려운 코드는 좋은 리뷰를 할 수 없게 만든다고 생각해요.

2024-04-01 13:51 UTC, seovalue commented on src/main/java/chess/ChessGame.java
> +    private ProgressStatus executeStatus() {
<img width="168" alt="Screenshot 2024-04-01 at 22 27 34" src="https://github.com/woowacourse/java-chess/assets/48412963/c09ea706-fbbf-4228-b693-307b721fb60e">

점수 계산 로직을 점검해주세요.

2024-04-01 13:51 UTC, seovalue commented on database/docker-compose.yml
> +version: "3.9"
👍

2024-04-01 13:51 UTC, seovalue commented on src/main/java/chess/ChessApplication.java
> +        ConnectionManager connectionManager = new ConnectionManager();
Connection은 언제 종료되나요?

2024-04-01 13:51 UTC, seovalue commented on src/main/java/chess/ChessGame.java
> +    private final ChessService chessService;
> 3개 이상의 인스턴스 변수를 가진 클래스를 쓰지 않는다.

2024-04-01 13:51 UTC, seovalue commented on src/main/java/chess/ChessApplication.java
> +        ChessGame chessGame = new ChessGame(INPUT_VIEW, OUTPUT_VIEW, chessService);
inputview와 outputview를 static 형태로 만들어서 넘겨주는 이유가 궁금해요

2024-04-01 13:51 UTC, seovalue commented on database/init.sql
> +    turn VARCHAR(10) CHECK (turn IN ('BLACK', 'WHITE')) not null,
turn 만 가지도록 chess_game db를 설계해주신 이유가 궁금해요.

2024-04-01 13:51 UTC, seovalue commented on database/init.sql
> +CREATE TABLE pieces (
optional한 요구사항인 
체스 게임방을 만들고 체스 게임방에 입장할 수 있는 기능을 추가한다.
사용자별로 체스 게임 기록을 관리할 수 있다.
를 필수로 구현해야했다면, 여전히 동일하게 pieces를 설계하실 건가요?

2024-04-01 13:51 UTC, seovalue commented on src/main/java/chess/ChessGame.java
> +        ProgressStatus status = chessService.moveTo(start, end);
1,2단계 때와 유사한 리뷰를 계속 남기게 되는 것 같은데요, 
moveTo를 수행했을 때 progressStatus가 반환되는 것이 어색하게 느껴져요.

2024-04-01 13:51 UTC, seovalue commented on src/main/java/chess/ChessService.java
> +public class ChessService {
ChessGame도 있고, ChessService도 있는 이유가 무엇인가요? 
ChessService의 정확한 역할이 뭔지 잘 와닿지 않는 것 같아요.

2024-04-01 13:51 UTC, seovalue commented on src/main/java/chess/dao/ChessDao.java
> +    public void saveMoving(PieceEntity piece, Position previous, TurnType currentTurn) {
매 움직임을 db에 persist 해주시는 이유가 궁금해요~

2024-04-01 13:51 UTC, seovalue commented on src/main/java/chess/dao/PieceEntity.java
> +    private final TeamType teamType;
> 3개 이상의 인스턴스 변수를 가진 클래스를 쓰지 않는다.

말씀주신 대로 전반적으로 요구사항이 안지켜진 부분이 많네요

2024-04-01 13:51 UTC, seovalue commented on src/main/java/chess/domain/Board.java
> +        Piece movingPiece = find(start).orElseThrow();
find라는 메서드명만 보고 어떤 것을 찾아올 지 다른 개발자들도 바로 알 수 있을까요?

2024-04-04 07:23 UTC, leegwichan reviewed
안녕하세요 조앤! 커찬입니다. 우테코 미션에 대한 나의 태도에 대해 생각해보느라 피드백 반영이 늦어졌습니다. 여러 방면으로 다시 생각해보는 계기가 된 피드백이었습니다.

> 미션을 진행하는 것은, 기한 내에 주어진 프로그래밍 요구사항을 모두 지킨 상태로 제출하는 것을 의미한다고 생각해요. 실제 업무에서도 동일할 거고요.

 이 문장을 읽고, 제가 가졌던 미션의 무게가 가벼웠다고 생각이 들었습니다. 무의식 중에 "이번에 좀 덜 노력하고 덜 성장해야지"라는 생각을 했었던 것 같습니다. 오늘 지난 한 달을 회고해 보았는데, 조금 안일하게 살았다는 생각이 드네요.

조앤이 써준 코멘트를 보면서, 우테코에서의 생활이 단지 배움의 목적이 아니라 실무에 준한 환경으로 바라보아야 한다는 것을 느꼈습니다.

> 지금이 실제 업무라고 가정했을 때, 기한 안에 지킬 수 있는 만큼만 지킨 채로 돌아가는 쓰레기를 배포하실 건가요?

 이 문장이 저를 가장 맘아프게 했습니다. 특히 제 자신에게 많이 실망했습니다. 제가 이 정도의 능력밖에 안되는지, 개발자가 나에게 맞는지 되돌아 보았습니다. 
 
 조앤도 아시겠지만, 저도 이 상황을 원치 않았습니다. 여러가지 일(체스 미션, 글쓰기, 테코톡)을 병행적으로 처리하는 것이 미숙해서 부족한 코드를 남겼습니다. 특히, 남아있는 일이 많다는 것에 심리적 부담을 느껴서 더 못했습니다.
 
 일을 기간 내에 요구사항을 다 맞추지 못한 것은 스포츠에서 흔히 말하는 '프로 정신'이 부족했다고 생각합니다. 그리고 이렇게 해야하는 일이 여러가지 인것도 일부러 실무 상황과 유사하게 만들었다고 생각합니다. 그래서 다음에는 이번보다 더 잘할 수 있도록 노력해보려 합니다.

> 리뷰를 하는 목적은 본인이 고심해서 구현한 내용에 대해 어떻게 생각하는지를 함께 이야기나눠보고 좋은 방향으로 개선하나가는 것이라고 생각해요. 

 저도 이런 리뷰가 가치있다고 생각합니다. 그러기 위해서는 제가 더 고심하고 신경써야 했습니다. 이번 리뷰에서 그런 점을 토의할 수 없었던 게 참 아쉽습니다.

> "돌아가는 쓰레기를 만들자"와 "주어진 프로그래밍 요구 사항을 지킬 수 있는 만큼 지키자"를 목표로 프로그램을 만들었습니다.

 다시 읽어보니, 이 글이 조앤을 힘빠지게 만들지 않았을까 생각이 듭니다. 실제 업무를 하시면서 여러 크루의 리뷰를 다는 것이 쉽지 않았는데, 이렇게 쓴 글이 보인다면 화가 났을 것 같네요. 만약에 그러셨다면 사과 드립니다.

---

 체스 미션에서 주어진 모든 요구사항을 지키는 데에는 시간이 부족했다고 생각했습니다. 다시 돌아보면 정성과 노력, 멘탈이 부족하지 않았나 생각이 듭니다. 모든 요구사항을 지키지 못했더라도, 여러 면에서 위처럼 생각하지는 말았어야 했네요. 이번 기회를 반면교사 삼아 좋은 개발자가 되도록 노력하겠습니다.

 조앤이 주신 피드백을 포함하여 여러 부분들을 리팩터링 했습니다. 그리고 조앤이 주신 피드백에는 제 생각을 적어보았습니다. 이외 추가적으로 궁금한 점 있으시면 커멘트 부탁드리겠습니다~!

2024-04-04 07:23 UTC, leegwichan commented on database/init.sql
> +    turn VARCHAR(10) CHECK (turn IN ('BLACK', 'WHITE')) not null,
아마 조금 더 일반적인 경우나 확장을 할 것이라는 생각을 했다면 auto increment하는 id값을 추가 해야 한다고 생각합니다.
지금은 chess_game에 row가 1개 밖에 쓰일 일이 없어서 turn만을 가지도록 설계했습니다.

이 프로그램에서 DB를 사용하는 목적는 데이터를 계속해서 쌓아나가기 보다는, 갑자기 게임이 중단 되는 것을 대비하여 중간 상황를 저장한다는 느낌이 들어서 위와 같이 설계했습니다.
만약 추가적인 요구사항을 고려한다면, id 열을 하나 추가해야 한다고 생각합니다.

2024-04-04 07:23 UTC, leegwichan commented on database/init.sql
> +CREATE TABLE pieces (
우선 필수적으로 pieces 테이블에 piece_id와 chess_game_id를 추가할 것입니다.
그리고 PK를 piece_id, FK를 chess_game_id로 할 것입니다.

그리고 나서 상황을 2가지로 생각해 볼 수 있을 것 같습니다.
상황1)
Table chess_game (chess_game_id, user_id, turn)
Table pieces (pieces_id, chess_game_id, board_file, board_rank, type, team)

상황2)
Table chess_game (chess_game_id, user_id, turn)
Table boards (board_id, chess_game_id, position_id, piece_id)
Table positions (position_id, rank, file)
Table pieces (piece_id, type, team)

상황 1은 성능 상의 이점을 가져갈 수 있지만, 나중에 수정 이상 등의 문제가 생길 수 있습니다. 상황 2는 이상 현상이 생길 가능성을 상대적으로 더 방지할 수 있지만, Table join 등의 성능상의 문제가 발생 할 것 같습니다. 그래서 어플리케이션에게 기대하는 요구에 따라 선택할 것 같습니다.

2024-04-04 07:23 UTC, leegwichan commented on src/main/java/chess/ChessApplication.java
> +        ConnectionManager connectionManager = new ConnectionManager();
Connection을 하나로 관리해야 겠다는 생각은 했는데, 이것을 언제 종료시킬지 여부는 미처 생각하지 못했습니다.
지금은 수정해서 Application 종료시에 Connection을 닫아주도록 수정했습니다.

2024-04-04 07:23 UTC, leegwichan commented on src/main/java/chess/ChessGame.java
> +    private ProgressStatus executeStatus() {
게임을 DB에서 불러올 때, 나이트를 킹으로 불러오는 버그가 있었네요...
테스트 코드가 없어서 미처 예방하지 못했습니다;;

지금은 수정하여 정상적으로 불러오는 것을 확인했습니다!

2024-04-04 07:23 UTC, leegwichan commented on src/main/java/chess/ChessApplication.java
> +        ChessGame chessGame = new ChessGame(INPUT_VIEW, OUTPUT_VIEW, chessService);
메서드 길이를 줄이기 위해서 급작스럽게 일관성 없이 처리했습니다.

지금은 일관성 있게 처리하도록 수정했습니다.

2024-04-04 07:23 UTC, leegwichan commented on src/main/java/chess/ChessGame.java
> +        ProgressStatus status = chessService.moveTo(start, end);
Board 자체가 특정 시점에 게임이 끝났는지 진행중인지 판단할 수 없어서 위와 같은 구조가 되었습니다.

GameStatus를 도입하여 게임이 어떤 상태인지 판단할 수 있도록 수정했습니다!

2024-04-04 07:23 UTC, leegwichan commented on src/main/java/chess/dao/ChessDao.java
> +    public void saveMoving(PieceEntity piece, Position previous, TurnType currentTurn) {
이번 미션의 필수 요구사항인 "애플리케이션을 재시작하더라도 이전에 하던 체스 게임을 다시 시작할 수 있어야 한다."를 애플리케이션을 **중단**하더라도 이전에 하던 체스 게임을 다시 시작할 수 있어야 한다."로 조금 다르게 이해했습니다.
그래서 불의의 사고로 어플리케이션이 중단될 때에도 이어할 수 있도록 하기 위해, 위와 같은 구조가 되었습니다.

2024-04-04 07:23 UTC, leegwichan commented on src/main/java/chess/ChessGame.java
> +    private final ChessService chessService;
이 부분에서 필드를 3개 사용한 이유는 "View와 Service를 연결하는 로직은 역할 분리만 잘 된다면 인스턴스 변수를 좀 더 가지고 있어도 되지 않을까?"라고 생각했습니다. 그 이유는 지금의 ChessGame은 "View와 Service를 연결"하는 역할인데, View가 2개로 나뉘어 있어서 그렇지, 충분히 역할과 책임을 많이 쥐고 있지 않다고 생각했습니다.

지금은 요구사항을 지키는 것이 우선이라고 생각하여 `ChessGameController`(구 ChessGame)을 수정했습니다. InputView와 OuputView가 특정 상태에 의존적이지 않아 상수로 선언하여 사용했습니다.

2024-04-04 07:23 UTC, leegwichan commented on src/main/java/chess/domain/Board.java
> +        Piece movingPiece = find(start).orElseThrow();
힘들어 보입니다;;

주신 의견 반영해서 수정 했습니다!

2024-04-04 07:23 UTC, leegwichan commented on src/main/java/chess/dao/PieceEntity.java
> +    private final TeamType teamType;
처음에는 Spring JPA를 쓰던 버릇이 있어, "그냥 필드 하나가 DB 테이블 컬럼에 하나씩 매칭되도록 하는게 좋은거 아닌가?"라는 막연한 생각을 했습니다. 다시 생각해보니 지금이 JPA을 사용하는 환경이 아니니까 그렇지 않도록 해야 되겠더라구요.

 일단 요구사항을 지키는 것이 우선이라 생각해 인스턴스 변수를 2개로 줄였습니다.

2024-04-04 07:23 UTC, leegwichan commented on src/main/java/chess/ChessService.java
> +public class ChessService {
ChessService는 ChessGame이 매 명령마다 해야하는 일들을 모두 들고있다면, ChessGame이 하는 일이 많아져 유지보수가 힘들어 질 것 같았습니다. 그래서 각 명령마다 도메인, DAO가 해야하는 일을 ChessService로 분리하기 위해서 만들어졌습니다.

여러차례 수정한 결과, ChessService의 메서드를 각 명령마다 수행해야 하는 단위, 조회해야 하는 단위로 메서드를 수정했습니다.

2024-04-05 02:18 UTC, seovalue commented on database/init.sql
> +CREATE TABLE pieces (
👍 
이와는 달리 아예 움직임에 대한 스냅샷을 남기는 방법도 있을 것 같아요! 
주어진 요구사항을 갖고 여러 방면으로 생각해보는 연습을 해보면 좋을 것 같아요ㅎㅎ 이런게 다 경험이 되더라고용

2024-04-05 03:07 UTC, seovalue requested changes
안녕하세요, 커찬! 
리팩터링 잘 수행해주셨네요💯
제가 남긴 코멘트로 깊이 생각해보셨다니 저도 좋네요ㅎㅎ
오늘이 방학식이지만ㅠ 우선은 코멘트 몇가지 남겨봤어요. 
다음 리뷰 요청 땐 아마 머지할 것 같아요 👍

2024-04-05 03:07 UTC, seovalue commented on src/main/java/chess/ChessApplication.java
> +            connectionManager.closeConnection();
오홍! 아예 finally 구문으로 닫아주셨군요! 👍 

Connection을 갖는 것은 저는 DAO가 더 잘 알고 있어야 한다고 생각이 들긴 하는데요, 다른 방법으로는 쿼리를 호출하는 시점에 커넥션을 생성하고, try-with-resources를 활용해서 커넥션을 닫아줘도 좋을 것 같아요! 보통은 커넥션 당 트랜잭션 하나를 관리하곤 하거든요.

2024-04-05 03:07 UTC, seovalue commented on src/main/java/chess/ChessApplication.java
> +    private static ChessService createChessService(ConnectionManager connectionManager) {
이 부분은 ChessService의 생성자 안에서 하지 않는 이유가 궁금해요!

2024-04-05 03:07 UTC, seovalue commented on src/main/java/chess/domain/GameStatus.java
> +        return ProgressStatus.WHITE_WIN;
질문! 그냥 WIN이 아니라 팀별 WIN이라는 상태로 분리해주신 이유가 궁금해요!
만약 팀이 100개가 된다면..?

2024-04-05 03:07 UTC, seovalue commented on database/init.sql
> +CREATE TABLE pieces (
그리고 이건 나중을 위해서 말씀드리고 싶어서요!

저는 개인적으로 도메인 로직과 무관한 PK를 만드는 것을 선호해요. auto_increment id가 그 예시인데요.
도메인 요구사항을 변경될 가능성이 매우 높아요. 예를 들어, 주민번호는 한국인을 고유하게 식별할 수 있는 값이니 주민번호를 PK로 설정했지만, 주민번호의 DB 저장은 불법이라 아예 다시 마이그레이션해야하는 상황 등이 있어요. (실제로!)

2024-04-05 03:07 UTC, seovalue commented on src/main/java/chess/ChessService.java
> +    public void inititalizeBoard() {
오타발견!
```suggestion
    public void  initializeBoard() {
```

2024-04-05 03:07 UTC, seovalue commented on src/main/java/chess/ChessService.java
> +    private List<PieceEntity> findEntities() {
이런 부분도 findPieceEntities로 명시되면 좋을 것 같아요!

2024-04-05 03:07 UTC, seovalue commented on src/main/java/chess/ChessService.java
> +    private Map<Team, Double> toDto(Map<Team, Point> status) {
이런 부분도요! 개인적으로는 그냥 Dto로 바꿔주는 컨버터가 분리되는 것도 괜찮아 보이네요. ChessService내부에 toSomething()이 많은 것 같아서요!

2024-04-05 03:07 UTC, seovalue commented on src/main/java/chess/dao/ConnectionManager.java
> +    private static final String PASSWORD = "root";
이런 부분은 yaml이나 properties로 관리할 수도 있어요!

2024-04-05 03:07 UTC, seovalue commented on src/main/java/chess/dao/MysqlChessGameRepository.java
> +        return countRow() >= 1;
count 쿼리를 해 온 뒤 >=1은 애플리케이션에서 해주시는 이유가 궁금해요!

2024-04-05 03:07 UTC, seovalue commented on src/main/java/chess/dao/MysqlChessGameRepository.java
> +        save(turn);
update로 묶는거 좋네요 👍

2024-04-05 03:07 UTC, seovalue commented on src/main/java/chess/domain/GameStatus.java
> +        currentTurn = currentTurn.nextTurn();
👍

2024-04-05 03:07 UTC, seovalue commented on src/main/java/chess/domain/Board.java
> +    }
이런 부분 Point 객체가 존재하는 김에 Point 내부로 숨겨봐도 좋을 것 같다는 생각이 들어요!

2024-04-05 03:07 UTC, seovalue commented on src/main/java/chess/dto/TurnType.java
> +public enum TurnType {
Team과 Turn을 구분주신 이유가 궁금해요!

2024-04-07 04:08 UTC, leegwichan reviewed
안녕하세요 조앤! 커찬입니다.
우선 리팩토링한 결과물을 꼼꼼히 보시고 피드백 주셔서 감사드립니다.
그래서 주말동안 주신 피드백을 곰곰히 생각해보고 반영해 보았습니다.
반영한 점은 어떤 점이 공감이 갔었고, 반영하지 않은 것은 어떠한 점이 염려되었는지 하나씩 코멘트를 달았습니다. 읽으시고 궁금한 점이나 이해되지 않는 점이 있으시다면 추가 코멘트 부탁드리겠습니다!

### 궁금한 점

처음에는 "이 정도는 괜찮겠지?"라고 생각하면서 코드를 짜는데, 점점 완성되어 갈수록 "어 언제 지저분해졌지?"라는 생각이 드네요. 이런 것들은 경험을 쌓아가면서 '리팩터링을 할 때'를 정하는 자신만의 기준을 만들면 되는 걸까요?

2024-04-07 04:08 UTC, leegwichan commented on src/main/java/chess/dto/TurnType.java
> +public enum TurnType {
데이터베이스에 저장할 때 사용하는 enum을 고려했습니다.

`TeamType`은 각 Piece가 저장 될 때 어떤 팀인지 구분하기 위해 사용했습니다. 데이터베이스는 내부 저장되는 상태에 따라서 insert와 update를 나누어 사용하기 때문에, null 객체를 도입했습니다. null 객체의 TeamType으로 `EMPTY`를 사용했습니다. 
이와 달리 `TurnType`은 현재 차례를 알려주기 위해 사용합니다. `EMPTY`와 같은 값이 필요 없습니다. 그래서 이를 따로 타입을 구분하여, 일부 부분의 내용이 중복되지만, 관리하기 용이하도록 했습니다.

만약 auto_increment PK를 도입했다면 DB에 null 객체를 도입하지 않고, 하나의 Enum으로 관리했을 수 있었을 것 같네요!

2024-04-07 04:08 UTC, leegwichan commented on src/main/java/chess/ChessApplication.java
> +    private static ChessService createChessService(ConnectionManager connectionManager) {
저는 지금 상황에서 `ChessApplication`은 각 객체 간의 런타임 의존 관계를 정해주는 역할을 한다고 생각했습니다. 그래서 최대한 의존 관계를 `ChessApplication`에서 정의 해주었습니다.

만약 이 부분을 "`ChessService`의 생성자"에서 하게 된다면, 설정 정보를 바꾸고 싶을 때 `ChessService`로 들어가지 않을 것 같았습니다. 그래서 `ChessApplication`에 두는 것을 유지 했습니다.

`ChessService`의 생성자에서 만들어 주어도 된다는 조앤의 말도 굉장히 합리적이라는 생각이 듭니다. 조앤은 "어디까지 의존성 주입을 해야 되는지?"에 대한 따로 기준이 있을까요?

2024-04-07 04:08 UTC, leegwichan commented on src/main/java/chess/ChessApplication.java
> +            connectionManager.closeConnection();
`Connection`이라는 객체가 확실히 무겁다고 알고 있다 보니, 현 상황에서는 하나로만 관리해도 된다고 생각했습니다. 생각만 하던 것을 적용해보니, 생각했던 것 만큼 좋은 설계가 나오기 힘드네요;;

"Connection을 갖는 것은 저는 DAO가 더 잘 알고 있어야 한다"라는 조앤의 의견에 공감이 가서 쿼리를 호출하는 시점에 커넥션을 생성하고 try-with-resources를 활용해서 커넥션을 닫도록 했습니다!

2024-04-07 04:08 UTC, leegwichan commented on src/main/java/chess/dao/ConnectionManager.java
> +    private static final String PASSWORD = "root";
확실히 설정 파일을 분리하는 편이 더 자연스러울 것 같습니다!

그래서 `mysql.properties`로 해당 부분을 분리해보았습니다!

2024-04-07 04:08 UTC, leegwichan commented on src/main/java/chess/dao/MysqlChessGameRepository.java
> +        return countRow() >= 1;
1개라도 있다면 게임이 있어야 하기 때문에 이런 방식으로 구현했습니다.

다시 생각해보면 `ChessGameRepository`의 책임은 조회한 값을 정제해서 넘겨주는 것이었는데, 해당 부분이 잘 안 지켜진 것으로 보여집니다. 그리고 count 쿼리를 사용하지 않고, `SELECT EXISTS (SELECT 1 FROM chess_game)`을 이용하면 손쉽게 "해당 테이블이 빈 테이블인지" 알 수 있었습니다.

그래서 sql을 조금 변경하여 조회하도록 했습니다!

2024-04-07 04:08 UTC, leegwichan commented on src/main/java/chess/ChessService.java
> +    private Map<Team, Double> toDto(Map<Team, Point> status) {
이전 미션들에서 DTO를 사용했을 때 클래스들이 많이 늘어나서, 이번에 최대한 DTO 객체를 도입하지 않겠다고 생각했습니다. 이러한 과정에서 toDto()와 같은 매핑 로직이 많아지면서, 읽을 때 중요한 부분과 부수적인 부분을 구분하는데 비용이 든다는 것을 알게 되었습니다.

그래서 toSomething()등이 필요한 부분에는 일급 컬렉션을 도입했습니다.
이렇게 바꾸어 보니, ChessService에서는 기능 관련 로직들만 남아, 가독성이 증가하는 것을 느낄 수 있었습니다.

2024-04-07 04:08 UTC, leegwichan commented on src/main/java/chess/domain/Board.java
> +    }
초기 `Point`의 의도는 '점수 더하는 방식을 관리하는 작은 객체'였습니다. double끼리 더하는 과정이 여러번 누적되면 문제가 발생할 수 있다고 생각했기 때문입니다.

점수 객체가 따로 있으니 전반적인 계산과정을 Point 내부로 숨기는 것도 합리적이라고 생각합니다. 하지만 직접 해보게 되면, 
- `Point`에 `Board`를 넘기게 되면 순환 참조 문제가 발생할 수 있습니다.
- `Point`에 `Map<Position, Piece>`를 넘기게 되면 `Point`에서 너무 많은 객체들을 알아야 하게 되서 좋지 않아 보였습니다.

이를 해결하는 전반적인 해결책으로 '전반적인 `TotalPoint`라는 객체를 생각해 보았습니다. 그렇게 하기에는 "기물 별로 점수를 더하는 것도 Board의 책임 아닌가?", "괜히 복잡성만 늘리는게 아닐까?"라는 생각이 들었습니다.

그래서 이 역할을 다른 객체로 넘기지 않고, Board에서 처리하도록 했습니다.

2024-04-07 04:08 UTC, leegwichan commented on src/main/java/chess/domain/GameStatus.java
> +        return ProgressStatus.WHITE_WIN;
`ProgressStatus`의 역할은 사용자가 입력한 커멘드에 따라 해당 기능을 진행하고 나서 다음에 무엇을 해야하는지를 나타내기 위함입니다. 흰 팀이 이겼을 때와 검정 팀이 이겼을 때를 구분하기 위해서 팀별 WIN 상태를 분리했습니다.

물론 그냥 WIN을 사용하고, WIN일 경우 다시 우승자를 물어보도록 할 수 있었습니다. 하지만 특정 상태일 때만 조회 가능한 메서드를 최대한 줄이고 싶었고, 지금 팀이 2개 밖에 없다보니 간단하게 처리할 수 있다고 생각했습니다. 만약 팀이 늘어난다면, 그 때에 맞추어 `ProgressStatus`를 수정하는게 좋겠다고 생각했습니다.

그래도 최대한 확장을 염려해야 한다는 점에서 조앤이 주신 피드백을 일부 반영하여 수정했습니다. ProgressStatus에서 `winGame(Team team)`이라는 static 메서드를 만들어, Team의 개수가 늘어나도 `ProgressStatus`만 구조를 변경하면 되도록 했습니다!

2024-04-07 05:13 UTC, seovalue commented on src/main/java/chess/dto/TurnType.java
> +public enum TurnType {
그럼 같은 개념이 db용과 도메인용으로 구분된 것 같아요. 제 생각에 나중에는 디비에 저장되는 용도의 엔티티와, 비즈니스 로직에서 사용되는 도메인을 같은 네이밍에 postfix만 다르게 해서 관리해보시는게 어떨까해요!

2024-04-07 05:14 UTC, seovalue commented on src/main/java/chess/ChessApplication.java
> +    private static ChessService createChessService(ConnectionManager connectionManager) {
ChessService가 생성될 때 필수적으로 호출되어야한다면 ChessService의 생성자 안에서 하는게 맞겠죠ㅎㅎ

2024-04-07 05:15 UTC, seovalue commented on src/main/java/chess/ChessService.java
> +    private Map<Team, Double> toDto(Map<Team, Point> status) {
너무 좋네요!

2024-04-07 05:15 UTC, seovalue commented on src/main/java/chess/domain/Board.java
> +    }
그럼 포인트는 단순 값 객체가 되는걸까요?!

2024-04-07 05:43 UTC, seovalue commented
네네 구현하다보면, 어느 순간 더 복잡해진 느낌이 들 때가 있을 거예요. 그때를 기점으로 현 구현을 한번 정리하고 보통 리팩터링&쿨다운 기간으로 가져가는 것 같아요ㅎㅎ

2024-04-07 05:44 UTC, seovalue approved these changes
안녕하세요, 커찬! 주말에도 작업을 해주셨군요ㅠㅠ 이제 잘 정리된 것 같아 말씀드린대로 머지할게요! 새로운 코멘트보다는 남겨주신 답변에 대해 저도 코멘트 남겨뒀어요ㅎㅎ 고생 많으셨어요! 혹시라도 질문 있으시면 남겨주세요~! 방학 푹 쉬시고 남은 기간도 화이팅이에요!

2024-04-07 05:44 UTC, merged