[3, 4 단계 - 체스] 테드(김규태) 미션 제출합니다.
woowacourse/java-chess pull request #814
Opened 2024-04-01 08:57 UTC by Kimprodp

안녕하세요, 알렉스.

지난 단계에서 병합하고 PR을 올리는 과정에서 절반정도의 커밋이 누락되어서 오류가 발생했습니다.
확인하지 못하고 PR 올린 점 죄송합니다.

이번 단계에서 누락된 항목을 모두 추가하고, 완성하지 못했던 부분을 진행하며 리팩터링도 같이 진행하였습니다.

DB추가하는 부분에서는 DB를 적용시키는 것이 처음이라 시간도 많이 걸리고 어려웠던 것 같습니다. 

리뷰 부탁드립니다!

2024-04-02 06:51 UTC, yxxnghwan requested changes
안녕하세요 테드! 생각해볼만한 코멘트 남겼습니다!
확인 부탁드려요! :)

2024-04-02 06:51 UTC, yxxnghwan commented on docker/db/mysql/data/#ib_16384_0.dblwr
gitignore 파일에 `docker/db/mysql/data` 경로 추가 부탁드려요!

2024-04-02 06:51 UTC, yxxnghwan commented on src/test/java/chess/domain/piece/PieceTest.java
> +
도메인 로직인데 실제 DB에 연결해서 테스트하고 있네요! DB에 의존적이지 않게 테스트할 수 있는 방법은 없을까요?

2024-04-02 06:51 UTC, yxxnghwan commented on src/main/java/chess/dao/ChessGameDao.java
> +            ResultSet resultSet = statement.executeQuery(query);
ResultSet도 닫아줘야하는 대상인데 try문에 포함되거나 해야할 것 같아요!

2024-04-02 06:51 UTC, yxxnghwan commented on src/main/java/chess/dao/ChessGameDao.java
> +public class ChessGameDao {
Dao 클래스들의 메소드들에 공통된 로직이 많네요!

1. 커넥션 맺기
2. PrepareStatement 세팅
3. 쿼리실행 or 쿼리실행하고 결과 매핑

이러한 중복 로직은 어떻게 줄여볼 수 있을까요? 🤔

2024-04-02 06:51 UTC, yxxnghwan commented on docker/docker-compose.yml
> +#      - ./db/mysql/config:/etc/mysql/conf.d
주석처리된 이유가 있을까요?

2024-04-02 06:51 UTC, yxxnghwan commented on src/main/java/chess/domain/position/Lettering.java
> +
다음 enum이 추가될 때를 생각해서 다음과 같이 쓰기도 한답니다 :)
```suggestion
    G,
    H,
    ;
```

2024-04-02 06:51 UTC, yxxnghwan commented on src/main/java/chess/domain/position/Lettering.java
> +    }
전체적으로 static메소드가 너무 많은데 이유가 있을까요? 인스턴스 메소드여도 충분할 것 같고 그게 더 객체지향적일 것 같네요

2024-04-02 06:51 UTC, yxxnghwan commented on src/main/java/chess/service/GameSaveManager.java
> +    private int inProgressGameID;
만약 한번에 여러 게임이 진행되는 멀티스레드 환경이라면 정상적으로 동작하지 않을 것 같네요..!

2024-04-02 06:51 UTC, yxxnghwan commented on src/main/java/chess/entity/ChessGameEntity.java
> +    }
자바 컨벤션상 카멜 케이스가 맞을 것 같네요!

2024-04-02 06:51 UTC, yxxnghwan commented on src/main/java/chess/domain/piece/Piece.java
> +    }
도메인이 dto를 알 필요가 있을까요?

2024-04-02 06:51 UTC, yxxnghwan commented on src/main/java/chess/domain/piece/PieceType.java
> +    private final Supplier<MoveStrategy> moveStrategySupplier;
Supplier일 필요가 있나요?

2024-04-04 03:29 UTC, Kimprodp commented on src/test/java/chess/domain/piece/PieceTest.java
> +
도메인 로직이 DB에 의존적이지 않도록 변경했습니다!

2024-04-04 03:30 UTC, Kimprodp commented on src/main/java/chess/dao/ChessGameDao.java
> +            ResultSet resultSet = statement.executeQuery(query);
ResultSet도 닫아줘야 하는 대상인지 몰랐네요.. 사용 후 닫을 수 있도록 변경했습니다!

2024-04-04 03:34 UTC, Kimprodp commented on src/main/java/chess/dao/ChessGameDao.java
> +public class ChessGameDao {
공통적으로 사용되는 부분에 대해 DaoTemplate 클래스를 통해 리팩터링 해봤습니다!

2024-04-04 03:35 UTC, Kimprodp commented on docker/docker-compose.yml
> +#      - ./db/mysql/config:/etc/mysql/conf.d
삭제한다는 것을 놓쳤네요.😢

2024-04-04 03:36 UTC, Kimprodp commented on src/main/java/chess/domain/position/Lettering.java
> +    }
인스턴스 메서드로 변경해도 기능에 문제가 없을 것 같은데 굳이 static 메서드를 사용한 감이 있네요.. 모두 변경했습니다!

2024-04-04 03:36 UTC, Kimprodp commented on src/main/java/chess/service/GameSaveManager.java
> +    private int inProgressGameID;
controller와 service 모두 멀티 스레드 환경에서도 동작할 수 있도록 고유 필드를 제거했습니다!

2024-04-04 03:37 UTC, Kimprodp commented on src/main/java/chess/entity/ChessGameEntity.java
> +    }
DB랑 같이 하다보니 실수가 있었네요. 수정했습니다!

2024-04-04 03:39 UTC, Kimprodp commented on src/main/java/chess/domain/piece/Piece.java
> +    }
dto의 데이터가 도메인의 데이터이니 도메인에서 생성해줘도 되겠다고 생각했었는데요, 아무래도 데이터 전송만을 위한 객체는 도메인에서 몰라도 될 것 같아 분리했습니다!

2024-04-04 03:40 UTC, Kimprodp commented on src/main/java/chess/domain/piece/PieceType.java
> +    private final Supplier<MoveStrategy> moveStrategySupplier;
이 부분은 제가 너무 어렵게 생각했나봐요. Supplier를 쓰지 않고서는 안될줄 알고 미리 고민해놓고 사용했는데, 그냥 사용해도 되는군요..........ㅎ

2024-04-04 14:57 UTC, yxxnghwan approved these changes
안녕하세요 테드! 레벨1 고생 많으셨습니다. 코멘트 반영해주신 것 확인했고 이번 단계에서 고민할만한 부분은 반영된 것 같아서 이만 머지하겠습니다! 다음 단계도 화이팅이에요! 💪

2024-04-04 14:57 UTC, merged